### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by zeeshan1981** [ContinuumIO/anaconda-issues#1000]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - spyder ==2.3.9
  - spyder-app ==2.3.8 -> spyder 2.3.8
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.8', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Please do

`conda update anaconda-navigator`

and

`conda update anaconda`
