### ISSUE TITLE
Missing vc=14.1 and vs2015_runtime>=15.5 packages

### ISSUE THREAD

**Issue by mparry** [ContinuumIO/anaconda-issues#10004]
The `vc=14.1` and corresponding `vs2015_runtime>=15.5` packages seem to have disappeared from the `main` channel. Briefly, in the last couple of days, they were still present but in a 'revoked' state that rendered them uninstallable, and now they are gone altogether. 

We have some internal packages that were dependent upon these. I was previously advised [here](https://github.com/ContinuumIO/anaconda-issues/issues/7883#issuecomment-365281961) that depending upon `vc=14.1` was the right thing to do, and we had followed that guidance.

Please could you advise as to the correct way this should be setup now?

(Apologies if I've missed an existing issue about this, but I couldn't find anything.)

**Comment by msarahan** [comment]
Sorry, we did not handle that very well. We are in the process of starting to use vs2017 ourselves. In updating our recipe, I noticed that several versions of ours were illogical. They had been based on the visual studio UI version.

We have new packages, where the compiler packages match the version of cl.exe, and the runtimes match the version of the vcruntume140.dll that they contain. We will make these packages available shortly. I believe that if your packages depend only on vc, not directly on vs2015_runtime, then you'll be fixed when the new packages are available.

We knew that we didn't have any packages that used vs2017, but we neglected to consider external usage. Our apologies.

**Comment by kalefranz** [comment]
FYI I created the `enable_revoked` channel last night while debugging and fixing https://github.com/conda/conda/issues/7714

**Comment by mparry** [comment]
Thanks for the information. If you could close this ticket with a note when the new packages are available, that would be really helpful.

**Comment by mparry** [comment]
This seems to be fine with newer versions of the `vc` package
