### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Pravirk22** [ContinuumIO/anaconda-issues#10008]
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Dependencies missing in current win-64 channels: 
  - rstudio ==1.1.456 -> fonts-anaconda
  - rstudio ==1.1.456 -> freetype >=2.9.1

Close matches found; did you mean one of these?

    fonts-anaconda: anaconda

(and similarly for the other packages)
```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by csoja** [comment]
Your default channels are likely out of date because you are using a very old version of conda. Please update to the latest conda and anaconda-navigator.
fonts-anaconda and freetype are found in the https://repo.anaconda.com/pkgs/main/noarch/ channel.
