### ISSUE TITLE
Please build scikit-learn 0.20rc1 to check for issues

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#10005]
Hey folks.
Can you please build scikit-learn 0.20rc1:
https://github.com/scikit-learn/scikit-learn/releases/tag/0.20rc1

We'll hope to do the release in about two weeks and it would be great if you could tell us if there's any issues in the meantime!

Thanks,
Andy

**Comment by msarahan** [comment]
Thanks for the heads up. We don't generally release rc's on the defaults channel, but we'll try to at least build it and run some smoke tests. Probably not much more than your test suite though, I'm afraid.

**Comment by amueller** [comment]
Yeah didn't expect you to release it, just running a smoke test would be
cool. Thanks!

**Comment by mingwandroid** [comment]
Can't you do this yourself?

**Comment by msarahan** [comment]
They can't run it through our build process. We obviously can't do this for every package, but for a critical one like scikit learn, I think it's reasonable. Maybe we'll avoid needing to patch it somehow.

**Comment by amueller** [comment]
Did you patch it in the past? It would be good if we knew how/why you did.

**Comment by msarahan** [comment]
We have applied some minor patches in the past around tests:

https://github.com/AnacondaRecipes/scikit-learn-feedstock/tree/master/recipe

I built these packages, and other than needing to adapt the recipe to switch to pytest, everything worked fine.

**Comment by msarahan** [comment]
Right, we haven't added any patches.  I didn't try removing these this time around.  If you think we should, I'm happy to try.

**Comment by amueller** [comment]
The cython fix shouldn't apply any more and is unnecessary. I'd be slightly surprised if the other patches apply seamlessly, but that's what you did, right?
I actually don't understand how you were able to apply the cython fix.

**Comment by msarahan** [comment]
That patch is cruft.  It's not applied - it's not in meta.yaml.  It should be removed from the recipe here.

**Comment by amueller** [comment]
Thanks!
