### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by zeeshan1981** [ContinuumIO/anaconda-issues#1001]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - setuptools ==25.1.6
  - spyder-app -> python 2.7*|3.4*
  - spyder-app -> spyder 2.2.0|2.2.4|2.2.5|2.3.0|2.3.0rc1|2.3.1|2.3.2|2.3.3|2.3.4|2.3.5.2|2.3.6|2.3.7|2.3.8
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.8', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
