### ISSUE TITLE
Please update mpi4py!

### ISSUE THREAD

**Issue by gapplef** [ContinuumIO/anaconda-issues#10018]
The mpi4py 3.0 has released almost one year,  but the mpi4py in Anaconda is still 2.0. Please update!!

**Comment by rainwoodman** [comment]
Please also be aware there is also no python 3.7 build of mpi4py.

Does anaconda still intend to provide mpi4py as part of the default channel? As people switch to Python 3.7 they will probably be forced to look else where for mpi4py. This may cause a cascade of problems ...

**Comment by jjhelmus** [comment]
mpi4py 3.0.3 packages are now available for linux-64, linux-ppc64le, and osx-64.
