### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by akardec53** [ContinuumIO/anaconda-issues#1002]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - cx_oracle ==5.1.2
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'language': 'pt_BR', 'platform': 'win-64', 'python': '3.5.1', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'version': '1.2.1', 'qt': '4.8.7', 'conda': '4.1.11'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
