### ISSUE TITLE
pip install breaks conda.cli dependency

### ISSUE THREAD

**Issue by Tagar** [ContinuumIO/anaconda-issues#10029]
`conda` became broken after I installed a package with pip into that a conda envrionment.

```
$ conda create -n py27_rd python==2.7.13
$ source activate py27_rd 
$ pip install featuretools

(py27_rd) $ conda
Traceback (most recent call last):
  File "/opt/conda/envs/py27_rd/bin/conda", line 4, in <module>
    import conda.cli
ImportError: No module named conda.cli
```
Any ideas how to fix this? 

One of our data scientists asked to install featuretools pip package ( I didn’t find it in conda).

**Comment by scw** [comment]
The `featuretools` doc notes that they provide it via conda on their own channel:

```conda install -c featuretools featuretools```

That should work. I also can't reproduce your error, but if you look you'll see that its referencing the conda bin within the environment, which typically is just a shell wrapper around the real script. Perhaps the hash-bang at the beginning of the script isn't set correctly?

**Comment by Tagar** [comment]
thanks for looking at this @scw .. it was something else.. my bad.
