### ISSUE TITLE
please add featuretools pip package as a conda package

### ISSUE THREAD

**Issue by Tagar** [ContinuumIO/anaconda-issues#10030]
Please add featuretools pip package as a conda package.

see https://github.com/ContinuumIO/anaconda-issues/issues/10029 

Thanks.

**Comment by msarahan** [comment]
Sorry, we can't take on arbitrary package requests.  If you'd like to explore support contracts, please contact sales@anaconda.com.  You may also want to try to package it yourself using conda-build https://conda.io/docs/user-guide/tasks/build-packages/index.html, and perhaps building it on conda-forge, https://conda-forge.org/

**Comment by Tagar** [comment]
Thank you @msarahan 

Publishing `feature-tools` into conda-forge makes sense as it's a very popular python package.

https://github.com/Featuretools/featuretools/ 

ps. We're considering getting Anaconda Enterprise, but it'll be determined a bit later.

**Comment by Seth-Rothschild** [comment]
Following up on the comment by @msarahan, Featuretools is already built with conda-build and you can install it  from the [Featuretools](https://anaconda.org/Featuretools/featuretools) channel on anaconda.org with `conda install -c featuretools featuretools`. If you have more questions we can continue discussion on your github issue on our repo.
