### ISSUE TITLE
R kernel keeps dying in Jupyter notebook 

### ISSUE THREAD

**Issue by ragaVishnu** [ContinuumIO/anaconda-issues#10044]
### Actual Behavior
Kernel keeps dying and restarting.

R kernel keeps dying in Jupyter notebook every time I open a new kernel. No problem with the python kernel though.
### Expected Behavior
Proper functioning of the kernel

Proper functioning of the kernel
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by mingwandroid** [comment]
Closing. Please try to fill out all requested information when you open bug reports.
