### ISSUE TITLE
Impossible to launch Jupiter Notebook with Anaconda Navigator

### ISSUE THREAD

**Issue by lullaby61** [ContinuumIO/anaconda-issues#10061]
Hi everyone,

When I launch the Jupiter Notebook from Anaconda Navigator, it is written "login: -anaconda-5.2.0-py36_3: Permission denied [Opération terminée]" on the terminal. I tried to reinstall several times the application but this issue is still existing. Can you help me please?

Many thanks,
Léa

**Comment by goanpeca** [comment]
@lullaby61 please provide the information requested on the issue template 



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by lullaby61** [comment]
@goanpeca I am really sorry for not giving a good template. However, I am a very beginner student and do not know what Conda list is etc... I am working on a Mac Computer, and the version of Anaconda Communicator is 5.2 (Python 3.6). 

When I click on Jupiter Notebook from the Anaconda Communicator, it doesn't open the browser and only opens the terminal, in which it is written "login: -anaconda-5.2.0-py36_3: Permission denied [Opération terminée]". I cannot write anything on the terminal. 

I would expect the Jupiter Notebook to open the browser when I click on it from the Anaconda Communicator and to be able to write some code on the terminal.

Many thanks for your help and comprehension,
Léa
