### ISSUE TITLE
Unable to start Anaconda-navigator:"get_server_api() got an unexpected keyword argument 'config'"

### ISSUE THREAD

**Issue by SB2512** [ContinuumIO/anaconda-issues#10070]
### Actual Behavior

![image](https://user-images.githubusercontent.com/16515301/45592516-ab20d780-b93d-11e8-93c5-deb1f19a79f7.png)

### Expected Behavior
Start up anaconda-navigator

### Steps to Reproduce

anaconda-navigator --version
1.8.4

running command 
anaconda-navaigator

##### Operating System:
Windows10
64-bit Operating System,x64-based processor
##### `conda info`

![image](https://user-images.githubusercontent.com/16515301/45592590-e7553780-b93f-11e8-97ef-f2b40b381dd2.png)

##### `conda list --show-channel-urls`

![image](https://user-images.githubusercontent.com/16515301/45592629-b32e4680-b940-11e8-8d96-720dbac3055c.png)

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

**Comment by echocolatos** [comment]
can you explain step by step sir?? i'm newbie

**Comment by echocolatos** [comment]
will it works as usual??
