### ISSUE TITLE
Anaconda distribution installation: confusing things for Windows users

### ISSUE THREAD

**Issue by ceball** [ContinuumIO/anaconda-issues#10087]
I'm reporting a couple of things that I've seen confuse people on windows (since at least a few years ago). If my report is out of date, or I missed existing issues, sorry about that! Or if there's something more specific I could add to this report that would help, please let me know.

### Actual Behavior

1. User installs Anaconda on Windows. User wants to uninstall Anaconda from Windows. User cannot find Anaconda in list of programs to uninstall. (The entry is maybe under 'python' or something like that?)

2. User installs multiple copies of Anaconda on Windows (e.g. Anaconda2 and Anaconda3). After multiple installations, the user's start menu contains only one Anaconda entry, and you can't easily tell which it's for. (Combined with 1, this can make things pretty confusing for people...)

3. Installer asks confusing questions about path and registering.

### Expected Behavior

1. Uninstall entry is called Anaconda (i.e. uninstall name same as install name).

2. I'm not sure :) Multiple start menu entries with some disambiguation? Prevent multiple installations (making subsequent installations be upgrade operations seems common on windows - not sure)?

3. I've seen these questions cause confusion and uncertainty about whether or not to proceed. What about hiding them behind some kind of collapsed 'advanced options' box, so that most users do not have to make a choice, but people who need to do something different are free to do it? This is only a suggestion, I'm not saying I know best :) I'm just reporting something that I have seen trip people up.

##### Anaconda or Miniconda version:

I'm not sure, but I think I've seen these things with anaconda versions 1 through 5, plus miniconda.

##### Operating System:

Windows 7 (and maybe 10 too, though I don't remember exactly).

**Comment by sheetalkalburgi** [comment]
Thank you for your feedback, we are doing are best to constantly improve! :)
