### ISSUE TITLE
In Anaconda3-4.0 symlink `python-config` is missing

### ISSUE THREAD

**Issue by dmitry-kabanov** [ContinuumIO/anaconda-issues#1009]
I have `Anaconda3-4.0` installed on my machine.

When I look into the `bin` directory, I see that there symlinks `python3-config` and `python3.5-config` linked to the `python3.5m-config`. However, `python-config` symlink is missing.

**Comment by juharris** [comment]
Any plans to add this?

**Comment by ilanschnell** [comment]
We don't do anything special with respect to the python-config scripts.  Basically we run `./configure`, `make`, `make install`.  So the Python source doesn't add `python-config` for Python 3.5.  Is the "missing" sym-link creating any problems?

**Comment by juharris** [comment]
On Ubuntu the system's `python-config` was being used which caused confusion. It was particularly confusing because the system's default was Python 2 even though my Conda installation defaulted to Python 3.

**Comment by ilanschnell** [comment]
When your not sure which command is used, you can always type `which python-config`.

**Comment by juharris** [comment]
Yep that's how I figured out the issue. The problem is that it's not obvious to everyone that Anaconda doesn't come with `python-config`.

**Comment by dmitry-kabanov** [comment]
I cannot recall right now how exactly the issue of missing `python-config` in Anaconda occurred because it was a long time ago. However, it undoubtedly caused some pain if I went to the Github and raised and an issue :-) I think I was compiling `scikits.odes` when the issue occurred.

So, due to the absent `python-config` in the Anaconda itself, the Ubuntu's `python-config` was called, which is for Python 2 (I was using Ubuntu 14.04 at the time).

I think this issue should be reopened.

**Comment by alexbw** [comment]
Just ran into this bug, with a separate package which requires the use of `python-config` to get some build flags.

**Comment by flipphillips** [comment]
Same - in my case I was building libsharp and it was using the Homebrew python's python-config.

**Comment by vsbogd** [comment]
I faced this issue when trying to build C++ library Python bindings using `pybind11` module installed in conda environment. `pybind11` CMake macro use `python-config` to get C++ module suffix. As `conda` doesn't contain `python-conifg` symlink `pybind11` uses mixed environment: conda `python` interpreter  and system `python-config`. As result conda python interpreter doesn't see built module.

**Comment by ktbarrett** [comment]
I have also faced the same issue building Kactus2, which uses python-config to determine the include paths to pull in Python.h. @ilanschnell Can you justify why you are not providing python-config? This is a command used by many build scripts for extension modules to query the Python build for its configuration. This is not an optional component unless you want to suggest an alternative for all these use cases and push that change onto everyone else...

**Comment by ktbarrett** [comment]
Please reopen this issue.
