### ISSUE TITLE
How can I install krls package of R using anaconda? It is not possible to install this package using "conda install -c r r-<packagename>"

### ISSUE THREAD

**Issue by saminpayro** [ContinuumIO/anaconda-issues#10095]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by mingwandroid** [comment]
You need to build it first using conda build, before that you need to make a recipe with conda skeleton cran

**Comment by saminpayro** [comment]
@mingwandroid Thanks, could you please be more specific? I did as you mentioned, but I faced some issues. Could write me the required commands please?

**Comment by mingwandroid** [comment]
It's difficult to provide support when people do not fill in the requested information in the template, but at its simplest this should work (tested on macOS):

```
conda activate base
conda install conda-build
conda skeleton krls
cd r-krls
conda-build .
conda install -c local r-krls
```

**Comment by saminpayro** [comment]
Thanks it's working.

**Comment by mingwandroid** [comment]
Great, thanks for the feedback.
