### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Egkachai** [ContinuumIO/anaconda-issues#1010]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - protobuf ==2.6.1
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.2', 'qt': '4.8.7', 'pyqt': '4.11.4', 'platform': 'osx-64', 'version': '1.2.1', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'conda': '4.1.11'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
