### ISSUE TITLE
Some vs2017 packages don't exist

### ISSUE THREAD

**Issue by Bezier89** [ContinuumIO/anaconda-issues#10106]
Visit https://repo.anaconda.com/pkgs/main/win-32 or https://repo.anaconda.com/pkgs/main/win-64 (the issue currently applies to both channels). Search (Ctrl+F) for one of these packages and click on the link to attempt to download:
- vs2017_win-32-19.15.26726-h590f102_0.tar.bz2
- vs2017_win-64-19.15.26726-hb4ce483_0.tar.bz2

### Expected result

Package begins to download

### Actual result

An error such as this:

> 404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: pkgs/main/win-64/vs2017_win-32-19.15.26726-h590f102_0.tar.bz2
RequestId: E5B240521C5515FE
HostId: 9/TgP1s29a2w+gGH0DpQytGAIQZlxGSliccHi+eHRyWCojzbAx9V2lm4GmS+InsPHvkqN134VbY=

**Comment by msarahan** [comment]
Thanks, we're looking into why these files seemingly did not get uploaded by the sync process.

**Comment by msarahan** [comment]
These packages were moved to archive, but our new indexer is still keeping them in the repodata.  We'll fix this bug in conda-build, and have applied a fix to the repodata.json in the meantime so that these moved files no longer appear.  The current vs2017 packages are present.
