### ISSUE TITLE
Cannot create an environment with caffe 1.0 and tensorflow 1.10.0 at the same time

### ISSUE THREAD

**Issue by 183amir** [ContinuumIO/anaconda-issues#10104]
Probably similar to https://github.com/ContinuumIO/anaconda-issues/issues/9144
```
conda create -n test caffe==1.0 tensorflow=1.10              
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - caffe==1.0
  - tensorflow=1.10
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jjhelmus** [comment]
New packages of `caffe` and `caffe-gpu` were added to the repository (build 4) which use a static libprotobuf library.  These are compatible with `tensorflow` and `tensorflow-gpu` version 1.10.0.
