### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by fionaeni** [ContinuumIO/anaconda-issues#1011]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - ndg-httpsclient ==0.3.3
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.11', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 63 Stepping 2, GenuineIntel', 'version': '1.2.1', 'language': 'en_US', 'platform': 'win-64', 'python': '3.5.2', 'qt': '4.8.7', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
