### ISSUE TITLE
Glib too old warnings

### ISSUE THREAD

**Issue by Zaharid** [ContinuumIO/anaconda-issues#1012]
With the latest build number of Qt, which now depends on glib, I get lots of warnings  when running e.g. matplotlib:

```
(python:6604): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(python:6604): Gtk-WARNING **: Loading IM context type 'ibus' failed

(python:6604): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(python:6604): Gtk-WARNING **: Loading IM context type 'ibus' failed

(python:6604): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
```

I can remove the warnings with `conda remove glib`, which also downgrades Qt. I have the impression this also improves the performance of a plotting tool.

I am using Linux Mint 18 with a 4.4 kernel.

**Comment by ccordoba12** [comment]
@mingwandroid, do you what packages we need to update to bump glib?

**Comment by mingwandroid** [comment]
This looks like a conflict with the system version of `glib`.

@Zaharid what desktop are you running?

**Comment by Zaharid** [comment]
I'm using Cinnamon 3.0.7

**Comment by Ben201310** [comment]
Just to add that the same warnings appear on openSUSE Leap 42.1 running gnome 3.16.0. Running "conda remove glib" also got rid of those warnings.
