### ISSUE TITLE
Anaconda linux-64/scipy-1.1.0-py36 link is broken

### ISSUE THREAD

**Issue by falaki** [ContinuumIO/anaconda-issues#10125]
Conda (miniconda) generates the wrong link when installing `scipy` (version 1.1.0, Python 3.6, Linux 64). 

Conda tries to download https://conda.anaconda.org/anaconda/linux-64/scipy-1.1.0-py36_nomklh9c1e066_0.tar.bz2

The link is broken.

### Actual Behavior

```
CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/scipy-1.1.0-py36_nomklh9c1e066_0.tar.bz2>
Elapsed: 00:00.355261
CF-RAY: 46183ef9fe132a31-SEA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

### Expected Behavior

Link should work and download the tar.bz2 file.

### Steps to Reproduce

```
$/home/conda/bin/conda install --prefix /home/python3 -c anaconda scipy==1.1.0
```

##### Operating System:
Linux 64

##### `conda info`
```
     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.5.4
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /home/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /home/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.15 Linux/4.4.0-1066-aws ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```

```

**Comment by Loquats** [comment]
This happens for me too :\

**Comment by msarahan** [comment]
repo.anaconda.com is the only authoritative source of packages. The anaconda channel on anaconda.org is a mirror (and a bad one that shouldn't be used, by the way, because it loses the distinction between the newer "main" defaults channel and the older "free" defaults channel.

This is a bug in our channel mirroring that we're working out, but you really shouldn't be using the anaconda channel.

**Comment by mjhamiltonus** [comment]
This happens to me currently for : 
<https://conda.anaconda.org/anaconda/linux-64/glib-2.53.6-h5d9569c_2.tar.bz2>
<https://conda.anaconda.org/anaconda/linux-64/scipy-1.0.0-py36hbf646e7_0.tar.bz2>
<https://conda.anaconda.org/anaconda/linux-64/pyzmq-16.0.3-py36he2533c7_0.tar.bz2>

I don't really understand why it looks to conda.anaconda.org when the channel URLs are set as above.  The old conda.anaconda.org seems to be cached in $CONDAHOME/pkgs/urls.txt.  but, I haven't found the trick to get rid of it from there and have rep;o.anaconda.com be default.

**Comment by falaki** [comment]
Switching to `https://conda.anaconda.com/anaconda/linux-64/` for channel resolved the issue. Interestingly if you use `-c anaconda` you get `anaconda.org` URLs.

**Comment by csoja** [comment]
The files reported in this issue are available again now from the anaconda channel of anaconda.org.  We believe we have resolved the root cause of these missing files - so you should no longer be running into these.  Please open a new issue if you come across any others.
