### ISSUE TITLE
PyCrypto in Anaconda3 5.2.0 x64 contains win32 binaries

### ISSUE THREAD

**Issue by akochepasov** [ContinuumIO/anaconda-issues#10145]
### Actual Behavior

Unable to run the following code in Anaconda3 5.2.0 x64
from Crypto.Cipher import AES
ImportError: cannot import name '_AES'

The Crypto directory in site-packages contains win32 native binaries.

### Expected Behavior

Should be importable, no exception, binaries should be x64

### Steps to Reproduce

from Crypto.Cipher import AES

##### Anaconda or Miniconda version:
Anaconda3 5.2.0 x64

##### Operating System:
Windows 10

**Comment by msarahan** [comment]
try updating it, or installing Anaconda 5.3.0.  We aren't going to go back and fix 5.2.0.

**Comment by akochepasov** [comment]
https://repo.anaconda.com/pkgs/main/**win-64**/pycrypto-2.6.1-py36hfa6e2cd_8.tar.bz2 **contains win32** binaries as well.

**Comment by msarahan** [comment]
what about build number 9?

**Comment by akochepasov** [comment]
> what about build number 9?

This one seems ok - _AES.cp36-win_amd64.pyd

**Comment by msarahan** [comment]
OK, please use that one then.  If we have a fixed package this is not an issue that we will do anything about.  It is the past.
