### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by westfielddave** [ContinuumIO/anaconda-issues#1014]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - _nb_ext_conf ==0.3.0
  - anaconda ==4.1.1 -> _nb_ext_conf 0.2.0 py27_0|0.2.0 py34_0|0.2.0 py35_0
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'qt': '4.8.7', 'version': '1.2.1', 'python': '3.5.2', 'pyqt': '4.11.4', 'conda': '4.1.6', 'language': 'en_US'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
