### ISSUE TITLE
Python 2.7.15 dbm

### ISSUE THREAD

**Issue by btyukodi** [ContinuumIO/anaconda-issues#10149]
DBM module seems to be missing in Anaconda's Python 2.7.15:

Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named dbm

Is there any way I could add it? Thank you.

**Comment by jjhelmus** [comment]
Can you use the `anydbm` or `dumbdbm` modules which provide similar functionality?  The `dbm` module is not included in Anaconda's Python library as it is very infrequently used.

**Comment by vikassriv14** [comment]
But dbm is used inside other modules such pysaml2, and this workaround won't work in such cases. If this issue could be fixed it would be easier to integrate other libraries inside Anaconda.

**Comment by mingwandroid** [comment]
Can they use `anydbm` or `dumdbm`. We're never going to package this GPL only module.
