### ISSUE TITLE
Spyder website and documentation links need to be updated in Anaconda Docs

### ISSUE THREAD

**Issue by CAM-Gerlach** [ContinuumIO/anaconda-issues#10168]
As tracked in spyder-ide/spyder-docs#39 , the Anaconda documentation contains a number of out of date references to Spyder's full name, website and documentation. These are

* [ ] [Spyder page](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/spyder)
    * [ ] Full name (capitalization) should be the Scientific Python Development Environment
    * [ ] Link to our [website](https://www.spyder-ide.org/) is lacking ``https`` and ``www`` to be fully 
    * [ ] Docs link is to our long-frozen PyPI docs and needs to be to our [new docs](https://docs.spyder-ide.org/)
* [ ] [Anaconda Navigator](https://docs.anaconda.com/anaconda/navigator/)
    * [ ] Link to Spyder is to our ancient PyPI docs; should be either to our website or to the Spyder wiki page
* [ ] [Overview](https://docs.anaconda.com/anaconda/navigator/overview)
    * [ ] Again, link to our old PyPI docs rather than either our website or the Spyder page above

Thanks @goanpeca !

**Comment by goanpeca** [comment]
Hi @CAM-Gerlach thanks for pointing out the issues!

**Comment by CAM-Gerlach** [comment]
Thanks @goanpeca ! Looks great!
