### ISSUE TITLE
import matplotlib not working

### ISSUE THREAD

**Issue by sidhart** [ContinuumIO/anaconda-issues#1018]
---

ValueError                                Traceback (most recent call last)
<ipython-input-11-82be63b7783c> in <module>()
----> 1 import matplotlib

//anaconda/lib/python3.5/site-packages/matplotlib/**init**.py in <module>()
   1129 
   1130 # this is the instance used by the matplotlib classes
-> 1131 rcParams = rc_params()
   1132 
   1133 if rcParams['examples.directory']:

//anaconda/lib/python3.5/site-packages/matplotlib/**init**.py in rc_params(fail_on_error)
    973         return ret
    974 
--> 975     return rc_params_from_file(fname, fail_on_error)
    976 
    977 

//anaconda/lib/python3.5/site-packages/matplotlib/**init**.py in rc_params_from_file(fname, fail_on_error, use_default_template)
   1098         parameters specified in the file. (Useful for updating dicts.)
   1099     """
-> 1100     config_from_file = _rc_params_in_file(fname, fail_on_error)
   1101 
   1102     if not use_default_template:

//anaconda/lib/python3.5/site-packages/matplotlib/**init**.py in _rc_params_in_file(fname, fail_on_error)
   1016     cnt = 0
   1017     rc_temp = {}
-> 1018     with _open_file_or_url(fname) as fd:
   1019         try:
   1020             for line in fd:

//anaconda/lib/python3.5/contextlib.py in **enter**(self)
     57     def **enter**(self):
     58         try:
---> 59             return next(self.gen)
     60         except StopIteration:
     61             raise RuntimeError("generator didn't yield") from None

//anaconda/lib/python3.5/site-packages/matplotlib/**init**.py in _open_file_or_url(fname)
    998     else:
    999         fname = os.path.expanduser(fname)
-> 1000         encoding = locale.getdefaultlocale()[1]
   1001         if encoding is None:
   1002             encoding = "utf-8"

//anaconda/lib/python3.5/locale.py in getdefaultlocale(envvars)
    556     else:
    557         localename = 'C'
--> 558     return _parse_localename(localename)
    559 
    560 

//anaconda/lib/python3.5/locale.py in _parse_localename(localename)
    484     elif code == 'C':
    485         return None, None
--> 486     raise ValueError('unknown locale: %s' % localename)
    487 
    488 def _build_localename(localetuple):

ValueError: unknown locale: UTF-8

**Comment by nehaljwani** [comment]
Please reopen this issue if the following doesn't work for you:
```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
If you are on OSX, then follow https://conda.io/docs/troubleshooting.html#unknown-locale
