### ISSUE TITLE
ctypes.util.find_library broken in python=2.7.15=h77bded6_1

### ISSUE THREAD

**Issue by pavoljuhas** [ContinuumIO/anaconda-issues#10180]
The current Python 2.7.15 package for Linux 64 contains patch that breaks `ctypes.util.find_library()` 

```sh
$ conda install python=2.7.15=h77bded6_1
$ python -c 'from ctypes.util import find_library; find_library("doesnotexist")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/anaconda/lib/python2.7/ctypes/util.py", line 298, in find_library
    _get_soname(_findLib_gcc(name) or _findLib_ld(name))
NameError: global name '_findLib_ld' is not defined
```

The undefined function is introduced by `0013-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch` included in package recipe.

Please use full-coverage tests for any patches that change standard Python modules.

**Comment by mingwandroid** [comment]
Thank you for the bug report, this is fixed now.

`conda update python` should get you going again.

**Comment by pavoljuhas** [comment]
This is fixed in the updated package.  Thank you!
