### ISSUE TITLE
Anaconda install on 64-bit Windows 10 fails. VSCode install fails.

### ISSUE THREAD

**Issue by genenaden** [ContinuumIO/anaconda-issues#10181]
0
down vote
favorite
I cannot install 64-bit Anaconda 3 on Windows 10. It says the install is complete but when I proceed to install VSCode, it fails. It says to check my internet connection and to look in the log file. But my internet connection is fine and there is no log file. I am running the install with Windows Defender turned off.

When I look at the start menu, none of the components except for Anaconda Prompt, are there. I would like to have Spyder and Jupyter, for example, but they are not there.

If I install the 32-bit version, it works fine. But I need the 64-bit version

**Comment by nehaljwani** [comment]
@genenaden In the process of installation when it fails, could you please open the directory where you chose to install Anaconda and check if python.exe resides there or not?

**Comment by genenaden** [comment]
Yes, Nehal, it is there.

**Comment by genenaden** [comment]
Yes, @nehaljwani , it is there

**Comment by nehaljwani** [comment]
@genenaden Could you share a screenshot of the failure when the VSCode installation fails? Also, are you doing this behind a corporate proxy / firewalled network?

**Comment by genenaden** [comment]
@nehaljwani , here is the screen shot. If I click "retry" I get the same message. 

I am on a home network with WiFi and not behind any kind of proxy or firewall that i am aware of.
![capture](https://user-images.githubusercontent.com/43540973/46903546-4608c500-ce9c-11e8-8371-2ea09791e6f0.JPG)

**Comment by genenaden** [comment]
PS the indicated log file does not exist anywhere in the install directory tree.

**Comment by nehaljwani** [comment]
@genenaden In the previous comment, I asked about the existence of 'python.exe'. Could you check the same for 'pythonw.exe' as well?

**Comment by genenaden** [comment]
Yes, @nehaljwani, they are both there.

**Comment by genenaden** [comment]
Yes, @nehaljwani, they are both there.

**Comment by smone00** [comment]
> @nehaljwani , here is the screen shot. If I click "retry" I get the same message.
> 
> I am on a home network with WiFi and not behind any kind of proxy or firewall that i am aware of.
> ![capture](https://user-images.githubusercontent.com/43540973/46903546-4608c500-ce9c-11e8-8371-2ea09791e6f0.JPG)

**How to solve this error ???**

**Comment by csoja** [comment]
In current Anaconda installers, no option to install VSCode is provided.  Closing, as this is no longer something we recommend installing from the installer.  We recommend downloading and installing VS Code directly from Microsoft yourself.
