### ISSUE TITLE
conda cannot build an environment .yml file that was created by conda

### ISSUE THREAD

**Issue by bgenchel** [ContinuumIO/anaconda-issues#10183]
On my Mac (OSX High Sierra), I am using anaconda 4.5.11

I am trying to pass my conda environment to a linux machine.

So, while in my environment I use the command

`conda env export > environment.yml`

to create an environment.yml file, which I then commit to my git repository.

On the linux machine:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

I am also using anaconda 4.5.11

once I clone my repo, I want to build my environment, so I run

`conda env create -f environment.yml`

and it fails. Error output:
```
Solving environment: failed

ResolvePackageNotFound:
  - openssl==1.0.2p=h1de35cc_0
  - libcxxabi==4.0.1=hebd6815_0
  - tk==8.6.8=ha441bb4_0
  - zlib==1.2.11=hf3cbc9b_2
  - readline==7.0=h1de35cc_5
  - libcxx==4.0.1=h579ed51_0
  - libffi==3.2.1=h475c297_4
  - libedit==3.1.20170329=hb402a30_2
  - ncurses==6.1=h0a44026_0
  - sqlite==3.24.0=ha441bb4_0
  - python==3.6.6=hc167b69_0
  - xz==5.2.4=h1de35cc_4
```

Why does this fail? I don't know if I've ever been able to successfully transfer an environment in this way, and being able to do this is purportedly one of the benefits of using something like anaconda in the first place.

**Comment by jjhelmus** [comment]
The environment file specifies packages down to their build string.  Packages with the same build string will almost never be available on a different platform, in fact the same packages may not be needed or even available on all platforms.  For example `libcxx` is available on the osx-64 platform but not on linux-64.

**Comment by bgenchel** [comment]
I was able to fix this problem by adding the --no-default-packages and manually deleting the lines in my environment.yml file related to libcxx. 

I found this solution in a forum where many people were having the same issue.

**Comment by TarekAlabrasTalend** [comment]
I am not sure why this is an open issue see issue #6220. To my understanding we shouldn't export environments that are expected to be cross platform without the flag --no-builds. can any one verify if this issue should be closed?

**Comment by msarahan** [comment]
We like it when users close their own issues.  I think it's safe to close this one, though.
