### ISSUE TITLE
fresh anaconda wants to downgrade from Python 3.7 to 3.6

### ISSUE THREAD

**Issue by intuitivetextmining** [ContinuumIO/anaconda-issues#10198]
With the latest MacOS Mojave and latest Anaconda command line installer package

https://repo.anaconda.com/archive/Anaconda3-5.3.0-MacOSX-x86_64.sh

a request to update the package collection 

`condo update anaconda`

causes the package manager to request downgrading almost all packages from python 3.7 to 3.6. See screenshot below.

I tested again by wiping the anaconda directory and associated bash profile and installed again. Same behaviour. This is a fresh MoJave install not an upgrade over High Sierra.

![dpll10qwwbutbv8 jpg-large](https://user-images.githubusercontent.com/42973185/46909656-df33ec00-cf2d-11e8-8798-d871e3c599ce.jpeg)

EDIT - `update conda --all` doesn't do this, I'm sure it did a few days ago but I might be wrong.

**Comment by nehaljwani** [comment]
@intuitivetextmining What happens when you try: `conda install anaconda=5.3.0=py37_0`

**Comment by intuitivetextmining** [comment]
@nehaljwani thanks for the suggestion. here is the result 

```
conda install anaconda=5.3.0=py37_0
Solving environment: done

# All requested packages already installed.
```

Does this help locate the bug?

**Comment by dkmcleod** [comment]
I am also running into the same issue. I upgraded to Mojave from High Sierra. When I install Anaconda Python 5.3 Everything works. I run "conda update conda" - no issue. When I run "conda update anaconda"  the installation is downgraded to python 3.6 as described above. If I skip the "conda update anaconda" step, launch the Navigator, then upgrade Jupiter lab or any package displayed
in the Navigator, the installation is downgraded to Python 3.6. Very Frustrating.

**Comment by msarahan** [comment]
closing to consolidate discussion at #10221

**Comment by makeyourownalgorithmicart** [comment]
latest fresh clean install of Anaconda3-5.3.1-MacOSX-x86_64.sh still can't upgrade/update properly

<img width="555" alt="screenshot 2018-12-20 at 17 35 29" src="https://user-images.githubusercontent.com/29485854/50301056-21bdfb80-047e-11e9-8d4d-eca4898c1882.png">

**Comment by himmetozcan** [comment]
Because tensorflow can not be installed with python 3.7 . Also python 3.6 is not compatible with pyinstaller. So it is best to downgrade to python 3.5.3 :)

**Comment by msarahan** [comment]
@makeyourownalgorithmicart Anaconda 2018.12 fixed this.  The problem was that MKL 2019 was not totally compatible with software built against MKL 2018.  We had to change the anaconda metapackage contents after its release (by altering the repository's dependency data) to use MKL 2018 instead.  The new anaconda release rebuilt everything with MKL 2019, so it properly support it.

@himmetozcan we haven't been building packages for python 3.5 for quite a while,  That's probably not a great way to go.  I'd recommend Python 3.6 if you need to work with Tensorflow.

**Comment by himmetozcan** [comment]
I need to work with tensorflow, I also need pyinstaller. So which python version would you recommend?

**Comment by Thisismfaisal** [comment]
i want to downgrade from python 3.7 to 3.6 to install tencerflow plz tell me step

**Comment by LtDan33** [comment]
Closed as the original issue was resolved
