### ISSUE TITLE
died R kernel in Jupyter

### ISSUE THREAD

**Issue by LittleBeannie** [ContinuumIO/anaconda-issues#10206]
Hello guys, I have a died R kernel every time I run the Jupyter. 
Here is the message from terminal. Could someone help me solve it?
I appreciate lots for your warm-hearted help!
### Actual Behavior

R kernel in Jupyter is always died.

### Expected Behavior

R kernel in Jupyter is connected.

##### Anaconda or Miniconda version:
anaconda 3

##### Operating System:
mac 

##### `conda info`

```
[I 17:39:32.972 NotebookApp] 302 GET /notebooks/Dropbox/Yujie%20Zhao%202018/short%20course/Lecture%20Notes/12.1%20advR_ggplot2/visualization-themes.png (::1) 3.13ms
[W 17:39:33.076 NotebookApp] 404 GET /static/components/codemirror/mode/%7Br%7D/%7Br%7D.js?v=20181016173916 (::1) 11.44ms referer=http://localhost:8888/notebooks/Dropbox/Yujie%20Zhao%202018/short%20course/Lecture%20Notes/12.1%20advR_ggplot2/ggplot2.ipynb
[I 17:39:35.933 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
[I 17:39:38.943 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
[I 17:39:41.955 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
[W 17:39:43.030 NotebookApp] Timeout waiting for kernel_info reply from 297eaa4c-5679-4914-9801-a7494907a4ee
[I 17:39:44.963 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 297eaa4c-5679-4914-9801-a7494907a4ee restarted
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
[W 17:39:47.976 NotebookApp] KernelRestarter: restart failed
[W 17:39:47.977 NotebookApp] Kernel 297eaa4c-5679-4914-9801-a7494907a4ee died, removing from map.
kernel 297eaa4c-5679-4914-9801-a7494907a4ee restarted failed!
[W 17:39:47.994 NotebookApp] 410 DELETE /api/sessions/2cb7e8e4-2169-4ee3-b9a5-e06a493660c3 (::1): Kernel deleted before session
[W 17:39:47.994 NotebookApp] Kernel deleted before session
[W 17:39:47.995 NotebookApp] 410 DELETE /api/sessions/2cb7e8e4-2169-4ee3-b9a5-e06a493660c3 (::1) 2.82ms referer=http://localhost:8888/notebooks/Dropbox/Yujie%20Zhao%202018/short%20course/Lecture%20Notes/12.1%20advR_ggplot2/ggplot2.ipynb

```

**Comment by mingwandroid** [comment]
Please provide the information requested in the issue template. It makes it possible for us to help you.

**Comment by LittleBeannie** [comment]
Hello Ray,

I finished modifying my issue in the template, thanks lots for you help!

Best wishes,
June

在 2018年10月16日，下午6:28，Ray Donnelly <notifications@github.com<mailto:notifications@github.com>> 写道：


Please provide the information requested in the issue template. It makes it possible for us to help you.

**Comment by mingwandroid** [comment]
I still don't see the info.

**Comment by csoja** [comment]
@LittleBeannie  You are missing the results of _conda info_ and _conda list_ - these are critical pieces of information needed to help debug the problem.

**Comment by csoja** [comment]
Oh - you aren't using Anaconda's version of R or using conda to install it.  We are not able to help you debug other installations of R.  
If you are interested in installing R with conda:
https://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language/
https://anaconda.org/r/repo  <- R packages available as conda packages
_conda install r-irkernel_ 
However, keep in mind, that a previous installation of R on your computer may conflict with a new one installed with conda - so it may not work right for you.
