### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aadehamid** [ContinuumIO/anaconda-issues#1020]
Application action error

/Users/hamidadesokan/anaconda/bin/python /Users/hamidadesokan/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/hamidadesokan/anaconda notebook=4.2.2: The following specifications were found to be in conflict:
  - notebook 4.2.2*
  - ssl_match_hostname -> python 2.6*|2.7*|3.3*|3.4*
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'conda': '4.1.8', 'qt': '4.8.7', 'platform': 'osx-64', 'python': '3.5.2', 'language': 'en', 'version': '1.2.2'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
