### ISSUE TITLE
Upgrade ipykernel to 5.1.0

### ISSUE THREAD

**Issue by ciupicri** [ContinuumIO/anaconda-issues#10203]
Upgrade ipykernel to version 5.1.0 which includes an important [bug fix](https://github.com/ipython/ipykernel/pull/362). Without this fix "Run all" doesn't work well in notebooks on Windows.

[ipykernel-feedstock](https://github.com/conda-forge/ipykernel-feedstock) is already at 5.1.0.

**Comment by jjhelmus** [comment]
ipykernel 5.1.0 is now available in the default repository for all platforms.
