### ISSUE TITLE
Anaconda installs in "/anaconda3" on macos mojave (10.14)

### ISSUE THREAD

**Issue by mixmixmix** [ContinuumIO/anaconda-issues#10225]
### Actual Behavior
Anaconda installs in `/anaconda3` which is 
1. a bad practice
2. undocumented (compare with [docs](https://docs.anaconda.com/anaconda/faq/#what-is-the-default-path-for-installing-anaconda) )
3. not exporting path properly when using zsh or bash (I tried to manually run the code added to `.bash_profile` but to no avail.

### Expected Behavior

Should be installed in user directory or some other sensible place. It is `/` for heavens sake. 
Should export the path properly so it is possible to use it without having to `find` it first.
At least should be documented!

### Steps to Reproduce

Install anaconda using graphical installer for macos

##### Anaconda or Miniconda version:
anaconda 5.3.0
##### Operating System:
macos mojave (10.14)
##### `conda info`
not working, path not exported.

##### `conda list --show-channel-urls`
n/a

**Comment by mingwandroid** [comment]
> Anaconda installs in /anaconda3 which is

No, it does not. I just verified that it installed into `~/anaconda3` as the docs state. Years ago it did but it doesn't anymore, otherwise I suspect you installed a newer one with sudo. You should avoid that, our software doesn't require sudo and it just gets in the way.

**Comment by mixmixmix** [comment]
I used a graphical installer which prompted for sudo password. I assume if I cancelled it would interrupt the installation. If the idea is not to acquire a sudo password, I suggest the installer shouldn't ask for it.

**Comment by mingwandroid** [comment]
The installer would only asks for a sudo password if you install for all users. You should not do that. It installs it to the root of the drive for all users and I see nothing wrong with that. Maybe /opt/anaconda3 would be better but I wouldn't bother it changing at this point.

**Comment by nehaljwani** [comment]
@mixmixmix Please see step number 6 at https://docs.anaconda.com/anaconda/install/mac-os/

**Comment by mixmixmix** [comment]
Okey.
On my computer *I only have one user* so the installer *silently skips* step 6 and I assume installs for all users. That causes behaviour described in the issue. 
@mingwandroid, I suggest that it is investigated since it doesn't sound like an intended default behaviour.

**Comment by mingwandroid** [comment]
Is there anything non-standard about your setup? Are you using an Administrator/root account for example?

**Comment by mixmixmix** [comment]
It is an "admin" account, a standard one-user setup for macos. I did have anaconda once installed on this system and I don't recall having this problem (it worked out of the box in console so at least $PATH was set up correctly). 
Are you on Mojave? It might be specific to the recent update and would explain why it hasn't been reported. 
I checked that for instance Python installer asks me "Installation Destination" query nonetheless. Do you know any other programs which I can test if they as for multiple-user installation?

**Comment by mingwandroid** [comment]
I test on a range of OSes, but yes, my primary machine runs macOS Mojave and I was unable to reproduce this. I'm a bit stumped. Might you consider using the shell script installer instead? It may help to diagnose what's going on here if nothing else!

**Comment by mixmixmix** [comment]
Shell script installs in home directory, no matter if executed with or without sudo. 
One option would be if any files left-over by previous anaconda installation I think I had in the past caused this problem. That seems highly unlikely. I'll report here if I find anything out of ordinary which might be relevant. 
Thanks for your help, anyway!

**Comment by nehaljwani** [comment]
@mixmixmix Try out the -p option in the shell script installer.

**Comment by mixmixmix** [comment]
`-p` also works correctly, setting up in home dir.
