### ISSUE TITLE
Update cuDNN version for compatibility with current Ubuntu and Nvidia driver

### ISSUE THREAD

**Issue by saskra** [ContinuumIO/anaconda-issues#10224]
### Actual Behavior

While installing the package tensorflow-gpu via Anaconda it also installs cuDNN version 7.2.1: https://anaconda.org/anaconda/cudnn This is incompatible to Nvidia driver 390, which is the only officially supported driver on Ubuntu 18.04.

### Expected Behavior

It should install version 7.3.1 as officially suggested: https://developer.nvidia.com/rdp/cudnn-download

### Steps to Reproduce

Just create an environment with tensorflow-gpu on Ubuntu 18.04 with Nvidia driver 390 and try to run a software like this: https://github.com/pcpLiu/DeepSeqPan/issues/2

##### `conda info`

```
active environment : None
            shell level : 0
       user config file : /home/me/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /opt/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/anaconda3/pkgs
                          /home/me/.conda/pkgs
       envs directories : /home/me/.conda/envs
                          /opt/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-34-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1003:1003
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at /home/me/.conda/envs/DeepSeqPan2:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.5.0                    py36_0    defaults
astor                     0.7.1                    py36_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.10.15               py36_0    defaults
cudatoolkit               9.2                           0    defaults
cudnn                     7.2.1                 cuda9.2_0    defaults
cupti                     9.2.148                       0    defaults
gast                      0.2.0                    py36_0    defaults
grpcio                    1.12.1           py36hdbcaa40_0    defaults
h5py                      2.8.0            py36h989c5e5_3    defaults
hdf5                      1.10.2               hba1933b_1    defaults
intel-openmp              2019.0                      118    defaults
keras                     2.2.4                         0    defaults
keras-applications        1.0.6                    py36_0    defaults
keras-base                2.2.4                    py36_0    defaults
keras-preprocessing       1.0.5                    py36_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libprotobuf               3.6.0                hdbcaa40_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
markdown                  3.0.1                    py36_0    defaults
mkl                       2019.0                      118    defaults
mkl_fft                   1.0.6            py36h7dd41cf_0    defaults
mkl_random                1.0.1            py36h4414c95_1    defaults
ncurses                   6.1                  hf484d3e_0    defaults
numpy                     1.15.2           py36h1d66e8a_1    defaults
numpy-base                1.15.2           py36h81de0dd_1    defaults
openssl                   1.0.2p               h14c3975_0    defaults
pip                       10.0.1                   py36_0    defaults
protobuf                  3.6.0            py36hf484d3e_0    defaults
python                    3.6.6                h6e4f718_2    defaults
pyyaml                    3.13             py36h14c3975_0    defaults
readline                  7.0                  h7b6447c_5    defaults
scikit-learn              0.20.0           py36h4989274_1    defaults
scipy                     1.1.0            py36hfa4b5c9_1    defaults
setuptools                40.4.3                   py36_0    defaults
six                       1.11.0                   py36_1    defaults
sqlite                    3.25.2               h7b6447c_0    defaults
tensorboard               1.11.0           py36hf484d3e_0    defaults
tensorflow                1.11.0          gpu_py36h9c9050a_0    defaults
tensorflow-base           1.11.0          gpu_py36had579c0_0    defaults
tensorflow-gpu            1.11.0               h0d30ee6_0    defaults
termcolor                 1.1.0                    py36_1    defaults
tk                        8.6.8                hbc83047_0    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.1                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults
```

**Comment by pplcc** [comment]
I ran into the same problem. Same versions Ubuntu 18.04.1, Nvidia driver 390.

**Comment by jjhelmus** [comment]
Can give provide some details on how the presence of the cuDNN 7.2.1 is causing issues?  The tensorflow 1.11.0 package is built against 7.2 and needs that version to function.  You may need to adjust the `LD_LIBRARY_PATH` environment variable to not include any system path which would provide cuDNN if you have a newer version installed.

**Comment by saskra** [comment]
> Can give provide some details on how the presence of the cuDNN 7.2.1 is causing issues?

That is the error message I get:
```
2018-10-16 10:07:55.381849: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2018-10-16 10:07:55.381944: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Possibly insufficient driver version: 390.87.0
Segmentation fault (core dumped)
```

>  You may need to adjust the `LD_LIBRARY_PATH` environment variable to not include any system path which would provide cuDNN if you have a newer version installed.

I would rather want the opposite: Include the cuDNN system path and exclude Anaconda's cuDNN version.

**Comment by jjhelmus** [comment]
That error message indicates that your driver insufficient for the CUDA version that Tensorflow was built against.  This is because the tensorflow in the environment is compiled against CUDA 9.2 which requires a minimum driver version of 396.26.  You can install the Tensorflow package built against CUDA 9.0, which will work with the 390 driver, using `conda install tensorflow-gpu cudatoolkit=9.0`.  

> I would rather want the opposite: Include the cuDNN system path and exclude Anaconda's cuDNN version.

Unfortunately this is not how conda is designed to work.  Conda installs its own libraries and packages and depends only minimally on system libraries.

**Comment by pplcc** [comment]
Jonathan, I am using driver version 396 now and everything is fine! Thank you!

Here are the steps a performed, in case anyone is interested: https://github.com/pplcc/ubuntu-tensorflow-pytorch-setup

**Comment by saskra** [comment]
> The tensorflow 1.11.0 package is **built against 7.2 and needs that version to function**.
 
> That error message indicates that your driver insufficient for the CUDA version that Tensorflow was built against. This is because the tensorflow in the environment is compiled against **CUDA 9.2** which requires a **minimum driver version of 396.26**. You can install the Tensorflow package built against CUDA 9.0, which will work with the 390 driver, using `conda install tensorflow-gpu cudatoolkit=9.0`.

Are these changes between the Anaconda and the original version mentioned anywhere officially? I believed the official TensorFlow website, where it says:
> The following NVIDIA® software must be installed on your system:
CUDA® Toolkit —TensorFlow supports **CUDA 9.0**.
NVIDIA® GPU drivers —**CUDA 9.0 requires 384.x or higher**.
cuDNN SDK **(>= 7.2)**
https://www.tensorflow.org/install/gpu

**Comment by jjhelmus** [comment]
The Anaconda documentation on installing [Tensorflow](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/tensorflow/) includes instructions on how to select different versions of CUDA.

**Comment by arvoelke** [comment]
> The Anaconda documentation on installing [Tensorflow](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/tensorflow/) includes instructions on how to select different versions of CUDA.

FYI, the above link has now changed to: http://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/
