### ISSUE TITLE
Jupyter notebook shortcut fails with space in user home directory path

### ISSUE THREAD

**Issue by matthew-brett** [ContinuumIO/anaconda-issues#10226]
### Actual Behavior

The user had a space in their home directory path - e.g. (`C:\Users\my laptop`).

They were warned against installing in their home directory (Install Just for Me) and so installed on the system (For everyone).

When they tried using the Jupyter Notebook shortcut, it failed.   The contents of the shortcut turned out to end with:

```
... Anaconda3\Scripts\jupyter-notebook-script.py %USERPROFILE%
```

and this was where the break happened, as the unquoted `%USERPROFILE%` string appears  to be two items on the command line, and the command fails trying to locate the part of the file name before the space in the user path.

This can be fixed by enclosing `%USERPROFILE%` in quotes: `"%USERPROFILE%"`.

### Expected Behavior

Jupyter notebook shortcut should run normally when there is a space in the user path.

### Steps to Reproduce

Install system-wide with the Anaconda installer, run Jupyter Notebook shortcut for user with space in home directory.

##### Anaconda or Miniconda version:

Anaconda3 5.3.0

##### Operating System:

Windows 10

**Comment by mingwandroid** [comment]
Thanks for the bug report.

**Comment by nehaljwani** [comment]
A new version of the notebook package (5.7.2-1) is now available in defaults. It contains:

```
\path\to\jupyter-notebook-script.py "%USERPROFILE%/"
```

Closing this issue as resolved. Feel free to re-open if you feel otherwise.
