### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by samjsam** [ContinuumIO/anaconda-issues#1022]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - anaconda-verify ==1.2.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'language': 'en_GB', 'version': '1.2.1', 'python': '3.5.2', 'qt': '4.8.7', 'platform': 'win-64', 'pyqt': '4.11.4', 'conda': '4.1.11', 'os': 'Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type
`conda update anaconda-navigator`
