### ISSUE TITLE
package updates for qt and pyqt request

### ISSUE THREAD

**Issue by geraldstanje** [ContinuumIO/anaconda-issues#1023]
Hi,

Could you update the packages Qt to Version 5.7. and PyQt to Version 5.7?

add: @ccordoba12 

Thanks

**Comment by ccordoba12** [comment]
Sorry, Qt and PyQt 5.7 won't be supported for the time being. The thing is Qt switched to C++11, which leave behind some platforms/compilers we still support.

However, there are already testing packages for Qt/PyQt 5.6 in our qttesting channel:

https://anaconda.org/qttesting

Right now we are working to move those packages to the main channels :-)

**Comment by geraldstanje** [comment]
@ccordoba12 thanks for the quick feedback. Do you plan to add the Qt5.7 and PyQt5.7 package anytime soon?

**Comment by ccordoba12** [comment]
Nop, sorry. As I told you, we're going to support Qt/PyQt 5.6 for at least a year, maybe a year and a half, until we decide what to do with old platforms :-)

**Comment by mingwandroid** [comment]
To follow up on @ccordoba12's comments, Qt 5.6 is the 'long term support' release and the Qt-Project will also be supporting it with essential bug-fixes and security updates for a good while. You can read more about this at:

http://blog.qt.io/blog/2015/12/18/introducing-long-term-support/

**Comment by geraldstanje** [comment]
So that means you will add Qt 5.6 and PyQt 5.6 soon?

**Comment by ccordoba12** [comment]
Yes, they'll be added in about two two weeks :-)

**Comment by geraldstanje** [comment]
ok, great! should not to be too much difference to qt.5.7 :D

**Comment by geraldstanje** [comment]
@ccordoba12 i just saw that pyqtgraph is only supported for qt4. do you know if pyqtgraph will b released for pyqt5.6 soon as well?

**Comment by ccordoba12** [comment]
No idea. We pinned the packages that don't support Qt5 to depend on pyqt 4.x

**Comment by geraldstanje** [comment]
hi, is pyqt5 already in with Anaconda 4.2.0 - Python 2.7 version, 64-Bit Installer?

**Comment by mingwandroid** [comment]
Yes.

**Comment by geraldstanje** [comment]
@mingwandroid: awesome!

**Comment by geraldstanje** [comment]
just a quick side node:
the install of packages fails, if the  you install anaconda for "all users"
e.g. pip install pywavelets

is that issue already tracked?

**Comment by ccordoba12** [comment]
@geraldstanje, nop. Please open a new issue for your problem :-)
