### ISSUE TITLE
What's the difference between two opencv packages?

### ISSUE THREAD

**Issue by tengerye** [ContinuumIO/anaconda-issues#10245]
Hi, there are two packages for opencv on Anaconda: [opencv](https://anaconda.org/conda-forge/opencv) and [opencv3](https://anaconda.org/menpo/opencv3) respectively. They are all opencv3 only with different versions. Is there any other difference?

Thank you.

**Comment by mingwandroid** [comment]
Neither of those channels are part of the `Anaconda Distribution` so you'd
need to ask the people reponsible. Our package is simply called opencv.
