### ISSUE TITLE
Virgin install of Anaconda3 into Windows 10 has empty apps

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#1025]
Installed as "Administrator" so it is usable by everyone.  Installed into `C:\Anaconda3`.  No apps appear.  Refresh doesn't change anything.  Same result whether I start from the icon in the windows menu (start menu) or if I run `anaconda-navigator` from the command line.

![screenshot 2016-08-30 13 56 51](https://cloud.githubusercontent.com/assets/293525/18100664/e2330976-6eb9-11e6-9868-64c56fbd82ac.png)

Only error messages I get when I run from the command line (otherwise Navigator starts up, it just has no apps visible):

```
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by goanpeca** [comment]
>Installed as "Administrator" so it is usable by everyone. 

Probably the issue... will look into it

**Comment by goanpeca** [comment]
Closing this as it is being tracked in the internal repo @ijstokes

**Comment by ijstokes** [comment]
@goanpeca can you provide a link?  It will only be accessible by authorized people.

**Comment by goanpeca** [comment]
Sure

https://github.com/ContinuumIO/navigator/issues/789
