### ISSUE TITLE
Connection error while installing vscode with anaconda

### ISSUE THREAD

**Issue by niskrev** [ContinuumIO/anaconda-issues#10286]
### Actual Behavior
After I answer with yes to this question

> Do you wish to proceed with the installation of Microsoft VSCode? [yes|no]

I get the following output:

> Proceeding with installation of Microsoft VSCode
> Checking Internet connectivity ...
>    Please make sure you are connected to the internet!
>    Check /home/xxx/anaconda3/vscode_inst.py.log for more info

The output of vscode_inst.py.log is:

>   ERROR:vscode_inst:haveInternet                                                                                      
>    Traceback (most recent call last):                                                                                  
>   File "/home/xxx/anaconda3/pkgs/vscode_inst.py", line 143, in haveInternet                                     
>        assert r.status_code == 200                                                                                     
>    AssertionError                                                                                                      
>    ERROR:vscode_inst:haveInternet                                                                                      
>    Traceback (most recent call last):                                                                                  
>      File "/home/xxx/anaconda3/pkgs/vscode_inst.py", line 143, in haveInternet                                     
>        assert r.status_code == 200                                                                                     
>   AssertionError 

There is no problem with my internet connection.

### Expected Behavior
installation should complete

### Steps to Reproduce

`bash ~/Downloads/Anaconda3-5.3.0-Linux-x86_64.sh`

##### Anaconda or Miniconda version:

Anaconda3-5.3.0

##### Operating System:

ubuntu 18.04.1

**Comment by sreisjr** [comment]
Same problem here on macOs Mojave

ERROR:vscode_inst:haveInternet
Traceback (most recent call last):
  File "/Users/username/anaconda3/pkgs/vscode_inst.py", line 143, in haveInternet
    assert r.status_code == 200
AssertionError
ERROR:vscode_inst:haveInternet
Traceback (most recent call last):
  File "/Users/username/anaconda3/pkgs/vscode_inst.py", line 143, in haveInternet
    assert r.status_code == 200
AssertionError
ERROR:vscode_inst:haveInternet
Traceback (most recent call last):
  File "/Users/username/anaconda3/pkgs/vscode_inst.py", line 143, in haveInternet
    assert r.status_code == 200
AssertionError

**Comment by goanpeca** [comment]
@niskrev what system packages did you have to update?

Pinging @nehaljwani

**Comment by niskrev** [comment]
@goanpeca When I was trying (seemingly  unsuccessfully) to install vscode with Anaconda Navigator I got 

> The package system is broken

message from Software Updater. I run
```
sudo apt clean
sudo apt update
sudo apt install -f
```
Then restarted Anaconda Navigator and vscode was installed. Whatever the above commands did/installed seemed to have helped.

**Comment by nehaljwani** [comment]
To check internet connectivity, the script sends a HEAD request to https://vscode-update.azurewebsites.net/api/update/linux-deb-x64/stable/version which used to work a while ago, returning 200. But now it returns 301, the logic will have to be fixed or changed.

**Comment by belkka** [comment]
To fix the problem `allow_redirects=True` can be specified:
`r = requests.head(VSCODE_ENDPOINT, timeout=5, allow_redirects=True)`
instead of
`r = requests.head(VSCODE_ENDPOINT, timeout=5)`
According to requests docs:

> By default Requests will perform location redirection for all verbs except HEAD.
http://docs.python-requests.org/en/master/user/quickstart/#redirection-and-history

Another option is to check that `r.ok` is True, because it also means we have an internet connection.
I would like to make a PR but cannot find the source of vscode_inst.py

**Comment by nehaljwani** [comment]
v5.3.1 Installers will be released soon with the fix! :-)

**Comment by JShibby** [comment]
@nehaljwani , any way for us to follow or be notified when v5.3.1 installers are out (with the fix to this issue)?

**Comment by nehaljwani** [comment]
@JShibby The 5.3.1 installers are live at https://repo.anaconda.com/archive
