### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by j450h1** [ContinuumIO/anaconda-issues#1028]
Anaconda Navigator Update error:

/Users/jas/anaconda2/bin/python /Users/jas/anaconda2/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.2.3: __init__() got an unexpected keyword argument 'max_retries'

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.1.11', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Tue Aug 23 17:02:44 PDT 2016; root:xnu-3789.1.31~2/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

Maybe this has something to do with being on macOS Sierra beta?

**Comment by goanpeca** [comment]
@kalefranz do you know about this?

**Comment by goanpeca** [comment]
`conda update anaconda-navigator`

or

`conda update anaconda` to update to the latest anaconda version :-)

**Comment by j450h1** [comment]
thanks!
