### ISSUE TITLE
Windows installation unstable if root path has space (or unicode for Anaconda2)

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#1029]
Certain Windows installation configurations use full human names (first SPACE middle SPACE last) appended onto `C:\Users`, e.g. `C:\Users\Kevin C Bloom`.  If someone installs Anaconda in such a home directory it appears not to work.  Spaces in the install path has a long history of creating problems:

https://github.com/ContinuumIO/anaconda-issues/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20in%3Atitle%20space

But this is a pretty common one that Anaconda should either support or identify during the install process and warn/abort/prevent the install from proceeding.

**Comment by msarahan** [comment]
I'm not clear from the issue what part is broken.  It sounds like Navigator is certainly broken, but I am less certain about the entire install.  The mailing list person did seem to say that the anaconda prompt worked, right?

**Comment by msarahan** [comment]
I guess just to explain a bit: the hard part about saying "we should support spaces" is that every single piece of software in our stack has to conform with that.  I still think that we should support it, because it is very common.  We had issues with the installer, and I think those are fixed.  Now it's something deeper in the stack.  Unless there is a test for everything that we install, I think we're doomed to frustrate people.

**Comment by ijstokes** [comment]
I get it.  So we could at least tell people the pain they are setting themselves up for if they install into their home directory (which we need to understand might be their only option).

**Comment by ijstokes** [comment]
OK, so this may be a Navigator specific issue for @goanpeca to consider, posted here because it is in discussion in public ML for a non CIO user (whereas the Navigator issue tracker is private).

**Comment by ijstokes** [comment]
Further to the October 1st 2016 Anaconda ML thread for a user with non-ASCII characters in his username, I've updated the title of this issue.

**Comment by goanpeca** [comment]
I dont follow here @ijstokes

**Comment by Ericvulpi** [comment]
Here is a practical example to help along : 
I've installed anaconda on windows 10 in the default directory proposed during installation : "C:\Program Files\Anaconda3". Obviously this path contains space by (microsoft) design.
Not withstanding authorizations issues (I'll write another post), I haven't run into any crippling issues. I've however managed to waste my entire first morning of 2017 to try and get Anaconda Navigator to open a terminal from the dropdown menu of a "non root" environment.
This produces the following error : 
```
C:\Users\name\Documents>() 1>&2
Error: did not expect more than one argument.
C:\Users\name\Documents>() 1>&2
    (Got C:\Program Files\Anaconda3\envs\EnvironmentName)
```
I initially thought it was trying to activate my 2 environments but looking at the root environment  activate.bat file that seems to be used when opening a terminal from anaconda, it looks more like a problem of the environment path being interpreted as 2 arguments.

While you (hopefully) look into this I'll include my quick fix in case anyone run into the same issue : 
 - copy the link called "anaconda prompt" from the start menu (probably generated during installation)
 - right click and go to property then the link tab
 - edit the target box : 
`%windir%\system32\cmd.exe "/K" "C:\Program Files\Anaconda3\Scripts\activate.bat" "C:\Program Files\Anaconda3"`
and replace it by 
`%windir%\system32\cmd.exe "/K" "C:\Program Files\Anaconda3\envs\EnvironmentName\Scripts\activate.bat" "C:\Program Files\Anaconda3\envs\EnvironmentName"`
or 
`%windir%\system32\cmd.exe "/K" "C:\Program Files\Anaconda3\Scripts\activate.bat" "C:\Program Files\Anaconda3\envs\EnvironmentName"`
with `EnvironmentName` to be replaced by the name of your custom environment
and maybe `Anaconda3` to be replaced by whatever the name of your anaconda instalation

**Comment by Ericvulpi** [comment]
An additional comment in case helpful : windows provide an alternate name to `C:\Program Files` to avoid issues with space -> `C:\PROGRA~1`

**Comment by goanpeca** [comment]
Tracking on #716

**Comment by JawadAr** [comment]
```
(base) C:\Users\Jawad Arshad>conda activate
Access is denied.
The system cannot find the file C:\Users\Jawad.
Could Not Find C:\Users\Jawad Arshad\AppData\Local\Temp\conda-17029.tmp
```

I am facing this issue also. My user profile has space in it. I don't want to create a new user. Is there no solution for this?

**Comment by mingwandroid** [comment]
Spaces in your installation folder should work just fine these days. Can you try the latest releases?

**Comment by JawadAr** [comment]
> Spaces in your installation folder should work just fine these days. Can you try the latest releases?

This is the latest release. I have reinstalled it many times. Same issue, but no problems with other user profiles.

C:\Users\Jawad Arshad>conda --version
conda 4.6.14

**Comment by nilavra** [comment]
> ```
> (base) C:\Users\Jawad Arshad>conda activate
> Access is denied.
> The system cannot find the file C:\Users\Jawad.
> Could Not Find C:\Users\Jawad Arshad\AppData\Local\Temp\conda-17029.tmp
> ```
> 
> I am facing this issue also. My user profile has space in it. I don't want to create a new user. Is there no solution for this?

> > Spaces in your installation folder should work just fine these days. Can you try the latest releases?
> 
> This is the latest release. I have reinstalled it many times. Same issue, but no problems with other user profiles.
> 
> C:\Users\Jawad Arshad>conda --version
> conda 4.6.14

I was having similar problems by installing Miniconda in my Users folder (which contains a space). So I did a complete uninstall and reinstalled Miniconda in C:\Miniconda3 (as is suggested [here](https://support.anaconda.com/customer/en/portal/articles/2913013-%22error-cannot-install-into-directories-with-spaces%22)). 
This new installation should not have anything to with my User directory, as it is completely detached. Yet somehow whenever I try to activate an environment, I get similar errors like @JawadAr .

Here's my output:

```
C:\Users\Nilavra Bhattacharya> conda activate nb
Access is denied.
The system cannot find the file C:\Users\Nilavra.
Could Not Find C:\Users\Nilavra Bhattacharya\AppData\Local\Temp\conda-9484.tmp

C:\Users\Nilavra Bhattacharya> conda --version
conda 4.6.14

C:\Users\Nilavra Bhattacharya> where conda
C:\Miniconda3\condabin\conda.bat
C:\Miniconda3\Scripts\conda.exe
```
