### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rawi707** [ContinuumIO/anaconda-issues#1030]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - freeimage ==3.17.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.6', 'version': '1.2.1', 'pyqt': '4.11.4', 'language': 'en_US', 'qt': '4.8.7', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'python': '3.5.2', 'platform': 'win-64'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda update anaconda-navigator`
