### ISSUE TITLE
Anaconda and spyder freeze my computer

### ISSUE THREAD

**Issue by aitor0307** [ContinuumIO/anaconda-issues#10315]
Hi!

I am new to python and I have just installed Anaconda because I want to use Spyder. It's the third time I have installed and uninstalled it because when I start Spyder my computer gets frozen.

Whenever I start Anaconda seems unresponsive and the color wheel on the pointer appears for a few seconds, disappears and appears back again. Then, if I click on Spyder launch it crashes and gets completely stuck.

I have tried to look on the forum for different solutions but I cannot work it out.

I'm running on a Macbook Pro 13 (2016) with OS Mojave 10.14 and Anaconda 2. Python 2.7.15
Has anyone had the same issue or would you know how to solve it?

Many thanks!

Aitor

**Comment by goanpeca** [comment]
@aitor0307 please update all dependencies

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
conda update navigator-updater
```
