### ISSUE TITLE
no python 3.5 build of matplotlib 3.0.1

### ISSUE THREAD

**Issue by Bezier89** [ContinuumIO/anaconda-issues#10311]
See https://anaconda.org/anaconda/matplotlib/files. Note that matplotlib 3.0.0 has python 3.5 builds, but matplotlib 3.0.1 only has python 3.6/3.7 builds. Are python 3.5 builds no longer being generated or was this an oversight?

**Comment by msarahan** [comment]
No longer being generated, as of the Anaconda 5.3.0 release.
