### ISSUE TITLE
ImportError opencv 3.4.3

### ISSUE THREAD

**Issue by peter73421** [ContinuumIO/anaconda-issues#10332]
I use to install opencv 3.4.3 as follows

`(ocv) ~/anaconda3$ conda install -c conda-forge opencv=3.4.3
`

and after using within python3 I got

```
(ocv) ~/anaconda3$ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/ubuntu/anaconda3/envs/ocv/lib/python3.6/site-packages/cv2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv3dnn19experimental_dnn_v414blobFromImagesERKNS_11_InputArrayEdNS_5Size_IiEERKNS_7Scalar_IdEEbb
```

I use recomendation from [issues/9601](https://github.com/ContinuumIO/anaconda-issues/issues/9601) 
that installing package from defaults using 

`conda install -c defaults libprotobuf protobuf 
`

should fix the import failure and **it did not fix** that...

**Comment by jjhelmus** [comment]
You are mixing packages from `conda-forge` and `defaults` which are known to be incompatible.  Creating an environment with OpenCV using packages entirely from one channel or another work fine but mixing them will cause issues.
