### ISSUE TITLE
not able to launch jupyter note from anaconda Navigator 

### ISSUE THREAD

**Issue by rajeev0306** [ContinuumIO/anaconda-issues#10335]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by rajeev0306** [comment]
using windows 10  Jupyter Notebook version 5.7.0 Anaconda Navigator version

**Comment by goanpeca** [comment]
Please provide the requested information on the issue template 



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by rajeev0306** [comment]
I tried just now and it is working now
