### ISSUE TITLE
conflict after installing tensorflow 

### ISSUE THREAD

**Issue by Aashaybane** [ContinuumIO/anaconda-issues#10355]
I am very new to python and data-science and I am using spyder 

 After installing Tensor flow , keras cpu version via anaconda navigator , I am unable to call tensor flow or keras also after installing this,  calling pandas giver error.

System : windows 8 , 64-bit

**Comment by Aashaybane** [comment]
@jjhelmus 
Hi , Jonathan  I have add  the conda info and conda list in issue templet

**Comment by jjhelmus** [comment]
discussion has moved to #10383
