### ISSUE TITLE
error loading spyder kernel 3.3.1

### ISSUE THREAD

**Issue by siafu2001** [ContinuumIO/anaconda-issues#10350]
after updating spyder 3.3.0 to spyder 3.3.1 kernel fails to load, this happens if you had changed the working directory, if you untick the wdir, this corrects the issue

**Comment by mingwandroid** [comment]
Pinging @ccordoba, is this our fault do you think?

**Comment by ccordoba12** [comment]
> is this our fault do you think?

No, I don't think so. Please close this one.

> if you untick the wdir, this corrects the issue

@siafu2001, I don't understand what this means. Please open an issue in our [issues tracker](https://github.com/spyder-ide/spyder/issues) so we can continue the discussion there. And don't forget to fill all the information we require in our issue template.

**Comment by siafu2001** [comment]
> > is this our fault do you think?
> 
> No, I don't think so. Please close this one.
> 
> > if you untick the wdir, this corrects the issue
> 
> @siafu2001, I don't understand what this means. Please open an issue in our [issues tracker](https://github.com/spyder-ide/spyder/issues) so we can continue the discussion there. And don't forget to fill all the information we require in our issue template.
I mean anyone who updated spyder from version 3.30 to 3.3.1 the kernel fails to load, I tried to follow remedies posted but didn't work on windows 10,64bit, when I changed the path to C;>\users it started working again
