### ISSUE TITLE
scikit-learn 0.20.1

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#10353]
Hey folks.
We're just doing a scikit-learn minor version, 0.20.1.
Tag here:
https://github.com/scikit-learn/scikit-learn/releases/tag/0.20.1

**Comment by msarahan** [comment]
We'll get this out early next week.  We're pretty much shut down for the Thanksgiving holiday.

**Comment by amueller** [comment]
That makes sense. Happy Thanksgiving!

**Comment by nehaljwani** [comment]
0.20.1 pkgs are in defaults (except ppc64le).
