### ISSUE TITLE
installation of anaconda failure

### ISSUE THREAD

**Issue by chinthanagendra** [ContinuumIO/anaconda-issues#10366]
i installed anaconda3 and i got some errors while installation,i skipped those errors and continued further.
anaconda prompt is opening and running fine but i can not able to launch the anaconda navigator.

i am using windows8.
 i am attaching the screenshots of the errors that i got.

thanks&regards
nagendra
![error2](https://user-images.githubusercontent.com/45386858/49072815-1a2c7d80-f257-11e8-81b4-06298259a74a.png)
![error3](https://user-images.githubusercontent.com/45386858/49072817-1a2c7d80-f257-11e8-8ee3-6f095750d714.png)
![error](https://user-images.githubusercontent.com/45386858/49072821-1ac51400-f257-11e8-92d5-378a4183877f.png)

**Comment by csoja** [comment]
@chinthanagendra it looks like you do not have a complete installation - those errors you saw during the installation were an indicator of a real problem.  You'll find in the documentation some ideas to try that might help you: https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#windows-error-failed-to-create-anaconda-menus-or-failed-to-add-anaconda-to-the-system-path
