### ISSUE TITLE
Spyder doesn't launch from anaconda navigator and prompt for Tensorflow environment

### ISSUE THREAD

**Issue by Adishah3103** [ContinuumIO/anaconda-issues#10363]
####  I am facing a weird issue where I am not able to launch spyder from anaconda prompt as well as anaconda navigator for tensorflow enviroment. Other applications like Jupyter notebook opens from anaconda prompt and navigator. 
Spyder opens from base env but not from tensorflow env.
Whenever in the prompt I type "spyder" or click "Launch" in navigator for spyder then nothing happens. There are no errors shown in the prompt and it simply doesn't open
Can anyone let me know what's the exact issue?  

#### Spyder opens in the base env
![screenshot 30](https://user-images.githubusercontent.com/30383061/49027799-09342b80-f1c7-11e8-9331-11ebe96283a9.png)

#### But not in tensorflow env
![screenshot 31](https://user-images.githubusercontent.com/30383061/49027760-f02b7a80-f1c6-11e8-9bfc-68f177342abc.png)

**Comment by goanpeca** [comment]
@ccordoba12 thoughts?

**Comment by ccordoba12** [comment]
If your Spyder from the root environment is working, then please follow our guide to use the packages on it without the need to run Spyder on the same env:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach

**Comment by Adishah3103** [comment]
Yeah but still in 3.3.1 there is some problem with "js resource file not loading" ... Although u can solve it by downgrading ipykernel version to 4.8.2 I guess.
Hope this issue solves in upcoming spyer versions
Thanks for your help

**Comment by ccordoba12** [comment]
> in 3.3.1 there is some problem with "js resource file not loading"

That was fixed in 3.3.2, released this weekend and available in Anaconda shortly.

**Comment by Adishah3103** [comment]
That's great

**Comment by csoja** [comment]
Spyder was updated to v3.3.2 in repo.anaconda.com yesterday.  (11/28/2018)

**Comment by rohitdeo90** [comment]
> ### Spyder doesn't launch from anaconda navigator and anaconda prompt
> #### I am facing a weird issue where I am not able to launch spyder from anaconda prompt as well as anaconda navigator for tensorflow enviroment. Other applications like Jupyter notebook opens from anaconda prompt and navigator.
> Spyder opens from base env but not from tensorflow env.
> Whenever in the prompt I type "spyder" or click "Launch" in navigator for spyder then nothing happens. There are no errors shown in the prompt and it simply doesn't open
> Can anyone let me know what's the exact issue?
> 
> #### Spyder opens in the base env
> ![screenshot 30](https://user-images.githubusercontent.com/30383061/49027799-09342b80-f1c7-11e8-9331-11ebe96283a9.png)
> 
> #### But not in tensorflow env
> ![screenshot 31](https://user-images.githubusercontent.com/30383061/49027760-f02b7a80-f1c6-11e8-9bfc-68f177342abc.png)



> If your Spyder from the root environment is working, then please follow our guide to use the packages on it without the need to run Spyder on the same env:
> 
> https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach

This works!
