### ISSUE TITLE
DEA package not available

### ISSUE THREAD

**Issue by diogonarciso** [ContinuumIO/anaconda-issues#10377]
Is it possible to include a Data Envelopment Analysis (DEA) package for Anaconda? It seems there is one available for Python:

https://pypi.org/project/pyDEA/

Is it possible to somehow use this within Anaconda, or in order to use this package I would have to have Python installed independently from Anaconda?

**Comment by csoja** [comment]
It should be possible to use this within Anaconda.  You have a few options for packages that are not available yet as conda packages.  Build a conda package yourself (https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html) or install it using pip into a conda environment.  We recommend not installing pip packages into your base (root) environment.

**Comment by diogonarciso** [comment]
Thanks for your reply. I followed the instructions but it did not work out. I installed conda-build and followed the steps. There was some error message related to "patch". I installed this package as well. I tried again and get the following message:

raise RuntimeError("directory already exists: %s" % dir_path)
RuntimeError: directory already exists: .\pydea

I could not find any "pydea" folder within the anaconda3 folder. Any suggestions? Thanks

**Comment by diogonarciso** [comment]
Ok, I found the pydea folder (looking in the wrong place...) and verified it includes the "meta.yaml" file. I copied the "build.sh" and "bld.bat" files into the folder and executed the command "conda-build pydea". This failed with a long output of messages, which I cannot interpret to find the current issue.

This is what I get (the output is longer):

No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for pydea
INFO:conda_build.metadata:Attempting to finalize metadata for pydea
Solving environment: ...working... failed

**Comment by csoja** [comment]
@msarahan  do you have any tips you could share to help?

**Comment by msarahan** [comment]
It looks like you have omitted part of the build log.  Conda-build should be telling you which dependencies are missing.  You might benefit from running conda-skeleton with the --recursive flag.

**Comment by diogonarciso** [comment]
I tried the followings steps:

1.
(base) C:\>conda skeleton pypi --recursive pyDEA 

It complained pydea folder already exists. So, I deleted it and tried the same command again. Aftar that was completed I ran:

2. (base) C:\>conda-build pyDEA

As I can't really read the log file for mistakes, I wanted to check if the package was there, so I tried:

3. (base) C:\>conda list

The package isn't there. I am not sure what went wrong along the way. The complete log for the 3 steps is attached. Can you spot the problem? Thank you.

[log.txt](https://github.com/ContinuumIO/anaconda-issues/files/2666973/log.txt)

**Comment by diogonarciso** [comment]
@nehaljwani Apparently, xlwt-future is not even one of the packages installed (you can check that on the log file). This problem seems to be somehow related to the package conda-build, which I installed as a recommended prerequisite for this kind of installation. How can I fix this? Thanks.

**Comment by diogonarciso** [comment]
Can anybody provide me some guidance on this subject?

**Comment by diogonarciso** [comment]
The main tool for the pyDEA package is actually a GUI. In that case it doesn't matter much if I am using the Anaconda distribution (and one of its IDEs) or Python. To solve this issue I just installed Python version 3.5.4 and load the pyDEA GUI from the command line.

**Comment by Farah-ab** [comment]
Hi, I'm facing the same problem, can you please explain in details the steps to load the pyDEA GUI from the command line?

**Comment by diogonarciso** [comment]
I haven't used this for a long time. If I remember correctly this library only worked with an older version of Python (~3.5). For additional details, I would suggest to get in touch with the project lead developer: Prof Andrea Raith (University of Auckland).
