### ISSUE TITLE
My navigator is python 3 but I want to use python 2

### ISSUE THREAD

**Issue by Kamillife** [ContinuumIO/anaconda-issues#1037]
Hello guys,

I recently installed anaconda, and I am using the navigator which is a little bit confusing. How do you switch it to python 2.7? Currently, it is by default launching python 3 and I don't like that. I want it to launch python 2.7 by default. 

BTW, I am using a Mac computer. I am totally new to programming, please help me.  Thank you!!

**Comment by goanpeca** [comment]
Hi @Kamillife, Navigator is a GUI working on top of conda the package manager. Are you familiar with conda and conda environments?

Navigator runs by default in the python version that was selected on download, that is, if you downloaded Anaconda3 or Miniconda3, you will get Python 3 and navigator will use that as the default. Likewise if you downloaded Anaconda2 or Miniconda2, you will get Python 2 and navigator will use that as the default. 

However if you need to work on a different environment, all you need to do is go to the Environments Tab and create a new environment that suits your needs and work from there. If you need more information please visit the [Navigator Docs](https://docs.continuum.io/anaconda/navigator)

If this information is enough, please let us know so we can close the issues,.

Cheers!
