### ISSUE TITLE
Navigator 1.9.2 Clone button disabled

### ISSUE THREAD

**Issue by swilson314** [ContinuumIO/anaconda-issues#10370]
I'm trying to follow the directions to clone my "base" environment, but the Clone button is disabled. What am I doing wrong?

![image](https://user-images.githubusercontent.com/24533910/49115462-bb173a80-f24f-11e8-930a-726345809cde.png)

**Comment by csoja** [comment]
@swilson314  The base (root) environment is unique and cannot be cloned.  The option to clone an environment will be available for all other environments.  If you create a new environment, and install the anaconda metapackage - you hopefully won't have too many more you need to select to install.
