### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by imszy** [ContinuumIO/anaconda-issues#10385]
When i try to install matplotlib-3.0.1 in python-3.5.2 with keras-2.2.3
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - matplotlib ==3.0.1
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.6', 'python': '3.5.2', 'os': 'Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel', 'version': '1.2.1', 'platform': 'win-64', 'qt': '4.8.7', 'pyqt': '4.11.4', 'language': 'zh_CN'}

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
