### ISSUE TITLE
Error 522 When Downloading Anaconda for Mac

### ISSUE THREAD

**Issue by db2Dean** [ContinuumIO/anaconda-issues#10389]
### Actual Behavior

I get an Error 522 Connection timed out error from https://www.continuum.io/downloads when trying to download Anaconda for my Mac.  It shows a graphic showing that my Browser is working as well as Cloudflare. However it says that there is an error on the www.continuum.io host.  

### Steps to Reproduce

Just go to https://www.continuum.io/downloads and the error shows up automatically

##### Operating System:
Mac OS 10.14.1

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by msarahan** [comment]
continuum.io URLs are deprecated and may not continue to work.  Try anaconda.com URLs instead (the company was renamed last year).

**Comment by db2Dean** [comment]
Thank you, everyone, who let me know about using the new link.  I am now downloading the installer.  It is worth noting that the link to install Anaconda on the Installing Jypyter page uses the old link.  https://jupyter.readthedocs.io/en/latest/install.html

**Comment by nehaljwani** [comment]
Opened a PR to fix the docs: https://github.com/jupyter/jupyter/pull/386
