### ISSUE TITLE
certifi: update available

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#10388]
A new version of certifi has been released: `2018.11.29`
Could you please build and publish corresponding conda packages?

https://pypi.org/project/certifi/2018.11.29/
https://github.com/AnacondaRecipes/certifi-feedstock

Thanks for your efforts and the great distribution!

**Comment by jjhelmus** [comment]
certifi `2018.11.29` packages are now available in pkgs/main.
