### ISSUE TITLE
Anaconda 3.5.1 linux install not working

### ISSUE THREAD

**Issue by pezcore** [ContinuumIO/anaconda-issues#10407]
### Actual Behavior

Anaconda installer hosted at https://repo.anaconda.com/ does not work. Appears corrupt
```
md5sum
334b43d5e8468507f123dbfe7437078f  Anaconda3-5.3.1-Linux-x86_64.sh
```

outputs:
```
bunzip2: Data integrity error when decompressing.
        Input file = /opt/anaconda3/pkgs/qt-5.9.6-h8703b6f_2.tar.bz2, output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

### Expected Behavior
Installs Anaconda 3

### Steps to Reproduce

```
sudo ./Anaconda3-5.3.1-Linux-x86_64.sh
```

##### Operating System:

```
Linux laptop 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux
```

**Comment by goanpeca** [comment]
@nehaljwani thoughts?

@pezcore wondering why you are using `sudo` on the install command

**Comment by msarahan** [comment]
Corrupt downloads happen because of internet connection problems. Try to download it again. Check the md5 against our published value. If it doesn't match, try again. 

As @goanpeca mentions, using sudo is usually a bad idea.

**Comment by nehaljwani** [comment]
@pezcore Do you see the same behavior if you try to install it to a different partition, for example /tmp or a place where tmpfs is mounted? Also, could you share what filesystem is being used by the path /opt/anaconda3 ?

**Comment by pezcore** [comment]
@nehaljwani 

Installing into tmpfs mount at `/dev/shm` works.

And now I am unable to reproduce the issue on my current machine. It must have just been a filesystem issue with the machine I was using when I opened this issue...

I'm still confused as to why this was happening, but it appears not to be due to a corrupted archive published on the Continuum repo.
