### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by arashsaber** [ContinuumIO/anaconda-issues#1040]
Anaconda Navigator Update error:

//anaconda/bin/python //anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.2.3: Could not find URL: https://pypi.python.org/simple/osx-64/

{'conda': '4.1.6', 'python': '3.5.2', 'language': 'en', 'platform': 'osx-64', 'version': '1.2.1', 'pyqt': '4.11.4', 'qt': '4.8.7', 'os': 'Darwin;15.4.0;Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64;x86_64;i386'}

**Comment by goanpeca** [comment]
It seem the content of your condarc is incorrect.

Please clean your condarc and try again with the latest version of Navigator (1.3)

`conda update anaconda-navigator`

or

`conda update anaconda` to update to the latest anaconda version (4.2)
