### ISSUE TITLE
Anaconda Python (2/3) slow probably because older GCC

### ISSUE THREAD

**Issue by ozancaglayan** [ContinuumIO/anaconda-issues#1041]
Hi,

I was experimenting with the performance of a text file reading script then I've found out a significant performance difference between the python interpreters shipped in Ubuntu 16.04 and the ones coming from anaconda. It seems that the slowdown is caused by the GCC version that is used by Continuum to compile the interpreters.

Here's the test code:

```
from __future__ import print_function
import time
import sys

print(sys.version)

l = ["hello world hello world hello world hello world hello world"] * 1000000

vocab = {}
times = []

for i in range(5):
    result = []
    st = time.time()
    for line in l:
        result.append([vocab.get(w, 1) for w in line.split()])
    times.append(time.time() - st)

print('Mean of 5 runs: {0}'.format(sum(times) / len(times)))
```

And the mean results of 5 consecutive runs:

| Python | Sys/Conda | GCC | Mean time (sec) |
| --- | --- | --- | --- |
| 2.7.12 | System | 5.4.0 20160609 | 3.503 |
| 2.7.12 | Conda | 4.4.7 20120313 | 4.010 |
| 3.5.2 | System | 5.4.0 20160609 | 3.584 |
| 3.5.2 | Conda | 4.4.7 20120313 | 4.282 |

This difference can become huge in large text processing tasks. Can this be directly attributed to the compiler version?

**Comment by Shuolongbj** [comment]
@ccordoba12 @mingwandroid

**Comment by csoja** [comment]
This should be significantly better in the Anaconda 5.0 installers.

**Comment by gokceneraslan** [comment]
@csoja Is there an easy way to switch to 5.0 for miniconda users?

**Comment by mingwandroid** [comment]
```
conda update conda
conda update --all
```

A word of warning, do not install the old `gcc` package. That's legacy and only for people who have not made the jump to 5.0 level packages.

**Comment by csoja** [comment]
Also, Miniconda installers built since September 26th, 2017 (https://repo.continuum.io/miniconda/) are equivalent to Anaconda 5.0 (just with the Miniconda subset of packages).

**Comment by gokceneraslan** [comment]
Thanks.
