### ISSUE TITLE
Anaconda silent installation is showing verifying installer window

### ISSUE THREAD

**Issue by chandan2495** [ContinuumIO/anaconda-issues#10420]
### Actual Behavior

![image](https://user-images.githubusercontent.com/6929170/49934781-4e5d9a80-fef5-11e8-9806-f43e5196c867.png)

### Expected Behavior
In case of silent installation can we avoid showing this popup.

##### Anaconda or Miniconda version:
Anaconda 5.3.1
##### Operating System:
Windows 2012 server

**Comment by goanpeca** [comment]
@nehaljwani thoughts?

**Comment by nehaljwani** [comment]
@chandan2495 What steps did you follow for the silent installation?

**Comment by chandan2495** [comment]
@nehaljwani I am trying to execute the exe with /S option for the silent install as mentioned [here](https://conda.io/docs/user-guide/install/windows.html). Also I noticed that in case of Miniconda installation same option is not showing any verifying installer option.
You can reproduce this with the help option as well.
`Anaconda.exe /?` (This will also show the verifying installer pop up first).

**Comment by LtDan33** [comment]
This is a long standing issue and right now not high priority. Also checked on silent install actually is silent in Windows 10
