### ISSUE TITLE
jpeg 8d (build 1) package is broken on macosx-64

### ISSUE THREAD

**Issue by anjos** [ContinuumIO/anaconda-issues#1042]
Apparently the runtime path is not correctly setup in the build.

Linking against this library will result in a binary that cannot be loaded unless `DYLD_LIBRARY_PATH` is previously set. If you're building a conda package, this is amended afterwards by the conda packaging process. Otherwise, the problem will show up. It would be good to have it fixed.

Here is the output of `otool -L`:

```sh
$ otool -L /opt/conda/envs/bob-devel-py27/lib/libjpeg.8.dylib
/opt/conda/envs/bob-devel-py27/lib/libjpeg.8.dylib:
       	libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
       	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
       	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
```

Here is the output for libgif instead (which works flawlessly):

```sh
$ otool -L /opt/conda/envs/bob-devel-py27/lib/libgif.7.dylib
/opt/conda/envs/bob-devel-py27/lib/libgif.7.dylib:
       	@rpath/libgif.7.dylib (compatibility version 8.0.0, current version 8.0.0)
       	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

(notice the `@rpath/` before the library path)

The version `9b` of the library in conda-forge seems to be correct:

```sh
$ otool -L /opt/conda/envs/test27/lib/libjpeg.9.dylib
/opt/conda/envs/test27/lib/libjpeg.9.dylib:
       	@rpath/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
       	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by anjos** [comment]
I have tried the build manually on OSX and it turns out this is a problem with the library itself.

The following line could be applied to `build.sh` to fix this issue for the Conda builds:

```sh
if [ "$(uname)" == "Darwin" ]; then
    install_name_tool -id @rpath/libjpeg.8.dylib $PREFIX/lib/libjpeg.8.dylib
fi
```

**Comment by 183amir** [comment]
@csoja and @ilanschnell could you please look into this?

**Comment by 183amir** [comment]
Hi @anjos could you please check to see if this still happens in `jpeg 8d` build number `2`?

**Comment by 183amir** [comment]
Ok I checked it:
```
otool -L lib/libjpeg.8.dylib 
lib/libjpeg.8.dylib:
        @rpath/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```
It seems ok.
Thank you.

**Comment by anjos** [comment]
This seems corrected with build 2.
