### ISSUE TITLE
Procedure to install Tensorflow GPU using Conda in Ubuntu 18.04

### ISSUE THREAD

**Issue by WrathofBhuvan11** [ContinuumIO/anaconda-issues#10435]
I'm trying to install Tensorflow GPU using GPU... One of the link (https://www.pugetsystems.com/labs/hpc/Install-TensorFlow-with-GPU-Support-the-Easy-Way-on-Ubuntu-18-04-without-installing-CUDA-1170/ ) says there's no need to install cuda toolkit and cudann separately but it will come in pack... But I get segmentation error core dumb....
But mark Jay says in his video https://m.youtube.com/watch?v=vxjbL5iN1XY we are supposed to install evrythng including cuda toolkit.. etc etc...
Now which method is proper... And please explain why I'm getting segmentation fault core dumb error..... Please explain ASAP
*Note:- mark Jay's method was working properly w months ago until some new driver version came out...!! Now there's incompatibility in drivers and cudnn ... 
My GPU 940mx GeForce 4GB.. and installed Nvidia driver version 396 ...

**Comment by csoja** [comment]
Have you seen this blog post? https://www.anaconda.com/blog/developer-blog/tensorflow-in-anaconda/   Note - you should find out what versions of cudnn your driver is compatible with and install the latest version of tensorflow that is compatible - and not upgrade it past that point. Here is a list of the available versions of tensorflow from Anaconda: https://anaconda.org/anaconda/tensorflow-gpu/files  

Also, you may find the conda docs or the conda cheatsheet helpful: https://conda.io/projects/conda/en/latest/user-guide/cheatsheet.html https://conda.io/en/latest/

I'm going to close this issue.  If you are still having trouble, please open a new issue with all the information requested in the issue template.  It is impossible to offer any additional advice without the requested information.
