### ISSUE TITLE
Enhancement request to Matplotlib package

### ISSUE THREAD

**Issue by saraneem** [ContinuumIO/anaconda-issues#10437]
### Actual Behavior
In our code, we use mouse-clicks in the graphics display for various purposes, but when someone enters matplotlib zoom or pan mode, this "steals" the mouse clicks and our code does not function. The failure to respond is a fairly frequently reported "bug." To make matters worse with wxPython 4.0. on the Mac the "highlighting" of the zoom and pan icons fails (see https://github.com/wxWidgets/Phoenix/issues/1091) so users cannot even see that they have selected either mode. One saving grace is that our code uses only the WXAgg MPL backend.

### Expected Behavior
One thought is that I can have my code clear the zoom/pan mode at various times, so that users are less likely to be caught by surprise. I have added code to my own wrapper for the MPL Toolbar class that allows me to test if the Zoom/Pan mode is active and to clear the mode. The code I wrote runs with MPL 1.1, 2.0 and 3.0, but accesses private variables, so it really should be in MPL. 

I'd like to propose adding the following code to the NavigationToolbar2 class in matplotlib/backend_bases.py to add this capability:

```
def get_zoompan(self):
"""Return "ZOOM" if Zoom is active, , "PAN" if Pan is active,
or None if neither
"""
return self._active

def reset_zoompan(self):
"""Turns off Zoom or Pan mode, if on. Ignored if neither is set"""
if self._active == 'ZOOM':
self._active = None
if self._idPress is not None:
self._idPress = self.canvas.mpl_disconnect(self._idPress)
self.mode = ''

if self._idRelease is not None:
self._idRelease = self.canvas.mpl_disconnect(self._idRelease)
self.mode = ''
self.canvas.widgetlock.release(self)
#self.????.toggle_toolitem('Zoom', False) # how do I get to
#matplotlib.backend_managers.ToolManager or ToolToggleBase;
# is this even needed?
elif self._active == 'PAN':
self._active = None
if self._idPress is not None:
self._idPress = self.canvas.mpl_disconnect(self._idPress)
self.mode = ''

if self._idRelease is not None:
self._idRelease = self.canvas.mpl_disconnect(self._idRelease)
self.mode = ''
self.canvas.widgetlock.release(self)
#self.????.toggle_toolitem('Pan', False) # needed, see above
```
This code works for me with very minimal testing (MPL 3.0.1, WXAgg backend, Mac OS X only), but I suspect that a clear of the toggle mode for the zoom or pan button may be needed to get this to work everywhere, but can't figure out how to get to the routines that implement that.

Comments/help appreciated.

**Comment by msarahan** [comment]
Please file this issue on the matplotlib issue tracker. We do not deal with 3rd party libraries like matplotlib in this level of detail.
