### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by monali45** [ContinuumIO/anaconda-issues#10447]
The following errors occured:

None:
Dependency missing in current win-64 channels: 
  - theano ==0.9.0 -> m2w64-toolchain

You can search for packages on anaconda.org with

    anaconda search -t conda m2w64-toolchain

{'python': '3.5.2', 'platform': 'win-64', 'pyqt': '4.11.4', 'conda': '4.1.6', 'version': '1.2.1', 'language': 'en_IN', 'qt': '4.8.7', 'os': 'Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel'}

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
