### ISSUE TITLE
Update rasterio

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/anaconda-issues#10443]
I'd like to raise a request that the `rasterio` package gets updated in the `defaults` channel.  Rasterio is critical for the GIS community (and others).  The last update was in 2016.

**Comment by jjhelmus** [comment]
rasterio 1.0.13 packages are now available in defaults for all supported platforms and python version.

**Comment by mrocklin** [comment]
Thanks @jjhelmus !

**Comment by scottyhq** [comment]
Just following up on this - can there be automatic updates for rasterio on the defaults channel? rasterio has had several minor releases already since December (up to 1.0.18):
```
conda search rasterio -c conda-forge
```
but defaults channel is still is at 1.0.13

**Comment by msarahan** [comment]
We're always working on ways to improve our package build speed, but there will never be a completely automated build and deployment to defaults.  Having the human in the loop is a necessary part of our process that ensures some sanity and consistency.  We do have automation scripts that help us build "easy" packages that are nothing more than version bumps.  Generally lack of updates means there's some problem that we need to address with manual attention, and that time is hard to come by.

If you need more rapid updates, the conda-forge packages should be generally more up-to-date, thanks to their more distributed maintainer model.
