### ISSUE TITLE
scikit-learn 0.20.2 not available

### ISSUE THREAD

**Issue by qinhanmin2014** [ContinuumIO/anaconda-issues#10455]
scikit-learn 0.20.2 is not available through the default channel (already available through pypi and conda-forge).
Github tag: https://github.com/scikit-learn/scikit-learn/releases/tag/0.20.2
pypi: https://pypi.org/project/scikit-learn/#history
conda-forge PR: https://github.com/conda-forge/scikit-learn-feedstock/pull/87

**Comment by msarahan** [comment]
Has been available since Friday.

**Comment by qinhanmin2014** [comment]
Thanks :)
