### ISSUE TITLE
Spyder not able to find python in windows

### ISSUE THREAD

**Issue by ShreyakTiwari** [ContinuumIO/anaconda-issues#1045]
Hi Team,
My spyder had got stuck and stopped python from task manager to close the app. I have restarted the system but am not able to open spyder still . Also i am able to run python scripts via command line. Could you please point where the problem lies.

Thanks a lot for your time,
Shreyak

**Comment by ccordoba12** [comment]
Sorry for not answering before, busy here ;-) What you need to do is to find a directory called `.spyder2` (note the dot at the beginning :-) in your `C:\Users\<you>` directory, and then delete a file called `spyder.lock` in there.

In Spyder 3.0 you just need to run in a terminal

    spyder --reset

and that will take care of removing `spyder.lock`.

**Comment by ShreyakTiwari** [comment]
Thanks a lot for your reply . Issue is resolved now.

**Comment by ccordoba12** [comment]
:+1: :+1:
