### ISSUE TITLE
tensorflow installation through conda-forge ― doesn't work for jupyter notebooks

### ISSUE THREAD

**Issue by matanster** [ContinuumIO/anaconda-issues#10473]
I've followed the official blog post on [installing tensorflow from anaconda](https://www.anaconda.com/blog/developer-blog/tensorflow-in-anaconda/) (does this still belong in this issue tracker?)

Installation command went smoothly:
```
conda create -n tensorflow_env tensorflow
```

And I activated the new environment
```
conda activate tensorflow_env
```
 
However, while in a python prompt I can `import tensorflow`, in a Jupyter notebook launched from the same terminal window and environment, it fails to locate the module:

> ModuleNotFoundError: No module named 'tensorflow'

Is this a known issue?
Any workaround? 

##### Operating System:
Ubuntu 16.04

##### `conda info`
```
     active environment : tensorflow_env
    active env location : /home/user/anaconda3/envs/tensorflow_env
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.5.11
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/user/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/user/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/anaconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.4.0-141-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : /home/user/.netrc
           offline mode : False

```

**Comment by matanster** [comment]
My python version where the import works, is slightly different than the one used by Jupyter:

$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux

But it may reflect an older install of tensorflow and not necessarily relevant to why my Anaconda borne Jupyter Notebook can't make the import after the installation command.

**Comment by jjhelmus** [comment]
@matanster You will need to either install notebook into the environment where `tensorflow` is install , `conda install -n tensorflow_env notebook`, or switch to the Jupyter kernel to use the `tensorflow_env` environment.

**Comment by matanster** [comment]
Thanks a lot for responding. What I've done now is like you suggest, explicitly install jupyter to the new `tensorflow_env` conda env now (conda install...), so that I launch conda's jupyter and not the default OS installed one I guess. That solves it. 

For future cases though, is there a straightforward configuration or startup command, for having Jupyter pick up the current environment, and use the environment's supplied kernel, when launching it?

**Comment by jjhelmus** [comment]
I am not aware of a method to specify the environment when you start Jupyter.  You can install the `nb_conda_kernels` package which will add a drop down to Jupyter where the environment can be selected when starting a notebook.  I believe notebook still needs to be installed in each environment.
