### ISSUE TITLE
Qt5 macOS text string does not render correctly if font was stretched

### ISSUE THREAD

**Issue by bug400** [ContinuumIO/anaconda-issues#10493]
### Actual Behavior

A text string in a Qt5 Application does not render correctly if a stretch factor > 100 is applied to the font (see example program and screenshot). This seems to be macOS specific. The string renders correctly in the Windows and LINUX versions of Anaconda.

### Expected Behavior

Text string should render correctly. 

### Steps to Reproduce

Run the attached program "hello.py"

##### Operating System:
macOS 10.14.2

##### `conda info`
active environment : None
       user config file : /Users/achim/.condarc
 populated config files : /Users/achim/.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /Users/achim/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/bug400/osx-64
                          https://conda.anaconda.org/bug400/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/achim/miniconda3/pkgs
                          /Users/achim/.conda/pkgs
       envs directories : /Users/achim/miniconda3/envs
                          /Users/achim/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 1137950790:1752730333
             netrc file : None
           offline mode : False
[files.zip](https://github.com/ContinuumIO/anaconda-issues/files/2736171/files.zip)

##### `conda list --show-channel-urls`

#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h6174b99_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.5.12                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.4.2            py37ha12b0ac_0    defaults
dbus                      1.13.2               h760590f_1    defaults
expat                     2.2.6                h0a44026_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
glib                      2.56.2               hd9629dc_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py37_0    defaults
jpeg                      9b                   he5867d9_2    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.35               ha441bb4_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.1.1a               h1de35cc_0    defaults
pcre                      8.42                 h378b8a2_0    defaults
pip                       18.1                     py37_0    defaults
pyalc7t                   1.0.0                    py37_0    bug400
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pyilper                   1.8.0                    py37_0    file:///Volumes/common/miniconda/channel
pyopenssl                 18.0.0                   py37_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pyserial                  3.4                      py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.1                haf84260_7    defaults
python.app                2                        py37_9    defaults
qt                        5.9.7                h468cd18_1    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
setuptools                40.6.3                   py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wheel                     0.32.3                   py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               h1de35cc_3    defaults

**Comment by mingwandroid** [comment]
Please report this to the Qt Project.

**Comment by mingwandroid** [comment]
Actually this is a known bug with Qt: https://bugreports.qt.io/browse/QTBUG-68041
