### ISSUE TITLE
Package install issue 

### ISSUE THREAD

**Issue by Aashaybane** [ContinuumIO/anaconda-issues#10502]
### Actual Behavior

**When ever I try to install any package from anaconda navigator it give below mentioned error** 

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> bleach==3.0.2=py37_0
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37hb782905_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37hdce8814_0
  - anaconda==2018.12=py37_0 -> scikit-learn==0.20.1=py37h343c172_0
  - tensorflow-base
Use "conda info <package>" to see the dependencies for each package.

## This is happens every time i try to install any package 
```

```
windows 8.1
processor  : Intel(R) corre(TM) i5 -4590 CPU @ 3.30 GHZ
RAM : 8 GB
SYS TYPE : 64-bit operating system , x64-based processor

**Comment by cneskey** [comment]
The latest of version of Python is not supported by the packages you're using.
Create an environment installed with a supported version of Python e.g. Python 3.5.

To do this with conda:
```
conda create -n projectname
activate projectname
```

If you use spyder:
`conda install spyder=3.2.3`

If you don't use spyder:
`conda install python=3.5`

Then run the commands you're trying to run that expect python 3.5.

You'll also see this new environment that has older Python in your Anaconda Navigator:
![image](https://user-images.githubusercontent.com/4606261/51319282-9a3abc80-1a2a-11e9-96ed-d5210f25a644.png)

**Comment by csoja** [comment]
tensorflow is not available for Python 3.7.  Sounds like tensorflow v1.13 may support Python 3.7 - but until then, you'll need to use Python 3.6 if you want to install and use tensorflow.
