### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by huangjiegis** [ContinuumIO/anaconda-issues#10509]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - matplotlib ==1.5.3
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Linux;4.15.0-43-generic;#46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018;x86_64;x86_64', 'qt': '4.8.7', 'python': '3.5.1', 'language': 'zh_CN', 'version': '1.2.1', 'conda': '4.1.4', 'pyqt': '4.11.4', 'platform': 'linux-64'}

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
