### ISSUE TITLE
VS Code Insiders

### ISSUE THREAD

**Issue by GiRiKoTTe** [ContinuumIO/anaconda-issues#10511]
I use VS Code Inside version but Anaconda Navigator doesn't recognize the installation. How can I get Anaconda navigator to recognize my VS Code Insider installation?

**Comment by goanpeca** [comment]
@GiRiKoTTe what do you mean by `VS Code Insider`. Where is this installed?

We currently recognize VSCode for user and global installs on defaults locations

**Comment by GiRiKoTTe** [comment]
https://code.visualstudio.com/insiders/

VS Code Insiders is the nightly equivalent of the standard VS Code.
The default installation path is C:\users\{username}\AppData\Local\Programs\

**Comment by goanpeca** [comment]
@GiRiKoTTe what version of Navigator are you using?

**Comment by GiRiKoTTe** [comment]
Version I use is 1.9.6

**Comment by GiRiKoTTe** [comment]
Resolved by choosing the python interpreter.
