### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kristanmarkey** [ContinuumIO/anaconda-issues#1052]
Anaconda Navigator Update error:

Extra data: line 2 column 1 (char 80)

{'python': '3.5.2', 'pyqt': '4.11.4', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'qt': '4.8.7', 'version': '1.2.2', 'conda': '4.1.11', 'platform': 'osx-64'}

**Comment by goanpeca** [comment]
Tracking with #969 
---

Closing as duplicate
