### ISSUE TITLE
Impact of upgrading  redhat version  on the installation of anaconda

### ISSUE THREAD

**Issue by sahbiept** [ContinuumIO/anaconda-issues#10524]
We will upgrade the redhat system version from 6.9 to 7.

I want to know if there will be an impact on the existing python package installations: I made the installation of these packages via anaconda 3.4.2.0. Should we reinstall anaconda after the upgrade of redhat or there will be no need ?

Thanks for your help

**Comment by csoja** [comment]
Anaconda is compatible with Centos6+, so it shouldn't break when you upgrade  - however, I suspect your version of Anaconda is very out of date. There was never an anaconda v3.4.2 - so I'm guess you either mean conda version or python version. We would definitely recommend upgrading, especially to get the latest security updates/patches - as well as performance improvements.  The current version of Anaconda is 2018.12, conda 4.5.12 and python 3.7.1.
