### ISSUE TITLE
How does one install tensorflow-nightly using anaconda over python3?

### ISSUE THREAD

**Issue by thebeancounter** [ContinuumIO/anaconda-issues#10534]

**Comment by csoja** [comment]
Anaconda does not build conda packages of tensorflow-nightly at this time.  The build time for tensorflow is quite extensive - so we focus on only building the stable releases.  
https://www.tensorflow.org/probability/install has instructions for using pip to install what you are looking for.

**Comment by callmekofi** [comment]
this should work `conda install -c conda-forge tensorflow`
