### ISSUE TITLE
Styleframe Python package (dataframe layout)

### ISSUE THREAD

**Issue by tmdBXL** [ContinuumIO/anaconda-issues#10532]
Hello

I'd like to use the Styleframe package in order to change the lay-out of  a dataframe when copying it to xls via xlsxwriter. Though, i have the impression Styleframe isn't including in Anaconda.
Any idea how I can resolve this? Add it to Anaconda?
many thanks in advance to all !

**Comment by csoja** [comment]
Unfortunately, it looks like there isn't a conda package for styleframe.  You do have the option to try and install it with pip.  This can work very well with Anaconda if the package you are looking to install is pure python.  I'd recommend reading a couple of our recent blog posts on best practices of using pip with conda and Anaconda. https://www.anaconda.com/blog/developer-blog/understanding-conda-pip/  https://www.anaconda.com/blog/developer-blog/using-pip-in-a-conda-environment/
