### ISSUE TITLE
Entire Conda/Miniconda installation website seems corrupted

### ISSUE THREAD

**Issue by gpetty** [ContinuumIO/anaconda-issues#10536]
### Actual Behavior

All pages in the conda.io web hierarchy appear to generate "this page does not yet exist" errors, including the pages for downloading/installing conda/miniconda.

### Expected Behavior

Pages should be accessible.

### Steps to Reproduce

Click on just about any link that turns up in a google search on "conda python", specifically those in the conda.io domain.

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by msarahan** [comment]
Thanks for reporting.  We're in the middle of restructuring our docs.  Please bear with us while we fix links that broke.   Direct downloads of Miniconda are at https://repo.anaconda.com/miniconda/

**Comment by csoja** [comment]
This should be in much better shape now: https://conda.io/en/latest/  There have also been many redirects put in place - for links to the docs that are found often through search engines.  Thanks for reporting and your patience while we fixed it.
