### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by togrishka** [ContinuumIO/anaconda-issues#1055]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - lz4 ==0.8.2
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.11', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Hi @togrishka, the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator

On the command prompt you can type:

`conda update anaconda-navigator`
