### ISSUE TITLE
Anaconda Navigator renders too small to read on Dell XPS 13

### ISSUE THREAD

**Issue by willkeenan** [ContinuumIO/anaconda-issues#1057]
The recommended resolution on is 3200 x 1800. When opening Anaconda Navigator the text is so small that it is difficult to read. Is there any parameter that can be adjusted to increase the text size?

**Comment by goanpeca** [comment]
Hi @willkeenan, it is a current limitation of the Qt version we use (4.8), but in two weeks, a new version of the Anaconda Distribution will be released which includes a new version of Qt (5.6) and a new version of Navigator that correctly handles this issue.

Thanks for reporting and stay tunned :-)

**Comment by carloslagorio** [comment]
I'm having the opposite problem. My resolution is 3200x1800 and the GUI displays so big that the top right icons (minimize, resize, close) don't fit in my screen.

Is there an update on this? I only installed navigator yesterday and am running version 1.3.1.

Thanks!

**Comment by goanpeca** [comment]
Closing as it has been fixed on the latest release (1,3)

@carloslagorio your problem has been reported on #1127. Please refer to that one

**Comment by willkeenan** [comment]
Many thanks, Gonzalo, to you and your colleagues. I've just installed 
the latest release and it renders perfectly!

Will

**Comment by goanpeca** [comment]
:+1:
