### ISSUE TITLE
psutil.AccessDenied (pid=3948)

### ISSUE THREAD

**Issue by rinky97** [ContinuumIO/anaconda-issues#10577]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by rinky97** [comment]
I had already tried the following commands
conda update conda
conda update anaconda-navigator
conda update navigator-updater

**Comment by csoja** [comment]
In the terminal or Anaconda Prompt:

conda update conda
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset

The last command is the key to fixing your issue - as it removes the lock file that is causing your problem.
