### ISSUE TITLE
Bump Dask package?

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/anaconda-issues#10574]
The `dask`, `dask-core`, and `distributed` packages are a couple versions out of date now on the defaults channel.  It seems like whatever automated process existed before has gone away?  Is there a good way for me to trigger a build?

**Comment by jjhelmus** [comment]
I've updated `dask`, `dask-core` and `distributed` to their latest versions in `defaults`  We are working on streamlining the process that we use to update packages, hopefully this will improve in the future.  Keeping the conda-forge recipes up-to-date is the best method for helping this process along.
