### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by saxenakrati09** [ContinuumIO/anaconda-issues#10604]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/bin/spyder", line 7, in <module>
    from spyder.app.start import main
ImportError: No module named spyder.app.start

```
## System information
```
python: 3.6.8
language: en
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.6.3
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

---

**See issue #8216 for more information on how to fix this issue.**

Or try running

```
conda upgrade jupyter_core
```
