### ISSUE TITLE
conda install cyvcf installs cyvcf2

### ISSUE THREAD

**Issue by mfoos** [ContinuumIO/anaconda-issues#10618]
Hi there, I was recommended a python package called cyvcf, and when I created an environment with it, everything installed without error. When I tried to `import cyvcf` it said module not found. After digging into paths in every way I knew how, a coworker tried `help('modules')` and we discovered that cyvcf installs cyvcf2, which is a different piece of software. You can see in the "home" link on the Anaconda package page that it does not go to cyvcf: [https://anaconda.org/bioconda/cyvcf](https://anaconda.org/bioconda/cyvcf)

Can you please fix either the name of the package, or the source link? (the former may be more appropriate, since cyvcf seems to be more regularly updated) Thank you!

**Comment by msarahan** [comment]
That package is part of bioconda, which is a totally separate group of people.  Please file your issue at https://github.com/bioconda/bioconda-recipes
