### ISSUE TITLE
Latest version of Navigator

### ISSUE THREAD

**Issue by Dipugee** [ContinuumIO/anaconda-issues#1061]
How do I check to see I have the latest version of Navigator? Currently I have version 1.2.3.

Also, each time I restart my Mac (running OS 10.11.6) the Navigator icon in my dock tray shows a "?" and I cannot launch it until I reinstall the icon from the Application folder. Is there a way to prevent this? None of my other application icons behave this way.

Thanks.

Dipu

**Comment by goanpeca** [comment]
Hi @Dipugee thanks for the message. We will look into it.

If navigator is not in the latest version, you will see an info icon that you can click to update

![image](https://cloud.githubusercontent.com/assets/3627835/18525327/9fee67a8-7a81-11e6-9d10-c75c208c5f39.png)

---

@ccordoba12, @ilanschnell do you guys know about the dock icon dissapearing?

**Comment by Dipugee** [comment]
Thanks. 

Also, I am not sure if this is the right forum for this question or not, but I will ask in case it is…

I would like to get the version of OpenCV package(s) that will work with Python 3.5. What do I need to do to get that/them?

Thanks.

Dipu

Dipankar Ganguly
Consultant: Strategy/Technology/Commercialization
Bothell, WA
Cell: 408-203-8814
email: dipugee@gmail.com
http://www.linkedin.com/in/dipugee

**Comment by goanpeca** [comment]
@Dipugee you can ask this here but as a separate question. Please do not mix issues

**Comment by Dipugee** [comment]
Ok. Thanks. I am new and learning.

Best.

Dipu


Dipankar Ganguly
Consultant: Strategy/Technology/Commercialization
Bothell, WA
Cell: 408-203-8814
email: dipugee@gmail.com
http://www.linkedin.com/in/dipugee

**Comment by goanpeca** [comment]
:+1:

**Comment by goanpeca** [comment]
New version available

`conda update anaconda-navigator`

or

`conda update anaconda` to update to the latest anaconda version :-)
