### ISSUE TITLE
Anaconda Prompt force closed after install keras

### ISSUE THREAD

**Issue by sleeplessme** [ContinuumIO/anaconda-issues#10622]
1. Im uninstalling anaconda because can't open jupyter notebook after updating db adapter for postgresql. Then after instaling anaconda again, im trying to install keras using 

conda install -c conda-forge keras 

on anaconda prompt

2. One of the requirement is update conda to conda xx(i forgot) then when installing updating the conda, error message access denied shown. 

3. Anaconda prompt suddenly closed, and when i want to open new anaconda prompt, always force closed even i can't read error message. But luckily i have another anaconda prompt open when trying to install (i dont know why im opening two anaconda prompt), so i'm uninstalling keras, and it say success.

But now i can't open anaconda prompt, it always force closed. I guess the problem in keras?

my conda version is 4.6.3

update:
im running my python code using vscode, and somehow i use python base conda, the error message is:

conda activate base

C:\Users\name>SET DISTUTILS_USE_SDK=1
C:\Users\name>SET MSSdk=1
C:\Users\name>SET platform=
C:\Users\name>IF /I [AMD64] == [amd64] set "platform=true"
C:\Users\name>IF /I [] == [amd64] set "platform=true"
C:\Users\name>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" )
C:\Users\name>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B"
ERROR: The system was unable to find the specified registry key or value.
C:\Users\name>if "" == "" (set "VSINSTALLDIR=" )
C:\Users\name>if "" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"
 exit 1
)
"Did not find VS in registry or in VS140COMNTOOLS env var - exiting"

**Comment by sleeplessme** [comment]
Im uninstalling vs_code library at conda, and it works! But still dont know why

**Comment by JdVaru** [comment]
I am also getting same problem after install keras. I have removed Keras and Tensorflow by using Anaconda Navigator. But still Anaconda Prompt force closed.  uninstalling vs_code linrary work for you??

**Comment by sleeplessme** [comment]
yes, it works for me. Do you have visual studio code berfore installing?

**Comment by JdVaru** [comment]
no i do not have visual studio installed in my system

**Comment by sleeplessme** [comment]
hmm maybe you could use vscode to see the error message, sorry that im not helping at all

**Comment by JdVaru** [comment]
ok.. Np let me dig more to get detail

**Comment by sleeplessme** [comment]
good luck and please tell us how you resolved it

**Comment by psn1997** [comment]
It is better to create a new environment for keras, do not install on base environment
