### ISSUE TITLE
Anaconda Navigator Channels modal incorrectly placed with multiple monitors

### ISSUE THREAD

**Issue by bs444** [ContinuumIO/anaconda-issues#10638]
### Actual Behavior

In Anaconda Navigator, when clicking the "Channels" button, the "Manage channels you want Navigator to include" modal appears off screen, at the "right" location, but on the main display.

### Expected Behavior

In Anaconda Navigator, when clicking the "Channels" button, the "Manage channels you want Navigator to include" modal appears immediately under the button on whatever display Anaconda Navigator is currently on.

### Steps to Reproduce

1. Open Anaconda Navigator
2. Move window to secondary monitor.
3. Click Environments tab
4. Click Channels button

##### Anaconda or Miniconda version:

Anaconda3 2018.12
Anaconda Navigator 1.9.6

##### Operating System:

Win 10 1803 x64

##### `conda info`

```
(base) C:\>conda info

     active environment : base
    active env location : C:\Users\<snipped>\AppData\Local\Continuum\anaconda3
            shell level : 1
       user config file : C:\Users\<snipped>\.condarc
 populated config files : C:\Users\<snipped>\.condarc
          conda version : 4.6.4
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Users\<snipped>\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\<snipped>\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\<snipped>\.conda\pkgs
                          C:\Users\<snipped>\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\<snipped>\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\<snipped>\.conda\envs
                          C:\Users\<snipped>\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
n/a

```

**Comment by goanpeca** [comment]
@bs444 thanks for reporting. Could you include a screenshot?

**Comment by bs444** [comment]
Unable to provide screenshot.
More info: 
The Channels button is greyed out. The Channels modal is open, but may not appear at all because it "follows" the relative location on monitor 2, but if monitor 1 is not the same size, the modal may be off screen. Focus remains on modal until ESC pressed.

**Comment by vshevchenko-anaconda** [comment]
I'm closing this ticket as stale. Please, open a new ticket if needed.
