### ISSUE TITLE
numpy import error in Eclipse/PyDev on win 7 but it works in Anaconda prompt.

### ISSUE THREAD

**Issue by usact** [ContinuumIO/anaconda-issues#10632]
I try to run python 3.7 script in Eclipse/pydev ion win 7.

Wheh I imported numpy, i got error:

	    import numpy.core.numeric as _nx
  	    File "C:\My_Program\Anaconda3p7\Lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    raise ImportError(msg)
            ImportError: 
	    Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy.
	     If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

I installed Anaconda 

	 active environment : base
	active env location : C:\My_Program\Anaconda3p7
        shell level : 1
        user config file : C:\Users\aName\.condarc
     ulated config files : C:\Users\aName\.condarc
        conda version : 4.6.3
      conda-build version : 3.17.8
      python version : 3.6.8.final.0
      base environment : C:\My_Program\Anaconda3p7  (writable)
       channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                      https://conda.anaconda.org/anaconda-fusion/noarch
                      https://repo.anaconda.com/pkgs/main/win-64
                      https://repo.anaconda.com/pkgs/main/noarch
                      https://repo.anaconda.com/pkgs/free/win-64
                      https://repo.anaconda.com/pkgs/free/noarch
                      https://repo.anaconda.com/pkgs/r/win-64
                      https://repo.anaconda.com/pkgs/r/noarch
                      https://repo.anaconda.com/pkgs/msys2/win-64
                      https://repo.anaconda.com/pkgs/msys2/noarch
      package cache : C:\ProgramData\Anaconda3p7\pkgs
                      C:\Users\aName\.conda\pkgs
                      C:\Users\aName\AppData\Local\conda\conda\pkgs
      envs directories : C:\ProgramData\Anaconda3p7\envs
                      C:\Users\aName\.conda\envs
                      C:\Users\aName\AppData\Local\conda\conda\envs
           platform : win-64
         user-agent : conda/4.6.3 requests/2.21.0 CPython/3.6.8 Windows/7 Windows/6.1.7601
      administrator : False
         netrc file : None
       offline mode : False

I have installed numpy 1.12.0 in Anaconda prompt.

If I imported numpy in Anaconda prompt, it works well. 

But, if I import numpy in Eclipse/pydev, I got the above error.

If I import numpy in command-line but not in  Anaconda prompt, I got error:

      >>> import numpy
      Traceback (most recent call last):
      File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
      from . import multiarray
      ImportError: DLL load failed: The specified module could not be found.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\__init__.py", line 142, in <module>
      from . import add_newdocs
      File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
       from numpy.lib import add_newdoc
      File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
      from .type_check import *
      File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
      import numpy.core.numeric as _nx
      File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
      raise ImportError(msg)
     
     ImportError:
       Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy.
       If you're working with a numpy git repo, try `git clean -xdf` (removes all files not under version control).  Otherwise reinstall numpy.

I have tried most solutions online, but none of them work.

Could anyone help about this ? 

thanks

**Comment by mingwandroid** [comment]
> If I imported numpy in Anaconda prompt, it works well.

> But, if I import numpy in Eclipse/pydev, I got the above error.

You must always activate your environment. The `Anaconda Prompt` does this for you. You could launch `eclipse` from the `Anaconda Prompt`.
