### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by xylary** [ContinuumIO/anaconda-issues#1064]
Anaconda Navigator Update error:

Extra data: line 2 column 1 - line 252 column 1 (char 81 - 19660)

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.2.6', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
This has been fixed in the latest version

`conda update anaconda-navigator`

or

`conda update anaconda`
