### ISSUE TITLE
Incomplete installation on windows 10

### ISSUE THREAD

**Issue by MaximGi** [ContinuumIO/anaconda-issues#10642]
### Actual Behavior, steps to reproduce

Anaconda is installed using the latest "2018.12" installer on a Windows 10 machine.
I choose not to add Anaconda to PATH, as recommended.
After installation, following various tutorials, I open an Anaconda prompt : 
![image](https://user-images.githubusercontent.com/34157556/52916676-cf188880-32e2-11e9-996e-e72c86c80eb3.png)

Both first lines say "Specified path does not exist"
python, conda aren't working (not found) in the anaconda prompt (and windows cmd as well).
Python works after manually adding anaconda to PATH

### Solving attempts
After investigation, this looks like an issue already present in 5.0.1 version last year :
http://docs.anaconda.com/anaconda/user-guide/troubleshooting/#cannot-open-anaconda-prompt-after-installation
conda.exe is absent from the /script folder in the installation path, the installation seems to be incomplete.

I tried to reinstall several times :
- Clearing any remaining "conda" file anywhere on my system
- Disabling my antivirus
- rebooting between uninstall and install

##### Anaconda or Miniconda version:
2018.12, 64 bit

##### Operating System:
Windows 10

**Comment by jamesmyatt** [comment]
I have this too with 2018.12, 64 bit on Windows 10

**Comment by StrikerRUS** [comment]
The same. Even no `Anaconda3` folder in start menu after the installation. Seems that installer is completely broken. 😕

**Comment by MaximGi** [comment]
Solved this issue by  : 
- uninstalling Anaconda
- clearing all conda/anaconda related registry entries
- rebooting
- downloading and installing [WinPython](https://sourceforge.net/projects/winpython/files/latest/download)
