### ISSUE TITLE
Latest updates to PyQt

### ISSUE THREAD

**Issue by joonpark72** [ContinuumIO/anaconda-issues#1065]
after performing latest conda update --all, resulting in updates of conda-env and PyQt, etc...  breaks functionality for Spyder as well as Jupyter notebook...   I initially thought it had to to with migration of Windows 10 to the latest 1607 versrion but I see the same result after re-installation of Anaconda 4.1.1 (Python3).  Would you please look into this?  I need Spyder for few MOOCs I am taking currently and will just use the default installation of anaconda 4.1.1.

**Comment by ccordoba12** [comment]
@joonpark72, I'm about to do a new release of Spyder that will be compatible with PyQt. It'll be available on September 21.

In the meantime, please use the default Anaconda installation and don't perform any updates. Sorry for the inconveniences ;-)

**Comment by joonpark72** [comment]
Thank you .  One more question.  In general, should I just use conda update anaconda instead of conda update --all to avoid these problems all together?

**Comment by ccordoba12** [comment]
Yes, it's safer. `conda update anaconda` will give you a consistent set of packages, meant to work all together, while `conda update --all` tries to update everything to its latest version, which sometimes give you some inconsistencies.

**Comment by joonpark72** [comment]
One last thing, I had to install ipyparallel using conda install ipyparallel and it updated conda andn conda-env to the latest version which seems to have few bugs...   How can I go about installing the version of a package consistent with default state of anaconda installation so as to avoid updating dependencies???

**Comment by jorisvandenbossche** [comment]
Matplotlib also does not seem to work anymore (due to update of either matplotlib or qt). If I just install it in a fresh env:

```
joris@joris-XPS-13-9350:~$ conda create -n test-mpl python=3.5 matplotlib -c defaults
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/joris/miniconda3/envs/test-mpl:

The following NEW packages will be INSTALLED:

    cycler:           0.10.0-py35_0    
    dbus:             1.10.10-0        
    expat:            2.1.0-0          
    fontconfig:       2.11.1-6         
    freetype:         2.5.5-1          
    glib:             2.43.0-1         
    gst-plugins-base: 1.8.0-0          
    gstreamer:        1.8.0-0          
    icu:              54.1-0           
    jpeg:             8d-1             
    libffi:           3.2.1-0          
    libgcc:           5.2.0-0          
    libpng:           1.6.22-0         
    libxcb:           1.12-0           
    libxml2:          2.9.2-0          
    matplotlib:       1.5.3-np111py35_0
    mkl:              11.3.3-0         
    numpy:            1.11.1-py35_0    
    openssl:          1.0.2h-1         
    pip:              8.1.2-py35_0     
    pyparsing:        2.1.4-py35_0     
    pyqt:             5.6.0-py35_0     
    python:           3.5.2-0          
    python-dateutil:  2.5.3-py35_0     
    pytz:             2016.6.1-py35_0  
    qt:               5.6.0-0          
    readline:         6.2-2            
    setuptools:       27.2.0-py35_0    
    sip:              4.18-py35_0      
    six:              1.10.0-py35_0    
    sqlite:           3.13.0-0         
    tk:               8.5.18-0         
    wheel:            0.29.0-py35_0    
    xz:               5.2.2-0          
    zlib:             1.2.8-3          
...

joris@joris-XPS-13-9350:~$ act test-mpl
(test-mpl) joris@joris-XPS-13-9350:~$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joris/miniconda3/envs/test-mpl/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/joris/miniconda3/envs/test-mpl/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/joris/miniconda3/envs/test-mpl/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/home/joris/miniconda3/envs/test-mpl/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/home/joris/miniconda3/envs/test-mpl/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/joris/miniconda3/envs/test-mpl/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'
```

**Comment by jorisvandenbossche** [comment]
I suppose this is an issue with pyqt 5, as it also gives the same error when fixing the matplotlib version to 1.5.1 (but still using latest pyqt), but works fine when fixing pyqt to 4.x with matplotlib 1.5.3

**Comment by ajheaps** [comment]
I'm trying to do a conda build of a package to release a new version and get what I think is the same error.  As part of the build process is trying to install matplotlib 1.5.3 and this fails with 
ImportError: No module named PyQt4

Specifying the matplotlib version number as 1.5.1 in the meta.yaml file doesn't help here as I thought it might have and I still get the same error even though it is trying to do a very minor upgrade to    
 matplotlib:       1.5.1-np111py27_0

**Comment by ReimarBauer** [comment]
qt-5.6.0 seems to work fine with linux while it currently seems to be not complete for windows because of missing DLL

from PyQT4 import QTCore, QtGui 

gives on windows an import error DLL load failed

Related no windows build for latest mss on our atmo channel
[](https://bitbucket.org/wxmetvis/mss/issues/76/meta-needs-more-version-pinnings-or-fix-on)

**Comment by mingwandroid** [comment]
`from PyQT4 import QTCore, QtGui` implies that you had PyQt4 installed, not PyQt5? @ccordoba12, @goanpeca does that seem to be the case to you also or am I mistaken?

Please give detailed reproduction steps. I know a lot more about Qt itself than I do PyQt.

**Comment by goanpeca** [comment]
You might have one or the other installed, but an env variable might be defining which one to use....

**Comment by ccordoba12** [comment]
@ReimarBauer, what are you trying to do exactly on Windows? I don't understand your last comment, sorry :-)

**Comment by joonpark72** [comment]
Back to the original question, has the new version of spyder compatible with new PyQt5, yet?

**Comment by joonpark72** [comment]
When would it be safe to update using conda update --all?  I noticed it no longer calls for pyQt version 5.

**Comment by ccordoba12** [comment]
In a week, after Anaconda 4.2 is released, but it's better to just run `conda update anaconda`
