### ISSUE TITLE
PyQt5 breaks in conda environment

### ISSUE THREAD

**Issue by polwel** [ContinuumIO/anaconda-issues#10665]
When creating a new conda environment, installing PyQt with `pip`, the latter will fail to run.

It happens regardless of the PyQt version I try to install, or Python version (tested with 3.6 and 3.7).
Needless to say, it works perfectly fine on a vanilla (non-conda) install of python.

### Steps to Reproduce

In the Anaconda prompt:
```
> conda create -n pyqttest
> activate pyqttest
> conda install python
> pip install pyqt5
```
Then running
```
> python -c "from PyQt5 import QtCore"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

##### Anaconda or Miniconda version:
64 bit, tested with the various versions of `conda` I have at hand. 

##### Operating System:
Can confirm issue on Windows 7 and Windows 10.

##### `conda info`
```
     active environment : base
    active env location : C:\Users\welterp\AppData\Local\Continuum\miniconda3
            shell level : 1
       user config file : C:\Users\welterp\.condarc
 populated config files :
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\Users\welterp\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\welterp\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\welterp\.conda\pkgs
                          C:\Users\welterp\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\welterp\.conda\envs
                          C:\Users\welterp\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.4 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`
```
# packages in environment at C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\pyqttest:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
openssl                   1.1.1a               he774522_0    defaults
pip                       19.0.1                   py37_0    defaults
pyqt5                     5.12                     pypi_0    pypi
pyqt5-sip                 4.19.14                  pypi_0    pypi
python                    3.7.2                h8c8aaf0_2    defaults
setuptools                40.8.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
```

**Comment by polwel** [comment]
By the way: the same also happens when I try to install numpy instead of pyqt5.

**Comment by polwel** [comment]
Considering that this seems to affect many packages that rely on some Windows DLL, I am tempted to say that this is the same issue as described in #10651.

**Comment by csevast** [comment]
I have the same problem some days now and I am struggling to find out what is going on. I have a series of CMD scripts on Windows to automate the installation of MINICONDA, and the creation of my specific CONDA environments, which were all working perfectly. Now everything is collapsed.

I am using YML files for the updating and creation of CONDA environments, and I found out that the PIP dependencies are not installed because of potential empty spaces in CONDA produced temporary files which raises the following error:

(base) G:\My Drive\software\ericIDE>C:\dev\Miniconda3\python.exe C:\dev\Miniconda3\Scripts\pip-script.py --disable-pip-version-check install -r G:\My Drive\software\ericIDE\condaenv.c12vw9ri.requirements.txt
Invalid requirement: 'Drive\software\ericIDE\condaenv.c12vw9ri.requirements.txt'
It looks like a path. File 'Drive\software\ericIDE\condaenv.c12vw9ri.requirements.txt' does not exist.

**Comment by csevast** [comment]
Also, I face the the following issues as well, which I think that are connected.
#8321 
#8308

**Comment by csevast** [comment]
Both of the above mentioned issues are conda-issues and not anaconda-issues.

**Comment by polwel** [comment]
The newly updated Python builds fixed this issue. See #10651 for context.
