### ISSUE TITLE
opencv

### ISSUE THREAD

**Issue by Maneeshmohan1** [ContinuumIO/anaconda-issues#10669]
cv2.imshow is not working in opencv 
/home/travis/miniconda/conda-bld/conda_1486587069159/work/opencv-3.1.0/modules/highgui/src/window.cpp:281: error: (-215) size.width>0 && size.height>0 in function imshow

**Comment by mingwandroid** [comment]
Please do not ignore the issue template. We cannot help you without the information requested.

**Comment by jyotimannur** [comment]
OpenCV(4.2.0) ..\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by jyotimannur** [comment]
please help me to resolve this error
