### ISSUE TITLE
Issues with latest python package

### ISSUE THREAD

**Issue by Bezier89** [ContinuumIO/anaconda-issues#10666]
In the latest Windows Python 3.6 build (python=3.6.8=h9f7ef89_1), a new patch was added that attempts to modify the DLL search order in a way that directories on PATH are considered before system directories (0020-Add- CondaEcosystemModifyDllSearchPath.patch). It achieves that by calling SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS) and then explicitly adding all directories found on PATH to the search path using AddDllDirectory. However, this patch contains two flaws.  

The first problem is that this approach does not guarantee that the conda environment's Library\bin directory is added to the search path. This is not an issue if the environment is activated before invoking Python, as the activate step explicitly adds the Library\bin directory to PATH. However, there are use cases where python.exe is invoked directly without activating the environment first (e.g. using the environment in PyCharm 2018). This used to work just fine, as there is a second patch (0005-Win32-Ensure-Library-bin-is-in-os.environ- PATH.patch) which always adds Library\bin to PATH. Crucially, the code in this patch runs after the DLL search path has been set up, rendering it ineffective. To resolve the issue, the patches should be adjusted so that Library\bin is added to PATH *before* the DLL search path is modified using SetDefaultDllDirectories/AddDllDirectory.

  The second issue is that the patch removes leading/trailing semicolons and double semicolons (';;') from PATH before setting up the search path. However, an empty entry in PATH is considered equivalent to "current working directory". Since the modified DLL search path used after calling SetDefaultDllDirectories/AddDllDirectory does not include the current working directory, this effectively leaves no way of including the current working directory in the DLL search path.

**Comment by msarahan** [comment]
Please try the latest builds on the conda-canary channel.  We've disabled the new path search behavior by default.

CC @mingwandroid for awareness.

**Comment by Bezier89** [comment]
@msarahan Thanks. The builds on conda-canary (python=3.6.8=h9f7ef89_3, python=3.6.8=h9f7ef89_7) seem to fix this, at least by default. Haven't experimented with the new behavior.

**Comment by mingwandroid** [comment]
> The second issue is that the patch removes leading/trailing semicolons and double semicolons (';;') from PATH before setting up the search path. However, an empty entry in PATH is considered equivalent to "current working directory".

I didn't know that, but actually it doesn't really matter as the latest iteration of the patch adds CWD anyway (ok it can be toggled off with an env var).

The whole thing's disabled for now. We'll advise people running into DLL hell to enable this new code but it's certainly not without downsides.

**Comment by mingwandroid** [comment]
Closing, thanks for the report.
