### ISSUE TITLE
import is not working on freshly installed anaconda

### ISSUE THREAD

**Issue by pavan540** [ContinuumIO/anaconda-issues#1067]
i have just installed anacoda for windows 10.  I am trying to import padas using the following
import pandas as pd
I am getting an error message that import is not a recognized command. Python is working perfectly
![stackoverflow](https://cloud.githubusercontent.com/assets/8725835/18606412/db5b8fbc-7ccc-11e6-93b2-c9e74ebdcbfc.png)

**Comment by nehaljwani** [comment]
@pavan540 You have to type the following inside the python prompt. It is not a separate command.
```bash
(1067) C:\Users\nwani>python
Python 3.5.3 |Continuum Analytics, Inc.| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>>
```
