### ISSUE TITLE
Miniconda installers repo not updated for conda-4.6?

### ISSUE THREAD

**Issue by chrizzFTD** [ContinuumIO/anaconda-issues#10673]
Hi,

Miniconda installers for `conda-4.5.13+` from https://repo.anaconda.com/miniconda/ have not been uploaded yet. I'm wondering if we'll see `4.6+` coming up there or if there is another place where we should get installers from.

Thanks a lot!

### Actual Behavior

Can't get installers for `conda-4.6+` from https://repo.anaconda.com/miniconda/

### Expected Behavior

Ability to grab installers from https://repo.anaconda.com/miniconda/

**Comment by rolweber** [comment]
Let's be patient :-) The current Anaconda release is 2018.12, and Miniconda was updated in early January. We might get a new version with the next Anaconda refresh.

**Comment by soapy1** [comment]
We don't currently build installers for each release. But you can expect some fresh ones in the next couple of weeks.

**Comment by chrizzFTD** [comment]
Thanks for the update, it makes sense that installers come with Anaconda releases and not with every conda release, I was not aware of that. Happy to wait now!

**Comment by tjd2002** [comment]
Msarahan has info on this issue at newer (duplicate) issue #10811

**Comment by chrizzFTD** [comment]
I can see installers for 4.6.14 now on https://repo.anaconda.com/miniconda/
Thanks a lot!
