### ISSUE TITLE
Anaconda3 installation - destination folder contains following invalid character error

### ISSUE THREAD

**Issue by mohamedsuhaib** [ContinuumIO/anaconda-issues#10670]
### Actual Behavior

I am trying to install anconda3-2018.12 (32bit version) in window7 32bit. I am getting error like 'destination folder contains following invalid characterC:\user\name\Anaconda3. I have tried installing by downloading several times, installing in other locations. And also tried 'just me/ all users options', but it shows the same error.can some one find me a solution. By the way 'XXXX' is only combination of alphabets without any white space or special characters.

![anaconda3 error](https://user-images.githubusercontent.com/12045187/53288854-f9bb8300-37b3-11e9-8dcb-9de224e8ca41.PNG)

### Expected Behavior

Anaconda3 should install.

### Steps to Reproduce

Install Anaconda3-2018.12 (32bit version) in windows7 32bit machine.

**Comment by mohamedsuhaib** [comment]
The problem is solved by disabling Antivirus during installation.

**Comment by danyaal-shaikh** [comment]
I am facing the same issue, i dont hsve any antivirus software on my pc ( windows 64 bit ) . I even tried renaming my computer. I cannot install it cuz its showing the same error

**Comment by mohamedsuhaib** [comment]
Try to clean/delete the old anaconda installation folder before installing anaconda3. This thread is already closed, if the issue still persist then you can create a new thread quoting the same issue.

**Comment by danyaal-shaikh** [comment]
I've tried everything, even tried deleting all the temps can you please help me with this issue i really need a solution asap and i am new here so i dont know how to create a new thread or can you help me personally. I really need help

**Comment by abdohanfi** [comment]
how about changing your account name if its local or setup anaconda for all users if its an option
