### ISSUE TITLE
Navigator doesn't work right

### ISSUE THREAD

**Issue by ReyesZYX99** [ContinuumIO/anaconda-issues#1069]
Freshly installed Anaconda, but the Home page shows nothing and only installed packages can be shown while the descriptions are blank

the log viewer shows:
2016-09-17 22:56:12,612 - ERROR
    download_api._request_finished : 240
    ('Head Reply Error:', 99)

**Comment by goanpeca** [comment]
@ReyesZYX99 it seems there was some sort of error connection.

Do you have the latest version of Navigator?

Could you try to update it manually by going to the command prompt and typing:

`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
@ReyesZYX99 ?

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
