### ISSUE TITLE
arrow keys malfunctioning

### ISSUE THREAD

**Issue by tydlwav** [ContinuumIO/anaconda-issues#1072]
While in Anaconda python, the left right up down keys which supposed to be navigating through my code returns "^[A]" and stuff like that. Original python does not have the problem.

**Comment by nehaljwani** [comment]
`conda install readline` should solve this problem for you. If it doesn't, please share output for `conda list python`

**Comment by nehaljwani** [comment]
Share output for 
```bash
ldd $CONDA_PREFIX/lib/pythonX.Y/lib-dynload/readline.so #replace X.Y with the python version
```
