### ISSUE TITLE
Please update py-xgboost version 0.82

### ISSUE THREAD

**Issue by Ingvar-Y** [ContinuumIO/anaconda-issues#10722]
Hi!

Could you please update py-xgboost to 0.82? The last release in anaconda/py-xgboost channel is 0.80 so now it's 2 versions behind the latest release.

**Comment by Zelazny7** [comment]
Agreed, would be very nice to dump json models on Windows without having to build myself.

**Comment by Ingvar-Y** [comment]
I'm closing this since py-xgboost 0.90 was released 2 weeks ago.
