### ISSUE TITLE
flatbuffers package is installing CMake config in the wrong place

### ISSUE THREAD

**Issue by xhochy** [ContinuumIO/anaconda-issues#10731]
See my recent PR to `conda-forge`: https://github.com/conda-forge/flatbuffers-feedstock/pull/15 This adds `-DCMAKE_INSTALL_LIBDIR=lib` to the `cmake` commandline. This should be sufficient to fix this.

**Comment by xhochy** [comment]
I just realised that https://github.com/AnacondaRecipes/flatbuffers-feedstock/blob/master/recipe/meta.yaml is still at 1.7.1 and not 1.10, thus this recipe requires a general update to have at least the cmake-based build.

**Comment by nehaljwani** [comment]
1.10.0 is now available in defaults with the fix.
