### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sergiubuciumas** [ContinuumIO/anaconda-issues#1073]
I do have continuously issue with anaconda when I try to install packages, can you please help me understand what is wrong ?

The following errors occured:

None:
Dependency missing in current osx-64 channels: 
  - conda >=4.1.6 -> conda-env >=2.5.0

You can search for packages on anaconda.org with

    anaconda search -t conda conda-env

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Hi @sergiubuciumas what channels are you using?

**Comment by sergiubuciumas** [comment]
http://conda.anaconda.org and http://conda.anaconda.org/gurobi

Was working fine till upgraded OSX to version: 10.11.6 (15G1004), also can't even create environments in anaconda, tried with Python2.7 and 3.5 and same issue.

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by kalefranz** [comment]
http://conda.anaconda.org isn't a valid channel.  So the only packages that will be picked up are those in http://conda.anaconda.org/gurobi

**Comment by goanpeca** [comment]
Thanks, I missed the lack of channel!
