### ISSUE TITLE
Anaconda version missing in the installer name

### ISSUE THREAD

**Issue by knzudgt** [ContinuumIO/anaconda-issues#10756]
### Actual Behavior

I downloaded the [installer for Linux](https://www.anaconda.com/distribution/#linux), and the name of this file is 'Anaconda3-2018.12-Linux-x86_64.sh'.
Since I want to verify data integrity with MD5 and SHA-250, I wonder how I can I do that if I do not know the Anaconda version I am going to install: the above name does not contain it. [The page with the hashes](http://docs.anaconda.com/anaconda/install/hashes/lin-3-64/) for Linux is a list of installer names each one linking to the appropriate hashes. I tried the most recent, the one at the top but the hashes do not correspond to the ones generated by the installer I downloaded. How can I check data integrity? Where are the hashes corresponding to the Linux installer?

### Expected Behavior

The installer should have a name like Anaconda3-5.3.1-Linux-x86_64.sh, containing Anaconda version, so that the corresponding hashes should be checked from [the dedicated page](http://docs.anaconda.com/anaconda/install/hashes/lin-3-64/).

### Steps to Reproduce

Go to the [Linux download page](https://www.anaconda.com/distribution/#linux) and download the installer: the name of the installer is 'Anaconda3-2018.12-Linux-x86_64.sh'.

##### Operating System:

Ubuntu 18.04 LTS

**Comment by msarahan** [comment]
The hashes are missing (that's an issue) but the version number is 2018.12.  We moved to date-based versioning in that release, as noted in the release blog post: https://www.anaconda.com/anaconda-distribution-2018-12-released/

**Comment by msarahan** [comment]
Oh, I misspoke.  They are there, but because of version ordering in the default sorting, they're not on top.  Here's the page you're looking for: https://docs.anaconda.com/anaconda/install/hashes/Anaconda3-2018.12-Linux-x86_64.sh-hash/

CC @rrigdon we should see about a docs fix for this.
