### ISSUE TITLE
New Anaconda release?

### ISSUE THREAD

**Issue by Tagar** [ContinuumIO/anaconda-issues#10766]
What is the regular cadence for Anaconda releases?

We noticed latest release also changed naming convention (from eg. 5.3 to 2018.12).

https://docs.anaconda.com/anaconda/reference/release-notes/

Thanks.

**Comment by spara** [comment]
The release cadence for Anaconda Distribution is at the end of each quarter (March, June, Sept, December). The actual release date may slip a tiny bit as we try to get more features and fixes added and passing testing. We changed the naming convention to YYYY.MM from major.minor to remove versioning collisions and differentiate Anaconda Distribution from our enterprise product.

**Comment by Tagar** [comment]
Thank you for explaining this @spara 

Since Q1 is now over we will patiently wait for the imminent 2016.Q1 release )

https://docs.anaconda.com/anaconda/reference/release-notes/

Thanks again.
