### ISSUE TITLE
Navigator fails to start on latest Anaconda installer v 4.2 

### ISSUE THREAD

**Issue by sriaz2** [ContinuumIO/anaconda-issues#1076]

**Comment by goanpeca** [comment]
@ilanschnell, my bad I forgot to warn you on the recipe updates, but yes, we need to change the dependencies for the new version and add  **_license as a dependency and pin **pyqt=5.**

**Comment by ilanschnell** [comment]
@goanpeca `_license` is no longer part of the Anaconda installer.  Would it be possible to this an optional dependency?

**Comment by goanpeca** [comment]
@ilanschnell sure, but If we do this the License Manager dialog functionality is a bit useless and completely undiscoverable :-| for users, and the idea was to ease the " pain" of having users copy paste stuff into a hidden folder (.continuum)

@chdoig?

**Comment by chdoig** [comment]
We need it as required dependency for Navigator - Crystal already talked to @ilanschnell, @goanpeca and they are working on it.

**Comment by goanpeca** [comment]
:-) :+1:
