### ISSUE TITLE
Missing tensorflow package for linux x86-64 python 3.7

### ISSUE THREAD

**Issue by MaxNoe** [ContinuumIO/anaconda-issues#10779]
The tensorflow packages are missing for linux 64 bit, python 3.7.

Any reason for this?

**Comment by msarahan** [comment]
Tensorflow itself (not just our packages) has not supported python 3.7 until very recently. I think the 1.13.1 packages will support it finally. @jjhelmus please confirm.

**Comment by MaxNoe** [comment]
The packages for macos and windows already exist, only linux is missing

**Comment by jjhelmus** [comment]
Tensorflow 1.13.1 was the first release that supported Python 3.7.  We are still working on building 1.13.1 for linux, some changes to CUDA have proved difficult to resolve.

**Comment by MaxNoe** [comment]
Seems the package arrived, thx!
