### ISSUE TITLE
anaconda should simplify the making of CLI script

### ISSUE THREAD

**Issue by aster94** [ContinuumIO/anaconda-issues#10777]
### Actual Behavior
To run a script in python you have to:
1. add pythion to path
2. add .py files to pathext
3. define pythonpath
4. install py (which is not part of miniconda, see https://github.com/ContinuumIO/anaconda-issues/issues/149)
5. set python as default program to open .py files
6. finally you can run from terminal the `script`

Please note that these I am not saying that these step are diffucult to make, but just that the user doesn't have any idea that they have to be made, these 6, *simple*, steps took my hours to be understood and i am not the only one who is confused by these https://stackoverflow.com/questions/19917492/how-to-use-pythonpath

### Expected Behavior
a simpler way do to all these? maybe powerscript tool that manage all these on its own? it would ease the life of many people who are doing a fresh install of anaconda

### Steps to Reproduce
write a python script and try to run it from command line

##### Operating System:
windows 10

**Comment by msarahan** [comment]
What you are asking for here is a fundamental change to the Python language.  We don't define that.  IDE's, such as PyCharm, Spyder or VSCode can help you with developing and running your code.  When you are far enough along to want to ship your code somehow, I recommend looking into the cookiecutter project, which will give you templates for your project.  Between cookiecutter and development installs (``pip install -e <src dir>``), you should never need to touch PYTHONPATH.
