### ISSUE TITLE
[Request] Re-build keras-base for Python 3.7.x

### ISSUE THREAD

**Issue by Hoeze** [ContinuumIO/anaconda-issues#10798]
Please upload an updated keras-base package to support python 3.7.
Currently, it is necessary to install keras for python3.7 via pip.

**Comment by catphive** [comment]
+1 on this. Keras is in the repository, but it seems that recent builds are broken. It looks like they don't have a build label associate with them, so if you try to do "conda install keras" it hangs trying to solve the dependencies.

conda search -f keras
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Loading channels: done
# Name                       Version           Build  Channel             
keras                          1.1.1          py27_0  pkgs/free           
keras                          1.1.1          py34_0  pkgs/free           
keras                          1.1.1          py35_0  pkgs/free           
keras                          2.0.2          py27_0  pkgs/free           
keras                          2.0.2          py35_0  pkgs/free           
keras                          2.0.2          py36_0  pkgs/free           
keras                          2.0.5          py27_0  pkgs/free           
keras                          2.0.5          py35_0  pkgs/free           
keras                          2.0.5          py36_0  pkgs/free           
keras                          2.0.8  py27hd1b5a5b_0  pkgs/main           
keras                          2.0.8  py35h4bddecc_0  pkgs/main           
keras                          2.0.8  py36hc0b6f7c_0  pkgs/main           
keras                          2.1.2          py27_0  pkgs/main           
keras                          2.1.2          py35_0  pkgs/main           
keras                          2.1.2          py36_0  pkgs/main           
keras                          2.1.3          py27_0  pkgs/main           
keras                          2.1.3          py35_0  pkgs/main           
keras                          2.1.3          py36_0  pkgs/main           
keras                          2.1.4          py27_0  pkgs/main           
keras                          2.1.4          py35_0  pkgs/main           
keras                          2.1.4          py36_0  pkgs/main           
keras                          2.1.5          py27_0  pkgs/main           
keras                          2.1.5          py35_0  pkgs/main           
keras                          2.1.5          py36_0  pkgs/main           
keras                          2.1.6          py27_0  pkgs/main           
keras                          2.1.6          py35_0  pkgs/main           
keras                          2.1.6          py36_0  pkgs/main           
keras                          2.2.0               0  pkgs/main           
keras                          2.2.2               0  pkgs/main           
keras                          2.2.4               0  pkgs/main

**Comment by jjhelmus** [comment]
keras packages are now available for python 3.7
