### ISSUE TITLE
Update R-IRkernel version to `0.7`

### ISSUE THREAD

**Issue by poplav** [ContinuumIO/anaconda-issues#1080]
The [IRkernel](https://github.com/IRkernel/IRkernel/releases/tag/0.7) has recently made a new release to `0.7` from `0.6.1`.  Based on the [listed packages `0.6.1`](http://repo.continuum.io/pkgs/r/linux-64/) is the latest hosted now.  I am requesting an upgrade.

I am not familiar with how the packaging repo works, but it looks to be at [conda-recipes/r-packages/r-irkernel](https://github.com/conda/conda-recipes/blob/master/r-packages/r-irkernel/meta.yaml#L8) for reference.

This would be very much appreciated as our work in https://github.com/jupyter-incubator/declarativewidgets/pull/509 is dependent on this newer version and we want to finally be able to peg to a release.

cc @lbustelo

**Comment by mingwandroid** [comment]
I'm looking into doing this update for you now.

**Comment by mingwandroid** [comment]
This is done now.

**Comment by poplav** [comment]
@mingwandroid:
Are you sure this was done correctly?
I am inspecting the `0.7` release is there, but it looks to be `0.6`.
```
root@bdca471428cf:/home/jovyan/work# cat /opt/conda/lib/R/library/IRkernel/DESCRIPTION 
Package: IRkernel
Title: Native R kernel for the Jupyter notebook
Description: This package provides a native interface to the R kernel from the
    Jupyter notebook
Version: 0.6
Authors@R: c(person("Thomas", "Kluyver", role = c("aut", "cre"),
    email = "thomas@kluyver.me.uk"),
    person("Philipp", "A.", role = "aut",
    email = "flying-sheep@web.de"),
    person("Karthik", "Ram", role = "aut",
    email = "karthik.ram@gmail.com"))
Author: Thomas Kluyver <thomas@kluyver.me.uk>
Maintainer: Thomas Kluyver <thomas@kluyver.me.uk>
Depends: R (>= 3.0.1)
License: MIT + file LICENSE
LazyData: true
Encoding: UTF-8
Imports: repr, methods, evaluate (>= 0.5.4), IRdisplay, pbdZMQ (>=
        0.2-1), jsonlite (>= 0.9.6), uuid, digest
Collate: 'options.r' 'execution.r' 'help.r' 'installspec.r' 'kernel.r'
RoxygenNote: 5.0.1
Built: R 3.3.1; ; 2016-09-21 19:10:24 UTC; unix
```
Note how is says it was built with R `3.3.1`.
Previously I had R `3.2.2`
When I ran `conda install -c R r-irkernel=0.7` It showed packages were updated such as r-base which appears to have been, but the irkernel even though listed as `0.7` appears to be `0.6`.
Can you make sure nothing went wrong?  Something feels wonky, but I can't put my finger on it.

**Comment by mingwandroid** [comment]
Seems I forgot to update the git ref, so yes this is 0.6.1 pretending to be
0.7. I didn't take enough care here. I will fix it when I get back from
vacation. If you need it before then, building it for yourself  is not too
difficult.

Here is my incomplete attempt for reference:
https://github.com/mingwandroid/conda-recipes/commit/bdcc60b18bbc0ef54c83004c7dc7cb7b6168ee9f

**Comment by poplav** [comment]
@mingwandroid Thank you for confirming.  
It can wait till you get back from vacation.  Please let me know/comment back on the issue when `0.7` is up.  Appreciate it!

**Comment by poplav** [comment]
@mingwandroid any updates here?

**Comment by mingwandroid** [comment]
I will get on it right away.

**Comment by mingwandroid** [comment]
I've uploaded new `r-irkernel` packages now.

**Comment by poplav** [comment]
@mingwandroid , Thanks I confirmed it works now!

**Comment by mingwandroid** [comment]
Thanks for the feedback.
