### ISSUE TITLE
Latest Miniconda installer is only v4.5

### ISSUE THREAD

**Issue by stuarteberg** [ContinuumIO/anaconda-issues#10811]
The available [Miniconda installers](https://repo.anaconda.com/miniconda/) are not up-to-date with conda's releases.  The latest release of conda is 4.6.11, but the latest Miniconda installer is only at 4.5.12.

Can a Miniconda installer be published for conda-4.6, please?

Of course one can always update to 4.6 via `conda update -n base -c defaults conda`, but my own documentation will be easier to write if I can simply tell my users "download this". 😄 

cc @DocSavage

**Comment by msarahan** [comment]
coming up soon.  We're fixing some bugs from 4.6.11 and will do a miniconda for 4.6.12.

**Comment by jakirkham** [comment]
As there are now 4.6.14 installers, should this be closed?
