### ISSUE TITLE
Anaconda deletes python.exe after creating an environment

### ISSUE THREAD

**Issue by djuarezr** [ContinuumIO/anaconda-issues#10817]
### Actual Behavior

The main python.exe file disappears from the installation directory after creating a new environment. This makes executing conda.bat then useless, as it depends on the missing python.exe.

By the way, if anaconda installer fails to create menus, the installer does not even install a base environment.

### Expected Behavior

Being able to use conda.bat and the created environment after the environment is created.

### Steps to Reproduce

- Install anaconda with the latest installer.
- Create and environment.
- Check that the executable python.exe has disappeared from the install directory.
- Try to run conda.bat, it will fail saying "create process failed".

EDIT:

This command makes the issue appear:
`conda create -n py37 numpy pandas matplotlib scikit-learn tensorflow`

##### Anaconda or Miniconda version:

Latest anaconda and miniconda installers.

##### Operating System:

Windows 10 pro x64.

##### `conda info`

Cannot paste conda info as it installation always fails when the installer tries to create menus.

**Comment by juselec** [comment]
It works as expected in Windows 7 pro SP1 x64.

**Comment by juselec** [comment]
If the base environment is activated all the problems are gone and it works great. Also this seems to solve errors with openssl like #10454.
