### ISSUE TITLE
Python >3.7.0 OpenSSL - loads wrong dll

### ISSUE THREAD

**Issue by MattiKloepper** [ContinuumIO/anaconda-issues#10823]
### Actual Behavior

Trying to `import ssl;` fails on my windows system for Python >V3.7.0 with `ImportError: DLL load failed: The specified procedure could not be found`.
Trying the same command with Python 3.7.0 works fine.

This happens because Python finds some older openSSL DLLs in my system directories instead of the ones supplied with the openssl package. Python searches through the following directories:

  - `<conda-dir>\dlls\`
  - `c:\windows\system32\`
  - `c:\windows\system\`
  - `c:\windows\`
  - `<conda-dir>\`
  - `<conda-dir>\library\mingw-w64\bin\`
  - `<conda-dir>\library\usr\bin\`
  - `<conda-dir>\library\bin\`

The openssl libraries of the openssl package were located under `<conda-dir>\dlls\` with python 3.7.0 but are located under `<conda-dir>\library\bin\` with python 3.7.3.

If I remove the openssl dlls from my system directory python finds the right ones and `import ssl;` works fine.

My %PATH% environment variable has listed the `<conda-dir>\library\bin\` way before the system directories. Seems there is something wrong with the search order in python. Are the system directories hardcoded?

### Expected Behavior

Import should work without error.

### Steps to Reproduce

1. Install OpenSSL 1.0 in Windows.

1.1 Install Miniconda v4.5.11 (includes python 3.7.0)
1.2 activate base environment
1.3 run `python -m conda update openssl`
1.4 deactive and reactivate base environment
1.3 run `python -c "import ssl;` => works fine
1.4 run `python -m conda update python`
1.5 deactive and reactivate base environment
1.6 run `python -c "import ssl;` => throws the error reported above
1.7 run `python -m conda python=3.7.0 --offline` (offline since online does not work anymore due to ssl error)
1.8 deactive and reactivate base environment
1.9 run `python -c "import ssl;` => works fine

2. Uninstall / delete Miniconda v4.5.11

3. Install Miniconda v4.5.12 (includes python 3.7.3)
3.1 activate base environment
3.2 run `python -c "import ssl;` => throws the error reported above

##### Anaconda or Miniconda version:

v4.5.11 / v4.5.12

##### Operating System:

Windows 10 1809 with openSSL v1.1.0 installed.

##### `conda info`

<details>

```
     active environment : base
    active env location : C:\Users\matth\Miniconda3.11
            shell level : 1
       user config file : C:\Users\matth\.condarc
 populated config files : C:\Users\matth\.condarc
          conda version : 4.6.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : C:\Users\matth\Miniconda3.11  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\matth\Miniconda3.11\pkgs
                          C:\Users\matth\.conda\pkgs
                          C:\Users\matth\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\matth\Miniconda3.11\envs
                          C:\Users\matth\.conda\envs
                          C:\Users\matth\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.11 requests/2.19.1 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at C:\Users\matth\Miniconda3.11:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.11                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.6.1            py37h7a1dbc1_0    defaults
idna                      2.7                      py37_0    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
openssl                   1.1.1b               he774522_1    defaults
pip                       10.0.1                   py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.18                     py37_1    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.3                h8c8aaf0_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.19.1                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                40.2.0                   py37_0    defaults
six                       1.11.0                   py37_1    defaults
sqlite                    3.27.2               he774522_0    defaults
urllib3                   1.23                     py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.31.1                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults

```

</details>

**Comment by mingwandroid** [comment]
Please try with conda 4.6.12 which you can install from the `conda-canary` channel via:

`conda update -c conda-canary conda`.

**Comment by MattiKloepper** [comment]
@mingwandroid Running conda 4.6.12 does not change anything with the described problem :-( 
`import ssl;` still tries to use my outdated openSSL dlls from the system directory. Correct libraries are located under `<conda-dir>\library\bin`. `<conda-dir>\dll` does not contain the dlls.

**Comment by msarahan** [comment]
With things in your system directory, yeah, it'll break.  You're depending on PATH, but system comes before PATH.  See https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed for a workaround.  Issue there is MKL, but the same stuff holds for your situation.

**Comment by msarahan** [comment]
PS: DLL load order on Windows: https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications

**Comment by MattiKloepper** [comment]
Ah ok. I thought PATH comes before system folders.
I am just wondering why `<conda-bin>\dlls` is searched first?
Maybe `<conda-bin>\library\bin` could be placed in the search order together with `<conda-bin>\dlls`?

**Comment by mingwandroid** [comment]
>  <conda-bin>\library\bin

This directory should not appear on PATH. Python manages that internally.

If you update your python you can set the CONDA_ENABLE_DLL_SEARCH_NOTIFICATION env var and PATH will take precedence over System32.

**Comment by MattiKloepper** [comment]
@mingwandroid `<condadir>\library\bin` is included into the path by activating the environment.

Setting the mentioned env var qualifies as a workaround for the time being. But I see that will break too, once another openSSL installation puts itself into the PATH env variable.
Why not search `<conda-bin>\library\bin` directly as you do with `<conda-dir>\dlls`?

**Comment by mingwandroid** [comment]
> Setting the mentioned env var qualifies as a workaround for the time being. But I see that will break too, once another openSSL installation puts itself into the PATH env variable.

If you use conda 'properly'this shouldn't be the case. Activation puts conda at the from of PATH.

> Why not search <conda-bin>\library\bin directly as you do with <conda-dir>\dlls?

Because the search in dlls is a thing that python does to locate some dlls.  We've decided to take a different approach, on that works for more software than just python and that is careful (hopefully) management of PATH.

**Comment by MattiKloepper** [comment]
> If you use conda 'properly'this shouldn't be the case. Activation puts conda at the from of PATH.

But what happens if another application is changing the path (e.g. putting itself in the front) after the activation?

> Because the search in dlls is a thing that python does to locate some dlls it is aware of. We've decided to take a different approach, one that works for more software than just python and that is careful (hopefully) management of PATH.

No offense meant but as I see it this design decision makes the stability of python programs depending on the well behaviour of other programs out of your control. I would always vote for searching all your own library folders first.

At the very least I propose to include the location of the unsuccesfully loaded library into the error message. That would have saved me quite some time debugging with process monitor ;-)

**Comment by mingwandroid** [comment]
> But what happens if another application is changing the path 

> No offense meant but as I see it this design decision makes the stability of python programs depending on the well behaviour of other programs out of your control. I would always vote for searching all your own library folders first.

What do you think other programs are able to do to the PATH environment variable as stored in the running instance of the Python interpreter? They can do *nothing* to it (without taking extraordinary, platform specific, usually security-restricted measures). This concern is however very valid when talking about other Python modules messing with PATH as they sometimes do, but usually that's done in a very controlled way pointing to a directory which contains only a few very specifically named DLLs.

> At the very least I propose to include the location of the unsuccesfully loaded library into the error message

The error message comes from Windows itself. I am not on the WIndows development team so I cannot help with this. Please suggest it to them if you wish though. I'd definitely add my support.

**Comment by MattiKloepper** [comment]
> What do you think other programs are able to do to the PATH environment variable as stored in the running instance of the Python interpreter? They can do nothing to it

That holds true, but I had something else on my mind. I'm not able to test it out currently since I'm on my mobile but what about something along the following lines:
- start a CMD console
- run some python script, that should work for sure
- activate conda environment
- running another, not very well behaving program that fiddles with path
- running some python script, that might fail now due to changed path

Or am I meant to (re)activate the environment before every start of the python interpreter? Sorry if I'm sounding ignorant but I just started to work with python due to my employers requirements. I'm much more confident with .NET ;-)

> The error message comes from Windows itself. I am not on the WIndows development team so I cannot help with this.

I thought you were catching and rethrowing that error in your import code and might be able to enrich it with some information on what you tried to do when the error occurred.

**Comment by mingwandroid** [comment]
> running another, not very well behaving program that fiddles with path

Once this program exits, its fiddles with path are lost to the world. Please read up about `source` (on POSIX) `call` on MSDOS/Windows and execution contexts.

**Comment by mingwandroid** [comment]
> I thought you were catching and rethrowing that error in your import code and might be able to enrich it with some information on what you tried to do when the error occurred

You cannot catch information that is not presented to you. DLLs can autoload other DLLs, so the one which actually failed to load is not something generally knowable by the caller. Only Windows knows that, and it doesn't let tell. Or maybe I don't know how to ask it?

**Comment by MattiKloepper** [comment]
Of course you are right with both points. Ways to modify the path variable in a way to cause problems are quite improbable to happen.
Sure you could only enrich the message of the error occuring while directly loading a dll. That might not be the dll really cauing the problem in the first place.

To bring this - quite interesting - discussion to an end:
Thanks for pointing me to the solution with the env variable and your insights into your design decisions.

Best,
Matti

**Comment by honglei** [comment]
So, I use the following code to fix this problem.
```python
import os
import sys
def fix_os_path():
    '''
      将前期python环境中的Library\bin目录放入PATH的搜索路径中去 
    '''
    added_search_path = r"Library\bin"
    dll_path = os.path.join(sys.prefix, added_search_path) 
    path = os.environ['PATH']
    if dll_path not in path:
        os.environ['PATH'] = f"{dll_path};{path}"  
```

**Comment by skyshy0707** [comment]
> With things in your system directory, yeah, it'll break. You're depending on PATH, but system comes before PATH. See https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed for a workaround. Issue there is MKL, but the same stuff holds for your situation.


MKL-files What is it? What files should be deleted?
