### ISSUE TITLE
Navigator not added to classic menu indicator on Ubuntu 16.04

### ISSUE THREAD

**Issue by dartdog** [ContinuumIO/anaconda-issues#1082]
No items on the menu, nor for Spyder or Orange.. the root python and the py27 items are added... all start fine from command line... (sometimes hard to remember so I like menus!)

**Comment by goanpeca** [comment]
Hi @dartdog thanks for your comment

---

@ilanschnell, @csoja ?

**Comment by ccordoba12** [comment]
This needs to be solved in the `menuinst` package.

**Comment by Gabriel-p** [comment]
Still no work on this bug? It's pretty annoying to install the app and not be able to launch it afterwards. The fix can not be all that complicated, can it?

**Comment by ccordoba12** [comment]
Please submit a pull request for it against the menuinst package to support adding menus on Linux.

**Comment by Gabriel-p** [comment]
This `menuist` package?

> Menuinst is currently only supported on Windows. Legacy code exists for Linux and OS X - use at your own risk. It may mess up your menus.

Why would you use a package that is only supported on Windows in your cross-platform app?

**Comment by ccordoba12** [comment]
menuinst is the right place to make this happen. It has missing functionality for Linux and macOS and (unfortunately) none of us has had the time to fix it, sorry.

**Comment by bilderbuchi** [comment]
:+1: to this issue! Relevant issue in the menuinst tracker is ContinuumIO/menuinst#48

**Comment by goanpeca** [comment]
@bilderbuchi indeed, I will be doing the work to update Osx/Linux support

**Comment by atb2dmtriy** [comment]
do not see workaround here, so this might help:
Anaconda Navigator
"Create launcher" and point it to "/home/user/.anaconda/navigator/scripts/anaconda-navigator-restart.sh"

Spyder
"Create launcher" and point it to "/home/user/anaconda3/bin/spyder3"

**Comment by cromat** [comment]
@jabaa [Here](https://image.ibb.co/iVHMDT/anaconda_icon.png) is the icon.

**Comment by jabaa** [comment]
Thank you. It would be great, if it was in the anaconda project. I looked for an icon but I only found navigator.ico. It's not usable for xfce starter.

**Comment by fbidu** [comment]
Just dropping by to say that I also spent some time looking for the official icon in order to create a menu launcher and was not able to find. I +1 the idea of adding the file supplied by @cromat to the official distribution.

**Comment by iam-mhaseeb** [comment]
I solved it with this solution:
```
nano ~/.local/share/applications/anaconda.desktop
[Desktop Entry]
Name=Anaconda
Comment=anaconda-navigator
Exec=/usr/bin/env PATH=/home/haseeb/anaconda3/bin/:$PATH /home/haseeb/anaconda3/bin/anaconda-navigator
Icon=/home/haseeb/anaconda3/lib/python3.6/site-packages/anaconda_navigator/static/images/logos/continuum_twitter.jpg
Terminal=false
Type=Application
StartupNotify=true
```
