### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by minifly** [ContinuumIO/anaconda-issues#1083]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - 7za ==920
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.6', 'version': '1.2.1', 'python': '3.5.2', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 63 Stepping 2, GenuineIntel', 'platform': 'win-64', 'language': 'zh_CN', 'qt': '4.8.7', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Hi @minifly the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type:

`conda update anaconda-navigator`
