### ISSUE TITLE
graphviz dot not finding /usr/lib/libltdl.7.dylib (from libtool?)

### ISSUE THREAD

**Issue by rvsasseen** [ContinuumIO/anaconda-issues#1084]
I'm not sure if this is the right place to post this; if not please suggest where to post. I'm on a new Mac, which is a new platform for me, and this is my first experience with Anaconda. I suspect the problem might be with Anaconda's libtool installation.

I installed graphviz via MacPorts, and installed (python) graphviz and pydot-ng from Navigator. I'm trying to graph a decision tree from sklearn.tree.DecisionTreeClassifier, using code adapted from http://scikit-learn.org/stable/modules/tree.html (pydot variation). When I call graph.write_pdf("graphviz.pdf") I get the following error:

InvocationException: Program terminated with status: -5. stderr follows: dyld: Library not loaded: /usr/lib/libltdl.7.dylib
  Referenced from: /Users/sasseen/anaconda/bin/dot
  Reason: image not found

I get the same error when I try to run graphviz's "dot" from the command line, passing the temp file that was created by the python code (pdb showed cmdline = "['/Users/sasseen/anaconda/bin/dot', '-Tpdf', '/var/folders/v_/fnbmzf710w7_f_cgkb0hq0b40000gp/T/tmpYuqKAU']"). In fact, there is no file /usr/lib/libltdl.7.dylib. I didn't have libtool installed in Anaconda, so I installed it with Navigator, but that file still doesn't exist. My best guess is that libtool should be installing it.

I can use the version of graphviz dot that came on my system and it works. /opt/local/bin/dot -Tpdf /var/folders/v_/fnbmzf710w7_f_cgkb0hq0b40000gp/T/tmpYuqKAU > graphviz.pdf works fine. If I run "otool -l" on the two dot exes, the system one is using /opt/local/lib/libltdl.7.dylib, while the Anaconda dot is trying to use the nonexistent /usr/lib/libltdl.7.dylib.

MacPorts reports it has graphviz @2.38.0_3+pangocairo+x11 and libtool @2.4.6_2, while looking at ~/anaconda/pkgs, that has graphviz-2.38.0-2 and libtool-2.4.2-0.

**Comment by lxkain** [comment]
I'm in the same boat. After install graphviz via conda install graphviz, I then execute $dot, and I get:

dyld: Library not loaded: /usr/lib/libltdl.7.dylib
  Referenced from: /Users/kain/anaconda/bin/dot
  Reason: image not found
Abort trap: 6

**Comment by goanpeca** [comment]
@rvsasseen I think you should install graphviz from anaconda (navigator) as well.

**Comment by goanpeca** [comment]
@ccordoba12, @mingwandroid ?

**Comment by bryevdv** [comment]
@csoja is there a GA date or target release for builds on OS X 10.9? (IIRC that is the issue?)

**Comment by ccordoba12** [comment]
I don't know what happened to Graphviz. I created good recipes for conda-forge but haven't had time to move them to our internal repo :-/

I don't know if @mingwandroid have had time to do it.

**Comment by mingwandroid** [comment]
I'm pretty busy with client work at present. I won't be able to look at this for a few weeks I think.

**Comment by bryevdv** [comment]
@ccordoba12 can you clarify: do the graphvix packages on conda-forge work? What platforms? I'd like too re-enable some parts of the Bokeh docs that rely on it. If there are working packages on conda-forge for linux I could use those.

**Comment by csoja** [comment]
@ilan The rebuild of graphviz on OSX that you did ~ November 10th - which version of OSX was that built on?  I had a note that this was done - though it looks like we did not close the loop and close the issue.

**Comment by nehaljwani** [comment]
`graphviz=2.38.0=2` had this problem:
```
(1084) somebuildmachine:~ nwani$ otool -L /Users/nwani/m2u/envs/1084/bin/dot | grep liblt
        /usr/lib/libltdl.7.dylib (compatibility version 10.0.0, current version 10.2.0)
```
`graphviz=2.38.0` (build number > 2) don't have this problem.
