### ISSUE TITLE
AssertionError: SRE module mismatch

### ISSUE THREAD

**Issue by Srinivasphyton** [ContinuumIO/anaconda-issues#10842]
Hi

I am trying to install restaurant bot using python3.7 and anaconda in my windows 10...
I am following this URL https://github.com/RasaHQ/starter-pack-rasa-stack
while I am running following command
 **make train-nlu**
facing this issue

      0 [main] make 3604 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
python bot.py train-nlu
make: python: Command not found
Makefile:24: recipe for target `train-nlu' failed
make: *** [train-nlu] Error 127

How to resolve this issue... can anyone suggest me!!

I have installed make(MINGW64)
And saw all the related issues.. but still facing same problem...!

Thanks in Advance

**Comment by Srinivasphyton** [comment]
Can anyone reply on the above issue...

**Comment by csoja** [comment]
This is the wrong issue tracker to report this issue - it sounds like you should be raising this issue on the issue tracker for the github repo of the URL you are following.  This is tracker is for conda packages - particularly those built by Anaconda, Inc - and the Anaconda installer itself.
