### ISSUE TITLE
segmentation fault: 11 on conda in terminal on Mac OS X (Navigator is not launching)

### ISSUE THREAD

**Issue by jonathan-liono** [ContinuumIO/anaconda-issues#1085]
This afternoon I tried to include opencv into anaconda environment through the following command: 

> conda install -c menpo opencv3=3.1.0

Then it asked me to update both conda and conda-env in order to proceed. As a result, everything broke down, for example, opening navigator leads to nothing (which I think it crashes due to this issue). 

And I tried applying conda update conda. However the response I got was "segmentation fault: 11". Maybe this is related to latest update of conda and conda-env? 

The following screenshot refers to "conda list --revisions" results: 

![image](https://cloud.githubusercontent.com/assets/5291441/18743473/8bac0bc0-80fc-11e6-9d5f-e4b5921d6f57.png)

The above screenshot basically points out the latest revision that I have done today. As you can see, conda was updated to 4.2.7 while conda-env was updated to 2.6.0.

**Comment by jonathan-liono** [comment]
I have resolved the issue by updating anaconda pip packages manually through the following (as mentioned in [here](http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip)): 

> pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U



Basically, all packages were updated. However, this may be related to qt & qtpy problems as mentioned here: [https://github.com/ContinuumIO/anaconda-issues/issues/1099](https://github.com/ContinuumIO/anaconda-issues/issues/1099)

**Comment by YYdeemo** [comment]
//
//  main.c
//  rrun
//
//  Created by Apple on 2017/5/9.
//  Copyright © 2017年 yin. All rights reserved.
//

#include<stdio.h>
#include <stdlib.h>

#define MAX 10

struct task_struct
{
    char name[10];           /*进程名称*/
    int number;              /*进程编号*/
    int come_time;           /*到达时间*/
    int begin_time;          /*开始运行时间*/
    int run_time;            /*运行时间*/
    int end_time;            /*运行结束时*/
    int round_time;          /*周转时间*/
    int priority;            /*优先级*/
    int order;               /*运行次序*/
    int rest_slice;          /*剩余时间片数*/
    int status;              /*run_flag调度标志*/
}tasks[MAX];
struct que{
    int task;
    int prio;
    int slice;
    struct que *front;
    struct que *rear;
    struct que *next;
    
};

int counter;/*实际进程个数*/
//int fcfs();      /*先来先服务*/
//int ps();        /*优先级调度*/
//int sjf();      /*短作业优先*/
int pstt();
//int tt();
int input();
int pinput();    /*进程参数输入*/
int poutput();   /*调度结果输出*/
int clear();     /*初始化数据*/
struct que *Addprocess();
struct que *creatQue();
int ifnewprocess();
int nextque();
struct que *adnew();

int main()
{
    int i,option;
    input();
/*
    clear();
    printf("\n\nFCFS:\n");
    fcfs();
    poutput();
    
    clear();
    printf("\n\nSJF  :\n");
    sjf();
    poutput();
    
    clear();
    printf("\n\nHRRN :\n");
    hrrn();
    poutput();
    
    clear();
    printf("\n\nPS  :\n");
    ps();
    poutput();
    
    clear();
    printf("\n\nTT    :\n");
    tt();
    poutput();
*/
    //clear();
    printf("\n\nPSTT  :\n");
    pstt();
    poutput();
}

int clear()
{
    int i;
    for(i=0;i<counter;i++)
    {
        tasks[i].begin_time=0;
        tasks[i].end_time=0;
        tasks[i].order=0;
        tasks[i].round_time=0;
        tasks[i].status=0;
        tasks[i].rest_slice=tasks[i].run_time;
    }
    return 0;
}

int pinput() 		/*进程参数手工输入   */
{
    int i;
    printf("please input the process counter:");
    scanf("%d",&counter);
    
    for(i=0;i<counter;i++)
    {
        printf("************************** %d\n",i+1);
        printf("Name     :    ");
        scanf("%s",tasks[i].name);
        printf("Come_time:");
        scanf("%d",&tasks[i].come_time);
        printf("Run_time :");
        scanf("%d",&tasks[i].run_time);
        printf("Priority :");
        scanf("%d",&tasks[i].priority);
        tasks[i].begin_time=0;
        tasks[i].end_time=0;
        tasks[i].order=0;
        tasks[i].round_time=0;
        tasks[i].status=0;
        tasks[i].rest_slice=tasks[i].run_time;
    }
    return 0;
}

int input() 		/*进程参数从文件data.in中读取   */
{
    int i;
    FILE *input = fopen("data.in", "r");
    printf("the process counter:");
    fscanf(input, "%d", &counter);
    printf("%d\n",counter);
    printf("name   come_time  run_time  priority\n");
    
    for(i=0;i<counter;i++)
    {
        fscanf(input, "%s %d %d %d", tasks[i].name,&tasks[i].come_time,&tasks[i].run_time,&tasks[i].priority);
        printf("%s %9d %9d %9d\n", tasks[i].name,tasks[i].come_time,tasks[i].run_time,tasks[i].priority);
        tasks[i].begin_time=0;
        tasks[i].end_time=0;
        tasks[i].order=0;
        tasks[i].round_time=0;
        tasks[i].status=0;
        tasks[i].rest_slice=tasks[i].run_time;
    }
    fclose(input);
    return 0;
}
/*
 1.实现队列优先级排序选择
 2.实现进程判断
 3.实现进程执行输出
*/


int pstt()     /*多级反馈轮转法*/
{
    //定义三个队列
    struct que *newprocess = creatQue();
    struct que *timeprocess = creatQue();
    //QUE *IOprocess = creatQue();
    adnew(newprocess);
    int i = 0;
    int time = 0;
    //QUE *p = malloc(sizeof(QUE));
    ifnewprocess(newprocess,timeprocess,tasks,i,time,1);
    free(newprocess);
    free(timeprocess);
    return 0;
}

int ifnewprocess(struct que *newprocess,struct que *timeprocess,struct task_struct tasks[],int i,int time,int num){
    newprocess->slice = 1;
    int j=0;
    if (time<tasks[i].come_time) {
                    time++;
        nextque(newprocess,timeprocess,tasks,i,time,num);
    }
    if(time>=tasks[newprocess->front->task].come_time){//有新进程加入
        
        i++;
        //开始执行newprocess 内的进程
                
        j = newprocess->front->task;
        //修改进程的参数
        if(newprocess->slice>tasks[j].run_time){//时间片足够该进程运行结束
            
            tasks[j].begin_time = time;//开始运行时间
            tasks[j].end_time = tasks[j].begin_time+tasks[j].run_time;//结束时间
            tasks[j].round_time = tasks[j].end_time-tasks[j].come_time;//周转时间
            tasks[j].rest_slice = 0;//剩余时间片
            tasks[j].status=0;//调度标志 已完成
            
            /*if(){
                //是否有IO中断
            }*/
            time = time+tasks[j].run_time;
            num = num+1;
            //输出
            printf("Process p%d------No.%d slice",j,i);
            //跳转一下进程
            /*while (time<tasks[i].come_time) {
                time++;
            }
            nextprocess(newprocess,timeprocess,tasks,i,j,time,num);
             */
            
            newprocess->front = newprocess->front->next;
            newprocess->front = newprocess->front->next;
            if(newprocess!=NULL){
                j = newprocess->front->task;
                ifnewprocess(newprocess,timeprocess,tasks,i,time,num);
            }else{
                
                nextque(newprocess,timeprocess,tasks,i,j,time,num);
            }
            
        }else{//时间不够该进程运行结束
            tasks[j].begin_time = time;//开始运行时间
            tasks[j].end_time = tasks[j].begin_time+newprocess->slice;//结束时间
            //tasks[j].round_time = tasks[j].come_time-tasks[j].begin.time;//周转时间
            tasks[j].rest_slice = tasks[j].run_time-newprocess->slice;//剩余时间片
            tasks[j].status=1;//未完成
            num = num+1;
            time = time+newprocess->slice;//记录现在的时间

            //进程进入timeprocess队列
            Addprocess(timeprocess, j);
            printf("Process p%d-------------No.%d slice",j,num);
            printf("time=%d",time);
            ifnewprocess(newprocess,timeprocess,tasks,i,time,num);
        }
        
    }else{//无 则进入下一队列
        timeprocess->front = timeprocess->front->next;
        timeprocess->front = timeprocess->front->next;
        j = timeprocess->front->task;
        nextque(newprocess,timeprocess,tasks,i,j,time,num);
        
    }
    return 0;
}
/*int nextprocess(QUE *newprocess,QUE *timeprocess,*Tasks[],int i ,int j,int time,int num){
    
    if(timeprocess->slice>tasks[j].run_time){//时间片足够该进程运行结束
        
        tasks[j].begin_time = time;//开始运行时间
        tasks[j].end_time = tasks[j].begin_time+tasks[j].run_time;//结束时间
        tasks[j].round_time = tasks[j].end_time-tasks[j].come_time;//周转时间
        tasks[j].rest_slice = 0;//剩余时间片
        tasks[j].status=0;//调度标志
        
        if(){
         //是否有IO中断
         }
        time = time+tasks[j].run_time;
        num = num+1;
        //输出
        printf("Process p%d------No.%d slice",j,num);
        //跳转一下进程
        timeprocess = timeprocess->next;
        if(timeprocess!=NULL){
            j = timeprocess->task;
            nextprocess(newprocess,timeprocess,tasks,i,j,time,num);
        }else{
            while (time<tasks[i].come_time) {
                time++;
            }
            nextprocess(newprocess,timeprocess,tasks,i,j,time,num);
        }
        
    }else{//时间不够该进程运行结束
        tasks[j].begin_time = time;//开始运行时间
        tasks[j].end_time = tasks[j].begin_time+timeprocess->slice;//结束时间
        //tasks[j].round_time = tasks[j].come_time-tasks[j].begin.time;//周转时间
        tasks[j].rest_slice = tasks[j].run_time-timeprocess->slice;//剩余时间片
        tasks[j].status=1;//未完成
        num = num+1;
        //?????????????????????????
        timeprocess->rear = j;
        time = time+timeprocess->slice;//记录现在的时间
        printf("Process p%d------No.%d slice",j,num);
        ifnewprocess(newprocess,timeprocess,tasks,i,time,num);
            }

    
}
*/
int nextque(struct que *newprocess,struct que *timeprocess,struct task_struct tasks[],int i,int j,int time,int num){
    timeprocess->slice = 2;
    
    if(timeprocess->front==NULL){
        ifnewprocess(newprocess,timeprocess,tasks,i,time+1,num);
    }
    if(timeprocess->slice>tasks[j].rest_slice){//时间片足够该进程运行结束
        tasks[j].round_time =tasks[j].end_time-tasks[j].come_time;//周转时间
        tasks[j].end_time = time+tasks[j].end_time-tasks[j].begin_time;//结束时间
        tasks[j].rest_slice = 0;//剩余时间片
        tasks[j].status=i;//调度标志
        
        /*if(){
            //是否有IO中断
        }*/
        time = time+tasks[j].run_time;
        num = num+1;
        //输出
         printf("Process p%d------No.%d slice",j,i);
        //跳转一下进程
        //判断下一节点是否为空
        timeprocess->front = timeprocess->front->next;
        timeprocess->front = timeprocess->front->next;
        if(timeprocess!=NULL){
            j = timeprocess->front->task;
            nextque(newprocess,timeprocess,tasks,i,j,time,num);
        }else{
            ifnewprocess(newprocess,timeprocess,tasks,i,time,num);
        }
        

    }else{//时间不够该进程运行结束
        tasks[j].begin_time = time;//开始运行时间
        tasks[j].end_time = tasks[j].begin_time+timeprocess->slice;//结束时间
        //tasks[j].round_time = tasks[j].come_time-tasks[j].begin.time;//周转时间
        tasks[j].rest_slice = tasks[j].run_time-timeprocess->slice;//剩余时间片
        tasks[j].status=i;
        num = num+1;
        time = time+timeprocess->slice;//记录现在的时间
         printf("Process p%d------No.%d slice",j,i);
        ifnewprocess(newprocess,timeprocess,tasks,i,time,num);
        
    }

    return i;
}
struct que *Addprocess(struct que *p,int i)
{
    struct que *q;
    q->task = i;
    p = p->rear;
    p->rear = q;
    return p;
}
struct que *adnew(struct que *q){
    
    int i=0;
    q->front = 0;
    for(i = 1;i<=4;i++){
        q->next = q->rear;
        q->rear->task = i;
    }
    return q;
    
}

struct que *creatQue(){
    struct que *q;
    q = (struct que* )malloc(sizeof(struct que));
    if(!q){
        printf("flow");
        return NULL;
    }
    q->rear = NULL;
    q->front = NULL;
    q->next = q->front;
    return q;
}

int poutput() /*调度结果输出*/
{
    int i;
    float turn_round_time=0,w=0;
    printf("name  come  run   priority  end  order  round  \n");
    for(i=0;i<counter;i++)
    {
        turn_round_time+=tasks[i].round_time;
        w+=(tasks[i].round_time/tasks[i].run_time);
        printf("%3s  %3d  %4d   %5d    %4d  %4d  %4d\n",tasks[i].name,tasks[i].come_time,tasks[i].run_time,tasks[i].priority,tasks[i].end_time,tasks[i].order,tasks[i].round_time);
        
    }
    printf("average_turn_round_time=%5.2f\n",turn_round_time/counter);
    /*printf("weight_average_turn_round_timer=%5.2f\n",w/counter);*/
    return 0;
}

/* i have a problem, segmentation fault: 11  in terminal on Mac OS X
