### ISSUE TITLE
Creating an environment fails with error: post-link failed for package defaults

### ISSUE THREAD

**Issue by NktSH** [ContinuumIO/anaconda-issues#10854]
Hello everyone! It's my first time on github and I apologize in advance for mistakes. I've installed the latest version of anaconda and tried to create environment . But I face consntant failes with the same error. 
Preparing transaction: done
Verifying transaction: done
Executing transaction: / DEBUG menuinst_win32:__init__(199): Menu: name: 'Anacon
da${PY_VER} ${PLATFORM}', prefix: 'C:\anaconda\envs\hghg', env_name: 'hghg', mod
e: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\anaconda\pythonw.exe, args
are ['C:\\anaconda\\cwp.py', 'C:\\anaconda\\envs\\hghg', 'C:\\anaconda\\envs\\hg
hg\\pythonw.exe', 'C:\\anaconda\\envs\\hghg\\Scripts\\spyder-script.py']
- DEBUG menuinst_win32:create(323): Shortcut cmd is C:\anaconda\python.exe, args
 are ['C:\\anaconda\\cwp.py', 'C:\\anaconda\\envs\\hghg', 'C:\\anaconda\\envs\\h
ghg\\python.exe', 'C:\\anaconda\\envs\\hghg\\Scripts\\spyder-script.py', '--rese
t']
\ ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while
 installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0

running your command again with `-v` will provide additional information
location of failed script: C:\anaconda\envs\hghg\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

failed
ERROR conda.core.link:_execute(568): An error occurred while installing package
'defaults::qt-5.9.7-vc14h73c81de_0'.
LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0

running your command again with `-v` will provide additional information
location of failed script: C:\anaconda\envs\hghg\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0

running your command again with `-v` will provide additional information
location of failed script: C:\anaconda\envs\hghg\Scripts\.qt-post-link.bat
==> script messages <==
<None>
Can you please tell me what's wrong with that? Thank you very much!
Nikita

**Comment by csoja** [comment]
Can you provide the command that gave you this error - the exact steps to be able to reproduce it?  Also, the issue template requests some critical information needed in order to provide any useful help.  i.e. OS, output of conda info and conda list --show-channels.

**Comment by NktSH** [comment]
Thank you for help! I've solved this problem by reinstalling windows. But if someone also has the same issue:
OS - windows 8.1
Anaconda 3
The command was: conda create -n hghg python=3.7 numpy scipy matplotlib spyder

**Comment by NeoKun004** [comment]
i've the same problem , i installed pytorch then tried to install matplotlib , i got the error 
RROR conda.core.link:_execute_post_link_actions(658): An error occurred while
installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0

**Comment by wolfni** [comment]
..the same problem for me

**Comment by markotoplak** [comment]
Seems to also be a problem for some users of Orange, but the development team was unable to reproduce it: biolab/orange3#3819
