### ISSUE TITLE
Security problem: Conflicting dependencies of arrow-cpp 0.11.1 and libtiff 4.0.10

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#10866]
The latest versions of `arrow-cpp` (via `pyarrow`) and `libtiff` depend on different versions of `zstd`:

`conda create -n dependency-clash python pyarrow=0.11.1 libtiff=4.0.10`
```txt
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - libtiff=4.0.10 -> zstd[version='>=1.3.7,<1.3.8.0a0']
  - pyarrow=0.11.1 -> arrow-cpp[version='>=0.11.1,<0.12.0a0'] -> zstd[version='>=1.3.3,<1.3.4.0a0']
```

This problem was introduced with an update of libtiff, the previous version 4.0.9 did not yet depend on zstd. However, libtiff 4.0.10 fixes several CVEs, see the [release notes](http://www.simplesystems.org/libtiff/v4.0.10.html).

Could you please re-build `arrow-cpp` with compatibility for `zstd` 1.3.7, so it can be used alongside the security fixes in `libtiff`?

**Comment by rolweber** [comment]
There's also `libarchive` 3.3.3 which depends on  `zstd` 1.3.3.

**Comment by rolweber** [comment]
Similar to `libarchive` 3.3.3, which since build 4 depends on `zstd` 1.3.7 rather than 1.3.3.

**Comment by rolweber** [comment]
Folks, this dependency clash forces users of arrow to stay on a version of libtiff with know security vulnerabilities. Is there any chance to raise awareness for this problem?

**Comment by rolweber** [comment]
Thanks!

**Comment by forrestwaters** [comment]
arrow-cpp 0.11.1 has been rebuilt with support for zstd 1.3.7

**Comment by rolweber** [comment]
Great, thank you very much! :-)
