### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vidhimodi116** [ContinuumIO/anaconda-issues#10872]
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda2
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda2'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda2"

```
## System information
```
platform: win-32
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by csoja** [comment]
This is a permissions error.  It looks like you installed it for all users with Admin privileges, but now you are attempting to run it as a user.  You either need to run Navigator as an Admin, reinstall it for your user, or use Anaconda Prompt to run conda and create an environment in a directory you do have access to.
