### ISSUE TITLE
Multiple start menu folders

### ISSUE THREAD

**Issue by sho-87** [ContinuumIO/anaconda-issues#1087]
I installed anaconda by following these steps on Windows 10:
1. Install Anaconda 4.1.1 (Python 2.7 64 bit) using the installer from the website
2. `conda update conda`
3. `conda update anaconda`

After step 1 a folder appears in my start menu called "Anaconda2 (64-bit)". After completing step 3, another folder shows up called "Anaconda (64-bit)"

They seem to contain (slightly) different things:

Anaconda (64-bit):
- Ipython notebook, QTconsole
- Spyder
- Launcher

Anaconda2 (64-bit):
- Anaconda navigator (doesnt start, see #1086)
- Ipython
- Jupyter notebook, QTConsole
- Spyder

None of the links in the Anaconda2 folder seem to work when you click them

Are both of these folders meant to exist or can I safely delete one of them? What is the purpose of multiple folders?

**Comment by ijstokes** [comment]
Community member reported similar on Anaconda ML: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/mE_ZEB_xrf8
