### ISSUE TITLE
Anaconda Navigator not opening in Windows 10

### ISSUE THREAD

**Issue by suhaskvaithal** [ContinuumIO/anaconda-issues#10880]
Anaconda Navigator stopped opening in windows 10.  

### I have tried to open using:
1) start->Anaconda3(64-bit)-> Anaconda Navigator
2) start->Anaconda3(64-bit)->Anaconda Prompt

### Following are the logs:

C:\Users\Varun>conda info

     active environment : None
       user config file : C:\Users\Varun\.condarc
       populated config files : C:\Users\Varun\.condarc
          conda version : 4.6.14
    conda-build version : 3.17.6
         python version : 3.6.7.final.0
       base environment : C:\Users\Varun\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Varun\Anaconda3\pkgs
                          C:\Users\Varun\.conda\pkgs
                          C:\Users\Varun\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Varun\Anaconda3\envs
                          C:\Users\Varun\.conda\envs
                          C:\Users\Varun\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.7 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

### I have also tried the following:
**C:\Users\Varun>conda update conda**

     Collecting package metadata: done

     Solving environment: |
     The environment is inconsistent, please check the package plan carefully
     The following packages are causing the inconsistency:

      defaults/win-64::dynd-python==0.7.2=py35_0
      done

       All requested packages already installed.

**C:\Users\Varun>conda update anaconda-navigator**

      Collecting package metadata: done
      Solving environment: \
      The environment is inconsistent, please check the package plan carefully
      The following packages are causing the inconsistency:

      defaults/win-64::dynd-python==0.7.2=py35_0
      done

      All requested packages already installed.

Kindly advice.

**Comment by csoja** [comment]
Do you use dynd?  If not, perhaps try uninstalling dynd-python? It looks like you have the most recent version of conda and anaconda-navigator.  Can you trying starting anaconda-navigator from the Anaconda Command Prompt?  (where you tried _conda update conda_, try _anaconda-navigator_ )  What errors show in the Window?  (There is not yet enough information to help diagnose the problem.)

**Comment by csoja** [comment]
No response from user.  Closing.  Will reopen if the user responds with the requested information.

**Comment by tosintriplet** [comment]
My Anaconda Navigator stopped opening on windows 10 and getting error while using quantiphyse on Python . how can I go about these . THanks 
![error on quantiphyse](https://user-images.githubusercontent.com/47099095/59250721-a97d0980-8c5a-11e9-8646-593c19853169.PNG)
![error on quantiphyse](https://user-images.githubusercontent.com/47099095/59250778-cdd8e600-8c5a-11e9-8964-517d2b2b58ae.PNG)
