### ISSUE TITLE
(OSX) `anaconda-navigator` produces "ImportError: No module named 'PySide'"

### ISSUE THREAD

**Issue by p-i-** [ContinuumIO/anaconda-issues#1089]
Launcher stalled. Googled and learned it has been superseded by navigator.  So:
```
    conda install anaconda-navigator
    conda update --all
```
Help said navigator would put icon on my desktop but it didn't. So I try to launch it from the commandline:

```
    anaconda-navigator
```

However, this fails:

> Traceback (most recent call last):
>   File "/Users/pi/anaconda/lib/python3.5/site-packages/qtpy/__init__.py", line 119, in <module>
>     from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
> ImportError: No module named 'PySide'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/pi/anaconda/bin/anaconda-navigator", line 4, in <module>
>     import anaconda_navigator.app.main
>   File "/Users/pi/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 16, in <module>
>     from qtpy.QtCore import QCoreApplication, QEvent, QObject, Qt
>   File "/Users/pi/anaconda/lib/python3.5/site-packages/qtpy/__init__.py", line 125, in <module>
>     raise PythonQtError('No Qt bindings could be found')
> qtpy.PythonQtError: No Qt bindings could be found

What's going wrong here? The obvious step is to install `PySide` but that begs the question "Why isn't it working out-of-the-box?"  -- it suggests that something is wrong at a deeper level.

If I do try to install PySide:

```
    sudo pip install pyside
```

> Collecting pyside
>   Downloading PySide-1.2.4.tar.gz (9.3MB)
>     100% |████████████████████████████████| 9.3MB 96kB/s 
>     Complete output from command python setup.py egg_info:
>     only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-nurirlcr/pyside/
>

**Comment by goanpeca** [comment]
Hi @p-i- we are having some issues with some packages updates.

You should do:

`conda install anaconda-navigator pyqt=4.* qt=4.* -f`

**Comment by p-i-** [comment]
Ok, that produces:

> The following NEW packages will be INSTALLED:
>     anaconda-navigator: 1.2.3-py35_0 
> 
> The following packages will be UPDATED:
>     pyqt:               4.11.4-py35_3 --> 4.11.4-py35_4
> 
> The following packages will be DOWNGRADED due to dependency conflicts:
>     qt:                 5.6.0-0       --> 4.8.7-4      
> 
> <...blablabla...>
> Linking packages ...
> CondaOSError: OS error: failed to link (src='/Users/pi/anaconda/pkgs/qt-4.8.7-4/mkspecs/default', dst='/Users/pi/anaconda/mkspecs/default', type=3, error=FileExistsError(17, 'File exists'))

I'm guessing the conflict is with my existing version of navigator I just installed.  But doing `conda uninstall anaconda-navigator` first doesn't change the error.

How to proceed?

(PS fwiw My eventual goal is to get an IPython Notebook running inside PyCharm, so that I can single step through Python code).

**Comment by goanpeca** [comment]
@p-i- while the new anaconda distribution is released in a couple of days you can do the following.

Go to the command line and type

`conda install anaconda-navigator pyqt=4.* qt=4.* qtpy=1.0`

Please let me know if this works for you

**Comment by goanpeca** [comment]
The new release of Anaconda should fix these issues

**Comment by manueldeljesus** [comment]
I have updated anaconda today and I am having this very same problem. Do I need to install PySide from pip still?

**Comment by goanpeca** [comment]
Could you type `conda info` and `conda list` and paste the output here?

**Comment by manueldeljesus** [comment]
conda info:

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.3
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/manuel/anaconda  (writable)
    default environment : /Users/manuel/anaconda
       envs directories : /Users/manuel/anaconda/envs
          package cache : /Users/manuel/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

**Comment by manueldeljesus** [comment]
conda list

# packages in environment at /Users/manuel/anaconda:
#
_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
abstract-rendering        0.5.1               np111py35_0
accelerate                2.3.0               np111py35_3
accelerate_cudalib        2.0                           0
alabaster                 0.7.9                    py35_0
anaconda                  custom                   py35_0
anaconda-client           1.5.1                    py35_0
anaconda-navigator        1.2.3                    py35_0
appnope                   0.1.0                    py35_0
appscript                 1.0.1                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
basemap                   1.0.7               np111py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_0
blaze-core                0.9.0                    py35_0
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
bottlechest               0.7.1                    py35_0
bottleneck                1.1.0               np111py35_0
cffi                      1.8.3                    py35_0
chardet                   2.3.0                    py35_0
click                     6.6                      py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
conda                     4.2.9                    py35_0
conda-build               2.0.3                    py35_0
conda-env                 2.6.0                         0
conda-manager             0.4.0                    py35_0
configobj                 5.0.6                    py35_0
configparser              3.5.0b2                  py35_0
cryptography              1.5.2                    py35_0
cudatoolkit               7.5                           0
curl                      7.45.0                        0
cycler                    0.10.0                   py35_0
cython                    0.24.1                   py35_0
cytoolz                   0.8.0                    py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
flask                     0.11.1                   py35_0
freetype                  2.5.5                         1
futures                   3.0.3                    py35_0
gdal                      2.0.0               np111py35_3
geos                      3.4.2                         0
get_terminal_size         1.0.0                    py35_0
glueviz                   0.8.2                    py35_1
greenlet                  0.4.10                   py35_0
gsl                       2.1                           1
h5py                      2.6.0               np111py35_1
hdf4                      4.2.11                        0
hdf5                      1.8.16                        0
icu                       54.1                          0
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
iopro                     1.7.2              np111py35_p0
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython-notebook          4.0.4                    py35_0
ipython-qtconsole         4.0.1                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jbig                      2.1                           0
jdcal                     1.3                      py35_0
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
joblib                    0.9.4                    py35_0
jpeg                      8d                            2
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
kealib                    1.4.5                         2
krb5                      1.13.2                        0
launcher                  1.0.0                         3
libdynd                   0.7.2                         0
libgcc                    4.8.5                         1
libgdal                   2.0.0                         4
libnetcdf                 4.4.0                         1
libpng                    1.6.22                        0
libspatialindex           1.8.5                         1    ioos
libtiff                   4.0.6                         2
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2
llvmlite                  0.11.0                   py35_0
lxml                      3.6.4                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.1               np111py35_0
mistune                   0.7.3                    py35_1
mkl                       11.3.3                        0
mkl-rt                    11.1                         p0
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
ncurses                   5.9                           8
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.26.0              np111py35_0
numexpr                   2.6.1               np111py35_0
numpy                     1.11.2                   py35_0
odo                       0.5.0                    py35_1
openpyxl                  2.4.0                    py35_0
openssl                   1.0.2j                        0
orange-app                1.0.1                    py35_0
orange3                   3.3.6                    py35_0
pandas                    0.19.0              np111py35_0
path.py                   8.2.1                    py35_0
patsy                     0.4.1                    py35_0
pcre                      8.39                          0
pep8                      1.7.0                    py35_0
pexpect                   4.0.1                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    3.4.1                    py35_0
pip                       8.1.2                    py35_0
pkginfo                   1.3.2                    py35_0
ply                       3.9                      py35_0
proj4                     4.9.2                         0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
ptyprocess                0.5.1                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.19.5.3                 py35_0
pyflakes                  1.3.0                    py35_0
pygments                  2.1.3                    py35_0
pyopenssl                 16.0.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      4.11.4                   py35_3
pyqtgraph                 0.9.10                   py35_1
pytables                  3.2.2               np111py35_4
pytest                    3.0.3                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
python.app                1.2                      py35_4
pytz                      2016.7                   py35_0
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.0                         0
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_0
qtpy                      1.1.2                    py35_0
r                         3.2.2                         0    r
r-base                    3.2.2                         0    r
r-boot                    1.3_17                r3.2.2_0a    r
r-class                   7.3_14                r3.2.2_0a    r
r-cluster                 2.0.3                 r3.2.2_0a    r
r-codetools               0.2_14                r3.2.2_0a    r
r-foreign                 0.8_66                r3.2.2_0a    r
r-gdata                   2.17.0                r3.2.2_0a    r
r-gtools                  3.5.0                 r3.2.2_0a    r
r-kernsmooth              2.23_15               r3.2.2_0a    r
r-lattice                 0.20_33               r3.2.2_0a    r
r-mass                    7.3_45                r3.2.2_0a    r
r-matrix                  1.2_2                 r3.2.2_0a    r
r-mgcv                    1.8_9                 r3.2.2_0a    r
r-nlme                    3.1_122               r3.2.2_0a    r
r-nnet                    7.3_11                r3.2.2_0a    r
r-recommended             3.2.2                  r3.2.2_0    r
r-rpart                   4.1_10                r3.2.2_0a    r
r-spatial                 7.3_11                r3.2.2_0a    r
r-survival                2.38_3                r3.2.2_0a    r
readline                  6.2                           2
redis                     3.2.0                         0
redis-py                  2.10.5                   py35_0
requests                  2.11.1                   py35_0
rope                      0.9.4                    py35_1
rpy2                      2.7.0              py35r3.2.2_0    r
rtree                     0.8.2                    py35_2    ioos
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.18                np111py35_0
scipy                     0.18.1              np111py35_0
seaborn                   0.7.1                    py35_0
setuptools                27.2.0                   py35_0
shapely                   1.5.16                   py35_0
simplegeneric             0.8.1                    py35_1
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snakeviz                  0.4.1                    py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.8                    py35_0
sphinx_rtd_theme          0.1.9                    py35_0
spyder                    2.3.8                    py35_1
spyder-app                2.3.8                    py35_0
sqlalchemy                1.1.0                    py35_0
sqlite                    3.13.0                        0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
terminado                 0.6                      py35_0
tk                        8.5.18                        0
toolz                     0.8.0                    py35_0
tornado                   4.4.2                    py35_0
traitlets                 4.3.1                    py35_0
ujson                     1.35                     py35_0
unicodecsv                0.14.1                   py35_0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
xerces-c                  3.1.4                         0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
xz                        5.2.2                         0
yaml                      0.1.6                         0
zeromq                    4.1.3                         0
zlib                      1.2.8                         3

**Comment by goanpeca** [comment]
Ok so there is an error there

```
pyqt______________________4.11.4___________________py35_3
qt________________________5.6.0_________________________0
```

They should both be 5 or 4 not a mix, so I suggest the following

`conda remove orange3 orange-app`
`conda install qt=5 pyqt=5`

**Comment by manueldeljesus** [comment]
Problem fixed. Thank you very much.

**Comment by goanpeca** [comment]
Awesome :-), glad to hear it is fixed!

**Comment by quanganhct** [comment]
Hello I have the same error like that. Just download Anaconda yesterday, and I'm using Mac OS 10.6. pyqt v 5.6.0 and qt 5.6.0. There isn't any orange. So how do I fix this ?

**Comment by colby-j-wise** [comment]
Getting the same error like that. Tried following steps as above but unsure where dependency error is - How do I fix?

Using Mac OS 10.11.6 - pyqt v 5.6 and qt 5.6. No orange. 

Conda info below:

`
 platform : osx-64
      conda version : 4.3.22
   conda is private : False
  conda-env version : 4.3.22
conda-build version : 2.1.16
     python version : 3.5.3.final.0
   requests version : 2.14.2
   root environment : /Users/colbywise/anaconda  (writable)
default environment : /Users/colbywise/anaconda
   envs directories : /Users/colbywise/anaconda/envs
                      /Users/colbywise/.conda/envs
      package cache : /Users/colbywise/anaconda/pkgs
                      /Users/colbywise/.conda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/osx-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/osx-64
                      https://repo.continuum.io/pkgs/pro/noarch
        config file : /Users/colbywise/.condarc
         netrc file : None
       offline mode : False
         user-agent : conda/4.3.22 requests/2.14.2 CPython/3.5.3 Darwin/15.6.0 OSX/10.11.6    
            UID:GID : 501:20`

**Comment by MelissaLaurino** [comment]
Also getting the same issue with Mac OSX qt and pyqt 5.9
