### ISSUE TITLE
Tried to 'conda install' something from my channel and ended up deleting Anaconda-Navigator

### ISSUE THREAD

**Issue by allenea** [ContinuumIO/anaconda-issues#10896]
### Actual Behavior

Something in the conda library I tried to make is really messed up....

Tried to install a package... Ended up losing my Anaconda-Navigator and no way to add it. I just reset the env since my conda info had produced None. Unfortunately I do not have all of the output when I tried to do the conda install. Is there any way I can revert it back without having to totally uninstall everything and reinstall?

Then side bar.... what the heck caused this so I can make sure that it doesn't happen to someone else?

### Expected Behavior

Installed package pydatpicture from my channel. 

This is my first time trying to put something onto conda... so I really don't know what I am doing here lol....

### Steps to Reproduce

conda install -c allenea pydatpicture

Since then I did the following...

  479  conda list --revisions
  481  conda list
  482  conda update all
  483      conda update --all
  484  conda install anaconda
  485  conda update -n base -c defaults conda
  486  anaconda-navigator
  487  conda install --revision
  488  conda list --revisions
  489  conda install --revision 51
  490  conda install --revision 49
  491  conda install --revision 50
  492  conda info
  493  conda list
  495  conda activate
  496  conda info --envs
  498  conda init bash
  499  exit
  501  conda activate /Users/allenea/anaconda3/
  502  conda info

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by YiboTang** [comment]
I have the same problem here, for two months. And  cant use anaconda navigator or jupyternotebook since then.

**Comment by csoja** [comment]
Can you paste in the output for conda info and conda list --show-channel-urls?  
You'll need either a terminal (Linux/macOS) or Anaconda Prompt (Windows)
Also, it is helpful if you attempt to start anaconda-navigator from a terminal or Anaconda Prompt and copy in whatever error you see when it won't start.

**Comment by allenea** [comment]
I was able to get the navigator back.... but Now I am trying to get spyder back....




Preparing transaction: done
Verifying transaction: done
Executing transaction: - WARNING conda.core.link:run_script(1098): pre-unlink script failed for package defaults::qt-5.9.5-h02808f3_0
consider notifying the package maintainer
failed
ERROR conda.core.link:_execute(568): An error occurred while uninstalling package 'defaults::qt-5.9.5-h02808f3_0'.
PermissionError(1, 'Operation not permitted')
Attempting to roll back.

Rolling back transaction: done


-------
conda info


wifi-roaming-128-4-72-160:~ allenea$ conda info

     active environment : None
            shell level : 0
       user config file : /Users/allenea/.condarc
 populated config files : /Users/allenea/.condarc
          conda version : 4.6.14
    conda-build version : 3.10.5
         python version : 3.6.8.final.0
       base environment : /Users/allenea/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/allenea/anaconda3/pkgs
                          /Users/allenea/.conda/pkgs
       envs directories : /Users/allenea/anaconda3/envs
                          /Users/allenea/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Darwin/18.5.0 OSX/10.14.4
                UID:GID : 504:20
             netrc file : None
           offline mode : False



------
 conda list --show-channel-urls



wifi-roaming-128-4-72-160:~ allenea$ conda list --show-channel-urls
# packages in environment at /Users/allenea/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.6.14                   py36_0    defaults
anaconda-navigator        1.9.7                    py36_0    defaults
anaconda-project          0.8.2            py36h9ee5d53_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
arm_pyart                 1.9.2                    py36_0    conda-forge
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.3                    py36_0    defaults
astropy                   3.0.2            py36h917ab60_1    defaults
attrs                     18.1.0                   py36_0    defaults
babel                     2.5.3                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h1de35cc_1    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.1.3                    py36_0    defaults
blosc                     1.14.3               hd9629dc_0    defaults
bokeh                     0.12.16                  py36_0    defaults
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1            py36hbd380ad_0    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.1.23                     0    defaults
cairo                     1.14.12              he6fea26_5    conda-forge
cartopy                   0.17.0          py36h929c6f0_1004    conda-forge
certifi                   2019.3.9                 py36_0    defaults
cffi                      1.11.5           py36h342bebf_0    defaults
cftime                    1.0.1            py36h7eb728f_0    conda-forge
chardet                   3.0.4            py36h96c241c_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.5.3                    py36_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
conda                     4.6.14                   py36_0    defaults
conda-build               3.10.5                   py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.4.2            py36ha12b0ac_0    defaults
curl                      7.63.0            ha441bb4_1000    defaults
cycler                    0.10.0                     py_1    conda-forge
cython                    0.28.2           py36h1de35cc_0    defaults
cytoolz                   0.9.0.1          py36h1de35cc_0    defaults
dask                      0.17.5                   py36_0    defaults
dask-core                 0.17.5                   py36_0    defaults
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                    py36_0    defaults
distributed               1.21.8                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.5                hb8e80ba_0    defaults
fastcache                 1.0.2            py36h1de35cc_2    defaults
filelock                  3.0.4                    py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.4                    py36_0    defaults
fontconfig                2.13.1               hce039c3_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
g2clib                    1.6.0                         5    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopy                     1.18.1                     py_0    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.4.3             hce09ea4_1000    conda-forge
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.0            py36h1de35cc_0    defaults
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
glob2                     0.6              py36h94c9186_0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36hf9c35bd_2    defaults
greenlet                  0.4.13           py36h1de35cc_0    defaults
gsw                       3.2.1            py36h470a237_2    conda-forge
h5netcdf                  0.6.2                      py_0    conda-forge
h5py                      2.7.1            py36ha8ecd60_2    defaults
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.2               hfa1e0ec_1    defaults
hdfeos2                   2.20                 h7a90ae3_0    conda-forge
hdfeos5                   5.1.16               h647bee3_2    conda-forge
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.6              py36h8628d0a_1    defaults
imageio                   2.3.0                    py36_0    defaults
imagesize                 1.0.0                    py36_0    defaults
intel-openmp              2018.0.0                      8    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   6.4.0                    py36_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.2.1                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jasper                    1.900.1              hff1ad4c_5    conda-forge
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.12.0                   py36_1    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.4.0            py36h79cf704_0    defaults
jupyterlab                0.32.1                   py36_0    defaults
jupyterlab_launcher       0.10.5                   py36_0    defaults
kealib                    1.4.9                h0bee7d0_2    conda-forge
keyring                   16.0.0                   py36_0    defaults
kiwisolver                1.0.1           py36h04f5b5a_1002    conda-forge
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcurl                   7.63.0            h051b688_1000    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libdap4                   3.19.1               h18059cb_1    conda-forge
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgdal                   1.11.2                        1    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1                h5e45101_3    conda-forge
libpng                    1.6.34               he12f830_0    defaults
libpq                     11.1                 h051b688_0    defaults
libprotobuf               3.6.0                hd9629dc_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.9                hcb84e12_1    defaults
libuuid                   2.32.1               h470a237_2    conda-forge
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvmlite                  0.23.1           py36hc454e04_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.3.0           py36h7166777_1000    conda-forge
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                3.0.1                      1001    conda-forge
matplotlib-base           3.0.1           py36hebca740_1001    conda-forge
mccabe                    0.6.1            py36hdaeb55d_0    defaults
metpy                     0.9.1                    py36_0    conda-forge
mistune                   0.8.3            py36h1de35cc_1    defaults
mkl                       2018.0.3                      1    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
more-itertools            4.1.0                    py36_0    defaults
mpc                       1.0.3                h7a72875_5    defaults
mpfr                      3.1.5                h711e7fd_2    defaults
mpmath                    1.0.0            py36hf1b8295_2    defaults
msgpack-python            0.5.6            py36h04f5b5a_0    defaults
multipledispatch          0.5.0                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.1                  h0a44026_0    defaults
netcdf4                   1.4.1            py36h08833f9_0    defaults
networkx                  2.1                      py36_0    defaults
nltk                      3.4                      py36_1    anaconda
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.5.0                    py36_0    defaults
numba                     0.38.0           py36h1702cab_0    defaults
numexpr                   2.6.5            py36h057f876_0    defaults
numpy                     1.15.4           py36h6a91979_0    defaults
numpy-base                1.15.4           py36h8a80b8c_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0                h316dc23_3    conda-forge
openpyxl                  2.5.3                    py36_0    defaults
openssl                   1.1.1b               h1de35cc_1    defaults
owslib                    0.17.1                     py_0    conda-forge
packaging                 17.1                     py36_0    defaults
pandas                    0.23.0           py36h1702cab_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
parso                     0.2.0                    py36_0    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   11.0.1                   py36_0    defaults
pathlib2                  2.3.2                    py36_0    defaults
patsy                     0.5.0                    py36_0    defaults
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.5.0                    py36_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    5.3.0           py36hbddbef0_1000    conda-forge
pint                      0.8.1                      py_1    conda-forge
pip                       18.1                     pypi_0    pypi
pixman                    0.34.0               h470a237_3    conda-forge
pkginfo                   1.4.2                    py36_1    defaults
pluggy                    0.6.0            py36hb1d0581_0    defaults
ply                       3.11                     py36_0    defaults
pooch                     0.1.1                    py36_0    conda-forge
poppler                   0.61.1               h4d7e492_4    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     5.2.0             h1de35cc_1001    conda-forge
prompt_toolkit            1.0.15           py36haeda067_0    defaults
protobuf                  3.6.0            py36h0a44026_0    defaults
psutil                    5.4.5            py36h1de35cc_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.5.3                    py36_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h1de35cc_8    defaults
pycurl                    7.43.0.2         py36ha12b0ac_0    defaults
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pykdtree                  1.3.1           py36h917ab60_1002    conda-forge
pykrige                   1.4.0            py36h52257b0_1    conda-forge
pylint                    1.8.4                    py36_0    defaults
pynio                     1.5.2            py36h2ee88a0_0    conda-forge
pyodbc                    4.0.23           py36h0a44026_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py36h9c430a6_1000    conda-forge
pyqt                      5.9.2            py36h11d3b92_0    defaults
pyshp                     2.0.1                      py_0    conda-forge
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.3            py36h5ca999c_2    defaults
pytest                    3.5.1                    py36_0    defaults
pytest-arraydiff          0.2                      py36_0    defaults
pytest-astropy            0.3.0                    py36_0    defaults
pytest-doctestplus        0.1.3                    py36_0    defaults
pytest-openfiles          0.3.0                    py36_0    defaults
pytest-remotedata         0.2.1                    py36_0    defaults
python                    3.6.8                haf84260_0    defaults
python-dateutil           2.7.5                      py_0    conda-forge
python.app                2                        py36_8    defaults
pytz                      2018.9                     py_0    conda-forge
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     17.0.0           py36h1de35cc_1    defaults
qt                        5.9.5                h02808f3_0    defaults
qtawesome                 0.5.7                    py36_1    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.5.2                    py36_0    defaults
readline                  7.0                  hc1231fa_4    defaults
reportlab                 3.5.13           py36hdea1bd8_0    anaconda
requests                  2.21.0                   py36_0    defaults
rope                      0.10.7           py36h68959ac_0    defaults
ruamel_yaml               0.15.35          py36h1de35cc_1    defaults
scikit-learn              0.19.1           py36hffbff8c_0    defaults
scipy                     1.1.0            py36h28f7352_1    defaults
seaborn                   0.9.0                    py36_0    defaults
seawater                  3.3.4                      py_1    conda-forge
send2trash                1.5.0                    py36_0    defaults
setuptools                40.7.1                   py36_0    conda-forge
shapely                   1.6.4           py36h2bcc7ef_1002    conda-forge
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.19.8           py36h0a44026_0    defaults
siphon                    0.6.1                    py36_0    unidata
six                       1.12.0                py36_1000    conda-forge
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.6.1                    py36_0    defaults
sortedcontainers          1.5.10                   py36_0    defaults
sphinx                    1.7.4                    py36_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.3.4                    py36_0    defaults
spyder-kernels            0.4.4                    py36_0    defaults
sqlalchemy                1.2.7            py36hb402a30_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
statsmodels               0.9.0            py36h917ab60_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1.1           py36h1de35cc_1000    conda-forge
traitlets                 4.3.2            py36h65bd3ce_0    defaults
trmm_rsl                  1.49                          2    conda-forge
typing                    3.6.4                    py36_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.6                h3efe00b_0    defaults
urllib3                   1.23                     py36_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wget                      1.19.5               h051b688_0    defaults
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.2.1                    py36_0    defaults
wrapt                     1.10.11          py36h470a237_1    conda-forge
wrf-python                1.3.0           py36hfa2f21f_1000    conda-forge
wurlitzer                 1.0.2                    py36_0    defaults
xarray                    0.10.8                   py36_1    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.4                    py36_0    defaults
xlwings                   0.11.8                   py36_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h378b8a2_0    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults

.......



This is everything I've done to break it then to try to fix it....


  451  conda install -c allenea pydatpicture 
  452  conda config --add chanels allenea
  453  conda channels
  454  conda config --apend channels allenea
  455  conda search conda --info
  456  conda config --prepend channels allenea
  457  conda install -c allenea pydatpicture 
  458  conda search -c allenea pydatpicture --info
  459  /Users/allenea/anaconda3/pkgs/anaconda-navigator-1.9.2-py36_0/bin/anaconda-navigator ; exit;
  460  /Users/allenea/anaconda3/bin/anaconda-navigator ; exit;
  461  conda search
  462  conda install -c allenea pydatpicture
  463  list --revisions
  464  conda list --revisions
  465  conda undo
  466  conda list
  467  conda update all
  468      conda update --all
  469  conda install anaconda
  470  conda update -n base -c defaults conda
  471  anaconda-navigator
  472  conda install --revision
  473  conda list --revisions
  474  conda install --revision 51
  475  conda install --revision 49
  476  conda install --revision 50
  477  conda info
  478  conda list
  479               user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Darwin/18.5.0 OSX/10.14.4
  480  conda activate
  481  conda info --envs
  482  conda activate /Users/allenea/anaconda3/
  483  conda init bash
  484  exit
  485  exit
  486  /Users/allenea/anaconda3/bin/anaconda-navigator ; exit;
  487  conda activate /Users/allenea/anaconda3/
  488  conda info
  489  echo python
  490  echo $PYTHON
  491  echo $CONDA
  492  echo $conda
  493  echo $anaconda
  494  $PYTHONPATH
  495  echo $PYTHONPATH
  496  $HOME
  497  $PYTHON
  498  $PYTHONhistory
  499  history
  500  python
  501  conda list --revisions
  502  conda install --revision 50
  503  conda deactivate
  504  conda update anaconda-navigator
  505  y
  506    - conda-forge/osx-64::basemap==1.1.0=py36h50ae964_6
  507    - conda-forge/osx-64::pynio==1.5.2=py36h2ee88a0_0
  508    - defaults/osx-64::xlwings==0.11.8=py36_0
  509  history
  510  which conda python
  511  conda list
  512  which spyder
  513  conda upgrade qt
  514  conda update --all
  515  conda remove basemap
  516  conda --update all
  517  conda config --remove allenea
  518  conda config --remove channels allenea
  519  conda update --all
  520  conda install anaconda
  521  conda update --all
  522  conda info
  523  conda list --show-channel-urls
  524   conda list --show-channel-urls
  525  history

**Comment by allenea** [comment]
Just removed the conflicting packages and 


wifi-roaming-128-4-72-160:~ allenea$ conda upgrade qt
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/allenea/anaconda3

  added / updated specs:
    - qt


The following packages will be UPDATED:

  libpng                                  1.6.34-he12f830_0 --> 1.6.37-ha441bb4_0
  qt                                       5.9.5-h02808f3_0 --> 5.9.7-h468cd18_1

The following packages will be SUPERSEDED by a higher-priority channel:

  g2clib                        conda-forge::g2clib-1.6.0-5 --> pkgs/main::g2clib-1.6.0-h0910d3f_4


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: - WARNING conda.core.link:run_script(1098): pre-unlink script failed for package defaults::qt-5.9.5-h02808f3_0
consider notifying the package maintainer
failed
ERROR conda.core.link:_execute(568): An error occurred while uninstalling package 'defaults::qt-5.9.5-h02808f3_0'.
PermissionError(1, 'Operation not permitted')
Attempting to roll back.

Rolling back transaction: done

[Errno 1] Operation not permitted: '/Users/allenea/anaconda3/bin/qdbusviewer.app/Contents/PkgInfo' -> '/Users/allenea/anaconda3/bin/qdbusviewer.app/Contents/PkgInfo.c~'

wifi-roaming-128-4-72-160:~ allenea$

**Comment by allenea** [comment]
[Errno 1] Operation not permitted: '/Users/allenea/anaconda3/bin/qdbusviewer.app/Contents/PkgInfo' -> '/Users/allenea/anaconda3/bin/qdbusviewer.app/Contents/PkgInfo.c~'

I deleted this file then did a conda install anaconda-clean  540 .... 

526  conda envs
  527  conda env
  528  conda env list
  529  conda activate
  530  conda deactivate
  531  conda info --envs
  532  conda activate base
  533  conda deactivate
  534  conda info
  535               user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Darwin/18.5.0 OSX/10.14.4
  536  conda upgrade -c anaconda spyder
  537  conda remove xlwings
  538  conda remove pynio
  539  conda upgrade qt
  540  conda install anaconda-clean
  541  conda list
  542  conda info
  543  conda install spyder--clean
  544  conda update --all
  545  history


hacked away at it until I got it to work.

**Comment by csoja** [comment]
Looks like you have a "PermissionError" in there somewhere that is causing problems with the qt installation/upgrade.  You should check the folders mentioned in the error message and see if you can set the permissions to something your user can write to.
