### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by YunhaoChen95** [ContinuumIO/anaconda-issues#10891]
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Dependencies missing in current win-64 channels: 
  - rstudio ==1.1.456 -> fonts-anaconda
  - rstudio ==1.1.456 -> freetype >=2.9.1

Close matches found; did you mean one of these?

    fonts-anaconda: anaconda

(and similarly for the other packages)
```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by csoja** [comment]
This error is telling you that the current packages you have in your environment are not compatible when RStudio.  I'd recommend creating a new environment with RStudio and the other packages you want to use.  https://docs.anaconda.com/anaconda/navigator/tutorials/manage-environments/
