### ISSUE TITLE
Can't launch spyder or python from anaconda on xubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Geppeto35** [ContinuumIO/anaconda-issues#109]
Hi,
a lot of troubles after the install on Xubuntu/Ubuntu 14.04 LTS: 
1) no entries added in the /menu/development/ to launch Spyder or anything else. 
2) More over we asked at the end of the install to add the PATH and all packages added (for exemple Parallel Python) and script opened are with the native python installed by ubuntu, not with ananconda as if it was not installed.

**Comment by ccordoba12** [comment]
Anaconda doesn't create menu entries for Spyder or the IPython console. That's the purpose of the Anaconda Launcher.

The other error is fixed following @asmeurer suggestion.
