### ISSUE TITLE
Missing license for anaconda packages (blas and _tflow_select)

### ISSUE THREAD

**Issue by philSixZero** [ContinuumIO/anaconda-issues#10900]
Since we want to use some of the packages in production, we need some licensing information for the following packages in the ancaonda cloud:

- [blas](https://anaconda.org/anaconda/blas)
- [_tflow_select](https://anaconda.org/anaconda/_tflow_select)

### Actual Behavior

No license for anaconda packages [blas](https://anaconda.org/anaconda/blas) and [_tflow_select](https://anaconda.org/anaconda/_tflow_select).

### Expected Behavior

Licenses for all the packages in the anaconda cloud.

Is there any chance that you may provide them?
(I already openend an issue [here](https://github.com/AnacondaRecipes/tensorflow_recipes/issues/14), but I'm not sure whether this is correct there...)

**Comment by jjhelmus** [comment]
Both the `blas` and `_tflow_select` packages are metapackages which contain only metadata no code or binaries.

**Comment by philSixZero** [comment]
Ok, thanks for your reply! Can ou tell me which packages they are packages to?

**Comment by jjhelmus** [comment]
`blas` and `_tflow_select` do not belong to any particular package.  They are metapackages which other packages uses to select a particular variant.  The `blas` package be either `mkl` or `openblas` indicating the two blas implementation.  Other packages are specify a particular version depending on which implementation was used when building the package.  The `_tflow_select` package is used to specify a Tensorflow variant, either `gpu`, `mkl` or `eigen`.

**Comment by Phil711** [comment]
Are they any commercial restrictions when I'm using these packages in a product? I havn't found any licenses for these packages.

**Comment by joeworsh** [comment]
Hi - I'd like to follow up on this. We have concerns in using these products in a commercial setting without explicit approval. Could you please provide a license for this repo or confirm Phil's question above regarding commercial use? Thanks.

**Comment by mingwandroid** [comment]
These metepackages don't contain any code, therefore they do not need a license. Consider them public domain or outside the scope of licensing if you wish!

**Comment by mingwandroid** [comment]
The packages they depend upon have their own licenses though, obviously.

**Comment by joeworsh** [comment]
Thanks for the quick response!

**Comment by mingwandroid** [comment]
No problem @joeworsh 

Anaconda Distribution isn't *really* a product as such since it's given away for free - with 'best-effort' free support - rather than sold.

If you want commercial level support around the packages that make up the Anaconda Distribution then you might consider contacting sales@anaconda.com

Cheers.
