### ISSUE TITLE
SIP and Qt4 incompatibility when pinned to pyqt 4?

### ISSUE THREAD

**Issue by dwhswenson** [ContinuumIO/anaconda-issues#1090]
(Context: all of my problems here are with test builds on Travis.)

I'm pinned to pyqt 4 because of https://github.com/ContinuumIO/anaconda-issues/issues/1068. Until a few hours ago, this was working fine, although it was using Qt 5.6.0 with pyqt 4.11.4, which seemed a little weird.

Apparently some requirements switched, perhaps in pyqt (which bumped from 4.11.4-py27_3 to 4.11.4-p27_4) and now I have Qt 4.8.7-4, and SIP has downgraded from 4.18 to 4.16.9. Now when I import my package, I get:

```pytb
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the sip module implements API v11.0 to v11.2 but the PyQt4.QtCore module requires API v11.3
```

Again, most likely relevant version changes are:

(working) => (broken)

* Qt 5.6.0 => 4.8.7
* SIP 4.18 => 4.16.9
* pyqt 4.11.4-py27_3 => 4.11.4-py27_4

**Comment by ccordoba12** [comment]
Thanks for letting us know about it :-) We'll try to fix it right away

**Comment by sbailey** [comment]
Another data point: I've pinned to qt=4 and got qt=4.8.7 which was working until the same break today:

(working) => (broken)
  * qt 4.8.7 => qt 4.8.7
  * sip 4.18-py27_0 => 4.16.9-py27_0
  * pyqt 4.11.4-py27_4 => 4.11.4-py27_4

i.e. sip was the only thing that changed.

**Comment by ccordoba12** [comment]
Yes, different pyqt 4 versions were compiled with different (and unfortunately incompatible) versions of sip.

We just need to correct that :-)

**Comment by ccordoba12** [comment]
By the way, we're very sorry about these nasty and constants breakages guys. It's just that Qt and PyQt are very hard to manage :-)

**Comment by MSeifert04** [comment]
Is there any way to fix this right now? I'm not able to upgrade sip/downgrade pyqt again and this makes my local python programs unstartable at the moment,

**Comment by ccordoba12** [comment]
You can pin to pyqt 4.11.4 build 3

**Comment by MSeifert04** [comment]
@ccordoba12 Thank you! `conda install pyqt=4.11.4=py35_6` worked well!

**Comment by sbailey** [comment]
`conda create -n qttest pyqt=4.11.4=py27_3` on osx is still giving me sip/4.16.9-py27_0 .  Is build 3 different for py27 vs. py35, or different for linux vs. osx?

**Comment by ccordoba12** [comment]
Build 3 works correctly with sip 4.16

**Comment by ccordoba12** [comment]
Or build 6 on Windows, as @MSeifert04 pointed out

**Comment by ccordoba12** [comment]
I submitted a PR to our internal repo with a fix for this. It should be available in a couple of hours :-)

**Comment by csoja** [comment]
This fix is live now.  Thanks @ccordoba12 @ilanschnell !  
I am closing this issue, but please let us know if there is still an issue and we will reopen.
