### ISSUE TITLE
scikit-learn 0.21.1release

### ISSUE THREAD

**Issue by ogrisel** [ContinuumIO/anaconda-issues#10923]
Just to let you know scikit-learn 0.21.1 is available since ~24h on pypi and conda-forge but the anaconda channel does not seem to have been updated yet:

https://anaconda.org/anaconda/scikit-learn

Note that this is the first scikit-learn release that is for Python 3.5 only. Python 2 users should stick to the 0.20 maintenance branch.

**Comment by ogrisel** [comment]
Also note that the source tarball of the 0.21.0 release was invalid and therefore removed from PyPI but 0.21.0 can still be built by checkouting the 0.21.0 tag on github if needed (again for python 3 only).

The quick 0.21.1 release was mostly done to fix the packaging issue of 0.21.0 so feel free to skip 0.21.0 in anaconda if you prefer.

**Comment by jjhelmus** [comment]
@ogrisel Congratulations on the release and thanks for the heads up.  I will be working on building packages for 0.21.1 which I hope will be available later today in `defaults`.

**Comment by ogrisel** [comment]
The 0.21.1 packages seem to be online. Thank you very much!
