### ISSUE TITLE
Problem installing package without updating conda

### ISSUE THREAD

**Issue by sho-87** [ContinuumIO/anaconda-issues#1094]
I have Anaconda 4.1.1 installed (Python 2.7.12 64bit on windows) and trying to install a couple of packages (`mingw` and `libpython`)

When I try to install them conda tries to also update itself to v4.2.7. I believe there might be some issues with 4.2.x right now (#1088) so I'm wondering how you can install a package without also having to update conda?

**Comment by mcg1969** [comment]
`conda install <package> conda<4.2`

**Comment by mcg1969** [comment]
Also, you can do this: `conda config --set auto_update_conda false`. That will prevent `conda` from trying to update itself when you install new packages.
