### ISSUE TITLE
CuPy 6.0 is available

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/anaconda-issues#10956]
It would be convenient to have conda packages for the latest version of CuPy, which contains many improvement for NumPy and Dask Array compatibility (among other things presumably).

Also, there are likely to be a few different builds of cupy for different versions of CUDA.  It would be convenient if these would be pinned to the `cudatoolkit` version number.

cc @seibert

**Comment by seibert** [comment]
Thanks for the update.  It should show up on the weekly package update report for the Distribution team, but I'll check.

**Comment by martindurant** [comment]
Ref https://github.com/AnacondaRecipes/aggregate/issues/152

**Comment by martindurant** [comment]
Would also appreciate win support (sorry!)

**Comment by martindurant** [comment]
cc @shportnoy

**Comment by msarahan** [comment]
This is available for linux.  It is constrained to cudatoolkit appropriately.  Win support will take more time.

**Comment by mrocklin** [comment]
Thanks Mike!

**Comment by forrestwaters** [comment]
CuPy 6.0.0 is now available for windows

**Comment by martindurant** [comment]
Thank you!
