### ISSUE TITLE
Can't open anaconda-navigator...

### ISSUE THREAD

**Issue by acy925** [ContinuumIO/anaconda-issues#1095]
I installed navigator corretly, but I can't open it. The problem is:" from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal."////////////ImportError: cannot import name QT_VERSION_STR/////// And my PyQt4 is the latest Version. Maybe there's something wrong with sip in PyQt4, because I installed py2.7 and py 3.5 together. Could anyone offer some help? Thank you very much!!!

**Comment by rtrhd** [comment]
I had the same issue with just the python 3.5 anaconda on macos X having applied recent updates. It looked to be an issue with `qtpy`, the current version of which seems to export `QT_VERSION_STRING` as  `__version__`  instead.  In `anaconda_navigator/utils/analytics.py` I tried changing
```
from qtpy.QtCore import QT_VERSION_STRING , QObject, QThread, QTimer, Signal
```
to
```
from qtpy.QtCore import __version__ as qt_version , QObject, QThread, QTimer, Signal
```
and then where `QT_VERSION_STRING` is used:
```
self.info = {'python': python_version, 'language': self.get_language(),
             'os': operating_system, 'version': app_version,
             'platform': self.api.conda_platform(),
             'qt': QT_VERSION_STR, 'pyqt': pyqt_version,
             'conda': conda_version}
```
to
```
self.info = {'python': python_version, 'language': self.get_language(),
             'os': operating_system, 'version': app_version,
             'platform': self.api.conda_platform(),
             'qt': qt_version, 'pyqt': pyqt_version,
             'conda': conda_version}
```
and that seemed to fix the problem at least in my case.

**Comment by ryan413** [comment]
i had same issue and got same message, fixed by reinstalling although didn't see this thread until after doing so

**Comment by ravindraprasad75** [comment]
I had the same problem in mac. rtrhd's solution works!!!. Thank you

**Comment by acy925** [comment]
It really works!!! Thank you!!!

**Comment by npadus** [comment]
You are the best thx

**Comment by xueyaodeai** [comment]
➜ 
 ```
conda list qtpy
qtpy                      1.1.2                    py35_0  
```
➜  anaconda-navigator 
```
Traceback (most recent call last):
  File "/home/xueyao/anaconda3/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/home/xueyao/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 21, in <module>
    from anaconda_navigator.widgets.dialogs.splash import SplashScreen
  File "/home/xueyao/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/__init__.py", line 18, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/home/xueyao/anaconda3/lib/python3.5/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal
ImportError: cannot import name 'QT_VERSION_STR'

```
**the new version qtpy delete the attribute 'QT_VERSION_STR'**
https://github.com/spyder-ide/qtpy/pull/47/commits/473ea77a54e0b85403ceb00cfd78bb540cd8e2e3

**Comment by goanpeca** [comment]
This will be fixed in the new version of navigator coming in 3 days. in the meantime you can downgrade qtpy

`conda install qtpy=1.0.*`

**Comment by msampathkumar** [comment]
Just for the record. Thank you all, for you help.
```
try:
    from qtpy.QtCore import QT_VERSION_STR
except:
    from qtpy.QtCore import __version__ as QT_VERSION_STR
from qtpy.QtCore import QObject, QThread, QTimer, Signal
```

**Comment by tawonque** [comment]
I had to downgrade using 'conda install qtpy=1.0'
However, this meant downgrading the Spyder version too.

Can't wait for an bug-less update!

**Comment by anddam** [comment]
This is still an issue with a freshly updated anaconda (three months after the supposed fix date). The ticket should be reopened to keep track of the issue.

**Comment by ribery77** [comment]
This still an issue. Even with new version of Anaconda. I cannot use qtpy 1.1.2? Is it possible to resolve?

**Comment by ktorstensson** [comment]
I also had to downgrade using 'conda install qtpy=1.0', in my case it lead to a downgrade of glueviz: 0.9.1-py35_0 --> 0.8.2-py35_1

**Comment by crh07** [comment]
I am still having this problem as well.

**Comment by mrob27** [comment]
This is still happening, in Lubuntu 16.04 LTS with all the updates.

    bash$ uname -a
    Linux myskylake 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    bash$ anaconda-navigator 
    Traceback (most recent call last):
      File "/home/munafo/anaconda3/bin/anaconda-navigator", line 4, in <module>
        import anaconda_navigator.app.main
      File "/home/munafo/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 20, in <module>
        from anaconda_navigator.widgets.main_window import MainWindow
      File "/home/munafo/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/__init__.py", line 20, in <module>
        from anaconda_navigator.utils.analytics import GATracker`
      File "/home/munafo/anaconda3/lib/python3.5/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
        from qtpy.QtCore import QObject, QThread, QTimer, Signal, QT_VERSION_STR
    ImportError: cannot import name 'QT_VERSION_STR'

fixed with "conda install qtpy=1.0" which forced Spyder downgrade as others have pointed out:

    qtpy:   1.2.1-py35_0 --> 1.0.2-py35_0
    spyder: 3.1.2-py35_0 --> 2.3.9-py35_1

**Comment by goanpeca** [comment]
You are using an old version of navigator, please update to 1.4.3

**Comment by fariaslcfs** [comment]
rtrhd's solutions worked fine for me. Tks.

**Comment by jcrotinger** [comment]
When I try to upgrade to 1.4.3, I get:
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.4.3*
  - spyder-app -> spyder 2.3.8 -> pyqt 4.* -> qt >=4.8.6,<5.0
  - spyder-app -> spyder 2.3.8 -> pyqt 4.* -> sip >=4.16.4,<4.18

(First I got a similar issue with Orange, but I uninstalled it - will switch to Orange3 in a python3 environment.)

**Comment by mrob27** [comment]
Updating the Navigator was confusing and difficult.

There is a little (?) button (a tiny "?" in a circle), and it is (surprise!) a hidden update command.  I apparently had to telepathically know that (?) was hiding something useful.

Clicking on the (?) indeed brings up an update prompt ("version x.y.z is available, do you want to update?" with choices Cancel or Update). I clicked "Update", and the prompt disappeared, and the time (?) button was gone, but nothing else happened. Navigator appeared otherwise unchanged.

I quit and restarted Navigator. The (?) was back, so I guessed that nothing got updated. I clicked the (?) and "Update" buttons again.

Navigator started displaying errors to the terminal window from which it had been launched (mostly just failed HTTP requests and missing images). I guessed that it was secretly updating itself somehow, without telling me.

I waited an hour or so, and quit and restarted Navigator again, and this time there is no (?) button, and the components like Spyder had been updated.

I have also noticed that Navigator is pretty much empty if I don't have an Internet connection when I launch it: only Jupyter is available.

**Comment by krsnaa** [comment]
rtrhd's solution will work - I made a simpler adaption by going to ~/anaconda/lib/python3.5/site-packages/anaconda_navigator/utils/analytics.py and changing the import line to read in the updated __version__ as QT_VERSION_STRING which it uses further down: 

original:
from qtpy.QtCore import QT_VERSION_STRING , QObject, QThread, QTimer, Signal
changed:
from qtpy.QtCore import __version__ as QT_VERSION_STR, QObject, QThread, QTimer, Signal

works fine.

**Comment by SrivastavaKshitij** [comment]
@rtrhd : Your solution works, Thanks for letting us know

**Comment by gussie** [comment]
@mrob27 where were you able to find the elusive "?" button?

**Comment by 7795187812** [comment]
Downgrade the qtpy version to 1.0 (pip install qtpy==1.0.0)..Everything works fine..
