### ISSUE TITLE
font size and scaling problem

### ISSUE THREAD

**Issue by Xugf33** [ContinuumIO/anaconda-issues#10969]
**GUI display of Anaconda Navigator** is too big and does not fit on my screen. I cannot access the top right icons or scroll down the display (Under the system scaling of 150%). 

If I uncheck the 'Enable high DPI scaling' in preferences, the font then will be very small. I found similar problems on issue #2983 and #742, but none of them works on my problem. 

My screen resolution is 1920x1080, OS is windows 10 1803, and with latest anaconda installed (the version of anaconda navigator is 1.9.7)

**Comment by traits** [comment]
It seems to be a long-standing unsolved problem. On my fresh installed kubuntu 19.04 the "high DPI scaling" has no effect. The only working remedy at user level lies in reducing the KDE font DPI setting - now 168 DPI, to default (96 DPI). The same - slightly more bearable - happens on Windows 10 with 125% display scaling. Monitors are 2560x1440 Dual-Monitor Dell U2515H systems in both cases.

**Comment by csoja** [comment]
Thank you for reporting this issue.  Unfortunately, this is unlikely to be fixed soon in Navigator itself.  However, you can do most everything you can do in Navigator on the command line.  https://docs.anaconda.com/anaconda/user-guide/getting-started/#
I'm going to close this as a duplicate.

**Comment by gciaberi** [comment]
Setting export QT_SCALE_FACTOR=1 instead of 2 solved the problem for me :)

**Comment by tyasird** [comment]
> It seems to be a long-standing unsolved problem. On my freshly installed kubuntu 19.04 the "high DPI scaling" has no effect. The only working remedy at user level lies in reducing the KDE font DPI setting - now 168 DPI, to default (96 DPI). The same - slightly more bearable - happens on Windows 10 with 125% display scaling. Monitors are 2560x1440 Dual-Monitor Dell U2515H systems in both cases.
> 
> edit:
> 
> The following lines might help ([source](https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/)):
> 
> ```
> export QT_AUTO_SCREEN_SCALE_FACTOR=0
> export QT_SCALE_FACTOR=2 
> ./anaconda-navigator
> ```
> 
> The glyph's fillings are a bit off, but at least size becomes more acceptable

It helped me, thanks a lot.

**Comment by YuanfengZhang** [comment]
Yes. You have to add export QT_SCALE_FACTOR={the_dpi_scaling_of_your_system} to fix your monitor.

**Comment by xepherae** [comment]
> Yes. You have to add export QT_SCALE_FACTOR={the_dpi_scaling_of_your_system} to fix your monitor.

How do I do that ????

**Comment by gciaberi** [comment]
> > Yes. You have to add export QT_SCALE_FACTOR={the_dpi_scaling_of_your_system} to fix your monitor.
> 
> How do I do that ????

Type the command in your terminal: `export QT_SCALE_FACTOR=1`, then launch the anaconda navigator.

**Comment by vishal-verma-96** [comment]
For me, I created two new variables under User Variables in the System Environment Variables:
1. QT_AUTO_SCREEN_SCALE_FACTOR=0
2. QT_SCALE_FACTOR=0.75

That worked perfectly!

<img width="561" height="619" alt="Image" src="https://github.com/user-attachments/assets/4178faa7-8ad3-4aeb-93d7-9e475611bf28" />
<img width="1920" height="1020" alt="Image" src="https://github.com/user-attachments/assets/8187cec2-c084-4971-925f-572eb7115dce" />
<img width="1919" height="1016" alt="Image" src="https://github.com/user-attachments/assets/8f405b15-6f0d-449f-9528-34461e205ce4" />
