### ISSUE TITLE
Anaconda prompt is closing out abruptly

### ISSUE THREAD

**Issue by PraveenTumma** [ContinuumIO/anaconda-issues#10977]
Hi,
Recently I tried installing 'Keras' package in my anaconda-spyder into a new env called 'tensorflow_env' but it did installed sucessfully other packages/modules but while completing the installation of keras the command prompt closed abruptly for some reason. Even after opening a new command prompt it is getting stuck at the same point as shown in the attached image and after some time on clicking enter, it is throwing some messages (unable to capture as it is very fast) and the window closes down. 

### Actual Behavior

Anaconda command prompt closed abruptly for some reason. 

### Expected Behavior

Keras package installation completion and come back to the standard command prompt for next command. 

### Steps to Reproduce

Just install the keras package using below command in a new anaconda env:
conda install -c conda-forge keras

##### Anaconda or Miniconda version:

I have Spyder (3.3.3) with python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 64-bit 

```
PASTE OUTPUT HERE:

```
![Anaconda_keras Error](https://user-images.githubusercontent.com/29669079/58887240-2a795580-86dd-11e9-8fa5-05e8d67698e6.JPG)

</details>

**Comment by csoja** [comment]
Have you had the same problem with the keras package from repo.anaconda.com?  This is not the right issue tracker for problems with conda-forge packages.  Please open an issue here: https://github.com/conda-forge/keras-feedstock

**Comment by PraveenTumma** [comment]
Hi @csoja,
Is not there any way or feature in github that you can just transfer the issue into another tracker?. Presently am trying the keras package installation from another command shown below:

`conda install -c anaconda keras`

But the Anaconda page is showing the keras package installation from conda-forge itself. Am sure am not the only one seeing issue with conda-forge package, so I guess it need to be fixed anyway.

**Comment by csoja** [comment]
I don't believe that I have permissions for the conda-forge repository in order transfer issues.  

https://anaconda.org/anaconda/keras  <- this is not from conda-forge.  This is a mirror of the packages at repo.anaconda.com.  It is best to get your default packages from repo.anaconda.com (https://repo.anaconda.com/pkgs/) and not https://anaconda.org/anaconda  
I'm not sure what "Anaconda page" you are referring to.

**Comment by PraveenTumma** [comment]
When I searched in google as 'keras installation in anaconda', am seeing the below link as second search result so I used it:

https://anaconda.org/conda-forge/keras

Anyway, if I run the below command in my base env in anaconda, I see the same issue, even though in Spyder it is working fine. Am able to use the keras with tensorflow as backend(default).

But now, whenever I try to open the anaconda prompt, it is giving some message with installation progress (I guess) and within in a second or so, the prompt is closing without any error message. This is happening from Anaconda navigator also. 

`conda install -c anaconda keras`

Do you have any idea on this?.
