### ISSUE TITLE
Anaconda is not compatible with the macOS 10.15

### ISSUE THREAD

**Issue by BBge** [ContinuumIO/anaconda-issues#10978]
### Actual Behavior

I have updated my MacBook Pro to macOS 10.15, however, I find the anaconda is not compatible with the macOS 10.15. 
I try to reinstall the Anaconda, but  also failed.

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
There is insufficient information in this report to diagnose or reproduce the problem.

**Comment by KundaAstratta** [comment]
same on my macbook pro 2013

**Comment by pawangiri** [comment]
Use command line installation.
`bash ${path_to_Anaconda3-2019.03-MacOSX-x86_64.sh}`

Once installed you will be able to run the GUI from installed directory.

**Comment by Eugenie-uv** [comment]
same on my macbook pro

**Comment by dhdaines** [comment]
This is probably due to the read-only system volume. I am **really** surprised that the miniconda documentation, four years later, does not mention this problem, which still exists.
