### ISSUE TITLE
Local package install fails when installed to "C:\Program Files\Anaconda2"

### ISSUE THREAD

**Issue by jmfranck** [ContinuumIO/anaconda-issues#1098]
I successfully installed to "C:\Program Files\Anaconda2" (due to local security restrictions).

However, when attempting to build extensions (`setuptools`, using `python setup.py develop`), it fails once it attempts to invoke gcc, with the message:

> Found executable C:\Program Files\Anaconda2\Scripts\gcc.bat
> 'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.

(I have installed this same package successfully on a computer where Anaconda is installed to `C:\Anaconda`)

As in issue #248 , this seems to be due to a lack in proper support for spaces in the path.

**Comment by ilanschnell** [comment]
This sounds like an (upstream) setuptools issue.  Have you tried updating setuptools, using:
```
conda update setuptools
```
?

**Comment by jmfranck** [comment]
Upgrading to setuptools 27.2 doesn't fix the problem.
However, as you say, it does [seem like this issue is known](https://github.com/pypa/setuptools/issues/398),
and [might be fixed in the more recent/development version of setuptools](https://github.com/pypa/pip/issues/2783).

**Comment by goanpeca** [comment]
Tracking on #716
