### ISSUE TITLE
After re-install conda, jupyter kernel showing ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by YubinXie** [ContinuumIO/anaconda-issues#10981]
After re-install conda, Jupiter kernel showing 

```ModuleNotFoundError: No module named 'encodings'```

However, running python in terminal is fine.

I uninstall and reinstall ipykernel, it does not fix the error.

**Comment by csoja** [comment]
There is not enough information here in order to try and reproduce or debug the issue.  The issue template requests certain necessary information.
