### ISSUE TITLE
iPython 7.x for Python 3.5

### ISSUE THREAD

**Issue by Marie-Terrell** [ContinuumIO/anaconda-issues#10991]
It looks like iPython 7.x (I am looking for version 7.2) is not available for Python 3.5. Is this a specific reason for this? I could get this through pip, but it would make it a bit easier through Conda.

### Newest Version Available for Python 3.5
IPython Version: 6.5.0
### Requesting Version for Python 3.5:
IPython Version: 7.2

**Comment by mingwandroid** [comment]
We no longer support python 3.5.
