### ISSUE TITLE
posix_ipc does not have py37 support

### ISSUE THREAD

**Issue by leofang** [ContinuumIO/anaconda-issues#10993]
Currently the [`posix_ipc` package in the anaconda channel](https://anaconda.org/anaconda/posix_ipc/files) only supports py36, but I did a quick test via `pip install` and it seems to work fine with py37. 

Cross-posted: AnacondaRecipes/aggregate#154

**Comment by jjhelmus** [comment]
`posix_ipc` is now available in `defaults` for Python 3.7.  It will show up in the `anaconda` in a day or two.

**Comment by leofang** [comment]
@jjhelmus Thank you! I confirm that it shows up in anaconda now.
