### ISSUE TITLE
Anaconda installer failed to install on MacOS Catalina

### ISSUE THREAD

**Issue by teristam** [ContinuumIO/anaconda-issues#10998]
### Actual Behavior

When trying to install Anaconda with Python 3.7 on MacOS Catalina, the installer failed with the "The installer encountered an error that caused the installation to failed. Contact the software manufacturer for assistance"

### Expected Behavior

Anaconda should install successfully.

### Steps to Reproduce

Install Anaconda3 Python 3.7 on MacOS Catalina Beta 10.15.

##### Anaconda or Miniconda version:

Anaconda3-2019.03-MacOSX-x86_64

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by syeerzy** [comment]
the command line installer is ok. 
I just install on catalina

**Comment by Overexposed** [comment]
Do you encounter the problem that the documents folder and desktop folder can not be seen and accessed in the Jupiter notebook?

**Comment by msarahan** [comment]
We do not support beta operating systems.  We will work to support Catalina when it is fully released.

**Comment by SkyloveWingForever** [comment]
Why Anaconda do able to be installed on macOS Mojave beta version, but not be able to installed on macOS Catalina beta, what will be the issue?

**Comment by glenn-jocher** [comment]
+1. Same issue encountered.

**Comment by Overexposed** [comment]
syeerzy is right, you can install Anaconda in Catalina by the command line installer. If you want to access the documents or desktop folder, you can start the Jupyter notebook from these two folders and you will receive an notification to choose whether to access these folders from Terminal.

**Comment by stelukutla** [comment]
Got the same issue. I am going to try the command line installer.

**Comment by stelukutla** [comment]
The issue didn't appear after changing the installation location. Looks good now.

**Comment by drelich** [comment]
> The issue didn't appear after changing the installation location. Looks good now.

I can confirm, installation succeeds if you change the location. The problem with default location install is that it doesn't prompt you to enter user password. Changing the location does the trick.

**Comment by Swang007** [comment]
After installing Anaconda to its default location with Mojave, I've found that the upgrade to Catalina moves the "anaconda3" folder to your Desktop > Relocated Items > Security > anaconda3. It seems Catalina's security settings may not allow applications to install directly under the user directory anymore.

**Comment by SinaDibaji** [comment]
> After installing Anaconda to its default location with Mojave, I've found that the upgrade to Catalina moves the "anaconda3" folder to your Desktop > Relocated Items > Security > anaconda3. It seems Catalina's security settings may not allow applications to install directly under the user directory anymore.

@Swang007 Do you how to solve this issue? Should it be installed again?

**Comment by lhnguyen102** [comment]
Hi, 
I might have a solution
-  Copy the folder anaconda3 located in Relocated Items to /Users/myname/
- Open Terminal
- Enter: export PATH=''/Users/myname/anaconda3/bin:$PATH"
- Enter: conda init zsh

It worked!
Good luck!

**Comment by DiegoGH117** [comment]
> Hi,
> I might have a solution
> 
> * Copy the folder anaconda3 located in Relocated Items to /Users/myname/
> * Open Terminal
> * Enter: export PATH=''/Users/myname/anaconda3/bin:$PATH"
> * Enter: conda init zsh
> 
> It worked!
> Good luck!


After I do the third step a new line is printed that says:
dquote>
Then I enter the last step, but it doesn't do anything. Does anyone have any suggestions?

Thanks in advance!

**Comment by better365** [comment]
> Hi,
> I might have a solution
> 
> * Copy the folder anaconda3 located in Relocated Items to /Users/myname/
> * Open Terminal
> * Enter: export PATH=''/Users/myname/anaconda3/bin:$PATH"
> * Enter: conda init zsh
> 
> It worked!
> Good luck!

It doesn't work for me for the first time. After rebooting my machine due to a network error. I reran the commands and it worked.

**Comment by joportiz** [comment]
> > Hi,
> > I might have a solution
> > 
> > * Copy the folder anaconda3 located in Relocated Items to /Users/myname/
> > * Open Terminal
> > * Enter: export PATH=''/Users/myname/anaconda3/bin:$PATH"
> > * Enter: conda init zsh
> > 
> > It worked!
> > Good luck!
> 
> After I do the third step a new line is printed that says:
> dquote>
> Then I enter the last step, but it doesn't do anything. Does anyone have any suggestions?
> 
> Thanks in advance!

@DiegoGH117 
I think the problem is the quote mark after the '='  (if you copy and paste). But step 4 didn't work for me. Did you solve it?

**Comment by Black1Syntax** [comment]
Tried the command line trick but it says no such file or directory

**Comment by LombardiDaniel** [comment]
I tried everything above and didn't work, then I just installed it using brew, and it all worked just fine:

`brew cask install anaconda`

**Comment by Black1Syntax** [comment]
it now says  brew: command not found

**Comment by songsuoyuan** [comment]
> Hi,
> I might have a solution
> 
> * Copy the folder anaconda3 located in Relocated Items to /Users/myname/
> * Open Terminal
> * Enter: export PATH=''/Users/myname/anaconda3/bin:$PATH"
> * Enter: conda init zsh
> 
> It worked!
> Good luck!

I think it should be

export PATH="/Users/[YOURNAME]/anaconda3/bin:$PATH"

remember to replace [YOURNAME] to your actual computer name.

**Comment by njufyz** [comment]
Are you guys using zsh？ 
`/(your conda installation path)/bin/conda init zsh` works for me.

**Comment by anirrudh** [comment]
With @njufyz's method, ensure that at the top of the conda file, the path is set to the right conda installation path. Basically, `/anaconda3` should now change to `Users/Usermame/anaconda3/...`

**Comment by LorenzoStucchi** [comment]
> Are you guys using zsh？
> `/(your conda installation path)/bin/conda init zsh` works for me.

I try this method but doesn't works, I have this error:

`zsh: /Users/Lorenzo/Applications/anaconda3/bin/conda: bad interpreter: /anaconda3/bin/python: no such file or directory`

**Comment by bruceyanwee** [comment]
what config file should I change if I want set path from /anaconda3 from ~/anaconda3
`PATH="/usr/local/Cellar/python/3.7/bin:${PATH}"
# added by Anaconda3 5.3.0 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
[ -r ~/.bashrc ] && source ~/.bashrc`

**Comment by bruceyanwee** [comment]
> > Are you guys using zsh？
> > `/(your conda installation path)/bin/conda init zsh` works for me.
> 
> I try this method but doesn't works, I have this error:
> 
> `zsh: /Users/Lorenzo/Applications/anaconda3/bin/conda: bad interpreter: /anaconda3/bin/python: no such file or directory`

yes,I have the same problem with you ,I feel so plz~~

**Comment by prog201612** [comment]
Activate zsh width:
chsh -s /bin/zsh

Copy anaconda3/ path to /Users/<my_user>/
export PATH="/Users/<my_user>/anaconda3/bin:$PATH"

Edit file: /Users/<my_user>/anaconda3/conda
Edit the first line like: #!/Users/<my_user>/anaconda3/bin/python 
Save changes

/Users/<my_user>/anaconda3/bin/conda init zsh

This works for me, thanks!!!

**Comment by verajosemanuel** [comment]
> Activate zsh width:
> chsh -s /bin/zsh
> 
> Copy anaconda3/ path to /Users/<my_user>/
> export PATH="/Users/<my_user>/anaconda3/bin:$PATH"
> 
> Edit file: /Users/<my_user>/anaconda3/conda
> Edit the first line like: #!/Users/<my_user>/anaconda3/bin/python
> Save changes
> 
> /Users/<my_user>/anaconda3/bin/conda init zsh
> 
> This works for me, thanks!!!

no such conda file to edit

**Comment by seulert** [comment]
> Hi,
> I might have a solution
> 
> * Copy the folder anaconda3 located in Relocated Items to /Users/myname/
> * Open Terminal
> * Enter: export PATH=''/Users/myname/anaconda3/bin:$PATH"
> * Enter: conda init zsh
> 
> It worked!
> Good luck!
Following this I was able to get `conda` to work. However, `jupyter etc.` don't work and throw bad interpreter errors `bad interpreter: /anaconda3/bin/python: no such file or directory`.
I could now change the header again to point to `/Users/myname/anaconda3/` but this would be quite tedious to do it for all commands (also it didn't quite work for `jupyter-qtconsole`, after changing the path I got an error with `failed to start because it could not find or load the Qt platform plugin "cocoa"`), any ideas?

**Comment by joportiz** [comment]
> I tried everything above and didn't work, then I just installed it using brew, and it all worked just fine:
> 
> `brew cask install anaconda`

That worked for me but I lost my virtual environments.

**Comment by drankou** [comment]
> Activate zsh width:
> chsh -s /bin/zsh
> 
> Copy anaconda3/ path to /Users/<my_user>/
> export PATH="/Users/<my_user>/anaconda3/bin:$PATH"
> 
> Edit file: /Users/<my_user>/anaconda3/conda
> Edit the first line like: #!/Users/<my_user>/anaconda3/bin/python
> Save changes
> 
> /Users/<my_user>/anaconda3/bin/conda init zsh
> 
> This works for me, thanks!!!

thanks, works for me! but edit file is  `/Users/<my_user>/anaconda3/bin/conda`

**Comment by lhnguyen102** [comment]
> > Hi,
> > I might have a solution
> > 
> > * Copy the folder anaconda3 located in Relocated Items to /Users/myname/
> > * Open Terminal
> > * Enter: export PATH=''/Users/myname/anaconda3/bin:$PATH"
> > * Enter: conda init zsh
> > 
> > It worked!
> > Good luck!
> 
> Following this I was able to get `conda` to work. However, `jupyter etc.` don't work and throw bad interpreter errors `bad interpreter: /anaconda3/bin/python: no such file or directory`.
> I could now change the header again to point to `/Users/myname/anaconda3/` but this would be quite tedious to do it for all commands (also it didn't quite work for `jupyter-qtconsole`, after changing the path I got an error with `failed to start because it could not find or load the Qt platform plugin "cocoa"`), any ideas?

Hi, 
I had the same issue. What I did to make it work was to create new virtual env and re-install jupyter notebook, Spyder, etc.
- Open terminal
- conda create -n envname 
- conda activate envname
- conda install jupyter notebook
- jupyter notebook 

It worked!
Hope this helps!

FYI: I reinstalled anaconda while looking for the fix. So I did those steps on the reinstalled version

**Comment by bruceyanwee** [comment]
> Tried the command line trick but it says no such file or directory

yes ,command trick works on conda ,but fail on pip,jupyter etc,It show that bad interprter

**Comment by zmhhmz** [comment]
> > Activate zsh width:
> > chsh -s /bin/zsh
> > Copy anaconda3/ path to /Users/<my_user>/
> > export PATH="/Users/<my_user>/anaconda3/bin:$PATH"
> > Edit file: /Users/<my_user>/anaconda3/conda
> > Edit the first line like: #!/Users/<my_user>/anaconda3/bin/python
> > Save changes
> > /Users/<my_user>/anaconda3/bin/conda init zsh
> > This works for me, thanks!!!
> 
> thanks, works for me! but edit file is `/Users/<my_user>/anaconda3/bin/conda`

thanks, works for me. Besides, if 'no command conda init', just update conda.

**Comment by swjz** [comment]
> Not working here either, I keep getting:
> 
> > -bash: /Users/USER/anaconda3/bin/conda: /anaconda3/bin/python: bad interpreter: No such file or directory
> 
> Similar question asked:
> 
> https://stackoverflow.com/questions/58293755/how-to-get-conda-to-work-on-mac-os-catalina

(Also answered on the StackOverflow site)

I have the exact same problem and this works for me:

After you move anaconda from "Relocated Items" to ~/anaconda3, edit the first line of ~/anaconda3/bin/conda file from #!/anaconda3/bin/python to #!/Users/USERNAME/anaconda3/bin/python to reflect the change.

**Comment by RyanRizzo96** [comment]
Issue SOLVED, as shown [here](https://stackoverflow.com/questions/58293755/how-to-get-conda-to-work-on-mac-os-catalina).

> After you move anaconda from "Relocated Items" to ~/anaconda3, edit the first line of ~/anaconda3/bin/conda file from #!/anaconda3/bin/python to #!/Users/USERNAME/anaconda3/bin/python to reflect the change.
> 
> Hope this helps.

**Comment by parachutel** [comment]
I copied /anaconda3 to /Users/my_user_name, and modified anaconda3 paths in ~/.bashrc and ~/.bash_profile to the one after copying, and then I edited  the first line in ~/anaconda3/bin/conda to #!/Users/my_user_name/anaconda3/bin/python. These steps work for me as a bash user.

**Comment by bruceyanwee** [comment]
> I copied /anaconda3 to /Users/my_user_name, and modified anaconda3 paths in ~/.bashrc and ~/.bash_profile to the one after copying, and then I edited the first line in ~/anaconda3/bin/conda to #!/Users/my_user_name/anaconda3/bin/python. These steps work for me as a bash user.

but you still need to do these same thing for pip and jupyter etc,I did have no idea for this problem

**Comment by parachutel** [comment]
> > I copied /anaconda3 to /Users/my_user_name, and modified anaconda3 paths in ~/.bashrc and ~/.bash_profile to the one after copying, and then I edited the first line in ~/anaconda3/bin/conda to #!/Users/my_user_name/anaconda3/bin/python. These steps work for me as a bash user.
> 
> but you still need to do these same thing for pip and jupyter etc,I did have no idea for this problem

I ran `conda update conda` after these operations, and all the prefixes (first-lines) are updated in /anaconda3/bin

**Comment by duanzy47** [comment]
> > > I copied /anaconda3 to /Users/my_user_name, and modified anaconda3 paths in ~/.bashrc and ~/.bash_profile to the one after copying, and then I edited the first line in ~/anaconda3/bin/conda to #!/Users/my_user_name/anaconda3/bin/python. These steps work for me as a bash user.
> > 
> > 
> > but you still need to do these same thing for pip and jupyter etc,I did have no idea for this problem
> 
> I ran `conda update conda` after these operations, and all the prefixes (first-lines) are updated in /anaconda3/bin. I exported enviroment.yml files and reinstalled the envs from them and they work.

This "conda update conda" worked for me to solve the path problem in all files at anaconda3/bin

**Comment by bruceyanwee** [comment]
> > > I copied /anaconda3 to /Users/my_user_name, and modified anaconda3 paths in ~/.bashrc and ~/.bash_profile to the one after copying, and then I edited the first line in ~/anaconda3/bin/conda to #!/Users/my_user_name/anaconda3/bin/python. These steps work for me as a bash user.
> > 
> > 
> > but you still need to do these same thing for pip and jupyter etc,I did have no idea for this problem
> 
> I ran `conda update conda` after these operations, and all the prefixes (first-lines) are updated in /anaconda3/bin. I exported enviroment.yml files and reinstalled the envs from them and they work.

conda update conda works for me ,T.T

**Comment by seulert** [comment]
> > > I copied /anaconda3 to /Users/my_user_name, and modified anaconda3 paths in ~/.bashrc and ~/.bash_profile to the one after copying, and then I edited the first line in ~/anaconda3/bin/conda to #!/Users/my_user_name/anaconda3/bin/python. These steps work for me as a bash user.
> > 
> > 
> > but you still need to do these same thing for pip and jupyter etc,I did have no idea for this problem
> 
> I ran `conda update conda` after these operations, and all the prefixes (first-lines) are updated in /anaconda3/bin. I exported enviroment.yml files and reinstalled the envs from them and they work.

Just tried it -- **doesn't work for me as a `zsh` user**. I switched the shell right after the update to Catalina and was using `bash` before that. 
The `zshrc` file already shows the new path (`/User/myuser/...`) but the `conda update conda` has no effect on the other commands such as `jupyter`.

**Comment by zmhhmz** [comment]
> > > > I copied /anaconda3 to /Users/my_user_name, and modified anaconda3 paths in ~/.bashrc and ~/.bash_profile to the one after copying, and then I edited the first line in ~/anaconda3/bin/conda to #!/Users/my_user_name/anaconda3/bin/python. These steps work for me as a bash user.
> > > 
> > > 
> > > but you still need to do these same thing for pip and jupyter etc,I did have no idea for this problem
> > 
> > 
> > I ran `conda update conda` after these operations, and all the prefixes (first-lines) are updated in /anaconda3/bin. I exported enviroment.yml files and reinstalled the envs from them and they work.
> 
> Just tried it -- **doesn't work for me as a `zsh` user**. I switched the shell right after the update to Catalina and was using `bash` before that.
> The `zshrc` file already shows the new path (`/User/myuser/...`) but the `conda update conda` has no effect on the other commands such as `jupyter`.

switch back to bash works well

**Comment by msarahan** [comment]
Anaconda will be publishing a blog post later today on this issue.  We are working on a tool to help users transition.  We can't retroactively fix old installations, but we should be able to make new installers that avoid the problem.

Locking this issue to prevent this reply from getting buried.  We will post the blog link here when it is available.

**Comment by msarahan** [comment]
Blog post is at https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/
