### ISSUE TITLE
anaconda-navigator can't be launched

### ISSUE THREAD

**Issue by zhiruiwang** [ContinuumIO/anaconda-issues#1099]
I recently update my qt and qtpy(and maybe other packages) to the latest version, however after that my anaconda-navigator can't be launched. I wonder is that the dependency of anaconda-navigator that cause the problem? Could you tell me which version of qt and qtpy or any other pachages should I downgrade to? My anaconda-navigator version is 1.2.3.

**Comment by goanpeca** [comment]
Hi @zhiruiwang you need to downrgarde qtpy to 1.0 version while we release a fix for it in a couple of days.

You can go to the command prompt and type

`conda install qtpy=1.0` and then naviagator should work. Also just to be sure can you go to the command line and launch Navigator from there to see if we get any error trace?

`anaconda-navigator`

**Comment by goanpeca** [comment]
This has been fixed with the latest version of both qtpy and Navigator

You can update navigator by going to the command line and typing

`conda update anaconda-navigator`

or

`conda update anaconda` to update to the latest anaconda version (4.2)
