### ISSUE TITLE
New unsaved notebook will not print. Save required first

### ISSUE THREAD

**Issue by root-11** [ContinuumIO/anaconda-issues#11]
A repeatable (cosmetic) bug:

A new unsaved notebook does not display correctly unless saved first.
After saving the notebook displays correctly.

Steps to repeat:
1. create new notebook.
2. enter any code in cells.
3. select file --> print view.
4. print view will be a blank cell.

Steps to resolve:
5. close print view tab
6. save notebook 
7. select file --> print view.
print view is now correct.

proposed solution: AutoSave before calling print view.

Build/release: Anaconda-1.6.2-Windows-x86_64
Installer: Windows 64-bit / 289M / md5: 80bc3fe5f8d2f83110eee775946ed3b8

**Comment by goanpeca** [comment]
This probably belongs to the Notebooks repository.
