### ISSUE TITLE
Navigator icon is missing from start menu

### ISSUE THREAD

**Issue by koustav19** [ContinuumIO/anaconda-issues#1100]
Updated navigator from version 1.2.1 to 1.2.3. After that the Anaconda Navigator icon is missing from Windows 10 start menu.

**Comment by koustav19** [comment]
![image](https://cloud.githubusercontent.com/assets/22253442/18859261/287318c2-8490-11e6-9a50-c392d0172c6a.png)

**Comment by goanpeca** [comment]
@koustav19 thanks for reporting

----

@ilanschnell is this fixed for the new release?

**Comment by koustav19** [comment]
I can open anaconda Navigator by command 'anaconda-navigator' but showing errors on cmd.

**Comment by goanpeca** [comment]
Can you paste the errors?

**Comment by koustav19** [comment]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\XXX>anaconda-navigator
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by goanpeca** [comment]
Yikes!, this is fixed i the next release coming tomorrow, can you try tomorrow :-), sorry for the trouble

**Comment by koustav19** [comment]
Thank you very much for the help.

**Comment by freyreeste** [comment]
I received an major update for Windows 10, after which I cannot find Condas' icons except for Anaconda Prompt.

I can manage to run the Anaconda Cloud though with the comand anaconda-navigator. However, there appears an error message saying: libpng warning: iccp : known incorrect sRGB profile. 

Please advice

**Comment by koustav19** [comment]
Thank you, problem has been solved.

**Comment by koustav19** [comment]
Now navigator is crashing...
![image](https://cloud.githubusercontent.com/assets/22253442/18901331/b75ab37e-8567-11e6-996b-c220dcedca2b.png)

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by amberpande** [comment]
After installing Anaconda in Windows 10 but I'm unable to find Anaconda3 folder in start menu and also I'm not able to find Anacinda Navigator, Anaconda Prompt, Spyder in the installed directory.

**Comment by manu-prakash-choudhary** [comment]
after installing anaconda3 unable to find it in start menu

**Comment by thecriticalpoint** [comment]
Here in 2021 with this same GDMF issue. I've uninstalled and removed the folders left behind, rebooted, re-installed. This blows.

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/124770210-bb7e2300-df6c-11eb-9024-d4a344a2eb15.png)

![image](https://user-images.githubusercontent.com/4510984/124770242-c3d65e00-df6c-11eb-8bf1-76930cafa666.png)

![image](https://user-images.githubusercontent.com/4510984/124770269-c933a880-df6c-11eb-8a81-51e3d0127021.png)
