### ISSUE TITLE
MD5 mismatch for vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2

### ISSUE THREAD

**Issue by xhochy** [ContinuumIO/anaconda-issues#11004]
At the moment all Windows builds in conda-forge fail due to an md5 mismatch in `vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2`:

```
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/win-64/vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2'.
  download saved to: C:\Miniconda\pkgs\vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2
  expected md5 sum: dfe2f62e921307f44e554b7c47aee31f
  actual md5 sum: 41f6a336e854ee8df80f70574d9b7883
```

**Comment by xhochy** [comment]
FYI, this is currently popping up again:

```
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/win-64/vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2'.
  download saved to: C:\Miniconda\pkgs\vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2
  expected md5 sum: dfe2f62e921307f44e554b7c47aee31f
  actual md5 sum: 41f6a336e854ee8df80f70574d9b7883
```

Source: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=42146&view=logs

cc @msarahan

**Comment by msarahan** [comment]
I manually verified that dfe2f62e921307f44e554b7c47aee31f is the correct md5, both on our reference server behind the CDN and by downloading the file manually from repo.anaconda.com/pkgs/main/win-64.  You may have a caching proxy between you and our servers.  We can try to bump the build number, but if you need this file, you really need to figure out how to clear out the proxy that has the old file.

I explained this on gitter at https://gitter.im/conda-forge/conda-forge.github.io?at=5d0283f05656e6268b93f158

**Comment by msarahan** [comment]
We are uploading build number 11 now.  Hopefully that clears things up.

**Comment by forrestwaters** [comment]
Build 11 has been uploaded which should fix this going forward.
