### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Asilve00** [ContinuumIO/anaconda-issues#1101]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator -> pyqt 4.*
  - anaconda-navigator -> python 2.7*|3.4*
  - matplotlib ==1.5.3
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64;x86_64;i386', 'platform': 'osx-64', 'language': 'en', 'conda': '4.2.8', 'qt': '4.8.7', 'python': '3.5.2', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
Hi @Asilve00  the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type:

`conda update anaconda-navigator`
