### ISSUE TITLE
can't find anaconda-navigator start menu

### ISSUE THREAD

**Issue by kerenbir** [ContinuumIO/anaconda-issues#11014]
### Actual Behavior
just install anaconda on my windows 10 laptop but cant find anaconda-navigator start menu

### Expected Behavior
just watch youtube they give tutorial how to installing anaconda and they have anconda-navigator start menu but not for me

### Steps to Reproduce
install anconda

##### Anaconda or Miniconda version:
Anaconda 2019.03 for Windows Installer

##### Operating System:
windows 10
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Closing. Insufficient information.  You may find the troubleshooting section in the documentation helpful.  https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#cannot-see-anaconda-menu-shortcuts-after-installation-on-windows
