### ISSUE TITLE
Website hacked?

### ISSUE THREAD

**Issue by dhirschfeld** [ContinuumIO/anaconda-issues#11025]
Not sure where to report this but it seems your website may have been hacked?

https://www.anaconda.com/updated-statement-about-our-relationship-with-datacamp/

![image](https://user-images.githubusercontent.com/881019/59646046-640b8f80-91b8-11e9-986f-b81e14f4048f.png)

**Comment by msarahan** [comment]
Nice. Thanks for letting us know.

**Comment by dhirschfeld** [comment]
Now that you're aware, feel free to close this...

**Comment by mungojam** [comment]
looks like it may have happened again:

this was in my feedly feed:
![image](https://user-images.githubusercontent.com/3154635/66001155-d9b21780-e498-11e9-9130-36ad1e3de00f.png)
