### ISSUE TITLE
New version of R (3.6.x)

### ISSUE THREAD

**Issue by j-hartshorn** [ContinuumIO/anaconda-issues#11027]
When will the default channels get updated with the new versions of R and dependencies built to match?

Final release of R 3.6.1 (Action of the Toes) is scheduled for release on Friday 2019-07-05. With that, the R language will be a whole major release behind on the anaconda official channels.

**Comment by csoja** [comment]
Looks like R 3.6.0 packages went up on the Anaconda R channels about a day after you created this issue.  https://anaconda.org/r/r-base https://repo.anaconda.com/pkgs/r/linux-64/ https://repo.anaconda.com/pkgs/r/
