### ISSUE TITLE
Dask 2.0

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/anaconda-issues#11047]
We recently announced Dask 2.0, which, among other things, drops support for Python 2.  I bring this up for two reasons:

1.  We plan to release a blogpost about this announcement on Thursday, and would love to be able to say `conda install dask` in that announcement and have people get the right version.  No worries if this doesn't work out.  We can always way that they'll be there soon.
2.  Some changes to the recipe may be needed on Anaconda's end.  The relevant changes to the recipes in conda-forge are here:
    -  https://github.com/conda-forge/dask-core-feedstock/pull/41
    -  https://github.com/conda-forge/distributed-feedstock/pull/84
    -  https://github.com/conda-forge/dask-feedstock/pull/79

**Comment by jjhelmus** [comment]
Congratulation on the release!  I've incorporated the recipe changes from conda-forge into the Anaconda recipes.  `dask`, `dask-core` and `distributed` have all been updated to 2.0.0 and are now available in `defaults`.
