### ISSUE TITLE
Check that bzip2 is installed

### ISSUE THREAD

**Issue by jgmorrison** [ContinuumIO/anaconda-issues#1104]
Anaconda does not check if bzip2 is installed on Linux systems during installation and results in an error during the Anaconda installation:

    tar (child): bzip2: Cannot exec: No such file or directory
    tar (child): Error is not recoverable: exiting now
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now

Some versions of Centos7/RHEL 7 do not have bzip2 by default. It would be great to check for bzip2 before the installation progresses and provided better output to suggest that bzip2 be installed before proceeding.

**Comment by ilanschnell** [comment]
The error message already tells the user that `bzip2` is not installed (although maybe not perfect).  Closing issue.
