### ISSUE TITLE
Issues with OpenBLAS 3.6 on SkylakeX

### ISSUE THREAD

**Issue by seberg** [ContinuumIO/anaconda-issues#11043]
Maybe this was already opened (or I am searching the wrong place). But we recently got some issues in NumPy using not very up to date versions of OpenBLAS in on Skylakex architectures.

I think Openblas basically got a bunch of new kernels and they were buggy. This affected svd through dgemm. Most discussion about these issues is probably in https://github.com/numpy/numpy/issues/13401 which also links to the OpenBLAS issues. Others (and one newer) are: https://github.com/numpy/numpy/issues/13478 and https://github.com/numpy/numpy/issues/13828

On NumPy 1.16.4 we ask to use OpenBLAS >0.3.7 I think to mitigate this. I did not keep up with the details, but it seems that it may be good to update the packaged openblas version, or maybe to disable the affected SkylakeX kernels.

**Comment by jjhelmus** [comment]
@seberg Sorry it look so long to look into this.  I'm applying the patch the conda-forge applies to OpenBLAS, conda-forge/openblas-feedstock#2111 to the openblas package distributed by Anaconda which I believe should fix this issue.  Please let me know if there is still unusual with Skylake-X when using these packages.
