### ISSUE TITLE
Fresh Anaconda install : conda remove wants to remove anaconda-2019.03-py37_0

### ISSUE THREAD

**Issue by moulla** [ContinuumIO/anaconda-issues#11058]
### Actual Behavior

Freshly installed Anaconda3-2019.03-Windows-x86_64.exe on win10.

>> conda remove scikit-image --offline

results in 

The following packages will be REMOVED:

  anaconda-2019.03-py37_0
  scikit-image-0.14.2-py37ha925a31_0

### Expected Behavior

Remove just scikit-image

### Steps to Reproduce

Freshly installed Anaconda3-2019.03-Windows-x86_64.exe on win10.

>> conda create -n baseclone --clone base (this step may not be needed, but I have wasted a lot of time over a corrupt conda update already today)

on completion:
>> conda remove scikit-image --offline

results in 

The following packages will be REMOVED:

  anaconda-2019.03-py37_0
  scikit-image-0.14.2-py37ha925a31_0

##### Anaconda or Miniconda version:

Freshly installed Anaconda3-2019.03-Windows-x86_64.exe on win10.

##### Operating System:
win10

##### `conda info`

<details>

```

     active environment : base
    active env location : C:\Users\x\AppData\Local\Continuum\anaconda3
            shell level : 1
       user config file : C:\Users\x\.condarc
 populated config files : C:\Users\x\.condarc
          conda version : 4.6.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\x\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\x\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\x\.conda\pkgs
                          C:\Users\x\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\x\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\x\.conda\envs
                          C:\Users\x\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
na

```

</details>

**Comment by msarahan** [comment]
Anaconda is a metapackage.  It represents a tested, known working configuration.  When you remove a package from that configuration, you are removing that state.  It is not removing any other packages, and nothing is wrong.
