### ISSUE TITLE
Anaconda 4.7.5 - Warning about conda-build <3.18.3 and issues with python packages

### ISSUE THREAD

**Issue by 00krishna** [ContinuumIO/anaconda-issues#11062]
### Actual Behavior

@csoja or others, the problem here is two-fold. First the problem is communication. So the Anaconda blog posted a [message](https://www.anaconda.com/how-we-made-conda-faster-4-7/) on Jun 25 about release 4.7 and how the made Anaconda faster. So that is great. But none of the users were actually warned about this change until after it was released. And what happened was that this change broke a lot of people's environments. I am not sure if it was an issue of testing or such, but a lot of people seem to have broken environment after this update.

I posted a Stack Exchange question about this when I ran into it. The post was released 2 days ago and has 1,919 view already. I basically got a gold badge (1,000 views) in 1 day because so many other people ran into the same problems. They all got warnings an all of a sudden some of the packages in their environments were uninstalled when they did an update and there were no instructions on how to roll back the changes, etc. 

Here is the post itself and you can read the comments. 

https://stackoverflow.com/questions/56765518/anaconda-4-7-5-warning-about-conda-build-3-18-3-and-issues-with-python-packag

In my case I updated anaconda with a simple `conda update --all` and then a message asked me to update the `defaults`. I did that, and all of a sudden `jupyter lab` was uninstalled and some other packages. And then I could not reinstall the packages. And trying to reinstall `conda-build` did not work until a few different tried, etc. 

The sad thing is that the improvements to the packaging system and its speed are actually really good things. I mean that is a worthy achievement. The problem is that in rolling the change out in this manner, it will look like a testing failure, or a communication failure. So something that is actually an improvement and an achievement actually looks like a failure. 

### Expected Behavior

What should happen is that a communication should have gone out to users that a change in the packaging system was going to happen. It is a pretty big change. Then users's would have expected this kind of update and how to roll it back if needed. 

I expected that I would do a `conda update --all` and it would keep my environment intact and not uninstall some packages that I was using. 

### Steps to Reproduce

I write the details in the Stack Exchange Post, so you can find them there. 

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by msarahan** [comment]
bugs happen.  These breakages were not intentional.  Not copying and pasting your details here makes us work harder and takes time that we could be spending actually troubleshooting.  Please respect our time.  An issue regarding update --all is at https://github.com/conda/conda/issues/8842
