### ISSUE TITLE
anaconda latest update issue

### ISSUE THREAD

**Issue by Misbahrani** [ContinuumIO/anaconda-issues#11061]
After the update, the anaconda prompt is not showing in my apps even. How to get it back? or I have to re-install the software again, as I have done this once.

**Comment by Misbahrani** [comment]
I am using windows 10.

**Comment by ECon87** [comment]
Same issue here. I tried "update index", update the navigator and so on, but nothing works. Cannot really create a new environment with python 3 either using the navigator. I can still open the apps with the terminal though.

**Comment by 634549** [comment]
Same thing happened to me. This is a disaster for me because the update also uninstalled two packages that are essential for my work and the Anaconda navigator does not show them.

**Comment by makeyourownalgorithmicart** [comment]
there seem to be many update related issues .. I know this is a volunteer project and we can'r demand .. so my suggestion is to focus limited resources more on stability and reliability and less on new features and GUI apps etc which are always secondary to the ability to do work without issue

**Comment by msarahan** [comment]
Please see https://github.com/conda/conda/issues/8842 - closing to consolidate discussion there.
