### ISSUE TITLE
anaconda-navigator blocking Qt 5.x installation

### ISSUE THREAD

**Issue by brylie** [ContinuumIO/anaconda-issues#1107]
I am trying to install Spyder 3.0, which was recently released. However, when trying to upgrade Qt to 5.x, I get the following message:

> conda install qt=5.*
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator -> pyqt 4.*
  - qt 5.*

How can I upgrade Qt to 5.x, while anaconda-navigator is installed?

**Comment by ccordoba12** [comment]
I think you need to update Navigator before trying to update to Qt5

**Comment by brylie** [comment]
After I uninstall anaconda-navigator and upgrade Spyder, I tried to re-install anaconda-navigator. However, it seems to want to downgrade several packages, including Qt and Spyder:

> The following NEW packages will be INSTALLED:
>
>    anaconda-navigator: 1.2.3-py35_0     
>
> The following packages will be DOWNGRADED due to dependency conflicts:
>
>    matplotlib:         1.5.3-np111py35_0 --> 1.5.1-np111py35_0
>   pyqt:               5.6.0-py35_0      --> 4.11.4-py35_4    
>  qt:                 5.6.0-0           --> 4.8.7-4          
>   qtconsole:          4.2.1-py35_1      --> 4.2.1-py35_0     
>    spyder:             3.0.0-py35_0      --> 2.3.9-py35_1

**Comment by goanpeca** [comment]
@brylie this is correct as only the new version of navigator works with Qt5. The new packages will be live tomorrow, please try again then when all these issues will be resolved.

Sorry for the inconveniences.

**Comment by brylie** [comment]
Thanks @goanpeca. No worries. I will try again soon :smiley:

**Comment by goanpeca** [comment]
@brylie we pushed the 1.3.1 release of Navigator now, can you try again

**Comment by brylie** [comment]
It works! Cool :sunglasses:

**Comment by goanpeca** [comment]
:+1:
