### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by xzstanford** [ContinuumIO/anaconda-issues#1108]
Application action error

/Users/username/anaconda/bin/python /Users/xzhang/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/xzhang/anaconda spyder=3.0.0: The following specifications were found to be in conflict:
  - pyqtgraph -> pyqt 4.*
  - pyqtgraph -> python 2.7*|3.4*
  - spyder 3.0.0*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'conda': '4.1.11', 'qt': '4.8.7', 'python': '3.5.2', 'pyqt': '4.11.4', 'version': '1.2.2', 'platform': 'osx-64'}

**Comment by goanpeca** [comment]
Hi @xzstanford the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type:

`conda update anaconda-navigator`
