### ISSUE TITLE
Issues with linking of QT package on Mac OS 10.12.1

### ISSUE THREAD

**Issue by martinpsz** [ContinuumIO/anaconda-issues#1109]
This is the error message I am receiving:

<img width="567" alt="screen shot 2016-09-27 at 7 14 28 pm" src="https://cloud.githubusercontent.com/assets/8620006/18898469/a9f77720-84e6-11e6-9030-067a8aed4302.png">

I have attempted to download the packages directly from anaconda's site and placing the files into my directory of packages. This does not resolve the linking issue. Any ideas on how I can clear this issue up?

**Comment by ccordoba12** [comment]
Any ideas about this @mingwandroid?

**Comment by mingwandroid** [comment]
@martinspz, please show everything you did to get into this situation, going from not having `anaconda` installed at all to encountering this problem so that I can try to reproduce it, because my naive attempt: `conda create -n qt4test anaconda-navigator=1.2.3` worked fine.

From the information you've given, it looks to me as though you've created an environment which is named, literally, `//anaconda` which would be an invalid name for an environment. I tried to create such an environment but was unable to:

```
$ conda create -n //anaconda anaconda-navigator=1.2.3

CondaValueError: Value error: '/' not allowed in environment name: //anaconda
```

**Comment by martinpsz** [comment]
First, my environment ‘//anaconda’, while probably a bad set up, has not posed issues in the past. I have had that setup for a while now. 

Second, I typically update packages by opening Terminal on Mac, typing in “conda update —all”. This results, typically, in an output that tells me the packages that need updating and it asks if i want to update them. This procedure, has historically at least, worked for me to keep up to date on software.

The linking issue came about recently when Qt required an upgrade. Not related to the anaconda navigator. Here is what I get when attempting to update again today:



Thanks for any advice on resolving this issue.


Martin

**Comment by mingwandroid** [comment]
For me to help I need to reproduce the issue, can you provide the details I asked for previously so that I can try to do that?

**Comment by martinpsz** [comment]
Ray,

I appreciate your willingness to help. 

It has been a long while since I set up Anaconda on my desktop. I downloaded the Anaconda software from the site and went through the usual installation procedure. I don’t recall if I did anything unusually that, many months later, would be lead to the issue I am having. 

Perhaps I will just uninstall, reinstall and set it up such that the directory is not //anaconda.

M

**Comment by mingwandroid** [comment]
Yeah, that sounds sensible.

Out of interest, did you install from the GUI installer or using the shell script?

**Comment by martinpsz** [comment]
GUI installer.

Updating using shell script.

**Comment by mingwandroid** [comment]
#martinpsz, in your opinion, can this be closed?

**Comment by martinpsz** [comment]
Yes, issue was fixed by reinstall.

**Comment by mingwandroid** [comment]
Thanks.
