### ISSUE TITLE
AnacondaCloud - another user posted my package as their own. How to remove?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [ContinuumIO/anaconda-issues#11093]
### Actual Behavior

https://anaconda.org/koraltp/repo

A 4 month old (over 800 commits behind current) copy of my package (PySimpleGUI) was posted by this user.  I don't know how to reach them nor how to get the package removed.

### Expected Behavior

PySimpleGUI should not be listed on AnacondaCloud, at all.

### Steps to Reproduce

Go here and you'll see this:

https://anaconda.org/koraltp/repo

![image](https://user-images.githubusercontent.com/13696193/60742415-52a5df80-9f3b-11e9-809c-fc7e351680bc.png)

I just want my copyrighted package and documentation to **_not_** be posted on Anaconda's Website, especially since I'm now seeing complaints posted on the net that this software is old, doesn't match the documentation ,etc.

What are my remedies?

**Comment by msarahan** [comment]
Your license is GPL.  That user is well within their rights to post packages of your software, so long as they adhere to the terms of the GPL.  This is not an employee of Anaconda, it is a community member using the service that we provide.  If you can't reach that user somehow, I don't think you have any recourse.

**Comment by msarahan** [comment]
Really, the best way to get people to stop complaining is to guide them towards a better package being available: https://conda-forge.org

I'm not suggesting that you do that work, but rather you should tell your users "if you want to use this with conda, you need to go make it available on conda-forge.  That's the right way to do it."

**Comment by MikeTheWatchGuy** [comment]
We both can post the same named package?

**Comment by MikeTheWatchGuy** [comment]
@msarahan  can I ask if you're an Anaconda employee and if this is an official corporate stance?

**Comment by msarahan** [comment]
> We both can post the same named package?

Yes, unlike PyPI, every user has their own channel.  Each channel is roughly analogous to PyPI.

> @msarahan can I ask if you're an Anaconda employee and if this is an official corporate stance?

I am an Anaconda employee, but I'm not claiming to have an official response in any legal sense.  I'm more of an oompa-loompa.

**Comment by MikeTheWatchGuy** [comment]
The reason I posted an Issue was to get the aid of an Anaconda employee.   Another developer that seemed more up on these things said this:

>  I have to say its nearly a 1on1 copy. And I think Anaconda won't like that if you notify them about it. Minimum 10 mayor changes is rule of thumb.

It in fact IS a 1 for 1 copy of my entire project.  Forks are one thing....  they're labeled as such.  People are able to see that indeed the project was not created by the person posting it.  But here, the poster made no effort to:
1. Keep the code up to date
2. Say anything about it being a re-distribution of someone else's work

I can see if you're a Conda user, then having a private copy of someone's PyPI package could make sense.  But to publicly put it out there as their own, I don't understand why the Anaconda company would encourage such behavior on their servers.  As you pointed out, it's someone using your company's service.

So it's join them on the Anaconda servers as my only recourse ( or move along)?  It feels like a "our hands are tied" kinda stance, but yet it's your own private servers.  You own them and set the policies for them.  

If / when my license changes such that distribution is no longer part of the license, I can count on Anaconda enforcing it?

**Comment by msarahan** [comment]
I think you're fundamentally misunderstanding what's happening here.  This person is not claiming your work as their own.  They took a snapshot of your code at a particular revision, with our site as a mirror of sorts.  Look, they kept your acknowledgements:

```
Author
MikeB

Demo Code Contributors
JorjMcKie - PDF and image viewers (plus a number of code suggestions) 
Otherion - Table Demos Panda & CSV. Loads of suggestions to the core APIs

License
GNU Lesser General Public License (LGPL 3) +

Acknowledgments
JorjMcKie was the motivator behind the entire project. His wxsimpleGUI concepts sparked PySimpleGUI into existence
Fredrik Lundh for his work on tkinter
Ruud van der Ham for all the help he's provided as a Python-mentor. Quite a few tricky bits of logic was supplied by Ruud. The dual-purpose return values scheme is Ruud's for example
Numerous users who provided feature suggestions! Many of the cool features were suggested by others. If you were one of them and are willing to take more credit, I'll list you here if you give me permission. Most are too modest
moshekaplan/tkinter_components wrote the code for the Calendar Chooser Element. It was lifted straight from GitHub
Bryan Oakley for the code that enables the grab_anywhere feature.
Otherion for help with Tables, being a sounding board for new features, naming functions, ..., all around great help
agjunyent figured out how to properly make tabs and wrote prototype code that demonstrated how to do it
jfongattw huge suggestion... dictionaries. turned out to be
one of the most critical constructs in PySimpleGUI
venim code to doing Alt-Selections in menus, updating Combobox using index, request to disable windows (a really good idea), checkbox and tab submits on change, returning keys for elements that have change_submits set, ...
rtrrtr Helped get the 2.7 and 3.x code unified (big damned deal)
Tony Crewe (anthony.crewe@gmail.com) Generously provided his classroom materials that he has written to teach a GUI course. If you're an educator and want to trade materials with Tony, he would like to hear from you.
spectre6000 - Readme updates
jackyOO7 - Demo programs. OpenCV with realtime image processing, popup keyboard, input Combo read only option.
AltoRetrato - Fonts for multiline and combo
frakman1 - Sample code error
deajan - Custom button tex
```

To be honest, I don't understand the purpose of a PyPI mirror on our site.  Conda packages would make a lot more sense - then the usage goal would just be to make it easier to use with conda as the package manager, instead of pip.  But all that said, I really, really don't think this user crosses any legal boundaries, and anyone who uses this package over your PyPI one is confused and lost.  Conda does not encourage use of PyPI mirrors on anaconda.org at all.  This is really a fringe use case, and I think more than anything, it comes down to SEO of some sort making our page show up in searches for your package name.  Trust me, we have a lot of heartburn over people mirroring our packages.  I understand your sentiment, but you need to talk to that user, and I don't think there's nothing you can force that user to do.  Even if you change license now, that only applies going forward.  All old code is still covered under the old license.

**Comment by MikeTheWatchGuy** [comment]
I really wish I could talk to that user.  That's where I started.... "How can I contact user .....?"
Anyway, hey, look, I really appreciate you answering SUPER quick, researching the issue to the point you're looking at code, documentation.  And you've been really educational and approached it all from that kind of direction.  I can really appreciate that and thank you for the effort.  Not everyone (not many) would handle this the way you did.

**Comment by mingwandroid** [comment]
@MikeTheWatchGuy that's really nice of you. Thanks!

**Comment by MikeTheWatchGuy** [comment]
Oh!  I REALLY didn't mean to bring anyone down that's helping me here.  @msarahan , Mike, you were awesome to work with on this.  Damn, I really hope both you guys know what a great job you're doing here.  Making stuff a priority, being mega-professional yet showing empathy.  That one little touch of empathy that Mike added in his explanation made all the difference in the world.  I feel bad that it did.  Anyway, thanks again and I'll keep learning, promise you there.

**Comment by MikeTheWatchGuy** [comment]
Hey, I just noticed a problem that's either a bug or an intentional removal of the license info.

![image](https://user-images.githubusercontent.com/13696193/60749043-5b5ddc00-9f62-11e9-9c50-d346079b5f87.png)


See on the left how it says LGPL3+.  It hasn't changed in a very very long time.

And then on the Conda page it says "unspecified"

![image](https://user-images.githubusercontent.com/13696193/60749051-7c263180-9f62-11e9-8017-f61d7fa3c88d.png)


Maybe that's enough for someone to get in contact with this guy?
