### ISSUE TITLE
anaconda command not found in custom environment

### ISSUE THREAD

**Issue by Xunius** [ContinuumIO/anaconda-issues#11124]
### Actual Behavior

I installed anaconda3 for Linux, version 4.6.x, using default settings (like putting the installation place at `~/anaconda3` and letting conda init.

I created a new env with nothing but python 3.7 in it, activated it, and tried to use `anaconda search` to search some package. Then I got `anaconda command is not found` error. `which anaconda` gives nothing. But the same command in the `base` env works fine.

I then updated conda to 4.7.9, the same problem happens.

### Expected Behavior

`anaconda search <package>` works both in the `base` and custom envs, at least this is what used to be in older versions of anaconda.

### Steps to Reproduce

I didn't try to reproduce this on a different system.

##### Anaconda or Miniconda version:

Anaconda3-2019.03-Linux-x86_64.sh

##### Operating System:

Linux mint 19.1

##### `conda info`

<details>

```
     active environment : base
    active env location : /home/guangzhi/anaconda3
            shell level : 1
       user config file : /home/guangzhi/.condarc
 populated config files : 
          conda version : 4.7.9
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : /home/guangzhi/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/guangzhi/anaconda3/pkgs
                          /home/guangzhi/.conda/pkgs
       envs directories : /home/guangzhi/anaconda3/envs
                          /home/guangzhi/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.9 requests/2.21.0 CPython/3.7.3 Linux/4.18.0-25-generic linuxmint/19.1 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```

</details>

##### `conda list --show-channel-urls`

I don't think this is relevant.

**Comment by msarahan** [comment]
conda 4.6+ has better isolation.  `anaconda` is a command that comes from the `anaconda-client` package.  It is only available when an env containing that package is active.  You can stack activation using the `--stack` CLI flag.
