### ISSUE TITLE
Can not update navigator

### ISSUE THREAD

**Issue by HJMRX** [ContinuumIO/anaconda-issues#11135]
### Actual Behavior

I can not update navigator

### Expected Behavior.

I can update navigator.

### Steps to Reproduce

After opening the anaconda navigator, the pop-up window prompted me to update the anaconda navigator. I chose yes. The pop-up window then prompts me to close Anaconda navigator. When I chose to do so, there was no response after closing it. When I chose not to, there was still no response.
If I use the upgrade application in the upper right corner, I will open anaconda-navigator-updater.bat first, but it quits immediately. Then there will be a choice of whether to quit the navigator or not. The result is the same as the previous one. I can't update the navigator.

##### Anaconda or Miniconda version:

anaconda navigator 1.9.6
##### Operating System:
windows 10
##### `conda info`

anaconda-navigator-updater.bat :
chcp 936
call F:\Anaconda\Scripts\activate F:\Anaconda
navigator-updater --latest-version 1.9.7 --prefix F:\Anaconda >C:\Users\шЋОѕУїШєйт\.anaconda\navigator\scripts\anaconda-navigator-updater-out-1.txt 2>C:\Users\шЋОѕУїШєйт\.anaconda\navigator\scripts\anaconda-navigator-updater-err-1.txt

anaconda-navigator-updater-err-1.txt:
'updater'is not an internal or external command, nor is it a runnable program
Or batch files.

Anaconda-navigator-updater-out-1.txt has no content

**Comment by csoja** [comment]
This may be a unicode issue.  Can you use the Anaconda Prompt to update Navigator?
Open the Anaconda Prompt and execute the following commands:
conda update anaconda-navigator

**Comment by HJMRX** [comment]
Thank you very much for your answer. I successfully updated Anaconda navigator
