### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by xzstanford** [ContinuumIO/anaconda-issues#1114]
Application action error

/Users/username/anaconda/bin/python /Users/xzhang/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/xzhang/anaconda spyder=3.0.0: UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqtgraph -> pyqt 4.*
  - pyqtgraph -> python 2.7*|3.4*
  - spyder 3.0.0*
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'pyqt': '4.11.4', 'platform': 'osx-64', 'python': '3.5.2', 'conda': '4.2.9', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'version': '1.2.2'}

**Comment by goanpeca** [comment]
Hi @xzstanford the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type:

`conda update anaconda-navigator`

**Comment by xzstanford** [comment]
Hi, thanks.
Have use conda update anaconda-navigator to updated version of navigator.

However, it still in conflict.
Thanks.

/Users/x/anaconda/bin/python /Users/x/anaconda/bin/conda install --yes
--json --force-pscheck --prefix /Users/x/anaconda spyder=3.0.0:
UnsatisfiableError: The following specifications were found to be in
conflict:
- spyder 3.0.0*
Use "conda info " to see the dependencies for each package.

**Comment by goanpeca** [comment]
@xzstanford could you run `conda info` and `conda list` on the command line and paste the output?

**Comment by xzstanford** [comment]
Current conda install:


               platform : osx-64

          conda version : 4.2.9

       conda is private : False

      conda-env version : 4.2.9

    conda-build version : 0+unknown

         python version : 3.5.2.final.0

       requests version : 2.9.1

       root environment : /Users/user/anaconda  (writable)

    default environment : /Users/user/anaconda

       envs directories : /Users/user/anaconda/envs

          package cache : /Users/user/anaconda/pkgs

           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/

                          https://repo.continuum.io/pkgs/free/noarch/

                          https://repo.continuum.io/pkgs/pro/osx-64/

                          https://repo.continuum.io/pkgs/pro/noarch/

            config file : None

           offline mode : False


=================

# packages in environment at /Users/user/anaconda:

#

alabaster                 0.7.7                    py35_0

anaconda                  custom                   py35_0

anaconda-client           1.4.0                    py35_0

anaconda-navigator        1.2.3                    py35_0

appnope                   0.1.0                    py35_0

appscript                 1.0.1                    py35_0

argcomplete               1.0.0                    py35_1

astropy                   1.1.2               np110py35_0

babel                     2.2.0                    py35_0

beautifulsoup4            4.4.1                    py35_0

bitarray                  0.8.1                    py35_0

blaze                     0.9.1                    py35_0

bokeh                     0.11.1                   py35_0

boto                      2.39.0                   py35_0

bottlechest               0.7.1                    py35_0

bottleneck                1.0.0               np110py35_0

cffi                      1.5.2                    py35_0

chardet                   2.3.0                    py35_0

chest                     0.2.3                    py35_0

cloudpickle               0.1.1                    py35_0

clyent                    1.2.1                    py35_0

colorama                  0.3.7                    py35_0

conda                     4.2.9                    py35_0

conda-build               1.20.0                   py35_0

conda-env                 2.6.0                         0

conda-manager             0.4.0                    py35_0

configobj                 5.0.6                    py35_0

cryptography              1.3                      py35_0

curl                      7.45.0                        0

cycler                    0.10.0                   py35_0

cython                    0.23.4                   py35_1

cytoolz                   0.7.5                    py35_0

dask                      0.8.1                    py35_0

datashape                 0.5.1                    py35_0

decorator                 4.0.9                    py35_0

dill                      0.2.4                    py35_0

docutils                  0.12                     py35_0

dynd-python               0.7.2                    py35_0

et_xmlfile                1.0.1                    py35_0

fastcache                 1.0.2                    py35_0

flask                     0.10.1                   py35_1

flask-cors                2.1.2                    py35_0

freetype                  2.5.5                         0

gevent                    1.1.0                    py35_0

glueviz                   0.8.2                    py35_0

greenlet                  0.4.9                    py35_0

h5py                      2.5.0               np110py35_4

hdf5                      1.8.15.1                      2

heapdict                  1.0.0                    py35_0

idna                      2.0                      py35_0

ipykernel                 4.3.1                    py35_0

ipython                   4.1.2                    py35_1

ipython_genutils          0.1.0                    py35_0

ipywidgets                4.1.1                    py35_0

itsdangerous              0.24                     py35_0

jbig                      2.1                           0

jdcal                     1.2                      py35_0

jedi                      0.9.0                    py35_0

jinja2                    2.8                      py35_0

joblib                    0.9.4                    py35_0

jpeg                      8d                            1

jsonschema                2.4.0                    py35_0

jupyter                   1.0.0                    py35_2

jupyter_client            4.2.2                    py35_0

jupyter_console           4.1.1                    py35_0

jupyter_core              4.1.0                    py35_0

libdynd                   0.7.2                         0

libpng                    1.6.17                        0

libtiff                   4.0.6                         2

libxml2                   2.9.2                         0

libxslt                   1.1.28                        2

llvmlite                  0.9.0                    py35_0

locket                    0.2.0                    py35_0

lxml                      3.6.0                    py35_0

markupsafe                0.23                     py35_0

matplotlib                1.5.1               np110py35_0

mistune                   0.7.2                    py35_1

mkl                       11.3.1                        0

mkl-service               1.1.2                    py35_0

mpmath                    0.19                     py35_0

multipledispatch          0.4.8                    py35_0

nbconvert                 4.1.0                    py35_0

nbformat                  4.0.1                    py35_0

networkx                  1.11                     py35_0

nltk                      3.2                      py35_0

nose                      1.3.7                    py35_0

notebook                  4.2.3                    py35_0

numba                     0.24.0              np110py35_0

numexpr                   2.5                 np110py35_0

numpy                     1.10.4                   py35_0

odo                       0.4.2                    py35_0

openpyxl                  2.3.2                    py35_0

openssl                   1.0.2g                        0

orange-app                1.0.1                    py35_0

orange3                   3.3.6                    py35_0

pandas                    0.18.0              np110py35_0

partd                     0.3.2                    py35_1

path.py                   8.1.2                    py35_1

patsy                     0.4.0               np110py35_0

pep8                      1.7.0                    py35_0

pexpect                   4.0.1                    py35_0

pickleshare               0.5                      py35_0

pillow                    3.1.1                    py35_0

pip                       8.1.2                     <pip>

pip                       8.1.1                    py35_1

ply                       3.8                      py35_0

psutil                    4.1.0                    py35_1

ptyprocess                0.5                      py35_0

py                        1.4.31                   py35_0

pyasn1                    0.1.9                    py35_0

pycosat                   0.6.1                    py35_0

pycparser                 2.14                     py35_0

pycrypto                  2.6.1                    py35_0

pycurl                    7.19.5.3                 py35_0

pyflakes                  1.1.0                    py35_0

pygments                  2.1.1                    py35_0

pyopenssl                 0.15.1                   py35_2

pyparsing                 2.0.3                    py35_0

PypeR                     1.1.2                     <pip>

pyqt                      4.11.4                   py35_1

pyqtgraph                 0.9.10                   py35_1

pytables                  3.2.2               np110py35_1

pytest                    2.8.5                    py35_0

python                    3.5.2                         0

python-dateutil           2.5.1                    py35_0

python.app                1.2                      py35_4

pytz                      2016.2                   py35_0

pyyaml                    3.11                     py35_1

pyzmq                     15.2.0                   py35_0

qt                        4.8.7                         1

qtawesome                 0.3.2                    py35_0

qtconsole                 4.2.1                    py35_0

qtpy                      1.0                      py35_0

readline                  6.2                           2

redis                     2.6.9                         0

redis-py                  2.10.3                   py35_0

reportlab                 3.3.0                    py35_0

requests                  2.9.1                    py35_0

rope                      0.9.4                    py35_1

ruamel_yaml               0.11.14                  py35_0

scikit-image              0.12.3              np110py35_0

scikit-learn              0.17.1              np110py35_0

scipy                     0.17.0              np110py35_0

setuptools                20.3                     py35_0

simplegeneric             0.8.1                    py35_0

singledispatch            3.4.0.3                  py35_0

sip                       4.16.9                   py35_0

six                       1.10.0                   py35_0

snowballstemmer           1.2.1                    py35_0

sockjs-tornado            1.0.1                    py35_0

sphinx                    1.3.5                    py35_0

sphinx_rtd_theme          0.1.9                    py35_0

spyder                    2.3.9                    py35_0

sqlalchemy                1.0.12                   py35_0

sqlite                    3.13.0                        0

statsmodels               0.6.1               np110py35_0

sympy                     1.0                      py35_0

terminado                 0.5                      py35_1

tesserocr                 2.1.2                     <pip>

tk                        8.5.18                        0

toolz                     0.7.4                    py35_0

tornado                   4.3                      py35_0

traitlets                 4.2.1                    py35_0

unicodecsv                0.14.1                   py35_0

werkzeug                  0.11.4                   py35_0

wheel                     0.29.0                   py35_0

xlrd                      0.9.4                    py35_0

xlsxwriter                0.8.4                    py35_0

xlwings                   0.7.0                    py35_0

xlwt                      1.0.0                    py35_0

xz                        5.2.2                         0

yaml                      0.1.6                         0

zeromq                    4.1.3                         0

zlib                      1.2.8                         0

**Comment by goanpeca** [comment]
@xzstanford this is probably related to qt

What if you do 

`conda install qt=5 pyqt=5`
and then
`conda install anaconda-navigator`
?

**Comment by xzstanford** [comment]
Hi,
I have uninstalled old version and installed updated version of Anaconda.
Thanks.
Best,
