### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sratel** [ContinuumIO/anaconda-issues#1115]
Anaconda Navigator Update error:

/Users/ratels/anaconda/bin/python /Users/ratels/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.1: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.1*
Use "conda info <package>" to see the dependencies for each package.

{'language': 'en', 'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386', 'python': '3.5.2', 'pyqt': '4.11.4', 'conda': '4.2.9', 'version': '1.2.1', 'qt': '4.8.7', 'platform': 'osx-64'}

**Comment by goanpeca** [comment]
Could you update navigator on the command line 

`conda update anaconda-navigator`

**Comment by goanpeca** [comment]
Hi @sratel any luck?

**Comment by sratel** [comment]
Unfortunately, no. The update command worked, but then when I opened Navigator it was still proposing me to update to version 1.3.1. And now Navigator doesn't open at all... Should I remove all and reinstall it ? Thank you for your help.

**Comment by sratel** [comment]
I reinstalled Anaconda and all seems to be fine now. I have Navigator 1.3.1. Thanks !

**Comment by goanpeca** [comment]
ok cool glad to hear is working now
