### ISSUE TITLE
Unable to install 2019.07, but can install 2019.03. Error "could not extract tar starting at offset..."

### ISSUE THREAD

**Issue by davidlowryduda** [ContinuumIO/anaconda-issues#11154]
### Actual Behavior

I decided to change to a more modern anaconda distribution on my webfaction server. I've used anaconda on various machines for a long time, and consider myself pretty savvy. But as this is a webfaction server, I should note that there are potentially odd permission problems and weird filesystem nonsense.

I downloaded the most 2019.07 linux x86 installer script and ran it. The installation fails very quickly. It prints out

```
PREFIX=/home/myname/anaconda3
Unpacking payload ...
[13822] Error loading Python lib '/tmp/_MEI<randomstring>/libpython3.6m.so.1.0': dlopen /tmp_MEI<randomstring>/libpython3.6m.so.1.0: failed to map segment from shared object: Operation not permitted
ERROR: could not extract tar starting at offset 00000000000020980+9231072+2
```

I thought to try one version older and tried to install Anaconda 2019.03, and that worked without any problem. Thus it seems that something important changed in the last 4 months.

### Expected Behavior

I expected anaconda to install as normal.

### Steps to Reproduce

1. Be on a webfaction server
2. Download latest linux x86 anaconda installer
3. Attempt to install

##### Anaconda or Miniconda version:

Installation fails with linux x86 2019.07, but succeeds with linux x86 2019.03.

##### Operating System:

CentOS 7 (on webfaction server)

I note that I have not given any conda_info, since this occurs at installation and is earlier than conda_info.

**Comment by mingwandroid** [comment]
I believe you have mounted /tmp as noexec. Please set TMP to somewhere else from which you can execute software.

**Comment by mingwandroid** [comment]
But if that is the case we need to do our temporary extracts somewhere else!

**Comment by davidlowryduda** [comment]
To make sure that I understand, when you say to set TMP to somewhere else, you mean something like `export TMP=/my/favorite/tmp/directory`? Or is there some other way that I should do this? I tried to read through the script to see if it mentioned something like setting a TMP directory, but I must have missed it (or missed some linux standard).

**Comment by mingwandroid** [comment]
Yes, plesse try that, but only temporarily for the install.

**Comment by davidlowryduda** [comment]
I can confirm that setting TMP to some random temporary folder that I have permissions to works just fine. In particular, in case anyone else wants to just copy and paste something, I did
```
cd
mkdir TMPconda
TMP=~/TMPconda bash Anaconda3-2019.07-Linux-x86_64.sh
```
and it proceeded just fine.

@mingwandroid Out of curiousity, is there something that I could have read to realize that anaconda used the TMP environmental variable?

**Comment by davidlowryduda** [comment]
I should add that I could close this since my original issue was resolved and I can now install the most recent anaconda. But I think there remains something here to be cleared up --- either through making the dependence on the TMP environment variable more transparent or to by default just make a directory like `anaconda3/tmp` and use that directory.

**Comment by rrigdon** [comment]
Hi @davidlowryduda, thanks for your feedback. I'll update the docs to provide more clarity around this topic.

**Comment by Pastthesun** [comment]
So I had this error too, but I just ran the bash Anaconda3-2019.07-Linux-x86_64.sh -u    
using a folder I created in my /data/anaconda3 folder by:
$ sudo mkdir anaconda3  (in the data folder... then)
$ sudo chmod 777 anaconda3
<this is where the bash command goes now...>

**Comment by msarahan** [comment]
Constructor is the tool that we use to make our installers: https://github.com/conda/constructor

Version 3 of constructor was a pretty big change.  It switched from needing a system installation of bzip2 to using a self-contained conda executable (using pyinstaller).  A consequence of this change is that the folder where the extracted conda executable lives must not be mounted noexec, and you must be able to run executables from that folder.  We will try to update error handling messaging accordingly, but permissions problems are very delicate.  We definitely don't want the installer to call sudo, nor be called with sudo under any normal circumstances.

**Comment by msarahan** [comment]
PS: preview installers for the next anaconda release, 2019.09, are at https://repo.anaconda.com/pkgs/misc/previews/anaconda/2019.09/ - if you can test them to see if our latest work has fixed your issue, we'd appreciate it.

**Comment by davidlowryduda** [comment]
Thank you for following up on this. I tried with the new download at https://repo.anaconda.com/pkgs/misc/previews/anaconda/2019.09/Anaconda3-2019.09.rc1-Linux-x86_64.sh

This does not work for me. There is a different error.

To test, I downloaded this and set it to install to the test directory that I affectionately call `tmpconda/conda3`. Running `bash <long_conda_installer_name>` gives the following output

```
PREFIX=/home/myname/tmpconda/conda3
Unpacking payload ...
[48307] Error loading Python lib '/tmp/_MEI002TS2/libpython3.6m.so.1.0': dlopen: /tmp/_MEI002TS2/libpython3.6m.so.1.0: failed to map segment from shared object: Operation not permitted
[48314] Error loading Python lib '/tmp/_MEIsKDX1e/libpython3.6m.so.1.0': dlopen: /tmp/_MEIsKDX1e/libpython3.6m.so.1.0: failed to map segment from shared object: Operation not permitted
```

This indicates to me that there remain references to /tmp that want write/exec powers. Setting `TMP=/somewhere/I/have/privileges` and installing again works.

**Comment by davidlowryduda** [comment]
P.S. For those who come along later and wonder where one should know about TMP: this is a python bit, not an anaconda-specific bit. What happens is that the installer makes a temporary directory with https://docs.python.org/3/library/tempfile.html, which by default uses the following environmental variables (in order):

- TMPDIR
- TEMP
- TMP
- (platform specific; on *nix, /tmp, /var/tmp, /usr/tmp in that order)
- current working directory

For me, it happened to be that I haven't set any of these. And thus setting TMP works. But conceivably a user might have set their own TMPDIR or TEMP, in which case calling `TMP=/something bash <anaconda.sh>` might not work.
