### ISSUE TITLE
Anaconda navigator won't start with new Anaconda 4.2

### ISSUE THREAD

**Issue by joonpark72** [ContinuumIO/anaconda-issues#1116]
Well, first of all, thank you for keeping things up-to-date.
This morning, I did a clean install of anaconda 4.2, mainly because conda update anaconda seem to make my shortcuts disappear...  Anyways, with this installation anaconda-navigator doesn't work.  I also tried to launch it from the command prompt and got the following error:
`(C:\Users\Joonho\Anaconda3) C:\Users\Joonho>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Joonho\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 355, in process_application_info
    packages, apps = output
TypeError: 'NoneType' object is not iterable`
Not that I use the navigator often but is there something I can do to rectify this situation???

**Comment by goanpeca** [comment]
@joonpark72 can you delete your `~/.anaconda` folder and try again?

**Comment by joonpark72** [comment]
It gives the same result.  However, the content of the new ~/.anaconda appears somewhat different.   Anything else, I should try?

**Comment by goanpeca** [comment]
Can you type on the command line

`conda info`

And paste the results here?

**Comment by joonpark72** [comment]
`(C:\Users\Joonho\Anaconda3) C:\Users\Joonho>conda info
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\Joonho\Anaconda3  (writable)
    default environment : C:\Users\Joonho\Anaconda3
       envs directories : C:\Users\Joonho\Anaconda3\envs
          package cache : C:\Users\Joonho\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
                          https://conda.anaconda.org/conda-forge/win-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://conda.binstar.org/menpo/win-64/
                          https://conda.binstar.org/menpo/noarch/
            config file : C:\Users\Joonho\.condarc
           offline mode : False
`
Here.

**Comment by goanpeca** [comment]
Thanks @joonpark72, I can reproduce the problem working on a hotfix.

**Comment by joonpark72** [comment]
Thanks!  Look forward to your reply.

**Comment by goanpeca** [comment]
@joonpark72 could you remove conda-forge from your channels?

`~/.condarc`

And try?

**Comment by joonpark72** [comment]
removed all but default channels and seem to work.  So I should leave these out from now on?

**Comment by goanpeca** [comment]
What was the exact content of that condarc file?

**Comment by joonpark72** [comment]
`channels:
  - defaults
  - conda-forge
  - https://conda.binstar.org/menpo

allow_softlinks: False`

Just had 2 extra channels.

**Comment by goanpeca** [comment]
I am not sure what is causing the issue... :-|

But perhaps you should add the channel as

**Comment by joonpark72** [comment]
add them as~~~~ ?

**Comment by goanpeca** [comment]
I am not sure what is causing the issue... :-|

But perhaps you should add the channel as 

Either

**`https://conda.anaconda.org/menpo`**  (Notice that is anaconda and not binstar)

Or just as 

**`menpo`**

**Comment by joonpark72** [comment]
Ok, I added them back as conda-forge and menpo.  It seems to work now somehow.  Thanks for the help.

**Comment by goanpeca** [comment]
Glad we sorted it out :-), but I am issuing a fix to make it more robust, thanks for all the help

:+1:

**Comment by joonpark72** [comment]
You're welcome and thanks for providing us with such a great platform!

**Comment by sntgluca** [comment]
Dear @joonpark72  and @goanpeca ,

I have a similar issue with anaconda-navigator and the .condarc file (hence I did not want to open a new issue).

I get the same error from the anaconda-navigator if I add the following local channel:

    - file://Users/<ME>/Library/conda/conda-builds

May you please take a look at this one as well?
I cannot exclude it's a configuration problem from my side, although I did not play around with the local builds directory...

Many thanks,
Gianluca

here's my .condarc:

    # This is a sample .condarc file
    # a condarc file should be placed in $HOME/.condarc

     channels:
     - defaults
    - http://repo.continuum.io/pkgs/free
    # - file://Users/<ME>/Library/conda/conda-builds
    
    show_channel_urls: True
    
    # when creating new environments add these packages by default
    create_default_packages:
      - python
    
    changeps1: False
    
    # Conda Build Options
    conda-build:
      root-dir: ~/Library/conda/conda-builds
    
    # binstar_upload: no
    # anaconda_upload: yes

And the conda info

    Current conda install:

                   platform : osx-64
              conda version : 4.2.13
           conda is private : False
          conda-env version : 4.2.13
        conda-build version : not installed
             python version : 3.5.2.final.0
           requests version : 2.11.1
           root environment : /Applications/miniconda  (writable)
        default environment : /Users/<ME>/.anaconda/envs/python3
           envs directories : /Users/<ME>/.anaconda/envs
                              /Applications/miniconda/envs
              package cache : /Users/<ME>/.anaconda/envs/.pkgs
                              /Applications/miniconda/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/pro/osx-64
                              https://repo.continuum.io/pkgs/pro/noarch
                              http://repo.continuum.io/pkgs/free/osx-64
                              http://repo.continuum.io/pkgs/free/noarch
                config file : /Users/<ME>/.condarc
               offline mode : False

**Comment by jrpwwilliams** [comment]
I have a similar issue with a slightly different stack trace for 4.2 for python 3.5 downloaded and installed on windows 10 1/5/17

Traceback (most recent call last):
  File "C:\Users\jrpwilliams\Anaconda3\Scripts\anaconda-navigator-script.py", line 5, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 70, in main
    window = run_app(splash)
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 38, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 145, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 434, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 39, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1185, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 267, in __init__
    self.set_root_prefix()
  File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 374, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers
