### ISSUE TITLE
Hello, I've installed Anaconda v3 on windows 10, but, when I run it, it does not run, I've run as administrator, uninstalled &  install again, but all didn't work. Any suggestions, please.  As a note, Anaconda v2 works without any problems.

### ISSUE THREAD

**Issue by Maria-Habib** [ContinuumIO/anaconda-issues#11169]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
You did not fill out any of the information in the issue template, so there is not much we can do to debug why this might be happening.  If Anaconda v2 works, I'd recommend installing that and then creating a Python3 environment.  See https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
