### ISSUE TITLE
Anaconda Navigator can not be opened

### ISSUE THREAD

**Issue by ainuzzahroh** [ContinuumIO/anaconda-issues#11168]
Shortly, everytime I open my Anaconda Navigator, the navigator could not be opened. This page is always appear when I open it.
Please help me fix this.
I am using Anaconda 3 and Python 3.7
![Capture](https://user-images.githubusercontent.com/53203486/62261731-82fc7300-b440-11e9-90ce-bc566e73f13a.PNG)

**Comment by ainuzzahroh** [comment]
I have trying to re-install Anaconda Navigator but it can't be fixed

**Comment by csoja** [comment]
@ainuzzahroh  it looks like your .condarc file might be corrupted.  I'd recommend deleting it (back it up under a different name if you'd like first) - and then attempting to restart navigator.
You can find where your .condarc file is located by using the Anaconda Prompt and the command _conda info_

**Comment by ainuzzahroh** [comment]
solved, thanks for your solution.
