### ISSUE TITLE
Please clarify the usage of mkl-dnn

### ISSUE THREAD

**Issue by dhirschfeld** [ContinuumIO/anaconda-issues#11173]
The [TensorFlow CPU optimizations blog post](https://www.anaconda.com/tensorflow-cpu-optimizations-in-anaconda/) specifically calls out the `MKL-DNN` as providing performance benefits:
> *the software-layer graph optimizations use the Intel Math Kernel Library for Deep Neural Networks*

...however, AFAICS it's not a dependency of the latest tensorflow?
<details>
<summary><b><tt>tensorflow-base 1.13.1 mkl_py37hcaf7020_0</tt></b></summary>

```
file name   : tensorflow-base-1.13.1-mkl_py37hcaf7020_0.tar.bz2
name        : tensorflow-base
version     : 1.13.1
build string: mkl_py37hcaf7020_0
build number: 0
size        : 49.4 MB
constrains  : ()
license     : Apache 2.0
subdir      : win-64
url         : https://repo.anaconda.com/pkgs/main/win-64/tensorflow-base-1.13.1-mkl_py37hcaf7020_0.tar.bz2
md5         : c20922a8fe7af32159c5d19e5600554d
dependencies:
  - absl-py >=0.1.6
  - astor >=0.6.0
  - gast >=0.2.0
  - grpcio >=1.8.6
  - keras-applications >=1.0.6
  - keras-preprocessing >=1.0.5
  - libmklml >=2019.0.3
  - numpy >=1.14.6,<2.0a0
  - protobuf >=3.6.1
  - python >=3.7,<3.8.0a0
  - six >=1.10.0
  - tensorflow-estimator >=1.13.0,<1.14.0a0
  - termcolor >=1.1.0
  - vc >=14.1,<15.0a0
  - zlib >=1.2.11,<1.3.0a0
```
</details>

If this library is available, does it provide the stated performance benefits?
i.e. it's not a hard dependency but tensorflow will *auto-magically* be faster if it happens to be installed?

**Comment by dhirschfeld** [comment]
If having the `mkl-dnn` installed does provide performance improvements can it please be updated as it's currently stuck at 0.14 which is over a year old and ~15 releases behind the latest `1.0.1`.

More to the point, it links to the older `intel-openmp 2018*` so can't be installed alongside the latest tensorflow.

**Comment by jjhelmus** [comment]
The MKL-DNN library is statically linked into a library inside the tensorflow package.  The `mkl-dnn` package does not need to be installed for these performance benefits.

**Comment by dhirschfeld** [comment]
Thanks for the clarification!
