### ISSUE TITLE
CPU Nightly build of Pytorch for Linux has not been updated in a while

### ISSUE THREAD

**Issue by calincru** [ContinuumIO/anaconda-issues#11181]
See title and [the package](https://anaconda.org/pytorch/pytorch-nightly-cpu).  For win64 it has been updated daily but the latest Linux build is from 07/31.

**Comment by msarahan** [comment]
The pytorch channel is operated by the pytorch team.  Please raise an issue with them at https://github.com/pytorch/pytorch
