### ISSUE TITLE
Bokeh 1.3.4

### ISSUE THREAD

**Issue by bryevdv** [ContinuumIO/anaconda-issues#11185]
From all the standard locations (note: 1.3.4, there is no 1.3.3)

cc @jjhelmus

Very sorry for the churn. PyPI changes their new token auth format and so a new live release test was needed. Should be done now until 1.4 at the end of the month.

**Comment by jjhelmus** [comment]
bokeh 1.3.4 packages are available in `pkg/main`.  I understand the frequent release, no problems building them.  We released a half dozen conda and conda-build version the last few weeks.
