### ISSUE TITLE
Spyder application appears to cause screen flashes / glitches

### ISSUE THREAD

**Issue by muskybread** [ContinuumIO/anaconda-issues#1118]
Hello,

I am having an issue where the Spyder application appears to cause visual glitches, including recurring black screen flashes (like my monitor is powering on / off or the cable is unplugged / plugged). It seems unlikely that Spyder would be the cause, but I cannot replicate the issue in any other scenario except Spyder being open. It's been a problem for a few weeks now, including with Spyder 2 and 3.

I thought it was a hardware issue at first, but after repeated tests (e.g., changing monitor connectors, different video card drivers, trying video-driven applications (e.g., movies, games), and CPU and memory stress tests), I cannot replicate the issue.

I am running Anaconda / Spyder on Windows 10 (not Anniversary, but I tried Anniversary and rolled back thinking that causes my issue) with the latest build of Anaconda / Spyder as well as the last two versions.

Thanks, and let me know if you need more info.

**Comment by ccordoba12** [comment]
I'd also say this is video drivers issue, specifically a wrong installation of DirectX or OpenGL. I don't know what else to say, given that you're clear that's not the case...
