### ISSUE TITLE
Jupyter notebook 404 Error

### ISSUE THREAD

**Issue by minkyawzaw** [ContinuumIO/anaconda-issues#11186]
### Actual Behavior

I installed Anaconda3-2019.07-Windows-x86 (win-32). When I open up the Jupyter notebook, I saw 404(File note found errors
![jupyter](https://user-images.githubusercontent.com/42461992/62601606-c1e66900-b917-11e9-9ceb-89a2c6015996.PNG)
) in the prompt. But notebook run and I can use it likes an old version. I want to know whether it has a problem and if it is, how can I fix it.

### Expected Behavior

I think 404 Errors should not show in the prompt.

##### Anaconda or Miniconda version:

[Anaconda3-2019.07-Windows-x86](url)
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>
#
[

](url)

**Comment by ciupicri** [comment]
It's an upstream [issue](https://github.com/jupyter/notebook/issues/4771) with the notebook package and it happens on Linux too.

It was fixed in [version 6.0.1](https://github.com/jupyter/notebook/issues/4790) which unfortunately is not available yet for Anaconda users.

**Comment by jjhelmus** [comment]
notebook 6.0.1 is now available in `defaults`.  @minkyawzaw can you update to this version using `conda update notebook` and see if the problem persists?

**Comment by minkyawzaw** [comment]
Thanks,
It recommends using conda update --all. But, the problem #11194 jupyter lab, nbconvert is still unsolved.
