### ISSUE TITLE
Package request: ipympl

### ISSUE THREAD

**Issue by BrenBarn** [ContinuumIO/anaconda-issues#11191]
This is a request for the `ipympl` package (https://github.com/matplotlib/jupyter-matplotlib) to be added to the main anaconda channel.  This package is required for interactive Matplotlib plots in Jupyterlab, so having it in the default channel would greatly increase accessibility for using Jupyterlab via Anaconda.

**Comment by jjhelmus** [comment]
@BrenBarn Thanks for the recommendation.  `ipympl` is now available via `defaults`.  Although we do not recommend using the `anaconda` channel on anaconda.org the package will be synced there in a day or two.
