### ISSUE TITLE
c# IronPython.Runtime.Exceptions.ImportException: 'No module named math'

### ISSUE THREAD

**Issue by LAW68** [ContinuumIO/anaconda-issues#11203]
I created a Python script in Spyder called classifier.py. The installation is in the following folders:-
C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\Lib

I then try and run the code from c# IronPython, all is working well until I try to call the Python function that contains import math.
classifier.py:-
**class classifier:
    
    def computeTF(self, wordString, bow, length):
        #print(wordString.split(','))
                
        wordString = wordString.split(',')
        wordDict = dict.fromkeys(wordString, 0)
        
        #print(wordDict)
        
        for word in bow:
            print(word)
            wordDict[word] += 1
        
        #print(wordDict)
        
        tfDict = {}
        bowCount = length
        for word, count in wordDict.items():
            #print(word)
            #print(count)
            tfDict[word] = count/float(bowCount)
            
        #print(tfDict)
        return tfDict

    def computeIDF(self, docList):   
        import math
        idfDict = {}
        N = len(docList)
        
        idfDict = dict.fromkeys(docList[0].keys(), 0)
        for doc in docList:
            for word, val in doc.items():
                if val > 0:
                    idfDict[word] += 1
        
        for word, val in idfDict.items():
            idfDict[word] = math.log10(N / float(val))
            
        return idfDict

    def computeTFIDF(self, tfBow, idfs):
        tfidf = {}
        for word, val in tfBow.items():
            tfidf[word] = val*idfs[word]
        return tfidf

    def ReturnFirstParameter(self, parameters):
        return parameters['first']**

My C# code:-
public void ExecIronPython()
        {
            //create documents
            string docA = "The cat sat on my face";
            string docB = "The dog sat on my bed";

            var bowA = docA.Split(' ');
            var bowB = docB.Split(' ');

            var wordSet = bowA.Union(bowB);
            var wordSetPython = string.Join(",", wordSet.ToArray());
            
            var engine = Python.CreateEngine();
            //reading code from file
            var source = engine.CreateScriptSourceFromFile(@"C:\Users\lee.williams\.spyder-py3\Classifier.py");
            //var source = engine.CreateScriptSourceFromString("import math" + Environment.NewLine + _Script, Microsoft.Scripting.SourceCodeKind.AutoDetect);
            var scope = engine.CreateScope();
            //executing script in scope
            source.Execute(scope);
            var classifier = scope.GetVariable("classifier");
            //initializing class
            var classifierInstance = engine.Operations.CreateInstance(classifier);

            var tfBowA = classifierInstance.computeTF(wordSetPython, bowA, bowA.Length);//WORKS
            var tfBowB = classifierInstance.computeTF(wordSetPython, bowB, bowB.Length);//WORKS

            var idfs = classifierInstance.computeIDF(tfBowA);//FAILS
            
            Console.WriteLine($"{tfBowA}");
            Console.WriteLine($"{tfBowB}");            
        }

**Comment by LAW68** [comment]
I sorted the issue myself :)

**Comment by saroup** [comment]
@LAW68 can you describe how you fixed it? It would be beneficial for others who ran into the same problem :)

**Comment by LAW68** [comment]
HI saroup

Yes. I used IRONPython(c#) to call the classifier.py class above, but I had to call Set Paths before calling the Classifier.py file:-

This tells C# where to find the PYTHON library files so IMPORT MATH can !!!

C# CODE
            var engine = Python.CreateEngine();
            string dir = Path.GetDirectoryName(_PythonClass);
            var Paths = **SetPaths**(engine);  //THIS SETS THE PYTHON LIBRARY PATHS
            engine.SetSearchPaths(Paths);

private static ICollection<string> **SetPaths**(ScriptEngine engine)
        {
            var Paths = engine.GetSearchPaths();
            Paths.Add(@"C:\Users\lee.williams");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\python37.zip");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\DLLs");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\lib");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\lib\site-packages");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\lib\site-packages\win32");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\lib\site-packages\win32\lib");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\lib\site-packages\Pythonwin");
            Paths.Add(@"C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\extensions");
            Paths.Add(@"C:\Users\lee.williams\.ipython");
            return Paths;
        }

**Comment by asif48** [comment]
> I sorted the issue myself :)

Hi Author...I am not been able to execute your code at my end , the code breaks at the same line as you pointed out 

var idfs = classifierInstance.computeIDF(tfBowA);//FAILS with the exception 

![Integration 2 Errror of blog ](https://user-images.githubusercontent.com/7997380/79297903-fa9ffe80-7ef8-11ea-9ca0-2f52a7420374.png)

My path variables are like this

` searchPaths.Add(@"C:\ProgramData\Anaconda3\DLLs");
            searchPaths.Add(@"C:\ProgramData\Anaconda3\lib");
            searchPaths.Add(@"C:\ProgramData\Anaconda3");
            searchPaths.Add(@"C:\ProgramData\Anaconda3\lib\site-packages");
            searchPaths.Add(@"C:\ProgramData\Anaconda3\lib\site-packages\win32");
            searchPaths.Add(@"C:\ProgramData\Anaconda3\lib\site-packages\win32\lib");
            searchPaths.Add(@"C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin");
            searchPaths.Add(@"C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions");
            searchPaths.Add(@"C: \Users\AsifRehman\ipython"); `

Actually I want to execute my own code which uses `import numpy`  in python, I was not been able to execute that code so I tried your code to check whether your `import math `works or not but it is failing at my end too... 

if you can help...

**Comment by ancich** [comment]
What on earth is the line
string dir = Path.GetDirectoryName(_PythonClass);
supposed to be used for?
