### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mvrmurty** [ContinuumIO/anaconda-issues#1120]
Anaconda Navigator Update error:

/Users/mvrmurty/anaconda/bin/python /Users/mvrmurty/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.1: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.1*
  - orange -> pyqt 4.*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.9', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@mvrmurty the orange package is only available for Qt4 (not Qt5, the latest and recommended package)

You can update all your anaconda installation by doing on the command line

`conda update anaconda`

If you still want to use Orange, for the moment, we advice you use a new environment.

Regards
