### ISSUE TITLE
Navigator error

### ISSUE THREAD

**Issue by aeshna25** [ContinuumIO/anaconda-issues#11217]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by aeshna25** [comment]
![Screenshot (255)](https://user-images.githubusercontent.com/31938370/63287006-ea3a7400-c2d6-11e9-8a55-c5cc5f4b5de0.png)

**Comment by aeshna25** [comment]
![Screenshot (255)](https://user-images.githubusercontent.com/31938370/63287135-34bbf080-c2d7-11e9-89a6-182107ee1187.png)

**Comment by csoja** [comment]
Looks like your .condarc file got corrupted.  If you can delete that, I expect that will eliminate this error.  If you don't know where that is, you can execute the command _conda info_ in the Anaconda Prompt - and the output will tell you the location of your .condarc file(s).

**Comment by aeshna25** [comment]
After running conda info
I am getting
'Conda'. Is not recognized as an internal or external command

**Comment by WietseKuipers** [comment]
I have the same issue as Aeshna25. I've tried to follow csoja:s guidelines but in Ananconda Prompt I receive the following message:

ConfigurationLoadError: Unable to load configuration file.
  path: C:\Users\MYNAME\.condarc
  reason: invalid yaml at position 0


C:\Users\MYNAME>

Anybody know what the problem can be?

Thanks,

WK

**Comment by csoja** [comment]
@WietseKuipers  you'll want to remove C:\Users\MYNAME\.condarc

@aeshna25 you should look for your .condarc conda configuration file in the same location - or do a search for it on your computer if you are having trouble with the Anaconda Prompt.  The file name is _.condarc_

**Comment by WietseKuipers** [comment]
@csoja Thank you for your solution, it worked perfectly :)

**Comment by Sefayay** [comment]
> @WietseKuipers you'll want to remove C:\Users\MYNAME.condarc
> 
> @aeshna25 you should look for your .condarc conda configuration file in the same location - or do a search for it on your computer if you are having trouble with the Anaconda Prompt. The file name is _.condarc_

ConfigurationLoadError: Unable to load configuration file.
  path: C:\Users\SY\.condarc
  reason: invalid yaml at position 0


C:\Users\SY>remove C:\Users\SY\.condarc
'remove' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\SY>

**Comment by Sherin1998** [comment]
1=>  do an environmental variable setup to remove Conda'. Is not recognized as an internal or external command
2.=> Delete .condarc file.You will get it after a system search.Restart anaconda.Worked for me!!
![file](https://user-images.githubusercontent.com/75293746/124222544-94b08e80-db1f-11eb-95fd-a9b0e8a5cdef.PNG)
