### ISSUE TITLE
Support Qt4 as separate package

### ISSUE THREAD

**Issue by H0R5E** [ContinuumIO/anaconda-issues#1121]
Hi, I've been using Ananconda to develop a Qt4 App (for the last 2 years) and now it seems like its been obsoleted by Qt5.

I can work around it (a bit) by pinning PyQt to version 4 in an environment, but it's not an ideal solution. Would it be possible to have Qt4 and Qt5 as separate packages?

```
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda2  (read only)
    default environment : C:\Program Files\Anaconda2
       envs directories : d:\Usuarios\108630\.conda\envs
                          C:\Program Files\Anaconda2\envs
          package cache : d:\Usuarios\108630\.conda\envs\.pkgs
                          C:\Program Files\Anaconda2\pkgs
           channel URLs : https://conda.anaconda.org/t/**EXPOSED TOKEN**/topper/win-64/
                          https://conda.anaconda.org/t/**EXPOSED TOKEN**/topper/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : d:\Usuarios\108630\.condarc
           offline mode : False
```

**Comment by H0R5E** [comment]
I think the point here is that, as a developer using Python 2,  I don't expect it to change significantly, but this change is a significant shift.

**Comment by ccordoba12** [comment]
> Would it be possible to have Qt4 and Qt5 as separate packages?

We tried really hard to make that possible (during six months or so), but we couldn't make it work correctly. We always ended up with changes that worked well for Qt4 and break Qt5, or viceversa.

So, I'm very sorry to tell you that this is not going to be possible.

**Comment by H0R5E** [comment]
OK thanks for the reply.

Is there any documentation or announcement describing the change? Particularly are there any plans to remove the archived Qt4 packages and if so when is that likely to happen?

**Comment by ccordoba12** [comment]
No, Qt4 packages will always remain in the default channels.
