### ISSUE TITLE
Anaconda Navigator not showing items on Home page latest version just downloaded 8-17-2019

### ISSUE THREAD

**Issue by jaaks** [ContinuumIO/anaconda-issues#11212]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
There is insufficient information in this issue to debug the issue.  At least some information requested in the issue template must be filled out.  Closing.
