### ISSUE TITLE
Upgrade pyarrow in defaults to 0.13.0 or later

### ISSUE THREAD

**Issue by wesm** [ContinuumIO/anaconda-issues#11227]
I'm surprised to find out that the `pyarrow` package is lagging upstream by almost a year

```
$ conda install pyarrow -c defaults
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/wesm/miniconda/envs/arrow-3.7

  added / updated specs:
    - pyarrow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    arrow-cpp-0.11.1           |   py37h5c3f529_1         4.5 MB  defaults
    ca-certificates-2019.5.15  |                1         134 KB  defaults
    certifi-2019.6.16          |           py37_1         156 KB  defaults
    gflags-2.2.2               |       he6710b0_0         126 KB  defaults
    glog-0.3.5                 |       hf484d3e_1         138 KB  defaults
    libboost-1.67.0            |       h46d08c1_4        13.0 MB  defaults
    libevent-2.1.8             |       h1ba5d50_0         884 KB  defaults
    lz4-c-1.8.1.2              |       h14c3975_0         130 KB  defaults
    openssl-1.1.1c             |       h7b6447c_1         2.5 MB  defaults
    pyarrow-0.11.1             |   py37he6710b0_0         1.6 MB  defaults
    snappy-1.1.7               |       hbae5bb6_3          35 KB  defaults
    zstd-1.3.7                 |       h0b5b093_0         401 KB  defaults
    ------------------------------------------------------------
                                           Total:        23.5 MB
```

Apache Arrow 0.11.1 was released in October 2018. The project is only 3.5 years old so the rate of new features, bug fixes, and performance improvements is quite fast, so leaving Anaconda users and customers on an old version is not only limiting the benefits that they derive from the project but also potentially putting them at risk. We routinely fix bugs that may yield segmentation faults in production code or, in rare cases, incorrect results. 

I would recommend upgrading at least to 0.13.0. Due to some an issue with 0.14.1 (see ARROW-6060) I would recommend waiting for 0.15.0 to upgrade past that.

**Comment by forrestwaters** [comment]
pyarrow 0.13.0 is now available in defaults

**Comment by jorisvandenbossche** [comment]
In the meantime, the latest pyarrow version is 0.15. Are there plans to update this further?

**Comment by wesm** [comment]
0.15.1, to be clear. I recommend upgrading

**Comment by jorisvandenbossche** [comment]
We are at the moment at version 2.0.0, while it seems the default channel is still at 0.15. Are there plans to update this?
