### ISSUE TITLE
Problems convert nbviewer out put to pdf for sharing

### ISSUE THREAD

**Issue by Dipugee** [ContinuumIO/anaconda-issues#1123]
Hi:

I am using Jupyter under Navigator 1.2.3 on my MacOS 10.12. I created an html output file using nbviewer and saved on my Ma. I attach it here. The print preview of this html file looks ok and the there are no line wrap around. However, .pdf file wraps the lines and destroys the readability of the notebook. I need to share this as a .pdf with a client who does not have Anaconda, Navigator or Jupyter,nor are they knowledgeable about github etc. How do I share this Notebook with them so that it looks like the Jupyter notebook I see on my screen?

Here is the pdf of the html file...

[ABVEst.pdf](https://github.com/ContinuumIO/anaconda-issues/files/504078/ABVEst.pdf)

**Comment by goanpeca** [comment]
@Dipugee, this seems to be a problem with Jupyter (and not Anaconda, or Navigator)

Could you check https://github.com/jupyter/nbviewer
