### ISSUE TITLE
more update problems (packages will be DOWNGRADED)

### ISSUE THREAD

**Issue by makeyourownalgorithmicart** [ContinuumIO/anaconda-issues#11243]
Over the last 2 years I've logged issues where the conda/anaconda package manager behaves incorrectly, counter-intuitively, or both.

Sometimes the issues have been ignored. Sometimes the replies admit a problem, with a promise to be fixed.

Today, I installed a fresh Anaconda Python on MacOS, and did a

```
conda update anaconda
```

The first thing that happened was expected, an update to conda itself.

```
conda update anaconda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/tariq/anaconda3

  added / updated specs:
    - anaconda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.11               |           py37_0         3.0 MB
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following packages will be UPDATED:

  conda                                       4.7.10-py37_0 --> 4.7.11-py37_0


Proceed ([y]/n)? y
```

Then after doing that, the problems began again .. the next update plan suggests anaconda will be downgraded.

```
The following packages will be DOWNGRADED:

  anaconda                                   2019.07-py37_0 --> custom-py37_1


Proceed ([y]/n)? n
```

This is wrong. It is wrong because it is counter-intuitive, even if for some reason it is technically the right thing to do.

I know this issue has been going on for years - I really think it needs to be fixed because apart from being incorrect technically and from a user experience angle, it also loses trust in the entire anaconda ecosystem.

This is also aside from the ongoing confusion on the official websites and sources on how to actually update the system.

I repeat buy previous position - make 90% of needs easy - that means 

1. conda **update** everything or conda **update** something
2. conda **upgrade** to the next release of packages tested together as a collection
3. conda special for the 10% of cases that need to do special things like pinning versions or choosing alternative repos etc etc

The following is the full plan if it helps you:

```
conda update anaconda
Collecting package metadata (current_repodata.json): done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-64::anaconda==2019.07=py37_0
  - defaults/osx-64::numba==0.44.1=py37h6440ff4_0
done

## Package Plan ##

  environment location: /Users/tariq/anaconda3

  added / updated specs:
    - anaconda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _anaconda_depends-2019.03  |           py37_0           6 KB
    anaconda-custom            |           py37_1           3 KB
    beautifulsoup4-4.8.0       |           py37_0         147 KB
    bitarray-1.0.1             |   py37h1de35cc_0          59 KB
    bokeh-1.3.4                |           py37_0         4.0 MB
    ca-certificates-2019.5.15  |                1         133 KB
    certifi-2019.6.16          |           py37_1         155 KB
    chardet-3.0.4              |        py37_1003         173 KB
    curl-7.65.3                |       ha441bb4_0         135 KB
    cython-0.29.13             |   py37h0a44026_0         2.0 MB
    dask-2.3.0                 |             py_0          12 KB
    dask-core-2.3.0            |             py_0         577 KB
    distributed-2.3.2          |             py_1         374 KB
    docutils-0.15.2            |           py37_0         736 KB
    fsspec-0.4.0               |             py_0          41 KB
    importlib_metadata-0.19    |           py37_0          40 KB
    ipykernel-5.1.2            |   py37h39e3cac_0         165 KB
    ipython-7.8.0              |   py37h39e3cac_0         1.1 MB
    ipywidgets-7.5.1           |             py_0         107 KB
    jedi-0.15.1                |           py37_0         711 KB
    json5-0.8.5                |             py_0          25 KB
    jsonschema-3.0.2           |           py37_0          90 KB
    jupyterlab_server-1.0.0    |             py_1          25 KB
    lazy-object-proxy-1.4.2    |   py37h1de35cc_0          29 KB
    libcurl-7.65.3             |       h051b688_0         528 KB
    lxml-4.4.1                 |   py37hef8c89e_0         1.3 MB
    matplotlib-3.1.1           |   py37h54f8f79_0         6.6 MB
    mkl_fft-1.0.14             |   py37h5e564d8_0         157 KB
    more-itertools-7.2.0       |           py37_0          99 KB
    nltk-3.4.5                 |           py37_0         2.1 MB
    numexpr-2.7.0              |   py37h7413580_0         131 KB
    packaging-19.1             |           py37_0          46 KB
    pandas-0.25.1              |   py37h0a44026_0        10.2 MB
    parso-0.5.1                |             py_0          68 KB
    pip-19.2.2                 |           py37_0         1.9 MB
    pyodbc-4.0.27              |   py37h0a44026_0          66 KB
    pyparsing-2.4.2            |             py_0          61 KB
    pytest-remotedata-0.3.2    |           py37_0          14 KB
    python-libarchive-c-2.8    |          py37_13          23 KB
    pytz-2019.2                |             py_0         245 KB
    pyyaml-5.1.2               |   py37h1de35cc_0         171 KB
    pyzmq-18.1.0               |   py37h0a44026_0         435 KB
    qtconsole-4.5.4            |             py_0          94 KB
    qtpy-1.9.0                 |             py_0          39 KB
    scipy-1.3.1                |   py37h1410ff5_0        16.0 MB
    soupsieve-1.9.2            |           py37_0          61 KB
    sqlalchemy-1.3.7           |   py37h1de35cc_0         1.7 MB
    statsmodels-0.10.1         |   py37h1d22016_0         8.8 MB
    tbb-2019.4                 |       h04f5b5a_0         147 KB
    werkzeug-0.15.5            |             py_0         256 KB
    widgetsnbextension-3.5.1   |           py37_0         1.8 MB
    wurlitzer-1.0.3            |           py37_0          14 KB
    zipp-0.5.2                 |             py_0           8 KB
    ------------------------------------------------------------
                                           Total:        63.9 MB

The following NEW packages will be INSTALLED:

  _anaconda_depends  pkgs/main/osx-64::_anaconda_depends-2019.03-py37_0
  fsspec             pkgs/main/noarch::fsspec-0.4.0-py_0
  tbb                pkgs/main/osx-64::tbb-2019.4-h04f5b5a_0

The following packages will be UPDATED:

  beautifulsoup4                               4.7.1-py37_1 --> 4.8.0-py37_0
  bitarray                             0.9.3-py37h1de35cc_0 --> 1.0.1-py37h1de35cc_0
  bokeh                                        1.2.0-py37_0 --> 1.3.4-py37_0
  ca-certificates                               2019.5.15-0 --> 2019.5.15-1
  certifi                                  2019.6.16-py37_0 --> 2019.6.16-py37_1
  chardet                                      3.0.4-py37_1 --> 3.0.4-py37_1003
  curl                                    7.65.2-ha441bb4_0 --> 7.65.3-ha441bb4_0
  cython                             0.29.12-py37h0a44026_0 --> 0.29.13-py37h0a44026_0
  dask                                           2.1.0-py_0 --> 2.3.0-py_0
  dask-core                                      2.1.0-py_0 --> 2.3.0-py_0
  distributed                                    2.1.0-py_0 --> 2.3.2-py_1
  docutils                                      0.14-py37_0 --> 0.15.2-py37_0
  importlib_metadata                            0.17-py37_1 --> 0.19-py37_0
  ipykernel                            5.1.1-py37h39e3cac_0 --> 5.1.2-py37h39e3cac_0
  ipython                              7.6.1-py37h39e3cac_0 --> 7.8.0-py37h39e3cac_0
  ipywidgets                                     7.5.0-py_0 --> 7.5.1-py_0
  jedi                                        0.13.3-py37_0 --> 0.15.1-py37_0
  json5                                          0.8.4-py_0 --> 0.8.5-py_0
  jsonschema                                   3.0.1-py37_0 --> 3.0.2-py37_0
  jupyterlab_server                              1.0.0-py_0 --> 1.0.0-py_1
  lazy-object-proxy                    1.4.1-py37h1de35cc_0 --> 1.4.2-py37h1de35cc_0
  libcurl                                 7.65.2-h051b688_0 --> 7.65.3-h051b688_0
  lxml                                 4.3.4-py37hef8c89e_0 --> 4.4.1-py37hef8c89e_0
  matplotlib                           3.1.0-py37h54f8f79_0 --> 3.1.1-py37h54f8f79_0
  mkl_fft                             1.0.12-py37h5e564d8_0 --> 1.0.14-py37h5e564d8_0
  more-itertools                               7.0.0-py37_0 --> 7.2.0-py37_0
  nltk                                         3.4.4-py37_0 --> 3.4.5-py37_0
  numexpr                              2.6.9-py37h7413580_0 --> 2.7.0-py37h7413580_0
  packaging                                     19.0-py37_0 --> 19.1-py37_0
  pandas                              0.24.2-py37h0a44026_0 --> 0.25.1-py37h0a44026_0
  parso                                          0.5.0-py_0 --> 0.5.1-py_0
  pip                                         19.1.1-py37_0 --> 19.2.2-py37_0
  pyodbc                              4.0.26-py37h0a44026_0 --> 4.0.27-py37h0a44026_0
  pyparsing                                      2.4.0-py_0 --> 2.4.2-py_0
  pytest-remotedata                            0.3.1-py37_0 --> 0.3.2-py37_0
  python-libarchive~                            2.8-py37_11 --> 2.8-py37_13
  pytz                                          2019.1-py_0 --> 2019.2-py_0
  pyyaml                               5.1.1-py37h1de35cc_0 --> 5.1.2-py37h1de35cc_0
  pyzmq                               18.0.0-py37h0a44026_0 --> 18.1.0-py37h0a44026_0
  qtconsole                                      4.5.1-py_0 --> 4.5.4-py_0
  qtpy                                           1.8.0-py_0 --> 1.9.0-py_0
  scipy                                1.3.0-py37h1410ff5_0 --> 1.3.1-py37h1410ff5_0
  soupsieve                                      1.8-py37_0 --> 1.9.2-py37_0
  sqlalchemy                           1.3.5-py37h1de35cc_0 --> 1.3.7-py37h1de35cc_0
  statsmodels                         0.10.0-py37h1d22016_0 --> 0.10.1-py37h1d22016_0
  werkzeug                                      0.15.4-py_0 --> 0.15.5-py_0
  widgetsnbextension                           3.5.0-py37_0 --> 3.5.1-py37_0
  wurlitzer                                    1.0.2-py37_0 --> 1.0.3-py37_0
  zipp                                           0.5.1-py_0 --> 0.5.2-py_0

The following packages will be DOWNGRADED:

  anaconda                                   2019.07-py37_0 --> custom-py37_1


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```

**Comment by datasciencecornwall** [comment]
I would like the issue to be fixed too - it has been going on far too long gives the impression that the anaconda system is poorly engineered.

I have read the explanations on the other issue but they are not satisfactory - they simply restate that the system is broken and counter-intuitive.

I realise this is an open source volunteer project so do take my enthusiasm for a solution with some moderation.

**Comment by mingwandroid** [comment]
If you could explain why you think this is wrong (other than the unfortunate choice of word "DOWNGRADED' that wins be really helpful.

This behavior is as expected and is the desirable behavior for eBay you are asking conda to do.

Hopefully this helps clarify things: https://www.anaconda.com/whats-in-a-name-clarifying-the-anaconda-metapackage/

But please try take a note productive tone.

**Comment by makeyourownalgorithmicart** [comment]
thanks for your input @mingwandroid 

my perspective is user experience and accessibility, as well as cognitive load and (counter-intuition)

with the greatest respect. and I don't underestimate the work you do, I would like to make some comments

- that link you recommended has 1155 words, that in most scenarios is not a user friendly approach to merely updating a distribution

 - "unfortunate names" are fine if you're a deeply technical person already familiar with the discussion on the various message lists .. but most normal users, including incredibly educated ones, will see "downgrade" as a fault, and so they should

My constructive suggestion was a new philosophy for the package management system, which several people have humbly admitted is overly complicated and difficult, and prone to error. 

Linux distributions manage an even greater number of packages, with a greater level of upstream diversity.

The intuitive solution that many have adopted, and understand, seems to work well.

- have release levels, a set of packaged tested to work well together - eg Debian 1.2
- at a later time we have a new release level  - eg Debian 1.3
- users can update within a release to new packages which have also been tested to work well with the rest of the release - just like apt/rpm/yum/dnf ...
- major changes justify a new release level when dependencies can't be held in sync 
- users have the option and choice to upgrade (cd update) the release level, which is a more disruptive change as it lifts the version numbers to the next release but which also is a set of packages tested to work together

this means for most normal users:

- users simply use `conda update package` to see if a new version is available and tested within the release level, it may seek to upgrade other packages within that release level
- users can simple use `conda install` and `conda remove`
- users can simply use `conda upgrade` to signal they want to move u top the next release level, which will entail a new "meta package" as you call it and a whole new set of packages, which have been tested to work together

that's 90% of use cases, which leave experts who want to do specialised things like pin package versions or force installs from different release levels or externally etc etc

I don't disagree with much of what you say but I feel the team behind anaconda needs to think about designing around users, user experience, usability, intuitive outcomes, consistency, discoverability ..  .. all that good stuff

thank you - we're all trying to make anaconda better for everyone

**Comment by mingwandroid** [comment]
To be clear, I don't necessarily disagree with your points, but this is a bug tracker and this bug has no explanation. It's not the place to discuss how Anaconda Distribution (and by extension, conda) is engineered.

**Comment by mingwandroid** [comment]
.. or is it literally just that "DOWNGRADED" text is scary? PRs would be welcome to address that.

**Comment by mingwandroid** [comment]
Well, since this custom package is not integration-tested nearly so well as any we release you could consider it a downgrade! But yes, I also meant we could special case it, though it'd make the code a bit horrible, and as you say, it's cosmetic and there's so many much more important things that we should spend our time on.

The Anaconda package is also aimed at beginners who are unlikely to update it and I am somewhat surprised that anyone would use it for 2 years without switching to using Miniconda and/or isolated environments which is a better way to use our software.

**Comment by csoja** [comment]
Thank you @makeyourownalgorithmicart & @datasciencecornwall for taking the time to voice your confusion and concerns about how the anaconda meta-package currently works.  Figuring out the best path forward here has been on our to-do list for some time.  Unfortunately, with the small team that we have and that it is not a "simple" thing to fix (as @mingwandroid and @msarahan have highlighted), there have been other higher priorities - but this remains on our list as something we do want to improve.  
Constructive feedback and discussion that does not belittle the team's efforts is always appreciated.

**Comment by makeyourownalgorithmicart** [comment]
thanks @csoja - may I ask that when and if this issue comes to be redesigned, perhaps you could put out a call for ideas about how it should work from a users perspective?

**Comment by csoja** [comment]
When we revisit the topic - I'll consolidate the related issues to one - and tag folks who have expressed interest.  If you're still interested at that point, please participate! I'm going to close this issue - as the following one is the issue we're tracking related to this feature for now. https://github.com/ContinuumIO/anaconda-issues/issues/4298  You may want to follow that issue so you get updates on it in the meantime.
