### ISSUE TITLE
Anaconda launcher suddenly always fails when opened

### ISSUE THREAD

**Issue by yujenny** [ContinuumIO/anaconda-issues#1124]
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by goanpeca** [comment]
Hi @yujenny 

Launcher has been deprecated for several months. Anaconda Navigator replaced it. Lo learn more please visit the [documentation](https://docs.continuum.io/anaconda/navigator).

To install navigator on the command line you can type:

`conda install anaconda-navigator` or download the latests Anaconda (version 4.2)
