### ISSUE TITLE
Navigator Issue 

### ISSUE THREAD

**Issue by Kopal-Sharma** [ContinuumIO/anaconda-issues#11251]
### Actual Behavior

error showed
expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior

Anaconda Navigator Opens

### Steps to Reproduce

Open Anaconda Navigator

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Insufficient information included in issue.  Please complete template. Closing.
