### ISSUE TITLE
Updating the plotly package?

### ISSUE THREAD

**Issue by nicolaskruchten** [ContinuumIO/anaconda-issues#11279]
Hello!

I'm part of the team working on the `plotly` package, and I notice that the version up at https://anaconda.org/anaconda/plotly is trailing the latest for the past month or so... Is there anything we can do to make it easier for this version to track the latest on on PyPI, which is 4.1.1?

In general it doesn't bother me too too much if the Anaconda version trails the latest, but there is an embarassing bug in 4.0.0 which was fixed in 4.1.0 ;)

cheers,
Nicolas

**Comment by jjhelmus** [comment]
plotly 4.1.1 is now available in `defaults`.  It may take a day or two to sync with the `anaconda` channel.  

The best method to aid us in getting timely updated is to keep the [conda-forge feedstock](https://github.com/conda-forge/plotly-feedstock) updated.  It looks like the current maintainers are doing an excellent job at this.

**Comment by nicolaskruchten** [comment]
Thanks so much!
