### ISSUE TITLE
Anaconda Navigator became so huge

### ISSUE THREAD

**Issue by WilliamLeeBravo** [ContinuumIO/anaconda-issues#1127]
Hi, I'm a beginner and recently I found my navigator became so huge and it made me not comfortable. Is there anyone could help me to solve this problem?  
![2016-10-01 12-51-45](https://cloud.githubusercontent.com/assets/7219519/19015651/13c1991e-87d6-11e6-9675-799cc6dfc037.png)

**Comment by WilliamLeeBravo** [comment]
Thank you so much!

**Comment by goanpeca** [comment]
@WilliamLeeBravo thanks for reporting, we are working on this.

**Comment by zhuyu2015** [comment]
I also have the same issue...

**Comment by goanpeca** [comment]
@zhuyu2015 and @WilliamLeeBravo, the new version of Anaconda Navigator added a fix for this.

To update to the latest version please type on the command prompt:

`conda update anaconda-navigator`

We added a new option in the preferences to disable high DPI scaling. It is on by default so you need to disable it and restart navigator.

<img width="479" alt="screen shot 2016-10-20 at 8 46 26 am" src="https://cloud.githubusercontent.com/assets/3627835/19560262/be1be2b4-96a1-11e6-8b21-e12f616b0a3f.png">

Could you try and let us know if it works ok?

**Comment by WilliamLeeBravo** [comment]
Thanks for working on this, however, the navigator is still that huge even
after I have updated it. I'm not quite sure what is wrong. I think it will
be more helpful if I give you my laptop information. I'm using a thinkpad
t450s laptop running Ubuntu 16.04 LTS system. The cpu is i5-5300u. Anyway
I'm starting to use ipython in terminal but not spyder IDE for my python
study, and I will keep checking my navigator. Thank you so much!

**Comment by goanpeca** [comment]
did you disable the option (uncheck it) on the preferences dialog as with the screenshot pasted in my previous message?

**Comment by WilliamLeeBravo** [comment]
[image: Inline image 1]
Yes, I've done this for several times but nothing changed.

**Comment by goanpeca** [comment]
@WilliamLeeBravo is this still an issue with the latest Qt packages?

Just to double check. Your laptop has a higher pixel density (like retina display I mean)?

**Comment by WilliamLeeBravo** [comment]
@goanpeca I forgot to say it here that there is no more problems after I started using my new monitor, so I think the former problem is because of this. BTW my laptop's screen is 14' FHD. Thank you!

**Comment by goanpeca** [comment]
Awesome to hear @WilliamLeeBravo, closing :-)

**Comment by Chuukwudi** [comment]
But I am having same issue myself. I can't even resize the anaconda-navigator window in other to see where to untick the high dpi
I am on ubuntu 20.04, 4k 15" display

**Comment by html1101** [comment]
> But I am having same issue myself. I can't even resize the anaconda-navigator window in other to see where to untick the high dpi
> I am on ubuntu 20.04, 4k 15" display

I was having the same problem here, I'm on Ubuntu 20.04, 4K with 13.3" display. The way I fixed it was the following:
1. Opening the preferences through the command line: <code>sudo nano ~/.anaconda/navigator/anaconda-navigator.ini</code>
2. Change the DPI setting by scrolling down and modifying this line: <code>enable_high_dpi_scaling = False</code>
3. When you open <code>anaconda-navigator</code> it shouldn't be so absurdly large anymore.
