### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by markusritschel** [ContinuumIO/anaconda-issues#1128]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - mayavi -> numpy 1.7*|1.8*|1.9*
  - pandas ==0.18.1
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Linux;4.4.0-21-generic;#37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016;x86_64;x86_64', 'qt': '4.8.7', 'python': '3.5.2', 'conda': '4.1.6', 'platform': 'linux-64', 'pyqt': '4.11.4', 'version': '1.2.1', 'language': 'de_DE'}

**Comment by goanpeca** [comment]
Hi @markusritschel the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type:

`conda update anaconda-navigator`
