### ISSUE TITLE
Win32 Import Error

### ISSUE THREAD

**Issue by SteelCode23** [ContinuumIO/anaconda-issues#11316]
### Actual Behavior

When I simply install Anaconda3 on Windows 10, and then install a new environment with Python and R, the notebook fails to open. Reading the error on the command prompt, the error is to that in:
C:\Projects\anaconda3\envs\Analyst2\lib\site-packages\jupyter_client\connect.py
there is an import error. 
import win32api
ImportError: DLL load failed: The specified procedure could not be found.
[W 17:37:11.362 NotebookApp] Unhandled error

![image](https://user-images.githubusercontent.com/20233529/65641798-b29ca700-dfbb-11e9-892f-0ba88f495664.png)

I was able to resolve this issue by simply commenting out line 100 of the connect.py file.
C:\Projects\anaconda3\envs\Analyst2\lib\site-packages\jupyter_client\connect.py

##### Operating System:
Windows 10
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by jjhelmus** [comment]
I new build of `jupyter_client` was recently added to the `defaults` channel which includes the missing dependency on pywin32 which address this issue.  This modification is not needed if this new build of `jupyter_client` is installed.
