### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by wenzler15** [ContinuumIO/anaconda-issues#11331]
Hey guys, i'm having some problems with Anaconda, I downloaded and tried to install tensorflow, by the environments I couldn't take it, so I did it by my own hands, and after some erros, I could download it, but now when I open my Jupyter notebook, and try just to import tensor flow, like.
import tensorflow as ts, a message apear that don't exists a module with this name, i'm using the python 3.7, pip 19.2 and tensorflow 1.8.

TKS

**Comment by csoja** [comment]
The issue template here requests important information to help with debugging any issues - without that information there is nothing we can do to help.  
There are instructions in this blog post on installing Tensorflow with Anaconda: https://www.anaconda.com/tensorflow-in-anaconda/

**Comment by wenzler15** [comment]
Thank you, but I tried with that way and didn't work too, what should I do, to you help me?
________________________________
De: csoja <notifications@github.com>
Enviado: terça-feira, 1 de outubro de 2019 12:25
Para: ContinuumIO/anaconda-issues <anaconda-issues@noreply.github.com>
Cc: wenzler15 <douglas_wenzler@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [ContinuumIO/anaconda-issues] Help me (#11331)


The issue template here requests important information to help with debugging any issues - without that information there is nothing we can do to help.
There are instructions in this blog post on installing Tensorflow with Anaconda: https://www.anaconda.com/tensorflow-in-anaconda/
