### ISSUE TITLE
Will anaconda support MacOS Catalina(zsh)?

### ISSUE THREAD

**Issue by GideonWeng** [ContinuumIO/anaconda-issues#11334]
For MacOS Catalina, the default shell is `zsh`.

**Comment by GideonWeng** [comment]
When clicking `bash(root)` at anaconda navigator, the terminal(zsh) will show
```sh
/Users/name/.anaconda/navigator/a.tool ; exit;
 name@nameMacBook-Pro  ~  /Users/gideon/.anaconda/navigator/a.tool ; exit;
/Users/name/.anaconda/navigator/a.tool: line 1: syntax error near unexpected token `('
/Users/name/.anaconda/navigator/a.tool: line 1: `bash --init-file <(echo "source activate /usr/local/anaconda3/envs/myenv;")'

[Process completed]
```
How to solve it?
Thx for any help.

**Comment by hbandukw** [comment]
I am having the same problem. Should I be manually editing the a.tool file?

**Comment by soapy1** [comment]
conda supports using zsh shell. You can initialize conda for zsh using `conda init --zsh` and then restarting your shell

**Comment by MohammadChavosh** [comment]
Just to add, of your terminal does not understand `conda` command, you should go to your anaconda setup folder, then go to bin and run `./conda init zsh`

**Comment by JetSethi** [comment]
> Just to add, of your terminal does not understand `conda` command, you should go to your anaconda setup folder, then go to bin and run `./conda init zsh`

and how exactly do you do that? sorry im a newbie

**Comment by MohammadChavosh** [comment]
> > Just to add, of your terminal does not understand `conda` command, you should go to your anaconda setup folder, then go to bin and run `./conda init zsh`
> 
> and how exactly do you do that? sorry im a newbie

So basically you should open terminal and then go to the bin in the anaconda setup path, for example: 
`cd /Users/YourName/anaconda3/bin`
Then, you should run `./conda init zsh`. If it is not working, you can try bash `zsh conda init zsh`

**Comment by ShaikhahMaasher** [comment]
I got this error msg:
```
>> zsh conda init zsh
conda:3: command not found: import
conda: parse error near `)'
```

I tried the other command, but it did nothing
```
>> ./conda init zsh
no change     /Users/shaikhahmaasher/anaconda3/condabin/conda
no change     /Users/shaikhahmaasher/anaconda3/bin/conda
no change     /Users/shaikhahmaasher/anaconda3/bin/conda-env
no change     /Users/shaikhahmaasher/anaconda3/bin/activate
no change     /Users/shaikhahmaasher/anaconda3/bin/deactivate
no change     /Users/shaikhahmaasher/anaconda3/etc/profile.d/conda.sh
no change     /Users/shaikhahmaasher/anaconda3/etc/fish/conf.d/conda.fish
no change     /Users/shaikhahmaasher/anaconda3/shell/condabin/Conda.psm1
no change     /Users/shaikhahmaasher/anaconda3/shell/condabin/conda-hook.ps1
no change     /Users/shaikhahmaasher/anaconda3/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /Users/shaikhahmaasher/anaconda3/etc/profile.d/conda.csh
no change     /Users/shaikhahmaasher/.zshrc
No action taken.
```

if you have any idea of the reason please help..

**Comment by MohammadChavosh** [comment]
> I got this error msg:
> 
> ```
> >> zsh conda init zsh
> conda:3: command not found: import
> conda: parse error near `)'
> ```
> 
> I tried the other command, but it did nothing
> 
> ```
> >> ./conda init zsh
> no change     /Users/shaikhahmaasher/anaconda3/condabin/conda
> no change     /Users/shaikhahmaasher/anaconda3/bin/conda
> no change     /Users/shaikhahmaasher/anaconda3/bin/conda-env
> no change     /Users/shaikhahmaasher/anaconda3/bin/activate
> no change     /Users/shaikhahmaasher/anaconda3/bin/deactivate
> no change     /Users/shaikhahmaasher/anaconda3/etc/profile.d/conda.sh
> no change     /Users/shaikhahmaasher/anaconda3/etc/fish/conf.d/conda.fish
> no change     /Users/shaikhahmaasher/anaconda3/shell/condabin/Conda.psm1
> no change     /Users/shaikhahmaasher/anaconda3/shell/condabin/conda-hook.ps1
> no change     /Users/shaikhahmaasher/anaconda3/lib/python3.7/site-packages/xontrib/conda.xsh
> no change     /Users/shaikhahmaasher/anaconda3/etc/profile.d/conda.csh
> no change     /Users/shaikhahmaasher/.zshrc
> No action taken.
> ```
> 
> if you have any idea of the reason please help..

I guess the second one worked correctly for you, so now if you open a new terminal, you can use the `conda` command in that. Am I right?

**Comment by ralphsliger** [comment]
> > > Just to add, of your terminal does not understand `conda` command, you should go to your anaconda setup folder, then go to bin and run `./conda init zsh`
> > 
> > 
> > and how exactly do you do that? sorry im a newbie
> 
> So basically you should open terminal and then go to the bin in the anaconda setup path, for example:
> `cd /Users/YourName/anaconda3/bin`
> Then, you should run `./conda init zsh`. If it is not working, you can try bash `zsh conda init zsh`

THANKKSSSS!!!!

**Comment by SAQUTTony** [comment]
> conda supports using zsh shell. You can initialize conda for zsh using `conda init --zsh` and then restarting your shell

I got "error: unrecognized arguments: --zsh" after this. So What do I do?  I tried "conda init zsh", but I got a series of "No Change" When I reopen a new terminal (zsh), conda is still nor found.

**Comment by evdoks** [comment]
Running `./conda init zsh` activates base environment each time I launch a terminal window, which not what I want (e.g., it introduces a considerable delay before prompt appears).
Moreover, even if `.zshrc` file is updated, I am still getting the same error message as @GideonWeng .

**Comment by mingwandroid** [comment]
@evdocs,

Simply run `conda config --set auto_activate_base false`

**Comment by aisync** [comment]
I have @GideonWeng 's original issue, and have re-installed Anaconda with no change. It's not related to shell path as `conda` is a recognized command in zsh (after the standard setup w/ .zshrc). 

Terminal throws the below error upon trying to access any environment via navigator: 
```
/Users/name/.anaconda/navigator/a.tool ; exit;
 name@nameMacBook-Pro  ~  /Users/name/.anaconda/navigator/a.tool ; exit;
/Users/name/.anaconda/navigator/a.tool: line 1: syntax error near unexpected token `('
/Users/name/.anaconda/navigator/a.tool: line 1: `bash --init-file <(echo "source activate /usr/local/anaconda3/envs/myenv;")'

[Process completed]
```
Opening with Python / IPython works seemingly okay. But `conda activate <env>` also returns an error although I'm not entirely certain to directly related: 

`/etc/conda/activate.d/java_home.sh:6: = not found`

**Comment by anderson-kl-1** [comment]
if ~/.zshrc doesn't exist, run 'touch ~/.zshrc' before running the above commands.   MacOS uses .zlogin but anaconda assumes .zshrc.
