### ISSUE TITLE
Does anaconda support catalina now

### ISSUE THREAD

**Issue by baldFemale** [ContinuumIO/anaconda-issues#11343]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by ralbso** [comment]
Piggybacking here; let it serve as a word of caution, too. Installed macOS Catalina last night, and my anaconda is now broken. Catalina moved anaconda out of the directory it was originally installed in. I moved it back, and made sure the PATH link was correct. Against all instincts, I tried opening Anaconda Navigator, and a Finder pop-up window appears saying 'The application “Anaconda-Navigator” can’t be opened.'

**Comment by Xiaolan89** [comment]
Same problem. And I also tried to re-install miniconda and anaconda but it shows the package is incompatible with this version of macOS (Catalina v 10.15). 
<img width="1026" alt="WeChat49f50f7378fbd444f48f0525905eab9a" src="https://user-images.githubusercontent.com/56330671/66499019-9fdaa580-ea84-11e9-9c65-3f32b48d5935.png">

**Comment by msarahan** [comment]
discussion is at #10998
