### ISSUE TITLE
We do not support beta versions of operating systems.  We will work to support Catalina when it reaches its final release.

### ISSUE THREAD

**Issue by lachi001** [ContinuumIO/anaconda-issues#11346]
We do not support beta versions of operating systems.  We will work to support Catalina when it reaches its final release.
So technically anaconda is not working with the new apple update Catalina anybody can help with this problem. Would appreciate it a lot. Thank you
_Originally posted by @msarahan in https://github.com/ContinuumIO/anaconda-issues/issues/11105#issuecomment-510283656_

**Comment by seulert** [comment]
There is already an issue (closed though)
[https://github.com/ContinuumIO/anaconda-issues/issues/10998](https://github.com/ContinuumIO/anaconda-issues/issues/10998)
where some suggestions were made...currently it seems that there is no solution except som.e workarounds

**Comment by msarahan** [comment]
reopened #10998 - that is the correct place to discuss this.

**Comment by Eugenie-uv** [comment]
Please hurry up to make anaconda works on Catalina

**Comment by lachi001** [comment]
> Please hurry up to make anaconda works on Catalina

it's working on my mac try reading the comments above they help #10998

**Comment by seulert** [comment]
> > Please hurry up to make anaconda works on Catalina
> 
> it's working on my mac try reading the comments above they help #10998

For me it doesn't: I was able to get `conda` to work but that's about it, I would have to edit all headers in the different executables like (`jupyter` etc.) with unknown dependencies. I wasn't able to get it to change automatically (neither in `bash` nor in `zsh`)...

**Comment by Eugenie-uv** [comment]
> > > Please hurry up to make anaconda works on Catalina
> > 
> > 
> > it's working on my mac try reading the comments above they help #10998
> 
> For me it doesn't: I was able to get `conda` to work but that's about it, I would have to edit all headers in the different executables like (`jupyter` etc.) with unknown dependencies. I wasn't able to get it to change automatically (neither in `bash` nor in `zsh`)...

I follow the instruction and reinstall anaconda. It works well now.
[How to Restore Anaconda after Update to MacOS Catalina](https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/l)

**Comment by csoja** [comment]
Correct link to the blog post: https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/
