### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by TheTC5** [ContinuumIO/anaconda-issues#1134]
Anaconda Navigator Update error:

/Users/Tim-Christoph/anaconda/bin/python /Users/Tim-Christoph/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.1: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.1*
Use "conda info <package>" to see the dependencies for each package.

{'version': '1.2.1', 'pyqt': '4.11.4', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64;x86_64;i386', 'platform': 'osx-64', 'language': 'en', 'conda': '4.1.12', 'qt': '4.8.7', 'python': '3.5.2'}

**Comment by goanpeca** [comment]
Hi @TheTC5 due to some Qt issues you probably need to do the following on the command line

`conda update anaconda`

This should install the latest version of Navigator, Qt and other programs.
