### ISSUE TITLE
Multiple Virtual Environment in Multiple Classes Files

### ISSUE THREAD

**Issue by RodrigoVilanova** [ContinuumIO/anaconda-issues#11352]
Hi there, I'm building a study case project with python and anaconda for web scraping and ML.
I've created two distincts virtual environments, one for web scraping and one for machine learning.
My main code is running in the web scraping virtual env, but I want to call methods from a class that uses the machine learning virtual env. When I do it, the code breaks saying I trying to import modules not installed. Is there a way to do it in anaconda?
I mean, I want to change the virtual env according to the class / method used.
I'm using spyder (3.3.4), anaconda (4.7.12) on linux. I've one virtual env named ML and other named WebScraping.

**Comment by csoja** [comment]
If you are using Anaconda, you'll find conda environments will probably work better for the use case you are describing.  You can find out more about them in the documentation: https://conda.io/projects/conda/en/latest/user-guide/concepts/environments.html

**Comment by RodrigoVilanova** [comment]
Hei csoja,
    Thank you for your reply. As sad I'm using conda environments! :-)
    My question was: Is it possible to switch the conda environments according to methods called from other classes? 
    In other words:
        **From my main code**:
            When I call a **methodX** from **ClassX** I want to use conda **environments X**.
            When I call a **methodY** from **ClassY** I want to use conda **environments Y**.

**Comment by csoja** [comment]
You had said virtual environments  - which is different from a conda environment.  When you said classes - I thought you meant like different school classes - not code.  I had misunderstood your question.  I'm not aware of a way to change environments in the middle of your code execution.

**Comment by RodrigoVilanova** [comment]
Thank you csoja! Sorry about that.
Do anyone have any idea?
