### ISSUE TITLE
Cannot install OS10.15 on MBP

### ISSUE THREAD

**Issue by hkstaub2** [ContinuumIO/anaconda-issues#11362]
### Actual Behavior

All is says is Anaconda is not compatible

I wanto play w/Jupiter Notebook. 

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Please see https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/
A macOS Catalina compatible pkg installer should be available later this week.

**Comment by hkstaub2** [comment]
Thank you
