### ISSUE TITLE
anaconda starting error

### ISSUE THREAD

**Issue by Tanaconda1** [ContinuumIO/anaconda-issues#11369]
# Actual Behavior

1.click icon and stop 「loading applications」
2.command prompt   type anaconda-navigator   then launch successfully.but
(comand prompt)shows error

C:\Users\taisu>conda activate
(base) C:\Users\taisu>anaconda-navigator
C:\Users\taisu\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py:1364: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)

**Comment by csoja** [comment]
The error is just a deprecation warning - and all should work properly.  We will look at handing this more cleanly in the next release of Navigator.  Thank you for the report.
