### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by marcodesouza** [ContinuumIO/anaconda-issues#1137]
Anaconda Navigator Update error:

/home/marco/programas/anaconda2/bin/python /home/marco/programas/anaconda2/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.1: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.1*
  - orange -> pyqt 4.*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'linux-64', 'version': '1.2.1', 'conda': u'4.2.9', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Linux;3.16.0-4-amd64;#1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03);x86_64;', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@marcodesouza thanks for reporting. Dure to updates in the Qt package (now version 5.6.* is available) orange is no longer compatible with the latest version of anaconda (and latest navigator hence). If you want to update anaconda to the latest, you have to uninstall orange. If you still want to use orange you can do so by installing it in a separate environment.

To update anaconda on the command line you can type:

`conda update anaconda`
