### ISSUE TITLE
conda install h5py fails for h5 files with szip compression

### ISSUE THREAD

**Issue by dwr-psandhu** [ContinuumIO/anaconda-issues#11382]
### Actual Behavior
conda install h5py

Then try to read this sample file Use this sample file https://support.hdfgroup.org/ftp/HDF5/examples/files/exbyapi/h5ex_d_szip.h5

It fails because szip compression is not compiled into h5py. This works from pip install of the same version

Here is the related issue https://github.com/conda-forge/h5py-feedstock/issues/63

### Expected Behavior
It should be able to read the h5py file. Again look at the referenced issue above

### Steps to Reproduce

Please see related issue https://github.com/conda-forge/h5py-feedstock/issues/63. There are samples on what to run. For convenience I am embedding them here as well
Using this file https://support.hdfgroup.org/ftp/HDF5/examples/files/exbyapi/h5ex_d_szip.h5
```
import h5py
h5f=h5py.File('h5ex_d_szip.h5')
print(h5f.get('/DS1').compression)
print(h5f.get('/DS1')[:])

```

##### Anaconda or Miniconda version:
anaconda 
conda version 4.7.12

##### `conda info`

<details>

```
(h5py_test) C:\Users\psandhu\Downloads>conda info

     active environment : h5py_test
    active env location : d:\Programs\Anaconda2\envs\h5py_test
            shell level : 3
       user config file : C:\Users\psandhu\.condarc
 populated config files : C:\Users\psandhu\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 2.7.16.final.0
       virtual packages : __cuda=8.0
       base environment : D:\Programs\Anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Programs\Anaconda2\pkgs
                          C:\Users\psandhu\.conda\pkgs
                          C:\Users\psandhu\AppData\Local\conda\conda\pkgs
       envs directories : D:\Programs\Anaconda2\envs
                          C:\Users\psandhu\.conda\envs
                          C:\Users\psandhu\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False


```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at d:\Programs\Anaconda2\envs\h5py_test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2019.8.28                     0    defaults
certifi                   2019.9.11                py37_0    defaults
h5py                      2.9.0            py37h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
intel-openmp              2019.4                      245    defaults
mkl                       2019.4                      245    defaults
mkl-service               2.3.0            py37hb782905_0    defaults
mkl_fft                   1.0.14           py37h14836fe_0    defaults
mkl_random                1.1.0            py37h675688f_0    defaults
numpy                     1.16.5           py37h19fb1c0_0    defaults
numpy-base                1.16.5           py37hc3f5095_0    defaults
openssl                   1.1.1d               he774522_3    defaults
pip                       19.2.3                   py37_0    defaults
pyreadline                2.1                      py37_1    defaults
python                    3.7.4                h5263a28_0    defaults
setuptools                41.4.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.30.0               he774522_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wheel                     0.33.6                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
zlib                      1.2.11               h62dcd97_3    defaults
```

</details>

**Comment by jjhelmus** [comment]
szip is licensed in a manner which prevents use from providing it to all users.

**Comment by dwr-psandhu** [comment]
@jjhelmus So is there a reason why "pip install h5py" is able to provide it ?

**Comment by msarahan** [comment]
People can put whatever they want wherever they want, and you're free to choose. The licenses associated may or may not be important to you as a consumer, but they are very important to us as a distributor. If we make that choice, we make it on behalf of all our users, and it may make our hdf5 packages unusable for many people. The h5py package on PyPI should be communicating this issue somehow. If they aren't, they are implicitly helping commercial users violate this license.

Here is the szip license: https://support.hdfgroup.org/doc_resource/SZIP/Commercial_szip.html

**Comment by dwr-psandhu** [comment]
@msarahan Understood. You can close this issue, as it seems to be a licensing issue. 
And yes, it will break it for many users who download hd5 package (which is distributed with szip and zlib support). So I wonder how they  (hdf5group) are able to work around the distribution issue?

**Comment by msarahan** [comment]
> So I wonder how they (hdf5group) are able to work around the distribution issue?

This is the wrong way to see it.  Read the license.  It binds the end user.  When people install h5py from PyPI and use SZIP, they are bound by that license, whether they know it or not.  It is the end user's responsibility to be aware of and in compliance with all applicable licenses.  There is no "workaround."  Some licenses limit redistribution.  This is not one of them.  We make the choice to not include SZIP so that our users do not get into license issues.

I did a little digging, and wheels are built with an alternative library that avoids the issue: https://github.com/h5py/h5py/issues/706#issuecomment-228069386

We can build this same way.  We'll put it on the list.  No time estimate, though.

**Comment by dwr-psandhu** [comment]
If that is the case, this my 2c on it. conda install always prompts the user for yes/no before install. 
How about a line around that prompt saying that the user is accepting the licenses for the various packages they are about to download and install ?

**Comment by remkade** [comment]
Unfortunately because szip is a patented algorithm we don't have any plans to support it in h5py right now. We may in the future add support for agreement to licenses, but with automated installs and deployments that could get difficult.
