### ISSUE TITLE
Problem with permissions in macOS Catalina

### ISSUE THREAD

**Issue by luismiguells** [ContinuumIO/anaconda-issues#11387]
### Actual Behavior

I upgrade macOS to Catalina. The problem is that now, I can't read any file. I tried to reinstall Anaconda but it doesn't work. I also reinstall the OS. When I run gives me this error:

```
PermissionError: [Errno 1] Operation not permitted: '/Users/luismiguells/...'

```

### Steps to Reproduce

I upgrade to macOS Catalina and I made a clean install with the command line installer.

##### Anaconda or Miniconda version:
Anaconda3

##### Operating System:
macOS Catalina

**Comment by csoja** [comment]
Please see this blog post for tips on Anaconda & Catalina: https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/

**Comment by luismiguells** [comment]
> Please see this blog post for tips on Anaconda & Catalina: https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/

I already do that. The problem is I made a clean installation and it doesn't work.

**Comment by csoja** [comment]
It says "PermissionError" - do you have the appropriate permissions to access that directory in the terminal where you are running the command line installer?  In other words, can you read/write/execute in the terminal in that directory separate from anything to do with the Anaconda installer.

**Comment by luismiguells** [comment]
> It says "PermissionError" - do you have the appropriate permissions to access that directory in the terminal where you are running the command line installer? In other words, can you read/write/execute in the terminal in that directory separate from anything to do with the Anaconda installer.

I already install Anaconda. The error comes when I execute a script.
<img width="709" alt="Captura de Pantalla 2019-10-21 a la(s) 15 18 15" src="https://user-images.githubusercontent.com/25065697/67239988-1b8a0a00-f416-11e9-91b0-8f9833d1f0c1.png">

**Comment by forrestwaters** [comment]
This seems to be a different problem introduced with MacOS Catalina where certain user folders are protected (Desktop/Documents/Downloads). According to Apple, your system is supposed to prompt you to request permission to those folders when access is needed. However that doesn't seem to apply to non-MacOS apps like the python interpreter, or shell commands run via terminal (for what it's worth, this problem also happens for the default python and terminal included with MacOS). 

One workaround you could try:

With Spyder open, hit the open folder button in the top left corner (cmd + o shortcut). Once there, navigate to the folder that you need access to and try to open a file (in your case the Documents folder). Once that is done, re-run your code and see if the permissions error is still there. 

Would you be willing to try that and let us know if it solves your problem?

**Comment by MarcosCarreira** [comment]
I had similar problems, installed the new version, but Jupyter Lab cannot access Desktop and Documents if launched from the Navigator; if launched from the terminal the authorization question pops up and it works; so now Spyder, Notebook and VS Code are ok, but Jupyter Lab still needs to launched by the terminal.

**Comment by DanilZherebtsov** [comment]
> This seems to be a different problem introduced with MacOS Catalina where certain user folders are protected (Desktop/Documents/Downloads). According to Apple, your system is supposed to prompt you to request permission to those folders when access is needed. However that doesn't seem to apply to non-MacOS apps like the python interpreter, or shell commands run via terminal (for what it's worth, this problem also happens for the default python and terminal included with MacOS).
> 
> One workaround you could try:
> 
> With Spyder open, hit the open folder button in the top left corner (cmd + o). Once there, navigate to the folder that you need access to and try to open a file (in your case the Documents folder). Once that is done, re-run your code and see if the permissions error is still there.
> 
> Would you be willing to try that and let us know if it solves your problem?

I've tried what you are proposing. When using the open button I can see and open any script located in that folder. But when I try to:
- navigate to the Documents folder via Spyder File explorer, the folder is empty
- navigate to the Documents folder from IPython console - I get a PermissionError 

Documents folder via "Open" button:
<img width="394" alt="Screenshot 2019-10-24 at 17 39 48" src="https://user-images.githubusercontent.com/35999411/67496830-b0466f00-f685-11e9-8c32-d49967574308.png">

Documents folder via File explorer:
<img width="613" alt="Screenshot 2019-10-24 at 17 40 07" src="https://user-images.githubusercontent.com/35999411/67496864-c3f1d580-f685-11e9-9579-077c33ba6661.png">

IPython console command:
<img width="640" alt="Screenshot 2019-10-24 at 17 40 13" src="https://user-images.githubusercontent.com/35999411/67496901-d3711e80-f685-11e9-9b29-30de3824b8e5.png">

**Comment by luismiguells** [comment]
I run the command `spyder` in the terminal. It helps me to avoid the problem, but when I run Spyder from Anaconda-Navigator. The problem stills.

**Comment by allenea** [comment]
For me too. Have no problem with running from the command line but cannot run on Spyder from Anaconda-Navigator.

**Comment by azeezx** [comment]
Solved:

What I did I create a new folder I call it 'dev' in my user folder and moved all my files & folders in there, then the permission error disappeared.

Hope this will help you as well.

**Comment by DanilZherebtsov** [comment]
> Solved:
> 
> What I did I create a new folder I call it 'dev' in my user folder and moved all my files & folders in there, then the permission error disappeared.
> 
> Hope this will help you as well.

I did the same and it does solve the problem indeed, but not quite. For example you download some data into the Downloads folder and then use that location to import data via Spyder (pd.read_csv('...') and here again you have the same problem. First you have to move those downloads elsewhere then you can import them.

I consider this a temporary workaround...

**Comment by dsimonovic** [comment]
I have granted "Full Disk Access" to Terminal and sh in Privacy settings and it worked. Details are here:
[http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/](url)

**Comment by forrestwaters** [comment]
I have uploaded a new Navigator package for OSX. Now when attempting to access these folders you should receive a prompt the first time requesting permission. You can update by running this from the terminal in the environment where you have anaconda-navigator installed:
```
conda update anaconda-navigator
```
Once updated, the easiest way I've found to generate the permissions prompt for Navigator for the first time is to open Spyder and run something like this in the console (can replace Desktop with Downloads/Documents folder depending which you need access to):
```
import os
os.listdir('Desktop')
```

**Comment by MarcosCarreira** [comment]
It works! I had a new computer with the same problem, updated navigator and the questions are asked for access to Anaconda-Navigator.app both in Spyder and JupyterLab (it asks again on each though).
Thanks!

**Comment by forrestwaters** [comment]
Thanks for testing @MarcosCarreira , glad that worked.

**Comment by DanilZherebtsov** [comment]
> I have uploaded a new Navigator package for OSX. Now when attempting to access these folders you should receive a prompt the first time requesting permission. You can update by running this from the terminal in the environment where you have anaconda-navigator installed:
> 
> ```
> conda update anaconda-navigator
> ```
> 
> Once updated, the easiest way I've found to generate the permissions prompt for Navigator for the first time is to open Spyder and run something like this in the console (can replace Desktop with Downloads/Documents folder depending which you need access to):
> 
> ```
> import os
> os.listdir('Desktop')
> ```

Thanks for the fix. It does work as described. One thing though: it keeps asking for the permission over and over. So after the first permission is granted, it does access the folder, but keeps asking if again I try to access the same folder... This is all within a single Spyder (python console) session. Any thoughts on that?

**Comment by MarcosCarreira** [comment]
Unfortunately the new Catalina update broke it - I decided to not use these folders for any code whatsoever.

**Comment by DanilZherebtsov** [comment]
Can't believe that it will stay like that! Anyone please update if you will find a fix for that.

**Comment by mhadi813** [comment]
> I have granted "Full Disk Access" to Terminal and sh in Privacy settings and it worked. Details are here:
> http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

it worked for me. Thank
I add python3, terminal and bunch of other jupyter apps
![image](https://user-images.githubusercontent.com/49832502/73627608-59a0e780-461b-11ea-867e-7d544974fc7a.png)

**Comment by keslingmj** [comment]
> This seems to be a different problem introduced with MacOS Catalina where certain user folders are protected (Desktop/Documents/Downloads). According to Apple, your system is supposed to prompt you to request permission to those folders when access is needed. However that doesn't seem to apply to non-MacOS apps like the python interpreter, or shell commands run via terminal (for what it's worth, this problem also happens for the default python and terminal included with MacOS).
> 
> One workaround you could try:
> 
> With Spyder open, hit the open folder button in the top left corner (cmd + o). Once there, navigate to the folder that you need access to and try to open a file (in your case the Documents folder). Once that is done, re-run your code and see if the permissions error is still there.
> 
> Would you be willing to try that and let us know if it solves your problem?

This worked for me.  I should add that simply navigating to the folder in question is insufficient to get Anaconda's Spyder to recognize that directory as readable by macOS Catalina.  I needed to create a text file in the directory in question and actually open it in Spyder.  After that, any file in that directory could be read.  (My other files aren't actually .txt files or .py files, so I couldn't open them in Spyder.)

**Comment by Simsimasel** [comment]
Hello i have anaconda- navigator problem, it doesn't start. i tried to remove .anaconda once i launche the navigator the .anaconda folder restore.
thank you for helping me : macos sierre 10.12.6
active environment : base
    active env location : /Users/utilisateur/anaconda3
            shell level : 1
       user config file : /Users/utilisateur/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __osx=10.12.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/utilisateur/anaconda3  (writable)
      conda av data dir : /Users/utilisateur/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/utilisateur/anaconda3/pkgs
                          /Users/utilisateur/.conda/pkgs
       envs directories : /Users/utilisateur/anaconda3/envs
                          /Users/utilisateur/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.8 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False





# packages in environment at /Users/utilisateur/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2021.05                  py38_0  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        2.0.3                    py38_0  
anaconda-project          0.9.1              pyhd3eb1b0_1  
anyio                     2.2.0            py38hecd8cb5_1  
appdirs                   1.4.4                      py_0  
applaunchservices         0.2.1                      py_0  
appnope                   0.1.2           py38hecd8cb5_1001  
appscript                 1.1.2            py38h9ed2024_0  
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38h9ed2024_1  
asn1crypto                1.4.0                      py_0  
astroid                   2.5              py38hecd8cb5_1  
astropy                   4.2.1            py38h9ed2024_1  
async_generator           1.10               pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.6              pyhd3eb1b0_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.0                pyhd3eb1b0_2  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.3              pyha847dfd_0  
bitarray                  1.9.2            py38h9ed2024_1  
bkcharts                  0.2                      py38_0  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
blosc                     1.21.0               h2842e9f_0  
bokeh                     2.3.2            py38hecd8cb5_0  
boto                      2.49.0                   py38_0  
bottleneck                1.3.2            py38hf1fa96c_1  
brotlipy                  0.7.0           py38h9ed2024_1003  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.17.1               h9ed2024_0  
ca-certificates           2021.4.13            hecd8cb5_1  
certifi                   2020.12.5        py38hecd8cb5_0  
cffi                      1.14.5           py38h2125817_0  
chardet                   4.0.0           py38hecd8cb5_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.4              pyhd3eb1b0_0  
conda                     4.10.3           py38hecd8cb5_0  
conda-build               3.21.4           py38hecd8cb5_0  
conda-content-trust       0.1.1              pyhd3eb1b0_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.7.3            py38h9ed2024_1  
conda-repo-cli            1.0.4              pyhd3eb1b0_0  
conda-token               0.3.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.6.0.post1                py_0  
cryptography              3.4.7            py38h2fd3fbb_0  
curl                      7.71.1               hb0a8c7a_1  
cycler                    0.10.0                   py38_0  
cython                    0.29.23          py38h23ab428_0  
cytoolz                   0.11.0           py38haf1e3a3_0  
dask                      2021.4.0           pyhd3eb1b0_0  
dask-core                 2021.4.0           pyhd3eb1b0_0  
dbus                      1.13.18              h18a8e69_0  
decorator                 5.0.6              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
distributed               2021.4.0         py38hecd8cb5_0  
docutils                  0.17             py38hecd8cb5_1  
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.3.0                h23ab428_2  
fastcache                 1.1.0            py38h1de35cc_0  
filelock                  3.0.12             pyhd3eb1b0_1  
flake8                    3.9.0              pyhd3eb1b0_0  
flask                     1.1.2              pyhd3eb1b0_0  
freetype                  2.10.4               ha233b18_0  
fsspec                    0.9.0              pyhd3eb1b0_0  
future                    0.18.2                   py38_1  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.21.0               h7535e17_0  
gevent                    21.1.2           py38h9ed2024_1  
glib                      2.68.1               hdf23fa2_0  
glob2                     0.7                pyhd3eb1b0_0  
gmp                       6.2.1                h23ab428_2  
gmpy2                     2.0.8            py38h6ef4df4_3  
greenlet                  1.0.0            py38h23ab428_2  
h5py                      2.10.0           py38h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
icu                       58.2                 h0a44026_3  
idna                      2.10               pyhd3eb1b0_0  
imageio                   2.9.0              pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        3.10.0           py38hecd8cb5_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2021.2.0           hecd8cb5_564  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.22.0           py38h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
itsdangerous              1.1.0              pyhd3eb1b0_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.2           py38hecd8cb5_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   he5867d9_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter-packaging         0.7.12             pyhd3eb1b0_0  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py38hecd8cb5_0  
jupyter_server            1.4.1            py38hecd8cb5_0  
jupyterlab                3.0.14             pyhd3eb1b0_1  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.4.0              pyhd3eb1b0_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keyring                   22.3.0           py38hecd8cb5_0  
kiwisolver                1.3.1            py38h23ab428_0  
krb5                      1.18.2               h75d18d8_0  
lazy-object-proxy         1.6.0            py38h9ed2024_0  
lcms2                     2.12                 hf1fd2bf_0  
libarchive                3.4.2                haa3ed63_0  
libcurl                   7.71.1               h8a08a2b_1  
libcxx                    10.0.0                        1  
libedit                   3.1.20210216         h9ed2024_1  
libev                     4.33                 haf1e3a3_0  
libffi                    3.3                  hb1e8313_2  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
liblief                   0.10.1               h0a44026_0  
libllvm10                 10.0.1               h76017ad_5  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h23ab428_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.2.0                h87d7836_0  
libuv                     1.40.0               haf1e3a3_0  
libwebp-base              1.2.0                h9ed2024_0  
libxml2                   2.9.10               h7cdb67c_3  
libxslt                   1.1.34               h83b36ba_0  
llvm-openmp               10.0.0               h28b9765_0  
llvmlite                  0.36.0           py38he4411ff_4  
locket                    0.2.1            py38hecd8cb5_1  
lxml                      4.6.3            py38h26b266a_0  
lz4-c                     1.9.3                h23ab428_0  
lzo                       2.10                 haf1e3a3_2  
markupsafe                1.1.1            py38h1de35cc_1  
matplotlib                3.3.4            py38hecd8cb5_0  
matplotlib-base           3.3.4            py38h8b3ea08_0  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h1de35cc_1001  
mkl                       2021.2.0           hecd8cb5_269  
mkl-service               2.3.0            py38h9ed2024_1  
mkl_fft                   1.3.0            py38h4a7008c_2  
mkl_random                1.2.1            py38hb2f4e1b_2  
mock                      4.0.3              pyhd3eb1b0_0  
more-itertools            8.7.0              pyhd3eb1b0_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.2                h9066e36_1  
mpmath                    1.2.1            py38hecd8cb5_0  
msgpack-python            1.0.2            py38hf7b0b51_1  
multipledispatch          0.6.0                    py38_0  
mypy_extensions           0.4.3                    py38_0  
navigator-updater         0.2.1                    py38_0  
nbclassic                 0.2.6              pyhd3eb1b0_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
nltk                      3.6.1              pyhd3eb1b0_0  
nose                      1.3.7           pyhd3eb1b0_1006  
notebook                  6.3.0            py38hecd8cb5_0  
numba                     0.53.1           py38hb2f4e1b_0  
numexpr                   2.7.3            py38h5873af2_1  
numpy                     1.20.1           py38hd6e1bb9_0  
numpy-base                1.20.1           py38h585ceec_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46                       py_0  
openpyxl                  3.0.7              pyhd3eb1b0_0  
openssl                   1.1.1k               h9ed2024_0  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.4            py38h23ab428_0  
pandoc                    2.12                 hecd8cb5_0  
pandocfilters             1.4.3            py38hecd8cb5_1  
parso                     0.7.0                      py_0  
partd                     1.2.0              pyhd3eb1b0_0  
path                      15.1.2           py38hecd8cb5_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5            py38hecd8cb5_2  
pathspec                  0.7.0                      py_0  
patsy                     0.5.1                    py38_0  
pcre                      8.44                 hb1e8313_0  
pep8                      1.7.1                    py38_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.2.0            py38h5270095_0  
pip                       21.0.1           py38hecd8cb5_0  
pkginfo                   1.7.0            py38hecd8cb5_0  
pluggy                    0.13.1           py38hecd8cb5_0  
ply                       3.11                     py38_0  
prometheus_client         0.10.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
psutil                    5.8.0            py38h9ed2024_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.10.0             pyhd3eb1b0_0  
py-lief                   0.10.1           py38haf313ee_0  
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py38h1de35cc_1  
pycparser                 2.20                       py_2  
pycurl                    7.43.0.6         py38hddc9c9b_0  
pydocstyle                6.0.0              pyhd3eb1b0_0  
pyerfa                    1.7.3            py38h9ed2024_0  
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.8.1              pyhd3eb1b0_0  
pylint                    2.7.4            py38hecd8cb5_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pyodbc                    4.0.30           py38h0a44026_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h655552a_2  
pyqt5                     5.15.0                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyrsistent                0.17.3           py38haf1e3a3_0  
pysocks                   1.7.1                    py38_1  
pytables                  3.6.1            py38h4727e94_0  
pytest                    6.2.3            py38hecd8cb5_2  
python                    3.8.8                h88f2d9e_5  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python.app                3                py38h9ed2024_0  
pytz                      2021.1             pyhd3eb1b0_0  
pywavelets                1.1.1            py38haf1e3a3_2  
pyyaml                    5.4.1            py38h9ed2024_1  
pyzmq                     20.0.0           py38h23ab428_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h9ed2024_0  
regex                     2021.4.4         py38h9ed2024_0  
requests                  2.25.1             pyhd3eb1b0_0  
ripgrep                   12.1.1                        0  
rope                      0.18.0                     py_0  
rtree                     0.9.7            py38hecd8cb5_1  
ruamel_yaml               0.15.100         py38h9ed2024_0  
scikit-image              0.18.1           py38hb2f4e1b_0  
scikit-learn              0.24.1           py38hb2f4e1b_0  
scipy                     1.6.2            py38hd5f7400_1  
seaborn                   0.11.1             pyhd3eb1b0_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py38hecd8cb5_0  
simplegeneric             0.8.1                    py38_2  
singledispatch            3.6.1           pyhd3eb1b0_1001  
sip                       4.19.8           py38h0a44026_0  
six                       1.15.0           py38hecd8cb5_0  
sniffio                   1.2.0            py38hecd8cb5_1  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcollections         2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
soupsieve                 2.2.1              pyhd3eb1b0_0  
sphinx                    4.0.1              pyhd3eb1b0_0  
sphinxcontrib             1.0                      py38_1  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    4.2.5            py38hecd8cb5_0  
spyder-kernels            1.10.2           py38hecd8cb5_0  
sqlalchemy                1.4.7            py38h9ed2024_0  
sqlite                    3.35.4               hce871da_0  
statsmodels               0.12.2           py38h9ed2024_0  
sympy                     1.8              py38hecd8cb5_0  
tbb                       2020.3               h879752b_0  
tblib                     1.7.0                      py_0  
terminado                 0.9.4            py38hecd8cb5_0  
testpath                  0.4.4              pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2020.10.1        py38h0cf3a3e_2  
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.11.1             pyhd3eb1b0_0  
tornado                   6.1              py38h9ed2024_0  
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py38h9ed2024_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py38h23ab428_0  
unicodecsv                0.14.1                   py38_0  
unixodbc                  2.3.9                haf1e3a3_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
watchdog                  1.0.2            py38h9ed2024_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1              pyhd3eb1b0_0  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.12.1           py38haf1e3a3_1  
wurlitzer                 2.1.0            py38hecd8cb5_0  
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                1.3.8              pyhd3eb1b0_0  
xlwings                   0.23.0           py38hecd8cb5_0  
xlwt                      1.3.0                    py38_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                h23ab428_0  
zict                      2.0.0              pyhd3eb1b0_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zope                      1.0                      py38_1  
zope.event                4.5.0                    py38_0  
zope.interface            5.3.0            py38h9ed2024_0  
zstd                      1.4.5                h41d2c2f_0

**Comment by Simsimasel** [comment]
hello i found my problem i had to go to "https://docs.anaconda.com/anaconda/install/#old-os" and choose the right version to my mac os on anaconda archive "https://repo.anaconda.com/archive/"

good luck.
