### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by gerardojuan** [ContinuumIO/anaconda-issues#1138]
Anaconda Navigator Update error:

Extra data: line 2 column 1 (char 80)

{'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64;x86_64;i386', 'pyqt': '4.11.4', 'version': '1.2.2', 'qt': '4.8.7', 'language': 'en', 'python': '3.5.2', 'conda': '4.1.9', 'platform': 'osx-64'}

**Comment by goanpeca** [comment]
@gerardojuan this has been in fix in the latest version of Navigator, please go to the command line ant type

`conda update anaconda-navigator` 

or 

`conda update anaconda` to update to the latests anaconda distribution

**Comment by gerardojuan** [comment]
Thanks. Works now.
