### ISSUE TITLE
Numpy 1.17.*

### ISSUE THREAD

**Issue by Dan-Patterson** [ContinuumIO/anaconda-issues#11399]
Python 3.6 and 3.7's win 64-bit distributions have numpy at 1.16.5, yet the equivalent Linux distirbutions have numpy 1.17.*.  Is there a reason for this?

```
# All requested packages already installed.
# packages in environment at C:\...\....:
#
numpy                     1.16.5           py36h19fb1c0_0

```
even --no-pin does nothing

**Comment by jjhelmus** [comment]
numpy 1.17.2 packages are now available for win-32 and win-64.

**Comment by jjhelmus** [comment]
I'll look at getting 1.17.3 packages for all platform out next week.

**Comment by Dan-Patterson** [comment]
Much appreciated.
