### ISSUE TITLE
Anaconda syntax error on macOS Catalina

### ISSUE THREAD

**Issue by DrMcQ** [ContinuumIO/anaconda-issues#11392]
I have an issue on Anaconda and I couldn't figure it out.
I couldn't update anything in Anaconda. When I opened the terminal, it asked me to change the shell to ZSH. I did so. Then, the following issue happened. I have tried to change the shell to BASH, yet still doesn't work.

Last login: Tue Oct 22 16:11:48 on ttys000
/Users/yulin/.anaconda/navigator/a.tool ; exit;
lin@Dr ~ % /Users/lin/.anaconda/navigator/a.tool ; exit;
/Users/lin/.anaconda/navigator/a.tool: line 1: syntax error near unexpected token (' /Users/lin/.anaconda/navigator/a.tool: line 1: bash --init-file <(echo "source activate /opt/anaconda3;")'

[Process completed]

**Comment by csoja** [comment]
Have you seen this blog post? https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/
Particularly step 3.
macOS Catalina made a number of changes that adversely affected Anaconda.
