### ISSUE TITLE
Anaconda navigator not opening

### ISSUE THREAD

**Issue by ItsVk** [ContinuumIO/anaconda-issues#11395]
I downloaded anaconda(64-bit) a few months ago and it used to be working fine back then.Now when i try to open the application the cursor shows loading and then its back to normal yet not opening 
i tried 
1)conda update conda and it still didn't work 

Hope someone else might have the same problem and have found the solution please let me in on it as soon as possible

**Comment by csoja** [comment]
Closing as there is insufficient information in this report to help.  When opening an issue, please provide all the information requested in the GitHub issue template for this repository.
