### ISSUE TITLE
Problem installing Anaconda on Windows 10

### ISSUE THREAD

**Issue by danilolimadutra** [ContinuumIO/anaconda-issues#11407]
After Anaconda installation, I can not find Anaconda icon on Windows Start Menu neither Anaconda Prompt, I did try to run anaconda-navigator command on Windows Prompt, but it is not a recognizable command.

The installation is completed without errors or warning. I have tried in two diferent PCs with Windows 10. Same issue at both.

I am using this installation guide, https://docs.anaconda.com/anaconda/install/windows/ 

I am try install this Anaconda version, Anaconda3-2019.10-Windows-x86_64.exe

I am using Windows 10 Pro, version 1903

**Comment by csoja** [comment]
Have you tried some of the suggestions in the troubleshooting section of the documentation?
https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#cannot-see-anaconda-menu-shortcuts-after-installation-on-windows
