### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by pakistanimoon** [ContinuumIO/anaconda-issues#11404]
### Expected Behavior

![image](https://user-images.githubusercontent.com/5585103/67633658-3fe15d00-f8d4-11e9-84a5-a9e05a4bfa66.png)

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
It looks like your .condarc file may have gotten corrupted.  Please see the docs for instructions on how to fix this: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
