### ISSUE TITLE
Build jupyter for python 3.8

### ISSUE THREAD

**Issue by eddy-geek** [ContinuumIO/anaconda-issues#11414]
Can you please build jupyter with python 3.8?
I see support is built for some time according to ipython.org: 
> IPython 7.3: several bugfixes, minor improvements and Python 3.8 support (February 18, 2019)

but https://anaconda.org/anaconda/jupyter/files show only 35/36/37 versions.

### Actual Behavior

```bash
conda create -n jupyter python=3.8.0  jupyter=1.0.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package python conflicts for:
jupyter=1.0.0 -> ipywidgets -> nbformat[version='>=4.2.0'] -> jsonschema[version='>=2.4,!=2.5.0'] -> functools32 -> python[version='<3']
python=3.8.0
jupyter=1.0.0 -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package pip conflicts for:
python=3.8.0 -> pip
jupyter=1.0.0 -> python=3.6 -> pip
Package python-dateutil conflicts for:
jupyter=1.0.0 -> ipykernel -> jupyter_client -> python-dateutil[version='>=2.1']
Package certifi conflicts for:
python=3.8.0 -> pip -> setuptools -> certifi[version='>=2016.09']
jupyter=1.0.0 -> jupyter_console -> pygments -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
jupyter=1.0.0 -> ipykernel -> tornado[version='>=4.0'] -> certifi
Package wheel conflicts for:
jupyter=1.0.0 -> python=3.6 -> pip -> wheel
python=3.8.0 -> pip -> wheel
Package ca-certificates conflicts for:
jupyter=1.0.0 -> python=3.6 -> ca-certificates
python=3.8.0 -> openssl[version='>=1.1.1d,<1.1.2a'] -> ca-certificates
Package ipython conflicts for:
jupyter=1.0.0 -> notebook -> ipython[version='>=4.0|>=4.0.0|>=5.0']
Package setuptools conflicts for:
jupyter=1.0.0 -> jupyter_console -> pygments -> setuptools
python=3.8.0 -> pip -> setuptools
```

### Expected Behavior

Installs ok

### Steps to Reproduce

```bash
conda create -n jupyter python=3.8.0  jupyter=1.0.0
```

##### `conda info`

<details>

```bash
conda info # (partial)

     active environment : base
            shell level : 1
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/2.6.32-754.14.2.el6.x86_64 rhel/6.10 glibc/2.12
                UID:GID : 200593:200272
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`
main / free / forge

**Comment by msarahan** [comment]
python 3.8 builds of all packages are underway and are being released as they are completed.  This will be out soon, but we have no concrete timeline for you - just whenever the build machines get to it.

**Comment by drorata** [comment]
@msarahan it seems like it takes longer than few days. Is there some ETA?

**Comment by eddy-geek** [comment]
seems pretty slow
* numpy got built for py38 on osx-64 & linux-64 built ~7 days ago (but not windows)
* pandas has no py38 build yet (except on conda-forge 10 days ago)
* ipython has no py38 build yet

so, I'm not holding my breath :-)

**Comment by vegerot** [comment]
I tried making a new environment with `conda create -n py38 -c conda-forge python=3.8 jupyter`, but when I run `jupyter console` I get Python 3.7.3.  Is this because installing `jupyter` doesn't install a 3.8 kernel with it?  Do I have to do extra steps after installing python 3.8 and jupyter 1.0.0-py_2 to get a 3.8 kernel?  How do I do that?

**Comment by JordanRex** [comment]
The above is happening because nb_conda_kernels is required to open kernels from other conda envs than the one (mostly base) when you started the Jupyter service, and it doesnt support installation on 3.8 as of yet

**Comment by eddy-geek** [comment]
Finally!
* jupyter py38 packages were (last) built on February 29.
* `conda create` defaults to python 3.8 as expected
* I am able to access python38 in jupyterlab afterwards
so, closing
