### ISSUE TITLE
OS X packages flagged by VirusTotal's CRDF engine as "malicious"

### ISSUE THREAD

**Issue by npongratz** [ContinuumIO/anaconda-issues#11418]
### Actual Behavior

Anaconda 2019.10 installers for OS X are being flagged as having a virus.

Submitting the URLs of any of the Anaconda 2019.10 installers (Python 3.7 and 2.7, graphical and command line installers) to VirusTotal.com results in the CRDF engine flagging said installer as "Malicious".

Example for Python 3.7 macOS graphical installer: https://www.virustotal.com/gui/url/86a0f70e97bf1a7b39ac84e18f78ccda3b685aa5bd5ee1d44466fd5b37ecbed5/detection

### Expected Behavior

Hopefully there are no viruses in the distribution. I suspect there are none, and this is a false positive from CRDF's engine, but it'd be nice to get confirmation of such.

### Steps to Reproduce

1. Go to https://www.anaconda.com/distribution/ and copy the URL for any of the OS X installers 
2. Go to https://www.virustotal.com/gui/home/url
3. Submit installer's URL to VirusTotal

##### Anaconda or Miniconda version:

Anaconda3-2019.10-MacOSX

##### Operating System:

OS X

##### `conda info`

Not applicable.

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

Not applicable.

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by msarahan** [comment]
We didn't knowingly put any in.  I'm not sure there's much else we can say without a much more detailed result from CRDF.

**Comment by npongratz** [comment]
Thanks! I assume it's a false positive. Mainly just wanted you to be aware.
