### ISSUE TITLE
Bokeh 1.4.0 available 

### ISSUE THREAD

**Issue by bryevdv** [ContinuumIO/anaconda-issues#11425]
From all the standard locations (note: this is the final release to support python 2.7 or 3.5)

cc @jjhelmus

**Comment by csoja** [comment]
@bryevdv Thanks for letting us know!

**Comment by jjhelmus** [comment]
bokeh 1.4.0 packages are now available for Python 2.7, 3.6 and 3.7 for all supported platforms.  Python 3.8 packages will be releases in the near future once our 3.8 build out reaches that level.
