### ISSUE TITLE
What to do **BEFORE** upgrading to MacOs Catalina to preserve virtual envs.

### ISSUE THREAD

**Issue by FalconBFR** [ContinuumIO/anaconda-issues#11422]
### Actual Behavior

N.A.///
(It is very hard to find a proper and complete guide for beginners to SMOOTHLY Migrate to Mac OS Mojave BEFORE all that migration mess happens. Like exporting the virtual envs. and uninstalling anaconda before upgrading and doing another fresh installation. Many thanks) 

### Expected Behavior

A way to export virtual environments and preserve them into a new, clean installation of Anaconda on Mac OS Catalina after upgrading to Mac OS Mojave

### Steps to Reproduce

///

##### Anaconda or Miniconda version:

////

##### Operating System:
Mac OS Mojave > Mac OS Catalina

##### `conda info`
/////

<details>

/////
PASTE OUTPUT HERE:

/////

</details>

////////////
<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by msarahan** [comment]
The repair instructions at https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/ are probably best. Export and recreate risks messing up any pip installed stuff, because installation order matters but it is not tracked by pip.
