### ISSUE TITLE
Error launching the Navigator

### ISSUE THREAD

**Issue by Guillaume2509** [ContinuumIO/anaconda-issues#11420]
### Actual Behavior

The Anaconda Navigator won't launch. It has launched without issue before until I installed VS Code at the last sign in. When launching, I get this error message:

![image](https://user-images.githubusercontent.com/45839232/68077879-293e7880-fda2-11e9-9e36-7d2c80bc6965.png)

### Expected Behavior

To launch the navigator as usual.

### Steps to Reproduce

I don't know how it was caused, althought I remember the last time I opened the navigator, I used it to install VS Code from within the navigator.

##### Anaconda or Miniconda version:

Latest as of 11/02/2019

##### Operating System:

Windows 10

**Comment by csoja** [comment]
Looks like your .condarc conda configuration file got corrupted.  Check the docs for tips on how to fix this: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
