### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Sharolyn** [ContinuumIO/anaconda-issues#11433]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
