### ISSUE TITLE
Anaconda navigator doesn't allow upgrade to TF2

### ISSUE THREAD

**Issue by MaverickMeerkat** [ContinuumIO/anaconda-issues#11445]
The version it installs is 1.10 for some reason, and even if I "Mark for update", it doesn't allow any update. I had to manually open the terminal and upgrade. The change doesn't appear in the GUI of the Navigator even after manual update.

**Comment by csoja** [comment]
Closing - there is insufficient information here to be able to reproduce the issue. The issue template is critical to complete when filing Github issues here.  It requests information that is critical to be able to offer any helpful advice.
