### ISSUE TITLE
`notebook` package version 6.0.2 is not available in `pkgs/main`

### ISSUE THREAD

**Issue by adt123** [ContinuumIO/anaconda-issues#11443]
The Jupyter team released `notebook` version 6.0.2 about a week ago (https://github.com/jupyter/notebook/releases/tag/6.0.2). I wanted to install this version of `notebook` using `conda`, but I noticed that the latest version available via `conda search` was 6.0.1, in the `pkgs/main` channel. What is generally the procedure for pushing new package releases? Also, is there a plan to push the latest `notebook` package?

I'm running `conda` version 4.7.11.

**Comment by jjhelmus** [comment]
`notebook` 6.0.2 packages are now available in `pkgs/main`.
