### ISSUE TITLE
[Security] libxslt 1.1.34 - Request for update

### ISSUE THREAD

**Issue by skukhtichev** [ContinuumIO/anaconda-issues#11449]
Hello Anaconda Team,

libxslt version 1.1.34 with several fixes and improvements was released: 
https://gitlab.gnome.org/GNOME/libxslt/commit/3653123f992db24cec417d12600f4c67388025e3

Could you please update libxslt in your repositories to version 1.1.34?

links:
ftp://xmlsoft.org/libxslt/libxslt-1.1.34.tar.gz
http://xmlsoft.org/XSLT/downloads.html

**Comment by rolweber** [comment]
ping?

**Comment by skukhtichev** [comment]
Hello Anaconda Team, libxslt 1.1.34 contains security fixes. Could you please update its version in the Anaconda Cloud Repository?

**Comment by csoja** [comment]
Thank you for the report.
libxslt was updated to 1.1.34 on 2020-06-12.
