### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by zhaossbnu** [ContinuumIO/anaconda-issues#1144]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - mayavi ==4.4.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.2', 'platform': 'win-32', 'pyqt': '4.11.4', 'language': 'zh_CN', 'os': 'Windows;10;10.0.10240;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'qt': '4.8.7', 'conda': '4.1.6', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
Hi @zhaossbnu the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
