### ISSUE TITLE
anaconda.org blacklisted by Cisco intrusion prevention due to bad conda packages 

### ISSUE THREAD

**Issue by Tagar** [ContinuumIO/anaconda-issues#11447]
Cisco Talos why they blacklisted whole anaconda.org domain.

![image](https://user-images.githubusercontent.com/3013418/68712471-06a61f80-0559-11ea-969a-b9fa90512e5f.png)

See details at

https://www.virustotal.com/gui/domain/anaconda.org/relations

Also please check 
https://github.com/conda-forge/staged-recipes/issues/10132
for more details 

See for example

https://www.virustotal.com/gui/url/220df9fa6f6b8dce9e119703b4e9837b00a336b2717f5a0d419651a85b9ee7c7/detection

This for example
https://anaconda.org/heyopler/putlockershq-watch-doctor-sleep-2019-full-or-free-123movies/notebook
is considered phishing by virustotal

Also please submit a dispute ticket at
https://talosintelligence.com/reputation
as this can only come from owners..

Thank you

**Comment by csoja** [comment]
Thank you for the report.   We are actively working with Cisco to get anaconda.org removed from the blacklist.  We also continue to remove spam accounts from anaconda.org (and have been doing so for quite some time).   The heyopler account has been removed.  We are also looking at other ways to reduce the number of spam accounts created in the first place.  Hopefully, we can get it resolved quickly.

**Comment by Tagar** [comment]
Thank you @csoja

**Comment by Tagar** [comment]
I see Cisco removed anaconda.org from blacklist 

![image](https://user-images.githubusercontent.com/3013418/68808422-f2c8ef00-0626-11ea-979a-dda92c0fedd1.png)

Thanks again @csoja

**Comment by tnguyen90** [comment]
This happened at my uni today, Talos seems to blacklist anaconda.org again,

https://talosintelligence.com/reputation_center/lookup?search=anaconda.org


BLACKLISTED | Yes
-- | --
CLASSIFICATION | Phishing
FIRST SEEN | 2019-11-09T10:44:35 UTC
EXPIRATION DATE | 2020-01-10T09:35:37 UTC
STATUS | ACTIVE

I'm not sure what can be done to prevent this? Perhaps the Conda dev can write to the Talos dev to stop it from blacklisting Conda? I feel like this repetitive pattern has its own set of reasons.

**Comment by Tagar** [comment]
Yep anaconda.org is not available for us too

**Comment by tnguyen90** [comment]
> Yep anaconda.org is not available for us too

Hi @Tagar, can you reopen the issue so that the devs can see it? At the moment its status is still "closed".

**Comment by Tagar** [comment]
And they fixed it again
