### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by darioromero** [ContinuumIO/anaconda-issues#1145]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - pydot-ng ==1.0.0.15
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'python': '3.5.2', 'language': 'en_US', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'version': '1.2.1', 'qt': '4.8.7', 'conda': '4.1.11', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Hi @darioromero  the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
