### ISSUE TITLE
ld from binutils_impl-linux-64 does not look for libraries under $CONDA_PREFIX/lib

### ISSUE THREAD

**Issue by rainwoodman** [ContinuumIO/anaconda-issues#11458]
I noticed this when trying to build a package that requires bzip2 with the anaconda compiler suite.
Even though the package is installed, the anaconda linker refuses to find it. I remember this used to work before.

```
(base) [yfeng1@waterfall fitsio]$ ls $CONDA_PREFIX/lib/libbz2.a
/home/yfeng1/anaconda3/lib/libbz2.a
(base) [yfeng1@waterfall fitsio]$ $LD a.o -lbz2
/home/yfeng1/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld: cannot find -lbz2
```

The path $CONDA_PREFIX/lib is not included in the search path of ld:
```
(base) [yfeng1@waterfall fitsio]$ $LD a.o -lbz2 --verbose | grep SEARCH
SEARCH_DIR("=/opt/conda/conda-bld/compilers_linux-64_1534500488818/work/gcc_built/x86_64-conda_cos6-linux-gnu/lib64");
SEARCH_DIR("=/usr/local/lib64");
SEARCH_DIR("=/lib64");
SEARCH_DIR("=/usr/lib64");
SEARCH_DIR("=/opt/conda/conda-bld/compilers_linux-64_1534500488818/work/gcc_built/x86_64-conda_cos6-linux-gnu/lib");
SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib");
```
I imagine this would break a lot of conda-build recipes, but obviously it isn't. Is there anything I am missing?

**Comment by mingwandroid** [comment]
This is deliberate. I do not want to force linking to our libraries on people who do not want that to happen. Set CONDA_BUILD=1 before activating your env if you do want -L${PREFIX}/lib (and -I${PREFIX}/include) added to the flags.

**Comment by rainwoodman** [comment]
Thanks for the explanation!
