### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by lbeltran71** [ContinuumIO/anaconda-issues#1146]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.5*
  - vtk ==6.3.0
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386', 'pyqt': '4.11.4', 'language': 'en', 'python': '3.5.2', 'platform': 'osx-64', 'conda': '4.2.9', 'version': '1.2.1', 'qt': '4.8.7'}

**Comment by goanpeca** [comment]
Hi @lbeltran71  the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
