### ISSUE TITLE
Anaconda installation fails on MacOS Catalina, segmentation fault 11 error

### ISSUE THREAD

**Issue by fritshermans** [ContinuumIO/anaconda-issues#11473]
When trying to install Anaconda using the command line installer on my Macbook Pro with MacOS Catalina, i get an error `Segmentation fault: 11`. I've removed old installations of Anaconda and use the default installation path.

### Actual Behavior

I tried to install Anaconda using: 

`bash Anaconda3-2019.10-MacOSX-x86_64.sh`

The error is:

`Collecting package metadata (current_repodata.json): | Anaconda3-2019.10-MacOSX-x86_64.sh: line 381: 13355 Segmentation fault: 11  CONDA_SAFETY_CHECKS=disabled CONDA_EXTRA_SAFETY_CHECKS=no CONDA_ROLLBACK_ENABLED=no CONDA_CHANNELS=https://repo.anaconda.com/pkgs/main,https://repo.anaconda.com/pkgs/main,https://repo.anaconda.com/pkgs/r,https://repo.anaconda.com/pkgs/pro CONDA_PKGS_DIRS="$PREFIX/pkgs" "$CONDA_EXEC" install --offline --file "$PREFIX/pkgs/env.txt" -yp "$PREFIX"`

### Expected Behavior

I expected Anaconda to be installed.

### Steps to Reproduce

`bash Anaconda3-2019.10-MacOSX-x86_64.sh`

##### Anaconda or Miniconda version:

Anaconda version 2019.10

##### Operating System:

MacOS Catalina 10.15.1

**Comment by forrestwaters** [comment]
I haven't been able to reproduce this on my own install of Catalina 10.15.1. Out of curiosity, is this reproducible for you if you try the installation again? Does this also happen for you with Miniconda?
https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-MacOSX-x86_64.sh

**Comment by fritshermans** [comment]
@forrestwaters i have tried it many times with different paths and with miniconda as well. in the end i solved it by following the steps by Anaconda on how to fix the installation in Catalina ([link](https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/)).
