### ISSUE TITLE
Target directory from installer command line option not recognized

### ISSUE THREAD

**Issue by wulmer** [ContinuumIO/anaconda-issues#1147]
Hi,

I tried running the latest installer `Anaconda3-4.2.0-Windows-x86_64.exe` with the silent option. However I did not succeed in changing the target installation directory.
I tried running the installer as described in the docs with the following command:

    start /wait "" Anaconda3-4.2.0-Windows-x86_64.exe /InstallationType=AllUsers /AddToPath=1 /RegisterPython=0 /D=C:\Anaconda3

What happens is that Anaconda is always installed into `C:\Program Files\Anaconda3`.
I tried the exactly same command line with the Miniconda installer, like below:

    start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=AllUsers /AddToPath=1 /RegisterPython=0 /D=C:\Anaconda3

And this works !

It seems that the behavior of the Miniconda installer and the Anaconda installer is different regarding the installation directory option.

Wolfgang

**Comment by msarahan** [comment]
@wulmer neither of these commands include the /S flag, and thus are not silent.  Is that just a mistake in reproducing the commands you used?

Also, I am unable to reproduce the behavior you describe, when adding /S to the flags.  I am always able to see the output at the specified directory.  Can you please confirm that you are using the /S flag?

**Comment by msarahan** [comment]
One other detail: are you running these commands from an elevated prompt?  From what I've seen, the installer should (and does, for me) show an error box if you try to install silently for all users from a non-elevated prompt.

**Comment by wulmer** [comment]
Sorry, I removed the `/S` flag to debug the command line settings and forgot to post it here. Of course I tried these commands with the silent flag.

And yes, I am running these commands from an elevated prompt.

@msarahan Could you please post the exact command line that you are using for the `Anaconda3-4.2.0-Windows-x86_64.exe` installer? I tried various syntaxes, w/ and w/o quotes, different order of arguments, etc. 
But whenever it works with the Miniconda installer, it doesn't for the Anaconda installer.

**Comment by msarahan** [comment]
Sure, I just copy/pasted your command, but added /S:

```
start "" /wait Anaconda3-4.2.0-Windows-x86_64.exe /S /InstallationType=AllUsers /AddToPath=1 /RegisterPython=0 /D=C:\Anaconda3
```

I'm using Windows 10, 10.0.14393, in a VMWare fusion virtual machine.  The md5 for the Anaconda installer that I've downloaded from the Continuum website is:

0ca5ef4dcfe84376aad073bbb3f8db00

**Comment by wulmer** [comment]
Thanks for checking, @msarahan . I don't know what happened, but it works now.
Actually, the `/D=` argument is ignored if the `/S` argument is missing. And as stated in the conda documentation, the `/D=` argument must be last and *not* enclosed in quotes!

Closing this issue then.
