### ISSUE TITLE
Navigator Issue

### ISSUE THREAD

**Issue by dA505819** [ContinuumIO/anaconda-issues#11477]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by magicgoose** [comment]
Why is this still opened?

**Comment by dA505819** [comment]
The anaconda still shows the error.

**Comment by magicgoose** [comment]
But there's zero info about the error in the issue text.

**Comment by dA505819** [comment]
I installed the setup of anaconda and the software properly. When I opened the anaconda, after some processing for minutes, it showed up this error.

**Comment by csoja** [comment]
There is insufficient information included in this issue to help you debug the issue.  I will close it.
You may find the tips in the Troubleshooting section of the documentation helpful:
https://docs.anaconda.com/anaconda/navigator/troubleshooting/
