### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by canhongluori** [ContinuumIO/anaconda-issues#11497]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - spyder-app ==2.3.8
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.1', 'os': 'Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 158 Stepping 13, GenuineIntel', 'qt': '4.8.7', 'conda': '4.1.4', 'language': 'zh_CN', 'platform': 'win-64', 'version': '1.2.1', 'pyqt': '4.11.4'}

**Comment by csoja** [comment]
The version of spyder-app you are attempting to install is incompatible with the current environment you are installing it into.  If possible, please create a new environment and install it and the other packages you need there.
