### ISSUE TITLE
ipython breaks because of prompt_toolkit>2.0.10

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/anaconda-issues#11492]
### Workaround 

`conda install prompt_toolkit==2.0.10`

see: https://github.com/ipython/ipython/issues/11962#issuecomment-561183756

### Actual Behavior

`conda create -n py3.8 python=3.8 ipython`

ipython fails to run and raises a stack trace:
```
 ipython
...
  File "/opt/anaconda/envs/py3.8/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 285, in init_prompt_toolkit_cli
    self.pt_app = PromptSession(
TypeError: __init__() got an unexpected keyword argument 'inputhook'
```

### Expected Behavior

ipython should have the correct dependencies to make it work.

### Steps to Reproduce

See actual behavior.

##### Operating System:
osx-64

**Comment by jjhelmus** [comment]
Thanks for bringing this to our attention @bkreider.

Packages for IPython 7.10.1 are now available which support `prompt_toolkit` 3.x.  Additionally, the dependency information for the packages for older versions of IPython have been adjusted to include an upper bound on the allowed prompt_toolkit version.

The `ipython` command now works in environment created using:
`conda create -n test1 python=3.8 ipython` and 
`conda create -n test2 python=3.8 ipython=7.9`.
