### ISSUE TITLE
Package request: scikit-learn 0.22

### ISSUE THREAD

**Issue by ogrisel** [ContinuumIO/anaconda-issues#11495]
Scikit-learn 0.22 was tagged and released a couple of days ago but as far as I know the main anaconda channel does not have it yet.

**Comment by ogrisel** [comment]
Any news? Are there any technical issues preventing to package scikit-learn 0.22 as part of the default channel?

**Comment by msarahan** [comment]
MacOS has issues with openmp, possibly related to https://github.com/scikit-learn/scikit-learn/issues/15443.  Builds for mac py37 and 38 are missing until we figure that out.  The other builds are being uploaded now.

**Comment by ogrisel** [comment]
The documentation has been updated to explain how to build with OpenMP on macOS:

https://scikit-learn.org/dev/developers/advanced_installation.html#compiler-macos

One option with homebrew, another option with the clang compiler from the conda-forge channel.

The scikit-learn-feedstock on conda-forge uses the llvm-openmp package (from that channel):

https://github.com/conda-forge/scikit-learn-feedstock/blob/master/recipe/meta.yaml#L27

I suppose something similar is required in the default channel. Please let us know (in particular @jeremiedbb :) if you need any assistance.

**Comment by ogrisel** [comment]
Or maybe you want to build with intel-openmp (using ICC) in the default channel? If so we can also help fix our setup.py to make it easier if it does not work by default. Unfortunately it's complicated to have ICC on free public CI services so we do not test this build automatically on regular basis.

**Comment by ogrisel** [comment]
Apparently scikit-learn 0.22 is now available in the default channel. Closing.

**Comment by ogrisel** [comment]
BTW, scikit-learn 0.22.1 is being released ATM.
