### ISSUE TITLE
Win: Anaconda Distro Python does not work when installed into a case-sensitive folder

### ISSUE THREAD

**Issue by mingwandroid** [ContinuumIO/anaconda-issues#11491]
Follow this and end up with a little bit of pain:

https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/

Looking in Procmon, we see python.exe searches for C:\opt\conda\lib\os.py whereas the file is in C:\opt\conda\Lib\os.py.

**Comment by LtDan33** [comment]
This is something that would only impact if someone went in and made this change, and also seems like it would be a Python specific issue and not Conda, so wont be something we prioritize
