### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by atterebf** [ContinuumIO/anaconda-issues#1150]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - orange3 ==3.3.6
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;14.5.0;Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Hi @atterebf the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1 now / 1.3.2 later today)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
