### ISSUE TITLE
Extra apps on main screen

### ISSUE THREAD

**Issue by J-Savage** [ContinuumIO/anaconda-issues#11501]
Hi,
I'm getting a bunch of extra app icons on the main Anaconda screen: 
![Untitled picture](https://user-images.githubusercontent.com/49253328/70393274-2148a880-19e0-11ea-90cc-efce107cc5d7.png)

I have tried re-installing several times and after the install it looks normal, then as soon as I update or install anything else it looks like this.
Any idea what's causing this?

**Comment by msarahan** [comment]
These extra apps come from conda forge, Wich you have added to your channel configuration. They appear once you fetch the conda forge repository data.

**Comment by J-Savage** [comment]
That worked, thanks.
