### ISSUE TITLE
Anaconda Navigator will not launch

### ISSUE THREAD

**Issue by FinDonny** [ContinuumIO/anaconda-issues#1151]
I installed Anaconda for windows 64 a month ago and it was working well until today.
I mainly use Spyder to write and run simple codes for python 2.7.12.
Today Spyder wouldn't launch and neither would Anaconda Navigator.

Last week I had to install Python 2.5 to facilitate and installation of another software and I think that may have been the the reason for my problems.
Another post indicated that my path variables might have been changed. I changed PYTHONHOME back from C:\Python27 from C:\Python25

I've uninstalled 2.7.12, 2.5 and Anaconda hoping that a reinstall would solve the issues but it still will not launch.

I've seen in other issues to do with the Navigator that you've asked for the results from "conda list" and "conda info". The result from both commands in Command Prompt is:

> Traceback (most recent call last):
> File "C:\Program Files\Anaconda2\Scripts\conda-script.py", line 3, in <module>
> import conda.cli
> ImportError: No module named conda.cli

I'll be honest that I'm not knowledgeable about Python so I don't know what the above means and I'm not really even sure if this is actually an Anaconda issue at all.

Any help that you can offer would be really appreciated.
Thanks

**Comment by goanpeca** [comment]
@FinDonny I would advice to just redownload the latest anaconda for your system and install it for your user only. https://www.continuum.io/downloads#windows
