### ISSUE TITLE
No Navigator Icon in Ubuntu 16.04

### ISSUE THREAD

**Issue by Dennis-Mayk** [ContinuumIO/anaconda-issues#1152]
No application icons for Anaconda 3 in application tray after installation of anaconda 3 for linux 64bit. 
Also anaconda-navigator needed to be installed seperately and is not automatically installed as described on the website.

When launching anaconda-navigator via terminal this error comes up (also here no icons are displayed in the taskbar):

`anaconda libpng warning: iCCP: known incorrect sRGB profile`

**Comment by goanpeca** [comment]
>anaconda libpng warning: iCCP: known incorrect sRGB profile

This is harmless and has been fixed in the new version to be released first week of January.

>No application icons for Anaconda 3 in application tray after installation of anaconda 3 for linux 64bit.
Also anaconda-navigator needed to be installed seperately and is not automatically installed as described on the website.

We are working on this. An issue already exists regarding this.
