### ISSUE TITLE
Anaconda installation does not complete in Cray

### ISSUE THREAD

**Issue by namus** [ContinuumIO/anaconda-issues#11536]
### Actual Behavior
I am trying to install Anaconda in a Cray system using the installer script Anaconda3-2019.10-Linux-x86_64.sh. But the installer hangs (becomes unresponsive) after making some progress with "Unpacking payload" as shown below. It stays there for a while, and the progress bar eventually disappears. The whole terminal (remote SSH shell) becomes unresponsive and even Ctrl-C does not work at this point!

The extent of progress varies at different trials, but the end result remains the same.

(chs1@login050) : [soft] : 28394 $ ./Anaconda3-2019.10-Linux-x86_64.sh -p /work/chs1/soft/anaconda3 PREFIX=/work/chs1/soft/anaconda3
Unpacking payload ...
Extracting : curl-7.65.3-hbc83047_0.conda: 45%|███████████████▊ | 131/291 [00:50<03:08, 1.18s/it]

**Comment by csoja** [comment]
This version of Anaconda was compiled for x86 processors and Centos6+ compatible - it sounds like your Cray system is not compatible based on your experience.  

https://docs.anaconda.com/anaconda/install/
