### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by alepignata** [ContinuumIO/anaconda-issues#1153]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
- _nb_ext_conf ==0.3.0
- bokeh ==0.12.3
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel', 'platform': 'win-64', 'pyqt': '4.11.4', 'qt': '4.8.7', 'python': '3.5.2', 'version': '1.2.1', 'language': 'pt_BR', 'conda': '4.1.6'}

**Comment by goanpeca** [comment]
Hi @alepignata the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
