### ISSUE TITLE
Windows Defender detects Trojan:Win32/Softcnapp when installing miniconda-latest

### ISSUE THREAD

**Issue by kunxi** [ContinuumIO/anaconda-issues#11539]
I tried to install miniconda from WSL with pyenv, 

```
❯ pyenv install miniconda-latest
Downloading Miniconda2-latest-Linux-x86_64.sh...
-> https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
Installing Miniconda2-latest-Linux-x86_64...

BUILD FAILED (Ubuntu 18.04 using python-build 1.2.15-11-g4e0ba2f4)

Inspect or clean up the working tree at /tmp/python-build.20200102234901.1918
Results logged to /tmp/python-build.20200102234901.1918.log

Last 10 log lines:
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Preparing transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::python-2.7.17-h9bab390_0'.

[Errno 22] Invalid argument: '/home/bookstack/.pyenv/versions/miniconda-latest/pkgs/python-2.7.17-h9bab390_0/bin/python2.7'
()

rm: cannot remove '/home/bookstack/.pyenv/versions/miniconda-latest/pkgs/python-2.7.17-h9bab390_0/bin': Directory not empty
```

And Windows Defender complains Trojan:Win32/Softcnapp detected.

![virtus](https://user-images.githubusercontent.com/152705/71713115-28838c00-2dbd-11ea-8c44-8c6eae770b7b.PNG)

### Actual Behavior

Windows Defender complains Trojan:Win32/Softcnapp detected.

![virtus](https://user-images.githubusercontent.com/152705/71713115-28838c00-2dbd-11ea-8c44-8c6eae770b7b.PNG)

### Expected Behavior

NO virus found.

### Steps to Reproduce

I can also repro without pyenv:

Inside WSL, fetch the package:

```
curl -O https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
```

Install miniconda2:

```
sh ./Miniconda2-latest-Linux-x86_64.sh

... ...
Preparing transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::python-2.7.17-h9bab390_0'.

[Errno 22] Invalid argument: '/home/bookstack/miniconda2/pkgs/python-2.7.17-h9bab390_0/bin/python2.7'
()
```

See the same error reported by Windows Defender.

##### Anaconda or Miniconda version:

miniconda-latest

##### Operating System:

Windows Pro 1909, Build 18363.535

##### `conda info`

N/A

##### `conda list --show-channel-urls`

N/A

**Comment by sungwonida** [comment]
I have the same issue too.

**Comment by csoja** [comment]
This is a false positive - can you report this as such to Windows Defender?

**Comment by kunxi** [comment]
Sure, I can try.

**Comment by kunxi** [comment]
Reported to Microsoft Security Intelligence:

https://www.microsoft.com/en-us/wdsi/submission/b139ccc5-79c0-490f-a963-495e2cce78da
