### ISSUE TITLE
Package request: scikit-learn 0.22.1

### ISSUE THREAD

**Issue by ogrisel** [ContinuumIO/anaconda-issues#11546]
scikit-learn 0.22.1 is out :)

Since this is a bugfix release and 0.22 is already on the anaconda default channel I suspect it should be quite easy to update/build.

**Comment by forrestwaters** [comment]
Thanks for letting us know. scikit-learn 0.22.1 is being uploaded now and should be available in defaults in the next 30 minutes or so
