### ISSUE TITLE
Glueviz Install Corrupts Python 3.5 Environment 

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#1155]
Was asked to pass this on as possible bug rom Google Conda Group and offered a fix.

https://groups.google.com/a/continuum.io/forum/#!topic/conda/KOwczpgw3vM

Windows 7, 64 bit, Anaconda 4.2, Python 2.7

I created a new Python 3.5 environment within my original Python 2.7 install.

All seemed to be OK with the install but in Navigator the icon it showed that Glueiviz 0.8.2 needed to be installed (it is part of the Anaconda package).

Once I clicked to install it, then it reverted to installing older files.
This corrupted the Python 3.5 environment.
For example, Spyder 3 (which had worked fine) somehow reverted to Spyder 2.7, but would not run.
The 2.7 environment was not effected and ran fine (including its version of Glueviz).

I removed the Python 3.5 environment and rebuilt it. It runs fine except that Navigator tells me to install Glueviz still.
I declined to install it again and otherwise the environment still works.

Would Glueviz install correctly by a direct conda command outside of Navigator?
(apparently not)

**Comment by goanpeca** [comment]
>Would Glueviz install correctly by a direct conda command outside of Navigator?
(apparently not)

@joesoap99 did you try the command in the command prompt?

**Comment by joesoap99** [comment]
I tried but in the end I uninstalled and reinstalled to remove the problem and Glueviz is working now.

**Comment by goanpeca** [comment]
Ok, good to hear it resolved with a reinstall.
