### ISSUE TITLE
Numpy 1.18 ignores __array_function__ override on Windows

### ISSUE THREAD

**Issue by pllim** [ContinuumIO/anaconda-issues#11568]
This is only a problem with Numpy 1.18 from the `defaults` channel. I do not see this error if I use Numpy 1.17 from `defaults` channel, `conda install numpy -c conda-forge` (which gives Numpy 1.17), nor `pip install numpy` (gives 1.18).

xref astropy/astropy#9871 and numpy/numpy#15378

### Actual Behavior

```
~\Miniconda3\envs\test-conda-numpy\lib\site-packages\mkl_fft\_numpy_fft.py in ff
t(a, n, axis, norm)
    158     """
    159     x = _float_utils.__downcast_float128_array(a)
--> 160     output = mkl_fft.fft(x, n, axis)
    161     if _unitary(norm):
    162         output *= 1 / sqrt(output.shape[axis])

mkl_fft\_pydfti.pyx in mkl_fft._pydfti.fft()

mkl_fft\_pydfti.pyx in mkl_fft._pydfti._fft1d_impl()

mkl_fft\_pydfti.pyx in mkl_fft._pydfti.__process_arguments()

ValueError: Invalid axis (-1) specified.
```

### Expected Behavior

```python
'Ha!'
```

### Steps to Reproduce

Installation using Miniconda3 on Windows 10:
```
conda create -n test-conda-numpy python=3.7
conda activate test-conda-numpy
conda install numpy
```

This grabs Numpy 1.18.1 (`numpy` and `numpy-base` from the `defaults` channel).

Code to produce the error as provided by @mhvk:
```python
import numpy as np

class A:
   def __array_function__(self, *args, **kwargs):
        return 'Ha!'

np.fft.fft(A())
# 'Ha!'
```

##### Anaconda or Miniconda version:

I do not know how to get this info, as I don't have the original installer anymore.

##### `conda info`

This is not the environment I used above but hopefully still give you some ideas.

```
active environment : py37
    active env location : C:\...\Miniconda3\envs\py37
            shell level : 1
       user config file : C:\...\.condarc
 populated config files : C:\...\.condarc
          conda version : 4.8.1
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\...\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\...\Miniconda3\pkgs
                          C:\...\.conda\pkgs
                          C:\...\AppData\Local\conda\conda\pkgs
       envs directories : C:\...\Miniconda3\envs
                          C:\...\.conda\envs
                          C:\...\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

##### `conda list --show-channel-urls`

I don't have that environment anymore, but you can recreate it with the installation commands provided above if you want.

**Comment by rgommers** [comment]
@pllim why don't you see this with numpy 1.17.x? I just verified and it has the same patching:
```
In [6]: np.__version__                                                         
Out[6]: '1.17.4'

In [7]: np.__file__                                                            
Out[7]: '/home/rgommers/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [8]: np.fft.fft??   
...
    """
    x = _float_utils.__downcast_float128_array(a)
    output = mkl_fft.fft(x, n, axis)
    if _unitary(norm):
        output *= 1 / sqrt(output.shape[axis])
    return output
```

Anaconda maintainers: I thought it was agreed to nuke these invasive patches. Should be a simple deletion I think?

**Comment by pllim** [comment]
@rgommers , I don't know why. Let me recreate the environment and see what is in my `__init__.py`, if that helps. Will report back.

**Comment by jjhelmus** [comment]
> Anaconda maintainers: I thought it was agreed to nuke these invasive patches. Should be a simple deletion I think?

A number of Intel patches were removed in for the 1.18.1 package in defaults, the umath and allocation modification.  I though the mkl_fft and mkl_random patches were optional but looking at them again I see that they are not.  I'll remove them and build new packages.

**Comment by rgommers** [comment]
Awesome, thanks @jjhelmus!

**Comment by pllim** [comment]
Update: I must have gotten `numpy` 1.17 from `conda-forge`. I can't get my Miniconda3 to install Numpy 1.17 from the `defaults` channel. Specifying `"numpy<1.18"` brings me all the way back to 1.16 if I explicitly give `-c defaults`. 🤷‍♀ 

But it looks like a resolution has been found, so there is no need for me to pursue this further. Thank you, all!

**Comment by jjhelmus** [comment]
numpy-base 1.18.1 build 1 packages are now available in `defaults` which do not include any mkl_fft nor mkl_random patches.  This build will be installed automatically in new environments when numpy is installed assuming only the `defaults` channel is configured.

**Comment by rgommers** [comment]
That was lightning fast, thanks @jjhelmus!
