### ISSUE TITLE
Installing pyqtgraph (and PyQt4 requirement) kills Spyder and Anaconda Explorer

### ISSUE THREAD

**Issue by jaxankey** [ContinuumIO/anaconda-issues#1156]
Windows 10, Anaconda3-4.2.0-Windows-x86_64

A fresh install of Anaconda works, and now uses PyQt5 as the default Qt. If I install pyqtgraph (or another library requiring PyQt4), PyQt4 is downloaded, compiled, linked and installed successfully. However, after this process, Spyder AND Anaconda Explorer fail.

Trying to launch Spyder from the command line, I get this:

```
Traceback (most recent call last):
  File "C:\Users\jaxankey\Anaconda3\lib\site-packages\qtpy\__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ImportError: No module named 'PySide'
```
Trying `conda install PySide` produces this:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pyside
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it :-)

**Comment by ccordoba12** [comment]
I talked with the Anaconda team, and our take on this one is: if you want to use PyQt4 applications, please create a new environment and install those apps there.

Don't mess with the root environment because we're now decided to support only Qt5/PyQt5 :-)
