### ISSUE TITLE
Navigator Error - handling versions when urllib2 install

### ISSUE THREAD

**Issue by ericbdc** [ContinuumIO/anaconda-issues#1157]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - ndg-httpsclient ==0.3.3
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.2', 'conda': '4.2.9', 'language': 'fr_FR', 'pyqt': '4.11.4', 'version': '1.2.1', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'qt': '4.8.7', 'platform': 'win-32'}

**Comment by goanpeca** [comment]
Hi @ericbdc the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
