### ISSUE TITLE
Is there any planned release for Miniconda 4.8.x?

### ISSUE THREAD

**Issue by alemorcuq** [ContinuumIO/anaconda-issues#11572]
Hi! I've noticed the latest release from Miniconda listed in the downloads page (https://repo.anaconda.com/miniconda/) is version 4.7.12, dating back to October, while conda 4.8.0 was released in December. Are there any plans to release newer versions?

Thank you.

**Comment by csoja** [comment]
There are plans for a newer release in February.

**Comment by alemorcuq** [comment]
Thank you very much!
