### ISSUE TITLE
macOS now defaults to zsh, Anaconda assumes bash to set path

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [ContinuumIO/anaconda-issues#11575]
The macOS installer optionally sets the PATH to give precedence to its Python using the bash_profile configuration file.

MacOS since Catalina now defaults to zsh not bash and so this doesn't work.

**Comment by makeyourownneuralnetwork** [comment]
anyone?

**Comment by forrestwaters** [comment]
I opened a PR a few days ago that addresses this. That will be included in our next release. For now, we do reference a workaround here: https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html

**Comment by makeyourownneuralnetwork** [comment]
thanks @forrestwaters
