### ISSUE TITLE
When is TensorFlow 2.1.0 coming? 

### ISSUE THREAD

**Issue by OverLordGoldDragon** [ContinuumIO/anaconda-issues#11584]
It'll soon be a month since its release, but conda's still at [2.0.0](https://anaconda.org/anaconda/tensorflow); when is 2.1.0 coming?

**Comment by csoja** [comment]
It is coming - as soon as we've been able to build & test it successfully (it is one of the harder ones to build) - it will be available on repo.anaconda.com.  We are juggling this along with a few other important tasks - so I cannot give you a specific target date.
