### ISSUE TITLE
Unable to install Anaconda3-2019.10-Linux-x86_64 getting -> conda.exe: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted error

### ISSUE THREAD

**Issue by bkrishna2006** [ContinuumIO/anaconda-issues#11587]
### Actual Behavior
Unable to install Anaconda3-2019.10-Linux-x86_64 in my RHEL machine; Getting the erro -> conda.exe: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted.
### Expected Behavior
Should complete installation without errors.
### Steps to Reproduce
1. wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
2. bash ./Anaconda3-2019.10-Linux-x86_64.sh
##### Anaconda or Miniconda version:
Anaconda3-2019.10-Linux-x86_64
##### Operating System:
"Red Hat Enterprise Linux Server" VERSION="7.7 (Maipo)"
##### `conda info`
Not applicable yet
##### `conda list --show-channel-urls`
Not applicable yet

I've followed the resolutinos steps mentioned in https://github.com/ContinuumIO/anaconda-issues/issues/11493, and https://github.com/ContinuumIO/anaconda-issues/issues/11154 by @davidlowryduda, @Pastthesun, but that doesn't fix my issue.

**Comment by bkrishna2006** [comment]
Just an update ...    I tried with older version of Anaconda --> Anaconda3-2019.**07**-Linux-x86_64 and Anaconda3-2019.**03**-Linux-x86_64.    Anaconda3-2019.**07**-Linux-x86_64 did not give the same issue related to libz.so.1, but gave another error.  But I had a smooth installation with Anaconda3-2019.**03**-Linux-x86_64.

**Comment by jatin7gupta** [comment]
I am facing the same issue.

**Comment by bkrishna2006** [comment]
Wondering if there are any takers for this issue; it's been 10 days ! @csoja - I believe you are an SME on this.  Can you please see if you can help ?  Thank you !

**Comment by cercis** [comment]
Hey folks,

On RHEL7.2 using the Anaconda3-2019.10-Linux-x86_64.sh installer I've had success setting TMPDIR rather than TMP (assuming your /tmp is mounted with noexec).  Setting TMP to an alternate location doesn't appear to do the trick.

Kind regards,

Chris

**Comment by davidlowryduda** [comment]
For reference on why the solution of @cercis might work, see https://github.com/ContinuumIO/anaconda-issues/issues/11154#issuecomment-535571313

**Comment by rivera10** [comment]
Had the same issue. Setting TMPDIR  worked for me.

**Comment by vingeelis** [comment]
> Hey folks,
> 
> On RHEL7.2 using the Anaconda3-2019.10-Linux-x86_64.sh installer I've had success setting TMPDIR rather than TMP (assuming your /tmp is mounted with noexec). Setting TMP to an alternate location doesn't appear to do the trick.
> 
> Kind regards,
> 
> Chris

On ubuntu 18, TMPDIR works, `mkdir ~/tmpconda; TMPDIR=~/tmpconda bash Anaconda3-*`

**Comment by bkrishna2006** [comment]
Ok; I didn't get a chance to try out the TMPDIR option;  but since this is reported as having worked for many, marking this issue as closed.  Thanks all for the response !

**Comment by HakamRashid** [comment]
I solved it like this: -- run the command >>> mount |grep tmp

check a tmp partition that does not contain the attribute: noexec and that contains the attribute: rw

in my case:

devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=3775584k,nr_inodes=943896,mode=755)

run in terminal:

export TMP='path/to/tmp'& export TMPDIR='path/to/tmp'& bash Anaconda_install_file.sh
