### ISSUE TITLE
Basemap / proj can't find epsg file

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#11590]
```
$ conda create -n basemap_test
$ conda activate basemap_test
$ conda install  basemap
(basemap_test) ~  python -c "from mpl_toolkits.basemap import Basemap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/andy/miniconda3/envs/basemap_test/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/andy/miniconda3/envs/basemap_test/share/proj/epsg'
```
This seems to be fixed in conda-forge so I assume it's a packaging issue:
https://github.com/conda-forge/basemap-feedstock/issues/45

<details>
<pre>
_libgcc_mutex             0.1                        main  
basemap                   1.2.0            py37h705c2d8_0  
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
geos                      3.6.2                heeff764_2  
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_1    conda-forge
gstreamer                 1.14.5               h36ae1b5_1    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                hea5a465_1  
matplotlib                3.1.2            py37h4fdacc2_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.17.5           py37h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pip                       20.0.2                   py37_1  
proj                      6.3.0                hc80f0dc_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1      py37h8ff28aa_1    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
readline                  7.0                  h7b6447c_5  
setuptools                45.1.0                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.14.0                   py37_0    conda-forge
sqlite                    3.30.1               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tornado                   6.0.3            py37h516909a_0    conda-forge
wheel                     0.34.1                   py37_0  
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
</pre>
</details>

**Comment by T-mang** [comment]
![image](https://user-images.githubusercontent.com/60680089/73806039-fedbcd00-478d-11ea-9a3b-891359392daa.png)
I have the same issue with configuration showed at the pic. above, message:
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-f30bd0438001> in <module>
----> 1 from mpl_toolkits.basemap import Basemap
      2 import matplotlib.pyplot as plt
      3 from pylab import rcParams
      4 get_ipython().run_line_magic('matplotlib', 'inline')
      5 rcParams['figure.figsize'] = (14,10)

~\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py in <module>
    154 # create dictionary that maps epsg codes to Basemap kwargs.
    155 pyproj_datadir = os.environ['PROJ_LIB']
--> 156 epsgf = open(os.path.join(pyproj_datadir,'epsg'))
    157 epsg_dict={}
    158 for line in epsgf:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XXX\\Anaconda3\\Library\\share\\proj\\epsg'

**Comment by forrestwaters** [comment]
basemap seems to be incompatible with `proj4>=6`. You can work around this by running:
```
conda install "proj4<6"
```
I'll work on getting our repodata hotfixed to reflect that incompatibility.

**Comment by forrestwaters** [comment]
basemap is now constrained to proj<6 which should prevent this issue going forward.

**Comment by amueller** [comment]
Thank you!
