### ISSUE TITLE
Launcher Error(cannot open Launcher at all)

### ISSUE THREAD

**Issue by joey1993** [ContinuumIO/anaconda-issues#1159]
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by goanpeca** [comment]
Launcher is deprecated and no longer in maintenance and was replace by [Anaconda Navigator](https://docs.continuum.io/anaconda/navigator).

Please update to the latest version of Anaconda by typing on the command line

`conda update anaconda` or 

Install Anaconda Navigator by typing

`conda update anaconda-navigator`

**Comment by joey1993** [comment]
conda doesn't work any more, it shows like: /opt/anaconda1anaconda2anaconda3/bin/python: bad interpreter: No such file or directory

**Comment by goanpeca** [comment]
I suggest you download the latest version of Anaconda from https://www.continuum.io/downloads

**Comment by joey1993** [comment]
Thanks! The error happened when I tried to update Spyder in Launcher. It seems the python in /opt was automatically removed but not updated. Then sehbang of /Users/me/anaconda/bin/conda directs the system to /opt/ana... which does not exist.
