### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by ilanschnell** [ContinuumIO/anaconda-issues#11619]
The RSS feed https://repo.anaconda.com/pkgs/rss.xml is broken.  My browser tells me:
```
XML Parsing Error: not well-formed
Location: https://repo.anaconda.com/pkgs/rss.xml
Line Number 261, Column 50:
      <title>hotfix basemap - also require proj <6</title>
-------------------------------------------------^
```

**Comment by csoja** [comment]
Thank you for the error report!

**Comment by jjhelmus** [comment]
The RSS feed is once again working.  @ilanschnell Can you confirm and close this issue if the feed works for you?

**Comment by ilanschnell** [comment]
Thanks for the fix!  It's working now, ie. no invalid XML.  However, when I look at the line which was causing trouble, I see that it is now `<title>hotfix basemap - also require proj ,lt;6</title>`.  In XML `<` should be encoded as `&lt;` (just like you would in HTML).

**Comment by jjhelmus** [comment]
I fixed the order of escaping in the script that generates the RSS feed. The encoding of `<` should be correct in the feed now.

**Comment by ilanschnell** [comment]
Yes, it is fixed now.
