### ISSUE TITLE
Miniconda 4.1.12 Release

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#1161]
We have encountered some issues installing and activating Miniconda 4.1.11 on AppVeyor. I suspect they have moved some things around resulting in a longer path length. As a result, activating the root environment resulted in AppVeyor CI crashing. `conda` version `4.1.12` included a much need fix in the form of PR ( https://github.com/conda/conda/pull/3349 ). It would be great if Miniconda could have a 4.1.12 release with version of `conda`.

cc @msarahan @astrofrog

xref: https://github.com/conda-forge/conda-forge.github.io/issues/252

**Comment by csoja** [comment]
@kalefranz @ilanschnell I think we are planning a release of Miniconda with 4.2.10 soon.

**Comment by kalefranz** [comment]
Yes, we're releasing 4.2.10 this week and will make a Miniconda installer for it also.

**Comment by csoja** [comment]
Miniconda with conda v4.2.10 has been released. https://repo.continuum.io/miniconda/
