### ISSUE TITLE
No new installers in 2020

### ISSUE THREAD

**Issue by ApoorvGuptaAi** [ContinuumIO/anaconda-issues#11620]
Though the [release notes](https://conda.io/projects/continuumio-conda/en/latest/release-notes.html) show releases in 2020 (4.8.*), there are no corresponding installers in the [repo](https://repo.anaconda.com/miniconda/)

**Comment by csoja** [comment]
The release notes are for conda itself - not Miniconda.  There is not currently a Miniconda release for every release of conda.  There are Miniconda release candidate installers if you want to take them for a spin.  These are not final - and are currently in QA.    https://repo.anaconda.com/pkgs/misc/previews/miniconda/4.8.2/
