### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by freed24** [ContinuumIO/anaconda-issues#1163]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.5*
  - wxpython ==3.0
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'language': 'zh_CN', 'pyqt': '4.11.4', 'conda': '4.2.9', 'version': '1.2.1', 'python': '3.5.2', 'platform': 'win-64', 'qt': '4.8.7'}

**Comment by goanpeca** [comment]
Hi @freed24  the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1 now / 1.3.2 later today)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
