### ISSUE TITLE
conda cannot install wxPython from its sourcefile

### ISSUE THREAD

**Issue by anikfal** [ContinuumIO/anaconda-issues#11653]
**Download page for wxPython version 3.0.0.0:**
https://sourceforge.net/projects/wxpython/files/wxPython/3.0.0.0/

**Code to install the downloaded wxPython package in an activated conda environment:**
```bash
conda install wxPython-src-3.0.0.0.tar.bz2
```

**Error massage:**

> Downloading and Extracting Packages
                                                                                                                                               |   0% ERROR: Encountered corrupt package tarball at /home/ah/.conda/pkgs/wxPython-src-3.0.0.0.tar.bz2. Conda has left it in place.  Please report this to the maintainers of your package.  For the defaults channel, please report to https://github.com/continuumio/anaconda-issues

OS: Linux (Fedora-31)

**Comment by jjhelmus** [comment]
conda can only install conda packages not arbitrary source packages.

**Comment by anikfal** [comment]
@jjhelmus Thank you for the clarification.
