### ISSUE TITLE
Fresh matplotlib/gdal compatability issues

### ISSUE THREAD

**Issue by Chris35Wills** [ContinuumIO/anaconda-issues#1166]
This relates to issue [#1068](https://github.com/ContinuumIO/anaconda-issues/issues/1068) but is with more specific regard to gdal - in short, I can't get gdal and matplotlib to work together. I can get matplotlib working with the new conda install using:

	conda create --name mplgeo_test python=3.5 matplotlib ipython
	source activate mplgeo_test
	conda update -c qttesting libxcb 
	python -c "from PyQt5 import QtCore, QtGui, QtWidgets" 	 # this works

Creating an environment JUST with gdal, gdal works ok....

	conda create --name gdal_test ipython python=3.5
	source activate gdal_test
	conda install -c conda-forge gdal

Output:

	Fetching package metadata .........
	Solving package specifications: ..........

	Package plan for installation in environment /home/cw14910/anaconda3/envs/gdal_test:

	The following NEW packages will be INSTALLED:

	    curl:          7.49.1-1          conda-forge
	    expat:         2.1.0-2           conda-forge
	    freexl:        1.0.2-1           conda-forge
	    gdal:          2.1.1-np111py35_5 conda-forge
	    geos:          3.4.2-2           conda-forge
	    giflib:        5.1.4-0           conda-forge
	    hdf4:          4.2.12-0          conda-forge
	    hdf5:          1.8.17-6          conda-forge
	    icu:           56.1-4            conda-forge
	    jpeg:          9b-0              conda-forge
	    json-c:        0.12-0            conda-forge
	    kealib:        1.4.6-3           conda-forge
	    libdap4:       3.18.0-2          conda-forge
	    libgfortran:   3.0.0-1
	    libiconv:      1.14-3            conda-forge
	    libnetcdf:     4.4.1-0           conda-forge
	    libpng:        1.6.24-0          conda-forge
	    libpq:         9.5.4-2           conda-forge
	    libspatialite: 4.3.0a-10         conda-forge
	    libtiff:       4.0.6-6           conda-forge
	    libuuid:       1.0.3-1           conda-forge
	    libxml2:       2.9.4-2           conda-forge
	    mkl:           11.3.3-0
	    numpy:         1.11.2-py35_0
	    openjpeg:      2.1.2-1           conda-forge
	    proj.4:        4.9.3-0           conda-forge
	    xerces-c:      3.1.4-2           conda-forge
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Then to test it:

	python -c "from osgeo import gdal" # this works
	python -c "import gdal" 		   # this works

However, on installing gdal from the conda-forge channel:

	conda install -c conda-forge gdal 

Output:

	The following packages will be downloaded:

	    package                    |            build
	    ---------------------------|-----------------
	    hdf4-4.2.12                |                0         968 KB  conda-forge

	The following NEW packages will be INSTALLED:

	    curl:          7.49.1-1          conda-forge
	    freexl:        1.0.2-1           conda-forge
	    gdal:          2.1.1-np111py35_5 conda-forge
	    geos:          3.4.2-2           conda-forge
	    giflib:        5.1.4-0           conda-forge
	    hdf4:          4.2.12-0          conda-forge
	    hdf5:          1.8.17-6          conda-forge
	    json-c:        0.12-0            conda-forge
	    kealib:        1.4.6-3           conda-forge
	    libdap4:       3.18.0-2          conda-forge
	    libgfortran:   3.0.0-1
	    libiconv:      1.14-3            conda-forge
	    libnetcdf:     4.4.1-0           conda-forge
	    libpq:         9.5.4-2           conda-forge
	    libspatialite: 4.3.0a-10         conda-forge
	    libtiff:       4.0.6-6           conda-forge
	    libuuid:       1.0.3-1           conda-forge
	    openjpeg:      2.1.2-1           conda-forge
	    proj.4:        4.9.3-0           conda-forge
	    xerces-c:      3.1.4-0

	The following packages will be UPDATED:

	    jpeg:          8d-2                          --> 9b-0              conda-forge
	    libpng:        1.6.22-0                      --> 1.6.24-0          conda-forge

	The following packages will be SUPERCEDED by a higher-priority channel:

	    pyqt:          5.6.0-py35_0                  --> 4.11.4-py35_0     conda-forge

	The following packages will be DOWNGRADED due to dependency conflicts:

	    matplotlib:    1.5.3-np111py35_0             --> 1.5.1-np111py35_0
	    qt:            5.6.0-1                       --> 4.8.7-3

I get a matplotlib downgrade, then matplotlib errors:

	python -c "from PyQt5 import QtCore, QtGui, QtWidgets"

Output:

	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	ImportError: cannot import name 'QtCore'

and osgeo/gdal errors:

	python -c "from osgeo import gdal"

Output:

	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
	    _gdal = swig_import_helper()
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
	    _mod = imp.load_module('_gdal', fp, pathname, description)
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/imp.py", line 242, in load_module
	    return load_dynamic(name, filename, file)
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/imp.py", line 342, in load_dynamic
	    return _load(spec)
	ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

Tested with:

	python -c "import gdal"

Output:

	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/site-packages/gdal.py", line 2, in <module>
	    from osgeo.gdal import deprecation_warn
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
	    _gdal = swig_import_helper()
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
	    _mod = imp.load_module('_gdal', fp, pathname, description)
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/imp.py", line 242, in load_module
	    return load_dynamic(name, filename, file)
	  File "/home/cw14910/anaconda3/envs/mplgeo_test/lib/python3.5/imp.py", line 342, in load_dynamic
	    return _load(spec)
	ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

There appears to be a clash between gdal and matplotlib - does anyone have a solution?

**Comment by ccordoba12** [comment]
@ocefpaf, would you like to comment here?

**Comment by Chris35Wills** [comment]
Getting everything from the conda_forge channel seems to sort out dependencies for python 3.4:

```
conda create -n py34_mpl_gdal
source activate py34_mpl_gdal
conda install -c conda-forge python=3.4 gdal matplotlib ipython
python -c "import matplotlib.pyplot"
```

This then works out without errors or warnings:

```
python -c "import gdal"
python -c "import matplotlib.pyplot"
ipython -c "import matplotlib.pyplot"
ipython -c "import gdal"
```

**Comment by ocefpaf** [comment]
There is no way we can make `gdal` from `conda-forge` work with `defaults` because of the `qt`, `jpeg` and `icu` versions being different. Sorry. You can either use all `conda-forge`, as you did above, or all from `defaults`. At the end of the day your choice of which one to use will be between an updated `gdal` (`conda-forge`) or an updated `Qt` (`defaults`).

**Comment by Chris35Wills** [comment]
@ocefpaf, thanks. I'll just stick with `conda-forge` then.

**Comment by ocefpaf** [comment]
Bare in mind that we are working to ameliorate those issue by getting `Qt` in `conda-forge` and, in the future, `defaults` may be using stable versions of `conda-forge` recipes. So hopefully things will be better soon.
