### ISSUE TITLE
Linux Mint 19.3 and Anaconda 2020-20 vscode.py DISTRO_NAME hangs anaconda navigator

### ISSUE THREAD

**Issue by PhilipYip1988** [ContinuumIO/anaconda-issues#11677]
<img width="645" alt="mint (1)" src="https://user-images.githubusercontent.com/56493395/77068130-01148680-69de-11ea-873b-6dfcc44ab477.png">
<img width="645" alt="mint (2)" src="https://user-images.githubusercontent.com/56493395/77068134-0245b380-69de-11ea-9898-fac6a6a9ed35.png">
<img width="646" alt="mint (3)" src="https://user-images.githubusercontent.com/56493395/77068136-02de4a00-69de-11ea-949f-afaeda42f0e7.png">
<img width="647" alt="mint (4)" src="https://user-images.githubusercontent.com/56493395/77068137-0376e080-69de-11ea-94ae-8da47f854224.png">
<img width="960" alt="mint (6)" src="https://user-images.githubusercontent.com/56493395/77068139-0376e080-69de-11ea-8cc6-0923d6561e44.png">
<img width="960" alt="mint (10)" src="https://user-images.githubusercontent.com/56493395/77068140-040f7700-69de-11ea-985b-3903c9e1b0d6.png">
<img width="960" alt="mint (13)" src="https://user-images.githubusercontent.com/56493395/77068141-040f7700-69de-11ea-996f-81a2dc765bde.png">
<img width="960" alt="mint (14)" src="https://user-images.githubusercontent.com/56493395/77068144-04a80d80-69de-11ea-9626-17eb33fd8f43.png">
<img width="960" alt="mint (16)" src="https://user-images.githubusercontent.com/56493395/77068145-0540a400-69de-11ea-9a7c-9a32cfb3635a.png">
![mint (17)](https://user-images.githubusercontent.com/56493395/77068147-05d93a80-69de-11ea-9d53-be2e96f0f079.png)
<img width="960" alt="mint (19)" src="https://user-images.githubusercontent.com/56493395/77068149-0671d100-69de-11ea-8bf7-e61a1d5d6b77.png">
<img width="960" alt="mint (20)" src="https://user-images.githubusercontent.com/56493395/77068151-070a6780-69de-11ea-96bd-c7690297478a.png">
![mint (22)](https://user-images.githubusercontent.com/56493395/77068153-07a2fe00-69de-11ea-9518-b034a43c4ba9.png)
<img width="960" alt="mint (23)" src="https://user-images.githubusercontent.com/56493395/77068155-083b9480-69de-11ea-9d22-ce4a091a9a20.png">
<img width="960" alt="mint (24)" src="https://user-images.githubusercontent.com/56493395/77068157-096cc180-69de-11ea-8953-1b62c7b5905e.png">
<img width="960" alt="mint (26)" src="https://user-images.githubusercontent.com/56493395/77068158-0a9dee80-69de-11ea-9cea-a620b8b88719.png">
<img width="960" alt="mint (27)" src="https://user-images.githubusercontent.com/56493395/77068161-0a9dee80-69de-11ea-8b66-b8d9ba99ce8c.png">
<img width="960" alt="mint (28)" src="https://user-images.githubusercontent.com/56493395/77068164-0b368500-69de-11ea-8bad-a26766bf91fd.png">
<img width="960" alt="mint (31)" src="https://user-images.githubusercontent.com/56493395/77068166-0c67b200-69de-11ea-96d2-21ceed9f2ac9.png">
<img width="960" alt="mint (34)" src="https://user-images.githubusercontent.com/56493395/77068167-0d004880-69de-11ea-9807-0201a74dc15a.png">
<img width="960" alt="mint (36)" src="https://user-images.githubusercontent.com/56493395/77068170-0d98df00-69de-11ea-91c5-1df1ac7639e7.png">
<img width="960" alt="mint (39)" src="https://user-images.githubusercontent.com/56493395/77068171-0d98df00-69de-11ea-9f28-8927d8bf27f5.png">

### Actual Behavior

anaconda-navigator hangs on Linux Mint 19.3 due to undefined DISTRO_NAME in vscode.py on Linux Mint. Adding this variable name to the python file and assigning it to None fixes the issue.

### Expected Behavior

anaconda-navigator should launch.

### Steps to Reproduce

Standard installation of Anaconda on Linux Mint 19.3

##### Anaconda or Miniconda version:

2020-02

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by forrestwaters** [comment]
Please see https://github.com/ContinuumIO/anaconda-issues/issues/11635#issuecomment-594494001
