### ISSUE TITLE
Anaconda update ruined custom GPU TensorFlow install

### ISSUE THREAD

**Issue by dartdog** [ContinuumIO/anaconda-issues#1167]
Any advice appreciated!!
This is sort of lengthy and in the weeds at this point so I will point to this issue raised in the TensorFlow git Hub issues https://github.com/tensorflow/tensorflow/issues/5017

TL:DR
I have a brand new machine (Linux 16.04) specifically bought with the new Nvidia 1060 gpu which requires the Nvidia 8 drivers (cudnn 5.1.5) Hence I don't want the base Anaconda TensorFlow which has the older CUDNN And is built against a much older Tensorflow (I was building against master.)

1st thing I did was install Anaconda (so it now is the default Python (3.5)) While I did create env's for 3.5 and 2.7 and kernels for Jupyter I consciously installed TensorFlow from Source in the BASE, (root) environment. All was running fine in both the command line and in Jupyter notebooks

Then I did an Anaconda update (with all the new packages) Tensorflow is now broken, I attempted a reinstall from source in the hopes that it would fix the broken paths..  Things seem to have gotten worse..
The end of my current traceback:

    tom@tomServal:~$ python -c "import tensorflow; print(tensorflow.__version__)"

    ImportError: /home/tom/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/tom/anaconda3/lib/python3.5/site-   packages/tensorflow/python/_pywrap_tensorflow.so)

    Error importing tensorflow.  Unless you are using bazel,
    you should not try to import tensorflow from its source directory;
    please exit the tensorflow source tree, and relaunch your python interpreter
from there.

So I'm thinking uninstall tensorflow from Anaconda using conda
uninstall tensorflow from source using PIP
Then reinstall from source?

**Comment by dartdog** [comment]
Note this response at the Tensor Flow GH
This is a bit beyond my Linux Knowledge:


    The ldd output here suggests that you're linking with /usr/lib/x86_64-linux-gnu/libstdc++.so.6, but 
    the error output you alluded to above (ImportError: /home/tom/anaconda3/bin/../lib/libstdc++.so.6:) 
    was linking with /home/tom/anaconda3/lib/libstdc++.so.6.

So I'm not quite sure what exactly is happening but it does seem to be something specific to the environment on your setup. Perhaps you can create an isolated environment with the docker installation? Doesn't quite solve your precise setup, but something to look into?

**Comment by dartdog** [comment]
This from the TensorFlow GH issues (Referenced above) site fixed the issue: Recording it here for people who follow.
try to do this:

    # cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/tom/anaconda3/lib/
and it should work, at least it works for me.

**Comment by saurabh-3896** [comment]
use "conda install libgcc"

**Comment by msarahan** [comment]
Here's the deal: you need a libstdc++ that is at least as new as the one that was used when you compiled TensorFlow (and any of its dependencies, e.g. CUDA).  ``conda install libgcc`` works because it includes a libstdc++ from gcc 5.2.0, which is fairly new.

If anyone else runs into issues here, you can also try to just remove libstdc++ from your conda installation - just manually remove the .so files from the lib folder.  That will then force your system to find the system libraries - which will work if and only if your system libraries are new enough.

**Comment by BoteRock** [comment]
hey, just bumped into this issue when trying to figure out something somewhat unrelated, but I hope that this helps people with the same issue
I installed PyAudio with conda pip, but had almost the same error, the fix was the same stated above: `conda install libgcc` fixed the issue.
