### ISSUE TITLE
Compile numpy with NPY_RELAXED_STRIDES_CHECKING

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#117]
See http://docs.scipy.org/doc/numpy/release.html#npy-relaxed-strides-checking

**Comment by gmarkall** [comment]
Pinging @msarahan as suggested by @asmeurer - it looks like Numpy is built with `NPY_RELAXED_STRIDES_CHECKING` in Anaconda, so this could be closed?

**Comment by remkade** [comment]
This appears to be complete.
