### ISSUE TITLE
What should i do to overcome this error?

### ISSUE THREAD

**Issue by Ankit-Patil-Simply** [ContinuumIO/anaconda-issues#11705]
What should i do to overcome this error?

_Originally posted by @Ankit-Patil-Simply in https://github.com/ContinuumIO/anaconda-issues/issues/11656#issuecomment-606880289_

**Comment by csoja** [comment]
Please see https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
