### ISSUE TITLE
IDE Spyder (any version) does not start in python 3.8 environments (anaconda, windows 10)

### ISSUE THREAD

**Issue by manfred2020** [ContinuumIO/anaconda-issues#11701]
spyder hangs with white screen at startup.

see: https://github.com/spyder-ide/spyder/issues/11880#issuecomment-606349084

at spyder they say, they can't do anything. they thought, that bug was already fixed by anaconda. but it is not fixed as we experience it right now.

**Comment by mingwandroid** [comment]
Please fill in the template with all of the details requested. I looked at the linked-to thread and it is very sparse in terms of details I could use to investigate this. I do not even know which operating system you are running into these problems on. Fill in the template please!

**Comment by mingwandroid** [comment]
Closed. Spyder cannot run on *any* Python 3.8 interpreter at present without applying the hack detailed at https://stackoverflow.com/a/58682830

I left a comment on the spyder bug tracker to this effect.
