### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by caixiao1998** [ContinuumIO/anaconda-issues#11719]
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64'

```
## System information
```
version: 1.6.2
platform: win-64
python: 3.5.3
pyqt: 5.9.2
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
qt: 5.6.2
language: zh_CN
conda: 4.8.2
```

**Comment by csoja** [comment]
This is an error with the mirror your are using: https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
This is not something we have any control over.  However, I will note that the free channel is not one of the default channels any longer.  https://docs.anaconda.com/anaconda/user-guide/tasks/using-repositories/#using-default-repositories  Closing.
