### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ceforest** [ContinuumIO/anaconda-issues#1171]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - pynio ==1.4.3
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'version': '1.2.1', 'python': '3.5.2', 'platform': 'osx-64', 'pyqt': '4.11.4', 'language': 'en', 'qt': '4.8.7', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64;x86_64;i386', 'conda': '4.1.6'}

**Comment by goanpeca** [comment]
Hi @ceforest the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.1 now / 1.3.2 later today)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
