### ISSUE TITLE
Showing Navigation error

### ISSUE THREAD

**Issue by nehavbishnoi** [ContinuumIO/anaconda-issues#11738]
An unexpected error occurred on Navigator start-up

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
There is insufficient information in this issue to debug the error.  We have a policy of closing issues when none of the template information is provided.
I suspect you are using a very old version of conda and Navigator and updating to the latest may address your issue.  I would also recommend checking out the Navigator troubleshooting section: https://docs.anaconda.com/anaconda/navigator/troubleshooting/
