### ISSUE TITLE
Unable to download installers via curl -O

### ISSUE THREAD

**Issue by habemus-papadum** [ContinuumIO/anaconda-issues#11731]
### Actual Behavior

If I run
```
curl -v -O https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
```

on my Catalina mac, Ubuntu on github workflow, or Mac on github workflow, I get a file with zero bytes.  

If I paste the url into chrome, the installer downloads properly. 

### Expected Behavior
Download the actual script rather than get a zero byte file

This seems to have suddenly stopped working.  

##### Operating System:
on my Catalina mac, default Ubuntu on github workflow, default Mac on github workflow,

**Comment by jjhelmus** [comment]
Use https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

repo.continuum.io has been depreciated. That URL now returns a 301 Moved Permanently status with a redirect to the correct location.  

Alternatively, you can add the `-L` option to the `curl` command to have it follow redirects.

**Comment by habemus-papadum** [comment]
Thanks! nehal
