### ISSUE TITLE
bytes' object has no attribute 'get'

### ISSUE THREAD

**Issue by kimrop19** [ContinuumIO/anaconda-issues#11734]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\kim\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

**Comment by csoja** [comment]
It looks like you are using a very old version of conda and Anaconda-Navigator.
Can you open the Anaconda Prompt and update conda and Anaconda-Navigator? 
_conda update conda
conda update anaconda-navigator
conda update navigator-updater_

Are you still seeing the error?

**Comment by kimrop19** [comment]
`

> It looks like you are using a very old version of conda and Anaconda-Navigator.
> Can you open the Anaconda Prompt and update conda and Anaconda-Navigator?
> _conda update conda conda update anaconda-navigator conda update navigator-updater_
> 
> Are you still seeing the error?

I'm am using Anaconda3-2020.02-Windows-x86_64 which I downloaded today I believe this is the most recent

**Comment by adigeak** [comment]
i am having same error. On opening the anaconda prompt it is showing 
`ConfigurationLoadError: Unable to load configuration file.
  path: C:\Users\user_name\.condarc
  reason: invalid yaml at position 0`

**Comment by kimrop19** [comment]
I solved mine, I think anaconda has an issue during the installation process, as soon as I finished installing anaconda it created a file in my user called .condarc I suppose this is supposed to be a folder instead of a file. a

> i am having same error. On opening the anaconda prompt it is showing
> `ConfigurationLoadError: Unable to load configuration file. path: C:\Users\user_name\.condarc reason: invalid yaml at position 0`

I solved mine, I think anaconda has an issue during the installation process, as soon as I finished installing anaconda it created a file in my user called .condarc I suppose this is supposed to be a folder instead of a file, so I deleted the file reinstalled anaconda and it worked fine

**Comment by mingwandroid** [comment]
.condarc is supposed to be a file not a folder

**Comment by kimrop19** [comment]
then I think it has an issue, however, I deleted mine and reinstalled anaconda nd it worked fine coz I think the file has an error

**Comment by mingwandroid** [comment]
Did you edit the file by hand by any chance?

**Comment by kimrop19** [comment]
nop.... just deleted the file and reinstalled anaconda and worked, maybe if the team can tell us what the file should contain for it to work fine

**Comment by kimrop19** [comment]
I had not done any installation using my conda so I had nothing to lose reinstalling it

**Comment by mingwandroid** [comment]
Weird. If it happens again, I'd like to see the contents of that file if you'd be so kind!

**Comment by Odatas** [comment]
Same issue here. I actually have the file. Opening it with Notepade reveleal the following:

`ssl_verify: true
channels:
  - defaults
`

**Comment by ashok14867** [comment]
I also had the same issue, I just deleted the .condarc file in C:\Users\Username and it started working again. No need to reinstall Anaconda.

**Comment by StonecutterX** [comment]
Same as Odatas. Once I change the existed .condarc file by adding some channel config, the navigator can't be loaded.

**Comment by tony31913** [comment]
> I also had the same issue, I just deleted the .condarc file in C:\Users\Username and it started working again. No need to reinstall Anaconda.

Yes, it works. Thanks.

**Comment by shas2704** [comment]
> I also had the same issue, I just deleted the .condarc file in C:\Users\Username and it started working again. No need to reinstall Anaconda.

yes this worked. Thanks.

**Comment by octoriefeisal** [comment]
thx its work

**Comment by chisrikanth** [comment]
> I also had the same issue, I just deleted the .condarc file in C:\Users\Username and it started working again. No need to reinstall Anaconda.

Thanks. This works

**Comment by yBlueP** [comment]
> o

Thanks.

**Comment by yBlueP** [comment]
> I also had the same issue, I just deleted the .condarc file in C:\Users\Username and it started working again. No need to reinstall Anaconda.

Thx. It works

**Comment by dipendra33** [comment]
I got the same error, deleted .condarc file, reinstalled anaconda, and tried. But it did not work. The problem persisted. Did anyone face this problem?

**Comment by lizhenhai22** [comment]
> 我遇到了同样的错误，删除了 .condarc 文件，重新安装了 anaconda，然后尝试了。但这没有用。问题仍然存在。有人遇到这个问题吗？

me too
![capture_20231022135708510](https://github.com/ContinuumIO/anaconda-issues/assets/146700515/150e0d76-ff2a-429b-98e3-6cfc73b8f176)

**Comment by jyothsnayeluru1990** [comment]
Hi i have the below error
![image](https://github.com/ContinuumIO/anaconda-issues/assets/148783554/7f030a48-4bc7-4950-91cf-bbc6607902a6)

**Comment by nicktaylorstl** [comment]
I'm having the same issue and deleting .condarc doesn't help

**Comment by nicktaylorstl** [comment]
Ok I finally got it to work by using the anaconda prompt and typing
conda --no-plugins update conda

**Comment by dipendra33** [comment]
> I got the same error, deleted .condarc file, reinstalled anaconda, and tried. But it did not work. The problem persisted. Did anyone face this problem?

I solved using Anaconda prompt: 
conda --no-plugins update conda
It worked!

**Comment by jyothsnayeluru1990** [comment]
Hi all
My issue got resolved by following the either of the steps given in the
below YouTube link.

https://youtu.be/ZI6tDpWvO1o?si=m5ZdNOJCAtuCFnhy

Regards,
Jyothsna yeluru

**Comment by Ill-win** [comment]
> > I got the same error, deleted .condarc file, reinstalled anaconda, and tried. But it did not work. The problem persisted. Did anyone face this problem?
> 
> I solved using Anaconda prompt: conda --no-plugins update conda It worked!

My issue has also been solved, thank you!

**Comment by lizhenhai22** [comment]
> > 我遇到了同样的错误，删除了 .condarc 文件，重新安装了 anaconda，然后尝试了。但这没有用。问题仍然存在。有人遇到这个问题吗？
> 
> 我使用 Anaconda 提示解决了： conda --no-plugins update conda 它有效！

thanks,it worked!

**Comment by Agus-web3** [comment]
> Ok I finally got it to work by using the anaconda prompt and typing conda --no-plugins update conda

Thanks it work with that

**Comment by BeshoAsham** [comment]
Thanks it work with that

**Comment by BeshoAsham** [comment]
> Ok I finally got it to work by using the anaconda prompt and typing conda --no-plugins update conda

Thanks it work with that

**Comment by hzp2333** [comment]
![ba83b9794b3e150ee3737c4dfd5d442](https://github.com/ContinuumIO/anaconda-issues/assets/79459902/4ee15606-1831-4434-9932-63ef911251e8)
![C52427EAE639DBDEEDFCDEE93C783179](https://github.com/ContinuumIO/anaconda-issues/assets/79459902/f91aaa20-9f15-43fc-bed9-f760f26288cc)
![F68CE5BB64938951AAE243163927F4C8](https://github.com/ContinuumIO/anaconda-issues/assets/79459902/c1658713-94e0-41c3-90f0-bfb6d7ab72ad)


this is my problem——**anaconda bytes object has no attribute get**.I found the answer in "Anaconda Powershell Prompt".There is a conflict between the paths of windows user variables and system variables. Just agree on the contents of the two. I made the mistake because Java's path is not recognized uniformly.

**Comment by yonasbb** [comment]
> > I got the same error, deleted .condarc file, reinstalled anaconda, and tried. But it did not work. The problem persisted. Did anyone face this problem?
> 
> I solved using Anaconda prompt: conda --no-plugins update conda It worked!

Thanks a lot, the above code is solved my problem too.

**Comment by JIZZX6** [comment]
> Ok I finally got it to work by using the anaconda prompt and typing conda --no-plugins update conda

Man you are the god

**Comment by lynnlu36x** [comment]
> Ok I finally got it to work by using the anaconda prompt and typing conda --no-plugins update conda

my hero, i got stuck for 1.5 months after previous update TT

**Comment by nestat111** [comment]
> Took a day installing and reinstalling: _**conda --no-plugins update conda**_ worked for me.
> 
> How is it possible that a fresh install results in such a stupid failure?

Thank you ! now solved following your advice by openning Anaconda Prompt and then typing : **_conda --no-plugins update conda_** after a downgrade that takes few minutes now it is working.

**Comment by jain-anoop** [comment]
I resolved by reviewing Path environment variable on windows and removed the duplicate path entry

**Comment by MariWantToDie** [comment]
![Screenshot (7)](https://github.com/user-attachments/assets/e3c502af-d73f-4691-92b8-83ad4b783311)
I'm having this problem for a while and I tried everything above still no solution , it just keeps opening those gpython.exe everytime I try doing anything related to anaconda

**Comment by dipendra33** [comment]
First uninstall everything. Then, reinstall and immediately after reinstalling, do: 
conda --no-plugins update conda

**Comment by MariWantToDie** [comment]
still  the same issue
