### ISSUE TITLE
ANACONDA navigator cannot launch-from win32com.shell import shellcon, shell

### ISSUE THREAD

**Issue by BiBiBiCat** [ContinuumIO/anaconda-issues#11752]
I have downloaded the ANACONDA(Anaconda3-2020.02-Windows-x86) and installed. However, i found that i cannot lauch the ANACONDA navigator so i tried using the command line and got its feedback.

***(base) C:\WINDOWS\system32>Anaconda -navigator
Traceback (most recent call last):
  File "C:\Users\aaron.wu\Anaconda3\Scripts\anaconda-script.py", line 6, in <module>
    from binstar_client.scripts.cli import main

File "C:\Users\aaron.wu\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 17, in <module>
    from .utils import compute_hash, jencode, pv

File "C:\Users\aaron.wu\Anaconda3\lib\site-packages\binstar_client\utils\__init__.py", line 17, in <module>
    from .config import (get_server_api, dirs, load_token, store_token,

File "C:\Users\aaron.wu\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 54, in <module>
    USER_LOGDIR = dirs.user_log_dir

File "C:\Users\aaron.wu\Anaconda3\lib\site-packages\binstar_client\utils\appdirs.py", line 258, in user_log_dir
    version=self.version)

File "C:\Users\aaron.wu\Anaconda3\lib\site-packages\binstar_client\utils\appdirs.py", line 205, in user_log_dir
    path = user_data_dir(appname, appauthor, version); version = False

File "C:\Users\aaron.wu\Anaconda3\lib\site-packages\binstar_client\utils\appdirs.py", line 67, in user_data_dir
    path = os.path.join(_get_win_folder(const), appauthor, appname)

File "C:\Users\aaron.wu\Anaconda3\lib\site-packages\binstar_client\utils\appdirs.py", line 284, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed: The specified module could not be found.***

It seems that the reason of failure is the module win32com.shell and i tried to install win32com.shell using conda install win32com.shell or reinstall the ANACONDA. In the end, it did not work out. I am new to ANACONDA and really need some help for sorting this out! Thanks!

**Comment by csoja** [comment]
There is no win32com.shell conda package, so attempting to conda install it will not work.  

It seems like somehow things are confused as to whether you are on a 32-bit Windows machine or 64-bit Windows machine.  
Based on your issue, you installed with the Windows 32 Anaconda installer instead of 64-bit.  It might be that the 64-bit installer will have fewer issues on your 64-bit machine.
https://repo.anaconda.com/archive/Anaconda3-2020.02-Windows-x86_64.exe

This issue/solution might provide another clue: https://github.com/conda/conda/issues/9356#issuecomment-577271046

**Comment by BiBiBiCat** [comment]
@csoja  Thanks! that's really helpful!
It finally solved!
1. i uninstalled the 32-bit Anaconda
2. Meanwhile, i noticed that in the C:\Users\aaron.wu\AppData\Local\Programs
    There is folder named python which is not supposed to be there and it includeds pip folder.
    I manually delete "python" folder and reinstalled 64-bit and it worked out!

**Comment by chenxjojo** [comment]
@BiBiBiCat Thanks a lot for your solution 2! I searched all kinds of solutions but none of them worked. 
I found a folder named "Python" in "AppData\Roaming". This was created a year ago. I deleted it and Anaconda Navigator launched successfully!

**Comment by phdsmhong** [comment]
@chenxjojo You saved my day. I tried everything recommended online (except for uninstallation), but nothing worked. I then I found a folder named "Python" in "AppData\Roaming" and delete it. When I restart my PC, Anaconda Navigator is back!

**Comment by yumengmeng0** [comment]
>Thank you.
