### ISSUE TITLE
Navigation error

### ISSUE THREAD

**Issue by tanishqborkar** [ContinuumIO/anaconda-issues#11758]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by bhawesh1997** [comment]
my Anaconda Navigator is not opening and it is showing error

**Comment by csoja** [comment]
There are not enough details in this issue to provide any real help.  You may find the answer to your troubles in the troubleshooting section of the Anaconda Navigator documentation: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting
