### ISSUE TITLE
Spyder only launches if run as Admin

### ISSUE THREAD

**Issue by saurabh87prabhu** [ContinuumIO/anaconda-issues#11755]
## Problem Description
Just installed Anaconda3-2020.02 using the 64-bit installer on Windows 7 pc. When I try to open Spyder using the "Launch" button in the Navigator, nothing happens. No prompts, no errors, no warnings. When I try running from the conda prompt using the command "spyder" and "spyder --show-console", nothing happens. No error, no messages, no traceback.

When I run as Administrator, everything works fine. It's hard to get admin credentials regularly at my company. 
Also, it seems to work fine for some of my colleagues, without admin credentials . Is this a known issue? Thanks in advance.
![spyder_launch_issue](https://user-images.githubusercontent.com/26367729/80275263-c4832b80-86fd-11ea-8c36-7fe534b8ff3d.PNG)

### What steps reproduce the problem?

1. Installed Anaconda3-2020.02 (using the 'Just me' option). No admin credentials given during installation
2. Hit 'Launch' button from Spyder
3. Updated Spyder to latest version
4. 'spyder' command on console
Restarted PC, Anaconda several times.

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7 (64-bit)

**Comment by sreek011** [comment]
I had this problem and it is resolved. I have the following to share. It may be useful:

A. Problem:
1. Anaconda-navigator  and Spyder (may be other apps also, I didn't try) stopped working (they used to work without any issue before). System - Windows 10 64bit (Anaconda 2019.10)

2. Error message for spyder:
(base) C:\Users\panicker>spyder

Traceback (most recent call last):
File "C:\Users\panicker\anaconda3\lib\site-packages\qtpy_init_.py", line 204, in
from PySide import version as PYSIDE_VERSION # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\panicker\anaconda3\Scripts\spyder-script.py", line 10, in
sys.exit(main())
File "C:\Users\panicker\anaconda3\lib\site-packages\spyder\app\start.py", line 201, in main
from spyder.app import mainwindow
File "C:\Users\panicker\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 52, in
requirements.check_qt()
File "C:\Users\panicker\anaconda3\lib\site-packages\spyder\requirements.py", line 41, in check_qt
import qtpy
File "C:\Users\panicker\anaconda3\lib\site-packages\qtpy_init_.py", line 210, in
raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found



B. Probable reason for the problem:
Installed PyQt5 by...  pip install PyQt5


C. Attempts to fix the problem:
Approach 1. 
a. Uninstalled anaconda (2019.10). (windows control panel, add remove programs, uninstall)
b. Newer version, 2020.02 was available and hence downloaded the same and installed (installed with default/ recommended options)

z. Outcome  - problem persisted, but able to launch both Anaconda Navigator and spyder in the admin mode.

Approach 2. 

a. Uninstalled anaconda (2020.02) (windows control panel, add remove programs, uninstall)
b. Old package 2019.10 installed. (installed with default/ recommended options)
Outcome  - problem persisted, but able to launch both Anaconda Navigator and spyder in the admin mode.

Approach 3. Did the following for clean uninstall as given in the anaconda documentation:
a. > 'conda install anaconda-clean' (Anaconda prompt was working) 
b. > 'anaconda-clean --yes' 
c. Uninstall anaconda (windows control panel, add remove programs, uninstall)
d. Entries (anaconda, spyder, python etc...) in windows registry removed
e. Installed Newer version, 2020.02 (installed with default/ recommended options) 

z. Outcome  - problem persisted, but able to launch both Anaconda Navigator and spyder in the admin mode.


D. Approach 3 - Solution that worked:

a. > 'conda install anaconda-clean' (Anaconda prompt was working) 
b. > 'anaconda-clean --yes' 
c. Uninstalled anaconda (2020.02) (windows control panel, add remove programs, uninstall)
d. Entries (anaconda, spyder, python etc...) in windows registry removed

e. Deleted files and folders persisting after uninstall. - Launch windows file explorer, go to root directory under which anaconda was installed ), In my case C: (windows) drive. Search with key words anaconda, python, spyder etc. Folders and files persisting after anaconda installation were listed in the search results. Delete all persisting files and folders

f. Installed Newer version, 2020.02 (installed with default/ recommended options) 

z. Outcome  - problem resolved.

**Comment by saurabh87prabhu** [comment]
@sreek011
Thanks a ton for the detailed response. I followed Approach 3 and it is now working after a few more steps, namely:
1. > conda update --all
2. > conda install -c conda-forge toml
