### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by shubhali-kadam** [ContinuumIO/anaconda-issues#11756]
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda3"

```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by csoja** [comment]
Based on the error message above, it looks like you do not have write permissions to make any package updates in the current environment.  Also, looking at the system information you are running a very, very old version of conda and probably Anaconda Navigator as well.  Please update and check the permissions on where Anaconda is installed on your machine.  I'm going to close this issue as the version of conda and Anaconda-Navigator is so out of date.  If you are still encountering an error after upgrading, please feel free to submit another issue.
