### ISSUE TITLE
Restore 'easy installer' for Orange 3

### ISSUE THREAD

**Issue by brylie** [ContinuumIO/anaconda-issues#1176]
Recently, the 'Install Orange3' button was removed from anaconda-navigator. This was, in part, due to mismatch in Qt dependency versions between anaconda-installer (Qt5) and orange3 (Qt4). I was instructed that to install Orange 3, I needed to create a new environment and manually install Orange 3 -- including the need to specify which Qt version manually (#1139). This process is error prone, and may be difficult for casual users.

As a casual end-user, I would greatly appreciate a simple one-click button to properly handle the manual steps involved in installing Orange 3, while the Qt dependency issues are sorted out.

**Comment by goanpeca** [comment]
hi @brylie, we are working on this for version 1.4 of navigator coming in some weeks. Thanks for the feedback.

**Comment by brylie** [comment]
Thanks @goanpeca :smile:

**Comment by goanpeca** [comment]
Hi @brylie this should be already working with 1.5.2 (or prior), closing :-)
