### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Berisha-mekayhu** [ContinuumIO/anaconda-issues#1177]
The following errors occured:

None:
Dependency missing in current win-64 channels: 
  - theano ==0.8.2 -> m2w64-toolchain

You can search for packages on anaconda.org with

    anaconda search -t conda m2w64-toolchain

{'conda': '4.1.11', 'os': 'Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'language': 'en_US', 'version': '1.2.1', 'python': '3.5.2', 'pyqt': '4.11.4', 'platform': 'win-64', 'qt': '4.8.7'}

**Comment by goanpeca** [comment]
Hi @Berisha-mekayhu the package is not available for the platform you use.

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`

Cheers
