### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by freed24** [ContinuumIO/anaconda-issues#1179]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - mysql-python ==1.2.5
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'pyqt': '4.11.4', 'python': '3.5.2', 'version': '1.2.1', 'conda': '4.2.9', 'qt': '4.8.7', 'language': 'zh_CN'}

**Comment by goanpeca** [comment]
Hi @freed the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
