### ISSUE TITLE
suddenly stopped working.....navigator start up error

### ISSUE THREAD

**Issue by priyankatalele** [ContinuumIO/anaconda-issues#11802]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Please refer to the Navigator Troubleshooting documentation: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting
