### ISSUE TITLE
I update Anaconda today and now get the following error:

### ISSUE THREAD

**Issue by Buddyha** [ContinuumIO/anaconda-issues#11803]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Details of the error are missing in this report.  Closing the issue.  

Links to the troubleshooting sections of the documentation:
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting
https://docs.anaconda.com/anaconda/user-guide/troubleshooting/
