### ISSUE TITLE
No Python 3.8 packages for `conda-build` on Linux or macOS

### ISSUE THREAD

**Issue by chrisjbillington** [ContinuumIO/anaconda-issues#11814]
As far as I can tell, there are no Python 3.8 Packages for `conda-build` for Linux or macOS in the Anaconda repositories, only for Windows.

### Actual Behavior
```
$ conda create -n py38 python=3.8
$ conda activate py38
$ conda install conda-build
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - conda-build -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

### Expected Behavior

`conda-build` installed sucessfully

### Steps to Reproduce

$ conda create -n py38 python=3.8
$ conda activate py38
$ conda install conda-build

##### Anaconda or Miniconda version:

Latest Miniconda 3 64 bit on Linux

**Comment by csoja** [comment]
Can you please include the output from conda info?  On macOS and Linux 64-bit, I can get a successful solve for python 3.8 & conda-build.  I also see conda-build v3.18.11 Python 3.8 packages listed here: https://repo.anaconda.com/pkgs/main/linux-64/ &  https://repo.anaconda.com/pkgs/main/osx-64/

**Comment by csoja** [comment]
Actually it looks like there were missing Python 3.8 packages that hadn't been uploaded that got uploaded recently.  Is it working for you now?  If so, please close this ticket.

**Comment by chrisjbillington** [comment]
Yep! Works now. Thanks, closing.
