### ISSUE TITLE
gcc compiler issues: remove gcc or change the PATH?

### ISSUE THREAD

**Issue by ptoche** [ContinuumIO/anaconda-issues#11818]
I understand that conda currently ships with `gcc-4.8.5` (I also understand that's for compatibility concerns with older versions of the OS). For some reason, I'm having problems compiling other programs when miniconda is on my PATH and this version of gcc is picked up as the default. When I remove miniconda from the PATH, my system picks up a newer version of gcc that I have and problems disappear.  So I'd like to keep miniconda on my PATH while at the same time taking gcc off as the default compiler. Is there a simple way to do that? Should I `conda remove gcc` or something like that? Thanks for suggestions!

OS: MacOS Catalina 10.15.4. I have run `conda update conda`, `conda update --all` and  `conda clean --all`

**Comment by mingwandroid** [comment]
Conda doesn't ship with gcc 4.8.5.

Conda is just a package manager. The anaconda distribution does have very old builds of gcc 4.8.5 but we don't use them to build any of our software and haven't done for a few years now. We provide and use clang 10 for macOS currently. To install that you issue: conda install clang_osx-64. If you need to compile C++ then you can use: conda install clangxx_osx-64

Thanks!

**Comment by ptoche** [comment]
Thanks mingwandroid! I don't know how I ended up with `gcc` in my miniconda installation, most likely I or some package installed it at some point without thinking too hard about it.
