### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by snowlizard13** [ContinuumIO/anaconda-issues#1181]
The following errors occured:

RuntimeError:
Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://conda.anaconda.org/conda-forge/win-64/shapely-1.5.16-np111py27_1.tar.bz2

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.11', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@snowlizard13 are you still seeing this issues? it was probably during the internet outage of a couple of days ago.

By the way please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
