### ISSUE TITLE
package request: scikit-learn 0.23.1

### ISSUE THREAD

**Issue by ogrisel** [ContinuumIO/anaconda-issues#11836]
https://anaconda.org/anaconda/scikit-learn is still pointing to 0.22.1

In the mean time the following releases happened:

- 0.22.2.post1
- 0.23.0
- 0.23.1

It would be great to get those releases in the anaconda default channel.

**Comment by adrinjalali** [comment]
0.22.2.post1 and 0.23.0 seem to have been skipped, 0.23.1 is there now.

**Comment by jjhelmus** [comment]
0.23.1 was added on Jun 22, 2020.  Is there a need for the older releases to be added as well?

**Comment by ogrisel** [comment]
Let's close this.
