### ISSUE TITLE
Please upgrade prompt_toolkit to 3.0.5

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [ContinuumIO/anaconda-issues#11841]
Could you please upgrade the prompt_toolkit package in the defaults channel from 3.0.4 to the latest version 3.0.5?

This will solve the
`Exception 'MouseEventType.MOUSE_DOWN' is not a valid MouseEventType`
issue that comes up when one tries to copy paste text from ipython.
```
$ ipython --version
7.13.0
```
More details on the issue at https://stackoverflow.com/questions/61238640/click-in-ipython-terminal-window-genrate-mouseeventype-mouse-down-exception

**Comment by jjhelmus** [comment]
`prompt_toolkit` version 3.0.5 packages are now available.

**Comment by KamarajuKusumanchi** [comment]
I do not see 3.0.5 listed in https://anaconda.org/anaconda/prompt_toolkit . It still shows 3.0.4. What am I missing?

**Comment by csoja** [comment]
The anaconda channel on anaconda.org is a mirror and is not the place to install packages from.  The default channels/packages are hosted from repo.anaconda.com.  In this case, the package was uploaded to https://repo.anaconda.com/pkgs/main/noarch/  but has not yet made it to anaconda.org.

**Comment by KamarajuKusumanchi** [comment]
ah, I see! Thanks. I am installing packages from defaults channel only. But I usually search for available package versions in https://anaconda.org/anaconda/ and incorrectly assumed they are one and the same. I will do as you suggest going forward.
