### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by HolyMonarch** [ContinuumIO/anaconda-issues#1184]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
- opencv ==2.4.8
- python 3.5*
  Use "conda info <package>" to see the dependencies for each package.

{'language': 'en', 'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386', 'qt': '4.8.7', 'platform': 'osx-64', 'version': '1.2.1', 'conda': '4.1.6', 'python': '3.5.2', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Hi @HolyMonarch  the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
