### ISSUE TITLE
Repo (and deb) rpm broken : 404 Not Found - NoSuchKey

### ISSUE THREAD

**Issue by gjelu** [ContinuumIO/anaconda-issues#11840]
We normally install miniconda from rpm, as described here: 
https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html

The repo location: https://repo.anaconda.com/pkgs/misc/rpmrepo/conda _currently_ returns

**404 Not Found**
- Code: NoSuchKey
- Message: The specified key does not exist.
- Key: pkgs/misc/rpmrepo/conda
- RequestId: 72DBF18E5662C0E3
- HostId: /7v9eKUm7a8j8Vwu+1DtvEJzq8vHqzqlMSjzNGNMWkkhpO871IJ9GBaViw5zzEPNOHe5Kc9lb0Y=

The same applies for debrepo: https://repo.anaconda.com/pkgs/misc/debrepo/conda

**Comment by gjelu** [comment]
My bad. 
Seems the sync on Red Hat Satellite is failing as the product in satellite is now configured to use a  http proxy and as such I was thinking the repo is invalid. When going directly, it works.

**Comment by entusias** [comment]
@gjelu I have the same problem. Would you mind describing a bit more how you solved this? What do you mean by "going directly" ?

Thank you

**Comment by gjelu** [comment]
@entusias 
With directly I mean without passing a proxy or using Satellite. Like this:

`/etc/yum.repos.d/conda.repo`
```
[conda]
name=Conda
baseurl=https://repo.anaconda.com/pkgs/misc/rpmrepo/conda
enabled=0
gpgcheck=1
gpgkey=https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
```
Executing `yum info conda` shows the available packages and you can install them using yum (note: when you access the baseurl using a normal browser (Chrome,etc.), you will get the 404 Not Found. This is normal!  You can access the [repomd.xml](https://repo.anaconda.com/pkgs/misc/rpmrepo/conda/repodata/repomd.xml) to verify the repo.)

We still have an issue in Satellite for syncing, which didn't occur before, but that part we're still investigating. For sure it has nothing to do with the conda repo. As a workaround, for our internal servers, we are now mirroring the repo using JFrog Artifactory.
