### ISSUE TITLE
i can,t launch my any application on Anaconda Navigator

### ISSUE THREAD

**Issue by vandana2405** [ContinuumIO/anaconda-issues#11854]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Insufficient detail included in this issue.  Please see the Troubleshooting page in the documentation for additional ideas: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting
