### ISSUE TITLE
conda update spyder hangs on unlinking stage

### ISSUE THREAD

**Issue by httassadar** [ContinuumIO/anaconda-issues#1186]
Windows
Python 2.7.12
Anaconda 4.2.0 (64 bit)
Spyder 3.0.0

When I do
conda update spyder
(to update from 3.0.0-py27_0 to 3.0.1_py27_0)

it will hang at unlinking stage.

Same if I do
conda uninstall spyder

**Comment by httassadar** [comment]
pip install spyder --upgrade
worked fine.

**Comment by ccordoba12** [comment]
You shouldn't mix pip and conda packages :-)

What happens if you do

    conda remove spyder

and then

    conda install spyder

?

**Comment by httassadar** [comment]
Found the problem.

I corrupted my conda update last time and removed/reinstalled Anaconda to the same folder. But somehow a conda_lock file exists in the directory (I suppose from the last crash) which blocks the unlinking. Deleting that file then all things work.
