### ISSUE TITLE
Please upgrade pip to 20.1.1

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [ContinuumIO/anaconda-issues#11862]
Could you please upgrade the pip package in the defaults channel from 20.0.2 to 20.1.1?

In 20.1, the 'pip cache dir' command was added which can be handy.
Ref:- https://pip.pypa.io/en/stable/news/

**Comment by jjhelmus** [comment]
pip 20.1.1 packages are now available in the defaults channel.
