### ISSUE TITLE
Python 3.8 installed, Do I install 3.7?

### ISSUE THREAD

**Issue by TimothyEbert** [ContinuumIO/anaconda-issues#11871]
I thought I would start learning Python. I downloaded Python 3.8. Then I started a course in Python, and they suggested installing Anaconda. I went to do that and Anaconda would install Python 3.7. Do I need to wait until Anaconda upgrades? I don't really want multiple versions of Python.

**Comment by jjhelmus** [comment]
The next release of Anaconda Individual Edition will be based on Python 3.8.  

If you want to use conda and Python 3.8 right now there are a few options.

* Download and install a Python 3.8 based Miniconda from https://repo.anaconda.com/miniconda/.  Look for py38 in the filename.  
* Create a python 3.8 conda environment using an existing install of Miniconda/Anaconda using `conda create -n py38 python=3.8`.  This environment need to be activated prior to use using `conda activate py38`

There is an anaconda metapackage that can be installed using `conda install anaconda=2020.02 python=3.8` in addition to these options if you want the packages that would come with Anaconda Individual Edition.
