### ISSUE TITLE
sha256sum for Miniconda3 Linux 64 bit mismatching

### ISSUE THREAD

**Issue by d2dugas** [ContinuumIO/anaconda-issues#11877]
https://docs.conda.io/en/latest/miniconda.html
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

## Problem description

Downloaded script Wed 17 June 2020 13:15:00 PM CEST and tried:

`sha256sum Miniconda3-latest-Linux-x86_64.sh`

should result in 

```
957d2f0f0701c3d1335e3b39f235d197837ad69a944fa6f5d8ad2c686b69df3b 
```
but does result in 

```
bb2e3cedd2e78a8bb6872ab3ab5b1266a90f8c7004a22d8dc2ea5effeb6a439a
```

**Fix necessary?**

**Comment by jjhelmus** [comment]
New Miniconda installers were released yesterday and the hashes in the documentation have not yet been updated.  They will be shortly.

**Comment by jjhelmus** [comment]
The SHA256 hashes on https://docs.conda.io/en/latest/miniconda.html have been updated.  The correct has for Miniconda3-latest-Linux-x86_64.sh as of today (June 17th 2020) is `bb2e3cedd2e78a8bb6872ab3ab5b1266a90f8c7004a22d8dc2ea5effeb6a439a`
