### ISSUE TITLE
Cannot launch Anaconda Navigator

### ISSUE THREAD

**Issue by SandrineMo** [ContinuumIO/anaconda-issues#1189]
If I try in a cmd window with "anaconda-navigator" I got the error 'No Qt bindings could be found'
What do I need to do?

**Comment by goanpeca** [comment]
Hi @SandrineMo, could you go to the command window and type

`conda info` and paste the output here and then

`conda list`  and paste the output here?

Thanks

**Comment by SandrineMo** [comment]
Hi,
Thank you for your answer.
I did it and put the information below.
Sand

**Comment by louika** [comment]
After updating I face a similar issue: 

mac:~ user$ anaconda-navigator
```
Traceback (most recent call last):
  File "/Applications/anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 20, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/__init__.py", line 20, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QObject, QThread, QTimer, Signal, QT_VERSION_STR
ImportError: cannot import name 'QT_VERSION_STR'
```

Here is conda info:
```
Current conda install:
               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.21.2
         python version : 3.5.1.final.0
       requests version : 2.10.0
       root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
       envs directories : /Applications/anaconda/envs
          package cache : /Applications/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
```

**Comment by goanpeca** [comment]
@SandrineMo you seem to have an outdated versions of Navigator and the Qt and PyQt libraries.

Qt4 is deprecated and the newer version of Navigator uses Qt5.

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by sundayle** [comment]
block Anacona Host
sudo vim /etc/hosts
```
127.0.0.1 api.alpha.binstar.org
127.0.0.1 api.anaconda.org
```

https://www.sundayle.com/2018/01/21/Anacona-Navigator-No-response/
