### ISSUE TITLE
error - there is an instance of anaconda is already running

### ISSUE THREAD

**Issue by pkj111** [ContinuumIO/anaconda-issues#11898]
Hi there,

I am having error, when I want to open anaconda navigator, there is an window pop up:
 " there is an instance of anaconda is already running"
I am using windows 10 and installed anaconda 3 2020-.02(64 bits)

Can anyone help with this?

**Comment by cheahcq99** [comment]
open a cmd window;
use command tasklist | findstr "pythonw" to find the pid of pythonw, like 37200;
use command tskill 37200 to kill the process.
