### ISSUE TITLE
Please rebuild pykerberos to depend on krb5 1.17

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#11917]
Hello Team Anaconda,

I'm running into a dependency conflict between `libpq` and `pykerberos`. The former requires `krb5` 1.17, while the latter requires 1.16. This makes it impossible to install the latest `sparkmagic` (depends on pykerberos) with the latest `psycopg2` (depends on libpq) and latest `python` 3.7 (see #11882).

Could you please rebuild `pykerberos` to work with `krb5` 1.17? conda-forge already has that package:

`conda search --override-channels -c conda-forge --info pykerberos=1.2.1=py37h74a8448_2`
```txt
pykerberos 1.2.1 py37h74a8448_2
-------------------------------
file name   : pykerberos-1.2.1-py37h74a8448_2.tar.bz2
name        : pykerberos
version     : 1.2.1
build       : py37h74a8448_2
build number: 2
size        : 26 KB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/pykerberos-1.2.1-py37h74a8448_2.tar.bz2
md5         : b06ed6a9bcedaa731ff0ba2453e52bae
timestamp   : 2020-04-02 09:32:58 UTC
dependencies: 
  - krb5 >=1.17.1,<1.18.0a0
  - libgcc-ng >=7.3.0
  - python >=3.7,<3.8.0a0
  - python_abi 3.7.* *_cp37m
```

**Comment by jjhelmus** [comment]
pykerberos 1.2.1 packages are now available in `defaults` which are build against krb5 1.17 and 1.18.

**Comment by rolweber** [comment]
Great, thanks!
