### ISSUE TITLE
Update of geopandas?

### ISSUE THREAD

**Issue by jorisvandenbossche** [ContinuumIO/anaconda-issues#11921]
In the default channel, the latest available version of geopandas is 0.6.1, which in the meantime is already quite old (from last year), the latest version is 0.8.0.

Would it be possible to update geopandas? (it's a noarch package, so is a relatively "easy" package by itself). It would be nice to have the latest version in the default channel.

**Comment by jjhelmus** [comment]
geopandas 0.8.1 is now available in `defaults`
