### ISSUE TITLE
Anaconda Jupyter noteboon - TensorFlow - ImportError: libprotobuf.so.22: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kalyan2823** [ContinuumIO/anaconda-issues#11922]
When i am trying to open Jupyter note book and issue command import tensorflow as tf, am getting error "ImportError: libprotobuf.so.22: cannot open shared object file: No such file or directory".

When i checked libprotobuf, its already installed with version 3.11

### Expected Behavior

am expecting it shoud show version as V2.2.0

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by jjhelmus** [comment]
Please provide the requested information in the issue template.  Without that information it is bot possible to provide guidance on how to fix this issue.
