### ISSUE TITLE
anaconda not open 

### ISSUE THREAD

**Issue by nitesh286** [ContinuumIO/anaconda-issues#11924]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by nitesh286** [comment]
Anaconda not open

**Comment by jjhelmus** [comment]
Please provide the requested information and explain you problem in more detail.
