### ISSUE TITLE
navigator issue

### ISSUE THREAD

**Issue by harish636** [ContinuumIO/anaconda-issues#11930]
my navigatior is not working

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Closing as there is no information included in the ticket.  
You may find something helpful on the Troubleshooting section of the documentation: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting
