### ISSUE TITLE
Anaconda Navigator is crashing frequently

### ISSUE THREAD

**Issue by VinayakDataScience** [ContinuumIO/anaconda-issues#11942]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
I'm sorry to hear you have having trouble with Navigator crashing.  However, you included none of the information that is requested in the template - so there is nothing that can be done with this error report.
