### ISSUE TITLE
Please build the Python 3.6.11 security fix release

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#11944]
Hello Team Anaconda,

a Python security fix release 3.6.11 was published a few weeks ago:
https://www.python.org/downloads/release/python-3611/

Could you please update the python 3.6 conda package with these security fixes?

**Comment by mingwandroid** [comment]
We no longer support Python 3.6 nor build packages for it. If you need this for business reasons please get in touch with sales@anaconda.com

Thanks.

**Comment by rolweber** [comment]
Thanks for the quick response.

**Comment by rolweber** [comment]
@mingwandroid I relayed your response to my superiors. You made a sale :-D
