### ISSUE TITLE
Anaconda Does Not Initialize Correctly Pop!_OS Linux (Fix included)

### ISSUE THREAD

**Issue by dasgeekchannel** [ContinuumIO/anaconda-issues#11940]
### Actual Behavior

After installing Anaconda it will not get past initialization logo. Terminal error states local variable distro name error.

### Expected Behavior

The fix for the issue is to run conda update anaconda-navigator. During this update there is something that resolves the naming error in the code which appears to search for Ubuntu, Debian, openSUSE, etc. but does not work with Pop!_OS or other derivatives like Mint. 

### Steps to Reproduce

Install Anaconda in Pop!_OS following site instructions. It will not launch.

##### Anaconda or Miniconda version:
Anaconda3-2020.02-Linux-x86_64.sh

##### Operating System:
Pop!_OS

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

     active environment : base
    active env location : /home/dasgeek/anaconda3
            shell level : 1
       user config file : /home/dasgeek/.condarc
 populated config files : /home/dasgeek/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.31
       base environment : /home/dasgeek/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dasgeek/anaconda3/pkgs
                          /home/dasgeek/.conda/pkgs
       envs directories : /home/dasgeek/anaconda3/envs
                          /home/dasgeek/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/5.4.0-7634-generic pop/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

</details>

**Comment by mingwandroid** [comment]
Where is the fix?

**Comment by dasgeekchannel** [comment]
In the first line of Expected Behavior: The fix for the issue is to run $ conda update anaconda-navigator.

**Comment by mingwandroid** [comment]
Ah thanks. Not a current bug then... Closing
