### ISSUE TITLE
Spyder not opening due to incomplete installation of anaconda

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1195]
_From @AshaSusan on October 25, 2016 10:1_

I had installed Anaconda suucessfully and could execute programs using spyder. One day I could not so I unsinstalled and reinstalled. But it didnt work
 Installed anaconda3-4.2.0 Windows 64 bit. Three error messages were shown hence used the following commands which worked
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib_nsis.py" addpath
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib_nsis.py" mkdirs
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib_nsis.py" mkmenus
- Spyder is not opening
- Error shown:
  ![image](https://cloud.githubusercontent.com/assets/23001679/19621162/7e118138-98a9-11e6-84fa-4f5233723ffb.png)
- .ipython directory is not present in my folder.
  I tried the following commands on command prompt. C://Users/Asha
  conda install -f qt
  conda install -f pyqt
  got the following output
  ![image](https://cloud.githubusercontent.com/assets/23001679/19681656/e9868128-9ac7-11e6-912c-59d40944b2ec.png)

_Copied from original issue: conda/conda#3723_

**Comment by AshaSusan** [comment]
Reinstalling it didnt work. Same error.

**Comment by mingwandroid** [comment]
@AshaSusan, would it be possible to copy the text of the error you got rather than attaching an image. Some of text has been cut off unfortunately.

Thanks.

**Comment by wjstarrsiii** [comment]
Hello, I am having the same issue with Anaconda2-4.2.0 32 bit on a Win7 64 bit machine.  Exact same error message as above.  Reinstalling did not work.  Force installing qt and pyqt did not work.  Unable to launch spyder or run scripts from the terminal that rely on qt such as matplotlib.

Thanks for any assistance.

**Comment by csoja** [comment]
@wjstarrsiii can you copy the text of the error you got to this issue?

**Comment by wjstarrsiii** [comment]
`This application failed to start because it could not find or load the QT platform plugin "windows" in "".  Reinstalling the application may fix the problem.`

This is the error in the popup window when trying to launch Spyder (same as in image above).  It is the same error message in the console when trying to execute a script that relies on qt for plotting with matplotlib.

**Comment by ccordoba12** [comment]
If your Anaconda installation is incomplete (as the title of this issue clearly states), could you reinstall it and try again?

**Comment by wjstarrsiii** [comment]
I had interpreted "Incomplete Installation" as that the install did not appropriately register the locations of Qt and is therefore incomplete.  I did not receive ANY error messages in my first install or in 2 additional attempts.  The installer appears unable to detect this issue as it reports no failures during installation.

**Comment by ccordoba12** [comment]
I don't know what else to say, sorry :-/

**Comment by wjstarrsiii** [comment]
I'm afraid I don't understand why this is dismissed.  I downloaded the latest installer last night and installed Anaconda.  I received no warnings or alerts during the installation.  Immediately after the install, I try to launch Spyder and it fails.  It tells me it can't find QT and recommends reinstalling.  I reinstall.  It still fails.  Clearly there is a bug here.

**Comment by ccordoba12** [comment]
It's not dismissed, I'm just out of ideas....

**Comment by BKJackson** [comment]
I was having the same issue with Spyder not launching.  

I've been trying to reinstall anaconda and it's failing to install qt because of "failed to link" errors.  It seems that some of the pointers are incorrect.  

Here is the complete error:

    conda update --all
    Fetching package metadata .......
    Solving package specifications: ..........

    Package plan for installation in environment /Applications/anaconda:

    The following NEW packages will be INSTALLED:

    anaconda-client: 1.5.3-py35_0
    ipython:         5.1.0-py35_1
    pyqt:            4.11.4-py35_4
    qt:              4.8.7-1
    qtconsole:       4.2.1-py35_0
    scipy:           0.17.1-np110py35_1
    smart_open:      1.3.5-py35_0

    Proceed ([y]/n)? y

    Linking packages ...
    [qt                  ]|                                                                                   |   0%

    CondaOSError: OS error: failed to link (src='/Applications/anaconda/pkgs/qt-4.8.7-1/mkspecs/default', dst='/Applications/anaconda/mkspecs/default', type=3, error=FileExistsError(17, 'File exists'))

**Comment by ccordoba12** [comment]
@BKJackson, what if you do

    conda remove qt
    conda install -f qt

?

**Comment by wjstarrsiii** [comment]
I tried to remove and force-install both qt and pyqt.  It still fails.

**Comment by BKJackson** [comment]
It can't find qt when it tries to remove it, even though there are multiple versions in my anaconda/pkgs directory. 

    conda remove qt
    Fetching package metadata .......
    Solving package specifications: .

    PackageNotFoundError: Package not found: '' no packages found to remove from environment: /Applications/anaconda


    conda install -f qt
    Fetching package metadata .......
    Solving package specifications: ..........

    Package plan for installation in environment /Applications/anaconda:

    The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qt-5.6.0                   |                0        70.7 MB

    The following NEW packages will be INSTALLED:

    qt: 5.6.0-0

    Proceed ([y]/n)? y

    Fetching packages ...
    qt-5.6.0-0.tar 100% |################################################################| Time: 0:00:20   3.58 MB/s
    Pruning extracted packages from the cache ...
    [      COMPLETE      ]|###################################################################################| 100%
    Extracting packages ...
    [      COMPLETE      ]|###################################################################################| 100%
    Linking packages ...
    An unexpected error has occurred.                                                                         |   0%
    Please consider posting the following information to the
    conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



    Current conda install:

    platform : osx-64
    conda version : 4.2.11
    conda is private : False
    conda-env version : 4.2.11
    conda-build version : not installed
    python version : 3.5.0.candidate.4
    requests version : 2.11.1
    root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
    envs directories : /Applications/anaconda/envs
    package cache : /Applications/anaconda/pkgs
    channel URLs : https://repo.continuum.io/pkgs/free/osx-64
    https://repo.continuum.io/pkgs/free/noarch
    https://repo.continuum.io/pkgs/pro/osx-64
    https://repo.continuum.io/pkgs/pro/noarch
    config file : /Users/[redacted]/.condarc
    offline mode : False



    `$ /Applications/anaconda/bin/conda install -f qt`




    Traceback (most recent call last):
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
    exit_code = args.func(args, p)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
    cmd(state, arg)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/install.py", line 960, in link
    os.makedirs(dst_dir)
    File "/Applications/anaconda/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
    File "/Applications/anaconda/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
    File "/Applications/anaconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
    NotADirectoryError: [Errno 20] Not a directory: '/Applications/anaconda/include/qt/QtCore/5.6.0'

**Comment by BKJackson** [comment]
As a test, I removed all of my old qt packages from my anaconda/pkgs folder and tried "conda update --all" again.  It's still trying to download qt-4.8.7.  This is a root python 3.5 environment, by the way.  

    conda update --all
    Fetching package metadata .......
    Solving package specifications: ..........

    Package plan for installation in environment /Applications/anaconda:

    The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qt-4.8.7                   |                1        39.0 MB

    The following NEW packages will be INSTALLED:

    anaconda-client: 1.5.3-py35_0
    ipython:         5.1.0-py35_1
    pyqt:            4.11.4-py35_4
    qt:              4.8.7-1
    qtconsole:       4.2.1-py35_0
    scipy:           0.17.1-np110py35_1
    smart_open:      1.3.5-py35_0

    Proceed ([y]/n)? y

    Fetching packages ...
    qt-4.8.7-1.tar 100% |#################################################################################################################| Time: 0:00:08   5.08 MB/s
    Extracting packages ...
    [      COMPLETE      ]|####################################################################################################################################| 100%
    Linking packages ...
    [qt                  ]|                                                                                                                                    |   0%

    CondaOSError: OS error: failed to link (src='/Applications/anaconda/pkgs/qt-4.8.7-1/mkspecs/default', dst='/Applications/anaconda/mkspecs/default', type=3, error=FileExistsError(17, 'File exists'))

**Comment by BKJackson** [comment]
I think this is related to the other Navigator errors after installation/updating of conda and anaconda. 

https://github.com/ContinuumIO/anaconda-issues/issues/1201

**Comment by goanpeca** [comment]
@ccordoba12 any ideas here?

**Comment by ccordoba12** [comment]
This is most probably an error about `qt.conf` not being set correctly by our post install script in the Qt package.

However, I have no clear idea about why that happens. But it seems related to global installations instead of home ones.

**Comment by goanpeca** [comment]
>However, I have no clear idea about why that happens. But it seems related to global installations instead of home ones.

Yes, that seems to be the case
