### ISSUE TITLE
Anaconda Navigator Updater "Updating package on root" then "UnsatisfiableError

### ISSUE THREAD

**Issue by MorzanDG** [ContinuumIO/anaconda-issues#11966]
Hi everyone! So today I was gonna update Anaconda on the GUI, as it told me a new update was available. 

Then, what happens is:
<img width="426" alt="Screenshot 2020-08-03 at 5 37 00 PM" src="https://user-images.githubusercontent.com/69145115/89169003-3d710980-d5b0-11ea-9813-6c249fd9c32b.png">
for like 20 minutes, and then after a while, it shows that there is an "Unsatisfiable Error"
<img width="423" alt="Screenshot 2020-08-03 at 5 22 35 PM" src="https://user-images.githubusercontent.com/69145115/89169026-4530ae00-d5b0-11ea-85fe-b8dd6df0a3b4.png">

I have tried using Terminal to do:
`conda update conda`
`conda update anaconda-navigator`
`conda update navigator-updater`

and it worked without many problems. But then when I opened anaconda it still says that there is a new version available, so I just clicked on it.

Anaconda version: (sorry I'm not sure)
Anaconda3
Anaconda Navigator version: 1.9.7, available version 1.9.12

```
     active environment : base
    active env location : /anaconda3
            shell level : 1
       user config file : /Users/morzan/.condarc
 populated config files : /Users/morzan/.condarc
          conda version : 4.8.3
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       virtual packages : __osx=10.14.6
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /anaconda3/pkgs
                          /Users/morzan/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/morzan/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.6.5 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

I really hope someone could help resolve this. Thanks!

**Comment by csoja** [comment]
What is the results of _conda list --show-channel-urls_  ?
I suspect you have the anaconda metapackage pinned - and you need to _conda install anaconda=custom_ in order to be able to update anaconda-navigator.

**Comment by MorzanDG** [comment]
Hi @csoja! Your solution worked perfectly! Thanks man!

**Comment by christakahashi** [comment]
this worked for me too.  Not sure what I did or what that command does but it worked.

**Comment by peterjordaninfo** [comment]
Took me a while to track this suggestion down. But it worked :). Thanks

**Comment by DevGlitch** [comment]
Thank you @csoja this worked for me.

**Comment by maryevanston** [comment]
This also worked for me, thanks @csoja!

**Comment by justkrismanohar** [comment]
Worked for upgrade form 1.10.0 to 2.1.1

Thanks!

**Comment by davidedesi** [comment]
It worked for me as well, from 1.10.0 to 2.1.1
Thanks, @csoja 👍

**Comment by cassandralsmith** [comment]
HELP!
CANNOT UPDATE WITH ANY OF FOLLOWING PUT IN TERMINAL WINDOW ON MAC WITH MONTEREY AND FIREFOX

conda update conda
conda update anaconda-navigator
conda update navigator-updater
conda install anaconda=custom 

OUTPUTS SHOWN BELOW...EVERYTHING METHOD FREEZES AT SOLVING ENVIRONMENT: (I.E. FLEXIBLE ENVIRONMENT, AFTER TRYING (I ASSUME) STRICT

ALSO BELOW SHOWS OUTPUT OF CONDA LIST AT END


tried custom command with and without version2.1.2 (see below)
with output: 
(base) cls16@macbookcls16 ~ % conda install anaconda=custom2.1.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - anaconda=custom2.1.2

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

HERE IS OUTPUT FROM A CUSTOM INSTALL WITHOUT VERSION NUMBER

cls16@macbookcls16 ~ % conda install anaconda=custom
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 


HERE IS A LIST OF CONDA
Last login: Fri Feb 25 14:48:47 on ttys000
(base) cls16@macbookcls16 ~ % conda list --show-channel-urls
# packages in environment at /Applications/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2021.11                  py38_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
anaconda                  custom                   py38_1    defaults
anaconda-client           1.9.0            py38hecd8cb5_0    defaults
anaconda-navigator        2.1.1                    py38_0    defaults
anaconda-project          0.10.2             pyhd3eb1b0_0    defaults
anyio                     2.2.0            py38hecd8cb5_1    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
applaunchservices         0.2.1              pyhd3eb1b0_0    defaults
appnope                   0.1.2           py38hecd8cb5_1001    defaults
appscript                 1.1.2            py38h9ed2024_0    defaults
argh                      0.26.2                   py38_0    defaults
argon2-cffi               20.1.0           py38h9ed2024_1    defaults
arrow                     0.13.1                   py38_0    defaults
asn1crypto                1.4.0                      py_0    defaults
astroid                   2.6.6            py38hecd8cb5_0    defaults
astropy                   4.3.1            py38hf9932de_0    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
audioread                 2.1.9            py38h50d1736_2    conda-forge
autopep8                  1.5.6              pyhd3eb1b0_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.0                pyhd3eb1b0_2    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.10.0             pyh06a4308_0    defaults
binaryornot               0.4.4              pyhd3eb1b0_1    defaults
bitarray                  2.3.0            py38h9ed2024_1    defaults
bkcharts                  0.2                      py38_0    defaults
black                     19.10b0                    py_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.0.0              pyhd3eb1b0_0    defaults
blosc                     1.21.0               h2842e9f_0    defaults
bokeh                     2.4.1            py38hecd8cb5_0    defaults
boto                      2.49.0                   py38_0    defaults
bottleneck                1.3.2            py38hf1fa96c_1    defaults
brotli                    1.0.9                hb1e8313_2    defaults
brotlipy                  0.7.0           py38h9ed2024_1003    defaults
brunsli                   0.1                  h23ab428_0    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
c-ares                    1.17.1               h9ed2024_0    defaults
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py38h50d1736_1    conda-forge
cffi                      1.14.6           py38h2125817_0    defaults
cfitsio                   3.470                hee0f690_6    defaults
chardet                   4.0.0           py38hecd8cb5_1003    defaults
charls                    2.2.0                h23ab428_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.3              pyhd3eb1b0_0    defaults
cloudpickle               2.0.0              pyhd3eb1b0_0    defaults
clyent                    1.2.2                    py38_1    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
conda                     4.11.0           py38h50d1736_0    conda-forge
conda-build               3.21.5           py38hecd8cb5_0    defaults
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-env                 2.6.0                         1    defaults
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    1.7.3            py38h9ed2024_1    defaults
conda-repo-cli            1.0.4              pyhd3eb1b0_0    defaults
conda-token               0.3.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
contextlib2               0.6.0.post1        pyhd3eb1b0_0    defaults
cookiecutter              1.7.2              pyhd3eb1b0_0    defaults
cryptography              3.4.8            py38h2fd3fbb_0    defaults
curl                      7.78.0               h7bc2e8c_0    defaults
cycler                    0.10.0                   py38_0    defaults
cython                    0.29.24          py38he9d5cce_0    defaults
cytoolz                   0.11.0           py38haf1e3a3_0    defaults
daal4py                   2021.3.0         py38h01d92e1_0    defaults
dal                       2021.3.0           hecd8cb5_555    defaults
dask                      2021.10.0          pyhd3eb1b0_0    defaults
dask-core                 2021.10.0          pyhd3eb1b0_0    defaults
dataclasses               0.8                pyh6d0b6a4_7    defaults
dbus                      1.13.18              h18a8e69_0    defaults
debugpy                   1.5.1            py38he9d5cce_0    defaults
decorator                 5.1.0              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713           pyhd3eb1b0_0    defaults
distributed               2021.10.0        py38hecd8cb5_0    defaults
docutils                  0.17.1           py38hecd8cb5_1    defaults
entrypoints               0.3                      py38_0    defaults
et_xmlfile                1.1.0            py38hecd8cb5_0    defaults
expat                     2.4.1                h23ab428_2    defaults
fastcache                 1.1.0            py38h1de35cc_0    defaults
ffmpeg                    4.3.2                h4dad6da_0    conda-forge
filelock                  3.3.1              pyhd3eb1b0_1    defaults
flake8                    3.9.2              pyhd3eb1b0_0    defaults
flask                     1.1.2              pyhd3eb1b0_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.11.0               hd8bbffd_0    defaults
fsspec                    2021.10.1          pyhd3eb1b0_0    defaults
future                    0.18.2                   py38_1    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.21.0               h7535e17_0    defaults
gevent                    21.8.0           py38h9ed2024_1    defaults
giflib                    5.2.1                haf1e3a3_0    defaults
glib                      2.69.1               hdf23fa2_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
gmp                       6.2.1                h23ab428_2    defaults
gmpy2                     2.0.8            py38h6ef4df4_3    defaults
gnutls                    3.6.13               h756fd2b_1    conda-forge
greenlet                  1.1.1            py38h23ab428_0    defaults
h5py                      2.10.0           py38h3134771_0    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
heapdict                  1.0.1              pyhd3eb1b0_0    defaults
html5lib                  1.1                pyhd3eb1b0_0    defaults
icu                       58.2                 h0a44026_3    defaults
idna                      3.2                pyhd3eb1b0_0    defaults
imagecodecs               2021.8.26        py38ha952a84_0    defaults
imageio                   2.9.0              pyhd3eb1b0_0    defaults
imagesize                 1.2.0              pyhd3eb1b0_0    defaults
importlib-metadata        4.8.1            py38hecd8cb5_0    defaults
importlib_metadata        4.8.1                hd3eb1b0_0    defaults
inflection                0.5.1            py38hecd8cb5_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
intel-openmp              2021.4.0          hecd8cb5_3538    defaults
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.4.1            py38hecd8cb5_1    defaults
ipython                   7.29.0           py38h01d92e1_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.5              pyhd3eb1b0_1    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
itsdangerous              2.0.1              pyhd3eb1b0_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4.1              pyhd3eb1b0_0    defaults
jedi                      0.17.2           py38hecd8cb5_1    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
jinja2-time               0.2.0              pyhd3eb1b0_2    defaults
joblib                    1.1.0              pyhd3eb1b0_0    defaults
jpeg                      9d                   h9ed2024_0    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter                   1.0.0                    py38_7    defaults
jupyter_client            6.1.12             pyhd3eb1b0_0    defaults
jupyter_console           6.4.0              pyhd3eb1b0_0    defaults
jupyter_core              4.9.1            py38hecd8cb5_0    defaults
jupyter_server            1.4.1            py38hecd8cb5_0    defaults
jupyterlab                3.2.1              pyhd3eb1b0_1    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.8.2              pyhd3eb1b0_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
jxrlib                    1.1                  haf1e3a3_2    defaults
keyring                   23.1.0           py38hecd8cb5_0    defaults
kiwisolver                1.3.1            py38h23ab428_0    defaults
krb5                      1.19.2               hcd88c3b_0    defaults
lame                      3.100             h35c211d_1001    conda-forge
lazy-object-proxy         1.6.0            py38h9ed2024_0    defaults
lcms2                     2.12                 hf1fd2bf_0    defaults
lerc                      3.0                  he9d5cce_0    defaults
libaec                    1.0.4                hb1e8313_1    defaults
libarchive                3.4.2                haa3ed63_0    defaults
libcurl                   7.78.0               hb8e4fae_0    defaults
libcxx                    12.0.0               h2f01273_0    defaults
libdeflate                1.8                  h9ed2024_5    defaults
libedit                   3.1.20210910         hca72f7f_0    defaults
libev                     4.33                 h9ed2024_1    defaults
libffi                    3.3                  hb1e8313_2    defaults
libflac                   1.3.3                h046ec9c_1    conda-forge
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.16                 h1de35cc_0    defaults
liblief                   0.10.1               h0a44026_0    defaults
libllvm11                 11.1.0               h9b2ccf5_0    defaults
libllvm9                  9.0.1                h21ff451_1    defaults
libnghttp2                1.46.0               ha29bfda_0    defaults
libogg                    1.3.4                h35c211d_1    conda-forge
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.37               ha441bb4_0    defaults
librosa                   0.8.1              pyhd8ed1ab_0    conda-forge
libsndfile                1.0.31               he49afe7_1    conda-forge
libsodium                 1.0.18               h1de35cc_0    defaults
libspatialindex           1.9.3                h23ab428_0    defaults
libssh2                   1.9.0                ha12b0ac_1    defaults
libtiff                   4.2.0                h87d7836_0    defaults
libuv                     1.40.0               haf1e3a3_0    defaults
libvorbis                 1.3.7                h046ec9c_0    conda-forge
libwebp                   1.2.0                hacca55c_0    defaults
libwebp-base              1.2.0                h9ed2024_0    defaults
libxml2                   2.9.12               hcdb78fc_0    defaults
libxslt                   1.1.34               h83b36ba_0    defaults
libzopfli                 1.0.3                hb1e8313_0    defaults
llvm-openmp               12.0.0               h0dcd299_1    defaults
llvmlite                  0.37.0           py38he4411ff_1    defaults
locket                    0.2.1            py38hecd8cb5_1    defaults
lxml                      4.6.3            py38h26b266a_0    defaults
lz4-c                     1.9.3                h23ab428_1    defaults
lzo                       2.10                 haf1e3a3_2    defaults
markupsafe                1.1.1            py38h1de35cc_1    defaults
matplotlib                3.4.3            py38hecd8cb5_0    defaults
matplotlib-base           3.4.3            py38h0a11d32_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mccabe                    0.6.1                    py38_1    defaults
mir_eval                  0.6                pyh9f0ad1d_0    conda-forge
mistune                   0.8.4           py38h1de35cc_1001    defaults
mkl                       2021.4.0           hecd8cb5_637    defaults
mkl-service               2.4.0            py38h9ed2024_0    defaults
mkl_fft                   1.3.1            py38h4ab4a9b_0    defaults
mkl_random                1.2.2            py38hb2f4e1b_0    defaults
mock                      4.0.3              pyhd3eb1b0_0    defaults
more-itertools            8.10.0             pyhd3eb1b0_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.2                h9066e36_1    defaults
mpi                       1.0                       mpich    defaults
mpich                     3.3.2                hc856adb_0    defaults
mpmath                    1.2.1            py38hecd8cb5_0    defaults
msgpack-python            1.0.2            py38hf7b0b51_1    defaults
multipledispatch          0.6.0                    py38_0    defaults
munkres                   1.1.4                      py_0    defaults
mypy_extensions           0.4.3                    py38_0    defaults
navigator-updater         0.2.1                    py38_0    defaults
nbclassic                 0.2.6              pyhd3eb1b0_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.1.0            py38hecd8cb5_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.3                  hca72f7f_2    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
nettle                    3.6                  hedd7734_0    conda-forge
networkx                  2.6.3              pyhd3eb1b0_0    defaults
nltk                      3.6.5              pyhd3eb1b0_0    defaults
nose                      1.3.7           pyhd3eb1b0_1006    defaults
notebook                  6.4.6            py38hecd8cb5_0    defaults
numba                     0.54.1           py38hae1ba45_0    defaults
numexpr                   2.7.3            py38h5873af2_1    defaults
numpy                     1.20.3           py38h4b4dc7a_0    defaults
numpy-base                1.20.3           py38he0bd621_0    defaults
numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
openh264                  2.1.1                hfd3ada9_0    conda-forge
openjpeg                  2.4.0                h66ea3da_0    defaults
openpyxl                  3.0.9              pyhd3eb1b0_0    defaults
openssl                   1.1.1l               h0d85af4_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.3.4            py38h743cdd8_0    defaults
pandoc                    2.12                 hecd8cb5_0    defaults
pandocfilters             1.4.3            py38hecd8cb5_1    defaults
parso                     0.7.0                      py_0    defaults
partd                     1.2.0              pyhd3eb1b0_0    defaults
path                      16.0.0           py38hecd8cb5_0    defaults
path.py                   12.5.0               hd3eb1b0_0    defaults
pathlib2                  2.3.6            py38hecd8cb5_2    defaults
pathspec                  0.7.0                      py_0    defaults
pathtools                 0.1.2              pyhd3eb1b0_1    defaults
patsy                     0.5.2            py38hecd8cb5_0    defaults
pcre                      8.45                 h23ab428_0    defaults
pep8                      1.7.1                    py38_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.4.0            py38h98e4679_0    defaults
pip                       21.2.4           py38hecd8cb5_0    defaults
pkginfo                   1.7.1            py38hecd8cb5_0    defaults
pluggy                    0.13.1           py38hecd8cb5_0    defaults
ply                       3.11                     py38_0    defaults
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
poyo                      0.5.0              pyhd3eb1b0_0    defaults
prometheus_client         0.12.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
prompt_toolkit            3.0.20               hd3eb1b0_0    defaults
psutil                    5.8.0            py38h9ed2024_1    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
py                        1.10.0             pyhd3eb1b0_0    defaults
py-lief                   0.10.1           py38haf313ee_0    defaults
pycodestyle               2.7.0              pyhd3eb1b0_0    defaults
pycosat                   0.6.3            py38h1de35cc_1    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pycurl                    7.44.1           py38hbcfaee0_1    defaults
pydocstyle                6.1.1              pyhd3eb1b0_0    defaults
pyerfa                    2.0.0            py38h9ed2024_0    defaults
pyflakes                  2.3.1              pyhd3eb1b0_0    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyjwt                     2.1.0            py38hecd8cb5_0    defaults
pylint                    2.9.6            py38hecd8cb5_1    defaults
pyls-spyder               0.4.0              pyhd3eb1b0_0    defaults
pyodbc                    4.0.31           py38h23ab428_0    defaults
pyopenssl                 21.0.0             pyhd3eb1b0_1    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py38h655552a_2    defaults
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyqtwebengine             5.15.4                   pypi_0    pypi
pyqtwebengine-qt5         5.15.2                   pypi_0    pypi
pyrsistent                0.18.0           py38hca72f7f_0    defaults
pysocks                   1.7.1                    py38_1    defaults
pysoundfile               0.10.3.post1       pyhd3deb0d_0    conda-forge
pytables                  3.6.1            py38h4727e94_0    defaults
pytest                    6.2.4            py38hecd8cb5_2    defaults
python                    3.8.11               h88f2d9e_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-jsonrpc-server     0.4.0                      py_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python-lsp-black          1.0.0              pyhd3eb1b0_0    defaults
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0    defaults
python-lsp-server         1.2.4              pyhd3eb1b0_0    defaults
python-slugify            5.0.2              pyhd3eb1b0_0    defaults
python.app                3                py38h9ed2024_0    defaults
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd3eb1b0_0    defaults
pywavelets                1.1.1            py38haf1e3a3_2    defaults
pyyaml                    6.0              py38hca72f7f_1    defaults
pyzmq                     22.2.1           py38h23ab428_1    defaults
qdarkstyle                3.0.2              pyhd3eb1b0_0    defaults
qstylizer                 0.1.10             pyhd3eb1b0_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 1.0.3              pyhd3eb1b0_0    defaults
qtconsole                 5.1.1              pyhd3eb1b0_0    defaults
qtpy                      1.10.0             pyhd3eb1b0_0    defaults
readline                  8.1                  h9ed2024_0    defaults
regex                     2021.8.3         py38h9ed2024_0    defaults
requests                  2.26.0             pyhd3eb1b0_0    defaults
resampy                   0.2.2                      py_0    conda-forge
ripgrep                   12.1.1                        0    defaults
rope                      0.21.1             pyhd3eb1b0_0    defaults
rtree                     0.9.7            py38hecd8cb5_1    defaults
ruamel_yaml               0.15.100         py38h9ed2024_0    defaults
scikit-image              0.18.3           py38hae1ba45_0    defaults
scikit-learn              1.0.1            py38hae1ba45_0    defaults
scikit-learn-intelex      2021.3.0         py38hecd8cb5_0    defaults
scipy                     1.7.1            py38h88652d9_2    defaults
seaborn                   0.11.2             pyhd3eb1b0_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                58.0.4           py38hecd8cb5_0    defaults
simplegeneric             0.8.1                    py38_2    defaults
singledispatch            3.7.0           pyhd3eb1b0_1001    defaults
sip                       4.19.8           py38h0a44026_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
snappy                    1.1.8                hb1e8313_0    defaults
sniffio                   1.2.0            py38hecd8cb5_1    defaults
snowballstemmer           2.1.0              pyhd3eb1b0_0    defaults
sortedcollections         2.1.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
sox                       1.4.1                    pypi_0    pypi
sphinx                    4.2.0              pyhd3eb1b0_1    defaults
sphinxcontrib             1.0                      py38_1    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
sphinxcontrib-websupport  1.2.4                      py_0    defaults
spyder                    5.1.5            py38hecd8cb5_1    defaults
spyder-kernels            2.1.3            py38hecd8cb5_0    defaults
sqlalchemy                1.4.22           py38h9ed2024_0    defaults
sqlite                    3.36.0               hce871da_0    defaults
statsmodels               0.12.2           py38h9ed2024_0    defaults
sympy                     1.9              py38hecd8cb5_0    defaults
tbb                       2021.4.0             haf03e11_0    defaults
tbb4py                    2021.4.0         py38haf03e11_0    defaults
tblib                     1.7.0              pyhd3eb1b0_0    defaults
terminado                 0.9.4            py38hecd8cb5_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
text-unidecode            1.3                pyhd3eb1b0_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
threadpoolctl             2.2.0              pyh0d69192_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tifffile                  2021.7.2           pyhd3eb1b0_2    defaults
tinycss                   0.4             pyhd3eb1b0_1002    defaults
tk                        8.6.11               h7bc2e8c_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.11.2             pyhd3eb1b0_0    defaults
tornado                   6.1              py38h9ed2024_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
typed-ast                 1.4.3            py38h9ed2024_1    defaults
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
ujson                     4.0.2            py38h23ab428_0    defaults
unicodecsv                0.14.1                   py38_0    defaults
unidecode                 1.2.0              pyhd3eb1b0_0    defaults
unixodbc                  2.3.9                haf1e3a3_0    defaults
urllib3                   1.26.7             pyhd3eb1b0_0    defaults
watchdog                  2.1.3            py38hd5f6b7e_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py38_1    defaults
werkzeug                  2.0.2              pyhd3eb1b0_0    defaults
wheel                     0.37.0             pyhd3eb1b0_1    defaults
whichcraft                0.6.1              pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1                    py38_0    defaults
wrapt                     1.12.1           py38haf1e3a3_1    defaults
wurlitzer                 2.1.1            py38hecd8cb5_0    defaults
x264                      1!161.3030           h0d85af4_1    conda-forge
xlrd                      2.0.1              pyhd3eb1b0_0    defaults
xlsxwriter                3.0.2              pyhd3eb1b0_0    defaults
xlwings                   0.24.9           py38hecd8cb5_0    defaults
xlwt                      1.3.0                    py38_0    defaults
xmltodict                 0.12.0             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
yapf                      0.31.0             pyhd3eb1b0_0    defaults
zeromq                    4.3.4                h23ab428_0    defaults
zfp                       0.5.5                h23ab428_6    defaults
zict                      2.0.0              pyhd3eb1b0_0    defaults
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zope                      1.0                      py38_1    defaults
zope.event                4.5.0                    py38_0    defaults
zope.interface            5.4.0            py38h9ed2024_0    defaults
zstd                      1.4.9                h322a384_0    defaults

**Comment by zeehasham** [comment]
Run these commands
conda deactivate
conda update anaconda-navigator

**Comment by AlteriusOmega** [comment]
@csoja thank you, that worked perfectly. Can you or anyone else please explain what `conda install anaconda=custom` actually does and why exactly it fixes this issue?

**Comment by csoja** [comment]
anaconda is a metapackage that lists includes all the packages that are in the Anaconda installer.  The particular versions have all the packages within it pinned to a particular version.  The "custom" version removes the pins - so allows you to update any of the packages within the metapackage to the latest, and you are not limited to particular pinned versions.

**Comment by menkes-tom** [comment]
> What is the results of _conda list --show-channel-urls_ ? I suspect you have the anaconda metapackage pinned - and you need to _conda install anaconda=custom_ in order to be able to update anaconda-navigator.

Ran this:
_conda install anaconda=custom_
in conda prompt, and then the navigator updated freely. Thanks!

**Comment by ex-code** [comment]
Ran this and it worked! Thanks!
conda deactivate
conda install anaconda=custom
conda update conda
conda update anaconda-navigator

update from 2.0.3 -> 2.1.4
macOS Monterey V 12.3.1

**Comment by janghyunchoi** [comment]
It works like a magic. Thanks!

**Comment by UcantWASHme** [comment]
@ex-code 
Had the exact same specs and worked like a charm. You've saved my statistics afternoon, thanks!

**Comment by openspaceranger** [comment]
Not sure why this is closed, because it's still an issue on Windows.

**Comment by rithvikmundra** [comment]
@ex-code This worked for me on macOS Monterey 12.4 while upgrading from Anaconda 2.0.1 to 2.1.2. Thank you 👍

**Comment by asieika** [comment]
@csoja thanks it worked perfectly 👍

**Comment by RDT3304** [comment]
for those who may still be having issues... I was getting stuck using both GUI anaconda navigator and anaconda prompt to try to update anaconda navigator but I was able to update using libmamba solver. Documentation can be found below.

https://conda.github.io/conda-libmamba-solver/getting-started/

Specifically, I ran anaconda prompt as admin, installed libmamba solver, and ran:

conda install anaconda-navigator=2.4.2 --solver=libmamba

And that ended up working for me. YMMV

**Comment by zabihshaik** [comment]
Hey @csoja ! Thanks for the solution & explanation. Was tired with facing the error & was about to uninstall it. Just a google search brought me here and got the solution to the problem. Thanks again 👍 

> anaconda is a metapackage that lists includes all the packages that are in the Anaconda installer. The particular versions have all the packages within it pinned to a particular version. The "custom" version removes the pins - so allows you to update any of the packages within the metapackage to the latest, and you are not limited to particular pinned versions.

**Comment by azmek** [comment]
27 November 2023,
Thanks @csoja, solution worked for me too using conda install anaconda=custom in the command line as admin
when that's done, i launched navigator and clicked yes for the update, closed the navigator and the updater took over,
i upgraded from 2.3.2 to 2.5.2 in no more than 5 min while it was going forever before this solution. Thanks again 👍

**Comment by chonydev** [comment]
> What is the results of _conda list --show-channel-urls_ ? I suspect you have the anaconda metapackage pinned - and you need to _conda install anaconda=custom_ in order to be able to update anaconda-navigator.

Thanks!. Here updating from 2.3 to 2.5. It works somehow.

 I'm not pretty sure which was the exact sequence. It raised the "root" message when running the update from Anaconda navigator and updating Conda and Anaconda from the shell didn't work. After running that command I tried again updating conda from shell and finally anaconda navigator from the GUI itself and works.

**Comment by blumrich** [comment]
Thanks, csoja.  My experience on Windows:
1. I opened the Anaconda Prompt and ran 'conda install anaconda=custom'
2. As instructed, I then ran 'conda update -n base -c defaults conda'
3. Finally, I restarted the Anaconda Navigator GUI, which asked me to upgrade, and this time it worked fine in about 2 minutes.
