### ISSUE TITLE
Anaconda wont start

### ISSUE THREAD

**Issue by fkamandika** [ContinuumIO/anaconda-issues#11980]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
object of type 'NoneType' has no len()
Traceback

**Comment by csoja** [comment]
There is insufficient information here.  Perhaps you can find something that will help in the Troubleshooting section of the Navigator documentation? https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting
