### ISSUE TITLE
Tensorflow 2.3.0 build failure when its conda package is built using Anaconda's toolchain

### ISSUE THREAD

**Issue by npanpaliya** [ContinuumIO/anaconda-issues#11987]
**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RHEL 7 ppc64le
TensorFlow installed from (source or binary): Source v2.3.0
TensorFlow version: 2.3.0
Python version: 3.6/3.7
Installed using virtualenv? pip? conda?: Building conda package of TF 2.3
Bazel version (if compiling from source): 3.1.0
GCC/Compiler version (if compiling from source): 7.3 from Anaconda
CUDA/cuDNN version: 10.2/7

**Describe the problem**
I'm trying to build conda package of Tensorflow 2.3 using Anaconda's toolchain with gcc 7.3 on ppc64le. And with gpu variant build, I'm getting following error -
```
ERROR: /home/builder/.cache/bazel/_bazel_builder/738bada2dae39de8837b3ef244ba3e1e/external/flatbuffers/BUILD.bazel:64:1: Linking of rule '@flatbuffers//:flatc' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/builder/.cache/bazel/_bazel_builder/738bada2dae39de8837b3ef244ba3e1e/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla \
    GCC_HOST_COMPILER_PATH=/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_build_env/bin/powerpc64le-conda_cos7-linux-gnu-cc \
    LD_LIBRARY_PATH=::/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/extras/CUPTI/lib64::/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/cuda/lib: \
    PATH=/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_build_env/bin:/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin:/opt/anaconda3/condabin:/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_build_env:/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_build_env/bin:/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla:/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python \
    PYTHON_LIB_PATH=/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.7,6.0,7.0,7.5 \
    TF_CUDA_PATHS=/opt/anaconda3/conda-bld/tensorflow-base_1597311086398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla \
    TF_CUDA_VERSION=10.2 \
    TF_CUDNN_VERSION=7 \
    TF_ENABLE_XLA=1 \
    TF_NCCL_VERSION=2 \
    TF_NEED_CUDA=1 \
    TF_SYSTEM_LIBS=org_sqlite \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/ppc-opt/bin/external/flatbuffers/flatc-2.params)
Execution platform: @local_execution_config_platform//:platform
powerpc64le-conda_cos7-linux-gnu-cc: error: bazel-out/ppc-opt/bin/external/flatbuffers/flatc: No such file or directory
Target @flatbuffers//:flatc failed to build
```

Even on Linux x86_64 with gcc 5.4 I'm seeing similar issue with some or other shared library being generated by build. Also, note that only GPU build is getting affected. CPU builds are working fine. And this error occurs only within conda environment. Standalone build of TF using gcc 7.4 works fine on ppc64le.

**Any other info / logs**
When I digged into the TF commits that went into 2.3.0, I found the change done in this commit https://github.com/tensorflow/tensorflow/commit/e0b19f6ef223af40e2e6d1d21b8464c1b2ebee8f#diff-ee64a9d8638aa0a655dfaac625f72bb2 has been causing the above problem. Since the exact error is not mentioned in the bazel output, I am unable to find out what has gone wrong in the above commit. Reverting the change done in this cc_toolchain_config.bzl.tpl file fixes the problem for me.

If somebody could help me figure out the reason why it is failing only with conda toolchain, it would be really appreciated.

**Conda information:**
```
(base) $ conda -V
conda 4.8.1
```
```
(base) $ conda-build -V
conda-build 3.18.10
```
```
$cat ~/.condarc
channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  - defaults
auto_update_conda: false
remote_max_retries: 5
remote_connect_timeout_secs: 20.0
remote_read_timeout_secs: 150.0
```

**Comment by npanpaliya** [comment]
I've further figured out the exact linker related changes that are causing the error. Changes done in https://github.com/tensorflow/tensorflow/commit/bb4c751414c3562ab3ab4298f866f47438078c37 have introduced the build issues in conda environment which otherwise work fine.

**Comment by npanpaliya** [comment]
@jjhelmus - I know conda recipe for TF is not yet updated for 2.3.0. But probably it would be done soon, so you may also encounter the same issue. Could you please give it a try and let me know if you also face the same issue. Although I'm able to get it working by reverting the changes done in the mentioned commit, a better fix would be welcome.

**Comment by npanpaliya** [comment]
I see that master branch of tensorflow recipes is updated with 2.3. I want to know if the builds are working for 2.3 with the changes that are checked-in as of now. Or if there are any other changes to be pushed in?
Because even with cuda 10.1 I see the same failure at my end. So, just want to know if you have also encounter the same error.

**Comment by npanpaliya** [comment]
@katietz - Could you please let me know if the changes you've pushed so far to create conda package for TF 2.3 are complete and builds are successful on x86_64?

**Comment by npanpaliya** [comment]
@katietz - Could you please let me know the details of your build environment?

**Comment by mikewerth1** [comment]
I'm curious about the state of this ticket; are there still problems in the 2.3 build of tensorflow and tensorflow-gpu on x86_64 with python 3.8?

**Comment by npanpaliya** [comment]
I was able to fix the problem by reverting linker changes done in the commit https://github.com/tensorflow/tensorflow/commit/bb4c751414c3562ab3ab4298f866f47438078c37.
