### ISSUE TITLE
Update PyMongo versions in https://anaconda.org/anaconda/pymongo

### ISSUE THREAD

**Issue by ShaneHarvey** [ContinuumIO/anaconda-issues#11983]
Hi,

Maintainer of [pymongo](https://github.com/mongodb/mongo-python-driver) here. A user has filed an issue with us ([PYTHON-2343](https://jira.mongodb.org/browse/PYTHON-2343)) about poor user experience when installing pymongo via `conda install --all`. Apparently when they run that command it installs pymongo v3.9.0 which is from August 2019. The latest pymongo release is 3.11.0 (see https://pymongo.readthedocs.io/en/stable/ and https://pypi.org/project/pymongo/).

I know that there is an alternative/preferred package maintained by conda-forge here: https://anaconda.org/conda-forge/pymongo and they are already upgrading to 3.11.0: https://github.com/conda-forge/pymongo-feedstock/pull/32
However this package requires a different installation method: `conda install -c conda-forge pymongo`

The issue I'm concerned with is that `conda install --all` seems to install 3.9.0 from https://anaconda.org/anaconda/pymongo. **Is that package still maintained? If so, can we update it to include the latest 3.10.1 and 3.11.0 releases?**

**Comment by cjmartian** [comment]
Thanks for reporting this to us. I'm going to look into building it today.

**Comment by cjmartian** [comment]
Alright, I have updated `pymongo` in defaults. There is both version `3.10.1` and `3.11.0` for `py36`, `37`, and `38` for linux, windows, and osx.
You can verify by running something like `conda search pymongo=3.10.1` or `conda search pymongo=3.11.0` on each arch.

I'm going to close this ticket, unless there are any other concerns. Thank you again for reporting this @ShaneHarvey! 

@csoja

**Comment by ShaneHarvey** [comment]
Thanks @cjmartian!

**Comment by cjmartian** [comment]
Anytime @ShaneHarvey!
