### ISSUE TITLE
Kite installation gives me an error. It says it cannot install since my laptop is 32-but in graphics. What can I do to fix this

### ISSUE THREAD

**Issue by liyema** [ContinuumIO/anaconda-issues#11986]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by cjmartian** [comment]
Can you please fill out the template?
It's hard to debug without any information.
What are you trying to download and how do I reproduce your issue?
