### ISSUE TITLE
We need a nomkl package for Windows for AMD CPU owners

### ISSUE THREAD

**Issue by kienerj** [ContinuumIO/anaconda-issues#11993]
### Actual Behavior

nomkl packages does not exist on Windows.

I'm aware of issue #656 but that is 4 years old and a lot has changed since then, most notably AMD having superior offerings in the workstation area.

##### Operating System:

Windows 10 / Any windows System

### Expected Behavior

With AMD having competitive CPUs again, well actually superior if we look at workstations, it's a pity the are being crippled by the prevalent usage of IntelMKL. On AMD CPUs Intel MKL defaults to a very slow code path and doesn't use AVX/AVX2 at all. There was a "loophole" with the well known trick of setting an environment variable `MKL_DEBUG_CPU_TYPE=5`. However as slimy as Intel are in the newest version of MKL 2020.1 they removed this "trick" and all AMD CPUs get very slow again with any MKL code. (Typically intel anti-competitive practices as always, they should get sued again but that is another topic).

PyPI seems to have openblas builds for all the important dependencies like numpy, pandas,  scikit-learn etc so it should certainly be double to also get a nomkl package on windows. Anyway as is, it's very annyoing as one is being locked into Nvida for deeplearning and now into inferior intel products due to prevalent use of intel MKL. I admit this is also partially AMDs fault for not providing a usable alternative BLAS library. AMD could alternatively simply provide resources for OpenBLAS builds.

Anyway currently anaconda directly leads to Intel vendor lock-in on Windows systems (=corporate environments).  "use linux" is not a solution because often you simply can't.

**Comment by kienerj** [comment]
It seems I was a bit naive and fully trusted social media (and in a pytorch github issue) were people are claiming that the MKL_DEBUG_CPU_TYPE=5 trick isn't working any more. I simply believed them. They are right in that the setting doesn't have an effect anymore. But the reason for that is actually a small miracle. I tested on my Ryzen machine and MKL 2020.1 in a interesting twist offers by default good performance on Ryzen CPU. So the trick has no effect because the fast code path is used by default. 

Anyone can test this by doing a dot product in numpy with 2 very large arrays. MKL numpy is faster than OpenBLAS numpy. With previous MKL versions without the trick MKL numpy dot product on Ryzen was about 4 times slower than vs openblas.

Hence I close this issue as it seems for now to be resolved.

**Comment by ekungurov** [comment]
@kienerj could you provide an example or perf test code, please?

**Comment by kienerj** [comment]
I will check if I can still find it. I have to admit, I do not know what the current status is with MKL and Ryzen.
