### ISSUE TITLE
Anaconda Navigator on MacOS cannot keep the full-screen mode

### ISSUE THREAD

**Issue by DrZDW** [ContinuumIO/anaconda-issues#1199]
When I switch back from other desktop, it will quit the full-screen mode automatically.

**Comment by goanpeca** [comment]
@DrZDW I don't understand your problem.

What OS are you using, what version?

**Comment by DrZDW** [comment]
OS X El Capitan Version 10.11.6
I clicked the green button on left-top corner of the window to make it fullscreen, then I switched to another desktop in the mission control and switched back, then it changed from fullscreen mode to window mode automatically.

**Comment by goanpeca** [comment]
Got it, will work on a fix for the next release

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
