### ISSUE TITLE
Unable to download anaconda from the site

### ISSUE THREAD

**Issue by godslayer201** [ContinuumIO/anaconda-issues#12009]
### Actual Behavior

Clicked on download for windows multiple times,yet didnt download,even after making an account

### Expected Behavior

Should have downloaded

##### Operating System:
windows 10
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Are you still having this issue? Can you download the installer you need directly from here: https://repo.anaconda.com/archive/ ?

**Comment by godslayer201** [comment]
Hello sir, no,I didnt have the issue today when i tried to download it. Its working now. Thnak you
