### ISSUE TITLE
Issue in Opening Anaconda Navigator

### ISSUE THREAD

**Issue by apar5070** [ContinuumIO/anaconda-issues#12003]
### Actual Behavior

I installed latest Anaconda Navigator on my laptop, it completed the process but the navigator is not opening. When searched in the search menu I can find the Anaconda Navigator but when clicked for opening the Navigator, it shows the blank dos screen for few seconds and then the same screen gets shut down. After that no any further progress of opening or any notifications. The same process continued but no any opening of Navigator. 
I tried all the commands instructions provided in https://docs.anaconda.com/anaconda/install/verify-install/ but no progress so far. 
I have got Windows 10, 32 bit, Office 13 installed with 4 GB RAM with 500 GB hard disk. Not sure what is the issue so far. I too installed .Net Framework core, thinking might be it's due to not installation of .Net Framework. But still it is not working.

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by cjmartian** [comment]
Could you fill out the rest of the template, it may provide information that I could use to further help you.
