### ISSUE TITLE
Anaconda Navigator on MacOS cannot be launched after updating the package in root env.

### ISSUE THREAD

**Issue by DrZDW** [ContinuumIO/anaconda-issues#1200]
The navigator crashed after the update, and could not be launched again. It will loading for a while and quit.

**Comment by maak** [comment]
Sounds like 1201. I am seeing the same issue.

**Comment by DrZDW** [comment]
I found that after cloning a new env, the .app file in the Application folder will be changed  to an alias of the Anaconda-Navigator.app in the ~/anaconda3/env/EnvName/ folder, and that one could not run successfully, it crashed during initializing. Then I ran the Anaconda-Navigator.app in ~/anaconda3/ and it worked. Hope that will be helpful to solve the bug.

**Comment by goanpeca** [comment]
@ilanschnell

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by jeremyabramson** [comment]
This exact thing happened to me today:
$ anaconda --version
anaconda Command line client (version 1.7.2).

Anaconda Navigator works perfectly upon install, cloned the base environment to new environment NEWENV and then /Applications/Anaconda-Navigator.app/navigatorapp/Contents/MacOS/run.sh is re-written to:

#!/bin/sh
source "/Users/XXX/anaconda3/envs/NEWENV"/bin/activate root
"/Users/XXX/anaconda3/envs/NEWENV"/bin/anaconda-navigator $@
