### ISSUE TITLE
repodata on repo.anaconda.com doesn't always match what's inside packages

### ISSUE THREAD

**Issue by lorenjanwilson** [ContinuumIO/anaconda-issues#12019]
### Actual Behavior

I've noticed that there are package entries on repo.anaconda.com that have dependencies that don't match what's inside the package itself. This causes broken behavior when creating local channels using the packages in question. I can't think of why this would happen... is it by design?

#### Example

If you download the repodata.json file here: https://repo.anaconda.com/pkgs/main/linux-64/repodata.json

...and scroll to the section for "libarchive-3.4.2-h62408e4_0.conda", you'll find this entry:

```
    "libarchive-3.4.2-h62408e4_0.conda": {
      "build": "h62408e4_0",
      "build_number": 0,
      "depends": [
        "bzip2 >=1.0.8,<2.0a0",
        "libgcc-ng >=7.3.0",
        "libxml2 >=2.9.9,<2.10.0a0",
        "lz4-c >=1.9.2,<1.10.0a0",
        "openssl >=1.1.1f,<1.1.2a",
        "xz >=5.2.5,<6.0a0",
        "zlib >=1.2.11,<1.3.0a0",
        "zstd >=1.4.4,<1.5.0a0"
      ],
      "license": "BSD-2-Clause",
      "license_family": "BSD",
      "md5": "da258dddbbcd789bf79b6051cbc228ab",
      "name": "libarchive",
      "sha256": "d5242e84ed82f74fd5304c8130fdf4574029a753ada78989458edd89826b7aa9",
      "size": 815451,
      "subdir": "linux-64",
      "timestamp": 1587215846741,
      "version": "3.4.2"
    }
```

Please note that the zstd dependency is `"zstd >=1.4.4,<1.5.0a0"` here. 

However, if you download that package file and open it, you'll find in info/index.json the dependency string `"zstd >=1.4.4,<1.4.5.0a0"`. 

Since the former is less restrictive than the latter, currently you'll be able to install zstd 1.4.5 to satisfy that dependency, which according to the contents of the libarchive-3.4.2 package, is not one of the allowed versions. (It's also worth noting that the latest zstd is 1.4.5, so "<1.5.0a0" doesn't even make much sense and is very likely some kind of parsing bug.)

### Expected Behavior

I'm pretty sure the repodata.json for any channel, including public channels, should not specify different dependency information from what is included in the packages. This seems like a bug.

### Steps to Reproduce

Try the following:

1. Create a fresh env
2. Run `conda install conda-build` from the default public channels
3. Copy all of the resulting downloaded packages to a custom local channel, then index it
4. Create another fresh env and try to run `conda install conda-build --channel=/my/local/channel --override-channels`. 

The latter install will fail with a "can't resolve dependencies" error, because the dependencies are different on repo.anaconda.com from what's inside the packages, and thus your resulting local channel has different dependencies in its repodata file which can't be resolved with the other available packages.

The errors you get back are very confusing, because they don't actually point to the problem, but you can work around this by manually copying a compliant version of the zstd package (such as version 1.4.4) into your repository, reindexing, and then the install will work.

Here are the errors you'll see if you do the above using the latest miniconda3 docker image:

```
(test3) root@ca29916457e5:/# conda install --channel /me/channel2/ --override-channels conda-build
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
chardet -> python[version='>=3.8,<3.9.0a0'] -> libgcc-ng[version='>=7.3.0']
pyyaml -> libgcc-ng[version='>=7.3.0']
conda[version='>=4.5'] -> conda-package-handling[version='>=1.3.0'] -> libgcc-ng[version='>=7.3.0']
filelock -> python -> libgcc-ng[version='>=7.3.0']
six -> python -> libgcc-ng[version='>=7.3.0']
py-lief -> libgcc-ng[version='>=7.3.0']
jinja2 -> markupsafe[version='>=0.23'] -> libgcc-ng[version='>=7.3.0']
beautifulsoup4 -> python[version='>=3.8,<3.9.0a0'] -> libgcc-ng[version='>=7.3.0']
python-libarchive-c -> libarchive -> libgcc-ng[version='>=7.3.0']
patchelf -> libgcc-ng[version='>=7.3.0']
requests -> python -> libgcc-ng[version='>=7.3.0']
setuptools -> python[version='>=3.8,<3.9.0a0'] -> libgcc-ng[version='>=7.3.0']
pkginfo -> python[version='>=3.8,<3.9.0a0'] -> libgcc-ng[version='>=7.3.0']
tqdm -> python -> libgcc-ng[version='>=7.3.0']
python[version='>=3.8,<3.9.0a0'] -> libgcc-ng[version='>=7.3.0']
psutil -> libgcc-ng[version='>=7.3.0']
glob2[version='>=0.6'] -> python -> libgcc-ng[version='>=7.3.0']
conda-package-handling[version='>=1.3'] -> libgcc-ng[version='>=7.3.0']
pytz -> python -> libgcc-ng[version='>=7.3.0']

Package certifi conflicts for:
requests -> urllib3[version='>=1.21.1,<1.26,!=1.25.0,!=1.25.1'] -> certifi
setuptools -> certifi[version='>=2016.9.26']
jinja2 -> setuptools -> certifi[version='>=2016.9.26']
requests -> certifi[version='>=2017.4.17']
conda[version='>=4.5'] -> requests[version='>=2.18.4,<3'] -> certifi[version='>=2016.9.26|>=2017.4.17']

Package conda-package-handling conflicts for:
conda-package-handling[version='>=1.3']
conda[version='>=4.5'] -> conda-package-handling[version='>=1.3.0']

Package tqdm conflicts for:
conda[version='>=4.5'] -> conda-package-handling[version='>=1.3.0'] -> tqdm
conda-package-handling[version='>=1.3'] -> tqdm
tqdm

Package chardet conflicts for:
conda[version='>=4.5'] -> requests[version='>=2.18.4,<3'] -> chardet[version='>=3.0.2,<4']
requests -> chardet[version='>=3.0.2,<4']
chardet

Package requests conflicts for:
conda[version='>=4.5'] -> requests[version='>=2.18.4,<3']
requests

Package yaml conflicts for:
pyyaml -> yaml[version='>=0.2.5,<0.3.0a0']
conda[version='>=4.5'] -> ruamel_yaml[version='>=0.11.14,<0.16'] -> yaml[version='>=0.2.5,<0.3.0a0']

Package six conflicts for:
six
conda[version='>=4.5'] -> conda-package-handling[version='>=1.3.0'] -> six[version='>=1.5.2']
conda-package-handling[version='>=1.3'] -> six

Package libstdcxx-ng conflicts for:
patchelf -> libstdcxx-ng[version='>=7.3.0']
python[version='>=3.8,<3.9.0a0'] -> libffi[version='>=3.3,<3.4.0a0'] -> libstdcxx-ng[version='>=7.3.0']
py-lief -> libstdcxx-ng[version='>=7.3.0']

Package setuptools conflicts for:
jinja2 -> setuptools
conda[version='>=4.5'] -> setuptools[version='>=31.0.1']
setuptools
```

##### Anaconda or Miniconda version:

conda 4.8.2, miniconda3 latest (4.8.2)

##### Operating System:

continuumio/miniconda3:latest docker image

##### `conda info`

<details>

```
     active environment : test4
    active env location : /opt/conda/envs/test4
            shell level : 3
       user config file : /root/.condarc
 populated config files :
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.19.76-linuxkit debian/10 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
(test4) root@ca29916457e5:/# conda list --show-channel-urls
# packages in environment at /opt/conda/envs/test4:
#
# Name                    Version                   Build  Channel
```

</details>

**Comment by jjhelmus** [comment]
This is by design.  Please see the explanation in #11920.

**Comment by lorenjanwilson** [comment]
Thanks for that pointer. I've been reading that issue as well as the docs I found at https://docs.conda.io/projects/conda-build/en/latest/concepts/generating-index.html and I have a follow-up question for you...

How can I figure out what patches I'm supposed to apply for each channel?

* I see python scripts for "main", "r", "pro", "msys2", and "free" in the repodata-hotfixes repository, or I can use the resulting patch_instructions.json files.
* For conda-forge, there's a different repository, "conda-forge/conda-forge-repodata-patches-feedstock", that contains a "gen_patch_json.py" script that appears to be the right one. They also save patch_instructions.json files that I can use.
* For the "intel" channel, though, it appears to contain no patch_instructions.json files, and I have no idea where to look to figure out what patches might be applied. I'm pretty sure patches have been applied, because looking at the repodata.json file for the intel channel, it has an updated "zstd" dependency, the same as the one I pasted above. 

Am I supposed to assume that for any repository that doesn't include patch_instructions.json files, I should be applying the main.py patch from repodata-hotfixes? That seems likely to be an unsafe assumption.

**Comment by jjhelmus** [comment]
The patches in the repodata-hotfixes repository are specific to the `main`, `r`, `pro`, `msys2` and `free` channel maintained by Anaconda, Inc which are available at https://repo.anaconda.com/pkgs/.

The patches generated by the scripts in the conda-forge-repodata-patches-feedstock produce the a dated conda-forge-repodata-patches package which is available at https://anaconda.org/conda-forge/conda-forge-repodata-patches.  The latest version of this package is applied to the `conda-forge` channel.  

If a channel does not include a `patch_instructions.json` file than no patching was done to the repodata.  As far as I know only the channels mentioned above have patched repodata.
