### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by twinkle055** [ContinuumIO/anaconda-issues#12015]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary):
TensorFlow version: 2.3.0
Python version: 3.8.3
Installed using virtualenv? pip? conda?: conda
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Provide the exact sequence of commands / steps that you executed before running into the problem : Just ran a file with import tensorflow on python

C:\Users\User.conda\envs\tensor\pythonw.exe F:/Tech_With_Tim/tensorEnv/test.py
Traceback (most recent call last):
File "C:\Users\User.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "F:/Tech_With_Tim/tensorEnv/test.py", line 1, in
import tensorflow
File "C:\Users\User.conda\envs\tensor\lib\site-packages\tensorflow_init_.py", line 41, in
from tensorflow.python.tools import module_util as module_util
File "C:\Users\User.conda\envs\tensor\lib\site-packages\tensorflow\python_init.py", line 40, in
from tensorflow.python.eager import context
File "C:\Users\User.conda\envs\tensor\lib\site-packages\tensorflow\python\eager\context.py", line 35, in
from tensorflow.python import pywrap_tfe
File "C:\Users\User.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in
from tensorflow.python import pywrap_tensorflow
File "C:\Users\User.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "C:\Users\User.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1

**Comment by twinkle055** [comment]
My issue is solved.
I downgraded my tensorflow because my tensorflow version was not compatible with python 3.7.
I used the command - pip install tensorflow==1.2.0
and also, the command - pip install keras==2.2.4
This resolved my issue.

**Comment by cjmartian** [comment]
https://anaconda.org/anaconda/tensorflow/files
https://anaconda.org/anaconda/keras/files

Why not just `conda install` it?

**Comment by twinkle055** [comment]
> https://anaconda.org/anaconda/tensorflow/files
> https://anaconda.org/anaconda/keras/files
> 
> Why not just `conda install` it?

@cjmartian Yes, we could do that too but I was getting a lot of errors doing that. So I opted this method.

**Comment by cjmartian** [comment]
@twinkle055 I see. Could you post those errors here?
There are potential issues with pip and conda in the same environment. I'd like to save you the headache, if I can.

**Comment by twinkle055** [comment]
> My issue

@cjmartian Like I said before, my problem was resolved, but thanks for taking your time to give me your valuable input
