### ISSUE TITLE
Please update dropbox

### ISSUE THREAD

**Issue by Lucurus** [ContinuumIO/anaconda-issues#12032]
The current version on Anaconda is [10.2.0](https://anaconda.org/anaconda/dropbox) with the available version being [10.4.1](https://pypi.python.org/pypi/dropbox).

Normally this shouldn't be a problem but the package is in Beta and some bigger changes happened between those two versions which is why an update would be really helpful.

Also, just for my clarification, as I couldn't find anything about this online: Is there any process where users can request an update of a package or can this only be done via a GitHub issue?

Thanks!

**Comment by Lucurus** [comment]
Pinging @anaconda-pkg-build

**Comment by jjhelmus** [comment]
dropbox 10.4.1 packages are now available in the `defaults` channel. 
Opening an issue here and pinging @anaconda-pkg-build is the recommended method for request these types of updates.

**Comment by Lucurus** [comment]
Perfect, thank you!
