### ISSUE TITLE
Unable to import yaml with fresh miniconda install.

### ISSUE THREAD

**Issue by titusjan** [ContinuumIO/anaconda-issues#1205]
I downloaded and installed a fresh install of the 64bit miniconda [here](http://conda.pydata.org/miniconda.html), but I am unable to `import yaml`

I have tried on both OS-X and Linux. Here is the Linux output:

```
~> python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'yaml'
>>> exit()
```

My info is:

```
~> conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/kenter/miniconda3  (writable)
    default environment : /home/kenter/miniconda3
       envs directories : /home/kenter/miniconda3/envs
          package cache : /home/kenter/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

~> conda list
# packages in environment at /home/kenter/miniconda3:
#
conda                     4.2.11                   py35_0  
conda-env                 2.6.0                         0  
decorator                 4.0.10                   py35_0  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
openssl                   1.0.2j                        0  
path.py                   8.2.1                    py35_0  
pexpect                   4.0.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pip                       8.1.2                    py35_0  
prompt_toolkit            1.0.8                    py35_0  
ptyprocess                0.5.1                    py35_0  
pycosat                   0.6.1                    py35_1  
pycrypto                  2.6.1                    py35_4  
pygments                  2.1.3                    py35_0  
python                    3.5.2                         0  
readline                  6.2                           2  
requests                  2.11.1                   py35_0  
ruamel_yaml               0.11.14                  py35_0  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
six                       1.10.0                   py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.1                    py35_0  
wcwidth                   0.1.7                    py35_0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  
~> conda info -e
# conda environments:
#
root                  *  /home/kenter/miniconda3

~> uname -a
Linux vbananke 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
~> 

```

Please let me know if you need more information. Any help would be appreciated. It could well be that I do something wrong of course.

**Comment by ilanschnell** [comment]
Miniconda does not include `pyyaml` anymore, because conda 4.2.x does not depend on `pyyaml` anymore.  Of course, you can sill `conda install pyyaml`.

**Comment by titusjan** [comment]
@ilanschnell, I thought I had yaml already installed because the "yaml" package is in the `conda list` output. Installing pyyaml separately works. Thank you.

However, it looks to me that conda 4.2.11 still depends on pyyaml when using the `conda env` command.
```
~> conda env
Traceback (most recent call last):
  File "/Users/kenter/miniconda3/bin/conda-env", line 4, in <module>
    import conda_env.cli.main
  File "/Users/kenter/miniconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 35, in <module>
    from . import main_attach
  File "/Users/kenter/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "/Users/kenter/miniconda3/lib/python3.5/site-packages/conda_env/env.py", line 17, in <module>
    from . import yaml
  File "/Users/kenter/miniconda3/lib/python3.5/site-packages/conda_env/yaml.py", line 8, in <module>
    import yaml
ImportError: No module named 'yaml'
```

Do you agree?

**Comment by ilanschnell** [comment]
Yes, this is correct.  Conda-env still depends on yaml.  This was an oversight, and we are planing to release conda 4.2.12 soon, where conda-env will not import `yaml` anymore.

**Comment by titusjan** [comment]
Ok thanks again.

**Comment by billtubbs** [comment]
This is super confusing.  If you're naive like me and you do the following, how are you supposed to know what happened?

```
$ conda install yaml
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/billtubbs/miniconda3/envs/tf-cpu

  added / updated specs:
    - yaml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.3.9           |           py36_0         155 KB
    ------------------------------------------------------------
                                           Total:         155 KB

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2019.3.9~ --> pkgs/main::ca-certificates-2019.1.23-0
  certifi                                       conda-forge --> pkgs/main
  openssl            conda-forge::openssl-1.1.1b-h14c3975_1 --> pkgs/main::openssl-1.1.1b-h7b6447c_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi-2019.3.9     | 155 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(tf-cpu) [....]$ ipython
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import yaml                                                             
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-38c9922a026e> in <module>
----> 1 import yaml

ModuleNotFoundError: No module named 'yaml'
```

**Comment by mingwandroid** [comment]
@billtubs, this is just how things have been done. It has nothing to do with Anaconda.

PyYAML *is* the name of the project you need to import the yaml module from, that's just how the authors of it decided they wished to do things.

In other words, if you weren't using Anaconda at all, you'd still need to be aware of what the project name is that supplies the yaml module so that you can install it via PIP (or something else).

Also, be aware that it's often done like this *deliberately* where two competing projects provide the same named module. One may be faster or more secure or whatever.

**Comment by billtubbs** [comment]
I see.  I suppose you are right.  But is there any way that Anaconda could help users avoid this confusion?

How about reporting a warning when the name of the conda package is the same as the name of a different Python package that will not be installed. 

I.e. something along the lines of:
```
User Warning: Please note that conda package yaml is not the Python yaml package.  For the Python yaml package use conda install pyyaml.
```

Or something.

Just a thought...

**Comment by mingwandroid** [comment]
> But is there any way that Anaconda could help users avoid this confusion?

Like enforcing mandatory package prefixes for every independent software developer in the world so we never have name clashes again? No.

You could write something yourself if you want this. I don't see that it's got anything to do with Anaconda in the least.

**Comment by billtubbs** [comment]
That's not what I was suggesting is it?

**Comment by mingwandroid** [comment]
I don't know, I gave two suggestions, one a bit silly and the other not silly at all. I would encourage you to program the not silly one.

**Comment by jrossyra** [comment]
So I'm not understanding why conda list --> yaml 0.1.something but import yaml doesn't import yaml... has that been answered and I just can't mince this yaml soup?

I know it's not a conda thing, but this yaml situation is just beyond rediculous. I conda list yaml, it has yaml, import yaml doesn't work. rediculous.

**Comment by jjhelmus** [comment]
The `yaml` package is the C yaml library.  `pyyaml` is a often used Python binding which is imported in python using the `yaml` name.  You will needed the later installed in order to import `yaml` in Python.

**Comment by billtubbs** [comment]
I agree it's very confusing.  But according to the comments above, all users (including beginners) should not expect a package called `something` to be importable using `import something`.  Rather than listening to your intuition which says "something went wrong with the package install" you should be thinking "I wonder if the package developer named the module with a different name?"

**Comment by jrossyra** [comment]
I'm glad this is the only such case I've come across and noticed so far. I do see that yaml is a C-level code, so imho going for "libyaml" for a library and "yaml" for the python package would be the straightforward choice if it really is a library. I'm not very deep into these things, but usually it's easy to distinguish a library in the conda list from a python package. I think I have a repressed memory from years ago where this was super confusing to work around for me and I didn't know how to look things up effectively...

There's probably something I don't understand as to why an easily understandable naming convention wasn't used by the various yaml developers in this case I guess. Thanks for the clarification.

**Comment by msarahan** [comment]
or rather "what did the package that I installed actually contain?" or "what package do I need in order to use this python import?"  Since this isn't entirely straightforward, I looked on Google for what "conda python yaml" would show.  The top hit is a link to the pyyaml package on anaconda.org.

Even on PyPI, not every package has an import name similar to its package name.  For example, scikit-learn (package name) has an import name "sklearn"

The only other one of these that comes to mind is graphviz.

**Comment by jrossyra** [comment]
@msarahan I see what you're saying... I think this one is a bit more insidious since the c code has the exact name of the python package we expect to type. At least I won't forget again to check for pyyaml.

**Comment by itzmrpainz** [comment]
Import wasnt found

**Comment by itzmrpainz** [comment]
I write “import yaml “what i got was import is not found but can be downloaded
