### ISSUE TITLE
Please rebuild googleapis-common-protos-feedstock for 1.52 version

### ISSUE THREAD

**Issue by npanpaliya** [ContinuumIO/anaconda-issues#12053]
Hello Anaconda team,

Although the recipe for googleapis-common-protos is updated for 1.52 version but the package isn't published on the conda channel yet. Could you please rebuild googleapis-common-protos package for 1.52 version?

Also, I see that recipe has also name and sha256 variables defined for 1.51 version along with new updated version and its sha256sum  at https://github.com/AnacondaRecipes/googleapis-common-protos-feedstock/blob/master/recipe/meta.yaml#L4. Is that intentional?

**Comment by jjhelmus** [comment]
`googleapis-common-protos` version 1.52.0 packages are now available in `defaults`. 

> Also, I see that recipe has also name and sha256 variables defined for 1.51 version along with new updated version and its sha256sum at https://github.com/AnacondaRecipes/googleapis-common-protos-feedstock/blob/master/recipe/meta.yaml#L4. Is that intentional?

This is a bug in the recipe.  I've updated the recipe in the AnacondaRecipes organization and submitted conda-forge/googleapis-common-protos-feedstock#19 to fix the conda-forge recipe.

**Comment by npanpaliya** [comment]
Thanks a lot @jjhelmus !
