### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Ryan-bao** [ContinuumIO/anaconda-issues#12064]
## Main error
The following errors occurred:
## Traceback
```

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by csoja** [comment]
There is insufficient information in this error report, so I will be closing the issue.  I do see you are using a very old version of conda and Anaconda Navigator - so you maybe have better luck using the latest version.  After updating, if you are still having issues, please open a new issue.
