### ISSUE TITLE
Failed to install Anaconda in MacOSX 10.9.5 by the official installer

### ISSUE THREAD

**Issue by dibbla** [ContinuumIO/anaconda-issues#12076]
**Actual Behavior**
I've tried to find history versions of installer for MacOSX 10.9.5 but in vain. I'm wandering if the failure is because of the old system version. If so, how can I get a anaconda that enables me to use Opencv in my computer. 
Thx

**Expected Behavior**
Anaconda should install successfully.

**Steps to Reproduce**
Install Anaconda3 Python 3.7 on MacOS 10.9.5

**Anaconda or Miniconda version**:
Anaconda3-2019.03-MacOSX-x86_64

**Comment by dibbla** [comment]
By the way, I also tried the command line installer, which returned:
`concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

**Comment by sergisantana** [comment]
The same issue faced today in my old fashion macos 10.9.5.

**Comment by dibbla** [comment]
> The same issue faced today in my old fashion macos 10.9.5 during the installation of conda with the official installer.
> I've found out the archive (https://repo.continuum.io/archive/) of old Anaconda releases. I chosen one around 2015, since my computer is from this period.

thanku u very much, I’ll give it a try.
