### ISSUE TITLE
Dead R Kernel, cannot install package

### ISSUE THREAD

**Issue by qiaoqiaozhu** [ContinuumIO/anaconda-issues#1208]
Hi,
I recently reinstall conda on my MacOs in order to use rpy2. However, my R kernel doesn't work. it's instantly dead upon starting from jupyter. I have R installation outside of conda which works fine, including rJava.
The conda R is installed through ```conda install -c r r-essentials.```
when creating new R kernel file from jupyter, the error message is
```
KernelRestarter: restarting kernel (4/5) WARNING:root:kernel 1ed6fc92-fd56-4d19-a7e3-e9db62e504ab restarted
Error in library(rJava) : there is no package called ‘rJava’
Execution halted
```
However, I do appear to have java. If I run: java -version, I get:
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```
Also, if I run R from command prompt, I cannot install package. A similar complaint about rJava persists (Error in library(rJava)). If I run system("java -version"), I get the same have version info.

I've tried suggestions in issue #999, but they didn't work. Please help.

**Comment by mingwandroid** [comment]
How did you install the outside of conda R installation?

Can you show the contents of `~/Library/R/3.3/library` please and also the output from `conda list --show-channel-urls`.

Thanks.

**Comment by qiaoqiaozhu** [comment]
R outside of conda was installed by downloading the R-3.3.2.pkg from Cran. I do not appear to have ~/Library/R folder.  ```conda list --show-channel-urls``` output follows:

[condaout.txt](https://github.com/ContinuumIO/anaconda-issues/files/564670/condaout.txt)

Thanks

**Comment by qiaoqiaozhu** [comment]
As an aside, I do have a .RProfile set up for RStudio that starts rJava and RJDBC for connection to a server.

**Comment by qiaoqiaozhu** [comment]
I figured it out. conda IRkernel also searches for any .Rprofile even outside conda. When it can't find java it reboots itself, and after a couple tries, shut itself down. I remove the .Rprofile, install necessary package and then put .Rprofile back up, IRkernal works fine. 

It might be worthwhile to limit searching scope of R startup to the conda environment or point this out more explicitly in the documents. Thanks.

**Comment by mingwandroid** [comment]
If I were to limit the scope like you say, I'd only get bugs about that. Closing.
