### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by nijiazhi** [ContinuumIO/anaconda-issues#1211]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - cx_oracle ==5.2
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 42 Stepping 7, GenuineIntel', 'platform': 'win-64', 'language': 'zh_CN', 'conda': '4.2.11', 'version': '1.2.2', 'qt': '4.8.7', 'python': '3.5.2'}

**Comment by goanpeca** [comment]
Hi @nijiazhi the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers

**Comment by nijiazhi** [comment]
3q, i did not log recently.
it already works, thank u very much
