### ISSUE TITLE
feature request: please include SHA256 hash in https://repo.anaconda.com/miniconda/

### ISSUE THREAD

**Issue by jason-sachs** [ContinuumIO/anaconda-issues#12112]
### Actual Behavior

- https://docs.conda.io/en/latest/miniconda.html shows SHA256 hashes
- https://repo.anaconda.com/miniconda/ shows MD5 hashes

### Expected Behavior

- https://docs.conda.io/en/latest/miniconda.html shows SHA256 hashes
- https://repo.anaconda.com/miniconda/ shows SHA256 hashes

### Steps to Reproduce

visit the above webpages

##### Anaconda or Miniconda version:

n/a

##### Operating System:

n/a

##### `conda info`

n/a

##### `conda list --show-channel-urls`

n/a

**Comment by cbouss** [comment]
repo.anaconda.com now includes sha256:
https://repo.anaconda.com/miniconda/

**Comment by Tobychev** [comment]
I think it happened again? 

`Miniconda3 Linux 64-bit | 00938c3534750a0e4069499baf8f4e6dc1c2e471c86a59caa0dd03f4a9269db6` 
at https://docs.conda.io/en/latest/miniconda.html

but

`Miniconda3-latest-Linux-x86_64.sh | 32d73e1bc33fda089d7cd9ef4c1be542616bd8e437d1f77afeeaf7afdb019787`
at https://repo.anaconda.com/miniconda/
