### ISSUE TITLE
anaconda-navigator installation fails to install qt (qt/QtCore/5.6.0) OS X

### ISSUE THREAD

**Issue by BKJackson** [ContinuumIO/anaconda-issues#1213]
The installation is trying and failing to find or create a directory in anaconda/include/qt/QtCore/ called 5.6.0.  

    conda install anaconda-navigator
    Fetching package metadata .......
    Solving package specifications: ..........

    Package plan for installation in environment /Applications/anaconda:

    The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qt-5.6.0                   |                0        70.7 MB
    anaconda-navigator-1.3.2   |           py35_0         3.3 MB
    ------------------------------------------------------------
    Total:        74.0 MB

    The following NEW packages will be INSTALLED:

    anaconda-client:    1.5.3-py35_0
    anaconda-navigator: 1.3.2-py35_0
    pyqt:               5.6.0-py35_0
    qt:                 5.6.0-0

    Proceed ([y]/n)? y

    Fetching packages ...
    qt-5.6.0-0.tar 100% |################################################################| Time: 0:00:12   5.83 MB/s
    anaconda-navig 100% |################################################################| Time: 0:00:00   5.41 MB/s
    Extracting packages ...
    [      COMPLETE      ]|###################################################################################| 100%
    Linking packages ...
    An unexpected error has occurred.                                                                         |   0%
    Please consider posting the following information to the
    conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

    Current conda install:

    platform : osx-64
    conda version : 4.2.11
    conda is private : False
    conda-env version : 4.2.11
    conda-build version : not installed
    python version : 3.5.0.candidate.4
    requests version : 2.11.1
    root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
    envs directories : /Applications/anaconda/envs
    package cache : /Applications/anaconda/pkgs
    channel URLs : https://repo.continuum.io/pkgs/free/osx-64
    https://repo.continuum.io/pkgs/free/noarch
    https://repo.continuum.io/pkgs/pro/osx-64
    https://repo.continuum.io/pkgs/pro/noarch
    config file : /Users/REDACTED/.condarc
    offline mode : False

    `$ /Applications/anaconda/bin/conda install anaconda-navigator`

    Traceback (most recent call last):
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
    exit_code = args.func(args, p)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
    cmd(state, arg)
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
    File "/Applications/anaconda/lib/python3.5/site-packages/conda/install.py", line 960, in link
    os.makedirs(dst_dir)
    File "/Applications/anaconda/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
    File "/Applications/anaconda/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
    File "/Applications/anaconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
    NotADirectoryError: [Errno 20] Not a directory: '/Applications/anaconda/include/qt/QtCore/5.6.0'

**Comment by goanpeca** [comment]
@BKJackson could you remove qt and PyQt from the terminal

`$ conda remove qt pyqt`

And then manually remove the following folder `/Applications/anaconda/include/qt/`

And then reinstalling Qt and PyQt

`$ conda install qt=5 pyqt=5`

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
