### ISSUE TITLE
anaconda-clean error

### ISSUE THREAD

**Issue by electronwill** [ContinuumIO/anaconda-issues#1214]
Made a new Windows 10 VM, installed 64-bit Windows Anaconda3, ran "conda update conda" and "conda update anaconda", ran "anaconda-clean", got no output. (Probably if there is nothing to delete, it would be best for anaconda-clean to output a message saying that.) Ran "mkdir .continuum", ran "anaconda-clean", got this error:

```
C:\Users\builder>anaconda-clean
Traceback (most recent call last):
  File "C:\Users\builder\Anaconda3\Scripts\anaconda-clean-script.py", line 5, in <module>
    sys.exit(anaconda_clean.main())
  File "C:\Users\builder\Anaconda3\lib\site-packages\anaconda_clean.py", line 69, in main
    delete = raw_input("Delete %s? (Y or N): " %fi )
NameError: name 'raw_input' is not defined
```

**Comment by electronwill** [comment]
Also tried on OSX and got the same error.

**Comment by electronwill** [comment]
Tried 'anaconda-clean' again in a python 2 environment and it worked fine.

**Comment by electronwill** [comment]
Made a new python 3 env, installed anaconda-clean there, and got the same error as in the root environment. I see that raw_input() was renamed to input() in python 3. https://docs.python.org/3/whatsnew/3.0.html#builtins

**Comment by electronwill** [comment]
Today another user submitted a report about this bug through the feedback form on the page that explains how to use anaconda-clean:

Submitted on Thursday, November 10, 2016 - 03:08
Email: aditya.dutta619@icloud.com
Please let us know how to improve this page: anaconda-clean command throws an error saying raw_input is not defined
page referrer: https://docs.continuum.io/anaconda/install

I created an issue to track this in the anaconda-clean repo at https://github.com/ContinuumIO/anaconda-clean/issues/2 .

I notice that someone outside Continuum submitted a patch for what seems to be the same problem, at https://github.com/ContinuumIO/anaconda-clean/pull/1 .

The patch does currently have merge conflicts.

Also I'm not sure if applying the patch as it is currently would work for both Python 2 and Python 3, or only for Python 3.

**Comment by csoja** [comment]
There is a new release of anaconda-clean (v1.0.1) that will work with both Python2 and Python3.  
_conda install anaconda-clean_
Closing this issue - please reopen if you encounter this issue with the new version.
