### ISSUE TITLE
Possibility of having a PyTorch > 1.4  GPU package in defaults ?

### ISSUE THREAD

**Issue by lesteve** [ContinuumIO/anaconda-issues#12157]
Is there a chance that a PyTorch > 1.4 GPU package can be made available in the `defaults` channel?

If I read https://anaconda.org/anaconda/pytorch/files correctly:
- for GPU: the latest available version of Pytorch is 1.4
- for CPU: the latest available version of PyTorch is 1.6 for Windows and OSX and 1.5 for Linux

Unfortunately we can not use the PyTorch package from the `pytorch` channel because it needs a glibc >= 2.14 and we are using a CentOS6 machines on an academic cluster with glibc 2.12. Being able to install PyTorch from the `defaults` channel has been very useful for us in the past.

Of course I would completely understand if there were time-consuming technical difficulties to make this happen and/or if it was not at the top of your priorities right now.

cc @jjhelmus @katietz who have been involved in updating the PyTorch recipe: https://github.com/AnacondaRecipes/aggregate/commits/d3b123134e84df55d2455f07af585766170791d2/pytorch-feedstock

For completeness, the dates of the PyTorch releases since 1.4 (from https://github.com/pytorch/pytorch/tags): 
- PyTorch 1.7: October 2020
- PyTorch 1.6: July 2020
- PyTorch 1.5: April 2020
- PyTorch 1.4: January 2020

**Comment by rgommers** [comment]
Note that conda-forge now has CUDA 10.2-11.2 PyTorch packages, and they seem to work well.
