### ISSUE TITLE
installing matplotlib raises error

### ISSUE THREAD

**Issue by rtotheb2000** [ContinuumIO/anaconda-issues#1215]
Hi,

I am trying to install matplotlib on a fresh conda installation, which throws:

`Linking packages ...`
`[COMPLETE]|###################################################################| 100%`
`dbus post-link :: /etc/machine-id not found ..`
`dbus post-link :: .. using /proc/sys/kernel/random/boot_id`

.

Information about the os:

`lsb_release -a`

`LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch`
`Distributor ID:	Scientific`
`Description:	Scientific Linux release 6.8 (Carbon)`
`Release:	6.8`
`Codename:	Carbon`

Using matplotlib.pyplot in a script then leads to

`QXcbConnection: Could not connect to display `

and trying to set

`import matplotlib as mpl`
`mpl.use('Agg')`
`import matplotlib.pyplot as plt`

raised

`python3.5/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;`

Can someone help with this error? I am sorry, if that is not actually a bug and I am just to uninformed to understand the issue. But setting up a new env and only trying to install matplotlib created the exact same behavior.

**Comment by ccordoba12** [comment]
@mingwandroid?

**Comment by mingwandroid** [comment]
The text is informative only, nothing to worry about.

How are you using matplotlib? From with Spyder? If so, this may be useful:

http://stackoverflow.com/questions/23452550/spyder-matplotlib-userwarning-this-call-to-matplotlib-use-has-no-effect-becau

**Comment by rtotheb2000** [comment]
@mingwandroid I do not use it from any IDE (spyder or any other), I just run a script `python test.py` importing pyplot as specified above and it raises the described error.

**Comment by rtotheb2000** [comment]
This seems to work:

`import matplotlib as mpl`
`mpl.use('Agg')`
`import matplotlib.pyplot as plt`
`plt.ioff()  #http://matplotlib.org/faq/usage_faq.html (interactive mode)`

.

source: [Stackoverflow - Problem running python/matplotlib in background after ending ssh session](http://stackoverflow.com/questions/2443702/problem-running-python-matplotlib-in-background-after-ending-ssh-session)

**Comment by mingwandroid** [comment]
Ah yes, of course. Thanks for updating us.
