### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by slwessels** [ContinuumIO/anaconda-issues#1216]
The following errors occured:

RuntimeError:
Could not find anaconda.org user t

{'qt': '4.8.7', 'version': '1.2.1', 'python': '3.5.2', 'pyqt': '4.11.4', 'platform': 'linux-64', 'language': 'en_ZA', 'conda': '4.1.12', 'os': 'Linux;4.4.0-45-generic;#66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016;x86_64;x86_64'}

**Comment by goanpeca** [comment]
@slwessels please update to the latest version. On the command prompt type

`conda update anaconda`

**Comment by slwessels** [comment]
Great! Thanks will do so immediately
