### ISSUE TITLE
Request to build cmake-feedstock to publish newer cmake

### ISSUE THREAD

**Issue by npanpaliya** [ContinuumIO/anaconda-issues#12168]
Hello,

Currently cmake package in the main channel is 3.14. We need the newer versions of cmake for our work.  I see that recipes are updated for 3.18.2 but the builds are not created with those. May I request to build and publish newer cmakes?

**Comment by adipietro18** [comment]
`cmake` version 3.19.3 is now available on repo.anaconda.com (including linux-ppc64le). 👍
