### ISSUE TITLE
Which anaconda installer will use python 3.7 not python 3.8

### ISSUE THREAD

**Issue by minertom** [ContinuumIO/anaconda-issues#12171]
I have an issue with a package called torchvision which is not compatible with python 3.8. When I load anaconda it uses python 3.8 and I have not been able to change this. Yes, in the environments tab of anaconda navigator there is a way to change the python version but this failed.

I have been to the anaconda archive site but there is no data as to which archive uses python 3.7.

Thank You
Tom

**Comment by csoja** [comment]
An alternative is to use the Miniconda Python 3.7 installer - https://repo.anaconda.com/miniconda/ for the ones available - the ones that say "py37" are Python 3.7 based.
The last Anaconda installer that was Python 3.7 based was 2020.02.
However, if you already have Anaconda installed, you just need to create a new environment with the packages you need and then activate it. 
i.e. conda create -n tv_env python=3.7 torchvision
