### ISSUE TITLE
HELP! I cannot import tensorflow2.3.0!

### ISSUE THREAD

**Issue by Fyzjym** [ContinuumIO/anaconda-issues#12177]
# Problem Description
The tf1.x and tf2.1 installed with anaconda can be imported correctly, but tf2.3 cannot. Please note that the above software is the cpu version.
# Command sequence
Create a virtual environment: conda create -n tensorflow2_3 python=3.8
Activate the virtual environment: activate tensorflow2_3
pip installation: pip install tensorflow-cpu==2.3.0
Open jupyter noteboook
import tensorflow
# System and software version information
OS: Microsoft Windows 10 --10.0.19041
CPU: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
Virtual environment python version: Python 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
# About the solution of the problem
1. MVCR c++ 2015 has been installed
# Log
Traceback (most recent call last):
  File "e:\Anaconda3\envs\tensorflow2_3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\Anaconda3\envs\tensorflow2_3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "e:\Anaconda3\envs\tensorflow2_3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "e:\Anaconda3\envs\tensorflow2_3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "e:\Anaconda3\envs\tensorflow2_3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "e:\Anaconda3\envs\tensorflow2_3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "e:\Anaconda3\envs\tensorflow2_3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by katietz** [comment]
I put the upcoming packages for tensorflow on windows in my channel 'ktietz' for testing.  If you want you can test them. Any feedback is most welcome.
For the pip install on Windows, tensorflow needs some special treatment.  You can find the adjusted recipes in our tensorflow_recipes repository.  Building it requires first a VS2019, additionally you will need recent version of bazel (already available on our channel), and some additional adjustments on building for various issues (eg zip64 point, too many arguments, etc).

**Comment by Fyzjym** [comment]
> I put the upcoming packages for tensorflow on windows in my channel 'ktietz' for testing. If you want you can test them. Any feedback is most welcome.
> For the pip install on Windows, tensorflow needs some special treatment. You can find the adjusted recipes in our tensorflow_recipes repository. Building it requires first a VS2019, additionally you will need recent version of bazel (already available on our channel), and some additional adjustments on building for various issues (eg zip64 point, too many arguments, etc).

thanks a lot~
