### ISSUE TITLE
bring all python modules and give them pre installed, i need chatterbot module, and way to install new modules

### ISSUE THREAD

**Issue by Jay-27** [ContinuumIO/anaconda-issues#12180]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by mingwandroid** [comment]
Sorry, chatterbot is not something we or conda-forge provide (if you wanted to contribute it there they may welcome that). I do not think we will provide it and this bug report is missing the requested details.
