### ISSUE TITLE
Anaconda doesn't update

### ISSUE THREAD

**Issue by colla10** [ContinuumIO/anaconda-issues#12198]
I've been having an issue with updating anaconda to the version 1.10.0. First, I click on a button that asks me if I want to update anaconda, so I click yes, and instead of restarting the app as it told me it would, nothing really happens.
My current anaconda version is 1.9.12

**Comment by csoja** [comment]
This is an unfortunate known bug of 1.9.x.  You will need to open a terminal or Anaconda Prompt and execute _conda update anaconda-navigator_

**Comment by colla10** [comment]
> This is an unfortunate known bug of 1.9.x. You will need to open a terminal or Anaconda Prompt and execute _conda update anaconda-navigator_

Thanks

**Comment by MrMoke** [comment]
> This is an unfortunate known bug of 1.9.x. You will need to open a terminal or Anaconda Prompt and execute _conda update anaconda-navigator_

Worked for me, thanks! :)

**Comment by halvey** [comment]
> This is an unfortunate known bug of 1.9.x. You will need to open a terminal or Anaconda Prompt and execute _conda update anaconda-navigator_

Thank you this also solved my issue :-)
