### ISSUE TITLE
curl: (2) Failed initialization from anaconda

### ISSUE THREAD

**Issue by shanjoshi** [ContinuumIO/anaconda-issues#122]
Hello,

If one uses curl supplied by anaconda, it fails:
curl: (2) Failed initialization from anaconda

This is because
ldd /<path to>/anaconda/bin/curl 
returns
libcurl.so.4 => /<path to >/anaconda/lib/libcurl.so.4 
However LD_LIBRARY_PATH does not include anaconda/lib

After anaconda installation, the anaconda/bin directory is added to the PATH using ~/.bashrc, but the LD_LIBRARY_PATH is not updated. 
So when one runs curl, it's picking up the wrong libs. 

There was some suggestion about removing curl altogether (https://github.com/ContinuumIO/anaconda-issues/issues/72). May not be a bad idea.

Platform: Linux
conda version: 3.5.0
Anaconda version: 1.9.2

Shantanu

**Comment by nehaljwani** [comment]
> libcurl.so.4 => //anaconda/lib/libcurl.so.4

This is intended. It is actually pointing to the right library. `LD_LIBRARY_PATH` is not needed since it uses `RPATH`.

```bash
(122) [nwani@heathens ~]$ ldd $CONDA_PREFIX/bin/curl | grep libcurl
	libcurl.so.4 => /home/nwani/m3/envs/122/bin/../lib/libcurl.so.4 (0x00007f29e7aa2000)
(122) [nwani@heathens ~]$ chrpath -l $CONDA_PREFIX/bin/curl
/home/nwani/m3/envs/122/bin/curl: RPATH=$ORIGIN/../lib
```
