### ISSUE TITLE
Updating pandas on main conda channel

### ISSUE THREAD

**Issue by Dr-Irv** [ContinuumIO/anaconda-issues#12204]
The current version of pandas on the main conda channel is 1.1.3, released October 5, 2020
Version 1.1.4 was released October 30, 2020
Version 1.1.5 was released December 7, 2020

What are the expectations of when the main conda channel will be updated with new versions of pandas?

We're trying to avoid installing things from conda-forge in our projects, because of the belief that binaries there aren't necessarily "stable".

**Comment by csoja** [comment]
Date:   Tue Dec 15 15:49:11 2020 -0600   "pandas 1.1.5"
This version should be available on the main channel of repo.anaconda.com.  

I'm going to close this issue - but, please let me know if you run into an issue, and if so, we can reopen it.
