### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by dtch12345** [ContinuumIO/anaconda-issues#1221]
The following errors occured:

None:
PackageNotFoundError: Package not found: '' Dependency missing in current win-64 channels: 
  - pytables ==3.3.0 -> hdf5 1.8.17

You can search for packages on anaconda.org with

    anaconda search -t conda hdf5

{'qt': '4.8.7', 'python': '3.5.2', 'pyqt': '4.11.4', 'platform': 'win-64', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel', 'version': '1.2.1', 'conda': '4.1.6', 'language': 'zh_CN'}

**Comment by goanpeca** [comment]
Hi @dtch12345 please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
