### ISSUE TITLE
Spyder Crashing Python

### ISSUE THREAD

**Issue by ebleo** [ContinuumIO/anaconda-issues#1223]
When attempting to open a file, the explorer fails to load and the spyder closes out due to a python crash.

I was running on a Windows 7 enterprise machine with a firewall, but nothing is currently being blocked through it.

I downloaded the Anaconda Navigator and was running the 64 bit version. I downgraded to 32 bit version which is working fine and not crashing from loading the explorer or opening or saving files.

In both versions the console was working fine and able to run code; I did not rest further than this.

I also do not have the error logs from the orginal issue. If needed, I can provide additional details.

**Comment by goanpeca** [comment]
@ebleo could you go to the command prompt and type:

`$ conda info` and paste the result here and then

`$ conda list` and paste the result here again.

Cheers

**Comment by ebleo** [comment]
No longer having this issue, do you still want the cmd output?

**Comment by goanpeca** [comment]
@ebleo nope, just checking on these issues I had missed.

So all good now? can we close this issue?

**Comment by ebleo** [comment]
Yes, please close. Thank you!
