### ISSUE TITLE
Internal Server Error when collecting package metadata for Pykaldi

### ISSUE THREAD

**Issue by zweygk** [ContinuumIO/anaconda-issues#12248]
### Actual Behavior

When running the conda command `conda install --yes -c pykaldi pykaldi`, the following error occurs:

> CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url <https://conda.anaconda.org/pykaldi/linux-64/repodata.json>

### Expected Behavior

Successful collection of metadata and package installation

### Steps to Reproduce

`conda install --yes -c pykaldi pykaldi`

##### Anaconda or Miniconda version:

Miniconda3-py37_4.8.2-Linux-x86_64.sh

##### Operating System:

Ubuntu 18.04

##### `conda info`

<details>

```
active environment : None
       user config file : /.condarc
 populated config files :
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : //miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : //miniconda/pkgs
                          /.conda/pkgs
       envs directories : //miniconda/envs
                          /.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/5.0.0-21-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by MathiasGruber** [comment]
Same error for `pytorch` and `rdkit` for me

**Comment by csoja** [comment]
I believe anaconda.org might have been down during this time.  It should be up now - are you still seeing this issue?

**Comment by zweygk** [comment]
Not seeing the issue anymore. Seems to be working again.
