### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by adarsh-3099** [ContinuumIO/anaconda-issues#12247]
### Actual Behavior

'list' object has no attribute 'get'

### Expected Behavior

anaconda should have opened

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Unfortunately, there is insufficient information in this ticket to provide any meaningful feedback or advice.  Closing.
