### ISSUE TITLE
Incomplete Installation Anaconda3-2020.11 When Ran As SYSTEM

### ISSUE THREAD

**Issue by slupmada** [ContinuumIO/anaconda-issues#12252]
### Actual Behavior

Trying to deploy Anaconda3-2020.11 Individual Edition to computer labs at our university through Microsoft Configuration Manager (SCCM). Application installation use the SYSTEM account.  When installation runs as SYSTEM these are the only files that get installed:

01/26/2021  12:16 PM     conda-meta
01/26/2021  12:16 PM     Lib
01/26/2021  12:16 PM     pkgs
01/26/2021  12:16 PM     Uninstall-Anaconda3.exe
11/13/2020  06:51 AM     19,309,814 _conda.exe

I cannot find any log files or records in the event log to tell me what is going on or what is getting blocked.

Command line executed is:
Anaconda3-2020.11-Windows-x86_64.exe /S /InstallationType=AllUsers /AddToPath=1 /RegisterPython=1

Also, no Anaconda entries appear in the Start Menu

### Expected Behavior

I expect several more files to be installed and items under the Start Menu
Any help would be greatly appreciated!

### Steps to Reproduce

Application deployment from Microsoft Configuration Manager

##### Anaconda or Miniconda version:
2020.11 Individual Edition x64

##### Operating System:
Windows 10 Enterprise x64 1909

**Comment by RitaFelix07** [comment]
Estou com o mesmo problema, já instalei outras versões, mas o problema persiste.

Versão Anaconda:
Anaconda3-2020.11-Windows-x86_64
Anaconda3-2020.02-Windows-x86_64

Sistema operacional:
Windows 8.1  x64

**Comment by slupmada** [comment]
I was able to solve this.  I originally neglected to check the box on the Programs tab of the Deployment Type that says "Run installation and uninstall program as 32-bit process on 64-bit clients."  Once I enabled that (checked the box) and updated content on the DPs, installation completed as expected.

**Comment by RitaFelix07** [comment]
O meu computador só aceitou a versão Anaconda3-2019.10-Windows-x86_64.exe, estou utilizando nesse exato momento.
