### ISSUE TITLE
Navigator error. subject has no attribute 'get'

### ISSUE THREAD

**Issue by Balqis-Famuyon** [ContinuumIO/anaconda-issues#12267]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Closing, as there is insufficient information included in this issue.  
You may find the Troubleshooting section of the Navigator documentation helpful: https://docs.anaconda.com/anaconda/navigator/troubleshooting/
