### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by alaaedeen** [ContinuumIO/anaconda-issues#1226]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - _nb_ext_conf ==0.3.0
  - anaconda-client ==1.5.4
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'language': 'en_CA', 'python': '3.5.1', 'platform': 'win-64', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel', 'version': '1.2.1', 'conda': '4.1.12', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Hi @alaaedeen the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers

**Comment by alaaedeen** [comment]
It seems that anaconda-navigator 1.3.2 is not compatible with pyqt4.11 and automatically upgrates to pyqt5.6 when i update/upgrade the navigator.

which version of the navigator is compatible with pyqt4.11.4?

**Comment by goanpeca** [comment]
anaconda-navigator is in theory compatible with qt4 and qt5 so "it should work". BUT Qt4 is no longer maintained so it is not encouraged, and now checking, the dependencies do pin to pyqt >= 5.

We could try to relax this pinning in the next version.

**Comment by alaaedeen** [comment]
Thank you for the quick reply. It is important to highlight that simply updating the navigator automatically & quietly upgrades pyqt from 4 to 5, even though the two versions are miles apart from compatibility, licensing and implementation at this point in time.
 It took a few moments to realize why my UI working from simply upgrading the anaconda navigator.
so if you can please either provide a warning during update of this situation, I believe that would be very helpful to many other users.
