### ISSUE TITLE
[Win7] Navigator can't find envs created by non-admin user

### ISSUE THREAD

**Issue by adriantorrie** [ContinuumIO/anaconda-issues#1227]
`conda info --envs`
```
C:\Windows\System32>conda info --envs
    # conda environments:
    #
    test                     C:\Users\torriea\.conda\envs\test
    root                  *  C:\Program Files\Miniconda3
```

`conda info`
```
C:\Windows\System32>conda info
    Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Miniconda3  (read only)
    default environment : C:\Program Files\Miniconda3
       envs directories : C:\Users\torriea\.conda\envs
                          C:\Program Files\Miniconda3\envs
          package cache : C:\Users\torriea\.conda\envs\.pkgs
                          C:\Program Files\Miniconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\torriea\.condarc
           offline mode : False
```

`.condarc` just has proxy server config (which works)

Miniconda was installed in system directories for all users to access. `anaconda-navigator` was installed in the conda root env.

Navigator runs when called by a user, they can click create env, it creates the env in local users folder:
```
C:\Users\<user_name>\.conda\envs
```

However the Navigator GUI can't see these envs once created, restarted app, restarted machine, nothing allows it to be seen.

`env-dirs` was added to `.condarc`, this didnt work either.

Need help fixing for local users to be able to use.

**Comment by goanpeca** [comment]
@adriantorrie thanks for reporting. We are working on a fix for this issues.

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by msyem2014** [comment]
this is the solve
1- search  .condarc file
2- edit .condarc file

add_anaconda_token: true
add_pip_as_python_dependency: true
allow_softlinks: true
always_copy: false
always_softlink: false
always_yes: false
auto_update_conda: true
binstar_upload: None
changeps1: true
channel_alias: https://conda.anaconda.org
channel_priority: true
channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
client_ssl_cert:
client_ssl_cert_key:
create_default_packages: []
debug: false
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
disallow: []
envs_dirs:
  - /ProgramData/Anaconda3/envs
  - /Users/kar/.conda/envs
ssl_verify: true
offline mode: true

3- only change path in envs_dirs:
put your path

4- save file

that all
