### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ali7amdi** [ContinuumIO/anaconda-issues#1228]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv ==2.4.8
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.2', 'qt': '4.8.7', 'language': 'en', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'conda': '4.2.11', 'pyqt': '4.11.4', 'platform': 'osx-64', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
Hi @ali7amdi the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
