### ISSUE TITLE
is anaoncda using the wrong package name for pytables? Issue installing blaze

### ISSUE THREAD

**Issue by davidslac** [ContinuumIO/anaconda-issues#1229]
When I search for pytables in pip, I don't find anything, if I search for tables, then I find a package called tables that is the pytables project. From this, I have built my own conda package with the name 'tables' for the pytables project. However if I try to conda install blaze from anaconda defaults, it says that is will be installing pytables into my environment, that is it doesn't see that I already have pytables installed since I gave the package the name tables. 

So, is anaconda using the wrong package name? Or am I? If I am, I'll change the name of my package to pytables - but this is confusing, when someone writes setup.py requirements to show a dependency on pytables, do they list the package name as tables or pytables? (to use pytables from Python, I've always had to import tables, not pytables)

**Comment by nehaljwani** [comment]
@davidslac The name of the conda package is `pytables`. The name of the module it provides it `tables`. Please rename your custom built package to `pytables`.
