### ISSUE TITLE
sublime+miniconda No response to compilation [returned non-zero exit status 120]

### ISSUE THREAD

**Issue by hanzch** [ContinuumIO/anaconda-issues#12292]
### Actual Behavior
I use sublime+miniconda to build a compilation environment.
use `ctrl + shift + p , conda:Activate conda` choose environment.
When using the conda build system, there is no response when compiling the .py file.

##### `sublime console output:`

> Traceback (most recent call last):
>   File "P:\MyFile\Programming\Sublime Text 3.2.2.3211(x64)\sublime_plugin.py", line 1050, in run_
>     return self.run(**args)
>   File "P:\MyFile\Programming\Sublime Text 3.2.2.3211(x64)\Data\Installed Packages\Conda.sublime-package\commands.py", line 682, in run
>   File "P:\MyFile\Programming\Sublime Text 3.2.2.3211(x64)\Data\Installed Packages\Conda.sublime-package\commands.py", line 645, in __enter__
>   File "P:\MyFile\Programming\Sublime Text 3.2.2.3211(x64)\Data\Installed Packages\Conda.sublime-package\commands.py", line 629, in conda_version
>   File "./python3.3/subprocess.py", line 589, in check_output
> subprocess.CalledProcessError: Command '['P:/MyFile/Programming/miniconda/python.exe', '-m', 'conda', 'info', '--json']' returned non-zero exit status 120

But if you switch the sublime default python compilation system and switch back to conda, you can use it normally.

### Expected Behavior

But I use cmd.exe RUN `P:/MyFile/Programming/miniconda/python.exe -m conda info --json` shows normal 

##### `cmd output:`
<details>

> 
> {
>   "active_prefix": "P:\\MyFile\\Programming\\miniconda",
>   "active_prefix_name": "base",
>   "channels": [
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64",
>     "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch"
>   ],
>   "conda_build_version": "not installed",
>   "conda_env_version": "4.9.2",
>   "conda_location": "P:\\MyFile\\Programming\\miniconda\\lib\\site-packages\\conda",
>   "conda_prefix": "P:\\MyFile\\Programming\\miniconda",
>   "conda_private": false,
>   "conda_shlvl": 1,
>   "conda_version": "4.9.2",
>   "config_files": [
>     "C:\\Users\\H1\\.condarc"
>   ],
>   "default_prefix": "P:\\MyFile\\Programming\\miniconda",
>   "env_vars": {
>     "CIO_TEST": "<not set>",
>     "CONDA_BAT": "P:\\MyFile\\Programming\\miniconda\\condabin\\conda.bat",
>     "CONDA_DEFAULT_ENV": "base",
>     "CONDA_EXE": "P:\\MyFile\\Programming\\miniconda\\condabin\\..\\Scripts\\conda.exe",
>     "CONDA_PREFIX": "P:\\MyFile\\Programming\\miniconda",
>     "CONDA_PROMPT_MODIFIER": "(base) ",
>     "CONDA_PYTHON_EXE": "P:\\MyFile\\Programming\\miniconda\\python.exe",
>     "CONDA_ROOT": "P:\\MyFile\\Programming\\miniconda",
>     "CONDA_SHLVL": "1",
>     "CURL_CA_BUNDLE": "<not set>",
>     "HOMEPATH": "\\Users\\H1",
>     "NODE_PATH": "P:\\MyFile\\Programming\\nodejs\\node_global\\node_modules",
>     "PATH": "P:\\MyFile\\Programming\\miniconda;P:\\MyFile\\Programming\\miniconda\\Library\\mingw-w64\\bin;P:\\MyFile\\Programming\\miniconda\\Library\\usr\\bin;P:\\MyFile\\Programming\\miniconda\\Library\\bin;P:\\MyFile\\Programming\\miniconda\\Scripts;P:\\MyFile\\Programming\\miniconda\\bin;P:\\MyFile\\Programming\\miniconda\\condabin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;P:\\MyFile\\Programming\\miniconda\\envs\\Scripts;P:\\MyFile\\Programming\\mysql-8.0.12-winx64\\bin;P:\\MyFile\\Programming\\miniconda;P:\\MyFile\\Programming\\miniconda\\Scripts;P:\\MyFile\\Programming\\php-7.4.3;P:\\MyFile\\Programming\\nodejs;P:\\MyFile\\Programming\\nodejs\\node_global;.",
>     "PSMODULEPATH": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
>     "PYTHON_HOME": "P:\\MyFile\\Programming\\miniconda",
>     "REQUESTS_CA_BUNDLE": "<not set>",
>     "SSL_CERT_FILE": "<not set>"
>   },
>   "envs": [
>     "P:\\MyFile\\Programming\\miniconda",
>     "P:\\MyFile\\Programming\\miniconda\\envs\\pps",
>     "P:\\MyFile\\Programming\\miniconda\\envs\\be1",
>     "P:\\MyFile\\Programming\\miniconda\\envs\\bet",
>     "P:\\MyFile\\Programming\\miniconda\\envs\\fssm"
>   ],
>   "envs_dirs": [
>     "P:\\MyFile\\Programming\\miniconda\\envs",
>     "C:\\Users\\H1\\.conda\\envs",
>     "C:\\Users\\H1\\AppData\\Local\\conda\\conda\\envs"
>   ],
>   "is_windows_admin": true,
>   "netrc_file": null,
>   "offline": false,
>   "pkgs_dirs": [
>     "P:\\MyFile\\Programming\\miniconda\\pkgs",
>     "C:\\Users\\H1\\.conda\\pkgs",
>     "C:\\Users\\H1\\AppData\\Local\\conda\\conda\\pkgs"
>   ],
>   "platform": "win-64",
>   "python_version": "3.7.4.final.0",
>   "rc_path": "C:\\Users\\H1\\.condarc",
>   "requests_version": "2.25.1",
>   "root_prefix": "P:\\MyFile\\Programming\\miniconda",
>   "root_writable": true,
>   "site_dirs": [],
>   "sys.executable": "P:\\MyFile\\Programming\\miniconda\\python.exe",
>   "sys.prefix": "P:\\MyFile\\Programming\\miniconda",
>   "sys.version": "3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]",
>   "sys_rc_path": "P:\\MyFile\\Programming\\miniconda\\.condarc",
>   "user_agent": "conda/4.9.2 requests/2.25.1 CPython/3.7.4 Windows/10 Windows/10.0.17763",
>   "user_rc_path": "C:\\Users\\H1\\.condarc",
>   "virtual_pkgs": [
>     [
>       "__win",
>       "0",
>       "0"
>     ],
>     [
>       "__archspec",
>       "1",
>       "x86_64"
>     ]
>   ]
> }
> 

</details>

##### Anaconda or Miniconda version:
conda 4.9.2

##### Operating System:
win10 x64 LTSC
##### `conda info`

<details>

```
     active environment : base
    active env location : P:\MyFile\Programming\miniconda
            shell level : 1
       user config file : C:\Users\H1\.condarc
 populated config files : C:\Users\H1\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : P:\MyFile\Programming\miniconda  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : P:\MyFile\Programming\miniconda\pkgs
                          C:\Users\H1\.conda\pkgs
                          C:\Users\H1\AppData\Local\conda\conda\pkgs
       envs directories : P:\MyFile\Programming\miniconda\envs
                          C:\Users\H1\.conda\envs
                          C:\Users\H1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.7.4 Windows/10 Windows/10.0.17763
          administrator : True
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at P:\MyFile\Programming\miniconda:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0                   pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.9.3                    pypi_0    pypi
bleach                    3.2.1                    pypi_0    pypi
brotlipy                  0.7.0           py37h2bbff1b_1003    defaults
bs4                       0.0.1                    pypi_0    pypi
ca-certificates           2021.1.19            haa95532_0    defaults
certifi                   2020.12.5        py37haa95532_0    defaults
cffi                      1.14.5           py37hcd4344a_0    defaults
chardet                   4.0.0           py37haa95532_1003    defaults
colorama                  0.4.4                    pypi_0    pypi
conda                     4.9.2            py37haa95532_0    defaults
conda-package-handling    1.7.2            py37h76e460a_0    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              3.3.1            py37hcd4344a_1    defaults
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
et-xmlfile                1.0.1                    pypi_0    pypi
idna                      2.10               pyhd3eb1b0_0    defaults
importlib-metadata        3.3.0                    pypi_0    pypi
ipykernel                 5.4.2                    pypi_0    pypi
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jdcal                     1.4.1                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-console           6.2.0                    pypi_0    pypi
jupyter-core              4.7.0                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4                    pypi_0    pypi
mouseinfo                 0.1.3                    pypi_0    pypi
nbclient                  0.5.1                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.0.8                    pypi_0    pypi
nest-asyncio              1.4.3                    pypi_0    pypi
notebook                  6.1.5                    pypi_0    pypi
numpy                     1.19.1                   pypi_0    pypi
openpyxl                  3.0.4                    pypi_0    pypi
openssl                   1.1.1j               h2bbff1b_0    defaults
packaging                 20.8                     pypi_0    pypi
pandas                    1.1.0                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.0.1                    pypi_0    pypi
pip                       21.0.1           py37haa95532_0    defaults
powershell_shortcut       0.0.1                         2    defaults
prometheus-client         0.9.0                    pypi_0    pypi
prompt-toolkit            3.0.8                    pypi_0    pypi
pyautogui                 0.9.52                   pypi_0    pypi
pycosat                   0.6.3            py37h2bbff1b_0    defaults
pycparser                 2.20                       py_2    defaults
pycryptodome              3.6.6                    pypi_0    pypi
pygetwindow               0.0.9                    pypi_0    pypi
pygments                  2.7.3                    pypi_0    pypi
pymsgbox                  1.0.9                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 2.4.7                    pypi_0    pypi
pyperclip                 1.8.1                    pypi_0    pypi
pyqt5                     5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyrect                    0.1.4                    pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pyscreeze                 0.1.26                   pypi_0    pypi
pysocks                   1.7.1                    py37_1    defaults
python                    3.7.4                h5263a28_0    defaults
python-dateutil           2.8.1                    pypi_0    pypi
pytweening                1.0.3                    pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
pywin32                   227              py37he774522_1    defaults
pywinpty                  0.5.7                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
qtconsole                 5.0.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.25.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.87          py37he774522_1    defaults
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                52.0.0           py37haa95532_0    defaults
six                       1.15.0           py37haa95532_0    defaults
snownlp                   0.12.3                   pypi_0    pypi
soupsieve                 2.0.1                    pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0    defaults
terminado                 0.9.1                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.56.0             pyhd3eb1b0_0    defaults
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.3             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1                    pypi_0    pypi
win_inet_pton             1.1.0            py37haa95532_0    defaults
wincertstore              0.2                      py37_0    defaults
wordcloud                 1.8.1                    pypi_0    pypi
xlrd                      1.2.0                    pypi_0    pypi
xlsxwriter                1.3.7                    pypi_0    pypi
xlwt                      1.3.0                    pypi_0    pypi
yaml                      0.2.5                he774522_0    defaults
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4    defaults

```

</details>

**Comment by parthe** [comment]
@hanzch Did you resolve? Can you explain how?

**Comment by hanzch** [comment]
I tried to update ST4, the problem was solved, I hope it helps you.
