### ISSUE TITLE
ERROR conda.core.link:_execute(698): An error occurred defaults::qt-5.9.7-vc14h73c81de_0'.

### ISSUE THREAD

**Issue by Heir93** [ContinuumIO/anaconda-issues#12298]
### Actual Behavior

There is an error being displayed during the installation preventing completion.

"Preparing transaction: ...working... done
Executing transaction: ...working... WARNING conda.core.envs_manager:register_env(50): Unable to register environment. Path not writable or missing.
  environment location: C:\Anaconda3
  registry file: C:\Users\<username>\.conda\environments.txt
done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\Anaconda3\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.

stderr: The system cannot find the file specified.
The system cannot find the file specified.

return code: 1

()

### Expected Behavior

Installation should finish normally. After having this error, most of the files are being deleted. There is no Script folder in Anaconda folder. No shortcuts are being created. No access to the program.

Tried multiple versions with same outcome. Tried changing the install location and the installation type. No result. The error is always the same.

##### Anaconda or Miniconda version:

Anaconda3 2020.11 (64-bit)

##### Operating System:

Windows 10 Pro (x64)

**Comment by mselmanyildirim** [comment]
I'm not sure if it's the same issue, but I encountered a very similar complain from conda: 
```ERROR conda.core.link:_execute(698): An error occurred while installing package'conda-forge::cudatoolkit-10.1.243-h3826478_8'.```
when trying to create an environment from a yaml file. It is mentioned in some issues that python version could be the reason, but the yaml file already defines the python version, which seems suitable for the packages we try to install.

**Comment by Heir93** [comment]
Hello everyone,

I managed to get rid of the issue after installing Windows feature update from Windows Update section (it was 1909 in my case).
The installation went well afterwards.

**Comment by meenaramlakhan321** [comment]
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: E:\Ram\udemy_project2\env\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout: Failed to create temp directory "C:\Users\Ram Lakhan\AppData\Local\Temp\conda-<RANDOM>\"

stderr:
return code: 1

()

**Comment by meenaramlakhan321** [comment]
Any solution ?

**Comment by picasso999** [comment]
Hi! 

I have tried many ways, this below one worked for me

the (base) in anaconda file has no environment variable set.

you can know what envs is set by typing 
"conda info"

if it shows

-active environment : none-

then, 

create a new envs as below

conda create --name environment_name_of_your_own

after following the steps

conda activate environment_name_of_your_own

from (base) , it changes to (environment_name_of_your_own)

you can run your commands from here now, it will work mostly.

it worked for me.

AlSO,

change your PC/Laptop Environment Variables -> User Variables -> TEMP (double click and change directory to) -> C:/Temp
 also
TMP (double click and change directory to) -> C:/Temp


MY "code info"

active environment : D:\miniconda_envi_setup_here\some_folder\env
    active env location : D:\miniconda_envi_setup_here\some_folder\env
            shell level : 3
       user config file : C:\Users\PC Dell\.condarc
 populated config files : C:\Users\PC Dell\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __cuda=11.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\PC Dell\.conda\pkgs
                          C:\Users\PC Dell\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\PC Dell\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\PC Dell\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.9.1 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

**Comment by phineas-pta** [comment]
same issue here #10165

**Comment by falahfakhri-Iraq** [comment]
I'm facing same issue, 

(DL) PS C:\> python -m spyder.app.start
C:\miniconda3\envs\DL\python.exe: Error while finding module specification for 'spyder.app.start' (ModuleNotFoundError: No module named 'spyder')
(DL) PS C:\> conda info

     active environment : DL
    active env location : C:\miniconda3\envs\DL
            shell level : 2
       user config file : C:\Users\FALAH FAKHRI\.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __cuda=11.3=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\miniconda3\pkgs
                          C:\Users\FALAH FAKHRI\.conda\pkgs
                          C:\Users\FALAH FAKHRI\AppData\Local\conda\conda\pkgs
       envs directories : C:\miniconda3\envs
                          C:\Users\FALAH FAKHRI\.conda\envs
                          C:\Users\FALAH FAKHRI\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.9.1 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

**Comment by tdedring** [comment]
Hello,
a colleague is also facing this problem.
The following error is given:
ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.

It appears when importing a yml or even when creating a new environment with "conda create -n env_full anaconda python=3.8"
We tried downloading and installing different Anaconda versions from the archive; turned off the Antivirus program; tested different Python versions; Updated Windows.
As I have no idea what can be done to finally solve this issue, I hope that somebody of you have found a way to deal with it.
Here are the information  from conda info, but from the base env:

active environment : base
    active env location : C:\Users\User\anaconda3
            shell level : 1
       user config file : C:\Users\User\.condarc
 populated config files : C:\Users\User\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\User\anaconda3  (writable)
      conda av data dir : C:\Users\User\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\User\anaconda3\pkgs

**Comment by HridoyHazard** [comment]
anyone got any solutions to this problem?? i'm stuck with it
