### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by lucheeseng827** [ContinuumIO/anaconda-issues#1230]
The following errors occured:

RuntimeError:
HTTPError: 409 Client Error: Conflict for url: https://repo.continuum.io/pkgs/pro/linux-64/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/linux-64/

{'platform': 'linux-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Linux;4.4.0-45-generic;#66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016;x86_64;x86_64', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Hi @lucheeseng827 this seems like a temporal network error. Are you still seeing the issue?

By the way please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers

**Comment by lucheeseng827** [comment]
it works, thanks for your help.
