### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jmtoral** [ContinuumIO/anaconda-issues#1231]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - fiona ==1.6.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel', 'version': '1.2.1', 'pyqt': '5.6.0', 'qt': '5.6.0', 'conda': '4.2.12', 'platform': 'win-64', 'language': 'en_US', 'python': '3.5.2'}

**Comment by goanpeca** [comment]
Hi @jmtoral the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
