### ISSUE TITLE
anaconda navigator problems 

### ISSUE THREAD

**Issue by nklever** [ContinuumIO/anaconda-issues#1234]
executing **anaconda-navigator** in a normal terminal, it runs fine,
but running it from a user-defined command terminal profile it brings the following error:

File "~/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 374, in set_root_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

The same problem arrives, if you set up anaconda-navigator into the ubuntu starter dashboard

**Comment by goanpeca** [comment]
@nklever could you open a terminal and type

`$ conda info` and paste the result here and then

`$ conda list` and paste the result here again.

Cheers

**Comment by goanpeca** [comment]
It seems that a `a user-defined command terminal profile` does not include conda on the PATH which is a requirement for conda and Navigator to work properly.

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by AnthonyWC** [comment]
I ran into this issue on ubuntu; launches fine in terminal but not from unity launcher:
anaconda-navigator        1.6.2                    py36_0
