### ISSUE TITLE
I can't open Anaconda Navigator 'bytes' object has no attribute 'get'

### ISSUE THREAD

**Issue by Rachel-Hii** [ContinuumIO/anaconda-issues#12348]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Unfortunately, there is insufficient information included in this issue to be able to understand or reproduce the problem.  I'd recommend you check the Troubleshooting section of the Navigator documentation: https://docs.anaconda.com/anaconda/navigator/troubleshooting/
