### ISSUE TITLE
SHA256 hashes are incorrect on miniconda download page

### ISSUE THREAD

**Issue by moble** [ContinuumIO/anaconda-issues#12345]
### Actual Behavior

  * https://docs.conda.io/en/latest/miniconda.html shows the latest versions of miniconda installers have (32-bit) MD5 sums listed in the "SHA256 hash" column.  Older versions appear to correctly use (64-bit) SHA 256 sums.  
  * https://conda.io/projects/conda/en/latest/user-guide/install/download.html#cryptographic-hash-verification provides documentation for verifying the installers that only mentions SHA 256.

### Expected Behavior

Those MD5 sums should be replaced by the SHA 256, or some reasoning should be given, and the documentation page updated with directions for checking MD5 sums.

Note the related but distinct issue #12112.

### Steps to Reproduce

Visit the above webpages

##### Anaconda or Miniconda version:

n/a

##### Operating System:

n/a

##### `conda info`

n/a

##### `conda list --show-channel-urls`

n/a

**Comment by cbouss** [comment]
https://docs.conda.io/en/latest/miniconda.html, https://docs.conda.io/en/latest/miniconda.html and https://repo.anaconda.com/miniconda/ are now aligned on using sha256.
