### ISSUE TITLE
ipython >= 7.20 still requires jedi < 0.18 although the incompatibility has been patched.

### ISSUE THREAD

**Issue by maxnoe** [ContinuumIO/anaconda-issues#12359]
The incompatibility of ipython with jedi 0.18 has been fixed in ipython 7.20, see https://github.com/ipython/ipython/issues/12740 and https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#ipython-7-20

### Actual Behavior

conda packages for ipython >= 7.20 still require jedi to be `<0.18`

```
❯ conda search ipython=7.22 --info
Loading channels: done
ipython 7.22.0 py37hb070fc8_0
-----------------------------
file name   : ipython-7.22.0-py37hb070fc8_0.conda
name        : ipython
version     : 7.22.0
build       : py37hb070fc8_0
build number: 0
size        : 992 KB
license     : BSD-3-Clause
subdir      : linux-64
url         : https://repo.anaconda.com/pkgs/main/linux-64/ipython-7.22.0-py37hb070fc8_0.conda
md5         : c42224cd4026a65d7caaf0dff3f1b423
timestamp   : 2021-03-30 15:34:35 UTC
dependencies: 
  - backcall
  - decorator
  - jedi >=0.10,<0.18
  - pexpect >4.3
  - pickleshare
  - prompt-toolkit !=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  - pygments
  - python >=3.7,<3.8.0a0
  - setuptools >=18.5
  - traitlets >=4.2
```

### Expected Behavior

Drop the `<0.18` requirement, see e.g. the conda-forge recipe: 
https://github.com/conda-forge/ipython-feedstock/blob/b48f3b1ed84ff0ec61012eb214dc3c94770a4ff6/recipe/meta.yaml#L33

**Comment by csoja** [comment]
This is fixed in the latest release of ipython to repo.anaconda.com.
