### ISSUE TITLE
Spyder crashes, unable to uninstall/reinstall

### ISSUE THREAD

**Issue by thekev63** [ContinuumIO/anaconda-issues#1235]
I installed Anaconda 3-4.2.0 and to my surprise it came with this great app - Spyder.  So I ran Spyder and loved it but noticed it had an upgrade to version 3.0.1.  So I ran pip and installed the upgrade.  It now crashes on startup.
![image](https://cloud.githubusercontent.com/assets/14210514/20330297/f208b868-ab5a-11e6-8b49-64d7603f0492.png)

I tried the remove command suggested - no luck.  Desperate to get this app working I uninstalled and reinstalled anaconda multiple times, deleted all the folders and registry settings dealing with anaconda and spyder - anything to get the app back.  It still crashes.  No matter what I try, I can't seem to get a working version of Spyder.  Short of reinstalling the OS is there any way to get back to a version that works?  Is there any hope?  TIA

**Comment by ccordoba12** [comment]
You can't mix conda and pip packages. Please reinstall Anaconda and to update Spyder run

    conda update spyder

**Comment by thekev63** [comment]
I tried all that multiple times with no success.  The only way I was able to fix this was to wait for the next version of Anaconda and install that.
