### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ModulusOperandi** [ContinuumIO/anaconda-issues#1238]
When I try to run anaconda-navigator from the terminal on my mac (10.12.1), I get a permission denied error. I've tried looking it up online but haven't found anything similar. Below is the error message:

File "/Users/adamgoldfarb/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 72, in main
    window = run_app(splash)
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 40, in run_app
    window = MainWindow(splash=splash)
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 189, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 125, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/packages.py", line 372, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 358, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/adamgoldfarb/anaconda/lib/python2.7/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/adamgoldfarb/.continuum/anaconda-client: Permission denied

**Comment by ModulusOperandi** [comment]
The issue seems to be related to using the 
`conda clean --all`
command which deletes something that is apparently critical

**Comment by goanpeca** [comment]
@ModulusOperandi not sure how this happened, but the folder

`/Users/adamgoldfarb/.continuum/anaconda-client` seems to have incorrect file permissions so that navigator cannot modify it.

First we can check that this is the case by running navigator from the terminal with sudo

`$ sudo anaconda-navigator`

To see if it runs

Then we will need to change the permissions of that folder (and the files inside) or delete so that when navigator runs the next time (without sudo) the file that gets created has the right permissions.

Pleas let me know how it goes.

**Comment by ModulusOperandi** [comment]
It worked! Thanks for your help.

It worked immediately after using sudo privileges and after modifying the privileges for the listed folder and subfiles, it worked without having to act as superuser.

**Comment by goanpeca** [comment]
Great to hear that @ModulusOperandi

**Comment by lmcook88** [comment]
I am having the same issue as @ModulusOperandi. Running sudo anaconda-navigator works just fine but anaconda-navigator without sudo tells me I don't have permission then crashes. @goanpeca How can I modify privileges so I don't have to open with sudo each time?

**Comment by goanpeca** [comment]
@lmcook88 you can look for /Users/adamgoldfarb/.continuum/anaconda-client and delete the folder or change the permissions there

**Comment by lmcook88** [comment]
I'm sorry, that didn't really help. I am new to python and using MacOSX version 10.10.5. Do I delete the folder from Finder or from terminal? Also, I do not have a folder /Users/laurencook/.continuum/anaconda-client. It is Users/laurencook/anaconda/ - is this the right directory?

**Comment by goanpeca** [comment]
Delete anything everything on this folder

`/Users/laurencook/.continuum`

**Comment by lmcook88** [comment]
That folder does not exist...

**Comment by goanpeca** [comment]
its a hidden folder
open the terminal and do

`$ rm -rf /Users/laurencook/.continuum`

**Comment by lmcook88** [comment]
I got this error... 
`$ rm -rf /Users/laurencook/.continuum` 
rm: /Users/laurencook/.continuum/anaconda-client/config.yaml: Permission denied
rm: /Users/laurencook/.continuum/anaconda-client: Permission denied
rm: /Users/laurencook/.continuum: Directory not empty

`Do I need to do sudo rm -rf /Users/laurencook/.continuum` ?

**Comment by goanpeca** [comment]
yes, oops

**Comment by lmcook88** [comment]
OK. Worked. Thank you! Sorry for all the confusion.

**Comment by fancyg** [comment]
I was just about to open the same issue then I found this. Seems that this is not uncommon.
Thanks~

**Comment by balletboy927** [comment]
Hi, @goanpeca could you help me out? I've working through what @ModulusOperandi and @lmcook88 had trouble with. After I do the `sudo rm -rf /Users/....`, this is what I get when I proceed:
`dyn-129-236-212-68:~ dylanptacek$ anaconda-navigator
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/community.py", line 153, in _json_downloaded
    self.load_content()
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/community.py", line 271, in load_content
    with open(self.saved_content_path, 'w') as f:
IOError: [Errno 13] Permission denied: u'/Users/dylanptacek/.anaconda/navigator/content/content.json'
Abort trap: 6`

Any help would be greatly appreciated.

**Comment by Bhavya223** [comment]
The initial error does not go away even after running the rf rm command.
/Users/bhavya/.continuum/anaconda-client/config.yaml: Permission denied
This is what I see. 

When I try to run the sudo navigator, it says that the navigator cannot be run with root user privileges
