### ISSUE TITLE
Windows builds of Python should up FD_SETSIZE

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#1241]
Default Windows builds of Python allow 512 maximum sockets in select(). This limit can be hit when an application has many connections. This is sometimes hit by users of [distributed](https://distributed.readthedocs.io/en/latest/) on Windows clusters.

Bumping it to a higher value (e.g. 2048) is straightforward and does not adverse consequences. It would be nice to our users if Anaconda builds of Python had such a higher limit.

See upstream issue: https://bugs.python.org/issue28708

**Comment by mrocklin** [comment]
I would like to see this happen.

**Comment by pitrou** [comment]
Also submitted as a PR to conda-forge: https://github.com/conda-forge/python-feedstock/pull/87

**Comment by ilanschnell** [comment]
I've created patches which set `FD_SETSIZE` to 2048 on Windows, which we will apply to Python 2.7 and 3.5 from now on.

**Comment by pitrou** [comment]
Thank you!

**Comment by mrocklin** [comment]
Thank you @ilanschnell !
