### ISSUE TITLE
Anaconda wont launch on MacOS Big Sur 11.3.1

### ISSUE THREAD

**Issue by matsvolmer** [ContinuumIO/anaconda-issues#12438]
### Actual Behavior

 If I click on the anaconda icon, the dot below it will appear, however it won't launch. A right click on the icon yields that the program is not responding. A full reinstall did fix the issue for one launching process. After closing it for the first time after the reinstall I cannot open it again. I have installed anaconda3 via the graphical installer. 

### Steps to Reproduce

Installing the current Anaconda3 version on a 2020 intel i5 Macbook pro.

**Comment by sheetalkalburgi** [comment]
Hi! Could you please include the output from starting anaconda-navigator from a terminal with the --debug option ?
Also, to get to the bottom of the issue, please provide information such as log info, conda info, system info etc.

**Comment by matsvolmer** [comment]
Hi!

launching from the terminal with anaconda-navigator --debug yields the following message:

2021-06-11 10:43:13,921 - INFO logs.setup_logger:122
Setting up logger

and then the terminal just freezes out.

I am not sure about how to find the log info and system info you are looking for (I am very new to this, sorry).

conda info yields the following:

active environment : base
    active env location : /Users/matsvolmer/opt/anaconda3
            shell level : 1
       user config file : /Users/matsvolmer/.condarc
 populated config files : /Users/matsvolmer/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/matsvolmer/opt/anaconda3  (writable)
      conda av data dir : /Users/matsvolmer/opt/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/matsvolmer/opt/anaconda3/pkgs
                          /Users/matsvolmer/.conda/pkgs
       envs directories : /Users/matsvolmer/opt/anaconda3/envs
                          /Users/matsvolmer/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Darwin/20.4.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by matsvolmer** [comment]
Also if you could help me on how to find the required data, this would be very nice. Even after some search on google I haven't found it yed. Thanks!
