### ISSUE TITLE
Current Spyder/Qt combination not compatible with Mac OS 10.11 & Py-2.7; crashes

### ISSUE THREAD

**Issue by tloredo** [ContinuumIO/anaconda-issues#1245]
With a fully updated Anaconda Py-2.7 installation on Mac OS 10.11.6, Spyder crashes during launch. For details, see this Spyder bug thread:

https://github.com/spyder-ide/spyder/issues/2820

Developers there indicate there is a known Qt issue, and that it can be fixed by using Spyder-3 (Anaconda currently uses 2.3.8), which requires pyqt-3, which in turn appears to require Py-3. I cannot easily figure out from Spyder's installation docs whether there is a working option for Py-2.7 Anaconda users.

**Comment by ccordoba12** [comment]
> Anaconda currently uses 2.3.8

This is not true. Anaconda 4.2 comes already with Spyder 3.

> which requires pyqt-3

It requires PyQt5, actually.

> which in turn appears to require Py-3

This is not true either. Spyder works with both Python 2 and 3 without problems.

> I cannot easily figure out from Spyder's installation docs whether there is a working option for Py-2.7

There is. I'd suggest you to uninstall your previous Anaconda installation and download and install this version:

https://repo.continuum.io/archive/Anaconda2-4.2.0-MacOSX-x86_64.pkg

It should work out of the box for Spyder. If you want to install to the latest Spyder version, please run this command (and only this command):

    conda update spyder

**Comment by ijstokes** [comment]
@ccordoba12 uninstalling Anaconda is a big burden for many people if they have successfully been using Anaconda for some time: they have a set of packages that have been installed/updated on top of the base Anaconda version they started with, and possibly also several Conda environments that they are actively using.  Wherever possible we should try to provide users with options so uninstall/re-install is only a last resort.

**Comment by ccordoba12** [comment]
I think the OP wanted to install a given version of Anaconda that came with Spdyer 3 an Python 2. That's why I pointed him to the right installer.

But I'll follow your advice for next time and tell people about conda envs.

----

By the way, I'm closing this issue because of lack of response from the OP.

**Comment by mingwandroid** [comment]
@ijstokes the problem with that is that the old, broken solver (*some people insist it was better back then, they probably didn't stress it too much) pre-conda 4.0 created environments that are not, given the current solver, viable.

I think asking people to make the re-install jump onto the 4 series is an unfortunate necessity in most situations.

**Comment by ijstokes** [comment]
@mingwandroid I think I managed to avoid this and have had the same base Anaconda going for years with judicious use of `conda update conda`, however it is true that I am not a representative Conda user and for sure I've had to revive thoroughly hosed Anaconda instances more than once.

I guess on balance, actually, you've just convinced me: people using Anaconda from pre-4.0 Conda are probably best served by starting from scratch.  We could help them out by writing a short blog post with details like `conda list -e` that might give them a chance at preserving/recreating their Anaconda setup after a fresh install.  Just a thought.  I don't have time to write said blog post...

**Comment by ijstokes** [comment]
And BTW to be clear: I am much happier with the new solver and I've been won over by the grace and patience of @mcg1969 while I said "I don't know if this will ever work" [keeping all dependencies satisfied].

**Comment by tloredo** [comment]
@ccordoba12
> By the way, I'm closing this issue because of lack of response from the OP.

I didn't find the response here (uninstall/reinstall) entirely satisfying. I pursued the problem further on the Anaconda users group, where there is further discussion of the broader underlying issues (but no resolution yet). It appears Spyder is particularly problematic for reasons no one has yet articulated clearly.

Best practices for updating conda, Anaconda?
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/Q50Yl1V2q9g

**Comment by ccordoba12** [comment]
@tloredo, as @mingwandroid said, most probably the best solution for you is to uninstall your previous Anaconda installation and install a new one with conda >= 4.0.

The problem is the old conda dependencies solver was broken and so (it seems) it's failing to resolve the Spyder dependencies correctly. (The fact that you can't install Spyder 3 but only Spyder 2.3.8 points definitely in that direction).

**Comment by tloredo** [comment]
As noted elsewhere, I had 4.0, so that's not the problem. However, something was preventing conda from updating it beyond 4.0, but without any warning/error message, so the only way for me to know I was "stuck" was to visit the Anaconda download web site and see that the current version was later. I've uninstalled/re-installed on one of my machines, but as the other thread noted, the problem is not unique to me, and the long-term solution evidently has yet been identified.

In any case, anyone else with the problem will now see here that it's being discussed elsewhere (and probably only peripherally is connected with Spyder), so you can close the issue again. Thanks for staying with it.
