### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by cmdr** [ContinuumIO/anaconda-issues#1247]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - alabaster ==0.7.9
  - anaconda-client ==1.5.5
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Darwin;16.1.0;Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64;x86_64;i386', 'version': '1.2.1', 'conda': '4.1.4', 'pyqt': '4.11.4', 'language': 'en', 'platform': 'osx-64', 'qt': '4.8.7', 'python': '3.5.1'}

**Comment by goanpeca** [comment]
Hi @cmdr the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers

**Comment by cmdr** [comment]
Hi @goanpeca,

Thank you for the reply!

Best
