### ISSUE TITLE
Navigator initializing stuck

### ISSUE THREAD

**Issue by xuan254** [ContinuumIO/anaconda-issues#1248]
Mac OS X 10.12.1 
I'm reinstalling my Mac OS and tried to install Anaconda for python 2.7. Previously it worked without any problem. I've tried to install for all user or only myself. Same issue, navigator just hangs there, not responding.

Please advise. Attached is a crash report. Thanks.

[Anaconda_Initializing.txt](https://github.com/ContinuumIO/anaconda-issues/files/602336/Anaconda_Initializing.txt)

**Comment by goanpeca** [comment]
@xuan254, thanks for reporting. This problem is fixed and will be available soon in the new version.

**Comment by dawnnao** [comment]
Same problem, but my Python is 3.5, help!
[notResponding.txt](https://github.com/ContinuumIO/anaconda-issues/files/700918/notResponding.txt)

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by LPYjack** [comment]
Mac OS X 10.12.1
My Anaconda navigator stuck on initializing and then just quit without any report, what's wrong with it ? Thanks  @goanpeca

**Comment by rubemd** [comment]
I was having the same problem, but I followed the instructions from goanpeca on another thread:

_You guys can fix it by typing in the terminal

sudo rm -rf ~/.continuum/_

**Comment by LPYjack** [comment]
It still doesn't work:( @rubemd

**Comment by johnnyjmendoza** [comment]
Same for me. Stuck while initializing. Finally goes through but takes approximately 5 minutes. Just wanted you all to know.
