### ISSUE TITLE
Storage Limit Request Habitat Sim 10 GiB total limit

### ISSUE THREAD

**Issue by mathfac** [ContinuumIO/anaconda-issues#12501]
### Project
[`aihabitat / packages / habitat-sim`](https://anaconda.org/aihabitat/habitat-sim/files)
Webpage: https://aihabitat.org/
Repo: https://github.com/facebookresearch/habitat-sim

Does this project already exist?
 Yes

### Reasons for the request
We're developing [Habitat](https://github.com/facebookresearch/habitat-sim), a GPU accelerated 3D simulator for virtual robots training. This limit increase is needed to provide support of released versions for 2 years.

Currently, we are estimating the size as follows:
- 50 MB per wheel x 3 Python versions x 2 platforms (Linux/MacOS) x 2 head/headless x 2 cuda versions "9.2", "10.0" = 1200 MB per release
- Three monthly releases.
- Maintain for 2 years for each version.
So our plan is to use approximately 10 GiB.

It would be great if you could increase the limit size as follows:

Project | Current Limit | Current Size | Requesting Limit
-- | -- | -- | --
habitat_sim | 3 GiB | 3.7 GiB | 10 GiB

Thanks you for your support!

**Comment by csoja** [comment]
Though the published storage maximum on anaconda.org free accounts is 3GB, the actual ceiling is 10GB.  Though we currently do not offer subscription tiers for anaconda.org - this is subject to change in the future.  For requests for more storage or private packages, we generally request you send an email directly to support@anaconda.com.  However, in this case, we'll go ahead and set the maximum explicitly to 10GB as all accounts essentially have that much storage now. Thank you for reaching out and thanks for using anaconda.org for your project!
