### ISSUE TITLE
NOTICE:Do not use the VPN!

### ISSUE THREAD

**Issue by Heart-of-engine** [ContinuumIO/anaconda-issues#12508]
### Actual Behavior

I would like to say that if you use a VPN(called "ladder" in China),there would be an error like this:
"ValueError: check_hostname requires server_hostname"

### Expected Behavior

I wish that you could **write a note in the README text that if Chinese users what to use the navigater, do not use the VPN!!!**

### Steps to Reproduce

I wish that you could write a note in the README text that if Chinese users what to use the navigater, do not use the VPN!!!

##### Operating System:
Windows 10
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by LtDan33** [comment]
Its tough to know what rules apply to which countries, so we want to avoid trying to go into each one (Anaconda is used in every country out there). There are also many different VPNs that might limit traffic in a certain way, and there are some that have no doubt done so successfully. It might be a good idea to add a disclaimer to the docs around that which we can look into
