### ISSUE TITLE
Anaconda Navigator Environment Issues with Cloning

### ISSUE THREAD

**Issue by coolum001** [ContinuumIO/anaconda-issues#1251]
Running Anaconda Navigator 1.3.1, on windows 10 Home, 64 bit.  Installed via Anaconda3 32 bit. Navigator root environment gives anaconda version no. as 4.2.0  

Issue 1.
When I try to Clone the root environment via the Navigator environment panel, the operation fails, but the environment directory is created in my home directory, as follows:
'C:\Users\donc\.conda\envs\root4'
  The Navigator fails to see it.

The error reported is Environment Create Error, Expecting value: line 1 column 1 (char 0)
The ERROR Log reports
2016-11-22 12:03:29,646 - ERROR
    packages._prepare_model_data : 446
    None

Issue 2.
When I use the command line environment clone (with admin priv), the new environment is created in the Programs(x86) directory.
"C:\Program Files (x86)\Anaconda3\envs\root3"
The Navigator can now see the new environment (in this case 'root3')

However, when  I switch to this environment in the Navigator, and try to update (say) pandas to the latest version, I get a permissions failure.

Issue 3.
The cloning of the environment root -> root3 by admin priv command line also introduces a duplicate entry for each of the Windows Start Menu icons.  I now have a 'Anaconda Navigator', and a 'Anaconda Navigator (root3)' entry, for example, and all the other icons (Cloud, Prompt, etc) are also duplicated.

I am happy to supply more information if needed

Note, conda status is:

C:\WINDOWS\system32>conda info --envs
# conda environments:
#
root3                    C:\Program Files (x86)\Anaconda3\envs\root3
root                  *  C:\Program Files (x86)\Anaconda3

C:\WINDOWS\system32>conda info
Current conda install:

               platform : win-32
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files (x86)\Anaconda3  (writable)
    default environment : C:\Program Files (x86)\Anaconda3
       envs directories : C:\Program Files (x86)\Anaconda3\envs
          package cache : C:\Program Files (x86)\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-32/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-32/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

C:\WINDOWS\system32>

**Comment by goanpeca** [comment]
could you update to the latest version and try again?

**Comment by coolum001** [comment]
I assume you mean go to 
https://www.continuum.io/downloads
and download and execute the Python 3.5 Windows 32 bit Installer? [Anaconda 4.2.0 For Windows]

Or some smaller subset [ Anaconda newbie here]?  Thanks, Don

**Comment by goanpeca** [comment]
no I mean openong the command prompt and typing

`conda update qtpy`

**Comment by coolum001** [comment]
Still get the same error on Environment Clone:

I updated conda as below:
C:\WINDOWS\system32>conda update qtpy
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Program Files (x86)\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          488 B
    conda-4.2.12               |           py35_0         441 KB
    ------------------------------------------------------------
                                           Total:         442 KB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

The following packages will be UPDATED:

    conda:     4.2.9-py35_0 --> 4.2.12-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00  81.25 kB/s
conda-4.2.12-p 100% |###############################| Time: 0:00:00   1.56 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

Current conda status:

C:\WINDOWS\system32>conda info
Current conda install:

               platform : win-32
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files (x86)\Anaconda3  (writable)
    default environment : C:\Program Files (x86)\Anaconda3
       envs directories : C:\Program Files (x86)\Anaconda3\envs
          package cache : C:\Program Files (x86)\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False


C:\WINDOWS\system32>

Still get the same error on Environment Clone:
Expecting value: line 1 column 1 (char 0)

Error log says:
2016-11-22 13:04:10,747 - ERROR
    packages._prepare_model_data : 446
    None

I still get new Start Menu Icons for each environment (even the ones that fail)
e.g. 'Anaconda Navigator', 'Anaconda Navigator (root3)', etc

**Comment by goanpeca** [comment]
`conda update anaconda-navigator` ?

**Comment by coolum001** [comment]
Still get 'Expecting value: line 1 column 1 (char 0)', on environment clone attempt

2016-11-22 13:55:53,255 - ERROR
    packages._prepare_model_data : 446
    None

Navigator at 1.3.2


Note that Jupyter notebooks (initiated from the Navigator) see the environments created in user directory, but Anaconda Navigator appears to only sees the system level environments.  Note also I have managed created an environment with the same name ('root3') in both the systems level and local user directories.

Should I be adding or defining additional entries in whatever holds the 
'envs directories :'  list?

Thanks, Don

Update script as below:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>conda update anaconda-navigator
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Program Files (x86)\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-custom            |           py35_0          13 KB
    anaconda-navigator-1.3.2   |           py35_0         3.1 MB
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following packages will be UPDATED:

    anaconda:           4.2.0-np111py35_0 --> custom-py35_0
    anaconda-navigator: 1.3.1-py35_0      --> 1.3.2-py35_0

Proceed ([y]/n)? y

Fetching packages ...
anaconda-custo 100% |###############################| Time: 0:00:00 372.29 kB/s
anaconda-navig 100% |###############################| Time: 0:00:01   1.76 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

C:\WINDOWS\system32>

C:\WINDOWS\system32>conda info
Current conda install:

               platform : win-32
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files (x86)\Anaconda3  (writable)
    default environment : C:\Program Files (x86)\Anaconda3
       envs directories : C:\Program Files (x86)\Anaconda3\envs
          package cache : C:\Program Files (x86)\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False


C:\WINDOWS\system32>

**Comment by goanpeca** [comment]
@coolum001 I think there is indeed an issue with conda cloning the root environment (@k

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
