### ISSUE TITLE
Anaconda navigator error/ The system cannot find the path specified.

### ISSUE THREAD

**Issue by BhuvanJoshi007** [ContinuumIO/anaconda-issues#12510]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Insufficient information is included in this ticket.  Closing as the requested template information is blank.
