### ISSUE TITLE
How to fix?? Prefix “100” in front of all Anaconda packages

### ISSUE THREAD

**Issue by eugenylitvinov** [ContinuumIO/anaconda-issues#12513]
There is a prefix of "100" in front of all my python packages in anaconda navigator. I believe this is making it difficult for applications to use these libraries. For example, I cannot open Spyder.

Packages will be listed as "100 numpy" rather than simply "numpy"

I updated a bulk of packages using both Navigator. Then Suddenly just about everything with my python installation started having problems. After restart, I have a prefix of 100 in front of all package names.

I would expect the packages to read "numpy" rather than "100 numpy" etc.

I've tried to undo:
conda list --revisions
conda install --revision #

but it doesn't help.

**Comment by eugenylitvinov** [comment]
After all I refused to reinstall all and just go down through --revisions until everything come back to normal. Thnx god!

**Comment by rvkmar** [comment]
Solution:
1. Remove all channels except defaults in the root(base) environment.
2. Open Terminal in conda and enter "conda upgrade --all" and select yes.
3. Close  Anaconda and open again and everything will be normal.

**Comment by YNZL0702** [comment]
> After all I refused to reinstall all and just go down through --revisions until everything come back to normal. Thnx god!

I meet the same problem.  I tried  "conda install  --revision  # " many times, it doesn't work.
