### ISSUE TITLE
werkzeug has lost debug/shared folders in conda packages between 0.11.8 and 0.11.9

### ISSUE THREAD

**Issue by rs2** [ContinuumIO/anaconda-issues#1252]
Using `conda install`.

Compare https://repo.continuum.io/pkgs/free/win-32/werkzeug-0.11.8-py35_0.tar.bz2
to https://repo.continuum.io/pkgs/free/win-32/werkzeug-0.11.9-py35_0.tar.bz2

Side effect: unable to debug `flask` apps using 0.11.9 or newer.

I'm able to create a valid `conda` package locally.

**Comment by ilanschnell** [comment]
The reason for this was an upstream change in the `setup.py` file, which not only includes the additional files correctly when `setuptools` is used in the install process.  I've fixed this issue by adding `setuptools` as a build dependency, and rebuild the latest version (0.11.11).
