### ISSUE TITLE
Update pandas in pkgs/main to 1.3.0

### ISSUE THREAD

**Issue by Dr-Irv** [ContinuumIO/anaconda-issues#12527]
### Actual Behavior

pandas 1.3.0 is released, and pkgs/main goes up to pandas 1.2.5

### Expected Behavior

pandas 1.3.0 should be available on the pkgs/main channel

**Comment by skupr-anaconda** [comment]
Now `pandas 1.3.0 `is available on the pkgs/main channel (https://anaconda.org/main/pandas, https://anaconda.org/anaconda/pandas).
Try `conda search pandas` or `conda install pandas`

**Comment by Dr-Irv** [comment]
> Now `pandas 1.3.0 `is available on the pkgs/main channel (https://anaconda.org/main/pandas, https://anaconda.org/anaconda/pandas).
> Try `conda search pandas` or `conda install pandas`

Thanks!

For future pandas releases, how can we accelerate the availability of pandas on the main channel?  Create an issue here?

**Comment by skupr-anaconda** [comment]
We were investigating the issues on https://github.com/pandas-dev/pandas/issues so it causes the later availability on the main channel

**Comment by csoja** [comment]
Creating an issue here is a good way to highlight any issues with the packages in repo.anaconda.com - including if there is one that needs to be updated.  Thanks for the initial report - and please let us know if you run into any problems.
