### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by maohuaxie** [ContinuumIO/anaconda-issues#1254]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - pydot-ng ==1.0.0.15
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'platform': 'win-64', 'language': 'en_US', 'version': '1.2.1', 'conda': '4.1.6', 'python': '3.5.2', 'pyqt': '4.11.4', 'qt': '4.8.7'}

**Comment by goanpeca** [comment]
Hi @maohuaxie the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
