### ISSUE TITLE
QTConsole launches second Python window after kernel install for nteract (Windows)

### ISSUE THREAD

**Issue by schodge** [ContinuumIO/anaconda-issues#1256]
On Windows 7.

I installed nteract, which doesn't recognize Anaconda kernels, so per https://github.com/nteract/nteract/issues/1030 I did `python -m ipykernel install --user`  . This made nteract work, but now when I launch QTConsole I get a secondary Python window opening.

![image](https://cloud.githubusercontent.com/assets/4616123/20578033/12c259f4-b17a-11e6-8169-2fc23176718e.png)

If I close it, I get the Kernel Died, restarting message shown and it comes back.

Is there anyway to get this behavior to revert, and, preferably, not break nteract in the process?

Apologies if this isn't the best issue board for this, wasn't sure exactly where it should go.

**Comment by ccordoba12** [comment]
We solved this in Spyder by using `pythonw.exe` instead of `python.exe` to start kernels.

@minrk, could the same be done in `qtconsole`?

**Comment by minrk** [comment]
It can definitely be done, though perhaps the place for it is in ipykernel itself. If it's true that IPython kernels should *always* be started with pythonw on Windows, then it should be an easy fix. If it's less than always, then it's a harder question to answer.

**Comment by ccordoba12** [comment]
> If it's true that IPython kernels should always be started with pythonw on Windows

I don't see why not. @takluyver, any thoughts about this?

**Comment by takluyver** [comment]
If you're running a Jupyter frontend (e.g. the notebook) from a command prompt, then you probably want to start kernels with `python` so that the kernel can write output to the console (e.g. errors while it's starting). With `pythonw`, the kernel cannot use stdout/stderr at all, as far as I know.

This will hopefully be mitigated once we do the kernel nanny thing and provide an explicit destination for kernel logging.

**Comment by ccordoba12** [comment]
> This will hopefully be mitigated once we do the kernel nanny thing

When is this going to happen? We need this for Spyder to let users interrupt and restart kernels in remote servers.

**Comment by ccordoba12** [comment]
@schodge, I'm closing this one because this is an upstream problem (i.e. not something that Continuum can address).

**Comment by schodge** [comment]
Thanks for looking at this. Do you know, if I uninstall the kernel with pip if QTConsole will revert to previous behavior? Then could I create a new conda env and pip install the kernel from there to make nteract work without popping up the window for QTConsole?

Sorry for the question and not just trying it, but I don't want to do something that'll require a complete removal and reinstall to fix...
