### ISSUE TITLE
Jupyter with R kernen on openSuse

### ISSUE THREAD

**Issue by DerJayDee** [ContinuumIO/anaconda-issues#1257]
Every time I try to run something in the R kernel in a jupyter notebook the kernel crashes. Even if the operation is only 1+1.

The following error is thrown:
```Fehler in ok_device(filename, ...) : X11 Modul kann nicht geladen werden
Ruft auf: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
Zusätzlich: Warnmeldung:
In ok_device(filename, ...) :
  kann shared object '/home/adminprj/anaconda3/lib/R/modules//R_X11.so' nicht laden:
  libXdmcp.so.6: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Ausführung angehalten
```
Approximated error message in english:
```Error in ok_device(filename, ...) : X11 unable to load module
Call: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
Additional: Warning:
In ok_device(filename, ...) :
  unable to load shared object '/home/adminprj/anaconda3/lib/R/modules//R_X11.so':
  libXdmcp.so.6: cannot open shared object file: file or directory not found
Interrupted
```

I installed Jupiter and R like this:
```wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
bash Anaconda3-4.2.0-Linux-x86_64.sh
anaconda3/bin/conda install -c r r-essentials```

**Comment by ccordoba12** [comment]
You need to install the package that contains the `libXdmcp.so.6` library then.

**Comment by DerJayDee** [comment]
Do I need to install it for the os (with zypper) or for my conda environment?
And why is it not installed via dependencies?

**Comment by mingwandroid** [comment]
You need to install it via zypper.

It is not installed through dependencies because it is a system component which is too specific for each Linux distribution for us to be able to build a generic one.

It is part of X windows.

**Comment by DerJayDee** [comment]
Thank you, solved this problem for me :-)
