### ISSUE TITLE
QXcbConnection: Could not connect to display 

### ISSUE THREAD

**Issue by pacosoplas** [ContinuumIO/anaconda-issues#1259]
From centos 6.8 the cloudera navigator doesnt start:

(/root/anaconda3) [root@ana01 ~]# anaconda-navigator 
QXcbConnection: Could not connect to display 
Abortado

**Comment by ccordoba12** [comment]
Are you able to start other graphical applications as root? Why not use a regular account instead?

**Comment by goanpeca** [comment]
@pacosoplas any comments?

**Comment by ccordoba12** [comment]
This is probably related to the OP trying to start Navigator using his root account and not setting DISPLAY before doing it.

**Comment by ccordoba12** [comment]
I think this doesn't deserve further investigation, given lack of response and that the error message is quite clear.

So I'm closing this one.

**Comment by pandeysudhanshu** [comment]
It will not work , if you will do it using root user .

**Comment by ccordoba12** [comment]
Of course it won't. Please google on how to start graphical applications as root on Linux.
