### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Luis411** [ContinuumIO/anaconda-issues#1260]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - python 3.5*
  - vispy ==0.4.0.106.gf8a69d0
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel', 'language': 'es_MX', 'conda': '4.1.11', 'version': '1.2.1', 'python': '3.5.2', 'platform': 'win-64', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Hi @Luis411 the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
