### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Philip619** [ContinuumIO/anaconda-issues#1262]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda ==4.2.0
  - anaconda-client ==1.5.5
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'zh_HK', 'python': '2.7.12', 'os': 'Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Hi @Philip619 the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
