### ISSUE TITLE
Wrong version of Bokeh listed in Anaconda 2020.02

### ISSUE THREAD

**Issue by SysEngDan** [ContinuumIO/anaconda-issues#12631]
We use 2020.02 intensively. Today, we noticed that the [website](https://docs.anaconda.com/anaconda/packages/old-pkg-lists/2020.02/py3.8_linux-64/) lists v2.1.1 as being included, however, the latest [download](https://repo.anaconda.com/archive/) has v1.4.0, which is the version we've been using as well with 2020.02.

I believe this is an error in the documentation.

**Comment by SysEngDan** [comment]
Additionally, it makes me wonder how many other packages have the wrong version listed. Can someone please check and confirm.

**Comment by LtDan33** [comment]
Hey there Daniel!

2021.05 is our latest, but even on older versions you should be able to pull down version of Bokeh more recent than 1.4.0. There might be some dependencies that you have that are requiring that specific version of Bokeh. When you create an environment Conda will try and pull down the latest that it can based on the packages you are trying to install. 

Doing a `conda search 'Bokeh[channel=pkgs/main]'` will show what versions are available from the main channel, and there might be others available on other channels. Depending on what version of Python you have, up to `2.3.3` is available

Can you give us a few more details? Where are you seeing the version of Bokeh is `v1.4.0`? Also the following could be helpful too:


##### Operating System:

##### `conda info`


<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`


<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by LtDan33** [comment]
Digging more into it, seems like there was an issue with the script that we used to generate those packages versions, so you are right that it is incorrect. Thanks for bringing this up!

**Comment by csoja** [comment]
Thank you for highlighting this issue in the documentation!  All of the 2020.2 package tables have been fixed and updated.
