### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by BoulderKiwi** [ContinuumIO/anaconda-issues#1264]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - pandas ==0.18.0
  - xgboost -> numpy 1.9*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.13', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.1.0;Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64;x86_64;i386', 'pyqt': u'5.6.0'}

**Comment by goanpeca** [comment]
Hi @BoulderKiwi the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers

**Comment by BoulderKiwi** [comment]
Will downloading the latest version of navigator fix the issue? 

I have trouble understanding what dependencies are currently in conflict, or more accurately, how to fix them without making things worse.

**Comment by goanpeca** [comment]
>Will downloading the latest version of navigator fix the issue?

Hi @BoulderKiwi, no as there is no issue to be solved. 

>I have trouble understanding what dependencies are currently in conflict, or more accurately, how to fix them without making things worse.

Please read the documentation at http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable
