### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jona2950** [ContinuumIO/anaconda-issues#1265]
The following errors occured:

RuntimeError:
Could not find URL: https://pypi.python.org/simple/osx-64/

{'version': '1.2.1', 'qt': '4.8.7', 'language': 'en', 'conda': '4.1.6', 'python': '3.5.2', 'pyqt': '4.11.4', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64;x86_64;i386', 'platform': 'osx-64'}

**Comment by goanpeca** [comment]
Hi @jona2950

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
