### ISSUE TITLE
Anaconda Navigator for Linux x86-64 hangs at "loading applications"

### ISSUE THREAD

**Issue by francisregan1** [ContinuumIO/anaconda-issues#12653]
Update: I read the documentation and solved my problem by installing the PyQt5 dependencies as discussed there.

**I have a similar issue: Anaconda Navigator for Linux x86-64 hangs at "loading applications".**
_(Apologies: I'm so far unable to pipe the full ```--verbose --debug``` output to a file due to shortcomings in Linux knowledge)_

From what I can tell, conda_api.py hits a point shortly after the start of "loading applications" where it loops between these two lines seven times and then hangs:
```
2021-10-07 07:17:13,626 - DEBUG conda_api.environment_exists:1402
(None, '/bin/anaconda3')

2021-10-07 07:17:13,626 - DEBUG conda_api.linked:604
/bin/anaconda3
```

Ordinarily I would simply use Anaconda on Windows; I'm unfortunately stuck with a Jupyter notebook which uses a C library that does not run on Windows. So I spun up Ubuntu on WSL and am working through an Anaconda install there.

I have tried all of the solutions mentioned previously in the thread— disconnecting from the internet; updating Anaconda; doing a clean uninstall/reinstall. I have also edited the conda_api.py file to change the ```yaml.full_load(f)``` call with no change in the result.

The file structure of my anaconda3 directory seems to be different from what I've read about in this thread and elsewhere: my _/bin/anaconda3/lib/_ has no _site-packages_ directory; instead, the conda_api.py file I have found is located in _/bin/anaconda3/pkgs/anaconda-navigator/2.1.0-py38h06a4308_0/lib/python3.8/site-packages/anaconda_navigator/api/_.

Within that conda_api.py file, line 1364 does not use ```yaml.full_load(f)```, but that method does appear on lines 1287 and 1297. I have changed both to use ```yaml.safe_load(f)```.

I am running Ubuntu 20.04.3 LTS on Windows Subsystem for Linux; Windows 11 Pro build 22471.1000.

**Conda info:**
```
     active environment : base
    active env location : /bin/anaconda3
            shell level : 1
       user config file : /home/franc/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __linux=5.10.43.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /bin/anaconda3  (read only)
      conda av data dir : /bin/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /bin/anaconda3/pkgs
                          /home/franc/.conda/pkgs
       envs directories : /home/franc/.conda/envs
                          /bin/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.8 Linux/5.10.43.3-microsoft-standard-WSL2 ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

_Originally posted by @francisregan1 in https://github.com/ContinuumIO/anaconda-issues/issues/10461#issuecomment-937515533_

**Comment by overFLOw721** [comment]
> Update: I read the documentation and solved my problem by installing the PyQt5 dependencies as discussed there.

where you found the documentation for installing PyQt5 dependencies?

i am discovering a pretty similar problem. working on: Ubuntu 20.04.3 LTS x86_64

launching anaconda-navigator via terminal will show an empty splash screen. i noticed this while moving some windows there is the little splash screen in the middle of my screen but nothing happens even after ~15 min.

I found a workaround in another thread:
Disable Wifi
start anaconda-navigator
Enable Wifi

this worked for me so far to start anaconda-navigator in a few seconds. but do i have to do this every time?
