### ISSUE TITLE
conda package for python 3.10 support

### ISSUE THREAD

**Issue by cdeepali** [ContinuumIO/anaconda-issues#12669]
Would it be possible to provide a new conda release for Python `3.10` support that includes the fix - https://github.com/conda/conda/pull/10970 for the issue https://github.com/conda/conda/issues/10969

**Comment by cdeepali** [comment]
By when do we expect a conda release with `python 3.10` fix?

**Comment by chenghlee** [comment]
We are working [fixing the recipe](https://github.com/AnacondaRecipes/conda-feedstock/pull/4) and should release it to defaults later today.

**Comment by cdeepali** [comment]
Thanks for providing conda release for this.
