### ISSUE TITLE
OpenGL/PyQt error: "QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled"

### ISSUE THREAD

**Issue by kelvinlawson** [ContinuumIO/anaconda-issues#1267]
Seen in Ubuntu 15 and 16. Not seen in Windows 7.

Running a very basic PyQt/PyOpenGL script does not work within Conda:

> "QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled"

But works fine when using Python from standard Ubuntu package manager.

Attached a simple script to reproduce the issue:
[conda-bug.zip](https://github.com/ContinuumIO/anaconda-issues/files/619005/conda-bug.zip)

```
conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/kelvin/miniconda2  (writable)
    default environment : /home/kelvin/miniconda2/envs/cv
       envs directories : /home/kelvin/miniconda2/envs
          package cache : /home/kelvin/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

conda list
# packages in environment at /home/kelvin/miniconda2/envs/cv:
#
cairo                     1.12.18                       6  
cycler                    0.10.0                   py27_0  
dbus                      1.10.10                       0  
docutils                  0.12                      <pip>
easygui                   0.98.0                    <pip>
expat                     2.1.0                         0  
fontconfig                2.11.1                        6  
freeglut                  2.8.1                         0  
freetype                  2.5.5                         1  
glib                      2.43.0                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
icu                       54.1                          0  
jpeg                      8d                            2  
libffi                    3.2.1                         0  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libxcb                    1.12                          1  
libxml2                   2.9.2                         0  
matplotlib                1.5.3               np111py27_1  
mkl                       11.3.3                        0  
mpmath                    0.19                     py27_1  
numpy                     1.11.2                   py27_0  
openssl                   1.0.2j                        0  
pandas                    0.19.1              np111py27_0  
pip                       9.0.1                    py27_0  
pixman                    0.32.6                        0  
pycairo                   1.10.0                   py27_0  
pyopengl                  3.1.1a1             np111py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_0  
python                    2.7.12                        1  
python-dateutil           2.6.0                    py27_0  
pytz                      2016.7                   py27_0  
qt                        5.6.0                         1  
readline                  6.2                           2  
scikit-kinematics         0.3.7                     <pip>
scipy                     0.18.1              np111py27_0  
setuptools                27.2.0                   py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
sympy                     1.0                      py27_0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3  

```

**Comment by mingwandroid** [comment]
This is tricky. The problem is that we support very old Linux (CentOS 5.11) and that doesn't have enough OpenGL support for Qt. I'm not sure what I can do in the short term to address this.

**Comment by ccordoba12** [comment]
@kelvinlawson, we'll move to CentOS 6 next year, after CentOS 5 ends its life cycle. Until then, as @mingwandroid points out, we are not able to address this issue.

**Comment by rossant** [comment]
I also have this problem on Ubuntu 16.04 since I upgraded PyQt from v4 to v5

```
     matplotlib  {1.5.1 -> 1.5.3}
     pyqt  {4.11.4 -> 5.6.0}
     qt  {4.8.7 -> 5.6.2}
     qtconsole  {4.2.1 -> 4.2.1}
    +dbus-1.10.10
    +expat-2.1.0
    +gst-plugins-base-1.8.0
    +gstreamer-1.8.0
    +icu-54.1
    +jpeg-8d
    +libgcc-5.2.0
    +libxcb-1.12
```

Is there any work-around? Or any ETA for an update that would fix this? Thanks.

**Comment by ccordoba12** [comment]
> Or any ETA for an update that would fix this?

Q2 or Q3 of 2017, we haven't decided that yet.

**Comment by astrofrog** [comment]
Just FYI I'm also running into this issue when packaging glueviz

**Comment by dragly** [comment]
A workaround is to install PyQt from pip. However, this may lead to a segfault, which probably is caused by different versions of the Python libraries used by PyQt and installed by Anaconda. In that case, a specific version of PyQt and pip needs to be installed. I found that the following works in our case, with Python 3.5:
```
pip install pyqt5==5.7 sip==4.18
```

**Comment by tymokvo** [comment]
Had the same error from pyqtgraph but @dragly 's solution is working for me on Ubuntu14.04 with Python 3.5 and PyQt5. Thanks!

**Comment by toinsson** [comment]
@dragly 's solution is working for me: ubuntu 16.04, pyqt5 and python 3.6.1

    pip install pyqt5==5.7.1 sip==4.19

**Comment by lromor** [comment]
pyqt5==5.7 sip==4.18 are not available anymore now. And the version after do segfaults. Any solutions?

**Comment by mingwandroid** [comment]
Do you have `LD_LIBRARY_PATH` set by any chance?

**Comment by lromor** [comment]
no, just an ld conf.

**Comment by dzhoshkun** [comment]
I'm experiencing this problem when trying to create a VisPy canvas under [Xvfb](https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml). I need to use Xvfb to be able to do headless CI testing on our test server.

My system configuration:
1. Ubuntu 16.04 LTS (4.4.0-89-generic)
1. `virtualenv -p $(which python3) venv-py3`
1. `pip3 install pyqt5`
1. `pip3 install git+https://github.com/vispy/vispy.git`
1. `/usr/bin/Xvfb :99 -screen 0 1400x900x24 +extension GLX -noreset &`

I'm trying to run this example: http://ipython-books.github.io/featured-06/ (saved as `ipvp06.py`).

Executing `python3 ipvp06.py` works fine.

But when I try to run it using `DISPLAY=:99.0 python3 ipvp06.py`, I get the `QXcbIntegration` error (pasting the whole stack trace in case this is helpful):

```
INFO: Could not import backend "PyQt4":
No module named 'PyQt4'
WARNING: QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Traceback (most recent call last):
  File "ipvp06.py", line 4, in <module>
    c = app.Canvas(keys='interactive')
  File "/home/dzhoshkun/ws/venvs/lv/venv-py3/lib/python3.5/site-packages/vispy/app/canvas.py", line 205, in __init__
    self.create_native()
  File "/home/dzhoshkun/ws/venvs/lv/venv-py3/lib/python3.5/site-packages/vispy/app/canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/dzhoshkun/ws/venvs/lv/venv-py3/lib/python3.5/site-packages/vispy/app/backends/_qt.py", line 267, in __init__
    self._init_specific(p, kwargs)
  File "/home/dzhoshkun/ws/venvs/lv/venv-py3/lib/python3.5/site-packages/vispy/app/backends/_qt.py", line 664, in _init_specific
    raise RuntimeError('context could not be created')
RuntimeError: context could not be created
(venv-py3) 
```

Any ideas?

**Comment by ccordoba12** [comment]
@dzhoshkun, it seems you're not using Anaconda, so please ask for help in the Vispy repo.

**Comment by speleo3** [comment]
[Anaconda 4.4 dropped support for CentOS 5](https://docs.continuum.io/anaconda/release-notes), which I expected will solve this issue, but it didn't. So what's the problem now?

Installing **qt** from **conda-forge** works for me. More specifically, this is currently sufficient:
`conda install --force -c conda-forge icu qt`

Looking at the **qt** recipes, [anaconda](https://github.com/ContinuumIO/anaconda-recipes/tree/master/qt) and [conda-forge](https://github.com/conda-forge/qt-feedstock/tree/master/recipe) seem to apply the same patches for Linux, and **build.sh** is also identical. Where's the difference?

**Comment by mingwandroid** [comment]
We have not yet released a Qt built on against CentOS6. It's coming though.

**Comment by astrofrog** [comment]
@mingwandroid - sorry to bug you, but just wanted to check whether the new builds released a couple of weeks ago address this?

**Comment by mingwandroid** [comment]
I tested with https://raw.githubusercontent.com/baoboa/pyqt5/master/examples/opengl/hellogl.py on CentOS6 on a VM and it worked well. @kelvinlawson's test app crashed, but I believe it contains some bugs. Here's a corrected version (note, it only displays for a frame but that's the behaviour as programmed AFAICT).

```
#!/usr/bin/env python

from PyQt5 import QtGui, QtWidgets, uic
from PyQt5.QtWidgets import (QFileDialog, QOpenGLWidget)
from PyQt5.QtCore import QThread


class WfWidget(QOpenGLWidget):
    def __init__(self, parent = None):
        super(WfWidget, self).__init__(parent)

    def paintGL(self):
        self.gl.glColor3f(0.0, 0.0, 1.0)
        self.gl.glRectf(-5, -5, 5, 5)
        self.gl.glColor3f(1.0, 0.0, 0.0)
        self.gl.glBegin(self.gl.GL_LINES)
        self.gl.glVertex3f(0, 0, 0)
        self.gl.glVertex3f(20, 20, 0)
        self.gl.glEnd()

    def resizeGL(self, w, h):
        self.gl.glMatrixMode(self.gl.GL_PROJECTION)
        self.gl.glLoadIdentity()
        self.gl.glOrtho(-50, 50, -50, 50, -50.0, 50.0)
        self.gl.glViewport(0, 0, w, h)

    def initializeGL(self):
        self.gl = self.context().versionFunctions()
        self.gl.initializeOpenGLFunctions()

        self.gl.glClearColor(0.0, 0.0, 0.0, 1.0)
        self.gl.glClear(self.gl.GL_COLOR_BUFFER_BIT)

if __name__ == '__main__':
    app = QtWidgets.QApplication(["Winfred's PyQt OpenGL"])
    widget = WfWidget()
    widget.show()
```

**Comment by mingwandroid** [comment]
While I'm here:
> Looking at the qt recipes, anaconda and conda-forge seem to apply the same patches for Linux, and build.sh is also identical. Where's the difference?

There's more to software than the recipes. In particular the system they are built on is crucial to things like the level of OpenGL or EGL support.

**Comment by mingwandroid** [comment]
Closed due to testing that it works for myself since AD 5.0
