### ISSUE TITLE
R kernel in Jupyter keeps dying

### ISSUE THREAD

**Issue by dthboyd** [ContinuumIO/anaconda-issues#1268]
Creating new notebook in 
[I 15:35:49.247 NotebookApp] Kernel started: ebfa1f01-cb7b-432e-a109-8f87c2253f49
dyld: Library not loaded: @rpath/libicuuc.54.dylib
  Referenced from: /Users/davidboyd/anaconda/lib/R/bin/exec/../../..//R/lib/libR.dylib
  Reason: image not found

Please Help

**Comment by mingwandroid** [comment]
From Terminal run:
`/Users/davidboyd/anaconda/bin/activate root`

Then show the output of `conda info` and the output from `conda list --show-channel-urls`

**Comment by dthboyd** [comment]
Error: activate must be sourced. Run 'source activate envname'
instead of 'activate envname'.
david-boyds-iMac:pkgs davidboyd$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : /Users/davidboyd/anaconda  (writable)
    default environment : /Users/davidboyd/anaconda
       envs directories : /Users/davidboyd/anaconda/envs
          package cache : /Users/davidboyd/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/davidboyd/.condarc
           offline mode : False

packages in environment at /Users/davidboyd/anaconda:
#
_nb_ext_conf              0.2.0                    py35_0    defaults
alabaster                 0.7.8                    py35_0    defaults
anaconda                  custom                   py35_0    defaults
anaconda-client           1.4.0                    py35_0    defaults
anaconda-navigator        1.2.1                    py35_0    defaults
aplus                     0.11.0                   py35_0    conda-forge
appnope                   0.1.0                    py35_0    defaults
appscript                 1.0.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astropy                   1.2.1               np111py35_0    defaults
babel                     2.3.3                    py35_0    defaults
backports                 1.0                      py35_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py35_0    conda-forge
beautifulsoup4            4.4.1                    py35_0    defaults
bitarray                  0.8.1                    py35_0    defaults
blas                      1.1                    openblas    conda-forge
blaze                     0.10.1                   py35_0    defaults
bokeh                     0.12.0                   py35_0    defaults
boto                      2.40.0                   py35_0    defaults
bottlechest               0.7.1                    py35_0    defaults
bottleneck                1.1.0               np111py35_0    defaults
cachetools                2.0.0                    py35_0    conda-forge
cffi                      1.6.0                    py35_0    defaults
chardet                   2.3.0                    py35_0    defaults
chest                     0.2.3                    py35_0    defaults
click                     6.6                      py35_0    defaults
cloudpickle               0.2.1                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
conda                     4.2.13                   py35_0    conda-forge
conda-build               1.21.3                   py35_0    defaults
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py35_0    defaults
contextlib2               0.5.3                    py35_0    defaults
cryptography              1.4                      py35_0    defaults
curl                      7.49.0                        0    defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.24                     py35_0    defaults
cytoolz                   0.8.0                    py35_0    defaults
dask                      0.10.0                   py35_0    defaults
datashape                 0.5.2                    py35_0    defaults
decorator                 4.0.10                   py35_0    defaults
dill                      0.2.5                    py35_0    defaults
docutils                  0.12                     py35_2    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
fastcache                 1.0.2                    py35_1    defaults
findspark                 1.1.0                     <pip>
flask                     0.11.1                   py35_0    defaults
flask-cors                2.1.2                    py35_0    defaults
freetype                  2.5.5                         1    defaults
future                    0.15.2                   py35_0    conda-forge
futures                   3.0.3                    py35_0    defaults
get_terminal_size         1.0.0                    py35_0    defaults
gevent                    1.1.1                    py35_0    defaults
glueviz                   0.8.2                    py35_0    defaults
greenlet                  0.4.10                   py35_0    defaults
gsl                       1.16                          2    r
h5py                      2.6.0               np111py35_1    defaults
hdf5                      1.8.16                        0    defaults
heapdict                  1.0.0                    py35_1    defaults
icu                       56.1                          4    conda-forge
idna                      2.1                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
ipykernel                 4.3.1                    py35_0    defaults
ipyparallel               5.2.0                     <pip>
ipython                   4.2.0                    py35_1    defaults
ipython-notebook          4.0.4                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                4.1.1                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py35_1    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.8                      py35_1    defaults
joblib                    0.9.4                    py35_0    defaults
jpeg                      8d                            1    defaults
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter_client            4.3.0                    py35_0    defaults
jupyter_console           4.1.1                    py35_0    defaults
jupyter_core              4.1.0                    py35_0    defaults
libdynd                   0.7.2                         0    defaults
libgcc                    4.8.5                         1    r
libgfortran               3.0.0                         0    conda-forge
libpng                    1.6.22                        0    defaults
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
llvmlite                  0.11.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.6.0                    py35_0    defaults
markupsafe                0.23                     py35_2    defaults
matplotlib                1.5.1               np111py35_0    defaults
mistune                   0.7.2                    py35_1    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py35_2    defaults
mock                      2.0.0                    py35_0    conda-forge
mpmath                    0.19                     py35_1    defaults
multipledispatch          0.4.8                    py35_0    defaults
nb_anacondacloud          1.1.0                    py35_0    defaults
nb_conda                  1.1.0                    py35_0    defaults
nb_conda_kernels          1.0.3                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.0.1                    py35_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
ncurses                   5.9                           8    r
networkx                  1.11                     py35_0    defaults
nltk                      3.2.1                    py35_0    defaults
nose                      1.3.7                    py35_1    defaults
notebook                  4.2.1                    py35_0    defaults
numba                     0.26.0              np111py35_0    defaults
numexpr                   2.6.0               np111py35_0    defaults
numpy                     1.11.2          py35_blas_openblas_201  [blas_openblas]  conda-forge
odo                       0.5.0                    py35_1    defaults
openblas                  0.2.18                        6    conda-forge
openpyxl                  2.3.2                    py35_0    defaults
openssl                   1.0.2h                        1    defaults
orange-app                1.0.1                    py35_0    defaults
orange3                   3.3.6                    py35_0    defaults
pandas                    0.18.1              np111py35_0    defaults
pandas-datareader         0.2.1                    py35_0    anaconda
partd                     0.3.4                    py35_0    defaults
path.py                   8.2.1                    py35_0    defaults
pathlib2                  2.1.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pbr                       1.10.0                   py35_0    conda-forge
pcre                      8.38                          1    conda-forge
pep8                      1.7.0                    py35_0    defaults
pexpect                   4.0.1                    py35_0    defaults
pickleshare               0.7.2                    py35_0    defaults
pillow                    3.2.0                    py35_1    defaults
pip                       8.1.2                    py35_0    defaults
pip                       9.0.1                     <pip>
ply                       3.8                      py35_0    defaults
progressbar2              3.10.1                   py35_0    conda-forge
prompt_toolkit            1.0.4                    py35_0    conda-forge
protobuf                  3.0.0b2                  py35_0    conda-forge
psutil                    4.3.0                    py35_0    defaults
ptyprocess                0.5.1                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.14                     py35_1    defaults
pycrypto                  2.6.1                    py35_4    defaults
pycurl                    7.43.0                   py35_0    defaults
pyflakes                  1.2.3                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pyopengl                  3.1.0                    py35_0    conda-forge
pyopenssl                 0.16.0                   py35_0    defaults
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      4.11.4                   py35_3    defaults
pyqtgraph                 0.9.10                   py35_1    defaults
pytables                  3.2.2               np111py35_4    defaults
pytest                    2.9.2                    py35_0    defaults
pytest-runner             2.9                      py35_0    conda-forge
python                    3.5.2                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
python-utils              2.0.0                    py35_0    conda-forge
python.app                1.2                      py35_4    defaults
pytz                      2016.4                   py35_0    defaults
pyyaml                    3.11                     py35_4    defaults
pyzmq                     15.2.0                   py35_1    defaults
qt                        4.8.7                         3    defaults
qtconsole                 4.2.1                    py35_0    defaults
qtpy                      1.0.2                    py35_0    defaults
r                         3.3.1                  r3.3.1_0    r
r-assertthat              0.1                    r3.3.1_4    r
r-base                    3.3.1                         0    r
r-base64enc               0.1_3                  r3.3.1_0    r
r-bh                      1.60.0_2               r3.3.1_0    r
r-bitops                  1.0_6                  r3.3.1_2    r
r-boot                    1.3_18                 r3.3.1_0    r
r-car                     2.1_2                  r3.3.1_0    r
r-caret                   6.0_70                 r3.3.1_0    r
r-catools                 1.17.1                 r3.3.1_2    r
r-chron                   2.3_47                 r3.3.1_0    r
r-class                   7.3_14                 r3.3.1_0    r
r-cluster                 2.0.4                  r3.3.1_0    r
r-codetools               0.2_14                 r3.3.1_0    r
r-colorspace              1.2_6                  r3.3.1_0    r
r-crayon                  1.3.1                  r3.3.1_0    r
r-curl                    0.9.7                  r3.3.1_0    r
r-data.table              1.9.6                  r3.3.1_0    r
r-dbi                     0.4_1                  r3.3.1_0    r
r-dichromat               2.0_0                  r3.3.1_2    r
r-digest                  0.6.9                  r3.3.1_0    r
r-dplyr                   0.4.3                  r3.3.1_0    r
r-essentials              1.4.3                  r3.3.1_0    r
r-evaluate                0.9                    r3.3.1_0    r
r-foreach                 1.4.3                  r3.3.1_0    r
r-foreign                 0.8_66                 r3.3.1_0    r
r-formatr                 1.4                    r3.3.1_0    r
r-ggplot2                 2.1.0                  r3.3.1_0    r
r-gistr                   0.3.6                  r3.3.1_0    r
r-glmnet                  2.0_5                  r3.3.1_0    r
r-gtable                  0.2.0                  r3.3.1_0    r
r-hexbin                  1.27.1                 r3.3.1_0    r
r-highr                   0.6                    r3.3.1_0    r
r-htmltools               0.3.5                  r3.3.1_0    r
r-htmlwidgets             0.6                    r3.3.1_0    r
r-httpuv                  1.3.3                  r3.3.1_0    r
r-httr                    1.2.0                  r3.3.1_0    r
r-irdisplay               0.4.3                  r3.3.1_2    r
r-irkernel                0.7                    r3.3.1_2    r
r-iterators               1.0.8                  r3.3.1_0    r
r-jsonlite                0.9.22                 r3.3.1_0    r
r-kernsmooth              2.23_15                r3.3.1_0    r
r-knitr                   1.13                   r3.3.1_0    r
r-labeling                0.3                    r3.3.1_2    r
r-lattice                 0.20_33                r3.3.1_0    r
r-lazyeval                0.2.0                  r3.3.1_0    r
r-lme4                    1.1_12                 r3.3.1_0    r
r-magrittr                1.5                    r3.3.1_2    r
r-maps                    3.1.0                  r3.3.1_0    r
r-markdown                0.7.7                  r3.3.1_2    r
r-mass                    7.3_45                 r3.3.1_0    r
r-matrix                  1.2_6                  r3.3.1_0    r
r-matrixmodels            0.4_1                  r3.3.1_0    r
r-memoise                 1.0.0                  r3.3.1_0    r
r-mgcv                    1.8_12                 r3.3.1_0    r
r-mime                    0.4                    r3.3.1_0    r
r-minqa                   1.2.4                  r3.3.1_2    r
r-munsell                 0.4.3                  r3.3.1_0    r
r-nlme                    3.1_128                r3.3.1_0    r
r-nloptr                  1.0.4                  r3.3.1_2    r
r-nnet                    7.3_12                 r3.3.1_0    r
r-openssl                 0.9.4                  r3.3.1_0    r
r-pbdzmq                  0.2_3                  r3.3.1_0    r
r-pbkrtest                0.4_6                  r3.3.1_0    r
r-plyr                    1.8.4                  r3.3.1_0    r
r-pryr                    0.1.2                  r3.3.1_0    r
r-quantmod                0.4_5                  r3.3.1_2    r
r-quantreg                5.26                   r3.3.1_0    r
r-r6                      2.1.2                  r3.3.1_0    r
r-randomforest            4.6_12                 r3.3.1_0    r
r-rbokeh                  0.4.2                  r3.3.1_0    r
r-rcolorbrewer            1.1_2                        2a    r
r-rcpp                    0.12.5                 r3.3.1_0    r
r-rcppeigen               0.3.2.8.1              r3.3.1_0    r
r-recommended             3.3.1                  r3.3.1_0    r
r-repr                    0.7                    r3.3.1_0    r
r-reshape2                1.4.1                        1a    r
r-rmarkdown               0.9.6                  r3.3.1_0    r
r-rpart                   4.1_10                 r3.3.1_0    r
r-scales                  0.4.0                  r3.3.1_0    r
r-shiny                   0.13.2                 r3.3.1_0    r
r-sparsem                 1.7                    r3.3.1_0    r
r-spatial                 7.3_11                 r3.3.1_0    r
r-stringi                 1.1.1                  r3.3.1_0    r
r-stringr                 1.0.0                  r3.3.1_0    r
r-survival                2.39_4                 r3.3.1_0    r
r-tibble                  1.0                    r3.3.1_0    r
r-tidyr                   0.5.1                  r3.3.1_0    r
r-ttr                     0.23_1                 r3.3.1_0    r
r-uuid                    0.1_2                  r3.3.1_0    r
r-xtable                  1.8_2                  r3.3.1_0    r
r-xts                     0.9_7                  r3.3.1_2    r
r-yaml                    2.1.13                 r3.3.1_2    r
r-zoo                     1.7_13                 r3.3.1_0    r
readline                  6.2                           0    conda-forge
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py35_0    defaults
requests                  2.10.0                   py35_0    defaults
requests-file             1.4                      py35_0    anaconda
rope                      0.9.4                    py35_1    defaults
rpy2                      2.8.2              py35r3.3.1_1    r
ruamel_yaml               0.11.14                  py35_0    defaults
scikit-image              0.12.3              np111py35_1    defaults
scikit-learn              0.18            np111py35_blas_openblas_202  [blas_openblas]  conda-forge
scipy                     0.18.1          np111py35_blas_openblas_200  [blas_openblas]  conda-forge
setproctitle              1.1.10                   py35_0    conda-forge
setuptools                23.0.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.16.9                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
six                       1.10.0                    <pip>
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.1                    py35_0    defaults
sphinx_rtd_theme          0.1.9                    py35_0    defaults
spyder                    2.3.9                    py35_0    defaults
sqlalchemy                1.0.13                   py35_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.6.1               np111py35_1    defaults
sympy                     1.0                      py35_0    defaults
tensorflow                0.10.0                   py35_0    conda-forge
terminado                 0.6                      py35_0    defaults
Theano                    0.8.2                     <pip>
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.3                      py35_1    defaults
traitlets                 4.2.1                    py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
Unidecode                 0.4.19                    <pip>
vaex                      1.0.0b3                  py35_1    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
werkzeug                  0.11.10                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.2                    py35_0    defaults
xlwings                   0.7.2                    py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
xonsh                     0.4.4                    py35_1    conda-forge
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         3    defaults
david-boyds-iMac:pkgs davidboyd$

**Comment by dthboyd** [comment]
On 2016-11-29, at 4:01 PM, Ray Donnelly wrote:

> conda install -c defaults icu

dyld: Library not loaded: @rpath/libncurses.5.dylib
  Referenced from: /Users/davidboyd/anaconda/lib/R/lib/../..//libreadline.6.2.dylib
  Reason: image not found

the new error after i do the above

**Comment by mingwandroid** [comment]
Right, so we continue:

Looking at your output we see:

`readline 6.2 0 conda-forge`

therefore:

`conda install -c defaults readline`

It may be better not to install anything from `conda-forge`, or to use separate environments for `conda-forge` software and `conda defaults` software.

**Comment by dthboyd** [comment]
thank you so much, R notebooks working now, i got the following message when i started up the notebook Warning: namespace ‘SparkR’ is not available and has been replaced
by .GlobalEnv when processing object ‘predictions’, was wondering if this is a potential problem? Anyway, thanks again.

**Comment by mingwandroid** [comment]
You probably had an old R installation from elsewhere and it left some files in your %AppData% folder.

Warnings are warnings, I try not to get overly concerned with them esp. when I have errors to deal with.
