### ISSUE TITLE
Anaconda not opening: couldn't find or load Qt platform plugin "Windows in ""

### ISSUE THREAD

**Issue by ignacioarnal1** [ContinuumIO/anaconda-issues#1270]
Hello, I've been using Anaconda on Windows 10 for the past few months. However, today I tried launching the program and got the following error:

 "This application failed to start because it could not find or load the Qt
 platform plugin "windows in "".

 Reinstalling the application may fix this problem."

 I read around about doing 'conda update -all' in cmd, however it didn't
 work for me, neither reinstalling Anaconda.

 This seems to be a common problem, however I can't seem to find a
 straightforward solution online, what can I do? and please bear in mind that
 I'm a newbie in Python.

 Thanks in advance!

PD: After reading other topics in this forums, I think this information could be useful:

`C:\Users\JoséIgnacio>conda info
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.11
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : C:\Users\JoséIgnacio\Anaconda3  (writable)
    default environment : C:\Users\JoséIgnacio\Anaconda3
       envs directories : C:\Users\JoséIgnacio\Anaconda3\envs
          package cache : C:\Users\JoséIgnacio\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False`

`C:\Users\JoséIgnacio>qmake --version
QMake version 3.0
Using Qt version 5.6.0 in C:/Users/JoséIgnacio/Anaconda3/Library/lib`

`C:\Users\JoséIgnacio>qmake -query
QT_SYSROOT:
QT_INSTALL_PREFIX:C:/Users/JoséIgnacio/Anaconda3/Library
QT_INSTALL_ARCHDATA:C:/Users/JoséIgnacio/Anaconda3/Library
QT_INSTALL_DATA:C:/Users/JoséIgnacio/Anaconda3/Library
QT_INSTALL_DOCS:C:/Users/JoséIgnacio/Anaconda3/Library/doc
QT_INSTALL_HEADERS:C:/Users/JoséIgnacio/Anaconda3/Library/include/qt
QT_INSTALL_LIBS:C:/Users/JoséIgnacio/Anaconda3/Library/lib
QT_INSTALL_LIBEXECS:C:/Users/JoséIgnacio/Anaconda3/Library/bin
QT_INSTALL_BINS:C:/Users/JoséIgnacio/Anaconda3/Library/bin
QT_INSTALL_TESTS:C:/Users/JoséIgnacio/Anaconda3/Library/tests
QT_INSTALL_PLUGINS:C:/Users/JoséIgnacio/Anaconda3/Library/plugins
QT_INSTALL_IMPORTS:C:/Users/JoséIgnacio/Anaconda3/Library/imports
QT_INSTALL_QML:C:/Users/JoséIgnacio/Anaconda3/Library/qml
QT_INSTALL_TRANSLATIONS:C:/Users/JoséIgnacio/Anaconda3/Library/translations
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:C:/Users/JoséIgnacio/Anaconda3/Library/examples
QT_INSTALL_DEMOS:C:/Users/JoséIgnacio/Anaconda3/Library/examples
QT_HOST_PREFIX:C:/Users/JoséIgnacio/Anaconda3/Library
QT_HOST_DATA:C:/Users/JoséIgnacio/Anaconda3/Library
QT_HOST_BINS:C:/Users/JoséIgnacio/Anaconda3/Library/bin
QT_HOST_LIBS:C:/Users/JoséIgnacio/Anaconda3/Library/lib
QMAKE_SPEC:win32-msvc2015
QMAKE_XSPEC:win32-msvc2015
QMAKE_VERSION:3.0
QT_VERSION:5.6.0`

**Comment by mingwandroid** [comment]
Can you try to install Anaconda in a folder that does not use non-ascii characters?

Also, you say you have done `conda update --all`, but your Qt version states 5.6.0. Last week we released version 5.6.2, so `conda update --all` should have got that version for you.

Perhaps try `conda update qt` and see that it installs 5.6.2?

**Comment by jgmorrison** [comment]
I can verify this happens on Windows installations that have spaces or non-ASCII characters in the username regardless of Python2 or Python3. The recent Anaconda-4.3 release does not allow Anaconda to be installed in a path that has spaces or non-ASCII characters anymore.

**Comment by mingwandroid** [comment]
It also happens with install prefixes longer than 30 characters, but we will fix that ASAP.

**Comment by staplegun** [comment]
I got this after my first ever install of 4.3.0 and tried to open Anaconda Navigator. I don't have non-ASCII characters in the install path. 

I opened Anaconda Prompt tried `conda update qt` (as above) and it complained it wasn't installed. So I tried `conda install qt` and it worked. I can now open the Navigator.

**Comment by ignacioarnal1** [comment]
¡Thanks for your comments!, I _'fixed'_ the issue by downgrading from Anaconda 4.2.0 to 4.1.1...

I'll stay on that version until the bug is fixed, or change my username to a non ASCII name (easier said than done).

**Comment by GolosCD** [comment]
Hi.
I have this problem too.

**Comment by mingwandroid** [comment]
https://github.com/JuliaPy/PyPlot.jl/issues/278 is not related to this.

@staplegun, @GolosCD, what install location did you use?

**Comment by sedulousfunds** [comment]
Seconding the results from Staplegun above. Same problem here with conda 4.3.8 on Windows 10. Opening Anaconda prompt and running `conda update qt ` yielded a PackageNotFoundError but `conda install qt ` solved it and I can run Navigator now. I installed Anaconda3-4.3.0.1-Windows-x86_64 from `repo.continuum.io/archive/`.

**Comment by mingwandroid** [comment]
Hi @GolosCD, @ignacioarnal1, @staplegun, @jgmorrison and @sedulousfunds, would it be possible for you to try: https://repo.continuum.io/pkgs/misc/preview/Miniconda3-4.3.13-Windows-x86_64.exe

It has fixes for both the accented character and also for install locations longer than 30 characters.

It is only a Miniconda (though you can just `conda install anaconda` afterwards to make it an Anaconda), and only the Python3 version works well (in my testing) at present.

Many thanks for your patience.

@jgmorrison:
> I can verify this happens on Windows installations that have spaces or non-ASCII characters in the username regardless of Python2 or Python3. The recent Anaconda-4.3 release does not allow Anaconda to be installed in a path that has spaces or non-ASCII characters anymore.

AFAICT, Anaconda2 has never supported being installed into a install location containing non-ASCII. It's very tricky to write non-ASCII-correct Python2 code, and even if we fix our own software (`conda`, `conda-build`, `menuinst` etc) then the software that our users subsequently install into that installation will often not work correctly, so I'm a bit torn about what to do about that. My current opinion is that the safest thing to do is to advise people who want to do this not to use Python2, but I'd like to get a better understanding of how much stuff is broken first.

**Comment by Serkan72** [comment]
I solved same problem using below execution.

COPY the
Continuum\Anaconda3\Library\plugins\platforms
folder to 
Continuum\Anaconda3

**Comment by Nguyencoho** [comment]
It worked for me, thanks @Serkan72

**Comment by lgonzalezsa** [comment]
It does not work to me  @Serkan72. Using D:\Anaconda path and copied the mentioned files into Anaconda directory but same error.
Any other guidelines?

**Comment by wannalearn4fun** [comment]
thanks @Serkan72 solved the issue for me also

BTW there were no spaces, no non-ASCII characters in the path
Anaconda3-4.4.0-Windows-x86
32bit install
Win7 Pro SP1

**Comment by chipmuenk** [comment]
Same problem, @Serkan72 solved the issue for me, too. No spaces or non-ASCII characters in the path, Win 7 64 bits, latest Anaconda download. Anaconda has got no rights to access the internet here at work - perhaps this is a part of the problem?

**Comment by Abdullah-MARAS** [comment]
Hi,

I have the same problem but unfortunately this solution didn't work for me

**Comment by Lauanb** [comment]
For those who could not, check if the directory was copied, not the files.

**Comment by jeanhubdes** [comment]
I got same issue and I did conda update --all, in Anaconda prompt, this solved the issue in my case.
W7 64bits.

**Comment by 6486484** [comment]
@Serkan72 
Worked for me as well. Python installation on a Windows network drive.

**Comment by dorbank** [comment]
my python file runs good. when I try to turn it to a .exe file and run it, I get: "This application failed to start because it could not find or load the qt platform plugin "windows" in "". ".  Any ideas?

**Comment by Abdullah-MARAS** [comment]
I also have problem related to qt. I solved my problem like below.

**Comment by HanSiyan** [comment]
@Serkan72 
Thanks a lot for the solution.

**Comment by ladydavy** [comment]
@Serkan72 It works for me. Thanks a lot.

**Comment by luigui2906** [comment]
@Serkan72 It works for me your solution. 
Thanks bro.

**Comment by GilCasale** [comment]
@Serkan72 It works too. Good play !

**Comment by duongtrung** [comment]
qt error in anaconda 4.3.30, qt 5,6,2, windows 10 64bit.

**Comment by sizzzzlerz** [comment]
Started getting the following error messages when starting ipython (python 2.7.14, windows 10, qt 5.6.2):

```
C:\Users\larry\Documents\projects>ipython --pylab
Using matplotlib backend: Qt5Agg

In [1]: This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Available platform plugins are: minimal, offscreen, windows.

Reinstalling the application may fix this problem.
```
Any use of matplotlib gives me this error whether in ipython on in my stand-alone apps. Using a backend of tcl/tk works, nothing else. I've done a "conda update --all", I've tried copying the plugin folder as described above. Nothing has solved the issue. This never happened before.  My python 3.6 environment doesn't do this either.

**Comment by ThomasThelen** [comment]
@sizzzzlerz I'm also running across this error when using `matplotlib`

```
C:\Users\Data>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\Data\Anaconda3  (writable)
    default environment : C:\Users\Data\Anaconda3
       envs directories : C:\Users\Data\Anaconda3\envs
                          C:\Users\Data\AppData\Local\conda\conda\envs
                          C:\Users\Data\.conda\envs
          package cache : C:\Users\Data\Anaconda3\pkgs
                          C:\Users\Data\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.15063
          administrator : False
```

Reinstalling QT and Anaconda has not resolved the issue.

**Comment by dataddiction** [comment]
Thanks a lot @Serkan72

**Comment by wtrenker** [comment]
I just updated Windows 10 Pro 32-bit (automated overnight update by Microsoft on December 6, 2017) and now get  "This application failed to start because it could not find or load the qt platform plugin "windows" in "". " 

However, running the application as Administrator works fine.

**Comment by zxr12748** [comment]
@lgonzalezsa 
I have  the same issue.
and tried as followed:

copy the folder 
\Anaconda3\Library\plugins\platforms
to 
$\venv\Scripts
where $ represents your project dir, because PyCharm calls the python.exe in this dir, not the one in \Anaconda3\.

hope it can help you to solve the problem :-D

**Comment by thatlittleboy** [comment]
I have the same issue on Windows 10, 64 bit, and using Pycharm 2017.3 Community, and I've tried everything on this thread already:

1) Copied the folder `\Anaconda3\Library\plugins\platforms` containing the 3 dll files to the same folder as my `python.exe`, i.e. `\Anaconda3` --> Doesn't work
2) Ensured there are no spaces or non-ASCII characters in the file name or install folder. --> Doesn't work.
3) Running Pycharm or python.exe as administrator doesn't seem to work as well.

Here's my `conda info`:
```
    active environment : None
       user config file : C:\Users\user\.condarc
 populated config files :
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : D:\user\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : D:\user\Anaconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : D:\user\Anaconda3\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
                          C:\Users\user\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

Please help!

**Comment by mingwandroid** [comment]
You probably have Qt DLLs (or zlib1.dll or one called windows.dll) in `C:\WIndows\System32`. Use cmd.exe and `where some.dll` to figure this out.

**Comment by thatlittleboy** [comment]
Thanks for the swift reply. I found `zlib1.dll` in my local Julia installation folder: `C:\Users\user\AppData\Local\Julia-0.6.0\bin\zlib1.dll`.

No `windows.dll` found. What am I supposed to do with these `.dll` files if and when I find them?

**Comment by mingwandroid** [comment]
Files in `C:\Windows\System32` are the most problematic. Files in your `System PATH` are problematic if Anaconda is in your `User PATH` since `System PATH` gets precedence. You can work around this by using the `Anaconda Prompt` and/or `Anaconda Navigator`. Our installers specifically discourage adding to `PATH`.

So you should use the `Anaconda Prompt` or you should not have allowed the Julia installer to add anything to your `PATH`.

**Comment by duffymo** [comment]
I'm running Anaconda3 5.0.1 64-bit on Windows 7 server.  I use PyCharm, running as administrator.

I can see the libEGL.lib file under anaconda3-5.0.1\pkgs\qt-5.6.2-vc14h6f8c307_12\Library\lib.

But when I run this code:

```
import numpy as np

def softmax(x):
    p = np.array([np.exp(v) for v in x])
    t = sum(p)
    return np.array([v/t for v in p])

#if __name__ == '__main__':
#    scores = np.array([
#        [1, 2, 3, 6],
#        [2, 4, 5, 6],
#        [3, 8, 7, 6]])
#
#    print(softmax(scores))

# plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2*np.ones_like(x)])
plt.plot(x, softmax(scores).T, linewidth=2)
plt.show()


```
I get this error popup:

![qt-error](https://user-images.githubusercontent.com/1179546/36316873-7f58d60a-1309-11e8-94b1-fe5539204d79.png)

How can I fix this?

**Comment by mingwandroid** [comment]
Your options are:

1. Use the `Anaconda Prompt` to launch `pycharm`.
2. Figure out which software you have on your `PATH` that's got a conflicting `libQtCore5.dll` (run cmd.exe, enter where libQtCore5.dll), then remove this from `PATH` (risking breaking whatever software this is).

I think for the next build-out of our Qt libraries I will consider adding a custom prefix to the Qt DLLs as DLL-hell issues with Qt libs comes up a little too often for my liking (mainly due to its popularity).

**Comment by duffymo** [comment]
I opened a command shell, executed "where libQtCore5.dll" per your instructions, and got this:

> Could not find files for the given pattern(s).

Opening PyCharm in the anaconda prompt worked.  Thank you!

**Comment by mingwandroid** [comment]
Sorry, I meant `where Qt5Core.dll`.

**Comment by duffymo** [comment]
Interesting.  There are two: One for Qt, another for MiKTeK.

**Comment by mingwandroid** [comment]
Well, that's your problem. This is nothing more than boring old DLL-hell on Windows. Using the Anaconda Prompt and/or Anaconda Navigator means that Anaconda is put to the front of PATH while running that software and this is the best way to handle PATH on Windows.

Personally when given the option I never allow software to modify my `PATH` as it's a really bad idea. I do not see why `Qt` or `MiKTeX` need to be on `PATH`.

**Comment by duffymo** [comment]
Thank you for your expertise and help.  I greatly appreciate it.

**Comment by mingwandroid** [comment]
It's a pleasure.

**Comment by u2berggeist** [comment]
Thanks @duffymo and @mingwandroid ! I ran into the exact same problem, with MiKTeK being the conflicting `Qt5Core.dll`. However, just a random point, I had no issues up until today when I decided to upgrade anaconda (`conda update anaconda`). 

Any idea as to what changed between my previous anaconda version (I didn't make note of it, so I couldn't tell you what it was) and 5.1.0?

**Comment by u2berggeist** [comment]
I did all that was recommended above and it did not work. I then uninstalled and reinstalled Anaconda and that seems to have worked.

**Comment by MLikelihood** [comment]
I tried the following in Anaconda prompt, and it solved this problem:

conda remove qt

conda remove pyqt

conda install qt

conda install pyqt

**Comment by elgplayer** [comment]
I had this issue too. What solved it was by resting the settings in spyder.

**Comment by dreamPoet** [comment]
I had the same issue as well. The way of copying the flatform folder to Anaconda3 directly did not work for me. I used "conda update --all" and solved the problem. However, I found the package of opencv3 back to 3.3.1 instead of the 3.4.1 installed by myself. Feel confused. Win10 x64.

**Comment by soberbia** [comment]
Hi guys, i also had this problem but recently i fixed installing python from source. Before i had Anaconda installed, it´s a great tool for some things but specially in this it causes some troubles and i decided uninstall it completly. 

I hope that this work well for you

**Comment by mingwandroid** [comment]
Windows can be very tricky and you ran into a DLL-hell conflict and one way to resolve such a conflict is to remove one of the conflicting items. Shame you pick Anaconda Distribution but we cannot fix the Windows DLL loader here.

This is why we specifically discourage adding anything to `PATH` and would love other software vendors to promote the same advice.

**Comment by CarolinaStephanie** [comment]
Hi, i solved just removing the anaconda's lib (all) from the PATH.

**Comment by mingwandroid** [comment]
That's fine, we don't recommend adding anything to `PATH` in the first place, in fact, we explicitly warn against that.

To run our software you should use `Anaconda Navigator` or the `Anaconda Prompt`. That way we do not interfere with other software and other software has less chance of interfering with our software.

**Comment by Gavinzgz** [comment]
Thanks for zxr12748 ,I have solve my problem !

**Comment by ashwaqar** [comment]
@zxr12748  Thank you

That worked perfectly for me. 
Copying "platforms" folder to my project directory solved the error.

**Comment by jmacura** [comment]
Hi there! I have run into this issue just now, while trying to use matplotlib. None of the tips and tricks listed here helped me, until I downgraded the Qt down to the old 5.6.2. Now it works just fine.

**Comment by kzwkt** [comment]
i fixed it by adjusting path in qt.conf file 

[Paths] 
Prefix =D:/Anaconda3/Library 
Binaries =D:/Anaconda3/Library/bin 
Libraries =D:/Anaconda3/Library/lib 
Headers =D:/Anaconda3/Library/include/qt

**Comment by Pechi77** [comment]
I am getting the same issue but from apache, what to do

**Comment by IngoKl** [comment]
I've found another solution (at least for my specific case). I have installed PySide2 directly from Qt. Copying (and overwriting) all DLLs from `Anaconda3\Lib\site-packages\PySide2\plugins\platforms`
into `Anaconda3/Library/plugins/platforms` has solved the issue for me.

**Comment by Smsmadly** [comment]
if installed PyQt5 and PySide2, i solved problem
Copy
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qminimal.dll
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qoffscreen.dll
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qwindows.dll
files to
\Anaconda3\Library\plugins\platforms\

**Comment by Shimion100** [comment]
If you are using MiKTeX, edit the qt.conf(in the Anaconda base directory), change the Header like:
Headers = E:/Program Files/MiKTeX 2.9/miktex/bin/x64

**Comment by YanaXu** [comment]
I installed Anaconda and Pycharm.
Run something with seaborn, and meet this problem.
![image](https://user-images.githubusercontent.com/12843157/56028545-f459ce00-5d4a-11e9-8b4b-748bab966667.png)
I tried all the steps above, but none of them is working...
According to the words of **mingwandroid** commented on Mar 28, 2018, I open Pycharm in "Anaconda Prompt". 
![image](https://user-images.githubusercontent.com/12843157/56028832-9d082d80-5d4b-11e9-9fcd-04c047a56a72.png)
The error is gone. Thank God!

**Comment by GoingMyWay** [comment]
In Windows, please activate the virtual env, for example, the `base`

**Comment by Antia123** [comment]
Hi, I´m getting the same error when I try to install Anaconda (Python 3.7) on Windows 10. I ran 'conda install qt ' in Anaconda prompt like you but it returns me the message : '
"conda" is not recognized as an internal or external command,
program or executable batch file'.
What can I do to solve this? Do you know?

Thank you in advance!

**Comment by antoinesarji** [comment]
> I solved same problem using below execution.
> 
> COPY the
> Continuum\Anaconda3\Library\plugins\platforms
> folder to
> Continuum\Anaconda3

Totally Works for me

**Comment by CarlosSchettini** [comment]
I faced this 'qt' issue every time I tried to install Anaconda. Many, many times!. So, Anaconda never worked in my notebook.  

I need to install a package using Conda (Iris), so I installed Miniconda. It didn't work (the package installation), but in the error reported it was listed that the Qt was addressed to another installed program (Delft3D from Deltares). 

After I removed the Delft3d and manually to delete its directory and contents, restarting the computer, Anaconda finally come to life on my computer!

**Comment by Winand** [comment]
I've found a "native" solution. cx_Freeze uses `QtCore.QCoreApplication.libraryPaths` to find `platforms` directory, so we have to initialize `QCoreApplication` beforehand.

```
from qtpy import QtCore
# otherwise `cx_freeze.hooks.copy_qt_plugins` will not find plugins folder
_ = QtCore.QCoreApplication([])
print("Qt library paths:", _.libraryPaths())
```

But the created package is bloated with duplicate files, e.g. icudt58.dll (25MB) is copied not only into `lib` but also `imageformats` and `platforms` directories.

**Comment by liudonghua123** [comment]
> Your options are:
> 
> 1. Use the `Anaconda Prompt` to launch `pycharm`.
> 2. Figure out which software you have on your `PATH` that's got a conflicting `Qt5Core.dll` (run cmd.exe, enter `where Qt5Core.dll`), then remove this from `PATH` (risking breaking whatever software this is).
> 
> I think for the next build-out of our Qt libraries I will consider adding a custom prefix to the Qt DLLs as DLL-hell issues with Qt libs comes up a little too often for my liking (mainly due to its popularity).

You saved me a lot of time. In my computer, I have the following envs.

```
D:\code\python\playground>python power_law_graph.py
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.


D:\code\python\playground>
D:\code\python\playground>where Qt5Core.dll
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\Qt5Core.dll
C:\Users\Liu.D.H\Anaconda3\Library\bin\Qt5Core.dll

D:\code\python\playground>
```

and after I changed `C:\Program Files\MiKTeX 2.9\miktex\bin\x64` priority, now it works.

```
D:\code\python\playground>where Qt5Core.dll
C:\Users\Liu.D.H\Anaconda3\Library\bin\Qt5Core.dll
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\Qt5Core.dll

D:\code\python\playground>python power_law_graph.py

```

**Comment by phatsp** [comment]
Hi, I have the same problem. I tried some of the above answers but it didn't work out for me. My PATH is as below, can you tell me what to do. I just learn how to code and don't even know how to handle all these system variable things (I really don't understand some of your answers so I couldn't know how to try those solutions)
  
![image](https://user-images.githubusercontent.com/43247670/81269682-df498e80-9073-11ea-8aba-cd157d37d55b.png)
![image](https://user-images.githubusercontent.com/43247670/81269735-f7b9a900-9073-11ea-8c6c-5e8664f8ea68.png)

**Comment by antlancer-solutions** [comment]
I have the same issue and fixed in this way
In Anaconda installation folder I went to : (change it to your installed path):
C:\ProgramData\Anaconda3\Lib\site-packages\PySide2
Edit this file by adding the following code lines :
# below the line 23 type.__signature__
    pyside_package_dir =  os.path.abspath(os.path.dirname(__file__))
    dirname = os.path.dirname(__file__)
    plugin_path = os.path.join(dirname, 'plugins', 'platforms')
    os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path

save this file and try again and the issue should be gone :)

**Comment by ND-Ha** [comment]
I just found reason why.

It is the difference of the user's name.
![image](https://user-images.githubusercontent.com/67629459/86106313-61e24d80-bafb-11ea-87e4-6ee62360e9f3.png)


qt.conf
conda-meta\certifi-2018.8.24-py35_1001.json
conda-meta\matplotlib-2.2.2-py35had4c4a9_2.json
conda-meta\openssl-1.0.2u-hfa6e2cd_0.json
conda-meta\pyqt-5.6.0-py35h764d66f_7.json
conda-meta\pyside2-5.6.0a1-py35h20f30f1_3.json
conda-meta\qt-5.6.2-vc14h6f8c307_12.json
conda-meta\sip-4.18.1-py35h6538335_0.json
conda-meta\tornado-5.1.1-py35hfa6e2cd_0.json
conda-meta\xlsxwriter-1.2.8-py_0.json

**Comment by meRscliche** [comment]
> I solved same problem using below execution.
> 
> COPY the
> Continuum\Anaconda3\Library\plugins\platforms
> folder to
> Continuum\Anaconda3

Works for me too. Thanks.

**Comment by dradamjones** [comment]
> > I solved same problem using below execution.
> > COPY the
> > Continuum\Anaconda3\Library\plugins\platforms
> > folder to
> > Continuum\Anaconda3
> 
> Totally Works for me

I keep getting this Qt platform error after conda update --all but this solution worked for me too.

**Comment by munkey01** [comment]
> For those who could not, check if the directory was copied, not only the files.

Thanks @Lauanb 

I have fought this for days!!! Finally, your comment helped me. I had only moved the contents of the folder.

`Copy-Item C:\ProgramData\Anaconda3\Library\plugins\platforms\ C:\ProgramData\Anaconda3\ -Recurse`

**Comment by deemano** [comment]
For me, the easiest way was to 
1. rename the anaconda3 folder into something else
2. reinstall Anaconda from the website
3. copy the old /envs folder content into the new anaconda3/envs

that's all.

**Comment by iSantPy** [comment]
> For me, the easiest way was to
> 
> 1. rename the anaconda3 folder into something else
> 2. reinstall Anaconda from the website
> 3. copy the old /envs folder content into the new anaconda3/envs
> 
> that's all.

it worked for me! I just remove Anaconda and reinstall it again from the web
