### ISSUE TITLE
Uninstalling CRAN packages mistakenly loaded in Jupyter

### ISSUE THREAD

**Issue by 1rdsk1** [ContinuumIO/anaconda-issues#1272]
Hi Mingwandroid
Thank for your advice  at https://github.com/ContinuumIO/anaconda-issues/issues/777
So I now need to uninstall the CRAN packages I installed in Jupyter but I find I cannot get the R kernel to start due to the error described in link.  Is there another way to remove the CRAN packages I mistakenly installed.
Also, how should I install HTTR using conda please?
Rupert

**Comment by mingwandroid** [comment]
You need to use R from the command line. Activate your environment and type `R`

Then to install r packages, again, from the command line:

`conda install -c r r-httr`.

You can use `conda search -c r <partial-name>` to search for packages. All of the r packages start with `r-` and many with `r-r`.

**Comment by 1rdsk1** [comment]
Thanks.  I uninstalled the CRAN packages and rebooted pc but still get the missing dll errors.
Do I need to do a complete reinstall of Annaconda to start afresh or can I fix Jupyter R dll error some other way please?
Rupert

**Comment by mingwandroid** [comment]
I would probably recommend that yes, but first, try launching `jupyter notebook` from the `Anaconda Prompt`.

**Comment by 1rdsk1** [comment]
launching jupyter notebook from the Anaconda Prompt seems to work.  Odd since presumably the menu points to same executable, Hope to figure that out.

I cant find how to do a reinstall of Annaconda,  How do I do that if this fails in a bit please? Just in case ...
Rupert

**Comment by mingwandroid** [comment]
Well, it's probably to do with PATHs then. If you were to launch `anaconda-navigator` from the `Anaconda Prompt` can you see if you can then launch `Jupyter` from that successfully?

I believe the shortcut for `Anaconda Navigator` may need to work more like the one for `Anaconda Prompt` and this is something for me to investigate.

I wouldn't be too concerned about reinstalling everything though, but you can either remove Anaconda from the Control Panel or just delete the folder and then re-run the installer.

**Comment by 1rdsk1** [comment]
Hi, 

I'll have to now see if its possible to get the webscrapers httr and xml R packages via conda. Fingers crossed although I suspect I'll get same R version issues,  Hopefully conda will manage that soon too!
Jupyter from anaconda-navigator from the Anaconda Prompt worked with below messafes.  Also the Jupyter icon disappeared from navigatotor after launch FYI,
I tried to paste images and list errors below.
Many thanks

Rupert
![image](https://cloud.githubusercontent.com/assets/16118846/20769509/172ff4a4-b73a-11e6-92fe-ca85fa269da1.png)
![capture](https://cloud.githubusercontent.com/assets/16118846/20769534/3564f492-b73a-11e6-8f05-bcbfb850fa77.PNG)

(C: \Users\rupert\Anaconda3) C: \Users\rupert>anaconda-navigator 
QWindowsFontDatabase: : createEngine  ...: 
createFontFromLOGFONT 
failed ...libpng warning: ... iccp: 
....
known incorrect sRGB profile

**Comment by mingwandroid** [comment]
I told you already how to get the r packages from conda. We have the packages at the right versions.

**Comment by mingwandroid** [comment]
The incorrect sRGB profile thing is nothing to worry about and the disappearing icon is known.

**Comment by goanpeca** [comment]
The disappearing icon is fixed on the latest version coming soon.

**Comment by mingwandroid** [comment]
Great!
