### ISSUE TITLE
Cannot install anaconda on mac with space in path name

### ISSUE THREAD

**Issue by jtrach** [ContinuumIO/anaconda-issues#1273]
I am trying to install Anaconda on my Mac, my home directory is in "Macintosh HD", and am unable to complete an installation. I greatly appreciate any guidance.

**Comment by jtrach** [comment]
https://github.com/asmeurer , 
https://github.com/ilanschnell, any idea? thanks!

**Comment by jtrach** [comment]
@ilanschnell @asmeurer, any ideas? thanks!

**Comment by jtrach** [comment]
I ended up just installing it in my boot SSD drive. Thanks.

**Comment by asmeurer** [comment]
I recommend removing spaces from any path that you intend to install Unix programs into. Anaconda isn't the only thing that doesn't support it (and worse, many programs just silently fail instead of error).

**Comment by goanpeca** [comment]
Tracking on #716

**Comment by guisei** [comment]
I had the same issue and solved it with this command :

bash Anaconda3-4.4.0-MacOSX-x86_64.sh -p /Users/username/anaconda3

to be edited to use your own username

**Comment by yochrung** [comment]
You might need that very specific directory.
