### ISSUE TITLE
IDLE vs Anaconda Python versions and library installations 

### ISSUE THREAD

**Issue by kkane0911** [ContinuumIO/anaconda-issues#12741]
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

### Actual Behavior

I am new to Python so sure this is straightforward. When I install libraries using Conda (or pip) they are available from all my Code editors etc. They are not available from the IDLE interpreter. This only starting happening after I installed Anaconda Navigator as I assume it is now the default Python version I am using. When I check the version of Python on both the IDLE terminal and in script (>>import sys. >>print (sys.version). Is there a way to sync these up again s that they are pointing to the same place when I do library installations. 

IDLE - 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)]
Script - 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]

### Expected Behavior

Run all libraries from same place

### Steps to Reproduce

See above

##### Anaconda or Miniconda version:

Anaconda Navigator 2.1.1

**Comment by csoja** [comment]
Does this help? https://docs.anaconda.com/anaconda/user-guide/tasks/integration/idle/

**Comment by kkane0911** [comment]
> Does this help? https://docs.anaconda.com/anaconda/user-guide/tasks/integration/idle/

thank you
