### ISSUE TITLE
a search gtk

### ISSUE THREAD

**Issue by dalanicolai** [ContinuumIO/anaconda-issues#1274]

**Comment by ccordoba12** [comment]
We don't support Gtk in Anaconda, sorry.

**Comment by dalanicolai** [comment]
I don't understand how I opened this issue. Does anaconda generate it by itself? Or did I unintentionally click/enter the wrong button? (I can not find information about this...) Anyway sorry for the 'irrelevant' issue, I did not actively open it...

**Comment by ccordoba12** [comment]
I don't what happened with either, but don't worry about it :-)
