### ISSUE TITLE
Please build pymssql 2.1.5 (or newer) for Python 3.9

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#12747]
Hello Team Anaconda,

the latest version of pymssql on the Anaconda main channel is 2.1.5. It has not been built for Python 3.9, although the previous version 2.1.4 was.

The latest release of the package on PyPI is 2.2.2. Maybe you want to consider an upgrade?
Version 2.2.2 has been tagged in the source repo, although it isn't listed as a release there.
https://github.com/pymssql/pymssql/tags
https://github.com/pymssql/pymssql/releases

Thanks and cheers!

**Comment by adipietro18** [comment]
`pymssql` v2.2.3 should now be available in **defaults** for Anaconda's supported Python versions and platforms, which includes Python 3.9. 👍
