### ISSUE TITLE
Update ipympl to latest version (0.8.2)

### ISSUE THREAD

**Issue by tovrstra** [ContinuumIO/anaconda-issues#12752]
I'm sorry for removing the `<details>` blocks. I got the impression they made the issue harder to process, so I took them out for the sake convenience.

## Package Information
```
Name: ipympl
Source: https://github.com/matplotlib/ipympl
Platform: Fedora Linux (35)
Conda-Forge feedstock: https://github.com/conda-forge/ipympl-feedstock
```

## Is your update request related to a problem? Please describe.
I am experiencing the following issue with the current combination of ipympl (0.7.0) and matplotlib (3.5.0) in the default channel: 
https://github.com/matplotlib/ipympl/issues/335

The error message cannot be reproduced with the code of that issue, but I ran into the same exception in a more complex notebook with animated plots. (I can upload it upon request but it is not yet a minimal example showing the error.)
Updating my packages to the latest versions from conda-forge did fix this.

## Describe the solution you'd like
An update of ipympl to the latest version (0.8.2) in the default channel should fix this. In general ipympl should be kept somewhat in sync with matplotlib updates, because apparently ipympl touches a lot of the internals of matplotlib, which are not part of a stable API.

## Describe alternatives you've considered
Switching to conda-forge channels. This is also what I recommend to the students, as a quick solution, when they run into this issue. It's not ideal because this installs a lot of other updates too, not all equally stable and reliable.

## Additional context
None at tho moment. If more background is needed, please let me know.

**Comment by tovrstra** [comment]
It may be better to update just to the latest ipympl, not just 0.8.2. 0.8.4 has recently been released.

**Comment by skupr-anaconda** [comment]
`ipympl` **0.8.7** should now be available in defaults:
https://repo.anaconda.com/pkgs/main/noarch
ipympl-0.8.7-pyhd3eb1b0_0.tar.bz2

Please report us if the issue persists.
