### ISSUE TITLE
Please update CMake package

### ISSUE THREAD

**Issue by tcaduser** [ContinuumIO/anaconda-issues#12756]
Thanks for opening an update package request! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

## Package Information
<details>

```
Name: cmake
Source: cmake.org
Platform:
Conda-Forge feedstock:

```

</details>

## Is your update request related to a problem? Please describe.
<details>
```
The current version of CMake does not support Visual Studio 2022.  Please update to a newer version.  The current install in Anaconda is 3.19, and Visual Studio 2022 support was added in Version 3.21:
https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html
```
</details>

## Describe the solution you'd like
<details>
```
Please update CMake to at least 3.21.
```
</details>

## Describe alternatives you've considered
<details>
```
CMake can be installed separately, but I prefer the Anaconda package management.
```
</details>

## Additional context
<details>
```
Add any other context or screenshots about the feature request here.
```
</details>

**Comment by skupr-anaconda** [comment]
`cmake v3.22.1` is available on defaults

**Comment by sheetalkalburgi** [comment]
cmake v3.22.1 is available on defaults. Closing this issue. Please reopen if issue persists.
