### ISSUE TITLE
Error at startup when launching jupyter from navigator (on mac): couldn't call conda

### ISSUE THREAD

**Issue by mgutman515** [ContinuumIO/anaconda-issues#1277]
Fresh install of anaconda 4.2. When running jupyter from navigator:
I get this error: [nb_conda_kernels] couldn't call conda: [Errno 2] No such file or directory: 'conda'

Jupyter continues starting despite the error. Most of it works except the "conda" tab.

It appears that the PATH is not set correctly from jupyter_mac.command. Specifically anaconda's bin directory is not included in the script. When I edit the script and export my PATH to include, everything works fine.

I noticed that the navigator application script DOES export anaconda's path correctly. Unfortunately, this does not get propagated when launching the jupyter app.

See below:

Anaconda-Navigator/app/Contents/MacOS/run.sh:

#!/bin/sh
export PATH=/Users/micah/anaconda3/bin:"$PATH" <<<--- Script exports the path!!
/Users/micah/anaconda3/bin/anaconda-navigator $@

but this script does not export the path and the PATH is not propogated when clicking on the app icon in navigator:

bin/jupyter_mac.command:

DIR=$(dirname $0)
$DIR/jupyter-notebook

**Comment by goanpeca** [comment]
Hi @mgutman515 what version of navigator are you using?

Could you open a terminal and type:

`$ conda info`
`$ conda list`

And paste the results here?

**Comment by mgutman515** [comment]
I already updated the files many times since the original download
unfortunately.
