### ISSUE TITLE
Error installing anaconda3 on Red Hat Enterprise Linux Server release 7.3 (Maipo)

### ISSUE THREAD

**Issue by abhishekupadhyaya** [ContinuumIO/anaconda-issues#1282]
I am getting errors while installing anaconda3 on RHEL server 7.3.

I can install it fine when I download "Anaconda3-4.0.0-Linux-x86_64.sh" file on /opt of the root directory and leave the path to be default i.e /root/anaconda3. However, when I download " Anaconda3-4.0.0-Linux-x86_64.sh" file on some other directory and change the installation path to some other location, I get the error. Here is the screen shot of the error message.

![screen shot 2016-12-05 at 10 26 01 am](https://cloud.githubusercontent.com/assets/8761854/20891288/0afc4b0a-bad8-11e6-85d4-7cdaa163b455.png)

**Comment by mingwandroid** [comment]
Does `/data` exist and do you have permission to read, write and execute files in it?

Is it a mount to a filesystem that does not support symbolic links?

**Comment by abhishekupadhyaya** [comment]
/data exists and i have permission to read, write and execute files as root user. it is a mount to a filesystem but i am not sure if it supports symbolic links or not

**Comment by mingwandroid** [comment]
Can you try:
```
cd /data
echo test > fileA
ln -s fileA linkToFileA
ls -l linkToFileA
```

**Comment by abhishekupadhyaya** [comment]
I get this: `ln: failed to create symbolic link ‘linkToFileA’: Operation not supported` for `ln -s fileA linkToFileA`

**Comment by mingwandroid** [comment]
You're going to have to install elsewhere then.

**Comment by abhishekupadhyaya** [comment]
ok. thank you for the help
