### ISSUE TITLE
ImportError: No module named 'PySide'

### ISSUE THREAD

**Issue by quanganhct** [ContinuumIO/anaconda-issues#1283]
Hello,

I just download anaconda 3 yesterday for my Mac and after installation, I cannot start anaconda navigation at all. Si I googled it and found out that there were people that had the same error like me, in this [https://github.com/ContinuumIO/anaconda-issues/issues/1089](https://github.com/ContinuumIO/anaconda-issues/issues/1089), but my pyqt and qt are both version 5.6.0, and there isn't any orange package, so the solution provided cannot fix my issue. Please help

**Comment by ccordoba12** [comment]
If you installed Anaconda in /Applications, please uninstall it and install it instead in your Users directory

**Comment by quanganhct** [comment]
Yes, it is in /Users/<myname>/anaconda

**Comment by ccordoba12** [comment]
Is that your current user?

**Comment by quanganhct** [comment]
Yes. It's my current user. Is that problem have anything related to Mac OS ? My OS is 10.6

**Comment by ccordoba12** [comment]
10.6? That's too old. You need to update to 10.7, that's the oldest version we support.
