### ISSUE TITLE
iris data

### ISSUE THREAD

**Issue by hiroshi-nakajima345** [ContinuumIO/anaconda-issues#12850]
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

### Actual Behavior

from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
x = iris.data[:, :2]
y = iris.target

x_reduced = PCA(n_components=3).\
fit_transform(iris.data)

fig = plt.figure(1, figsize=(8, 6))
ax =Axes3D(fig, elev=-150, azim=110)
ax.scatter(x_reduced[:, 0], x_reduced[:
                 1], x_reduced[:2], c=y,cmap=plt.
		cm.Set1, edgecolor='k', s=40)

ax.set_title(
	"First three PCA directions")
ax.se_xlabel("PC1 eigenvector")
ax.w_xaxis.set_ticklabels([])
ax.sey_ylabel("PC2 eigenvector")
ax.w_yaxis.set_ticklabels([])
ax.sey_zlabel("PC3 eigenvector")
ax.w_zaxis.set_ticklabels([])
plt.show()

### Expected Behavior

How Can I progress this code & this issue.
My Englishi ability & Ability of using this Column.

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by LtDan33** [comment]
This looks to be an question on how to use sklearn so isn't a good fit for this issue tracker. I'd suggest you take a look at kaggle for many ways that people have used this dataset. https://www.kaggle.com/uciml/iris/code
