### ISSUE TITLE
Unavailability of python 3.9 with Anaconda - conda 4.11.0

### ISSUE THREAD

**Issue by nadirdbit** [ContinuumIO/anaconda-issues#12852]
Hi,

The latest version of Anaconda Individual edition mentions availability of Python 3.9

However, when attempting to do a "conda update python" on both Windows and macOS, python -V output shows Python 3.8.8

Please advise how one may obtain the latest release without creating that in some other new location.

Thank you.

**Comment by nadirdbit** [comment]
Oddly, this got resolved with doing these steps:

o conda update --all
[update done from Python 3.8.8 to Python 3.8.12]

o conda update python
[update done from Python 3.8.12 to Python 3.9.7]

**Comment by nadirdbit** [comment]
This issue on Windows is still persistent - even with conda upgrade to 4.12.0

As two months have elapsed since when this was first reported, can resolution please be expedited?

**Comment by jezdez** [comment]
Hey @nadirdbit,

Could you please try the following options:

- `conda install python=3.9` (in an activated conda environment) or
- `conda create -n my_new_env python=3.9` (to create a new environment with Python 3.9)?

**Comment by nadirdbit** [comment]
Hi Jannis,

With the prior step, only able to upgrade from Python 3.8.12 to Python 3.8.13.

On trying the first option, didn't work and goes into a loop without any package refresh -

conda install python=3.9
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done

Thank you.

Nadir

**Comment by nadirdbit** [comment]
Hi Jannis,

The package downloads did occur fine in the 3rd attempt and Python 3.9.12 got installed fine.

Thanks again.

Nadir
