### ISSUE TITLE
Missing tiles in new Anaconda: PyCharm Community 

### ISSUE THREAD

**Issue by Adham9** [ContinuumIO/anaconda-issues#12863]
Hello, 

I recently installed Anaconda and I cannot find the PyCharm community title (only the professional, see screenshot below). Any ideas how can I add PyCharm community to the navigator?
**Anaconda navigator version is 2.1.1 ( there is no message to update to 2.1.2)**
![image](https://user-images.githubusercontent.com/60254901/157442946-9ae5eb32-be35-4478-a004-2f3d2ac32fcc.png)

**Comment by csoja** [comment]
If you install PyCharm community on your machine, you should see the tile in the home tab of Navigator.  If not, you can then configure the install location under preferences.  There may have been a bug in one version, where it was not appearing properly.  You can upgrade Navigator to the latest in a terminal using conda, if you aren't seeing the option to upgrade from within the application.

**Comment by Adham9** [comment]
Thank you very much @csoja ! I Installed Pycharm and now it is visble. regarding upgrading to 2.1.2. I downgraded to 2.1.0 and then it was available to update to 2.1.2

**Comment by hemiphractus** [comment]
Pycharm CE will not be visible if installed in a non-default location, even if you try to set it in preferences.
