### ISSUE TITLE
conda build for 32bit python 2 stores build material in conda-bld/linux-64

### ISSUE THREAD

**Issue by merraksh** [ContinuumIO/anaconda-issues#1288]
Using conda 4.2.13 and conda-build 2.0.11 from the Conda 32bit distribution for Python 2, the command

conda build --python 2.7 my_package

creates build material in the directory conda-bld/linux-64

but I understand it should be in conda-bld/linux-32, in accordance with what happens with the same for the 32bit distribution for Python 3.

**Comment by msarahan** [comment]
What architecture is the parent system?  I'm guessing 64-bit.  Simply installing the 32-bit version of miniconda is insufficient - it does not ensure architecture match for built packages.  The basic reasoning is that the lower-level system tools and libraries necessary to support building are quite often architecture specific, even though Python code isn't really.

The only officially supported way to build 32-bit packages is on 32-bit systems.  There is, however, a different, more hackish, less guaranteed way to do it: set the CONDA_FORCE_32BIT environment variable:

CONDA_FORCE_32BIT=1 conda build --python 2.7 my_package

**Comment by merraksh** [comment]
Indeed the system is 64bit. I have anaconda installed on it, specifically four versions ({32,64} for Python {2,3}). I think I overlooked one (possibly legitimate) thing that Conda did: when running one version of Conda, instead of setting CONDA_ROOT I was running the absolute path of its executable, and when looking for the built stuff it was looking in the 64bit directory. 

I think this is actually a non-issue, please feel free to close it. Apologies for the trouble.

Also, thanks for the force-32bit hint, I'll definitely try it out.
