### ISSUE TITLE
install cvxopt_glpk

### ISSUE THREAD

**Issue by chivalry123** [ContinuumIO/anaconda-issues#1289]
Ok... inistally, all I want to do is to install cvxopt with glpk support porperly... I go through a lot a lot of diffuclties:

https://stackoverflow.com/questions/41069796/installing-glpk-cvxopt-with-conda

 In the end... cvxopt with glpk is not installed and the fortran environment I think is just totally messed up ... 

[me@server se]$ CVXOPT_BUILD_GLPK=1 pip install cvxopt

Collecting cvxopt

Installing collected packages: cvxopt

Successfully installed cvxopt-1.1.9

This does not mean installation is successfully.... please see below when i try to load the packages (this happens even if I do not use GLPK, my environment is totally cracked now)!

[me@sever se]$ ipython 

Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 

Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.

?         -> Introduction and overview of IPython's features.

%quickref -> Quick reference.

help      -> Python's own help system.

object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import cvxopt

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-1-14abf1b564a4> in <module>()

----> 1 import cvxopt

/home/me/anaconda2/lib/python2.7/site-packages/cvxopt/__init__.py in <module>()

     30 # You should have received a copy of the GNU General Public License

     31 

---> 32 import cvxopt.base

     33 

     34 def normal(nrows, ncols=1, mean=0.0, std=1.0):

ImportError: /home/me/anaconda2/lib/python2.7/site-packages/cvxopt/base.so: undefined symbol: _gfortran_st_write_done

Please help. Thank you

**Comment by nehaljwani** [comment]
`cvxopt` package on the conda-forge channel has been built with glpk support, as is evident from: https://github.com/conda-forge/cvxopt-feedstock/blob/master/recipe/build.sh#L16

You can get it by typing:

```bash
conda install -c conda-forge cvopt
```

**Comment by nehaljwani** [comment]
Reopen this issue if your request is to have this in the defaults channel.
