### ISSUE TITLE
zlib package v1.2.12 broken

### ISSUE THREAD

**Issue by njzjz** [ContinuumIO/anaconda-issues#12902]
I also created an issue in https://github.com/AnacondaRecipes/zlib-feedstock/issues/10

### Actual Behavior

`zlib.so` is missing in v1.2.12, which breaks a lot of downstream packages.

### Expected Behavior

It should exist like v1.2.11.

### Steps to Reproduce

Decompress https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.12-h7f8727e_0.tar.bz2

**Comment by csoja** [comment]
Thank you for the error report!  This broken packages was removed from repo.anaconda.com/pkgs/main yesterday.

**Comment by ScottBailey** [comment]
v1.2.12 b1 is now available.
