### ISSUE TITLE
Navigator Error An unexpected error occurred on Navigator start-up  5/5/2022 5:54 pm Arizona Time

### ISSUE THREAD

**Issue by naeemahaz** [ContinuumIO/anaconda-issues#12919]
Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Naeemah\.continuum\anaconda-client\config.yaml", position 0

It was working this morning.  Come on

**Comment by naeemahaz** [comment]
I uninstalled Anaconda and reinstalled it.  It still doesn't work. What's up?

**Comment by csoja** [comment]
Sounds like your anaconda-client configuration file got corrupted.  Those configuration files aren't automatically removed when you uninstall and reinstall Anaconda.  If you rename C:\Users\Naeemah.continuum\anaconda-client\config.yaml to C:\Users\Naeemah.continuum\anaconda-client\config.old and restart Navigator, I expect it will fix it.

**Comment by vshevchenko-anaconda** [comment]
Duplicate of #12762
