### ISSUE TITLE
Navigator Error -- update failed

### ISSUE THREAD

**Issue by bobsavage** [ContinuumIO/anaconda-issues#1292]
Anaconda Navigator Update error:

//anaconda/bin/python //anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.2: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.2*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.7', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.1.0;Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@bobsavage could you go to the command line and type

`$ conda update anaconda-navigator` ?

**Comment by bobsavage** [comment]
@goanpeca  I'm closing this, because i is being worked on under a different ticket. See https://github.com/ContinuumIO/anaconda-issues/issues/1313 which has a little more info.
