### ISSUE TITLE
Installing on Mac Monterey fails

### ISSUE THREAD

**Issue by mauricev** [ContinuumIO/anaconda-issues#12940]
### Actual Behavior
The installer fails.

### Expected Behavior
The installation should have proceeded uneventfully

### Steps to Reproduce
I don’t know if this issue is my computer specific. I just ran the installer; it ran to completion and failed. 

##### Anaconda or Miniconda version:
The installer is version 3-2022.05.

##### Operating System:
Mac 12.1

The install log seems to imply that sudo was needed for some reason, which I am assuming it shouldn’t need. The question is why did the system think sudo was needed. 

[install.log.zip](https://github.com/ContinuumIO/anaconda-issues/files/8741924/install.log.zip)

**Comment by csoja** [comment]
Does this help? https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#the-installation-failed-message-when-running-a-pkg-installer-on-osx

**Comment by mauricev** [comment]
No, my problem appears to be the opposite. Anaconda is trying to install as root when it should be trying to install as me.

**Comment by pseudoyim** [comment]
Hi @mauricev - Could you please try running this:
```ls -ld $HOME```

and then send us the output?

**Comment by mauricev** [comment]
A-ha! It turns out I have my home profile on a dedicated volume and it’s symlinked in /Users. The symlink itself was owned by root and admin like so:

```
lrwxr-xr-x  1 root  admin  15 Dec 22 17:09 /Users/maurice -> /Volumes/datahd
```

When I changed ownership of the symlink itself to me and staff, the installer just worked. Thank you for your help in this matter. Who would have known the ownership of a symlink made that kind of difference?

**Comment by sheebamoghal** [comment]
I'm facing the same problem

**Comment by codingYogi** [comment]
I also have the same issue, without any hint, the installer just sais "The installation failed."
