### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by arzachel23** [ContinuumIO/anaconda-issues#1294]
Anaconda Navigator Update error:

/Users/jasonwitherspoon/anaconda/bin/python /Users/jasonwitherspoon/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.2: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.2*
  - pyqtgraph -> pyqt 4.*
  - pyqtgraph -> python 2.7*|3.4*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'language': 'en', 'os': 'Darwin;16.1.0;Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64;x86_64;i386', 'pyqt': '4.11.4', 'version': '1.2.1', 'conda': '4.1.8', 'qt': '4.8.7', 'python': '3.5.2'}

**Comment by goanpeca** [comment]
Hi @arzachel23  the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
