### ISSUE TITLE
Enable win-arm64 as a platform on anaconda.org

### ISSUE THREAD

**Issue by chenghlee** [ContinuumIO/anaconda-issues#12957]
The community has expressed interest in building out PyData and other Python packages for Windows on ARM; e.g., the [Linaro project](https://www.linaro.org/windows-on-arm/). To better support this, we should add "win-arm64" as an officially supported package on anaconda.org

xref: conda/conda#11472.

**Comment by pbo-linaro** [comment]
Our goal is to help enable conda-forge for this new platform. Getting support from Anaconda is needed for this part.

**Comment by Solid-Snake-Jay** [comment]
Sounds Great! We can get working on this right away. To clarify a few things: when do you expect first packages to show up? Just so we can figure out whether we need to cut a quick patch release to add this? Or whether it can wait until our next release. 

> Our goal is to help enable conda-forge for this new platform. Getting support from Anaconda is needed for this part.

**Comment by pbo-linaro** [comment]
We can start to help immediately, by testing, and enabling some packages!
Depending on time frame for your next release (weeks, months?), it's possible to wait for it.

**Comment by pbo-linaro** [comment]
@chenghlee @Solid-Snake-Jay: Do you have any update or time estimation for this on anaconda side?

**Comment by Solid-Snake-Jay** [comment]
@pbo-linaro I will follow up with the team today. At this point, I have not received an update on the timeframe. We have our next release planned in about 3 weeks but I'll verify with the team if that timeframe fits with this enablement.

**Comment by pbo-linaro** [comment]
Thanks. Please let us know on this thread when you have update. 👍

**Comment by Solid-Snake-Jay** [comment]
Hi @pbo-linaro , the support for win-arm64 has been merged and should be shipped within release 2.37.0. As of right now I do not have a firm date on that release, but you should see that in early - mid Q3.

**Comment by pbo-linaro** [comment]
Great to see that!

When you talk about release 2.37.0, is that anaconda.org, or another thing you are talking about?

**Comment by GitHubJobutex** [comment]
I'm curious if this is still going to be released or was delayed. Looking at the release notes for August 2023 there was no mention of Windows on ARM as a supported platform.

Microsoft has officially started supporting Windows/ARM running as a VM inside of a Parallels hypervisor on the Mac with the M1/M2 chip. As more and more users begin utilizing this as their Windows development environments I would think Anaconda support for this would be important.

**Comment by csoja** [comment]
I think this happened last year - in 3Q2022.  On anaconda.org, during a search - there is the option for win-arm64.  Whether or not Anaconda or conda-forge or others are building packages for that platform is a different question.  I'm going to close this particular issue, as the original request that anaconda.org support the win-arm64 platform has been completed for some time.
