### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hamza-ghadyali** [ContinuumIO/anaconda-issues#1296]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - enum34 -> python 2.6*|2.7*|3.3*
  - python ==3.5.2
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.13', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.11', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Hi @hamza-ghadyali the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
