### ISSUE TITLE
All Users Installer on Windows for 3.4 version is missing colons in file paths

### ISSUE THREAD

**Issue by TheBeege** [ContinuumIO/anaconda-issues#1297]
When running the x86_64 installer of Anaconda for Python 3.4 on Windows 10, it hits an error listing several file paths stating that it's unable to open file for writing. With the exception of the first one, all of these file paths are missing the colon after the primary drive (often C). I imagine it should be an easy fix.

If anyone else runs into this issue, just install for the current user, and it appears to work fine.

**Comment by nehaljwani** [comment]
Closing as `Python 3.4` is no longer supported.
