### ISSUE TITLE
Anaconda3-2022.05-Windows-x86_64 Error loading  ... python39.dll

### ISSUE THREAD

**Issue by madeinaus** [ContinuumIO/anaconda-issues#12977]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

Anaconda installation. Win7-64, Home Premium, 
Install for 'just me' (with or without environment path) or 'all users'  
UAC turned off, Anti-virus turned off, run as Administrator.
No existing python installation.

Anaconda3-2022.05-Windows-x86_64.exe, fails at

> Extract: anaconda-2022.05-py39_0.tar.bz2
Error loading Python DLL 'C:\Users\User\AppData\Local\Temp\_MEI65722\python39.dll'.
LoadLibrary: The specified module could not be found.
Delete file: C:\apps\Anaconda3\pkgs\env.txt
Output folder: C:\apps\Anaconda3\conda-meta
Extract: history
Creating Anaconda3 menus...
Error loading Python DLL 'C:\Users\User\AppData\Local\Temp\_MEI56322\python39.dll'.
LoadLibrary: The specified module could not be found.

Without python39.dll, the installation has failed, and I get the subsequent error message for creating Anaconda3 menus.

### Conda info

```shell
>'conda' is not recognized as an internal or or external command, operable program or batch file
```

### Conda config

```shell
'conda' is not recognized as an internal or or external command, operable program or batch file
```

### Conda list

```shell
'conda' is not recognised as an internal or or external command, operable program or batch file
```

### Additional Context

Anaconda3-2020.07-Windows-x86_64.exe installs correctly (and I can see python38.dll extracted from the tar)

Anaconda3-2022.05-Windows-x86_64.exe starts to extract, I can see the temp folder, but the folder is deleted before I can check to see if python39.dll has been extracted. (I tried removing all delete permissions from the temp folder, but unzipping fails entirely with that setting).

As far as I can tell, I don't have an version of Anaconda or Conda or Python installed, in my path, in my environment, in my registry, or on my disk. In any case, the log suggests that the problem is on the previous line, with the failed extraction, not with running or locating the wrong version of python.

I haven't tried any other versions on this PC apart from 2020.07 (3.8), (works) and 2022.05 (3.9) (fails)

**Comment by ErikRtvl** [comment]
As far as I know, Python 3.9 does not work on Windows 7. So you need to stick with Python 3.8 or upgrade your Windows version. Given that Windows 7 is no longer supported, I suggest that you update to Windows 10.

**Comment by madeinaus** [comment]
Pleh. I didn't consider seriously the idea that Python 3.9 might be the problem, because I _already run python 3.9_.  Turns out that /later versions/ of 3.9 are incompatible, and the 2022.05 installer uses the later incompatible version of 3.9.

Also, I **looked** to see if Anaconda was incompatible, but everywhere I just saw "Windows". Turns out that the version of conda included in 2022.05 is _also_ incompatible with Win7-64 (for a different reason) so it doesn't work even if the installer hadn't flaked.

BTW, when I found the place telling me that Anaconda was incompatible, it told me to use a 2019 version --- which is odd, because I went back to using the 2020 version, which I already knew worked.

This whole saga was triggered by the need to use environment path variable, and I figured that rather than working out what the path values should be, I'd just update and select that option, which lead me down a trail of uninstalation, cleaning, failure -- which, if it had worked, wouldn't have given me the path value for 'all users' anyway.

**Comment by gnevan** [comment]
I have the same error installing Miniconda3-py38_23.1.0-1-Windows-x86_64.exe and Miniconda3-py38_22.11.1-1-Windows-x86_64.exe for Python 3.8 on Windows 7 SP1 x64 Professional.

> Error loading Python DLL 'C:\Users\admin\AppData\Local\Temp\_MEI65522\python39.dll'.

Why do they reference Python 3.9? Is it hard to fix?

**Comment by madeinaus** [comment]
The Anaconda version of python 3.9 does not work on Windows. This
realization came late for me, because I already had 3.9  on Win7/64,
as part of a utility and separately as part of an application.

MingW builds of 3.9 work on Win7, and any build compiled with a Win7
compatible version of Visual Studio works on Win7.

**Comment by keymou** [comment]
> Reference

I ran into the same problem and was wondering why the version that is adapted to python38 would refer to python39.dll，crap!
