### ISSUE TITLE
OpenSSL 1.1.1p causes dependency conflicts

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#12991]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

openssl
1.1.1p
linux-64 linux-ppc64le linux-s390x

### Problem

With the update from openssl 1.1.1o to 1.1.1p, the dependencies of the package changed.
It now requires libgcc-ng >=11.2.0, while before it worked with >= 7.5.0.

What used to be a trivial security update until 1.1.1o has now a major impact on our conda environments. I doubt that I can even integrate the new dependency with the r-base 3.6 package.

Please re-build 1.1.1p or 1.1.1q, and future updates of the 1.1.1 series, for compatibility with existing environments that have libgcc-ng versions 7.5, 8.x, or 9.x.

**Comment by skupr-anaconda** [comment]
We pinned GCC to 7.* in `openssl 1.1.1q` https://github.com/AnacondaRecipes/openssl-feedstock/pull/11
You can update it. 
Let us know if the issue persists.

**Comment by rolweber** [comment]
Thank you!

openssl 1.1.1q resolves this problem.
