### ISSUE TITLE
Update Spyder

### ISSUE THREAD

**Issue by ycwang-hello** [ContinuumIO/anaconda-issues#13001]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

Name: Spyder
Conda-Forge feedstock: [spyder](https://anaconda.org/conda-forge/spyder): [spyder-feedstock](https://github.com/conda-forge/spyder-feedstock)

Spyder [official site](https://www.spyder-ide.org/) and [GitHub](https://github.com/spyder-ide/spyder/)

### Problem

It seems that the Spyder in the defaults channel is still [v5.1.5](https://anaconda.org/anaconda/spyder), while the latest version is v5.3.2.
The old v5.1.5 version has several bugs with, e.g., [debugging](https://github.com/spyder-ide/spyder/issues/18608) and [input](https://github.com/spyder-ide/spyder/issues/18801). In fact, the bugs have already been fixed in their latest version. 
I suggest updating the Spyder in the defaults channel to the latest version. (People are constantly reporting these bugs to the [issues of Spyder](https://github.com/spyder-ide/spyder/issues).)

**Comment by Jamy-L** [comment]
It is very important, spyder debugging is currently unusable with anaconda, as downgrading to earlier versions is causing compatibility issues with the console. None of the solutions provided by the spyder team are convenient in my opinion, because they require to deal with many more troubles, and make everything harder

**Comment by Dan-Patterson** [comment]
They upgraded to 5.2.2 for some reason and not 5.3.2.
It would be nice to know the logic behind their upgrade policies.

**Comment by skupr-anaconda** [comment]
@ycwang-hello `spyder` was updated to **v5.3.3**.

@Dan-Patterson For updating to v5.3.3 were needed to update around 20 dependencies. Sometimes the chain of dependencies was a quite long, for example, `applaunchservices 0.3.0` (`pyobjc-core 8.5`  -> `pyobjc-framework-cocoa  8.5` -> `pyobjc-framework-fsevents  8.5` -> `pyobjc-framework-coreservices  8.5` -> `applaunchservices` -> `spyder`). But I guess `qt`, `pyqt`, and `pyqtwebengines` were the most difficult part.

**Comment by ycwang-hello** [comment]
> @ycwang-hello `spyder` was updated to **v5.3.3**.
> 
> @Dan-Patterson For updating to v5.3.3 were needed to update around 20 dependencies. Sometimes the chain of dependencies was a quite long, for example, `applaunchservices 0.3.0` (`pyobjc-core 8.5` -> `pyobjc-framework-cocoa 8.5` -> `pyobjc-framework-fsevents 8.5` -> `pyobjc-framework-coreservices 8.5` -> `applaunchservices` -> `spyder`). But I guess `qt`, `pyqt`, and `pyqtwebengines` were the most difficult part.

Happy to know that `spyder` has been updated. Since there seem to be no more problem here, I am closing this issue.
