### ISSUE TITLE
Pytorch conda repodata broken for osx arm64

### ISSUE THREAD

**Issue by atalman** [ContinuumIO/anaconda-issues#13006]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

We have following issues: 
https://github.com/pytorch/pytorch/issues/82483
https://github.com/pytorch/audio/issues/2536

The osx-arm64 files are in the conda repo:
osx-arm64/pytorch-1.12.0-py3.9_0.tar.bz2
osx-arm64/torchaudio-0.12.0-py39_cpu.tar.bz2

However when installing them using conda it does not work:

```
conda install pytorch torchvision torchaudio -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio

Current channels:

  - https://conda.anaconda.org/pytorch/osx-arm64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Bottom line: https://conda.anaconda.org/pytorch/osx-arm64/current_repodata.json needs to be properly rebuilt so that pytorch and its ecosystem can work again on osx arm64/M1 computers.

**Comment by skupr-anaconda** [comment]
`torchaudio` is available on the other platform (`osx-64`) of the `pytorch` channel https://conda.anaconda.org/pytorch/osx-64/ and **not** on `osx-arm64` https://conda.anaconda.org/pytorch/osx-arm64/

**Comment by seemethere** [comment]
> `torchaudio` is available on the other platform (`osx-64`) of the `pytorch` channel [conda.anaconda.org/pytorch/osx-64](https://conda.anaconda.org/pytorch/osx-64/) and **not** on `osx-arm64` [conda.anaconda.org/pytorch/osx-arm64](https://conda.anaconda.org/pytorch/osx-arm64/)
<img width="1015" alt="Screen Shot 2022-08-01 at 10 04 27 AM" src="https://user-images.githubusercontent.com/1700823/182204021-776ac6a6-b5ca-4ad8-ae4f-945f0ea322a7.png">

Appears as though the files exist within the [UI](https://anaconda.org/pytorch/torchaudio/files)?

**Comment by seemethere** [comment]
Note, this problem doesn't occur on conda version `4.11`, see https://github.com/pytorch/pytorch/issues/82428#issuecomment-1201527554

**Comment by divideconcept** [comment]
@seemethere even though you can see the files listed on anaconda website, the issue is that conda is actually reading the index from https://conda.anaconda.org/pytorch/osx-arm64/current_repodata.json and https://conda.anaconda.org/pytorch/osx-arm64/repodata.json and if you look at the content of these files, both are broken, only listing Pytorch 1.11 and not Pytorch 1.12 or any package such as torchvision or torchaudio.

**Comment by skupr-anaconda** [comment]
@atalman @seemethere It seems like it's already fixed https://conda.anaconda.org/pytorch/osx-arm64/

**Comment by barabo** [comment]
Last week the `pytorch` channel was activated in the Cloudflare CDN to alleviate performance issues for users in the Pacific region.  The process that clones package updates into the CDN appears to have had some problems.  We have bypassed the CDN for now while we investigate the cloning process.

**Comment by divideconcept** [comment]
I confirm the issue seems to be fixed here too.

**Comment by seemethere** [comment]
@atalman this can probably be closed now
