### ISSUE TITLE
Please update Shapely package (current included version not compatible with latest numpy)

### ISSUE THREAD

**Issue by jorisvandenbossche** [ContinuumIO/anaconda-issues#13008]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

Name: shapely
Source: https://github.com/shapely/shapely
Conda-forge feedstock: https://github.com/conda-forge/shapely-feedstock/

### Problem

The current version available in the defaults channel is 1.7.1 (dating from August 2020). Shapely 1.8.0 was already released in October 2021 (and it's now at 1.8.2). 

The 1.7.1 version is no longer compatible with the latest numpy release 1.23. Thus, when creating a new environment with just the latest available versions of shapely and numpy, you will currently get errors. This is fixed with shapely 1.8.

**Comment by skupr-anaconda** [comment]
shapely 1.8.4 is already available

**Comment by jorisvandenbossche** [comment]
Indeed, so closing
