### ISSUE TITLE
setuptools 27.2 on default channel is missing dependency

### ISSUE THREAD

**Issue by michaelaye** [ContinuumIO/anaconda-issues#1300]
The last version (27.2) of setuptools on default channel is missing certifi in its dependency list, while all other versions show it.
This creates problems with installing GH masters from repos, see for example https://github.com/jupyter/notebook/issues/1977

**Comment by nehaljwani** [comment]
Related: https://github.com/conda-forge/setuptools-feedstock/commit/a9d30a45343c1dc8d970afda25197a74d1448104

**Comment by michaelaye** [comment]
obsolete
