### ISSUE TITLE
Windows error: Failed to create Anaconda menus or Failed to add Anaconda to the system PATH

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [ContinuumIO/anaconda-issues#13005]
### Checklist

![Untitled-1](https://user-images.githubusercontent.com/45887282/182028488-11cf3d25-de17-4756-8506-c71733cd8689.jpg)

### What happened?

Hello, I tried your fix, removed all PATH, JAVA, PYTHON env variables, no python installed, cleared all temp files, appdata, roaming, local, programs. Why is this Installer still causing trouble?

**Comment by ntucker-anaconda** [comment]
Are you able to get the packages you need using Miniconda? We will add this bug to the backlog for further investigation at some point.
