### ISSUE TITLE
Spyder won't start in Anaconda - could not find or load the Qt platform plugin "xcb" - problem and solution.

### ISSUE THREAD

**Issue by DougWellington** [ContinuumIO/anaconda-issues#1301]
<h1>Problem</h1>
<p>I'm using Anaconda 4.2.0 for Python 2.7 on a Linux system.  If I install Anaconda as root, then only the root user can work with Spyder.  (There may be problems with other apps as well; I've only worked with Spyder so far.)  All other users get this error when trying to use Spyder:</p>

<blockquote>
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Abort (core dumped)
</blockquote>

<h1>Quick Fix</h1>
<p>After some troubleshooting, I realized that some files were not readable by world.  That is, if you weren't the root user or in the root group, you couldn't access those files.  You can find the files with this command in the anaconda directory:</p>

<pre>find . ! -perm /o=r -ls</pre>

<p>In my case, these are the files I found:</p>

<pre>
189716    4 -rwxr-x---   2 root     root          766 Sep 13 21:29 ./bin/.dbus-post-link.sh
166285    4 -rwxr-x---   1 root     root          125 Dec 16 17:40 ./bin/qt.conf
196343    4 -rw-------   2 root     root         1254 Mar 25  2015 ./LICENSE.rst
198013  180 -rwsr-x---   1 root     root       176268 Dec 16 17:40 ./libexec/dbus-daemon-launch-helper
261680    4 -rwxrwx---   2 root     root           21 Nov 30  2015 ./lib/python2.7/site-packages/cairo/__init__.py
261669    8 -rw-rw----   2 root     root         7489 Nov 30  2015 ./include/pycairo/pycairo.h
190341    4 -rwxrwx---   1 root     root          734 Sep 13 21:28 ./pkgs/libxcb-1.12-0/info/recipe/meta.yaml
190314    4 -rwxrwx---   1 root     root           73 Sep 13 17:48 ./pkgs/libxcb-1.12-0/info/recipe/build.sh
190340    4 -rwxrwx---   1 root     root          485 Sep 13 17:48 ./pkgs/libxcb-1.12-0/info/recipe/meta.yaml.template
138744    4 -rwxrwx---   1 root     root          998 Jun 26 23:10 ./pkgs/harfbuzz-0.9.39-1/info/recipe/meta.yaml
138729    4 -rwxrwx---   1 root     root          115 Jun 26 23:10 ./pkgs/harfbuzz-0.9.39-1/info/recipe/build.sh
261512    4 -rw-------   1 root     root         1061 Jan 19  2016 ./pkgs/py-1.4.31-py27_0/info/LICENSE.txt
197493    4 -rwxrwx---   1 root     root          416 Jun 30 12:14 ./pkgs/gst-plugins-base-1.8.0-0/info/recipe/meta.yaml
197492    4 -rwxrwx---   1 root     root          410 Jun 30 12:14 ./pkgs/gst-plugins-base-1.8.0-0/info/recipe/build.sh
197716    4 -rwxrwx---   1 root     root          394 Jun 30 12:13 ./pkgs/gstreamer-1.8.0-0/info/recipe/meta.yaml
197717    4 -rwxrwx---   1 root     root          410 Jun 30 12:13 ./pkgs/gstreamer-1.8.0-0/info/recipe/build.sh
262723    4 -rwxrwx---   1 root     root         1111 Jul 11 15:18 ./pkgs/pyqt-5.6.0-py27_0/info/recipe/meta.yaml
262689    4 -rwxrwx---   1 root     root          351 Jul 11 15:18 ./pkgs/pyqt-5.6.0-py27_0/info/recipe/build.sh
262697    4 -rwxrwx---   1 root     root          574 Jul 11 15:18 ./pkgs/pyqt-5.6.0-py27_0/info/recipe/run_test.py
262687    4 -rwxrwx---   1 root     root          256 Jul 11 15:18 ./pkgs/pyqt-5.6.0-py27_0/info/recipe/bld.bat
263467 19180 -rwxrwx---   1 root     root     19612602 Jul 11 15:18 ./pkgs/pyqt-5.6.0-py27_0/info/recipe/sys
196343    4 -rw-------   2 root     root         1254 Mar 25  2015 ./pkgs/filelock-2.0.6-py27_0/LICENSE.rst
261680    4 -rwxrwx---   2 root     root           21 Nov 30  2015 ./pkgs/pycairo-1.10.0-py27_0/lib/python2.7/site-packages/cairo/__init__.py
261669    8 -rw-rw----   2 root     root         7489 Nov 30  2015 ./pkgs/pycairo-1.10.0-py27_0/include/pycairo/pycairo.h
189716    4 -rwxr-x---   2 root     root          766 Sep 13 21:29 ./pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh
190103  180 -rwsr-x---   1 root     root       176268 Sep 13 21:29 ./pkgs/dbus-1.10.10-0/libexec/dbus-daemon-launch-helper
189710    4 -rwxrwx---   1 root     root          661 Sep 13 17:48 ./pkgs/dbus-1.10.10-0/info/recipe/post-link.sh.Darwin
189718    4 -rwxrwx---   1 root     root          794 Sep 13 21:29 ./pkgs/dbus-1.10.10-0/info/recipe/meta.yaml
189705    4 -rwxrwx---   1 root     root          415 Sep 13 17:48 ./pkgs/dbus-1.10.10-0/info/recipe/build.sh
189706    4 -rwxrwx---   1 root     root          531 Sep 13 17:48 ./pkgs/dbus-1.10.10-0/info/recipe/meta.yaml.template
189717    4 -rwxrwx---   1 root     root          766 Sep 13 17:48 ./pkgs/dbus-1.10.10-0/info/recipe/post-link.sh.Linux
272037    4 -rwxr-x---   1 root     root          201 Sep 16 15:28 ./pkgs/qt-5.6.0-0/bin/qt.conf
272320    4 -rwxrwx---   1 root     root         1048 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/write_qtconf.bat
272207    4 -rwxrwx---   1 root     root          646 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0002-qtwebkit-ruby-1.8.patch
272333    4 -rwxrwx---   1 root     root         1158 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0006-zlib_dependency-Add-EXTRA_INCLUDEPATH-for-system-zli.patch
272340    4 -rwxrwx---   1 root     root         1221 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0001-qtwebengine-Darwin-remove-Xcode-and-kernel-min-versions.patch
272399    4 -rwxrwx---   1 root     root         1899 Sep 16 18:36 ./pkgs/qt-5.6.0-0/info/recipe/meta.yaml
272846    4 -rwxrwx---   1 root     root         3489 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/obvci_appveyor_python_build_env.cmd
272274    4 -rwxrwx---   1 root     root          923 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0002-qtwebengine-moz-libvpx-apple-clang.patch
272350    4 -rwxrwx---   1 root     root         1342 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/issue1244883002_1.diff
272797    4 -rwxrwx---   1 root     root         3240 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0004-VS2008-Add-typedefs-for-more-int-_t-and-define-_STDI.patch
272347    4 -rwxrwx---   1 root     root         1310 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0002-angle-Add-Scott-Meyer-s-nullptr-emulation.patch
273167    8 -rwxrwx---   1 root     root         6247 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/v4l2.patch
273040    8 -rwxrwx---   1 root     root         4931 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/build.sh
271958    4 -rwxrwx---   1 root     root          170 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/yum_requirements.txt
272415    4 -rwxrwx---   1 root     root         1954 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/win8_sdk_path.patch
273238    8 -rwxrwx---   1 root     root         7728 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/issue1228063005_1_10001.diff
273135    8 -rwxrwx---   1 root     root         5813 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/avx2.patch
273042    8 -rwxrwx---   1 root     root         4956 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/meta.yaml.template
272384    4 -rwxrwx---   1 root     root         1756 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/vs2015_update2_warnings.patch
272355    4 -rwxrwx---   1 root     root         1455 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0001-shobjidl-Fix-compile-guard-around-SHARDAPPIDINFOLINK.patch
272605    4 -rwxrwx---   1 root     root         2623 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0008-qtbase-Ubuntu-disable_overlay_scrollbars.patch
272658    4 -rwxrwx---   1 root     root         2793 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/notes.md
272330    4 -rwxrwx---   1 root     root         1111 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/patch_prefix_files.py
272438    4 -rwxrwx---   1 root     root         2073 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0003-qtwebengine-builtin_bswap16-for-clang-4_3.patch
272394    4 -rwxrwx---   1 root     root         1877 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0004-qtwebkit-CentOS5-Fix-fucomip-compat-with-gas-2.17.50.patch
272987    8 -rwxrwx---   1 root     root         4402 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0001-angle-Split-DirectX-headers-and-libraries-out-from-c.patch
271819    4 -rwxrwx---   1 root     root           50 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/run_test.sh
272253    4 -rwxrwx---   1 root     root          817 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0005-Remove-unused-include-sys-signalfd.h.patch
272034    4 -rwxrwx---   1 root     root          201 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/qt.conf
272312    4 -rwxrwx---   1 root     root         1011 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0010-qtbase-XCB-Auto-detect-xcb-glx-also-with-xcb-qt.patch
273165    8 -rwxrwx---   1 root     root         6194 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/bld.bat
272765    4 -rwxrwx---   1 root     root         3133 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0005-qtwebkit-fix-TEXTREL-on-x86-changeset_172759.patch
271946    4 -rwxrwx---   1 root     root          166 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/test/main.cpp
271909    4 -rwxrwx---   1 root     root          126 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/test/hello.pro
272631    4 -rwxrwx---   1 root     root         2703 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0001-qtwebkit-old-ld-compat.patch
272336    4 -rwxrwx---   1 root     root         1170 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0003-angle-Add-c-begin-end-iterators.patch
272228    4 -rwxrwx---   1 root     root          737 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/README.md
272998    8 -rwxrwx---   1 root     root         4501 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/avx1.patch
272265    4 -rwxrwx---   1 root     root          870 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/avx.patch
272315    4 -rwxrwx---   1 root     root         1018 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0009-qtbase-Reduce-gtk-2-version-from-2.18-to-2.10.patch
273548   40 -rwxrwx---   1 root     root        39255 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/tst_compiler.cpp
272368    4 -rwxrwx---   1 root     root         1598 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0003-qtwebkit-O_CLOEXEC-workaround.patch
272582    4 -rwxrwx---   1 root     root         2561 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0001-Don-t-re-typedef-int-_t-if-_STDINT-is-defined.patch
272294    4 -rwxrwx---   1 root     root          959 Sep 13 18:22 ./pkgs/qt-5.6.0-0/info/recipe/0007-qtbase-CentOS5-Do-not-use-strict_c++.patch
</pre>

<p>To fix the permissions, I just went ahead and set both read and execute on those files:</p>

<pre>find . ! -perm /o=r -exec chmod o+rx {} \;</pre>

<p>Now all users can run spyder.</p>

<h1>Permanent Solution</h1>
<p>I think the problem will be solved if the Anaconda build scripts are modified to make sure all packages are installed with proper permissions,</p>

**Comment by ccordoba12** [comment]
Thanks for the solution. Pinging @mingwandroid about this one.

**Comment by mingwandroid** [comment]
Qt 5.6.0 is quite old and I don't *think* this is a problem with 5.6.2. I need to rebuild Linux 64-bit Qt 5.6.2 soon anyway so I'll make sure it's all `o+w`.

**Comment by ccordoba12** [comment]
Ok, closing then. Thanks @mingwandroid for chiming in :-)

**Comment by mingwandroid** [comment]
Qt 5.6.2-2 for Linux 64 has been released now. I eyeballed the o+r permissions and they looked correct.

**Comment by MadhuPasula** [comment]
I get this Error: 
"FIND: Invalid switch"
