### ISSUE TITLE
Please update multidict for Python 3.10

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#13020]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

multidict
https://pypi.org/project/multidict/#history

### Problem

The latest version on Anaconda main is 5.2.0, built only for Python 3.9, 3.8, 3.7.
The older version 5.1.0 on Anaconda main was also built for Python 3.10 and 3.6.

The latest version on PyPI is 6.0.2.

Please build a recent version of multidict for Python 3.10. I suggest to update the package to 6.0.2.
If there are concerns about the major version update, rebuilding 5.2.0 for Python 3.10 would also help.

### Additional Context

I'm currently migrating a Python 3.9 environment to Python 3.10, and this issue causes a package downgrade.

**Comment by skupr-anaconda** [comment]
Now `multidict 5.2.0` has python 3.10 support and it's available on the defaults channel

**Comment by rolweber** [comment]
Thanks a lot!
