### ISSUE TITLE
Unable to access anaconda.com - 403 fobidden

### ISSUE THREAD

**Issue by argyrodagdileli** [ContinuumIO/anaconda-issues#13035]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

Hi,

I am trying to download and setup anaconda but I am unable to download the executable.
Every link to anaconda.com results in `403 Forbidden`
I am able to access `https://anaconda.org` and `https://docs.anaconda.com/` with no issue

**Comment by LoonSongSoftware** [comment]
Same issue here.  Hopefully, whoever's managing the web server will see this soon!

**Comment by argyrodagdileli** [comment]
Looks like it's accessible again.
