### ISSUE TITLE
Please update sparkmagic (and friends) to 0.20.0, for compatibility with ipykernel 6

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#13032]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

sparkmagic
https://github.com/jupyter-incubator/sparkmagic/releases/tag/0.20.0
https://pypi.org/project/sparkmagic/#history

autovizwidget
https://pypi.org/project/autovizwidget/#history

hdijupyterutils
https://pypi.org/project/autovizwidget/#history

### Problem

Latest sparkmagic on Anaconda main is 0.19.1. That version is not compatible with ipykernel 6.

Please update sparkmagic to the latest 0.20.0, which provides compatibility with ipykernel 6.
The current dependency spec `ipykernel <6.0.0` must be updated. 

Please keep autovizwidget and hdijupyterutils in sync with sparkmagic.

### Additional Context

`conda search --info sparkmagic=0.19.1`
```txt
Loading channels: done
sparkmagic 0.19.1 pyhd3eb1b0_0
------------------------------
file name   : sparkmagic-0.19.1-pyhd3eb1b0_0.conda
name        : sparkmagic
version     : 0.19.1
build       : pyhd3eb1b0_0
build number: 0
size        : 74 KB
license     : BSD-3-Clause
subdir      : noarch
url         : https://repo.anaconda.com/pkgs/main/noarch/sparkmagic-0.19.1-pyhd3eb1b0_0.conda
md5         : ce5cf0c34c3dfa374453da7aa84814e7
timestamp   : 2021-10-06 13:02:34 UTC
dependencies: 
  - autovizwidget >=0.6
  - hdijupyterutils >=0.6
  - ipykernel <6.0.0
  - ipython >=4.0.2
  - ipywidgets >5.0.0
  - mock
  - nose
  - notebook >=4.2
  - numpy
  - pandas >=0.17.1
  - python
  - requests
  - requests-kerberos >=0.8.0
  - tornado >=4
```

**Comment by rolweber** [comment]
`autovizwidget` is released in sync with `sparkmagic`, please update both packages.

**Comment by rolweber** [comment]
`hdijupyterutils` is also released in sync with `sparkmagic`, please update all three packages.

**Comment by skupr-anaconda** [comment]
`hdijupyterutils`, `autovizwidget`, and `sparkmagic` were updated to the vesrion `0.20.0`. 
@rolweber Could you check if all works as expected?

**Comment by rolweber** [comment]
@skupr-anaconda Thanks. I found eight out of nine packages, but I'm missing `sparkmagic 0.20.0` for linux-ppc64le.
The other two packages are available for all three platforms I'm working with: linux-64, linux-ppc64le, and linux-s390x.

**Comment by skupr-anaconda** [comment]
Thanks for reporting, @rolweber. I've found out why it was missing. And now it's available:
https://repo.anaconda.com/pkgs/main/linux-ppc64le
sparkmagic-0.20.0-py310h6ffa863_1.tar.bz2
sparkmagic-0.20.0-py37h6ffa863_1.tar.bz2
sparkmagic-0.20.0-py38h6ffa863_1.tar.bz2
sparkmagic-0.20.0-py39h6ffa863_1.tar.bz2

**Comment by rolweber** [comment]
Thanks a lot, I can install the package now!
