### ISSUE TITLE
Please build pyspnego for py310 on ppc64le

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#13034]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

pyspnego
https://pypi.org/project/pyspnego/#history

### Problem

The Anaconda main channel has `pyspnego 0.3.1` for platforms linux-64, linux-ppc64le, and linux-s390x. However, the py310 build of the package is missing for linux-ppc64le.

The latest version of pyspnego on PyPI is 0.6.0, in case you want to update. Version 0.3.1 is from last October, there have been several releases this year.

### Additional Context

pyspnego is a dependency of requests-kerberos 0.14.0. I can only install requests-kerberos 0.12.0 on linux-ppc64le at the moment.

**Comment by skupr-anaconda** [comment]
Now `pyspnego 0.3.1` has python 3.10 support for the `ppc64le` platform and it's available on the defaults channel

**Comment by rolweber** [comment]
Thanks a lot!
