### ISSUE TITLE
Hello, the Spyder IDE Team is saying this is an Anaconda issue

### ISSUE THREAD

**Issue by Satoshi-Nakamoto69** [ContinuumIO/anaconda-issues#13041]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

Anaconda Navigator

I'm having trouble running the Spyder IDE, and the Spyder team is saying this is an Anaconda issue

### Problem

![image](https://user-images.githubusercontent.com/55071104/189564753-86d89af6-46af-41da-bf5b-9379ea1ded24.png)

### Additional Context

Please refer to ticket #19316 on Spyder's GitHub page

**Comment by vshevchenko-anaconda** [comment]
https://github.com/spyder-ide/spyder/issues/19316

**Comment by Satoshi-Nakamoto69** [comment]
FYI, the only solution I have found so far to this issue was to uninstall Anaconda and all associated files and install spyder alone from their website. 
Spyder is now working again for me.
To confirm, it does sound like an issue with Anaconda. 
I hope this feedback is helpful because Anaconda looked cool to me, and I hope to try it again if it gets fixed and some other tools are included.

Cheers,

**Comment by pseudoyim** [comment]
Hi @Satoshi-Nakamoto69. We're sorry for the delay in responding to your issue, and we're glad you were able to resolve it by installing the Spyder installer.

After reviewing [your original issue](https://github.com/spyder-ide/spyder/issues/19316), my best guess is: 
You had two installations of _Anaconda Distribution_ on your system and these were somehow conflicting with each other. The two installation paths I noticed were:
```
C:\Users\Mitchell\anaconda3\
C:\ProgramData\Anaconda3\
```
If you had `spyder` installed in one location, your attempt at updating it in the other location could explain the problem you were seeing. But we would have needed more information to fully debug the issue.

Please let us know if you have any future Anaconda-related issues.
