### ISSUE TITLE
[Question] package: IPython | version: 8.x | platform: win64

### ISSUE THREAD

**Issue by Diogo-Rossi** [ContinuumIO/anaconda-issues#13079]
### Checklist

- [X] I added a descriptive title (including the requested package **name**, **version**, and **platform**).
- [X] I searched the defaults channels ([Python](https://repo.anaconda.com/pkgs/main/) and [R](https://repo.anaconda.com/pkgs/r/)) and did not find the package I'm requesting.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and did not find a duplicate request for this package.

### Request type

- [ ] New (i.e. no versions of this package currently exist on repo.anaconda.com)
- [X] Update (i.e. older versions of this package exist and I'm requesting an updated version)
- [ ] Rebuild (i.e. something is wrong with an existing version of this package and it needs to be rebuilt)

### Name

ipython

### Version

8.x

### Platform(s)

windows 64

### Location of source code

https://github.com/ipython/ipython

### Conda-Forge feedstock

N/A

# Question
I would like to understand some of the selected version in new releases.
Why the new [release of Anaconda installer](https://www.anaconda.com/blog/anaconda-distribution-2022-10) does not came with **IPython 8.x**?
It is already available in the default channel (8.4) for all platforms (https://anaconda.org/anaconda/ipython)
But the current version in  the installer is 7.31

**Comment by dong-zeyu** [comment]
I believe it should be a bug. Because the official [release note](https://docs.anaconda.com/anaconda/reference/release-notes/) indicates it should have been upgraded to ipython 8.4.0

**Comment by dong-zeyu** [comment]
I find out it should be the result of this commit
https://github.com/spyder-ide/spyder-kernels/commit/1fded8649148f76173c3a289985254e396ab4454
We need to wait until spyder accepts higher version of ipython

**Comment by Diogo-Rossi** [comment]
@dong-zeyu Thankyou! Question answered.
