### ISSUE TITLE
VirusTotal (Zillya) claims that miniconda3 contains "Trojan.Filecoder.Script.44"

### ISSUE THREAD

**Issue by Naxey** [ContinuumIO/anaconda-issues#13071]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

Uploading the "Miniconda3-latest-Windows-x86_64.exe" to VirusTotal responds with the detection of "Trojan.Filecoder.Script.44"

[https://www.virustotal.com/gui/file/1acbc2e8277ddd54a5f724896c7edee112d068529588d944702966c867e7e9cc](url)

**Comment by barabo** [comment]
Thanks @Naxey for bringing this to our attention!  We contacted Zillya to see if they would correct the issue on their end.  This is clearly a false-positive, but we were not watching `virustotal.com` following our releases before today.

Going forward I think we'll be keeping an eye on that site for such instances.

Until Zillya updates their categorization of the binary, there's nothing more we can do.

**Comment by codingbutstillalive** [comment]
As of today, the problem still persists: Zillya reports "Trojan.Disco.Script.781" for Miniconda3-py10.
