### ISSUE TITLE
numpy-base 1.23.3 is missing for linux-ppc64le

### ISSUE THREAD

**Issue by npanpaliya** [ContinuumIO/anaconda-issues#13088]
### Checklist

- [X] I added a descriptive title (including the requested package **name**, **version**, and **platform**).
- [X] I searched the defaults channels ([Python](https://repo.anaconda.com/pkgs/main/) and [R](https://repo.anaconda.com/pkgs/r/)) and did not find the package I'm requesting.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and did not find a duplicate request for this package.

### Request type

- [ ] New (i.e. no versions of this package currently exist on repo.anaconda.com)
- [x] Update (i.e. older versions of this package exist and I'm requesting an updated version)
- [ ] Rebuild (i.e. something is wrong with an existing version of this package and it needs to be rebuilt)

### Name

numpy-base

### Version

1.23.3

### Platform(s)

linux-ppc64le

### Reason for this request

numpy 1.23.3 is available for linux-ppc64le but not numpy-base. We need numpy-base 1.23.3 for linux ppc64le as well.

**Comment by skupr-anaconda** [comment]
Could you update it to **v1.23.4**?
It's available in the main channel:
https://repo.anaconda.com/pkgs/main/linux-ppc64le
numpy-base-1.23.4-py310hac71eb6_0.conda
numpy-base-1.23.4-py310hac71eb6_0.tar.bz2
numpy-base-1.23.4-py38h1bde650_0.conda
numpy-base-1.23.4-py38h1bde650_0.tar.bz2
numpy-base-1.23.4-py39h1bde650_0.conda
numpy-base-1.23.4-py39h1bde650_0.tar.bz2

**Comment by npanpaliya** [comment]
Yes, we have updated it to 1.23.4. Thank you!
