### ISSUE TITLE
the installer encountered an error that caused the installation to fail. 

### ISSUE THREAD

**Issue by DeDon82** [ContinuumIO/anaconda-issues#13086]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

similar issue to some that have been raised regarding the installation of anaconda. but in my case even by deleting the installation folder i couldn't then re install anaconda. 
the log file returns: "install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Anaconda3-2022.10-MacOSX-x86_64.pkg”"
not sure how to get around this, any help will be greatly appreciated as i used to have anaconda installed few years ago and it worked fine. 

### Expected behavior or outcome

anaconda installation

**Comment by mfripp** [comment]
Is your problem the same as https://github.com/ContinuumIO/anaconda-issues/issues/13089? i.e., are you trying to install "for me only" using a non-administrator account? If so, you may be able to fix it by temporarily converting the account to an administrator and then installing "for me only", or by using the [2021.11 installer](https://repo.anaconda.com/archive/).

**Comment by astyve** [comment]
Same problem here. Tried installing on my MacBookPro 2018 (Intel Core i7). I am an administrator on the Mac, but still got the "An issue occurred during installation"-message at the end of installation. Could not start the app after the installation either.
Tried removing the .app-file, and the folder under user/opt and re-installing, but same result.

**Comment by alexcw-5** [comment]
I'm also having the same issue

**Comment by DeDon82** [comment]
sorted!
