### ISSUE TITLE
libffi package bug (The filename libffi.7.so should be libffi.so.7)

### ISSUE THREAD

**Issue by jinzhen-lin** [ContinuumIO/anaconda-issues#13098]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

Hi, I installed latest [`libffi`](https://anaconda.org/anaconda/libffi)  package from anaconda channel and found that the library file `libffi.so.7` doesn't exists. And I then found that the filename of `libffi.so.7` is typo to `libffi.7.so` and the filename of `libffi.so.8` is typo to `libffi.8.so`.

Here is the content of `libffi-3.4.2-h295c915_4/lib` :
```
$ ll
total 172
drwxrwsr-x 3 username username  4096 Nov 21 14:52 ./
drwxrwsr-x 6 username username  4096 Nov 21 14:52 ../
lrwxrwxrwx 1 username username    11 Jun 11 00:29 libffi.7.so -> libffi.8.so
-rw-rw-r-- 2 username username 91958 Jun 11 00:29 libffi.a
lrwxrwxrwx 1 username username    15 Jun 11 00:29 libffi.so -> libffi.so.8.1.0*
lrwxrwxrwx 1 username username    15 Jun 11 00:29 libffi.so.8 -> libffi.so.8.1.0*
-rwxrwxr-x 2 username username 68048 Jun 11 00:29 libffi.so.8.1.0*
drwxrwsr-x 2 username username  4096 Nov 21 14:52 pkgconfig/
```

### Expected behavior or outcome

The filename `libffi.7.so` should be `libffi.so.7` and the filename `libffi.8.so` should be `libffi.so.8` .

**Comment by skupr-anaconda** [comment]
@jinzhen-lin It seems like the issue was fixed https://github.com/AnacondaRecipes/libffi-feedstock/pull/12/files
Could you check if it persists?

**Comment by jinzhen-lin** [comment]
Yes, it was fixed by this pr. Thank you.
