### ISSUE TITLE
PyQt missing SVG, JPG, TIFF and other support in QImageReader

### ISSUE THREAD

**Issue by 3five8** [ContinuumIO/anaconda-issues#131]
The pyqt available through `conda install pyqt` only supports the following.

> > print QtGui.QImageReader.supportedImageFormats()
> > [PyQt4.QtCore.QByteArray('bmp'), PyQt4.QtCore.QByteArray('pbm'), PyQt4.QtCore.QByteArray('pgm'), PyQt4.QtCore.QByteArray('png'), PyQt4.QtCore.QByteArray('ppm'), PyQt4.QtCore.QByteArray('xbm'), PyQt4.QtCore.QByteArray('xpm')]

The Qt4 documentation list several more.
- BMP  Windows Bitmap
- GIF  Graphic Interchange Format (optional)
- JPG  Joint Photographic Experts Group
- JPEG Joint Photographic Experts Group
- MNG  Multiple-image Network Graphics
- PNG  Portable Network Graphics
- PBM  Portable Bitmap
- PGM  Portable Graymap
- PPM  Portable Pixmap
- TIFF Tagged Image File Format
- XBM  X11 Bitmap
- XPM  X11 Pixmap
- SVG  Scalable Vector Graphics
- TGA  Targa Image Format

Could this be due to missing configuration during compilation?

I am running conda 3.5.5 on Win32.

**Comment by ccordoba12** [comment]
@Nodd could you test if this is fixed in the latest packages provided by conda?

**Comment by dannyfier** [comment]
It does not

**Comment by jepebe** [comment]
On OSX the latest version PyQt4 does not have JPEG/JPG.

**Comment by dannyfier** [comment]
On Ubuntu 15.10 and Windows 10 the latest version of PyQt4 does not have JPEG/JPG support

**Comment by ccordoba12** [comment]
The `plugins` location has changed. Now it is at

    /<path-to-Anaconda-or-env>/lib/qt4/plugins

Please verify that it's working for you.

**Comment by jepebe** [comment]
These are the files in /anaconda/lib/qt4/plugins
```
libqgif.dylib
libqico.dylib
libqjpeg.dylib
libqmng.dylib
libqsvg.dylib
libqtga.dylib
libqtiff.dylib
```

While this is the output of `print(QImageReader.supportedImageFormats())`

`[PyQt4.QtCore.QByteArray('bmp'), PyQt4.QtCore.QByteArray('gif'), PyQt4.QtCore.QByteArray('ico'), PyQt4.QtCore.QByteArray('mng'), PyQt4.QtCore.QByteArray('pbm'), PyQt4.QtCore.QByteArray('pgm'), PyQt4.QtCore.QByteArray('png'), PyQt4.QtCore.QByteArray('ppm'), PyQt4.QtCore.QByteArray('svg'), PyQt4.QtCore.QByteArray('svgz'), PyQt4.QtCore.QByteArray('tga'), PyQt4.QtCore.QByteArray('tif'), PyQt4.QtCore.QByteArray('tiff'), PyQt4.QtCore.QByteArray('xbm'), PyQt4.QtCore.QByteArray('xpm')]`

**Comment by jepebe** [comment]
I also added these paths with the same result.
```
QCoreApplication.addLibraryPath("%s/anaconda/lib/qt4" % user_path)
QCoreApplication.addLibraryPath("%s/anaconda/lib/qt4/plugins" % user_path)
QCoreApplication.addLibraryPath("%s/anaconda/lib/qt4/plugins/imageformats" % user_path)
```

**Comment by ccordoba12** [comment]
So the only unsupported one is Jpeg, but I don't know why as we provide the Qt plugin for it :-/

**Comment by jepebe** [comment]
Anything else I can do to debug this?

**Comment by brylie** [comment]
I am unable to render SVG images in Orange3 when Anaconda is installed. Here are my available image formats:

```py
>>> print("PyQt4 installed in", os.path.dirname(PyQt4.__file__))
PyQt4 installed in /home/brylie/anaconda3/lib/python3.5/site-packages/PyQt4
>>> print("Qt4 library paths", QApplication.libraryPaths())
Qt4 library paths []
>>> print([bytes(f).decode("ascii") for f in QImageReader.supportedImageFormats()])
['bmp', 'pbm', 'pgm', 'png', 'ppm', 'xbm', 'xpm']
```

**Comment by brylie** [comment]
As a previous comment suggested, I looked under the anaconda folder in my home directory. I found the following:

- ~/anaconda3/lib/qt4/plugins/iconengines
  - libqsvgicon.so
- ~/anaconda3/lib/qt4/plugins/imageformats
  - libqgif.so
  - libqjpeg.so
  - libqsvg.so
  - libqtiff.so
  - libqico.so
  - libqmng.so
  - libqtga.so

I notice SVG in both locations, but am unable to render SVG icons in orange3 (see above).

**Comment by astaric** [comment]
I am experiencing the same problem with anaconda 4.1.6 on OSX (missing SVG support).

I can work around the issue by moving the qt.conf from anaconda/bin to anaconda/python.app/Contents/Resources.

**Comment by brylie** [comment]
Thanks @astaric. I don't have a `python.app` folder. My folder structure looks like:

- ~/anaconda3
  - bin/
  - conda-meta
  - envs/
  - etc/
  - Examples/
  - include/
  - lib/
  - LICENSE.txt
  - pkgs/
  - share
  - ssl/
  - var

To which folder should I copy qt.conf?

**Comment by ccordoba12** [comment]
@astaric, thanks a lot for the suggestion. I'll add it to the our next build of Qt4 :-)

**Comment by ccordoba12** [comment]
@brylie, you need to install `python.app` first:

    conda install python.app

**Comment by brylie** [comment]
Thanks @ccordoba12. Here is the output of that command:

```
Error: Package missing in current linux-64 channels: 
  - python.app

Close matches found; did you mean one of these?

    python.app: python-snappy, python-ldap, python

You can search for packages on anaconda.org with

    anaconda search -t conda python.app
```

When searching for the python.app, three packages appear:

```
anaconda search -t conda python.app
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     aetrial/python.app        |          | conda           | osx-64         
     anaconda/python.app       |      1.2 | conda           | osx-64         
     asmeurer/python.app       |      1.2 | conda           | osx-64         
Found 3 packages
```

Should I install 'anaconda/python.app'?

**Comment by ccordoba12** [comment]
`python.app` is only available for Mac.

**Comment by JPFrancoia** [comment]
Hi, I'm jumping into the issue.

On a fresh install of Mac OS X El capitan, fresh install of anaconda3 (conda 4.2.12), fresh install of pyqt4, I don't have the directory ```~/anaconda3/lib/qt4/```, just ```~/anaconda3/lib/```.

Also, I tried @astaric 's solution: I installed ```python.app```, moved ```qt.conf``` from anaconda/bin to anaconda/python.app/Contents/Resources, but my program still can't load jpeg images.

What can I try ?

**Comment by JPFrancoia** [comment]
Should I open a new issue ?

**Comment by ccordoba12** [comment]
We're probably not going to update Qt4/PyQt4 anymore.

Is this problem still present in Qt5?

**Comment by JPFrancoia** [comment]
I don't know, but I can check if you want. For now, I have a huge software developed with PyQt4 and I don't intend to port it to qt5 anytime soon. Is there a way/tweak I can make PyQt4 work for now ?

**Comment by ccordoba12** [comment]
> I don't know, but I can check if you want.

I checked it, and our Qt5 packages support all these formats out of the box.

> I don't intend to port it to qt5 anytime soon

You could use [qtpy](https://github.com/spyder-ide/qtpy) to quite easily do the porting job. That's a compatibility library to work seamlessly with PyQt4 and PyQt5 in the same codebase.

> Is there a way/tweak I can make PyQt4 work for now ?

I don't think so, it seems to have this we'd need to recompile Qt4 and PyQt4. You have two alternatives here:

1. You could hire us to add these formats for Qt4.
2. You could experiment in the conda-forge [qt feedstock](https://github.com/conda-forge/qt-feedstock) to add these formats. Feedstocks are repos of conda packages that are built automatically in CI services. However, that feedstock only builds Linux packages.

**Comment by dzimbeck** [comment]
This is totally crazy 2016 and PyQt4 has problems with something as basic as a JPEG. We should be in flying cars by now, what is this.

I'm having the same issue. Deployed software and on some platforms the image dlls refuse to load with a frozen executable.

Had to use Pillow to convert the images manually to PNG. That works but not a great solution.

Can anyone confirm Qt5 works with JPEG?

**Comment by JPFrancoia** [comment]
Yes, Qt5 works with jpeg. However, Qt4 is not to blame here. I can work with it on linux and windows without problem.

**Comment by mingwandroid** [comment]
> This is totally crazy 2016 and PyQt4 ..

Qt 5 is 4 years old now. The amount of code change required to adapt Qt4 code to work on Qt5 is minimal: https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5. I expect PyQt and ptpy make the transition even easier. Please do your project(s) a favour and make those changes.

**Comment by dzimbeck** [comment]
Actually Qt4 is to blame. When you deploy the software as a frozen executable some systems will not correctly load the plugins. This is true for pyinstaller and others. It depends on the system. Deployed my applications work on 99% of the systems. But some users can't get jpegs because the plugin won't load. This is a known issue.

**Comment by JPFrancoia** [comment]
Is it because the system doesn't properly loads the plugin, or because anaconda puts it in the wrong place ?

**Comment by ccordoba12** [comment]
> Is it because the system doesn't properly loads the plugin, or because anaconda puts it in the wrong place ?

This just happens because we (i.e. Continuum) don't provide those plugins, that's all.

----

To restate our position: Qt4 is not supported by us anymore. You're very welcome to hire us to add support for it in your projects if that's a priority for you.

If that alternative is not suitable, you have the option of sending a pull request against the [qt conda-forge feedstock](https://github.com/conda-forge/qt-feedstock) for all operating systems. Those recipes are the sames we used internally, so we could pick your work and provide new packages for Qt4 on Continuum's side.

I hope our position is clear now.

**Comment by JPFrancoia** [comment]
It's not a problem for me anymore. I ported my code to Qt5 (it just required 2 days of work, that's not much). Now jpeg images load properly, but I have other issues with freezing my app (but it's another story).

If you don't support pyqt4 anymore, shouldn't we close the issue as "won't fix" ?

**Comment by mingwandroid** [comment]
Won't fix
