### ISSUE TITLE
Installation Failed on M2 Pro Chip

### ISSUE THREAD

**Issue by avrilmauro** [ContinuumIO/anaconda-issues#13127]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [X] Miniconda
- [ ] Anaconda.org

### What happened?

"The Installer encountered an error that caused the installation to fail. Contac the software manufacturer for assistance."

I tried installing both Anaconda and Miniconda on my new M2 Pro Chip MacBook and it gave me this error. 

### Expected behavior or outcome

Anaconda should install normally as I have Rosetta installed too.

**Comment by buoyancy99** [comment]
Same issue here. Hope there will be a solution

**Comment by buoyancy99** [comment]
Installation with .sh instead of installer solved my problem.

**Comment by surajmathew** [comment]
But then all the packages are outdated and even if you try and upgrade the packages to match the Windows version it does not. Any notebook or code that is imported from Windows to Mac does not run because of the out dated packages. Example plot_confusion_matrix does not work in the M1/M2 Pro versions as the scikit-learn is outdated.

**Comment by bharathmuppa** [comment]
same here.

**Comment by pseudoyim** [comment]
Hi @avrilmauro @buoyancy99 @bharathmuppa. I'm sorry for the delay. Could you please provide the following info to help us debug?
- The link(s) to the installer you are trying to install.
- The MacOS version installed on your system, along with the chip architecture (e.g. M1 or Intel).

**Comment by pseudoyim** [comment]
If you run into the `This package is incompatible with this version of macOS` error, we've posted a workaround [here](https://docs.anaconda.com/free/anaconda/reference/troubleshooting/#this-package-is-incompatible-with-this-version-of-macos-error-when-running-a-pkg-installer-on-osx).

**Comment by minnyqiu** [comment]
> Installation with .sh instead of installer solved my problem.

I tried to install it with .sh but failed again. May I know which tutorial should I follow?

**Comment by minnyqiu** [comment]
> Hi @avrilmauro @buoyancy99 @bharathmuppa. I'm sorry for the delay. Could you please provide the following info to help us debug?
> 
> * The link(s) to the installer you are trying to install.
> * The MacOS version installed on your system, along with the chip architecture (e.g. M1 or Intel).

I met the same issue. 
the link: https://www.anaconda.com/download
MacOS version: 13.3 (22E252), the chip architecture: M2 Pro
