### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by bobsavage** [ContinuumIO/anaconda-issues#1313]
Anaconda Navigator Update error:

//anaconda/bin/python //anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.2: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.2*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.13', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.3.0;Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by bobsavage** [comment]
BTW, I ran the following code in the terminal just before opening navigator, "conda update anaconda-navigator". Navigator still shows "version 1.3.2 is available".

**Comment by goanpeca** [comment]
@bobsavage this is probably related to Qt incompatibilities.

Could you please try to update Qt to the latest version?

`conda install qt=5 pyqt=5`

Cheers

**Comment by bobsavage** [comment]
> On Dec 26, 2016, at 10:39 AM, Gonzalo Peña-Castellanos <notifications@github.com> wrote:
> 
> conda install qt=5 pyqt=5

I get this response:

Rah-Xephon:~ bobsavage$ conda install qt=5 pyqt=5
Fetching package metadata .......
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqtgraph -> pyqt 4.*
  - pyqtgraph -> python 2.7*|3.4*
  - qt 5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by goanpeca** [comment]
@bobsavage could you do the following

`conda remove pyqtgraph`
`conda install qt=5 pyqt=5`

**Comment by bobsavage** [comment]
Okay, I did that, but now Anaconda-Navigator crashes on launch.

**Comment by goanpeca** [comment]
what is the error on launch?

**Comment by bobsavage** [comment]
No error. I see the splash, which contains the text "initializing", then it disappears with no message. I checked "Activity Monitor" and it isn't listed under CPU or Memory usage (or Disk, or Network), but there is a greyed out entry for Anaconda-Navigator under "Energy".

**Comment by goanpeca** [comment]
Did you launch it from the terminal?

`$ anaconda-navigator` nothing appears on the console?

**Comment by bobsavage** [comment]
$ anaconda-navigator
INFO navigator:setup(42): Setting up logger
DEBUG navigator:start(233): conda info --json
DEBUG navigator:environment_exists(914): (None, '//anaconda/envs/py27')
DEBUG navigator:get_envs(399): 
DEBUG navigator:environment_exists(914): (None, '//anaconda/envs/py27')
DEBUG navigator:environment_exists(914): (None, '//anaconda')
DEBUG navigator:linked(427): //anaconda
DEBUG navigator:get_envs(399): 
DEBUG navigator:environment_exists(914): (None, '//anaconda/envs/py27')
DEBUG navigator:environment_exists(914): (None, '//anaconda')
DEBUG navigator:linked(427): //anaconda
DEBUG navigator:get_envs(399): 
DEBUG navigator:environment_exists(914): (None, '//anaconda/envs/py27')
DEBUG navigator:environment_exists(914): (None, '//anaconda')
DEBUG navigator:linked(427): //anaconda
DEBUG navigator:get_envs(399): 
DEBUG navigator:environment_exists(914): (None, '//anaconda/envs/py27')
DEBUG navigator:environment_exists(914): (None, '//anaconda')
DEBUG navigator:linked(427): //anaconda
DEBUG navigator:set_domain(355): https://api.anaconda.org
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "//anaconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/bobsavage/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 72, in main
    window = run_app(splash)
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 40, in run_app
    window = MainWindow(splash=splash)
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 189, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 125, in __init__
    data_directory=CHANNELS_PATH,
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/manager/packages.py", line 372, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/api/client_api.py", line 358, in set_domain
    binstar_client.utils.set_config(config)
  File "//anaconda/lib/python3.5/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "//anaconda/lib/python3.5/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/bobsavage/.continuum/anaconda-client: Permission denied

**Comment by goanpeca** [comment]
Ok now to test something

`$ sudo anaconda-navigator`

runs?

**Comment by bobsavage** [comment]
Yes. It launches and I no longer have the "i" indicating an update is available. This removes Orange. Does this mean that Orange is currently incompatible with the navigator?

**Comment by goanpeca** [comment]
@bobsavage since Orange has not (yet) migrated to Qt5 officially we removed it for the moment. The new release of navigator for next week handles Orange in a saner way so it is back in the home applications.

In the meantime you can create a new env and install orange in there and then open the terminal. I know this is not the best user experience but we will fix this with the new release.

Thanks for the feedback.

----

Now regarding the issue at hand.

There seems to be some sort of permission mishap somewhere cause you should not need to use sudo to run navigator.

You could remove `/Users/bobsavage/.continuum/anaconda-client` this folder and then retry running

`$ anaconda-navigator` and it should work.

**Comment by bobsavage** [comment]
In the end I think this worked. I needed to delete the .continuum folder as well, else I kept getting a permissions error. I can now launch from the command prompt without sudo, and I can also launch the navigator from the finder (actually I did it from the launchpad), and the message about an update being available is gone.

Thanks for your help! Closing this ticket.

**Comment by goanpeca** [comment]
Glad to hear that @bobsavage :-).

Thanks for all the feedback
