### ISSUE TITLE
Miniconda with Python 3.6

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#1315]
When is Miniconda with Python 3.6 expected to be released by?

**Comment by ilanschnell** [comment]
Even though Python 3.6 is already in the default repository, it is not fully supported yet, ie. not all Python packages are available as `py36` builds yet.  We plan to release Anaconda 4.3 at the end of January, and the Anaconda3 installers will be using Python 3.6 by then.  A Python 3.6 based Miniconda3 installer will not be available before then.  In the meantime, you can use `conda create`.

**Comment by thomco** [comment]
@ilanschnell Any update on the expected release date of Anaconda/Miniconda3 4.3 with Python 3.6

**Comment by upokatik** [comment]
It looks like Anaconda 4.3.0 has been finally released: https://www.continuum.io/downloads

**Comment by ilanschnell** [comment]
Yes, we are very happy.  There is also a blog post: https://www.continuum.io/blog/developer-blog/anaconda-43-released

**Comment by thomco** [comment]
Awesome!  A few questions about the update:
Do I need to reinstall, or I can I 'conda update conda' to get 4.3?   If doing condos update, will be root environment become Python 3.6
I did not see a updated miniconda, is that also available

**Comment by csoja** [comment]
There are not updated Miniconda installers yet - but there will be soon (hopefully this week).

**Comment by fingul** [comment]
When is Miniconda with Python 3.6 expected to be released by?

**Comment by jakirkham** [comment]
> Yes, we are very happy. There is also a blog post: https://www.continuum.io/blog/developer-blog/anaconda-43-released

Very neat. Cool to see we (conda-forge and defaults) now share the same minimum OS X version and the same versions of some basic libraries. Hoping we can maintain and improve on this going forward.

**Comment by fingul** [comment]
Updated! 

https://repo.continuum.io/miniconda/
https://repo.continuum.io/miniconda/Miniconda3-4.3.11-Linux-x86_64.sh

But, miniconda download site need to be updated. (https://conda.io/miniconda.html)
