### ISSUE TITLE
Unable to install the anaconda software on MacBook Air M2

### ISSUE THREAD

**Issue by rathodsa** [ContinuumIO/anaconda-issues#13168]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

I have downloaded anaconda software from the anaconda site. but while launching the package to install it, I see the issue like the software is incompatible with the package that I am trying to download. Please do the needful and help us get it done.

### Expected behavior or outcome

<img width="628" alt="Screenshot 2023-04-01 at 2 19 02 PM" src="https://user-images.githubusercontent.com/74365465/229279459-a9723456-84bd-475d-b815-0d2ea6a3da94.png">

**Comment by pseudoyim** [comment]
Hi @rathodsa. Could you please provide the following info to help us debug?

- The link to the installer you are trying to download.
- The MacOS version installed on your system, along with the chip architecture (e.g. M1 or Intel).

Thank you!

**Comment by pseudoyim** [comment]
If you run into the `This package is incompatible with this version of macOS` error, we've posted a workaround [here](https://docs.anaconda.com/free/anaconda/reference/troubleshooting/#this-package-is-incompatible-with-this-version-of-macos-error-when-running-a-pkg-installer-on-osx).
