### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tiddler83** [ContinuumIO/anaconda-issues#1317]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda -> python 2.7*|3.3*|3.4*|3.5*
  - python ==3.6.0
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.11', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@tiddler83 

You were trying to install a different python version in an existing environment? or you were creating a new environment?

**Comment by 3ICE** [comment]
This happens currently when one tries to update the python package to the latest version, as found under the Environments tab. (Click Update Index, then filter for Upgradable; One item, "python" will show up but it's impossible to upgrade. [or 59 items for a fresh install])

If there are no conflicts between conda and python 3.6, the dependencies could be updated in the meta json files to be forward-compatible.

**Comment by goanpeca** [comment]
At the moment there is a conflict so you cannot upgrade to python 3.6 on the root environment, you will need to create a new environment.
