### ISSUE TITLE
Latest official conda .deb package (23.1.0-0) installs directories with permissions 777

### ISSUE THREAD

**Issue by mliertzer** [ContinuumIO/anaconda-issues#13172]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [X] Miniconda
- [ ] Anaconda.org

### What happened?

I followed https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html and installed conda on Debian Bullseye via the repository https://repo.anaconda.com provided by Anaconda. The latest deb package 23.1.0-0 from the repository installs all directories in /opt/conda with permissions 777, which makes it world writable/executable for any user on the host defeating the purpose of a system package. This is in contrast to earlier package versions (such as 4.12.0-0) located in the same repository. The problem occurred on a fresh installation of the conda package on both Debian Bullseye, as well as Ubuntu 23.04 .

### Expected behavior or outcome

The directories in the official debian package are only writable by the root user.

**Comment by nassarmu** [comment]
This is a security issue as /opt/conda/etc/profile.d/conda.sh prepends /opt/conda/condabin to the default PATH and this issue allows an attacker to override system binaries by placing trojaned versions in /opt/conda/condabin

**Comment by pseudoyim** [comment]
Hello @mliertzer - thank you for reporting this. We have rebuilt the `.deb` package for `conda-23.1.0` (latest has build number `1`; look for `conda-23.1.0-1`). This should install into `/opt/conda` with `755` permissions.

Please let us know if you have any other questions or concerns. Thanks again.

**Comment by mliertzer** [comment]
@pseudoyim  Note, that the fix requires a reinstallation of the package, i.e., if someone has installed the package before, upgrading the package does not fix the issue. Only purging/removing the packaging and then cleanly reinstalling solved the issue here.

Futhermore, I have noticed, that files are installed with 0664 permissions, instead of the conventional 0644 permissions. It's probably not a security issue, since the files are installed with the 'root' group, but still non-standard for .deb packages.

**Comment by pseudoyim** [comment]
Thanks @mliertzer. Please note we had to do another rebuild because of a problem with the shebangs (see issue here: https://github.com/ContinuumIO/anaconda-issues/issues/13240).
