### ISSUE TITLE
Bad metainfo on r-essentials-1.5.0-0.tar.bz2 package

### ISSUE THREAD

**Issue by bigeagle** [ContinuumIO/anaconda-issues#1318]
Hi there,

I found that the metainfo of `r-essentials-1.5.0-0.tar.bz2` does not match that in `repodata.json`. This problem appears in `linux-32`, `linux-64` and `osx-64`.

For example, downloaded <https://repo.continuum.io/pkgs/r/linux-64/r-essentials-1.5.0-0.tar.bz2> has size `2076` and md5 `5cafd7e8085f6f2ed2c51eb518773264`, but <https://repo.continuum.io/pkgs/r/linux-64/repodata.json> shows it has size `2020` and md5 `e6e39a9c6f599a5b7da005131370813a`.

Cheers,
Justin

**Comment by goanpeca** [comment]
@mingwandroid I am testing installing R on Mac and it seems to do nothing when it reaches 

```
...
notebook-4.3.0 100% |################################| Time: 0:00:04   1.18 MB/s
r-essentials-1 100% |################################| Time: 0:00:00   4.29 MB/s
```

It is stuck there. Could this be related?

**Comment by mingwandroid** [comment]
I don't think it's related. I encountered something similar, conda seemed to be hung, but I left it and had lunch, and when I got back it had finished.

Can you try that?

I am going to add the `tidyverse` to `r-essentials` soon which will correct the sha1.

**Comment by bigeagle** [comment]
Hi @mingwandroid , is the md5 mismatch fixed?
