### ISSUE TITLE
Spam account report

### ISSUE THREAD

**Issue by rvalieris** [ContinuumIO/anaconda-issues#13197]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [X] Anaconda.org

### What happened?

I found this account by chance: https://anaconda.org/pottslewis82/repo, looks like a spammer.

not sure if this is the best place to report this but I couldn't find another way.

### Expected behavior or outcome

no spam

**Comment by csoja** [comment]
Thank you for the report!  It is a never ending battle against spam - we appreciate the help in flagging them.
