### ISSUE TITLE
Navigator Error: Not allowing to downgrade bokeh

### ISSUE THREAD

**Issue by sumonigupta** [ContinuumIO/anaconda-issues#1319]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - bokeh ==0.9.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.2.13', 'python': '3.5.2', 'language': 'en', 'qt': '4.8.7', 'platform': 'osx-64', 'version': '1.2.1', 'pyqt': '4.11.4', 'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386'}

**Comment by goanpeca** [comment]
Hi @sumonigupta the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
