### ISSUE TITLE
Anaconda Navigator crashed during update

### ISSUE THREAD

**Issue by 3ICE** [ContinuumIO/anaconda-issues#1320]
Hi,

Apologies for the wordy title. It's almost a whole paragraph in its own right...

I attempted to update Anaconda Navigator (1.3.1 → 1.3.2) because apparently the downloadable installer that continuum.io hosts does not contain the absolute latest version of many things. But unfortunately it crashed during the update process. Maybe that's why it's not included? Anyway, let's not get sidetracked and instead continue with the bug report; I would attach the update logs. (But where are they?) So far I only found 200kb worth of mostly nothing in my \.anaconda\navigator\logs\ subfolder inside /Users/. (The whole thing compresses to a mere 13 kb.) The one error line in it is quoted verbatim at the end of my post (likely not relevant though). A possible mistake I recall committing was that I ran Anaconda Navigator elevated, with full admin rights. Just so it could write to Program Files.

I wish to download just Anaconda Navigator. Not 2.8GB worth of stuff I already have. _So I can avoid increasing my already high (metered) internet bills. Download limit exceeded, throttling is real and very, very, painfully slow. Lets pretend only mobile internet is available in my area. (Limited to 500MB per month.)_

I wish to cherry pick what gets downloaded and installed and what doesn't. Current installer has no options for this. More than half the libraries, currently clocking in at over 2.8 GB in size, probably aren't necessary for a beginner. I never use the less fancy consoles either. Just the graphical IDE for me thank you. And no web-based notebooks on localhost please. Nor superfluous runtimes.

Uninstall does not remove all registry entries so now I have an unclickable, already uninstalled line in control panel → add/remove programs.
![image](https://cloud.githubusercontent.com/assets/5385790/21537028/c908047c-cd93-11e6-90c9-bfa21c1f4ab7.png)

(Skip forward two hours of troubleshooting...)

After the third reinstall, I finally learned my lesson and ignored Navigator's request for updating itself.

However, several other applications were outdated as well. They are multiple versions behind, in fact. I had to update spyder to 3.0.2 (skipping 3.0.1 entirely) and jupyter from 4.2.3 to 4.3.0 which was a whole major version behind.

I downloaded the installer just five minutes ago, why is most everything in it expired right out of the box?

Attempting to install the offered glueviz application on root created 220MB worth of junk in \Anaconda3\pkgs\qt-5.6.0-vc14_0.tmp then also crashes. Two more attempts later however, it installed. And works well. Except more than half of this needs to be manually deleted:
\Anaconda3\pkgs\qt-5.6.0-vc14_0\
\Anaconda3\pkgs\qt-5.6.2-vc14_0\
\Anaconda3\pkgs\qt-5.6.2-vc14_0.tar.bz2
\Anaconda3\pkgs\qt-5.6.0-vc14_0.tar.bz2
\Anaconda3\pkgs\pyqt-5.6.0-py35_0.tar.bz2

According to \Anaconda3\conda-meta\qt-5.6.2-vc14_0.json I should keep 5.6.2:
>   "fn": "qt-5.6.2-vc14_0.tar.bz2",

and
>   "link": {
>     "source": "\\Anaconda3\\pkgs\\qt-5.6.2-vc14_0",
>     "type": "hard-link"
>   },

There are no references to qt-5.6.0 anywhere, so why wasn't it cleaned up? 300 MB wasted... Free space is rather precious on my small SSD.

Finally, 58 packages (in Environments → root) were ready for an upgrade also. Including python itself from 3.5 to 3.6. Though that's quickly prevented by conda's dependency on these specific versions of python: "2.7*|3.3*|3.4*|3.5*" The rest went fine:
![image](https://cloud.githubusercontent.com/assets/5385790/21537205/64838960-cd96-11e6-9251-e56775073edc.png)
From that big list, numpy and qt are the only libraries I know. And they're both out of date. (Ultimately, qt shall remain out of date as it's stuck on the Linking... step.)

Sincerely,
Daniel "3ICE" Berezvai

p.s.: Starting my Machine Learning course in two weeks. More than enough time for me to fix this all up until then.

The promised error:
```
2016-12-29 05:18:32,881 - ERROR
    main_window._conda_output_ready : 859
    C:\Program Files\Anaconda3\python.exe C:\Program Files\Anaconda3\Scripts\
conda-script.py install --yes --json --force-pscheck --prefix C:\Program Files\Anaconda3 spyder==3.0.2:
IO error: Missing write permissions in: C:\Program Files\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\Program Files\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone=C:\Program Files\Anaconda3
```

Now I definitely do not want to do that. My roaming profile can absolutely not handle a 2.8GB monster folder cloned under my home directory.

The same message repeats at:
2016-12-29 05:18:53,709 - ERROR
    conda_api.communicate : 217
[...]
Only difference is it's all on one line with `\n`s and other escaped characters.

Original title was: "Anaconda Navigator crashed during update, so now I'm stuck with a Navigator that uninstalled itself and cannot be repaired unless I redownload and reinstall the whole 1.7GB Anaconda software family. Also several items were outdated right away even though I chose the latest available version. Uninstall does not remove all registry entries so now I have an unclickable, already uninstalled line in control panel → add/remove programs."

**Comment by goanpeca** [comment]
@3ICE I would advice you install anaconda for the current user and not all users

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
