### ISSUE TITLE
Navigator won't launch on Mac: AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by chrisprocaccino** [ContinuumIO/anaconda-issues#13226]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

First time ever using miniconda; I installed the Miniconda3 macOS Apple M1 64-bit pkg from the website and then installed Anaconda Navigator. I tried to launch it, received this message:

"Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)

Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/app/start.py", line 137, in start_app
    window = run_app(splash)
             ^^^^^^^^^^^^^^^
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/app/start.py", line 59, in run_app
    window = MainWindow(splash=splash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
               ^^^^^^^^^^^^^
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/api/anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
                   ^^^^^^^^^^^^^^
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/api/anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
                      ^^^^^^^^^^
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 1743, in CondaAPI
    CONDA_API = _CondaAPI()
                ^^^^^^^^^^^
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 434, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "/Users/anthonyprocaccino/miniconda3/lib/python3.11/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 583, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
                       ^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
"

Followed all the steps on the docs: uninstalled and reinstalled miniconda, reset the navigator, and tried to delete the .condarc file and it's not anywhere on my computer. Any time I try to launch the navigator it brings me back to this error message. I'm very very new to coding so any help would be appreciated.

### Conda info

```shell
active environment : my_navigator_env
    active env location : /Users/anthonyprocaccino/miniconda3/envs/my_navigator_env
            shell level : 2
       user config file : /Users/anthonyprocaccino/.condarc
 populated config files : 
          conda version : 23.7.0
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /Users/anthonyprocaccino/miniconda3  (writable)
      conda av data dir : /Users/anthonyprocaccino/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/anthonyprocaccino/miniconda3/pkgs
                          /Users/anthonyprocaccino/.conda/pkgs
       envs directories : /Users/anthonyprocaccino/miniconda3/envs
                          /Users/anthonyprocaccino/.conda/envs
               platform : osx-64
             user-agent : conda/23.7.0 requests/2.29.0 CPython/3.11.4 Darwin/22.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda config

```shell
nothing comes up
```

### Conda list

```shell
# packages in environment at /Users/anthonyprocaccino/miniconda3/envs/my_navigator_env:
#
# Name                    Version                   Build  Channel
anaconda-client           1.12.0          py311hecd8cb5_0    defaults
anaconda-navigator        2.4.2           py311hecd8cb5_0    defaults
attrs                     22.1.0          py311hecd8cb5_0    defaults
boltons                   23.0.0          py311hecd8cb5_0    defaults
brotlipy                  0.7.0           py311h6c40b1e_1002    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
ca-certificates           2023.05.30           hecd8cb5_0    defaults
certifi                   2023.7.22       py311hecd8cb5_0    defaults
cffi                      1.15.1          py311h6c40b1e_3    defaults
chardet                   4.0.0           py311hecd8cb5_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
clyent                    1.2.2           py311hecd8cb5_1    defaults
conda                     23.7.0          py311hecd8cb5_0    defaults
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-package-handling    2.1.0           py311hecd8cb5_0    defaults
conda-package-streaming   0.8.0           py311hecd8cb5_0    defaults
conda-repo-cli            1.0.41          py311hecd8cb5_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
cryptography              41.0.2          py311h2093b18_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
freetype                  2.12.1               hd8bbffd_0    defaults
gettext                   0.21.0               he85b6c0_1    defaults
giflib                    5.2.1                h6c40b1e_3    defaults
glib                      2.69.1               hfff2838_2    defaults
gst-plugins-base          1.14.1               hcec6c5f_1    defaults
gstreamer                 1.14.1               h6c40b1e_1    defaults
icu                       58.2                 h0a44026_3    defaults
idna                      3.4             py311hecd8cb5_0    defaults
jpeg                      9e                   h6c40b1e_1    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.17.3          py311hecd8cb5_0    defaults
jupyter_core              5.3.0           py311hecd8cb5_0    defaults
krb5                      1.20.1               hdba6334_1    defaults
lcms2                     2.12                 hf1fd2bf_0    defaults
lerc                      3.0                  he9d5cce_0    defaults
libclang                  12.0.0          default_hbc2896b_2    defaults
libcxx                    14.0.6               h9765a3e_0    defaults
libdeflate                1.17                 hb664fd8_0    defaults
libedit                   3.1.20221030         h6c40b1e_0    defaults
libffi                    3.4.4                hecd8cb5_0    defaults
libiconv                  1.16                 hca72f7f_2    defaults
libllvm12                 12.0.0               h9b2ccf5_3    defaults
libpng                    1.6.39               h6c40b1e_0    defaults
libpq                     12.15                hdb2fb19_1    defaults
libtiff                   4.5.0                hcec6c5f_2    defaults
libwebp                   1.2.4                hf6ce154_1    defaults
libwebp-base              1.2.4                h6c40b1e_1    defaults
libxml2                   2.10.3               h930c0e2_0    defaults
libxslt                   1.1.37               h6d1eb0e_0    defaults
llvm-openmp               14.0.6               h0dcd299_0    defaults
lz4-c                     1.9.4                hcec6c5f_0    defaults
navigator-updater         0.4.0           py311hecd8cb5_0    defaults
nbformat                  5.7.0           py311hecd8cb5_0    defaults
ncurses                   6.4                  hcec6c5f_0    defaults
nspr                      4.35                 hcec6c5f_0    defaults
nss                       3.89.1               hcec6c5f_0    defaults
openssl                   1.1.1u               hca72f7f_0    defaults
packaging                 23.0            py311hecd8cb5_0    defaults
pathlib                   1.0.1              pyhd3eb1b0_1    defaults
pcre                      8.45                 h23ab428_0    defaults
pillow                    9.4.0           py311hcec6c5f_0    defaults
pip                       23.2.1          py311hecd8cb5_0    defaults
platformdirs              2.5.2           py311hecd8cb5_0    defaults
pluggy                    1.0.0           py311hecd8cb5_1    defaults
ply                       3.11            py311hecd8cb5_0    defaults
psutil                    5.9.0           py311h6c40b1e_0    defaults
pycosat                   0.6.4           py311h6c40b1e_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyjwt                     2.4.0           py311hecd8cb5_0    defaults
pyopenssl                 23.2.0          py311hecd8cb5_0    defaults
pyqt                      5.15.7          py311hcec6c5f_0    defaults
pyqt5-sip                 12.11.0         py311hcec6c5f_0    defaults
pyrsistent                0.18.0          py311h6c40b1e_0    defaults
pysocks                   1.7.1           py311hecd8cb5_0    defaults
python                    3.11.4               h1fd4e5f_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2          py311hecd8cb5_0    defaults
pytz                      2022.7          py311hecd8cb5_0    defaults
pyyaml                    6.0             py311h6c40b1e_1    defaults
qt-main                   5.15.2               h719ae48_7    defaults
qt-webengine              5.15.9               h90a370e_4    defaults
qtpy                      2.2.0           py311hecd8cb5_0    defaults
qtwebkit                  5.212                hbfab81c_5    defaults
readline                  8.2                  hca72f7f_0    defaults
requests                  2.29.0          py311hecd8cb5_0    defaults
requests-toolbelt         0.9.1              pyhd3eb1b0_0    defaults
ruamel.yaml               0.17.21         py311h6c40b1e_0    defaults
setuptools                68.0.0          py311hecd8cb5_0    defaults
sip                       6.6.2           py311hcec6c5f_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h6c40b1e_0    defaults
tk                        8.6.12               h5d9f67b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.12.0          py311hecd8cb5_0    defaults
tqdm                      4.65.0          py311h85bffb1_0    defaults
traitlets                 5.7.1           py311hecd8cb5_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
ujson                     5.4.0           py311hcec6c5f_0    defaults
urllib3                   1.26.16         py311hecd8cb5_0    defaults
wheel                     0.38.4          py311hecd8cb5_0    defaults
xz                        5.4.2                h6c40b1e_0    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
zlib                      1.2.13               h4dc903c_0    defaults
zstandard                 0.19.0          py311h6c40b1e_0    defaults
zstd                      1.5.5                hc035e20_0    defaults
```

**Comment by jgerardhodge** [comment]
Been having issues with Anaconda myself and just began to receive this as well after a clean install.

**Comment by SukhBhagsar** [comment]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda [issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)

Main Error

'list' object has no attribute 'get'
Traceback

Traceback (most recent call last):
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/app/start.py", line 137, in start_app
    window = run_app(splash)
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/app/start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/api/anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/api/anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 1743, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 434, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "/Users/sukhjindersingh/anaconda3/lib/python3.10/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 583, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

**Comment by Mwafaq1990** [comment]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda [issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) 

Main Error

'list' object has no attribute 'get'


Traceback

Traceback (most recent call last):
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 1743, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 434, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "C:\Users\Mwafaq\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 583, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

**Comment by chrisprocaccino** [comment]
Not an expert at coding whatsoever but I just completely uninstalled miniconda and installed anaconda itself and it worked fine.
