### ISSUE TITLE
MD5 Checksum Mismatch Issue During Anaconda Installation. (WARNING: md5sum mismatch of tar archive)

### ISSUE THREAD

**Issue by yifan-dadada** [ContinuumIO/anaconda-issues#13234]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [X] Miniconda
- [ ] Anaconda.org

### What happened?

During the Anaconda installation process, I encountered an issue with MD5 checksum mismatch. While using the wget command to download the Anaconda installation package, the obtained MD5 checksum is consistently d41d8cd98f00b204e9800998ecf8427e, whereas the expected MD5 checksum should be b35af0fae8e8667609722e2c0d196f1d. Due to this problem, I am unable to successfully install Anaconda. And I attempted to download Anaconda from different sources. 

My Linux version is CentOS Linux release 7.9.2009 (Core).
And I tried to install Miniconda, but the result was similar. The error message is pasted below.

Anaconda error message：

Do you accept the license terms? [yes|no]
[no] >>> yes
Anaconda3 will now be installed into this location:
/home/zzdx/anaconda3
  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below
[/home/zzdx/anaconda3] >>>
PREFIX=/home/zzdx/anaconda3
WARNING: md5sum mismatch of tar archive
expected: b35af0fae8e8667609722e2c0d196f1d
     got: d41d8cd98f00b204e9800998ecf8427e  -
     

Miniconda error message：

[/home/zzdx/miniconda3] >>>
PREFIX=/home/zzdx/miniconda3
WARNING: md5sum mismatch of tar archive
expected: 46f2d0f5fb3daa70cf7708787ce3bd89
     got: d41d8cd98f00b204e9800998ecf8427e  -

### Expected behavior or outcome

The expected behavior is that I should be able to download and install Anaconda or Miniconda successfully without any MD5 checksum mismatch or other errors. 

Thank you for your assistance.

### Additional information

I have carefully verified the SHA256 checksum of the downloaded Anaconda3-2023.07-1-Linux-x86_64.sh file, and I can confirm that the calculated SHA256 checksum (111ce0a7f26e606863008a9519fd608b1493e483b6f487aea71d82b13fe0967e) is exactly the same as the SHA256 checksum provided by the official source. Despite this verification, I still encounter an MD5 checksum error during the installation process.

<img width="960" alt="image" src="https://github.com/ContinuumIO/anaconda-issues/assets/88924753/3dd9ba13-c347-4efd-b883-5f50bac41b83">

The following are the questions I have raised elsewhere as a supplement to the problem description.
https://forums.centos.org/viewtopic.php?f=48&t=80309&p=336658#p336658

**Comment by waito3209** [comment]
facing similar issues here

**Comment by EJMBoomer** [comment]
same

**Comment by yifan-dadada** [comment]
After installing the old version, this issue was resolved. 
https://forums.centos.org/viewtopic.php?f=48&t=80309&p=336658#p336658

**Comment by SuhasSrinivasan** [comment]
Facing similar issue on HPC cluster
Following the recommended installation steps
https://docs.anaconda.com/free/miniconda/
