### ISSUE TITLE
Astropy version in defaults is out of date newest version is v5.3.3 and 5.1.0 is currently packaged

### ISSUE THREAD

**Issue by Cadair** [ContinuumIO/anaconda-issues#13239]
### Checklist

- [X] I added a descriptive title (including the requested package **name**, **version**, and **platform**).
- [X] I searched the defaults channels ([Python](https://repo.anaconda.com/pkgs/main/) and [R](https://repo.anaconda.com/pkgs/r/)) and did not find the package I'm requesting.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and did not find a duplicate request for this package.

### Request type

- [ ] New (i.e. no versions of this package currently exist on repo.anaconda.com)
- [X] Update (i.e. older versions of this package exist and I'm requesting an updated version)
- [ ] Rebuild (i.e. something is wrong with an existing version of this package and it needs to be rebuilt)

### Name

astropy

### Version

latest

### Platform(s)

all

### Location of source code

https://github.com/astropy/astropy

### Conda-Forge feedstock

https://github.com/conda-forge/astropy-feedstock

### Reason for this request

The version of astropy in defaults is incompatible with the version of matplotlib and numpy currently shipping in defaults, this is causing significant issues for users.

**Comment by jezdez** [comment]
Thanks @Cadair, I've bubbled that up at Anaconda with the packaging team based on a conversation with @eerovaher at the NumFOCUS Summit 2023.

**Comment by skupr-anaconda** [comment]
`astropy 5.3.4` is available on the defaults channel

**Comment by Cadair** [comment]
Thanks!
