### ISSUE TITLE
Navigator UI issues

### ISSUE THREAD

**Issue by kerrywatson1** [ContinuumIO/anaconda-issues#1324]
Received from software feedback form:

Anaconda Navigator "Please finish the UI. It isn't even at alpha.
When the confirm dialog opens the OK button is unavailable off the bottom of the screen. Zoom and Pan is not available. Also the font sizes and contrast suck and the theme seems not to have a way to change. Most problematic is that the descriptions of many of the packages are scant or even non-existent."

Submitted by @patrmccormack

@patrmccormack, can you provide more info such as operating system and Navigator version?

**Comment by njp729** [comment]
I'm not @patrmccormack, but I'll give some details on similar problems I'm having with the Navigator UI.

On my old laptop (Asus something 13", Windows 10), Navigator was fine. Recently got a new laptop (Asus Zenbook Flip 13", Windows 10), installed Anaconda, and immediately had issues with scaling, font, and UI usability.

Details: Anaconda 1.3.2 (upgraded from 1.3.0 on this computer, which had the same problems.) Specifically, font size is generally too big; buttons in bottom left don't show entire words (Documentation, XXX [can't read it], and Feedback); on Environments tab, large font size cuts off version numbers and Anaconda icon looks too big and pixelated.

FWIW, I had similar problems with Spyder on this new computer, but an upgrade to the latest version resolved the font and scaling problems.

![image](https://cloud.githubusercontent.com/assets/22358572/21736116/fdfbbb5a-d433-11e6-9117-43c04a5d2677.png)

![image](https://cloud.githubusercontent.com/assets/22358572/21736123/0688b9c6-d434-11e6-9e00-7867e29f6fd3.png)

Details from log:
2017-01-06 12:48:08,079 - DEBUG
    download_api.download : 225
    (u'https://www.continuum.io/sites/default/files/anaconda_logo.png', u'C:\\Users\\Nick\\.anaconda\\navigator\\images\\anaconda.png', False)
2017-01-06 12:48:08,079 - DEBUG
    community.download_thumbnail : 395
    Fetching thumbnail https://www.continuum.io/sites/default/files/anaconda_logo.png

**Comment by goanpeca** [comment]
@njp729 there is a setting in the preferences of navigator that allows you to enable/disable HIGH DPI screens scaling.

Could you try toggling this option and restarting navigator?

<img width="476" alt="screen shot 2017-01-08 at 1 44 33 pm" src="https://cloud.githubusercontent.com/assets/3627835/21752568/a14f1e8a-d5a8-11e6-95ec-64be76e0864b.png">

**Comment by njp729** [comment]
@goanpeca thanks for your reply. I changed the setting and restarted, but now the font is tiny (relative to the default size used elsewhere - say, the window's header bar - and what Navigator looks like on my old computer), and when I resize the Navigator window, I occasionally get weird displays.

Full size
![image](https://cloud.githubusercontent.com/assets/22358572/21866969/dddd99ce-d811-11e6-9131-9d86cdcaceee.png)

Less than full size
![image](https://cloud.githubusercontent.com/assets/22358572/21866980/eacba8c4-d811-11e6-9f5a-71c2c9e113d2.png)

**Comment by majia67** [comment]
I use Windows 10 and I updated my Anaconda Navigator to the latest version (1.5.0). There's a new scaling issue on my laptop. The font size is fine, but the window is way too big, which extends beyond my whole screen. I could only view half of them. My default windows scaling ratio is 150%. When I lower it down to 125%, the navigator looks like as if there is no high DPI scaling. Hope this bug could be fixed because it really influences the using experience on Windows laptop considering 1080p screen is quite common for laptops.

**Comment by goanpeca** [comment]
@majia67 thanks for the update. Could you attach the screen information of your laptop?

**Comment by gordon-n-stevenson** [comment]
I'm having issues with anaconda-navigator being way to large for my hidpi chromebook. Is there a way to force a custom sizing of the window?

I'm using the QT_SCREEN factor as suggested and the hidpi text scaling. These are fine - the issue is simply the size of navigator seems is too big and cannot be resized!

**Comment by majia67** [comment]
@goanpeca 
![image](https://cloud.githubusercontent.com/assets/11867815/24584230/6f252c92-1734-11e7-9b44-e7ef4c89ca59.png)
![image](https://cloud.githubusercontent.com/assets/11867815/24584236/ab4b3e50-1734-11e7-976b-d1edf002f8f8.png)

**Comment by chseeling** [comment]
Installed the latest anaconda on windows 10, however on running navigator, the windows are too large for screen and unresponsive to any mouse clicks or key strokes.
There are two windows that are created on startup.
How can I get to the preferences window to resolve this default behavior given that I can get to any buttons?

**Comment by majia67** [comment]
Thank you @chseeling! Lowering the window scaling solves the problem.

**Comment by LesterCovax** [comment]
Changing the following did the trick for me:
`Compatibility Settings > Change High DPI Settings > High DPI Override > System` 

![image](https://user-images.githubusercontent.com/34850610/50532177-9d095800-0ae3-11e9-8a9a-ee0cd873ed98.png)
