### ISSUE TITLE
Error when installing Anaconda3 2023.7-2 (64 -bit) setup in Win7

### ISSUE THREAD

**Issue by jpcgandre** [ContinuumIO/anaconda-issues#13257]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

Hello,

I had some issues with Spyder and Win7 and so I uninstalled Anaconda and all packages entirely from my windows 7 system.
I also did:
Check c:\users\user_name\appdata for the directory conda and delete it
Check c:\users\user_name\ for directory .conda and delete it
delete the file “.condarc” in “C:\Users\my name”
install Anaconda3

But I always get the error:
![Untitled](https://github.com/ContinuumIO/anaconda-issues/assets/99285734/b0c1a162-fdff-428c-a599-4f698185f33d)

Is there a way out? Installing miniconda would be better?
Thanks

### Expected behavior or outcome

Install successfully Anaconda3

**Comment by dbast** [comment]
Recent Anaconda versions only support Windows 10 and newer, see https://docs.anaconda.com/free/anaconda/install/index.html
