### ISSUE TITLE
conda install fails with proxyerror behind proxy. Need a way to bypass repo url.

### ISSUE THREAD

**Issue by dofine** [ContinuumIO/anaconda-issues#1326]
I know this issue has been posted many times. But I've tried all possible solutions online. No one works for me. Some more information:

1. curl responses with 200 OK

```
curl -I https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2
```

2. I can install it with `pip install`, because I monkey patched the `requests` package in pip, made it return empty for environment proxies. (in file `utils.py` from `requests`)

```python
def get_environ_proxies(url):
    """Return a dict of environment proxies."""
    # if should_bypass_proxies(url):
    #     return {}
    # else:
    #     return getproxies()
    return {}
```

3. I can also do `requests.get` in python interpreter after setting 

```
import os
os.environ['no_proxy']='repo.continuum.io'
```

So I think basically I need a way to tell `conda install` to ignore proxy setting and don't use any proxy to connect. Is there any way to do this?

```
λ conda install pep8
Fetching package metadata ...

CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000002C597B8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)))",),)
```

```
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.20.0
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : E:\n3132\Programs\anaconda2\anaconda  (writable)
    default environment : E:\n3132\Programs\anaconda2\anaconda
       envs directories : E:\n3132\Programs\anaconda2\anaconda\envs
          package cache : E:\n3132\Programs\anaconda2\anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\n3132\.condarc
           offline mode : False

# conda environments:
#
py3                      E:\n3132\Programs\anaconda2\anaconda\envs\py3
root                  *  E:\n3132\Programs\anaconda2\anaconda

sys.version: 2.7.12 |Anaconda 4.0.0 (64-bit)| (defaul...
sys.prefix: E:\n3132\Programs\anaconda2\anaconda
sys.executable: E:\n3132\Programs\anaconda2\anaconda\python.exe
conda location: E:\n3132\Programs\anaconda2\anaconda\lib\site-packages\conda
conda-build: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-build.exe
conda-convert: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-convert.exe
conda-develop: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-develop.exe
conda-env: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-env.exe
conda-index: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-index.exe
conda-inspect: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-inspect.exe
conda-metapackage: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-metapackage.exe
conda-pipbuild: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-pipbuild.exe
conda-server: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-server.exe
conda-sign: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-sign.exe
conda-skeleton: E:\n3132\Programs\anaconda2\anaconda\Scripts\conda-skeleton.exe
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: E:\n3132\Programs\anaconda2\anaconda\Library\bin;E:\n3132\cmder\bin;E:\n3132\cmder\vendor\git-for-windows\cmd;E:\n3132\cmder\vendor\conemu-maximus5\ConEmu\Scripts;E:\n3132\cmder\vendor\conemu-maximus5;E:\n3132\cmder\vendor\conemu-maximus5\ConEmu;C:\Python26\Lib\site-packages\PyQt4;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Python26;C:\Program Files\EmEditor;E:\n3132\Programs\anaconda2\anaconda;E:\n3132\Programs\anaconda2\anaconda\Scripts;E:\n3132\Programs\anaconda2\anaconda\Library\bin;C:\Users\n3132\AppData\Local\rodeo\app-2.4.3\bin;C:\Go\bin;E:\n3132\bin;E:\n3132\Programs\anaconda2\anaconda\Scripts;E:\n3132\babun\.babun;E:\n3132\cmder\vendor\git-for-windows\usr\bin;E:\n3132\cmder\vendor\git-for-windows\usr\share\vim\vim74;E:\n3132\cmder\;E:\n3132\Programs\anaconda2\anaconda\lib\site-packages\pywin32_system32
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

**Comment by rickyi22** [comment]
same problem here +1

**Comment by dofine** [comment]
https://github.com/pypa/pip/issues/1182

May be i'll try this and set to my `.condarc`. Hope it'll work.

```
- proxy_servers: {}
```

**Comment by heather999** [comment]
Did you find a work-around?  I see the same problem.  Did setting the proxy_servers in .condarc help?

**Comment by dofine** [comment]
@heather999 works for me. You can have a try.

**Comment by dofine** [comment]
Have to hack conda source code and add
`os.environ['no_proxy'] = 'whatever-repo-url'`

**Comment by soulpacket** [comment]
solved

**Comment by rarry1988** [comment]
@dofine hi, i added - proxy_servers: {} in .condarc. where do i need to add os.environ['no_proxy'] = 'whatever-repo-url'? thank you .

**Comment by nehaljwani** [comment]
@rarry1988 Instead of editing the source code, try doing:
```cmd
set NO_PROXY=continuum.io,anaconda.org
```

**Comment by dofine** [comment]
@rarry1988 Hi, nehaljwani 's answer is better than mine.

**Comment by surenciodepalma** [comment]
@nehaljwani I am somewhat of a novice at this but can you please share the exact steps I should enter into Terminal to bypass the proxy? I am working from OS.

![image](https://user-images.githubusercontent.com/12286134/28184430-62a45a26-67e1-11e7-9ce8-4d81b7e92039.png)

**Comment by mrdivine** [comment]
I'm still having the same problem exactly as described by surenciodepalma. Anyone got some ideas?

**Comment by dofine** [comment]
@surenciodepalma @mrdivine 
Hi, on Mac OS maybe you should try `export NO_PROXY=continuum.io,anaconda.org`.

**Comment by prachiichandak** [comment]
I am having the same problem as mrdivine and surenciodepalma.I am using windows 7 professional

**Comment by mbrennan** [comment]
I have the same issue on Windows 7.  Our corporate firewall does not allow programs other than approved ones to pass through the firewall, so setting any proxy settings via the `HTTP_PROXY` or `HTTPS_PROXY` environment variables, or settings them up in the `.condarc` file does not fix the problem.  We host our own conda packages via a custom channel.  Conda ought to be able to connect to that channel without attempting to connect to any of the default channels.

I've searched for some way to remove or disable default channels but Conda always seems to want to connect to the default ones regardless of the approach I take (for example, using `--override-channels` still causes the error from the OP.  The only way I've gotten it to work is to turn on offline mode and point it to a local file channel.

Perhaps there should be some "internal" mode that behaves similar to offline mode, but doesn't use any of the default channels?

**Comment by IvanNFZ** [comment]
I have the same problem with corporate firewall. I cant even download glueviz, because it only downloadable over Navigator.

**Comment by nehaljwani** [comment]
@mbrennan This should help you: https://conda.io/docs/config.html#set-a-channel-alias-channel-alias

**Comment by mbrennan** [comment]
@nehaljwani Using the `channel_alias` config key seems to get around the problem of conda trying to access anaconda.org.

Is there any way to configure it so that it always uses a specific alias by default?  I'd rather not have to type in `conda <command> --channel my_channel` every time I want to use it.

Ideally, conda would work on an internal network without access to the public internet if configured properly.  Our IT team will never open access to *.anaconda.org for conda unfortunately.

**Comment by nehaljwani** [comment]
@mbrennan  Along with `channel_alias`, does `conda config --prepend channels my_channel` help?

**Comment by mbrennan** [comment]
@nehaljwani Yes, that worked, except I had to remove `defaults` from the channels config.  Thanks!

**Comment by seagu11** [comment]
@nehaljwani  @mbrennan I'm having the same issues seen here and was wondering are setting your alias to a local drive or URL.

**Comment by mbrennan** [comment]
@seagu11 Mine is an internal remote server, not a local drive.

**Comment by tannerjt** [comment]
I was having a similar problem installing via pyenv.  My solution was to delete the original .conda and .condarc files.

```bash
cd ~/
rm -rf .conda
rm -rf .condarc
```

**Comment by tianshi-wang** [comment]
@tannerjt Thanks! It works for me!~

**Comment by masabem** [comment]
Solutions here are given in a complex hard for a beginner to understand!!!
