### ISSUE TITLE
KeyError: 'base'

### ISSUE THREAD

**Issue by Iphykay** [ContinuumIO/anaconda-issues#13269]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Starboy\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Starboy\anaconda3\Lib\site-packages\conda\cli\main.py", line 91, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Starboy\anaconda3\Lib\site-packages\conda\activate.py", line 199, in execute
        return getattr(self, self.command)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Starboy\anaconda3\Lib\site-packages\conda\activate.py", line 165, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Starboy\anaconda3\Lib\site-packages\conda\activate.py", line 343, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Starboy\anaconda3\Lib\site-packages\conda\activate.py", line 372, in _build_activate_stack
        conda_prompt_modifier = self._prompt_modifier(prefix, conda_default_env)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Starboy\anaconda3\Lib\site-packages\conda\activate.py", line 736, in _prompt_modifier
        return context.env_prompt.format(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
    KeyError: 'base'

### Conda info

```shell
active environment : None
       user config file : C:\Users\Starboy\.condarc
 populated config files : C:\Users\Starboy\.condarc
          conda version : 23.7.2
    conda-build version : 3.26.0
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : C:\Users\Starboy\anaconda3  (writable)
      conda av data dir : C:\Users\Starboy\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Starboy\anaconda3\pkgs
                          C:\Users\Starboy\.conda\pkgs
                          C:\Users\Starboy\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Starboy\anaconda3\envs
                          C:\Users\Starboy\.conda\envs
                          C:\Users\Starboy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.2 requests/2.31.0 CPython/3.11.4 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config

```shell
Conda config *

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Conda list

```shell
The same as the previous.

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Additional Context

To be honest, I am tired of using your platform

**Comment by csoja** [comment]
Can you update the version of conda you are using and see if that fixes the issue? conda v23.7.4 was just released.  (On windows, open the Anaconda Command Prompt, _conda update conda_ or _conda install conda=23.7.4_

**Comment by Iphykay** [comment]
When I open the window, i see the error message I gave just shown at the top. Even if i type the command it gives 

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

**Comment by csoja** [comment]
Sounds like something has broken with your installation - has it always been this way, or did this change happen recently?

**Comment by Iphykay** [comment]
Not really, I just installed the newest version and boom that happen.

**Comment by Iphykay** [comment]
I had to uninstall the older version I was using because it was taking too long to update a yml file in an venv i created

**Comment by csoja** [comment]
unfortunately, this is not a common error. This is the only similar open or closed error I was able to find: https://github.com/ContinuumIO/anaconda-issues/issues/12760  And in that case, it seemed like maybe a case of the installation being spread across multiple drives - and it looks like you are just on C:\. Perhaps you were not able to cleanly uninstall your previous installation.  Did you remove the .anaconda and .continuum directories as part of the uninstall process? Is there anything unusual in your .condarc file?  (these are often hidden files on Windows)

**Comment by Iphykay** [comment]
Yeah i did remove both the .conda and .anaconda directories after uninstalling the previous version.

**Comment by Iphykay** [comment]
Ohhh i think i didn't delete the .continuum and .condarc file. Okay let me uninstall the current one and install it again removing the directories and files mentioned

**Comment by Iphykay** [comment]
Voila!!!! It worked now. I guess the files you spoke were the issues. Thanks alot.
