### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hwestbro** [ContinuumIO/anaconda-issues#1329]
Anaconda Navigator Update error:

/Users/hwestbro/anaconda/bin/python /Users/hwestbro/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.2: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.2*
  - orange -> pyqt 4.*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.13', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Darwin;16.3.0;Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@hwestbro this is related to Qt incompatibilities. Qt4 version is deprecated and no longer supported. Navigator and other software using Qt (except for orange) now rely on having Qt5. Qt5 is the current supported version of Qt and is the recommended one.

Could you please try to update Qt to the latest version?

`conda remove orange`
`conda install qt=5 pyqt=5 anaconda-navigator=1.3.2`

If you are using or plan to use orange, you can do so by installing it in a new environment (with Qt4)

Please let me know if this solves the issues.

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
