### ISSUE TITLE
Repodata is not updated for pytorch 

### ISSUE THREAD

**Issue by atalman** [ContinuumIO/anaconda-issues#13295]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

We have published Release 2.1.1 of PyTorch, TorchVision, TorchAudio, TorchText and TorchData:

https://anaconda.org/pytorch/pytorch/files?version=2.1.1
https://anaconda.org/pytorch/torchvision/files?version=0.16.1
https://anaconda.org/pytorch/torchaudio/files?version=2.1.1
https://anaconda.org/pytorch/torchtext/files?version=0.16.1
https://anaconda.org/pytorch/torchdata/files?version=0.7.1

However when running validation we see that anaconda still serves old version 2.1.0:
https://github.com/pytorch/builder/actions/runs/6869727043/job/18683179371

following command:
```
conda install -y pytorch torchvision torchaudio cpuonly -c pytorch
installs:
    pytorch-2.1.0              |      py3.8_cpu_0        77.2 MB  pytorch
    torchaudio-2.1.0           |         py38_cpu         4.8 MB  pytorch
    torchvision-0.16.0         |         py38_cpu        11.4 MB  pytorch
```
These are previous versions, we expect to install newly released vesions.
Pytorch 2.1.1
Torchaudio 2.1.1
Torchvision 0.16.1

Possible issue could be that repodata is not updated:
https://conda.anaconda.org/pytorch/noarch

### Expected behavior or outcome

 we expect to install newly released vesions:
Pytorch 2.1.1
Torchaudio 2.1.1
Torchvision 0.16.1

Same issue as: https://github.com/ContinuumIO/anaconda-issues/issues/13188

**Comment by atalman** [comment]
cc @csoja @yshmatov-anaconda @barabo

**Comment by rasquith** [comment]
Hey folks, helping to triage this. Re: https://conda.anaconda.org/pytorch/noarch -- Did you upload a noarch version for each of the packages on this list?

**Comment by atalman** [comment]
Hi @rasquith looks like issue is resolved. Confirmed by running: https://github.com/pytorch/builder/actions/runs/6869727043/job/18685626963

**Comment by rasquith** [comment]
Gotcha. thanks for the update.
