### ISSUE TITLE
Navigator for 4.2 not opening

### ISSUE THREAD

**Issue by jrpwwilliams** [ContinuumIO/anaconda-issues#1331]
I have a similar issue with a slightly different stack trace for 4.2 for python 3.5 downloaded and installed on windows 10 1/5/17

```
Traceback (most recent call last):
File "C:\Users\jrpwilliams\Anaconda3\Scripts\anaconda-navigator-script.py", line 5, in 
sys.exit(anaconda_navigator.app.main.main())
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 70, in main
window = run_app(splash)
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 38, in run_app
window = MainWindow(splash=splash)
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 145, in init
self.api = AnacondaAPI()
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 434, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 39, in init
self._conda_api = CondaAPI()
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1185, in CondaAPI
CONDA_API = _CondaAPI()
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 267, in init
self.set_root_prefix()
File "C:\Users\jrpwilliams\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 374, in set_root_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers
```

**Comment by goanpeca** [comment]
@jrpwwilliams could yo go to the console and type

```
$ conda info
$ conda list
```

And paste the results here?

**Comment by jrpwwilliams** [comment]
[0x7FFEF22C70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FFEF22C70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\jrpwilliams\Anaconda3  (writable)
    default environment : C:\Users\jrpwilliams\Anaconda3
       envs directories : C:\Users\jrpwilliams\Anaconda3\envs
          package cache : C:\Users\jrpwilliams\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

-----------------------------------------------------------------------------
[0x7FFEF22C70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FFEF22C70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
# packages in environment at C:\Users\jrpwilliams\Anaconda3:
#
_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
alabaster                 0.7.9                    py35_0
anaconda                  4.2.0               np111py35_0
anaconda-clean            1.0.0                    py35_0
anaconda-client           1.5.1                    py35_0
anaconda-navigator        1.3.1                    py35_0
argcomplete               1.0.0                    py35_1
astroid                   1.4.7                    py35_0
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.7.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.2.9                    py35_0
conda-build               2.0.2                    py35_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.5                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24.1                   py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.11.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.2                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_2  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
lazy-object-proxy         1.2.1                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.13.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.4                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.3               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.3                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.28.1              np111py35_0
numexpr                   2.6.1               np111py35_0
numpy                     1.11.1                   py35_1
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2j                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0
partd                     0.3.6                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    3.3.1                    py35_0
pip                       8.1.2                    py35_0
pkginfo                   1.3.2                    py35_0
ply                       3.9                      py35_0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.3.0                    py35_0
pygments                  2.1.3                    py35_0
pylint                    1.5.4                    py35_1
pyopenssl                 16.0.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.6.1                 py35_0
pywin32                   220                      py35_1
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.0                    vc14_0  [vc14]
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.1.2                    py35_0
requests                  2.11.1                   py35_0
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.18.1              np111py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.6                    py35_0
spyder                    3.0.0                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.4.1                    py35_0
traitlets                 4.3.0                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.6                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by goanpeca** [comment]
@jrpwwilliams could you update to the latest version 1.3.2 ?

On the command prompt you can type

`$ conda install anaconda-navigator=1.3.2`

**Comment by jrpwwilliams** [comment]
I still get the same stack trace after, except where it was main lines 70&38 it's now 72%40

**Comment by jrpwwilliams** [comment]
[0x7FFEF22C70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FFEF22C70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\jrpwilliams\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    conda-4.2.13               |           py35_0         449 KB
    anaconda-navigator-1.3.2   |           py35_0         3.1 MB
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following NEW packages will be INSTALLED:

    conda-env:          2.6.0-0

The following packages will be UPDATED:

    anaconda-navigator: 1.3.1-py35_0 --> 1.3.2-py35_0
    conda:              4.2.9-py35_0 --> 4.2.13-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00  55.29 kB/s
conda-4.2.13-p 100% |###############################| Time: 0:00:00 827.93 kB/s
anaconda-navig 100% |###############################| Time: 0:00:01   1.95 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

**Comment by goanpeca** [comment]
Could you delete this folder

`C:\Users\jrpwilliams\.anaconda\`

And then try again. If you keep getting the error could you send the logs file located at

`C:\Users\jrpwilliams\.anaconda\navigator\logs\`

**Comment by jrpwwilliams** [comment]
[logs.zip](https://github.com/ContinuumIO/anaconda-issues/files/694033/logs.zip)

**Comment by jrpwwilliams** [comment]
Is that log any help? User error or tough problem?

**Comment by goanpeca** [comment]
Could you type

`$ conda info --json` on the terminal and past the complete ouput?

**Comment by jrpwwilliams** [comment]
[0x7FF8502A70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FF8502A70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/win-64",
    "https://repo.continuum.io/pkgs/free/noarch",
    "https://repo.continuum.io/pkgs/pro/win-64",
    "https://repo.continuum.io/pkgs/pro/noarch",
    "https://repo.continuum.io/pkgs/msys2/win-64",
    "https://repo.continuum.io/pkgs/msys2/noarch"
  ],
  "conda_build_version": "2.0.2",
  "conda_env_version": "4.2.13",
  "conda_prefix": "C:\\Users\\jrpwilliams\\Anaconda3",
  "conda_private": false,
  "conda_version": "4.2.13",
  "default_prefix": "C:\\Users\\jrpwilliams\\Anaconda3",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "<not set>",
    "CONDA_ENVS_PATH": "<not set>",
    "PATH": "C:\\Users\\jrpwilliams\\Anaconda3\\Library\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files\\Dell\\Dell Data Protection\\Drivers\\TSS\\bin\\;C:\\Vagrant\\bin;C:\\Program Files\\OpenSSH\\bin;C:\\ProgramData\\chocolatey\\bin;;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Users\\jrpwilliams\\Anaconda3;C:\\Users\\jrpwilliams\\Anaconda3\\Scripts;C:\\Users\\jrpwilliams\\Anaconda3\\Library\\bin;C:\\Users\\jrpwilliams\\AppData\\Local\\Microsoft\\WindowsApps;",
    "PYTHONHOME": "<not set>",
    "PYTHONPATH": "<not set>"
  },
  "envs": [],
  "envs_dirs": [
    "C:\\Users\\jrpwilliams\\Anaconda3\\envs"
  ],
  "offline": false,
  "pkgs_dirs": [
    "C:\\Users\\jrpwilliams\\Anaconda3\\pkgs"
  ],
  "platform": "win-64",
  "python_version": "3.5.2.final.0",
  "rc_path": null,
  "requests_version": "2.11.1",
  "root_prefix": "C:\\Users\\jrpwilliams\\Anaconda3",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "C:\\Users\\jrpwilliams\\Anaconda3\\python.exe",
  "sys.prefix": "C:\\Users\\jrpwilliams\\Anaconda3",
  "sys.version": "3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]",
  "sys_rc_path": "C:\\Users\\jrpwilliams\\Anaconda3\\.condarc",
  "user_rc_path": "C:\\Users\\jrpwilliams\\.condarc"
}

**Comment by goanpeca** [comment]
What is

[0x7FF8502A70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FF8502A70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)?

Is that is part of the stdout then that is why navigator does not start. We expect a json reply and those 2 lines are not json at all.

**Comment by jrpwwilliams** [comment]
I get those two lines with every conda command I enter. I've just googled it and got some suggestions. Let me play with those and get back to you if there are still problems after that.
Thanks

**Comment by jrpwwilliams** [comment]
Thank you for your help. I have been unable to resolve the anomaly... issue with any of the guidance I've found, but have been able to successfully install and run on an older windows 7 machine so I can work from  that.
Thanks
