### ISSUE TITLE
Anaconda-navigator and spyder not opening

### ISSUE THREAD

**Issue by Manik-Goyal** [ContinuumIO/anaconda-issues#1333]
After the command conda update anaconda
the navigator and spyder are not woking with the following error

```
Traceback (most recent call last):
  File "C:\Users\mgext\Anaconda2\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\mgext\Anaconda2\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\mgext\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\mgext\Anaconda2\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\mgext\Anaconda2\lib\site-packages\qtpy\__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

error simmilar for navigato

**Comment by goanpeca** [comment]
@Manik-Goyal could yo go to the command prompt and type

```
$ conda info
$ conda list
``` 

And paste the results here?

**Comment by Manik-Goyal** [comment]
_license                  1.1                      py27_1
_nb_ext_conf              0.3.0                    py27_0
alabaster                 0.7.9                    py27_0
anaconda                  4.2.0               np111py27_0
anaconda-clean            1.0.0                    py27_0
anaconda-client           1.5.1                    py27_0
anaconda-navigator        1.3.1                    py27_0
anaconda-navigator        1.2.3                     <pip>
argcomplete               1.0.0                    py27_1
astroid                   1.4.7                    py27_0
astropy                   1.2.1               np111py27_0
babel                     2.3.4                    py27_0
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
beautifulsoup4            4.5.1                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.10.1                   py27_0
bokeh                     0.12.2                   py27_0
boto                      2.42.0                   py27_0
bottlechest               0.7.1                    py27_0
bottleneck                1.1.0               np111py27_0
bzip2                     1.0.6                     vc9_3  [vc9]
cdecimal                  2.3                      py27_2
cffi                      1.7.0                    py27_0
chest                     0.2.3                    py27_0
click                     6.6                      py27_0
cloudpickle               0.2.1                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.7                    py27_0
comtypes                  1.1.2                    py27_0
conda                     4.2.13                   py27_0
conda-build               2.0.0                    py27_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py27_0
configparser              3.5.0                    py27_0
console_shortcut          0.1.1                    py27_1
contextlib2               0.5.3                    py27_0
cryptography              1.5                      py27_0
curl                      7.49.0                    vc9_0  [vc9]
cycler                    0.10.0                   py27_0
cython                    0.24.1                   py27_0
cytoolz                   0.8.0                    py27_0
dask                      0.11.0                   py27_0
datashape                 0.5.2                    py27_0
decorator                 4.0.10                   py27_0
dill                      0.2.5                    py27_0
django                    1.10.5                   py27_0
docutils                  0.12                     py27_2
entrypoints               0.2.2                    py27_0
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_1
filelock                  2.0.6                    py27_0
flask                     0.11.1                   py27_0
flask-cors                2.1.2                    py27_0
freetype                  2.5.5                     vc9_1  [vc9]
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
get_terminal_size         1.0.0                    py27_0
gevent                    1.1.2                    py27_0
git                       2.9.3                         0
greenlet                  0.4.10                   py27_0
grin                      1.2.1                    py27_3
h5py                      2.6.0               np111py27_2
hdf4                      4.2.12                    vc9_0  [vc9]
hdf5                      1.8.15.1                  vc9_4  [vc9]
heapdict                  1.0.0                    py27_1
html5lib                  0.999                    py27_0
icu                       57.1                      vc9_0  [vc9]
idna                      2.1                      py27_0
imagesize                 0.7.1                    py27_0
ipaddress                 1.0.16                   py27_0
ipykernel                 4.5.0                    py27_0
ipython                   5.1.0                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                5.2.2                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.2                      py27_1
jedi                      0.9.0                    py27_1
jinja2                    2.8                      py27_1
jpeg                      8d                        vc9_2  [vc9]
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.4.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.2.0                    py27_0
Keras                     1.1.0                     <pip>
Keras                     1.0.0                     <pip>
launcher                  1.0.0                         4
lazy-object-proxy         1.2.1                    py27_0
libpng                    1.6.22                    vc9_0  [vc9]
libpython                 2.0                      py27_0
libtiff                   4.0.6                     vc9_2  [vc9]
llvmlite                  0.13.0                   py27_0
locket                    0.2.0                    py27_1
lxml                      3.6.4                    py27_0
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
make                      3.82                          0
markupsafe                0.23                     py27_2
matplotlib                1.5.3               np111py27_0
matplotlib-tests          1.5.1                      py_0
menuinst                  1.4.1                    py27_0
mingw                     4.7                           1
mistune                   0.7.3                    py27_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py27_2
mpmath                    0.19                     py27_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.8                    py27_0
mysql-connector           2.1.4                     <pip>
mysql-connector-python    2.0.4                    py27_0
MySQL-python              1.2.5                     <pip>
mysql-python              1.2.5                    py27_0
nb_anacondacloud          1.2.0                    py27_0
nb_conda                  2.0.0                    py27_0
nb_conda_kernels          2.0.0                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.1.0                    py27_0
nbpresent                 3.0.2                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2.1                    py27_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py27_1
notebook                  4.2.3                    py27_0
numba                     0.28.1              np111py27_0
numexpr                   2.6.1               np111py27_0
numpy                     1.11.1                   py27_1
numpy                     1.11.3                    <pip>
odo                       0.5.0                    py27_1
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2j                    vc9_0  [vc9]
pandas                    0.18.1              np111py27_0
pandas-datareader         0.2.1                    py27_0
pandasql                  0.7.3                    py27_0
partd                     0.3.6                    py27_0
path.py                   8.2.1                    py27_0
pathlib2                  2.1.0                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
perl                      5.20.3.1                      1
pickleshare               0.7.4                    py27_0
pillow                    3.3.1                    py27_0
pip                       9.0.1                     <pip>
pip                       8.1.2                    py27_0
pkginfo                   1.3.2                    py27_0
ply                       3.9                      py27_0
prompt_toolkit            1.0.3                    py27_0
psutil                    4.3.1                    py27_0
py                        1.4.31                   py27_0
pyasn1                    0.1.9                    py27_0
pycosat                   0.6.1                    py27_1
pycparser                 2.14                     py27_1
pycrypto                  2.6.1                    py27_4
pycurl                    7.43.0                   py27_0
pyflakes                  1.3.0                    py27_0
pygments                  2.1.3                    py27_0
pylint                    1.5.4                    py27_1
pyopenssl                 16.0.0                   py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_0
pyreadline                2.1                      py27_0
pytables                  3.2.2               np111py27_4
pytest                    2.9.2                    py27_0
python                    2.7.12                        0
python-dateutil           2.5.3                    py27_0
pytz                      2016.6.1                 py27_0
pywin32                   220                      py27_1
pyyaml                    3.12                     py27_0
pyzmq                     15.4.0                   py27_0
qgrid                     0.3.2                    py27_0
qt                        5.6.0                     vc9_0  [vc9]
qtawesome                 0.3.3                    py27_0
qtconsole                 4.2.1                    py27_2
qtpy                      1.1.2                    py27_0
requests                  2.11.1                   py27_0
requests-file             1.4                      py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_0
scikit-image              0.12.3              np111py27_1
scikit-learn              0.17.1              np111py27_1
scipy                     0.18.1              np111py27_0
setuptools                27.2.0                   py27_1
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.3                    py27_0
sphinx                    1.4.6                    py27_0
sphinx_rtd_theme          0.1.9                    py27_0
spyder                    3.0.0                    py27_0
sqlalchemy                1.0.13                   py27_0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.6.1               np111py27_1
sympy                     1.0                      py27_0
Theano                    0.9.0.dev3                <pip>
theano                    0.8.2                    py27_0
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.0                    py27_0
tornado                   4.4.1                    py27_0
traitlets                 4.3.0                    py27_0
transaction               1.6.1                    py27_0
unicodecsv                0.14.1                   py27_0
vs2008_runtime            9.00.30729.1                  2
wcwidth                   0.1.7                    py27_0
werkzeug                  0.11.11                  py27_0
wget                      2.2                      py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        1.2.6                    py27_0
win_unicode_console       0.5                      py27_0
wrapt                     1.10.6                   py27_0
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.3                    py27_0
xlwings                   0.10.0                   py27_0
xlwt                      1.1.2                    py27_0
zlib                      1.2.8                     vc9_3  [vc9]
zope                      1.0                      py27_0
zope.interface            4.3.3                    py27_0

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\mgext\Anaconda2  (writable)
    default environment : C:\Users\mgext\Anaconda2
       envs directories : C:\Users\mgext\Anaconda2\envs
          package cache : C:\Users\mgext\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

**Comment by goanpeca** [comment]
@Manik-Goyal not sure what could be the problem

Could you reinstall qt5 and pyqt5 and qtpy?

`$ conda install qt=5 pyqt=5 qtpy=1.1.2 --force`

Does your user name contain spaces or non ascii characters?

**Comment by Manik-Goyal** [comment]
I tried re-installing qt5, pyqt5 and qtpy .Unfortunately that didn't solve so I finally deleted the whole Anaconda and installed again.
Guess its somewhat windows related problem.
Thanks for the help.

**Comment by goanpeca** [comment]
@Manik-Goyal, did the reinstall solve the issue?

**Comment by Manik-Goyal** [comment]
Yes it solved the issue.

**Comment by lourew** [comment]
Hi, I have the same issue but i have deleted it and reinstalled a number of times and the anaconda navigator will still not open.

Any help would be much appreciated

**Comment by M00NSH0T** [comment]
same here. I was able to open spyder after doing a clean install, but once I did a 'conda update --all', I found myself back at square one.

**Comment by HritikKumarSharma** [comment]
Hey, You can try this one also:
**$ conda install PySide**

**Comment by BLMeltdown** [comment]
I would not advice this; before arriving there, I have tried to figure out the problem and observed that the pyside module was missing, but when I wanted to install it, it tried to downgrade every package to python 2.7 from python 3.7.
This obviouly is not a solution.

**Comment by M00NSH0T** [comment]
I found the issue for me was caused when I tried to update Pandas to 0.24 or 0.24.1 alongside Keras-gpu. There are a lot of dependencies that get updated along with Pandas, so I suspect the conflict is with one of those and Keras (or perhaps one of its dependencies, like tensorflow), but I don't know which. I encountered this in both Windows and Linux. My solution has been to delete my broken environment (which coincidentally also prevents Spyder from opening in any other environment for some reason), and then recreate it, but force Pandas to 0.23.4. As long as Pandas stays there, it seems to all be ok. Anyway, I don't have time at the moment to go through each of the dependencies one by one and isolate this, but if anyone else wants to have a go, perhaps this can finally get resolved. 

I will say that having both Keras and Pandas installed is pretty common, so I imagine as more people update their version of Pandas, we should see more people encountering this issue.

**Comment by dberrian** [comment]
I managed to solve that as follow: 
1- Run this on Anaconda prompt : conda install -c anaconda pyqt 
2 - Uninstall and install Spyder through Anaconda navigator.

**Comment by PhysXu** [comment]
> 
> 
> I managed to solve that as follow:
> 1- Run this on Anaconda prompt : conda install -c anaconda pyqt
> 2 - Uninstall and install Spyder through Anaconda navigator.

Hi, I have met the same problem with Spyder-opening, But additionally, my  Anaconda Navigator is also cannot open.
How can I solve that?

**Comment by yahya2020** [comment]
i had the same issue (can't open anaconda-navigator or spyder). i fixed it by installing anaconda2 Anaconda2-2018.12-Windows-x86_64.exe in the place of anaconda3 from the repository  https://repo.anaconda.com/archive/

--

**Comment by liuhh02** [comment]
This worked for me:

> pip uninstall PyQt5
conda update conda
conda update anaconda-navigator
conda install --force-reinstall pyqt qt

**Comment by dhodyrahmad** [comment]
> This worked for me:
> 
> > pip uninstall PyQt5
> > conda update conda
> > conda update anaconda-navigator
> > conda install --force-reinstall pyqt qt

this worked for me too but **conda update conda** and **conda update anaconda-navigator** cant be done. so i used **conda update --all** instead and spyder can running as usually again.
