### ISSUE TITLE
LibMambaUnsatisfiableError: Encountered problems while solving: while creating new conda env via .yml file win-64

### ISSUE THREAD

**Issue by MarkusRenner** [ContinuumIO/anaconda-issues#13340]
### Checklist

- [X] I added a descriptive title (including the requested package **name**, **version**, and **platform**).
- [X] I searched the defaults channels ([Python](https://repo.anaconda.com/pkgs/main/) and [R](https://repo.anaconda.com/pkgs/r/)) and did not find the package I'm requesting.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and did not find a duplicate request for this package.

### Request type

- [X] New (i.e. no versions of this package currently exist on repo.anaconda.com)
- [X] Update (i.e. older versions of this package exist and I'm requesting an updated version)
- [X] Rebuild (i.e. something is wrong with an existing version of this package and it needs to be rebuilt)

### Name

LibMambaUnsatisfiableError

### Version

latest

### Platform(s)

Win-64

### Location of source code

https://github.com/DataScienceHamburg/PyTorchUltimateMaterial

### Reason for this request

I cannot install the .yml file because I am facing a "LibMambaUnsatisfiableError".
I'd highly appreciate any help to solve this issue.

### (OPTIONAL) Additional information

(base) C:\Users\Markus\Documents\Git\GitHub\udemy\PyTorchUltimateMaterial>conda env create --file pytorch.yml --force
Channels:
 - pytorch
 - conda-forge
 - anaconda
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - pytorch
 - conda-forge
 - anaconda
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package bottleneck-1.3.4-py310h9128911_0 is excluded by strict repo priority
  - package brotlipy-0.7.0-py310h2bbff1b_1002 is excluded by strict repo priority
  - package bzip2-1.0.8-he774522_0 is excluded by strict repo priority
  - package cffi-1.15.0-py310h2bbff1b_1 is excluded by strict repo priority
  - package colorama-0.4.4-pyhd3eb1b0_0 is excluded by strict repo priority
  - package cryptography-37.0.1-py310h21b164f_0 is excluded by strict repo priority
  - package cycler-0.11.0-pyhd3eb1b0_0 is excluded by strict repo priority
  - package debugpy-1.5.1-py310hd77b12b_0 is excluded by strict repo priority
  - package decorator-5.1.1-pyhd3eb1b0_0 is excluded by strict repo priority
  - package entrypoints-0.4-py310haa95532_0 is excluded by strict repo priority
  - package fonttools-4.25.0-pyhd3eb1b0_0 is excluded by strict repo priority
  - package glib-2.69.1-h5dc1a3c_1 is excluded by strict repo priority
  - package gst-plugins-base-1.18.5-h9e645db_0 is excluded by strict repo priority
  - package gstreamer-1.18.5-hd78058f_0 is excluded by strict repo priority
  - package icu-58.2-vc14hc45fdbb_0 is excluded by strict repo priority
  - package idna-3.3-pyhd3eb1b0_0 is excluded by strict repo priority
  - package intel-openmp-2021.4.0-haa95532_3556 is excluded by strict repo priority
  - package ipython-8.3.0-py310haa95532_0 is excluded by strict repo priority
  - package jedi-0.18.1-py310haa95532_1 is excluded by strict repo priority
  - package joblib-1.1.0-pyhd3eb1b0_0 is excluded by strict repo priority
  - package jpeg-9e-h2bbff1b_0 is excluded by strict repo priority
  - package jupyter_client-7.2.2-py310haa95532_0 is excluded by strict repo priority
  - package jupyter_core-4.10.0-py310haa95532_0 is excluded by strict repo priority
  - package kiwisolver-1.3.1-py310hd77b12b_0 is excluded by strict repo priority
  - package libffi-3.4.2-h604cdb4_1 is excluded by strict repo priority
  - package libpng-1.6.37-h2a8f88b_0 is excluded by strict repo priority
  - package libprotobuf-3.20.1-h23ce68f_0 is excluded by strict repo priority
  - package libtiff-4.2.0-he0120a3_1 is excluded by strict repo priority
  - package libuv-1.40.0-he774522_0 is excluded by strict repo priority
  - package libwebp-1.2.2-h2bbff1b_0 is excluded by strict repo priority
  - package lz4-c-1.9.3-h2bbff1b_1 is excluded by strict repo priority
  - package matplotlib-3.5.1-py310haa95532_1 is excluded by strict repo priority
  - package matplotlib-base-3.5.1-py310hd77b12b_1 is excluded by strict repo priority
  - package mkl-2021.4.0-haa95532_640 is excluded by strict repo priority
  - package mkl-service-2.4.0-py310h2bbff1b_0 is excluded by strict repo priority
  - package mkl_fft-1.3.1-py310ha0764ea_0 is excluded by strict repo priority
  - package mkl_random-1.2.2-py310h4ed8f06_0 is excluded by strict repo priority
  - package numexpr-2.8.1-py310hb57aa6b_1 is excluded by strict repo priority
  - package numpy-1.21.5-py310h6d2d95c_3 is excluded by strict repo priority
  - package opencv-4.5.5-py310h42e1cb5_0 is excluded by strict repo priority
  - package packaging-21.3-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pandas-1.4.2-py310hd77b12b_0 is excluded by strict repo priority
  - package pickleshare-0.7.5-pyhd3eb1b0_1003 is excluded by strict repo priority
  - package pillow-9.0.1-py310hdc2b20a_0 is excluded by strict repo priority
  - package pip-21.2.4-py310haa95532_0 is excluded by strict repo priority
  - package pycparser-2.21-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pygments-2.11.2-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pyopenssl-22.0.0-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pyparsing-3.0.4-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pyqt-5.9.2-py310hd77b12b_6 is excluded by strict repo priority
  - package pysocks-1.7.1-py310haa95532_0 is excluded by strict repo priority
  - package python-3.10.4-hbb2ffb3_0 is excluded by strict repo priority
  - package python-dateutil-2.8.2-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pytz-2021.3-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pywin32-302-py310h2bbff1b_2 is excluded by strict repo priority
  - package pyzmq-22.3.0-py310hd77b12b_2 is excluded by strict repo priority
  - package qt-5.9.7-vc14h73c81de_0 is excluded by strict repo priority
  - package requests-2.27.1-pyhd3eb1b0_0 is excluded by strict repo priority
  - package scipy-1.7.3-py310h6d2d95c_0 is excluded by strict repo priority
  - package setuptools-61.2.0-py310haa95532_0 is excluded by strict repo priority
  - package sip-4.19.13-py310hd77b12b_0 is excluded by strict repo priority
  - package six-1.16.0-pyhd3eb1b0_1 is excluded by strict repo priority
  - package sqlite-3.38.3-h2bbff1b_0 is excluded by strict repo priority
  - package tk-8.6.12-h2bbff1b_0 is excluded by strict repo priority
  - package tornado-6.1-py310h2bbff1b_0 is excluded by strict repo priority
  - package traitlets-5.1.1-pyhd3eb1b0_0 is excluded by strict repo priority
  - package typing_extensions-4.1.1-pyh06a4308_0 is excluded by strict repo priority
  - package urllib3-1.26.9-py310haa95532_0 is excluded by strict repo priority
  - package vc-14.2-h21ff451_1 is excluded by strict repo priority
  - package vs2015_runtime-14.27.29016-h5e58377_2 is excluded by strict repo priority
  - package wcwidth-0.2.5-pyhd3eb1b0_0 is excluded by strict repo priority
  - package wheel-0.37.1-pyhd3eb1b0_0 is excluded by strict repo priority
  - package win_inet_pton-1.1.0-py310haa95532_0 is excluded by strict repo priority
  - package wincertstore-0.2-py310haa95532_2 is excluded by strict repo priority
  - package xz-5.2.5-h8cc25b3_1 is excluded by strict repo priority
  - package zlib-1.2.12-h8cc25b3_2 is excluded by strict repo priority
  - package zstd-1.5.2-h19a0ad4_0 is excluded by strict repo priority
  - package asttokens-2.0.5-pyhd3eb1b0_0 is excluded by strict repo priority
  - package backcall-0.2.0-pyhd3eb1b0_0 is excluded by strict repo priority
  - package charset-normalizer-2.0.4-pyhd3eb1b0_0 is excluded by strict repo priority
  - package executing-0.8.3-pyhd3eb1b0_0 is excluded by strict repo priority
  - package matplotlib-inline-0.1.2-pyhd3eb1b0_2 is excluded by strict repo priority
  - package munkres-1.1.4-py_0 is excluded by strict repo priority
  - package nest-asyncio-1.5.5-py310haa95532_0 is excluded by strict repo priority
  - package parso-0.8.3-pyhd3eb1b0_0 is excluded by strict repo priority
  - package prompt-toolkit-3.0.20-pyhd3eb1b0_0 is excluded by strict repo priority
  - package pure_eval-0.2.2-pyhd3eb1b0_0 is excluded by strict repo priority
  - package stack_data-0.2.0-pyhd3eb1b0_0 is excluded by strict repo priority
  - package threadpoolctl-2.2.0-pyh0d69192_0 is excluded by strict repo priority
  - package tzdata-2022a-hda174b7_0 is excluded by strict repo priority
  - package ipykernel-6.9.1-py310haa95532_0 is excluded by strict repo priority
  - package scikit-learn-1.0.2-py310h4ed8f06_0 is excluded by strict repo priority
  - package seaborn-0.11.2-pyhd3eb1b0_0 is excluded by strict repo priority

**Comment by MsAlEhR** [comment]
I have same issue , do you find any solution ?

**Comment by Soumya624** [comment]
Got the same issue when I was trying to use **conda config --set channel_priority strict**. But, making it **Flexible** was solving the issue!

**Comment by MarkusRenner** [comment]
Thanks a lot @Soumya624!

**Comment by beetlejuice007** [comment]
this didn't work for me. still getting the same error.

**Comment by kwaititu** [comment]
Kindly assist in solving the error 'Solving environment: failed'

"LibMambaUnsatisfiableError: Encountered problems while solving" when i install .yml file below

"conda env create -n qiime2-amplicon-2024.5 --file https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml"

Channels:
 - https://packages.qiime2.org/qiime2/2024.5/amplicon/released
 - bioconda
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed
