### ISSUE TITLE
Application launch error

### ISSUE THREAD

**Issue by geovanifreitas** [ContinuumIO/anaconda-issues#13352]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

I moved some files within Jupyter Notebook to the OneDrive folder and after that my OneDrive cloud got updated. All of a sudden, when I tried to launch Jupyter Notebook, I found this error that my conda repository was empty, and therefore it could not be launched. After that, I tried to uninstall Anaconda, but the conda commands were not recognized because there was no valid conda directory. So I decided to delete manually all the files linked to the Anaconda and tried to install again Anaconda in my Windows system and it worked, however when I launched any of the applications, such as Jupyter Notebook or Spyder, I found that the applications could not run on my PC and therefore I should contact the software suppliers. Therefore if you could help me with this issue, I would really appreciate. Thank you in advance.

### Expected behavior or outcome

The application cannot run on my PC, and therefore I should contact the software suppliers.

### Conda info

```shell
Conda command not recognized and I should contact the software suppliers.
```

### Conda config

```shell
Conda command not recognized and I should contact the software suppliers.
```

### Conda list

```shell
Conda command not recognized and I should contact the software suppliers.
```

### Additional information

I decided to delete Anaconda folders manually because the executable to uninstall Anaconda was not working at all. Even when I tried to uninstall Anaconda in the Control Panel, the action could not be done because there was no valid conda directory. When i installed Anaconda again, I realized that there were two versions of Anaconda in the Control Panel, and after I uninstalled the two versions and install Anaconda latest version, I saw that none of the applications could run on my PC.

**Comment by pseudoyim** [comment]
Hi @geovanifreitas 
>I moved some files within Jupyter Notebook to the OneDrive folder and after that my OneDrive cloud got updated. 

Without knowing which files you moved, it will be very difficult for us to help you troubleshoot. Also, the _Anaconda Distribution_ installer is meant to be used locally, not with a cloud service like OneDrive. If you run into issues with a local installation, please reach out to us with details and we'll be happy to take a look.
