### ISSUE TITLE
Conda can only create environments 3.8 and below. 3.9, 3.10, 3.11, 3.12 will build errors. The error message is as follows

### ISSUE THREAD

**Issue by zjh-nuc-AIOT** [ContinuumIO/anaconda-issues#13355]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [X] Anaconda.org

### What happened?

Conda can only create environments 3.8 and below. 3.9, 3.10, 3.11, 3.12 will build errors. 
conda create -n test39 python=3.9
The error message is as follows
![ac54dc2926cc9f81ae494b62e8e3e15](https://github.com/ContinuumIO/anaconda-issues/assets/57065248/b50a0fcb-cd84-4a46-93e0-4c2b72c31d4c)

### Expected behavior or outcome

Striving for a Creating Environment

**Comment by ryanskeith** [comment]
How did you install conda and would you provide your conda info output?

**Comment by pseudoyim** [comment]
Issue reporter has not responded. Closing.
