### ISSUE TITLE
Unavailable Multibyte language (Mozc )

### ISSUE THREAD

**Issue by hk216** [ContinuumIO/anaconda-issues#1335]
I use spyder by starting it from Anaconda-Navigator, and starting it from a terminal. I can't use Multibyte language(Mozc) in IPython console in the former case. I can use it in the latter case. Why I can't use it? I sent the mail to know the reasons.

**Comment by hk216** [comment]
I mention in a postscript that I can use Mozc from jupyter called from Anaconda-Navigator like IPython notebook called from a terminal.
I think the Ipython console which was called from Anaconda-Navigator doesn't support Multibyte language thogh the original Ipython console which was called from a terminal supports  Multibyte language.
Please teach me the reason.

**Comment by goanpeca** [comment]
@hk216 please report this in the [spyder issue tracker](https://github.com/spyder-ide/spyder)
