### ISSUE TITLE
Downloads from `pytorch` channel are very slow

### ISSUE THREAD

**Issue by apoorvkh** [ContinuumIO/anaconda-issues#13366]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

I am currently not able to download Pytorch from the `pytorch` and `pytorch-test` channels in a reasonable time. Some portions of the file download faster but it usually seems to be bottlenecked at 30 KB/s (maybe the download will take 10s of minutes or hours).
I am using a university cluster with a pretty fast network connection (near Boston).

We can see that this seems to be a current issue for other users as well: https://github.com/pytorch/pytorch/issues/88659#issuecomment-2007974239

E.g. (just using `wget` instead of `conda install` here to see speeds):
```
❯ wget https://conda.anaconda.org/pytorch/linux-64/pytorch-2.2.2-py3.11_cuda12.1_cudnn8.9.2_0.tar.bz2
--2024-04-04 00:02:49--  https://conda.anaconda.org/pytorch/linux-64/pytorch-2.2.2-py3.11_cuda12.1_cudnn8.9.2_0.tar.bz2
Resolving conda.anaconda.org (conda.anaconda.org)... 104.19.144.37, 104.19.145.37, 2606:4700::6813:9025, ...
Connecting to conda.anaconda.org (conda.anaconda.org)|104.19.144.37|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1446426807 (1.3G) [application/x-tar]
Saving to: ‘pytorch-2.2.2-py3.11_cuda12.1_cudnn8.9.2_0.tar.bz2’

pytorch-2.2.2-py3.11_cuda12.1_cudnn8  17%[===========>                                                           ] 241.98M   28.9KB/s
```

cc: @atalman (since you opened #13364 here recently)

### Expected behavior or outcome

Can we solve the underlying issue or create a faster mirror to get a reasonable download speed?

**Comment by moracca** [comment]
same for me.  I'm getting ~180 kB/s when downloading torch

**Comment by apoorvkh** [comment]
The downloads are fast again, so I think it was a temporary issue. If this is a problem in the future, should probably make an issue in PyTorch, since these issues don't appear to be monitored.
