### ISSUE TITLE
mac-x86 build python 3.10, with "--with-ensurepip" flag，no 'pip3' file in "bin" directory

### ISSUE THREAD

**Issue by LittleBox-x** [ContinuumIO/anaconda-issues#13363]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

mac-x86 build python 3.10, with "--with-ensurepip" flag，no 'pip3' file in "bin" directory

### Expected behavior or outcome

mac-x86 build python 3.10, with "--with-ensurepip" flag，no 'pip3' file in "bin" directory

**Comment by pseudoyim** [comment]
Not enough info here to help.
