### ISSUE TITLE
RStudio Installation Issue experienced on Anaconda 4.2

### ISSUE THREAD

**Issue by TheMitchWorksPro** [ContinuumIO/anaconda-issues#1337]
Started this issue here and was asked to move it under this repo.  This issue is open and all details are accessible on this link (but closing it on the other repo so discussion and solutions can continue here:

https://github.com/conda/conda/issues/4204

More detail is provided at above issue URL, including some comments with ideas that raise some more questions about how to implement work-around.  But in summation here's a few things from that URL:

Graphic of the original problem:
![image](https://cloud.githubusercontent.com/assets/23440318/21707657/34d46ba8-d39f-11e6-9bf1-ccb18b566dc6.png)

Files showing all environments that already existed in the environment before the RStudio button threw this error:

[anaconda_envs_list.txt](https://github.com/conda/conda/files/690132/anaconda_envs_list.txt)

[anaconda_env_update_dry-run.txt](https://github.com/conda/conda/files/690260/anaconda_env_update_dry-run.txt)

Some notes:
* This occurred on Windows 7 64 bit using Anaconda 4.2
* goal was environment with default Python 2.7, and additional envs for Python 3.6 and R
* 2.7 was needed in root so that Spyder would be 2.7 for an upcoming class
* class also needs RStudio installed
* Python 3.6 env was created using Jupyter --> conda tab [+] because Anaconda Navigator only goes up to 3.5
* all other environments created in Anaconda Navigator tab
* any environment with "clone" in the name was created using Anaconda clone button
* using "conda update --all" on the R environments resulted Python 2.7 packages showing up in them even though initially only selected R and they had R packages in them

Where I left off in comment thread on other environment:  it was proposed that I could build an R environment to install into, but I did not see an option when clicking the RStudio button to select environments even though I had two already at that time.  If I am to try again to use RStudio button, I need a step by step on what to do. Can someone provide this so I can complete my setup?

I am so close to having what I need now.  Thanks.

**Comment by TheMitchWorksPro** [comment]
@goanpeca posted this comment on the earlier issue before I closed it to migrate it here.  In reviewing this I now see I mis-read something and can attempt this.  Will give this a try and let you know how it goes.  Thanks so much for posts and the fact that I see people care and are looking into how to build a better Anaconda.  :-)

Thing I will attempt later today:

You can install applications in specific environments by selecting the environment on the combobox of the home screen.

On the environments tab create a new R/Python3.5 environment
On the Home tab install RStudio on The new environment you created by selecting it on the combobox on top (Applications on...)

**Comment by TheMitchWorksPro** [comment]
@goanpeca - screenshot you posted on previous issue (conda/conda/#4204) - was that Anaconda 4.3?  It looks different than mine.  

To that point - when Anaconda 4.3 is out, is there a way for those of us who used 4.2 to upgrade so Navigator gets all the right enhancements and what-not without having to blow away our environment and re-install under the new version?  

Saw references to 4.3 in issue repository but downloads page is still 4.2 so I assume you are testing this right now and it may not be out for a bit.

**Comment by goanpeca** [comment]
@TheMitchWorksPro the screenshot is the latest version of Navigator coming out soon. This version will also be the default shipped with the new release of Anaconda

**Comment by TheMitchWorksPro** [comment]
Root of my installation is Python 2.7.  As instructed, I started by creating R_w_PY35 environment on Navigator but then it started to do something that to me looks unexpected.  It gave messages that began with "linking Python" and then ran through a host of package names, but skipped up to the root environment while doing it.  Is this normal?

Is this normal or did we just corrupt my environment again?

![image](https://cloud.githubusercontent.com/assets/23440318/21755443/de254bca-d5e1-11e6-9c96-d3a3691acbfd.png)

**Comment by TheMitchWorksPro** [comment]
Environments seem to be working, but below is a dry run of the new environment if "conda update --all" were to be run on it immediately after having created it.  (also provided - a list of what is in the environment).

Does this need to be updated?  Can i update it safely to get all the additional packages?

# packages in environment at C:\ProgramFilesCoders\Anaconda2\envs\R_wPY35:
#
colorama                  0.3.7                    py35_0
decorator                 4.0.10                   py35_1
entrypoints               0.2.2                    py35_0
ipykernel                 4.5.2                    py35_0
ipython                   5.1.0                    py35_0
ipython-notebook          4.0.4                    py35_3
ipython_genutils          0.1.0                    py35_0
jinja2                    2.8.1                    py35_0
jsonschema                2.5.1                    py35_0
jupyter_client            4.4.0                    py35_0
jupyter_core              4.2.1                    py35_0
markupsafe                0.23                     py35_2
mistune                   0.7.3                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.2.0                    py35_0
notebook                  4.3.0                    py35_0
path.py                   9.0.1                    py35_0
pickleshare               0.7.4                    py35_0
pip                       9.0.1                    py35_1
prompt_toolkit            1.0.9                    py35_0
pygments                  2.1.3                    py35_0
python                    3.5.2                         0
pyzmq                     16.0.2                   py35_0
r                         3.1.3                         0    r
r-assertthat              0.1                          0a    r
r-base64enc               0.1_2                 r3.1.3_0a    r
r-bh                      1.55.0_3                     0a    r
r-bitops                  1.0_6                        0a    r
r-bradleyterry2           1.0_6                        0a    r
r-brglm                   0.5_9                        0a    r
r-car                     2.0_24                       0a    r
r-caret                   6.0_41                       0a    r
r-catools                 1.17.1                       0a    r
r-chron                   2.3_45                r3.1.3_0a    r
r-colorspace              1.2_4                        0a    r
r-data.table              1.9.4                 r3.1.3_0a    r
r-dbi                     0.3.1                        0a    r
r-dichromat               2.0_0                        0a    r
r-digest                  0.6.8                        0a    r
r-dplyr                   0.4.1                        0a    r
r-essentials              1.1                   r3.1.3_0a    r
r-evaluate                0.7                   r3.1.3_0a    r
r-foreach                 1.4.2                        0a    r
r-formatr                 1.2                   r3.1.3_0a    r
r-ggplot2                 1.0.0                        0a    r
r-glmnet                  2.0_2                 r3.1.3_0a    r
r-gtable                  0.1.2                        0a    r
r-gtools                  3.4.1                        0a    r
r-hexbin                  1.27.0                       0a    r
r-highr                   0.5                   r3.1.3_0a    r
r-htmltools               0.2.6                        0a    r
r-htmlwidgets             0.5                   r3.1.3_0a    r
r-httpuv                  1.3.2                 r3.1.3_0a    r
r-irdisplay               0.3                   r3.1.3_0a    r
r-irkernel                0.4                   r3.1.3_0a    r
r-iterators               1.0.7                        0a    r
r-jsonlite                0.9.16                r3.1.3_0a    r
r-knitr                   1.10                  r3.1.3_0a    r
r-labeling                0.3                          0a    r
r-lazyeval                0.1.10                       0a    r
r-lme4                    1.1_7                        0a    r
r-magrittr                1.5                          0a    r
r-maps                    2.3_9                        0a    r
r-markdown                0.7.7                 r3.1.3_0a    r
r-mime                    0.3                   r3.1.3_0a    r
r-minqa                   1.2.4                        0a    r
r-munsell                 0.4.2                        0a    r
r-nloptr                  1.0.4                        0a    r
r-pbkrtest                0.4_2                        0a    r
r-plyr                    1.8.1                        0a    r
r-profilemodel            0.5_9                        0a    r
r-proto                   0.3_10                       0a    r
r-quantmod                0.4_5                 r3.1.3_0a    r
r-quantreg                5.11                         0a    r
r-r6                      2.0.1                        0a    r
r-randomforest            4.6_10                r3.1.3_0a    r
r-rbokeh                  0.2.2                 r3.1.3_0a    r
r-rcolorbrewer            1.1_2                        0a    r
r-rcpp                    0.11.3                       0a    r
r-rcppeigen               0.3.2.3.0                    0a    r
r-repr                    0.3                   r3.1.3_0a    r
r-reshape2                1.4.1                        0a    r
r-rjsonio                 1.3_0                        0a    r
r-rmarkdown               0.5.1                 r3.1.3_0a    r
r-rzmq                    0.7.7                 r3.1.3_0a    r
r-scales                  0.2.4                        0a    r
r-shiny                   0.11.1                r3.1.3_0a    r
r-sparsem                 1.6                          0a    r
r-stringi                 0.4_1                 r3.1.3_0a    r
r-stringr                 0.6.2                        0a    r
r-tidyr                   0.2.0                 r3.1.3_0a    r
r-ttr                     0.23_0                r3.1.3_0a    r
r-uuid                    0.1_1                 r3.1.3_0a    r
r-xtable                  1.7_4                 r3.1.3_0a    r
r-xts                     0.9_7                 r3.1.3_0a    r
r-yaml                    2.1.13                       0a    r
r-zoo                     1.7_11                       0a    r
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
six                       1.10.0                   py35_0
tornado                   4.4.2                    py35_0
traitlets                 4.3.1                    py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
wheel                     0.29.0                   py35_0
win_unicode_console       0.5                      py35_0

(R_wPY35) C:\Users\Mitch\Documents\a_MLA\MLA\Code\education\Python\Anaconda\Mitc
h_Documentation>

Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\ProgramFilesCoders\Anaconda2\envs\R_wPY35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    notebook-4.3.1             |           py35_0         5.2 MB

The following NEW packages will be INSTALLED:

    m2w64-bwidget:           1.9.10-2              
    m2w64-bzip2:             1.0.6-6               
    m2w64-c-ares:            1.11.0-2              
    m2w64-ca-certificates:   20150426-103          
    m2w64-curl:              7.48.0-2              
    m2w64-expat:             2.1.1-2               
    m2w64-fftw:              3.3.4-6               
    m2w64-flac:              1.3.1-3               
    m2w64-gcc-libgfortran:   5.3.0-6               
    m2w64-gcc-libs:          5.3.0-7               
    m2w64-gcc-libs-core:     5.3.0-7               
    m2w64-gettext:           0.19.7-2              
    m2w64-gmp:               6.1.0-2               
    m2w64-gnutls:            3.4.11-2              
    m2w64-gsl:               2.1-2                 
    m2w64-jansson:           2.7-3                 
    m2w64-libffi:            3.2.1-4               
    m2w64-libiconv:          1.14-6                
    m2w64-libidn:            1.32-4                
    m2w64-libjpeg-turbo:     1.4.2-3               
    m2w64-libmetalink:       0.1.3-2               
    m2w64-libogg:            1.3.2-3               
    m2w64-libpng:            1.6.21-2              
    m2w64-libsndfile:        1.0.26-2              
    m2w64-libsodium:         1.0.10-2              
    m2w64-libssh2:           1.7.0-2               
    m2w64-libsystre:         1.0.1-3               
    m2w64-libtasn1:          4.7-2                 
    m2w64-libtiff:           4.0.6-2               
    m2w64-libtre-git:        122.c2f5d13-5         
    m2w64-libvorbis:         1.3.5-2               
    m2w64-libwinpthread-git: 5.0.0.4634.697f757-2  
    m2w64-libxml2:           2.9.3-3               
    m2w64-mpfr:              3.1.4-4               
    m2w64-nettle:            3.1.1-4               
    m2w64-nghttp2:           1.9.2-2               
    m2w64-nlopt:             2.4.2-3               
    m2w64-openssl:           1.0.2.g-2             
    m2w64-p11-kit:           0.23.2-2              
    m2w64-pcre:              8.38-2                
    m2w64-rtmpdump-git:      499.a107cef-4         
    m2w64-speex:             1.2rc2-3              
    m2w64-speexdsp:          1.2rc3-3              
    m2w64-tcl:               8.6.5-3               
    m2w64-tk:                8.6.5-3               
    m2w64-tktable:           2.10-5                
    m2w64-wineditline:       2.101-5               
    m2w64-xz:                5.2.2-2               
    m2w64-zeromq:            4.1.4-2               
    m2w64-zlib:              1.2.8-10              
    msys2-conda-epoch:       20160418-1            
    r-backports:             1.0.4-r3.3.2_0       r
    r-base:                  3.3.2-0              r
    r-boot:                  1.3_18-r3.3.2_0      r
    r-broom:                 0.4.1-r3.3.2_0       r
    r-class:                 7.3_14-r3.3.2_0      r
    r-cluster:               2.0.5-r3.3.2_0       r
    r-codetools:             0.2_15-r3.3.2_0      r
    r-crayon:                1.3.2-r3.3.2_0       r
    r-curl:                  2.3-r3.3.2_0         r
    r-forcats:               0.1.1-r3.3.2_0       r
    r-foreign:               0.8_67-r3.3.2_0      r
    r-gistr:                 0.3.6-r3.3.2_0       r
    r-haven:                 1.0.0-r3.3.2_0       r
    r-hms:                   0.3-r3.3.2_0         r
    r-httr:                  1.2.1-r3.3.2_0       r
    r-kernsmooth:            2.23_15-r3.3.2_0     r
    r-lattice:               0.20_34-r3.3.2_0     r
    r-lubridate:             1.6.0-r3.3.2_0       r
    r-mass:                  7.3_45-r3.3.2_0      r
    r-matrix:                1.2_7.1-r3.3.2_0     r
    r-matrixmodels:          0.4_1-r3.3.2_0       r
    r-mgcv:                  1.8_16-r3.3.2_0      r
    r-mnormt:                1.5_5-r3.3.2_0       r
    r-modelmetrics:          1.1.0-r3.3.2_0       r
    r-modelr:                0.1.0-r3.3.2_0       r
    r-nlme:                  3.1_128-r3.3.2_0     r
    r-nnet:                  7.3_12-r3.3.2_0      r
    r-openssl:               0.9.5-r3.3.2_0       r
    r-pbdzmq:                0.2_4-r3.3.2_0       r
    r-pryr:                  0.1.2-r3.3.2_0       r
    r-psych:                 1.6.9-r3.3.2_0       r
    r-purrr:                 0.2.2-r3.3.2_0       r
    r-readr:                 1.0.0-r3.3.2_0       r
    r-readxl:                0.1.1-r3.3.2_0       r
    r-recommended:           3.3.2-r3.3.2_0       r
    r-rpart:                 4.1_10-r3.3.2_0      r
    r-rprojroot:             1.1-r3.3.2_0         r
    r-rvest:                 0.3.2-r3.3.2_0       r
    r-selectr:               0.3_0-r3.3.2_0       r
    r-sourcetools:           0.1.5-r3.3.2_0       r
    r-spatial:               7.3_11-r3.3.2_0      r
    r-survival:              2.40_1-r3.3.2_0      r
    r-tibble:                1.2-r3.3.2_0         r
    r-tidyverse:             1.0.0-r3.3.2_0       r
    r-xml2:                  1.0.0-r3.3.2_0       r

The following packages will be UPDATED:

    notebook:                4.3.0-py35_0           --> 4.3.1-py35_0        
    r:                       3.1.3-0              r --> 3.3.2-r3.3.2_0     r
    r-assertthat:            0.1-0a               r --> 0.1-r3.3.2_4       r
    r-base64enc:             0.1_2-r3.1.3_0a      r --> 0.1_3-r3.3.2_0     r
    r-bh:                    1.55.0_3-0a          r --> 1.62.0_1-r3.3.2_0  r
    r-bitops:                1.0_6-0a             r --> 1.0_6-r3.3.2_2     r
    r-bradleyterry2:         1.0_6-0a             r --> 1.0_6-r3.3.2_2     r
    r-brglm:                 0.5_9-0a             r --> 0.5_9-r3.3.2_2     r
    r-car:                   2.0_24-0a            r --> 2.1_4-r3.3.2_0     r
    r-caret:                 6.0_41-0a            r --> 6.0_73-r3.3.2_0    r
    r-catools:               1.17.1-0a            r --> 1.17.1-r3.3.2_2    r
    r-chron:                 2.3_45-r3.1.3_0a     r --> 2.3_47-r3.3.2_0    r
    r-colorspace:            1.2_4-0a             r --> 1.3_1-r3.3.2_0     r
    r-data.table:            1.9.4-r3.1.3_0a      r --> 1.10.0-r3.3.2_0    r
    r-dbi:                   0.3.1-0a             r --> 0.5_1-r3.3.2_0     r
    r-dichromat:             2.0_0-0a             r --> 2.0_0-r3.3.2_2     r
    r-digest:                0.6.8-0a             r --> 0.6.10-r3.3.2_0    r
    r-dplyr:                 0.4.1-0a             r --> 0.5.0-r3.3.2_0     r
    r-essentials:            1.1-r3.1.3_0a        r --> 1.5.1-0            r
    r-evaluate:              0.7-r3.1.3_0a        r --> 0.10-r3.3.2_0      r
    r-foreach:               1.4.2-0a             r --> 1.4.3-r3.3.2_0     r
    r-formatr:               1.2-r3.1.3_0a        r --> 1.4-r3.3.2_0       r
    r-ggplot2:               1.0.0-0a             r --> 2.2.0-r3.3.2_0     r
    r-glmnet:                2.0_2-r3.1.3_0a      r --> 2.0_5-r3.3.2_0     r
    r-gtable:                0.1.2-0a             r --> 0.2.0-r3.3.2_0     r
    r-gtools:                3.4.1-0a             r --> 3.5.0-r3.3.2_0     r
    r-hexbin:                1.27.0-0a            r --> 1.27.1-r3.3.2_0    r
    r-highr:                 0.5-r3.1.3_0a        r --> 0.6-r3.3.2_0       r
    r-htmltools:             0.2.6-0a             r --> 0.3.5-r3.3.2_0     r
    r-htmlwidgets:           0.5-r3.1.3_0a        r --> 0.8-r3.3.2_0       r
    r-httpuv:                1.3.2-r3.1.3_0a      r --> 1.3.3-r3.3.2_0     r
    r-irdisplay:             0.3-r3.1.3_0a        r --> 0.4.4-r3.3.2_0     r
    r-irkernel:              0.4-r3.1.3_0a        r --> 0.7.1-r3.3.2_0     r
    r-iterators:             1.0.7-0a             r --> 1.0.8-r3.3.2_0     r
    r-jsonlite:              0.9.16-r3.1.3_0a     r --> 1.1-r3.3.2_0       r
    r-knitr:                 1.10-r3.1.3_0a       r --> 1.15.1-r3.3.2_0    r
    r-labeling:              0.3-0a               r --> 0.3-r3.3.2_2       r
    r-lazyeval:              0.1.10-0a            r --> 0.2.0-r3.3.2_0     r
    r-lme4:                  1.1_7-0a             r --> 1.1_12-r3.3.2_0    r
    r-magrittr:              1.5-0a               r --> 1.5-r3.3.2_2       r
    r-maps:                  2.3_9-0a             r --> 3.1.1-r3.3.2_0     r
    r-markdown:              0.7.7-r3.1.3_0a      r --> 0.7.7-r3.3.2_2     r
    r-mime:                  0.3-r3.1.3_0a        r --> 0.5-r3.3.2_0       r
    r-minqa:                 1.2.4-0a             r --> 1.2.4-r3.3.2_2     r
    r-munsell:               0.4.2-0a             r --> 0.4.3-r3.3.2_0     r
    r-nloptr:                1.0.4-0a             r --> 1.0.4-r3.3.2_2     r
    r-pbkrtest:              0.4_2-0a             r --> 0.4_6-r3.3.2_0     r
    r-plyr:                  1.8.1-0a             r --> 1.8.4-r3.3.2_0     r
    r-profilemodel:          0.5_9-0a             r --> 0.5_9-r3.3.2_2     r
    r-proto:                 0.3_10-0a            r --> 1.0.0-r3.3.2_0     r
    r-quantmod:              0.4_5-r3.1.3_0a      r --> 0.4_7-r3.3.2_0     r
    r-quantreg:              5.11-0a              r --> 5.29-r3.3.2_0      r
    r-r6:                    2.0.1-0a             r --> 2.2.0-r3.3.2_0     r
    r-randomforest:          4.6_10-r3.1.3_0a     r --> 4.6_12-r3.3.2_0    r
    r-rbokeh:                0.2.2-r3.1.3_0a      r --> 0.5.0-r3.3.2_0     r
    r-rcolorbrewer:          1.1_2-0a             r --> 1.1_2-r3.3.2_3     r
    r-rcpp:                  0.11.3-0a            r --> 0.12.8-r3.3.2_0    r
    r-rcppeigen:             0.3.2.3.0-0a         r --> 0.3.2.9.0-r3.3.2_0 r
    r-repr:                  0.3-r3.1.3_0a        r --> 0.10-r3.3.2_0      r
    r-reshape2:              1.4.1-0a             r --> 1.4.2-r3.3.2_0     r
    r-rjsonio:               1.3_0-0a             r --> 1.3_0-r3.3.2_2     r
    r-rmarkdown:             0.5.1-r3.1.3_0a      r --> 1.2-r3.3.2_0       r
    r-rzmq:                  0.7.7-r3.1.3_0a      r --> 0.7.7-r3.3.2_3     r
    r-scales:                0.2.4-0a             r --> 0.4.1-r3.3.2_0     r
    r-shiny:                 0.11.1-r3.1.3_0a     r --> 0.14.2-r3.3.2_0    r
    r-sparsem:               1.6-0a               r --> 1.74-r3.3.2_0      r
    r-stringi:               0.4_1-r3.1.3_0a      r --> 1.1.2-r3.3.2_0     r
    r-stringr:               0.6.2-0a             r --> 1.1.0-r3.3.2_0     r
    r-tidyr:                 0.2.0-r3.1.3_0a      r --> 0.6.0-r3.3.2_0     r
    r-ttr:                   0.23_0-r3.1.3_0a     r --> 0.23_1-r3.3.2_0    r
    r-uuid:                  0.1_1-r3.1.3_0a      r --> 0.1_2-r3.3.2_0     r
    r-xtable:                1.7_4-r3.1.3_0a      r --> 1.8_2-r3.3.2_0     r
    r-xts:                   0.9_7-r3.1.3_0a      r --> 0.9_7-r3.3.2_2     r
    r-yaml:                  2.1.13-0a            r --> 2.1.14-r3.3.2_0    r
    r-zoo:                   1.7_11-0a            r --> 1.7_13-r3.3.2_0    r

**Comment by TheMitchWorksPro** [comment]
Second attempt to install RStudio Failed.  I selected the environment first in the only place the UI allows you to select it.  Here are screenshots of what I did and what happened:

![image](https://cloud.githubusercontent.com/assets/23440318/21856533/5adb4e66-d7f0-11e6-9d9e-9a8ec9d5f93e.png)

![image](https://cloud.githubusercontent.com/assets/23440318/21856546/6506391e-d7f0-11e6-9f89-1f0256e9077d.png)

Looks like selecting an environment has no effect and the installation fails same way regardless.  Is there anything else we can try?  (sorry I about the delay in getting this test done)

**Comment by goanpeca** [comment]
@TheMitchWorksPro in your screenshot I see you installed (on the Home screen) on the root environment not on R_wPY35

<img width="256" alt="screen shot 2017-01-11 at 11 27 48 am" src="https://cloud.githubusercontent.com/assets/3627835/21856726/014f2d80-d7f1-11e6-9ff1-1ef8ba11c846.png">

**Comment by TheMitchWorksPro** [comment]
Could have sworn I tested drop-down at top of Home screen and it did not work before I switched to Environments tab to do it.  Now I see I was mistaken.  Trying again.  Results to post shortly (I hope).

**Comment by TheMitchWorksPro** [comment]
Process failed again.  Unidentified error on the pop up screen (screen is blank).  

![image](https://cloud.githubusercontent.com/assets/23440318/21857466/89483086-d7f3-11e6-91b4-9749ac727023.png)

Precise process followed this time:
1) environment used (selected on home screen) was created earlier on Anaconda Navigator with R and Python 3.5 checked during its creation.  List of what it contains is in an earlier comment exported using command "conda list" for the environment.

2) clicked button again

This time it appeared to get much farther with the install.  It downloaded and installed packages but errored out at the point shown in the screen shot.

Anything else we can try?

**Comment by goanpeca** [comment]
Please hold on for a couple of days, there is a release coming that takes care of this, sorry for the trouble

**Comment by TheMitchWorksPro** [comment]
In case this helps with debugging - here is a list of what the environment looked like after it died:

[R_wPY35_condaList_2017-01-11_12pm.txt](https://github.com/ContinuumIO/anaconda-issues/files/699477/R_wPY35_condaList_2017-01-11_12pm.txt)

To take advantage of new release - will I have to blow away Anaconda 4.2 and start over with 4.3?
Or is there a way to update this environment after the new release without having to start over?

Please advise.  Thanks.

**Comment by mingwandroid** [comment]
Those R packages are very old. I am not sure what would cause such old versions to be installed.

**Comment by TheMitchWorksPro** [comment]
Based @goanpeca 's comments, I am holding off on attempting to complete RStudio installation for now, but I had to know.  So in case this helps with your research, this file is the output of running "conda update --all" on the environment followed by "conda list" to show what it looks like after running the command.

[R_wPY35_update-all-output_2017-01-11-12-24.txt](https://github.com/ContinuumIO/anaconda-issues/files/699548/R_wPY35_update-all-output_2017-01-11-12-24.txt)

**Comment by TheMitchWorksPro** [comment]
Please keep this issue open and use it to let me know when I should try again.  Also, please advise on earlier comment:  is there way to update 4.2?  Or would trying the new release require blowing it away and re-installing and configuring?  I will need to know my options when I attempt the next fix.

Thanks.

**Comment by goanpeca** [comment]
@TheMitchWorksPro, you will be able to install the new anaconda without "blowing up" everything. I will keep you updated

**Comment by TheMitchWorksPro** [comment]
sounds great.  Able to use my R env. to run code in Jupyter and study ahead of my upcoming class.  Hoping to install RStudio before the 23rd as I think they will want us to work in it when I get to my R class, so being able to pick up where I left off during the upgrade would save me oodles of time.

Anaconda is an amazing tool.  

Just struggling with some of the issues on my machine.  Kept a file that was supposed to be help for me (and possibly others) as to what to do for the myriad of things that went wrong when I tried to rebuild my environment using 4.2 recently.  Thinking of posting that like a "unit test" issue so you guys can evaluate it and see if it brings to light things that might still need fixing in the next release.

Really appreciate your diligence and devotion to building a better mouse trap.
Cheers!

**Comment by goanpeca** [comment]
@TheMitchWorksPro we could really use your experience to improve our internal testing :-)

**Comment by TheMitchWorksPro** [comment]
Hope this isn't too overwhelming as it is long ... but here's the "unit test" documentation I alluded to.  Hope it helps with all of your efforts:

https://github.com/ContinuumIO/anaconda-issues/issues/1352

**Comment by TheMitchWorksPro** [comment]
@goanpeca My R class begins on Monday, January the 23rd.  I know you must be very busy.  Please just let me know if Anaconda 4.3 will be ready for me to try upgrading and then triggering RStudio installation by then, or if I need to download and install RStudio independantly to get ready for it.  I need my full environment working day 1 when I walk into class so your time-table will drive what solution I explore for now.

Thanks,
Mitch

**Comment by TheMitchWorksPro** [comment]
These comments left here that further correct update what is reported in this issue. Advice is being sought concerning next steps based on the way the installation of RStudio went (please see these comments):

https://github.com/ContinuumIO/anaconda-issues/issues/1352#issuecomment-274831510
https://github.com/ContinuumIO/anaconda-issues/issues/1352#issuecomment-274891464

**Comment by mingwandroid** [comment]
The upcoming 4.3 release will make using RStudio with Anaconda Navigator work properly, or at least we are working hard to make sure of that. In the meantime, this is recommended approach for using R and RStudio on Anaconda on Windows at present.

I think your system probably has artefacts from previous attempts at this, so uninstall all `Anaconda/Miniconda` using the `Control Panel`, then make sure that your System `PATH` environment variable does not contain any `Anaconda/Miniconda` entries (`This PC=>Properties=>Advanced system settings=>Environment Variables`).

1. Download https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe.
2. Install it to `C:\Users\Mitch\Anaconda3` (untick `Add Anaconda to my PATH...`, we should not let Anaconda contribute to DLL-hell).
3. From the `Start Menu` launch the `Anaconda Prompt`.
4. In the console enter `conda install -c r rstudio`.
5. In the console enter `rstudio`.

Subsequently when you just want to run `RStudio`, start at step 4.

It seems you want Python 2 in as your default Python (each to their own, I personally avoid Python 2 which I can). Unfortunately you cannot use RStudio in an environment with Python 2 on Windows (other OSes don't suffer this limitation) so if you want to use Python 2 in your root environment and RStudio and Python3 in another environment then please follow these instructions instead:

1. Download https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86_64.exe
2. Install it to `C:\Users\Mitch\Anaconda2` (untick `Add Anaconda to my PATH...` => DLL-hell again)
3. From the `Start Menu` launch the `Anaconda Prompt`.
4. In the console enter `conda create -n rstudio_python35 -c r rstudio python=3.5`.
5. In the console enter `activate rstudio_python35`.
6. In the console enter `rstudio`.

Subsequently when you just want to run rstudio, start at step 5.

If you follow these steps precisely and it doesn't work then please share what goes wrong.

Good luck.

**Comment by TheMitchWorksPro** [comment]
Just saw this.  Personally, I wanted to use the latest Python, but not all libraries have been migrated and I am taking a class that requires Python 2.7 for both Jupyter and Spyder.  Since Spyder from an Anaconda distribution only appears to launch on the root environment, I was forced to choose PY27 for root, and add environments for when I want to work in 3.x.

I have a mostly working environment.  The only quirk is what happened to RStudio. Though I hope to upgrade to 4.3 when ready (and help you with testing efforts there as we given my detailed use case, I need a quick fix for now to keep up with my studies.  I am going to try killing RStudio with deinstallation, and re-install outside of Anaconda for now.  If that doesn't work, then I will need to attempt what you suggested which I hoped to avoid.  I wanted a full version, not mini, and I did so much work to get my current Anaconda setup to the state it is in now that I could lose days or even a week trying to re-build it after flowing it away.

Thanks for this write-up thought.  It will serve as my "emergency - can't get it working solution" if my hopefully faster approach does not work.  Anaconda (except RStudio) seems to work fine.  State of RStudio and more symptoms uncovered leading to this approach are posted on the other "4.2 unit test thread" (see my previous comment with links to them) if this helps your reserach.  I posted there before reading your write-up.

Thanks again.
Best wishes and good luck with 4.3 roll out.

**Comment by TheMitchWorksPro** [comment]
situation worse than I thought.  RStudio does not appear in my control panel as a program I can de-install.  I assume this is because it was bundled in Anaconda same way Spyder is and blowing away whole of Anaconda is now the only way to cleanly get rid of it.  Looks like I will need to initiate the emergency protocol of blowing it all away and starting fresh.

**Comment by mingwandroid** [comment]
To remove RStudio you should:

1. Launch `Anaconda Prompt` from the `Start Menu`
2. Type `conda remove rstudio`

Conda does not put the packages it manages in the Windows Control Panel, as if it were to do that, you would see potentially hundreds and hundreds of them.

**Comment by TheMitchWorksPro** [comment]
Thanks! will try that

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by TheMitchWorksPro** [comment]
if I do "conda update conda" followed by "conda update anaconda" - will
this update the whole of the Anaconda tools?
do you recommend this approach or is it safer to just do "conda update
anaconda-navigator"

I have an elaborate working environment and am looking to avoid de-install
/ re-install to reap the benefits of this upgrade if possible.  Please
advise, and I can take the next step and see how this all works.

Thanks.

**Comment by goanpeca** [comment]
@TheMitchWorksPro I recommend you download the latest anaconda distribution and start from scratch.

**Comment by TheMitchWorksPro** [comment]
Thanks for the speedy response.  My classes are now in full swing, so since
my environment works, stopping to de-install and rebuild is not an option
until I graduate from them in July.

Hope to follow your instructions and try again then with whatever release
is current at that time.
Best wishes
