### ISSUE TITLE
Saving the Software Directory in "C:\Program Files"

### ISSUE THREAD

**Issue by Flrebolt** [ContinuumIO/anaconda-issues#13385]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [X] Miniconda
- [ ] Anaconda.org

### What happened?

I had a project for my company, where i had to create a Software Package via a Software Distribution Program, for usage inside the company. In order to have a good Installation and Uninstallation Path, which is working on every Windows Machine, i wanted to put the Miniforge3 folder into the "Program Files" Directory, this didn´t work because of the space. I´ve found a workaround and was able to finish my project, still i was wondering, cause this directory would be the perfect place to save the Software Directory, if or why you guys can´t solve the problem, so that people can save the Miniforge3 folder inside of the "Program Files" directory. I think it would be a sensible addition to the program.

Greetings,
Stephan

### Expected behavior or outcome

The possibility to save the Software Directory (Miniforge3) into "C:\Program Files".

**Comment by marcoesters** [comment]
The Miniforge installers are maintained by conda-forge, not Anaconda. Anaconda's installers are [Miniconda](https://docs.anaconda.com/free/miniconda/) and [Anaconda Distribution](https://docs.anaconda.com/free/anaconda/).

Please file the issue at the Miniforge repository: https://github.com/conda-forge/miniforge/

Thank you!
