### ISSUE TITLE
What are best practices to build packages compatible with Anaconda?

### ISSUE THREAD

**Issue by dmitry-kabanov** [ContinuumIO/anaconda-issues#1339]
Are there any best practices to build packages such that they are compatible with Anaconda?

I want to build [sundials](http://computation.llnl.gov/projects/sundials) and [scikits.odes](https://github.com/bmcage/odes) at least for linux-64 architecture and osx-64.
Documentation for building packages with conda doesn't say anything about the versions of compilers that must be used to get packages that are compatible with Anaconda.

**Comment by csoja** [comment]
I'd recommend this README: https://github.com/ContinuumIO/anaconda-recipes/blob/master/README.md

**Comment by dmitry-kabanov** [comment]
@csoja, thanks!

Since I wrote my previous message, I've realized that I cannot build `sundials` with MKL support although Anaconda is supplied with MKL.
It seems like it's easier to switch to what `condo-forge` provides since they already have `sundials` built against `openblas`.
