### ISSUE TITLE
name conflict with macos codesign

### ISSUE THREAD

**Issue by Anton-4** [ContinuumIO/anaconda-issues#13414]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

anaconda3/bin contains codesign, during installation, this folder is prepended to the PATH. The widely used macOS xcode command line tools also have an application called codesign. Because anaconda puts its folder first in the PATH, this means that anaconda's codesign will be used any time a user or program calls codesign, while they probably intended to use the xcode codesign.

Given that anaconda puts itself first in the PATH, it should avoid unintentionally having their programs  take precedence over popular programs.

### Expected behavior or outcome

codesign in a macOS terminal should not use anaconda's codesign. Given my limited context, renaming anaconda's codesign seems like a possible solution.

**Comment by marcoesters** [comment]
Which installer are you using? I just downloaded [2024.06-1 for Apple Silicon](https://repo.anaconda.com/archive/Anaconda3-2024.06-1-MacOSX-arm64.sh) and I do not see `codesign` in the installation directory (I only see `codesign_allocate`).

**Comment by bsassoli** [comment]
Hi, I am the one who originally found the bug. TBH I am not sure what I used.

**Comment by Anton-4** [comment]
Perhaps you can search your history to figure it out; `cat ~/.zsh_history | grep conda`

**Comment by bsassoli** [comment]
Tried but I get hundreds off results and the first ones don't seem related :-(

**Comment by Anton-4** [comment]
Based on @marcoesters comment, it looks like codesign was already renamed, the issue can always be re-opened if this does not turn out to be true.

**Comment by marcoesters** [comment]
`codesign_allocate` is actually a different binary (I have both `codesign` and `codesign_allocate` in `/usr/bin` on my Mac). It should probably not be the Anaconda path either, but I will forward this to our package building team.
