### ISSUE TITLE
Navigator for 4.2 not opening (bis)

### ISSUE THREAD

**Issue by LaurentThiol** [ContinuumIO/anaconda-issues#1342]
Hi
I'm not able to launch "anaconda navigator" under windows10 any more.
It used to work then for an unknown reason, now you can click on the shortcut nothing happen :
shortcut :
"C:\Program Files\Anaconda3\envs\py35\pythonw.exe" "C:\Program Files\Anaconda3\envs\py35\cwp.py" "C:\Program Files\Anaconda3\envs\py35" "C:/Program Files/Anaconda3/envs/py35/pythonw.exe" "C:/Program Files/Anaconda3/envs/py35/Scripts/anaconda-navigator-script.

The strange is that I first install Py 35 64 bits before the 27, but the shortcut is py 27!

I made manually a launcher for 35 : same result nothing happens...

I checked the version : anaconda-navigator        1.3.2                    py35_0

Do you have an idea, in order to restore the launcher?
Thanks per advance.

**Comment by goanpeca** [comment]
Hi @LaurentThiol could you go to the command prompt and type

`$ anaconda-navigator`

Also could you type

```
$ conda info
$ conda list
```

And paste the results here?

**Comment by ccordoba12** [comment]
The space in

    Program Files

could be the cause.

**Comment by goanpeca** [comment]
Good catch @ccordoba12 indeed

**Comment by goanpeca** [comment]
@LaurentThiol you seem to have a "All users install" of anaconda.

Is there any reason for not using "This user only install" ?

**Comment by ccordoba12** [comment]
Installation in directories with spaces is going to be prevented in Anaconda 4.3

**Comment by LaurentThiol** [comment]
@goanpeca 
Whaou ! anaconda-navigator did great !

I can change to "This user only install" if necessary, Do I have to uninstall first ?

**Comment by goanpeca** [comment]
Yes it is better

**Comment by LaurentThiol** [comment]
@ccordoba12 
As I'm under windows the space is native...
I did not change the standard install dir...

**Comment by ccordoba12** [comment]
Yep, I know. But you have to choose another location, even for a system-wide installation.

**Comment by LaurentThiol** [comment]
ok thanks to all
