### ISSUE TITLE
Add support for shapely for Windows

### ISSUE THREAD

**Issue by mwtoews** [ContinuumIO/anaconda-issues#1345]
Currently, shapely is supported for only Linux and macOS, but not Windows:
https://anaconda.org/anaconda/shapely

Looking at the file history, it seems that shapely has never been supported for Windows on Anaconda.

While there are several 3rd party channels that support shapely on Windows, it would be most convenient to have this from the core anaconda channel.

Note that this recipe depends on libgeos, which is also used for gdal (which has good cross platform support on anaconda).

**Comment by jorisvandenbossche** [comment]
Shapely is supported for Windows nowadays(https://anaconda.org/anaconda/shapely), so this issue can be closed I think
