### ISSUE TITLE
Navigator fails to install a package that triggers a Navigator update

### ISSUE THREAD

**Issue by coolum001** [ContinuumIO/anaconda-issues#1348]
Running Anaconda Navigator 1.3.2, windows/Anaconda env. as  detailed below
Tried to install the package 'opencv' from the Navigator:
It appears that this (at some stage) triggers an update of Navigator itself, and hence the Navigator application crashes in mid-install (presumably after removing Navigator binaries).  The Navigator icon no longer appears in the Start menu.

Reinstalled Anaconda (Windows 10, 64 bit), and installed opencv by command line  in its own environment, and all OK.

Suggest either (a) Navigator should  refuse to install packages that trigger a Navigator update, or (b) opencv should be removed from list of available packages that can be installed from Navigator

Running Windows 10, Anaconda  as below
(D:\Anaconda3) C:\Users\donrc>conda info
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : D:\Anaconda3  (writable)
    default environment : D:\Anaconda3
       envs directories : D:\Anaconda3\envs
          package cache : D:\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\donrc\.condarc
           offline mode : False

Status after command line install of opencv into separate environment

(D:\Anaconda3) C:\Users\donrc>activate compvision

```
(compvision) C:\Users\donrc>conda list
# packages in environment at D:\Anaconda3\envs\compvision:
#
backports.shutil_get_terminal_size 1.0.0                    py35_0    conda-forge
ca-certificates           2016.9.26                     0    conda-forge
certifi                   2016.9.26                py35_0    conda-forge
colorama                  0.3.7                    py35_0    conda-forge
decorator                 4.0.10                   py35_0    conda-forge
entrypoints               0.2.2                    py35_0    conda-forge
ipykernel                 4.5.2                    py35_0    conda-forge
ipython                   5.1.0                    py35_1    conda-forge
ipython_genutils          0.1.0                    py35_0    conda-forge
ipywidgets                5.2.2                    py35_2    conda-forge
jinja2                    2.8                      py35_1    conda-forge
jpeg                      9b                       vc14_0  [vc14]  conda-forge
jsonschema                2.5.1                    py35_0    conda-forge
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0    conda-forge
jupyter_console           5.0.0                    py35_0    conda-forge
jupyter_core              4.2.1                    py35_0    conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.26                   vc14_0  [vc14]  conda-forge
libtiff                   4.0.6                    vc14_7  [vc14]  conda-forge
libxml2                   2.9.3                    vc14_9  [vc14]  conda-forge
markupsafe                0.23                     py35_1    conda-forge
mistune                   0.7.3                    py35_0    conda-forge
mkl                       11.3.3                        1
nbconvert                 4.2.0                    py35_0    conda-forge
nbformat                  4.2.0                    py35_0    conda-forge
notebook                  4.3.1                    py35_0    conda-forge
numpy                     1.11.2                   py35_0
opencv3                   3.1.0                    py35_0    menpo
openssl                   1.0.2h                   vc14_3  [vc14]  conda-forge
pickleshare               0.7.3                    py35_0    conda-forge
pip                       9.0.1                    py35_0    conda-forge
prompt_toolkit            1.0.9                    py35_0    conda-forge
pygments                  2.1.3                    py35_1    conda-forge
pyqt                      4.11.4                   py35_2    conda-forge
python                    3.5.2                         3    conda-forge
pyzmq                     16.0.2                   py35_0    conda-forge
qt                        4.8.7                    vc14_6  [vc14]  conda-forge
qtconsole                 4.2.1                    py35_1    conda-forge
setuptools                32.3.0                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.10.0                   py35_1    conda-forge
tornado                   4.4.2                    py35_0    conda-forge
traitlets                 4.3.1                    py35_0    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wheel                     0.29.0                   py35_0    conda-forge
widgetsnbextension        1.2.6                    py35_3    conda-forge
win_unicode_console       0.5                      py35_0    conda-forge
wincertstore              0.2                      py35_0    conda-forge
zlib                      1.2.8                    vc14_3  [vc14]  conda-forge
```

**Comment by goanpeca** [comment]
>It appears that this (at some stage) triggers an update of Navigator itself, and hence the Navigator application crashes in mid-install (presumably after removing Navigator binaries). The Navigator icon no longer appears in the Start menu.

Is this an assumption or you are sure this actually happened (I dont see how it could?, also opencv has as dependencies numpy and python only)

**Comment by coolum001** [comment]
This is an assumption of mine.  I will try and see if I can recreate the problem in a clean system (as I may have been installing other packages at the same time with command line conda).  The behaviour seems to be similar to issue "After updating Anaconda 3 via Anaconda Navigator the Navigator disappears #1280 ".

Close if you wish, and I will resubmit when I have reproducible issue.

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
1.6 to be release in a week will definitely fix this
