### ISSUE TITLE
Python 3.6 segfaulting on OSX 10.7

### ISSUE THREAD

**Issue by olaurino** [ContinuumIO/anaconda-issues#1349]
As OSX 10.7 is advertised as the baseline platform for Anaconda, I build my packages on this platform, to ensure binary compatibility.

However, as I started building packages against Python 3.6, I realized this package is not working on OSX 10.7.

Is this not the baseline platform for anaconda packages anymore?

More in detail, I create a new environment as follows, in a OSX 10.7 vagrant box (tuupola/osx-lion-10.7-xcode in case you are wondering):

````
conda create -n test python=3.6
source activate test
````

Then, given any Python package with a `setup.py` (I tried with [sherpa](https://github.com/sherpa/sherpa) and [astropy](https://github.com/astropy/astropy)), I get:

````
(test) osx-10_7:astropy-1.3 vagrant$ python setup.py help
Illegal instruction: 4
````

In other instances, i.e. running `conda-build` I get a segmentation fault, but the pattern is clear.

Some info:

````
(py36) osx-10_7:~ vagrant$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.7.5
BuildVersion:   11G63


(py36) osx-10_7:~ vagrant$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/vagrant/miniconda2  (writable)
    default environment : /Users/vagrant/miniconda2/envs/py36
       envs directories : /Users/vagrant/miniconda2/envs
          package cache : /Users/vagrant/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
````

Please let me know if you need any more info.

Thanks!

**Comment by csoja** [comment]
We are moving to 10.9 as the baseline going forward.   We will be updating the documentation soon to reflect that.  Thanks for reporting the issue - sorry for the trouble.

**Comment by olaurino** [comment]
BTW, is your Linux baseline still CentOS 5 or are you migrating to a different platform as well?

**Comment by msarahan** [comment]
Centos 5 is what we strive for, but it is not always possible. There are
some newer packages, such as tensorflow that use centos 6 instead.

**Comment by olaurino** [comment]
Thanks a lot for the info!
