### ISSUE TITLE
Anaconda 4.2 - Unit Test - Issues encountered (some w/ work-arounds, some not) for your research

### ISSUE THREAD

**Issue by TheMitchWorksPro** [ContinuumIO/anaconda-issues#1352]
Updates:  slides updated.  Title page explains what's new this version.

Sorry that this is badly organized and doesn't have a clean summary in it but I am short on time.  Posted other issues (a few of them) one by one while working on them.  This attached file is an amalgam of all the things that went wrong with my Anaconda 4.2 environment, work-arounds where known, and what was attempted when a workaround is not known.  Recommendations for Anaconda team about what to do are in bold red on some slides.  Others should be evaluated anyway in case this helps you shake out the kinks in upcoming releases.

Original intent:  I thought I was documenting how to fix it all when I started.  Then I hit the wall on RStudio.  In the powerpoints, a section divider marks earlier issues from earlier build before I blew away my environment and started fresh.  Slides up front were all the things that happened in the fresh installation (and environments) despite all that was learned along the way to get there.  My environment works despite its quirks, it just does not have RStudio yet as per another open issue.

Hope this helps with your testing effort. Keep this open or closed as you need to in order to evaluate it and use it for your development efforts.

Thanks and here's hoping this helps with your efforts to build a better Anaconda.

[Anaconda 42 - PY27 Installation Erros and Notes - Install3 - v2c.pptx](https://github.com/ContinuumIO/anaconda-issues/files/714616/Anaconda.42.-.PY27.Installation.Erros.and.Notes.-.Install3.-.v2c.pptx)

**Comment by TheMitchWorksPro** [comment]
With more testing, had to add a few slides and update a few more.  Change made in main comment.  Just replaced the powerpoints with updated copy.

**Comment by TheMitchWorksPro** [comment]
One more not in the slides: 

 In "R in a Nutshell" (good resource for novices like me), they point you to a dataset called "cars" and indicate that with RStudio, this comes with a default installation.  But as shown in this image, looks like that package is not working right in my R environment (the one I set up as per other issue hoping to use it for RStudio install once you get the kinks ironed out there).

My tests would seem to indicate that cars is there.  I can output it -- but I can't access its components (speed I think) using code I literally copied and pasted from R in a Nutshell.   Not sure if this means a package is missing or something is not working right or what?  What is in my environment is also provide with this comment.  scroll down to the R_wPY35 environment list to view it.

![image](https://cloud.githubusercontent.com/assets/23440318/21935030/cd8bce42-d979-11e6-9002-eaa6242aa906.png)

more tests in same Notebook:

![image](https://cloud.githubusercontent.com/assets/23440318/21935060/ed97c998-d979-11e6-96e2-5d18f071c754.png)

List of this environment -- How created:
* used Anaconda Navigator (4.2) to build the environment with R and Python 3.5 checked
* tried RStudio button but it failed as indicated in slides (several times)
* ran "conda update --all" after dry-run did not show any errors but that much would be added / updated

List is here.  Results of dry run were posted on other thread about RStudio failing to install:
Other thread with outputs of update dry run:  
https://github.com/ContinuumIO/anaconda-issues/issues/1337

Conda list of the environment as it is right now:


(R_wPY35) C:\Users\Mitch>conda list
# packages in environment at C:\ProgramFilesCoders\Anaconda2\envs\R_wPY35:
#
colorama                  0.3.7                    py35_0
decorator                 4.0.10                   py35_1
entrypoints               0.2.2                    py35_0
icu                       57.1                     vc14_0  [vc14]
ipykernel                 4.5.2                    py35_0
ipython                   5.1.0                    py35_0
ipython-notebook          4.0.4                    py35_3
ipython_genutils          0.1.0                    py35_0
jinja2                    2.8.1                    py35_0
jpeg                      8d                       vc14_2  [vc14]
jsonschema                2.5.1                    py35_0
jupyter_client            4.4.0                    py35_0
jupyter_core              4.2.1                    py35_0
libpng                    1.6.27                   vc14_0  [vc14]
m2-bash                   4.3.042                       5
m2-gcc-libs               5.3.0                         4
m2-heimdal                1.5.3                        10
m2-heimdal-libs           1.5.3                        10
m2-icu                    56.1                          2
m2-libcrypt               1.3                           2
m2-libdb                  5.3.28                        3
m2-libedit                3.1                    20150326
m2-libopenssl             1.0.2.g                       2
m2-libreadline            6.3.008                       8
m2-libsqlite              3.10.0.0                      2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-ncurses                6.0.20160220                  2
m2-openssh                7.1p2                         2
m2-openssl                1.0.2.g                       2
m2-zlib                   1.2.8                         4
m2w64-bzip2               1.0.6                         6
m2w64-diffutils           3.3.2                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-grep                2.24                          2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-pcre                8.38                          2
m2w64-wineditline         2.101                         5
m2w64-zlib                1.2.8                        10
markupsafe                0.23                     py35_2
mistune                   0.7.3                    py35_0
msys2-conda-epoch         20160418                      1
nbconvert                 4.2.0                    py35_0
nbformat                  4.2.0                    py35_0
notebook                  4.3.0                    py35_0
openssl                   1.0.2j                   vc14_0  [vc14]
path.py                   9.0.1                    py35_0
pickleshare               0.7.4                    py35_0
pip                       9.0.1                    py35_1
prompt_toolkit            1.0.9                    py35_0
pygments                  2.1.3                    py35_0
python                    3.5.2                         0
pyzmq                     16.0.2                   py35_0
qt                        5.6.2                    vc14_0  [vc14]
r                         3.1.3                         0    r
r-assertthat              0.1                          0a    r
r-base64enc               0.1_2                 r3.1.3_0a    r
r-bh                      1.55.0_3                     0a    r
r-bitops                  1.0_6                        0a    r
r-bradleyterry2           1.0_6                        0a    r
r-brglm                   0.5_9                        0a    r
r-car                     2.0_24                       0a    r
r-caret                   6.0_41                       0a    r
r-catools                 1.17.1                       0a    r
r-chron                   2.3_45                r3.1.3_0a    r
r-colorspace              1.2_4                        0a    r
r-data.table              1.9.4                 r3.1.3_0a    r
r-dbi                     0.3.1                        0a    r
r-dichromat               2.0_0                        0a    r
r-digest                  0.6.8                        0a    r
r-dplyr                   0.4.1                        0a    r
r-essentials              1.1                   r3.1.3_0a    r
r-evaluate                0.7                   r3.1.3_0a    r
r-foreach                 1.4.2                        0a    r
r-formatr                 1.2                   r3.1.3_0a    r
r-ggplot2                 1.0.0                        0a    r
r-glmnet                  2.0_2                 r3.1.3_0a    r
r-gtable                  0.1.2                        0a    r
r-gtools                  3.4.1                        0a    r
r-hexbin                  1.27.0                       0a    r
r-highr                   0.5                   r3.1.3_0a    r
r-htmltools               0.2.6                        0a    r
r-htmlwidgets             0.5                   r3.1.3_0a    r
r-httpuv                  1.3.2                 r3.1.3_0a    r
r-irdisplay               0.3                   r3.1.3_0a    r
r-irkernel                0.4                   r3.1.3_0a    r
r-iterators               1.0.7                        0a    r
r-jsonlite                0.9.16                r3.1.3_0a    r
r-knitr                   1.10                  r3.1.3_0a    r
r-labeling                0.3                          0a    r
r-lazyeval                0.1.10                       0a    r
r-lme4                    1.1_7                        0a    r
r-magrittr                1.5                          0a    r
r-maps                    2.3_9                        0a    r
r-markdown                0.7.7                 r3.1.3_0a    r
r-mime                    0.3                   r3.1.3_0a    r
r-minqa                   1.2.4                        0a    r
r-munsell                 0.4.2                        0a    r
r-nloptr                  1.0.4                        0a    r
r-pbkrtest                0.4_2                        0a    r
r-plyr                    1.8.1                        0a    r
r-profilemodel            0.5_9                        0a    r
r-proto                   0.3_10                       0a    r
r-quantmod                0.4_5                 r3.1.3_0a    r
r-quantreg                5.11                         0a    r
r-r6                      2.0.1                        0a    r
r-randomforest            4.6_10                r3.1.3_0a    r
r-rbokeh                  0.2.2                 r3.1.3_0a    r
r-rcolorbrewer            1.1_2                        0a    r
r-rcpp                    0.11.3                       0a    r
r-rcppeigen               0.3.2.3.0                    0a    r
r-repr                    0.3                   r3.1.3_0a    r
r-reshape2                1.4.1                        0a    r
r-rjsonio                 1.3_0                        0a    r
r-rmarkdown               0.5.1                 r3.1.3_0a    r
r-rzmq                    0.7.7                 r3.1.3_0a    r
r-scales                  0.2.4                        0a    r
r-shiny                   0.11.1                r3.1.3_0a    r
r-sparsem                 1.6                          0a    r
r-stringi                 0.4_1                 r3.1.3_0a    r
r-stringr                 0.6.2                        0a    r
r-tidyr                   0.2.0                 r3.1.3_0a    r
r-ttr                     0.23_0                r3.1.3_0a    r
r-uuid                    0.1_1                 r3.1.3_0a    r
r-xtable                  1.7_4                 r3.1.3_0a    r
r-xts                     0.9_7                 r3.1.3_0a    r
r-yaml                    2.1.13                       0a    r
r-zoo                     1.7_11                       0a    r
rstudio                   1.0.44                   vc14_1  [vc14]  r
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
six                       1.10.0                   py35_0
tornado                   4.4.2                    py35_0
traitlets                 4.3.1                    py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
wheel                     0.29.0                   py35_0
win_unicode_console       0.5                      py35_0
zlib                      1.2.8                    vc14_3  [vc14]

(R_wPY35) C:\Users\Mitch>

**Comment by TheMitchWorksPro** [comment]
More information to help your research:  When Anaconda Navigator failed to install RStudio as shown in the slides, it did something I did not realize.  RStudio icon is on my machine and when I click it, I get a prompt as if it is ready to go, it just does not know how to find a usable R installation to hook to (popup tells me to select my R installation).  I waited as long as I could, but now I am out of time.  As an experiment, I will try installing R from Cran in a separate path and see if I can point RStudio to it.  If that fails, I will then de-install it and attempt re-installation.  Results of this experiment will be added to this thread in case they help.  Please do let me know when Anaconda 4.3 is ready and how to attempt upgrade of Anaconda and my Python/R Notebook environments.  I can still attempt that for you post-release and if I encounter anything strange, report it back to help the effort (though I am hoping that upgrade will go cleanly).

Thanks,
Mitch

**Comment by TheMitchWorksPro** [comment]
@goanpeca - Please advise on this one.

Started the tests indicated above.  Here is what happened and I could use a little advice to determine what I should do next? ...

As per comment above, I installed the R language to a new directory off the Cran site.  Then when I launched my RStudio icon (the one that got installed by navigator before it appeared to error out), this time, it loaded without even asking where to point the application in terms of R. The icon (for RStudio when Navigator build it) got created with the name of my R/Python environment appended to it.  Properties on the icon has this path:

C:\ProgramFilesCoders\Anaconda2\pythonw.exe C:\ProgramFilesCoders\Anaconda2\cwp.py C:\ProgramFilesCoders\Anaconda2\envs\R_wPY35 C:\ProgramFilesCoders\Anaconda2\envs\R_wPY35\Library\bin\rstudio.exe  

Further testing is required to determine if this works or if I have to blow it away and start again as indicated above, but it seems to be working at least for the moment.  The console in R-studio reports that it is using R version 3.3.2.  If I load a notebook in Jupyter using my R_wPY35 environment and go to the about menu, it reports this version of R:  R version 3.1.3 (2015-03-09)

This would lead me to believe that while RStudio is running off a path that installed under Anaconda and it seems to trigger with some kind of Anaconda settings, it is actually using my separate R installation to run.

I am a little uncertain if this is a safe way to use it or not in terms of issues that might arise when adding and updating packages.  Planning to start using it for class to night and if no issues, keep it as is for now.  If issues arise, then I may need to blow it away and start again.  

Any thoughts on this?
Any more info I should provide to help you comment?

**Comment by TheMitchWorksPro** [comment]
Looks like I get my own answer the hard way.  Went to class and an experienced guy looked at my installation and said it was fine.  Then tried to use it got weird buggy symptoms.  Will blow it away and re-install today clean (outside Anaconda) to get it working.  Will be happy to retest on Anaconda 4.3 at a later date after it comes out as having all the tools integrated through your system is a good goal despite what went wrong with 4.2.  Symptoms:  the system is unable to recognize R files as R and not text files (this has to be set for every file loaded or created within this RStudio installation.  Worse - file loads with the code invisible and the only way I found to clear it was weird:  copy and past the code of existing R file into a fresh new document created in RStudio and re-save it.  Then, upon reloading file, problem recurs requiring these steps every time I want to work with file.  Then when code was run in class, it through warnings on my machine that it did not throw on machines with a clean installation of RStudio (not done through Anaconda).  Good luck with your research.  Looking forward to trying 4.3 when its ready, but take your time.  Better to get it right than have me build another set of powerpoints. on the next one   :-)

**Comment by TheMitchWorksPro** [comment]
Something to consider for your future release:  Inability to de-install RStudio independantly if something goes wrong means a user is saddled with lots of work rebuilding all of Anaconda (which may include multiple R/Python environments, Spyder, and other stuff I don't know because I haven't tried it yet).

If not 4.3, then some future release should consider installing tools in such a way that users can de-install them independanty in case of of trouble with just one tool.  I am about to lose time I can't aford now that my classes have already started blowing away Anaconda and starting over because of issues with the RStudio installation I thought I got working from my earlier attempts.

**Comment by TheMitchWorksPro** [comment]
Re-writing last recommendation based on new information:  command prompt can be used with command "conda remove RStudio" to get rid of RStudio.  I assume same is true for Spyder.  a nice to have in future release would be ability to add/remove packages from within the Navigator Environment tab, ability to view their versions there (like you can on "conda" tab of Jupyter UI) and applications like Spyder / RStudio should have some kind of separate "remove me" UI.  Just as home shows all applications you can use Navigator to add .. once added, they should get icons or other GUI elements on a "Remove Applications" tab.  But this is just "make it cleaner it nicer get it all in one place .." -- other things documented in the powerpoints are greater importance as they reflect what actually went wrong.  Thanks for working on this.

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
