### ISSUE TITLE
Installing from Miniconda3-3.5.5-Linux-x86_64.sh results in Python 3.4.5 being installed

### ISSUE THREAD

**Issue by edminer** [ContinuumIO/anaconda-issues#1353]
FYI.  I downloaded Miniconda3-3.5.5-Linux-x86_64.sh from  http://repo.continuum.io/miniconda/index.html.  
Executing that install resulted in this version of Python being installed instead of 3.5.5:
python -V
Python 3.**4.**5 :: Continuum Analytics, Inc.

**Comment by csoja** [comment]
The version number in the miniconda installer name is for conda - not python.  This one https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh should install Python 3.5.
