### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by BLOODP** [ContinuumIO/anaconda-issues#1358]
The following errors occured:

None:
CondaHTTPError: HTTP None None for url <None>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
SSLError(SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')",),),)

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.3.0;Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Hi @BLOODP it seems to be a temporal connectivity issue

**Comment by BLOODP** [comment]
but how to solve it

**Comment by cherryz** [comment]
Did you solve it？
