### ISSUE TITLE
-bash: conda: command not found

### ISSUE THREAD

**Issue by Phoestia** [ContinuumIO/anaconda-issues#1361]
-bash: conda: command not found shows up at my terminal when I try to update anaconda.

Anaconda is still able to be use, but can not call from terminal and not able to be updated...

Can anyone help please?

**Comment by gordeli** [comment]
Short story: I have the same problem.

Full story:
OS: macOS Sierra
I have installed Anaconda 4.2.0 Python 3.5 version from the graphical installer on Friday. Everything was working fine until I tried to update all packages with the command "conda update --all". Then the anaconda-navigator stopped launching by starting the app (I could still launch it from Terminal though).
Trying to fix this made the problem worse so I have decided to wipe out anaconda clean and install it again. To uninstall I think I run the following commands:
"anaconda-clean --yes"
"rm -rf ~/anaconda"     %this one had no effect, so I have deleted the anaconda folder manually

Then I have reinstalled Anaconda in the same way as in the beginning. However now running any commands in Terminal gives:
-bash: conda: command not found

**Comment by avyukt** [comment]
What worked for me was to use the following command. 
source $HOME/anaconda/bin/activate

https://conda.io/docs/user-guide/install/macos.html#install-macos-silent

**Comment by joobei** [comment]
I am still having this issue on MacOS 10.14.6 after installing with the command line anaconda installer. After I open a new terminal window I get "-bash: conda: command not found". Despite that message base environment is activated and any subsequent conda commands work fine. It's just the error message is annoying :)
