### ISSUE TITLE
Update installer images to new background

### ISSUE THREAD

**Issue by VictoriaODell** [ContinuumIO/anaconda-issues#1362]
Hey ya'll, we need to update our installer from the dark background to a light one. 
EX: 
Currently we have this for navigator and miniconda:
![anaconda-installer](https://cloud.githubusercontent.com/assets/10767430/21996936/334532f8-dbf2-11e6-954d-0577f2bda2ba.png)

And we need to get images like this (from Fusion):
![fusion-installer-welcome-image](https://cloud.githubusercontent.com/assets/10767430/21996957/48e3040a-dbf2-11e6-9cf6-6aeff0dacd6f.gif)

Is there an ETA of when we can have this done if I give ya'll the correct files EOD? Also let me know if I put this issue in the correct channel. Thanks!

**Comment by ilanschnell** [comment]
Thanks.  This should really go into https://github.com/ContinuumIO/anaconda/issues
