### ISSUE TITLE
Error when uninstalling portaudio

### ISSUE THREAD

**Issue by chohner** [ContinuumIO/anaconda-issues#1364]
Current conda install:

               platform : osx-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/chohner/miniconda3  (writable)
    default environment : /Users/chohner/miniconda3
       envs directories : /Users/chohner/miniconda3/envs
          package cache : /Users/chohner/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /Users/chohner/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/3.5.2 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20

`$ /Users/chohner/miniconda3/bin/conda uninstall portaudio`

    Traceback (most recent call last):
      File "/Users/chohner/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/chohner/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/Users/chohner/miniconda3/lib/python3.5/site-packages/conda/cli/main_remove.py", line 164, in execute
        pinned=args.pinned))
      File "/Users/chohner/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 776, in remove_actions
        if pinned and any(r.match(ms, old_dist.to_filename()) for ms in pinned_specs):
      File "/Users/chohner/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 776, in <genexpr>
        if pinned and any(r.match(ms, old_dist.to_filename()) for ms in pinned_specs):
      File "/Users/chohner/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 474, in match
        rec = self.index[fkey]
    KeyError: 'portaudio-19-0.tar.bz2'

Tried re-installing with `--force`, no dice. Let me know if I can help in any way.

**Comment by kalefranz** [comment]
As of conda 4.3.11 I can't reproduce this issue.  Are you still having problems @chohner?

**Comment by chohner** [comment]
Just retried with `4.3.11` and `portaudio` seems to install & uninstall without errors! Thanks for checking.
