### ISSUE TITLE
Padding Error for `conda install qt`

### ISSUE THREAD

**Issue by pwsutherland** [ContinuumIO/anaconda-issues#1366]
I am using `IPython 5.1.0` as part of `Python 2.7.12 |Anaconda 4.2.0 (32-bit)` which has `matplotlib 1.5.3`

When I try to import  matplotlib's `pyplot` I get the following error:

`In [6]: %matplotlib
Using matplotlib backend: Qt5Agg 
In [7]: This application failed to start because it could not find or load the Qt platform plugin "windows" in "". 
Reinstalling the application may fix this problem.`

When I try `conda install qt` I get `PaddingError: Placeholder of length '30' too short in package qt-5.6.2-vc9_0.
The package must be rebuilt with conda-build > 2.0.`

I am planning to build a conda recipe but wanted to make you aware of this issue. Let me know if you need any further information.

**Comment by msarahan** [comment]
Please update conda. Recent 4.2 and 4.3 releases address this issue.

**Comment by pwsutherland** [comment]
Really appreciate your prompt reply. 

That worked!
