### ISSUE TITLE
Navigator won't start

### ISSUE THREAD

**Issue by Dynorat** [ContinuumIO/anaconda-issues#1369]
I performed the following actions:

conda update anaconda
conda update --all

Now my distribution appears to be broken when I try to call Navigator through both the icon and command line.  Though some parts like Jupyter Notebook still work if I call them directly from command line.

Here is the error message:
:~ mfields$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/mfields/anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Users/mfields/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 21, in <module>
    from anaconda_navigator.widgets.dialogs.splash import SplashScreen
  File "/Users/mfields/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/__init__.py", line 18, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Users/mfields/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal
ImportError: cannot import name QT_VERSION_STR
MFIELDS-28881S:~ mfields$ 

Also conda info output here:
               platform : osx-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : 2.1.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/mfields/anaconda  (writable)
    default environment : /Users/mfields/anaconda
       envs directories : /Users/mfields/anaconda/envs
          package cache : /Users/mfields/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/mfields/.condarc
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/2.7.13 Darwin/16.3.0 OSX/10.12.2
                UID:GID : 285269828:18434217

**Comment by goanpeca** [comment]
Try

`$ conda update qtpy`

**Comment by Dynorat** [comment]
I performed the update
qtpy: 1.1.2-py27_0 --> 1.2.0-py27_0

No impact on navigator function.  

:~ mfields$ /Users/mfields/Desktop/anaconda-navigator ; exit;
Traceback (most recent call last):
  File "/Users/mfields/Desktop/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Users/mfields/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 21, in <module>
    from anaconda_navigator.widgets.dialogs.splash import SplashScreen
  File "/Users/mfields/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/__init__.py", line 18, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Users/mfields/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal
ImportError: cannot import name QT_VERSION_STR
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by gordeli** [comment]
I had exactly the same issue. Reinstalling anaconda now gives "-bash: anaconda: command not found" when launching anything from the Terminal (was working fine after the original install of Anaconda 4.2.0). The navigator app is working again though

**Comment by goanpeca** [comment]
Looks like the path is not set correctly in your case

**Comment by gordeli** [comment]
@goanpeca 
apparently, the path was set correctly automatically during the original install. Why wouldn't it work the same way after reinstall? I guess the uninstall process does not really uninstall that well. Maybe you could tell me how to do proper uninstall and I can try to see if it fixes my issue. Thanks

**Comment by goanpeca** [comment]
>apparently, the path was set correctly automatically during the original install. Why wouldn't it work the same way after reinstall? I guess the uninstall process does not really uninstall that well. Maybe you could tell me how to do proper uninstall and I can try to see if it fixes my issue. Thanks

@ilanschnell ?

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by afdebbas** [comment]
I am facing the same problem. I have updated anaconda-navigator

`[root@db-hdp-dn1 ~]# conda install anaconda-navigator
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /root/anaconda2:

The following packages will be UPDATED:

    anaconda:           4.4.0-np112py27_0 --> custom-py27_0
    anaconda-navigator: 1.6.2-py27_0      --> 1.6.3-py27_0
`
yet i still cannot run the navigator

[root@db-hdp-dn1 ~]# anaconda-navigator
QXcbConnection: Could not connect to display
Aborted (core dumped)
