### ISSUE TITLE
Python cannot find my system SSL certificates

### ISSUE THREAD

**Issue by brandon-rhodes** [ContinuumIO/anaconda-issues#137]
When I run the following script with Ubuntu `/usr/bin/python3.4` it runs successfully:

```
import socket, ssl

raw_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
raw_sock.connect(('www.google.com', 443))

context = ssl.create_default_context()
ssl_sock = context.wrap_socket(raw_sock, server_hostname='www.google.com')
print('Success!')
```

This is now the recommended way to create SSL connections. The old `ssl.wrap_socket()` call has very poor defaults, but the maintainers did not want to alter it and break existing code, so `create_default_context()` was invented which builds an SSL context and sets several best-practices options so that all the checking is performed that should be (and so that out-of-date and insecure ciphers and protocol versions are disallowed).

But when I run the same script under Ubuntu 14.04 using Python 3.4 from the Anaconda distribution, it cannot find my system SSL certificates, and so it dies with this exception:

```
Traceback (most recent call last):
  ...
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
```

If I run the system Python 3.4 under `strace` I see that it finds the right key, presumably by first attempting the connection, learning the hash of the CA that signed `www.google.com`, and using that hash to jump directly to the right CA file:

```
...
open("/usr/lib/ssl/cert.pem", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
...
open("/usr/lib/ssl/certs/578d5c04.0", O_RDONLY|O_LARGEFILE) = 4
...
```

Whereas `strace` reveals that Anaconda Python 3.4, mystifyingly enough, looks in a directory that does not even exist on my filesystem and whose name almost looks to be the result of some kind of programming error:

```
...
open("/opt/anaconda1anaconda2anaconda3/ssl/cert.pem", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
...
```

Does this path indicate some kind of misconfiguration on my end? And: is there some setup step that I should try, like installing an additional SSL dependency with `conda`, if I am going to be running Python programs that use SSL?

Thanks for any advice!

**Comment by pearljam100** [comment]
Hi, same issue for me. I  did conda install openssl and tried softlink (linux env) but when I try anaconda search -t conda pygtk get [SSLError] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)...why does this happend? any ideas to fix? many thanks

**Comment by sarkisderderian** [comment]
Hi All, Right same issue for me also, but i got this message when using conda command, for install or update.
i tried 
$ conda update openssl
but i get same message.
any idea  and Thanks.

**Comment by nehaljwani** [comment]
If one wants to use a self signed CA certificate, one can do: 
```
cat openssl x509 -in /path/to/custom/ca.crt -outform PEM >> $CONDA_PREFIX/ssl/cacert.pem
```

**Comment by bkreider** [comment]
> If one wants to use a self signed CA certificate

It's not too hard to go one extra step to make your own CA.  I think you are saying how to add a self-signed certificate and not a self-signed CA (which is redundant).

Also, understand the ramifications of appending to this file.  Conda uses hardlinks, so you are modifying the same file in $CONDA_PREFIX/pkgs/openssl....../ssl/cacert.pem.  All new environments will get the same modification, which is probably what you want, but you should know what is happening so you aren't surprised.  If you want to only affect the file in that conda environment, you should unlink it (by moving/renaming it).
