### ISSUE TITLE
r-feather 0.3.1 missing on OSX

### ISSUE THREAD

**Issue by rgrinberg** [ContinuumIO/anaconda-issues#1371]
Seems to be available for Win/Linux. Why is it omitted on OSX?

https://anaconda.org/r/r-feather

**Comment by mingwandroid** [comment]
It got omitted because it requires extra steps to build it vs the other packages (it must be built on OSX 10.9 instead of 10.7) and, well, I forgot to do it. I'll put it on my list.

**Comment by nehaljwani** [comment]
Closing as package has been made available in the r channel.
```bash
(1371) ➜  ~ conda search -c r r-feather
Fetching package metadata ...........
r-feather                    0.3.0                  r3.3.1_0  defaults
                             0.3.1                  r3.3.2_0  defaults
                             0.3.0                  r3.3.1_0  r
                             0.3.1                  r3.3.2_0  r
```
