### ISSUE TITLE
Anaconda-navigator error on MacBook. 

### ISSUE THREAD

**Issue by ahmedAll92** [ContinuumIO/anaconda-issues#1374]
I installed Anaconda and when I try to lunch the anaconda-navigator the logo appears then disappears again. I tried to lunch it using terminal and there was an error message like this. Any suggestion or help? 

Traceback (most recent call last):
  File "/Users/ahmedalluhaydan/Desktop/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 355, in process_application_info
    packages, apps = output
TypeError: 'NoneType' object is not iterable
Abort trap: 6
Ahmeds-MBP:~ ahmed----------$ lunch
-bash: lunch: command not found

**Comment by goanpeca** [comment]
Could you update to the latest version

`$ conda update anaconda-navigator`

And make sure to delete any custome channels from the `~/.condarc` file and try again?

**Comment by ahmedAll92** [comment]
Ahmeds-MBP:~ ahmedalluhaydan$ ~/.condarc
-bash: /Users/ahmedalluhaydan/.condarc: Permission denied

I don't know why it denied my action? 
any other suggestions?

**Comment by goanpeca** [comment]
Could you type `$ conda info` and `$ conda list` in the terminal and paste the results here?

**Comment by ahmedAll92** [comment]
Current conda install:

               platform : osx-64
          conda version : 4.3.6
       conda is private : False
      conda-env version : 4.3.6
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/ahmedalluhaydan/Desktop/anaconda  (writable)
    default environment : /Users/ahmedalluhaydan/Desktop/anaconda
       envs directories : /Users/ahmedalluhaydan/Desktop/anaconda/envs
          package cache : /Users/ahmedalluhaydan/Desktop/anaconda/pkgs
           channel URLs : http://conda.anaconda.org/gurobi/osx-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ahmedalluhaydan/.condarc
           offline mode : False
             user-agent : conda/4.3.6 requests/2.12.4 CPython/2.7.12 Darwin/16.3.0 OSX/10.12.2
                UID:GID : 501:20

# packages in environment at /Users/ahmedalluhaydan/Desktop/anaconda:
#
_license                  1.1                      py27_1  
_nb_ext_conf              0.3.0                    py27_0  
alabaster                 0.7.9                    py27_0  
anaconda                  4.2.0               np111py27_0  
anaconda-clean            1.0.0                    py27_0  
anaconda-client           1.5.1                    py27_0  
anaconda-navigator        1.3.2                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astroid                   1.4.7                    py27_0  
astropy                   1.2.1               np111py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
beautifulsoup4            4.5.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.2                   py27_0  
boto                      2.42.0                   py27_0  
bottleneck                1.1.0               np111py27_0  
cdecimal                  2.3                      py27_2  
cffi                      1.7.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.6                      py27_0  
cloudpickle               0.2.1                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.3.6                    py27_0  
conda-build               2.0.2                    py27_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.3                    py27_0  
cryptography              1.5                      py27_0  
curl                      7.49.0                        1  
cycler                    0.10.0                   py27_0  
cython                    0.24.1                   py27_0  
cytoolz                   0.8.0                    py27_0  
dask                      0.11.0                   py27_0  
datashape                 0.5.2                    py27_0  
decorator                 4.0.10                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.12                     py27_2  
dynd-python               0.7.2                    py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
filelock                  2.0.6                    py27_0  
flask                     0.11.1                   py27_0  
flask-cors                2.1.2                    py27_0  
freetype                  2.5.5                         1  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.2                    py27_0  
greenlet                  0.4.10                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.6.0               np111py27_2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
icu                       54.1                          0  
idna                      2.1                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.16                   py27_0  
ipykernel                 4.5.0                    py27_0  
ipython                   5.1.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.2                      py27_1  
jedi                      0.9.0                    py27_1  
jinja2                    2.8                      py27_1  
jpeg                      8d                            2  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.0                    py27_0  
lazy-object-proxy         1.2.1                    py27_0  
libdynd                   0.7.2                         0  
libpng                    1.6.22                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvmlite                  0.13.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.6.4                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.3               np111py27_0  
mistune                   0.7.3                    py27_1  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py27_2  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.8                    py27_0  
nb_anacondacloud          1.2.0                    py27_0  
nb_conda                  2.0.0                    py27_0  
nb_conda_kernels          2.0.0                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.1.0                    py27_0  
nbpresent                 3.0.2                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.1                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.2.3                    py27_0  
numba                     0.28.1              np111py27_0  
numexpr                   2.6.1               np111py27_0  
numpy                     1.11.1                   py27_0  
odo                       0.5.0                    py27_1  
openpyxl                  2.3.2                    py27_0  
openssl                   1.0.2j                        0  
pandas                    0.18.1              np111py27_0  
partd                     0.3.6                    py27_0  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    3.3.1                    py27_0  
pip                       8.1.2                    py27_0  
pkginfo                   1.3.2                    py27_0  
ply                       3.9                      py27_0  
prompt_toolkit            1.0.3                    py27_0  
psutil                    4.3.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.14                     py27_1  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_0  
pyflakes                  1.3.0                    py27_0  
pygments                  2.1.3                    py27_0  
pylint                    1.5.4                    py27_1  
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_1  
pytables                  3.2.3.1             np111py27_0  
pytest                    2.9.2                    py27_0  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
python.app                1.2                      py27_4  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     15.4.0                   py27_0  
qt                        5.6.2                         0  
qtawesome                 0.3.3                    py27_0  
qtconsole                 4.2.1                    py27_1  
qtpy                      1.1.2                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.12.4                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_0  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.17.1              np111py27_2  
scipy                     0.18.1              np111py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.4.6                    py27_0  
spyder                    3.0.0                    py27_0  
sqlalchemy                1.0.13                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
sympy                     1.0                      py27_0  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py27_0  
tornado                   4.4.1                    py27_0  
traitlets                 4.3.0                    py27_0  
unicodecsv                0.14.1                   py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.11                  py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
wrapt                     1.10.6                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.3                    py27_0  
xlwings                   0.10.0                   py27_0  
xlwt                      1.1.2                    py27_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3

**Comment by goanpeca** [comment]
Let me take a look at the info and I will get back to you tomorrow, we are releasing soon a new version so I think you could use that one, which most likely fixes what you are seeing.

**Comment by ahmedAll92** [comment]
Alright really appreciate it. I have work on and it most be done soon and it's not working. I will be waiting tomorrow for the new version.

**Comment by ahmedAll92** [comment]
Anything yet? It seems it's taking more than I thought.

**Comment by goanpeca** [comment]
@ahmedAll92 the QA team is working on testing the package, it should be available on repo this Monday 23rd. Thanks for the patience

**Comment by ahmedAll92** [comment]
Can you please notify me when it's available. Thanks again.

**Comment by goanpeca** [comment]
Will do

**Comment by gordeli** [comment]
I had the same problem 2 days ago. The problem appeared after running "conda update -all". (before that the navigator was launching just fine). I was able to launch navigator from terminal adding "sudo" in front of the command and typing in my password (which was not needed before the issue appeared). After wiping off anaconda and reinstalling I am getting "-bash: conda: command not found" and "-bash: anaconda: command not found"  error when running in the terminal. The navigator is launching fine though by clicking on the app

**Comment by goanpeca** [comment]
@gordeli what was the error?

**Comment by gordeli** [comment]
@goanpeca 
there was a series of errors as described in my post. Not sure what exactly you want to know.
1. conda update --all breaks all package dependencies I guess and breaks the anaconda navigator app (somehow you have to run it with administrator privileges after that.
2. instructions to uninstall anaconda on continuum website do not really work. maybe anaconda-clean starts malfunctioning as well after conda update-all. I have no idea.
3. installing again gives different behavior than on the original install (some issue with PATH even though there was no issue before).

It seems to be exactly the same issue as for everyone who did "conda update --all"

**Comment by goanpeca** [comment]
@gordeli please open a new issue and report it there.

**Comment by fancyg** [comment]
Hi!
Whenever I tried to include a new channel it crashed immediately with the same error message as above.

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by esoztas** [comment]
When I want uptade anaconda navigator with this command

`conda update --all`

Error:  conda: command not found.

Solution:

_go to   ~/anaconda3/bin_

and run

`./conda update --all`

it  worked in my computer.
