### ISSUE TITLE
.py files not associated properly in Windows

### ISSUE THREAD

**Issue by alexei-argus** [ContinuumIO/anaconda-issues#1375]
Hi,
I noticed that if you invoke .py scripts without prepending "python" to the command line the arguments aren't passed propertly.
For example, "python script.py first second" works well, but "script.py first second" receives no arguments.
I believe this has to do with the fact that the assoc utility reports that .py files aren't associated with any executable in the registry, at least according to [this StackOverflow question](http://stackoverflow.com/questions/1934675/how-to-execute-python-scripts-in-windows).

I had this issue on several Windows 10 64 bit machines.

**Comment by nehaljwani** [comment]
CC @mingwandroid

**Comment by mingwandroid** [comment]
Anaconda doesn't do *anything* with file associations on Windows. If we were to set them without asking it would annoy a large number of people (who may associate .py with Visual Studio or Sublime Text 3 or whatever) and making a dialog to provide choice of which extensions to associate is a lot of work. There is a 'standard' official-ish Python launcher that was discussed here previously: https://github.com/ContinuumIO/anaconda-issues/issues/149 but it's not very well suited for Anaconda Distribution's requirements and capabilities.

For this reason, I am closing this as it is out of scope.

**Comment by ijstokes** [comment]
@mingwandroid I'm not asking you to re-open this, but the majority of our downloads are Windows users and the majority of our target end users have Windows on their desktop/laptop work systems.  Who is the person who thinks about what their experience is like (i.e. the Windows-only Anaconda user)?  Can that person think about whether this is in-scope or out-of-scope for 2017?

**Comment by mingwandroid** [comment]
I think I do more work on Windows OS integration than others in the team these days. I have a soft spot for Windows and want Windows users to have as good an experience as time allows.

**Comment by ijstokes** [comment]
Sounds good to me.
