### ISSUE TITLE
My navigator doesn't show up after I installed it. 

### ISSUE THREAD

**Issue by xinwang356** [ContinuumIO/anaconda-issues#1377]
Traceback (most recent call last):
  File "/Users/xw/anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Users/xw/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 16, in <module>
    from qtpy.QtCore import QCoreApplication, QEvent, QObject, Qt
  File "/Users/xw/anaconda/lib/python2.7/site-packages/qtpy/QtCore.py", line 34, in <module>
    from PyQt4.QtGui import (QItemSelection, QItemSelectionModel,
ImportError: dlopen(/Users/xw/anaconda/lib/python2.7/site-packages/PyQt4/QtGui.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/xw/anaconda/lib/libQtGui.4.8.7.dylib
  Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 34.0.0

Thank you in advance.

**Comment by xinwang356** [comment]
platform : osx-64
          conda version : 4.3.7
       conda is private : False
      conda-env version : 4.3.7
    conda-build version : 1.18.2
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/xw/anaconda  (writable)
    default environment : /Users/xw/anaconda
       envs directories : /Users/xw/anaconda/envs
          package cache : /Users/xw/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/xw/.condarc
           offline mode : False
             user-agent : conda/4.3.7 requests/2.12.4 CPython/2.7.13 Darwin/15.0.0 OSX/10.11.1
                UID:GID : 501:20

**Comment by xinwang356** [comment]
# packages in environment at /Users/xw/anaconda:
#
_license                  1.1                      py27_1  
abstract-rendering        0.5.1               np110py27_0  
alabaster                 0.7.9                    py27_0  
anaconda                  custom                   py27_0  
anaconda-client           1.6.0                    py27_0  
anaconda-navigator        1.2.3                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astroid                   1.4.9                    py27_0  
astropy                   1.0.6               np110py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
beautifulsoup4            4.4.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze-core                0.8.3                    py27_0  
bokeh                     0.10.0                   py27_0  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0               np110py27_0  
cdecimal                  2.3                      py27_0  
cffi                      1.9.1                    py27_0  
chardet                   2.3.0                    py27_0  
clyent                    1.2.0                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     4.3.7                    py27_0  
conda-build               1.18.2                   py27_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
cryptography              1.7.1                    py27_0  
curl                      7.45.0                        0  
cycler                    0.9.0                    py27_0  
cython                    0.23.4                   py27_1  
cytoolz                   0.7.4                    py27_0  
datashape                 0.4.7               np110py27_1  
decorator                 4.0.11                   py27_0  
docutils                  0.13.1                   py27_0  
dynd-python               0.7.0                    py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
freetype                  2.5.5                         0  
funcsigs                  0.4                      py27_0  
functools32               3.2.3.2                  py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
greenlet                  0.4.9                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.5.0               np110py27_4  
hdf5                      1.8.15.1                      2  
icu                       54.1                          0  
idna                      2.2                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.5.2                    py27_0  
ipython                   5.1.0                    py27_1  
ipython-notebook          4.0.4                    py27_0  
ipython-qtconsole         4.0.1                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.0                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.0                      py27_0  
jedi                      0.9.0                    py27_1  
jinja2                    2.9.4                    py27_0  
jpeg                      8d                            1  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_1  
jupyter_client            4.4.0                    py27_0  
jupyter_console           4.0.3                    py27_0  
jupyter_core              4.2.1                    py27_0  
launcher                  1.0.0                         3  
lazy-object-proxy         1.2.2                    py27_0  
libdynd                   0.7.0                         0  
libpng                    1.6.17                        0  
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvmlite                  0.8.0                    py27_0  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.0               np110py27_0  
mistune                   0.7.3                    py27_1  
multipledispatch          0.4.8                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.2.0                    py27_0  
networkx                  1.10                     py27_0  
nltk                      3.1                      py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0  
notebook                  4.0.6                    py27_0  
numba                     0.22.1              np110py27_0  
numexpr                   2.4.4               np110py27_0  
numpy                     1.10.1                   py27_0  
numpydoc                  0.6.0                    py27_0  
odo                       0.3.4                    py27_0  
openpyxl                  2.2.6                    py27_0  
openssl                   1.0.2j                        0  
pandas                    0.17.1              np110py27_0  
path.py                   10.0                     py27_0  
pathlib2                  2.2.0                    py27_0  
patsy                     0.4.0               np110py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    3.0.0                    py27_1  
pip                       9.0.1                    py27_1  
ply                       3.8                      py27_0  
prompt_toolkit            1.0.9                    py27_0  
psutil                    5.0.1                    py27_0  
ptyprocess                0.5                      py27_0  
py                        1.4.30                   py27_0  
pyasn1                    0.1.9                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_3  
pyflakes                  1.5.0                    py27_0  
pygments                  2.1.3                    py27_0  
pylint                    1.6.4                    py27_0  
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.4                   py27_4  
pytables                  3.2.2               np110py27_0  
pytest                    2.8.1                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2016.10                  py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     16.0.2                   py27_0  
qt                        4.8.7                         4  
qtawesome                 0.4.1                    py27_0  
qtconsole                 4.2.1                    py27_0  
qtpy                      1.2.0                    py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.12.4                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
scandir                   1.4                      py27_0  
scikit-image              0.11.3              np110py27_0  
scikit-learn              0.17                np110py27_1  
scipy                     0.16.0              np110py27_1  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.5.1                    py27_0  
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.8                    py27_1  
spyder-app                2.3.8                    py27_0  
sqlalchemy                1.0.9                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np110py27_0  
sympy                     0.7.6.1                  py27_0  
terminado                 0.5                      py27_1  
tk                        8.5.18                        0  
toolz                     0.7.4                    py27_0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.1                    py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.14.1                   py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.2                   py27_0  
wheel                     0.29.0                   py27_0  
wrapt                     1.10.8                   py27_0  
xlrd                      0.9.4                    py27_0  
xlsxwriter                0.7.7                    py27_0  
xlwings                   0.5.0                    py27_0  
xlwt                      1.0.0                    py27_0  
xz                        5.0.5                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         3

**Comment by xinwang356** [comment]
I used launcher before. Today, I updated the spyder and restart the launcher. The launcher stuck at loading the apps. Then, I installed the navigator. It even didn't show up. Please help me resolve this issue. Thank you in advance.

**Comment by xinwang356** [comment]
xwangs-MacBook-Pro:~ xw$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/xw/anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Users/xw/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 21, in <module>
    from anaconda_navigator.widgets.dialogs.splash import SplashScreen
  File "/Users/xw/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/__init__.py", line 18, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Users/xw/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal
ImportError: cannot import name QT_VERSION_STR
xwangs-MacBook-Pro:~ xw$

**Comment by allyelsey** [comment]
Would you mind explaining how you fixed your issue? I have seen this issue before and am curious how you solved it.
