### ISSUE TITLE
Install Issue for R-Essentials on Windows

### ISSUE THREAD

**Issue by jgmorrison** [ContinuumIO/anaconda-issues#1378]
When installing R-Essentials on any version of Windows the following error occurs.

    echo ***** post_link.bat for m2w64-p11-kit ****
    **** post_link.bat for m2w64-p11-kit ****
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.

With r-essentials and rpy2(rpy2 installs r-essentials) there is a possibly related issue:

    %load_ext rpy2.ipython fails with “libbz2-1.dll is missing from your computer”

It appears that "C:\Program Files\Anaconda3\Library\mingw-w64\bin" is never added to the path. Adding this to the path fixes the rpy2 issue. This happens on "All User" installs and "Just Me" installs. Could the failed post_link.bat issue be where it is not adding a path to "C:\Program Files\Anaconda3\Library\mingw-w64\bin"?

**Comment by mingwandroid** [comment]
This was a problem but without any negative consequences.

It should be fixed now anyway.
