### ISSUE TITLE
PyQt5 and Anaconda trouble

### ISSUE THREAD

**Issue by David-OConnor** [ContinuumIO/anaconda-issues#138]
Qt doesn't like having multiple versions installed at the same time: 'RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class', after installing PyQt5 with Anaconda.

I got Qt5 working using 'conda remove PyQt', followed by 'f'[orce] . This must be done before installing PyQt5, since it removes sip. Also had to 'conda remove matplotlib' with a force, and reinstall it from the LFCI packages website. Ipython GUI and Spyder too. (Haven't found a workaround like this for Linux yet)

Is there a way to have PyQt 4 and 5 installed at the same time Anaconda? I'd like to be able to use PyQt5 without breaking Spyder, Matplotlib and IPython.

**Comment by MrLeeh** [comment]
I also got trouble using PyQt5 in a conda environment. I did the following steps:

* install PyQt5 package in conda root with `conda install pyqt5`
* create a new environment with `conda create -n myenv`
* install PyQt5 package in the new environment with `conda install pyqt5`

When I tried to import PyQt5.QtWidgets module I got the following error:

 ```python
>>> from PyQt5.QtWidgets import *
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application
```
I got the whole thing working by copying the Qt directory (c:\miniconda3\Lib\site-packages\PyQt5\Qt) from the root environment to the virtual environment. Still I' m not happy with this solution. Does somebody know a better way?

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
@MrLeeh, we still don't have official packages for PyQt5, so I don't know where you get them.

**Comment by MrLeeh** [comment]
I got them from the [inso repository](https://conda.anaconda.org/inso).
https://conda.anaconda.org/t/Mr-56d558cb-15c2-4d19-bbe1-909c14db8f86/inso/win-64/pyqt5-5.5.1-py35_0.tar.bz2

**Comment by ccordoba12** [comment]
I don't know where those packages are coming from. Please contact the author and talk to him/her about the problems you're having :-)

**Comment by MrLeeh** [comment]
Alright thanks, I' ll do this. Is there going to be an official PyQt5 support in the future?

**Comment by mingwandroid** [comment]
Yes, please use https://anaconda.org/qttesting channel to test.

**Comment by MrLeeh** [comment]
@mingwandroid Thanks for this tipp. I tried the pyqt package from https://anaconda.org/qttesting and it works out of the box. Why is it still declared as testing?

**Comment by ccordoba12** [comment]
Because we haven't moved them to our main channels :-) Sorry for not mentioning those packages, but we're working on the last details before announcing them publicly.

**Comment by mingwandroid** [comment]
@ccordoba12, I figured that by mentioning them we'd get some extra testing, apologies if you'd rather I didn't.

**Comment by ccordoba12** [comment]
@mingwandroid, no problem if you take the bullets for problems about them ;-) I don't have time to give them support right now.

**Comment by MrLeeh** [comment]
So this finally seems to work. Maybe this issue should be closed. Just installed [PyQt5](https://anaconda.org/anaconda/pyqt) from the default channel.

**Comment by phpmind** [comment]
pip install PyQt5   :::

After struggling 2 hrs,  finally, this worked for me. Just wanted to share.

**Comment by Lyoyanu** [comment]
conda install -c dsdale24 pyqt5 

Try this one . It works for me .

**Comment by DaveDave9994** [comment]
Im having this issue on a virgin anaconda install.
OS = Win 10
anaconda  = Anaconda3-5.3.0-Windows-x86_64
python = 3.7

Im playing around with PyQt5.  When i run the following in Spyder it works.
`import sys
from PyQt5.QtWidgets import QApplication, QWidget`

When i run it in Visual Studio i get the following error
"ModuleNotFoundError: No module named 'pyqt5'"

Is there a definitive fix for this?

**Comment by mingwandroid** [comment]
@DaveDave9994, did you activate your environment before launching Sypder?

You may have run into local packages causing problems. Perhaps try `conda update python`. More info at https://github.com/ContinuumIO/anaconda-issues/issues/10236

**Comment by DaveDave9994** [comment]
I have uninstalled and made sure that anaconda is the only package for python.  C:\Users\antho\Anaconda3

if i `pip install pyqt5` i break anaconda and need to unistall, clean then reinstall.  
if i `conda install pyqt5` i get PackagesNotFoundError:

Im thinking of getting rid on anaconda and doing a straight Python3.7 install.

**Comment by msarahan** [comment]
Please see https://www.anaconda.com/blog/developer-blog/who-you-gonna-call-halloween-tips-treats-to-protect-you-from-ghosts-gremlins-and-software-vulnerabilities/ for more potential causes and remedies.

**Comment by ccordoba12** [comment]
> if i conda install pyqt5 i get PackagesNotFoundError

It's `conda install pyqt`, not `conda install pyqt5`

**Comment by Runekeon** [comment]
The fact that this issue has been causing problems since 2014 and I'm having it in 2019 makes me think Anaconda is not worth it.

**Comment by mingwandroid** [comment]
@Runekeon, I hope you find what you are looking for, good luck!

**Comment by aron-alarik** [comment]
tried all of the solutions above, still facing the same issue: the moment I install pyqtgraph (latest version) or update PyQT, anaconda stops working !!
