### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by deepak1409** [ContinuumIO/anaconda-issues#1380]
The following errors occured:

RuntimeError:
Could not find URL: https://pypi.python.org/simple/win-32/

{'pyqt': '4.11.4', 'python': '3.5.2', 'conda': '4.1.6', 'version': '1.2.1', 'platform': 'win-32', 'language': 'en_IN', 'qt': '4.8.7', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel'}

**Comment by goanpeca** [comment]
@deepak1409 could you go to the console and type

```
$ conda info
$ conda list
```
And paste the output here?

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`
