### ISSUE TITLE
Problem with installing r-rodbc

### ISSUE THREAD

**Issue by torp56** [ContinuumIO/anaconda-issues#1384]
Created from https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/WRb1UVIrvr4

First I use Anaconda Navigator to install r-rodbc in an R  and rBokeh environment.

I removed MRO from .condarc

channels:
  - r
  - bokeh
  - defaults

Now
Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\IBM_ADMIN\Anaconda3  (writable)
    default environment : C:\Users\IBM_ADMIN\Anaconda3
       envs directories : C:\Users\IBM_ADMIN\Anaconda3\envs
          package cache : C:\Users\IBM_ADMIN\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bokeh/win-64
                          https://conda.anaconda.org/bokeh/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\IBM_ADMIN\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Windows/7 Windows/6.1.7601

But problem persist:

UnsatisfiableError:
The following specifications were found to be in conflict:
- r-modelmetrics -> r-base 3.3.2*
- r-rodbc
Use "conda info " to see the dependencies for each package.

Den torsdag den 26. januar 2017 kl. 12.32.13 UTC+1 skrev Ray Donnelly:

    Please remove the mro channel (though I don't think it is the cause of
    your trouble). Can you show what command you issued to conda to
    attempt this installation?

    On Thu, Jan 26, 2017 at 11:26 AM,  <erik...@gmail.com> wrote:
    > I have not considered to install r-modelmetrics, it may be from when I
    > installed r-essentials?
    >
    > Here is conda info
    >
    > Current conda install:
    >
    >                platform : win-64
    >           conda version : 4.3.8
    >        conda is private : False
    >       conda-env version : 4.3.8
    >     conda-build version : 2.0.2
    >          python version : 3.5.2.final.0
    >        requests version : 2.12.4
    >        root environment : C:\Users\IBM_ADMIN\Anaconda3  (writable)
    >     default environment : C:\Users\IBM_ADMIN\Anaconda3
    >        envs directories : C:\Users\IBM_ADMIN\Anaconda3\envs
    >           package cache : C:\Users\IBM_ADMIN\Anaconda3\pkgs
    >            channel URLs : https://conda.anaconda.org/mro/win-64
    >                           https://conda.anaconda.org/mro/noarch
    >                           https://conda.anaconda.org/r/win-64
    >                           https://conda.anaconda.org/r/noarch
    >                           https://conda.anaconda.org/bokeh/win-64
    >                           https://conda.anaconda.org/bokeh/noarch
    >                           https://repo.continuum.io/pkgs/free/win-64
    >                           https://repo.continuum.io/pkgs/free/noarch
    >                           https://repo.continuum.io/pkgs/r/win-64
    >                           https://repo.continuum.io/pkgs/r/noarch
    >                           https://repo.continuum.io/pkgs/pro/win-64
    >                           https://repo.continuum.io/pkgs/pro/noarch
    >                           https://repo.continuum.io/pkgs/msys2/win-64
    >                           https://repo.continuum.io/pkgs/msys2/noarch
    >             config file : C:\Users\IBM_ADMIN\.condarc
    >            offline mode : False
    >              user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2
    > Windows/7 Windows/6.1.7601
    >
    >
    > Den torsdag den 26. januar 2017 kl. 12.19.53 UTC+1 skrev Ray Donnelly:
    >>
    >> I just want `conda info` on its own, not `conda info r-base`.
    >> The problem here is that r-rodbc is not available for r-3.3.2 at
    >> present, and r-modelmetrics is not available for r-3.3.1. Do you need
    >> both of them?
    >>
    >> On Thu, Jan 26, 2017 at 10:53 AM,  <erik...@gmail.com> wrote:
    >> > See attached files
    >> >
    >> >
    >> > Den torsdag den 26. januar 2017 kl. 11.39.00 UTC+1 skrev Ray Donnelly:
    >> >>
    >> >> Please open an issue on GitHub:
    >> >> https://github.com/ContinuumIO/anaconda-issues
    >> >>
    >> >> Please show the commands you tried to execute, the output from `conda
    >> >> info` and from `conda list --show-channel-urls`
    >> >>
    >> >> On Jan 26, 2017 9:14 AM, <erik...@gmail.com> wrote:
    >> >>>
    >> >>> Hi
    >> >>>
    >> >>> I get this message - and in doubt what I do to solve.
    >> >>>
    >> >>> UnsatisfiableError:
    >> >>> The following specifications were found to be in conflict:
    >> >>> - r-modelmetrics -> r-base 3.3.2*
    >> >>> - r-rodbc
    >> >>> Use "conda info " to see the dependencies for each package.
    >> >>>
    >> >>> best regards
    >> >>> Erik Torp
    >> >>>
    >> >>> --
    >> >>> Anaconda Community Support Group Brought to you by Continuum Analytics
    >> >>> ---
    >> >>> You received this message because you are subscribed to the Google
    >> >>> Groups
    >> >>> "Anaconda - Public" group.
    >> >>> To unsubscribe from this group and stop receiving emails from it, send
    >> >>> an
    >> >>> email to anaconda+u...@continuum.io.
    >> >>> To post to this group, send email to anac...@continuum.io.
    >> >>> Visit this group at
    >> >>> https://groups.google.com/a/continuum.io/group/anaconda/.
    >> >
    >> > --
    >> > Anaconda Community Support Group Brought to you by Continuum Analytics
    >> > ---
    >> > You received this message because you are subscribed to the Google
    >> > Groups
    >> > "Anaconda - Public" group.
    >> > To unsubscribe from this group and stop receiving emails from it, send
    >> > an
    >> > email to anaconda+u...@continuum.io.
    >> > To post to this group, send email to anac...@continuum.io.
    >> > Visit this group at
    >> > https://groups.google.com/a/continuum.io/group/anaconda/.
    >
    > --
    > Anaconda Community Support Group Brought to you by Continuum Analytics
    > ---
    > You received this message because you are subscribed to the Google Groups
    > "Anaconda - Public" group.
    > To unsubscribe from this group and stop receiving emails from it, send an
    > email to anaconda+u...@continuum.io.
    > To post to this group, send email to anac...@continuum.io.
    > Visit this group at
    > https://groups.google.com/a/continuum.io/group/anaconda/.

**Comment by mingwandroid** [comment]
OK, thanks for all the info, I'm fixing it now.

**Comment by mingwandroid** [comment]
This should be fixed now. Please close it if works for you.

**Comment by torp56** [comment]
r-rodbc now installs without errors.
Thanks!
