### ISSUE TITLE
Error Spawn ENOET

### ISSUE THREAD

**Issue by abthabib** [ContinuumIO/anaconda-issues#1385]
Hi, 
I am new to python and after installing the system and worked for a while, I am receiving this error and it asked me to posted here:

Error: spawn ENOENT
at experts.errnoException (until.js:742:11)
at Process ChileProcess.handle.onexit (child_process.js:1027:32)
at chiled_process.js:1110:20
at process._tickCallback (node.js:279:11)

**Comment by goanpeca** [comment]
what system what program?

**Comment by abthabib** [comment]
Sorry: Im using Mac OS and this is Python Anaconda Launcher

**Comment by goanpeca** [comment]
Anaconda Launcher is deprecated for a long time. Please update to the latest Anaconda Distribution 

https://www.continuum.io/downloads#osx

And use Navigator, as Launcher is deprecated

https://docs.continuum.io/anaconda/navigator

Cheers

**Comment by abthabib** [comment]
Thank you. I appreciate your fast response.
