### ISSUE TITLE
the pillow package is broken

### ISSUE THREAD

**Issue by 183amir** [ContinuumIO/anaconda-issues#1387]
Similar to https://github.com/ContinuumIO/anaconda-issues/issues/1379#issuecomment-275640870 the `pillow` package is also broken:
```sh
$ conda create -n test python=2 pillow
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/amir/miniconda/envs/test:

The following NEW packages will be INSTALLED:

    freetype:   2.5.5-2       defaults
    jbig:       2.1-0         defaults
    jpeg:       9b-0          defaults
    libpng:     1.6.27-0      defaults
    libtiff:    4.0.6-3       defaults
    openssl:    1.0.2k-0      defaults
    pillow:     4.0.0-py27_0  defaults
    pip:        9.0.1-py27_1  defaults
    python:     2.7.13-0      defaults
    readline:   6.2-2         defaults
    setuptools: 27.2.0-py27_0 defaults
    sqlite:     3.13.0-0      defaults
    tk:         8.5.18-0      defaults
    wheel:      0.29.0-py27_0 defaults
    xz:         5.2.2-1       defaults
    zlib:       1.2.8-3       defaults

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate test
#
# To deactivate this environment, use:
# > source deactivate test
#

$ source activate test
$ python -c "import pkg_resources; pkg_resources.require('pillow')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/amir/miniconda/envs/test/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 968, in require
  File "/home/amir/miniconda/envs/test/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'olefile' distribution was not found and is required by pillow
```
It depends on `olefile` but it's not a dependency of `pillow` in the defaults channel.
I suspect this is a new dependency in pillow version 4.

@ilanschnell you might want to consider adding tests like what I proposed here: https://github.com/ContinuumIO/anaconda-recipes/pull/77 to prevent these kind of broken packages early on.

P.S. pillow 4 in conda-forge depends on `olefile`:
```sh
conda-forge.github.io (git) $ python scripts/list_deps.py conda-forge --dependencies olefile
Fetching package metadata .....
msg-extractor 0.2 py27_0 None      : olefile
msg-extractor 0.2 py34_0 None      : olefile
msg-extractor 0.2 py35_0 None      : olefile
pillow 4.0.0 py27_1 None           : olefile
pillow 4.0.0 py35_1 None           : olefile
pillow 4.0.0 py36_1 None           : olefile
```

**Comment by ilanschnell** [comment]
Thanks for pointing this out.  I will add an `olefile` package to repository, and as a dependency to `pillow`.  Do you know to which extend Pillow is actually broken by missing `olefile`?

**Comment by 183amir** [comment]
The problem is when I try to package another package that depends on pillow, setuptools tries to download olefile. However olefile is not a dependency of that package.

**Comment by ilanschnell** [comment]
Hmm, but `pillow` is using `setuptools` as a build dependency, see: https://github.com/ContinuumIO/anaconda-recipes/blob/master/pillow/meta.yaml#L24 so when you build `pillow`, it should already try to have downloaded `olefile` and failed, but it works fine.

Anyway, I'll add `olefile` as a new dependency of `pillow`.

**Comment by 183amir** [comment]
Yes it's wired. I don't know why these requirements are caught in conda
forge though.

**Comment by 183amir** [comment]
@ilanschnell looking at conda-forge, the dependency on olefile was not caught in conda-forge too. Rather it was fixed later: https://github.com/conda-forge/pillow-feedstock/issues/25

**Comment by anjos** [comment]
@ilanschnell: In Anaconda, you're extensively using `--single-version-externally-managed` flag for setuptools. I think it implies setuptools defers things such as dependence tracking to the caller - in this case, to conda. Unfortunately, conda is unaware of the dependence to `olefile` at this point.

**Comment by 183amir** [comment]
Hi @ilanschnell would it be possible that we see this fixed soon, please? We have a deadline and this is blocking our release. I can make the `olefile` a dependency of my packages but that is not a very clean solution because they don't depend on it. Thanks.

**Comment by ilanschnell** [comment]
I was hoping there would be a new pillow release, such that I could combine updating pillow with adding the new `olefile` dependency.  Since that hasn't happened yet, I'm just doing new rebuilding 4.0.0 with the new dependency.  Pillow 4.0.0 (build 1) packages should be available shortly.

**Comment by 183amir** [comment]
Thank you very much @ilanschnell. I think hotfixing the metadata of the build 0 package would have been enough. Is this going to be reflected in anaconda 4.3.0 too? I mean will either pillow 4.0.0-0 be hotfixed or anaconda 4.3.0  depend on pillow 4.0.0-1 or we will have to wait for the next release of anaconda?

**Comment by ilanschnell** [comment]
The problem with just hotfixing the metadata would be that then anaconda 4.3.0 would also have to change (and include olefile), so it wouldn't be anaconda 4.3.0 anymore.  Anyway the new packages are available now.

**Comment by ilanschnell** [comment]
Closing issue.  Please reopen if there are still issues.
