### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ShashankSSingh** [ContinuumIO/anaconda-issues#1389]
The following errors occured:

RuntimeError:
Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/conda-env-2.5.2-py35_0.tar.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003E4BE48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))): https://repo.continuum.io/pkgs/free/win-64/conda-env-2.5.2-py35_0.tar.bz2

{'conda': '4.1.6', 'version': '1.2.1', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'language': 'en_IN', 'qt': '4.8.7', 'pyqt': '4.11.4', 'python': '3.5.2', 'platform': 'win-64'}

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.
