### ISSUE TITLE
Possible problems with Conda and R (R package deps?)

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#1390]
I am seeing what seems to be some inconsistent behavior with R packages installed via Conda.  It might be a problem with the R packages, or with Conda, or just my misunderstanding of "expected behavior".

My first guess is that it seems like R cares about patch/micro version differences in libraries whereas Python does not (Python supports semver, so only MAJOR.MINOR need to match up, whereas R complains if there are PATCH/MICRO discrepancies between the interpreter and libraries).  I don't know how much "complains" translates into "may not work properly".

But here is my situation:

1. I have setup my Conda environment initially with this operation:

```
conda create -n rcore -c r anaconda python=3.5 \
                           r-essentials r-devtools r-nycflights13 rpy2
```

    This gave me R 3.3.2 based packages (and R version 3.3.2).

2. And then shortly later I went and did this to the environment:

```
conda install -c bioconda r-viridis
```

That second operation down-graded **some** of the R packages to the 3.3.1 versions, but not all of them.  R itself is downgraded to the `r-base` package version 3.3.1.

Now when I try to load the `repr` R library (which was not downgraded), I get the following:

```
> library(repr)
Warning message:
“package ‘repr’ was built under R version 3.3.2”
```

So I'm not sure if this is an R-package-building issue for @mingwandroid to consider or a Conda package resolution issue for @mcg1969 (I feel less likely, given I'm generally trusting "new-generation" Conda).  Or if this is all "OK" and I shouldn't worry about it.

**Comment by mingwandroid** [comment]
You cannot use bioconda with conda defaults for two reasons:
1. They are not Binary Compatible (since bioconda are basing themselves on conda-forge now).
2. bioconda do not have any R-3.3.2 packages.

**Comment by ijstokes** [comment]
Got it. Closing.  Still a bit confused about how R was partially downgraded to create these warnings, but I'll assume that it is based on the idea that MICRO level versions should all be cross-compatible.

**Comment by mingwandroid** [comment]
You asked conda to install a package + version which only exists in the r-3.3.1 package set (because of `-c bioconda`) and that package depends on r-base, so it installed r-base 3.3.1 from the bioconda channel for you due to channel priorities (channels listed with -c get precedence).

**Comment by ijstokes** [comment]
I sort of understand that, but not entirely.  If 3.3.1 is required (because it is MICRO version level sensitive) then why weren't all the other 3.3.2 R packages also down-graded?  If it is NOT sensitive to MICRO version levels then why wasn't the already installed 3.3.2 (from defaults) acceptable?
