### ISSUE TITLE
Lockerror when conda install qt-5.6.2  

### ISSUE THREAD

**Issue by bninopaul** [ContinuumIO/anaconda-issues#1393]
I get this error when installing qt-5.6.2:

``$conda install qt``
``Fetching package metadata .......``
``Solving package specifications: ..........``

``Package plan for installation in environment /Users/user/anaconda3:``

``The following packages will be downloaded:``

    package                    |            build
    ---------------------------|-----------------
    qt-5.6.2                   |                0        67.2 MB
    requests-2.12.4            |           py35_0         792 KB
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.3.7                |           py35_0         489 KB
    ------------------------------------------------------------
                                           Total:        68.6 MB

``The following NEW packages will be INSTALLED:``

    ``conda-env: 2.6.0-0``

``The following packages will be UPDATED:``

    ``conda:     4.2.9-py35_0  --> 4.3.7-py35_0``
    ``pyopenssl: 16.0.0-py35_0 --> 16.2.0-py35_0``
    ``qt:        5.6.0-0       --> 5.6.2-0``
    ``requests:  2.11.1-py35_0 --> 2.12.4-py35_0``

``Proceed ([y]/n)?``

``Fetching packages ...``
``qt-5.6.2-0.tar 100% |#########################################| Time: 0:00:47   1.45 MB/s``
``Exceeded max retries, giving upLockError: Lock error: Already locked: Lock error:``
``LOCKERROR: It looks like conda is already doing something.``
``The lock ['/Users/user/anaconda3/pkgs/qt-5.6.2-0.tar.bz2.pid11988.conda_lock'] was found. Wait for it to finish before continuing.``
``If you are sure that conda is not running, remove it and try again.``
``You can also use: $ conda clean --lock``

I already tried the `conda clean --lock`  but still same error.

Here's the conda info of the Anaconda installed in my machine:

  ``$conda info``
  ``Current conda install:``

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/user/anaconda3  (writable)
    default environment : /Users/user/anaconda3
       envs directories : /Users/user/anaconda3/envs
          package cache : /Users/user/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False`

**Comment by ccordoba12** [comment]
I don't understand this error. @mingwandroid, have you seen it before?

**Comment by mingwandroid** [comment]
It's a conda thing, but 4.2.9 is quite old. @bninopaul can you so `conda update conda` then try again?

**Comment by bninopaul** [comment]
I update the conda version to 4.2.13.
```
$conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/user/anaconda  (writable)
    default environment : /Users/user/anaconda
       envs directories : /Users/user/anaconda/envs
          package cache : /Users/user/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/user/.condarc
           offline mode : False
```
but still same error,
```
$conda install qt

Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/user/anaconda/envs/cs231n:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qt-5.6.2                   |                0        67.2 MB

The following NEW packages will be INSTALLED:

    icu: 54.1-0
    qt:  5.6.2-0

Proceed ([y]/n)? y

Fetching packages ...
qt-5.6.2-0.tar 100% |##########| Time: 0:02:03 561.91 kB/s
Exceeded max retries, giving up

LockError: Lock error: Already locked: Lock error:
LOCKERROR: It looks like conda is already doing something.
The lock ['/Users/user/anaconda/pkgs/qt-5.6.2-0.tar.bz2.pid17776.conda_lock'] was found. Wait for it to finish before continuing.
If you are sure that conda is not running, remove it and try again.
You can also use: $ conda clean --lock
```

**Comment by kalefranz** [comment]
@bninopaul is there a reason you can't upgrade to conda 4.3.11?

**Comment by bninopaul** [comment]
@kalefranz i already resolved the issue by just adding another channel conda-forge
