### ISSUE TITLE
python3.dll is missing

### ISSUE THREAD

**Issue by Siecje** [ContinuumIO/anaconda-issues#1394]
Anaconda 4.2.0 is missing python3.dll.

After `pip install PyQt5==5.7.1` importing `import PyQt5.QtCore` fails with missing .dll message.

Dependency Walker lists python3.dll as missing.

By adding `python3.dll` from an installer from python.org to the Anaconda install directory (same place as python35.dll), PyQt5 works.

**Comment by ccordoba12** [comment]
Please use conda packages to install PyQt5. We don't support pip packages for it right now.

**Comment by Aspirinkb** [comment]
I use 'conda install -c nmearl pyqt5=5.5.0' to install PyQt5 on my mac in python3.5 env. `from PyQt5.QtWidgets import (
    QWidget,
    QPushButton,
    QApplication,
    QHBoxLayout,
    QVBoxLayout,
    QFileDialog,
    QMessageBox,
    QLabel,
    QTableWidget,
    QTableWidgetItem,
    QDialog)` can not run and the error information as follows 
> Traceback (most recent call last):
  File "<ipython-input-29-bde02c373f5b>", line 1, in <module>
    from PyQt5.QtWidgets import (
ImportError: dlopen(/Users/yan/anaconda/envs/face_identification_tpe/lib/python3.5/site-packages/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/./libicui18n.56.dylib
  Referenced from: /Users/yan/anaconda/envs/face_identification_tpe/lib/libQt5Core.5.5.0.dylib
  Reason: image not found

**Comment by ccordoba12** [comment]
`nmearl` is not the default channel. To install PyQt5 with conda you simply need to run

    conda install pyqt

**Comment by Aspirinkb** [comment]
@ccordoba12 I see, but the official channel does not support PyQt5. `conda install pyqt` installs pyqt 4.11.4...

**Comment by Aspirinkb** [comment]
@ccordoba12 Oh, thank you. I had pyqt 4.11.4 installed, so I update it.

**Comment by ccordoba12** [comment]
:+1:

**Comment by Siecje** [comment]
There is no conda package for the newest PyQt5.

> It might be worth you updating the report to say that the bug is not specific to PyQt5 and affects all extension modules that rely on PEP 384.
> https://www.riverbankcomputing.com/pipermail/pyqt/2017-February/038833.html

**Comment by ccordoba12** [comment]
> There is no conda package for the newest PyQt5.

We know there isn't. The reason is we need to support Python 2 on Windows and that's impossible to do for Qt 5.7 and newer versions.

**Comment by ccordoba12** [comment]
@mingwandroid, do you understand the implications of not having `python3.dll` on Windows? Can we provide it?

**Comment by mingwandroid** [comment]
Seems like we're breaking PEP 384 by not having it.

I expect we could easily provide it yes; taking a look now.

**Comment by rausm** [comment]
As a temporary workaround, python3.dll from WinPython works for me (Python 3.6, x64).

At least latest WinPython (2017/4/1) has it (maybe even the 2017/01/28, i think the older ones didn't have it).

Should cover at least Python 3.5 & 3.6, both 32 & 64bit

**Comment by Shaanraza** [comment]
By adding python3.dll from an installer from python.org to the Anaconda install directory (same place as python35.dll), PyQt5 works.

Installing using conda install qyqt does not fix the issue.

**Comment by scw** [comment]
The conda packages for Python from the last six months all include `python3.dll`. I think this issue can safely be closed.

**Comment by mingwandroid** [comment]
Thanks @scw.

**Comment by liudenaxietian** [comment]
after install anaconda with python 3.7.3 (contain python3.dll),when execute"from PyQt5 import QtCore",it will show "DLL load fail" error,can anyone  who can tell me why?

**Comment by rausm** [comment]
> after install anaconda with python <whatever> (contain python3.dll),when execute"from PyQt5 import QtCore",it will show "DLL load fail" error,can anyone who can tell me why?

when having troubles with missing dependencies, grab http://dependencywalker.com/ and have a blast ;-)
