### ISSUE TITLE
Spyder / qtawesome issue.

### ISSUE THREAD

**Issue by mingwandroid** [ContinuumIO/anaconda-issues#1395]
Hey Carlos,

I was wondering if you could cast your eyes over this issue reported on the Anaconda - Public Google Group:

From https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/E7lx8rA6xwQ

The final resolution was:

> Hello,
> 
> had the same issues with both Anaconda 4.2 32-bit and 64-bit editions. Resetting Spyder didn't helped either. But I finally made it work. Here is what I did:
> 
> 1. go to Anaconda's Environments page;
> 2. click on "root" or whatever environment you use;
> 3. search in the installed packages for "spyder";
> 4. in the "Version" column you will see the arrow, which means there is a newer version of the package. Click on it, Press Apply. That will update Spyder;
> 5. wait until it updates spyder, then kill all Python processes in Task Manager. You can use PowerShell code: "Get-Process | where ProcessName -eq 'python' | %{ kill $_}"
> 6. run cmd.exe, type "spyder --reset"
> 7. run Spyder
> 
> Hopefully this will help you.
> 
> Regards,
> Shyngys

Is this a known issue? Is there anything that can be done to detect the issue and fix whatever it is in the config that is corrupted and causing the need for `spyder --reset`?

**Comment by ccordoba12** [comment]
Hey Ray, yep, this error is known to us. It was fixed in Spyder 3.1 and QtAwesome 0.4.1. A simple

    conda update spyder

should fix it because we added `qtawesome >=0.4.1` to the 3.1 Spyder recipe.

----

*Note*: This problem only happens on Windows 10 because that OS prevents reading/loading fonts not installed in the system and Spyder is using FontAwesome for its icon set through qtawesome.

**Comment by mingwandroid** [comment]
Thanks Carlos,

So `spyder --reset` was unnecessary here?

**Comment by ccordoba12** [comment]
Yes, it shouldn't be necessary. We take care of showing a message saying that we have to use our old icon set if an error is found while reading qtawesome fonts, and we set the config option accordingly.

**Comment by mingwandroid** [comment]
Great, thanks Carlos.
