### ISSUE TITLE
dlib in the  defaults channel

### ISSUE THREAD

**Issue by tiagofrepereira2012** [ContinuumIO/anaconda-issues#1396]
Hi, 

I saw that dlib is available in `conda-forge`, is it possible to have it in the `defaults` channel?

Thanks

**Comment by 183amir** [comment]
I support this request. Dlib is an excellent C++ library with a few dependencies and Python bindings. Thank You for considering this addition.

**Comment by tiagofrepereira2012** [comment]
Is there anything blocking this package to not be part of the defaults channel?

thanks

**Comment by tiagofrepereira2012** [comment]
Any news on this one?

Thanks for any feedback

**Comment by tiagofrepereira2012** [comment]
I've seen that `dlib` 19.17 is already part of the defaults.

Thanks for pushing this.

Would be nice to have the last release (19.21), but I'll open another issue for this.

Thanks again
