### ISSUE TITLE
program shutdown on 1st launch after installation on mac

### ISSUE THREAD

**Issue by ju-me** [ContinuumIO/anaconda-issues#1398]
hey there,
anaconda shuts down on 1st launch after installation on os x el capitan during initializing sequence, i tried reinstallation several times, no error message, no further use possible. any ideas anyone? would be much appreciated 
thx

**Comment by goanpeca** [comment]
@ju-me what version of anaconda are you using?

If you go to the terminal and type

`$ anaconda-navigator`

What is the result?

**Comment by ju-me** [comment]
command not found,
so it seems installation hasn't worked

**Comment by goanpeca** [comment]
@ju-me could you please try again, and make sure you install for the current user (and not for all users?)

**Comment by ju-me** [comment]
thouhgt of that too and have tried that 2 times already, selecting the 'just for me field', try one more time now after deleting every connected file

**Comment by goanpeca** [comment]
Are you using the .pkg or the .sh file?

**Comment by ju-me** [comment]
.pkg

**Comment by goanpeca** [comment]
If you type

```
$ conda info
$ conda list
```

On the command prompt?

**Comment by ju-me** [comment]
after installation now..
both commands turn out 'command not found'

**Comment by goanpeca** [comment]
So it seems the path is not correctly set

You can open ~/.bash_profile file and include the following line

```
export PATH="/Users/<YOUR USER NAME>/<ANACONDA FOLDER>/bin:$PATH"
```
Anaconda folder can be anaconda, or maybe anaconda3?

**Comment by ju-me** [comment]
tried that, deleted the preexisting entry from the wrond installation, did it 2 times over
is there info stored anywhere else, that might create a conflict with reinstalling?

**Comment by goanpeca** [comment]
@ilanschnell

**Comment by tlk** [comment]
@ju-me Sorry if this is obvious to you, but just double checking - when goanpeca asks you to type in commands, do you include the '$' sign? That symbol is not to be copy-pasted :-)

**Comment by slowbeatz** [comment]
Hi!
Exactly same issue: I've installed anaconda via command line, installation seemed to complete, but after I've restarted terminal and tried 
$ conda info
$ conda list
Terminal had returned command not found


Please help =)

**Comment by goanpeca** [comment]
@mingwandroid do you have some thoughts here?

**Comment by slowbeatz** [comment]
Hi,

my problem was that the path was not set correctly, as it mentioned in post above. I've changed the path and problem had gone )

Thnks @goanpeca
