### ISSUE TITLE
Anaconda Navigator Crashes After Launch

### ISSUE THREAD

**Issue by oharb** [ContinuumIO/anaconda-issues#1401]
Hi friends,

I tried installing anaconda via pkg and sh installers and with both installations of the Anaconda Navigator the app crashes every time I try to launch it. The logo will display in the center of my screen and it will say "initializing" and will then crash. Happy to provide any helpful information from terminal and thanks in advance for the help!

Running OS X Sierra 10.12.2 and Anaconda 4.3.0 for Python 3.6

**Comment by goanpeca** [comment]
Could you try going to the command prompt ant typing

`$ sudo rm -rf ~/.continuum` 

And try again?

**Comment by mwjun** [comment]
Thank you! It works. @goanpeca

**Comment by abhishekchhabra259** [comment]
Hi..I am facing the same problem with a mac machine. Could you please suggest a solution.

**Comment by joshgraves3** [comment]
I am also facing the crash issue on a Mac. Application will load and right when the GUI opens up, it crashes.

**Comment by derrickstaten** [comment]
Same issue. 

My system info if it helps.
<img width="249" alt="screen shot 2017-09-04 at 10 03 37 am" src="https://user-images.githubusercontent.com/5950251/30034767-5e5bfc30-9158-11e7-8c87-9d0aa35bdd94.png">

**Comment by namshub3** [comment]
Getting same crash on macOS.

When launching anaconda-navigator in Terminal:

Traceback (most recent call last):
  File "/Users/rory/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6

<img width="259" alt="screen shot 2017-09-05 at 01 42 26" src="https://user-images.githubusercontent.com/4661056/30040808-dd3a76f2-91db-11e7-9000-236364ed7e32.png">

**Comment by eloiup** [comment]
same issue. windows. rm -rf ~/.continuum did not help.

**Comment by Arri** [comment]
Thanks. That worked on Windows 7.

**Comment by Nirmalkusahoo** [comment]
I faced the same issue but Windows.
So I ran below command in cmd. It resolved my issue.

**_conda remove anaconda-navigator
conda install anaconda-navigator_**

**Comment by Supermariaworld** [comment]
@Nirmalkusahoo it worked! Cheers

**Comment by rishabhkgp** [comment]
First navigate to the folder where anaconda is installed. (Works for MAC as well) 
cd anaconda 
conda remove anaconda-navigator
conda install anaconda-navigator

Launch Anaconda Navigator now :)

**Comment by derrickstaten** [comment]
Thanks @Nirmalkusahoo and @rishabhkgp. I ended up removing and installing via the command line script.

**Comment by Faazie** [comment]
Thanks, @Nirmalkusahoo.

**Comment by flicknewb** [comment]
thanks @rishabhkgp worked like a charm.

**Comment by lf19902001** [comment]
Thanks a lot! @Nirmalkusahoo

**Comment by Shubham1605** [comment]
@Nirmalkusahoo thanks buddy.It resolved my issue

**Comment by msadv** [comment]
Thanks @rishabhkgp . very helpful

**Comment by ykelanemer** [comment]
Thanks a lot! @Nirmalkusahoo

**Comment by architjen** [comment]
Thanks, @Nirmalkusahoo. 
And guys this is gold, it almost solves every problem.
conda remove anaconda-navigator
conda install anaconda-navigator

**Comment by anjsudh** [comment]
Thanks @eloiup It worked !

**Comment by lavanyakumarallu** [comment]
I'm facing the same problem but the problem is the file path in anaconda prompt is different from the path I installed

**Comment by lavanyakumarallu** [comment]
help me fixing it...
