### ISSUE TITLE
R ICU dependency conflict not detected

### ISSUE THREAD

**Issue by alimanfoo** [ContinuumIO/anaconda-issues#1403]
As described [here](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/myBjZaaAoDI), if a user installs rpy2 from the r channel, then installs any software from conda-forge that depends on ICU, then ICU will get upgraded to version 56 and r-base will get installed from conda-forge. After this, some parts of R run fine, but others generate an error regarding a missing ICU 54 library file (e.g., running the rpy2 test suite). This suggests that there is a dependency conflict somewhere that is not being caught by the conda installer, which ideally should raise a version conflict message rather than allow upgrade of ICU.

**Comment by alimanfoo** [comment]
Just to say the bigger issue here is to enable both rpy2 and software from conda-forge to be installed safely into the same conda environment. But I realise that is tricky right now so I am comfortable with whatever resolution is appropriate for this issue right now.

**Comment by sebastian-luna-valero** [comment]
Hello,

Having the same issue here:
https://travis-ci.org/CGATOxford/cgat/builds/240711411#L1893

when upgrading from R-3.3.1 to R-3.3.2

Best regards,
Sebastian

**Comment by mingwandroid** [comment]
The only possible resolution, while `conda-defaults` and `coda-forge` remain binary incompatible is not to mix them in the same environment (you can often get away with mixing pure-Python things though).

**Comment by sebastian-luna-valero** [comment]
Many thanks @mingwandroid
