### ISSUE TITLE
Cannot downgrade Spyder in Anaconda 4.3 due to conflict with Python 3.6

### ISSUE THREAD

**Issue by pbentkowski** [ContinuumIO/anaconda-issues#1407]
I wanted to downgrade Spyder in Anaconda Navigator (anaconda 4.3) from 3.1.x to 3.0.2 and I got this:

```
The following specifications were found to be in conflict:
- python 3.6*
- spyder ==3.0.2 -> python 2.7* -> openssl 1.0.1*
Use "conda info " to see the dependencies for each package.
```

Anaconda 4.3 on *ubuntu 14.04, 64 bit

**Comment by goanpeca** [comment]
There is not a version of spyder 3.0.2 available for python 3.6

**Comment by pbentkowski** [comment]
Yes, I know. This is what the error is saying. Removing the downgrade options from the menu would be reasonable ;-) 
 Cheers.

**Comment by ccordoba12** [comment]
Closing then.

**Comment by pbentkowski** [comment]
Yup. Thanks for quick response.
