### ISSUE TITLE
basemap does not work on Centos 6

### ISSUE THREAD

**Issue by ilanschnell** [ContinuumIO/anaconda-issues#141]
From: Al Danial al@danial.org
Date: Tue, Jun 24, 2014 at 7:14 PM

Hello.  This program

```
#!/usr/bin/env python
from mpl_toolkits.basemap import Basemap
m = Basemap(width=5423141.4794921875      ,
            height=2088918.3044433594     ,
            resolution='h'                ,
            projection='stere'            ,
            lat_ts=40.015995025634766     ,
            lat_0=40.015995025634766      ,
            lon_0=257.02978515625         )
```

causes a seg fault on this platform:
  Anaconda 2.0.1 (64-bit)
  Red Hat Enterprise Linux Server release 6.5 (Santiago)
  Linux 2.6.32-431.11.2.el6.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

However the program runs fine using
  Anaconda 1.8 (64-bit) and
  Red Hat Enterprise Linux Server release 5.4 (Tikanga)
  Linux 2.6.18-308.16.1.el5 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by csoja** [comment]
closing - very old issue.
