### ISSUE TITLE
Windows (x86_64) install consistently fails as of 4.3.0 (claiming non-ascii characters in path)

### ISSUE THREAD

**Issue by luiscrouch** [ContinuumIO/anaconda-issues#1410]
Windows 7
Python 2.7 version
Anaconda 4.3.0

Message from error window:
> Error: Due to incompatibility with several Python libraries, path cannot contain non-ascii characters (special characters or diacritics). Please choose a different install path.

Happens regardless of installing for "Just Me" or "All Users".

Desired path is:
`C:\ProgramData\Anaconda2`
which, clearly, contains no non-ascii characters.

4.2.0 installer works fine on same machine, so easy to work around (can update via conda once installed).

![image](https://cloud.githubusercontent.com/assets/25516431/22570226/890ec82e-e968-11e6-8a8b-0537e6987bb0.png)

**Comment by mingwandroid** [comment]
I have no idea about this, @msarahan, any clues?

@luiscrouch, if you open a command prompt and type `chcp` what does it report?

**Comment by msarahan** [comment]
Any more specific info @luiscrouch?  What edition of Windows 7 (Home/Pro/Enterprise?)  What is the default language setting on the PC?  Are there any internationalization settings on the computer?

**Comment by msarahan** [comment]
Also, is the computer current on Windows updates?

**Comment by luiscrouch** [comment]
@mingwandroid: `chcp` prints `Active` code page: 437`

@msarahan: It's a work machine, not my own, so managed by IT. Additional info:

Windows 7 Enterprise Version 6.1.7601 Service Pack 1 Build 7601
Default language is English (United States)

**Comment by msarahan** [comment]
Thanks for the info.  I have been unable to reproduce this failure, unfortunately.  I have tried with a Windows 7 VM:

OS Name:                   Microsoft Windows 7 Professional N
OS Version:                6.1.7601 Service Pack 1 Build 7601

For some strange reason, my VM was initially set to English (Denmark).  Code page was 850.  I set it to English (US), rebooted, and now have code page 437.  The installer worked fine for me under both - Just Me and All Users, both pointed at C:\ProgramData\Anaconda2

That path is one that you've typed in manually, or you've just taken the default?  Might you have pasted it in from somewhere?  Do you have write permissions to that folder?  Permissions errors really should raise different errors, but I'm really lost on this one.  Do you have the ability to elevate permissions (are you an admin on your machine?)

**Comment by mingwandroid** [comment]
I also cannot reproduce this problem.

**Comment by luiscrouch** [comment]
@msarahan No problem if you can't replicate. Like I said, I am able to work around this issue. Just thought I'd submit it in case others were having the same problem.

As for questions: tried both manual typing and taking default, neither worked. Permission issue is a good question. I have admin rights and should have been operating at elevated levels (installing for all users generates a UAC prompt from Windows to elevate). I didn't try running the installer as administrator from scratch, but can attempt it.

**Comment by DheerajAgarwal** [comment]
I just had the same issue.

Win7 Enterprise SP1. 
Python3.5, Anaconda 4.3.0.1

I tried it both for individual vs all user options. Also tried browsing and typing the path. Same issue. Downloaded couple of hours ago. Anaconda 4.2 worked fine but is now uninstalled :(

**Comment by msarahan** [comment]
If anyone encounters this on a VM or has any tips for reproducing this, please let us know ASAP.  We would really like to fix this, but have no idea where to start right now, since we are unable to reproduce the problem locally.

**Comment by mingwandroid** [comment]
@csoja, I would like to see if my CP_ACP thing fixes this issue for the reporters here, but we'd need to provide a release (of Miniconda?) with that in so that people here can test it as we cannot reproduce this despite a lot of attempts.

**Comment by csoja** [comment]
@mingwandroid good idea.  Can you work with @ilanschnell to create one and put it in an accessible location separate from where we generally keep miniconda installers?

**Comment by nathanhere** [comment]
i'm getting this error for Anaconda 4.3.0 install as well. Python 3.6 64x Windows 10

**Comment by mingwandroid** [comment]
@kalefranz, @csoja, @ilanschnell, what is the plan here?

**Comment by jerodestapa** [comment]
Windows 7 Enterprise - Service Pack 1 (32 bit)
Python 3.6
Anaconda 4.3.0.1

I am also getting this error, but with the 32 bit version.

**Comment by Rblivingstone** [comment]
I am also getting this issue. Using default path.

**Comment by ksrteja** [comment]
Same issue.

On Windows 10
Python 2.7
64 bit version of Anaconda 4.3.0

**Comment by kalefranz** [comment]
I don't know if it's related to the install process or not, but there's a fix pending for the next patch release regarding unicode in conda.

https://github.com/conda/conda/pull/4585

**Comment by mingwandroid** [comment]
This is to do with the NSIS installer. I have a fix ready to go, but it also requires either: https://github.com/conda/conda/pull/4558 or else anaconda PR#708 and then building test installers for the reporters since we've not been able to reproduce it.

I'd really appreciate it if we could make some progress on this.

**Comment by kalefranz** [comment]
I'd prefer building the test package to merging the conda PR just yet.  But that's easy for me to say.  I just always get really nervous anytime we touch anything in activate/deactivate.  Just so much pain there.

But now I've just discussed with @ilanschnell.  He seems to be fine with it.  I'd like to release conda 4.3.12 into canary today or tomorrow, and then have it into defaults 48 hours later.

@csoja What are your thoughts on how to proceed?  I'll click the merge button on https://github.com/conda/conda/pull/4558 for 4.3.12 if that's the way you think we should go.

**Comment by mingwandroid** [comment]
I don't mind which way we go.

**Comment by kalefranz** [comment]
So at @csoja just indicated the preferred path forward would be to make a new Miniconda installer with the PR#708 patch, and then have that uploaded to a special place somewhere and tested separately.  @csoja please correct anything I've misstated.

**Comment by mingwandroid** [comment]
Sounds good to me.

**Comment by fenpark15** [comment]
I am also having this issue with 4.3.0.1, Python 3.6.   It occurs on 2 different computers, both Windows 7 Enterprise, 64-bit.

**Comment by Templetona1** [comment]
has a new installer been created on Anaconda site to address this issue ?

**Comment by mingwandroid** [comment]
Not yet.

**Comment by mingwandroid** [comment]
@luiscrouch, @Templetona1, @Rblivingstone, @jerodestapa, @nathanhere, @DheerajAgarwal, would it be possible for you to try: https://repo.continuum.io/pkgs/misc/preview/Miniconda3-4.3.13-Windows-x86_64.exe (64-bit) or https://repo.continuum.io/pkgs/misc/preview/Miniconda3-4.3.13-Windows-x86.exe (32-bit).

It has fixes for both the accented characters (you can use those in your native code-page), changes to the detection of non-ascii and also fixes for install locations longer than 30 characters (though 4.3.0.1 already had that one).

It a Miniconda release only at present, though you can just `conda install anaconda` afterwards to make it a full Anaconda and only the Python3 version works well (in my testing) at present.

Many thanks for your patience.

**Comment by Templetona1** [comment]
Installed 32 bit worked for me   thanks

**Comment by duartecordeiro** [comment]
Windows 10 Enterprise version 1511
Tried to install Anaconda2-4.3.0.1-Windows-x86_64 failed with the error mentioned above.
Worked with Anaconda2-4.3.1-Windows-x86_64 in the preview folder.

**Comment by mingwandroid** [comment]
Thank you for the feedback @duartecordeiro.

**Comment by kamilk** [comment]
@mingwandroid I'm experiencing the same issue described here and the packages you provided earlier have worked for me, thanks! Would it be possible to release a patched version or provide a Python 2.7 version including the fix?

I wonder why this issue is not being prioritised higher, judging from the age of this report the software has been impossible to install on Windows for the past 3 months!

**Comment by mingwandroid** [comment]
> judging from the age of this report the software has been impossible to install on Windows for the past 3 months

Blatantly this is not the case. As stated, we were never able to reproduce the issue despite many attempts.

Anyway, the chcp thing has been in all released Anacondas since 4.4.
