### ISSUE TITLE
Python hard crashes on windows 64bit 3.5 & 3.6 for specific scipy function

### ISSUE THREAD

**Issue by chohner** [ContinuumIO/anaconda-issues#1415]
Hello!

As mentioned over here https://github.com/scipy/scipy/issues/7002, the scipy binaries from conda hard crash Python when calling any spherical bessel function with a complex argument. This only happens on Windows 64Bit 3.5 and 3.6. All 32 Bit installs as well as 64 Bit Python 3.4 are fine, as are OSX and Unix builds.

This seems to be an anaconda problem as the functions work fine when replacing numpy/mkl/scipy with the binaries from Gohlke.

To test this, you can run the following snippet and use any of  `spherical_jn`, `spherical_yn`, `spherical_in`, `spherical_kn`, as well as derivative `False` and `True`.

```
from scipy import special
special.spherical_jn(1, 1+1j, derivative=True)
```

**Comment by chohner** [comment]
Any news on this?

**Comment by DavidPowell** [comment]
I have experienced the same issue under Python 3.5 on Windows x64. 

I can also confirm that the problem does not occur under Python 2.7 on Windows x64, nor under Python 3.5 on Linux x64.
