### ISSUE TITLE
issue with dlib which can not be imported

### ISSUE THREAD

**Issue by Aspirinkb** [ContinuumIO/anaconda-issues#1417]
env: Mac os, Anaconda 4.2, Python 3.5, dlib 19.0
Something is wrong with dlib.so when I import dlib in python.
>\>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/yan/anaconda/envs/face_identification_tpe/lib/python3.5/site-packages/dlib.so, 2): Symbol not found: __ZN5boost6python7objects15function_objectERKNS1_11py_functionERKNSt3__14pairIPKNS0_6detail7keywordESA_EE
  Referenced from: /Users/yan/anaconda/envs/face_identification_tpe/lib/python3.5/site-packages/dlib.so
  Expected in: /Users/yan/anaconda/envs/face_identification_tpe/lib/python3.5/site-packages/../..//libboost_python.dylib
 in /Users/yan/anaconda/envs/face_identification_tpe/lib/python3.5/site-packages/dlib.so

**Comment by nehaljwani** [comment]
Related https://github.com/conda-forge/dlib-feedstock/issues/5

**Comment by nehaljwani** [comment]
Closing, as the packaging problem is related to the conda-forge channel.
