### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by adalau** [ContinuumIO/anaconda-issues#1419]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - bottleneck
  - opencv ==2.4.8
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.3.9', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.4.0;Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@adalau you have a very old version of navigator. Please update to the latest version (1.4.3)
