### ISSUE TITLE
Jupiter notebook not sowing up after clicking a launch buttun on Anaconda Nvigator. 

### ISSUE THREAD

**Issue by nekokagayaku** [ContinuumIO/anaconda-issues#1421]
I have installed Anaconda3, today. But I don't  know how to visit the dashboad, please let me know about it.
Best regards,
Kazuki.

**Comment by goanpeca** [comment]
Hi @nekokagayaku 

Could you open the terminal ant type

`conda info`

and paste the results here?

Thanks

**Comment by nekokagayaku** [comment]
Hi @goanpeca 

Thanks for your information.
Finally, I'm getting on the dashboad.

Thanks
