### ISSUE TITLE
Anaconda New Install - Launcher not working

### ISSUE THREAD

**Issue by vesummers** [ContinuumIO/anaconda-issues#1422]
After reinstalling the latest version of Anaconda, the launchers no longer work. I accepted the defaults, in particular opting for single user usage. My user folder contains a space in its name. The install kicked up an alert about this but proceeded with installation. Might this be the problem?

**Comment by mingwandroid** [comment]
Which version did you install? What installation location did you use?

Can you check to see if you have a qt.conf file in `<installation_location>\Library\bin` and paste the contents here please?

**Comment by vesummers** [comment]
Thank you very much for responding. I installed version 4.3.0, for Windows. I installed user the my user folder (my first and last name).

[Paths] 
Prefix = C:/Users/Vincent Summers/Anaconda3/Library 
Binaries = C:/Users/Vincent Summers/Anaconda3/Library/bin 
Libraries = C:/Users/Vincent Summers/Anaconda3/Library/lib 
Headers = C:/Users/Vincent Summers/Anaconda3/Library/include/qt

**Comment by mingwandroid** [comment]
OK, you've run into the bug that was fixed in 4.3.0.1 which prevents installing to a location made up of more than 30 characters.

Spaces are not recommended but *shouldn't* prevent `Anaconda Navigator` from launching. I'd be interested to know how 4.3.0.1 works for you.

**Comment by vesummers** [comment]
The navigator does invoke but the launchers don't work. Is there a solution?

**Comment by mingwandroid** [comment]
I think you need to use a location without spaces then, sorry. I'll bring it up with the `Navigator` team.

**Comment by vesummers** [comment]
Thank you for your help.

**Comment by goanpeca** [comment]
@vesummers just to double check, what you mean by launchers is:

Once you open navigator, the applications on the home screen no longer launch?

Or do you mean the start menu?

**Comment by vesummers** [comment]
Now, after reinstalling, the launcher buttons (Python, Jupyter, Spyder...) no longer work.

**Comment by goanpeca** [comment]
@vesummers ok, I am fixing the issue but a hotfix release will only be available tomorrow. Could you install in a path with no spaces?

**Comment by vesummers** [comment]
Wow. Tomorrow would be spectacular! I did consider uninstalling and reinstalling to path without spaces but was not sure this matter was the culprit, especially since it worked before. I even researched, to no avail, renaming the user folder. Please forgive my ignorance, how would I go about applying a hotfix and know when it is available, please?

**Comment by goanpeca** [comment]
Navigator 1.4.4 will be released including this fix very likely this week.

**Comment by vesummers** [comment]
Thank you very much. I will wait until then. 
Grateful...

**Comment by vesummers** [comment]
Hello,
Has this fix been released yet?
Thanks...

**Comment by arian-siddiqi** [comment]
I'm having issues when trying to start Navigator on macOS Sierra 10.12.3 on a 2016 Macbook Pro. 
I downloaded Anaconda but when I click on the launcher application it doesn't open. The navigator starts to initialise and abruptly crashes and the navigator disappears. I regret uninstalling my previous version of Anaconda as Spyder needed to update, now, I think should have put up with annoying update pop up. Any help would be much appreciated.

**Comment by goanpeca** [comment]
There is version 1.4.3 available
