### ISSUE TITLE
Need nb_conda for Python 3.6

### ISSUE THREAD

**Issue by DavidMertz** [ContinuumIO/anaconda-issues#1423]
(moved from https://github.com/conda/conda/issues/4539#issuecomment-277586319)

There currently does not seem to be support for `nb_conda` that is compatible with Python 3.6.  This makes it cumbersome to work with Py36 environments that use Jupyter.  Or in Jupyter when you need to choose an environment (whichever way you want to look at it).

```bash
532-Downloads % conda create -n nb36 python=3.6 jupyter nb_conda
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by schlichtanders** [comment]
same here,
this also is the case when installing ``nb_conda``, ``nbpresent`` and the like from the anaconda-nb-extensions channel, however the UnsatifiableError is slightly different:
```
conda install -c anaconda-nb-extensions nbpresent
Fetching package metadata .....................
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - nbpresent -> nb_config_manager -> python 3.4*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jingw222** [comment]
Apparently, I'm not alone with this issue...

**Comment by fmkoba** [comment]
Getting this same error, thanks in advance guys.

**Comment by martindurant** [comment]
As far as I understand, https://github.com/conda-forge/nb_conda-feedstock/pull/4 should build a py36 conda-forge package automatically.

**Comment by DavidMertz** [comment]
conda-forge doesn't help out Anaconda Repo customers who mirror the main
repo but not channels (and have firewalls).

On Feb 24, 2017 3:58 PM, "Martin Durant" <notifications@github.com> wrote:

As far as I understand, conda-forge/nb_conda-feedstock#4
<https://github.com/conda-forge/nb_conda-feedstock/pull/4> should build a
py36 conda-forge package automatically.

—
Yoou are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ContinuumIO/anaconda-issues/issues/1423#issuecomment-282402649>,
or mute the thread

**Comment by akku005** [comment]
UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
but when i created environment supporting python 2 then installed nb_conda then it was working..

**Comment by Synergist** [comment]
I'm joining the bandwagon...getting the same error. Thanks in advance.

**Comment by DavidMertz** [comment]
I was traveling and didn't have a chance to verify conda-forge, but nb_conda is **also** not there for the latest Python/Anaconda:

```bash
505-tmp % conda install nb_conda -c conda-forge
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> python 3.5* -> sqlite 3.9.*
  - nb_conda -> python 3.5* -> xz 5.0.*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by DavidMertz** [comment]
If I were only trying for Python 3.5 I guess this would succeed using conda-forge, but that's not what we need.  We need it in the main channel, and also for 3.6.

**Comment by bollard** [comment]
It seems rather cumbersome to me that the four nb packages (nbpresent, nb_anacondacloud, nb_conda, nb_conda_kernels) depend on one another as we have to wait for all four packages to be updated in order to install the one we may want. As of today, I believe it is just nb_anacondacloud (a package I have no intention of using) which has yet to be updated, but stops me using nb_conda.

**Comment by ajit555** [comment]
I am new to Anaconda. It is on Windows 10 with latest Anaconda 64 bit install. 

`
C:\Users\Ajit>conda install nb_conda
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

C:\Users\Ajit>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Ajit\AppData\Local\conda\conda\envs
                          C:\Users\Ajit\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Ajit\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Ajit\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393
`

**Comment by damianavila** [comment]
Packages will be available in the next few week. I will let you know when it is done. Thanks.

**Comment by znmeb** [comment]
does it work for 3.5? If so, I'll just drop back to Miniconda 3.5

**Comment by durgeshm** [comment]
FWIW, I am creating a 3.5 environment and it works, i.e. it allows me to switch between different environment kernels. e.g.

`conda create -n p35 python=3.5 numpy matplotlib nb_conda jupyter`

**Comment by jcpan1977** [comment]
Same here....

UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by yoavram** [comment]
+1

**Comment by sinhavartika** [comment]
@DavidMertz I am getting the same error. 
with `conda install nb_conda`
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7*
  - python 3.6*

```
with `conda install -c conda-forge nb_conda`
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> python 3.5* -> sqlite 3.9.*
  - nb_conda -> python 3.5* -> xz 5.0.*
  - python 3.6*

```
Is there any temporary work around for this?

**Comment by trmanish** [comment]
Create conda env using python 3.5 and it works fine then.

**Comment by DavidMertz** [comment]
@trmanish: Yes, that is **exactly** what the bug reports! There's no support for the latest Python. As indicated in all the above comments, there is support for older Pythons.

**Comment by stolsvik** [comment]
It's kinda strange that the current Anaconda-package for python 3.6 makes you default stuck in this situation. I just installed it, and instantly hit this road block when trying to use jupyter with environments (which everybody tells you to use..)

**Comment by damianavila** [comment]
All, finally I have some time to work on this. `nb_conda 2.2.0` (latest release) is available through conda-forge, including the solicited py36 support.

**Comment by mingwandroid** [comment]
@damianavila, putting a package on `conda-forge` is not a fix for this. `conda-forge` and the packages from the `Anaconda Distribution` are not binary compatible.

**Comment by damianavila** [comment]
> @damianavila, putting a package on conda-forge is not a fix for this. conda-forge and the packages from the Anaconda Distribution are not binary compatible.

This extension are no longer shipped with Anaconda by default... so... do you want to have it available from repo.cio before closing this issue? @mingwandroid @csoja

**Comment by mingwandroid** [comment]
Yes. bugs in `anaconda-issues` can never be fixed by packages in `conda-forge`.

**Comment by damianavila** [comment]
> Yes. bugs in anaconda-issues can never be fixed by packages in conda-forge.

Fair enough... sorry for the premature closing. Let's figure out how we can ship the latest release into repo.cio as soon as you (or the team) have time availability.

**Comment by drorata** [comment]
I could install `nb_conda` from `conda-forge`.

**Comment by QCaudron** [comment]
I also succeeded in installing `nb_conda` from `conda-forge`. This solves my immediate problem ( `jupyter notebook` was using a different IPython kernel, not the one provided by Anaconda ), but it would be fantastic to have this package in the main repo, and installed by default, given that Jupyter comes out of the box.

**Comment by oshribr** [comment]
Hi all, 
I bumped with this issue. 
I tried to install nb_conda & _nb_ext_conf but without success.

```
[oshri@analytics ~]$ conda install nb_conda 
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /data/anaconda:
#
nb_conda                  2.2.0                    py35_0    conda-forge
[oshri@analytics ~]$ conda install _nb_ext_conf 
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /data/anaconda:
#
_nb_ext_conf              0.3.0                    py35_0  
[oshri@analytics ~]$ conda install python=3.6
Fetching package metadata .........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by damianavila** [comment]
@oshribr just get it from conda-forge with `conda install -c conda-forge nb_conda`.

**Comment by oshribr** [comment]
@damianavila   ;-(
```
[oshri@analytics ~]$ conda install -c conda-forge nb_conda
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /data/anaconda:
#
nb_conda                  2.2.0                    py35_0    conda-forge
[oshri@analytics ~]$ conda install python=3.6
Fetching package metadata .........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.


[oshri@analytics ~]$ conda install python=3.6
Fetching package metadata .........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_config_manager -> python 2.7*|3.4*|3.5*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.


[oshri@analytics ~]$ conda install python=3.6
Fetching package metadata .........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_config_manager -> python 2.7*|3.4*|3.5*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by damianavila** [comment]
You have very old extensions there. Suggestion:

`conda create -n test python=3.6`

and then 

`source activate test`

and finally

`conda install -c conda-forge nb_conda`

If that works for you, then you should clean you root environments getting rid of the old extensions.

**Comment by mingwandroid** [comment]
Can we not just get this fixed in defaults? What's currently blocking it?

**Comment by ccordoba12** [comment]
I think nobody has had the time to create packages for 3.6.

**Comment by damianavila** [comment]
There are further complications, I will open an issue to describe them and discuss how we solve it properly.

**Comment by laserson** [comment]
How does one "clean" the root environment?

**Comment by damianavila** [comment]
>How does one "clean" the root environment?

In this case, essentially conda remove ANY extension from your environment. Plus, IF there is some leftover in the activation/enabling step, you probably need to audit some notebook config files (such as PREFIX/etc/jupyter/nbconfig/*).

**Comment by bollard** [comment]
Over three months since this issue was first opened... are we any closer to a new release in official channels?

**Comment by csoja** [comment]
Yes - it is high on the list after the upcoming Anaconda v4.4 release.  The way the notebook extensions were installed from defaults was different than from conda-forge.  The current defaults method requires all the extensions to be updated for Python 3.6 - and not all of them are.  We are looking into changing the approach for defaults so that the notebook extensions can be updated individually (including nb_conda).

**Comment by bollard** [comment]
@csoja, yes separating out the extensions would certainly be my preference ([see original comment](https://github.com/ContinuumIO/anaconda-issues/issues/1423#issuecomment-285373147))

**Comment by Odomontois** [comment]
What about nbpresent ?

**Comment by csoja** [comment]
@ilanschnell has updated the extensions in defaults now.  Please let us know if you continue to have issues with them.
