### ISSUE TITLE
Anaconda-Navigator.app fails to start due to ".continuum/anaconda-client: Permission denied"

### ISSUE THREAD

**Issue by Rossell9** [ContinuumIO/anaconda-issues#1426]
The navigator app won't open for me, it keeps saying that its initializing and then will crash. I sent the navigator file through terminal and it said that I didn't have permission to use it (PermissionError: [Errno 13] Permission denied: '/Users/ryanossell/.continuum/anaconda-client'). What should I do to solve this problem?

**Comment by goanpeca** [comment]
Go to your terminal and then type:

`sudo rm -rf ~/.continuum/`

And that should solve it

**Comment by trgrey** [comment]
Thanks! That fixed it.

**Comment by mirgrigory** [comment]
just want to point out that witnessed same problem - your advice fixed it
