### ISSUE TITLE
Various installation issues with PyQt5.Qtcore, QtCharts and QtDataVisualization

### ISSUE THREAD

**Issue by Rapidice** [ContinuumIO/anaconda-issues#1427]
I've been trying to install PyQtChart and PyQtDataVisualization in Anaconda environment, but the packages, besides being installed, throw a "ImportError: DLL....." when trying to import, for example `from PyQt5 import QtCore` , or `from PyQt5.QtChart import QChart`

Installing by using `pip install PyQt5 PyQtChart` shows no error log, but when trying to import, the "ImportError: DLL..." appears. Lib/site-packages is populated with the correct files. 

Installing with pip on a clean python 3.6 environment (not anaconda) works as intended, without import errors

Installing via the *.exe provided for PyQt5  in the Anaconda environment, gives the same import error.

**Comment by goanpeca** [comment]
@mingwandroid ?

**Comment by ccordoba12** [comment]
We don't support the PyQt5 pip packages because we provide our own (i.e. conda) packages instead.

Unfortunately, we don't have packages for PyQt 5.7 because it's not compatible with Python 2. However, someone else mentioned that you need to put python3.dll (I think) on the root of your environment to make the pip package work. But that's something we don't support nor we assure it will work.

**Comment by mingwandroid** [comment]
@Rapidice did you try to install from the conda package?

If so, please try to re-install Anaconda 4.3.0.1 from scratch and try again.

**Comment by ccordoba12** [comment]
@mingwandroid, PyQtChart and PyQtDataVisualization are only available for PyQt 5.7, if I'm not mistaken. That's the problem here.

**Comment by mingwandroid** [comment]
Ah, ok. Thanks @ccordoba12.

**Comment by Rapidice** [comment]
Thanks for the responses. Guess I'll have to stick to matplotlib for now. Are there any plans of including PyQt 5.7 in future relases?

**Comment by goanpeca** [comment]
@Rapidice 5.6 is long term support, so 5.7 or 5.8 are not currently under consideration

**Comment by ccordoba12** [comment]
Yep, 5.7 and newer releases are out of question for now, sorry.

**Comment by mrpraline** [comment]
Qt 5.9 LTS is a long term support release. Will this be integrated into anaconda?

**Comment by ccordoba12** [comment]
Yes, it will, but there's no time frame for that to happen yet.

**Comment by mathiasrabe** [comment]
It seems that Anaconda is now supporting Qt 5.9 but I still can't find QtCharts. Is it still not supported or did I miss anything?

**Comment by mingwandroid** [comment]
Please feel free to submit a PR to add support to https://github.com/AnacondaRecipes/qt-feedstock/tree/master or enquire at sales@anaconda.com if this is an Enterprise feature request.

**Comment by free-coffee** [comment]
If you run into this, you are probably running pyQt5.7 due to your packet manager. Try to install the [newest ](https://www.riverbankcomputing.com/software/pyqt/download5)one.

**Comment by free-coffee** [comment]
It's not quite obvious from the [documentation](https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html), but you need to install pyqtchart from pip for this.
