### ISSUE TITLE
Please, update virtualenv package form anaconda repository for python 3.6

### ISSUE THREAD

**Issue by anton-petrov** [ContinuumIO/anaconda-issues#1431]
At this moment it's impossible to install virtualenv using conda, for example by command:
`conda install -c anaconda virtualenv=15.1`
So, please, update virtualenv package to latest version, that supports Python 3.6
P.S.: Of course, there is an opportunity to install virtualenv using classic way => `pip install virtualenv`

**Comment by mingwandroid** [comment]
We released a new `virtualenv` package with patches to allow it to find the correct libpython. Please test and close this if it works for you.

**Comment by nehaljwani** [comment]
Closing as the package has already been made [available](https://anaconda.org/anaconda/virtualenv/files).

**Comment by ilanschnell** [comment]
Thanks for closing this and many other issues.
