### ISSUE TITLE
conda install six==1.10.0 installs wrong version

### ISSUE THREAD

**Issue by origarin** [ContinuumIO/anaconda-issues#1436]
When installing the latest version of **six** with conda:

`conda install six==1.10.0`

The installed version is **1.4.1**, both in `.../python2.7/site-packages/six.py` and when running `python -c 'import os,six;print(six.__version__)'`

Downgrading and upgrading to 1.10.0 with pip works (`pip install six==1.10.0`)

Probably error linking to the correct version

**Comment by nehaljwani** [comment]
```bash
(1436) [nwani@centos6x64 ~]$ conda create -yn 1436py27 python=2.7 six==1.10.0
(1436) [nwani@centos6x64 ~]$ source activate 1436py27
(1436py27) [nwani@centos6x64 ~]$ conda list six
# packages in environment at /home/nwani/m2/envs/1436py27:
#
six                       1.10.0                   py27_0
(1436py27) [nwani@centos6x64 ~]$ python -c "import six; print six.__version__"
1.10.0
```

Unable to reproduce this. Feel free to re-open if you can share the exact steps to reproduce.
