### ISSUE TITLE
Anaconda install process not robust to spaces in path

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#144]
_Issue by **[mattwescott](https://github.com/mattwescott)** from Friday Jul 11, 2014 at 15:25 GMT_
_Originally opened as https://github.com/conda/conda/issues/809_

---

The install scripts were in "/home/matt/usr/Anaconda Jul_2014"

It appears to be looking in Anaconda folder, and then attempts to open itself in the Jul_2014 folder.

Error:

> PREFIX=/home/matt/usr/anaconda
> tail: cannot open `/home/matt/usr/Anaconda' for reading: No such file or directory
> tail: cannot open`Jul_2014/Anaconda-2.0.1-Linux-x86_64.sh' for reading: No such file or directory
> WARNING: md5sum mismatch of tar archive
> expected: 0d987605e23d4c7140b31e490852dbf1
>      got: d41d8cd98f00b204e9800998ecf8427e  -
> tail: cannot open `/home/matt/usr/Anaconda' for reading: No such file or directory
> tail: cannot open`Jul_2014/Anaconda-2.0.1-Linux-x86_64.sh' for reading: No such file or directory
> tar: This does not look like a tar archive
> tar: Exiting with failure status due to previous errors
> ERROR: could not extract tar starting at line 452

**Comment by bjamesvERT** [comment]
Was this issue ever addressed? I just encountered a similar issue with Miniconda3-3.18.9-Linux-x86_64.sh when installing from a directory called "/var/lib/jenkins/workspace/warehouse-server dependency check" (i.e.: path includes 2x spaces)
```
../build/Miniconda3-3.18.9-Linux-x86_64.sh -b -p ../build/miniconda3
PREFIX=/var/lib/jenkins/workspace/warehouse-server dependency check/warehouse/build/miniconda3
installing: _cache-0.0-py35_x0 ...
tar (child): /var/lib/jenkins/workspace/warehouse-server: Cannot read: Is a directory
tar (child): At beginning of tape, quitting now
tar (child): Error is not recoverable: exiting now

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Invalid argument
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

It seems like tests may never have been put in place when #575 changes were made

**Comment by goanpeca** [comment]
Closing in favor of #716
