### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by medakasbi** [ContinuumIO/anaconda-issues#1441]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - beautiful-soup ==4.3.2 -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'language': 'fr_FR', 'os': 'Windows;10;10.0.10586;AMD64;AMD64 Family 16 Model 6 Stepping 3, AuthenticAMD', 'qt': '4.8.7', 'version': '1.2.1', 'platform': 'win-64', 'conda': '4.1.11', 'pyqt': '4.11.4', 'python': '3.5.2'}

**Comment by goanpeca** [comment]
@medakasbi conda cannot install the packages due to the problems it highlights. 

You could also update navigator to a more up to date version, by running on the **Anaconda Command Prompt**:

```
$ conda remove qt=4 pyqt=4
$ conda remove qt=5 pyqt=5
$ conda install anaconda-navigator
```

**Comment by medakasbi** [comment]
Thanks
