### ISSUE TITLE
Mac - OS Sierra - Navigator - Need to use "sudo anaconda-navigator"

### ISSUE THREAD

**Issue by projetmbc** [ContinuumIO/anaconda-issues#1442]
Hello. I must use `sudo anaconda-navigator` to launch the navigator. I can't no longer user simply the icon.

It is a known bug ?

**Comment by AlloriMD** [comment]
I noted this as well. If you open Anaconda Navigator via icon (macOS Sierra), the Anaconda logo shows for a few seconds, and then the program quits. There is no error message, and it doesn't appear to be a crash.

I can confirm the above report by @projetmbc that `sudo anaconda-navigator` is able to launch the application normally.

**Comment by dreamlegends** [comment]
i have the same issue. I solved this by adding the write permission to a file. here is how:
1. run anaconda-navigator in terminal. this will give you a error message which said Permission denied: '/Users/username/.continuum/anaconda-client/config.yaml'
2.go into that folder
3.ls -l it gives you the permission, you should see the permission rw-r-r, it need rw-rw-r
so i did sudo chmod 664 config.yaml which will fix the sudo problem.

**Comment by projetmbc** [comment]
Thanks for the fix.

PS: I had no message in my terminal when launching Anaconda-Navogator.

**Comment by goanpeca** [comment]
This issue can be solved in the terminal by doing

`rm -rf ~/.continuum/`

**Comment by projetmbc** [comment]
Thanks. That does the job. :-)


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French teacher of **math** in a high school **and **amateur **Python *
*developer*

2017-02-12 15:53 GMT+01:00 Gonzalo Peña-Castellanos <
notifications@github.com>:

**Comment by jxf413** [comment]
+1 on @goanpeca 's fix. Worked on my end.
