### ISSUE TITLE
Anaconda new version is having some issues in Mac

### ISSUE THREAD

**Issue by vibaskaran** [ContinuumIO/anaconda-issues#1443]
Greetings.

I am getting the following issues after the new installation on 2016 MAc book Pro, while starting the navigator. Please help.

MacBook-Pro:$ ./anaconda-navigator
Traceback (most recent call last):
  File "./anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
MacBook-Pro:bin $

**Comment by goanpeca** [comment]
@vibaskaran looks you are using an older verison of navigator. Could you type in the terminal

`conda info` and then `conda list` and paste the result here?

**Comment by vibaskaran** [comment]
Greetings. Sorry i did not see the reply.

conda info

Baskarans-MacBook-Pro:bin vbaskaran$ ./conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/vbaskaran/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/vbaskaran/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/vbaskaran/.condarc



           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

conda list

 packages in environment at //anaconda:
#
_license                  1.1                      py36_1
alabaster                 0.7.9                    py36_0
anaconda                  custom                   py36_0
anaconda-client           1.6.1                    py36_0
anaconda-navigator        1.4.3                    py36_0
appnope                   0.1.0                    py36_0
appscript                 1.0.1                    py36_0
astroid                   1.4.9                    py36_0
astropy                   1.3                 np111py36_0
babel                     2.3.4                    py36_0
backports                 1.0                      py36_0
beautifulsoup4            4.5.3                    py36_0
bitarray                  0.8.1                    py36_0
blaze                     0.10.1                   py36_0
bokeh                     0.12.4                   py36_0
boto                      2.45.0                   py36_0
bottleneck                1.2.0               np111py36_0
cffi                      1.9.1                    py36_0
chardet                   2.3.0                    py36_0
chest                     0.2.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.7                    py36_0
conda                     4.3.11                   py36_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py36_0
contextlib2               0.5.4                    py36_0
cryptography              1.7.1                    py36_0
curl                      7.52.1                        0
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.13.0                   py36_0
datashape                 0.5.4                    py36_0
decorator                 4.0.11                   py36_0
dill                      0.2.5                    py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_0
et_xmlfile                1.0.1                    py36_0
fastcache                 1.0.2                    py36_1
flask                     0.12                     py36_0
flask-cors                3.0.2                    py36_0
freetype                  2.5.5                         2
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
greenlet                  0.4.11                   py36_0
h5py                      2.6.0               np111py36_2
hdf5                      1.8.17                        1
heapdict                  1.0.0                    py36_1
icu                       54.1                          0
idna                      2.2                      py36_0
imagesize                 0.7.1                    py36_0
ipykernel                 4.5.2                    py36_0
ipython                   5.1.0                    py36_1
ipython_genutils          0.1.0                    py36_0
ipywidgets                5.2.2                    py36_1
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jbig                      2.1                           0
jdcal                     1.3                      py36_0
jedi                      0.9.0                    py36_1
jinja2                    2.9.4                    py36_0
jpeg                      9b                            0
jsonschema                2.5.1                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            4.4.0                    py36_0
jupyter_console           5.0.0                    py36_0
jupyter_core              4.2.1                    py36_0
launcher                  1.0.0                         3
lazy-object-proxy         1.2.2                    py36_0
libiconv                  1.14                          0
libpng                    1.6.27                        0
libtiff                   4.0.6                         3
libxml2                   2.9.4                         0
libxslt                   1.1.29                        0
llvmlite                  0.15.0                   py36_0
locket                    0.2.0                    py36_1
lxml                      3.7.2                    py36_0
markupsafe                0.23                     py36_2
matplotlib                2.0.0               np111py36_0
mistune                   0.7.3                    py36_1
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
multipledispatch          0.4.9                    py36_0
nbconvert                 4.2.0                    py36_0
nbformat                  4.2.0                    py36_0
networkx                  1.11                     py36_0
nltk                      3.2.2                    py36_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py36_1
notebook                  4.3.1                    py36_0
numba                     0.30.1              np111py36_0
numexpr                   2.6.1               np111py36_2
numpy                     1.11.3                   py36_0
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
openpyxl                  2.4.1                    py36_0
openssl                   1.0.2k                        0
pandas                    0.19.2              np111py36_1
partd                     0.3.7                    py36_0
path.py                   10.0                     py36_0
pathlib2                  2.2.0                    py36_0
patsy                     0.4.1                    py36_0
pep8                      1.7.0                    py36_0
pexpect                   4.2.1                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.0.0                    py36_0
pip                       9.0.1                    py36_1
ply                       3.10                     py36_0
prompt_toolkit            1.0.9                    py36_0
psutil                    5.1.3                    py36_0
ptyprocess                0.5.1                    py36_0
py                        1.4.32                   py36_0
pyasn1                    0.1.9                    py36_0
pycosat                   0.6.1                    py36_1
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_4
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.1.3                    py36_0
pylint                    1.6.4                    py36_1
pyopenssl                 16.2.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyqt                      5.6.0                    py36_2
pytables                  3.3.0               np111py36_0
pytest                    3.0.5                    py36_0
python                    3.6.0                         0
python-dateutil           2.6.0                    py36_0
python.app                1.2                      py36_4
pytz                      2016.10                  py36_0
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                         0
qtawesome                 0.4.4                    py36_0
qtconsole                 4.2.1                    py36_1
qtpy                      1.2.1                    py36_0
readline                  6.2                           2
redis                     3.2.0                         0
redis-py                  2.10.5                   py36_0
requests                  2.12.4                   py36_0
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.12.3              np111py36_1
scikit-learn              0.18.1              np111py36_1
scipy                     0.18.1              np111py36_1
seaborn                   0.7.1                    py36_0
setuptools                27.2.0                   py36_0
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
snowballstemmer           1.2.1                    py36_0
sockjs-tornado            1.0.3                    py36_0
sphinx                    1.5.1                    py36_0
spyder                    3.1.2                    py36_0
sqlalchemy                1.1.5                    py36_0
sqlite                    3.13.0                        0
statsmodels               0.6.1               np111py36_1
sympy                     1.0                      py36_0
terminado                 0.6                      py36_0
tk                        8.5.18                        0
toolz                     0.8.2                    py36_0
tornado                   4.4.2                    py36_0
traitlets                 4.3.1                    py36_0
unicodecsv                0.14.1                   py36_0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.11.15                  py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        1.2.6                    py36_0
wrapt                     1.10.8                   py36_0
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.2                   py36_0
xlwt                      1.2.0                    py36_0
xz                        5.2.2                         1
yaml                      0.1.6                         0
zlib                      1.2.8                         3

**Comment by mingwandroid** [comment]
The issue here is that your root install location contains two forward slashes:
```
root environment : //anaconda
```

How did you install Anaconda? From the shell script or from the installer?

**Comment by tw-rwth** [comment]
I have the same issue with a single-slashed root directory.

**Comment by goanpeca** [comment]
```
self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```

This is probably due to the PATH not correctly set! (Conda not in the path)

**Comment by tw-rwth** [comment]
Could you look over the following 1) error message 2) conda info 3) path?

Error message

Traceback (most recent call last):
  File "/Users/tw_rwth/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'


Conda info

               platform : osx-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/tw_rwth/anaconda  (writable)
    default environment : /Users/tw_rwth/anaconda
       envs directories : /Users/tw_rwth/anaconda/envs
                          /Users/tw_rwth/.conda/envs
          package cache : /Users/tw_rwth/anaconda/pkgs
                          /Users/tw_rwth/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20


Echo $PATH
/Users/tw_rwth/anaconda/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by tw-rwth** [comment]
FYI

1) With previous version (Anaconda2-4.3.0-MacOSX-x86_64) "anaconda-navigator" works.
2) After executing "conda update conda" and "conda update anaconda", the same error message shows up.

Before installing, I execute "anaconda-clean" and "rm -rf anaconda"

**Comment by tw-rwth** [comment]
"Anaconda2-4.1.1-MacOSX-x86_64" works instead of "Anaconda2-4.3.0-MacOSX-x86_64".

**Comment by chuymtz** [comment]
I'm also having the same issues. When I type `conda info` I get

`Current conda install:

               platform : osx-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/chuypotter/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/chuypotter/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/chuypotter/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Darwin/14.5.0 OSX/10.10.5
                UID:GID : 501:20
`

Everything was working until a few hours ago. Tried updating, then I tried doing a clean install. When I choose Anaconda-Navigator, it will look like it's about to open and then suddenly close. 

Just in case it is relevant, I had been working on a python 2 environment to run FEniCS code.

**Comment by RaviGSrinivas** [comment]
I too am having the same issue with getting the two forward slashes before my anaconda folder.  The launcher is not launching and just disappears.  Have struggled the last few days and am just seeing this thread.  Hop we can get this working again.

Current conda install:

               platform : osx-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/rsrinivas/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/rsrinivas/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/rsrinivas/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 486718593:2032920826

CLI-4793:~ rsrinivas$ conda list
# packages in environment at //anaconda:
#
_license                  1.1                      py36_1  
alabaster                 0.7.9                    py36_0  
anaconda                  4.3.0               np111py36_0  
anaconda-client           1.6.0                    py36_0  
anaconda-navigator        1.4.3                    py36_0  
appnope                   0.1.0                    py36_0  
appscript                 1.0.1                    py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3                 np111py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bokeh                     0.12.4                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np111py36_0  
cairo                     1.14.8                        0  
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
conda                     4.3.11                   py36_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.13.0                   py36_0  
datashape                 0.5.4                    py36_0  
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_0  
et_xmlfile                1.0.1                    py36_0  
fastcache                 1.0.2                    py36_1  
flask                     0.12                     py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py36_0  
gettext                   0.19.8                        1  
gevent                    1.2.1                    py36_0  
glib                      2.50.2                        1  
greenlet                  0.4.11                   py36_0  
gsl                       2.2.1                         0  
h5py                      2.6.0               np111py36_2  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
icu                       54.1                          0  
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.5.2                    py36_0  
ipython                   5.1.0                    py36_1  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                5.2.2                    py36_1  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.9.0                    py36_1  
jinja2                    2.9.4                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            4.4.0                    py36_0  
jupyter_console           5.0.0                    py36_0  
jupyter_core              4.2.1                    py36_0  
launcher                  1.0.0                         3  
lazy-object-proxy         1.2.2                    py36_0  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.2                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np111py36_0  
mistune                   0.7.3                    py36_1  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
nbconvert                 4.2.0                    py36_0  
nbformat                  4.2.0                    py36_0  
ncurses                   5.9                          10  
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py36_1  
notebook                  4.3.1                    py36_0  
numba                     0.30.1              np111py36_0  
numexpr                   2.6.1               np111py36_2  
numpy                     1.11.3                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        0  
pandas                    0.19.2              np111py36_1  
pango                     1.40.3                        1  
partd                     0.3.7                    py36_0  
path.py                   10.0                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.0.0                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
ply                       3.9                      py36_0  
prompt_toolkit            1.0.9                    py36_0  
psutil                    5.0.1                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.32                   py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.1.3                    py36_0  
pylint                    1.6.4                    py36_1  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_1  
pytables                  3.3.0               np111py36_0  
pytest                    3.0.5                    py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
python.app                1.2                      py36_4  
pytz                      2016.10                  py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         0  
qtawesome                 0.4.3                    py36_0  
qtconsole                 4.2.1                    py36_1  
qtpy                      1.2.1                    py36_0  
r                         3.3.2                  r3.3.2_0    r
r-base                    3.3.2                         1    r
r-boot                    1.3_18                 r3.3.2_0    r
r-class                   7.3_14                 r3.3.2_0    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-codetools               0.2_15                 r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-kernsmooth              2.23_15                r3.3.2_0    r
r-lattice                 0.20_34                r3.3.2_0    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-mgcv                    1.8_16                 r3.3.2_0    r
r-nlme                    3.1_128                r3.3.2_0    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-recommended             3.3.2                  r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-spatial                 7.3_11                 r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.12.4                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.12.3              np111py36_1  
scikit-learn              0.18.1              np111py36_1  
scipy                     0.18.1              np111py36_1  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sphinx                    1.5.1                    py36_0  
spyder                    3.1.2                    py36_0  
sqlalchemy                1.1.5                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py36_1  
sympy                     1.0                      py36_0  
terminado                 0.6                      py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.1                    py36_0  
unicodecsv                0.14.1                   py36_0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.11.15                  py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        1.2.6                    py36_0  
wrapt                     1.10.8                   py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwings                   0.10.2                   py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3

**Comment by goanpeca** [comment]
@ilanschnell, @kalefranz do you have some thoughts on this? It seems the OSX installer might be related to this?

**Comment by mingwandroid** [comment]
Would the reporters who ended up with a root environment beginning with `//` please confirm how they installed Anaconda? Was it via the installer pkg or via the shell script?

**Comment by goanpeca** [comment]
@vibaskaran, @RaviGSrinivas, @chuymtz, @tw-rwth

**Comment by chuymtz** [comment]
I installed it via the pkg.

**Comment by tw-rwth** [comment]
Install “Anaconda2-4.3.0-MacOSX-x86_64.pkg”: 
    1) Installation: ok
    2) anaconda-navigator: does not work (see error message below)
    3) conda update conda
    4) conda update anaconda
    5) anaconda-navigator: still does not work (the same error message)

After above steps, remove anaconda
    6) install and run “anaconda-clean”
    7) remove folder using “rm -rf anaconda”

Then, install old version, “Anaconda2-4.1.1-MacOSX-x86_64”
    8) installation: ok
    9) anaconda-navigator: ok (works and previously written python codes work)
  10) conda update conda
  11) conda update anaconda
  12) anaconda-navigator: dos not work

Additionally, I tested the following procedure:
     I) clean install the previous version,  “Anaconda2-4.1.1-MacOSX-x86_64”
    II) “anaconda-navigator”: ok
   III) install “anaconda-clean”. This updates the following modules (see the following output): 
        anaconda, conda, conda-env, pyopenssl, requests, and ruamel_yaml
   IV) “anaconda-navigator”: does not work (before run anaconda-clean) 


===============================================
========== Return of “anaconda-navigator”       ==========
===============================================

Traceback (most recent call last):
  File "/Users/tw_rwth/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/Users/tw_rwth/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'


===============================================
========== Return from “conda info”                   ==========
===============================================
Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/tw_rwth/anaconda  (writable)
    default environment : /Users/tw_rwth/anaconda
       envs directories : /Users/tw_rwth/anaconda/envs
          package cache : /Users/tw_rwth/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20


===============================================
========== Output of “conda install anaconda-clean   ======
===============================================
The following NEW packages will be INSTALLED:

    anaconda-clean: 1.1.0-py27_0     

The following packages will be UPDATED:

    anaconda:       4.1.1-np111py27_0 --> custom-py27_0 
    conda:          4.1.6-py27_0      --> 4.3.13-py27_0 
    conda-env:      2.5.1-py27_0      --> 2.6.0-0       
    pyopenssl:      0.16.0-py27_0     --> 16.2.0-py27_0 
    requests:       2.10.0-py27_0     --> 2.13.0-py27_0 
    ruamel_yaml:    0.11.7-py27_0     --> 0.11.14-py27_1

**Comment by goanpeca** [comment]
@tw-rwth could you got to the console and type

`conda info --json` and paste the output?

**Comment by tw-rwth** [comment]
{
  "error": "Traceback (most recent call last):\n  File \"/Users/tw_rwth/anaconda/lib/python2.7/site-packages/conda/exceptions.py\", line 591, in conda_exception_handler\n    return_value = func(*args, **kwargs)\n  File \"/Users/tw_rwth/anaconda/lib/python2.7/site-packages/conda/cli/main.py\", line 134, in _main\n    exit_code = args.func(args, p)\n  File \"/Users/tw_rwth/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py\", line 286, in execute\n    site_dirs = get_user_site()\n  File \"/Users/tw_rwth/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py\", line 85, in get_user_site\n    for path in listdir(expanduser('~/.local/lib/')):\nOSError: [Errno 13] Permission denied: '/Users/tw_rwth/.local/lib/'\n"
}

**Comment by scttfrdmn** [comment]
The // seems to occur when installing via the pkg install method and running into @836 and selecting a disk as an alternative.

**Comment by goanpeca** [comment]
@ilanschnell

**Comment by kalefranz** [comment]
So for the permission error just above, it really is just a permissions issue.  Happens often when using `sudo` but operating on files for your own user.  I think

    sudo chown -R $USER:$USER $HOME/.local

should work.

**Comment by tw-rwth** [comment]
My issue was solved, thank you. The issue was the permission of /.local/lib.
