### ISSUE TITLE
Navigator problem on macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by mehran-kafai** [ContinuumIO/anaconda-issues#1445]
First of all thank you for this great product!

I'm having issues when trying to start Navigator on macOS Sierra 10.12.3 on a 2016 Macbook Pro. Below I've provided the error message, conda info, and conda list. 

Traceback (most recent call last):
  File "/Users/mkafai/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/Users/mkafai/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

Current conda install:
               platform : osx-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/mkafai/anaconda  (writable)
    default environment : /Users/mkafai/anaconda
       envs directories : /Users/mkafai/anaconda/envs
                          /Users/mkafai/.conda/envs
          package cache : /Users/mkafai/anaconda/pkgs
                          /Users/mkafai/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/mkafai/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

# packages in environment at /Users/mkafai/anaconda:
#
_license                  1.1                      py27_1  
alabaster                 0.7.9                    py27_0  
anaconda                  custom                   py27_0  
anaconda-client           1.6.1                    py27_0  
anaconda-navigator        1.4.3                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astroid                   1.4.9                    py27_0  
astropy                   1.3                 np111py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
beautifulsoup4            4.5.3                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.4                   py27_0  
boto                      2.45.0                   py27_0  
bottleneck                1.2.0               np111py27_0  
cdecimal                  2.3                      py27_2  
cffi                      1.9.1                    py27_0  
chardet                   2.3.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.3.11                   py27_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.4                    py27_0  
cryptography              1.7.1                    py27_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask                      0.13.0                   py27_0  
datashape                 0.5.4                    py27_0  
decorator                 4.0.11                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.13.1                   py27_0  
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
flask                     0.12                     py27_0  
flask-cors                3.0.2                    py27_0  
freetype                  2.5.5                         2  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.2.1                    py27_0  
greenlet                  0.4.12                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.6.0               np111py27_2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
icu                       54.1                          0  
idna                      2.2                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.5.2                    py27_0  
ipython                   5.1.0                    py27_1  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_1  
isort                     4.2.5                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.9.0                    py27_1  
jinja2                    2.9.4                    py27_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.1                    py27_0  
lazy-object-proxy         1.2.2                    py27_0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.7.2                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                2.0.0               np111py27_0  
mistune                   0.7.3                    py27_1  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_3  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.9                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.2.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.2                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.3.1                    py27_0  
numba                     0.30.1              np111py27_0  
numexpr                   2.6.2               np111py27_0  
numpy                     1.11.3                   py27_0  
numpydoc                  0.6.0                    py27_0  
odo                       0.5.0                    py27_1  
openpyxl                  2.4.1                    py27_0  
openssl                   1.0.2k                        0  
pandas                    0.19.2              np111py27_1  
partd                     0.3.7                    py27_0  
path.py                   10.0                     py27_0  
pathlib2                  2.2.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    4.0.0                    py27_0  
pip                       9.0.1                    py27_1  
ply                       3.10                     py27_0  
prompt_toolkit            1.0.9                    py27_0  
psutil                    5.1.3                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.32                   py27_0  
pyasn1                    0.1.9                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_2  
pyflakes                  1.5.0                    py27_0  
pygments                  2.1.3                    py27_0  
pylint                    1.6.4                    py27_1  
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_2  
pytables                  3.3.0               np111py27_0  
pytest                    3.0.5                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
python.app                1.2                      py27_4  
pytz                      2016.10                  py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         0  
qtawesome                 0.4.4                    py27_0  
qtconsole                 4.2.1                    py27_1  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.12.4                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
scandir                   1.4                      py27_0  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.18.1              np111py27_1  
scipy                     0.18.1              np111py27_1  
seaborn                   0.7.1                    py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.5.1                    py27_0  
spyder                    3.1.2                    py27_0  
sqlalchemy                1.1.5                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
subprocess32              3.2.7                    py27_0  
sympy                     1.0                      py27_0  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.1                    py27_0  
unicodecsv                0.14.1                   py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.15                  py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
wrapt                     1.10.8                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
xlwings                   0.10.2                   py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3

**Comment by arian-siddiqi** [comment]
I use the same mac specifications as mehran-kafai (above question). I downloaded anaconda but when I click on the launcher application it doesn't open. The navigator starts to initialise and abruptly crashes and the navigator disappears. I regret by uninstalling my previous version of anaconda as Spyder needed to update, now, I think should have put up with annoying update pop up. Any help would be much appreciated.

**Comment by mehran-kafai** [comment]
I haven't heard back with any tips yet. Can you help me solve the issue?

**Comment by goanpeca** [comment]
Hi @mehran-kafai, how did you install anaconda?

**Comment by mehran-kafai** [comment]
I used the graphical installer from https://www.continuum.io/downloads

**Comment by goanpeca** [comment]
What is the content of the bash_profile file, you can open with VIM from the terminal by typing

`vim ~/.bash_profile`

**Comment by mehran-kafai** [comment]
# added by Anaconda2 4.2.0 installer
export PATH="~/anaconda/bin:$PATH"

**Comment by goanpeca** [comment]
If you change it to:
`export PATH="/Users/mkafai/anaconda/bin:$PATH"`

And you try to run `anaconda-navigator`, what do you get?

**Comment by goanpeca** [comment]
Also, could you type

`conda info --json` on the terminal and paste the output?

**Comment by mehran-kafai** [comment]
I still get the same message after changing the path. 
Here is the output that you asked for:
{
  "GID": 20, 
  "UID": 501, 
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64", 
    "https://repo.continuum.io/pkgs/free/noarch", 
    "https://repo.continuum.io/pkgs/r/osx-64", 
    "https://repo.continuum.io/pkgs/r/noarch", 
    "https://repo.continuum.io/pkgs/pro/osx-64", 
    "https://repo.continuum.io/pkgs/pro/noarch"
  ], 
  "conda_build_version": "not installed", 
  "conda_env_version": "4.3.11", 
  "conda_prefix": "/Users/mkafai/anaconda", 
  "conda_private": false, 
  "conda_version": "4.3.11", 
  "default_prefix": "/Users/mkafai/anaconda", 
  "env_vars": {
    "CIO_TEST": "<not set>", 
    "CONDA_DEFAULT_ENV": "<not set>", 
    "CONDA_ENVS_PATH": "<not set>", 
    "DYLD_LIBRARY_PATH": "<not set>", 
    "PATH": "~/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", 
    "PYTHONHOME": "<not set>", 
    "PYTHONPATH": "<not set>"
  }, 
  "envs": [], 
  "envs_dirs": [
    "/Users/mkafai/anaconda/envs", 
    "/Users/mkafai/.conda/envs"
  ], 
  "offline": false, 
  "pkgs_dirs": [
    "/Users/mkafai/anaconda/pkgs", 
    "/Users/mkafai/.conda/pkgs"
  ], 
  "platform": "osx-64", 
  "python_version": "2.7.13.final.0", 
  "rc_path": "/Users/mkafai/.condarc", 
  "requests_version": "2.12.4", 
  "root_prefix": "/Users/mkafai/anaconda", 
  "root_writable": true, 
  "site_dirs": [], 
  "sys.executable": "/Users/mkafai/anaconda/bin/python", 
  "sys.prefix": "/Users/mkafai/anaconda", 
  "sys.version": "2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]", 
  "sys_rc_path": "/Users/mkafai/anaconda/.condarc", 
  "user_agent": "conda/4.3.11 requests/2.12.4 CPython/2.7.13 Darwin/16.4.0 OSX/10.12.3", 
  "user_rc_path": "/Users/mkafai/.condarc"
}

**Comment by goanpeca** [comment]
@mehran-kafai I am afraid I am not sure what is the cause if this problem, everything seems to be in order.

**Comment by gcarrenoz** [comment]
Test by changing all the file permissions from the user folder. Granting them writing and reading, applying to all. Do not forget before clicking on the lock that unlocks that option.
This worked for me correctly.

**Comment by mehran-kafai** [comment]
@gcarrenoz Can you explain with a little bit more detail please. Do you mean the permissions for the anaconda folder? also which lock do you mean. Thanks!

**Comment by gcarrenoz** [comment]
You must grant permissions from the user folder to all subfolders. I tried doing just that with anaconda and its subfolders but it did not work. It worked correctly when I did it from the user folder to all subfolders. The anaconda folder is located in my case inside the user folder.

**Comment by mehran-kafai** [comment]
@gcarrenoz @goanpeca 
It's working now. After changing the permissions I also deleted the content of .continum and .anaconda and everything is working fine. Thanks!
