### ISSUE TITLE
Remainder (%) operator NaN

### ISSUE THREAD

**Issue by 983** [ContinuumIO/anaconda-issues#1446]
There is a bug in remainder and fmod in Visual Studio 2015 on Windows 8.1 which results in 1.7976931348623157e+308 % 1.8111139825551001 and many other values being NaN instead of the correct result.
I found the bug on the Chromium issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=691345
gcc and clang on Windows seem to be unaffected.

```py
import sys, math

x = sys.float_info.max
y = 1.8111139825551001

# prints "nan"
print(x % y)

import numpy as np

X = np.array([[x]])
Y = np.array([[y]])

# prints "[[ nan]]"
print(np.mod(X, Y))

# crashes with "ValueError: math domain error"
print(math.fmod(x, y))
```

![nan_anaconda](https://cloud.githubusercontent.com/assets/11274194/22945691/590f3528-f2f5-11e6-8a61-e3a67b3f32c7.png)

**Comment by remkade** [comment]
This appears to be fixed now. If you see this come up again though, please reopen this ticket. Thanks for reporting this!
