### ISSUE TITLE
I'm having issues when trying to start Navigator on macOS Sierra 10.12.3 on a 2016 Macbook Pro.

### ISSUE THREAD

**Issue by arian-siddiqi** [ContinuumIO/anaconda-issues#1447]
I'm having issues when trying to start Navigator on macOS Sierra 10.12.3 on a 2016 Macbook Pro.
I downloaded Anaconda but when I click on the launcher application it doesn't open. The navigator starts to initialise and abruptly crashes and the navigator disappears. I regret uninstalling my previous version of Anaconda as Spyder needed to update, now, I think should have put up with annoying update pop up. Any help would be much appreciated.

**Comment by goanpeca** [comment]
@arian-siddiqi please go to the terminal and type

`sudo rm -rf ~/.continuum/`

**Comment by arian-siddiqi** [comment]
thanks for your reply. It ask me for a password.

**Comment by arian-siddiqi** [comment]
Arians-MacBook-Pro:anaconda ariansiddiqi$ sudo rm -rf ~/.continuum/
Password:
Sorry, try again.
Password:
sudo: 1 incorrect password attempt
Arians-MacBook-Pro:anaconda ariansiddiqi$ sudo rm -rf ~/.continuum/
Password:
Arians-MacBook-Pro:anaconda ariansiddiqi$ sudo rm -rf ~/.continuum/
Password:

**Comment by goanpeca** [comment]
You need to use the password  you use for logging to your PC

**Comment by arian-siddiqi** [comment]
You are the shining star in the sky! Thanks a million! Worked!!!
