### ISSUE TITLE
conda install pandas brings in scipy

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#145]
_Issue by **[cpcloud](https://github.com/cpcloud)** from Sunday Jul 13, 2014 at 21:59 GMT_
_Originally opened as https://github.com/conda/conda/issues/811_

----

`conda install pandas` shouldn't install `scipy`, as its an optional dependency.

**Comment by ilanschnell** [comment]
I removed the optional dependency from the recipe.  The next time we build pandas, it will no longer depend on scipy.

**Comment by shoyer** [comment]
Thanks!
