### ISSUE TITLE
Python GDAL broken

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1450]
_From @Auerilas on November 30, 2016 16:41_

I've installed GDAL using Anaconda on my Linux machine

  `  conda install gdal`

but I can't load it. If I run Python

```
import gdal
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-27bf4694dd2b> in <module>()
    ----> 1 import gdal
    
    /home/auerilas/anaconda3/lib/python3.5/site-packages/gdal.py in <module>()
          1 # import osgeo.gdal as a convenience
    ----> 2 from osgeo.gdal import deprecation_warn
          3 deprecation_warn('gdal')
          4
          5 from osgeo.gdal import *
    
    /home/auerilas/anaconda3/lib/python3.5/site-packages/osgeo/__init__.py in <module>()
         19                 fp.close()
         20             return _mod
    ---> 21     _gdal = swig_import_helper()
         22     del swig_import_helper
         23 else:
    
    /home/auerilas/anaconda3/lib/python3.5/site-packages/osgeo/__init__.py in swig_import_helper()
         15         if fp is not None:
         16             try:
    ---> 17                 _mod = imp.load_module('_gdal', fp, pathname, description)
         18             finally:
         19                 fp.close()
    
    /home/auerilas/anaconda3/lib/python3.5/imp.py in load_module(name, file, filename, details)
        240                 return load_dynamic(name, filename, opened_file)
        241         else:
    --> 242             return load_dynamic(name, filename, file)
        243     elif type_ == PKG_DIRECTORY:
        244         return load_package(name, filename)
    
    /home/auerilas/anaconda3/lib/python3.5/imp.py in load_dynamic(name, path, file)
        340         spec = importlib.machinery.ModuleSpec(
        341             name=name, loader=loader, origin=path)
    --> 342         return _load(spec)
        343
        344 else:
    
    ImportError: libnetcdf.so.7: cannot open shared object file: No such file or directory
```

I run into the same error if I try to run gdal from the command line

```
    gdalwarp
    gdalwarp: error while loading shared libraries: libnetcdf.so.7: cannot open shared object file: No such file or directory
```

However, it looks as though libnetcdf is installed:

 ```
   ls -R | grep libnetcdf
    libnetcdf-4.4.1-0.json
    libnetcdf.a
    libnetcdf.la
    libnetcdf.settings
    libnetcdf.so
    libnetcdf.so.11
    libnetcdf.so.11.0.3
    libnetcdf-4.4.1-0
    libnetcdf-4.4.1-0.tar.bz2
    ./anaconda3/pkgs/libnetcdf-4.4.1-0:
    ./anaconda3/pkgs/libnetcdf-4.4.1-0/bin:
    ./anaconda3/pkgs/libnetcdf-4.4.1-0/include:
    ./anaconda3/pkgs/libnetcdf-4.4.1-0/info:
    ./anaconda3/pkgs/libnetcdf-4.4.1-0/lib:
    libnetcdf.a
    libnetcdf.la
    libnetcdf.settings
    libnetcdf.so
    libnetcdf.so.11
    libnetcdf.so.11.0.3
    ./anaconda3/pkgs/libnetcdf-4.4.1-0/lib/pkgconfig:

```
Does anyone have any ideas? I've tried compiling gdal from source and that doesn't work, I run into an error about gdalinfo missing. However, gdal config works

```
    gdal-config --version
    2.0.0

```
and I've also tried running 

`    sudo apt-get install libgdal1-dev`

I hacked together a solution by following the broken links. When I installed gdal, I had libnetcdf.so.11, libkea.so.1.4.6, and libhdf5_cpp.so.12. But gdal was looking for libnetcdf.so.7, libkea.so.1.4.5, and libhdf5_cpp.10. I made the following symlinks:

```
    cd ~/anaconda3/lib
    ln -s libnetcdf.so.11 libnetcdf.so.7
    ln -s libkea.so.1.4.6 libkea.so.1.4.5
    ln -s libhdf5_cpp.12 libhdf5_cpp.10
```

and it works fine. Something was broken in the install where gdal was attempting to find the libraries by specific version rather than by the generic libnetcdf.so. If gdal uses the generic, non-versioned files, those act as symbolic links to the current version. It may just be that gdal needs to be updated to the current version on conda?

_Copied from original issue: conda/conda#3973_

**Comment by kalefranz** [comment]
_From @ajoros on February 6, 2017 23:27_

I would like to know if there is an update to this... I am having same issue as well...

**Comment by kalefranz** [comment]
_From @Auerilas on February 7, 2017 1:0_

Another note: I recently updated all my packages and conda gdal remains broken. There was another .so file that would not load, so I had to use

`conda install hdf4`

which downgraded the qt package and removed the error.

**Comment by kalefranz** [comment]
_From @ajoros on February 7, 2017 1:3_

Yea, I had to use the following line to fix the gdal error:
`conda install -c nesii gdal=1.11.3`

And then I had to fix another geos lib error by using:
`conda install -c anaconda geos=3.5.0`

**Comment by kalefranz** [comment]
_From @drf5n on February 7, 2017 17:25_

This configuration works:
```

$ conda list
# packages in environment at /sciclone/home10/drf/anaconda3/envs/gdal:
#
curl                      7.49.0                        1  
decorator                 4.0.11                   py35_0  
gdal                      2.1.0                    py35_0  
geos                      3.5.0                         0  
geotiff                   1.4.1                         0  
hdf4                      4.2.12                        0  
hdf5                      1.8.17                        1  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
jbig                      2.1                           0  
jpeg                      8d                            2  
kealib                    1.4.6                         0  
libgdal                   2.1.0                         0  
libnetcdf                 4.4.1                         0  
libtiff                   4.0.6                         2  
mkl                       2017.0.1                      0  
numpy                     1.11.3                   py35_0  
openssl                   1.0.2k                        0  
path.py                   10.0                     py35_0  
pexpect                   4.2.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pip                       9.0.1                    py35_1  
proj4                     4.9.2                         0  
prompt_toolkit            1.0.9                    py35_0  
ptyprocess                0.5.1                    py35_0  
pygments                  2.1.3                    py35_0  
python                    3.5.2                         0  
readline                  6.2                           2  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
six                       1.10.0                   py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.1                    py35_0  
wcwidth                   0.1.7                    py35_0  
wheel                     0.29.0                   py35_0  
xerces-c                  3.1.4                         0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  

$ conda info --envs
# conda environments:
#
gdal                  *  /sciclone/home10/drf/anaconda3/envs/gdal
root                     /sciclone/home10/drf/anaconda3

```

I had a similar issue when I had both my root environment and my gdal environment both in my $PATH, so it was pulling ipython from my ~/anaconda/bin/ environment, when it should have been pulling it from the gdal environment.   Cleaning $PATH up and activating my gdal env seems to work fine now.

**Comment by kalefranz** [comment]
_From @ajoros on February 7, 2017 22:18_

Interesting thanks for the feedback. Yea I just kept going to Anaconda cloud and finding the most used packages that I needed and of course with the correct version.

**Comment by kalefranz** [comment]
_From @Auerilas on February 15, 2017 16:14_

Is there any chance the devs will fix these issues with gdal? My current strategy is to run

conda update --all

to update my packages and then revert the conflicted dependencies by

conda install hdf4

It'd be nice to not have to do this.

**Comment by davidraleigh** [comment]
I'm trying to build GDAL manually on Ubuntu with conda installed on the machine. At the gdal_wrap stage of the build I get the following error:

``` makefile
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/usr/include/python2.7 -I. -I/opt/src/gdal/gdal/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-2.7/extensions/gdal_wrap.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
extensions/gdal_wrap.cpp:155:21: fatal error: Python.h: No such file or directory
```

If I look at the recommended python compilation flags I see that the above code isn't pointing to the correct include directories:

```bash
/opt/src/gdal/gdal# python-config --cflags
-I/opt/conda/include/python2.7 -I/opt/conda/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
``` 

When I symbolically link the conda to the `-I/usr/include/python2.7` referenced above:
``` bash
ln -s /opt/conda/include/python2.7 /usr/include/python2.7
```

After linking the include directory I no longer get the build error and I can `import gdal` and `import ogr` without error.

Maybe if we could see the build script ContinuumIO is using for building GDAL and linking all the SWIG wrappers, that'd be really helpful. Maybe they just need to symbolic link?

**Comment by ensafi** [comment]
I could open a new issue, but since my Python GDAL is also broken due to a possibly related bug, I am reporting it here first.  My observation may explain why a symbolic link outside of Conda solved some of the originally reported issues.  I am using GDAL 2.3.2 under Python 3.6 (Anaconda3).  When I ```import gdal``` my PATH is clobbered as a result of code in ```osgeo/__init.py___``` which does not check to see if my platform is Windows, and it blindly appends ```\Library\bin;``` to the PATH entry matching ```sys.prefix``` as follows:

```
if not '%s\Library\bin' % (sys.prefix) in os.environ['PATH']:
    os.environ['PATH'] = r'%s\Library\bin;%s' % (sys.prefix, os.environ['PATH'])
```

**Comment by msarahan** [comment]
That bit comes from this patch: https://github.com/AnacondaRecipes/gdal-feedstock/blob/master/recipe/0003-prepend-dll.patch

We should probably remove it.  We generally don't support usage of Anaconda without "activation" of environments anyway, so it's superfluous.

**Comment by ensafi** [comment]
I wasn’t aware that Anaconda packages are sometimes patched versions.  If it’s called GDAL 2.3.2, I always assumed that it would be a standard 2.3.2 release.

I see a lot of similar practices in other packages installed by Conda.  In most cases, an OS check is performed first, but perhaps many of these patches are superfluous?

**Comment by DaveDM** [comment]
> That bit comes from this patch: https://github.com/AnacondaRecipes/gdal-feedstock/blob/master/recipe/0003-prepend-dll.patch
> 
> We should probably remove it. We generally don't support usage of Anaconda without "activation" of environments anyway, so it's superfluous.

@msarahan are there any plans to remove, or make that patch platform specific?  I can control the imports in my own code to make sure they're well behaved, but can't easily to so for our dependencies.

**Comment by remkade** [comment]
This patch appears to have been removed on our and conda-forge's recipes. Is this still causing problems?

The patch was removed in conda-forge/gdal-feedstock#211

I'll close for now, but please reopen if this is still a problem!
