### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by XiayangNL** [ContinuumIO/anaconda-issues#1453]
The following errors occured:

None:
Package missing in current win-64 channels: 
  - scipy ==0.18.1

You can search for packages on anaconda.org with

    anaconda search -t conda scipy

{'pyqt': '4.11.4', 'python': '3.5.2', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'version': '1.2.1', 'language': 'en_US', 'qt': '4.8.7', 'conda': '4.1.6', 'platform': 'win-64'}

**Comment by goanpeca** [comment]
@XiayangNL  you are using an old version of Navigator. Could you update to the latest Anaconda/Navigator?
