### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by qqopp** [ContinuumIO/anaconda-issues#1454]
The following errors occured:

None:
Package missing in current win-64 channels: 
  - sip ==4.18

You can search for packages on anaconda.org with

    anaconda search -t conda sip

{'pyqt': '4.11.4', 'version': '1.2.1', 'platform': 'win-64', 'qt': '4.8.7', 'language': 'zh_CN', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel', 'conda': '4.1.6', 'python': '3.5.2'}

**Comment by goanpeca** [comment]
@qqopp you are using an old version of Navigator. Could you update to the latest Anaconda/Navigator?
