### ISSUE TITLE
Anaconda is blowing away PATH variable when deactivate

### ISSUE THREAD

**Issue by 921kiyo** [ContinuumIO/anaconda-issues#1459]
In GitBash on Windows 10, I am no longer able to use "ls" command when deactivate. The screenshot below explains what is happening. 

<img width="437" alt="conda-error" src="https://cloud.githubusercontent.com/assets/8097799/23064298/39c6ba1a-f507-11e6-8d72-af25512a9680.PNG">

**Comment by mingwandroid** [comment]
This is in @kalefranz's remit.

**Comment by kalefranz** [comment]
Can you please provide the output of `conda info`? Also, which shell are you using? I thought `ls` was generally a shell built-in. Please provide `type -a ls`.

**Comment by mingwandroid** [comment]
`ls` is an executable on all systems I have seen. It is part of the GNU coreutils package on Linux and MSYS2 (which Git for Windows is a derivative of).

**Comment by kalefranz** [comment]
Yeah I figured that out after I wrote that initial comment, and then poked around. Learned something new :)

**Comment by mingwandroid** [comment]
I fixed this a while back.
