### ISSUE TITLE
OS X Mavericks + Tkinter window drawing issue due to outdated Tcl/Tk

### ISSUE THREAD

**Issue by issira** [ContinuumIO/anaconda-issues#146]
I am working on developing an app using Tkinter, but ran into some window drawing issues on OS X Mavericks described here: http://bugs.python.org/issue19373

Apparently, the issue has been fixed in Tcl/Tk 8.5.15.1, but it seems the latest Tk package included in Anaconda is 8.5.15

**Comment by ccordoba12** [comment]
Tk was updated to version 8.5.18 a couple of weeks ago. Please update to that version with

    conda update tk
