### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by XiayangNL** [ContinuumIO/anaconda-issues#1463]
Anaconda Navigator Update error:

E:\anaconda3\a\python.exe E:\anaconda3\a\Scripts\conda-script.py install --yes --json --force-pscheck --name root anaconda-navigator=1.4.3: Package missing in current win-64 channels: 
  - anaconda-navigator 1.4.3*

You can search for packages on anaconda.org with

    anaconda search -t conda anaconda-navigator

{'version': '1.2.1', 'pyqt': '4.11.4', 'language': 'en_US', 'python': '3.5.2', 'platform': 'win-64', 'conda': '4.1.6', 'qt': '4.8.7', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel'}

**Comment by goanpeca** [comment]
The latests version on Navigator depends on qt5, to install pelase open the **Anaconda Command Prompt** and type:

```
$ conda remove qt=4 pyqt=4
$ conda install qt=4 pyqt=4
$ conda install anaconda-navigator
```
