### ISSUE TITLE
Conditional conflict between py2cairo and r-essentials 1.5.2

### ISSUE THREAD

**Issue by rcthomas** [ContinuumIO/anaconda-issues#1464]
I would like to install `r-essentials=1.5.2` in a Linux Python 2.7 Miniconda setup.  A complication is that the environment also needs to include `basemap` and `blz.`  This combination (possibly others, but I can cause the issue with these 3 packages at least) seems to be a problem.  I can make everything go just fine if I do:

```
wget https://repo.continuum.io/miniconda/Miniconda2-4.3.11-Linux-x86_64.sh
bash Miniconda2-4.3.11-Linux-x86_64.sh -b -p $(pwd)/env1
export PATH=$(pwd)/env1/bin:$PATH
conda update --quiet --yes --all
conda install --quiet --yes basemap blz r-essentials=1.5.2
```

I can do that for a completely new environment of course.  Simulating the environment I already have though, if you do this:

```
wget https://repo.continuum.io/miniconda/Miniconda2-4.3.11-Linux-x86_64.sh
bash Miniconda2-4.3.11-Linux-x86_64.sh -b -p $(pwd)/env2
export PATH=$(pwd)/env2/bin:$PATH
conda update --quiet --yes --all
conda install --quiet --yes basemap blz
conda install --quiet --yes r-essentials=1.5.2
```

You end up with a conflict between `r-essentials=1.5.2` and `py2cairo.`  

At the bottom of this seems to be `numpy` --- if you separate the `basemap` and `blz` installs, the first package  installs `numpy 1.12.0-py27_0` but the `blz` install comes along and "updates" (is it really an update?) `basemap` like:

```
basemap:     1.0.7-np112py27_0 defaults --> 1.0.7-np19py27_0 defaults
```

And that's why `py2cairo` pops in.  It's the same basemap source version, but different `numpy` dependency?  I don't see why that changes `py2cairo`.

I would like `r-essentials=1.5.2` as it gets me past things like #1063 with R 3.3.1.  I confirm that force uninstalling `py2cairo` makes that work.   I note this doesn't seem to be an issue if I try the above steps with the Python 3 Miniconda installer.

**Comment by mingwandroid** [comment]
You should *not* do `export PATH=$(pwd)/env1/bin:$PATH`. You should instead do `source  $(pwd)/env1/bin/activate`.

But that's not your issue here. The issue here seems to be that `blz` has been removed from Anaconda in manner. @ilanschnell can you give us more details please?

**Comment by rcthomas** [comment]
Sorry, I'm just following the documentation here:

https://docs.continuum.io/anaconda/install#linux-install

Also if I run the installer not in batch mode, at the end, it says,

```
You may wish to edit your .bashrc or prepend the Miniconda2 install location:

$ export PATH=/global/homes/r/rthomas/miniconda2/bin:$PATH
```

**Comment by mingwandroid** [comment]
OK, thanks, @electronwill, can I propose we change that?

**Comment by electronwill** [comment]
Yes, I'll fix that using the info on PATH you gave in https://github.com/ContinuumIO/navigator/pull/919 . Instead of adding conda to PATH we'll recommend that all users instead start each new session by opening a terminal window and running ``source ~/miniconda2/bin/activate`` (replacing ``~/miniconda2/`` with their conda directory, which might be different).
