### ISSUE TITLE
Import error for scipy.misc.imread and scipy.misc.imsave

### ISSUE THREAD

**Issue by jtouati** [ContinuumIO/anaconda-issues#147]
I tried to import those funcions with both the 0.12.0 and 0.14.0 version of scipy but I still get the same import error
ImportError: No module named imsave
ImportError: No module named imread

Ps : those imports are working with other python interpreters (canopy)

**Comment by pabloj100000** [comment]
I'm having the same problem. Any solution to this?

**Comment by damianavila** [comment]
IIRC, some of these scipy functions needs PIL (or Pillow) installed. Can you try it again after installing PIL or Pillow with `conda install PIL` (or `conda install Pillow`).

**Comment by pabloj100000** [comment]
Thanks Damián, that solved the problem



----- Original Message -----

**Comment by damianavila** [comment]
Nice to know... then, closing here.

**Comment by Bamorovat** [comment]
I had this problem in anaconda ,as well. I just update scipy as below:
 conda install -c anaconda scipy

**Comment by nazarovsky** [comment]
Had the same problem, seems that newer scipy versions don't work... Solved by downgrading
`conda install -c anaconda scipy=1.2.0`
