### ISSUE TITLE
numpy is not linked to MKL but OpenBLAS on Anaconda 4.3.0 Linux x86_64?

### ISSUE THREAD

**Issue by striges** [ContinuumIO/anaconda-issues#1471]
Clean installation. Python 3.6
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

which seems to be MKL on a Python 3.5 env

Python 3.5.2 |Anaconda 4.3.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.show_config()
lapack_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sugar/anaconda3/envs/python35/include']
    library_dirs = ['/home/sugar/anaconda3/envs/python35/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sugar/anaconda3/envs/python35/include']
    library_dirs = ['/home/sugar/anaconda3/envs/python35/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
openblas_lapack_info:
  NOT AVAILABLE
blas_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sugar/anaconda3/envs/python35/include']
    library_dirs = ['/home/sugar/anaconda3/envs/python35/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
blas_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sugar/anaconda3/envs/python35/include']
    library_dirs = ['/home/sugar/anaconda3/envs/python35/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
>>> 

Is this an intentional change?

**Comment by ilanschnell** [comment]
When I create an Anaconda (Python 3.5) environment, on 64-bit Linux, using:
```
$ conda create -n py35 anaconda python=3.5
```
I see that numpy is linked to MKL:
```
$ <prefix>/envs/py35/lib/python3.5/site-packages/numpy/linalg
$ ldd lapack_lite.cpython-35m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffffffe5000)
	libmkl_intel_lp64.so => /home/ilan/a/envs/py35/lib/python3.5/site-packages/numpy/linalg/./../../../../libmkl_intel_lp64.so (0x00007fd6ac964000)
	libmkl_intel_thread.so => /home/ilan/a/envs/py35/lib/python3.5/site-packages/numpy/linalg/./../../../../libmkl_intel_thread.so (0x00007fd6aaefe000)
	libmkl_core.so => /home/ilan/a/envs/py35/lib/python3.5/site-packages/numpy/linalg/./../../../../libmkl_core.so (0x00007fd6a9406000)
	libiomp5.so => /home/ilan/a/envs/py35/lib/python3.5/site-packages/numpy/linalg/./../../../../libiomp5.so (0x00007fd6a905c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd6a8e29000)
	libpython3.5m.so.1.0 => /home/ilan/a/envs/py35/lib/python3.5/site-packages/numpy/linalg/./../../../../libpython3.5m.so.1.0 (0x00007fd6a8939000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd6a858c000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd6a8387000)
	libgcc_s.so.1 => /home/ilan/a/envs/py35/lib/python3.5/site-packages/numpy/linalg/./../../../.././libgcc_s.so.1 (0x00007fd6a8171000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd6ad58b000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fd6a7f6d000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fd6a7d65000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd6a7a67000)
```
How did you create the conda environment?  Also, which command did you use to get all the configuration parameters from?

**Comment by striges** [comment]
I mean numpy in Python 3.6 is *not* linked to MKL, which is at least reported in numpy.show_config(). Yes, you're right, in Python 3.5 numpy *is* linked to MKL.

**Comment by ilanschnell** [comment]
When I run `conda create -n py36 anaconda python=3.6` and look at the `ldd` output, I see the same as with Python 3.5 (things are linked to MKL).  Also, here is my `numpy.show_config()` output for the Python 3.6 anaconda environment:
```
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy
<module 'numpy' from '/home/ilan/a/envs/py36/lib/python3.6/site-packages/numpy/__init__.py'>
>>> numpy.show_config()
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/ilan/a/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ilan/a/envs/py36/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/ilan/a/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ilan/a/envs/py36/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/ilan/a/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ilan/a/envs/py36/include']
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/ilan/a/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ilan/a/envs/py36/include']
```

**Comment by striges** [comment]
I did a fresh install again on a clean machine (ArchLinux), still not
```
(root) ➜  ~ python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
>>>
```

**Comment by striges** [comment]
My fault. It seems numpy doesn't referring numpy in anaconda. Sorry for that.

**Comment by ivan-bilan** [comment]
> My fault. It seems numpy doesn't referring numpy in anaconda. Sorry for that.

What do you mean?
