### ISSUE TITLE
Missing astropy 1.3 with numpy 1.12 for Python3

### ISSUE THREAD

**Issue by bsipocz** [ContinuumIO/anaconda-issues#1474]
In the defaults channel there are builds available with the new numpy versions for python2, but the ones for the python3 versions are missing causing troubles for continuous integration for a few packages (e.g. https://github.com/conda/conda/issues/4701).
Would it be possible to upload those builds, too? Thanks.

**Comment by bsipocz** [comment]
While I realize that these combinations got built recently, we have just released a new bugfix today 1.3.1. 

I wonder what is the preferred way to let you know about new releases? Opening an issue, e-mail, or you have a pypi watchlist?

**Comment by ilanschnell** [comment]
Thanks, for letting us know about the 1.3.1 release.  Astropy, is a packages which is usually very easy to build, and which we keep very up-to-date.  New astropy conda packages should be available in the default channel on Monday!

**Comment by bsipocz** [comment]
Thanks!

**Comment by ilanschnell** [comment]
Astropy 1.3.1 is now available for all platforms, Python versions we currently support (2.7, 3.5 and 3.6), and also compiled against Numpy 1.11 and 1.12.

**Comment by MSeifert04** [comment]
🎉 Thanks @ilanschnell
