### ISSUE TITLE
Anaconda Navigator crashes upon launch (Mac OS X Yosemite)

### ISSUE THREAD

**Issue by Bhersbach** [ContinuumIO/anaconda-issues#1476]
I've downloaded and installed Anaconda version 3.4.0. on my MacBook Pro yesterday and it does not want to launch. As there is a space in my username I first got an error during the installation but when I tried to install it directly in the applications folder things were fine. However when launching Anaconda Navigator it crashes immediately, the dock icon appears and then disappears directly. I'm still very new to this but I looked online and could not seem to find any solution to this. I did manage to find out how to launch it from the terminal, which gives the same result but also this error that I thought my make sense to some of you. Hope you can help.

[Terminal output.txt](https://github.com/ContinuumIO/anaconda-issues/files/800023/Terminal.output.txt)

**Comment by goanpeca** [comment]
Hi @Bhersbach I susggest yo delete that anaconda installation and install for the current user only (and use the home directory as default for it) and try installing it again

**Comment by Bhersbach** [comment]
Hi @goanpeca, Thanks for you suggestion. I've tried that just now but unfortunately I get the error again that there's a space in my username and the installion fails. Is there any other way around this?

**Comment by goanpeca** [comment]
is it the same error or a different error? you can paste the error directly here

**Comment by Bhersbach** [comment]
It's a different error that occurs during the installation. I've attached a picture of the installation error. 
![screen shot 2017-02-24 at 19 01 48](https://cloud.githubusercontent.com/assets/26010144/23314941/4029dbae-fac4-11e6-9122-8c54cb2aca39.png)
![screen shot 2017-02-24 at 19 04 22](https://cloud.githubusercontent.com/assets/26010144/23314942/402a92c4-fac4-11e6-813b-7a445a83cac0.png)

**Comment by goanpeca** [comment]
@mingwandroid do you have a suggestion of another (default) location we should use if this occurs?

**Comment by mingwandroid** [comment]
I wasn't aware we had this restriction in place on macOS. I don't know anything about the installer side of things there to be honest. Perhaps the installer shell script would allow you to install to a path with spaces in it?

**Comment by Bhersbach** [comment]
Maybe I'm missing something obvious but when I follow the instructions on how to do that I get this: 
MacBook-Pro-van-Bob:~ Bob Hersbach$ bash ~/Users/Bob Hersbach/Desktop/Anaconda3-4.3.0-MacOSX-x86_64.sh
bash: /Users/Bob Hersbach/Users/Bob: No such file or directory

**Comment by mingwandroid** [comment]
The problem here is that bash splits arguments at spaces and passes them in independently, so here, it sees `/Users/Bob` and `Hersbach/Desktop/Anaconda3-4.3.0-MacOSX-x86_64.sh`. This is a common problem with lots of software and that is the reason that using spaces in your username is a bad idea.

When you're using a package manager, usually the idea is to install lots of software so installing the whole thing into a folder with a space in it increases the chances of running into problems.

I would recommend (though this is done at your own risk!) you create a new user on your machine called "BobHersbach" if possible and move all your files from the old folder into this new one then take ownership of all the files via:

```
cd /Users/BobHersbach
chown -R BobHersbach:staff *
```

Then login as the new user, and once you are happy that everything is working, remove the old user account.

If you wish to proceed with a username with spaces in it then you need to quote your username to prevent bash splitting it into two arguments via:

```
bash ~/Users/"Bob Hersbach"/Desktop/Anaconda3-4.3.0-MacOSX-x86_64.sh
```

If you don't want to do either of these things, then there's a third way which requires `sudo` access to your machine. Do you have that? Can you enter `sudo ls` and see a directory listing (after entering your password)?

**Comment by Bhersbach** [comment]
Thanks a lot for your explanation and suggestions Ray, it all makes a bit more sense now! I more or less went with the first option you suggested and made an additional account on my computer where it works like a charm! For now I think I'll just use that account for Anaconda and keep all the other stuff where it is. But when this will get inconvenient I will move all the stuff over to that account. Again, thanks so much for your help on this!

Best,

Bob

**Comment by tuulihill** [comment]
I'm also having this issue with Mac OSSierra - no spaces in any user names. I tried uninstalling and reinstalling from the command line but Navigator still crashes on launch. Any ideas? Thanks.

**Comment by tuulihill** [comment]
I'm having the same problem with Mac OSSierra - there are no spaces in my username. I've tried uninstalling and reinstalling from the command line, and still navigator crashes on launch. Any ideas?

**Comment by mingwandroid** [comment]
Did you try installing for `All Users` or `Just Me`? Is any information given when navigator crashes?

**Comment by tuulihill** [comment]
I was doing it from the command line for just my username. No info - the icon appears on the screen and on the dock and then just suddenly disappears.

**Comment by mingwandroid** [comment]
Can you show the output from `conda info` please?

**Comment by goanpeca** [comment]
@tuulihill could you please open a terminal and type:

`anaconda-navigator` and copy/paste the error traceback (if any appears?)

**Comment by tuulihill** [comment]
currently anything with conda i get `command not found` . I tried adding `export PATH="/Users/<username>/anaconda/bin:$PATH"` with my username to the bashhrc.sh file that I read somewhere to do, but that has not resolved this.

**Comment by robgolson** [comment]
Having the same issue, crashing before even opening on OS Sierra 10.12.2
Feedback from terminal:

student-10-245-154-195:~ robgolson$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/robgolson/anaconda2/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/robgolson/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/robgolson/.continuum/anaconda-client: Permission denied

**Comment by goanpeca** [comment]
@robgolson you can fix by typing in the terminal

`sudo rm -rf ~/.continuum/`

**Comment by robgolson** [comment]
"Password:" with a key symbol coming up now?

**Comment by goanpeca** [comment]
Just type the password you normally use to login to that computer

**Comment by robgolson** [comment]
All sorted, thank you!

**Comment by tuulihill** [comment]
@goanpeca anything with anaconda or conda i just get command not found. after install it said it had been successful but perhaps there is still something basic that can be fixed?

**Comment by tuulihill** [comment]
@goanpeca i used `sudo rm -rf ~/.continuum/`and now navigator will launch...however, i still can't use pip in the terminal, for example, and when i try `conda info` i still get "command not found". something seems to be wrong.

**Comment by goanpeca** [comment]
Hi @tuulihill, it seems conda is not correctly set on your path. How did you install conda and f you go to the terminal and type:

`vim ~/.bash_profile` what is the content?

**Comment by tuulihill** [comment]
This time I installed it with the GUI for this user only. 
The content for `vim ~/.bash_profile` is 
`# added by Anaconda3 4.3.0 installer
export PATH="//anaconda/bin:$PATH"
`

**Comment by goanpeca** [comment]
Hmm, well the content should be something like

```
# added by Anaconda3 4.3.0 installer
export PATH="/Users/<username>/anaconda/bin:$PATH"
```

**Comment by tuulihill** [comment]
OK - sorry to be so new at all this but how do I change that? Thanks!

**Comment by goanpeca** [comment]
Where is the anaconda folder located?

**Comment by tuulihill** [comment]
it's right under /Users/<username>/

**Comment by lifelikely** [comment]
have done all of the above. install via gui and command line. I can run the executables but have to "./" to force them to run. "./condo info" returns valid info but then this happens:

XXXXXXXXX:bin XXXXXXXXX$ ./anaconda-navigator
Traceback (most recent call last):
  File "./anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/Users/XXXXXXXXX/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by tuulihill** [comment]
I see this issue is officially closed but I continue to have it and can't use Anaconda!

**Comment by striatum** [comment]
The latest version also crushes once it opens the window. From the command line I am copying in last relevant lines:

`File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 418, in convert_image
    extension = path.split('.')[-1].upper()
AttributeError: 'NoneType' object has no attribute 'split'
Abort trap: 6`

I am running Python 3.5.3 (Continuum Analytics, Inc.) on Mac OSX.

**Comment by goanpeca** [comment]
@striatum seems you are using an older version of navigator.

Could you try with the latest 1.5.2 version?

**Comment by striatum** [comment]
I did conda update --all. (The above problem is after updating!) Do I need to remove old anaconda and install fresh?

**Comment by goanpeca** [comment]
@striatum could you open a new issue an paste the output of `conda list`
and `conda info`

**Comment by striatum** [comment]
Done! Thanks!

**Comment by maladeep** [comment]
@goanpeca Brother,I am   Having Traceback error,I uninstall the anaconda and reinstalled it and same problem was faced,So I updated all using $ condo update --all and after doing so also I get same error.What should I do now?

$ Conda info
platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.30
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/XXXXXX/anaconda3  (writable)
    default environment : /Users/XXXXXX/anaconda3
       envs directories : /Users/XXXXXXX/anaconda3/envs
                          /Users/XXXXXX/.conda/envs
          package cache : /Users/XXXXXXX/anaconda3/pkgs
                          /Users/XXXXXXX/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/XXXXXXXXX/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Darwin/15.6.0 OSX/10.11.6    
                UID:GID : 501:20

I did all the tips that you have shared on this page and few others but still my issues is not resolved.Help me Please.

**Comment by goanpeca** [comment]
what does `XXXXXX` mean?

**Comment by maladeep** [comment]
Brother,XXXXXX just for my username of the computer.

**Comment by grebenyuksv-preply** [comment]
`conda update --all` fixed that for me

**Comment by anirbunt** [comment]
I'm suffering  from a similar issue and the error that's shown when i run anaconda-navigator is as below
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6

**Comment by shishirsriv** [comment]
i m also facing exactly same issues 
Shishirs-MacBook-Air:anaconda shishir$ anaconda-navigator 
Traceback (most recent call last):
  File "/Users/shishir/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6

**Comment by shishirsriv** [comment]
this worked for me 
shishir$ conda update anaconda-navigator

**Comment by Fredilly** [comment]
Does most recent anaconda work well with python 2.7. Crashes at startup. Will try updating conda.

Traceback (most recent call last):  
 File "//anaconda/lib/python2.7/site-
packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list     uri=item['uri'], date=item.get('date', '') or "", 
KeyError: 'uri' 
Abort trap: 6
