### ISSUE TITLE
Incorrect pandoc version

### ISSUE THREAD

**Issue by acarril** [ContinuumIO/anaconda-issues#1477]
The lastest pandoc stable version is supposed to be 1.19.2.1, but due to an error reported [here](https://github.com/jgm/pandoc/issues/3416), version 2.0 was actually packaged in Windows. pandoc's authors seem to have corrected the issue, but it appears that an incorrect version still remains [here](https://anaconda.org/anaconda/pandoc/files). This can be verified by typing `pandoc --version`, which shows it's actually 2.0.

**Comment by mingwandroid** [comment]
Urgh.

**Comment by acarril** [comment]
OK thank you! Please report when you do, so I can reinstall pandoc.

**Comment by mingwandroid** [comment]
An updated `pandoc` for Windows has now been released:

```
conda update pandoc
pandoc --version
pandoc 1.19.2.1
```
