### ISSUE TITLE
Jupyter Notebook does not launch. (Anaconda 4.3.0 in Windows)

### ISSUE THREAD

**Issue by hwyncho** [ContinuumIO/anaconda-issues#1480]
This is my PC's environment.
> Windows 10 Pro 64-bit
> Anaconda3 4.3.0

I've experienced this problem since updated to Anaconda3 4.3.0

This is the default target of "Jupyter Notebook" shortcut. (in my case)
> C:\Users\hwync\Anaconda3\python.exe C:\Users\hwync\Anaconda3\cwp.py C:\Users\hwync\Anaconda3 "C:/Users/hwync/Anaconda3/python.exe" "C:/Users/hwync/Anaconda3/Scripts/jupyter-notebook-script.py" %HOME%

In here, `%HOME%` caused the problem.

So, I solved the problem with following solutions.
Please choose your preferred method.

## 1. Add a new `HOME` in system variables.
Go to `Advanced System Settings > Environment Variables`, add a new `HOME` in system variables.
> Variable name : HOME
> Variable value : C:\Users\hwync\Documents\Notebooks

## 2. Change `%HOME%` to path.
`%HOME%` ⇒ `C:\Users\hwync\Documents\Notebooks`

## 3. Change `%HOME%` to `%JUPYTER_HOME%` and add in system variables.
`%HOME%` ⇒ `%JUPYTER_HOME%`
Go to `Advanced System Settings > Environment Variables`, add a new `JUPYTER_HOME` in system variables.
> Variable name : JUPYTER_HOME
> Variable value : C:\Users\hwync\Documents\Notebooks

I hope my comments helped. 🙂

**Comment by mingwandroid** [comment]
We should be using %USERPROFILE% here on Windows .. hmm, I'll take this.

**Comment by hwyncho** [comment]
@mingwandroid 

- `%HOME%` is in the default target of "Jupyter Notebook" shortcut.
- But, `%HOME%` is not in the Windows 10's system variables.

I think that this problem is caused by the above items.

So, I solved the problem with following solutions.
- Add `%HOME%` in system variables.
- Change `%HOME%` to something that is in system variables. (i.e USERPROFILE, JUPYTER_HOME)

**Comment by mingwandroid** [comment]
@hwyncho, yeah, thanks, I was suggesting we (Continuum) do the first variant of you second proposed solution, i.e.

> Change %HOME% to something that is in system variables. (i.e %USERPROFILE% ..
