### ISSUE TITLE
fails to install qt package

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1491]
_From @dchuong105 on February 27, 2017 21:17_

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

overtaking stderr and stdout

stderr and stdout yielding back

Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProductTest\Anaconda  (writable)
    default environment : C:\ProductTest\Anaconda
       envs directories : C:\ProductTest\Anaconda\envs
                          C:\Users\dchuong\AppData\Local\conda\conda\envs
                          C:\Users\dchuong\.conda\envs
          package cache : C:\ProductTest\Anaconda\pkgs
                          C:\Users\dchuong\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-canary/win-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dchuong\.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601

`$ C:\ProductTest\Anaconda\Scripts\conda-script.py install -v qt`

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 493, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\gateways\subprocess.py", line 58, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/c', 'C:\\ProductTest\\Anaconda\\Scripts
\\.qt-post-link.bat']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 320, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 509, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package defaults::qt-5.6.2-vc14_3
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProductTest\Anaconda\Scripts\.qt-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 273, in execute
        pkg_data, actions)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 337, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package defaults::qt-5.6.2-vc14_3
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProductTest\Anaconda\Scripts\.qt-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 289, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package defaults::qt-5.6.2-vc14_3
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProductTest\Anaconda\Scripts\.qt-post-link.bat
    ==> script messages <==
    <None>

_Copied from original issue: conda/conda#4748_

**Comment by mingwandroid** [comment]
@dchuong105 can you please paste the contents of `C:\ProductTest\Anaconda\Library\bin\qt.conf`.

**Comment by dchuong105** [comment]
[Paths]
Prefix = C:/ProductTest/Anaconda/Library
Binaries = C:/ProductTest/Anaconda/Library/bin
Libraries = C:/ProductTest/Anaconda/Library/lib
Headers = C:/ProductTest/Anaconda/Library/include/qt

**Comment by bdonkers** [comment]
I'm having the same (or similar) problem. Is there any progress on this?
Thanks

**Comment by mingwandroid** [comment]
How did you install Anaconda? The most reliable way is to:

1. Install for "Just Me".
2. Do not add to PATH.
3. Ensure that install location has no spaces nor unicode characters.

Then use the `Anaconda Prompt` or `Anaconda Navigator` to run your `Anaconda` software.

**Comment by bdonkers** [comment]
Dear Ray,

I tried it on a different machine, where I had the same problem but a more insightful error message. What ended up being the solution (on my company managed windows machine with sometimes limited rights) was to run conda with administrator rights. Then the installation worked properly.

Thanks,
Bas

**Comment by platinumluthier** [comment]
I must be missing something here. I'm having the same issue, but running it with admin privileges doesn't work.
```
C:\WINDOWS\system32>conda install qt -v
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)

  added / updated specs:
    - qt


The following NEW packages will be INSTALLED:

    certifi:         2018.1.18-py36_0
    qt:              5.6.2-vc14h6f76a7e_12
    sqlite:          3.22.0-h9d3ae62_0
    wincertstore:    0.2-py36hcdd9a18_0

The following packages will be UPDATED:

    ca-certificates: 2017.08.26-h94faf87_0 anaconda --> 2017.08.26-h94faf87_0
    conda:           4.4.11-py36_0         anaconda --> 4.4.11-py36_0
    icu:             57.1-vc14_0                    --> 58.2-h3fcc66b_1
    libpng:          1.6.27-vc14_0                  --> 1.6.34-h79bbb47_0
    openssl:         1.0.2l-vc14hb3c0c5f_5 anaconda [vc14] --> 1.0.2n-h74b6da3_0
    setuptools:      27.2.0-py36_1                  --> 38.5.1-py36_0
    zlib:            1.2.8-vc14_3                   --> 1.2.11-hbb18732_2

Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ===> UNLINKING PACKAGE: anaconda::conda-4.4.11-py36_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> UNLINKING PACKAGE: defaults::setuptools-27.2.0-py36_1 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> UNLINKING PACKAGE: defaults::libpng-1.6.27-vc14_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> UNLINKING PACKAGE: defaults::zlib-1.2.8-vc14_3 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> UNLINKING PACKAGE: anaconda::openssl-1.0.2l-vc14hb3c0c5f_5 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> UNLINKING PACKAGE: defaults::icu-57.1-vc14_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> UNLINKING PACKAGE: anaconda::ca-certificates-2017.08.26-h94faf87_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> LINKING PACKAGE: defaults::ca-certificates-2017.08.26-h94faf87_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\ca-certificates-2017.08.26-h94faf87_0


===> LINKING PACKAGE: defaults::icu-58.2-h3fcc66b_1 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\icu-58.2-h3fcc66b_1


===> LINKING PACKAGE: defaults::openssl-1.0.2n-h74b6da3_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\openssl-1.0.2n-h74b6da3_0


===> LINKING PACKAGE: defaults::sqlite-3.22.0-h9d3ae62_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\sqlite-3.22.0-h9d3ae62_0


===> LINKING PACKAGE: defaults::zlib-1.2.11-hbb18732_2 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\zlib-1.2.11-hbb18732_2


===> LINKING PACKAGE: defaults::certifi-2018.1.18-py36_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\certifi-2018.1.18-py36_0


===> LINKING PACKAGE: defaults::libpng-1.6.34-h79bbb47_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\libpng-1.6.34-h79bbb47_0


===> LINKING PACKAGE: defaults::wincertstore-0.2-py36hcdd9a18_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\wincertstore-0.2-py36hcdd9a18_0


===> LINKING PACKAGE: defaults::qt-5.6.2-vc14h6f76a7e_12 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)
  source=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\pkgs\qt-5.6.2-vc14h6f76a7e_12


$ C:\WINDOWS\system32\cmd.exe /d /c C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Scripts\.qt-post-link.bat
==> cwd: C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Scripts <==
==> exit code: 1 <==
==> stdout <==
b''
==> stderr <==
b"'C:\\Users\\srhodes\\AppData\\Local\\Continuum\\Anaconda3_' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"


===> REVERSING PACKAGE LINK: defaults::qt-5.6.2-vc14h6f76a7e_12 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


failed
An error occurred while installing package 'defaults::qt-5.6.2-vc14h6f76a7e_12'.
LinkError: post-link script failed for package defaults::qt-5.6.2-vc14h6f76a7e_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.


Rolling back transaction: ...working... ===> REVERSING PACKAGE LINK: defaults::wincertstore-0.2-py36hcdd9a18_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE LINK: defaults::libpng-1.6.34-h79bbb47_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE LINK: defaults::certifi-2018.1.18-py36_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE LINK: defaults::zlib-1.2.11-hbb18732_2 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE LINK: defaults::sqlite-3.22.0-h9d3ae62_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE LINK: defaults::openssl-1.0.2n-h74b6da3_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE LINK: defaults::icu-58.2-h3fcc66b_1 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE LINK: defaults::ca-certificates-2017.08.26-h94faf87_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE UNLINK: anaconda::ca-certificates-2017.08.26-h94faf87_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE UNLINK: defaults::icu-57.1-vc14_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE UNLINK: anaconda::openssl-1.0.2l-vc14hb3c0c5f_5 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE UNLINK: defaults::zlib-1.2.8-vc14_3 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE UNLINK: defaults::libpng-1.6.27-vc14_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE UNLINK: defaults::setuptools-27.2.0-py36_1 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


===> REVERSING PACKAGE UNLINK: anaconda::conda-4.4.11-py36_0 <===
  prefix=C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)


done
Traceback (most recent call last):
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\core\link.py", line 770, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
    output=_format_output(command_str, path, rc, stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/d', '/c', 'C:\\Users\\srhodes\\AppData\\Local\\Continuum\\Anaconda3_(x86)\\Scripts\\.qt-post-link.bat']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\core\link.py", line 537, in _execute_actions
    run_script(target_prefix, prec, 'post-unlink' if is_unlink else 'post-link')
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\core\link.py", line 786, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package defaults::qt-5.6.2-vc14h6f76a7e_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Scripts\.qt-post-link.bat
==> script messages <==
<None>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\core\link.py", line 472, in _execute
    cls._execute_actions(pkg_idx, axngroup)
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\core\link.py", line 553, in _execute_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package defaults::qt-5.6.2-vc14h6f76a7e_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Scripts\.qt-post-link.bat
==> script messages <==
<None>



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\exceptions.py", line 789, in __call__
    return func(*args, **kwargs)
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\cli\install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\cli\install.py", line 285, in handle_txn
    unlink_link_transaction.execute()
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\core\link.py", line 225, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Lib\site-packages\conda\core\link.py", line 500, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package defaults::qt-5.6.2-vc14h6f76a7e_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\srhodes\AppData\Local\Continuum\Anaconda3_(x86)\Scripts\.qt-post-link.bat
==> script messages <==
<None>
```
