### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by desirehwh** [ContinuumIO/anaconda-issues#1493]
The following errors occured:

RuntimeError:
Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/osx-64/db-5.3.28-1.tar.bz2

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@desirehwh you are using an olde version of navigator. Could you upgrade to the latest version 1.4.2?

Please go to a terminal and type

`conda update anaconda-navigator`
