### ISSUE TITLE
miniconda-latest-linux-x86_64.sh is not latest

### ISSUE THREAD

**Issue by rth** [ContinuumIO/anaconda-issues#1494]
When using the `Miniconda-latest-linux-x86_64.sh` script from https://repo.continuum.io/miniconda/, one would expect to get the latest version of miniconda.

Instead, this downloads a version from 2015,
```bash
Miniconda-latest-Linux-x86_64.sh	25.9M	2015-08-24 12:34:00	42dac45eee5e58f05f37399adda45e85
```
which corresponds to `Miniconda2-4.0.5-Linux-x86_64.sh` (the latest version being `4.3.11`). 

The solution is to use `Miniconda2-latest-Linux-x86_64.sh` or `Miniconda3-latest-Linux-x86_64.sh`. 
However a [numer of people](https://github.com/search?q=Miniconda-latest-linux-x86_64.sh&type=Code&utf8=%E2%9C%93) are using the Miniconda-latest installer thinking, I believe, that they have the latest miniconda which is not the case. 

Could something be done about it? Possible solutions could be,
  - Make Miniconda-latest point to the latest PY2 installer
  - patch this installer with a warning mentionning it is outdated.

**Comment by ilanschnell** [comment]
Ah, this is because these installers are now either `Miniconda2` or `Miniconda3` (depending on which Python they come with).  I removed `Miniconda-latest-linux-x86_64.sh` to avoid confusion.

**Comment by rth** [comment]
@ilanschnell Great, thank you!

**Comment by rth** [comment]
@ilanschnell The same applies to `Miniconda-latest-Linux-armv7l.sh`, though fewer people are probably using it...

**Comment by MichaelCurrie** [comment]
It certainly tough love to [break 3,257 projects' CI tests](https://github.com/search?q=Miniconda-latest-linux-x86_64.sh&type=Code&utf8=%E2%9C%93) in order to get them to use the right Miniconda binary, but I have to admit it forced us to make the fix, and this is for the better.
