### ISSUE TITLE
Error during installation on Mac Os X

### ISSUE THREAD

**Issue by France1** [ContinuumIO/anaconda-issues#1495]
Hi, I am trying to install Anaconda on Mac Os X by running the command:

bash Anaconda2-4.3.0-MacOSX-x86_64.sh 

At the end of the installation I get the following error:

creating default environment...
/Users/francescobattocchio/anaconda2/bin/.openssl-post-link.sh: line 7:  1085 Segmentation fault: 11  $PREFIX/bin/.openssl-libcrypto-fix $PREFIX
Error: post-link failed for: openssl-1.0.2k-0

Can you help me?

Francesco

**Comment by VranjesHR** [comment]
I have exactly the same problem. Hoping someone can give us some inputs.

**Comment by ilanschnell** [comment]
What is the output the following two commands?
```
$ sw_vers
$ uname -a
```

**Comment by VranjesHR** [comment]
I get the following outputs for the mentioned commands...

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.6.8
BuildVersion:	10K549
$ uname -a
...10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:32:41 PDT 2011; root:xnu-1504.15.3~1/RELEASE_X86_64 x86_64

**Comment by ilanschnell** [comment]
Ah, you are using OSX `10.6` which is no longer supported by Anaconda.  The last Anaconda version which supports OSX 10.5 is Anaconda 1.8.  You can download the from: https://repo.continuum.io/archive/

**Comment by VranjesHR** [comment]
perfect, thank you!
