### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by gigicandy** [ContinuumIO/anaconda-issues#1497]
Anaconda Navigator Update error:

Extra data: line 2 column 1 - line 336 column 1 (char 79 - 27200)

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.3.9', 'qt': '5.6.2', 'language': 'en', 'python': '2.7.11', 'os': 'Darwin;16.3.0;Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'5.6.0'}

**Comment by goanpeca** [comment]
@gigicandy it seems you are using an outdated version of navigator. Could you open a terminal and type:

`conda update anaconda-navigator`

Cheers
