### ISSUE TITLE
Problem in launching

### ISSUE THREAD

**Issue by satyams407** [ContinuumIO/anaconda-issues#1499]
I am not able to launch sypder, qtconsole through anaconda navigator

**Comment by goanpeca** [comment]
@satyams407 could yo go to the terminal and type

`conda info`

and paste the output?

**Comment by satyams407** [comment]
![screenshot 758](https://cloud.githubusercontent.com/assets/13750239/24330649/f0abe966-1240-11e7-90a2-1fdfdf04d7a8.png)

**Comment by goanpeca** [comment]
@satyams407 there is an bug for launching apps with spaces on anaconda navigator. It is already fixed and will be released this week. sorry for the issues.
