### ISSUE TITLE
Anaconda won't open

### ISSUE THREAD

**Issue by newToTheGame** [ContinuumIO/anaconda-issues#1500]
Anaconda will start to initialize and just shutdown without flagging a crash on Mac

**Comment by newToTheGame** [comment]
conda info:
Current conda install:

               platform : osx-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/johnrasmussen/anaconda3  (writable)
    default environment : /Users/johnrasmussen/anaconda3
       envs directories : /Users/johnrasmussen/anaconda3/envs
                          /Users/johnrasmussen/.conda/envs
          package cache : /Users/johnrasmussen/anaconda3/pkgs
                          /Users/johnrasmussen/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/johnrasmussen/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

**Comment by goanpeca** [comment]
@newToTheGame could you open a terminal and run

`anaconda-navigator` and paste the error traceback (if any present)?

**Comment by SteveHotScoopsGaynor** [comment]
![image](https://cloud.githubusercontent.com/assets/26276815/23704357/6539f014-03fc-11e7-8cb5-2a14a0272eab.png)

I am on windows and get this error. Stopped being able to open the navigator a day or two ago.

**Comment by goanpeca** [comment]
could you please run on the terminal

`conda info`

and 

`conda list`

And paste the results here?

**Comment by SteveHotScoopsGaynor** [comment]
![image](https://cloud.githubusercontent.com/assets/26276815/23710611/3c614a70-0415-11e7-8e02-80210e306d77.png)
![image](https://cloud.githubusercontent.com/assets/26276815/23710636/4f624bc4-0415-11e7-955a-02cb3740d555.png)
![image](https://cloud.githubusercontent.com/assets/26276815/23710656/62c4c2b4-0415-11e7-8030-246bf32bf3a1.png)
![image](https://cloud.githubusercontent.com/assets/26276815/23710677/74b83820-0415-11e7-8180-0f9790ce98ed.png)
![image](https://cloud.githubusercontent.com/assets/26276815/23710692/8591d4f8-0415-11e7-93c3-a0b338f86978.png)
![image](https://cloud.githubusercontent.com/assets/26276815/23710705/94f611f2-0415-11e7-8adf-810fcfd83f2e.png)

**Comment by goanpeca** [comment]
@SteveHotScoopsGaynor it seems you are using an oudated version of Navigator. Could you update to the latest? On the anaconda command prompt please type:

`conda update anaconda-navigator`

**Comment by SteveHotScoopsGaynor** [comment]
![image](https://cloud.githubusercontent.com/assets/26276815/23711848/f8421190-0418-11e7-966d-faa1f10992d8.png)

**Comment by goanpeca** [comment]
Please try again :-)

**Comment by SteveHotScoopsGaynor** [comment]
I have tried multiple times, I think it may be down to my company's firewall. I have had problems installing packages with this error before.

**Comment by newToTheGame** [comment]
The program still fail silently I have tried uninstalling the whole program and reinstall on command line and graphic interface and it still fails silently

**Comment by newToTheGame** [comment]
I've even try updating everything from the command line

**Comment by goanpeca** [comment]
@newToTheGame you still have not provided the traceback when running from the terminal. Could you also provide `conda info` and `conda list` output?

Regards

**Comment by newToTheGame** [comment]
conda info:
platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/home/anaconda3  (writable)
    default environment : /Users/home/anaconda3
       envs directories : /Users/home/anaconda3/envs
                          /Users/home/.conda/envs
          package cache : /Users/home/anaconda3/pkgs
                          /Users/home/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/home/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.5.2 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

conda list:
# packages in environment at /Users/home/anaconda3:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.2.0                    py35_0  
alabaster                 0.7.9                    py35_0  
anaconda                  4.3.0               np111py35_0  
anaconda-client           1.6.0                    py35_0  
anaconda-navigator        1.4.3                    py35_0  
anaconda-project          0.4.1                    py35_0  
appnope                   0.1.0                    py35_0  
appscript                 1.0.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astroid                   1.4.9                    py35_0  
astropy                   1.3                 np111py35_0  
babel                     2.3.4                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.5.3                    py35_0  
bitarray                  0.8.1                    py35_0  
blaze                     0.10.1                   py35_0  
bokeh                     0.12.4                   py35_0  
boto                      2.45.0                   py35_0  
bottleneck                1.2.0               np111py35_0  
cffi                      1.9.1                    py35_0  
chardet                   2.3.0                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.7                      py35_0  
cloudpickle               0.2.2                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
conda                     4.3.14                   py35_0  
conda-build               1.21.3                   py35_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py35_0  
contextlib2               0.5.4                    py35_0  
cryptography              1.7.1                    py35_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py35_0  
cython                    0.25.2                   py35_0  
cytoolz                   0.8.2                    py35_0  
dask                      0.13.0                   py35_0  
datashape                 0.5.4                    py35_0  
decorator                 4.0.11                   py35_0  
dill                      0.2.5                    py35_0  
docutils                  0.13.1                   py35_0  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_0  
et_xmlfile                1.0.1                    py35_0  
fastcache                 1.0.2                    py35_1  
flask                     0.12                     py35_0  
flask-cors                3.0.2                    py35_0  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py35_0  
gevent                    1.2.1                    py35_0  
greenlet                  0.4.11                   py35_0  
h5py                      2.6.0               np111py35_2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py35_1  
icu                       54.1                          0  
idna                      2.2                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.5.2                    py35_0  
ipython                   5.1.0                    py35_1  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                5.2.2                    py35_1  
isort                     4.2.5                    py35_0  
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.3                      py35_0  
jedi                      0.9.0                    py35_1  
jinja2                    2.9.4                    py35_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            4.4.0                    py35_0  
jupyter_console           5.0.0                    py35_0  
jupyter_core              4.2.1                    py35_0  
lazy-object-proxy         1.2.2                    py35_0  
libdynd                   0.7.2                         0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.7.2                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                2.0.0               np111py35_0  
mistune                   0.7.3                    py35_1  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py35_3  
mpmath                    0.19                     py35_1  
multipledispatch          0.4.9                    py35_0  
nb_anacondacloud          1.1.0                    py35_0  
nb_conda                  1.1.0                    py35_0  
nb_conda_kernels          1.0.3                    py35_0  
nbconvert                 4.2.0                    py35_0  
nbformat                  4.2.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.2                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  4.3.1                    py35_0  
numba                     0.30.1              np111py35_0  
numexpr                   2.6.1               np111py35_2  
numpy                     1.11.3                   py35_0  
numpydoc                  0.6.0                    py35_0  
odo                       0.5.0                    py35_1  
openpyxl                  2.4.1                    py35_0  
openssl                   1.0.2k                        0  
pandas                    0.19.2              np111py35_1  
partd                     0.3.7                    py35_0  
path.py                   10.0                     py35_0  
pathlib2                  2.2.0                    py35_0  
patsy                     0.4.1                    py35_0  
pep8                      1.7.0                    py35_0  
pexpect                   4.2.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    4.0.0                    py35_0  
pip                       9.0.1                    py35_1  
ply                       3.9                      py35_0  
prompt_toolkit            1.0.9                    py35_0  
psutil                    5.0.1                    py35_0  
ptyprocess                0.5.1                    py35_0  
py                        1.4.32                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_1  
pycparser                 2.17                     py35_0  
pycrypto                  2.6.1                    py35_4  
pycurl                    7.43.0                   py35_2  
pyflakes                  1.5.0                    py35_0  
pygments                  2.1.3                    py35_0  
pylint                    1.6.4                    py35_1  
pyopenssl                 16.2.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_1  
pytables                  3.3.0               np111py35_0  
pytest                    3.0.5                    py35_0  
python                    3.5.2                         0  
python-dateutil           2.6.0                    py35_0  
python.app                1.2                      py35_4  
pytz                      2016.10                  py35_0  
pyyaml                    3.12                     py35_0  
pyzmq                     16.0.2                   py35_0  
qt                        5.6.2                         0  
qtawesome                 0.4.3                    py35_0  
qtconsole                 4.2.1                    py35_1  
qtpy                      1.2.1                    py35_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0  
requests                  2.12.4                   py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14                  py35_1  
scikit-image              0.12.3              np111py35_1  
scikit-learn              0.18.1              np111py35_1  
scipy                     0.18.1              np111py35_1  
seaborn                   0.7.1                    py35_0  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.5.1                    py35_0  
sphinx_rtd_theme          0.1.9                    py35_0  
spyder                    3.1.2                    py35_0  
sqlalchemy                1.1.5                    py35_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py35_1  
sympy                     1.0                      py35_0  
terminado                 0.6                      py35_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py35_0  
tornado                   4.4.2                    py35_0  
traitlets                 4.3.1                    py35_0  
unicodecsv                0.14.1                   py35_0  
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.11.15                  py35_0  
wheel                     0.29.0                   py35_0  
widgetsnbextension        1.2.6                    py35_0  
wrapt                     1.10.8                   py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.6                    py35_0  
xlwings                   0.10.2                   py35_0  
xlwt                      1.2.0                    py35_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3

**Comment by newToTheGame** [comment]
Traceback (most recent call last):
  File "/Users/home/anaconda3/lib/python3.5/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "/Users/home/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/home/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/home/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/home/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/home/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/home/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/home/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/home/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/home/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/home/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/home/anaconda3/lib/python3.5/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/home/anaconda3/lib/python3.5/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/home/.continuum/anaconda-client: Permission denied

**Comment by newToTheGame** [comment]
it opens with super user.

**Comment by goanpeca** [comment]
@newToTheGame you dont need to use as super user. You can run the following command and it should work:

`sudo rm -rf ~/.continuum/`
