### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by udayoo7** [ContinuumIO/anaconda-issues#1505]
The following errors occured:

None:
CondaHTTPError: HTTP None None for url <None>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authorization Required',)))",),)

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.3.11', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@udayoo7 you are using an old version of navigator, please update to the latest and try again.

Open a windows anaconda prompt and type

`conda update anaconda-navigator`

Also regarding your error, seems like a transient connectivity issues.
