### ISSUE TITLE
Can no longer open anaconda navigator on windows

### ISSUE THREAD

**Issue by SteveHotScoopsGaynor** [ContinuumIO/anaconda-issues#1509]
![image](https://cloud.githubusercontent.com/assets/26276815/23704396/a6e2f63c-03fc-11e7-92b9-1437d5b39aaa.png)

Up until very recently I could open the navigator fine. Now clicking on the shortcut causes the normal startup animations (green wheel) but nothing happens afterwards. Trying to open on the command line gives the above error.

**Comment by goanpeca** [comment]
Please type on the terminal

`conda info`

`conda list`

And paste the results here

**Comment by goanpeca** [comment]
Closing due to lack of response. The latest navigator should have fixed this
