### ISSUE TITLE
No conda tab on jupiter notebook

### ISSUE THREAD

**Issue by piovere** [ContinuumIO/anaconda-issues#1511]
After a fresh installation of Anaconda 4.3.0 on a mac, the Jupyter notebook does not show the Conda tab, and the "New" menu does not show any environments. This is true in both the root environment and a new environment, both of which had Jupyter installed.

I am seeing this issue on both Python 2.7 and 3.6 installations of Anaconda.

> (nuc) nechrg04:~ jrpowers-luhn$ jupyter notebook
> [I 18:35:48.034 NotebookApp] Serving notebooks from local directory: /Users/jrpowers-luhn
> [I 18:35:48.034 NotebookApp] 0 active kernels 
> [I 18:35:48.034 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=a4c0f0be0f3a2e66de5c5852228c22ac65286a5682f93b3e
> [I 18:35:48.034 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [C 18:35:48.034 NotebookApp] 
>     
>     Copy/paste this URL into your browser when you connect for the first time,
>     to login with a token:
>         http://localhost:8888/?token=a4c0f0be0f3a2e66de5c5852228c22ac65286a5682f93b3e
> [I 18:35:48.355 NotebookApp] Accepting one-time-token-authenticated connection from ::1
> 

![screen shot 2017-03-08 at 6 34 52 pm](https://cloud.githubusercontent.com/assets/3093805/23729107/248f0446-042e-11e7-9b3e-15b486ca1d1a.png)

**Comment by csoja** [comment]
We are no longer shipping the Jupyter Notebook Extensions in the Anaconda installer (starting with Anaconda v4.3) - which added those features to Jupyter.  They are still available in repo.continuum.io and you can use conda to install them.  The extensions are not yet available for Python 3.6.  For further instructions, please see https://docs.continuum.io/anaconda/jupyter-notebook-extensions
