### ISSUE TITLE
Anaconda update doesn't clean automatically older packages

### ISSUE THREAD

**Issue by SMH17** [ContinuumIO/anaconda-issues#1515]
I usually update packages with 

`conda update --all`

I have see that in `Anaconda3\pkgs `there are accumulated all older versions of updated packages that aren't needed anymore. That isn't good. Update task should clean older packages after the upgrade, not only download newer versions updating dependencies, deleting manually all older packages is very annoying. 

OS: Windows 10 x64

**Comment by nehaljwani** [comment]
This issue was moved to conda/conda#5347
