### ISSUE TITLE
Incorrectly marking a syntax error on print function

### ISSUE THREAD

**Issue by cpagravel** [ContinuumIO/anaconda-issues#1516]
I have the following line of code:
`print("%d%%   %d / %d\r" % (count / total * 100, count, total), end='\r')`

Anaconda is marking this as incorrect syntax. This is the correct syntax. It's not used very often, but it works. I use this to write over the last line of text in a console output. Using this I can make a download status indicator.

Is this reproducible for anyone else?

**Comment by nehaljwani** [comment]
If you are using `python 2.x`, then try adding to the top of your file:
```python
from __future__ import print_function
```

If you are still able to reproduce this issue, feel free to re-open with the output for the commands:
```bash
which python
conda list
```
