### ISSUE TITLE
Conda install theano UnsatisfiableError (Python3.6) Windows7

### ISSUE THREAD

**Issue by vladimircape** [ContinuumIO/anaconda-issues#1517]
I got such error. I delete Python2.7 some months ago, and can't install theano through conda

D:\Programms\Anaconda36\Scripts>conda info theano
Fetching package metadata ...........

theano 0.8.2 py27_0
-------------------
file name   : theano-0.8.2-py27_0.tar.bz2
name        : theano
version     : 0.8.2
build string: py27_0
build number: 0
channel     : defaults
size        : 3.6 MB
arch        : x86_64
date        : 2016-10-15
license     : BSD 3-Clause
license_family: BSD
md5         : 847f294850c6c38fc6c5d80802348163
noarch      : None
platform    : win32
url         : https://repo.continuum.io/pkgs/free/win-64/theano-0.8.2-py27_0.tar.bz2
dependencies:
    libpython >=2.0
    m2w64-toolchain
    mkl-service
    numpy >=1.3.0
    python 2.7*
    scipy >=0.7.0
    six >=1.9.0

theano 0.8.2 py34_0
-------------------
file name   : theano-0.8.2-py34_0.tar.bz2
name        : theano
version     : 0.8.2
build string: py34_0
build number: 0
channel     : defaults
size        : 3.7 MB
arch        : x86_64
date        : 2016-10-15
license     : BSD 3-Clause
license_family: BSD
md5         : 7d398562657e0698933d7f2563af3495
noarch      : None
platform    : win32
url         : https://repo.continuum.io/pkgs/free/win-64/theano-0.8.2-py34_0.tar.bz2
dependencies:
    libpython >=2.0
    m2w64-toolchain
    mkl-service
    numpy >=1.3.0
    python 3.4*
    scipy >=0.7.0
    six >=1.9.0

theano 0.8.2 py35_0
-------------------
file name   : theano-0.8.2-py35_0.tar.bz2
name        : theano
version     : 0.8.2
build string: py35_0
build number: 0
channel     : defaults
size        : 3.7 MB
arch        : x86_64
date        : 2016-10-15
license     : BSD 3-Clause
license_family: BSD
md5         : d636c509cce56297df6066e9601a073b
noarch      : None
platform    : win32
url         : https://repo.continuum.io/pkgs/free/win-64/theano-0.8.2-py35_0.tar.bz2
dependencies:
    libpython >=2.0
    m2w64-toolchain
    mkl-service
    numpy >=1.3.0
    python 3.5*
    scipy >=0.7.0
    six >=1.9.0

D:\Programms\Anaconda36\Scripts>conda install theano
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - theano -> python 2.7*
Use "conda info <package>" to see the dependencies for each package.

**Comment by csoja** [comment]
@ilanschnell @mingwandroid Looks like we do not have a Python 3.6 version of Theano on repo.continuum.io.

**Comment by mingwandroid** [comment]
@vladimircape, if you want to try the latest release candidate for theano 0.9 (which includes about a years worth of work) you can use `conda install -c rdonnelly theano`.

I was hoping not to have to build 0.8.x again but if upstream do not get the final 0.9 release done soon then I might have to.

**Comment by vladimircape** [comment]
Thanks guys.

**Comment by nehaljwani** [comment]
Closing as https://repo.continuum.io/pkgs/free/win-32/theano-0.9.0-py36_0.tar.bz2 is available in the defaults channel now.
