### ISSUE TITLE
ImportError when importing sklearn on jupyter on anaconda2 v 4.3.0.1 win-32bit OS

### ISSUE THREAD

**Issue by pharouhk** [ContinuumIO/anaconda-issues#1519]
In reply to @Ray Donelly-->
I always use cmd.exe or anaconda prompt to launch. Whenever I try to launch the anaconda navigator or jupyter notebook they never launch.
here is the output of the codes on the anaconda prompt terminal:
conda info:

Current conda install:

               platform : win-32
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
          package cache : C:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Windows/7 W
indows/6.1.7600

And:
conda list --show-channel-urls:

# packages in environment at C:\Anaconda:
#
_license                  1.1                      py27_1    defaults
alabaster                 0.7.9                    py27_0    defaults
anaconda                  4.3.0               np111py27_0    defaults
anaconda-client           1.6.0                    py27_0    defaults
anaconda-navigator        1.4.3                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astroid                   1.4.9                    py27_0    defaults
astropy                   1.3                 np111py27_0    defaults
babel                     2.3.4                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.5                      py27_0    defaults
beautifulsoup4            4.5.3                    py27_0    defaults
bitarray                  0.8.1                    py27_1    defaults
blaze                     0.10.1                   py27_0    defaults
bokeh                     0.12.4                   py27_0    defaults
boto                      2.45.0                   py27_0    defaults
bottleneck                1.2.0               np111py27_0    defaults
bzip2                     1.0.6                     vc9_3  [vc9]  defaults
cdecimal                  2.3                      py27_2    defaults
cffi                      1.9.1                    py27_0    defaults
chardet                   2.3.0                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.7                      py27_0    defaults
cloudpickle               0.2.2                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
comtypes                  1.1.2                    py27_0    defaults
conda                     4.3.8                    py27_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0                    py27_0    defaults
console_shortcut          0.1.1                    py27_1    defaults
contextlib2               0.5.4                    py27_0    defaults
cryptography              1.7.1                    py27_0    defaults
curl                      7.52.1                    vc9_0  [vc9]  defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.25.2                   py27_0    defaults
cytoolz                   0.8.2                    py27_0    defaults
dask                      0.13.0                   py27_0    defaults
datashape                 0.5.4                    py27_0    defaults
decorator                 4.0.11                   py27_0    defaults
dill                      0.2.5                    py27_0    defaults
docutils                  0.13.1                   py27_0    defaults
entrypoints               0.2.2                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_1    defaults
flask                     0.12                     py27_0    defaults
flask-cors                3.0.2                    py27_0    defaults
freetype                  2.5.5                     vc9_2  [vc9]  defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.0.5                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.2.1                    py27_0    defaults
greenlet                  0.4.11                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
h5py                      2.6.0               np111py27_2    defaults
hdf5                      1.8.15.1                  vc9_4  [vc9]  defaults
heapdict                  1.0.0                    py27_1    defaults
icu                       57.1                      vc9_0  [vc9]  defaults
idna                      2.2                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
ipaddress                 1.0.18                   py27_0    defaults
ipykernel                 4.5.2                    py27_0    defaults
ipython                   5.1.0                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                5.2.2                    py27_1    defaults
isort                     4.2.5                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jdcal                     1.3                      py27_0    defaults
jedi                      0.9.0                    py27_1    defaults
jinja2                    2.9.4                    py27_0    defaults
jpeg                      9b                        vc9_0  [vc9]  defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter_client            4.4.0                    py27_0    defaults
jupyter_console           5.0.0                    py27_0    defaults
jupyter_core              4.2.1                    py27_0    defaults
lazy-object-proxy         1.2.2                    py27_0    defaults
libpng                    1.6.27                    vc9_0  [vc9]  defaults
libtiff                   4.0.6                     vc9_3  [vc9]  defaults
llvmlite                  0.15.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.7.2                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                2.0.0               np111py27_0    defaults
menuinst                  1.4.4                    py27_0    defaults
mistune                   0.7.3                    py27_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py27_3    defaults
mpmath                    0.19                     py27_1    defaults
multipledispatch          0.4.9                    py27_0    defaults
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.2.0                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2.2                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  4.3.1                    py27_1    defaults
numba                     0.30.1              np111py27_0    defaults
numexpr                   2.6.1               np111py27_2    defaults
numpy                     1.11.3                   py27_0    defaults
numpydoc                  0.6.0                    py27_0    defaults
odo                       0.5.0                    py27_1    defaults
openpyxl                  2.4.1                    py27_0    defaults
openssl                   1.0.2k                    vc9_0  [vc9]  defaults
pandas                    0.19.2              np111py27_1    defaults
partd                     0.3.7                    py27_0    defaults
path.py                   10.0                     py27_0    defaults
pathlib2                  2.2.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    4.0.0                    py27_0    defaults
pip                       9.0.1                    py27_1    defaults
ply                       3.9                      py27_0    defaults
prompt_toolkit            1.0.9                    py27_0    defaults
psutil                    5.0.1                    py27_0    defaults
py                        1.4.32                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycosat                   0.6.1                    py27_1    defaults
pycparser                 2.17                     py27_0    defaults
pycrypto                  2.6.1                    py27_5    defaults
pycurl                    7.43.0                   py27_2    defaults
pyflakes                  1.5.0                    py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pylint                    1.6.4                    py27_1    defaults
pyopenssl                 16.2.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyqt                      5.6.0                    py27_2    defaults
pytables                  3.2.2               np111py27_4    defaults
pytest                    3.0.5                    py27_0    defaults
python                    2.7.13                        0    defaults
python-dateutil           2.6.0                    py27_0    defaults
pytz                      2016.10                  py27_0    defaults
pywin32                   220                      py27_2    defaults
pyyaml                    3.12                     py27_0    defaults
pyzmq                     16.0.2                   py27_0    defaults
qt                        5.6.2                     vc9_3  [vc9]  defaults
qtawesome                 0.4.3                    py27_0    defaults
qtconsole                 4.2.1                    py27_2    defaults
qtpy                      1.2.1                    py27_0    defaults
requests                  2.12.4                   py27_0    defaults
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_1    defaults
scandir                   1.4                      py27_0    defaults
scikit-image              0.12.3              np111py27_1    defaults
scikit-learn              0.18.1              np111py27_1    defaults
scipy                     0.18.1              np111py27_1    defaults
seaborn                   0.7.1                    py27_0    defaults
setuptools                27.2.0                   py27_1    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sphinx                    1.5.1                    py27_0    defaults
spyder                    3.1.2                    py27_0    defaults
sqlalchemy                1.1.5                    py27_0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.6.1               np111py27_1    defaults
subprocess32              3.2.7                    py27_0    defaults
sympy                     1.0                      py27_0    defaults
tk                        8.5.18                    vc9_0  [vc9]  defaults
toolz                     0.8.2                    py27_0    defaults
tornado                   4.4.2                    py27_0    defaults
traitlets                 4.3.1                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
vs2008_runtime            9.00.30729.5054               0    defaults
wcwidth                   0.1.7                    py27_0    defaults
werkzeug                  0.11.15                  py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        1.2.6                    py27_0    defaults
win_unicode_console       0.5                      py27_0    defaults
wrapt                     1.10.8                   py27_0    defaults
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.6                    py27_0    defaults
xlwings                   0.10.2                   py27_0    defaults
xlwt                      1.2.0                    py27_0    defaults
zlib                      1.2.8                     vc9_3  [vc9]  defaults

**Comment by mingwandroid** [comment]
From the Anaconda Prompt, please try to run with:

Jupyter notebook

And paste the output.

**Comment by pharouhk** [comment]
it runs the jupyter notebook well.
the issue arises in importing sklearn library on the notebook. sorry I was not clear on that I was referred here from anaconda public and instructed to display the outputs of those codes.

**Comment by pharouhk** [comment]
when I type import sklearn this is what I get:


import sklearn

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8fd979e02004> in <module>()
----> 1 import sklearn

C:\Anaconda2\lib\site-packages\sklearn\__init__.py in <module>()
     55 else:
     56     from . import __check_build
---> 57     from .base import clone
     58     __check_build  # avoid flakes unused variable error
     59 

C:\Anaconda2\lib\site-packages\sklearn\base.py in <module>()
     10 from scipy import sparse
     11 from .externals import six
---> 12 from .utils.fixes import signature
     13 from .utils.deprecation import deprecated
     14 from .exceptions import ChangedBehaviorWarning as _ChangedBehaviorWarning

C:\Anaconda2\lib\site-packages\sklearn\utils\__init__.py in <module>()
      9 
     10 from .murmurhash import murmurhash3_32
---> 11 from .validation import (as_float_array,
     12                          assert_all_finite,
     13                          check_random_state, column_or_1d, check_array,

C:\Anaconda2\lib\site-packages\sklearn\utils\validation.py in <module>()
     16 
     17 from ..externals import six
---> 18 from ..utils.fixes import signature
     19 from .deprecation import deprecated
     20 from ..exceptions import DataConversionWarning as _DataConversionWarning

C:\Anaconda2\lib\site-packages\sklearn\utils\fixes.py in <module>()
    289     from ._scipy_sparse_lsqr_backport import lsqr as sparse_lsqr
    290 else:
--> 291     from scipy.sparse.linalg import lsqr as sparse_lsqr
    292 
    293 

C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\__init__.py in <module>()
    114 from .interface import *
    115 from .eigen import *
--> 116 from .matfuncs import *
    117 from ._onenormest import *
    118 from ._norm import *

C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\matfuncs.py in <module>()
     17 import numpy as np
     18 
---> 19 import scipy.misc
     20 from scipy.linalg.basic import solve, solve_triangular
     21 

C:\Anaconda2\lib\site-packages\scipy\misc\__init__.py in <module>()
     49 from .common import *
     50 from numpy import who, source, info as _info
---> 51 from scipy.special import comb, factorial, factorial2, factorialk
     52 
     53 import sys

C:\Anaconda2\lib\site-packages\scipy\special\__init__.py in <module>()
    634 from __future__ import division, print_function, absolute_import
    635 
--> 636 from ._ufuncs import *
    637 
    638 from .basic import *

ImportError: DLL load failed: The specified procedure could not be found.
