### ISSUE TITLE
rpy2 import error due to libreadline undefined symbol

### ISSUE THREAD

**Issue by Horta** [ContinuumIO/anaconda-issues#152]
``` bash
> conda --version
```

```
conda 3.5.5
```

``` bash
> echo "import rpy2.robjects" > foo.py
> python foo.py
```

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import rpy2.robjects
  File "/homes/horta/research/software/opt/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "/homes/horta/research/software/opt/anaconda/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 100, in <module>
    from rpy2.rinterface._rinterface import *
ImportError: /nfs/research2/stegle/software/opt/anaconda/bin/../lib/libreadline.so.6: undefined symbol: PC
```

The same does not happen if ipython is used, or if I perform the same under an interactive python session. rpy2 was installed using pip.

By the way:

``` bash
> which python
```

```
/homes/horta/research/software/opt/anaconda/bin/python
```

``` bash
> which ipython
```

```
/homes/horta/research/software/opt/anaconda/bin/ipython
```

And the following linking between folders is true: /homes/horta/research -> /nfs/research/stegle/ -> /nfs/research2/stegle/

**Comment by xgdgsc** [comment]
I also get this error today when trying to run rpy2 tests. Can it be fixed?

**Comment by ccordoba12** [comment]
I think this is going to be fixed when we fix issue #42. I'll test it tomorrow.

**Comment by ccordoba12** [comment]
Or maybe not =p. The cause of this problem seems to be conda's readline is not linked against ncurses.

**Comment by asmeurer** [comment]
Try to manually install my readline (`conda install -c asmeurer readline`). That is linked against ncurses.

**Comment by tacaswell** [comment]
We are also having issues with this at BNL.

attn @danielballan

**Comment by asmeurer** [comment]
@tacaswell , does my readline fix it?

**Comment by tacaswell** [comment]
We independently found a version that works on some machines but not others (https://github.com/NSLS-II/conda-prescriptions/tree/master/releases/readline/6.2 , a 6.2.5 recipe is in one of my branches and built versions are on my channels).

It seems to work in an ubuntu box, but am having issues finding `libtinfo` during the link step on an arch linux box.  I am sort of baffled as libtinfo and libreadline are in the same directory, `ldd libreadline` finds the correct libtinfo, but during the linking stage `ld` does not find find libtinfo, but _does_ find libreadline.  It is also part of a rather complicated build (epics-base) which does not use auto* tool chain and with a pre-release build of gcc so lots of confounding issues. 

If I have have time tonight I will try your readline on my arch system and @danielballan is on the osx issue (which is slightly different as it does not find `_BC`).

Which is a very long way to say I don't know, but I will get back to you.

**Comment by danielballan** [comment]
@asmeurer Thanks for the suggestion, but unfortunately the readline on your channel breaks worse. Instead of not finding what it needs in readline, it can't even locate the readline lib.

```
/Users/dallan/miniconda/envs/_build/epics/bin/darwin-x86/antelope -l -d ../parse.y
dyld: Library not loaded: @rpath/./libreadline.6.2.dylib
  Referenced from: /Users/dallan/miniconda/envs/_build/epics/lib/darwin-x86/libCom.3.14.12.dylib
  Reason: image not found
```

**Comment by asmeurer** [comment]
Oh that would mean that you'll have to rebuild the conda package that has libCom with the newest version of conda-build (an unfortunate side-effect of the switch to using `@rpath` in the install names on OS X).

**Comment by tacaswell** [comment]
`libCom` is one of the things being built in this recipe.

**Comment by asmeurer** [comment]
Are you using the latest version of conda-build? Where is the recipe?

**Comment by tacaswell** [comment]
Either recipe in this folder: https://github.com/tacaswell/conda-prescriptions/tree/working/releases/epics-base

And I believe latest version of conda-build everywhere we have tried this.

**Comment by tacaswell** [comment]
And no luck on my mis-behaving linux system with your readline/ncurses

```
/usr/bin/g++ -o antelope  -L/home/tcaswell/.virtualenvs/_build/epics/lib/linux-x86_64 -Wl,-rpath,/home/tcaswell/.virtualenvs/_build/epics/lib/linux-x86_64       -m64                closure.o error.o lalr.o lr0.o main.o mkpar.o output.o reader.o skeleton.o symtab.o verbose.o warshall.o   -lCom   
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `PC'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `tgetflag'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `tgetent'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `UP'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `tputs'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `tgoto'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `tgetnum'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `BC'
/home/tcaswell/.virtualenvs/_build/lib/libreadline.so.6: undefined reference to `tgetstr'
collect2: error: ld returned 1 exit status
```

**Comment by jeffalstott** [comment]
+1 person this happening to. I used @mattexx's workaround:

```
import readline
import rpy2.robjects
```

**Comment by cbonilla20** [comment]
I used 

    import readline
    import rpy2.robjects

and works for me, but is a little bit dirty solution.

**Comment by jseabold** [comment]
I just ran into this or similar issue with R 3.2.2 installed via apt-get from `http://cran.rstudio.com/bin/linux/ubuntu trusty/` while doing a fresh install with miniconda.

```
$ R
/usr/lib/R/bin/exec/R: /home/ubuntu/miniconda3/lib/liblzma.so.5: no version information available (required by /usr/lib/R/lib/libR.so)
/usr/lib/R/bin/exec/R: symbol lookup error: /home/ubuntu/miniconda3/lib/libreadline.so.6: undefined symbol: PC
$ conda --version
conda 3.16.0
```

Installing readline from Aaron's channel didn't help. Copying over the system readline shared objects to `~/miniconda3/lib` seemed to have done the trick for better or worse.

**Comment by yerfdogyrag** [comment]
OK, I really cheated here.  Just copied:

cp -p /lib/x86_64-linux-gnu/libreadline.so.6 ~/anaconda/lib/libreadline.so.6

Running ubuntu utopic

**Comment by lzamparo** [comment]
I also just ran into this issue with R 3.2.2 installed via [rocker/r-devel](https://hub.docker.com/u/rocker/).  

```
Pulling repository lzamparo/fithic
Traceback (most recent call last):
  File "/src/fit_hic/fit-hi-c-fixedSize-withBiases.py", line 36, in <module>
    import rpy2.robjects as ro
  File "/root/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "/root/anaconda/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 100, in <module>
    from rpy2.rinterface._rinterface import *
ImportError: /root/anaconda/lib/libreadline.so.6: undefined symbol: PC
```

Strangely this only happens in a non-interactive docker session.  Importing readline prior to importing Rpy2 seems to work:

```
[zamparol@gpu-1-14 ~]$ docker run -t -e PATH="/root/anaconda/bin:$PATH" lzamparo/fithic:ready python -c "import numpy as np; import rpy2.robjects as ro"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "/root/anaconda/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 100, in <module>
    from rpy2.rinterface._rinterface import *
ImportError: /root/anaconda/lib/libreadline.so.6: undefined symbol: PC


[zamparol@gpu-1-14 ~]$ docker run -t -e PATH="/root/anaconda/bin:$PATH" lzamparo/fithic:ready python -c "import numpy as np; import readline; import rpy2.robjects as ro; print np.__version__"
1.9.3
[zamparol@gpu-1-14 ~]$
```

**Comment by rleonid** [comment]
Any updates?

**Comment by wmvanvliet** [comment]
so, is this going to be fixed?

**Comment by titipata** [comment]
I still have a problem with kernel die on OSX. Is there any solution for OSX? I installed `rpy2` using pip, i.e. `pip install rpy2==2.7.8` and `conda --version` > `conda 3.14.1`

**Comment by abjer** [comment]
I also have the issue and have been unable to solve it.

**Comment by toinsson** [comment]
same here, temporay fix for me is to remove conda readline from the environment:

    conda remove --force readline

and install the python bindings with `pip install readline`.

That way, I  presume it is using the system `readline`.

**Comment by lidaof** [comment]
@toinsson's solution works for me. thanks.

**Comment by cstich** [comment]
@toinsson's solution also worked for me.

**Comment by iacercalixto** [comment]
@toinsson's solution worked here too.

Some more info: I wasn't being able to open the bc binary (in /usr/bin/bc) and was previously getting the following error:

bc: symbol lookup error: /home/icalixto/anaconda2/lib/libreadline.so.6: undefined symbol: PC

After the workaround suggested, it now works again.

**Comment by jhamrick** [comment]
I also just ran into this issue. @toinsson's workaround works for me as well.

**Comment by yourinoelnelson** [comment]
Ran into the same issue with conda version 4.2.9 while trying to install the R kernell, got the libreadline.so.6: undefined symbol: PC error while trying to install git2r package. The work around seem to solve that issue.

**Comment by stringhamc** [comment]
@toinsson workaround worked for me, I also had to do a 'pip uninstall readline' as well.

**Comment by mingwandroid** [comment]
Can you try:

`conda install -c rdonnellyr r-base`

**Comment by tbonza** [comment]
This was an issue for me too. Using Fedora 25, Python 3.5, IPython, R version 3.3.2. Successful workaround:

```
$ vi ~/.bashrc
# Rpy2
export LD_LIBRARY_PATH="/usr/lib64/R/lib:$LD_LIBRARY_PATH"
$ source ~/.bashrc
$ sudo dnf -y install readline-devel
$ ipython
[1] import readline
[2] import rpy2.robjects
[3] import pandas.rpy.common as com
```

The use case here is reading in an SPSS file. See "[Is there a Python module to open SPSS files?](http://stackoverflow.com/questions/14647006/is-there-a-python-module-to-open-spss-files)" for more details on my use case

**Comment by mingwandroid** [comment]
Conda now has R 3.3.2, if you use that you should not need to use your system R and then you should not need to set `LD_LIBRARY_PATH` either.

**Comment by tbonza** [comment]
That's a good point. I'm actually using miniconda but forgot to mention it. LD_LIBRARY_PATH will still be necessary for miniconda, right?

**Comment by mingwandroid** [comment]
I'm not sure what you mean. Provided you use the `conda defaults` channels to get rpy2 and R you do not need to use `LD_LIBRARY_PATH`, regardless of whether you installed from `Anaconda` or `Miniconda` initially.

If you try to mix conda software with non-conda software then hacks like setting `LD_LIBRARY_PATH` may become necessary.

**Comment by tbonza** [comment]
Oh okay, I'll try installing R from conda default and see if that resolves the issue. Happy holidays!

**Comment by mingwandroid** [comment]
@tbonza, can this be closed now?

**Comment by tbonza** [comment]
Yes, thanks!

**Comment by mingwandroid** [comment]
Thank you for the confirmation.

**Comment by docsteveharris** [comment]
I have this problem on Mac OS 10.13, and @toinsson's  solution didn't work

```
(root) ~ ❯❯❯ R                                                                            ⏎
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/steve/anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
[1]    6747 abort      R
```
