### ISSUE TITLE
Changing timeout limit when using conda install

### ISSUE THREAD

**Issue by stevenwong** [ContinuumIO/anaconda-issues#1520]
Hi all,

I have been trying to create a Python 3.4 environment with the latest installer, which I  managed to get through the early part fine. It downloads the first few packages but hangs at 99% then subsequently times out when it gets to this package.

https://repo.continuum.io/pkgs/free/win-64/qt-5.6.2-vc14_3.tar.bz2

I can download it manually in Chrome but it has a similar behaviour - getting stuck at 55.2/55.3mb and stays there for a while before completing. I'm behind a proxy but I do have the correct proxy settings in .condarc. Is there a way to change the timeout limit when I'm downloading it through conda?

Cheers

**Comment by nehaljwani** [comment]
Closing this issue as `Python 3.4` is no longer supported. Please reopen the ticket if you face the same issue with `Python >= 3.5` and latest version of `Conda`.
