### ISSUE TITLE
Cannot Install qt and Cannot Open Anaconda Navigator 

### ISSUE THREAD

**Issue by PauliusMaximus** [ContinuumIO/anaconda-issues#1524]
New user to Anaconda and Jupyter.

I do not have qt installed and run into problems trying to update it or install it. When I try to open Anaconda Navigator nothing happens whatsoever not even an error message.

Really unsure as to how to proceed. Please see attached screenshot for hopefully useful information.

![screencapture](https://cloud.githubusercontent.com/assets/26446410/23974806/3f3deed8-09ab-11e7-9ad2-ca8ca9f3454e.PNG)

Thanks - Much appreciated

Paul

**Comment by mingwandroid** [comment]
Something has gone very wrong during installation. Qt comes with Anaconda and Navigator should work without needing to do anything.

Please uninstall, then disable your virus scanner temporarily and reinstall. You should probably install for Just Me into your user directory and elect not to add Python to your system path.
