### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by VeronicaBehrens** [ContinuumIO/anaconda-issues#1528]
Near the end of Anaconda 4.3.1 Python 2 Navigator installation on Windows (64 bit), get the error "Failed to create Anaconda menus."  After "ignoring" get another error: "Failed to initialize Anaconda directories."  And after ignoring that error: "Failed to add Anaconda to the system PATH."  Note:  I uninstalled a previous version of Anaconda about a year ago.

**Comment by goanpeca** [comment]
@ilanschnell ?

**Comment by VeronicaBehrens** [comment]
@ilanschnell @goanpeca I get the same error messages when I try to install Anaconda 4.3.1 Python 3 Navigator on Windows (64 bit).  Any ideas how to fix this?

**Comment by ilanschnell** [comment]
Which version of Windows are you using?  CC @msarahan

**Comment by VeronicaBehrens** [comment]
Windows 10

**Comment by cecbur** [comment]
Me too. Same version.

**Comment by shelbymustang** [comment]
Still happening.  Had a similar issue with machine names that have a space in them for Vagrant.  Could this be similar?   Is there a manual way to fix (adding PATH or other ENV variables?)  Its obviously at the end of the process and all files are in place successfully.

**Comment by shelbymustang** [comment]
Updating my comment above.   As mentioned above I had a similar issue with Vagrant.   This time I went ahead and modified the user name on the Windows account to not have a space (or special character like Main-Computer)   Seems to have solved this problem for me.

**Comment by y2kbugger** [comment]
See #732, #1775 

Look like this is still a problem in 4.4.0 according to:
#2352

**Comment by goanpeca** [comment]
Tracking on #2352
