### ISSUE TITLE
Anaconda Navigator won't launch after reboot

### ISSUE THREAD

**Issue by Pelonza** [ContinuumIO/anaconda-issues#1529]
I've installed the full 64-bit anaconda distribution without any trouble.
When I first install it, I can open all the associated menu items (like the navigator) without any problems.

However, after rebooting my computer the navigator won't open again using the created short-cuts, or trying to directly run from the executables or scripts.

All the other menu short-cuts seem to work just fine. I guess I'm going to have to get better with command-line usage...but the gui is nicer... 

I've tried reinstalling anaconda several times and get exactly the same behavior. It opens just fine immediately after installing, but not after reboot. I'm guessing this is actually on my end, not an installer issue, but I figured someone here ought to have a better idea what is lost on reboot than my tech support.

**Comment by goanpeca** [comment]
@Pelonza could you go to the anaconda prompt (if on windows) or the terminal and type

`conda info`

`conda list` and paste the results here?

Thanks

**Comment by Pelonza** [comment]
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
                          C:\Users\kschmit1\AppData\Local\conda\conda\envs
                          C:\Users\kschmit1\.conda\envs
          package cache : C:\Anaconda3\pkgs
                          C:\Users\kschmit1\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\kschmit1\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.10586

# packages in environment at C:\Anaconda3:
#
_nb_ext_conf              0.2.0                    py35_0
alabaster                 0.7.8                    py35_0
anaconda                  4.1.1               np111py35_0
anaconda-client           1.4.0                    py35_0
anaconda-navigator        1.2.1                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.2.1               np111py35_0
babel                     2.3.3                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.0                   py35_0
boto                      2.40.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.6.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.14                   py35_1
conda-build               1.21.3                   py35_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.4                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24                     py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.10.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.1                    py35_0
glueviz                   0.9.1                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.3.1                    py35_0
ipython                   4.2.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.1                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           4.1.1                    py35_0
jupyter_core              4.1.0                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.11.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.0                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.1               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.2                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.1.0                    py35_0
nb_conda                  1.1.0                    py35_0
nb_conda_kernels          1.0.3                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.0.1                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.1                    py35_0
numba                     0.26.0              np111py35_0
numexpr                   2.6.0               np111py35_0
numpy                     1.11.1                   py35_0
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2h                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0
partd                     0.3.4                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.2                    py35_0
pillow                    3.2.0                    py35_1
pip                       8.1.2                    py35_0
ply                       3.8                      py35_0
psutil                    4.3.0                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.2.3                    py35_0
pygments                  2.1.3                    py35_0
pyopenssl                 16.2.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      4.11.4                   py35_6
pyreadline                2.1                      py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.4                   py35_0
pywin32                   220                      py35_1
pyyaml                    3.11                     py35_4
pyzmq                     15.2.0                   py35_0
qt                        4.8.7                    vc14_8  [vc14]
qtconsole                 4.2.1                    py35_0
qtpy                      1.2.1                    py35_0
requests                  2.13.0                   py35_0
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_1
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.17.1              np111py35_1
setuptools                23.0.0                   py35_0
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.16.9                   py35_2
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.1                    py35_0
sphinx_rtd_theme          0.1.9                    py35_0
spyder                    2.3.9                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.3                      py35_1
traitlets                 4.2.1                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
werkzeug                  0.11.10                  py35_0
wheel                     0.29.0                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.2                    py35_0
xlwings                   0.7.2                    py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by goanpeca** [comment]
@Pelonza did you install Anaconda for all users or current user? In general we advice the later

**Comment by Pelonza** [comment]
I'm done both. I think the most recent install was for all users.

To schedule a meeting or appointment try:
https://karlrbschmitt.youcanbook.me/

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana

**Comment by goanpeca** [comment]
@Pelonza I would advice to use the latest installer for current user and if possible with no spaces or unicode characters in the path. We are issuing a fix for this, but in the meantime is the only way to avoid some subtle path issues.

**Comment by JulesVerny** [comment]
Got the same problem Anaconda Navigator failed to Launch to work after Windows  10 Creators Update Installed (Was working OK on Windows 64 bit before) 

Current conda install:
               platform : win-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
                          C:\Users\Julia\AppData\Local\conda\conda\envs
                          C:\Users\Julia\.conda\envs
          package cache : C:\Anaconda3\pkgs
                          C:\Users\Julia\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
           user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.15063

_nb_ext_conf              0.2.0                    py35_0
alabaster                 0.7.8                    py35_0
anaconda                  4.1.1               np111py35_0
anaconda-client           1.4.0                    py35_0
anaconda-navigator        1.2.2                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.2.1               np111py35_0
babel                     2.3.3                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.0                   py35_0
boto                      2.40.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.6.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
cmake                     3.6.3                    vc14_0  [vc14]
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.16                   py35_0
conda-build               1.21.3                   py35_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.4                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24                     py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.10.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.1                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.3.1                    py35_0
ipython                   4.2.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.1                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           4.1.1                    py35_0
jupyter_core              4.1.0                    py35_0
Keras                     2.0.2                     <pip>
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.11.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.0                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.1               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.2                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.1.0                    py35_0
nb_conda                  1.1.0                    py35_0
nb_conda_kernels          1.0.3                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.0.1                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.1                    py35_0
numba                     0.26.0              np111py35_0
numexpr                   2.6.0               np111py35_0
numpy                     1.11.1                   py35_0
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2h                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0
partd                     0.3.4                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.2                    py35_0
pillow                    3.2.0                    py35_1
pip                       8.1.2                    py35_0
pip                       9.0.1                     <pip>
ply                       3.8                      py35_0
protobuf                  3.2.0                     <pip>
psutil                    4.3.0                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.2.3                    py35_0
pyglet                    1.2.4                     <pip>
pygments                  2.1.3                    py35_0
pyopenssl                 16.2.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      4.11.4                   py35_6
pyreadline                2.1                      py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.4                   py35_0
pywin32                   220                      py35_1
pyyaml                    3.11                     py35_4
pyzmq                     15.2.0                   py35_0
qt                        4.8.7                    vc14_8  [vc14]
qtconsole                 4.2.1                    py35_0
qtpy                      1.0.2                    py35_0
requests                  2.13.0                   py35_0
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_1
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.17.1              np111py35_1
setuptools                23.0.0                   py35_0
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.16.9                   py35_2
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.1                    py35_0
sphinx_rtd_theme          0.1.9                    py35_0
spyder                    2.3.9                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tensorflow-gpu            1.0.1                     <pip>
tflearn                   0.3                       <pip>
Theano                    0.9.0                     <pip>
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.3                      py35_1
traitlets                 4.2.1                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
werkzeug                  0.11.10                  py35_0
wheel                     0.29.0                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.2                    py35_0
xlwings                   0.7.2                    py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by mradultiw** [comment]
@goanpeca 
Hi !
I'm facing similar issue. I've been using anaconda for past few months and every thing (jupyter, spyder) was working just fine. However past few days since I've installed Ubuntu on VBox, anaconda is behaving like sick. Every time i start the laptop and try to run jupyter/spyder none of them starts and each time when I run "conda update anaconda" then it don't download any new packages rather shows that I'm on latest but jup/spy both starts working untill next poweron! Isn't this very strange!!!

(As far as I remember, I haven't made any big changes to my machine but installed ubuntu as said).

Any suggestions are heartily welcomed.

**Comment by Godstrump** [comment]
I have got the same issue 
On install my anaconda works just until a system restart and anytime I open it it opens up a prompt for me 
My anaconda version is 4.7.

**Comment by MohamedSaiedEssa** [comment]
same here

Microsoft Windows [Version 10.0.19044.1865]
(c) Microsoft Corporation. All rights reserved.

C:\Users\msaied>cd C:\Anaconda\Scripts
The system cannot find the path specified.

C:\Users\msaied>C:\ProgramData\Anaconda3\Scripts
'C:\ProgramData\Anaconda3\Scripts' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\msaied>cd C:\ProgramData\Anaconda3\Scripts

C:\ProgramData\Anaconda3\Scripts>activate root
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
    from ..activate import main as activator_main
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\activate.py", line 9, in <module>
    from tempfile import NamedTemporaryFile
  File "C:\ProgramData\Anaconda3\lib\tempfile.py", line 43, in <module>
    import shutil as _shutil
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 22, in <module>
    import bz2
  File "C:\ProgramData\Anaconda3\lib\bz2.py", line 19, in <module>
    from threading import RLock
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916
    '                self.run()
    ^
IndentationError: expected an indented block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 108, in main
    init_loggers()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 54, in init_loggers
    from logging import CRITICAL, getLogger
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 41, in <module>
    import threading
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916
    '                self.run()
    ^
IndentationError: expected an indented block

C:\ProgramData\Anaconda3\Scripts>activate root
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
    from ..activate import main as activator_main
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\activate.py", line 9, in <module>
    from tempfile import NamedTemporaryFile
  File "C:\ProgramData\Anaconda3\lib\tempfile.py", line 43, in <module>
    import shutil as _shutil
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 22, in <module>
    import bz2
  File "C:\ProgramData\Anaconda3\lib\bz2.py", line 19, in <module>
    from threading import RLock
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916
    '                self.run()
    ^
IndentationError: expected an indented block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 108, in main
    init_loggers()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 54, in init_loggers
    from logging import CRITICAL, getLogger
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 41, in <module>
    import threading
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916
    '                self.run()
    ^
IndentationError: expected an indented block

C:\ProgramData\Anaconda3\Scripts>conda update -n root conda
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 7, in <module>
    from logging import getLogger
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 41, in <module>
    import threading
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916
    '                self.run()
    ^
IndentationError: expected an indented block
