### ISSUE TITLE
Offline manuals for python package in Anaconda: don't you have such?

### ISSUE THREAD

**Issue by Felix-neko** [ContinuumIO/anaconda-issues#1530]
Our students sometimes have to work offline. They have Python interpreter from Anaconda kit, they have PyCharm, but don't have manuals for the Python packages they have (only for a few they have downloaded).

Can you tell me, don't you have a pack of offline versions of the manuals for your python packages?

**Comment by electronwill** [comment]
(cc @cio-docs )

Currently you can download and install offline documentation for Anaconda with the command "conda install continuum-docs". These docs will install the html files locally, and you can open them in a browser and view them locally. For example, I have Anaconda with Python 3 on macOS, and after running this command I can open the index file on my machine with the command "open ~/anaconda3/pkgs/continuum-docs-2.0.7-0/share/doc/continuum/index.html".

This includes the documentation for Anaconda, but not the documentation for all 700+ Python packages available in Anaconda. Each of these projects maintains their own documentation at their own web site.

We are considering including documentation for the top 20 most commonly used packages in a future Anaconda release, and this would also be available in the offline documentation, and in a single large downloadable PDF file from the web site. Thank you for letting us know that you and your students are interested in this feature.

**Comment by Felix-neko** [comment]
Well, we really need the feature.

**Comment by electronwill** [comment]
To get offline documents for some of these open source projects sooner, you could track down each project's documentation and save a local copy. For example, the documentation for NumPy is at https://github.com/numpy/numpy/tree/master/doc .

**Comment by electronwill** [comment]
Actually, we have decided to work on adding documentation for all 720 packages as soon as possible. It is almost certain to be available for next school year.

**Comment by Felix-neko** [comment]
Really? That will be brilliant!

**Comment by Allenite** [comment]
Checking in on this.  Is it still in the works?

Thank you for doing this!

**Comment by kerrywatson1** [comment]
We have added a conda package for Python and other popular OSS packages. The package is updated every 2 weeks. 

From the command line, get your copy with "conda install anaconda-docs".

Or in Anaconda Navigator, use the Environments tab to select packages "Not installed." Then in the "Search packages" box type "anaconda-docs".

**Comment by electronwill** [comment]
Building out an automated system to repackage up to date docs for open source projects has proved time consuming in some cases, so it will be a while before we have all 720 packages, but we're continuing to add them a few at a time. The "anaconda-docs" package has the documentation from docs.anaconda.com, which covers most projects developed by Anaconda. The "anaconda-oss-docs" package has documentation for other open source projects included in Anaconda, including Python, conda, NumPy, SciPy, Pandas, Blaze, Dask, Jupyter, Pip, and others.

**Comment by deszoeke** [comment]
This should be very useful for traveling and working in the field.

How does one access the anaconda-docs or anaconda-oss-docs?

Install and then point browser to some local anaconda-docs? Load a certain PDF? I guess I'm looking for the documentation on the docs package.

**Comment by kwells-anaconda** [comment]
You can access the online docs here: https://docs.anaconda.com/ and select PDF in the version selector in the bottom right of the page to download a .pdf version that you can access offline.

<img width="848" alt="version-selector-pdf" src="https://user-images.githubusercontent.com/40577714/47171084-676b1600-d2cd-11e8-91f7-f022455a2ad1.png">

**Comment by csoja** [comment]
@deszoeke 

_conda install anaconda-docs_ or _conda install anaconda-oss-docs_

Once you've installed anaconda-docs or anaconda-oss-docs - if you navigate into the pkgs directory in your anaconda installation and then either the anaconda-docs* folder or the anaconda-oss-docs* folder, then share/doc/anaconda-* - (in other words, something like: anaconda3/pkgs/anaconda-oss-docs-1.0.14-0/share/doc/anaconda-oss)  

You'll find pdfs from when those packages were last released and zip files - that if you unzip you can navigate the docs in your browser (i.e. file:///users/csoja/anaconda3_51/anaconda3/pkgs/anaconda-oss-docs-1.0.14-0/share/doc/anaconda-oss/bleach-latest/index.html), similar how you would if you were connected to the internet.   

These are not released very frequently however, so going to the live website is the best bet.
