### ISSUE TITLE
Path resolution bug prevents import function to work correctly with Spyder

### ISSUE THREAD

**Issue by SMH17** [ContinuumIO/anaconda-issues#1532]
Assuming you have a folder with different script named _project_ that contains:
`script_a.py`
that needs features that are included in a different script in the same folder:
`script_b.py`

if script_a.py code include a reference to script b eg
`import script_b`

the execution in _Spyder_ fails with the error: 
`ImportError: No module named script`

seems that the underscore symbol prevent the right path resolution

OS: Windows 10 x64
Anaconda updated to latest version with Spyder 3.1.3

**Comment by mingwandroid** [comment]
You haven't given very many details here with which to help you.

Try adding this to the top of your script:

```
import sys, os
print(os.getcwd())
print(sys.path)
```

You will probably see that the folder containing your scripts is not in `sys.path`.

**Comment by SMH17** [comment]
@mingwandroid As I have said the imported script in the same folder of the script that I'm running, aren't in the system path.
Spyder should look in the current folder not only in the `sys.path ` and if I remove the underscore from the script name the import works

**Comment by mingwandroid** [comment]
This is not to do with Spyder, this is how Python works.

**Comment by SMH17** [comment]
This isn't how python works. In others IDE you aren't forced to remove the underscore from script names to resolve path.

**Comment by goanpeca** [comment]
@SMH17 please add this to the top of the script

```python
import sys, os
print(os.getcwd())
print(sys.path)
```

**Comment by mingwandroid** [comment]
@SMH17, while you are at it:

```
import script
print script.__file__
```

**Comment by SMH17** [comment]
here the path

```
D:\development\tensorflow\models\computer_vision\inception
['', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\spyder\\utils\\site', 'C:\\ProgramData\\Anaconda3\\python35.zip', 'C:\\ProgramData\\Anaconda3\\DLLs', 'C:\\ProgramData\\Anaconda3\\lib', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\silvi\\.ipython']
```

As I have said if I include a script file that has some underscore in its name, Spyder is unable to resolve path, if all python script used are without any underscore **_** in their file name import in Spyder works fine

**Comment by SMH17** [comment]
To be more clear this problem happens because the part of the name after the underscore is ignored 

so if I use `import segment_picture` Spyder tries to import a script named `segment` and since the file name is `segment_picture.py` NOT `segment.py` this cause the error `ImportError: No module named segment`

**Comment by mingwandroid** [comment]
Please share the output I requested in https://github.com/ContinuumIO/anaconda-issues/issues/1532#issuecomment-287422927

**Comment by SMH17** [comment]
@mingwandroid if cannot resolve the import the execution terminates before reaching the print codeline with `No module named 'supposedfilename'`

**Comment by mingwandroid** [comment]
Could it be possible that your `_` is not an ascii `_` character and instead a different unicode one, such as one of the others listed here: http://unicode-search.net/unicode-namesearch.pl?term=UNDERSCORE

For the record, incase it isn't obvious, I cannot repeat this, at all. Here are the exact steps I used to try to repeat it:

1. Launch `Spyder` from the `Start Menu`
2. Go to `File->New File`, enter:
```
import module_b
print("world")
```
3. Go to `File->Save As`, rename to `module_a.py`
4. Go to `File->New File`, enter:
```
print("hello")
```
5. Go to `File->Save As`, rename to `module_b.py`
6. Click the big green arrow run button.
7. Observe that the IPython console showed:
```
runfile('C:/Users/builder/module_a.py', wdir='C:/Users/builder')
hello
world
```

**Comment by SMH17** [comment]
The underscore is the standard ascii _ however unistalling and re-installing the whole Conda distribution this issue seems doesn't happen anymore.
