### ISSUE TITLE
Anaconda navigator doesn't open

### ISSUE THREAD

**Issue by troublecuber** [ContinuumIO/anaconda-issues#1533]
HI. I recently installed anaconda but the shortcut for the navigator doesn't open the navigator. Any solutions?

**Comment by Pelonza** [comment]
I have a similar issue, however it only happens after reboot.
The navigator opens fine when I first install, but after reboot it doesn't open. I'm still trying to track down what the issue is for me....

Did you have similar behavior? Or is it not opening at ALL for you?

**Comment by troublecuber** [comment]
It doesn't open at all. Even after reinstalling

**Comment by betaglobin** [comment]
I have the same issue. I deleted Anaconda completely (literally) about a month ago, since I noticed that it has been installed on a root (mac OS) previously. Today, I tried everything, installation via GUI, via terminal, updating, deinstallation of the Homebrew packages... I open the Navigator, I see the initialization process and the app quites by itselft.

I hope there is a solution for this.

**Comment by goanpeca** [comment]
@troublecuber

**Comment by milindmalkani1** [comment]
i have the similar problem while typing the above command you listed i.e `conda info` and `conda list` it shows **failed to create process.**

**Comment by janhavi028** [comment]
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=3544)
This is the error I am getting while opening navigator a few days ago it was working just fine suddenly it has stopped working I uninstalled and installed it again but it does not wok still

**Comment by csoja** [comment]
@janhavi028 in the Anaconda Prompt, please try:
_anaconda-navigator --reset_

Also, if you haven't updated Anaconda Navigator recently, you also should try updating by running the following in the Anaconda Prompt:
_conda update conda_

_conda update anaconda-navigator_

_conda update navigator-updater_

**Comment by dherikf** [comment]
Here is the conda list from my PC:

(base) C:\Users\Dherik França HP>conda info

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Dherik França HP\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-32
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Dherik França HP\AppData\Local\conda\conda\pk
gs
       envs directories : C:\Users\Dherik França HP\AppData\Local\conda\conda\en
vs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\Dherik França HP\.conda\envs
               platform : win-32
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/7 Wi
ndows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False


(base) C:\Users\Dherik França HP>conda list
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36ha9200a3_0
alabaster                 0.7.10           py36hedafc74_0
anaconda                  5.2.0                    py36_3
anaconda-client           1.6.14                   py36_0
anaconda-navigator        1.8.7                    py36_0
anaconda-project          0.8.2            py36hdea9eaf_0
asn1crypto                0.24.0                   py36_0
astroid                   1.6.3                    py36_0
astropy                   3.0.2            py36h452e1ab_1
attrs                     18.1.0                   py36_0
babel                     2.5.3                    py36_0
backcall                  0.1.0                    py36_0
backports                 1.0              py36hf8a4c8f_1
backports.shutil_get_terminal_size 1.0.0            py36h567543b_2
beautifulsoup4            4.6.0            py36h4361f19_1
bitarray                  0.8.1            py36hfa6e2cd_1
bkcharts                  0.2              py36h41dda5e_0
blas                      1.0                         mkl
blaze                     0.11.3           py36h70bead1_0
bleach                    2.1.3                    py36_0
blosc                     1.14.3               he51fdeb_0
bokeh                     0.12.16                  py36_0
boto                      2.48.0           py36h2dece20_1
bottleneck                1.2.1            py36hd155fb5_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py36_0
cffi                      1.11.5           py36h945400d_0
chardet                   3.0.4            py36hf2a9688_1
click                     6.7              py36hfb6b3c4_0
cloudpickle               0.5.3                    py36_0
clyent                    1.2.2            py36h4dd741a_1
colorama                  0.3.9            py36he9a059a_0
comtypes                  1.1.4                    py36_0
conda                     4.5.4                    py36_0
conda-build               3.10.5                   py36_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h5d0fd5b_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py36h19a5d9b_0
cryptography              2.2.2            py36hfa6e2cd_0
curl                      7.60.0               h7602738_0
cycler                    0.10.0           py36hd299a41_0
cython                    0.28.2           py36hfa6e2cd_0
cytoolz                   0.9.0.1          py36hfa6e2cd_0
dask                      0.17.5                   py36_0
dask-core                 0.17.5                   py36_0
datashape                 0.5.4            py36h801e743_0
decorator                 4.3.0                    py36_0
distributed               1.21.8                   py36_0
docutils                  0.14             py36h4cf9f97_0
entrypoints               0.2.3            py36hd26a89c_2
et_xmlfile                1.0.1            py36ha14dd7c_0
fastcache                 1.0.2            py36hfa6e2cd_2
filelock                  3.0.4                    py36_0
flask                     1.0.2                    py36_1
flask-cors                3.0.4                    py36_0
freetype                  2.8                  h0224ed4_1
get_terminal_size         1.0.0                h4b36c58_0
gevent                    1.3.0            py36hfa6e2cd_0
glob2                     0.6              py36h2e90fdd_0
greenlet                  0.4.13           py36hfa6e2cd_0
h5py                      2.7.1            py36h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py36_2
html5lib                  1.0.1            py36h6ed1b79_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 h3fcc66b_1
idna                      2.6              py36h787667b_1
imageio                   2.3.0                    py36_0
imagesize                 1.0.0                    py36_0
intel-openmp              2018.0.0                      8
ipykernel                 4.8.2                    py36_0
ipython                   6.4.0                    py36_0
ipython_genutils          0.2.0            py36h011d6f9_0
ipywidgets                7.2.1                    py36_0
isort                     4.3.4                    py36_0
itsdangerous              0.24             py36h0eb04fb_1
jdcal                     1.4                      py36_0
jedi                      0.12.0                   py36_1
jinja2                    2.10             py36hc376a56_0
jpeg                      9b                   he27b436_2
jsonschema                2.6.0            py36hc586ae5_0
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36hb66b1b8_1
jupyter_core              4.4.0            py36h575da4c_0
jupyterlab                0.32.1                   py36_0
jupyterlab_launcher       0.10.5                   py36_0
kiwisolver                1.0.1            py36h7de1d16_0
lazy-object-proxy         1.3.1            py36hfebf436_0
libcurl                   7.60.0               hc4dcbb0_0
libiconv                  1.15                 hc4a7105_7
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                hd619d38_4
libtiff                   4.0.9                hb8ad9f9_1
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.23.1           py36hcacf6c6_0
locket                    0.2.0            py36h3eabf40_1
lxml                      4.2.1            py36heafd4d3_0
lzo                       2.10                 h00ab751_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py36h3b07c4d_1
matplotlib                2.2.2            py36h153e9ff_1
mccabe                    0.6.1            py36ha34857b_1
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.8.3            py36hfa6e2cd_1
mkl                       2018.0.2                      1
mkl-service               1.1.2            py36h10c1010_4
mkl_fft                   1.0.1            py36h452e1ab_0
mkl_random                1.0.1            py36h9258bd6_0
more-itertools            4.1.0                    py36_0
mpmath                    1.0.0            py36haf93544_2
msgpack-python            0.5.6            py36he980bc4_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.5.0                    py36_0
navigator-updater         0.2.1                    py36_0
nbconvert                 5.3.1            py36h5066f46_0
nbformat                  4.4.0            py36hfe36a2e_0
networkx                  2.1                      py36_0
nltk                      3.3.0                    py36_0
nose                      1.3.7            py36h732162c_2
notebook                  5.5.0                    py36_0
numba                     0.38.0           py36h830ac7b_0
numexpr                   2.6.5            py36hcd2f87e_0
numpy                     1.14.3           py36h9fa60d3_1
numpy-base                1.14.3           py36h555522e_1
numpydoc                  0.8.0                    py36_0
odo                       0.5.1            py36h3d61389_0
olefile                   0.45.1                   py36_0
openpyxl                  2.5.3                    py36_0
openssl                   1.0.2o               h8ea7d77_0
packaging                 17.1                     py36_0
pandas                    0.23.0           py36h830ac7b_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36hbaae778_1
parso                     0.2.0                    py36_0
partd                     0.3.8            py36h9032c1e_0
path.py                   11.0.1                   py36_0
pathlib2                  2.3.2                    py36_0
patsy                     0.5.0                    py36_0
pep8                      1.7.1                    py36_0
pickleshare               0.7.4            py36he181f7f_0
pillow                    5.1.0            py36h0738816_0
pip                       10.0.1                   py36_0
pkginfo                   1.4.2                    py36_1
pluggy                    0.6.0            py36hbdfd5d1_0
ply                       3.11                     py36_0
prompt_toolkit            1.0.15           py36ha226939_0
psutil                    5.4.5            py36hfa6e2cd_0
py                        1.5.3                    py36_0
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hbfdb8c3_0
pycparser                 2.18             py36h315bf61_1
pycrypto                  2.6.1            py36hfa6e2cd_7
pycurl                    7.43.0.1         py36h74b6da3_0
pyflakes                  1.6.0            py36h66794c8_0
pygments                  2.2.0            py36h1a04f08_0
pylint                    1.8.4                    py36_0
pyodbc                    4.0.23           py36h6538335_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.0            py36h9ef7486_1
pyqt                      5.9.2            py36h1aa27d4_0
PyQt5_sip                 4.19.12                   <pip>
pysocks                   1.6.8                    py36_0
pytables                  3.4.3            py36he6f6034_1
pytest                    3.5.1                    py36_0
pytest-arraydiff          0.2                      py36_0
pytest-astropy            0.3.0                    py36_0
pytest-doctestplus        0.1.3                    py36_0
pytest-openfiles          0.3.0                    py36_0
pytest-remotedata         0.2.1                    py36_0
python                    3.6.5                h0c2934d_0
python-dateutil           2.7.3                    py36_0
pytz                      2018.4                   py36_0
pywavelets                0.5.2            py36hf262123_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.1                    py36_0
pyyaml                    3.12             py36h624d9f2_1
pyzmq                     17.0.0           py36hfa6e2cd_1
qt                        5.9.5            vc14he4a7d60_0  [vc14]
qtawesome                 0.4.4            py36h6b33ce7_0
qtconsole                 4.3.1            py36h86495bc_0
qtpy                      1.4.1                    py36_0
requests                  2.18.4           py36h964142b_1
rope                      0.10.7           py36h2a980e7_0
ruamel_yaml               0.15.35          py36hfa6e2cd_1
scikit-image              0.13.1           py36hfa6e2cd_1
scikit-learn              0.19.1           py36hb0057d7_0
scipy                     1.1.0            py36h672f292_0
seaborn                   0.8.1            py36hcff10e0_0
send2trash                1.5.0                    py36_0
setuptools                39.1.0                   py36_0
simplegeneric             0.8.1                    py36_2
singledispatch            3.4.0.3          py36h2687f66_0
sip                       4.19.8           py36h6538335_0
six                       1.11.0           py36h7f2c006_1
snappy                    1.1.7                h8327587_3
snowballstemmer           1.2.1            py36h5e2b779_0
sortedcollections         0.6.1                    py36_0
sortedcontainers          1.5.10                   py36_0
sphinx                    1.7.4                    py36_0
sphinxcontrib             1.0              py36h3cc09c9_1
sphinxcontrib-websupport  1.0.1            py36h10e879d_1
spyder                    3.2.8                    py36_0
sqlalchemy                1.2.7            py36ha85dd04_0
sqlite                    3.23.1               h35aae40_0
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.1.1            py36hba5725f_0
tblib                     1.3.2            py36h96aaa60_0
terminado                 0.8.1                    py36_1
testpath                  0.3.1            py36ha9283f1_0
tk                        8.6.7                ha9f76c9_3
toolz                     0.9.0                    py36_0
tornado                   5.0.2                    py36_0
traitlets                 4.3.2            py36h0dbcc04_0
typing                    3.6.4                    py36_0
unicodecsv                0.14.1           py36h238903e_0
urllib3                   1.22             py36hf0c4117_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7            py36hc8ec93f_0
webencodings              0.5.1            py36hf0a7dc3_1
werkzeug                  0.14.1                   py36_0
wheel                     0.31.1                   py36_0
widgetsnbextension        3.2.1                    py36_0
win_inet_pton             1.0.1            py36h6b5aef5_1
win_unicode_console       0.5              py36ha08cfaa_0
wincertstore              0.2              py36hcdd9a18_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py36h084cbfa_0
xlrd                      1.1.0            py36he7b893d_1
xlsxwriter                1.0.4                    py36_0
xlwings                   0.11.8                   py36_0
xlwt                      1.3.0            py36hb79324b_0
yaml                      0.1.7                h896c600_2
zeromq                    4.2.5                hd6b2f15_0
zict                      0.1.3            py36hf291af1_0
zlib                      1.2.11               hbb18732_2

**Comment by dherikf** [comment]
If I type: anaconda-navigator, I have this:

(base) C:\Users\Dherik França HP>anaconda-navigator
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\__init__.py", line 166,
in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\anaconda-navigator-script.py", line 6,
in <module>
    from anaconda_navigator.app.main import main
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\main.p
y", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\__in
it__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\__init__.py", line 172,
in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
