### ISSUE TITLE
why anaconda launch for a long time in “updating reportdata”

### ISSUE THREAD

**Issue by chenshanghao** [ContinuumIO/anaconda-issues#1535]
My Os is MacOs 10.12.3. I download "Anaconda3-4.3.1-MacOSX-x86_64.pkg" for install. However, when I launch anaconda, I have wait 4 hours in "updating reportdata".

**Comment by ilanschnell** [comment]
I assume that the Anaconda-Navigator is talking a long time.  This might be related internet connectivity.

**Comment by goanpeca** [comment]
1.6 version does not rely on internet for starting up (unless you want to sign in to anaconda cloud). Updating the index is now only performed on demand or when packages are installed (conda updates the index as part of its normal process)
