### ISSUE TITLE
Anaconda 4.3.1 

### ISSUE THREAD

**Issue by Qalkaseasbeh** [ContinuumIO/anaconda-issues#1537]
I downloaded Anaconda 4.3.1 from (https://www.continuum.io/downloads#windows, Python 2.7 version), and I have 64 bit system but ANACONDA navigator doesn't work.

I tried 32 bit, same problem appears. I did many install & uninstall.

Could you help please?

**Comment by goanpeca** [comment]
@Qalkaseasbeh could you open the anaconda prompt and type

`anaconda-navigator` and paste the output (error trace) here?

**Comment by Qalkaseasbeh** [comment]
Thanks a lot. It works now for me. I forgot to delete this question yesterday.

**Comment by goanpeca** [comment]
@Qalkaseasbeh still we should see what the issue is for the shortcuts not working.

Could you please paste the information I asked for?

**Comment by Qalkaseasbeh** [comment]
![capture](https://cloud.githubusercontent.com/assets/24799302/24162679/5711f330-0e36-11e7-8d94-21915fc31de8.PNG)

**Comment by Qalkaseasbeh** [comment]
Yes, I can open Anaconda by typing anaconda-navigator in the anaconda prompt.

**Comment by goanpeca** [comment]
`conda info` and `conda list` and paste the output :-) ?

**Comment by Qalkaseasbeh** [comment]
![capture](https://cloud.githubusercontent.com/assets/24799302/24163457/acd969fe-0e38-11e7-9d50-efe18bfaf264.PNG)
![conda list](https://cloud.githubusercontent.com/assets/24799302/24163459/ace96d7c-0e38-11e7-9d83-e10425502e63.PNG)

**Comment by goanpeca** [comment]
Everything seems to be fine. Please open if you find any issues
