### ISSUE TITLE
Christopher Santos' issue from the Anaconda mailing list

### ISSUE THREAD

**Issue by mingwandroid** [ContinuumIO/anaconda-issues#1539]
Christopher reports:

Okay after clearing up more hard drive space, I reinstalled Anaconda.

I did the following steps in this order (details folow):

1) Retrograde to Py3.5 = successful
2) r-essentials conda install = fail
3) r-base conda install = appears to be successful (no errors)
4) r-essentials conda install = fail
5) rstudio conda install = fail
6) attempt to run [python] from Anaconda prompt = successful
7) attempt to run [r-base] from Anaconda prompt = fail; unrecognized command
8) attempt to run [r] from Anaconda prompt = fail; a window pops up "This version of ... R.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) versino of the program then contact the software publisher."

Details to the above steps:
I tried [conda install r-essentials] and got the following error: "An error occurred while installing package 'defaults::m2w64-p11-kit-0.23.2-2'." There are several traceback errors that are also logged.

Using [conda install -c r r-essentials], an error also occurs. ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::m2w64-p11-kit-0.23.2-2'.

When I attempt [conda install r-base], this appears to work, but r-essentials still throws the same error.

Attempting [conda install rstudio] but the same error pops up.

At this point, I will leave well enough alone as I need this laptop with Py3.5 working this week. I have not attempted further Rstudio or R installations via the Navigator shell nor from the Anaconda prompt.

**Comment by mingwandroid** [comment]
2 to 5: All harmless, annoying that it reports an error but this error does not cause the software to behave incorrectly.
7: There is no program called r-base, the program is called r, but installing r-base on it's own doesn't get you a useful R installation. At a minimum you should install the r package which also includes the core R libraries.
8: This I cannot understand. I've never seen it before. I can only guess you are low on disk space and something went wrong due to that.

Here is how I tested this on Windows 7 64-bit just now, (when diagnosing or running into problems I don't use Anaconda Navigator since you can't see the output).

1. Open cmd.exe prompt, download then  install Anaconda3 4.3.1 into a temporary folder, then 'activate' this conda setup:

```
cd %TEMP%
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/archive/Anaconda3-4.3.1-Windows-x86.exe', 'ac3.exe') }"
start /wait "" ac3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%TEMP%\ac3
%TEMP%\ac3\Scripts\activate.bat
```

2. Update conda to the latest version to get any important bug-fixes since the Anaconda release:

```
conda update -y conda -v -v -v > ac3\conda-update.txt 2>&1
```

2. Downgrade to Python 3.5, keeping a detailed log if anything goes wrong:

```
conda install -y python=3.5 -v -v -v > ac3\python-downgrade.txt 2>&1
```

3. Install r-essentials and r-studio (r-essentials is a dependency of r-studio so doesn't *need* to be installed explicitly), again keeping a log:

```
conda install -y r-studio -v -v -v > ac3\r-studio-install.txt 2>&1
```

**Comment by mingwandroid** [comment]
After the steps above, from the same `cmd.exe` prompt, I can enter `rstudio` and use `RStudio` just fine. Also, running `R.exe` gives:

```
(root) C:\Users\builder\AppData\Local\Temp>R

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
```

**Comment by mingwandroid** [comment]
Can you open a normal `cmd.exe` prompt and enter: `echo %PATH%`, then do the same thing from the `Anaconda Prompt` please? I suspect your `PATH` env. var has run out of space.

**Comment by goanpeca** [comment]
@mingwandroid this issues seems stale, closing?
