### ISSUE TITLE
"502 Server dropped connection"when try to start jupyter notebook

### ISSUE THREAD

**Issue by dxj1113** [ContinuumIO/anaconda-issues#1540]
windows7,anaconda 4.3.1 foy python 3.6.

Error message shows "0 active kernels"

**Comment by mingwandroid** [comment]
Please run the `Ananconda Prompt` from the `Start Menu` and then type:

`jupyter notebook`

It should launch a browser. Please copy the text output from the `Anaconda Prompt` here.

**Comment by dxj1113** [comment]
(C:\ProgramData\Anaconda3) C:\Users\Administrator>jupyter notebook
[I 10:49:00.281 NotebookApp] The port 8888 is already in use, trying another por
t.
[I 10:49:00.282 NotebookApp] The port 8889 is already in use, trying another por
t.
[I 10:49:00.282 NotebookApp] The port 8890 is already in use, trying another por
t.
[I 10:49:00.345 NotebookApp] Serving notebooks from local directory: C:\Users\Ad
ministrator
[I 10:49:00.345 NotebookApp] 0 active kernels
[I 10:49:00.345 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8891/?token=7cd69491d138926d56c9d4dc6404078b7a5d2be30b208708
[I 10:49:00.345 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[C 10:49:00.346 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8891/?token=7cd69491d138926d56c9d4dc6404078b7a5d2be30b2
08708


and the chrome shows

502 Server dropped connection

The following error occurred while trying to access http://localhost:8891/tree?token=97534b9cf58d0df8cd6e1169faa453b6b3e53906db90b9e6:

502 Server dropped connection

Generated Tue, 21 Mar 2017 02:49:01 GMT by Polipo on QX-PC-070:8123.

**Comment by mingwandroid** [comment]
Do you have any ad blocker running? Can you try some different browsers? Run with to `jupyter notebook --no-browser` prevent it from launching a browser, then copy the URL into a different one.

**Comment by dxj1113** [comment]
@mingwandroid  Thank you.It works use your way on IE.But still not work on chrome

**Comment by dxj1113** [comment]
I remove my ad blocker from chrome,and still not work.......

**Comment by mingwandroid** [comment]
I guess some other extension that you use in chrome is causing this, or perhaps some virus scanning software is blocking the communication?

If you could go to chrome://extensions/ and list them (with version numbers) that could be helpful incase this comes up again.

**Comment by dxj1113** [comment]
Thank you.
Here are my extension lists.

Adobe Acrobat 15.1.0.6
将当前网页转换为 Adobe PDF 文件（仅限 Windows）
详细信息  选项
ID： efaidnbmnnnibpcajpcglclefindmkaj
检查视图： 背景页

在隐身模式下启用
 
已启用
  
chromeIPass 2.8.1
KeePass integration for browser Chrome using KeePassHttp
详细信息  选项
ID： ompiailgknfdndiefoaoiligalphfdae
检查视图： 背景页

在隐身模式下启用
 
已启用
  
Clippings.io for Kindle and Evernote 1.0.15
Import your Kindle notes and highlights into www.clippings.io and www.evernote.com. Export your Kindle highlights to Word and PDF
详细信息
ID： pnibcoleffbpdiohejiinidocmklphde
检查视图： 背景页

在隐身模式下启用
 
已启用
  
Coding with Chrome 4.3.12
Learn, improve, or teach coding skills within a Chrome browser.
详细信息
ID： becloognjehhioodmnimnehjcibkloed
检查视图： 背景页 （无效）

在隐身模式下启用
 
已启用
  
Google Dictionary (by Google) 4.0.5
View definitions easily as you browse the web.
详细信息  选项
ID： mgijmajocgfcbeboacabfgobmjgjcoja
检查视图： background.html （无效）

在隐身模式下启用
  
允许访问文件网址
 
已启用
  
Google Mail Checker 4.4.0
显示 Google Mail 收件箱中的未读邮件数。点击该按钮还可以打开您的收件箱。
详细信息
ID： mihcahmgecmbnbcchbopgniflfhgnkff
检查视图： background.html

在隐身模式下启用
 
已启用
  
Google 日历 (来自 Google) 2.7
以便捷的方式查看 Google 日历及在当前网站上直接添加新的日历事件
详细信息  选项
ID： gmbgaklkmjakoegficnlkhebmhkjfich
检查视图： 背景页

在隐身模式下启用
 
已启用
  
Google翻译 2.0.6
浏览网页时可轻松查看翻译版本。由Google翻译小组提供。
详细信息
ID： aapbdbdomjkkjkaonfhkkikfgjllcleb

启用
  
iCloud 书签 1.4.20
使您 Windows 上的 Chrome 书签与您的 iPhone、iPad 和 Mac 上的 Safari 书签保持一致。
详细信息
ID： fkepacicchenbjecpbpbclokcabebhah
检查视图： background.html

在隐身模式下启用
 
已启用
  
MaDe 0.8
MaDe Editor for markdown
详细信息
ID： oknndfeeopgpibecfjljjfanledpbkog

在隐身模式下启用
 
已启用
  
Octotree 2.1.0
Code tree for GitHub
详细信息
ID： bkhaagjahfmjljalopjnoealnfndnagc
检查视图： 背景页 （无效）

在隐身模式下启用
  
允许访问文件网址
 
已启用
  
Office Online 1.5.0
在浏览器中查看、编辑和创建 Office 文件。
详细信息
ID： ndjpnladcallmjemlbaebfadecfhkepb
检查视图： background/background.html

在隐身模式下启用
  
允许访问文件网址
 
已启用
  
Send to Kindle for Google Chrome 1.0.1.74
Sending and reading web content such as news articles and blog posts to your Kindle device or reading app is now easier than ever.
详细信息  选项
ID： cgdjpilhipecahhcilnafpblkieebhea
检查视图： 背景页

在隐身模式下启用
  
允许访问文件网址
 
已启用
  
保存到 Google 云端硬盘 2.1.1
将网络内容或屏幕截图直接保存到Google 云端硬盘。
详细信息  选项
ID： gmbmikajjgmnabiglmofipeabaddhgne
检查视图： 背景页

在隐身模式下启用
  
允许访问文件网址
 
已启用
  
印象笔记·剪藏 6.11
使用印象笔记扩展程序一键保存精彩网页内容到印象笔记帐户。
详细信息  选项
ID： pioclpoplcdbaefihamjohnefbikjilc
检查视图： background.html https://www.baidu.com/s?wd=hbase%20hive&rsv_spt=1&rsv_iqid=0x8b9b59030000fb91&issp=1&f=8&rsv_bp=0&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_sug3=14&rsv_sug2=0&inputT=6862&rsv_sug4=6863&rsv_jmp=slow (iframe)

在隐身模式下启用
  
允许访问文件网址
 
已启用
  
右键搜图（以图搜图） 2.0.0
在图片上点击右键，即可以图搜图
详细信息
ID： fkgbhcmlofdeklgahnbdedemjfckhbnf
检查视图： background.html

在隐身模式下启用
 
已启用
  
捕捉网页截图 - FireShot的 0.98.91
捕捉网页截图，编辑并将它们保存为PDF，JPEG，GIF，PNG或BMP；上传，打印，在Photoshop中打开，复制到剪贴板或电子邮件
详细信息  选项
ID： mcbpblocgmgfnpjjppndjkmgjaogfceg
检查视图： 背景页

在隐身模式下启用
  
允许访问文件网址
 
已启用
  
掘金 0.3.7
为设计师、程序员、产品经理每日发现优质内容。
详细信息
ID： lecdifefmmfjnjjinhaennhdlmcaeeeb

启用
  
有道词典Chrome划词插件 1.55
支持Chrome浏览器的划词翻译
详细信息  选项
ID： eopjamdnofihpioajgfdikhhbobonhbb
检查视图： 背景页

**Comment by mingwandroid** [comment]
Thanks, you might want to try disabling them all and seeing if that fixes this, and it if does, attempting to isolate one extension that's causing it?

**Comment by Kangqiang0** [comment]
I solve the problem by disabling my Shadowsocks service.

**Comment by MagShadow** [comment]
Same as @Kangqiang0  I solved this problem by disabling my Shadowsocks Service.
But even with ss working, **Windows Edges** can also open the page successfully.
