### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by srikanth-narayanan** [ContinuumIO/anaconda-issues#1541]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv ==2.4.8 -> numpy 1.7* -> python 3.3*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'conda': '4.3.14', 'language': 'en', 'pyqt': '4.11.4', 'version': '1.2.1', 'python': '3.5.2', 'platform': 'osx-64', 'os': 'Darwin;16.4.0;Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64;x86_64;i386'}

**Comment by goanpeca** [comment]
@srikanth-narayanan it seems you are using an outdated version of Navigator.

I would advice to update to the latest version by typing un the terminal:

`conda update anaconda-navigator`

**Comment by srikanth-narayanan** [comment]
@goanpeca - Thanks for your feedback. My navigator is stable now.
