### ISSUE TITLE
Spyder missing 

### ISSUE THREAD

**Issue by dorshman** [ContinuumIO/anaconda-issues#1542]
Hello ,
I was using spyder on Anaconda so i try to install opencecv  and Keras  packages which were not successful but i found out that my spyder is no longer on Anaconda Navigator .
How can i get the spyder back ?
thanks

**Comment by goanpeca** [comment]
@dorshman could you open a terminal, or anaconda prompt (if on windows) and type:

`conda info`

and `conda list` and paste the results?

**Comment by goanpeca** [comment]
No feedback, closing
