### ISSUE TITLE
Anaconda not working on either of my Macs

### ISSUE THREAD

**Issue by dshadravan** [ContinuumIO/anaconda-issues#1544]
Downloaded newest release today, tried installing on a Macbook Pro and an iMac. Both have macOS 10.12.3.  Both systems hang on initializing Navigator. Tried running sudo rm -rf ~/.continuum/_ on both of them to no avail.  Sigh....

**Comment by goanpeca** [comment]
@dshadravan if you open a terminal and type

`anaconda-navigator` could you paste the output?

**Comment by dshadravan** [comment]
Turns out I was just being impatient. It took _several_ minutes for it to initialize the first time. Once I let it sit and spin for 5-10 minutes, then it finally launched. thanks @goanpeca

**Comment by goanpeca** [comment]
Startup of Navigator now does not rely on internet connectivity for 1.6
