### ISSUE TITLE
installing qgrid causes Jupyter to ask for a password

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#1546]
I don't know why but when I go and install qgrid `conda install qgrid` Jupyter then asks me for an auth token (password).  There is nothing shown in the terminal log output URL, nor does `jupyter notebook list` show me the token, so total mystery.

@twiecki any thoughts?

FWIW, `pip install qgrid` doesn't have this effect, however it also doesn't seem to make qgrid available to me with Anaconda 4.3.1 and Jupyter 4.2.3.

**Comment by ccordoba12** [comment]
This is the default normal behavior since the release of version 4.3 of the Jupyter notebook, i.e. to ask their users to set a password even if they are running the notebook locally.

**Comment by ijstokes** [comment]
OK, I re-opened because I was going to explain how this happened to me with more clarity.  However now I can't reproduce it, so I'm closing again.
