### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by iamstr1ng** [ContinuumIO/anaconda-issues#1547]
Anaconda Navigator Update error:

/home/ankit/anaconda3/bin/python /home/ankit/anaconda3/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.5.0: The following specifications were found to be in conflict:
  - anaconda-navigator 1.5.0*
  - orange3 -> pyqt 4.*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.2', 'os': 'Linux;4.4.0-66-generic;#87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017;x86_64;x86_64', 'pyqt': '4.11.4', 'version': '1.2.1', 'conda': '4.1.11', 'qt': '4.8.7', 'platform': 'linux-64', 'language': 'en_IN'}

**Comment by goanpeca** [comment]
@iamstr1ng the newer versions of navigator depend on `qt=5.6` but orange does not support that. If you want to use the latest navigator you need to 

```
conda remove orange3
conda update anaconda-navigator
```

Cheers
