### ISSUE TITLE
Can't get PATH of Sublime Text 3 for Python in Anaconda right 

### ISSUE THREAD

**Issue by Coastlight** [ContinuumIO/anaconda-issues#1550]
Hi, I have Sublime Text 3 installed and I have Python 3.5 installed via an Anaconda distribution on my Windows 10 machine. I can't make Sublime Text 3 work. Trying to point to the right PATH. When I had Python installed without the Anaconda distribution I was able to assign the right PATH. I am not referring to the Anaconda add-on package in Sublime Text 3, but to the Anaconda distribution. Any suggestions?

**Comment by mingwandroid** [comment]
I do not use Sublime Text 3, so I will need some assistance from you. Please open a cmd.exe prompt and show the results from:

```
echo %PATH%
where python
```

**Comment by Coastlight** [comment]
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\e\cmd;C:\Users\roman\Anaconda3;C:\Users\roman\Anaconda3\Scripts;C:\Users\roman\Anaconda3\Library\bin;C:\blp\DAPI;C:\blp\DAPI\DDE;C:\Users\roman\AppData\Local\Microsoft\WindowsApps;C:\python27;C:\Users\roman\Anaconda3\pkgs\python3.5.2-0


C:\Users\roman\Anaconda3\python.exe

**Comment by Coastlight** [comment]
these are the two results from the two commands you gave me

**Comment by mingwandroid** [comment]
How do you launch `Sublime Text 3`?

**Comment by Coastlight** [comment]
I click on the symbol and lunch it

**Comment by mingwandroid** [comment]
From the `Start Menu`? Please right click and go to More->Open File Location.

**Comment by mingwandroid** [comment]
Did you manually change your %PATH%? It should not have `C:\Users\roman\Anaconda3\pkgs\python3.5.2-0` in it.

**Comment by Coastlight** [comment]
just did that, but there is no option for More->Open File Location.
I have Windows 10

**Comment by Coastlight** [comment]
yes, I did :(

**Comment by mingwandroid** [comment]
Remove that entry. It shouldn't be there. If you want to use `Anaconda Python`, then use the `Anaconda Prompt` from the `Start Menu`.

**Comment by Coastlight** [comment]
how do I get there again to remove that entry?

**Comment by mingwandroid** [comment]
https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

**Comment by Coastlight** [comment]
removed that entry

**Comment by mingwandroid** [comment]
Great. Does it work now?

**Comment by Coastlight** [comment]
oh, let me check

**Comment by mingwandroid** [comment]
Heh.

**Comment by Coastlight** [comment]
no, it does not

**Comment by Coastlight** [comment]
I am talking about Sublime Text 3

**Comment by Coastlight** [comment]
to execute a python command

**Comment by Coastlight** [comment]
the Anaconda prompt works fine

**Comment by mingwandroid** [comment]
Where is your Sublime Text 3 installed? What installer did you use to install it? I would like the exact link if possible.

**Comment by Coastlight** [comment]
C:\Program Files\Sublime Text 3

**Comment by Coastlight** [comment]
I downloaded it directly from their website and installed it by open it and using the windows installer

**Comment by mingwandroid** [comment]
Can you try to reinstall it?

**Comment by Coastlight** [comment]
ok. will do that.

**Comment by Coastlight** [comment]
done that. nothing has changed

**Comment by Coastlight** [comment]
When I try to run a simple python command I get the following message in Sublime Text 3:

C:\Users\roman\Anaconda3\python.exe: can't find '__main__' module in ''
[Finished in 0.1s with exit code 1]
[shell_cmd: python -u ""]
[dir: C:\Program Files\Sublime Text 3]
[path: C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\e\cmd;C:\Users\roman\Anaconda3;C:\Users\roman\Anaconda3\Scripts;C:\Users\roman\Anaconda3\Library\bin;C:\blp\DAPI;C:\blp\DAPI\DDE;C:\Users\roman\AppData\Local\Microsoft\WindowsApps;C:\python27]

**Comment by mingwandroid** [comment]
I don't really understand exactly what you are trying to do. My knowledge of Sublime Text 3 is that it is a text editor. Why are you trying to run commands in it?

I am also aware that there's an IDE plugin for Sublime (which is unfortunately also called Anaconda) and that would allow you to do Python development using Sublime. It also seems that it is possible for that Anaconda to use other Pythons, which would mean you can set it up to use Continuum's Python.

Is that what you are trying to do?

**Comment by Coastlight** [comment]
I want to use Sublime Text 3 to execute my Python code. And I was able to do that. But then I saw the advantage to use the Anaconda distribution for very good reasons and installed Python new via the Anaconda distribution. But after I did that I was not more able to use Sublime Text 3 to execute Python code.

**Comment by Coastlight** [comment]
I must have done something wrong after I installed Anaconda and Python. EVERYTHING else works great!
I have Tensorflow and Tensorboard installed. All is good.

**Comment by Coastlight** [comment]
I cant bring the most simple component of all my installations, Sublime Text 3, to work :(

**Comment by mingwandroid** [comment]
I will need to install Sublime Text 3 to figure out what you are trying to achieve. If you have some links to hand about how to:

> use Sublime Text 3 to execute my Python code.

.. I would appreciate it. At a guess (and I may be wrong) this is probably intended for some very simple use-cases where you wish to use *the same Python interpreter that Sublime Text 3 uses* to run some simple Python function. At another guess, the `Anaconda IDE Plugin` was likely created, in-part, to address your (much more complicated) use-case.

Did you enter your command somewhere manually into Sublime Text 3? If so, if you were to use the full path to the python executable instead of just `python` it might work. For you, the Python in your root env would be in `C:\Users\roman\Anaconda3\python.exe`.

**Comment by Coastlight** [comment]
I am really a beginner and cant honestly follow you :(. All I want to do is use Python in the Sublime Text 3 editor as I did before I installed Anaconda distribution and Python via that Anaconda distribution. I am just learning Python and want to use Sublime Text 3.

**Comment by Coastlight** [comment]
https://www.sublimetext.com/3

that's where I downloaded it

**Comment by Coastlight** [comment]
When you type a python command in Sublime Text 3 you click CTRL B to run it

**Comment by mingwandroid** [comment]
OK, are there any settings in Sublime Text 3 that allow you to specify the Python interpreter that you use? If so, please enter `C:\Users\roman\Anaconda3\python.exe` into it.

**Comment by Coastlight** [comment]
Under Tools, click on Build System. Then Click either on Automatic or Python

**Comment by Coastlight** [comment]
But Sublime Text 3 requires you to point to the right PATH where your Python is. That's what I don't get right anymore when I installed Python via the Anaconda Distribution

**Comment by mingwandroid** [comment]
You need to follow this: http://docs.sublimetext.info/en/latest/reference/build_systems/configuration.html

**Comment by mingwandroid** [comment]
You should not modify your PATH if you have any hope of running two different Python interpreters at the same time.

**Comment by Coastlight** [comment]
Ok. So what do I now need to do to solve the problem?

**Comment by Coastlight** [comment]
Do I need to delete stuff in the PATH or add something there?

**Comment by mingwandroid** [comment]
Follow the instructions in the link I provided: http://docs.sublimetext.info/en/latest/reference/build_systems/configuration.html

If Sublime Text launches OK for you then it may be wise to not rock the boat, then again, if you do remove that entry and it still launches OK then great. Less stuff in PATH is always best.

**Comment by Coastlight** [comment]
Where you able to run a Python command in Sublime Text 3?

**Comment by Coastlight** [comment]
I read the instructions. I honestly don't understand them.

**Comment by Coastlight** [comment]
C:\Users\roman\Anaconda3\python.exe: can't find '__main__' module in ''
[Finished in 0.1s with exit code 1]
[shell_cmd: python -u ""]
[dir: C:\Program Files\Sublime Text 3]
[path: C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\e\cmd;C:\Users\roman\Anaconda3;C:\Users\roman\Anaconda3\Scripts;C:\Users\roman\Anaconda3\Library\bin;C:\blp\DAPI;C:\blp\DAPI\DDE;C:\Users\roman\AppData\Local\Microsoft\WindowsApps;C:\python27]

**Comment by Coastlight** [comment]
Thank you for all your time and help yesterday! I was finally able to make it work. It was a very simple step which I found in a YouTube video. But I first uninstalled Sublime Text 3 and removed al reg entries with an app to make sure I can start from a clean slate. Then I reinstalled Sublime Text 3. 
Here is the video https://www.youtube.com/watch?v=6ZpuwW-9T54
I did not even do all the steps in the video. Here is what I did after reinstalling Sublime Text 3:

1. Open Sublime Text 3
2. Clicked on Tools and Build System and chose Python
3. Clicked on Tools and chose Save All on Build
4. Enterd simple Python code
5. Saved file with Save as command with a .py file extension: e.g. test1.py
6. After saving the file the code turned partially into colored text (recognizing the python commands)
7. Run the code with CTRL+B
8. Code was executed. Happy end! :)

Then I was curios if it uses the Python which I have installed via the Anaconda distribution. I tested that with the following code:
import sys
print (sys.version)
Then I run the code with CTRL+B and that was what I got:
"3.5.3 |Anaconda 4.2.0 (64-bit)| (default, Feb 22 2017, 21:28:42) [MSC v.1900 64 bit (AMD64)]
[Finished in 0.2s]"
That means all is good and Sublime Text 3 runs Python via the Anaconda distribution out of the box!

Thank you again for your help!

**Comment by adcnet** [comment]
Having same issue after 2 days! frustrated cannot find my path cannot find where Python is as it uses Anaconda "install package" via Sublime Text 3 IDE.

http://damnwidget.github.io/anaconda/#

Have watched about 5 YT videos still stuck.

Have followed this exactly  http://www.gtlambert.com/blog/python-sublime-text-3 / everything is fine until I run - ctrl - B

http://imgur.com/BbO8qy3
