### ISSUE TITLE
Anaconda Navigator not showing items on Home page

### ISSUE THREAD

**Issue by kalmdown** [ContinuumIO/anaconda-issues#1551]
I shut down my machine and when I started it and then Navigator back up many of the applications on the home page have disappeared. 

When I shutdown I had R, Jupyter, Anaconda Fusion, qtconsole, and spyder 
Now only shows qtconsole and spyder

Anaconda Navigator 1.4.3, OS X Sierra 10.12.3, conda 4.3.14, python 3.6.0.final.0

**Comment by goanpeca** [comment]
@kalmdown could you please attach the output of 

`conda info` and `conda list` ?

**Comment by kalmdown** [comment]
Info

Current conda install:


               platform : osx-64

          conda version : 4.3.14

       conda is private : False

      conda-env version : 4.3.14

    conda-build version : not installed

         python version : 3.6.0.final.0

       requests version : 2.12.4

       root environment : /Users/212316291/anaconda  (writable)

    default environment : /Users/212316291/anaconda

       envs directories : /Users/212316291/anaconda/envs

                          /Users/212316291/.conda/envs

          package cache : /Users/212316291/anaconda/pkgs

                          /Users/212316291/.conda/pkgs

           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64

                          https://conda.anaconda.org/anaconda-fusion/noarch

                          https://repo.continuum.io/pkgs/free/osx-64

                          https://repo.continuum.io/pkgs/free/noarch

                          https://repo.continuum.io/pkgs/r/osx-64

                          https://repo.continuum.io/pkgs/r/noarch

                          https://repo.continuum.io/pkgs/pro/osx-64

                          https://repo.continuum.io/pkgs/pro/noarch

            config file : /Users/212316291/.condarc

           offline mode : False

             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0
Darwin/16.4.0 OSX/10.12.3

                UID:GID : 727921297:1515967849


Conda List

# packages in environment at /Users/212316291/anaconda:

#

_license                  1.1                      py36_1

alabaster                 0.7.9                    py36_0

anaconda                  custom                   py36_0

anaconda-client           1.6.0                    py36_0

anaconda-fusion           1.0.2                    py36_0    anaconda-fusion

anaconda-navigator        1.4.3                    py36_0

appnope                   0.1.0                    py36_0

appscript                 1.0.1                    py36_0

astroid                   1.4.9                    py36_0

astropy                   1.3                 np111py36_0

babel                     2.3.4                    py36_0

backports                 1.0                      py36_0

beautifulsoup4            4.5.3                    py36_0

bitarray                  0.8.1                    py36_0

blaze                     0.10.1                   py36_0

bokeh                     0.12.3                   py36_0

boto                      2.45.0                   py36_0

bottleneck                1.2.0               np111py36_0

cairo                     1.14.8                        0

cffi                      1.9.1                    py36_0

chardet                   2.3.0                    py36_0

chest                     0.2.3                    py36_0

click                     6.7                      py36_0

cloudpickle               0.2.2                    py36_0

clyent                    1.2.2                    py36_0

colorama                  0.3.7                    py36_0

conda                     4.3.14                   py36_0

conda-env                 2.6.0                         0

configobj                 5.0.6                    py36_0

contextlib2               0.5.4                    py36_0

cryptography              1.7.1                    py36_0

curl                      7.52.1                        0

cycler                    0.10.0                   py36_0

cython                    0.25.2                   py36_0

cytoolz                   0.8.2                    py36_0

dask                      0.13.0                   py36_0

datashader                0.4.0                    py36_0

datashape                 0.5.4                    py36_0

decorator                 4.0.11                   py36_0

dill                      0.2.5                    py36_0

django                    1.10.5                   py36_0

docutils                  0.13.1                   py36_0

easydev                   0.9.34                    <pip>

entrypoints               0.2.2                    py36_0

et_xmlfile                1.0.1                    py36_0

fastcache                 1.0.2                    py36_1

flask                     0.12                     py36_0

flask-cors                3.0.2                    py36_0

font-ttf-dejavu-sans-mono 2.37                          0

font-ttf-inconsolata      2.000                         0

font-ttf-source-code-pro  2.030                         0

font-ttf-ubuntu           0.83                          0

fontconfig                2.12.1                        3

fonts-continuum           1                             0

freetype                  2.5.5                         2

get_terminal_size         1.0.0                    py36_0

gettext                   0.19.8                        1

gevent                    1.2.1                    py36_0

glib                      2.50.2                        1

glueviz                   0.9.1                    py36_0

greenlet                  0.4.11                   py36_0

gsl                       2.2.1                         0

gspread                   0.6.2                     <pip>

h5py                      2.6.0               np111py36_2

harfbuzz                  0.9.39                        2

hdf5                      1.8.17                        1

heapdict                  1.0.0                    py36_1

holoviews                 1.6.2                    py36_0

html5lib                  0.999                    py36_0

httplib2                  0.10.3                   py36_0    conda-forge

icu                       54.1                          0

idna                      2.2                      py36_0

imagesize                 0.7.1                    py36_0

ipykernel                 4.5.2                    py36_0

ipython                   5.1.0                    py36_1

ipython_genutils          0.1.0                    py36_0

ipywidgets                5.2.2                    py36_1

isort                     4.2.5                    py36_0

itsdangerous              0.24                     py36_0

jbig                      2.1                           0

jdcal                     1.3                      py36_0

jedi                      0.9.0                    py36_1

jinja2                    2.9.4                    py36_0

jpeg                      9b                            0

jsonschema                2.5.1                    py36_0

jupyter                   1.0.0                    py36_3

jupyter_client            4.4.0                    py36_0

jupyter_console           5.0.0                    py36_0

jupyter_core              4.2.1                    py36_0

lazy-object-proxy         1.2.2                    py36_0

libffi                    3.2.1                         1

libgcc                    4.8.5                         1

libiconv                  1.14                          0

libpng                    1.6.27                        0

libtiff                   4.0.6                         3

libxml2                   2.9.4                         0

libxslt                   1.1.29                        0

llvmlite                  0.15.0                   py36_0

locket                    0.2.0                    py36_1

lxml                      3.7.2                    py36_0

markupsafe                0.23                     py36_2

matplotlib                2.0.0               np111py36_0

mistune                   0.7.3                    py36_1

mkl                       2017.0.1                      0

mkl-service               1.1.2                    py36_3

mpmath                    0.19                     py36_1

multipledispatch          0.4.9                    py36_0

nbconvert                 4.2.0                    py36_0

nbformat                  4.2.0                    py36_0

ncurses                   5.9                          10

networkx                  1.11                     py36_0

nltk                      3.2.2                    py36_0

nodejs                    4.2.6                         0

nose                      1.3.7                    py36_1

notebook                  4.2.3                    py36_0

numba                     0.30.1              np111py36_0

numexpr                   2.6.1               np111py36_2

numpy                     1.11.3                   py36_0

numpydoc                  0.6.0                    py36_0

oauth2client              4.0.0                     <pip>

oauth2client              2.2.0                    py36_0    conda-forge

odo                       0.5.0                    py36_1

openpyxl                  2.4.1                    py36_0

openssl                   1.0.2k                        0

pandas                    0.19.2              np111py36_1

pandoc                    1.19.2.1                      0

pango                     1.40.3                        1

param                     1.4.2                    py36_0

partd                     0.3.7                    py36_0

path.py                   10.0                     py36_0

pathlib2                  2.2.0                    py36_0

patsy                     0.4.1                    py36_0

pcre                      8.39                          1

pep8                      1.7.0                    py36_0

pexpect                   4.2.1                    py36_0

pickleshare               0.7.4                    py36_0

pillow                    4.0.0                    py36_0

pip                       9.0.1                    py36_1

pixman                    0.34.0                        0

ply                       3.9                      py36_0

proj4                     4.9.2                         0

prompt_toolkit            1.0.9                    py36_0

psutil                    5.0.1                    py36_0

ptyprocess                0.5.1                    py36_0

py                        1.4.32                   py36_0

pyasn1                    0.1.9                    py36_0

pyasn1                    0.2.3                     <pip>

pyasn1-modules            0.0.8                    py36_0

pycosat                   0.6.1                    py36_1

pycparser                 2.17                     py36_0

pycrypto                  2.6.1                    py36_4

pycurl                    7.43.0                   py36_2

pyflakes                  1.5.0                    py36_0

pygments                  2.1.3                    py36_0

pylint                    1.6.4                    py36_1

pyopenssl                 16.2.0                   py36_0

pyparsing                 2.1.4                    py36_0

pyqt                      5.6.0                    py36_1

pytables                  3.3.0               np111py36_0

pytest                    3.0.5                    py36_0

python                    3.6.0                         0

python-dateutil           2.6.0                    py36_0

python.app                1.2                      py36_4

pytz                      2016.10                  py36_0

pyyaml                    3.12                     py36_0

pyzmq                     16.0.2                   py36_0

qt                        5.6.2                         0

qtawesome                 0.4.3                    py36_0

qtconsole                 4.2.1                    py36_1

qtpy                      1.2.1                    py36_0

r-assertthat              0.1                    r3.3.2_4

r-backports               1.0.4                  r3.3.2_0

r-base                    3.3.2                         1

r-base64enc               0.1_3                  r3.3.2_0

r-bh                      1.62.0_1               r3.3.2_0

r-bitops                  1.0_6                  r3.3.2_2

r-boot                    1.3_18                 r3.3.2_0

r-broom                   0.4.1                  r3.3.2_0

r-car                     2.1_4                  r3.3.2_0

r-caret                   6.0_73                 r3.3.2_0

r-catools                 1.17.1                 r3.3.2_2

r-class                   7.3_14                 r3.3.2_0

r-cluster                 2.0.5                  r3.3.2_0

r-codetools               0.2_15                 r3.3.2_0

r-colorspace              1.3_1                  r3.3.2_0

r-crayon                  1.3.2                  r3.3.2_0

r-curl                    2.3                    r3.3.2_0

r-data.table              1.10.0                 r3.3.2_0

r-dbi                     0.5_1                  r3.3.2_0

r-dichromat               2.0_0                  r3.3.2_2

r-digest                  0.6.10                 r3.3.2_0

r-dplyr                   0.5.0                  r3.3.2_0

r-essentials              1.5.2                  r3.3.2_0    r

r-evaluate                0.10                   r3.3.2_0

r-forcats                 0.1.1                  r3.3.2_0

r-foreach                 1.4.3                  r3.3.2_0

r-foreign                 0.8_67                 r3.3.2_0

r-formatr                 1.4                    r3.3.2_0

r-ggplot2                 2.2.0                  r3.3.2_0

r-gistr                   0.3.6                  r3.3.2_0

r-glmnet                  2.0_5                  r3.3.2_0

r-gtable                  0.2.0                  r3.3.2_0

r-haven                   1.0.0                  r3.3.2_0

r-hexbin                  1.27.1                 r3.3.2_0

r-highr                   0.6                    r3.3.2_0

r-hms                     0.3                    r3.3.2_0

r-htmltools               0.3.5                  r3.3.2_0

r-htmlwidgets             0.8                    r3.3.2_0

r-httpuv                  1.3.3                  r3.3.2_0

r-httr                    1.2.1                  r3.3.2_0

r-irdisplay               0.4.4                  r3.3.2_0

r-irkernel                0.7.1                  r3.3.2_0

r-iterators               1.0.8                  r3.3.2_0

r-jsonlite                1.1                    r3.3.2_0

r-kernsmooth              2.23_15                r3.3.2_0

r-knitr                   1.15.1                 r3.3.2_0

r-labeling                0.3                    r3.3.2_2

r-lattice                 0.20_34                r3.3.2_0

r-lazyeval                0.2.0                  r3.3.2_0

r-lme4                    1.1_12                 r3.3.2_0

r-lubridate               1.6.0                  r3.3.2_0

r-magrittr                1.5                    r3.3.2_2

r-maps                    3.1.1                  r3.3.2_0

r-markdown                0.7.7                  r3.3.2_2

r-mass                    7.3_45                 r3.3.2_0

r-matrix                  1.2_7.1                r3.3.2_0

r-matrixmodels            0.4_1                  r3.3.2_0

r-mgcv                    1.8_16                 r3.3.2_0

r-mime                    0.5                    r3.3.2_0

r-minqa                   1.2.4                  r3.3.2_2

r-mnormt                  1.5_5                  r3.3.2_0

r-modelmetrics            1.1.0                  r3.3.2_0

r-modelr                  0.1.0                  r3.3.2_0

r-munsell                 0.4.3                  r3.3.2_0

r-nlme                    3.1_128                r3.3.2_0

r-nloptr                  1.0.4                  r3.3.2_2

r-nnet                    7.3_12                 r3.3.2_0

r-openssl                 0.9.5                  r3.3.2_0

r-packrat                 0.4.8_1                r3.3.2_0

r-pbdzmq                  0.2_4                  r3.3.2_0

r-pbkrtest                0.4_6                  r3.3.2_0

r-pki                     0.1_3                  r3.3.2_0

r-plyr                    1.8.4                  r3.3.2_0

r-pryr                    0.1.2                  r3.3.2_0

r-psych                   1.6.9                  r3.3.2_0

r-purrr                   0.2.2                  r3.3.2_0

r-quantmod                0.4_7                  r3.3.2_0

r-quantreg                5.29                   r3.3.2_0

r-r6                      2.2.0                  r3.3.2_0

r-randomforest            4.6_12                 r3.3.2_0

r-rbokeh                  0.5.0                  r3.3.2_0

r-rcolorbrewer            1.1_2                  r3.3.2_3

r-rcpp                    0.12.8                 r3.3.2_0

r-rcppeigen               0.3.2.9.0              r3.3.2_0

r-rcurl                   1.95_4.8               r3.3.2_0

r-readr                   1.0.0                  r3.3.2_0

r-readxl                  0.1.1                  r3.3.2_0

r-recommended             3.3.2                  r3.3.2_0

r-repr                    0.10                   r3.3.2_0

r-reshape2                1.4.2                  r3.3.2_0

r-rjsonio                 1.3_0                  r3.3.2_2

r-rmarkdown               1.3                    r3.3.2_0

r-rpart                   4.1_10                 r3.3.2_0

r-rprojroot               1.1                    r3.3.2_0

r-rsconnect               0.7                    r3.3.2_0

r-rstudioapi              0.6                    r3.3.2_0

r-rvest                   0.3.2                  r3.3.2_0

r-scales                  0.4.1                  r3.3.2_0

r-selectr                 0.3_0                  r3.3.2_0

r-shiny                   0.14.2                 r3.3.2_0

r-sourcetools             0.1.5                  r3.3.2_0

r-sparsem                 1.74                   r3.3.2_0

r-spatial                 7.3_11                 r3.3.2_0

r-stringi                 1.1.2                  r3.3.2_0

r-stringr                 1.1.0                  r3.3.2_0

r-survival                2.40_1                 r3.3.2_0

r-tibble                  1.2                    r3.3.2_0

r-tidyr                   0.6.0                  r3.3.2_0

r-tidyverse               1.0.0                  r3.3.2_0

r-ttr                     0.23_1                 r3.3.2_0

r-uuid                    0.1_2                  r3.3.2_0

r-xml2                    1.0.0                  r3.3.2_0

r-xtable                  1.8_2                  r3.3.2_0

r-xts                     0.9_7                  r3.3.2_2

r-yaml                    2.1.14                 r3.3.2_0

r-zoo                     1.7_13                 r3.3.2_0

readline                  6.2                           2

redis                     3.2.0                         0

redis-py                  2.10.5                   py36_0

requests                  2.12.4                   py36_0

rope                      0.9.4                    py36_1

rpy2                      2.8.5                     <pip>

rsa                       3.4.2                    py36_0    conda-forge

rstudio                   1.0.136                       1

rtools                    0.2.12                    <pip>

ruamel_yaml               0.11.14                  py36_1

scikit-image              0.12.3              np111py36_1

scikit-learn              0.18.1              np111py36_1

scipy                     0.18.1              np111py36_1

seaborn                   0.7.1                    py36_0

setuptools                27.2.0                   py36_0

simplegeneric             0.8.1                    py36_1

singledispatch            3.4.0.3                  py36_0

sip                       4.18                     py36_0

six                       1.10.0                   py36_0

snowballstemmer           1.2.1                    py36_0

sockjs-tornado            1.0.3                    py36_0

sphinx                    1.5.1                    py36_0

spyder                    3.1.2                    py36_0

sqlalchemy                1.1.5                    py36_0

sqlite                    3.13.0                        0

statsmodels               0.6.1               np111py36_1

sympy                     1.0                      py36_0

terminado                 0.6                      py36_0

tk                        8.5.18                        0

toolz                     0.8.2                    py36_0

tornado                   4.4.2                    py36_0

traitlets                 4.3.1                    py36_0

unicodecsv                0.14.1                   py36_0

wcwidth                   0.1.7                    py36_0

werkzeug                  0.11.15                  py36_0

wheel                     0.29.0                   py36_0

widgetsnbextension        1.2.6                    py36_0

wrapt                     1.10.8                   py36_0

xarray                    0.9.1                    py36_0

xlrd                      1.0.0                    py36_0

xlsxwriter                0.9.6                    py36_0

xlwings                   0.10.2                   py36_0

xlwt                      1.2.0                    py36_0

xz                        5.2.2                         1

yaml                      0.1.6                         0

zeromq                    4.1.3                         0

zlib                      1.2.8                         3


----------
Karl Mochel
Interaction, Interface, Information, Experience  Design
kalm at kalmdesigns dot com
http://www.kalmdesigns.com
Also at: LinkedIn | Facebook

**Comment by goanpeca** [comment]
This is fixed by 1.6

**Comment by codebunny101** [comment]
Thanks for confirming this is fixed goanpeca.  However, how do I get 1.6?  It doesn't seem to be available as an automatic upgrade from the Navigator GUI.  Strangely the highest version I can 'easily' obtain from the "upgrade now" link at the top of the GUI screen is 1.5.3.

**Comment by goanpeca** [comment]
Its coming out in 3 days :-)
