### ISSUE TITLE
Anaconda Navigator not working

### ISSUE THREAD

**Issue by albus702** [ContinuumIO/anaconda-issues#1552]
Current conda install:

           
```
platform : osx-64
conda version : 4.3.14
conda is private : False
conda-env version : 4.3.14
conda-build version : 2.1.8
python version : 2.7.13.final.0
requests version : 2.13.0
root environment : /Users/username/anaconda  (writable)
default environment : /Users/username/anaconda
envs directories : /Users/username/anaconda/envs
                             /Users/username/.conda/envs
package cache : /Users/username/anaconda/pkgs
                            /Users/username/.conda/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
config file : /Users/username/.condarc
offline mode : False
user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.13 Darwin/16.4.0 OSX/10.12.3
UID:GID : 501:20

> $anaconda-navigator 
Traceback (most recent call last): File "/Users/username/anaconda/bin/anaconda-navigator", line 4, in import anaconda_navigator.app.main File "/Users/username/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 21, in from anaconda_navigator.widgets.dialogs.splash import SplashScreen File "/Users/username/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/init.py", line 18, in from anaconda_navigator.utils.analytics import GATracker File "/Users/username/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/analytics.py", line 33, in from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal ImportError: cannot import name QT_VERSION_STR

```

```
> $anaconda-navigator--help 
Traceback (most recent call last): File "/Users/username/anaconda/bin/anaconda-navigator", line 4, in import anaconda_navigator.app.main File "/Users/username/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 21, in from anaconda_navigator.widgets.dialogs.splash import SplashScreen File "/Users/username/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/init.py", line 18, in from anaconda_navigator.utils.analytics import GATracker File "/Users/username/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/analytics.py", line 33, in from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal ImportError: cannot import name QT_VERSION_STR
```

**Comment by goanpeca** [comment]
@albus702 could you type `conda list` and paste the output?

**Comment by albus702** [comment]
> 
> conda list
packages in environment at /Users/username/anaconda:
_license                  1.1                      py27_1  
abstract-rendering        0.5.1               np111py27_0  
alabaster                 0.7.10                   py27_0  
anaconda                  custom                   py27_0  
anaconda-clean            1.1.0                    py27_0  
anaconda-client           1.6.2                    py27_0  
anaconda-navigator        1.2.3                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
argparse                  1.3.0                     <pip>
astropy                   1.3.1               np111py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
bcolz                     1.0.0                    py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.5.3                    py27_0  
binstar                   0.12                          2  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
blaze-core                0.9.0                    py27_0  
bleach                    1.5.0                    py27_0  
blz                       removed                       0  
bokeh                     0.12.4                   py27_0  
boto                      2.46.1                   py27_0  
bottleneck                1.2.0               np111py27_0  
cdecimal                  2.3                      py27_2  
certifi                   2016.2.28                py27_0  
cffi                      1.9.1                    py27_0  
chardet                   2.3.0                    py27_0  
cheat                     2.1.27                    <pip>
chest                     0.2.3                    py27_0  
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.3.14                   py27_0  
conda-build               2.1.8                    py27_0  
conda-env                 2.6.0                         0  
conda-manager             0.4.0                    py27_0  
conda-verify              2.0.0                    py27_0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.4                    py27_0  
cryptography              1.7.1                    py27_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask                      0.14.1                   py27_0  
datashape                 0.5.4                    py27_0  
decorator                 4.0.11                   py27_0  
dill                      0.2.5                    py27_0  
docopt                    0.6.2                     <pip>
docutils                  0.13.1                   py27_0  
dynd-python               0.7.2                    py27_0  
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
eventlet                  0.17.4                    <pip>
fastcache                 1.0.2                    py27_1  
filelock                  2.0.7                    py27_0  
flask                     0.12                     py27_0  
flask-cors                3.0.2                    py27_0  
freetype                  2.5.5                         2  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.0                    py27_0  
gevent-socketio           0.3.6                     <pip>
gevent-websocket          0.9.5                    py27_1  
greenlet                  0.4.12                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.7.0               np111py27_0  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
HPOlibConfigSpace         0.1.dev0                  <pip>
html5lib                  0.999                    py27_0  
idna                      2.2                      py27_0  
imagesize                 0.7.1                    py27_0  
imutils                   0.3.6                     <pip>
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.5.2                    py27_0  
ipython                   5.3.0                    py27_0  
ipython-notebook          4.0.4                    py27_0  
ipython-qtconsole         4.0.1                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                6.0.0                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.9.0                    py27_1  
jinja2                    2.9.5                    py27_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            5.0.0                    py27_0  
jupyter_console           5.1.0                    py27_0  
jupyter_core              4.3.0                    py27_0  
launcher                  1.0.0                         3  
libdynd                   0.7.2                         0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.16.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.7.3                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                2.0.0                     <pip>
mistune                   0.7.4                    py27_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_3  
mock                      2.0.0                    py27_0  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.9                    py27_0  
nbconvert                 5.1.1                    py27_0  
nbformat                  4.3.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.2                    py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_1  
notebook                  4.4.1                    py27_0  
numba                     0.31.0              np111py27_0  
numexpr                   2.6.2               np111py27_0  
numpy                     1.11.3                   py27_0  
numpy                     1.11.0                    <pip>
odo                       0.5.0                    py27_1  
olefile                   0.44                     py27_0  
openpyxl                  2.4.1                    py27_0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np111py27_1  
pandocfilters             1.4.1                    py27_0  
ParamSklearn              0.1.dev0                  <pip>
partd                     0.3.7                    py27_0  
path.py                   10.1                     py27_0  
pathlib2                  2.2.0                    py27_0  
patsy                     0.4.1                    py27_0  
pbr                       1.10.0                   py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    4.0.0                    py27_1  
pip                       9.0.1                     <pip>
pip                       9.0.1                    py27_1  
pkginfo                   1.4.1                    py27_0  
ply                       3.10                     py27_0  
prompt_toolkit            1.0.13                   py27_0  
protobuf                  3.0.0b2                   <pip>
psutil                    5.2.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.32                   py27_0  
pyasn1                    0.2.3                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.2                    py27_0  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_2  
pyenchant                 1.6.6                     <pip>
pyflakes                  1.5.0                    py27_0  
pygments                  2.2.0                    py27_0  
pymongo                   3.0.3                     <pip>
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_4  
pytables                  3.3.0               np111py27_0  
pytesseract               0.1.6                     <pip>
pytest                    3.0.7                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
python-engineio           0.7.1                     <pip>
python-socketio           0.6.0                     <pip>
python.app                1.2                      py27_4  
pytz                      2016.10                  py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        4.8.7                         4  
qtawesome                 0.4.4                    py27_0  
qtconsole                 4.2.1                    py27_0  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.13.0                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
runipy                    0.1.5                    py27_0  
scandir                   1.5                      py27_0  
scikit-learn              0.18.1              np111py27_1  
scipy                     0.19.0              np111py27_0  
setuptools                27.2.0                   py27_0  
setuptools                20.7.0                    <pip>
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
six                       1.10.0                    <pip>
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.5.1                    py27_0  
sphinx_rtd_theme          0.1.9                    py27_1  
spyder                    2.3.8                    py27_1  
spyder-app                2.3.8                    py27_0  
sqlalchemy                1.1.6                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.8.0               np111py27_0  
subprocess32              3.2.7                     <pip>
sympy                     1.0                      py27_0  
tensorflow                0.8.0rc0                  <pip>
terminado                 0.6                      py27_0  
testpath                  0.3                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.2                    py27_0  
ujson                     1.35                     py27_0  
unicodecsv                0.14.1                   py27_0  
utils                     0.8.0                     <pip>
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.12                     py27_0  
wheel                     0.29.0                    <pip>
wheel                     0.29.0                   py27_0  
widgetsnbextension        2.0.0                    py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
XlsxWriter                0.9.4                     <pip>
xlwings                   0.10.4                   py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         3

**Comment by goanpeca** [comment]
@albus702 it seems you are using an old version of navigator and you are using qt=4 (which is deprecated)

Could you update to the latest version of anaconda-navigator?

Please open a terminal and tyupe

`conda install anaconda-navigator=1.5`

**Comment by tbsexton** [comment]
I'm getting the same error, and running the above gets 
```
Fetching package metadata .........
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.5* -> pyqt >=5.6
  - chaco
  - matplotlib
Use "conda info <package>" to see the dependencies for each package.

```

In addition, trying to force the pyqt update from anaconda cloud: 
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - chaco
  - matplotlib -> freetype 2.4*
  - matplotlib -> pyqt 4.* -> qt >=4.8.6,<5.0
  - pyqt 5.6.0*
Use "conda info <package>" to see the dependencies for each package.

```

Running python 2.7.3

**Comment by goanpeca** [comment]
Could you remove matplotlib and chaco before?

`conda remove matplotlib chaco`
`conda install anaconda-navigator=1.5.1`

**Comment by tbsexton** [comment]
The first command resulted in
```
The following packages will be REMOVED:

    chaco:        4.5.0-np110py27_0 
    matplotlib:   1.5.1-np110py27_0 
    scikit-image: 0.12.3-np110py27_1
    seaborn:      0.7.1-py27_0      
```

The second downgraded pretty much every scientific computing package I use:
```
The following NEW packages will be INSTALLED:

    anaconda-project:   0.4.1-py27_0      
    dbus:               1.10.10-0         
    gst-plugins-base:   1.8.0-0           
    gstreamer:          1.8.0-0           
    icu:                54.1-0            
    libgcc:             5.2.0-0           
    libxcb:             1.12-1            
    pyside:             1.2.0-py27_0      
    shiboken:           1.2.1-py27_0      

The following packages will be UPDATED:

    anaconda-navigator: 1.2.3-py27_0       --> 1.5.1-py27_0     
    pyqt:               4.11.4-py27_4      --> 5.6.0-py27_2     
    qt:                 4.8.7-4            --> 5.6.2-0          
    qtconsole:          4.2.1-py27_0       --> 4.2.1-py27_1     

The following packages will be DOWNGRADED due to dependency conflicts:

    abstract-rendering: 0.5.1-np110py27_0  --> 0.5.0-np18py27_0 
    astropy:            1.1.2-np110py27_0  --> 0.4.1-np18py27_0 
    atom:               0.3.10-py27_0      --> 0.3.5-py27_0     
    dask:               0.13.0-py27_0      --> 0.11.1-py27_0    
    enable:             4.5.1-np110py27_0  --> 4.3.0-np18py27_1 
    enaml:              0.9.8-py27_1       --> 0.8.9-py27_0     
    h5py:               2.6.0-np110py27_1  --> 2.3.1-np18py27_0 
    hdf5:               1.8.16-0           --> 1.8.9-1          
    numba:              0.26.0-np110py27_0 --> 0.13.4-np18py27_0
    numexpr:            2.5.2-np110py27_1  --> 2.3.1-np18py27_0 
    numpy:              1.10.4-py27_2      --> 1.8.2-py27_0     
    odo:                0.5.0-py27_1       --> 0.4.2-py27_0     
    pandas:             0.18.1-np110py27_0 --> 0.14.1-np18py27_0
    ply:                3.10-py27_0        --> 3.4-py27_0       
    pyface:             4.5.2-py27_0       --> 4.4.0-py27_0     
    pytables:           3.2.2-np110py27_3  --> 3.1.1-np18py27_1 
    scikit-learn:       0.17.1-np110py27_2 --> 0.15.2-np18py27_0
    scipy:              0.17.1-np110py27_1 --> 0.14.0-np18py27_0
    statsmodels:        0.6.1-np110py27_1  --> 0.5.0-np18py27_0 
    theano:             0.9.0-py27_0       --> 0.8.2-py27_0     
    traits:             4.5.0-py27_0       --> 4.4.0-py27_0     
    traitsui:           4.5.1-py27_0       --> 4.4.0-py27_0     
```

Also, still broken, since running `anaconda-navigator` results in a type error 
```
Traceback (most recent call last):
  File "/home/tbsexton/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 723, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 50, in __init__
    self._conda_api = CondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1314, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 308, in __init__
    self.set_root_prefix()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 428, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str
```

**Comment by goanpeca** [comment]
If you open a terminal and type

`conda info --json` what is the output?

**Comment by tbsexton** [comment]
```
{
  "GID": 1000, 
  "UID": 1000, 
  "channels": [
    "https://repo.continuum.io/pkgs/free/linux-64", 
    "https://repo.continuum.io/pkgs/free/noarch", 
    "https://repo.continuum.io/pkgs/r/linux-64", 
    "https://repo.continuum.io/pkgs/r/noarch", 
    "https://repo.continuum.io/pkgs/pro/linux-64", 
    "https://repo.continuum.io/pkgs/pro/noarch"
  ], 
  "conda_build_version": "2.1.8", 
  "conda_env_version": "4.3.15", 
  "conda_prefix": "/home/tbsexton/anaconda", 
  "conda_private": false, 
  "conda_version": "4.3.15", 
  "default_prefix": "/home/tbsexton/anaconda", 
  "env_vars": {
    "CIO_TEST": "<not set>", 
    "CONDA_DEFAULT_ENV": "<not set>", 
    "CONDA_ENVS_PATH": "<not set>", 
    "LD_LIBRARY_PATH": "<not set>", 
    "PATH": "~/anaconda/bin:/opt/texbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games", 
    "PYTHONHOME": "<not set>", 
    "PYTHONPATH": "<not set>"
  }, 
  "envs": [
    "/home/tbsexton/anaconda/envs/elfi"
  ], 
  "envs_dirs": [
    "/home/tbsexton/anaconda/envs", 
    "/home/tbsexton/.conda/envs"
  ], 
  "offline": false, 
  "pkgs_dirs": [
    "/home/tbsexton/anaconda/pkgs", 
    "/home/tbsexton/.conda/pkgs"
  ], 
  "platform": "linux-64", 
  "python_version": "2.7.13.final.0", 
  "rc_path": null, 
  "requests_version": "2.13.0", 
  "root_prefix": "/home/tbsexton/anaconda", 
  "root_writable": true, 
  "site_dirs": [], 
  "sys.executable": "/home/tbsexton/anaconda/bin/python", 
  "sys.prefix": "/home/tbsexton/anaconda", 
  "sys.version": "2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]", 
  "sys_rc_path": "/home/tbsexton/anaconda/.condarc", 
  "user_agent": "conda/4.3.15 requests/2.13.0 CPython/2.7.13 Linux/4.4.0-21-generic debian/stretch/sid glibc/2.23", 
  "user_rc_path": "/home/tbsexton/.condarc"
}
```

**Comment by goanpeca** [comment]
@tbsexton I am sorry I dont know what the problem is :-|

**Comment by goanpeca** [comment]
Lets try to see what the info is returning, could you open

`/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py`
And add in line 428, in set_root_prefix

from:
```python
    self.ROOT_PREFIX = info['root_prefix']
```
to:
```python
    print(info)
    self.ROOT_PREFIX = info['root_prefix']
```

And the paste the output of running `anaconda-navigator`?

**Comment by tbsexton** [comment]
```
Traceback (most recent call last):
  File "/home/tbsexton/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 723, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 50, in __init__
    self._conda_api = CondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1315, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 308, in __init__
    self.set_root_prefix()
  File "/home/tbsexton/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 429, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str
Segmentation fault
```

**Comment by tbsexton** [comment]
@goanpeca it looks identical, and strangely I don't see a printout of `info`

**Comment by tbsexton** [comment]
@goanpeca I decided to use a bit of a nuclear option. `rm -rf anaconda` at the directory location and reinstalled from the newest shell script online. 

`anaconda-navigator` works like a charm now, with no dependency conflicts. Not sure what was causing this, but I guess it's nice to have a fresh install anyway.

**Comment by goanpeca** [comment]
@tbsexton I was going to suggest that, but its a bummer to suggest that :-\

**Comment by goanpeca** [comment]
Glad it works works now though

**Comment by albus702** [comment]
I managed to fix mine.

`conda install anaconda-navigator=1.5`

>Fetching package metadata .........
>Solving package specifications: .
>UnsatisfiableError: The following specifications were found to be in conflict:
>  - anaconda-navigator 1.5*
>  - spyder-app -> spyder 2.3.1 -> pyqt 4.* -> qt 4.8.5
>  - spyder-app -> spyder 2.3.1 -> pyqt 4.* -> sip 4.15.*
> Use "conda info <package>" to see the dependencies for each package.

`conda remove spyder-app`

>Fetching package metadata .........
>Solving package specifications: .
>Package plan for package removal in environment /Users/ajinkyapuar/anaconda:
>The following packages will be REMOVED:
>    spyder-app: 2.3.8-py27_0
>Proceed ([y]/n)? y

`conda remove anaconda-navigator`

>Fetching package metadata .........
>Solving package specifications: .
>Package plan for package removal in environment /Users/ajinkyapuar/anaconda:
>The following packages will be REMOVED:
>    anaconda-navigator: 1.2.3-py27_0
>Proceed ([y]/n)? y

`conda install anaconda-navigator=1.5`

>Fetching package metadata .........
>Solving package specifications: .
>Package plan for installation in environment /Users/username/anaconda:
>The following NEW packages will be INSTALLED:

    anaconda-navigator: 1.5.1-py27_0 
    anaconda-project:   0.4.1-py27_0 
    astroid:            1.4.9-py27_0 
    icu:                54.1-0       
    isort:              4.2.5-py27_0 
    lazy-object-proxy:  1.2.2-py27_0 
    numpydoc:           0.6.0-py27_0 
    pylint:             1.6.4-py27_1 
    wrapt:              1.10.8-py27_0

The following packages will be UPDATED:

    conda:              4.3.14-py27_0 --> 4.3.15-py27_0
    pyqt:               4.11.4-py27_4 --> 5.6.0-py27_2 
    qt:                 4.8.7-4       --> 5.6.2-0      
    qtconsole:          4.2.1-py27_0  --> 4.3.0-py27_0 
    spyder:             2.3.8-py27_1  --> 3.1.3-py27_0 

>Proceed ([y]/n)? y
icu-54.1-0.tar 100% |################################| Time: 0:02:02  93.50 kB/s
qt-5.6.2-0.tar 100% |################################| Time: 0:02:22 486.16 kB/s
qt-5.6.2-0.tar 100% |################################| Time: 0:07:16 158.83 kB/s
qt-5.6.2-0.tar 100% |################################| Time: 0:02:52 401.34 kB/s
lazy-object-pr 100% |################################| Time: 0:00:00 289.50 kB/s
wrapt-1.10.8-p 100% |################################| Time: 0:00:00 293.89 kB/s
astroid-1.4.9- 100% |################################| Time: 0:00:00 350.24 kB/s
isort-4.2.5-py 100% |################################| Time: 0:00:00 262.31 kB/s
pyqt-5.6.0-py2 100% |################################| Time: 0:00:22 200.70 kB/s
pylint-1.6.4-p 100% |################################| Time: 0:00:00 505.01 kB/s
anaconda-proje 100% |################################| Time: 0:00:00 527.94 kB/s
numpydoc-0.6.0 100% |################################| Time: 0:00:00 910.93 kB/s
anaconda-navig 100% |################################| Time: 0:00:15 321.87 kB/s
conda-4.3.15-p 100% |################################| Time: 0:00:00   1.01 MB/s
qtconsole-4.3. 100% |################################| Time: 0:00:00   1.35 MB/s
spyder-3.1.3-p 100% |################################| Time: 0:00:07 417.46 kB/s


Thanks
