### ISSUE TITLE
unable to launch any console from anaconda navigator

### ISSUE THREAD

**Issue by nitishr19** [ContinuumIO/anaconda-issues#1553]
plz help me to open all the consoles in navigator for gui based works

**Comment by goanpeca** [comment]
@nitishr19 please open a terminal / command prompt and type

`conda info` and `conda list` and paste the output of running those commands

**Comment by nitishr19** [comment]
hi ,sorry i cant get your commnts ,where to paste and what to paste?
plz explain

**Comment by nitishr19** [comment]
![conda1](https://cloud.githubusercontent.com/assets/25814007/24323437/2549494e-119b-11e7-8f4d-f36e470946d8.png)
![conda2](https://cloud.githubusercontent.com/assets/25814007/24323441/292c561e-119b-11e7-8322-296f4996f65b.png)

**Comment by goanpeca** [comment]
@nitishr19 

We have some issues with spaces on windows for launching applications. So I have the following suggestion to get you system to work

1.) Reinstall Anaconda for the current user (and not all users as you did)
2.) Make sure the path of installation does not include spaces. In this case you username is ok (`C:/users/Nitish/anaconda` should work fine)

We are working on a fix, but in the meantime this will get your system running without issues
