### ISSUE TITLE
kqueue warnings when launching spyder on macos sierra

### ISSUE THREAD

**Issue by hartemink** [ContinuumIO/anaconda-issues#1555]
i have already spent a number of hours looking here and elsewhere online, reading about conda, anaconda, spyder, qt, libevent, macos sierra, chromium, tmux, etc.  however, i still can’t figure out exactly why my kqueue warnings have not yet gone away when i run spyder on macos sierra.

i already understand from other threads that it’s not spyder’s fault, and that the kqueue issue has been fixed upstream in libevent, so i thought i was just waiting for some intermediate software to start using the fixed version of libevent.  specifically, i understood that these warnings would go away once i was using qt 5.6.2 (maybe i misunderstood that).  and yet, here is my setup and i’m still getting all the warnings:

=============

Current conda install:

              platform : osx-64
         conda version : 4.3.14
      conda is private : False
     conda-env version : 4.3.14
   conda-build version : not installed
        python version : 3.5.3.final.0
      requests version : 2.13.0
      root environment : /Users/amink/Applications/Miniconda3  (writable)
   default environment : /Users/amink/Applications/Miniconda3
      envs directories : /Users/amink/Applications/Miniconda3/envs
                         /Users/amink/.conda/envs
         package cache : /Users/amink/Applications/Miniconda3/pkgs
                         /Users/amink/.conda/pkgs
          channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                         https://repo.continuum.io/pkgs/free/noarch
                         https://repo.continuum.io/pkgs/r/osx-64
                         https://repo.continuum.io/pkgs/r/noarch
                         https://repo.continuum.io/pkgs/pro/osx-64
                         https://repo.continuum.io/pkgs/pro/noarch
           config file : None
          offline mode : False
            user-agent : conda/4.3.14 requests/2.13.0 CPython/3.5.3 Darwin/16.4.0 OSX/10.12.3

and here are some relevant package versions in my environment:

ipython                   5.3.0                    py35_0  
python                    3.5.3                         1  
python.app                1.2                      py35_4
pyqt                      5.6.0                    py35_2  
qt                        5.6.2                         0  
qtawesome                 0.4.4                    py35_0  
qtconsole                 4.2.1                    py35_1  
qtpy                      1.2.1                    py35_0
spyder                    3.1.3                    py35_0

=============

i think i have the latest versions of all the packages, including qt 5.6.2, but i still get the kqueue warnings.  where along the chain is the corrected libevent not being included?  might it be pyqt, which is suspiciously at 5.6.0?

**Comment by mingwandroid** [comment]
I think you need to just ignore these warnings.

**Comment by ccordoba12** [comment]
Please see https://github.com/spyder-ide/spyder/issues/3730

**Comment by ccordoba12** [comment]
The solution is there.

**Comment by hartemink** [comment]
i can ignore the warnings, and i guess the solution of setting an environment variable to eliminate the warnings is a sort of solution, but it isn't satisfying because it means that i'm eliminating the warnings about kqueues by disabling their use.  i'm not necessarily asking for anything to be fixed -- i'm mostly asking to help understand where the problem lies.  i guess i can boil it down to: libevent has fixed the bug, and qt 5.6.2 is claimed to have addressed the bug somehow, and spyder is not the problem, so who is dropping the ball on the chain from libevent to spyder?

**Comment by mingwandroid** [comment]
> so who is dropping the ball on the chain from libevent to spyder?

No idea. In the scheme of things I'm not going to spend two days deep diving into the stack to figure that out (please, if you care enough then go ahead). When programming, programmer X may choose to emit a warning about every minor detail while programmer Y only about very important things so seeing a warning is not indicative a serious problem, unless of course it's strongly correlated with a serious problem.

**Comment by hartemink** [comment]
fair enough.  i was not asking for an investigation.  i was just curious if someone knew, without investigating.  thanks!

**Comment by ccordoba12** [comment]
This https://github.com/tmux/tmux/issues/475#issuecomment-231527159 says it clearly

> kqueue is broken on OS X

I agree with @mingwandroid: we're not going to waste our to fix something that seems to be broken.

**Comment by hartemink** [comment]
my impression was that kqueue is not broken on os x (now macos) but that the issue is a bug in libevent that was only visible when running on os x: https://github.com/tmux/tmux/issues/475#issuecomment-248477013 

so i was confused when libevent fixed the bug and yet i still get the error.  as i said, i'm not asking for an investigation, nor for anything to be fixed, nor for you to "waste your time".  i was just seeing if someone actually knew what was going on.

**Comment by hartemink** [comment]
p.s.  no need to reply further.  perhaps someone will eventually reply who has an idea about why this is happening, or perhaps the warnings will eventually go away, at which point i'll update the thread to let others know what changed.
