### ISSUE TITLE
Not able to launch sypder from anaconda Navigator 

### ISSUE THREAD

**Issue by satyams407** [ContinuumIO/anaconda-issues#1556]
When ever I try to launch sypder or jupyter notebook from navigator It shows loading bar at the bottom and after some time it get disappear . I tried on more than one version of spyder but still it's not launching on Windows 32-bit. @ccordoba12 @jdweaver @goanpeca 

I also tried to run command spyder --reset on command prompt but still problem hasn't been solved. 

![screenshot 752](https://cloud.githubusercontent.com/assets/13750239/24330631/69813306-1240-11e7-8287-f28223358a1a.png)
![screenshot 755](https://cloud.githubusercontent.com/assets/13750239/24330632/6982b1ae-1240-11e7-8821-eb731128417d.png)
After some time it also get disppear and nothing get launch 
![screenshot 757](https://cloud.githubusercontent.com/assets/13750239/24330633/69858910-1240-11e7-984a-4e9859771e9b.png)

**Comment by ccordoba12** [comment]
Please start Spyder from a terminal with

    spyder --show-console

and report what errors appear there (if any)

**Comment by goanpeca** [comment]
@satyams407 we have a problem with spaces in the path that is fixed in the latest release of navigator to be released this week

**Comment by satyams407** [comment]
@ccordoba12  Now It's working fine from the terminal .Thanks a lot sir
