### ISSUE TITLE
AnacondaProjects folder created without user's permission

### ISSUE THREAD

**Issue by mhavu** [ContinuumIO/anaconda-issues#1557]
Anaconda Navigator creates folder AnacondaProjects inside user's home directory at startup without user's permission. This behaviour should be optional, and the user should be able to set the folder location in application preferences.

**Comment by goanpeca** [comment]
@chdoig ?

**Comment by danilo-augusto** [comment]
Very annoying indeed

**Comment by chdoig** [comment]
@mhavu, thanks for the feedback. We are working on making this change for 1.6 release:

- Don't create a project folder when Navigator starts. 
- When you go to the Projects tab, and a folder has not been defined, then ask the user: Select Projects folder or Create new folder. 
- When selecting Create, you can select where the folder is created and the name of the folder.

**Comment by goanpeca** [comment]
@mhavu this will be coming next week with the new navigator release

**Comment by rcfrias** [comment]
Where can I find this on the newest anaconda navigator? I would also like to define my own path for my anaconda projects.
