### ISSUE TITLE
Anaconda rstudio

### ISSUE THREAD

**Issue by alfredzj** [ContinuumIO/anaconda-issues#1558]
Hi guys,

I use `conda install -c rdonnelly rstudio=1.0.44` to install rstudio in my pc (Ubuntu 16.04). Nut when I open it in the terminal, but it always shows that 
`load glyph failed err=6 face=0xdd8d20, glyph=2797
load glyph failed err=6 face=0xdd8d20, glyph=2797
`

Do you guys know how to fix it?

**Comment by mingwandroid** [comment]
Please install the latest from defaults instead:

conda install rstudio

**Comment by alfredzj** [comment]
Hi the situation stills exist if I install the latest version. 

> 
platform : linux-64
conda version : 4.3.14
python version : 2.7.13
R version: 3.3.2 (2016-10-31): /home/xxx/anaconda2/bin/R

**Comment by mingwandroid** [comment]
Does this cause you any problems or is it just some warning text?

**Comment by alfredzj** [comment]
Just the two-line warning. But I am very curious why it happens.

**Comment by mingwandroid** [comment]
Searching using Google turns up:

https://support.rstudio.com/hc/en-us/community/posts/222368268-Ubuntu-16-04-freezes-when-using-Rstudio-load-glyph-failed-

.. while no answer is provided, it doesn't seem to be a problem that concerns upstream RStudio too much so I'd try not to worry.

**Comment by alfredzj** [comment]
I found those things before and didn't figure out what is going on. 
Initially I suspect it is because I installed Rstudio from conda. However the error still exists when I install Rstudio from their website.
Thank you anyway.

**Comment by mingwandroid** [comment]
OK, thanks, I'm going to close this as it's harmless and has been reported upstream already.
