### ISSUE TITLE
Could use Py 3.6 build of pyqt 4.* plus matplotlib

### ISSUE THREAD

**Issue by jeanconn** [ContinuumIO/anaconda-issues#1559]
Not sure if this is related to other Qt issues, but I don't seem to be having much luck with Qt5 vs my nomachine NX environment, and would also like to use Python 3.6.  So it would be great if somebody could add the Python 3.6 + pyqt 4.* combination to the build system (and associated builds ... i.e. matplotlib against that 3.6 pyqt 4.* ) for now.

**Comment by mingwandroid** [comment]
Qt4 is many years old now and no longer supported so we won't be building it for Python 3.6.

If you need to use it (please give full details of what goes wrong with Qt5) then you are stuck on Python 3.5 I am afraid.

**Comment by ccordoba12** [comment]
Sorry, but that's not going to happen. We're not going to create more PyQt4 packages because Qt4 reached end of life in December 2015.

**Comment by jeanconn** [comment]
OK!  Thanks.  I built it and matplotlib with Qt4 myself but was hoping not to maintain custom packages for these and figured this was just adding a combination to your build system (which I haven't examined).  For Qt5 in nomachine NX I get warnings like:
```
# QXcbConnection: XCB error: 173 (Unknown), sequence: 164, resource id: 89,
#   major code: 150 (Unknown), minor code: 20
```
and figure I have to do some custom Qt5 build to fix that.

**Comment by mingwandroid** [comment]
Do those warnings cause more than minor annoyance? If not I'd suggest ignoring them.

**Comment by ccordoba12** [comment]
You can use conda-forge if you need this combination. Conda-forge is a community maintained set of packages of very good quality.

**Comment by ccordoba12** [comment]
Yeah, that warning is harmless.

**Comment by jeanconn** [comment]
Thanks for the conda-forge suggestion @ccordoba12 ! I haven't been paying much attention to the evolution of package support and was working straight off of "If you need a package that’s not availble [sic] on this page, please go to the Anaconda issues page and click the Submit button to request one."

**Comment by ccordoba12** [comment]
Yep, conda-forge released a lot of pressure from our shoulders!

**Comment by ccordoba12** [comment]
But please be sure to use conda-forge packages in a different environment from root because conda-forge and default packages are not compatible (use different compilers, under different Linux versions, etc)
