### ISSUE TITLE
miniconda/anaconda installers for tcsh and sh (bourne shell)

### ISSUE THREAD

**Issue by j3mdamas** [ContinuumIO/anaconda-issues#1560]
There are still people who use `tsch` or `sh` as login, and many times they are not even aware.

It would be nice if the default installers, for example Miniconda ones (https://conda.io/miniconda.html), would detect the shell environment and suggest the appropriate login profile. For example, in bourne shell it's `~/.profile` and tsch it's `~/.tcshrc`.

I could modify that part of the code myself and do a pull request, but I can't find the source of the installers anywhere in here. Are they available here or somewhere else? Google did not help me much either.

Thanks,
João

(from https://github.com/conda/conda/issues/4951)

**Comment by ilanschnell** [comment]
So Miniconda can be installed just fine on machines where you use `tcsh`, `ksh`, `sh`, etc. , all you need to do is type `bash Miniconda...` (regardless of which type of shell you are actually using).  The only change to the `.bashrc` which is being made is to add the Miniconda `bin/` to `PATH`, which is easily to do manually if you use any other shell as well.

**Comment by j3mdamas** [comment]
Yes, it is easy indeed. For me at least, and anyone who knows Linux.

I still find the help that is printed at the end of the installation very useful for those who are not as savant. My point is that the suggestion is directly related with `.bashrc`, which will not do anything for those who then login with tcsh, for example (no conda in the PATH).

Also, the manual suggestion does not work for something like tcsh, where export is not available (and setenv is used instead).

It was just a suggestion for something more user friendly. I can do it myself by editing your own installers and providing them instead of linking to yours, but I would like to contribute to make the installers more user-friendly, if it was possible.

The source of the installers is not available for modification and pull request?

Thanks,
João

**Comment by goanpeca** [comment]
@ilanschnell ?

**Comment by ilanschnell** [comment]
The header of the `.sh` installer is available here: https://github.com/conda/constructor/blob/master/constructor/header.sh , and PR's are welcome.

**Comment by j3mdamas** [comment]
Great! This is what I wanted and I couldn't find. Thanks!

I'll test some different shell environments and when I have something good, I'll do a PR

**Comment by goanpeca** [comment]
@j3mdamas thanks for the help to make this process much better :-)

**Comment by j3mdamas** [comment]
Hi guys,

Sorry I didn't close this before. I'm working on having our own constructor, so I dropped this.

Thanks for the help anyway
