### ISSUE TITLE
conda build R packages to different library location

### ISSUE THREAD

**Issue by deliarusu** [ContinuumIO/anaconda-issues#1562]
I'm following the instructions from https://www.continuum.io/content/conda-data-science in order to build a CRAN-available R package (e.g. party).
```
conda skeleton cran party
conda build r-party
```
How can I change the default conda build sequence to install to a different library location, as I don't have permission to install to the default one? 
  ```
 installing to library ‘/path/to/default/lib’
   Error: ERROR: no permission to install to directory ‘/path/to/default/lib’
```
Also, I'm running conda build from within a conda env.

Also tried `conda build --croot /path/to/somewhere/env r-party/`, but got same error.

This was also posted here: https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/conda/wVrcvH7znzg/T1XTyP1JCQAJ

The full build output:
[conda-build-issue.txt](https://github.com/ContinuumIO/anaconda-issues/files/877335/conda-build-issue.txt)

**Comment by mingwandroid** [comment]
I didn't mean for you to use `/path/to/somewhere` literally here. Is that what you did?

Can you show the literal output from `conda info` and `conda list --show-channel-urls`?

**Comment by deliarusu** [comment]
I did not use the /path/to/somewhere literally :) but cannot show the exact paths.

```
/path/to/anaconda3 - the anaconda install path
/path/to/somewhere/env - path to the conda env
```
* these are not the actual paths

Current `conda list` output is here: 
[current-conda-install.txt](https://github.com/ContinuumIO/anaconda-issues/files/877572/current-conda-install.txt)
And the ` conda list --show-channel-urls ` output is here: 
[conda-channel-urls.txt](https://github.com/ContinuumIO/anaconda-issues/files/877584/conda-channel-urls.txt)

**Comment by mingwandroid** [comment]
Did you have to install anaconda with read-only permissions or as super user? The easiest solution is to install it normally, e.g. inside your $HOME directory.

**Comment by mingwandroid** [comment]
You should try `conda update -n root conda-build`, you may need to run that with sudo though because of how you installed anaconda.

Because you cannot show actual unmodified PATHs, it is difficult for me to know if you've made an error when 1) installing (spaces, unicode, too deep a PATH) or 2) when modifying the output files.

For example, this looks wrong to me:

```
/path/to/somewhere/env/r-party_1490741733740/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/R
CMD INSTALL --build .
* installing to library ‘/path/to/R’
Error: ERROR: no permission to install to directory ‘/path/to/R’
```

I would have expected instead to see:

```
/path/to/somewhere/env/r-party_1490741733740/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/R
CMD INSTALL --build .
* installing to library ‘/path/to/somewhere/env/r-party_1490741733740/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/R’
Error: ERROR: no permission to install to directory ‘/path/to/somewhere/env/r-party_1490741733740/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/R’
```

**Comment by lparkes** [comment]
@mingwandroid Yes, you are right. We (I work with @deliarusu) are not expecting to see /path/to/R either and I can't see where it is coming from. It's certainly not in ~/.Rprofile. This is what has us stumped.

**Comment by mingwandroid** [comment]
I'm not sure if `conda` and all the software it comes with works right in every situation when the root installation is read-only. Also, if you have a system R installed that could interact badly with Anaconda's R (though I have not experienced this and will attempt to fix any problems I find).

Given that you just want to build a package here, you can do that in an entirely separate environment and you should then be able to install that built package (it's just a `.tar.bz2` file) into other environments. Can you open a new shell and enter the following:

```
unset LD_LIBRARY_PATH
export PATH=/usr/bin
pushd /tmp
curl -SLO https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ./Miniconda3-latest-Linux-x86_64.sh -b -p /tmp/mc3
source /tmp/mc3/bin/activate
conda update -y conda
conda install -y conda-build
conda skeleton cran party
conda build r-party
```

If this doesn't work paste the output, and also add --debug to the last line and paste that output.

If it does work, you should be able to install it either:
1. Immediately in this temporary installation in your current shell or
2. Into your real `conda` installation by activating (source /path/to/other/anaconda3/bin/activate) it in a *new* shell (do not attempt to do this in the same shell!) 
.. and typing:

```
conda install -y r-essentials r-mvtnorm
conda install -y /tmp/mc3/conda-bld/linux-64/r-party-1.2_2-r3.3.2_0.tar.bz2
```

.. here, unfortunately, installing from explicitly named tarballs does not install any of the needed dependencies, so we install `r-essentials` and `r-mtvnorm` which *should* cover them all. An alternative is to upload the package to anaconda.org then install it via:

```
conda install -c <anaconda_channel_name> r-rparty
```

Finally, to test:

```
R
library(party)
```

**Comment by deliarusu** [comment]
Thanks a lot for the tips.
I've done the first bit, starting from scratch using miniconda and I get the same error. These are the actual paths this time. 
[conda-build-miniconda.txt](https://github.com/ContinuumIO/anaconda-issues/files/884157/conda-build-miniconda.txt)

You're right that there are two R installs, one of which is the Anaconda R:

`/usr/bin/R`
`/u01/app/anaconda3/bin/R`

and they seem to share the library path `/u01/app/R` (if I do a `.libPaths()` in R, the first library path for both R install sould be the `/u01/app/R`)

**Comment by deliarusu** [comment]
After removing this line from .Rprofile:

`.libPaths(new=c("/u01/app/R", .libPaths()))`

I could build and install the R package from CRAN.
