### ISSUE TITLE
anaconda navigator and spyder issues after matplotlib update

### ISSUE THREAD

**Issue by lvikt** [ContinuumIO/anaconda-issues#1563]
After updating to matplotlib 2.0.0 from Anaconda Navigator I cannot open Anaconda Navigator again and when trying to open spyder I get this message:
Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.

**Comment by goanpeca** [comment]
@lvikt could you open a terminal and provide the output of

`conda info`

and

`conda list` ?

**Comment by lvikt** [comment]
C:\Users\a002087>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : C:\Continuum\Anaconda2  (writable)
    default environment : C:\Continuum\Anaconda2
       envs directories : C:\Continuum\Anaconda2\envs
                          C:\Users\a002087\AppData\Local\conda\conda\envs
                          C:\Users\a002087\.conda\envs
          package cache : C:\Continuum\Anaconda2\pkgs
                          C:\Users\a002087\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.12 Windows/7
Windows/6.1.7601


C:\Users\a002087>conda list
# packages in environment at C:\Continuum\Anaconda2:
#
_license                  1.1                      py27_1
_nb_ext_conf              0.3.0                    py27_0
alabaster                 0.7.9                    py27_0
anaconda                  4.2.0               np111py27_0
anaconda-clean            1.0.0                    py27_0
anaconda-client           1.6.2                    py27_0
anaconda-navigator        1.5.0                    py27_0
anaconda-project          0.4.1                    py27_0
argcomplete               1.0.0                    py27_1
astroid                   1.4.7                    py27_0
astropy                   1.2.1               np111py27_0
babel                     2.3.4                    py27_0
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
basemap                   1.0.7               np111py27_0
beautifulsoup4            4.5.1                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.10.1                   py27_0
bokeh                     0.12.2                   py27_0
boto                      2.42.0                   py27_0
bottleneck                1.1.0               np111py27_0
bzip2                     1.0.6                     vc9_3  [vc9]
cdecimal                  2.3                      py27_2
cffi                      1.7.0                    py27_0
chardet                   2.3.0                    py27_0
chest                     0.2.3                    py27_0
click                     6.6                      py27_0
cloudpickle               0.2.1                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.7                    py27_0
comtypes                  1.1.2                    py27_0
conda                     4.3.14                   py27_1
conda-build               2.0.2                    py27_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py27_0
configparser              3.5.0                    py27_0
console_shortcut          0.1.1                    py27_1
contextlib2               0.5.3                    py27_0
cryptography              1.5                      py27_0
curl                      7.49.0                    vc9_0  [vc9]
cycler                    0.10.0                   py27_0
cython                    0.24.1                   py27_0
cytoolz                   0.8.0                    py27_0
dask                      0.11.0                   py27_0
datashape                 0.5.2                    py27_0
decorator                 4.0.10                   py27_0
dill                      0.2.5                    py27_0
docutils                  0.12                     py27_2
entrypoints               0.2.2                    py27_0
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_1
filelock                  2.0.6                    py27_0
flask                     0.11.1                   py27_0
flask-cors                2.1.2                    py27_0
freetype                  2.5.5                     vc9_1  [vc9]
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
get_terminal_size         1.0.0                    py27_0
gevent                    1.1.2                    py27_0
greenlet                  0.4.10                   py27_0
grin                      1.2.1                    py27_3
h5py                      2.6.0               np111py27_2
hdf5                      1.8.15.1                  vc9_4  [vc9]
heapdict                  1.0.0                    py27_1
icu                       57.1                      vc9_0  [vc9]
idna                      2.1                      py27_0
imagesize                 0.7.1                    py27_0
ipaddress                 1.0.16                   py27_0
ipykernel                 4.5.0                    py27_0
ipython                   5.1.0                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                5.2.2                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.2                      py27_1
jedi                      0.9.0                    py27_1
jinja2                    2.8                      py27_1
jpeg                      8d                        vc9_2  [vc9]
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.4.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.2.0                    py27_0
lazy-object-proxy         1.2.1                    py27_0
libpng                    1.6.27                    vc9_0  [vc9]
libtiff                   4.0.6                     vc9_2  [vc9]
llvmlite                  0.13.0                   py27_0
locket                    0.2.0                    py27_1
lxml                      3.6.4                    py27_0
markupsafe                0.23                     py27_2
matplotlib                2.0.0               np111py27_0
menuinst                  1.4.1                    py27_0
mistune                   0.7.3                    py27_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py27_2
mpmath                    0.19                     py27_1
multipledispatch          0.4.8                    py27_0
nb_anacondacloud          1.2.0                    py27_0
nb_conda                  2.0.0                    py27_0
nb_conda_kernels          2.0.0                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.1.0                    py27_0
nbpresent                 3.0.2                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2.1                    py27_0
nose                      1.3.7                    py27_1
notebook                  4.2.3                    py27_0
numba                     0.28.1              np111py27_0
numexpr                   2.6.1               np111py27_2
numpy                     1.11.3                   py27_0
odo                       0.5.0                    py27_1
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2j                    vc9_0  [vc9]
pandas                    0.19.2              np111py27_1
partd                     0.3.6                    py27_0
path.py                   8.2.1                    py27_0
pathlib2                  2.1.0                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
pickleshare               0.7.4                    py27_0
pillow                    3.3.1                    py27_0
pip                       8.1.2                    py27_0
pkginfo                   1.3.2                    py27_0
ply                       3.9                      py27_0
prompt_toolkit            1.0.3                    py27_0
psutil                    4.3.1                    py27_0
py                        1.4.31                   py27_0
pyasn1                    0.1.9                    py27_0
pycosat                   0.6.1                    py27_1
pycparser                 2.14                     py27_1
pycrypto                  2.6.1                    py27_4
pycurl                    7.43.0                   py27_0
pyflakes                  1.3.0                    py27_0
pygments                  2.1.3                    py27_0
pylint                    1.5.4                    py27_1
pyodbc                    3.0.10                   py27_1
pyopenssl                 16.2.0                   py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_2
pyshp                     1.2.10                   py27_0    ioos
pytables                  3.2.2               np111py27_4
pytest                    2.9.2                    py27_0
python                    2.7.12                        0
python-dateutil           2.5.3                    py27_0
pytz                      2016.6.1                 py27_0
pywin32                   220                      py27_1
pyyaml                    3.12                     py27_0
pyzmq                     15.4.0                   py27_0
qt                        5.6.0                     vc9_0  [vc9]
qtawesome                 0.3.3                    py27_0
qtconsole                 4.2.1                    py27_0
qtpy                      1.2.1                    py27_0
requests                  2.12.4                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_0
scikit-image              0.12.3              np111py27_1
scikit-learn              0.18.1              np111py27_1
scipy                     0.18.1              np111py27_1
seawater                  3.3.4                    py27_0    conda-forge
setuptools                27.2.0                   py27_1
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.3                    py27_0
sphinx                    1.4.6                    py27_0
spyder                    2.3.9                    py27_1
sqlalchemy                1.0.13                   py27_0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.6.1               np111py27_1
subprocess32              3.2.7                    py27_0
sympy                     1.0                      py27_0
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.0                    py27_0
tornado                   4.4.1                    py27_0
traitlets                 4.3.0                    py27_0
transaction               1.6.1                    py27_0
unicodecsv                0.14.1                   py27_0
vs2008_runtime            9.00.30729.1                  2
wcwidth                   0.1.7                    py27_0
werkzeug                  0.11.11                  py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        1.2.6                    py27_0
win_unicode_console       0.5                      py27_0
wrapt                     1.10.6                   py27_0
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.3                    py27_0
xlwings                   0.10.0                   py27_0
xlwt                      1.1.2                    py27_0
zlib                      1.2.8                     vc9_3  [vc9]
zope                      1.0                      py27_0
zope.interface            4.3.3                    py27_0
zope.sqlalchemy           0.7.7                    py27_0

C:\Users\a002087>

**Comment by goanpeca** [comment]
@lvikt if you open the anaconda prompt and type

`anaconda-navigator` could you paste the error trace?

**Comment by lvikt** [comment]
(C:\Continuum\Anaconda2) C:\Users\a002087>anaconda-navigator
Traceback (most recent call last):
  File "C:\Continuum\Anaconda2\Scripts\anaconda-navigator-script.py", line 5, in
 <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "C:\Continuum\Anaconda2\lib\site-packages\anaconda_navigator\app\main.py"
, line 47, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "C:\Continuum\Anaconda2\lib\site-packages\anaconda_navigator\utils\__init
__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Continuum\Anaconda2\lib\site-packages\qtpy\__init__.py", line 125, in
 <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

(C:\Continuum\Anaconda2) C:\Users\a002087>

**Comment by goanpeca** [comment]
@lvikt seems installing matplotlib somehow broke qt

Could you try reinstalling it from the anaconda prompt?

`conda install qt=5.6.2`

And launching again?

**Comment by lvikt** [comment]
Sorry, I did not change anything, still the same problems.
`(C:\Continuum\Anaconda2) C:\Users\a002087>conda install qt=5.6.2
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Continuum\Anaconda2:

The following NEW packages will be INSTALLED:

    olefile: 0.44-py27_0

The following packages will be UPDATED:

    jpeg:    8d-vc9_2     [vc9] --> 9b-vc9_0     [vc9]
    libtiff: 4.0.6-vc9_2  [vc9] --> 4.0.6-vc9_3  [vc9]
    pillow:  3.3.1-py27_0 --> 4.0.0-py27_1
    qt:      5.6.0-vc9_0  [vc9] --> 5.6.2-vc9_3  [vc9]

Proceed ([y]/n)? y

jpeg-9b-vc9_0. 100% |###############################| Time: 0:00:00   1.40 MB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:00   2.20 MB/s
olefile-0.44-p 100% |###############################| Time: 0:00:00   1.12 MB/s
qt-5.6.2-vc9_3 100% |###############################| Time: 0:00:05  10.31 MB/s
pillow-4.0.0-p 100% |###############################| Time: 0:00:00   2.93 MB/s

(C:\Continuum\Anaconda2) C:\Users\a002087>
`

**Comment by goanpeca** [comment]
Try these commands

`conda install qt --force`
`conda install pyqt --force`
`conda install qtpy --force`

**Comment by lvikt** [comment]
'
(C:\Continuum\Anaconda2) C:\Users\a002087>conda install qt --force
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Continuum\Anaconda2:

The following NEW packages will be INSTALLED:

    qt: 5.6.2-vc9_3 [vc9]

Proceed ([y]/n)? y


(C:\Continuum\Anaconda2) C:\Users\a002087>conda install pyqt --force
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Continuum\Anaconda2:

The following NEW packages will be INSTALLED:

    pyqt: 5.6.0-py27_2

Proceed ([y]/n)? y


(C:\Continuum\Anaconda2) C:\Users\a002087>conda install qtpy --force
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Continuum\Anaconda2:

The following NEW packages will be INSTALLED:

    qtpy: 1.2.1-py27_0

Proceed ([y]/n)? y


(C:\Continuum\Anaconda2) C:\Users\a002087>
´´´

**Comment by lvikt** [comment]
I still get the same message when trying to open Spyder and Anaconda Navigator does not open.

**Comment by goanpeca** [comment]
@mingwandroid thoughts?

**Comment by lvikt** [comment]
@goanpeca 
I can open Spyder and Anaconda Navigator again, after installing pyside with 
`conda install pyside`
as suggested in this Issue [[https://github.com/spyder-ide/spyder/issues/2699](https://github.com/spyder-ide/spyder/issues/2699)]

Sorry for not googling carefully enough before opening this issue. However, I still do not understand why this happend after the upgrade to matplotlib 2.0.0. (I did upgraded matplotlib after struggling with this [bug](https://github.com/matplotlib/matplotlib/pull/8297) matplotlib PdfPages).

**Comment by markgillis0** [comment]
@lvikt @goanpeca   I had the exact same issue as above after doing a Conda update --all.   After upgrading navigator to 1.5.1 +  `conda install pyside`, Navigator worked again.

**Comment by markgillis0** [comment]
I lied..   It started to work, loaded the initialization graphic, and then this.... 

> (C:\Users\userg\Anaconda2) C:\Users\userg>anaconda-navigator
> Traceback (most recent call last):
>   File "C:\Users\userg\Anaconda2\Scripts\anaconda-navigator-script.py", line 5, in <module>
>     sys.exit(anaconda_navigator.app.main.main())
>   File "C:\Users\userg\Anaconda2\lib\site-packages\anaconda_navigator\app\main.py", line 52, in main
>     start_app(options)
>   File "C:\Users\userg\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 87, in start_app
>     window = run_app(splash)
>   File "C:\Users\userg\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 42, in run_app
>     window = MainWindow(splash=splash)
>   File "C:\Users\userg\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 205, in __init__
>     self.home_tab = HomeTab(parent=self)
>   File "C:\Users\userg\Anaconda2\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 173, in __init__
>     self.set_environments()  # Set the envs combobox and hook signal
>   File "C:\Users\userg\Anaconda2\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 219, in set_environments
>     self.combo_environments.currentIndexChanged.disconnect()
> RuntimeError: Failed to disconnect signal currentIndexChanged(int).

And my package list:

> # packages in environment at C:\Users\userg\Anaconda2:
> #
> _license                  1.1                      py27_1
> alabaster                 0.7.10                   py27_0
> alembic                   0.7.7                    py27_0    Quantopian
> anaconda                  custom                   py27_0
> anaconda-client           1.6.2                    py27_0
> anaconda-navigator        1.5.1                    py27_0
> anaconda-project          0.4.1                    py27_0
> argcomplete               1.0.0                    py27_1
> astroid                   1.4.9                    py27_0
> astropy                   1.3.2               np111py27_0
> babel                     2.4.0                    py27_0
> backports                 1.0                      py27_0
> backports_abc             0.5                      py27_0
> bcolz                     1.0.0                    py27_0
> beautifulsoup4            4.5.3                    py27_0
> bitarray                  0.8.1                    py27_1
> blaze                     0.10.1                   py27_0
> bleach                    1.5.0                    py27_0
> blpapi                    3.9.0                     <pip>
> bokeh                     0.12.4                   py27_0
> boto                      2.46.1                   py27_0
> bottleneck                1.2.0               np111py27_0
> bzip2                     1.0.6                     vc9_3  [vc9]
> cachetools                1.1.6                    py27_0    Quantopian
> cdecimal                  2.3                      py27_2
> cffi                      1.9.1                    py27_0
> chardet                   2.3.0                    py27_0
> chest                     0.2.3                    py27_0
> click                     6.7                      py27_0
> cloudpickle               0.2.2                    py27_0
> clyent                    1.2.2                    py27_0
> colorama                  0.3.7                    py27_0
> comtypes                  1.1.2                    py27_0
> conda                     4.3.16                   py27_0
> conda-build               2.1.9                    py27_0
> conda-env                 2.6.0                         0
> conda-manager             0.4.0                    py27_0
> conda-verify              2.0.0                    py27_0
> configobj                 5.0.6                    py27_0
> configparser              3.5.0                    py27_0
> console_shortcut          0.1.1                    py27_1
> contextlib2               0.5.4                    py27_0
> cryptography              1.7.1                    py27_0
> curl                      7.52.1                    vc9_0  [vc9]
> cycler                    0.10.0                   py27_0
> cyordereddict             0.2.2                    py27_0    Quantopian
> cython                    0.25.2                   py27_0
> cytoolz                   0.8.2                    py27_0
> dask                      0.11.0                   py27_0
> datashape                 0.5.4                    py27_0
> decorator                 4.0.11                   py27_0
> dill                      0.2.5                    py27_0
> docutils                  0.13.1                   py27_0
> empyrical                 0.2.2                    py27_0    Quantopian
> entrypoints               0.2.2                    py27_1
> enum34                    1.1.6                    py27_0
> et_xmlfile                1.0.1                    py27_0
> fastcache                 1.0.2                    py27_1
> feedparser                5.2.1                    py27_0
> filelock                  2.0.7                    py27_0
> flask                     0.12.1                   py27_0
> flask-cors                3.0.2                    py27_0
> freetype                  2.5.5                     vc9_2  [vc9]
> funcsigs                  1.0.2                    py27_0
> functools32               3.2.3.2                  py27_0
> futures                   3.0.5                    py27_0
> get_terminal_size         1.0.0                    py27_0
> gevent                    1.2.1                    py27_0
> greenlet                  0.4.12                   py27_0
> grin                      1.2.1                    py27_3
> h5py                      2.7.0               np111py27_0
> hdf5                      1.8.15.1                  vc9_4  [vc9]
> heapdict                  1.0.0                    py27_1
> html5lib                  0.999                    py27_0
> icu                       57.1                      vc9_0  [vc9]
> idna                      2.2                      py27_0
> imagesize                 0.7.1                    py27_0
> intervaltree              2.1.0                    py27_0    Quantopian
> ipaddress                 1.0.18                   py27_0
> ipykernel                 4.6.0                    py27_0
> ipython                   5.3.0                    py27_0
> ipython_genutils          0.2.0                    py27_0
> ipywidgets                6.0.0                    py27_0
> isort                     4.2.5                    py27_0
> itsdangerous              0.24                     py27_0
> jdcal                     1.3                      py27_0
> jedi                      0.9.0                    py27_1
> jinja2                    2.9.5                    py27_0
> jpeg                      9b                        vc9_0  [vc9]
> jsonschema                2.5.1                    py27_0
> jupyter                   1.0.0                    py27_3
> jupyter_client            5.0.0                    py27_0
> jupyter_console           5.1.0                    py27_0
> jupyter_core              4.3.0                    py27_0
> lazy-object-proxy         1.2.2                    py27_0
> libpng                    1.6.27                    vc9_0  [vc9]
> libsodium                 1.0.3                         0
> libtiff                   4.0.6                     vc9_3  [vc9]
> llvmlite                  0.11.0                   py27_0
> locket                    0.2.0                    py27_1
> logbook                   0.12.5                   py27_0    Quantopian
> lxml                      3.7.3                    py27_0
> mako                      1.0.6                    py27_0
> markupsafe                0.23                     py27_2
> matplotlib                2.0.0               np111py27_0
> menuinst                  1.4.4                    py27_0
> mistune                   0.7.4                    py27_0
> mkl                       11.3.3                        1
> mkl-service               1.1.2                    py27_3
> mpmath                    0.19                     py27_1
> multipledispatch          0.4.9                    py27_0
> nbconvert                 5.1.1                    py27_0
> nbformat                  4.3.0                    py27_0
> networkx                  1.11                     py27_0
> nltk                      3.2.2                    py27_0
> nose                      1.3.7                    py27_1
> notebook                  5.0.0                    py27_0
> numba                     0.26.0              np111py27_0
> numexpr                   2.6.1               np111py27_1
> numpy                     1.11.2                   py27_0
> numpy                     1.12.1                    <pip>
> numpydoc                  0.6.0                    py27_0
> oauthlib                  1.1.2                     <pip>
> odo                       0.5.0                    py27_1
> olefile                   0.44                     py27_0
> openpyxl                  2.4.1                    py27_0
> openssl                   1.0.2k                    vc9_0  [vc9]
> pandas                    0.19.2              np111py27_1
> pandas-datareader         0.2.1                    py27_0
> pandocfilters             1.4.1                    py27_0
> partd                     0.3.7                    py27_0
> patch                     2.5.9                         1
> path.py                   10.1                     py27_0
> pathlib2                  2.2.0                    py27_0
> patsy                     0.4.1                    py27_0
> pep8                      1.7.0                    py27_0
> pickleshare               0.7.4                    py27_0
> pillow                    4.0.0                    py27_1
> pip                       9.0.1                    py27_1
> pkginfo                   1.4.1                    py27_0
> plotly                    1.12.9                   py27_0
> ply                       3.10                     py27_0
> prompt_toolkit            1.0.14                   py27_0
> psutil                    5.2.1                    py27_0
> py                        1.4.31                   py27_0
> pyasn1                    0.2.3                    py27_0
> pycosat                   0.6.2                    py27_0
> pycparser                 2.17                     py27_0
> pycrypto                  2.6.1                    py27_5
> pyflakes                  1.5.0                    py27_0
> pygments                  2.2.0                    py27_0
> pylint                    1.6.4                    py27_1
> pyopenssl                 16.2.0                   py27_0
> pyparsing                 2.1.4                    py27_0
> pyqt                      5.6.0                    py27_2
> pyreadline                2.1                      py27_0
> pyside                    1.2.1                    py27_0
> pytables                  3.2.2               np111py27_4
> pytest                    3.0.7                    py27_0
> python                    2.7.13                        0
> python-dateutil           2.6.0                     <pip>
> python-dateutil           2.6.0                    py27_0
> pytz                      2017.2                   py27_0
> pytz                      2017.2                    <pip>
> pywin32                   220                      py27_2
> pyyaml                    3.12                     py27_0
> pyzmq                     16.0.2                   py27_0
> qt                        5.6.2                     vc9_3  [vc9]
> qtawesome                 0.4.4                    py27_0
> qtconsole                 4.3.0                    py27_0
> qtpy                      1.2.1                    py27_0
> requests                  2.12.4                   py27_0
> requests-file             1.4.1                    py27_0
> requests-oauthlib         0.6.1                     <pip>
> rope                      0.9.4                    py27_1
> ruamel_yaml               0.11.14                  py27_1
> scandir                   1.5                      py27_0
> scikit-learn              0.18.1              np111py27_0
> scipy                     0.18.1              np111py27_0
> seaborn                   0.7.1                    py27_0
> setuptools                27.2.0                   py27_1
> simplegeneric             0.8.1                    py27_1
> singledispatch            3.4.0.3                  py27_0
> sip                       4.18                     py27_0
> six                       1.10.0                   py27_0
> snowballstemmer           1.2.1                    py27_0
> sockjs-tornado            1.0.3                    py27_0
> sortedcontainers          1.5.7                    py27_0
> sphinx                    1.5.4                    py27_0
> sphinx_rtd_theme          0.2.4                    py27_0
> spyder                    3.1.3                    py27_0
> sqlalchemy                1.1.8                    py27_0
> ssl_match_hostname        3.4.0.2                  py27_1
> statsmodels               0.8.0               np111py27_0
> subprocess32              3.2.7                    py27_0
> sympy                     1.0                      py27_0
> systemtools               1.0.2                     <pip>
> TA-Lib                    0.4.10                    <pip>
> testpath                  0.3                      py27_0
> tk                        8.5.18                    vc9_0  [vc9]
> toolz                     0.8.2                    py27_0
> tornado                   4.4.2                    py27_0
> traitlets                 4.3.2                    py27_0
> transaction               1.6.1                    py27_0
> tweepy                    3.5.0                     <pip>
> unicodecsv                0.14.1                   py27_0
> vs2008_runtime            9.00.30729.5054               0
> vs2010_runtime            10.00.40219.1                 2
> wcwidth                   0.1.7                    py27_0
> werkzeug                  0.12.1                   py27_0
> wheel                     0.29.0                   py27_0
> widgetsnbextension        2.0.0                    py27_0
> win_unicode_console       0.5                      py27_0
> wrapt                     1.10.8                   py27_0
> xlrd                      1.0.0                    py27_0
> xlsxwriter                0.9.6                    py27_0
> xlwings                   0.10.4                   py27_0
> xlwt                      1.2.0                    py27_0
> zlib                      1.2.8                     vc9_3  [vc9]
> zope                      1.0                      py27_0
> zope.interface            4.3.3                    py27_0
> zope.sqlalchemy           0.7.7                    py27_0

**Comment by goanpeca** [comment]
@ccordoba12 do you have any thoughts?

**Comment by ccordoba12** [comment]
We're getting reports about this in Spyder too. But I have no idea why it is happening...

**Comment by lvikt** [comment]
I still have the same problem, just like @markgillis0, Navigator starts, shows the graphic but then does not open.

**Comment by mingwandroid** [comment]
@ccordoba12, @goanpeca, why is `pyside` needed here?

**Comment by ccordoba12** [comment]
@lvikt installed `pyside` following Spyder advice (because Spyder couldn't find PyQt4 nor 5). That advice is old and we should have removed it a long time ago, sorry for that.
