### ISSUE TITLE
GDAL_DATA env var set incorrectly

### ISSUE THREAD

**Issue by dcsoft4** [ContinuumIO/anaconda-issues#1564]
# Installation

1. Start with new Anaconda2 4.3.1
2. conda install gdal <-- installs GDAL 2.1.0

# Symptom

"Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files."

# Fix

I had to remove the double-quotes around the value of the GDAL_PATH environment variable. Originally the batch file set

`set` GDAL_DATA="%~dp0\..\..\..\Library\share\gdal"`

It worked after I changed it to

`set GDAL_DATA=%~dp0\..\..\..\Library\share\gdal`

# Reference

It seems [conda-forge](https://github.com/conda-forge/gdal-feedstock/issues/54) has a fix and they recommended I post an issue here.

**Comment by gillins** [comment]
Changing it to:
```
set "GDAL_DATA=%~dp0\..\..\..\Library\share\gdal"
```
Means it will work with spaces in the path...
