### ISSUE TITLE
Navigator lists python as upgradable to 2.7.13 while it's already installed

### ISSUE THREAD

**Issue by Khris777** [ContinuumIO/anaconda-issues#1565]
I'm using Anaconda with Python 2 on Windows 10. When I go into the Environments -> root list of the Navigator I see python itself listed as upgradable to 2.7.13 although this version is already installed as can be confirmed by a quick `conda update python`.

I did update Navigator to 1.5.1 and hit Update Index multiple times, it still claims that python 2 can be upgraded.

Output of `conda info`  if that helps in any way:

               platform : win-64
          conda version : 4.3.15
       conda is private : False
      conda-env version : 4.3.15
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\My.Name\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\My.Name\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\My.Name\AppData\Local\Continuum\Anaconda2\envs
                          C:\Users\My.Name\AppData\Local\conda\conda\envs
                          C:\Users\My.Name\.conda\envs
          package cache : C:\Users\My.Name\AppData\Local\Continuum\Anaconda2\pkgs
                          C:\Users\My.Name\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
            config file : C:\Users\My.Name\.condarc
           offline mode : False
             user-agent : conda/4.3.15 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

My `.condarc`, I'm using company proxy servers:

	ssl_verify: true
	channels:
	  - defaults
	  - conda-forge
	  - anaconda-fusion
	proxy_servers:
	  http: http://...
      https: https://...

**Comment by goanpeca** [comment]
@Khris777 thanks for the report, will look into what might be the issue

**Comment by Khris777** [comment]
It looks like Navigator simply lists Python 2.7.13 as upgradeable because Python 3 has a higher version number though the environment is a specific Python 2 environment. A similar issue is with ipython 6 which is not compatible with Python 2 anymore but is still listed as upgradeable in the Python 2 environment.

**Comment by goanpeca** [comment]
>It looks like Navigator simply lists Python 2.7.13 as upgradeable because Python 3 has a higher version number though the environment is a specific Python 2 environment. A similar issue is with ipython 6 which is not compatible with Python 2 anymore but is still listed as upgradeable in the Python 2 environment.

Yes, probably, although higher versions of python should have been filtered out if there is a package pinning (which is the case for python).
