### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by meloamaury** [ContinuumIO/anaconda-issues#1567]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy ==1.12.1
  - vispy -> numpy 1.10*|1.9*
  - vispy -> pyqt 4.*
  - vispy -> python 2.6*|3.3*|3.4*|3.5*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.12', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.4.0;Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@meloamaury you are using an old version of Navigator, I strongly advice you update to the latest 1.5.1 version by typing on the terminal

`conda install anaconda-navigator=1.5.1`

To learn more about the error you see please look a this [document](https://conda.io/docs/troubleshooting.html#unsatisfiable)
