### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tdk3** [ContinuumIO/anaconda-issues#1569]
Anaconda Navigator Update error:

//anaconda/bin/python //anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.5.1: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.5.1*
  - spyder-app -> spyder 2.3.5.2 -> pyqt 4.* -> qt 4.8.6
  - spyder-app -> spyder 2.3.5.2 -> pyqt 4.* -> sip 4.16.5
Use "conda info <package>" to see the dependencies for each package.

{'language': 'en', 'os': 'Darwin;16.4.0;Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64;x86_64;i386', 'pyqt': '4.11.4', 'version': '1.2.1', 'qt': '4.8.7', 'platform': 'osx-64', 'python': '3.5.1', 'conda': '4.3.15'}

**Comment by goanpeca** [comment]
@tdk3 the new version of navigator is qt=5 only compatible (since qt=4 is deprecated now)

You need to install qt5.

`conda install qt=5`
`conda install anaconda-navigator`
