### ISSUE TITLE
doc: cronjob description wrong?

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/anaconda-issues#1574]
https://docs.continuum.io/anaconda-repository/admin/install#set-up-automatic-restart-on-reboot-fail-or-error

```
Run the anaconda-server-install-supervisord-config.sh script to configure supervisord management of the Anaconda server and worker processes:

anaconda-server-install-supervisord-config.sh
Then create the following entry in the anaconda-server users crontab:

@reboot /home/anaconda-server/repo/bin/supervisord
```

Doesn't the script automatically create the cron job?  The user shouldn't have to do this.  However, if the user is disallowed from using cron, it will show an error message to that effect.  

What you can do to fix that is have a sudo user edit the cronjob and add it for that user.  Generally, that error means the user can't **add** cronjobs, but you can manually add the cronjob as root with:  `sudo crontab -e -u anaconda-server`

**Comment by electronwill** [comment]
OK, we can make that correction.

@bkreider , am I understanding correctly that if the user runs ``sudo crontab -e -u anaconda-server`` then it will add that line without the user having to copy and paste it or type it in?

@dsludwig , could you please confirm that ``anaconda-server-install-supervisord-config.sh`` will try to add the line to crontab automatically?

**Comment by bkreider** [comment]
> if the user runs sudo crontab -e -u anaconda-server then it will add that line without the user having to copy and paste it or type it in?

No.  Well, they might not even have sudo.  That might be the time to switch back to root and run it.  That just lets the root user edit the user's crontab.  They'd have to paste in the command.

>  could you please confirm that anaconda-server-install-supervisord-config.sh will try to add the line to crontab automatically?

Historically, it has always done this.  I during an edit someone was confused and thought it had to be manually added.  It used to say:  "Running the script does 2 things:  blah blah blah, and adds the following line to crontab".  

See the old runbook here: http://runbooks.readthedocs.io/en/latest/AnacondaRepository.html#set-up-automatic-restart-on-reboot-fail-or-error

**Comment by electronwill** [comment]
OK, that all makes sense. @dsludwig please disregard the earlier question.

**Comment by electronwill** [comment]
Fixed:
https://github.com/Anaconda-Platform/anaconda-server/pull/3678
https://github.com/Anaconda-Platform/anaconda-server/pull/3679
https://github.com/Anaconda-Platform/anaconda-server/pull/3680
https://github.com/Anaconda-Platform/anaconda-server/pull/3681

Also fixes https://github.com/Anaconda-Platform/anaconda-server/issues/3514 .
