### ISSUE TITLE
BEAST2 install problem

### ISSUE THREAD

**Issue by delfinut** [ContinuumIO/anaconda-issues#1575]
I tried to install BEAST 2 using: conda install -c bioconda beast2=2.4.5

And got the following error message that just ends abruptly with the single quote mark: 
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Package not found: Conda could not find '

Any idea what may be wrong/how to fix this? 

Thanks,
Divya

**Comment by nehaljwani** [comment]
The blank `Conda could not find '` error was fixed in `conda >= 4.3.16`.  The exact error message is:

```bash
(scratch) [nwani@centos6x64 ~]$ conda install -c bioconda beast2=2.4.5
Fetching package metadata ...........
Solving package specifications:

PackageNotFoundError: Dependencies missing in current linux-64 channels:
  - beast2 2.4.5* -> openjdk 8.0* zulu8*
  - beast2 2.4.5* -> xorg-libxtst
```

Closing as this is not related to the defaults channel. Please raise this issue at https://github.com/bioconda/bioconda-recipes
