### ISSUE TITLE
Navigator upgrade from 1.3.2 to 1.5.1 results in error "win32 hard link failed"

### ISSUE THREAD

**Issue by TaviaRaventail** [ContinuumIO/anaconda-issues#1582]
Upgrading Navigator 1.3.2 to 1.5.1 from within Navigator on Windows 8.1 64-bit results in the error:

`D:\Tools\Anaconda2\python.exe D:\Tools\Anaconda2\Scripts\conda-script.py install --yes --json --force-pscheck --name root anaconda-navigator=1.5.1: OS error: failed to link (src=u'D:\\Tools\\Anaconda2\\pkgs\\anaconda-navigator-1.5.1-py27_0\\Lib/site-packages/anaconda_navigator/static/images/spinner-green-16x16.gif', dst='D:\\Tools\\Anaconda2\\Lib/site-packages/anaconda_navigator/static/images/spinner-green-16x16.gif', type=1, error=CondaOSError: OS error: win32 hard link failed
)`

**Note the mix of slashes** - the first part of the path in `src `and `dst `uses double-backslashes (\\\\) like something is needing to escape the backslash, and the second part of the path uses forward slashes (/).

Navigator upgrade is aborted, partially completed.

**Comment by goanpeca** [comment]
@TaviaRaventail if you try to run the update from the command line or directly on navigator?

Do you get the same result if you open the Anaconda Prompt and type

`conda install anaconda-navigator=1.5.1`

**Comment by TaviaRaventail** [comment]
At this point, starting the Anaconda Prompt gives:
`'D:\Tools\Anaconda2\Scripts\activate.bat' is not recognized as an internal or external command, operable program or batch file.`
I checked that directory, and that batch file is not there.
I also checked for the script mentioned in the error (`D:\Tools\Anaconda2\Scripts\conda-script.py`) and that file is also not present in the Scripts directory.

Running `conda` from the command line gives the same error: `'conda' is not recognized as an internal or external command, operable program or batch file.`
I checked my PATH environment variable and the following *are* present:
`D:\Tools\Anaconda2;D:\Tools\Anaconda2\Scripts;D:\Tools\Anaconda2\Library\bin;`

I think I'm going to have to manually download and install Navigator because it looks like this installation is now broken.

**Comment by goanpeca** [comment]
@TaviaRaventail yep, it does look that way indeed :-|

**Comment by TaviaRaventail** [comment]
Update: manually downloaded anaconda and installed everything to a new directory - successful.  Anaconda Navigator runs successfully.  
One new issue appeared: Navigator kept prompting to upgrade from 1.5 to 1.5.1.  I clicked yes, did the restart and the upgrade never 'took'.  Had to do the upgrade from the command-line to get it to work.

**Comment by Bruno-Hanzen** [comment]
Similar phenomenon happened to me. I finally updated manually (conda command), and I was upgraded to 1.5.1.
Then, today, I got a message to update to 1.5.2. Then got the "hard link failed" message, and par of my anaconda install disappeared. I guess that I'll have to reinstall anaconda from scratch. Seems that the Navigator update process could be more robust.
