### ISSUE TITLE
Updating Anaconda Navigator

### ISSUE THREAD

**Issue by ret2727** [ContinuumIO/anaconda-issues#1583]
Opened AN and message said "Do you want to update to AN 1.5.1" Answered "Yes" and it downloaded data then message "Update successful" So shut down and restarted BUT it had not updated. tried several times but it wouldn't do So tried to update from Anaconda prompt YES successful

**Comment by goanpeca** [comment]
@ret2727, yes we are working on a new update procedure for Navigator for it to be more reliable.

We are working on this for 1.6 release

**Comment by rct** [comment]
Fresh, first time install, same problem.    Do you need any info / logs for this?

How to upgrade by command line manually wasn't obvious at first, I wound up using

`conda update --prefix C:\sw\Andaconda3 anaconda-navigator`

Possibly related:
The docs look like Anaconda4 is latest, but the Python 3.6 package installed anaconda3.   If I try to update Anaconda, it wants to downgrade navigator BACK to 1.5.0.

```
C:\Users\rct>conda update --prefix C:\sw\Anaconda3 anaconda
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\sw\Anaconda3:

The following packages will be UPDATED:

    anaconda:           custom-py36_0 --> 4.3.1-np111py36_0

The following packages will be DOWNGRADED due to dependency conflicts:

    anaconda-navigator: 1.5.1-py36_0  --> 1.5.0-py36_0

Proceed ([y]/n)?
```

**Comment by francas** [comment]
Same issue here, can't update to 1.5.1

**Comment by Wason1** [comment]
I have exactly the same issue. Update anaconda navigator to 1.5.1 and then it asks me to update to 1.5.1 when I open it again.

**Comment by Wason1** [comment]
put this in cmd (admin)
conda install -c continuumcrew anaconda-navigator=1.5.1
finally updated

**Comment by goanpeca** [comment]
@Wason1 there is a new version of Navigator

`conda install anaconda-navigator=1.5.2`

**Comment by polaroidkidd** [comment]
same issue when trying to update to 1.5.2

**Comment by stolsvik** [comment]
With @goanpeca's solution (or just 'conda update anaconda-navigator'), I get the following:
`The following packages will be UPDATED:

    anaconda:           4.3.1-np111py36_0 --> custom-py36_0
    anaconda-navigator: 1.5.0-py36_0      --> 1.5.2-py36_0`

What's that "custom-py36_0" thing? Seems like something I do not want?

**Comment by goanpeca** [comment]
@stolsvik its actually fine.

`anaconda-custom-py36` is an "empty made up" package that allow to track if your installation diverted from a default anaconda installation. What it basically means in this case is that Anaconda Navigator 1.5.2 is not a package of anaconda-4.3.1, hence it will install the `custom` version package (which is just an empty dummy package for tracking the current anaconda install version, as I said before)

**Comment by sqlshep** [comment]
When i launch navigator, i just get the ring updating meta data, I have followed all of the instructions in this thread, 

The following packages will be UPDATED:

    anaconda:           4.3.1-np111py36_0 --> custom-py36_0
    anaconda-navigator: 1.5.0-py36_0      --> 1.5.2-py36_0 

And the "conda update --all".  Everything appears to have been successful but no luck launching navigator.

**Comment by noisedb** [comment]
issue still happen between 1.5.0 to 1.5.2..
work for me by running `conda install anaconda-navigator=1.5.2`

**Comment by silverjad3** [comment]
"yes we are working on a new update procedure for Navigator for it to be more reliable.
We are working on this for 1.6 release"

1.6+ is now out and still happening.

**Comment by sqlshep** [comment]
I am new to Python, but, For what its worth, i let the spinning ring go for probably 45 minutes and it did update and eventually launch.  It now launches successfully every time, but the only apps in Navigator are RStudio, and anaconda fusion.  I was after Spyder which i have been launching from terminal...

**Comment by simonegabbriellini** [comment]
I was on 1.6.1 and everything was fine, then update to 1.6.2 and two things happened: 
- when trying to update to 1.6.3 it quits but then do nothign
- I am unable to launch Jupyter anymore since 1.6.2: 0:97: execution error: "http://localhost:8890/tree?token=c9d8af4749529c9865e874c8b7a602a19dd5a1accbbd18af" does not understand “open location”. (-1708)

**Comment by eliot1785** [comment]
Same thing happening to me for 1.6.3 update...

**Comment by saurius** [comment]
same thing for me I'm on 1.5.3 and won't upgrade. I just close the program.

**Comment by tgb417** [comment]
+1 for me 1.5.3 navigator closes.  No launch of updater to 1.6.4 on Mac OS 10.11.6.
I'm wondering if this is related to the Mac OS security that will prevent internet programs from launching.  I'm going to turn this feature off for a moment in system preferences and see if I can get the upgrade to work of me that way.  More on this later.

**Comment by tgb417** [comment]
So no luck  I've tried the Mac OS Security "Allow apps downloaded from: Anywhere option."  Still no joy.  The Anaconda Navigator closes.  The Upgrade does not start.  Actively looking for solutions.

**Comment by tgb417** [comment]
Trying:

In terminal of root environment

`conda install anaconda-navigator=1.5.2`

Needed to re-start the navigator manually.

Then things seem to be OK.

**Comment by goanpeca** [comment]
@tgb417 the latest version is 1.6.4, you can get it with

`$ conda update anaconda-navigator`

**Comment by skypather** [comment]
@goanpeca Thanks for your help.  Your suggestion worked perfectly for me.

**Comment by sundayle** [comment]
### block Anacona Host

sudo vim /etc/hosts
127.0.0.1       api.alpha.binstar.org
127.0.0.1       api.anaconda.org

https://www.sundayle.com/2018/01/21/Anacona-Navigator-No-response/

**Comment by jason-akashic** [comment]
I'm stuck on 1.6.3.  Won't update to 1.7.  Have tried manual solution.  No luck

**Comment by goanpeca** [comment]
@jason-akashic could you open the Terminal or Anaconda Prompt and type

```
conda install conda=4.4.10
conda install anaconda-navigator=1.7.0
```

**Comment by jason-akashic** [comment]
Hey Gonzalo—

Sorry, I already dumped my old anaconda3 folder for a fresh install.  Moving the env folder over seems to make that a pretty painless “clean install” option, no?


Jason

**Comment by vshemet** [comment]
Issue persists with update to 1.8.3 from 1.7 at Windows 7
The install is user-based, with no admin rights. There is a firewall, but I used "conda config --set ssl_verify False" to work around. Now I can install packages, but can not update anything. During attempt, it shows "successful" yet I'm unable to launch navigator. Only reinstall

**Comment by Farhod7** [comment]
For Windows user need to run: 
c:\Anaconda3\Scripts\conda.exe 
conda update anaconda-navigator
updates successfully

**Comment by PepeChan** [comment]
Farhod7, thanks!

Your solution worked for me.
