### ISSUE TITLE
Anaconda.org version badge not being updated

### ISSUE THREAD

**Issue by rolando** [ContinuumIO/anaconda-issues#1584]
This is happening in this package: https://anaconda.org/conda-forge/spacy

Latest package version is 1.7.3, while badge shows 1.6.0.

<img width="275" alt="spacy____anaconda_cloud" src="https://cloud.githubusercontent.com/assets/26015/24716055/efd7aa82-1a03-11e7-9dc9-9e7f93e6919b.png">

<img width="295" alt="badges____anaconda_cloud" src="https://cloud.githubusercontent.com/assets/26015/24716073/ff94a420-1a03-11e7-9f05-03c9db36f94a.png">

**Comment by jakirkham** [comment]
Sounds like this is the same as issue ( https://github.com/Anaconda-Platform/support/issues/7 ). Maybe we should ask them to reopen that issue and close this one out. Thoughts?

**Comment by rolando** [comment]
Already being addressed in https://github.com/Anaconda-Platform/support/issues/7
