### ISSUE TITLE
Can't launch anaconda-navigator

### ISSUE THREAD

**Issue by jingw222** [ContinuumIO/anaconda-issues#1594]
The graphical interface stuck at the the green anaconda circle, showing 'Loading application', for ever. Here is the terminal output also:

`2017-04-10 14:57:27,238 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:27,244 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:27,245 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:27,245 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:27,245 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:28,425 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:28,426 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:28,426 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:28,426 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-10 14:57:28,427 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`Traceback (most recent call last):
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 442, in process_application_info
    self.post_setup(processed_apps)
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 457, in post_setup
    self.home_tab.setup_tab(apps, prefix=self.current_prefix)
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/home.py", line 253, in setup_tab
    self.set_applications(prefix=prefix)
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/home.py", line 271, in set_applications
    for app_name in sorted(list(self.apps.keys())):
AttributeError: 'NoneType' object has no attribute 'keys'
`

I have no idea what's exactly going on here and how to get out of the problem. Any suggestions?

**Comment by goanpeca** [comment]
@jingw222 could you provide more information? where you working offline?

What is the output of `conda info` and `conda list`?

**Comment by jingw222** [comment]
`Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : /home/jingw222/anaconda3  (writable)
    default environment : /home/jingw222/anaconda3
       envs directories : /home/jingw222/anaconda3/envs
                          /home/jingw222/.conda/envs
          package cache : /home/jingw222/anaconda3/pkgs
                          /home/jingw222/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/linux-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jingw222/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.6.1 Linux/4.8.0-46-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000
`
`
_license                  1.1                      py36_1  
alabaster                 0.7.10                   py36_0  
anaconda                  custom                   py36_0  
anaconda-client           1.6.2                    py36_0  
anaconda-navigator        1.5.1                    py36_0  
anaconda-project          0.4.1                    py36_0  
appdirs                   1.4.3                     <pip>
astroid                   1.4.9                    py36_0  
astropy                   1.3.1               np112py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
better-exceptions         0.1.6                     <pip>
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                    py36_0  
bleach                    2.0.0                     <pip>
bokeh                     0.12.4                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np112py36_0  
cairo                     1.14.8                        0  
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
conda                     4.3.16                   py36_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.1                   py36_0  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                     <pip>
entrypoints               0.2.2                    py36_0  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py36_1  
flask                     0.12                     py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        2  
freetype                  2.5.5                         2  
future                    0.16.0                   py36_1  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
glib                      2.50.2                        1  
graphviz                  0.6                       <pip>
graphviz                  2.38.0                        4  
greenlet                  0.4.12                   py36_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.7.0               np112py36_0  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.999                    py36_0  
html5lib                  0.999999999               <pip>
icu                       54.1                          0  
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.6.0                     <pip>
ipykernel                 4.5.2                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.9.0                    py36_1  
Jinja2                    2.9.6                     <pip>
jinja2                    2.9.5                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter-client            5.0.1                     <pip>
jupyter_client            5.0.0                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
jupyterlab                0.19.0                    <pip>
jupyterthemes             0.15.3                    <pip>
launcher                  1.0.0                         1  
lazy-object-proxy         1.2.2                    py36_0  
lesscpy                   0.12.0                    <pip>
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libtool                   2.4.2                         0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.16.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
MarkupSafe                1.0                       <pip>
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np112py36_0  
mistune                   0.7.4                     <pip>
mistune                   0.7.3                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py36_1  
notebook                  4.4.1                    py36_0  
notebook                  5.0.0                     <pip>
numba                     0.31.0              np112py36_0  
numexpr                   2.6.2               np112py36_0  
numpy                     1.12.1                    <pip>
numpy                     1.12.1                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        1  
packaging                 16.8                      <pip>
pandas                    0.19.2              np112py36_1  
pandas-datareader         0.2.1                    py36_0  
pandocfilters             1.4.1                    py36_0  
pango                     1.40.3                        1  
partd                     0.3.7                    py36_0  
path.py                   10.1                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.0.0                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
plotly                    1.12.9                   py36_0  
ply                       3.10                      <pip>
ply                       3.10                     py36_0  
prompt_toolkit            1.0.13                   py36_0  
protobuf                  3.2.0                     <pip>
psutil                    5.2.1                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.33                   py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.2                    py36_0  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.2.0                     <pip>
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytables                  3.3.0               np112py36_0  
pytest                    3.0.7                    py36_0  
python                    3.6.1                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2016.10                  py36_0  
pywavelets                0.5.2               np112py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         3  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.13.0                   py36_0  
requests-file             1.4.1                    py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.13.0              np112py36_0  
scikit-learn              0.18.1              np112py36_1  
scikit-plot               0.2.2                     <pip>
scipy                     0.19.0              np112py36_0  
seaborn                   0.7.1                    py36_0  
setuptools                34.3.3                    <pip>
setuptools                27.2.0                   py36_0  
shadowsocks               2.8.2                     <pip>
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                    <pip>
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sphinx                    1.5.1                    py36_0  
spyder                    3.1.3                    py36_0  
sqlalchemy                1.1.7                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np112py36_0  
sympy                     1.0                      py36_0  
tensorflow                1.0.1                     <pip>
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
tornado                   4.4.3                     <pip>
traitlets                 4.3.2                    py36_0  
unicodecsv                0.14.1                   py36_0  
urllib3                   1.20                      <pip>
utils                     0.9.0                     <pip>
wcwidth                   0.1.7                    py36_0  
webencodings              0.5                       <pip>
werkzeug                  0.12.1                   py36_0  
wheel                     0.29.0                   py36_0  
wheel                     0.29.0                    <pip>
widgetsnbextension        2.0.0                    py36_0  
wrapt                     1.10.8                   py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3 
`

**Comment by JBCoded** [comment]
Having the exact same issue, except it now won't open at all

**Comment by DawnMe** [comment]
I'm having similar problem, anaconda launch fails on ubuntu 14.04.
When trying to launch anaconda from the icon on the start menu, it shows the logo for a seconds an then disappear. 

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/shahar/anaconda3  (writable)
    default environment : /home/shahar/anaconda3
       envs directories : /home/shahar/anaconda3/envs
                          /home/shahar/.conda/envs
          package cache : /home/shahar/anaconda3/pkgs
                          /home/shahar/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-74-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000

--

# packages in environment at /home/shahar/anaconda3:
#
_license                  1.1                      py36_1  
alabaster                 0.7.9                    py36_0  
anaconda                  4.3.1               np111py36_0  
anaconda-client           1.6.0                    py36_0  
anaconda-navigator        1.5.2                    py36_0  
anaconda-project          0.4.1                    py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3                 np111py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bokeh                     0.12.4                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np111py36_0  
cairo                     1.14.8                        0  
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
conda                     4.3.16                   py36_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.13.0                   py36_0  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_0  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py36_1  
flask                     0.12                     py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        2  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
glib                      2.50.2                        1  
greenlet                  0.4.11                   py36_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py36_2  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
icu                       54.1                          0  
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.5.2                    py36_0  
ipython                   5.1.0                    py36_0  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                5.2.2                    py36_1  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.9.0                    py36_1  
jinja2                    2.9.4                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            4.4.0                    py36_0  
jupyter_console           5.0.0                    py36_0  
jupyter_core              4.2.1                    py36_0  
launcher                  1.0.0                         1  
lazy-object-proxy         1.2.2                    py36_0  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.2                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np111py36_0  
mistune                   0.7.3                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
nbconvert                 4.2.0                    py36_0  
nbformat                  4.2.0                    py36_0  
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py36_1  
notebook                  4.3.1                    py36_0  
numba                     0.30.1              np111py36_0  
numexpr                   2.6.1               np111py36_2  
numpy                     1.11.3                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np111py36_1  
partd                     0.3.7                    py36_0  
path.py                   10.0                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.0.0                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
ply                       3.9                      py36_0  
prompt_toolkit            1.0.9                    py36_0  
psutil                    5.0.1                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.32                   py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.1.3                    py36_0  
pylint                    1.6.4                    py36_1  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytables                  3.3.0               np111py36_0  
pytest                    3.0.5                    py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2016.10                  py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         3  
qtawesome                 0.4.3                    py36_0  
qtconsole                 4.2.1                    py36_1  
qtpy                      1.2.1                    py36_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.12.4                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.12.3              np111py36_1  
scikit-learn              0.18.1              np111py36_1  
scipy                     0.18.1              np111py36_1  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sphinx                    1.5.1                    py36_0  
spyder                    3.1.2                    py36_0  
sqlalchemy                1.1.5                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py36_1  
sympy                     1.0                      py36_0  
terminado                 0.6                      py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.1                    py36_0  
unicodecsv                0.14.1                   py36_0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.11.15                  py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        1.2.6                    py36_0  
wrapt                     1.10.8                   py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3  
shahar@shahar-ThinkPad-T460:~$

**Comment by goanpeca** [comment]
@DawnMe could you paste the output of running `anaconda-navigator` on the terminal?

**Comment by DawnMe** [comment]
@goanpeca running `anaconda-navigator` worked well, and the navigator launched after updating the libraries. Running it from the start menu (icon called "Anaconda Navigator - Beta") still doesn't work and stop after showing "initializing" for less than a second.

**Comment by jingw222** [comment]
Launching ``anaconda-navigator`` right from the launcher icon would never worked on my Ubuntu 16.04 laptop. It does work on Windows though.

**Comment by goanpeca** [comment]
>Launching Anaconda Navigator right from the launcher icon would never worked on my Ubuntu 16.04 laptop

We don't have an Ubuntu Launcher Icon :-\

**Comment by goanpeca** [comment]
@DawnMe lets try updating navigator with the force (`--force, -f`) flag and see if it works

`conda install anaconda-navigator=1.5.2 -f`

**Comment by DawnMe** [comment]
@goanpeca I've tried to force install, but it didn't do anything, probably because it seems I already have the latest version (see below from `conda list`).
I'll keep with the terminal launch on my Ubuntu 14.04 for now, it works fine.

anaconda                  4.3.1               np111py36_0  
anaconda-client           1.6.0                    py36_0  
anaconda-navigator        1.5.2                    py36_0  
anaconda-project          0.4.1                    py36_0

**Comment by gakuba** [comment]
I fixed this is on my computer by running `conda anaconda-navigator install `
