### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by henghenghengforever** [ContinuumIO/anaconda-issues#1596]
Application action error

D:\Program Files\codes\Anaconda\python.exe D:\Program Files\codes\Anaconda\Scripts\conda-script.py install --yes --json --force-pscheck --prefix D:\Program Files\codes\Anaconda orange3=3.4.1: CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Read timed out. (read timeout=6.1)",))',),)

{'conda': '4.2.13', 'pyqt': '4.11.4', 'qt': '4.8.7', 'python': '3.5.2', 'language': 'zh_CN', 'version': '1.2.2', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'platform': 'win-64'}

**Comment by goanpeca** [comment]
Hi @henghenghengforever you are using an old version of NAvigator, please update to the latests by running on the terminal

`conda install anaconda-navigator`
