### ISSUE TITLE
Cannot Launch Anaconda Navigator

### ISSUE THREAD

**Issue by eoindelahunty** [ContinuumIO/anaconda-issues#1597]
When I type below in the Command Prompt window to launch Anaconda Navigator, I get the below error message, has anyone else seen this before? 

C:\Users\eoind>anaconda-navigator
Load Error: in C:\Users\eoind\.condarc on line 5, column 0. Invalid YAML

**Comment by eoindelahunty** [comment]
Two updates, I uninstalled and reinstalled. Same issue. When I referred to Command Prompt, I meant the regular Windows Command Prompt not the Anaconda Prompt. When I tried it in Anaconda Prompt, I got the same result.

**Comment by eoindelahunty** [comment]
Right so I deleted the below from the .condaarc file and hey presto it worked! :)

channels:
  - anaconda-fusion
  - defaults
on
  - defaults

**Comment by eoindelahunty** [comment]
Closed

**Comment by Kamar2012** [comment]
i have similar problem , kindly assist me
