### ISSUE TITLE
Various Mac Graphical Installer Language issues

### ISSUE THREAD

**Issue by LawrencePersonCIO** [ContinuumIO/anaconda-issues#1600]
- "Copyright 2016, Continuum Analytics, Inc." should read "Copyright © 2017, Continuum Analytics, Inc."
- Bullet points should ideally use real bullets aligned left with text aligned rather than asterisk with normal paragraph align. 
- Remove extra space at the end of "http://docs.continuum.io/anaconda/pkg-docs ." line in first paragraph under Notice of Third Party Software Licenses.
- "you obtain" should be "obtained".
- Might change "are provided in Anaconda" to "are bundled with Anaconda".
- Replace all instances of two spaces after a period with one space in second paragraph under Notice of Third Party Software Licenses.
- "<http://www.wassenaar.org/>" should probably be "(http://www.wassenaar.org/)".
- I would change the two space indent for the redistributed cryptographic packages at the bottom to a line space after the title and no indent. 
- I notice the current Anaconda installer skips the Destination Select screen entirely, but jumps back if you select "Change Install Location". This seems an odd way for an installer to behave.

**Comment by csoja** [comment]
Issue moved to [ContinuumIO/anaconda #806](https://github.com/ContinuumIO/anaconda/issues/806) via [**ZenHub**](https://www.zenhub.com/)
