### ISSUE TITLE
ImportError: cannot import name __check_build

### ISSUE THREAD

**Issue by punkuj** [ContinuumIO/anaconda-issues#1604]
ImportError                               Traceback (most recent call last)
<ipython-input-1-0ecd553abc53> in <module>()
   1605 
   1606 
-> 1607 from sklearn.metrics import accuracy_score
   1608 import numpy as np
   1609 y_true = np.array(labels)

C:\Python27\Lib\site-packages\sklearn\__init__.py in <module>()
     35     # process, as it may not be compiled yet
     36 else:
---> 37     from . import __check_build
     38     from .base import clone
     39     __check_build  # avoid flakes unused variable error

ImportError: cannot import name __check_build

**Comment by nehaljwani** [comment]
Presence of `C:\Python27\Lib\site-packages\sklearn_init_.py` indicates that you are not using anaconda's `scikit-learn` .  Please make sure that you do not have either of `C:\Python27` in `PATH` environment variable and `C:\Python27\Lib\site-packages` in `PYTHONPATH` environment variable.
