### ISSUE TITLE
Anaconda Navigator won't open and Win10 says "Python has stopped working."

### ISSUE THREAD

**Issue by maanasadi** [ContinuumIO/anaconda-issues#1605]
when I click the anaconda navigator app as administrator from the start window in windows10, Anaconda symbol/icon appears for sometime but after that Win10 message "Python has stopped working"

when I type 'anaconda-navigator' into the anaconda command prompt command line I get this:

<urlopen error Tunnel connection failed: 407 Proxy Authentication Required>
<urlopen error Tunnel connection failed: 407 Proxy Authentication Required>
<urlopen error Tunnel connection failed: 407 Proxy Authentication Required>

I am working through proxy server and updated the proxy_server in .condarc file.

Conda list command shows following:

_license                  1.1                      py36_1    defaults
alabaster                 0.7.10                   py36_0    defaults
anaconda                  custom                   py36_0    defaults
anaconda-client           1.6.2                    py36_0    defaults
anaconda-navigator        1.5.1                    py36_0    defaults
anaconda-project          0.4.1                    py36_0    defaults
astroid                   1.4.9                    py36_0    defaults
astropy                   1.3.2               np111py36_0    defaults
babel                     2.4.0                    py36_0    defaults
backports                 1.0                      py36_0    defaults
beautifulsoup4            4.5.3                    py36_0    defaults
bitarray                  0.8.1                    py36_1    defaults
blaze                     0.10.1                   py36_0    defaults
bleach                    1.5.0                    py36_0    defaults
bokeh                     0.12.5                   py36_0    defaults
boto                      2.46.1                   py36_0    defaults
bottleneck                1.2.0               np111py36_0    defaults
bzip2                     1.0.6                    vc14_3  [vc14]  defaults
cffi                      1.9.1                    py36_0    defaults
chardet                   3.0.2                    py36_0    defaults
chest                     0.2.3                    py36_0    defaults
click                     6.7                      py36_0    defaults
cloudpickle               0.2.2                    py36_0    defaults
clyent                    1.2.2                    py36_0    defaults
colorama                  0.3.7                    py36_0    defaults
comtypes                  1.1.2                    py36_0    defaults
conda                     4.3.16                   py36_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py36_0    defaults
console_shortcut          0.1.1                    py36_1    defaults
contextlib2               0.5.4                    py36_0    defaults
cryptography              1.7.1                    py36_0    defaults
curl                      7.52.1                   vc14_0  [vc14]  defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.25.2                   py36_0    defaults
cytoolz                   0.8.2                    py36_0    defaults
dask                      0.14.1                   py36_0    defaults
datashape                 0.5.4                    py36_0    defaults
decorator                 4.0.11                   py36_0    defaults
dill                      0.2.6                    py36_0    defaults
docutils                  0.13.1                   py36_0    defaults
entrypoints               0.2.2                    py36_1    defaults
et_xmlfile                1.0.1                    py36_0    defaults
fastcache                 1.0.2                    py36_1    defaults
flask                     0.12.1                   py36_0    defaults
flask-cors                3.0.2                    py36_0    defaults
freetype                  2.5.5                    vc14_2  [vc14]  defaults
get_terminal_size         1.0.0                    py36_0    defaults
gevent                    1.2.1                    py36_0    defaults
greenlet                  0.4.12                   py36_0    defaults
h5py                      2.7.0               np111py36_0    defaults
hdf5                      1.8.15.1                 vc14_4  [vc14]  defaults
heapdict                  1.0.0                    py36_1    defaults
html5lib                  0.999                    py36_0    defaults
icu                       57.1                     vc14_0  [vc14]  defaults
idna                      2.2                      py36_0    defaults
imagesize                 0.7.1                    py36_0    defaults
ipykernel                 4.6.1                    py36_0    defaults
ipython                   5.1.0                    py36_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                6.0.0                    py36_0    defaults
isort                     4.2.5                    py36_0    defaults
itsdangerous              0.24                     py36_0    defaults
jdcal                     1.3                      py36_0    defaults
jedi                      0.9.0                    py36_1    defaults
jinja2                    2.9.6                    py36_0    defaults
jpeg                      9b                       vc14_0  [vc14]  defaults
jsonschema                2.6.0                    py36_0    defaults
jupyter                   1.0.0                    py36_3    defaults
jupyter_client            5.0.1                    py36_0    defaults
jupyter_console           5.1.0                    py36_0    defaults
jupyter_core              4.3.0                    py36_0    defaults
lazy-object-proxy         1.2.2                    py36_0    defaults
libpng                    1.6.27                   vc14_0  [vc14]  defaults
libtiff                   4.0.6                    vc14_3  [vc14]  defaults
llvmlite                  0.17.0                   py36_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      3.7.3                    py36_0    defaults
markupsafe                0.23                     py36_2    defaults
matplotlib                2.0.0               np111py36_0    defaults
menuinst                  1.4.4                    py36_0    defaults
mistune                   0.7.4                    py36_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py36_3    defaults
mpmath                    0.19                     py36_1    defaults
multipledispatch          0.4.9                    py36_0    defaults
nbconvert                 5.1.1                    py36_0    defaults
nbformat                  4.3.0                    py36_0    defaults
networkx                  1.11                     py36_0    defaults
nltk                      3.2.2                    py36_0    defaults
nose                      1.3.7                    py36_1    defaults
notebook                  5.0.0                    py36_0    defaults
numba                     0.32.0              np111py36_0    defaults
numexpr                   2.6.2               np111py36_0    defaults
numpy                     1.11.3                   py36_0    defaults
numpydoc                  0.6.0                    py36_0    defaults
odo                       0.5.0                    py36_1    defaults
olefile                   0.44                     py36_0    defaults
openpyxl                  2.4.1                    py36_0    defaults
openssl                   1.0.2k                   vc14_0  [vc14]  defaults
pandas                    0.19.2              np111py36_1    defaults
pandocfilters             1.4.1                    py36_0    defaults
partd                     0.3.7                    py36_0    defaults
path.py                   10.1                     py36_0    defaults
pathlib2                  2.2.1                    py36_0    defaults
patsy                     0.4.1                    py36_0    defaults
pep8                      1.7.0                    py36_0    defaults
pickleshare               0.7.4                    py36_0    defaults
pillow                    4.1.0                    py36_0    defaults
pip                       9.0.1                    py36_1    defaults
ply                       3.10                     py36_0    defaults
prompt_toolkit            1.0.14                   py36_0    defaults
psutil                    5.2.2                    py36_0    defaults
py                        1.4.32                   py36_0    defaults
pyasn1                    0.2.3                    py36_0    defaults
pycosat                   0.6.2                    py36_0    defaults
pycparser                 2.17                     py36_0    defaults
pycrypto                  2.6.1                    py36_5    defaults
pycurl                    7.43.0                   py36_2    defaults
pyflakes                  1.5.0                    py36_0    defaults
pygments                  2.2.0                    py36_0    defaults
pylint                    1.6.4                    py36_1    defaults
pyopenssl                 16.2.0                   py36_0    defaults
pyparsing                 2.1.4                    py36_0    defaults
pyqt                      5.6.0                    py36_2    defaults
pyreadline                2.1                      py36_0    defaults
pytables                  3.2.2               np111py36_4    defaults
pytest                    3.0.7                    py36_0    defaults
python                    3.6.1                         0    defaults
python-dateutil           2.6.0                    py36_0    defaults
pytz                      2017.2                   py36_0    defaults
pywavelets                0.5.2               np111py36_0    defaults
pywin32                   220                      py36_2    defaults
pyyaml                    3.12                     py36_0    defaults
pyzmq                     16.0.2                   py36_0    defaults
qt                        5.6.2                    vc14_3  [vc14]  defaults
qtawesome                 0.4.4                    py36_0    defaults
qtconsole                 4.3.0                    py36_0    defaults
qtpy                      1.2.1                    py36_0    defaults
requests                  2.13.0                   py36_0    defaults
rope                      0.9.4                    py36_1    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
scikit-image              0.13.0              np111py36_0    defaults
scikit-learn              0.18.1              np111py36_1    defaults
scipy                     0.19.0              np111py36_0    defaults
seaborn                   0.7.1                    py36_0    defaults
setuptools                27.2.0                   py36_1    defaults
simplegeneric             0.8.1                    py36_1    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.18                     py36_0    defaults
six                       1.10.0                   py36_0    defaults
snowballstemmer           1.2.1                    py36_0    defaults
sockjs-tornado            1.0.3                    py36_0    defaults
sphinx                    1.5.4                    py36_0    defaults
spyder                    3.1.3                    py36_0    defaults
sqlalchemy                1.1.9                    py36_0    defaults
statsmodels               0.8.0               np111py36_0    defaults
sympy                     1.0                      py36_0    defaults
testpath                  0.3                      py36_0    defaults
tk                        8.5.18                   vc14_0  [vc14]  defaults
toolz                     0.8.2                    py36_0    defaults
tornado                   4.5                      py36_0    defaults
traitlets                 4.3.2                    py36_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
vs2015_runtime            14.0.25123                    0    defaults
wcwidth                   0.1.7                    py36_0    defaults
werkzeug                  0.12.1                   py36_0    defaults
wheel                     0.29.0                   py36_0    defaults
widgetsnbextension        2.0.0                    py36_0    defaults
win_unicode_console       0.5                      py36_0    defaults
wrapt                     1.10.10                  py36_0    defaults
xlrd                      1.0.0                    py36_0    defaults
xlsxwriter                0.9.6                    py36_0    defaults
xlwings                   0.10.4                   py36_0    defaults
xlwt                      1.2.0                    py36_0    defaults
zlib                      1.2.8                    vc14_3  [vc14]  defaults

I am able to use conda install command and have updated all the packages.

**Comment by goanpeca** [comment]
@maanasadi you will need to update your environment variables

`HTTP_PROXY`
`HTTPS_PROXY` to match the entries in condarc. Sorry for the inconvenience, we are working on a fix
