### ISSUE TITLE
Parallel install of Python 2 and 3

### ISSUE THREAD

**Issue by chrish42** [ContinuumIO/anaconda-issues#161]
As a "wishlist" feature request, it would be nice to be able to create both a Python 2 and 3 install (in "anaconda/bin", etc.) from running the Anaconda installer. This would allow system scripts to run with either Python 2 or 3. All the relevant Python executables, etc. are prefixed with aversion number, so they could be installed in the same "bin", etc. directories without conflicts.

Right now this can be accomplished by creating two Anaconda installs, say in "anaconda2" and "anaconda3" directories, and adding both "bin" subdirectories to the path. But this leads to a lot of unnecessary, duplicate packages installed in both hierarchies.

This is done by many recent Linux distributions already, which make both "python2" and "python3" available in the path. I'm using RHEL 6.5, which doesn't have a great Python story, so I'm using Anaconda to supply a recent Python 2. I'd like to be able to use Anaconda to supply a system-wide (available in the path, etc.) Python3 also. Thanks for reading!

**Comment by thriveth** [comment]
Sorry to reopen this, but can I have both a Python 2.7 python and a python 3.x python3 executable available in one Anaconda environment? I am using Anaconda for my default python for my user, but run into problems now because then some programs cannot find the system python3 executable.

**Comment by TheMitchWorksPro** [comment]
This is also a wish list item:  But To this poster's point:  if you are trying to learn Python or Data Science concepts, some classes now use Python 2.7.x and others use 3.x (3.5 ... 3.6 ...).  A novice user can get into real trouble trying to solve problems like how to make Spyder switchable between two environments.  If there were an Anaconda distribution that set up the two main environments that aspiring Data scientists need as Python 2.x and Python 3.x and deployed with Spyder in both with icons to run either Spyder, that would really help students use this application and go a long way towards students loving what you've done.  Related points:  Root currently installs on windows with Notebook menu items of [default] and [root] that point to the same environment.  If the distribution named [root] according to the version deployed, this would be a nice-to-have as well.  lastly - there should be warnings in a readme or help file that comes with all distributions and that user is pointed to at end of install that mixing and matching conda install packages with pip or other non-conda installs can be dangerous and can break your environment and that conda update --all should not be run unless you take precaution of running conda update conda first.  In fact - the distribution should run both these commands in proper order and/or run conda update spyder in right sequence (if this too has to run ahead of update --all) so the user at least gets one clean up-to-date working environment as a result of using the Anaconda distribution file.  Sorry - I know this is a lot but you would not believe how many hours of pain I have been going through with my distribution on a Windows 7 64 bit machine that this stuff might have helped me avoid.  If any of this could be in a future distribution I think your users would love you. :-)

**Comment by arita37** [comment]
Think best is to address those problems to Python foundation, to make robust, reliable wrappers on top of Python 3.XXX so python 2 is compatible.
If enough people request the needs, maybe, there is enough funding to make this dream because true....


You can also Google to release Tensor Flow (2015 !!!), available in Python 3.... (not only in Python 2).
