### ISSUE TITLE
Anaconda installation on users with non-ascii characters

### ISSUE THREAD

**Issue by maidy199** [ContinuumIO/anaconda-issues#1613]
I recently tried to install anaconda 4.3.1 on several computers with Windows 10 on them. The users have Chinese characters as their username so I tried using the path C:\anaconda\ to install. The installer runs until the very end but then an error comes out by the end of the installation about the existence of non-ascii characters and then it fails to create anaconda paths and installation cancels. I try to open the anaconda navigator from its installed location but the same error shows up on the command window.

I am guessing the error comes due to the foldername of the User account is in Chinese characters.

Is there a way around that to install anaconda on that account or it would be better to make a new user account with only latin characters.

**Comment by mingwandroid** [comment]
> The installer runs until the very end but then an error comes out by the end of the installation about the existence of non-ascii 

Can you give the exact details of this error?

> it would be better to make a new user account with only latin characters

This is what I would recommend, yes.
