### ISSUE TITLE
R Kernel died in jupyter notebook dyld: Library not loaded: @rpath/libintl.9.dylib

### ISSUE THREAD

**Issue by camilogavo** [ContinuumIO/anaconda-issues#1614]
Hi, 

I am trying to run r in Jupyter notebook but after launch the Kernel dies, the message in the prompt is:

dyld: Library not loaded: @rpath/libintl.9.dylib

  Referenced from: /Users/camilogavo/anaconda/lib/R/lib/libR.dylib

  Reason: image not found

Abort trap: 6

I'm using MacOS Sierra 10.12.4

Anaconda 1.5.2

conda info is

Juans-MacBook-Pro:~ camilogavo$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/camilogavo/anaconda  (writable)
    default environment : /Users/camilogavo/anaconda
       envs directories : /Users/camilogavo/anaconda/envs
          package cache : /Users/camilogavo/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/camilogavo/.condarc
           offline mode : False

conda list is

Juans-MacBook-Pro:~ camilogavo$ conda list
# packages in environment at /Users/camilogavo/anaconda:
#
_license                  1.1                      py36_1  
alabaster                 0.7.9                    py36_0  
anaconda                  custom                   py36_0  
anaconda-clean            1.1.0                    py36_0  
anaconda-client           1.6.0                    py36_0  
anaconda-navigator        1.5.2                    py36_0  
anaconda-project          0.4.1                    py36_0  
appnope                   0.1.0                    py36_0  
appscript                 1.0.1                    py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3                 np111py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bokeh                     0.12.4                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np111py36_0  
cairo                     1.14.6                        4    conda-forge
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
conda                     4.2.13                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.13.0                   py36_0  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       3    conda-forge
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_0  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         2    conda-forge
fastcache                 1.0.2                    py36_1  
flask                     0.12                     py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
get_terminal_size         1.0.0                    py36_0  
gettext                   0.19.7                        1    conda-forge
gevent                    1.2.1                    py36_0  
glib                      2.51.4                        0    conda-forge
graphite2                 1.3.9                         0    conda-forge
greenlet                  0.4.11                   py36_0  
gsl                       2.2.1                         1    conda-forge
h5py                      2.6.0               np111py36_2  
harfbuzz                  1.4.3                         0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
icu                       58.1                          1    conda-forge
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.5.2                    py36_0  
ipython                   5.1.0                    py36_1  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                5.2.2                    py36_1  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.9.0                    py36_1  
jinja2                    2.9.4                    py36_0  
jpeg                      9b                            0    conda-forge
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            4.4.0                    py36_0  
jupyter_console           5.0.0                    py36_0  
jupyter_core              4.2.1                    py36_0  
lazy-object-proxy         1.2.2                    py36_0  
libffi                    3.2.1                         3    conda-forge
libgcc                    4.8.5                         1  
libiconv                  1.14                          0  
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.2                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np111py36_3    conda-forge
mistune                   0.7.3                    py36_1  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
nbconvert                 4.2.0                    py36_0  
nbformat                  4.2.0                    py36_0  
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  4.3.1                    py36_0  
numba                     0.30.1              np111py36_0  
numexpr                   2.6.1               np111py36_2  
numpy                     1.11.3                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0    conda-forge
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np111py36_1  
pandoc                    1.19.2                        0    conda-forge
pango                     1.40.4                        0    conda-forge
partd                     0.3.7                    py36_0  
path.py                   10.0                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          0    conda-forge
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.1.0                    py36_0    conda-forge
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0    conda-forge
ply                       3.9                      py36_0  
prompt_toolkit            1.0.9                    py36_0  
psutil                    5.0.1                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.32                   py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.1.3                    py36_0  
pylint                    1.6.4                    py36_1  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_1  
pytables                  3.3.0               np111py36_0  
pytest                    3.0.5                    py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
python.app                1.2                      py36_4  
pytz                      2016.10                  py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         1    conda-forge
qtawesome                 0.4.3                    py36_0  
qtconsole                 4.2.1                    py36_1  
qtpy                      1.2.1                    py36_0  
r-assertthat              0.1                    r3.3.2_4    r
r-backports               1.0.4                  r3.3.2_0    r
r-base                    3.3.2                         4    conda-forge
r-base64enc               0.1_3                  r3.3.2_0    r
r-bh                      1.62.0_1               r3.3.2_0    r
r-bitops                  1.0_6                  r3.3.2_2    r
r-boot                    1.3_18                 r3.3.2_0    r
r-broom                   0.4.1                  r3.3.2_0    r
r-car                     2.1_4                  r3.3.2_0    r
r-caret                   6.0_73                 r3.3.2_0    r
r-catools                 1.17.1                 r3.3.2_2    r
r-class                   7.3_14                 r3.3.2_0    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-codetools               0.2_15                 r3.3.2_0    r
r-colorspace              1.3_1                  r3.3.2_0    r
r-crayon                  1.3.2                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-dbi                     0.5_1                  r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-dplyr                   0.5.0                  r3.3.2_0    r
r-essentials              1.5.2                  r3.3.2_0    https://repo.continuum.io/pkgs/r
r-evaluate                0.10                   r3.3.2_0    r
r-forcats                 0.1.1                  r3.3.2_0    r
r-foreach                 1.4.3                  r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-formatr                 1.4                    r3.3.2_0    r
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-gistr                   0.3.6                  r3.3.2_0    r
r-glmnet                  2.0_5                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-haven                   1.0.0                  r3.3.2_0    r
r-hexbin                  1.27.1                 r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hms                     0.3                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-htmlwidgets             0.8                    r3.3.2_0    r
r-httpuv                  1.3.3                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-irdisplay               0.4.4                  r3.3.2_0    r
r-irkernel                0.7.1                  r3.3.2_0    r
r-iterators               1.0.8                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-kernsmooth              2.23_15                r3.3.2_0    r
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lattice                 0.20_34                r3.3.2_0    r
r-lazyeval                0.2.0                  r3.3.2_0    r
r-lme4                    1.1_12                 r3.3.2_0    r
r-lubridate               1.6.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-maps                    3.1.1                  r3.3.2_0    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-matrixmodels            0.4_1                  r3.3.2_0    r
r-mgcv                    1.8_16                 r3.3.2_0    r
r-mime                    0.5                    r3.3.2_0    r
r-minqa                   1.2.4                  r3.3.2_2    r
r-mnormt                  1.5_5                  r3.3.2_0    r
r-modelmetrics            1.1.0                  r3.3.2_0    r
r-modelr                  0.1.0                  r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nlme                    3.1_128                r3.3.2_0    r
r-nloptr                  1.0.4                  r3.3.2_2    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-openssl                 0.9.5                  r3.3.2_0    r
r-pbdzmq                  0.2_4                  r3.3.2_0    r
r-pbkrtest                0.4_6                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-pryr                    0.1.2                  r3.3.2_0    r
r-psych                   1.6.9                  r3.3.2_0    r
r-purrr                   0.2.2                  r3.3.2_0    r
r-quantmod                0.4_7                  r3.3.2_0    r
r-quantreg                5.29                   r3.3.2_0    r
r-r6                      2.2.0                  r3.3.2_0    r
r-randomforest            4.6_12                 r3.3.2_0    r
r-rbokeh                  0.5.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-rcppeigen               0.3.2.9.0              r3.3.2_0    r
r-readr                   1.0.0                  r3.3.2_0    r
r-readxl                  0.1.1                  r3.3.2_0    r
r-recommended             3.3.2                  r3.3.2_0    r
r-repr                    0.10                   r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rmarkdown               1.3                    r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-rprojroot               1.1                    r3.3.2_0    r
r-rvest                   0.3.2                  r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-selectr                 0.3_0                  r3.3.2_0    r
r-shiny                   0.14.2                 r3.3.2_0    r
r-sourcetools             0.1.5                  r3.3.2_0    r
r-sparsem                 1.74                   r3.3.2_0    r
r-spatial                 7.3_11                 r3.3.2_0    r
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
r-tibble                  1.2                    r3.3.2_0    r
r-tidyr                   0.6.0                  r3.3.2_0    r
r-tidyverse               1.0.0                  r3.3.2_0    r
r-ttr                     0.23_1                 r3.3.2_0    r
r-uuid                    0.1_2                  r3.3.2_0    r
r-xml2                    1.0.0                  r3.3.2_0    r
r-xtable                  1.8_2                  r3.3.2_0    r
r-xts                     0.9_7                  r3.3.2_2    r
r-yaml                    2.1.14                 r3.3.2_0    r
r-zoo                     1.7_13                 r3.3.2_0    r
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.12.4                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.12.3              np111py36_1  
scikit-learn              0.18.1              np111py36_1  
scipy                     0.18.1              np111py36_1  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sphinx                    1.5.1                    py36_0  
spyder                    3.1.2                    py36_0  
sqlalchemy                1.1.5                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py36_1  
sympy                     1.0                      py36_0  
terminado                 0.6                      py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.1                    py36_0  
unicodecsv                0.14.1                   py36_0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.11.15                  py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        1.2.6                    py36_0  
wrapt                     1.10.8                   py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwings                   0.10.2                   py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                            3

I'll be glad for your help.

Thanks

**Comment by mingwandroid** [comment]
Please show the output from `conda list --show-channel-urls`.

**Comment by camilogavo** [comment]
Juans-MacBook-Pro:~ camilogavo$ conda list --show-channel-urls
# packages in environment at /Users/camilogavo/anaconda:
#
_license                  1.1                      py36_1    defaults
alabaster                 0.7.9                    py36_0    defaults
anaconda                  custom                   py36_0    defaults
anaconda-clean            1.1.0                    py36_0    defaults
anaconda-client           1.6.0                    py36_0    defaults
anaconda-navigator        1.5.2                    py36_0    defaults
anaconda-project          0.4.1                    py36_0    defaults
appnope                   0.1.0                    py36_0    defaults
appscript                 1.0.1                    py36_0    defaults
astroid                   1.4.9                    py36_0    defaults
astropy                   1.3                 np111py36_0    defaults
babel                     2.3.4                    py36_0    defaults
backports                 1.0                      py36_0    defaults
beautifulsoup4            4.5.3                    py36_0    defaults
bitarray                  0.8.1                    py36_0    defaults
blaze                     0.10.1                   py36_0    defaults
bokeh                     0.12.4                   py36_0    defaults
boto                      2.45.0                   py36_0    defaults
bottleneck                1.2.0               np111py36_0    defaults
cairo                     1.14.6                        4    conda-forge
cffi                      1.9.1                    py36_0    defaults
chardet                   2.3.0                    py36_0    defaults
chest                     0.2.3                    py36_0    defaults
click                     6.7                      py36_0    defaults
cloudpickle               0.2.2                    py36_0    defaults
clyent                    1.2.2                    py36_0    defaults
colorama                  0.3.7                    py36_0    defaults
conda                     4.2.13                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py36_0    defaults
contextlib2               0.5.4                    py36_0    defaults
cryptography              1.7.1                    py36_0    defaults
curl                      7.52.1                        0    defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.25.2                   py36_0    defaults
cytoolz                   0.8.2                    py36_0    defaults
dask                      0.13.0                   py36_0    defaults
datashape                 0.5.4                    py36_0    defaults
dbus                      1.10.10                       3    conda-forge
decorator                 4.0.11                   py36_0    defaults
dill                      0.2.5                    py36_0    defaults
docutils                  0.13.1                   py36_0    defaults
entrypoints               0.2.2                    py36_0    defaults
et_xmlfile                1.0.1                    py36_0    defaults
expat                     2.1.0                         2    conda-forge
fastcache                 1.0.2                    py36_1    defaults
flask                     0.12                     py36_0    defaults
flask-cors                3.0.2                    py36_0    defaults
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
get_terminal_size         1.0.0                    py36_0    defaults
gettext                   0.19.7                        1    conda-forge
gevent                    1.2.1                    py36_0    defaults
glib                      2.51.4                        0    conda-forge
graphite2                 1.3.9                         0    conda-forge
greenlet                  0.4.11                   py36_0    defaults
gsl                       2.2.1                         1    conda-forge
h5py                      2.6.0               np111py36_2    defaults
harfbuzz                  1.4.3                         0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py36_1    defaults
icu                       58.1                          1    conda-forge
idna                      2.2                      py36_0    defaults
imagesize                 0.7.1                    py36_0    defaults
ipykernel                 4.5.2                    py36_0    defaults
ipython                   5.1.0                    py36_1    defaults
ipython_genutils          0.1.0                    py36_0    defaults
ipywidgets                5.2.2                    py36_1    defaults
isort                     4.2.5                    py36_0    defaults
itsdangerous              0.24                     py36_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.3                      py36_0    defaults
jedi                      0.9.0                    py36_1    defaults
jinja2                    2.9.4                    py36_0    defaults
jpeg                      9b                            0    conda-forge
jsonschema                2.5.1                    py36_0    defaults
jupyter                   1.0.0                    py36_3    defaults
jupyter_client            4.4.0                    py36_0    defaults
jupyter_console           5.0.0                    py36_0    defaults
jupyter_core              4.2.1                    py36_0    defaults
lazy-object-proxy         1.2.2                    py36_0    defaults
libffi                    3.2.1                         3    conda-forge
libgcc                    4.8.5                         1    defaults
libiconv                  1.14                          0    defaults
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         0    defaults
libxslt                   1.1.29                        0    defaults
llvmlite                  0.15.0                   py36_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      3.7.2                    py36_0    defaults
markupsafe                0.23                     py36_2    defaults
matplotlib                2.0.0               np111py36_3    conda-forge
mistune                   0.7.3                    py36_1    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py36_3    defaults
mpmath                    0.19                     py36_1    defaults
multipledispatch          0.4.9                    py36_0    defaults
nbconvert                 4.2.0                    py36_0    defaults
nbformat                  4.2.0                    py36_0    defaults
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0    defaults
nltk                      3.2.2                    py36_0    defaults
nose                      1.3.7                    py36_1    defaults
notebook                  4.3.1                    py36_0    defaults
numba                     0.30.1              np111py36_0    defaults
numexpr                   2.6.1               np111py36_2    defaults
numpy                     1.11.3                   py36_0    defaults
numpydoc                  0.6.0                    py36_0    defaults
odo                       0.5.0                    py36_1    defaults
olefile                   0.44                     py36_0    conda-forge
openpyxl                  2.4.1                    py36_0    defaults
openssl                   1.0.2k                        1    defaults
pandas                    0.19.2              np111py36_1    defaults
pandoc                    1.19.2                        0    conda-forge
pango                     1.40.4                        0    conda-forge
partd                     0.3.7                    py36_0    defaults
path.py                   10.0                     py36_0    defaults
pathlib2                  2.2.0                    py36_0    defaults
patsy                     0.4.1                    py36_0    defaults
pcre                      8.39                          0    conda-forge
pep8                      1.7.0                    py36_0    defaults
pexpect                   4.2.1                    py36_0    defaults
pickleshare               0.7.4                    py36_0    defaults
pillow                    4.1.0                    py36_0    conda-forge
pip                       9.0.1                    py36_1    defaults
pixman                    0.34.0                        0    conda-forge
ply                       3.9                      py36_0    defaults
prompt_toolkit            1.0.9                    py36_0    defaults
psutil                    5.0.1                    py36_0    defaults
ptyprocess                0.5.1                    py36_0    defaults
py                        1.4.32                   py36_0    defaults
pyasn1                    0.1.9                    py36_0    defaults
pycosat                   0.6.1                    py36_1    defaults
pycparser                 2.17                     py36_0    defaults
pycrypto                  2.6.1                    py36_4    defaults
pycurl                    7.43.0                   py36_2    defaults
pyflakes                  1.5.0                    py36_0    defaults
pygments                  2.1.3                    py36_0    defaults
pylint                    1.6.4                    py36_1    defaults
pyopenssl                 16.2.0                   py36_0    defaults
pyparsing                 2.1.4                    py36_0    defaults
pyqt                      5.6.0                    py36_1    defaults
pytables                  3.3.0               np111py36_0    defaults
pytest                    3.0.5                    py36_0    defaults
python                    3.6.0                         0    defaults
python-dateutil           2.6.0                    py36_0    defaults
python.app                1.2                      py36_4    defaults
pytz                      2016.10                  py36_0    defaults
pyyaml                    3.12                     py36_0    defaults
pyzmq                     16.0.2                   py36_0    defaults
qt                        5.6.2                         1    conda-forge
qtawesome                 0.4.3                    py36_0    defaults
qtconsole                 4.2.1                    py36_1    defaults
qtpy                      1.2.1                    py36_0    defaults
r-assertthat              0.1                    r3.3.2_4    r
r-backports               1.0.4                  r3.3.2_0    r
r-base                    3.3.2                         4    conda-forge
r-base64enc               0.1_3                  r3.3.2_0    r
r-bh                      1.62.0_1               r3.3.2_0    r
r-bitops                  1.0_6                  r3.3.2_2    r
r-boot                    1.3_18                 r3.3.2_0    r
r-broom                   0.4.1                  r3.3.2_0    r
r-car                     2.1_4                  r3.3.2_0    r
r-caret                   6.0_73                 r3.3.2_0    r
r-catools                 1.17.1                 r3.3.2_2    r
r-class                   7.3_14                 r3.3.2_0    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-codetools               0.2_15                 r3.3.2_0    r
r-colorspace              1.3_1                  r3.3.2_0    r
r-crayon                  1.3.2                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-dbi                     0.5_1                  r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-dplyr                   0.5.0                  r3.3.2_0    r
r-essentials              1.5.2                  r3.3.2_0    https://repo.continuum.io/pkgs/r
r-evaluate                0.10                   r3.3.2_0    r
r-forcats                 0.1.1                  r3.3.2_0    r
r-foreach                 1.4.3                  r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-formatr                 1.4                    r3.3.2_0    r
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-gistr                   0.3.6                  r3.3.2_0    r
r-glmnet                  2.0_5                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-haven                   1.0.0                  r3.3.2_0    r
r-hexbin                  1.27.1                 r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hms                     0.3                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-htmlwidgets             0.8                    r3.3.2_0    r
r-httpuv                  1.3.3                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-irdisplay               0.4.4                  r3.3.2_0    r
r-irkernel                0.7.1                  r3.3.2_0    r
r-iterators               1.0.8                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-kernsmooth              2.23_15                r3.3.2_0    r
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lattice                 0.20_34                r3.3.2_0    r
r-lazyeval                0.2.0                  r3.3.2_0    r
r-lme4                    1.1_12                 r3.3.2_0    r
r-lubridate               1.6.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-maps                    3.1.1                  r3.3.2_0    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-matrixmodels            0.4_1                  r3.3.2_0    r
r-mgcv                    1.8_16                 r3.3.2_0    r
r-mime                    0.5                    r3.3.2_0    r
r-minqa                   1.2.4                  r3.3.2_2    r
r-mnormt                  1.5_5                  r3.3.2_0    r
r-modelmetrics            1.1.0                  r3.3.2_0    r
r-modelr                  0.1.0                  r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nlme                    3.1_128                r3.3.2_0    r
r-nloptr                  1.0.4                  r3.3.2_2    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-openssl                 0.9.5                  r3.3.2_0    r
r-pbdzmq                  0.2_4                  r3.3.2_0    r
r-pbkrtest                0.4_6                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-pryr                    0.1.2                  r3.3.2_0    r
r-psych                   1.6.9                  r3.3.2_0    r
r-purrr                   0.2.2                  r3.3.2_0    r
r-quantmod                0.4_7                  r3.3.2_0    r
r-quantreg                5.29                   r3.3.2_0    r
r-r6                      2.2.0                  r3.3.2_0    r
r-randomforest            4.6_12                 r3.3.2_0    r
r-rbokeh                  0.5.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-rcppeigen               0.3.2.9.0              r3.3.2_0    r
r-readr                   1.0.0                  r3.3.2_0    r
r-readxl                  0.1.1                  r3.3.2_0    r
r-recommended             3.3.2                  r3.3.2_0    r
r-repr                    0.10                   r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rmarkdown               1.3                    r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-rprojroot               1.1                    r3.3.2_0    r
r-rvest                   0.3.2                  r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-selectr                 0.3_0                  r3.3.2_0    r
r-shiny                   0.14.2                 r3.3.2_0    r
r-sourcetools             0.1.5                  r3.3.2_0    r
r-sparsem                 1.74                   r3.3.2_0    r
r-spatial                 7.3_11                 r3.3.2_0    r
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
r-tibble                  1.2                    r3.3.2_0    r
r-tidyr                   0.6.0                  r3.3.2_0    r
r-tidyverse               1.0.0                  r3.3.2_0    r
r-ttr                     0.23_1                 r3.3.2_0    r
r-uuid                    0.1_2                  r3.3.2_0    r
r-xml2                    1.0.0                  r3.3.2_0    r
r-xtable                  1.8_2                  r3.3.2_0    r
r-xts                     0.9_7                  r3.3.2_2    r
r-yaml                    2.1.14                 r3.3.2_0    r
r-zoo                     1.7_13                 r3.3.2_0    r
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py36_0    defaults
requests                  2.12.4                   py36_0    defaults
rope                      0.9.4                    py36_1    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
scikit-image              0.12.3              np111py36_1    defaults
scikit-learn              0.18.1              np111py36_1    defaults
scipy                     0.18.1              np111py36_1    defaults
seaborn                   0.7.1                    py36_0    defaults
setuptools                27.2.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_1    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.18                     py36_0    defaults
six                       1.10.0                   py36_0    defaults
snowballstemmer           1.2.1                    py36_0    defaults
sockjs-tornado            1.0.3                    py36_0    defaults
sphinx                    1.5.1                    py36_0    defaults
spyder                    3.1.2                    py36_0    defaults
sqlalchemy                1.1.5                    py36_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.6.1               np111py36_1    defaults
sympy                     1.0                      py36_0    defaults
terminado                 0.6                      py36_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.2                    py36_0    defaults
tornado                   4.4.2                    py36_0    defaults
traitlets                 4.3.1                    py36_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
wcwidth                   0.1.7                    py36_0    defaults
werkzeug                  0.11.15                  py36_0    defaults
wheel                     0.29.0                   py36_0    defaults
widgetsnbextension        1.2.6                    py36_0    defaults
wrapt                     1.10.8                   py36_0    defaults
xlrd                      1.0.0                    py36_0    defaults
xlsxwriter                0.9.6                    py36_0    defaults
xlwings                   0.10.2                   py36_0    defaults
xlwt                      1.2.0                    py36_0    defaults
xz                        5.2.2                         1    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         3    defaults

**Comment by mingwandroid** [comment]
You cannot mix packages from `conda-forge` and those from the `Anaconda`'s `defaults` channel like this unfortunately.

You can still use both provided you keep `conda-forge` packages in a separate environment from `defaults` packages. You can read about conda environments [here](https://conda.io/docs/using/envs.html)

At present `conda-forge` do not have their `R` package infrastructure complete enough for general use.

**Comment by camilogavo** [comment]
Thanks a lot. I made a mistake installing those packages from conda-forge.

Do you know how to remove them?

**Comment by mingwandroid** [comment]
The easiest way is to remove `conda-forge` from your channels (probably in `~/.condarc`) then run `conda update --all`. If it isn't in there, then just run the command.

**Comment by Richyrecarey** [comment]
@mingwandroid I'm having the same problem which I didn't quite understand. Can I have at the same time packages from r, and from sebp?

I have a clean installation, no problems whatsoever, but when I install that packages from sebp:
`conda install -c sebp r-fda.usc `
My depencecies break and jupyter does not work, nor R. Problem is that I don't know how to install that package (which I need for college), in any other way. I've been trying all the posible solutions and they didn't work out so far.

Regards!
