### ISSUE TITLE
macOS scipy needs to be rebuilt with the latest GCC package

### ISSUE THREAD

**Issue by mingwandroid** [ContinuumIO/anaconda-issues#1618]
From https://github.com/conda/conda/issues/4981:

> I installed conda and created an environment using the following directions:
> https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md
> 
> In python when I try:
> from sklearn.svm import LinearSVC
> 
> I get the following error:
> 
> Traceback (most recent call last):
> File "", line 1, in 
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/init.py", line 57, in 
> from .base import clone
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/base.py", line 12, in 
> from .utils.fixes import signature
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/utils/init.py", line 11, in 
> from .validation import (as_float_array,
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/utils/validation.py", line 18, in 
> from ..utils.fixes import signature
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/utils/fixes.py", line 290, in 
> from scipy.sparse.linalg import lsqr as sparse_lsqr
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/init.py", line 113, in 
> from .isolve import *
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/init.py", line 6, in 
> from .iterative import *
> File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/iterative.py", line 7, in 
> from . import _iterative
> ImportError: dlopen(/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-35m-darwin.so, 2): Library not loaded: /Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libgcc_s.1.dylib
> Referenced from: /Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-35m-darwin.so
> Reason: image not found
> I am confused about where it is looking for libgcc_s.1.dylib
> /Users/ray etc ?
>

**Comment by hsunsmile** [comment]
bump, same issue here.
```
➔ ipython
Python 3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import scipy.special as special
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-51f4b7f310bc> in <module>()
----> 1 import scipy.special as special

/Users/x/anaconda/envs/ph2t/lib/python3.5/site-packages/scipy/special/__init__.py in <module>()
    634 from __future__ import division, print_function, absolute_import
    635
--> 636 from ._ufuncs import *
    637
    638 from .basic import *

ImportError: dlopen(/Users/x/anaconda/envs/ph2t/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so, 2): Library not loaded: /Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libgcc_s.1.dylib
  Referenced from: /Users/x/anaconda/envs/ph2t/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so
  Reason: image not found
```

**Comment by mingwandroid** [comment]
Bugs in`conda-forge` packages should not be added here. I filed it in the right place for you: https://github.com/conda-forge/scipy-feedstock/issues/59
