### ISSUE TITLE
Anaconda Navigator repeatedly asks for same  update

### ISSUE THREAD

**Issue by kmathers** [ContinuumIO/anaconda-issues#1620]
Anaconda navigator asks me to update to version 1.5.2 every time I open, then that the installation was successful and to restart once I'm done. When I restart it's still 1.5.1 and asks me to update to 1.5.2 again.

**Comment by goanpeca** [comment]
@kmathers 

Could you open a terminal and update navigator from there?

`conda update anaconda-navigator` ?

We are improving the update procedure for 1.6

**Comment by kmathers** [comment]
Yup, that fixed it. Thanks!
