### ISSUE TITLE
R KERNEL DYING IN JUPYTER NOTEBOOK RUNNING ON OSXLION

### ISSUE THREAD

**Issue by dthboyd** [ContinuumIO/anaconda-issues#1621]
WARNING:root:kernel f0e2ca21-6ef0-4d5e-8292-f29f45fd31af restarted
dyld: Library not loaded: @rpath/libicuuc.56.dylib
  Referenced from: //anaconda/lib/R/lib/libR.dylib
  Reason: image not found
[W 16:45:27.073 NotebookApp] KernelRestarter: restart failed
[W 16:45:27.074 NotebookApp] Kernel f0e2ca21-6ef0-4d5e-8292-f29f45fd31af died, removing from map.
ERROR:root:kernel f0e2ca21-6ef0-4d5e-8292-f29f45fd31af restarted failed!

**Comment by mingwandroid** [comment]
Please do not install packages from `conda-forge` in the same environment as packages the `Anaconda`'s `default` channels they are binary incompatible.

**Comment by dthboyd** [comment]
so do i delete and reinstall

**Comment by mingwandroid** [comment]
No, just remove `conda-forge` from your `~/.condarc` and then do `conda update --all`.

If you don't have it in there then just do `conda update --all`.

**Comment by dthboyd** [comment]
ok, thanks for the help
