### ISSUE TITLE
Anaconda Navigator Home page showing nothing

### ISSUE THREAD

**Issue by jingw222** [ContinuumIO/anaconda-issues#1622]
After upgrading Anaconda Navigator to the latest 1.5.2 version, I managed to open it without an issue. But oddly it didn't show me anything under the `Home` tab. Usually, I would see Spyder, Ipython, Rstudio, and so on. How can possibly I deal with that weird thing? Here again was the terminal output:

`2017-04-22 08:38:47,109 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-22 08:38:47,110 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

`2017-04-22 08:38:47,110 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)`

**Comment by goanpeca** [comment]
@jingw222 could you show the output of `conda info` and `conda list`?

**Comment by jingw222** [comment]
``Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : /home/jingw222/anaconda3  (writable)
    default environment : /home/jingw222/anaconda3
       envs directories : /home/jingw222/anaconda3/envs
                          /home/jingw222/.conda/envs
          package cache : /home/jingw222/anaconda3/pkgs
                          /home/jingw222/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/linux-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jingw222/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.6.1 Linux/4.8.0-46-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000``

``# packages in environment at /home/jingw222/anaconda3:
#
_license                  1.1                      py36_1  
alabaster                 0.7.10                   py36_0  
anaconda                  custom                   py36_0  
anaconda-client           1.6.2                    py36_0  
anaconda-navigator        1.5.2                    py36_0  
anaconda-project          0.4.1                    py36_0  
appdirs                   1.4.3                     <pip>
arrow                     0.8.0                     <pip>
astroid                   1.4.9                    py36_0  
astropy                   1.3.1               np112py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
better-exceptions         0.1.6                     <pip>
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                    py36_0  
bleach                    2.0.0                     <pip>
bokeh                     0.12.4                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np112py36_0  
bz2file                   0.98                     py36_0  
bzip2                     1.0.6                         3  
cairo                     1.14.8                        0  
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
CommonMark                0.5.4                     <pip>
conda                     4.3.16                   py36_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
cssselect                 1.0.1                     <pip>
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cymem                     1.31.2                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.1                   py36_0  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_0  
entrypoints               0.2.2                     <pip>
enum34                    1.1.6                     <pip>
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py36_1  
flask                     0.12                     py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        2  
freetype                  2.5.5                         2  
future                    0.16.0                   py36_1  
future                    0.16.0                    <pip>
gensim                    1.0.1               np112py36_0  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
glib                      2.50.2                        1  
gmp                       6.1.0                         0  
graphviz                  2.38.0                        4  
graphviz                  0.6                       <pip>
greenlet                  0.4.12                   py36_0  
gsl                       2.2.1                         0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.7.0               np112py36_0  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
howdoi                    1.1.9                     <pip>
html5lib                  0.999999999               <pip>
html5lib                  0.999                    py36_0  
hypertools                0.1.6                     <pip>
icu                       54.1                          0  
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
infinity                  1.4                       <pip>
intervals                 0.8.0                     <pip>
ipykernel                 4.6.0                     <pip>
ipykernel                 4.5.2                    py36_0  
ipython                   6.0.0                     <pip>
ipython                   5.3.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.10.2                    <pip>
jedi                      0.9.0                    py36_1  
Jinja2                    2.9.6                     <pip>
jinja2                    2.9.5                    py36_0  
joblib                    0.11                      <pip>
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter-client            5.0.1                     <pip>
jupyter_client            5.0.0                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
jupyterlab                0.19.0                    <pip>
jupyterthemes             0.15.3                    <pip>
launcher                  1.0.0                         1  
lazy-object-proxy         1.2.2                    py36_0  
lesscpy                   0.12.0                    <pip>
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libtool                   2.4.2                         0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
lime                      0.1.1.20                  <pip>
llvmlite                  0.16.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
markupsafe                0.23                     py36_2  
MarkupSafe                1.0                       <pip>
matplotlib                2.0.0               np112py36_0  
mistune                   0.7.4                     <pip>
mistune                   0.7.3                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
more-itertools            3.0.0                     <pip>
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
murmurhash                0.26.4                   py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
nbsphinx                  0.2.13                    <pip>
ncurses                   5.9                          10  
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
node-webkit               0.10.1                        0  
nodejs                    4.4.0                         0    javascript
nose                      1.3.7                    py36_1  
notebook                  4.4.1                    py36_0  
notebook                  5.0.0                     <pip>
numba                     0.31.0              np112py36_0  
numexpr                   2.6.2               np112py36_0  
numpy                     1.12.1                    <pip>
numpy                     1.12.1                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        1  
packaging                 16.8                      <pip>
pandas                    0.19.2              np112py36_1  
pandas-datareader         0.2.1                    py36_0  
pandoc                    1.15.0.6                      0  
pandocfilters             1.4.1                    py36_0  
pango                     1.40.3                        1  
partd                     0.3.7                    py36_0  
path.py                   10.1                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pdir2                     0.2.0                     <pip>
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.0.0                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
plac                      0.9.6                    py36_0  
plotly                    1.12.9                   py36_0  
ply                       3.10                     py36_0  
ply                       3.10                      <pip>
ppca                      0.0.2                     <pip>
preshed                   0.46.4                   py36_0  
prompt-toolkit            1.0.14                    <pip>
prompt_toolkit            1.0.13                   py36_0  
protobuf                  3.2.0                     <pip>
psutil                    5.2.1                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.33                   py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.2                    py36_0  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pymc                      2.3.6                     <pip>
pymc3                     3.0                       <pip>
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.2.0                     <pip>
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pyquery                   1.2.17                    <pip>
pystan                    2.14.0.0                  <pip>
pytables                  3.3.0               np112py36_0  
pytest                    3.0.7                    py36_0  
python                    3.6.1                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2016.10                  py36_0  
pywavelets                0.5.2               np112py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         3  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
r                         3.3.2                  r3.3.2_0  
r-assertthat              0.1                    r3.3.2_4    r
r-backports               1.0.4                  r3.3.2_0    r
r-base                    3.3.2                         1    r
r-base64enc               0.1_3                  r3.3.2_0    r
r-bh                      1.62.0_1               r3.3.2_0    r
r-bitops                  1.0_6                  r3.3.2_2    r
r-boot                    1.3_18                 r3.3.2_0    r
r-broom                   0.4.1                  r3.3.2_0    r
r-car                     2.1_4                  r3.3.2_0    r
r-caret                   6.0_73                 r3.3.2_0    r
r-catools                 1.17.1                 r3.3.2_2    r
r-class                   7.3_14                 r3.3.2_0    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-codetools               0.2_15                 r3.3.2_0    r
r-colorspace              1.3_1                  r3.3.2_0    r
r-crayon                  1.3.2                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-dbi                     0.5_1                  r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-dplyr                   0.5.0                  r3.3.2_0    r
r-essentials              1.5.2                  r3.3.2_0    r
r-evaluate                0.10                   r3.3.2_0    r
r-forcats                 0.1.1                  r3.3.2_0    r
r-foreach                 1.4.3                  r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-formatr                 1.4                    r3.3.2_0    r
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-gistr                   0.3.6                  r3.3.2_0    r
r-glmnet                  2.0_5                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-haven                   1.0.0                  r3.3.2_0    r
r-hexbin                  1.27.1                 r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hms                     0.3                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-htmlwidgets             0.8                    r3.3.2_0    r
r-httpuv                  1.3.3                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-irdisplay               0.4.4                  r3.3.2_0    r
r-irkernel                0.7.1                  r3.3.2_0    r
r-iterators               1.0.8                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-kernsmooth              2.23_15                r3.3.2_0    r
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lattice                 0.20_34                r3.3.2_0    r
r-lazyeval                0.2.0                  r3.3.2_0    r
r-lme4                    1.1_12                 r3.3.2_0    r
r-lubridate               1.6.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-maps                    3.1.1                  r3.3.2_0    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-matrixmodels            0.4_1                  r3.3.2_0    r
r-mgcv                    1.8_16                 r3.3.2_0    r
r-mime                    0.5                    r3.3.2_0    r
r-minqa                   1.2.4                  r3.3.2_2    r
r-mnormt                  1.5_5                  r3.3.2_0    r
r-modelmetrics            1.1.0                  r3.3.2_0    r
r-modelr                  0.1.0                  r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nlme                    3.1_128                r3.3.2_0    r
r-nloptr                  1.0.4                  r3.3.2_2    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-openssl                 0.9.5                  r3.3.2_0    r
r-pbdzmq                  0.2_4                  r3.3.2_0    r
r-pbkrtest                0.4_6                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-pryr                    0.1.2                  r3.3.2_0    r
r-psych                   1.6.9                  r3.3.2_0    r
r-purrr                   0.2.2                  r3.3.2_0    r
r-quantmod                0.4_7                  r3.3.2_0    r
r-quantreg                5.29                   r3.3.2_0    r
r-r6                      2.2.0                  r3.3.2_0    r
r-randomforest            4.6_12                 r3.3.2_0    r
r-rbokeh                  0.5.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-rcppeigen               0.3.2.9.0              r3.3.2_0    r
r-readr                   1.0.0                  r3.3.2_0    r
r-readxl                  0.1.1                  r3.3.2_0    r
r-recommended             3.3.2                  r3.3.2_0    r
r-repr                    0.10                   r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rmarkdown               1.3                    r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-rprojroot               1.1                    r3.3.2_0    r
r-rvest                   0.3.2                  r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-selectr                 0.3_0                  r3.3.2_0    r
r-shiny                   0.14.2                 r3.3.2_0    r
r-sourcetools             0.1.5                  r3.3.2_0    r
r-sparsem                 1.74                   r3.3.2_0    r
r-spatial                 7.3_11                 r3.3.2_0    r
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
r-tibble                  1.2                    r3.3.2_0    r
r-tidyr                   0.6.0                  r3.3.2_0    r
r-tidyverse               1.0.0                  r3.3.2_0    r
r-ttr                     0.23_1                 r3.3.2_0    r
r-uuid                    0.1_2                  r3.3.2_0    r
r-xml2                    1.0.0                  r3.3.2_0    r
r-xtable                  1.8_2                  r3.3.2_0    r
r-xts                     0.9_7                  r3.3.2_2    r
r-yaml                    2.1.14                 r3.3.2_0    r
r-zoo                     1.7_13                 r3.3.2_0    r
readline                  6.2                           2  
recommonmark              0.4.0                     <pip>
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.13.0                   py36_0  
requests-cache            0.4.13                    <pip>
requests-file             1.4.1                    py36_0  
rope                      0.9.4                    py36_1  
rpy2                      2.8.5              py36r3.3.2_2  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.13.0              np112py36_0  
scikit-learn              0.18.1              np112py36_1  
scikit-plot               0.2.2                     <pip>
scipy                     0.19.0              np112py36_0  
seaborn                   0.7.1                    py36_0  
semver                    2.7.6                    py36_0  
setuptools                27.2.0                   py36_0  
setuptools                35.0.1                    <pip>
shadowsocks               2.8.2                     <pip>
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
six                       1.10.0                    <pip>
smart_open                1.4.0                    py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sortedcontainers          1.5.3                     <pip>
spacy                     0.101.0                  py36_0  
spark-sklearn             0.2.0                     <pip>
sphinx                    1.5.1                    py36_0  
sputnik                   0.9.3                    py36_0  
spyder                    3.1.3                    py36_0  
sqlalchemy                1.1.7                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np112py36_0  
sympy                     1.0                      py36_0  
tensorflow                1.0.1                     <pip>
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
Theano                    0.9.0                     <pip>
thefuck                   3.16                      <pip>
thinc                     5.0.8                    py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
tornado                   4.4.3                     <pip>
tqdm                      4.11.2                    <pip>
traces                    0.3.1                     <pip>
traitlets                 4.3.2                    py36_0  
tsfresh                   0.7.1                     <pip>
ujson                     1.35                     py36_0  
unicodecsv                0.14.1                   py36_0  
urllib3                   1.20                      <pip>
utils                     0.9.0                     <pip>
wcwidth                   0.1.7                    py36_0  
webencodings              0.5                       <pip>
werkzeug                  0.12.1                   py36_0  
wheel                     0.29.0                    <pip>
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
word2vec                  0.9.1                     <pip>
wrapt                     1.10.8                   py36_0  
xgboost                   0.6a2                     <pip>
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3  ``

**Comment by nobodykid** [comment]
I also got the same problem here. When I opened Anaconda Navigator, the only one appeared is RStudio (which I haven't installed).

And also, all packages descriptions also disappear from the Package tab. Though, I still can install them through Prompt

**Comment by jingw222** [comment]
Exactly. In addition, I'm still not able to update packages through the app. The `Upgradable` tab simply shows nothing as well.

**Comment by goanpeca** [comment]
Look like a problem with the downloaded repodata files.

Could you try reseting navigator?

Form the terminal please type

`anaconda-navigator --reset`

**Comment by jingw222** [comment]
Yes, it did. A reset solved the issue for me. Great help! Thanks!

**Comment by nobodykid** [comment]
Worked well with me too, but some packages still shows no descriptions

**Comment by goanpeca** [comment]
>, but some packages still shows no descriptions

Yes, metadata is not available for all packages. This should be fixed in subsequent releases

**Comment by nobodykid** [comment]
> Yes, metadata is not available for all packages.

Aah I see. Thanks for the clarification
