### ISSUE TITLE
windows 10, updating anaconda navigator to version 1.5.2,  failed

### ISSUE THREAD

**Issue by Schleg65** [ContinuumIO/anaconda-issues#1626]
after each newstart of the anaconda navigator there pops the request to update it to version 1.5.2.;
the update was done, the navigator gave also the message, succesfully updated, but next time after start the same update should be done again, obviously the update process does't work?

**Comment by goanpeca** [comment]
@Schleg65 yes, we have an issue with the update process. Could you open the anaconda prompt and update from there?

`conda install anaconda-navigator=1.5.2`

**Comment by Schleg65** [comment]
Hi Gonzalo,

unfortunately the installation failed from the anaconda terminal (conda
install anaconda-navigator=1.5.2), with the message below:



*An HTTP error occurred when trying to retrieve this URL.HTTP errors are
often intermittent, and a simple retry will get you on your
way.ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org
<http://conda.anaconda.org>', port=443): Max retries exceeded with url:
/t/Sc-9edd243f-c82a-4f78-963d-e5d592029692/anaconda-fusion/win-64/repodata.json
(Caused by
ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection
object at 0x0000028DFA1C7048>, 'Connection to conda.anaconda.org
<http://conda.anaconda.org> timed out. (connect timeout=9.15)'))",),)*

After launching anaconda navigator most of the former applications
disappeared, there are only two present (qtconsole and spyder) there is no
jupyter notebook, orange-app, anaconda-fusion, anaconda-mosaic, gluevlz,
rstudio...there are all gone.
So what can one do? Complete new installation?

Kind Regards
Christian

2017-04-23 17:21 GMT+02:00 Gonzalo Peña-Castellanos <
notifications@github.com>:

**Comment by dlbfleet** [comment]
@Schleg65 My team having the same problem today. Since the above comment indicates the command line update has it's own issues, what should we do now that this is closed? CLI update, wait for a fix? Thanks for your help.

**Comment by goanpeca** [comment]
There are no problems with cli,

```
URL.HTTP errors are
often intermittent, and a simple retry will get you on your
way.ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org
<http://conda.anaconda.org>', port=443): Max retries exceeded with url:

```
is very clear
