### ISSUE TITLE
Import New Environment in Navigator not functioning 

### ISSUE THREAD

**Issue by csheaff** [ContinuumIO/anaconda-issues#1628]
Hello,

I cannot seem to create a new environment in Anaconda Navigator from a .yml file generated using conda. I attempt to load it, the progress bar becomes active for a while, then nothing happens. The following is my file contents. Can someone tell me if I am doing anything wrong?

name: myenv
channels:
- defaults
dependencies:
- cycler=0.10.0=py36_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.0=np112py36_0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- openssl=1.0.2k=1
- pandas=0.19.2=np112py36_1
- pcre=8.39=1
- pip=9.0.1=py36_1
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=0
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=3
- readline=6.2=2
- scipy=0.19.0=np112py36_0
- setuptools=27.2.0=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
prefix: /home/me/miniconda3/envs/myenv

**Comment by goanpeca** [comment]
@csheaff could you send the file, or format the text in the github issue correctly?

**Comment by csheaff** [comment]
Apologies. Attached is what is contained in my .yml file (i had to convert to txt to attach).

[requirements.txt](https://github.com/ContinuumIO/anaconda-issues/files/952597/requirements.txt)

**Comment by goanpeca** [comment]
Sure, that will work, let me check and I will get back to you, ok?

**Comment by csheaff** [comment]
yep!

**Comment by goanpeca** [comment]
Ok found the issue, need to issue a fix for it in the coming weeks

**Comment by csheaff** [comment]
That would be great. Also, if this could work with a pip-generated requirements file, it would be much appreciated.

**Comment by goanpeca** [comment]
@csheaff what operating system are you running?

**Comment by csheaff** [comment]
I generated the yml file in Ubuntu 16.04 and am attempting to use it in
Windows 7.

**Comment by goanpeca** [comment]
>I generated the yml file in Ubuntu 16.04 and am attempting to use it in
Windows 7.

That will no work unfortunately as these generated envs are not cross platform

**Comment by csheaff** [comment]
So there is no way to reproduce a virtual environment generated in Linux on
a Windows machine?

**Comment by goanpeca** [comment]
>So there is no way to reproduce a virtual environment generated in Linux on
a Windows machine?

Not at the moment

**Comment by csheaff** [comment]
Can you recommend what tweaks should be implemented? Can I simply remove Linux-specific packages from the list?

**Comment by goanpeca** [comment]
@csheaff remove any pins to builds, so that you have 

```
name: usucd_env
channels:
- conda-forge
- defaults
dependencies:
- cycler=0.10.0
- dbus=1.10.10
- expat=2.1.0
- fontconfig=2.12.1
- freetype=2.5.5
- glib=2.50.2
...
```

Also you need to provide the channels that contain the missing packages as I said before this file will not work on ubuntu, cause some packages are not in defaults.

**Comment by csheaff** [comment]
Okay, thanks Gonzalo. I might try to write a bash script that will do this
for me and post it in the case that it is useful for others.

**Comment by goanpeca** [comment]
@csheaff this cross functionality is under work cause os differences make this a non trivial task, we will get there (hopefully) soon.

pinging @kalefranz

**Comment by kalefranz** [comment]
We should have a ticket as a conda issue to export an environment that drops the build strings. But if we're changing or augmenting this user experience, we should probably do it with a full view of what conda currently is. Sometimes user's might want to keep all per-package channels but drop build strings, for example. With work in conda 4.4, we should start to be able to rebuild environments from the Alecs explicitly requested on the command line by user's. That'll probably eventually be useful here.

**Comment by csheaff** [comment]
I think it would really help with user adoption. I'm currently a Linux +
Python user trying to ween others off of Matlab who predominantly use
Windows. Because of the complexities involving the command line, I believe
that Anaconda Navigator would be really useful for this purpose. But,
perhaps selfishly, I really don't want to have to start using Windows in
order to share an environment. However i imagine that many others are in
the same camp.
