### ISSUE TITLE
Anaconda Navigator does not Initialize Windows 7 EPRs

### ISSUE THREAD

**Issue by CFM90** [ContinuumIO/anaconda-issues#1633]
Hello!
I installed the most recent version of Anaconda and tried to start it on a windows 7 Enterprise SP 1 machine. I have administrator privileges and write privilege for the installation folder. Java 8.91 64bit is installed, there were no installation errors. During installation I checked both options (Add anaconda to the system path.. and register anaconda as the system Python 3.6). 
I right clicked and run as admin, but it does not start the program. It rather freezes when it says "initializing". There is no error message. 
- I am not connetcted to the internet on that machine...
- Does anaconda have any dependencies, which I need to install beforehand?

**Comment by mingwandroid** [comment]
Can you launch the `Anaconda Prompt` from the start menu and then type `anaconda-navigator`. Hopefully it will give some indication of what is going on.

FWIW, I would not recommend adding to PATH, installing as Administrator or installing for All Users. Things work much more smoothly when you don't those things.

**Comment by goanpeca** [comment]
>Can you launch the Anaconda Prompt from the start menu and then type anaconda-navigator. Hopefully it will give some indication of what is going on.

The new version hopefully fixes this lack of information when things go wrong at startup :-|

**Comment by CFM90** [comment]
I tried mingwandroid 's recommendations, it did not work. When launching Anaconda Promt, the same error occures. Reinstalling without checking both boxes did not help ether.

**Comment by mingwandroid** [comment]
> Can you launch the Anaconda Prompt from the start menu and then type anaconda-navigator. Hopefully it will give some indication of what is going on

**Comment by CFM90** [comment]
@mingwandroid:  I tried that already, the same error occures. The green navigator circle shows-up, says initializing and freezes.

**Comment by mingwandroid** [comment]
Was there any text output on the console? Please paste that here.

**Comment by CFM90** [comment]
I found the issue. It takes 15 min. for anaconda to start because it tries to establish an internet connection, but the PC is not connected to the internet. @mingwandroid 's hint to use annaconda prompt helped to identify the issue. Thanks a lot! 
Is there a way to start annaconda without it trying to connect to the internet?

**Comment by mingwandroid** [comment]
@goanpeca?

**Comment by goanpeca** [comment]
@mingwandroid it should actually open with no internet connection and just display locally installed info. 1.6 version fixes definitely annoyances with offline for good

**Comment by goanpeca** [comment]
1.6 to be released in a couple of days
