### ISSUE TITLE
doctuils for python 3.5 seems to be the Python 2 version of docutils.

### ISSUE THREAD

**Issue by moorepants** [ContinuumIO/anaconda-issues#1638]
If I `conda install docutils` in a Python 3.5 environment I get this error on import:

```
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import docutils
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-2b6970339386> in <module>()
----> 1 import docutils

/home/moorepants/src/docutils/docutils/docutils/__init__.py in <module>()
     66 import sys
     67 
---> 68 class ApplicationError(StandardError):
     69     # Workaround:
     70     # In Python < 2.6, unicode(<exception instance>) calls `str` on the

NameError: name 'StandardError' is not defined
```

Seems like the Python 2 version of docutils is installed instead of the Python 3 version.

**Comment by nehaljwani** [comment]
As of writing this comment, there are three different builds of `docutils` on the defaults channel for `python = 3.5` and all of them work correctly for me. 

The error message shown by you indicates that the docutils module is being picked up from `/home/moorepants/src/docutils/docutils/docutils/__init__.py` which doesn't seem to be a place where conda would install `docutils`.  Do you have happen to have the `PYTHONPATH` environment variable set?

**Comment by moorepants** [comment]
Closing because I can't reproduce the error. I may have simply been in that docutils source directory. Thanks for cheking @nehaljwani.
