### ISSUE TITLE
miniconda3 installation in raspberry pi 3

### ISSUE THREAD

**Issue by maanasadi** [ContinuumIO/anaconda-issues#1640]
I am trying to install miniconda3 in rpi3 but after the complete installation i get the following message:

installing: pip-9.0.1-py36_1 ...
installing: wheel-0.29.0-py36_0 ...
./Miniconda3-latest-Linux-x86.sh: line 300: /home/pi/miniconda3/pkgs/python-3.6.0-0/bin/python: cannot execute binary file: Exec format error
ERROR:
cannot execute native linux-32 binary, output from 'uname -a' is:
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

Python 3.4.2 is already installed with raspbian OS.

What should i do?

**Comment by nehaljwani** [comment]
The Raspberry Pi has an ARM CPU and not an x86 CPU. Delete `Miniconda3-latest-Linux-x86.sh` and use https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh
