### ISSUE TITLE
Tensorflow 1.0.1 (or superior) alongside anaconda 4.3 (with numpy 1.11)

### ISSUE THREAD

**Issue by anjos** [ContinuumIO/anaconda-issues#1644]
Just noticed that tensorflow 1.0.1, available through the defaults channel, is only compatible with numpy 1.12. It turns out anaconda 4.3.1 uses numpy 1.11, so installing the latest version of tensorflow alongside anaconda is not currently possible.

Would you be able to roll-out a version of tensorflow that keeps compatibility with anaconda 4.3.1 (i.e. compiled against numpy 1.11)?

**Comment by jjhelmus** [comment]
@anjos I'll look into this.  Tensorflow 1.1.0 has benn released, so packages for the new version are needed anyway.

**Comment by anjos** [comment]
Thanks @jjhelmus looking forward for any input here - we're stuck getting our basic dev env going w/o this.

**Comment by mingwandroid** [comment]
@183amir and @anjos, I'd like to know what's preventing you from moving to numpy 1.12.

**Comment by 183amir** [comment]
@mingwandroid we try to use the `anaconda` package in our dev environment to pin everything down to a stable version but the latest version of anaconda depends on numpy 1.11

**Comment by jjhelmus** [comment]
NumPy 1.11 packages for `caffe` should be possible @183amir.  Can you open a new issue on that topic so it can be tracked separately?

**Comment by jjhelmus** [comment]
Tensorflow `1.1.0` conda packages are now available for the `linux-64` platform.  Packages are available which support both NumPy 1.11 and NumPy 1.12.
