### ISSUE TITLE
Navigator wrapper scripts have wrong slash for Windows

### ISSUE THREAD

**Issue by dadegroot** [ContinuumIO/anaconda-issues#1647]
Environment:

Anaconda Navigator 1.5 from the Anaconda 4.3.1 package (x64)
Windows 10 Edu R1607 Build 14393.1066

Install switches for Anaconda package:  /InstallationType=AllUsers /RegisterPython=1 /S /D=%ProgramFiles%\Anaconda3

Issue:

Clicking Launch on any application in the Navigator creates a batch file for that application in C:\Users\%USERNAME%\.anaconda\navigator\scripts\

The batch file(s) created have the wrong slash character in the paths and as such the applications do not launch.
eg:
C:/Program Files/Anaconda3/Scripts/spyder
instead of what it should be:
C:\Program Files\Anaconda3\Scripts\spyder

**Comment by goanpeca** [comment]
@dadegroot what version of Navigator are you using? 1.5.X  -> X ????

**Comment by dadegroot** [comment]
1.5.2 (upgraded from 1.5.0 when prompted to see if that resolved the issue - it didn't)

**Comment by goanpeca** [comment]
@dadegroot just to confirm, are we talking about launching applications on the home screen? or launching navigator itself, from the menu?

**Comment by dadegroot** [comment]
Yes launching applications from within Navigator.

**Comment by dadegroot** [comment]
Out of interest, I tried Anaconda 4.2.0 (as that's what another dept uses) and it does not have this issue.

**Comment by goanpeca** [comment]
@dadegroot issuing a hot fix for starting next week

**Comment by goanpeca** [comment]
@dadegroot releasing 1.5.3 which fixes this issue. 1.6 is also coming soon which adds several improvements
