### ISSUE TITLE
caffe with numpy 1.11

### ISSUE THREAD

**Issue by 183amir** [ContinuumIO/anaconda-issues#1652]
As it was discussed in #1644, is it possible to have a release of caffe compiled against numpy 1.11 so it is installable against anaconda 4.3.1?

**Comment by jjhelmus** [comment]
NumPy 1.11 support in caffe will be added in the update to version `1.0`.  Need to check into the effort required to build packages for `caffe2` as well.

**Comment by 183amir** [comment]
This is no longer needed since we switched to numpy 1.12.
