### ISSUE TITLE
The lauching of ipython under conda is much slower than the system's ipython.

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1653]
_From @wangg12 on March 11, 2017 9:8_

I consistently found that conda's ipython is slower than the system's ipython, more or less. Sometimes it takes seconds to start, while the system's ipython starts almost instantly. I've tested on several ubuntu machines and mac. What may cause the ipython under conda so slow? Confusing...

_Copied from original issue: conda/conda#4855_

**Comment by wangg12** [comment]
This may be due to my anaconda is installed on HDD, while the system's python is on SSD. After moving anaconda to SSD, the speed improves a lot.

**Comment by csoja** [comment]
@wangg12 Are you ok if we close this issue?

**Comment by wangg12** [comment]
Sure.

**Comment by rbhanot4739** [comment]
Even I am having the same issue. I am running Ubuntu 16.04.3 LTS and using the latest version of Anaconda Python. The Ipython shipped with system launches instantly, however the Ipython3 shipped with Anaconda takes much more time to launch, sometimes even upto 1 minute.

One thing i should mention here is that the system ipython is installed locally and ipython3 installed in my homedir which is on NFS. So could it be the reason for slowness ?

**Comment by ipstone** [comment]
Same experience here - we probably should reopen this issue. I am using conda python 3.6.3 and ipython 6.1.0.
