### ISSUE TITLE
Anaconda Prompt and Navigator - stopped working

### ISSUE THREAD

**Issue by LUKELIEM** [ContinuumIO/anaconda-issues#1657]
I was able to launch both from Window 10 using from Start menu until I performed a "conda install".

Now when I try to launch Anaconda Navigator, nothing happens - not even the Green Circle.

And when I open Anaconda Prompt, it started with "directory name is invalid" and nothing works, not even conda

![anaconda](https://cloud.githubusercontent.com/assets/10457709/25645389/6d2a5070-2f62-11e7-9b81-c0cfac75583a.jpg)

**Comment by kalefranz** [comment]
What version of conda and Anaconda were you previously using?

This is likely the result of conda 4.2 or earlier failing in the middle of an update operation. That behavior has been completely fix in conda 4.3. Unfortunately, to recover your current install, you'll need to download a new miniconda installer and run it overtop your current install. Or just manually delete your old Anaconda directory and download a new miniconda installer.

**Comment by LUKELIEM** [comment]
conda version 4.2.9
Navigator 1.3.1

I ended up uninstalling and reinstalling the latest Anaconda and it seems to fix the problem.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
