### ISSUE TITLE
Damaged installation with conda install in combination with pip install

### ISSUE THREAD

**Issue by ChristianECooper** [ContinuumIO/anaconda-issues#1660]
I've come across an installation problem, where root and derived environments are trashed while updating/installing with pip.

The problem can be replicated on a Linux system as follows:

1. Create an Anaconda installation.
1. Create new conda environment 'working' with a super set of packages in the root environment.  This creates symbolic links rather than reinstallations.
1. Create new conda environment 'bystander' as a duplicate or superset of working's packages.
1. Activate the 'working' environment.
1. Use pip to install a package **that is not in Anaconda but that has dependencies that are present in the root environment but for alternate versions**.

As you would expect, the version of pip used is the one in the 'working' environment.

At this point, pip is not cognisant of the symlinks being symlinks will attempt to uninstall then reinstall dependent packages where the symlinks reference - it will delete the root packages, then build, compile, and install packages directly.

If the user performing these actions is not the user that owns the root environment - then the process will fail due to file system security violations, with the current environment potentially broken.

However, if the user performing these actions is the user that owns the root environment - then the process may not appear to fail, but the all three environments will be damaged regardless of who owns them.

Granted I'm are using an older version of Anaconda: 2.2.0, but I was unable to find any reference to similar problems in the closed bug list, so thought it was worth highlighting in case it is still a problem.

**Comment by caesar** [comment]
This is a fatal flaw in conda for me; it makes it pretty much unusable.

**Comment by chillage** [comment]
Thanks for pinpointing the cause, I just spent an inordinate amount of time debugging this. Can confirm that the issue has not been resolved - as of Anaconda 5.0.0 it's still impossible to use pip with multiple environments

**Comment by msarahan** [comment]
Sorry, this is a known issue with conda and pip not knowing about each other enough.  It is something we want to fix in the short term, but we have no exact timeline for when we'll be able to do it.  PR's to conda are always welcome if you find time and want a faster fix.

**Comment by kiwi0fruit** [comment]
I guess this happen because of pip design: it does not have installation plan. A plain fix would be to add special installation mode to pip - that asks before unistalling/reinstalling during installing deps.

As a hack I made [`pip-resolve` script](https://github.com/kiwi0fruit/misc/tree/master/pip-resolve) that predicts what pip would install.

**Comment by kiwi0fruit** [comment]
Looks like it have been already fixed: https://github.com/AnacondaRecipes/pip-feedstock/pull/1

**Comment by ChristianECooper** [comment]
As an alternative could we have a global option for conda to copy rather than symlink, it would be slower and take up more space, but at least installations would be guaranteeably independent?

**Comment by kiwi0fruit** [comment]
They claim that they fixed pip and now it doesn't mess things up. I tested
it yesterday one time - it for real stopped installation instead of
updating conda package. So I guess we should update pip (that come from
conda), enjoy, and report issues.

вт, 22 мая 2018, 14:42 Chris Cooper <notifications@github.com>:

**Comment by kiwi0fruit** [comment]
I've just encountered behaviour that indicates that this issue id not over:

When having conda cython v0.28.2 and installing a package that depend on higher version of cython: `"cython>=0.28.3"` (or pip installing higher version cython itself) pip uninstalls conda's cython and installs.

I tested on conda's main repo pip v10.0.1 and on conda-forge pip v0.9.3

**Comment by kalefranz** [comment]
@kiwi0fruit see response at https://github.com/conda/conda/issues/6861#issuecomment-393882705

**Comment by kalefranz** [comment]
This issue can be closed following AnacondaRecipes/pip-feedstock#1.
