### ISSUE TITLE
Is there a up-to-date miniconda installer for Linux x86_64?

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1663]
_From @hartzell on April 5, 2017 4:5_

The newest installer [in the repo](https://repo.continuum.io/miniconda/) seems to be for 4.3.11, but I see releases on github up to 4.3.14.

Is there a schedule for an installer?  I can't use the "install 4.3.11 and use conda to update itself" route.

**Thanks!**

_Copied from original issue: conda/conda#5000_

**Comment by kalefranz** [comment]
_From @hartzell on April 18, 2017 18:10_

**ping?**

**Comment by kalefranz** [comment]
_From @mingwandroid on April 18, 2017 18:16_

We do not build a new `Miniconda` (the minimal set of packages needed to run `conda`) for each release on `conda`. Usually we plan to only release on `Miniconda` per release of `Anaconda Distribution` but sometimes issues force us to release `Miniconda` more frequently.

`conda update conda` will get you the latest `conda`.

**Comment by kalefranz** [comment]
_From @hartzell on April 18, 2017 22:29_

[edit for tone]

> We do not build a new Miniconda (the minimal set of packages needed to run conda) for each release on conda.

Is there a technical reason (a place that I could contribute instead of whining) or is it Policy?

> conda update conda will get you the latest conda

Sadly, that's a total non-starter for folks downstream who are trying to package your tools.

I wouldn't care, except that you seem to have fixed a number of problems with running in a multi-user environment between .11 and .14, our users keep tripping over them and complaining.

My shrugging at them isn't a very satisfying response.

**Comment by kalefranz** [comment]
_From @mingwandroid on April 18, 2017 22:48_

> Is there a technical reason (a place that I could contribute instead of whining) or is it Policy?

`Anaconda` and `Miniconda` are rolling software distributions with fixed checkpointed releases (roughly 4 times a year). Those releases take a *significant* amount of time and time to test, time that would otherwise be spent fixing and improving our packages or adding new ones.

> Sadly, that's a total non-starter for folks downstream who are trying to package your tools.

You can package your own installers as and when you wish. We have an open source tool called `constructor` that you can install via `conda install constructor`. You can read the documentation here: https://github.com/conda/constructor

**Comment by kalefranz** [comment]
_From @mingwandroid on April 19, 2017 0:22_

I do have sympathy for your use case around multi user issues by the way. We're not far off the next release though, and that one should have all of those issues put to bed. Pinging @csoja too so that your concern is further noted.

**Comment by kalefranz** [comment]
_From @hartzell on April 19, 2017 1:39_

**Thanks!**

My intuition was that most of the effort invested in ensuring that installing release X and then doing `conda update conda` works reliably overlaps with what you'd do to ensure that an updated installer works.

I'll hold my horses and keep pointing the users at my FAQ about it.

**Comment by kalefranz** [comment]
_From @csoja on April 19, 2017 15:25_

We are planning to release a Miniconda v4.3.14.  We plan to at a minimum release a version of Miniconda with the same version of conda as is found in Anaconda installer releases.  There is quite a bit of extra work required for a Miniconda release - both building the installers and the testing required on all platforms - and as conda patch releases often come out quite frequently, we cannot release Miniconda as often as conda.  However, you have a good argument for increasing the frequency of our Miniconda releases.  Will a Miniconda with conda v4.3.14 version work for you?

**Comment by kalefranz** [comment]
_From @hartzell on April 19, 2017 18:17_

I appreciate (particularly now that I understand it better!) the work you put into the releases.

It's hard for me to discern the release pattern when I look back through the repository, perhaps a useful thing would be to describe the release schedule/policy some where on [the miniconda page](https://conda.io/miniconda.html).  Then everyone's working from the same plan.

> Will a Miniconda with conda v4.3.14 version work for you?

I've done the `conda update conda` process by hand and *believe* that it fixes the issues that I've seen with writability of the shared env/package dirs and interpolation of variables in ~/.condarc files and etc....

I'd be happy to test drive a release candidate if it would be helpful.

**Comment by kalefranz** [comment]
_From @csoja on April 20, 2017 17:33_

Thank you for the offer to help test.  I'll plan to send you a link to it when it is available for testing.

**Comment by csoja** [comment]
@hartzell the release candidates for miniconda v4.3.14 have been uploaded to  https://repo.continuum.io/pkgs/misc/preview/  if you'd like to take it for a spin.  We should be able to include it in the main channel for miniconda installers next week.

**Comment by hartzell** [comment]
@csoja -- Thanks.  Will test drive it today/tomorrow!

**Comment by hartzell** [comment]
Looks like I missed my window to test drive these, but I see them at https://repo.continuum.io/miniconda/ since 2016-05-12.

I'll update the Spack packages ([miniconda2](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/miniconda2/package.py) and [miniconda3](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/miniconda3/package.py)).

**THANKS!**
