### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kd2ac** [ContinuumIO/anaconda-issues#1669]
Application action error

/Users/khanhdang/anaconda/bin/python /Users/khanhdang/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/khanhdang/anaconda spyder=3.1.4: The following specifications were found to be in conflict:
  - spyder 3.1.4*
  - spyder-app -> python 2.7*|3.4*
  - spyder-app -> spyder 2.2.0|2.2.4|2.2.5|2.3.0|2.3.0rc1|2.3.1|2.3.2|2.3.3|2.3.4|2.3.5.2|2.3.6|2.3.7|2.3.8
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'version': '1.2.2', 'conda': '4.1.11', 'python': '3.5.1', 'os': 'Darwin;14.5.0;Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64;x86_64;i386', 'qt': '4.8.7', 'platform': 'osx-64', 'language': 'en'}

**Comment by kalefranz** [comment]
@goanpeca where's the public issue tracker for Navi?

**Comment by goanpeca** [comment]
This one is :-)

**Comment by goanpeca** [comment]
@kd2ac you are using a very old version of Navigator, could you please update to the latest version and try again?

On the terminal you can install it by doing

`conda install anaconda-navigator=1.5.2`
