### ISSUE TITLE
Install without tk

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1670]
_From @anderson-dan-w on February 14, 2017 17:33_

I want to be able to create a conda environment, specifically a python environment, without tk - that's a dependency I don't need (and is unnecessary when my code will eventually run on a headless server). However, if I try `conda remove tk` it also removes `pip, python, setuptools, wheel`. And if I then try to re-install, say, `pip`, it forces me to reinstall `tk` again. I don't need or want GUI support.

Any way around this?

Thanks 

_Copied from original issue: conda/conda#4632_

**Comment by kalefranz** [comment]
I just talked with @ilanschnell about this.  We're working through how to just completely drop `tk` as a dependency from conda's python packages...  You're not the first person who has wanted a solution here.

**Comment by kalefranz** [comment]
@csoja I don't know if this is in scope for Anaconda 4.4, but it's something @ilanschnell and I both would like to do.  Perhaps we should put it on the priority list for after 4.4 is released.

**Comment by mingwandroid** [comment]
I don't get why you'd go against upstream CPython so radically here. What is the benefit?

**Comment by bryevdv** [comment]
I don't see the value either. If someone doesn't need tk they can just ignore it. It might be different if tk was difficult to install but that's precisely not the case here.

**Comment by mbargull** [comment]
Try to `conda update -yn base conda && conda update -yn base --all` before running `conda clean`. Reason: A fresh Miniconda installation uses packages provided by the installer which are often older than those that get installed into the environment you created. If you update those, it's likely that the `base` environment and your `pip` environment share the same packages, hence those duplicates will be removed by `conda clean -tpy`.

**Comment by buhrmann** [comment]
Ah, great. Many thanks! I'll give that a try right now.
