### ISSUE TITLE
Unable to import matplotlib.pyplot

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1672]
_From @dipanarya on February 10, 2017 15:12_

I am unable to import Mataplotlib on anaconda environment.please find below code snippet.

C:\Users\Dipan Arya\Desktop\uda\dnd\DLND-your-first-network>conda create --name
 dlnd1  matplotlib python=3 ipython=3 numpy pandas jupyter notebook pyzmq
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3\envs\dlnd1
:

The following NEW packages will be INSTALLED:

    cycler:           0.10.0-py35_0
    decorator:        4.0.11-py35_0
    entrypoints:      0.2.2-py35_0
    icu:              57.1-vc14_0        [vc14]
    ipykernel:        4.1.1-py35_0
    ipython:          3.2.3-py35_0
    ipython_genutils: 0.1.0-py35_0
    ipywidgets:       4.1.1-py35_0
    jinja2:           2.9.4-py35_0
    jpeg:             9b-vc14_0          [vc14]
    jsonschema:       2.5.1-py35_0
    jupyter:          1.0.0-py35_3
    jupyter_client:   4.4.0-py35_0
    jupyter_console:  5.0.0-py35_0
    jupyter_core:     4.2.1-py35_0
    libpng:           1.6.27-vc14_0      [vc14]
    markupsafe:       0.23-py35_2
    matplotlib:       2.0.0-np111py35_0
    mistune:          0.7.3-py35_0
    mkl:              2017.0.1-0
    nbconvert:        4.2.0-py35_0
    nbformat:         4.2.0-py35_0
    notebook:         4.3.1-py35_1
    numpy:            1.11.3-py35_0
    openssl:          1.0.2k-vc14_0      [vc14]
    pandas:           0.19.2-np111py35_1
    pip:              9.0.1-py35_1
    prompt_toolkit:   1.0.9-py35_0
    pygments:         2.1.3-py35_0
    pyparsing:        2.1.4-py35_0
    pyqt:             5.6.0-py35_2
    pyreadline:       2.1-py35_0
    python:           3.5.2-0
    python-dateutil:  2.6.0-py35_0
    pytz:             2016.10-py35_0
    pyzmq:            16.0.2-py35_0
    qt:               5.6.2-vc14_3       [vc14]
    qtconsole:        4.2.1-py35_2
    setuptools:       27.2.0-py35_1
    sip:              4.18-py35_0
    six:              1.10.0-py35_0
    tk:               8.5.18-vc14_0      [vc14]
    tornado:          4.4.2-py35_0
    traitlets:        4.3.1-py35_0
    vs2015_runtime:   14.0.25123-0
    wcwidth:          0.1.7-py35_0
    wheel:            0.29.0-py35_0
    zlib:             1.2.8-vc14_3       [vc14]

Proceed ([y]/n)? y

python-3.5.2-0 100% |###############################| Time: 0:00:49 614.58 kB/s
decorator-4.0. 100% |###############################| Time: 0:00:00 659.01 kB/s
entrypoints-0. 100% |###############################| Time: 0:00:00   1.52 MB/s
ipython_genuti 100% |###############################| Time: 0:00:00 540.08 kB/s
jsonschema-2.5 100% |###############################| Time: 0:00:00 739.20 kB/s
markupsafe-0.2 100% |###############################| Time: 0:00:00 849.47 kB/s
mistune-0.7.3- 100% |###############################| Time: 0:00:01  95.48 kB/s
numpy-1.11.3-p 100% |###############################| Time: 0:00:05 635.87 kB/s
pygments-2.1.3 100% |###############################| Time: 0:00:02 491.18 kB/s
pyparsing-2.1. 100% |###############################| Time: 0:00:00 536.00 kB/s
pyreadline-2.1 100% |###############################| Time: 0:00:01  36.19 kB/s
pytz-2016.10-p 100% |###############################| Time: 0:00:00 690.74 kB/s
pyzmq-16.0.2-p 100% |###############################| Time: 0:00:00 685.00 kB/s
setuptools-27. 100% |###############################| Time: 0:00:01 661.07 kB/s
sip-4.18-py35_ 100% |###############################| Time: 0:00:01 144.80 kB/s
six-1.10.0-py3 100% |###############################| Time: 0:00:00   2.04 MB/s
tornado-4.4.2- 100% |###############################| Time: 0:00:00 692.38 kB/s
wcwidth-0.1.7- 100% |###############################| Time: 0:00:00  89.00 kB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00 694.12 kB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00   1.23 MB/s
ipython-3.2.3- 100% |###############################| Time: 0:00:07 521.42 kB/s
jinja2-2.9.4-p 100% |###############################| Time: 0:00:00 670.60 kB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:02 635.96 kB/s
prompt_toolkit 100% |###############################| Time: 0:00:00 671.95 kB/s
python-dateuti 100% |###############################| Time: 0:00:00 748.59 kB/s
traitlets-4.3. 100% |###############################| Time: 0:00:00 760.60 kB/s
jupyter_core-4 100% |###############################| Time: 0:00:00 861.70 kB/s
pandas-0.19.2- 100% |###############################| Time: 0:00:11 618.11 kB/s
pyqt-5.6.0-py3 100% |###############################| Time: 0:00:05 630.67 kB/s
jupyter_client 100% |###############################| Time: 0:00:01 118.21 kB/s
matplotlib-2.0 100% |###############################| Time: 0:00:15 592.41 kB/s
nbformat-4.2.0 100% |###############################| Time: 0:00:00 719.97 kB/s
ipykernel-4.1. 100% |###############################| Time: 0:00:00  62.16 kB/s
nbconvert-4.2. 100% |###############################| Time: 0:00:01 197.22 kB/s
jupyter_consol 100% |###############################| Time: 0:00:00   1.05 MB/s
notebook-4.3.1 100% |###############################| Time: 0:00:09 580.39 kB/s
qtconsole-4.2. 100% |###############################| Time: 0:00:01 121.63 kB/s
ipywidgets-4.1 100% |###############################| Time: 0:00:01  88.30 kB/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00 889.99 kB/s
#
# To activate this environment, use:
# > activate dlnd1
#
# To deactivate this environment, use:
# > deactivate dlnd1
#
# * for power-users using bash, you must source
#

C:\Users\Dipan Arya\Desktop\uda\dnd\DLND-your-first-network>activate dlnd1

(dlnd1) C:\Users\Dipan Arya\Desktop\uda\dnd\DLND-your-first-network>ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:45:57) [MSC v
.1900 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 3.2.3 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6f467123fe04> in <module>()
----> 1 import matplotlib.pyplot

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\pyplot.py in <m
odule>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\colorbar.py in
<module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\contour.py in <
module>()
     21 import matplotlib.collections as mcoll
     22 import matplotlib.font_manager as font_manager
---> 23 import matplotlib.text as text
     24 import matplotlib.cbook as cbook
     25 import matplotlib.mlab as mlab

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\text.py in <mod
ule>()
     31 from matplotlib.artist import allow_rasterization
     32
---> 33 from matplotlib.backend_bases import RendererBase
     34 from matplotlib.textpath import TextPath
     35

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\backend_bases.p
y in <module>()
     61
     62 import matplotlib.tight_bbox as tight_bbox
---> 63 import matplotlib.textpath as textpath
     64 from matplotlib.path import Path
     65 from matplotlib.cbook import mplDeprecation, warn_deprecated

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\textpath.py in
<module>()
     18 from matplotlib.ft2font import KERNING_DEFAULT, LOAD_NO_HINTING
     19 from matplotlib.ft2font import LOAD_TARGET_LIGHT
---> 20 from matplotlib.mathtext import MathTextParser
     21 import matplotlib.dviread as dviread
     22 from matplotlib.font_manager import FontProperties, get_font

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\mathtext.py in
<module>()
     60
     61 import matplotlib.colors as mcolors
---> 62 import matplotlib._png as _png
     63
     64 ####################

ImportError: DLL load failed: The specified procedure could not be found.

In [2]: import matplotlib

In [3]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-6f467123fe04> in <module>()
----> 1 import matplotlib.pyplot

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\pyplot.py in <m
odule>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\colorbar.py in
<module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\contour.py in <
module>()
     21 import matplotlib.collections as mcoll
     22 import matplotlib.font_manager as font_manager
---> 23 import matplotlib.text as text
     24 import matplotlib.cbook as cbook
     25 import matplotlib.mlab as mlab

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\text.py in <mod
ule>()
     31 from matplotlib.artist import allow_rasterization
     32
---> 33 from matplotlib.backend_bases import RendererBase
     34 from matplotlib.textpath import TextPath
     35

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\backend_bases.p
y in <module>()
     61
     62 import matplotlib.tight_bbox as tight_bbox
---> 63 import matplotlib.textpath as textpath
     64 from matplotlib.path import Path
     65 from matplotlib.cbook import mplDeprecation, warn_deprecated

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\textpath.py in
<module>()
     18 from matplotlib.ft2font import KERNING_DEFAULT, LOAD_NO_HINTING
     19 from matplotlib.ft2font import LOAD_TARGET_LIGHT
---> 20 from matplotlib.mathtext import MathTextParser
     21 import matplotlib.dviread as dviread
     22 from matplotlib.font_manager import FontProperties, get_font

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\mathtext.py in
<module>()
     60
     61 import matplotlib.colors as mcolors
---> 62 import matplotlib._png as _png
     63
     64 ####################

ImportError: DLL load failed: The specified procedure could not be found.

In [4]:

_Copied from original issue: conda/conda#4595_

**Comment by kalefranz** [comment]
_From @dipanarya on February 10, 2017 15:15_

@msarahan  can you please help on the above issue.i checked the other related issues but didn't work.
Please provide your valuable inputs.

i reset environment variable also.please find details below:
"C:\ProgramData\Anaconda3\Library\bin"

**Comment by kalefranz** [comment]
_From @abalter on February 11, 2017 1:35_

Question: are you working on a remote machine? Some Matplotlib packages will cause a poorly reported error if there is no X connection. 

http://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv

http://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server

**Comment by cbcoutinho** [comment]
I'm unable to use matplotlib.pyplot on a fresh install of anaconda python 3.5 or 3.6 on Windows 10. Issuing the following command:

```python -c 'import matplotlib.pyplot```

results in the following error:

```
python : Traceback (most recent call last):
At line:1 char:1
+ python -c 'import matplotlib.pyplot' 2> error.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "<string>", line 1, in <module>
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 29, in <modu
le>
    import matplotlib.colorbar
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 36, in <mo
dule>
    import matplotlib.contour as contour
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\contour.py", line 21, in <mod
ule>
    import matplotlib.font_manager as font_manager
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 58, in
 <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.
```

I've searched around (conda/conda/issues/4595, #540), and this issue doesn't seem to have been resolved - or I'm at a loss and have been missing it.

**Comment by msarahan** [comment]
@cbcoutinho it looks like you are using powershell.  Our activate scripts don't currently support that, and without them, you really shouldn't trust that you have correct environment variables set.

You should stick to using the "Anaconda Prompt" on windows.  Adding powershell support is soemthing we'd like to do, but we don't have a definite timeline for it.

**Comment by cbcoutinho** [comment]
Hi @msarahan, thanks for the quick reply.

Using the anaconda prompt doesn't seem to help. Here's the same command as above executed in the anaconda prompt as you suggested:

```
$ python -c "import matplotlib.pyplot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\contour.py", line 22, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.
```

Seems like there is a path issue at work here. Allow me to add some context here - this is a Windows 10 laptop for work where the 'home' variable is actually a different directory than what is normally expected. What I mean by that is that I think home is usually expected to be something like `C:\Users\user\`; however, on this machine the home directory is actually on a network drive somewhere: `H:\`.

Anaconda is installed under `C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3`, but that's different that home. Would that make a difference?

Also, where is the .matplotlibrc file located on windows? I'm unable to find it

**Comment by cbcoutinho** [comment]
I get some additional output when attempting to import `matplotlib.pyplot` in ipython using the Anaconda prompt:

```
(C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3) C:\Users\ccoutinho\Documents>ipython
Python 3.5.4 |Anaconda custom (64-bit)| (default, Nov  8 2017, 14:34:30) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6f467123fe04> in <module>()
----> 1 import matplotlib.pyplot

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\pyplot.py in <module>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\colorbar.py in <module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\contour.py in <module>()
     19 import matplotlib.colors as colors
     20 import matplotlib.collections as mcoll
---> 21 import matplotlib.font_manager as font_manager
     22 import matplotlib.text as text
     23 import matplotlib.cbook as cbook

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\font_manager.py in <module>()
     56
     57 import matplotlib
---> 58 from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
     59 from matplotlib.compat import subprocess
     60 from matplotlib.fontconfig_pattern import (

ImportError: DLL load failed: The specified procedure could not be found.

In [2]:
```

Any way to go further with this?

**Comment by msarahan** [comment]
The most likely culprit here is that you have DLLs that are being loaded preferentially before Anaconda's DLLs.  Those DLLs seem to be incompatible with the ones that Anaconda uses.  The most common way that this happens is when other programs install things into C:\Windows\System32.

Unfortunately, there's nothing we can do on the Anaconda side to overcome this issue - you need to clean up whatever DLL files are interfering.  There's more info on how Windows finds DLL files at https://msdn.microsoft.com/en-us/library/7d83bc18.aspx

This particular one looks like freetype2.  Fortunately that has few possible dependencies to find.  Look for png, zlib, or freetype/ft2 DLLs.

Dependency Walker may also be useful tool to show which libraries are getting picked up: http://www.dependencywalker.com/

**Comment by cbcoutinho** [comment]
You're right about the freetype/ft2 issue @msarahan, I was able to isolate the error message to specifically that import:

```bash
$ python -c 'from matplotlib import ft2font'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

I'll try uninstalling and re-installing.

**Comment by jsh9** [comment]
I had the identical issue as @cbcoutinho . Freshly installed Anaconda 5.0.1 (python 3) on Windows 10 (64-bit), and saw that identical DLL error when `from matplotlib import ft2font`.

However, fortunately for me, I uninstalled the whole Anaconda software from Windows' control panel, rebooted, and reinstalled it, and it worked.

I feel that there could be some solution on the OS level done by the Anaconda Windows binary installer...

**Comment by mingwandroid** [comment]
Given that we can not reproduce this we can not do very much about it. Also
the installer should do absolutely nothing to the users system outside of
the install directory imho. Yes we write to the registry if you select to
register Python and change path if you select that unrecommended option but
there's no way we should go deleting files we did not create, breaking
other software. We could warn and advise if we detect such problems but
while we cannot reproduce it we cannot implement this warning.

On Nov 18, 2017 9:20 AM, "Jian Shi" <notifications@github.com> wrote:

I had the identical issue as @cbcoutinho <https://github.com/cbcoutinho> .
Freshly installed Anaconda 5.0.1 (python 3) on Windows 10 (64-bit), and saw
that identical DLL error when from matplotlib import ft2font.

However, fortunately for me, I uninstalled the whole Anaconda software from
Windows' control panel, rebooted, and reinstalled it, and it worked.

I feel that there could be some solution on the OS level done by the
Anaconda Windows binary installer...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ContinuumIO/anaconda-issues/issues/1672#issuecomment-345429833>,
or mute the thread

**Comment by jsh9** [comment]
Would it be beneficial if you guys talk to the developers of matplotlib? Even though this error is not always reproducible, there are still error messages for diagnosing.

**Comment by jsh9** [comment]
@mingwandroid 
Hi, I think I found the issue that caused this DLL crash. It was from installing CNTK on Anaconda 3.

I reported this issue on CNTK, just FYI: https://github.com/Microsoft/CNTK/issues/2654

**Comment by erikhaverkamp** [comment]
Hi, I am facing the exact same issue on Windows10, Anaconda 5.0.1. Any working solutions?

**Comment by cbcoutinho** [comment]
I am still having this issue, and I haven't gotten around to posting an
issue with the matplotlib developers.

I also unfortunately don't use CNTK, so I don't think that is the issue -
at least for me.

**Comment by mingwandroid** [comment]
Please open a normal (i.e. non `Anaconda Prompt`) `cmd.exe` prompt and type:

```
where freetype.dll
where zlib.dll
where ft2font.pyd
```

**Comment by mingwandroid** [comment]
I can almost guarantee that `where zlib.dll` will show `C:\Windows\System32\zlib.dll`

**Comment by cbcoutinho** [comment]
I just executed the three commands on my machine that's affected by this bug, and it can't find either the `freetype.dll` file or the `ft2font.pyd` file.

The `zlib.dll` file was indeed where you expected it to be, namely in `C:\Windows\System32\zlib.dll`

**Comment by mingwandroid** [comment]
OK you are suffering from the worst form of DLL hell which is where inconsiderate software vendors put themselves to the front of the DLL search queue by installing their non-system software in `C:\Windows\System32` (only MS and 3rd party driver installs should be installing things in there).

You need to find out what this software is (date stamps on the file may provide a hint) and report it to them. If you do not need this software you may be able to delete the dll (and maybe any that are from the same vendor).

However, messing around with files in `C:\Windows\System32` is not something to do lightly (which is precisely why no software vendor should ever install a DLL in there). We can take no responsibility if anything goes wrong from deleting this file / these files. Renaming them first may be a good idea, then seeing if things still work ok.

**Comment by cbcoutinho** [comment]
Some good news and bad news:

Renaming the file from `zlib.dll` to `zlib_.dll` now allows me to successfully use `matplotlib` and produce plots with `pyplot`.

Unfortunately the zlib library was installed sometime last march, which is also when I installed a fresh copy of Windows 10 on the machine. That means determining the 'depender' of `zlib.dll` in my case will prove challenging. For now this workaround seems to have solved my problem.

Thanks for articulating the problem @mingwandroid.

**Comment by mingwandroid** [comment]
I am going to close this issue. It's a problem the user machine and not something we are in control of or responsible for.

**Comment by drcrook1** [comment]
Rats, I'm having this same problem as well...

**Comment by erfannoury** [comment]
This is what I did that solved the problem (I know that it's not a good solution, but it works for now).
I first uninstalled the package using `conda uninstall matplotlib`. Then I ran `conda clean --all` to remove every thing that might remain from the installation of matplotlib using conda. Finally I installed matplotlib using pip, i.e. `pip install matplotlib`. After this I could run the matplotlib once again.
P.S. I installed scikit-image using pip, too.

**Comment by shashank6** [comment]
The solution for the problem can be resolved as what @erfannoury said but make sure you don't have a double image of the same package installed i.e, once using conda and once using pip it will lead to conflicts.

If you have prior knowledge in it you would know but if you are a newbie then the above mentioned suggestion will help you.

**Comment by vvkdby** [comment]
On my system (Win 10, Python 3.6), this was caused because I installed HDF5. 
I found this out using @mingwandroid 's suggestion(Thank you !):  
```
where zlib.dll
C:\Program Files\HDF_Group\HDF5\1.8.20\bin\zlib.dll
C:\Users\vivekd\AppData\Local\Continuum\anaconda3\Library\bin\zlib.dll
```

On uninstalling HDF5, this issue went away :)

**Comment by mingwandroid** [comment]
@vvkdby you also had the option to use the `Anaconda Prompt` or `Anaconda Navigator` instead of relying on the order things appear on `PATH`.

That is the recommended approach in fact.

**Comment by IIyDeJIb** [comment]
Here is a simple solution I figured for myself. I am using Pythin 3.7 on Windows 7.

Simply go to the Environment Variables (Win + Pause), open the Path variable and move the ..\DLLs python path into the very beginning of the string.

Example:

Before:
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft VS Code\bin;%PY_HOME%;%PY_HOME%\Lib;**%PY_HOME%\DLLs**;%PY_HOME%\Lib\lib-tk

Now:
**%PY_HOME%\DLLs**;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft VS Code\bin;%PY_HOME%;%PY_HOME%\Lib;%PY_HOME%\Lib\lib-tk

Reading about that error having to do with some conflict with other DLLs in the system, I figured why not to try move the DLLs directory into the beginning of the path and let it load first, possibly overriding the conflicting DLLs. It worked.

**Comment by parvaneh9492** [comment]
Hi, sorry I know that this issue is closed! but I found too many people who they have this problem still.
it is all about your project path !
open your cmd, **copy your project path** **which there is Scripts file** and change your cmd path to it, for example, type in your cmd:
cd C:\Users\...\PycharmProjects\mltest1\venv\Scripts
 then type:
pip install matplotlib

I installed both pandas and matplotlib with this way!
I hope it will be useful
Best Regards
