### ISSUE TITLE
Runtime error: C libraries

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1679]
_From @karoush on March 15, 2017 21:0_

Everytime I try to open Anaconda Navigator, I get the error below. I have re-installed both Anaconda and Microsoft's C++ distribution. How do I resolve this issue?
![image](https://cloud.githubusercontent.com/assets/13799010/23970614/c24f3d1e-09a0-11e7-9704-dc75d89bbb5d.png)

_Copied from original issue: conda/conda#4883_

**Comment by kalefranz** [comment]
_From @mingwandroid on March 15, 2017 21:9_

This is a *very* strange error.

Can you try the suggestions at: https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/windows-10-settings-window-link-errors-in-some/af24a3dd-3634-4a67-96e4-a3054f2c5736

**Comment by kalefranz** [comment]
_From @karoush on March 15, 2017 21:51_

I did try it. Of note, I am running windows 7- though I'm not sure if it makes a difference

**Comment by kalefranz** [comment]
_From @karoush on March 15, 2017 21:54_

I also have the same issue with miniconda. Running a version check pulls the following issue:
![image](https://cloud.githubusercontent.com/assets/13799010/23972491/601c8b26-09a8-11e7-97a8-31e60636a103.png)
![image](https://cloud.githubusercontent.com/assets/13799010/23972502/6b8ed9d2-09a8-11e7-8e5e-99883043a153.png)

**Comment by kalefranz** [comment]
_From @mingwandroid on March 15, 2017 21:59_

From the `Anaconda Prompt`, please show the output from:

```
echo %PATH%
where python
python --version
```

**Comment by kalefranz** [comment]
_From @karoush on March 15, 2017 22:30_

Here is the output:
![image](https://cloud.githubusercontent.com/assets/13799010/23973646/69b62e94-09ad-11e7-81e3-eadae4d749f1.png)

**Comment by kalefranz** [comment]
_From @mingwandroid on March 15, 2017 22:55_

This is a mismatch between Anaconda and your system Python.

Please use the Anaconda Prompt to launch your command shell and repeat these commands. Also try launching Anaconda Navigator from that.

**Comment by kalefranz** [comment]
_From @karoush on March 15, 2017 23:15_

When I open Anaconda Prompt, I get the runtime error message. Clicking ok eventually allows me to input commands producing the image in my last post.
![image](https://cloud.githubusercontent.com/assets/13799010/23974792/825d526e-09b3-11e7-9254-a0c6671dde71.png)
Attempting to launch navigator from prompt produces the same error.

**Comment by kalefranz** [comment]
_From @karoush on March 15, 2017 23:16_

After repeatedly hitting ok after the initial navigator launch attempt, this is what is outputted
![image](https://cloud.githubusercontent.com/assets/13799010/23974851/ea6dbdbc-09b3-11e7-8407-01019971e873.png)

**Comment by EntPyle** [comment]
Was a solution to this ever found? I'm encountering the same issue with miniconda and this post does not contain a resolution.

**Comment by MANiCURE9** [comment]
after i use `conda install conda`, I receive the same warning

**Comment by EntPyle** [comment]
I did some troubleshooting and discovered what caused my particular issue. I had updated conda specifically in my base environment, and NOT in my created environments. As soon as I updated conda in my other environments as well, the error stopped occurring and everything behaved as expected.
