### ISSUE TITLE
python package doesn't provide test package

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#168]
Some third-party packages (such as my own pathlib) can import `test.test_support` for their own test suite:

```
$ python
Python 2.6.9 |Continuum Analytics, Inc.| (unknown, Aug 21 2014, 18:28:52) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import test.test_support
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named test.test_support
```

Note that it's provided in e.g. the default Ubuntu install for Python.

**Comment by pmarks** [comment]
ping -- I'm facing this issue as well. In particular it prevents one from installing the pdb-clone

**Comment by handong1587** [comment]
@pmarks You are right. I found I cannot install pdb-clone. Do you have any suggestion?

**Comment by handong1587** [comment]
I commented the code "from test import test_support as support" in pdb-clone-1.10/setup.py, seems like  I can resume the installation correctly.

**Comment by loeiten** [comment]
@handong1587 Same problem here, also found that simply copying the ```test``` directory from ```Python-3.5.0/Lib/``` in ```Python-3.5.0.tar.xz``` to ```anaconda3/lib/python3.5``` worked.
