### ISSUE TITLE
Anaconda launcher disappeared after windows 10 anniversary update

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1682]
_From @alpha36turn on October 5, 2016 19:19_

Hi,

I lost the launcher and icons for Jupyter and other apps in Anaconda after the update.  I've tried Mohit's solution: 
"C:\Anaconda3\pythonw.exe" "C:\Anaconda3\Lib_nsis.py" mkmenus 
https://github.com/conda/conda/issues/1558

but got the following error:

C:\Users\alpha\Anaconda3\Lib>_nsis.py
Traceback (most recent call last):
  File "C:\Users\alpha\Anaconda3\Lib_nsis.py", line 117, in <module>
    main()
  File "C:\Users\alpha\Anaconda3\Lib_nsis.py", line 101, in main
    cmd = sys.argv[1].strip()
IndexError: list index out of range

Has anyone found a workaround to this?

Thanks!

_Copied from original issue: conda/conda#3582_

**Comment by goanpeca** [comment]
@alpha36turn  Launcher is deprecated at the moment. 

Did you mean Anaconda Navigator? To install the latest version you can from the **Anaconda Command Prompt**

`conda install anaconda-navigator=1.5.2`

Do you still experience this issue?
