### ISSUE TITLE
python.exe crashes while using QComboBox in pyQt GUI from a Miniconda install

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1683]
_From @PertuyF on September 23, 2016 15:42_

I am using `miniconda3 4.1.11` (reinstalled with `python 3.4`) to deploy a python software to windows users.

When I launch the GUI from the miniconda install everything works except that triggering a `QComboBox` will crash `python.exe`.

I tried several install options including the fully portable one (NoRegistry=1, InstallationType=JustMe, AddToPath=0, RegisterPython=0) and it produces the same result.

By contrast, when I use a `WinPython 64-bit python 3.4.4.3` expurgated from all unnecessary packages (basically I reduced it to the same list as my miniconda install) I do not get this bug.
The GUI works perfectly well with my main anaconda install (`python 3.4` too).

Any clue on what's the cause?

_Copied from original issue: conda/conda#3501_

**Comment by goanpeca** [comment]
@PertuyF this is an old issue and since then we only support 3.5 and 3.6. There were some issues with Qt and Python 3.4 but they are not present (in theory) on 3.5/3.6

Is this something that still affects your system?

**Comment by PertuyF** [comment]
@goanpeca when I met this problem I was planning to use miniconda to deploy an application, but I ended up using another python distribution because of this issue. But as you said, this is an old issue, since then I am not working on this project anymore, therefore I cannot test things on Python 3.5 or 3.6.
