### ISSUE TITLE
Futurize, Pasteurize scripts not installed

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1685]
_From @woodscn on September 10, 2015 15:54_

When using conda to install the future package, the futurize, pasteurize scripts are not installed, as they are when using pip.

_Copied from original issue: conda/conda#1593_

**Comment by nehaljwani** [comment]
It seems to work for `future >= 0.16.0` . Fixed by https://github.com/ContinuumIO/anaconda-recipes/commit/3524d6a9b238a9025660e349ce258213f36d9a05

```bash
(root) bash-4.1# conda create -yn testing_future future
(root) bash-4.1# source activate testing_future
(testing_future) bash-4.1# which futurize
/conda/envs/testing_future/bin/futurize
(testing_future) bash-4.1# which pasteurize
/conda/envs/testing_future/bin/pasteurize
```
