### ISSUE TITLE
import matplotlib.pylab results in "Illegal instruction: 4"

### ISSUE THREAD

**Issue by NewNork** [ContinuumIO/anaconda-issues#1696]
Running an up-to-date version of anaconda (Downloaded installer fro Python3.6, then `conda update --all`)

An `import matplotlib.pyplot` or `import matplotlib.pylab` crashes Python with a "Illegal instruction: 4"

Mac OS version: 10.12.4

**Comment by remkade** [comment]
This appears to be fixed now. I'll go ahead and close it, but please reopen if it is still causing problems!
