### ISSUE TITLE
anaconda-navigator crashes after `conda update --all`

### ISSUE THREAD

**Issue by striatum** [ContinuumIO/anaconda-issues#1698]
I am using the latest Mac OSX on MacBook Air, and Python 3.5.3 (Continuum Analytics, Inc.). After `conda update --all` `anaconda-navigator` crashes. From the command line I am copying in last relevant lines:

> File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 418, in convert_image
> extension = path.split('.')[-1].upper()
> AttributeError: 'NoneType' object has no attribute 'split'
> Abort trap: 6

`conda info` output is:

[conda_info.txt](https://github.com/ContinuumIO/anaconda-issues/files/981834/conda_info.txt)

`conda list` output is:

[conda_list.txt](https://github.com/ContinuumIO/anaconda-issues/files/981835/conda_list.txt)

**Comment by striatum** [comment]
I was wondering whether I would need to do a clean install of the latest build?

**Comment by goanpeca** [comment]
@striatum could you update the latest navigator?

There are some issues with your current install based on `conda_list.txt`

```
...
anaconda-navigator        1.2.3                    py35_0  
...
pyqt                      4.11.4                   py35_4  
PyQt5                     5.8.1                     <pip>
...
qt                        4.8.7                         4  
```

**Comment by mqclark** [comment]
I too am having this problem. I tried the above suggestions but to no avail. From the little experience I have I think there is a problem with different versions of qt? I installed anaconda a while back for a course, now I am trying to use it (after update) for research. Thanks @goanpeca for any assistance or guidance you may be able to provide!
[Terminal Saved Output -not fixed.pdf](https://github.com/ContinuumIO/anaconda-issues/files/1845790/Terminal.Saved.Output.-not.fixed.pdf)
[anaconda crash report.pdf](https://github.com/ContinuumIO/anaconda-issues/files/1845791/anaconda.crash.report.pdf)
