### ISSUE TITLE
pyside-uic

### ISSUE THREAD

**Issue by Nodd** [ContinuumIO/anaconda-issues#170]
I have anaconda v2.0.1, pyside v1.2.1 on Linux. I can't find the `pyside-uic script` needed to compile .ui qt files into .py. Using `find . -name "*uic*"` finds (amongst other things) the qt `uic` program and  `pyuic4` from qt, but nothing for pyside.

**Comment by ccordoba12** [comment]
PySide is not supported anymore. But now `pyuic` is part of the PyQt4 packages on all platforms :-)
