### ISSUE TITLE
ipython package does not install iptest

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1703]
_From @janschulz on October 8, 2015 10:20_

The latest version of the ipython conda packages does not install the iptest binary. This is needed to test ipython extensions :-( Is there a way to install it with conda?

_Copied from original issue: conda/conda#1690_

**Comment by nehaljwani** [comment]
@janschulz [`iptest.py`](http://ipython.readthedocs.io/en/stable/api/generated/IPython.testing.iptest.html) is present as a module within the `ipython` package. You can use it directly, like this:
```bash
(root) ➜  ~ conda create -yn iptest python=3 ipython nose testpath
(root) ➜  ~ source activate iptest
(iptest) ➜  ~ python $CONDA_PREFIX/lib/python3.6/site-packages/IPython/testing/iptest.py -vvs IPython
```

**Comment by janschulz** [comment]
This can be closed, I don't remember why I wanted this and the projects where it might be useful have all solved that issue.
