### ISSUE TITLE
Anacoda Navigator unable to install or upgrade packages

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1707]
_From @gabrif7 on February 24, 2017 15:37_

Hello everyone,

When I try to Install packages or to upgrade already installed packages, after some processes and elaboration, nothing happened and the libraries result not installed or upgraded.

I am using Anaconda Navigator 1.4.3 and the software is installed in C:\ProgramData\Anaconda3.
Python version 3.6
Unfortunately I haven't found similar issues online.

Gabriele

_Copied from original issue: conda/conda#4725_

**Comment by goanpeca** [comment]
@gabrif7

Could you please update to the latest version of anaconda navigator?

`conda install anaconda-navigator=1.5.2`

It seems you are using an "all users" install instead of the "current user only" install. Any particular reason for doing that? We advice to use the current user install.

**Comment by nikhila912** [comment]
hey, how do you shift from 'all users' to 'current user only'?I'm trying to install packages but not able to do so.

**Comment by chandanchinta** [comment]
> hey, how do you shift from 'all users' to 'current user only'?I'm trying to install packages but not able to do so.

There is a option while installing. After the installing I don't think we have to option to shift. Re-install Anaconda with preferences set to **current-user only**

**Comment by dunnamin** [comment]
> > hey, how do you shift from 'all users' to 'current user only'?I'm trying to install packages but not able to do so.
> 
> There is a option while installing. After the installing I don't think we have to option to shift. Re-install Anaconda with preferences set to **current-user only**

- You can't just reinstall or you get both versions;
- uninstalling the old version uninstalls both from the Start Menu (Windows 10);
- reinstalling for one user gives a Navigator error that environment is missing now;
- updating Navigator makes navigator start (but it's still installing to 'root');
- same problem, can't do the first and only thing in the 'Get Started' video, updating 'pandas'.

All I was trying to do was install SymPy to take a coursera course, and I followed the links saying you should use 'Conda'.

I'm pretty sure, at this point, that this thing has entries all through the registry that I can't possible get rid of and even the creators don't know how to get rid of. People use this software professionally?
