### ISSUE TITLE
Deprecated R version

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1712]
_From @danvilar on May 9, 2017 16:40_

Hi guys. As you know, many people who work with R will eventually use Bioconductor. As of today, this is what you can read from their install page:

> "The current release of Bioconductor is version 3.5; it works with R version 3.4.0. Users of older R and Bioconductor users must update their installation to take advantage of new features and to access packages that have been added to Bioconductor since the last release."

Do you have plans on providing newer R versions?
Thanks

_Copied from original issue: conda/conda#5262_

**Comment by mingwandroid** [comment]
Yes, we plan to update to 3.4.x, hopefully in the next month or so.

**Comment by adityabandla** [comment]
Any updates on the upgrade?

**Comment by kobeho24** [comment]
It's late June, any update on R 3.4? BTW, how about rstudio? Update as well?

**Comment by mingwandroid** [comment]
3.4.1 comes out tomorrow, but from reading the R mailing list 3.4.1 will be a bit buggy ([regexec bug](https://stat.ethz.ch/pipermail/r-devel/2017-June/074552.html) for example).

**Comment by kobeho24** [comment]
So the R version in conda will not be upgraded until all the bugs are fixed?

**Comment by mingwandroid** [comment]
Clearly not, but waiting a day or two for pretty important ones before kicking off a roughly 2 week-long (~250 packages on 5 different OSes) build process is a good idea (here I am not promising to start the R 3.4.1 build in a day or two as we're pretty busy improving and automating our build procedure with the hope that such 2 week-long build processes becomes a thing of the past).

**Comment by MarcSaric** [comment]
Hi, any plans to start the rebuild using 3.4.1?

**Comment by mingwandroid** [comment]
@danvilar, @MarcSaric, @adityabandla, @kobeho24, if you are using 64-bit Linux, can you please try the preview release?

`conda install -c rdonnellyr r-essentials=1.6.0 rstudio`

Feel free to drop `rstudio` if you don't want it of course.

Feedback would be appreciated.

**Comment by MarcSaric** [comment]
Hi,

I did a quick test , see https://github.com/MarcSaric/docker-stacks/issues/1

Base for the test was a the r-essentials docker image based on r-notebook from https://github.com/jupyter/docker-stacks/blob/master/README.md

**Comment by mingwandroid** [comment]
@danvilar, @MarcSaric, @adityabandla, @kobeho24, @csoja, I have now moved the preview release to the 'normal' R channel (for linux-64 only).

**Comment by mingwandroid** [comment]
Leaving the issue open since it's linux-64 only.

**Comment by z5ouyang** [comment]
Hi,
Do you guys know when r-base-3.4.1 can be installed from conda? Thanks

I saw "linux-64/r-base-3.4.1-0.tar.bz2" listed in "https://anaconda.org/r/r-base/files";
but I cannot update/install it, by "conda install -c r r-base" or "conda install -c r r-base-3.4" with notice seems like it doesn't exist in "https://conda.anaconda.org/r/linux-64" yet:

PackageNotFoundError: Packages missing in current channels:
            
  - r-base-3.4

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/r/linux-64
  - https://conda.anaconda.org/r/noarch

**Comment by gfcannon12** [comment]
Hey guys,

It appears that conda R 3.4.1 is available on win32, win64, OSX, and linux.
https://anaconda.org/r/r-base/files

I've updated r-essentials, and R.3.4.1 is working nicely for me on OSX.  One tip: I had to upgrade rstudio separately to get it to launch from terminal into the desired environment.

**Comment by iagomez** [comment]
@gfcannon12 
How did you install R 3.4.1 using conda? 
I see R 3.4.1 in the output of `conda search r-base`:

```
[root@localhost ~]# conda search r-base
Fetching package metadata ...........
r-base                       3.1.2                         0  defaults
                             3.1.3                         0  defaults
                             3.1.3                         1  defaults
                             3.1.3                         2  defaults
                             3.2.0                         0  defaults
                             3.2.1                         0  defaults
                             3.2.2                         0  defaults
                             3.3.1                         1  defaults
                             3.3.1                         2  defaults
                             3.3.1                         3  defaults
                             3.3.1                         5  defaults
                             3.3.1                         6  defaults
                             3.3.2                         0  defaults
                             3.3.2                         1  defaults
                             3.4.1                         0  defaults
```

But when I try to `conda install r-base` it keeps trying to install `3.3.2`

```
[root@localhost ~]# conda install r-base
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /opt/anaconda:

The following NEW packages will be INSTALLED:

    bzip2:            1.0.6-h0376d23_1
    gsl:              2.2.1-h8267d9d_2
    libgcc:           7.2.0-h69d50b8_2
    libiconv:         1.14-0
    r-base:           3.3.2-0
```

Thanks!

**Comment by mingwandroid** [comment]
Please use:

`conda install -c rdonnellyr -c main r-essentials=1.7.0`

**Comment by MarcSaric** [comment]
Will that move to the main repository anytime soon?

**Comment by mingwandroid** [comment]
It happened nearly a month ago.
