### ISSUE TITLE
dyld: Library not loaded: @rpath/./libgfortran.3.dylib for install.packages("maps") for R 3.3.2

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1715]
_From @Shuolongbj on May 10, 2017 17:56_

1、(gcc) Ru@bogon:~$ conda info
    Current conda install:

                   platform : osx-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : 2.1.9
             python version : 3.6.1.final.0
           requests version : 2.12.4
           root environment : /Users/Ru/anaconda  (writable)
        default environment : /Users/Ru/anaconda/envs/gcc
           envs directories : /Users/Ru/anaconda/envs
                          /Users/Ru/.conda/envs
              package cache : /Users/Ru/anaconda/pkgs
                          /Users/Ru/.conda/pkgs
               channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                config file : /Users/Ru/.condarc
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.12.4 CPython/3.6.1 Darwin/16.5.0 OSX/10.12.4
                    UID:GID : 501:20

2、(gcc) Ru@bogon:~$ conda list --show-channel-urls
#packages in environment at /Users/Ru/anaconda/envs/gcc:
#
cairo                     1.14.8                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cloog                     0.18.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
curl                      7.52.1                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
fontconfig                2.12.1                        3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
freetype                  2.5.5                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gcc                       4.8.5                         8    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gettext                   0.19.8                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
glib                      2.50.2                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gmp                       6.1.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gsl                       2.2.1                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
harfbuzz                  0.9.39                        2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icu                       54.1                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
isl                       0.12.2                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jbig                      2.1                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libffi                    3.2.1                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgcc                    4.8.5                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgfortran               3.0.0                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libiconv                  1.14                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libpng                    1.6.27                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libtiff                   4.0.6                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libxml2                   2.9.4                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mpc                       1.0.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mpfr                      3.1.5                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ncurses                   5.9                          10    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openjdk                   8.0.121                       0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.0.2k                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pango                     1.40.3                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pcre                      8.39                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pixman                    0.34.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python                    3.6.1                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
r                         3.3.2                  r3.3.2_0    conda-forge
r-base                    3.3.2                         1    defaults
r-boot                    1.3_18                 r3.3.2_0    conda-forge
r-class                   7.3_14                 r3.3.2_0    conda-forge
r-cluster                 2.0.6                  r3.3.2_0    conda-forge
r-codetools               0.2_15                 r3.3.2_0    conda-forge
r-foreign                 0.8_67                 r3.3.2_0    conda-forge
r-kernsmooth              2.23_15                r3.3.2_0    conda-forge
r-lattice                 0.20_34                r3.3.2_0    conda-forge
r-mass                    7.3_45                 r3.3.2_0    conda-forge
r-matrix                  1.2_7.1                r3.3.2_0    conda-forge
r-mgcv                    1.8_17                 r3.3.2_0    conda-forge
r-nlme                    3.1_131                r3.3.2_0    conda-forge
r-nnet                    7.3_12                 r3.3.2_0    conda-forge
r-recommended             3.3.2                  r3.3.2_0    conda-forge
r-rpart                   4.1_10                 r3.3.2_0    conda-forge
r-spatial                 7.3_11                 r3.3.2_0    conda-forge
r-survival                2.40_1                 r3.3.2_0    conda-forge
readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                27.2.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xz                        5.2.2                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.8                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

3、(gcc) Ru@bogon:~$ r

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin11.4.2 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> .libPaths()
[1] "/Users/Ru/anaconda/envs/gcc/lib/R/library"
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin11.4.2 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

> install.packages("maps")
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/maps_3.1.1.tar.gz'
Content type 'application/octet-stream' length 2338492 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

* installing *source* package ‘maps’ ...
** package ‘maps’ successfully unpacked and MD5 sums checked
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
configure: creating ./config.status
config.status: creating src/Makefile
** libs
** arch -
clang -I/Users/Ru/anaconda/envs/gcc/include  -I/Users/Ru/anaconda/envs/gcc/include -arch x86_64 -L/Users/Ru/anaconda/envs/gcc/lib -lgfortran -L/Users/Ru/anaconda/envs/gcc  Gmake.c   -o Gmake
clang -I/Users/Ru/anaconda/envs/gcc/include  -I/Users/Ru/anaconda/envs/gcc/include -arch x86_64 -L/Users/Ru/anaconda/envs/gcc/lib -lgfortran -L/Users/Ru/anaconda/envs/gcc  Lmake.c   -o Lmake
Converting world to world2
awk -f convert.awk < world.line > world2.line
Creating legacy world2 database
awk -f legacy_convert.awk < legacy_world.line > legacy_world2.line
make county.L state.L usa.L nz.L world.L world2.L italy.L france.L state.vbm.L state.carto.L legacy_world.L legacy_world2.L lakes.L
./Lmake 0 s b county.line county.linestats ../inst/mapdata/county.L
dyld: Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /private/var/folders/l8/vgdsznqs12l6yxf4tdljm04h0000gn/T/Rtmp56FR4e/R.INSTALL2593136a3842/maps/src/./Lmake
  Reason: image not found
make[1]: *** [county.L] Abort trap: 6
make: *** [ldata] Error 2
ERROR: compilation failed for package ‘maps’
* removing ‘/Users/Ru/anaconda/envs/gcc/lib/R/library/maps’

The downloaded source packages are in
  ‘/private/var/folders/l8/vgdsznqs12l6yxf4tdljm04h0000gn/T/RtmpxnRFVd/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("maps") :
  installation of package ‘maps’ had non-zero exit status

4、~/.bash_profile
#added by Anaconda3 4.3.1 installer
export PATH="/Users/Ru/anaconda/bin:$PATH"
#DYLD 
export DYLD_FALLBACK_LIBRARY_PATH=/Users/Ru/anaconda/lib:/usr/local/lib:/usr/lib:$DYLD_FALLBACK_LIBRARY_PATH

5、(gcc) Ru@bogon:~$ otool -L ~/anaconda/envs/gcc/lib/libgfortran.3.dylib
/Users/Ru/anaconda/envs/gcc/lib/libgfortran.3.dylib:
	@rpath/./libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	@rpath/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

Read a lot of issues, but still did not solve, look forward to your help.
  
@kalefranz Can you help diagnose it?

_Copied from original issue: conda/conda#5279_

**Comment by Shuolongbj** [comment]
@kalefranz Thank you very much for your help.

**Comment by Shuolongbj** [comment]
I encountered this problem in the process of installing Caffe / Caffe2 / OpenCV (with Python3.6 env)
The problem is mainly concentrated in gfortran and gcc, thanks for the help again. @kalefranz

**Comment by Shuolongbj** [comment]
@kalefranz @mingwandroid Thank you for your help. 
By the way, conda in the gcc (4.85) how to upgrade to gcc5 or gcc6 / 7 version.  When I use of brew install gcc (gcc7)  in the envs environment (~/anaconda/Ru/envs/xxxx/...)  ,the global gcc whether on the impact. Thank you

**Comment by mingwandroid** [comment]
You cannot solve this build-R-packages-from-source problem without disabling `System Integrity Protection` (or, as we do, using Mac OS X 10.9 to build software on instead since `SIP` came a long later).

Upgrading your `homebrew` `GCC` should not change anything for your `conda` env provided you use the activate script instead of adding `conda` to your `PATH` globally.

In other words, you cannot really use `GCC` > 4.8.5 in `conda` at present.

**Comment by Shuolongbj** [comment]
@mingwandroid Thank you for your help

1、maps for R package temporary solution:directly unpacked into the library directory
https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.4/maps_3.1.1.tgz

2、the conda path in ~/.bash_profile

#added by Anaconda3 4.3.1 installer
export PATH="/Users/Ru/anaconda/bin:$PATH"
#DYLD
export DYLD_FALLBACK_LIBRARY_PATH=/Users/Ru/anaconda/lib:/usr/local/lib:/usr/lib:$DYLD_FALLBACK_LIBRARY_PATH

#Dyld
export DYLD_LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/5:$DYLD_LIBRARY_PATH
#export DYLD_LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/6:$DYLD_LIBRARY_PATH
#export DYLD_LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/7:$DYLD_LIBRARY_PATH

can i use the gcc5/6/7( -brew installed) under the conda envs(:~/anaconda/envs/xx,~/anaconda/envs/yy...) with the above settings ?
 thank you again @mingwandroid and @kalefranz

**Comment by mingwandroid** [comment]
> can i use the gcc5/6/7( -brew installed) under the conda envs

No you cannot unless you disable SIP. Why do you want to use gcc5/6/7 anyway?

**Comment by Shuolongbj** [comment]
thank you  @mingwandroid 
1.i'll disable the sip to test it again.

2.about GCC

I encountered the following gcc problem when installing sonnet(bazel build --config=opt :install, ref:https://github.com/deepmind/sonnet)
Gcc: error: unrecognized command line option '-Wthread-safety'
Gcc: error: unrecognized command line option '-Wself-assign'


(deepmind) Ru@bogon:~sonnet$ touch blah.cc && gcc -c -Wthread-safety blah.cc
gcc: error: unrecognized command line option ‘-Wthread-safety’
(deepmind) Ru@bogon:~sonnet$touch blah.cc && gcc -c -Wself-assign blah.cc
gcc: error: unrecognized command line option ‘-Wself-assign’


i tested to install sonnet through the two envs with conda,one for Python2.7(conda create -n deepmind python=2.7) and the other for Python3.6(conda create -n sonnet mind python=3.6),and i encountered the same error :Gcc: error: unrecognized command line option '-Wthread-safety'
Gcc: error: unrecognized command line option '-Wself-assign'

most likely because gcc is actually aliased to Clang ... 
I'm not sure why this discrepancy would be there,On my Mac (10.12.4),Xcode(8.3.2)

(deepmind)@bogon:~sonnet$ gcc --version
gcc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(deepmind)@bogon:~sonnet$:~sonnet$ which gcc
/Users/Ru/anaconda/bin/gcc

**Comment by mingwandroid** [comment]
Urgh, bazel strikes again. I don't know anything about that build system, sorry.

**Comment by Shuolongbj** [comment]
@mingwandroid 
thank you.i'll check it again.good day for you.

**Comment by laventura** [comment]
Hey folks --   

I'm seeing this error: **Library not loaded: @rpath/./libgfortran.3.dylib** when I created a brand new conda env.  All I've done is install numpy on a python=3.5 environment. 

Is the **libgfortran.3.dylib** missing? 

See below

```
 tfk-py35 ▶ ~ ▶ Developer ❯ … ❯ envs ❯ tfk-py35 ❯ lib ▶ $ ▶ python
Python 3.5.3 | packaged by conda-forge | (default, May 12 2017, 15:35:12)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/aa/Developer/miniconda/envs/tfk-py35/lib/libopenblasp-r0.2.19.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen(/Users/aa/Developer/miniconda/envs/tfk-py35/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/aa/Developer/miniconda/envs/tfk-py35/lib/libopenblasp-r0.2.19.dylib
  Reason: image not found

>>>
```

Here's conda info:
```
tfk-py35 ▶ ~ ▶ Developer ❯ … ❯ envs ❯ tfk-py35 ❯ lib ▶ $ ▶ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/aa/Developer/miniconda  (writable)
  default environment : /Users/aa/Developer/miniconda/envs/tfk-py35
     envs directories : /Users/aa/Developer/miniconda/envs
        package cache : /Users/aa/Developer/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/aa/.condarc
    is foreign system : False
```

and here are the packages installed:
```
 tfk-py35 ▶ ~ ▶ Developer ❯ … ❯ envs ❯ tfk-py35 ❯ lib ▶ $ ▶ conda list
# packages in environment at /Users/aa/Developer/miniconda/envs/tfk-py35:
#
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
blas                      1.1                    openblas    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.4.17                py35_0    conda-forge
libgfortran               3.0.0                         1    defaults
numpy                     1.13.1          py35_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2l                        0    conda-forge
pip                       9.0.1                    py35_1    defaults
python                    3.5.3                         3    conda-forge
readline                  6.2                           2    <unknown>
scipy                     0.19.1          np113py35_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                33.1.1                   py35_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
wheel                     0.29.0                   py35_0    defaults
xz                        5.2.2                         1    defaults
zlib                      1.2.11                        0    conda-forge
 tfk-py35 ▶ ~ ▶ Developer ❯ … ❯ envs ❯ tfk-py35 ❯ lib ▶ $ ▶
```

When I go into `/Users/aa/Developer/miniconda/envs/tfk-py35/lib` (where all the libs are installed), I only see `libgfortran.2.dylib`, **not the libgfortran.3.dylib**. See here:
```
 tfk-py35 ▶ ~ ▶ Developer ❯ … ❯ envs ❯ tfk-py35 ❯ lib ▶ $ ▶ ls -l *fortran*
-rwxrwxr-x  2 aa  staff  1027349 Jan 24 17:42 libgfortran.2.dylib
 tfk-py35 ▶ ~ ▶ Developer ❯ … ❯ envs ❯ tfk-py35 ❯ lib ▶ $ ▶
```

Is the **libgfortran.3.dylib** missing? 
Any help appreciated! Thanks!

---

FYI -- here's how the env was created:
```
 ~ ▶ $ ▶ conda create --name tfk-py35 python=3.5 numpy scipy
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/aa/Developer/miniconda/envs/tfk-py35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-0.19.1               |np113py35_blas_openblas_200        15.1 MB

The following NEW packages will be INSTALLED:

    blas:            1.1-openblas
    ca-certificates: 2017.4.17-0
    certifi:         2017.4.17-py35_0
    libgfortran:     3.0.0-1
    numpy:           1.13.1-py35_blas_openblas_200      [blas_openblas]
    openblas:        0.2.19-2
    openssl:         1.0.2l-0
    pip:             9.0.1-py35_1
    python:          3.5.3-3
    readline:        6.2-2
    scipy:           0.19.1-np113py35_blas_openblas_200 [blas_openblas]
    setuptools:      33.1.1-py35_0
    sqlite:          3.13.0-1
    tk:              8.5.19-1
    wheel:           0.29.0-py35_0
    xz:              5.2.2-1
    zlib:            1.2.11-0

Proceed ([y]/n)? y

Fetching packages ...
scipy-0.19.1-n 100% |#########################################################################################| Time: 0:00:02   6.54 MB/s
Extracting packages ...
[      COMPLETE      ]|############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|############################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate tfk-py35
#
# To deactivate this environment, use:
# $ source deactivate
#
```

**Comment by mingwandroid** [comment]
`conda install r-maps`

**Comment by KateKraft** [comment]
`conda install r-maps` does not work.
