### ISSUE TITLE
Issue with: conda install mysql-python

### ISSUE THREAD

**Issue by pathaine** [ContinuumIO/anaconda-issues#1717]
Hello, I get the following error when running "conda install mysql-python" on Ubuntu 16.04:

UnsatisfiableError: The following specifications were found to be in conflict:
  - mysql-python -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

Thank you in advance!

**Comment by nehaljwani** [comment]
The `mysql-python` conda package hasn't been built for `python 3` . You can try creating a `python 2.7` environment and install `mysql-python` into that.

```bash
(root) bash-4.1# conda create -yn py27 python=2.7 mysql-python
(root) bash-4.1# source activate py27
(py27) bash-4.1# python -c 'import MySQLdb; print(MySQLdb.__version__)'
1.2.5
```

**Comment by pathaine** [comment]
Oh, I see. Thank you!
