### ISSUE TITLE
Ipython 6.0 within Spyder problems

### ISSUE THREAD

**Issue by jurekK** [ContinuumIO/anaconda-issues#1719]
Upgrading IPython from 5.1 to 6.0 - both through conda update, and using the anaconda-navigator, makes it troublesome to use it within Spyder. Internal console error report:

  **File "C:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'banner**
followed by some other messages, e.g.:
**from IPython.core.usage import quick_guide
ImportError: cannot import name 'quick_guide'**

Ipython launched from a terminal seems to work correctly.

System: Windows 10, Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32. Conda 4.3.17. Spyder 3.1.3

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.1.4. Please update to that version.
