### ISSUE TITLE
ImportError: No module named math

### ISSUE THREAD

**Issue by IamGianluca** [ContinuumIO/anaconda-issues#172]
For some reason I can't load the math library. I'm running it on a Linux Mint 17 64-bit machine (Linux 3.13 kernel).
```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.6.3
  conda-build version : 1.3.5
       python version : 2.7.8.final.0
     requests version : 2.4.0
     root environment : /home/gianluca/anaconda  (writable)
  default environment : /home/gianluca/anaconda
     envs directories : /home/gianluca/anaconda/envs
        package cache : /home/gianluca/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
```

```
$ python
Python 2.7.8 |Continuum Analytics, Inc.| (default, Aug 21 2014, 18:22:21) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from math import sqrt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named math
```

I've tried to update all libraries but got this error message:
```
$ conda update --all
Fetching package metadata: ..
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
WARNING: This could take a while. Type Ctrl-C to exit.
[      COMPLETE      ] |##################################################| 100%
Hint: anaconda >=2.0.1 has a conflict with the remaining packages
```

Install Anaconda from scratch (and update it) doesn't fix the issue.

**Comment by ilanschnell** [comment]
Maybe it was a problem with having PYTHONPATH, or PYTHONHOME set.  Anyway, closing issue.

**Comment by JMoVS** [comment]
I currently have the same problem that in my Pycharm, it complains that there is no module named "math" but it works nevertheless... So if you want, you could reopen this issue and we could try to find out the error. I'm using Python 3.5.1 and Windows 10 here

**Comment by pabarber** [comment]
I had the same issue using PyCharm. Solved by changing the project interpreter (for my anaconda env) to point at python 3.5 rather than python 3.

**Comment by tahirahmad2030** [comment]
This is problem of Anaconda, uninstall and reinstall Anaconda

**Comment by ZhouM1118** [comment]
I have some problem, I use python 3.5 for Anaconda and I can't import math

**Comment by taewookim** [comment]
same here

**Comment by ethanyxu** [comment]
I'm having the exact same problem. 
"Maybe it was a problem with having PYTHONPATH, or PYTHONHOME set. Anyway, closing issue."??
How is this a valid reason to close an issue that is not resolved??

**Comment by csoja** [comment]
@ethanyxu Can you open a new issue detailing your problem?  Many, many things have changed with Anaconda since Sep 8, 2014 when the original issue was created.  I believe the issue was closed because the original poster no longer had the issue after reinstalling Anaconda, so there was no way to track it down further at that time.

**Comment by sogapalag** [comment]
same problem.
I test it on **notebook**, it works, which shows
In: math.__file__
out: '<usr>/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so'
but still, when run it on **terminal**, 
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda custom (64-bit) on linux
shows ModuleNotFoundError: No module named 'math'.
