### ISSUE TITLE
Version of spacy package is very old

### ISSUE THREAD

**Issue by agsax2002** [ContinuumIO/anaconda-issues#1721]
Hi. I noticed that spacy is only on 0.101.0. The latest version from pip is 1.8.2.
Is this common to be that far behind? Can this be updated without too much trouble? Thanks.

I'm having trouble getting another package (not available through anaconda -- "textacy" to work with the older spacy package).

**Comment by goanpeca** [comment]
@ilanschnell , @mingwandroid ?

**Comment by agsax2002** [comment]
I installed spacy from anaconda.org, and this seems to solve my issue.
Website: https://anaconda.org/conda-forge/spacy
Installation code: conda install -c conda-forge spacy=1.8.2

I'm not sure why the pip version of spaCy wouldn't talk to textacy. Now that I have an updated version from Conda, my software seems happy.
