### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vv111y** [ContinuumIO/anaconda-issues#1722]
The following errors occured:

None:
UnsatisfiableError: The following specifications were found to be in conflict:
  - biopython ==1.68
  - numbapro -> accelerate 2.0|2.0.2
  - numbapro -> llvmlite 0.2.0|0.2.2|0.4.0|0.5.0|0.6.0|0.7.0|0.8.0
  - numbapro -> numba 0.1.1|0.10.2|0.11.0|0.11.1|0.12.1|0.12.2|0.13.0|0.13.1|0.13.2|0.13.3|0.14.0|0.15.1|0.16.0|0.17.0|0.18.1|0.18.2|0.19.1|0.2|0.20.0|0.21.0|0.23.1|0.3|0.3.1|0.3.2|0.5.0|0.6.0|0.7.0|0.7.1|0.8.1|0.9.0
  - numbapro -> numpy 1.10*|1.5*|1.6*|1.7*|1.8*|1.9*
  - numbapro -> python 2.6*|3.3*|3.4*|3.5*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.3.16', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.13', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@vv111y current version of navigator is 1.5.2, I recommend you to update to the latest version.

As the error states, its not possible to satisfy the install request, so it is not a bug per se, just the specification solver in conda does not find a solution that fits the request.

To update please open a terminal and do

`conda remove qt`
`conda install qt=5 pyqt=5`
`conda install anaconda-navigator`

**Comment by vv111y** [comment]
Thanks, that did resolve the issue.

Sorry for delay in responding, there seems to be other dependancy issues with apps/components, and I wanted to respond once all is settled. That is for another time.
