### ISSUE TITLE
not able to find xgboost package for python.  Kindly help

### ISSUE THREAD

**Issue by abhim701** [ContinuumIO/anaconda-issues#1726]

**Comment by mingwandroid** [comment]
`conda search` should be used in this situation:

```
conda search xgboost
Fetching package metadata ...........
libxgboost                   0.60                 h8fd8b8a_0  defaults        
py-xgboost                   0.60            py27np112hf8e804c_0  defaults        
                             0.60            py35np112h1606666_0  defaults        
                             0.60            py36np112hcfb0327_0  defaults        
r-xgboost                    0.60             r332h8f6dcb1_0  defaults
```

So for python you need to use `conda install py-xgboost`

**Comment by abhim701** [comment]
Thanks for the help. I am able to install it now . But when I try import xgboost from Spyder notebook I am getting this error :   **the program can't start because libgcc_s_seh-1.dll is missing** 
Any idea ?  I am using Windows 8.1 and Anaconda Spyder

**Comment by mingwandroid** [comment]
How are you launching Spyder?

**Comment by abhim701** [comment]
Thanks for the help and suggestion!
I am launching Spyder from Anaconda UI/Navigator.  I am able to import and run my XGBoost now :) 
I downloaded the file libgcc_s_seh-1.dll and copied it to \Anaconda3\Library\bin. Hope this was the appropriate way to fix it.

**Comment by mingwandroid** [comment]
No, it isn't, `conda update anaconda-naviagator` is, or `conda update --all` though some people don't recommend that (I've never had a problem with it though).
