### ISSUE TITLE
Anaconda Python on Linux claims utime cannot follow symlinks

### ISSUE THREAD

**Issue by goerz** [ContinuumIO/anaconda-issues#1727]
It appears that any Linux Anaconda version of Python does not support `utime(... follow_symlinks=False)` even though this should generally supported on Linux, and the system version of Python handles it correctly:

    root@webserver:~> /usr/bin/python3
    Python 3.5.2 (default, Nov 17 2016, 17:05:23)
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.supports_follow_symlinks
    {<built-in function chown>, <built-in function stat>, <built-in function access>, <built-in function link>, <built-in function utime>}

In comparison, with Anaconda, the result is

    root@webserver:~> /opt/anaconda/bin/python
    Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01)
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.supports_follow_symlinks
    {<built-in function access>, <built-in function stat>, <built-in function link>, <built-in function chown>}

I've tested this with several python versions (3.5 / 3.6) and on several different workstations, running different versions of Ubuntu.

See also https://github.com/borgbackup/borg/issues/2507

**Comment by nehaljwani** [comment]
To permit use of `follow_symlinks` as an argument to any of the os.* functions, python [checks](https://github.com/python/cpython/blob/v3.5.1/Lib/os.py#L163-L198) whether it was compiled with `HAVE_LUTIMES` or `HAVE_UTIMENSAT` set to `1`.  

If you compare anaconda's python3 and system's python3, you will see:

```bash
(root) bash-4.1# python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var('HAVE_LUTIMES')
0
>>> sysconfig.get_config_var('HAVE_UTIMENSAT')
0
```
```bash
bash-4.1# /usr/bin/python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("HAVE_LUTIMES")
1
>>> sysconfig.get_config_var("HAVE_UTIMENSAT")
1
```

The configure script run while compiling python, sets `HAVE_LUTIMES=1` if the library function `lutimes()` is available (glibc >= 2.6) and sets `HAVE_UTIMENSAT=1` if the system call `utimensat()` is available (kernel >= 2.6.22).

The python v3 package that is shipped with anaconda is probably built on CentOS 5, which has glibc version `2.5` and kernel version `2.6.18`, neither of which satisfies the above requirements.

CentOS 5 is now EoL, and future versions of python may be compiled on CentOS 6, which satisfies the above requirements. Either you can wait, or, if this is a deal breaker for you, compile python 3 on a system which satisfies the above requirements yourself :-)

**Comment by goerz** [comment]
That certainly explains it. Thanks for the detailed analysis. It's not a dealbreaker, but they should probably move to a less outdated build system soon.

**Comment by mingwandroid** [comment]
> they should probably move to a less outdated build system soon.

Moving to a 'less outdated build system' results in binaries that cannot be run on those old systems. The aim here is to build the most modern software on the oldest OS versions that are still in popular use. We are in the process of determining if CentOS 5 is still in popular use.

**Comment by goerz** [comment]
I understand the reasoning behind using an older built-system, but I think it becomes a problem when it affects functionality (as in the linked borgbackup crash). Maybe at some point the existing built-packages could be archived to a "legacy Linux" distribution of Anaconda, while the normal distribution moves to a newer system.

Incidentally, I've found Anaconda to becomes significantly more unstable in recent months, resulting in segfaults (matplotlib is commonly affected, or something like https://github.com/qutip/qutip/issues/674). Now I'm wondering if this is all just due to a completely outdated build-system producing incompatibilities with the Ubuntu > 14.04 systems I'd assume most people are using these days. I might be way off on this, so just food for thought. Anaconda has been absolutely amazing in the past, and I hope it keeps up!

**Comment by mingwandroid** [comment]
> Now I'm wondering if this is all just due to a completely outdated build-system producing incompatibilities with the Ubuntu > 14.04 systems I'd assume most people are using these days

Unlikely. Linux and glibc provide very good forward compatibility guarantees.

**Comment by MestreLion** [comment]
2021... has Anaconda moved away from CentOS 5? If so, I believe this can be closed

**Comment by csoja** [comment]
Thanks.  You are correct, Centos5 is no longer the minimum supported platform.
