### ISSUE TITLE
20 Errors after experimental installation procedure

### ISSUE THREAD

**Issue by droid-smith** [ContinuumIO/anaconda-issues#1728]
Hi everybody,

I just installed NILMTK using the experimental installation procedure to the third linux machine. My issue: **I always get the same 20 Errors when exectuing the nosetests in ~/nilmtk**:

the test_all.py result in OK:

> (nilmtk-env) hej19153@rz411:~/anaconda2$ python ./lib/python2.7/site-packages/tables/tests/test_all.py
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> PyTables version:    3.3.0
> HDF5 version:        1.8.17
> NumPy version:       1.12.1
> Numexpr version:     2.6.2 (using VML/MKL 2017.0.1)
> Zlib version:        1.2.8 (in Python interpreter)
> LZO version:         2.06 (Aug 12 2011)
> BZIP2 version:       1.0.6 (6-Sept-2010)
> Blosc version:       1.11.1 (2016-09-03)
> Blosc compressors:   blosclz (1.0.5), lz4 (1.7.2), lz4hc (1.7.2), snappy (1.1.1), zlib (1.2.8), zstd (1.0.0)
> Blosc filters:       shuffle, bitshuffle
> Cython version:      0.25.2
> Python version:      2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> Platform:            Linux-3.16.0-4-amd64-x86_64-with-debian-8.8
> Byte-ordering:       little
> Detected cores:      4
> Default encoding:    ascii
> Default FS encoding: UTF-8
> Default locale:      (de_DE, UTF-8)
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> Performing only a light (yet comprehensive) subset of the test suite.
> If you want a more complete test, try passing the --heavy flag to this script
> (or set the 'heavy' parameter in case you are using tables.test() call).
> The whole suite will take more than 4 hours to complete on a relatively
> modern CPU and around 512 MB of main memory.
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> version: 1.11.1

**Any hints?**

[log-nosetests.txt](https://github.com/ContinuumIO/anaconda-issues/files/1001827/log-nosetests.txt)

**Comment by jjhelmus** [comment]
It looks like most (all?) of the errors are `AttributeError: 'module' object has no attribute 'period'`.  The 0.20.x release of pandas renamed `pd.tseries.period.PeriodIndex` to `pd.PeriodIndex`.  Perhaps `nilmtk` needs to be run with a 0.19.x version of pandas?

**Comment by droid-smith** [comment]
wow, you were right =)
`(nilmtk-env) hej19153@rz411:~/nilmtk$ conda list | grep pandas
pandas                    0.19.2              np112py27_1
(nilmtk-env) hej19153@rz411:~/nilmtk$ nosetests
...........................................
----------------------------------------------------------------------
Ran 43 tests in 45.455s

OK
Closing remaining open files:/home/hej19153/nilmtk/data/energy.h5...done
`
For all other people having this issue - here are the necessary commands. Note: [pandas 0.19.2 was obviously the last minor version before 0.20](http://pandas.pydata.org/pandas-docs/stable/release.html#pandas-0-19-2):

`(nilmtk-env) hej19153@rz411:~/nilmtk$ conda remove pandas
Fetching package metadata .........
Solving package specifications: .

Package plan for package removal in environment /home/hej19153/anaconda2/envs/nilmtk-env:

The following packages will be REMOVED:

    pandas: 0.20.1-np112py27_0

Proceed ([y]/n)? y

(nilmtk-env) hej19153@rz411:~/nilmtk$ conda install pandas=0.19.2
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/hej19153/anaconda2/envs/nilmtk-env:

The following NEW packages will be INSTALLED:

    pandas: 0.19.2-np112py27_1

Proceed ([y]/n)? y

pandas-0.19.2- 100% |#############################################################################################################################################| Time: 0:00:02   5.52 MB/s



(nilmtk-env) hej19153@rz411:~/nilmtk$
`
