### ISSUE TITLE
ROOT from CERN fails to compile against Anaconda python 3

### ISSUE THREAD

**Issue by buuck** [ContinuumIO/anaconda-issues#1734]
ROOT nearly compiles against anaconda python3, but bonks at the very end with this message:

```shell
[100%] Linking CXX executable ../../bin/hist2workspace
/usr/bin/ld: warning: libiconv.so.2, needed by //home/mbuuck/Dev/anaconda3/lib/libxml2.so.2, not found (try using -rpath or -rpath-link)
//home/mbuuck/Dev/anaconda3/lib/libxml2.so.2: undefined reference to `libiconv_open'
//home/mbuuck/Dev/anaconda3/lib/libxml2.so.2: undefined reference to `libiconv_close'
//home/mbuuck/Dev/anaconda3/lib/libxml2.so.2: undefined reference to `libiconv'
collect2: error: ld returned 1 exit status
roofit/histfactory/CMakeFiles/hist2workspace.dir/build.make:138: recipe for target 'bin/hist2workspace' failed
make[2]: *** [bin/hist2workspace] Error 1
CMakeFiles/Makefile2:23028: recipe for target 'roofit/histfactory/CMakeFiles/hist2workspace.dir/all' failed
make[1]: *** [roofit/histfactory/CMakeFiles/hist2workspace.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

But I have libiconv sitting right there in ~/Dev/anaconda3/lib:
 ```shell
mbuuck@mbuuck-Lenovo-ideapad-510S-14ISK:~/Dev/anaconda3/lib$ ldd libxml2.so.2
	linux-vdso.so.1 =>  (0x00007ffc1f5fd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff71754a000)
	libz.so.1 => /home/mbuuck/Dev/anaconda3/lib/././libz.so.1 (0x00007ff717333000)
	libiconv.so.2 => /home/mbuuck/Dev/anaconda3/lib/././libiconv.so.2 (0x00007ff717044000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff716d3b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff716971000)
	/lib64/ld-linux-x86-64.so.2 (0x000055cf1bf60000)
mbuuck@mbuuck-Lenovo-ideapad-510S-14ISK:~/Dev/anaconda3/lib$ ll libiconv.*
-rw-rw-r-- 1 mbuuck mbuuck 1051850 Nov 16 00:16 libiconv.a
-rw-rw-r-- 1 mbuuck mbuuck     938 May 16 14:25 libiconv.la
lrwxrwxrwx 1 mbuuck mbuuck      17 May 16 14:25 libiconv.so -> libiconv.so.2.5.1*
lrwxrwxrwx 1 mbuuck mbuuck      17 May 16 14:25 libiconv.so.2 -> libiconv.so.2.5.1*
-rwxrwxr-x 1 mbuuck mbuuck 1025476 May 16 14:25 libiconv.so.2.5.1*
```

What gives?

**Comment by msarahan** [comment]
The presence of libraries in the conda root environment is irrelevant.  They must be in the build environment, which will look something like:

```~/Dev/anaconda3/conda-bld/ROOT_(timestamp)/_h_env_placehold.....```

To get your libraries in there, you must list them as build time dependencies in your meta.yaml file.

**Comment by buuck** [comment]
@msarahan, sorry I don't really understand your response. I'm not using a meta.yaml file; I'm trying to compile a system-wide ROOT from scratch, version 6.08.06. It works just fine when I build it against my system python 2.7 and it picks up all the standard system-wide libraries (e.g. /usr/lib/x86_64-linux-gnu/libxml2.so). I wanted to build it against python3, so I installed Anaconda with python 3.6 (and prepended it to $PATH as suggested so that it would mask my system python). Now, because ~/Dev/anaconda3/bin is in front of all the system locations in $PATH, cmake picks up the anaconda libraries instead of the system ones when I try to compile ROOT. This shouldn't be a problem since I think all of the necessary libraries are present in ~/Dev/anaconda3/lib/, but ~/Dev/anaconda3/lib/libxml2.so.2 can't find ~/Dev/anaconda3/lib/libiconv.so.2 even though it exists in the same folder.

I've unpacked the ROOT tarball into ~/Dev/mjdeps/ROOT/6.08.06/src, wrote build files to ~/Dev/mjdeps/ROOT/6.08.06/build with
```shell
cmake -DCMAKE_INSTALL_PREFIX=../install -Dgdml=ON -Dminuit2=ON -Droofit=ON ../src
```
I've since uninstalled anaconda and have successfully built ROOT against my system python installation and I think I'll probably just stick with that for now.

I apologize if this is not the correct place for this question (not sure it's necessarily a bug with anaconda), but since I can compile against my system python but not anaconda3, I thought I'd ask here. I don't know much about dynamic linking, but it seems like that could be the problem here (or maybe it's something wrong with cmake?).

**Comment by msarahan** [comment]
Nah, nothing's fundamentally wrong here.  You just need to adjust your paradigm of thought.

Here's the deal: Anaconda is Python plus a bunch of packages, including conda.  Conda is a package manager.  Think of it like apt-get or yum.  The advantages that it has over apt-get or yum are:

1. Does not need root privileges
2. messing up your conda install does not hose your OS
3. You can have multiple environments to take advantage of different python versions and different dependencies.  Keeping your environments small makes them less fragile, and more reproducible.

OK, so with that in mind: conda-build is not a tool to build stuff into your root anaconda installation.  Conda-build is a tool to build packages that *anyone* can install into any conda environment.  To do this, conda-build creates temporary build environments that are something like your root environment, but contain only what is necessary to build your software.  This is what part of meta.yaml specifies.  You also specify runtime dependencies - which packages need to be present when your package is installed.

So, again, it doesn't matter that your root prefix has the libraries - that's not what conda-build is using to build your package.  It is creating another self-contained prefix, and in that prefix, cmake does not see the libraries from your root prefix.

I highly recommend checking out some of the packages on conda-forge as examples.  See https://conda-forge.github.io/ and https://github.com/conda-forge/sqlite-feedstock/tree/master/recipe

**Comment by buuck** [comment]
I'm not using conda-build at all, and I'm also not trying to install a conda hosted version of ROOT. I'm just trying to install a system-wide version of ROOT that is compiled against python3, more or less following these instructions: https://root.cern.ch/building-root. I'm confused as to why you are bringing it up; are you suggesting that I drop this approach and switch to using conda-build to compile ROOT into a conda environment instead of compiling it manually at system level?

**Comment by msarahan** [comment]
Sorry I got mixed up.  I spend most of my time answering conda-build issues.

I would advise you to use conda-build.  It might be a tiny bit more work on the front end, but being able to distribute binary packages to other conda users is a major perk.  It also has lots of things to make life easier, as far as setting assorted environment variables and putting tools in the right place.  It might make this all just work -  hopefully, anyway.

If you don't want to go down that road, you may need to set LD_LIBRARY_PATH so that your anaconda lib path is part of it.  LDFLAGS might also be necessary.

**Comment by nehaljwani** [comment]
@buuck Could you please share on which Linux distribution are you trying to build ROOT on?

**Comment by buuck** [comment]
This is on Ubuntu 16.04.2

**Comment by nehaljwani** [comment]
@buuck I was able to build `ROOT` using the command:

```bash
cmake \
    -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath,$CONDA_PREFIX/lib" \
    -DCMAKE_INSTALL_PREFIX=../install \
    -Dgdml=ON -Dminuit2=ON -Droofit=ON \
    ../root-6.08.06/
```

`CONDA_PREFIX` is set automatically when a conda environment is activated. However, if you didn't do that, you can set it to `/home/mbuuck/Dev/anaconda3/`

There might be a better way to do this, however, the above generated the following compiler/linker command:
```bash
roofit/histfactory/CMakeFiles/hist2workspace.dir/link.txt:/usr/bin/c++    -pipe -m64  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -fPIC -pthread -std=c++11 -O2 -g -DNDEBUG  -Wl,-rpath,/conda/lib -rdynamic CMakeFiles/hist2workspace.dir/src/MakeModelAndMeasurements.cxx.o CMakeFiles/hist2workspace.dir/src/hist2workspace.cxx.o  -o ../../bin/hist2workspace ../../lib/libHistFactory.so ../../lib/libRooStats.so ../../lib/libXMLParser.so ../../lib/libRooFit.so ../../lib/libRooFitCore.so ../../lib/libTree.so ../../lib/libNet.so ../../lib/libGpad.so ../../lib/libMinuit.so ../../lib/libGraf.so ../../lib/libRIO.so ../../lib/libThread.so ../../lib/libFoam.so ../../lib/libHist.so ../../lib/libMatrix.so ../../lib/libMathCore.so ../../lib/libCore.so -Wl,-rpath,/tmp/build/lib:
```
And finally, the binary has:
```bash
(root) root@buildme:/tmp/build# ldd /tmp/build/lib/libRSQLite.so
	linux-vdso.so.1 =>  (0x00007fff43bd3000)
	libsqlite3.so.0 => /conda/lib/libsqlite3.so.0 (0x00007fbcf024e000)
	libNet.so => /tmp/build/lib/libNet.so (0x00007fbceff86000)
	libCore.so => /tmp/build/lib/libCore.so (0x00007fbcef991000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbcef60b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbcef3f5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbcef02b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbceee27000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbceec0a000)
	libssl.so.1.0.0 => /conda/lib/libssl.so.1.0.0 (0x00007fbcee992000)
	libcrypto.so.1.0.0 => /conda/lib/libcrypto.so.1.0.0 (0x00007fbcee55b000)
	libRIO.so => /tmp/build/lib/libRIO.so (0x00007fbcee099000)
	liblzma.so.5 => /conda/lib/liblzma.so.5 (0x00007fbcede73000)
	libz.so.1 => /conda/lib/libz.so.1 (0x00007fbcedc5d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbced954000)
	/lib64/ld-linux-x86-64.so.2 (0x0000562482842000)
	libThread.so => /tmp/build/lib/libThread.so (0x00007fbced727000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbced51f000)

(root) root@buildme:/tmp/build# chrpath -l /tmp/build/lib/libRSQLite.so
/tmp/build/lib/libRSQLite.so: RPATH=/conda/lib:/tmp/build/lib:
```

**Comment by buuck** [comment]
@nehaljwani Thanks! I think I'm going to stick with python 2.7 for now, but if/when I try this again I'll see if setting DCMAKE_EXE_LINKER_FLAGS works for me.
