### ISSUE TITLE
windows 10, updating anaconda navigator to version 1.5.2, fails

### ISSUE THREAD

**Issue by Tom-a-Hawk** [ContinuumIO/anaconda-issues#1738]
When opening Anaconda Navigator I am prompted to update.

I get a message that "Anaconda Navigator Updated succefully" (typo) and to "restart the application".

I click okay and shut down the navigator. I restart my computer.  

When I re-open Anaconda Navigator I get the same prompt to update to 1.5.2

**Comment by ak0** [comment]
Same for me.
Is there any follow up, fix for that?

**Comment by goanpeca** [comment]
@Tom-a-Hawk @ak0  yes we have a bug in our updater. This is solved for 1.6 to be released next week. In the meantime please open a Terminal/Anaconda Prompt and type

`$ conda install anaconda-navigator=1.5.2`

**Comment by Tom-a-Hawk** [comment]
Worked like a champ! Thanks for the help!
