### ISSUE TITLE
import re2 in Anaconda in Mac OS X

### ISSUE THREAD

**Issue by RahulKulhari** [ContinuumIO/anaconda-issues#174]
> > > import re2
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: dlopen(/Users/us/Anaconda/anaconda/lib/python2.7/site-packages/re2.so, 2): Symbol not found: __ZN3re23RE213GlobalReplaceEPSsRKS0_RKNS_11StringPieceE
> > >   Referenced from: /Users/us/Anaconda/anaconda/lib/python2.7/site-packages/re2.so
> > >   Expected in: dynamic lookup

I am using anaconda. 
I am getting this error when i am importing re2 in python Mac OS X.

How to solve this issue ?

**Comment by mansweet** [comment]
I am also getting this error.  Was there a resolve we can refer to?

**Comment by ryanskeith** [comment]
Closing old issue.
