### ISSUE TITLE
[closed:GCC]cross-compilers/compilers_generic

### ISSUE THREAD

**Issue by Shuolongbj** [ContinuumIO/anaconda-issues#1741]
Up to now there are 1738 issues(open:661,closed:1077),and have 119 issues related to gcc ,what's means?Whether there is a better plan to improve？
ref:https://github.com/ContinuumIO/anaconda-issues/issues?utf8=✓&q=gcc%20

**Comment by mingwandroid** [comment]
120 now, but most of them have nothing to do with GCC and just happen to mention it in lists of packages and what not.

**Comment by mingwandroid** [comment]
We have a plan and have done a good amount of work towards that plan. You can see the latest iteration of those recipes here:

https://github.com/mingwandroid/conda-recipes/tree/master/cross-compilers/compilers_generic

**Comment by Shuolongbj** [comment]
@mingwandroid thank you.good job !

cuz.Many DL frameworks are related to gcc when compiled through source...
