### ISSUE TITLE
Anti virus detecting files while running jupyter

### ISSUE THREAD

**Issue by ccordoba12** [ContinuumIO/anaconda-issues#1746]
@waqasanjum6 commented on [Tue Mar 07 2017](https://github.com/ContinuumIO/anaconda/issues/739)

Winodws 10 64 with anti malware installed 
Anaconda 4.3.1

While running jupyter from start menu anti malware detecting files 

![image](https://cloud.githubusercontent.com/assets/21064071/23665116/6557db20-0379-11e7-8d41-168b34fbcb1a.png)

![avg](https://cloud.githubusercontent.com/assets/21064071/23745058/ab096d5e-04d8-11e7-900b-4b123bdfafb7.jpg)

---

@Usama23 commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302671714)

@csoja             
This issue comes up again on latest Anaconda with "AVAST free antivirus" on Windows10x64-av. When launch Notebook & Qt console application from start menu and navigator. After that  antivirus alerts appear and when Ok that alerts, navigator auto quit . when launch navigator again "Failed to process" appear on prompt. This also removes "python.exe" file.

![screenshot_149](https://cloud.githubusercontent.com/assets/21064099/26244522/6afdc792-3ca9-11e7-8c85-2e08a3af2f96.png)
![screenshot_150](https://cloud.githubusercontent.com/assets/21064099/26244524/6afec7d2-3ca9-11e7-813f-5d49f4aa2e3b.png)
![screenshot_151](https://cloud.githubusercontent.com/assets/21064099/26244523/6afdcb7a-3ca9-11e7-8679-fd8657237c64.png)

---

@csoja commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302711663)

@mingwandroid  any thoughts on this one?

---

@mingwandroid commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302716983)

It removes the python.exe, urgh ..

We just need to report it ASAP I think. I'm on it.

---

@mingwandroid commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302718634)

Done. I wish they'd give a case URL we could follow but they don't. You just throw things into their false positive webform and hope for the best.

---

@mingwandroid commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302725232)

Can we move / copy this issue to anaconda-issues? I cannot share a URL with AVAST while it is here. I don't think the nature of the problem is such that they detected a virus in the exe, more likely they consider the way that jupyter is running a http server to be something bad.

---

@csoja commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302725768)

---

@mingwandroid commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302727400)

OK, how do I do that then?

---

@ccordoba12 commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302730988)

I'll move it for you. Give me a sec.

---

@Usama23 commented on [Fri May 19 2017](https://github.com/ContinuumIO/anaconda/issues/739#issuecomment-302731088)

@csoja  and on reinstallation these alerts appear..

![screenshot_158](https://cloud.githubusercontent.com/assets/21064099/26254451/0d886c26-3cd0-11e7-973d-5851318e4fc0.png)

![screenshot_159](https://cloud.githubusercontent.com/assets/21064099/26254452/0d8fa70c-3cd0-11e7-9559-d40dc33d2811.png)

**Comment by anykate** [comment]
This is happening even on windows 32 bit - filename: win-32/python-3.6.4-h0c2934d_3.tar.bz2 downloaded from the below URL:
https://anaconda.org/anaconda/python/files?version=3.6.4

Windows Defender detects it as a Malware and removes python.exe executable from Miniconda3 folder which makes the process execution throw the below error message:

"_**Unable to create process using 'D:\Miniconda3\python.exe D:\Miniconda3\Scripts\conda-script.py shell.cmd.exe activate activate D:\Miniconda3'**_"
