### ISSUE TITLE
How can I edit the default python environment in Visual Studio 2017?

### ISSUE THREAD

**Issue by Jarvis73** [ContinuumIO/anaconda-issues#1749]
I have installed my own anaconda4.1.1(python3) and 4.3.1(python2), but VS 2017 installed another anaconda4.3.0(python3) and python3.5 and added both into python environment of VS 2017, so I want to delete or edit the new installed anaconda and python3.5. But I can't find the menu of button to config.

![image](https://cloud.githubusercontent.com/assets/26033896/26285270/0887eff2-3e7f-11e7-918d-5e6f8ee9783e.png)

**Comment by goanpeca** [comment]
https://docs.continuum.io/anaconda/ide_integration#python-tools-for-visual-studio-ptvs

https://docs.continuum.io/anaconda/ide_integration#python-for-visual-studio-code
