### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by AhmedRebai** [ContinuumIO/anaconda-issues#1750]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - python 3.5*
  - vtk ==6.3.0
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'platform': 'linux-64', 'pyqt': '4.11.4', 'language': 'en_US', 'version': '1.2.1', 'python': '3.5.1', 'os': 'Linux;4.4.0-78-generic;#99~14.04.2-Ubuntu SMP Thu Apr 27 18:49:46 UTC 2017;x86_64;x86_64', 'conda': '4.1.11'}

**Comment by goanpeca** [comment]
You have an old version of Navigator

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```
