### ISSUE TITLE
Windows shortcuts for new environments are not correctly set

### ISSUE THREAD

**Issue by omid-jf** [ContinuumIO/anaconda-issues#1758]
Upon creating new environments, several shortcuts are created automatically with the following command as their target:
`
C:\Anaconda3\envs\myenv\python.exe C:\Anaconda3\cwp.py C:\Anaconda3\envs\myenv "C:/Anaconda3/envs/myenv/python.exe" "C:/Anaconda3/envs/myenv/Scripts/ipython-script.py"
`
However, due to not using the cwp.py file in that specific environment, the shortcut fails to work.

This is true for all shortcuts including "Anaconda Cloud", "Anaconda Navigator", "IPython", "Jupyter Notebook", "Jupyter QTConsole", "Reset Spyder Settings" and "Spyder".

Solution: `C:\Anaconda3\cwp.py` should be changed to `C:\Anaconda3\envs\myenv\cwp.py`

**Comment by msarahan** [comment]
@wulmer I believe you're right.  Sorry I missed seeing being assigned here.  I'll look into this today.
