### ISSUE TITLE
MKL-FFT produces bad results

### ISSUE THREAD

**Issue by cossatot** [ContinuumIO/anaconda-issues#176]
Hi,

I've recently updated mkl and mklfft on several computers (OS X and Linux) and have noticed some major problems in my calculations w/ mklfft.  I am sorry in that I don't yet have trivial examples to reproduce the problem (it's embedded in a larger scientific calculation), but I have tested w/ installing and uninstalling mklfft, which produces or fixes the problem, respectively.  I have noticed this behavior on OS X w/ `mklfft: 1.0-np19py33_p0` and on Linux w/ `mklfft: 1.0-np18py27_p0` (note that I haven't run the exact code on each machine, but I am getting similar garbage results).

The only time I use anything related to fft is with a call to `scipy.signal.fftconvolve()` on two 2D arrays.

Here is part of the good output (it's the array in the background):
![convo_good](https://cloud.githubusercontent.com/assets/2835718/4262011/a9605344-3b88-11e4-85c1-a61d69939776.png)

And here is the same image w/ the bad output (exact same code throughout):
![convo_buggy](https://cloud.githubusercontent.com/assets/2835718/4262013/cf51225e-3b88-11e4-9c0e-d042a84db8f9.png)

If it's at all helpful, I can post notebooks that produce all of this.

Thanks,
Richard

**Comment by crocha700** [comment]
Any new thoughts on this problem? Has this ever been solved?  

Here with Anaconda 2.1.0 (64-bit) on a Mac Pro it works real rfft works with mklfft.fftpack.rfft2 . But some of my colleagues working on slightly different platforms are reporting the exact same bug as fakufaku reported.

**Comment by sklam** [comment]
@crocha700, can you check the version of mklfft by `conda list mklfft`?  The problem should have been fixed in mklfft 2.0.

**Comment by crocha700** [comment]
Thanks @sklam !

Things work just fine with mklfft 2.0

**Comment by divenex** [comment]
I also confirm that the problems I had reported above have disappeared in mklfft 2.0. Thanks @sklam!
