### ISSUE TITLE
Wrong output for `python3-config --ldflags`

### ISSUE THREAD

**Issue by ppwwyyxx** [ContinuumIO/anaconda-issues#1761]
Just install anaconda for python3.6 on macos sierra, with the graphical installer.
After the installation:
```
$ python3-config --ldflags
-lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation
```
Two things:
1. It should include `-L/Users/xxx/anaconda/lib` in ldflags as well, otherwise a compiler cannot find `-lpython3.6m`. This is done in anaconda Linux, also in non-conda python.
2. Why `-stack_size,1000000`? Clang complains that this flag is only valid when linking an executable, while I'm linking a shared library.

**Comment by nofacer** [comment]
Hi I just came across the same error when build another project and finally found the solution. Just modify the makefile manually like this:
PYLIBS := -L/Users/Your_name/anaconda3/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation

**Comment by Atry** [comment]
This bug is introduced by CPython, and has been fixed in anaconda's python 3.5:
https://github.com/ContinuumIO/anaconda-recipes/commit/931bfbaf161bf41edcfa76ae1e53bbbf04de011a

However, other 3.x versions of anaconda's python still produce wrong ldflags.

**Comment by mingwandroid** [comment]
Please explain what's wrong with our ldflags.

**Comment by Atry** [comment]
@mingwandroid Wrong ldflags as described in @ppwwyyxx's post.

**Comment by mingwandroid** [comment]
`python3-config --ldflags` returns the linker flags for *[embedding Python in another application](https://docs.python.org/3/extending/embedding.html#compiling-and-linking-under-unix-like-systems)*, it does not give the linker flags for compiling a Python extension module. To get those you need to run the following:

```
python -c "import sysconfig; print(sysconfig.get_config_vars('LDSHARED'))"
```

**Comment by mingwandroid** [comment]
.. and our Python prefers static linking, so:

```
python3-config --ldflags
-L/opt/conda/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation
ls /opt/conda/lib/python3.6/config-3.6m-darwin
lrwxr-xr-x  1 rdonnelly  admin     21 23 Jan 12:14 libpython3.6m.a -> ../../libpython3.6m.a
```

.. is just fine.

**Comment by saraedum** [comment]
@mingwandroid Interesting, so Debian/Ubuntu gets this wrong on their man-page: http://manpages.ubuntu.com/manpages/xenial/en/man1/i386-linux-gnu-python2.7-config.1.html

**Comment by mingwandroid** [comment]
Yes it looks like they do indeed get it wrong here! You should note, the python build scripts from Debian/Ubuntu are what inspired me to switch to a static interpreter, that and the prompting of @pitrou

**Comment by saraedum** [comment]
Ok. I wrote an email to the author of the man-page.
