### ISSUE TITLE
Unable to install Anaconda3 4.3.1(32-bit) on Windows XP 32 bit

### ISSUE THREAD

**Issue by VineshGupta** [ContinuumIO/anaconda-issues#1767]
I am installing  Anaconda3 4.3.1(32-bit) on Windows XP 32 -bit laptop. Getting the error “Failed to create Anaconda menus “. My user is having admin writes .Can anybody help in getting it install ? I appreciate any assistance! Thanks !

Tried the solution which are already mentioned in githug but no success 
![anoconda_error](https://cloud.githubusercontent.com/assets/28974434/26484026/ba7b3ade-420d-11e7-8e84-be9ff1fd3de8.JPG)

Screen shot attached for reference

**Comment by mingwandroid** [comment]
We no longer support Windows XP and at this point, it is a really bad idea to use it due to the lack of security updates.
