### ISSUE TITLE
Can't install RStudio on Anaconda Windows - rmarkdown broken?

### ISSUE THREAD

**Issue by calz1** [ContinuumIO/anaconda-issues#1771]
Installation from within Anaconda Navigator never finishes. When I try:

`conda install -c r rstudio`

I get this after a few other packages install:

> ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'r::r-rmarkdown-1.3-r3.3.2_0'.
> CondaError: Cannot link a source that does not exist. C:\Users\me\AppData\Local\Continuum\Anaconda3\pkgs\r-rmarkdown-1.3-r3.3.2_0\R\library\rmarkdown\COPYING

**Comment by mingwandroid** [comment]
Please try conda update conda first, then try again.

**Comment by calz1** [comment]
Good news and bad news! I ran:

`conda update conda`

in my root environment and that seemed to help a bit in that I can now install Rstudio. Unfortunately, when I install it and then do:

`rstudio`

I get a pop-up that says:

> the application was unable to start correctly 000007b 

I tried deleting the whole virtual environment, created an empty new one, installed rstudio again, and got the same error.

**Comment by mingwandroid** [comment]
Are you activating your environment correctly? (by running activate.bat or using the Anaconda Prompt?)

**Comment by calz1** [comment]
@mingwandroid  Thanks for continued suggestions! Yeah, I am on windows and just running activate <env name>

I noticed something else. I am running Windows 10 64-bit. 

1. On 32-bit Anaconda, I am able to install rmarkdown after conda update conda as described above. Since some reports on the Internet said that Rstudio error I posted before had to do with memory allocation, I went back to 64-bit Anaconda to see if that would help.

2. On 64-bit Anaconda, rmarkdown still will not install after conda update conda.  


Here's a full example:

> 
> (C:\Users\me\AppData\Local\Continuum\Anaconda3) C:\Users\me>conda update conda
> Fetching package metadata .............
> Solving package specifications: .
> 
>  All requested packages already installed.
>  packages in environment at C:\Users\me\AppData\Local\Continuum\Anaconda3:
> 
> conda                     4.3.21                   py36_0
> 
> (C:\Users\me\AppData\Local\Continuum\Anaconda3) C:\Users\me>activate myenv
> 
> (myenv) C:\Users\me>conda install r-rmarkdown
> Fetching package metadata .............
> Solving package specifications: .
> 
> Package plan for installation in environment C:\Users\me\AppData\Local\Continuum\Anaconda3\envs\myenv:
> 
> The following NEW packages will be INSTALLED:
> 
>     m2w64-bwidget:       1.9.10-2
>     m2w64-libjpeg-turbo: 1.4.2-3
>     m2w64-libpng:        1.6.21-2
>     m2w64-libsndfile:    1.0.26-2
>     m2w64-libtiff:       4.0.6-2
>     m2w64-libvorbis:     1.3.5-2
>     m2w64-libxml2:       2.9.3-3
>     m2w64-pcre:          8.38-2
>     m2w64-speex:         1.2rc2-3
>     m2w64-speexdsp:      1.2rc3-3
>     m2w64-tcl:           8.6.5-3
>     m2w64-tk:            8.6.5-3
>     m2w64-tktable:       2.10-5
>     m2w64-xz:            5.2.2-2
>     m2w64-zlib:          1.2.8-10
>     r-backports:         1.0.4-r3.3.2_0
>     r-base:              3.3.2-0
>     r-base64enc:         0.1_3-r3.3.2_0
>     r-bitops:            1.0_6-r3.3.2_2
>     r-catools:           1.17.1-r3.3.2_2
>     r-digest:            0.6.10-r3.3.2_0
>     r-evaluate:          0.10-r3.3.2_0
>     r-highr:             0.6-r3.3.2_0
>     r-htmltools:         0.3.5-r3.3.2_0
>     r-jsonlite:          1.1-r3.3.2_0
>     r-knitr:             1.15.1-r3.3.2_0
>     r-magrittr:          1.5-r3.3.2_2
>     r-markdown:          0.7.7-r3.3.2_2
>     r-mime:              0.5-r3.3.2_0
>     r-rcpp:              0.12.8-r3.3.2_0
>     r-rmarkdown:         1.3-r3.3.2_0
>     r-rprojroot:         1.1-r3.3.2_0
>     r-stringi:           1.1.2-r3.3.2_0
>     r-stringr:           1.1.0-r3.3.2_0
>     r-yaml:              2.1.14-r3.3.2_0
> 
> Proceed ([y]/n)? y
> 
> ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::r-rmarkdown-1.3-r3.3.2_0'.
> CondaError: Cannot link a source that does not exist. C:\Users\me\AppData\Local\conda\conda\pkgs\r-rmarkdown-1.3-r3.3.2_0\R\library\rmarkdown\COPYING
> Attempting to roll back.

**Comment by mingwandroid** [comment]
I need to look into this on Monday.

**Comment by calz1** [comment]
@mingwandroid OK, more news!

So I've tried reinstalling 64 & 32 bit Anaconda several times and recreating several environments with no dice. I went with 64-bit **Mini**conda and had no problem installing on two different PCs. I know Anaconda comes up with a bunch of stuff pre-installed. Is it possible something is corrupt in there? Is there some "refresh package cache" command?

**Comment by mingwandroid** [comment]
Interesting. At least you found a way forward.

There is a metapackage called anaconda that turns miniconda into anaconda. I wonder if that works or not?

**Comment by mingwandroid** [comment]
This is fixed now, please make sure you have the latest conda: From the `Anaconda Prompt`, `conda update conda` then `conda update r-essentials=1.7.0 rstudio`.
