### ISSUE TITLE
Anaconda navigotor and its applications wont work

### ISSUE THREAD

**Issue by HamzaAtcoding** [ContinuumIO/anaconda-issues#1772]
Anaconda navigator along and its enclosed applications stopped working when **qtpy4** package was inserted manually, clicking their .exe icons wont raise any errors as nothing happens.

> But upon manual launch of

``C:\ProgramData\Anaconda2\Scripts\anaconda-navigator.exe
`
or

``C:\ProgramData\Anaconda2\Scripts\spyder.exe
`
> Raised the attached error

![prob](https://cloud.githubusercontent.com/assets/22961431/26543452/72e4694a-4477-11e7-85e2-d9095e4aa405.png)

***It is worth mentioning jupyter-notebook.exe launched from**

`C:\ProgramData\Anaconda2\Scripts\jupyter-notebook.exe
`**Worked fine**
`
`

**Comment by goanpeca** [comment]
@HamzaAtcoding Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```
