### ISSUE TITLE
Cannot find PATH to execute Python using Anaconda Python IDE + ST3

### ISSUE THREAD

**Issue by adcnet** [ContinuumIO/anaconda-issues#1781]
Frustrated cannot find my path cannot find where Python is as it uses Anaconda "install package" via Sublime Text 3 IDE.

http://damnwidget.github.io/anaconda/#

Have watched about 5 YT videos still stuck.

Have followed this exactly http://www.gtlambert.com/blog/python-sublime-text-3 / everything is fine until I run - ctrl - B

http://imgur.com/BbO8qy3

My OS is Windows 8

**Comment by ijstokes** [comment]
@adcnet you need to chase down the GH Issue tracker for the confusingly named "Anaconda" Sublime Text IDE.  That has no relation to the Anaconda Python distribution you're inquiring about here.  I'd suggest you go to: https://github.com/DamnWidget/anaconda/issues.

Continuum Analytics has no association with that Anaconda IDE.
