### ISSUE TITLE
Navigator "Home" panel contains no default apps.

### ISSUE THREAD

**Issue by o12johns** [ContinuumIO/anaconda-issues#1784]
Before upgrade to 1.6.2, saw Spyder, etc., etc. apps in the Home panel.  Now it is empty.  ???

**Comment by LeoChando** [comment]
tried deleting .condarc only Jupyter, QtConsole and Spyder still available. Orange, Glueviz, Rstudio not showing

**Comment by o12johns** [comment]
Double click to open Navigator.app See six apps in home panel.
    Do Command/q to quit Navigator
    Open an Apple Terminal. Do conda clean --all -y
    Once again double click Navigator.app Now see only three apps.
    Do Command/q to quit Navigator
    In Apple Terminal, run navigator-updater. Let it finish, click dismiss.
    Double click to open Navigator.app See the correct six apps back again!

Problem is that conda clean --all also deletes directory ~/anaconda/pkgs/cache which Navigator is using to store information for its Home screen. The navigator-updater restores the ~/anaconda/pkgs/cache directory and its files. Maybe Navigator developers should rename that directory to something besides "cache"?

Current conda install:
           platform : osx-64
      conda version : 4.3.21
   conda is private : False
  conda-env version : 4.3.21
conda-build version : not installed
     python version : 3.6.1.final.0
   requests version : 2.14.2
   root environment : /Users/ojohns/anaconda  (writable)
default environment : /Users/ojohns/anaconda
   envs directories : /Users/ojohns/anaconda/envs
                      /Users/ojohns/.conda/envs
      package cache : /Users/ojohns/anaconda/pkgs
                      /Users/ojohns/.conda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/osx-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/osx-64
                      https://repo.continuum.io/pkgs/pro/noarch
        config file : /Users/ojohns/.condarc
         netrc file : None
       offline mode : False
         user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
            UID:GID : 501:20
