### ISSUE TITLE
netcdf4 not compiled with Cython

### ISSUE THREAD

**Issue by coobas** [ContinuumIO/anaconda-issues#179]
Hello,

I just encountered a problem with the netCDF4 module from Anaconda. The filepath method is not working due to not using Cython for netCDF4 compilation:
<pre>
/sw/python2/anaconda/lib/python2.7/site-packages/netCDF4.so in netCDF4.Dataset.filepath (netCDF4.c:20250)()
ValueError: 
filepath method not enabled.  To enable, install Cython, make sure you have 
version 4.1.2 or higher of the netcdf C lib, and rebuild netcdf4-python.
</pre>

<pre>
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.6.4
  conda-build version : 1.8.1
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : /sw/python2/anaconda  (writable)
  default environment : /sw/python2/anaconda
     envs directories : /sw/python2/anaconda/envs
        package cache : /sw/python2/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
</pre>
<pre>
$ conda list | grep -i cdf
libnetcdf                 4.3.2                         0
netcdf4                   1.1.1                np19py27_0
</pre>

Would it be possible to rebuild netCFD4 with Cython?

Thank you,
Jakub

**Comment by ocefpaf** [comment]
Rebuilding netCDF4-python with cython would be awesome.
:+1:

**Comment by ChrisBarker-NOAA** [comment]
Anyone know what other features this enables? but sounds like a no-brainer to me, in any case.

**Comment by sandhujasmine** [comment]
Related issue with a comment about API features enabled when using cython: https://github.com/Unidata/netcdf4-python/issues/263

I tested filepath on linux and it looks like it must include cython since it works. The latest netdf4 version I got from conda install is 1.2.2 so it seems it has been updated.
```
> conda list|grep cdf
libnetcdf                 4.3.3.1                       1
netcdf4                   1.2.2               np110py27_0

> conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : /home/jasmine/miniconda3  (writable)
  default environment : /home/jasmine/miniconda3/envs/cy_example
     envs directories : /home/jasmine/miniconda3/envs
        package cache : /home/jasmine/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by ChrisBarker-NOAA** [comment]
yup -- working for me now, too. looks like you can close this issue.

**Comment by msarahan** [comment]
Thanks for bringing this up, and for looking into it.  Closing.

**Comment by coobas** [comment]
Thank you for fixing this and sorry for not responding.

**Comment by envhyf** [comment]
@ocefpaf. I'm not familiar with cython. How to rebuild the netcdf4-python package with cython using Conda install? I have already installed cython, and then re-installed netcdf4 using `conda install`. However, the problem "filepath method not enabled" still occured.

**Comment by mingwandroid** [comment]
It's safer to use a different environment than mixing conda-forge with
defaults. I would go with:

conda create -n netcdf4 -c conda-forge netcdf4

.. but I'm not sure there's anything wrong with the package in defaults
either. That hl may need some investigation

**Comment by ocefpaf** [comment]
This issue is from 2014 when `defaults` did not use `cython` to build `netcdf4` that was fixed a long time ago! @envhyf you probably don't need to rebuild it yourself.

@mingwandroid there is an issue with latest `libnetcdf 4.6.1` that is related to short timeout when accessing remote servers. See https://github.com/AnacondaRecipes/libnetcdf-feedstock/issues/5

(But the package per se is OK and users can set their own timeout interval with a `.daprc` file.)
