### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by baharrrr** [ContinuumIO/anaconda-issues#1798]
After installing, when I am checking to make sure install was successful. After typing conda list, this is the error I get:
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffae4673c0 (most recent call first):
Abort trap: 6

I have no idea what should I do with that

**Comment by nehaljwani** [comment]
Could you please share the complete error that you see on the screen?

Also, on the anaconda command prompt, please share the output for the command:
```
set PATH
```

**Comment by baharrrr** [comment]
This is the complete error that I see when I type anything related to conda. I cannot get to the anaconda command on my terminal because of the same issue. 

conda
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffeb4e93c0 (most recent call first):
Abort trap: 6

**Comment by nehaljwani** [comment]
@baharrrr I had asked you for the output of a command , could you please share that output?

**Comment by shayestehfard** [comment]
Hi all, 
I have same issue. After installing anaconda successfully, when I typed conda list I got the following error:
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffa9f633c0 (most recent call first):
Abort trap: 6
