### ISSUE TITLE
Anaconda's libm may have issues

### ISSUE THREAD

**Issue by moorepants** [ContinuumIO/anaconda-issues#182]
I'm compiling some Cython files that are generated from SymPy expressions and when I use the gcc `--ffast-math` compilation flag I'm not able to import the compile `.so` file due to missing math symbols. But if I remove the `--ffast-math` flag from the setup.py file, it works. It get this error, for example:

```
ImportError: ./ufuncify_matrix_0.so: undefined symbol: __pow_finite
```

Here is a minimal working example: https://gist.github.com/moorepants/088c3673df50bbf26684

When I searched the net, I found some references to Anaconda causing this issue:

https://www.google.com/search?client=ubuntu&channel=fs&q=anaconda+__pow_finite&ie=utf-8&oe=utf-8

Two threads recommend removing the `~/anaconda/lib/libm.so` library so that the system `libm` will be used.

**Comment by Jorge-C** [comment]
Not very helpful, but I was also hit by this trying to build [`python-pcl`](https://github.com/strawlab/python-pcl) (well, it built fine but it failed at import time). As @Juanlu001 mentioned, renaming `anaconda/lib/libm.so.6` solved it.

**Comment by ccordoba12** [comment]
@asmeurer do we have time to work on this before the next Anaconda release? What packages do we need to build separately to fix this issue?

**Comment by asmeurer** [comment]
At http://repo.continuum.io/pkgs/free/linux-64/repodata.json, the packages that depend on system (other than anaconda) are llvm, pigz, pycurl, and python.

**Comment by ccordoba12** [comment]
So what would be the idea? Create recipes for each one of them?

And how libm enters the game?

**Comment by mjuric** [comment]
It looks like this issue has been fixed in Anaconda 2.2.0 (and system 5.8-2)?

**Comment by asmeurer** [comment]
Yes, the latest version of the `system` package no longer has libm.

**Comment by AKSHAYUBHAT** [comment]
This error was fixed by removing and then installing system for me.
