### ISSUE TITLE
Reopen: After upgrade to Navigator 1.6.2, no default apps show in Home window.

### ISSUE THREAD

**Issue by o12johns** [ContinuumIO/anaconda-issues#1823]
File ~/.condarc reads:

AeroNew:~ ojohns$ cat .condarc
channels:
  - defaults
ssl_verify: true

I tried deleting this file and reopening Navigator.  (1) Still no default apps in Home (2) Navigator writes the above .condarc back again.

I am running OSX 10.12.5.  Am installing "me only" with anaconda in ~/anaconda

AeroNew:~ ojohns$ conda upgrade --all  
shows all package up-to-date

**Comment by goanpeca** [comment]
@o12johns try to reset navigator settings.

From the command line type

`anaconda-navigator --reset`

**Comment by o12johns** [comment]
did anaconda-navigator --reset   When then start anaconda-navigator I get the new-user spalsh screen.  But still no default apps in Home window.
Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/ojohns/anaconda  (writable)
    default environment : /Users/ojohns/anaconda
       envs directories : /Users/ojohns/anaconda/envs
                          /Users/ojohns/.conda/envs
          package cache : /Users/ojohns/anaconda/pkgs
                          /Users/ojohns/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ojohns/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

**Comment by goanpeca** [comment]
@o12johns, not sure what is going on, could you reinstall the latest Anaconda Distribution installer? 4.4 version is out today

**Comment by o12johns** [comment]
OK will try that. 
        Complete new install.  Stay tuned, probably tomorrow before I
        know result.  Tnx much,  O. Johns
    
    
    On 5/31/17 19:26 PM, Gonzalo
      Peña-Castellanos wrote:
    
    
      @o12johns, not sure what is going on,
        could you reinstall the latest Anaconda Distribution installer?
        4.4 version is out today
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ContinuumIO/anaconda-issues","title":"ContinuumIO/anaconda-issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ContinuumIO/anaconda-issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@goanpeca in #1823: @o12johns, not sure what is going on, could you reinstall the latest Anaconda Distribution installer? 4.4 version is out today"}],"action":{"name":"View Issue","url":"https://github.com/ContinuumIO/anaconda-issues/issues/1823#issuecomment-305371471"}}}

**Comment by o12johns** [comment]
Did a complete wipe of ~/anaconda.  Also deleted ~/.condarc and ~/.conda directory.  Did a complete "me-only" re-install of anaconda using Anaconda3-4.4.0-MacOSX-x86_64.pkg.  This solved the problem, whatever it was.  Now I see all six Applications in the anaconda-navigator Home screen.  Thank you Gonzalo for the suggestion.  BTW, did ~/conda remove anaconda after install and then ~/conda upgrade --all .  So everything should be up to date.
Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/ojohns/anaconda  (writable)
    default environment : /Users/ojohns/anaconda
       envs directories : /Users/ojohns/anaconda/envs
                          /Users/ojohns/.conda/envs
          package cache : /Users/ojohns/anaconda/pkgs
                          /Users/ojohns/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ojohns/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

**Comment by goanpeca** [comment]
@o12johns glad to hear its solved, the nuking of the installation should be a last resort, but I am glad it solved your issues
