### ISSUE TITLE
Windows: Unable to verify downloaded file

### ISSUE THREAD

**Issue by tpowellcio** [ContinuumIO/anaconda-issues#184]
Internet explorer doesnt like the .exe files. 
Vista x32
![screen shot 2014-09-22 at 15 08 10](https://cloud.githubusercontent.com/assets/649601/4363371/e17d0692-4294-11e4-95f6-d9919a628934.png)

7 x32
![screen shot 2014-09-22 at 15 11 56](https://cloud.githubusercontent.com/assets/649601/4363364/cb210fc4-4294-11e4-884f-8f97f9b01ae2.png)

**Comment by remkade** [comment]
Closing, please reopen if you see the same errors with the latest installers.
