### ISSUE TITLE
pillow tk extension problem on os x

### ISSUE THREAD

**Issue by ddale** [ContinuumIO/anaconda-issues#188]
Pillow's default setup.py builds an _imagingtk extension that is not compatible with the anaconda environment, because it links with the system tk framework: 

```
WARNING: Non standard TIFF. Rows per strip TAG missing
WARNING: Non standard TIFF. Strip byte counts TAG missing
objc[5020]: Class TKApplication is implemented in both /anaconda/envs/hedm/lib/python2.7/lib-dynload/../../libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[5020]: Class TKMenu is implemented in both /anaconda/envs/hedm/lib/python2.7/lib-dynload/../../libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[5020]: Class TKContentView is implemented in both /anaconda/envs/hedm/lib/python2.7/lib-dynload/../../libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[5020]: Class TKWindow is implemented in both /anaconda/envs/hedm/lib/python2.7/lib-dynload/../../libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
Segmentation fault: 11
```

This simple patch allows pillow to find the tcl/tk provided by anaconda and fixes the problem:

```diff
diff --git setup.py setup.py
index 2d8cafa..f95c871 100644
--- setup.py
+++ setup.py
@@ -575,7 +575,7 @@ class pil_build_ext(build_ext):
             exts.append(Extension(
                 "PIL._webp", ["_webp.c"], libraries=libs, define_macros=defs))
 
-        if sys.platform == "darwin":
+        if sys.platform == "":
             # locate Tcl/Tk frameworks
             frameworks = []
             framework_roots = [
```

(Please also note issue #185)

**Comment by slobodan-ilic** [comment]
Hi, I'm experiencing the same error message on OSX. I installed the latest official anaconda, created conda environment and installed pillow in it, with "conda install pillow". The version of the installed pillow is 2.7.0. Is there any way I could get around this issue?

**Comment by asampat3090** [comment]
I have the same issue but I'm not too familiar with conda but when I use the command ```conda install pillow=2.6.1``` there are no packages found that match that. Is there a way to manually fix this setup.py and if so, how do I actually install it? As of now I installed pillow using ```conda install pillow``` and this gave me pillow 2.8.2 and I have the same issue. Specifically, 

```bash
objc[87311]: Class TKApplication is implemented in both /Users/anandsampat/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[87311]: Class TKMenu is implemented in both /Users/anandsampat/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[87311]: Class TKContentView is implemented in both /Users/anandsampat/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[87311]: Class TKWindow is implemented in both /Users/anandsampat/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
[1]    87311 segmentation fault  python cleanup.py
```

**Comment by goretkin** [comment]
I'm experiencing this issue. `conda install pillow` is pulling pillow: 3.1.1-py35_0 defaults, which is producing the same error.

**Comment by goretkin** [comment]
Could this issue be re-opened, or should I make a new issue?

**Comment by sametz** [comment]
I am having the same issue. Python 3.5.1, Anaconda 4.0.5, OS X.

**Comment by drabastomek** [comment]
Same deal... Can you fix this?

**Comment by stevengj** [comment]
This is not just an issue for Tk; we're seeing the same issue in using a miniconda Matplotlib with the Tk backend on OS X from Julia (stevengj/PyPlot.jl#164).

**Comment by stevengj** [comment]
And the same issue appears for Python matplotlib users with the Tk backend: http://stackoverflow.com/questions/31998271/matplotlib-cant-work-in-os-x-with-error-tkapplication-is-implemented-in-both

A workaround is just to use a different Matplotlib backend, but it would be good to fix the anaconda Tk library conflict.

**Comment by goretkin** [comment]
This is the fix that worked for me: https://github.com/python-pillow/Pillow/issues/950#issuecomment-292223310
