### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by dengyingguo** [ContinuumIO/anaconda-issues#1881]
## Main error
<b>Unable to move <i>IpythonData</i></b><br><br>Error message:<br>[Errno 13] Permission denied: 'E:\\DataWarehouse\\IpythonData'
## Traceback
```

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@dengyingguo what is the context of this error? We need you to provide more information of what you were doing.
