### ISSUE TITLE
Navigator Error While Installing glueviz

### ISSUE THREAD

**Issue by rolandog** [ContinuumIO/anaconda-issues#1895]
## Main error
The following errors occurred while attempting to install glueviz:
## Traceback
```
CondaOSError: OS error: failed to link (src='C:\\Anaconda3\\pkgs\\anaconda-navigator-1.2.3-py35_0\\Lib/site-packages/anaconda_navigator/static/images/spinner-green-16x16.gif', dst='C:\\Anaconda3\\Lib/site-packages/anaconda_navigator/static/images/spinner-green-16x16.gif', type=1, error=CondaOSError: OS error: win32 hard link failed
)

```
## System information
```
language: en_US
qt: 5.6.2
os: Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
platform: win-64
pyqt: 5.6.0
conda: 4.2.13
python: 3.5.3
version: 1.6.2
```

**Comment by goanpeca** [comment]
@kalefranz 
CondaOSError: OS error: failed to link (src='C:\\Anaconda3\\pkgs\\anaconda-navigator-1.2.3-py35_0\\Lib/site-packages/anaconda_navigator/static/images/spinner-green-16x16.gif', dst='C:\\Anaconda3\\Lib/site-packages/anaconda_navigator/static/images/spinner-green-16x16.gif', type=1, error=CondaOSError: OS error: win32 hard link failed
)

Thoughts?

**Comment by kalefranz** [comment]
I guess we don't have a full stack trace?  The first thing I'd check is that the file actually exists.  It's also possible that the mixed `\` and `/` are causing a problem somewhere.  But without a full stack trace I don't know where to fix that.
