### ISSUE TITLE
Please update PyQt4 to at least 4.11.1

### ISSUE THREAD

**Issue by pmagwene** [ContinuumIO/anaconda-issues#190]
The current default PyQt4 included with Anaconda is 4.10.4. I've run into a PyQt bug involgving QtPainter that appears to be fixed in the latest builds of PyQt4 (i.e. 4.11+).

Might an upgrade of PyQt4 be in the works?

**Comment by ccordoba12** [comment]
This was fixed in Anaconda 2.2. Please update to it :-)
