### ISSUE TITLE
ipython stops responding after suspending with ctrl-z

### ISSUE THREAD

**Issue by jesaerys** [ContinuumIO/anaconda-issues#191]
With other python+ipython installations (e.g., using homebrew), I can suspend a terminal ipython session with `ctrl-z`, work in the shell for a bit, and then come back to ipython with `fg`. This does not work with ipython in anaconda. I never get my prompt back after typing `fg` (even after pressing `enter` and `ctrl-c` a few times), so I have to `ctrl-z` back to the shell and then kill the ipython process.

Is this a bug?

`ctrl-z` and `fg` work just fine for the regular python interpreter in anaconda.

I'm on Mac OS 10.9.

**Comment by keflavich** [comment]
I had asked a question about this [here](http://stackoverflow.com/questions/27041268/sending-ipython-to-the-background-with-control-z/34588001#34588001) (after this issue was raised... so I just missed it when googling or it wasn't indexed yet), and the answer in this thread worked for me.

**Comment by ideascidata** [comment]
I realize this is a blast from the past...but I finally was able to figure out a working solution in Anaconda!

CTRL+S worked for me when using jupyter notebook **with Anaconda.**

You must use this key combo in the terminal for this to work. Also, other key combinations that didn't work for me but were suggested elsewhere include: CTRL+Z and CTRL+I

Hopefully this can at least help out someone down the line...
