### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by LoFaiTh** [ContinuumIO/anaconda-issues#1922]
The following errors occured:

RuntimeError:
Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/win-64/hdf5-1.8.16-vc14_0.tar.bz2

{'language': 'zh_CN', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 70 Stepping 1, GenuineIntel', 'qt': '4.8.7', 'pyqt': '4.11.4', 'python': '3.5.2', 'version': '1.2.1', 'platform': 'win-64', 'conda': '4.1.6'}

**Comment by goanpeca** [comment]
@LoFaiTh you have a very old version of Navigator. I recommend you update to the latest Anaconda Installer (4.4) released this week.

https://www.continuum.io/downloads
