### ISSUE TITLE
No launcher icons

### ISSUE THREAD

**Issue by haicen** [ContinuumIO/anaconda-issues#1923]
I have just installed the anaconda package Anaconda3-4.4.0-Linux-x86_64.sh. I can launch spyder and navigator from the terminal, but that is rather annoying. I attempted to create my own spyder.desktop shortcut, but that doesn't seem to work.

OS: Debian GNU/Linux 8 (jessie) 64-bit (Gnome Version 3.14.1)

**Comment by goanpeca** [comment]
@haicen we are working on this for a next release
