### ISSUE TITLE
netcdf4 broken

### ISSUE THREAD

**Issue by hazbottles** [ContinuumIO/anaconda-issues#1945]
conda install netcdf4

Seems to be broken

    $ python
    >>> import netCDF4
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/accounts/hjack/local/miniconda2/envs/tester/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>    
    from ._netCDF4 import *
    ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory

If I use conda-forge (in a fresh environment) it all seems ok:
    
    conda install -c conda-forge netcdf4

    >>> import netCDF4
    >>> # no error

**Comment by nehaljwani** [comment]
I am able to reproduce this. 
```
(root) [agent@zypher ~]$ conda create -yn 1945 netcdf4 python=3

(root) [agent@zypher ~]$ source activate 1945

(1945) [agent@zypher ~]$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nwani/m3/envs/1945/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory
>>>

(1945) [agent@zypher ~]$ ldd $CONDA_PREFIX/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-x86_64-linux-gnu.so | grep jpeg
	libjpeg.so.8 => not found
	libjpeg.so.9 => /home/nwani/m3/envs/1945/lib/python3.6/site-packages/netCDF4/../../../././libjpeg.so.9 (0x00007f301c3c9000)
```

Related: https://github.com/ContinuumIO/anaconda-issues/issues/1346#issuecomment-283768822

**Comment by naught101** [comment]
See also https://github.com/jswhit/pygrib/issues/55

**Comment by jklymak** [comment]
I have this bug as well.  Using `conda-forge` is fine as a workaround, but...

See also: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/39XFO8Hf4lM

**Comment by msarahan** [comment]
Please test using packages from the c3i_test2 channel on anaconda.org.  These are the packages that will make up the looming anaconda 5.0 release, due later today or tomorrow.

**Comment by remkade** [comment]
Closing as fixed, please reopen if you see this issue again with the latest packages.
