### ISSUE TITLE
Anaconda 4.4 Upgrade Not working

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#1957]
Windows 8.1
Anaconda 4.4 Python 3.6, 64 bit
Selected - paths not to be set
Installed for local user and non Administrator

I tried to upgrade my working installation with the latest 4.4, using conda update etc
It failed to work fully, so I removed Anaconda and clean installed a fresh download of Anaconda 4.4 Python 3.6

conda list worked and I can run Python from the Anaconda prompt

Using Windows Start Menu the following works:
Cloud, Navigator (partially), Anaconda Prompt, Ipython, Jupyter Qt Console, Spyder

Jupyter just opens a blank page at localhost:8888/
I have tried to add the Jupyter token to it but Google Search intervenes.
It did eventually open Jupyter once.

Using Navigator,
It opens, but none of the icons eg Spyder, Jupyter finish loading anything.
They start to open the programs but just stop half way.

Shoud I add the normal Python paths (if so which?) and reinstall?
Should I run anacond-clean first?
Should I just go back to the Anaconda version that worked.?

**Update:**

I uninstalled and reinstalled, but selected Anaconda to set paths and had my anti-virus shut down.
Still not working properly with the same faults as before. (The navigator program icons do not load programs)

When I looked at the paths it had added C:\Anaconda 3 , \Scripts and \Library\bin - OK

However it had added bogus paths that do not have any associated files:

C:\Anaconda3\Library\usr\bin
C:\Anaconda3\Library\mingw -w64\bin
What are these?

When I ran Jupyter from the Windows Start Menu
It opened a blank page localhost:8888/files/myname

I corrected the web page to localhost:8888/tree and jupyter page loaded properly.
Why did a clean install set the wrong webpage URL?

What is in my system that corrupts fresh anaconda installs?
Will anacond-clean remove all past history of previous anaconda installs and give my machine a fresh start?

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
