### ISSUE TITLE
psycopg2 only python 2.7

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/anaconda-issues#197]
psycopg2 claims to be Python 3 compatible 

```
The current psycopg2 implementation supports:

Python 2 versions from 2.5 to 2.7
Python 3 versions from 3.1 to 3.4
PostgreSQL versions from 7.4 to 9.4
```
Source: http://initd.org/psycopg/docs/install.html

Conda disagrees

```
Hint: the following combinations of packages create a conflict with the
remaining packages:
  - psycopg2
  - python 3.3*

Hint: the following combinations of packages create a conflict with the
remaining packages:
  - psycopg2
  - python 2.6*

```

**Comment by ilanschnell** [comment]
I've created psycopg2 2.6 packages for all the Python versions we currently support (2.6, 2.7, 3.3 and 3.4).  They will be available shortly.

**Comment by afonit** [comment]
This is great - I just installed it and it works, thanks for doing this. (py 3.4)

**Comment by ilanschnell** [comment]
Thanks for the feedback, glad it works.
