### ISSUE TITLE
pip-installing PyQt5 in root environment irrevocably breaks all environments?

### ISSUE THREAD

**Issue by BrenBarn** [ContinuumIO/anaconda-issues#1970]
After installing Anaconda, I noticed the conda pyqt package only has Qt 5.6.  I wanted to upgrade, so I did `pip install PyQt5`.  This broke the Qt installation such that apps like Spyder or even the Anaconda Navigator wouldn't load (either hard-crashing or giving a DLL load error).  I tried every conceivable order of uninstalling and reinstalling the PyQt packages from pip and conda, but they didn't work.  Other environments also appeared to be broken.  The only way I could fix it was by uninstalling and reinstalling Anaconda entirely.  (A similar issue was reported in #1554 but that discussion veered somewhat from the core issue of this breakage into a discussion about changing the conda package name.)

It is clear from #1554 that conda PyQt and pip PyQt5 shouldn't be combined in the same environment.  However, being able to break your whole Anaconda installation by doing this seems a bit extreme.  Since pip is unaware of conda but not the other way around, it would seem that the conda PyQt package should provide some kind of "purge" or "clear" option to detect existing pip-installed PyQt and erase it well and good, so that at least the conda PyQt can keep working.

Also, I think the basic documentation (e.g., https://docs.continuum.io/anaconda/ or https://conda.io/docs/using/pkgs.html) should include some more overt warnings about this.  Right now it just says "Others [packages] can be downloaded using the “pip install” command that is included and installed with Anaconda."  This does not make clear that if a package is available from pip *and* from conda, you have to be careful because they will interact in funny ways.  In particular, it doesn't explain what to do if a package is available from both sources, but the conda version is older and you want the newer pip version.  (The answer appears to be "install only the pip version and don't install the conda version before or after or you will break everything", but that's not stated anywhere that I can see.)

**Comment by ccordoba12** [comment]
> the conda PyQt package should provide some kind of "purge" or "clear" option to detect existing pip-installed PyQt and erase it well and good, so that at least the conda PyQt can keep working.

I don't think we could do this because we would have to know in detail how PyQt wheels are packaged (something we are not interested in because we create our own packages), and that could even change from version to version (because it's up to the wheel creator).

> This does not make clear that if a package is available from pip and from conda, you have to be careful because they will interact in funny ways.

I've been warning about this since a couple of months ago. I think the best thing we can do is show a warning to users when they are about to install a package with pip. Something like:

    Use pip packages on your own risk. They could break your Anaconda installation.

> The answer appears to be "install only the pip version and don't install the conda version before or after or you will break everything", but that's not stated anywhere that I can see.

The "break everything" part only happens with PyQt5, as far as I know. Most pip packages should be harmless because they are pure Python. Problems happen when they contain C/C++ libraries. Installing them will probably break your installation (that includes Numpy, Pandas, Matplotlib and Pyzmq).

----

Pinging @csoja about this problem. Crystal, what do you think we should do in this case? This is becoming more and more common with time, i.e. people mixing pip and conda packages without being aware of the potential consequences.

**Comment by BrenBarn** [comment]
Is it possible to show a message like that with pip?  It seems like that would require some kind of custom version of pip.  And if we could do that, we could maybe do something even smarter (like check if the package is actually available in conda).

I think it is a bit optimistic to say that "most" pip packages should be harmless.  There are tons of pip packages out there.  Also, even if a package in itself is harmless, it may list a pip version of a conda-maintained package as a dependency, which will also spell doom.

Part of the problem is that pip (still?  is this true?) has no way to do a "dry run" which tells what is going to be installed before actually installing it.  As a result, installing a pip package can be a leap of faith.  But just saying "never install any pip packages" seems rather extreme, since there are still way more pip packages than conda packages.  It would be nice if there were some more happy medium.

**Comment by ccordoba12** [comment]
> Is it possible to show a message like that with pip?

That's my suggestion, but I'm not in charge to take that decision.

> check if the package is actually available in conda

Against all possible (80.000) pip packages? That seems like a lot of work! I think the warning is enough.

> I think it is a bit optimistic to say that "most" pip packages should be harmless

The biggest problem is with packages that come with precompiled libraries (like the ones I mentioned above). For the rests there is (essentially) no difference between a conda and a pip package.

> But just saying "never install any pip packages" seems rather extreme

I'm not saying that. I'm saying that you have to know very well what pip packages you are installing and be aware that they could break your installation. But we wouldn't forbid pip-installation, just show a warning.

**Comment by bryevdv** [comment]
> I think it is a bit optimistic to say that "most" pip packages should be harmless

FWIW I have been pip installing *pure-python* packages into conda envs for 4+ years without incident.

**Comment by tlambert03** [comment]
I know this is a closed topic, but just wanted to provide a minimum working example and a "fix" for anyone who may be affected by this.  Though it really seems like it, I think `pip install pyqt5` is not breaking the entire anaconda installation after all... but `conda clean --tarballs` is required to fix it.    

example below:

```bash
# create fresh environment for testing pyqt
$ conda create -n qttest1 python=3.6 pyqt
$ source activate qttest1
$ conda list qt
# packages in environment at ~/anaconda/envs/qttest1:
#
pyqt                      5.6.0                    py36_2  
qt                        5.6.2                         2  
# works:
$ python -c "from PyQt5 import QtCore; print(QtCore.__file__)"
~/anaconda/envs/qttest1/lib/python3.6/site-packages/PyQt5/QtCore.so

# now switch to pip PyQt5
$ conda uninstall pyqt qt -y
$ pip install pyqt5
$ conda list qt
# packages in environment at ~/anaconda/envs/qttest1:
#
PyQt5                     5.9                       <pip>
# works:
$ python -c "from PyQt5 import QtCore; print(QtCore.__file__)"
~/anaconda/envs/qttest1/lib/python3.6/site-packages/PyQt5/QtCore.so

# try to switch back, breaks...
$ pip uninstall pyqt5
$ conda install pyqt
$ conda list qt
# packages in environment at ~/anaconda/envs/qttest1:
#
pyqt                      5.6.0                    py36_2  
qt                        5.6.2                         2  
# broken
$ python -c "from PyQt5 import QtCore; print(QtCore.__file__)"
Segmentation fault: 11

# try to create a new environemnt:
$ conda create -n qttest2 python=3.6 pyqt
$ source activate qttest2
$ conda list qt
# packages in environment at ~/anaconda/envs/qttest2:
#
pyqt                      5.6.0                    py36_2  
qt                        5.6.2                         2  
# STILL broken:
$ python -c "from PyQt5 import QtCore; print(QtCore.__file__)"
Segmentation fault: 11

# have to clean tarballs to fix it... pip cache does not seem to matter
$ conda clean --tarballs
$ conda create -n qttest3 python=3.6 pyqt
# works again...
$ python -c "from PyQt5 import QtCore; print(QtCore.__file__)"
~/anaconda/envs/qttest3/lib/python3.6/site-packages/PyQt5/QtCore.so

# but uninstalling and reinstalling pyqt qt in the broken qttest2 environment
# doesn't seem to fix that environment...

```

**Comment by BrenBarn** [comment]
@tlambert03 : Thanks, that is good to know.  Are you saying that the fix only makes it so you can create a new environment with a working PyQt, but still irrevocably breaks any existing environments that had PyQt?  Also, what happens if you pip-installed PyQt into the *root* environment?

Incidentally, I still don't really understand why this issue was closed, because I don't see that any resolution was achieved.  As far as I'm concerned if you can irreparably break even a single environment by using pip, with no warning displayed, then that is a flaw in Anaconda.  If using pip is dangerous in an Anaconda environment then either: A) there should be a bright red warning in [the docs](https://conda.io/docs/user-guide/tasks/manage-pkgs.html) saying "NEVER USE PIP TO INSTALL A PACKAGE IF A CONDA PACKAGE IS AVAILABLE, IT MAY BREAK YOUR ENVIRONMENT"; or B) a warning should be displayed when you actually use pip.  Ideally both.  Absent that, I don't see how this is issue is fixed (or invalid).  The apparent "answer" seems to be "don't use pip for certain packages", but as far as I can see there's no documentation of this anywhere, nor any explicit statement of which packages are dangerous to pip-install, allowing people to break their environments without realizing what they're doing.

**Comment by tlambert03** [comment]
> @BrenBarn: Are you saying that the fix only makes it so you can create a new environment with a working PyQt, but still irrevocably breaks any existing environments that had PyQt?

I was unable to figure out a way to fix any existing environments if they were created _after_ `pip install pyqt5` was installed but _before_ `conda clean --tarballs`.  In those environments, even uninstalling and reinstalling pyqt after tar balls and pip caches have been cleaned still didn't seem to fix it.  

> @BrenBarn: Also, what happens if you pip-installed PyQt into the root environment?

Regarding the root environment.  I just did a quick test: `pip install pyqt5; pip uninstall pyqt5; conda clean --tarballs` ... _seems_ to leave a working installation that lets you create more environments.   At least it's currently working on my system...
