### ISSUE TITLE
Update VS2015 runtime

### ISSUE THREAD

**Issue by scw** [ContinuumIO/anaconda-issues#1974]
The current VS2015 runtime package (`vs2015_runtime`) is shipping the initial release of the Windows 10 SDK , the version which was included with Visual Studio 2015 RTM. The latest update of Visual Studio 2015, Update 3 instead includes Windows 10 SDK 1511, and updated copies of the MSVCR DLLs. These DLLs should be updated, which are bugfix only updates, to fix known Python issues in conda environments which use them. The Update 3 DLLs are shipped in the equivalent [`conda-forge` package](https://github.com/conda-forge/vs2015_runtime-feedstock), but should also make their way out to the defaults channel. Issues resolved by this upgrade include these:
 
 - [Python issue 25023](https://bugs.python.org/issue25023)
 - [Python issue 26624](https://bugs.python.org/issue26624)

MSVC++ Release |MSVCR Version|Windows SDK Version
---------------|----------------|----------------------
2015 RTM    |   14.0.23026     |      1507 (10.0.10240.0)
2015 Update 3 | 14.0.25420 | 1511 (10.0.10586.212)

***Test case and environment***

Note that the UCRT DLLs (ucrtbase.dll plus the stub DLLs) will _not_ be used on Windows 10, which will always use the Windows provided versions of those DLLs. However, on Windows 7 and 8.1, the app-local copies that Conda ships _will_ be used, and are affected by the versions being out of date. A simple test case for these being fixed, as per Python issue 25023:

```python
import locale, time
locale.setlocale(locale.LC_ALL, 'ko')
time.strftime('%a')
```

If correct, it should show the day of the week in Korean. If it's still using the broken DLLs, it will instead return:

    ValueError: embedded null byte

***Source locations***

These should be the locations for the DLLs, here the x64 paths:

Windows 10 SDK: `C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64`
MSVCR:  `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT`

To simply check that the updated DLLs are in use, right click > Properties > Details, and check the "File version" information for ucrtbase.dll (for the UCRT components) or msvcr140.dll (for the MSVCR components).

**Comment by scw** [comment]
I see that last week @ilanschnell uploaded a new package with the updated VS2015 and UCRT components. I've verified this fixes the issue. Thanks Ilan!

I'll leave this open for your own internal verification, but the Python code above no longer throws an error, and I consider this resolved.

**Comment by scw** [comment]
@csoja, actually, I did a little more digging. It looks like while the VS2015 components are updated (e.g. mvscp140.dll), the UCRT components are not. For DLLs like ucrtbase.dll, they still show the version:
  10.0.10240.16384

This is the release that has the problematic behavior, and should be updated. You can test that the issue by doing this from a Windows 7 or 8.1 machine:

```sh
conda create -n vs2015_test python=3.6
```

Then from Python:
```python
import locale, time
locale.setlocale(locale.LC_ALL, 'ko')
time.strftime('%a')
```

**Comment by msarahan** [comment]
The UCRT comes from the Win10 SDK.  It seems like the current Win10 SDK requires VS2017: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

@scw can you comment on what version you're expecting to see, and where you're expecting us to get it from?

**Comment by msarahan** [comment]
Ah, I've just re-read your issue.  I think we actually may need to be packaging other UCRT's, https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

I have no idea how conda can handle this.  Conda has never had a notion of which particular Windows version it's running on.

**Comment by scw** [comment]
@msarahan You don't need to be running on that version of Windows, just to have the relevant UCRT installed as part of the Visual Studio 2015 installation. Here's where you can select the version installed (here showing VS2015 Update 3):

![ucrt-in-vs2015](https://user-images.githubusercontent.com/1314/30000600-831e865a-9040-11e7-810f-4d74ce263119.png)

That should lay down the correct files into the Windows Kits directory, at least it did on my end.

**Comment by msarahan** [comment]
These are updated in the vs2015_runtime packages that will go into the anaconda 5 release.  These packages are at https://anaconda.org/c3i_test/vs2015_runtime/files right now.  @scw do you mind testing these packages?

**Comment by scw** [comment]
Hi @msarahan,

I can confirm that the updated UCRT DLLs are version 10.0.10586.212, and the specific issue here is resolved. I've tested it on multiple Windows 8 machines, including a Japanese installation. Thanks!

While you're updating the package, you may also want to update the MSVC 2015 redistribution, which based on the version included is Update 2 (14.0.23918). The Update 3 version of these DLLs is 14.0.24100.0. I think you'd have to install Visual Studio 2015 update 3 for this. However, I don't know of any specific bugs this fixes with Python, but thought I'd mention it for completeness. The resulting redistributable DLLs are located in

    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT

Cheers,
Shaun

**Comment by msarahan** [comment]
Update 2 is correct. We have needed to downgrade to update 2 because of internal compiler errors while compiling scipy and astropy.

**Comment by scw** [comment]
OK, makes sense. I've also found SciPy to be problematic to compile correctly on Windows, particularly when you need to mix between the VS toolchain and the Intel one at the same time.
