### ISSUE TITLE
conda clean --all   removes   ~/anaconda/pkgs/cache  directory in use by Navigator

### ISSUE THREAD

**Issue by o12johns** [ContinuumIO/anaconda-issues#1977]
1. Double click to open Navigator.app  See six apps in home panel.
2. Do Command/q to quit Navigator
3. Open an Apple Terminal.  Do   conda clean --all -y
4. Once again double click Navigator.app  Now see only three apps.
5. Do Command/q to quit Navigator
5. In Apple Terminal, run navigator-updater.  Let it finish, click dismiss.
6. Double click to open Navigator.app  See the correct six apps back again!

Problem is that   conda clean --all   also deletes directory   ~/anaconda/pkgs/cache   which Navigator is using to store information for its Home screen.  The navigator-updater restores the ~/anaconda/pkgs/cache  directory and its files.  Maybe Navigator developers should rename that directory to something besides "cache"?

**Comment by o12johns** [comment]
At o12johns,
Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/ojohns/anaconda  (writable)
    default environment : /Users/ojohns/anaconda
       envs directories : /Users/ojohns/anaconda/envs
                          /Users/ojohns/.conda/envs
          package cache : /Users/ojohns/anaconda/pkgs
                          /Users/ojohns/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ojohns/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
