### ISSUE TITLE
Anaconda-clean does not clean

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#1990]
Windows 8.1
Anaconda 4.4 Python 3.6, 64 bit
Selected - paths not to be set
Installed for local user and non Administrator

My fresh installation was not working in Navigator - icons did not load programs. I looked at the various config files and saw that paths from older installs were still being referenced and had not been deleted by the fresh install.

I installed anaconda-clean and ran it.
I was asked y/n? to delete . anaconda on to .matplotlib.
I selected y each time.
I re-ran it and it no longer gave me any delete options.

However when I looked in my C:\Users\My_name directory
the .anaconda to .matplot config files were still there, undeleted.

I looked in the hidden file C:\VRoot\Harddisk\Volume4\Users ...\anaconda_backup and the .conda etc files were still intact and undeleted. This backup had information on older installations I had thought long deleted.

So what does anaconda-clean actually do, and how do you ensure getting rid of all past Anaconda history files?

**Comment by goanpeca** [comment]
@joesoap99 you probably need to get rid of all conda config files

.condarc ones
