### ISSUE TITLE
gettext 0.19.8 erroneously bumped libintl shared library version 

### ISSUE THREAD

**Issue by pkgw** [ContinuumIO/anaconda-issues#1995]
Continuum's `gettext` package on OSX provides `libintl.9.dylib` as of version 0.19.8 — previous versions provided `libintl.8.dylib`. But it appears that version bump [was a mistake](https://lists.gnu.org/archive/html/info-gnu/2016-06/msg00006.html) and has been reverted in `gettext` version 0.19.8.1. The `conda-forge` version of gettext is at 0.19.7 which also provides `libintl.8.dylib`.

Have dependent packages been rebuilt to use the newer version of libintl? Well, either way, it would be good to update to 0.19.8.1 ASAP to get back to binary compatibility with everybody else. But if the version bump didn't propagate through the system the problem it will be easier to fix.

(Note that we have no idea when Gettext will decide to actually bump the libintl shared library version, so sticking with the new one doesn't seem like a good option.)

**Comment by mingwandroid** [comment]
What about software we built since then that has the incorrect `SONAME` already in it? Are GNU going to skip that `SONAME`? I really hope so.

**Comment by pkgw** [comment]
Yeah, I'm not sure that undoing the version bump was the best call from the gettext maintainers. But most distros move sufficiently slowly that the erroneous bump probably never made it into their build systems, and it does seem a bit silly to break compatibility for all of those users for no good reason.

**Comment by mingwandroid** [comment]
Fixed.
