### ISSUE TITLE
_sys_version function in platform.py is broken on Windows (python33, 32 bit)

### ISSUE THREAD

**Issue by almarklein** [ContinuumIO/anaconda-issues#2]
Calling platform._sys_version() on Windows raises an exception. Pip uses this function (via platform.python_implementation()) and is therefore broken.

_sys_version uses a regexp to parse sys.version. The regexp that I see in platform.py is different from the one that I see in a "normal" Pythin install (from python.org).

    _sys_version_parser = re.compile(
        r'([\w.+]+)\s*'
        '\|[^|]*\|\s*' # version extra  --> This line seems to have been added
        '\(#?([^,]+),\s*([\w ]+),\s*([\w :]+)\)\s*'
        '\[([^\]]+)\]?', re.ASCII)

I suspect that the regexp was changed in order to parse the modified sys.version string that has the "Continuum Analytics" text in it. However, on Windows `sys.version` does not have this string (it is the same as in the normal interpreter).

If I either change back the regexp, or if I set sys.version to the text "3.3.2 |Continuum Analytics, Inc.| (default, May 17 2013, 11:33:25) \n[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]", then the bug is gone.

**Comment by ilanschnell** [comment]
I can verify that this has been fixed at some point.

**Comment by almarklein** [comment]
I can't remember how I got around this issue, but I certainly have not been bitten by it since. Thanks Ilan.
