### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by colinybrown** [ContinuumIO/anaconda-issues#2013]
The following errors occured:

RuntimeError:
Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/win-64/mysql-connector-python-2.0.3-py35_0.tar.bz2

{'version': '1.2.1', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'qt': '4.8.7', 'pyqt': '4.11.4', 'language': 'en_US', 'platform': 'win-64', 'python': '3.5.2', 'conda': '4.1.6'}

**Comment by goanpeca** [comment]
@colinybrown you have a very old version of Navigator. Please update to the latest version of Anaconda and Anaconda Navigator

**Comment by colinybrown** [comment]
Noted - thanks for fast response.
