### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by colinybrown** [ContinuumIO/anaconda-issues#2014]
The following errors occured:

None:
Package missing in current win-64 channels: 
  - mysql-connector-python ==2.0.4

You can search for packages on anaconda.org with

    anaconda search -t conda mysql-connector-python

{'version': '1.2.1', 'os': 'Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'qt': '4.8.7', 'pyqt': '4.11.4', 'language': 'en_US', 'platform': 'win-64', 'python': '3.5.2', 'conda': '4.1.6'}

**Comment by goanpeca** [comment]
@colinybrown you have a very old version of Navigator. Please update to the latest version of Anaconda and Anaconda Navigator

**Comment by colinybrown** [comment]
Thanks - was using older version for compatibility with other integrated components.  Will workaround.

**Comment by goanpeca** [comment]
You can install environments with packages as old as needed, but for root I recommend you use the latest version (1.6.2 that comes with qt5)
