### ISSUE TITLE
CondaHTTPError

### ISSUE THREAD

**Issue by allaydesai** [ContinuumIO/anaconda-issues#2024]
Hi,

I am unable to use any network capabilities in anaconda. Anytime I try to create an env or upgrade I get the following error. So far I have tried the following things:
- Reinstalled anaconda
- Disabled Firewall
- Add as a trusted application 

All of these with no luck. Really lost here. Would appreciate some help.

(C:\Users\Allay\Anaconda3) C:\WINDOWS\system32>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\Allay\Anaconda3  (writable)
    default environment : C:\Users\Allay\Anaconda3
       envs directories : C:\Users\Allay\Anaconda3\envs
                          C:\Users\Allay\AppData\Local\conda\conda\envs
                          C:\Users\Allay\.conda\envs
          package cache : C:\Users\Allay\Anaconda3\pkgs
                          C:\Users\Allay\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Allay\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.14393
          administrator : True

(C:\Users\Allay\Anaconda3) C:\WINDOWS\system32>conda upgrade conda
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001B09E7A03C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))",),)

**Comment by nehaljwani** [comment]
Are you behind a proxy server?

Share output for:

`conda config --show-sources`

and

`set | findstr /I proxy`

**Comment by allaydesai** [comment]
Thank you for your prompt reply I have been breaking my head over this. I am on my home network with no proxy.

Here are the results:
(C:\Users\Allay\Anaconda3) C:\WINDOWS\system32>conda config --show-sources
==> C:\Users\Allay\.condarc <==
remote_connect_timeout_secs: 60.0
channels:
  - conda-forge
  - defaults


(C:\Users\Allay\Anaconda3) C:\WINDOWS\system32>set | findstr /I proxy

**Comment by nehaljwani** [comment]
Could you also share output for:
`conda config --show`

**Comment by allaydesai** [comment]
Here you go:
(C:\Users\Allay\Anaconda3) C:\WINDOWS\system32>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/msys2: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro", "https://repo.continuum.io/pkgs/msys2"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
envs_dirs:
  - C:\Users\Allay\Anaconda3\envs
  - C:\Users\Allay\AppData\Local\conda\conda\envs
  - C:\Users\Allay\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - C:\Users\Allay\Anaconda3\pkgs
  - C:\Users\Allay\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 60.0
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0

**Comment by nehaljwani** [comment]
Could you also share the output for `set` ? The output will be long, so you can attach it to the comment as a file.

**Comment by allaydesai** [comment]
I would also like to point out that I am able to navigate to the url
https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2
which results in garbage data being displayed proving that connectivity might not be the issue? 
[
[conda_set_output.txt](https://github.com/ContinuumIO/anaconda-issues/files/1056786/conda_set_output.txt)
](url)

**Comment by nehaljwani** [comment]
Can you try the following:

```cmd
set NO_PROXY=repo.continuum.io
conda update conda
```

**Comment by allaydesai** [comment]
It works!!!!! Finally, I spent days looking for a solution. I truly appreciate your help. Just so I understand this, the error seems to be the fact that it was looking for a proxy server? We just turned that setting off?

**Comment by nehaljwani** [comment]
Well, we tried looking in your conda configuration and environment, but I couldn't find trace of any proxy setting. I wonder from where is the requests library picking up proxy. 

If you want to also search other repositories on anaconda cloud, you will have to use:

```cmd
set NO_PROXY=continuum.io,anaconda.org
```

**Comment by allaydesai** [comment]
Ok I just updated it. Thanks for all the help!
