### ISSUE TITLE
conda stack (modules) leading to import error in jupyter notebook

### ISSUE THREAD

**Issue by Moondra** [ContinuumIO/anaconda-issues#2056]
I currently have jupyter notebook installed with two kernels, Python 2 and Python 3. However, I don't have any kernels representing my Conda stack.

When running either kernel, the sys path is leading to python's original exe file

#python 3.6
`import sys
sys.executable`

'C:\\Users\\Moondra\\AppData\\Local\\Programs\\Python\\Python36\\python3.6.exe'

I'm unable to access Conda modules via jupyter notebook. 

I have some modules installed via Conda (due to ease of use) but my Python 3 and Python 2 kernels are throwing import errors when trying to import these specific modules.

Conda seems to have jupyter as well as notebook installed (requirements satisfied), so shouldn't I have a kernel that leads to the anaconda stack? Thank you.

**Comment by csoja** [comment]
If you launch Jupyter from an Anaconda environment or Anaconda Navigator, you'll have the Anaconda stack. Beyond that, this is probably a better question for https://github.com/jupyter/notebook/issues
