### ISSUE TITLE
error when trying to launch anaconda on Windows 8

### ISSUE THREAD

**Issue by Hayat25** [ContinuumIO/anaconda-issues#207]
I have downloaded the anaconda package on windows 8, the download seems to be successful. However, when I try to launch it through the launcher, it gives me the following error: "sorry the application encountered a fatal error. Please report the following to us..."
Is it a windows 8 related problem? how can i fix this?

Thanks in advance,

**Comment by nosregor** [comment]
Hi,
I am a Mac OS X Yosemite with the latest version of Anaconda (python 2.7). I also got  the same errot message:

"Sorry the application encountered a fatal error. Please report the following to us at https://github.com/ContinuumIO/anaconda-issues/"

SyntaxError: Unexpected token <"

What should I do?

**Comment by tswicegood** [comment]
Hey guys!  I'm trying to collect these issues as I go.  I'm actively working on the next version of the Launcher and just as soon as it's read for testing I'll post here with instructions on how to get the latest.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
