### ISSUE TITLE
Spyder IDE is broken in conda

### ISSUE THREAD

**Issue by canesin** [ContinuumIO/anaconda-issues#208]
Because it incompatible with pygments >=2.0 in the IPython console, there is a patch to it in the repository that conda should apply until they didn't release a new version https://code.google.com/p/spyderlib/source/detail?r=fc906f49c9c1

So @asmeurer , continuing the issue attention calling from other issue, please look at #175 , as Cython cannot compile openmp code (the prange) in windows with the supplied gcc.

**Comment by ccordoba12** [comment]
Thanks for reporting. This was fixed in Spyder 2.3.2 (released in December 2014).
