### ISSUE TITLE
UnsatisfiableError When trying to downgrade PyQt from 5 to 4

### ISSUE THREAD

**Issue by uyuyliu831** [ContinuumIO/anaconda-issues#2120]
This is what I got when I tried the command: conda install pyqt=4.11.4
```
Fetching package metadata ............
Solving package specifications: .
UnsatisfiableError: The following specifications were found to be in conflict:
- navigator-updater -> pyqt >=5.6 -> qt5.6.*
- pyqt 4.11.4* -> qt >=4.8.6,<5.0
-pyqt 4.11.4* -> sip >=4.16.4,<4.18
Use "conda info <package>" to see the dependencies for each package.

```
What can I do to downgrade pyqt from 5 to 4 without having weird errors?

**Comment by mingwandroid** [comment]
You need to create a separate environment for it: `conda create -n oldpyqt pyqt=4`

**Comment by uyuyliu831** [comment]
@mingwandroid Thanks a lot Ray. So I just need to run your magic command? or do I need to run create command then run install command?

**Comment by mingwandroid** [comment]
`conda create -n oldpyqt pyqt=4` creates an env called `oldpyqt` and at the same time installs `pyqt4` into it.

After that, you need to activate that env via, e.g. `~/miniconda3/bin/activate oldpyqt`. Please read the docs though.

**Comment by yuriajala** [comment]
If I create a separate environment for pyqt4 will I have access to it while using the main environment just by using `import PyQt4`?
In details:
I have two virtual environments: one with python 2.x and the other 3.x, both currently with pyqt5 as they were created by downloading the whole anaconda package. My goal is to have pyqt5 in the python3 environment and pyqt4 in the python2 environment, along with the other standard packages (scikit, matplotlib, jupyter, etc). If I try to uninstall pyqt5 in the python2 environment, it will also uninstall several other packages (such as spyder, scikit-image, jupyter) that won't be reinstalled with pyqt4. So, is it enough to create another environment for pyqt4 only?
