### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by striatum** [ContinuumIO/anaconda-issues#2122]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py:993: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py:993: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
Could not load properties for 'File'.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'File'.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'File'.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Test & Score'.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.5.0;Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@striatum could you open the terminal and run orange3 from there to get the full stack trace?

**Comment by striatum** [comment]
@goanpeca it's attached! Complains about 
[log.txt](https://github.com/ContinuumIO/anaconda-issues/files/1141440/log.txt)

> SystemError: unable to find to find module: PyQt4.QtCore

**Comment by goanpeca** [comment]
@striatum could you please open a terminal and paste the output of:

```
$ conda info
$ conda list
```

**Comment by striatum** [comment]
`conda info`

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Library/Frameworks/Python.framework/Versions/anaconda  (writable)
    default environment : /Library/Frameworks/Python.framework/Versions/anaconda
       envs directories : /Library/Frameworks/Python.framework/Versions/anaconda/envs
                          /Users/petar/.conda/envs
          package cache : /Library/Frameworks/Python.framework/Versions/anaconda/pkgs
                          /Users/petar/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/petar/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

`conda list`

    # packages in environment at /Library/Frameworks/Python.framework/Versions/anaconda:
    #
    _license                  1.1                      py36_1  
    alabaster                 0.7.10                   py36_0  
    anaconda                  custom                   py36_0  
    anaconda-client           1.6.3                    py36_0  
    anaconda-fusion           1.0.2                    py36_0    anaconda-fusion
    anaconda-navigator        1.6.3                    py36_0  
    anaconda-project          0.6.0                    py36_0  
    anyqt                     0.0.8                    py36_0  
    appnope                   0.1.0                    py36_0  
    appscript                 1.0.1                    py36_0  
    asn1crypto                0.22.0                   py36_0  
    astroid                   1.4.9                    py36_0  
    astropy                   1.3.3               np112py36_0  
    babel                     2.4.0                    py36_0  
    backports                 1.0                      py36_0  
    beautifulsoup4            4.6.0                    py36_0  
    bitarray                  0.8.1                    py36_0  
    blaze                     0.10.1                   py36_0  
    bleach                    1.5.0                    py36_0  
    bokeh                     0.12.3                   py36_0  
    boto                      2.47.0                   py36_0  
    bottleneck                1.2.1               np112py36_0  
    cairo                     1.14.8                        0  
    cffi                      1.10.0                   py36_0  
    chardet                   3.0.4                    py36_0  
    chest                     0.2.3                    py36_0  
    click                     6.7                      py36_0  
    cloudpickle               0.2.2                    py36_0  
    clyent                    1.2.2                    py36_0  
    colorama                  0.3.9                    py36_0  
    conda                     4.3.22                   py36_0  
    conda-env                 2.6.0                         0  
    configobj                 5.0.6                    py36_0  
    contextlib2               0.5.5                    py36_0  
    cryptography              1.8.1                    py36_0  
    curl                      7.52.1                        0  
    cycler                    0.10.0                   py36_0  
    cython                    0.25.2                   py36_0  
    cytoolz                   0.8.2                    py36_0  
    dask                      0.15.0                   py36_0  
    datashape                 0.5.4                    py36_0  
    decorator                 4.0.11                   py36_0  
    dill                      0.2.6                    py36_0  
    docutils                  0.13.1                   py36_0  
    entrypoints               0.2.2                    py36_1  
    et_xmlfile                1.0.1                    py36_0  
    fastcache                 1.0.2                    py36_1  
    filterpy                  0.1.5                     <pip>
    flask                     0.12.2                   py36_0  
    flask-cors                3.0.2                    py36_0  
    font-ttf-dejavu-sans-mono 2.37                          0  
    font-ttf-inconsolata      2.000                         0  
    font-ttf-source-code-pro  2.030                         0  
    font-ttf-ubuntu           0.83                          0  
    fontconfig                2.12.1                        3  
    fonts-continuum           1                             0  
    freetype                  2.5.5                         2  
    geopy                     1.11.0                    <pip>
    get_terminal_size         1.0.0                    py36_0  
    gettext                   0.19.8                        1  
    gevent                    1.2.2                    py36_0  
    glib                      2.50.2                        1  
    glue-core                 0.10.4                   py36_0  
    glue-vispy-viewers        0.7.2                    py36_0  
    glueviz                   0.10.4                   py36_0  
    greenlet                  0.4.12                   py36_0  
    gsl                       2.2.1                         0  
    h5py                      2.7.0               np112py36_0  
    harfbuzz                  0.9.39                        2  
    hdf5                      1.8.17                        1  
    heapdict                  1.0.0                    py36_1  
    html5lib                  0.999                    py36_0  
    icu                       54.1                          0  
    idna                      2.5                      py36_0  
    imagesize                 0.7.1                    py36_0  
    ipykernel                 4.6.1                    py36_0  
    ipython                   6.1.0                    py36_0  
    ipython_genutils          0.2.0                    py36_0  
    ipywidgets                5.2.2                    py36_1  
    isort                     4.2.15                   py36_0  
    itsdangerous              0.24                     py36_0  
    jbig                      2.1                           0  
    jdcal                     1.3                      py36_0  
    jedi                      0.10.2                   py36_2  
    jinja2                    2.9.6                    py36_0  
    joblib                    0.11                     py36_0  
    jpeg                      9b                            0  
    jsonschema                2.6.0                    py36_0  
    jupyter                   1.0.0                    py36_3  
    jupyter_client            5.0.1                    py36_0  
    jupyter_console           5.1.0                    py36_0  
    jupyter_core              4.3.0                    py36_0  
    keyring                   9.3.1                    py36_0  
    lazy-object-proxy         1.3.1                    py36_0  
    libffi                    3.2.1                         1  
    libgcc                    4.8.5                         1  
    libiconv                  1.14                          0  
    libpng                    1.6.27                        0  
    libtiff                   4.0.6                         3  
    libxml2                   2.9.4                         0  
    libxslt                   1.1.29                        0  
    llvmlite                  0.18.0                   py36_0  
    locket                    0.2.0                    py36_1  
    lxml                      3.8.0                    py36_0  
    markupsafe                0.23                     py36_2  
    matplotlib                2.0.2               np112py36_0  
    mistune                   0.7.4                    py36_0  
    mkl                       2017.0.1                      0  
    mkl-service               1.1.2                    py36_3  
    mpmath                    0.19                     py36_1  
    multipledispatch          0.4.9                    py36_0  
    nbconvert                 5.2.1                    py36_0  
    nbformat                  4.3.0                    py36_0  
    ncurses                   5.9                          10  
    networkx                  1.11                     py36_0  
    nltk                      3.2.4                    py36_0  
    nose                      1.3.7                    py36_1  
    notebook                  4.2.3                    py36_0  
    numba                     0.33.0              np112py36_0  
    numexpr                   2.6.2               np112py36_0  
    numpy                     1.12.1                   py36_0  
    numpydoc                  0.6.0                    py36_0  
    odo                       0.5.0                    py36_1  
    olefile                   0.44                     py36_0  
    openpyxl                  2.4.7                    py36_0  
    openssl                   1.0.2l                        0  
    orange3                   3.4.1                    py36_0  
    packaging                 16.8                     py36_0  
    pandas                    0.20.2              np112py36_0  
    pandoc                    1.19.2.1                      0  
    pandocfilters             1.4.1                    py36_0  
    pango                     1.40.3                        1  
    partd                     0.3.8                    py36_0  
    path.py                   10.3.1                   py36_0  
    pathlib2                  2.2.1                    py36_0  
    patsy                     0.4.1                    py36_0  
    pcre                      8.39                          1  
    pep8                      1.7.0                    py36_0  
    pexpect                   4.2.1                    py36_0  
    pickleshare               0.7.4                    py36_0  
    pillow                    4.1.1                    py36_0  
    pip                       9.0.1                    py36_1  
    pixman                    0.34.0                        0  
    ply                       3.10                     py36_0  
    prompt_toolkit            1.0.14                   py36_0  
    psutil                    5.2.2                    py36_0  
    ptyprocess                0.5.1                    py36_0  
    py                        1.4.34                   py36_0  
    pyasn1                    0.2.3                    py36_0  
    pycosat                   0.6.2                    py36_0  
    pycparser                 2.17                     py36_0  
    pycrypto                  2.6.1                    py36_6  
    pycurl                    7.43.0                   py36_2  
    pyflakes                  1.5.0                    py36_0  
    pygments                  2.2.0                    py36_0  
    pylint                    1.6.4                    py36_1  
    pyopengl                  3.1.1a1             np112py36_0  
    pyopenssl                 17.0.0                   py36_0  
    pyparsing                 2.1.4                    py36_0  
    pyqt                      5.6.0                    py36_2  
    pyqtgraph                 0.10.0                   py36_0  
    pytables                  3.3.0               np112py36_0  
    pytest                    3.1.2                    py36_0  
    python                    3.6.1                         2  
    python-dateutil           2.6.0                    py36_0  
    python.app                1.2                      py36_4  
    pytz                      2017.2                   py36_0  
    pywavelets                0.5.2               np112py36_0  
    pyyaml                    3.12                     py36_0  
    pyzmq                     16.0.2                   py36_0  
    qt                        5.6.2                         2  
    qtawesome                 0.4.4                    py36_0  
    qtconsole                 4.3.0                    py36_0  
    qtpy                      1.2.1                    py36_0  
    readline                  6.2                           2  
    redis                     3.2.0                         0  
    redis-py                  2.10.5                   py36_0  
    requests                  2.14.2                   py36_0  
    rope                      0.9.4                    py36_1  
    ruamel_yaml               0.11.14                  py36_1  
    scikit-image              0.13.0              np112py36_0  
    scikit-learn              0.18.1              np112py36_1  
    scipy                     0.19.0              np112py36_0  
    seaborn                   0.7.1                    py36_0  
    setuptools                27.2.0                   py36_0  
    simplegeneric             0.8.1                    py36_1  
    singledispatch            3.4.0.3                  py36_0  
    sip                       4.18                     py36_0  
    six                       1.10.0                   py36_0  
    snowballstemmer           1.2.1                    py36_0  
    sockjs-tornado            1.0.3                    py36_0  
    sphinx                    1.6.2                    py36_0  
    sphinxcontrib             1.0                      py36_0  
    sphinxcontrib-websupport  1.0.1                    py36_0  
    spyder                    3.1.4                    py36_0  
    sqlalchemy                1.1.11                   py36_0  
    sqlite                    3.13.0                        0  
    statsmodels               0.8.0               np112py36_0  
    sympy                     1.0                      py36_0  
    terminado                 0.6                      py36_0  
    testpath                  0.3.1                    py36_0  
    tk                        8.5.18                        0  
    toolz                     0.8.2                    py36_0  
    tornado                   4.5.1                    py36_0  
    traitlets                 4.3.2                    py36_0  
    unicodecsv                0.14.1                   py36_0  
    wcwidth                   0.1.7                    py36_0  
    werkzeug                  0.12.2                   py36_0  
    wheel                     0.29.0                   py36_0  
    widgetsnbextension        1.2.6                    py36_0  
    wrapt                     1.10.10                  py36_0  
    xlrd                      1.0.0                    py36_0  
    xlsxwriter                0.9.6                    py36_0  
    xlwings                   0.10.4                   py36_0  
    xlwt                      1.2.0                    py36_0  
    xz                        5.2.2                         1  
    yaml                      0.1.6                         0  
    zeromq                    4.1.3                         0  
    zlib                      1.2.8                         3

**Comment by goanpeca** [comment]
@striatum seems you have another python version installed with qt also and that seems to be currently picked first, so some path issues I am afraid.

```/Library/Frameworks/Python.framework/Versions/anaconda/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
```
?

**Comment by goanpeca** [comment]
@ccordoba12 thoughts?

**Comment by striatum** [comment]
@ccordoba12, @goanpeca 

As I said I did clean install from scratch. Previously I had issues with anaconda-navigator and that was the reason to reinstall, as advised.
