### ISSUE TITLE
Navigator channel management is awry

### ISSUE THREAD

**Issue by BrenBarn** [ContinuumIO/anaconda-issues#2127]
If I use the "Channels" button in Anaconda Navigator to manage channels, I can't find any way to reorder the channel priority.  If I add a new channel, it always seems to go to the top of the list.  I think I came close to causing serious problems by adding conda-forge, then trying to install something, and finding that it wanted to downgrade conda itself.  I thought was suspicious so held off, but it seems like it would be easy to screw up your environment really bad this way.

To fix it, I had to manually edit .condarc to reorder the channels.

It's dangerous to provide a UI for adding channels without providing a UI to set their priority, and doubly dangerous if newly added channels go to the highest priority.  There needs to be a way to reorder channel priority in the UI.

In addition, the [documentation](https://docs.continuum.io/anaconda/navigator/tutorials/manage-channels) describes a way of disabling channels by unchecking a checkbox, but my Anaconda Navigator shows no such checkbox.  The only thing showing on each channel (besides the name and the path to my .condarc) is a trash can icon to delete the channel altogether.

**Comment by goanpeca** [comment]
Issue moved to [ContinuumIO/navigator #1366](https://github.com/ContinuumIO/navigator/issues/1366) via [**ZenHub**](https://www.zenhub.com/)

**Comment by goanpeca** [comment]
tracking on the internal repo
