### ISSUE TITLE
Error when trying to run launcher

### ISSUE THREAD

**Issue by vanem** [ContinuumIO/anaconda-issues#213]
Os: Windows 7 Professional x64
I've installed Anaconda 32 bit in c:\python, and I also unchecked both "set path..." and "set registry..."

I get the error below when I try to run Start/All Programs/Anaconda (32 bit)/Launcher:
![anaconda_error](https://cloud.githubusercontent.com/assets/5991324/5180147/0e6d769a-7491-11e4-9973-201359209455.jpg)

If I click OK, another popup menu offers to restart the launcher, and the error cycle repeats itself

**Comment by nubok** [comment]
I also have this error. The reason why I unchecked both boxes is that I don't want Anaconda to interfere with my default python installations.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by kflu** [comment]
I can confirm that after updating launcher this issue was resolved.

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
