### ISSUE TITLE
Anaconda Launcher Fatal Error

### ISSUE THREAD

**Issue by ghost** [ContinuumIO/anaconda-issues#215]
Hi!  I just installed Anaconda on a 64-bit Windows 7 (Version 6.1, Build 7601: Service Pack 1) machine.  I tried to start Launcher from the programs menu and got the following error message: "Sorry, the application encountered a fatal error.  Please report the following to us at https://github.com/ContinuumIO/anaconda-issues."  I am brand new to Anaconda and have no idea how to proceed.  Do I need to uninstall and try again?  I uninstalled, rebooted, and reinstalled Anaconda.  It didn't work, same error, so now what?  I appreciate any assistance you can give me.  Thanks!

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by tanmaythakar4** [comment]
suddenly I get same error ...please help me my project is on python so i need help ASAP...
can't able update 'conda' is not recognize ..

**Comment by RatulGhosh** [comment]
I am getting the same error even after installing the new version.

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
