### ISSUE TITLE
Can't open anaconda-navigator

### ISSUE THREAD

**Issue by PyAntony** [ContinuumIO/anaconda-issues#2153]
whenever I click the desktop app it says:

Navigator Error
An unexpected error occurred on Navigator start-up

I have Windows 10.

**Comment by goanpeca** [comment]
@PyAntony please open the anaconda prompt and type

`anaconda-navigator` and paste any traceback

**Comment by PyAntony** [comment]
1) Jupyter Notebook doesn't launch from cmd, but it does by clicking the desktop app. I've tried using PATH but it doesn't work. See trace back from cmd:

C:\Users\agd10>jupyter notebook
'jupyter' is not recognized as an internal or external command,
operable program or batch file.

2) Anaconda Navigator doesn't launch from cmd. Desktop app doesn't work either. See trace back from cmd:

C:\Users\agd10> anaconda-navigator
'anaconda-navigator' is not recognized as an internal or external command,
operable program or batch file.

3) 'conda' commands don't work:

C:\Users\agd10>conda --version
'conda' is not recognized as an internal or external command,
operable program or batch file.

I have uninstall and reinstall anaconda and nothing changes. I have also install anaconda in another windows computer and the same happens. Anaconda used to work perfect about a year ago, but now it seems to dislike Windows 10...

**Comment by goanpeca** [comment]
@PyAntony you need to start the `Anaconda Prompt` not a normal windows console

**Comment by PyAntony** [comment]
2 issues:

1) I found Anaconda Prompt and Jupyter Notebook launches from there. No problem. When was this change released? I was not aware there was such a thing as "Anaconda Prompt". Is it deliberate that jupyter notebook doesn't launch from normal cmd anymore?

2) conda commands still don't work from Anaconda Prompt. When I type "anaconda-navigator" the anaconda icon appear and says "initializing", but then a "navigation error" tab appear. Please see traceback from Conda Prompt:

(C:\USERS\AGD10\ANACONDA3) C:\Users\agd10>anaconda-navigator
2017-06-11 15:03:50,890 - WARNING conda_api.communicate:228
Conda command output on stderr {/'command/': /'conda info --json/', /'stderr/': 'usage: CONDA-script.py [-h] [-V] command .../r/nCONDA-script.py: error: argument command: invalid choice: /'C:////USERS////AGD10////ANACONDA3////SCRIPTS////CONDA-script.py/' (choose from /'info/', /'help/', /'list/', /'search/', /'create/', /'install/', /'update/', /'upgrade/', /'remove/', /'uninstall/', /'config/', /'clean/', /'package/')/r/n'}

An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\USERS\AGD10\ANACONDA3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

2017-06-11 15:03:51,938 - WARNING conda_api.communicate:228
Conda command output on stderr {/'command/': /'conda info --json/', /'stderr/': 'usage: CONDA-script.py [-h] [-V] command .../r/nCONDA-script.py: error: argument command: invalid choice: /'C:////USERS////AGD10////ANACONDA3////SCRIPTS////CONDA-script.py/' (choose from /'info/', /'help/', /'list/', /'search/', /'create/', /'install/', /'update/', /'upgrade/', /'remove/', /'uninstall/', /'config/', /'clean/', /'package/')/r/n'}



Also, conda commands don't work. For example, when I type "conda --version", "conda --info", or "conda info", this shows:

(C:\USERS\AGD10\ANACONDA3) C:\Users\agd10>conda --version
usage: CONDA-script.py [-h] [-V] command ...
CONDA-script.py: error: argument command: invalid choice: 'C:\\USERS\\AGD10\\ANACONDA3\\SCRIPTS\\CONDA-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

(C:\USERS\AGD10\ANACONDA3) C:\Users\agd10>conda --info
usage: CONDA-script.py [-h] [-V] command ...
CONDA-script.py: error: argument command: invalid choice: 'C:\\USERS\\AGD10\\ANACONDA3\\SCRIPTS\\CONDA-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

(C:\USERS\AGD10\ANACONDA3) C:\Users\agd10>conda info
usage: CONDA-script.py [-h] [-V] command ...
CONDA-script.py: error: argument command: invalid choice: 'C:\\USERS\\AGD10\\ANACONDA3\\SCRIPTS\\CONDA-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

**Comment by goanpeca** [comment]
@PyAntony `Anaconda Prompt` has existed for a long time and is the correct way of using Anaconda. Looks like you have a broken install somehow. You should reinstall for current user (not all users) and use the default options.

**Comment by PyAntony** [comment]
I have uninstall and install Anaconda again following all steps indicated in web page (“Just Me”, not adding Anaconda to the PATH, etc.) and the problems still persist. I am testing my installation indicated in web page:

- TYPE "python" in normal cmd:

C:\Users\agd10>python
'python' is not recognized as an internal or external command,
operable program or batch file.

- TYPE "conda list" in normal cmd:

C:\Users\agd10>conda list
'conda' is not recognized as an internal or external command,
operable program or batch file.

- TYPE "conda list" in Anaconda Prompt:

(C:\USERS\AGD10\ANACONDA3) C:\Users\agd10>conda list
usage: CONDA-script.py [-h] [-V] command ...
CONDA-script.py: error: argument command: invalid choice: 'C:\\USERS\\AGD10\\ANACONDA3\\SCRIPTS\\CONDA-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

I am following all steps for installation and there seems to be no problems during installation; again, I did the same installation in another "brand new" laptop with window 10 and the same problems appear. There should be other windows users with the exact same problem. Please help...

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by scramblingbalam** [comment]
I'm having a similar problem, on Windows: 10 home,  Version: 1607, OS build: 14393.1884
I give this info cause it's been a while since I used this machine so maybe I need an update.
I installed Anaconda 5, chose install for all users and it installed with no errors.
Then I clicked on the navigator and  nothing happened
Doing a web search suggested I try launching from Anaconda Prompt
it opens but has a cursor but I can select the window and nothing will type into it nor will it execute what I typed
I'm going to try and reinstall with only the current user selected and see what happens 
but I thought I should share that I couldn't get it to work at all
FYI I also have an older version of Anaconda (2.3.0 installed 
and at first I was just gonna use that and add an environment but while `conda create IIT_in_orgs_Win python=3.6` ran with no errors couldn't switch to it using `activate IIT_in_orgs_Win`

I'm going to uninstall all versions and see if a fresh install of anaconda 5 will solve these problems

**Comment by scramblingbalam** [comment]
Fresh installs seem to have solved both the problem with launching navigator and activating an environment from command line, though I haven't tried power shell yet

**Comment by danieljoche** [comment]
Having a similar problem here. I had these problem during installation of miniconda:

![image](https://user-images.githubusercontent.com/28716168/34323232-97571a90-e826-11e7-92d3-f7f3f51f98f8.png)
I ignored the error and then after that I installed anaconda via cmd with "conda install -c anaconda anaconda-navigator" commmand. but it also have some error:

![image](https://user-images.githubusercontent.com/28716168/34323335-fe1b36f8-e82b-11e7-815f-5acb5991729e.png)

As a result of all that I can't launch neither anaconda-navigator nor Spyder. 

I have already uninstalled everything several times using administrator profile, removing all folder with python/conda names and also the Windows Paths.

Before that I had the version 2 of Python and Anaconda working correctly here, may this have any influence with the current error?

Can someone help me?

**Comment by Adamzynoni** [comment]
i cant open jupyter notebok from anaconda-navigator on my Linux. Any help?
![screenshot from 2018-02-03 09-04-53](https://user-images.githubusercontent.com/5907129/35768449-93774592-08c1-11e8-84dc-7c079244a6b4.png)

**Comment by darshantak** [comment]
If all these methods doesn't work and you want to open .ipnyb files go to pycharm IDE it will surely open all the python notebooks without any errors.

**Comment by goanpeca** [comment]
@Adamzynoni if you launch the jupyter notebook from the terminal directly, do you see any error trace?

```
$ jupyter notebook
```

**Comment by gautamanandniam09** [comment]
> i cant open jupyter notebok from anaconda-navigator on my Linux. Any help?
> ![screenshot from 2018-02-03 09-04-53](https://user-images.githubusercontent.com/5907129/35768449-93774592-08c1-11e8-84dc-7c079244a6b4.png)

It is Kali Linux and you need to add --allow-root to lauch the jupyter notebook from terminal. Full code as jupyter-notebook --allow-root

**Comment by samathmika** [comment]
When I type the commmand anaconda-navigator in the anaconda prompt, i get this!

'anaconda-navigator' is not recognized as an internal or external command,
operable program or batch file.

What is to be done?

**Comment by akansha-sharma12** [comment]
I am using Linux mint 19 when I write anaconda navigator into my terminal, the kind of error it shows -:
(base) akansha@akansha:~$ anaconda navigator
usage: anaconda [-h] [--disable-ssl-warnings] [--show-traceback] [-v] [-q]
                [-V] [-t TOKEN] [-s SITE]
                ...
anaconda: error: argument : invalid choice: 'navigator' (choose from 'auth', 'label', 'channel', 'config', 'copy', 'download', 'groups', 'login', 'logout', 'move', 'notebook', 'package', 'remove', 'search', 'show', 'upload', 'whoami').
what needs to be done please help ..
