### ISSUE TITLE
Fatal Error Launcher Anaconda 32 bit Windows 8.1 64 bit

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#217]
Just installed the latest Anaconda.
Launcher failed on first run - it could not open a Temp file?
Second time it gave an Alert and asked me to report error.

**Comment by tswicegood** [comment]
Doing some issue gardening.  Is this still and issue @joesoap99?

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
