### ISSUE TITLE
conda install <some-package> seems to produce unsatisfiable dependencies

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/anaconda-issues#218]
Using a fresh install of anaconda, installing some packages seems to produce unsatisfiable dependencies.

To reproduce: start with Windows anaconda installer. Then run:

```
conda update conda
conda update anaconda
conda update --all
```

So far so good. The last command informs user that all packages are already "installed".

Now installing pylint:

```
conda install pylint
```

This forces an update: `requests: 2.4.1-py27_0 --> 2.4.3-py27_0`

Running the update all again:

```
conda update --all
```

Results in the user being informed that a hint for unsatisfiable dependencies is created. This process runs over several hours. It is not clear if it ever finishes. Using `--alt-hint` produces a slew of clearly non-applicable hints.

**Comment by csoja** [comment]
Closing as this should already be fixed in more recent releases of conda.
