### ISSUE TITLE
Navigator 1.5 Not Updating to 1.6.2

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#2195]
![untitled picture](https://user-images.githubusercontent.com/8518350/27031142-f8f91914-4f66-11e7-8db6-ec390191d0fb.png)

Navigator asks me to upgrade from 1.5 to 1.6.2.
I agree, and it reports that the Navigator update is complete and to restart application.
When I restart Navigator it is still the 1.5 version, and it asks me again to update and so on with same result.

**Comment by goanpeca** [comment]
@joesoap99 Navigator 1.5.0 had a bug when updating. Please co to the Anaconda prompt and manually update navigator with

```
$ conda update anaconda-navigator
```

**Comment by techscolasticus** [comment]
@goanpeca Thank you very much for the solution. I had the same issue upgrading from 1.6 - 1.6.3.

**Comment by goanpeca** [comment]
@techscolasticus version 1.6.4 fixes this problem.

Coming out soon! thanks for the heads up

**Comment by joesoap99** [comment]
Your fix to upgrade using conda worked in that it upgraded but the navigator icons such as Spyder did not work. The blue line at the bottom right started but it just ended without Spyder loading.
I ran "conda update anaconda" and it reverted my set up back to navigator 1.5 (and downgraded a dozen or so programs). The Spyder etc icons then all worked again to run their respective programs.

The shortcuts in the Windows Start Menu all worked.
The programs all worked when run from a terminal in navigator.

I don't know if upgrade 1.6.4 will fix all these other issues.

**Comment by superbole** [comment]
Thank you @goanpeca for this solution.

I was upgrading to 1.6.4 and it was doing exactly what @joesoap99 originally had. Updating from the conda comand prompt fixed the problem.

**Comment by goanpeca** [comment]
@superbole yes we had a bug on earlier navigator versions. You will need to use the navigator updater package now.

```
$ conda update anaconda-navigator
$ conda install navigator-updater
```

**Comment by joesoap99** [comment]
I upgraded navigator as instructed.
However, now the navigator large icons such as Spyder did not work. The blue bar line at the bottom right indicates loading has started but it just ends without Spyder loading.

My programs such as Spyder all work from the shortcuts in the Windows Start Menu.
The programs all worked when run from a terminal in navigator.

It is just the large icons in Navigator that do not work now.
