### ISSUE TITLE
Navigator Icons Not Working

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#2197]
Windows 8.1 64 bit
Conda 4.3.21
Python 3.6

In Navigator the icons such as spyder start but do not load the programs.
The navigator.log shows this error:

        "level": "ERROR",
        "line": 192,
        "message": "Invalid url https://continuum.io/sites/default/files/Minne.png",
        "method": "_download",
        "module": "download_api",
        "path": "C:/AP34/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2017-06-12 12:51:06,953"

**Comment by goanpeca** [comment]
```
"level": "ERROR",
    "line": 192,
    "message": "Invalid url https://continuum.io/sites/default/files/Minne.png",
    "method": "_download",
    "module": "download_api",
    "path": "C:/AP34/lib/site-packages/anaconda_navigator/api/download_api.py",
    "time": "2017-06-12 12:51:06,953"
```

This is a download error and is harmless.

**Comment by joesoap99** [comment]
Hi,

 

Why have you closed the problem when it has not been solved?

 

Joe
