### ISSUE TITLE
GDAL missing gcs.csv

### ISSUE THREAD

**Issue by kapadia** [ContinuumIO/anaconda-issues#221]
Anaconda's version of GDAL doesn't work as expected. Normally programs such as `gdalwarp` just work. In the case of Anaconda's, the installation is either missing, or hiding some important data files.

This is resolved by following the instructions in the error (`export GDAL_DATA=/path/to/gcs.csv`), but it becomes cumbersome when creating multiple conda environments, all requiring a manual tweak to work correctly.

    > gdalwarp -t_srs epsg:3857 in.tif out.tif
    ERROR 4: Unable to open EPSG support file gcs.csv.
    Try setting the GDAL_DATA environment variable to point to the
    directory containing EPSG csv files.
    ERROR 1: Translating source or target SRS failed:
    epsg:3857

Is there a way to include `gcs.csv` in the Anaconda distribution without having to manually define `GDAL_DATA`?

**Comment by kpurdon** [comment]
This is a pretty major issue for anyone trying to use anaconda. Any updates on the status of this or of any potential alternative solutions available now?

**Comment by kpurdon** [comment]
@tswicegood thanks for talking with me today at PyCon I got some great information from you guys.

I'd love to find a solution (and test @jgomezdans proposed solution) for this and submit it (ideally as a PR to the actual recipe).

* Am I missing the source of the recipe for this? 

If I cant get the source recipe why would I not just try and fix the [recipe here](https://github.com/conda/conda-recipes) and always use the "conda" channel? What is the relationship between Anaconda, binstar(defaults), and binstar(conda)?

**Comment by groutr** [comment]
GDAL has been repackaged into libgdal and gdal (the python bindings).
These changes were introduced for gdal 1.11.2 build >= 2 on windows and >= 1 on unix.

**Comment by ivanmeyer** [comment]
To fix this error do the following steps.

- [ ] go to the activate.d folder of your conda env, this should be something like:

C:\ProgramData\Anaconda2\envs\ _ENV_NAME_ \etc\conda\activate.d

- [ ] Then create a new bat file with the next text:

```
if not defined GDAL_DATA (
  set GDAL_DATA=%~dp0..\..\..\Library\share\gdal
  set _CONDA_SET_GDAL_DATA=1
)
```

This new bat file will replace the text with double quotation marks and a slash after `dp0`, that is shown as follow


```
if not defined GDAL_DATA (
  set GDAL_DATA="%~dp0**\**..\..\..\Library\share\gdal"
  set _CONDA_SET_GDAL_DATA=1
)
```

bye!

**Comment by AgilentGCMS** [comment]
GDAL 3.0.2 is missing a bunch of EPSG csv files such as gcs.csv, coordinate_axis.csv, etc. My GDAL_DATA dir is set correctly, but those csv files are simply not there. I compiled GDAL from source, and those files are not in the source tarball either.

**Comment by mmann1123** [comment]
Yes still having trouble here with GDAL 3.0.2
