### ISSUE TITLE
h5py-HDF5 issue: resource exhaustion issue

### ISSUE THREAD

**Issue by idjibril** [ContinuumIO/anaconda-issues#222]
As mentioned by  https://github.com/garrison in https://github.com/h5py/h5py/issues/480 , 
there is a resource exhaustion issue with HDF5 1.8.13, and updating to HDF5 1.8.14 seems to solve the issue. It would be very helpful to see anaconda updating hdf5 to 1.8.14

**Comment by ilanschnell** [comment]
I'm updating to HDF5 1.8.14 right now.

**Comment by idjibril** [comment]
That's good news! Thanks

**Comment by ilanschnell** [comment]
The new HDF5 1.8.14 has been uploaded and is now available.  However, since those binaries are incompatible with the old ones, I also had to rebuild h5py, pytables, libnetcdf, gdal, netcdf4, ... against those new HDF5 binaries.  So to update, use:
```
conda update h5py
```
