### ISSUE TITLE
Failed to import the side module conda

### ISSUE THREAD

**Issue by Alfreddatui** [ContinuumIO/anaconda-issues#2227]
I tried to to install Anaconda, and it works pretty well. After that, I tried to install some modules and while it is downloading (in command prompt), I accidentally close it.  After that I try to fix it, but no hope. So I uninstall my Anaconda AND DELETE THE PATH IN Control Panel -> System -> Advance System setting -> Enviroment Variables that contain my anaconda. After I install again, It cannot run, the problems are the path. 
Error messsage are : 
Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\alfred.datui\Anaconda\lib\site.py", line 547, in <module>
    main()
  File "C:\Users\alfred.datui\Anaconda\lib\site.py", line 542, in main
    os.environ["PATH"])
  File "C:\Users\alfred.datui\Anaconda\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'

Thanks!

**Comment by nehaljwani** [comment]
@Alfreddatui You deleted the `PATH` environment variable? You probably shouldn't have done that. You only had to remove the path to installation of Anaconda from the `PATH` variable.

**Comment by Alfreddatui** [comment]
@nehaljwani Thanks for the fast reply, Do you have any idea how to fix it ?
After I literally delete the PATH, when I tried to open my Anaconda prompt, this is the error message : 
'chcp' is not recognized as an i
operable program or batch file.
'cmd' is not recognized as an in
operable program or batch file.
'cmd' is not recognized as an in
operable program or batch file.

**Comment by Alfreddatui** [comment]
@nehaljwani 
Thanks guys, I figure it out.
Thanks for your help!

Best Regards,
Alfred
