### ISSUE TITLE
Anaconda navigator error

### ISSUE THREAD

**Issue by 57005** [ContinuumIO/anaconda-issues#2280]
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\mini\AppData\Local\ContinuumIO\binstar\config.yaml", position 0

![image](https://user-images.githubusercontent.com/28647682/27148953-ae0624ce-515f-11e7-9e69-9e0cd1394e53.png)
![image](https://user-images.githubusercontent.com/28647682/27148991-bf6152ca-515f-11e7-9990-fe182f01b9fc.png)

**Comment by goanpeca** [comment]
@57005 just delete the file and try again
Open a windows prompt and type

```
del /f C:\Users\mini\AppData\Local\ContinuumIO\binstar\config.yaml
```
