### ISSUE TITLE
/opt/anaconda1anaconda2/anaconda3 too short in openssl-1.0.1j-1

### ISSUE THREAD

**Issue by rmcgibbo** [ContinuumIO/anaconda-issues#230]
On a linux64 workstation using Miniconda 3.7.3, I'm getting the following odd error. Not sure if this is related to #228, or what.

```
$ conda create -n test python=3.4 openssl
Fetching package metadata: ...
Solving package specifications: .
Package plan for installation in environment /home/rmcgibbo/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.1j             |                1         2.6 MB

The following NEW packages will be INSTALLED:

    openssl:  1.0.1j-1 
    python:   3.4.2-0  
    readline: 6.2-2    
    sqlite:   3.8.4.1-0
    system:   5.8-1    
    tk:       8.5.15-0 
    xz:       5.0.5-0  
    zlib:     1.2.7-0  

Proceed ([y]/n)? y

Fetching packages ...
openssl-1.0.1j 100% |####################################################################################################################################################################| Time: 0:00:04 675.60 kB/s
Extracting packages ...
[      COMPLETE      ] |######################################################################################################################################################################################| 100%
Linking packages ...
Error: ERROR: placeholder '/opt/anaconda1anaconda2anaconda3' too short in: openssl-1.0.1j-1                                                                                                                   |  12%
```

**Comment by jheinen** [comment]
I also have this problem on several Linux systems, e.g. CentOS 5 / 6 / 7, Fedora 20, Ubuntu 14.04, when I try to build a conda package for our GR framework (http://gr-framework.org). Anaconda is installed in /usr/local/anaconda on all of our systems.

    conda build --no-binstar-upload recipe
    BUILD START: gr
    Fetching package metadata: ...
    Solving package specifications: .
    The following NEW packages will be INSTALLED:
    
        openssl:  1.0.1j-4 
        python:   2.7.9-1  
        readline: 6.2-2    
        sqlite:   3.8.4.1-0
        system:   5.8-1    
        tk:       8.5.15-0 
        zlib:     1.2.8-0  
    
    Linking packages ...
    ERROR: placeholder     '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8anaconda9anaconda10anaconda11anaconda12anaconda13an' too short in: openssl-1.0.1j-4

On Mac OS X 10.10, everything works fine.
