### ISSUE TITLE
Update broke entire install

### ISSUE THREAD

**Issue by Pelonza** [ContinuumIO/anaconda-issues#2319]
I tried to update the navigator from inside the navigator and it broke my entire anaconda install (again)... so that none of my other links actually work to even get me to a conda prompt (when I run the short-cuts it says the files aren't there).

I'm just reinstalling... this just reminded me why I try to avoid ever actually updating my anaconda installs...because every time I do it, the install breaks.

**Comment by goanpeca** [comment]
@Pelonza sorry to hear about this :-|, what version did you had originally and what version did you update to?

**Comment by Pelonza** [comment]
I believe I was on 1.4.2 and updated to the most recent. I also realized
while trying to clean things up that one of the issues might have been a
"user" install vs. a "global" install... but I still would have expected
the update run from inside the navigator to not break things...

It also seems that the most recent full version doesn't include a Anaconda
Prompt short-cut?

==================================================
To schedule a meeting or appointment try:
https://karlrbschmitt.youcanbook.me/

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana
==================================================

**Comment by Pelonza** [comment]
Edit:
The fresh install DID include a new "anaconda prompt" link... but when I
updated it without having cleaned the old one off (or deleting the start
menu items) the prompt's link was broken/not re-installed... or at least
seemed not to be.

==================================================
To schedule a meeting or appointment try:
https://karlrbschmitt.youcanbook.me/

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana
==================================================
