### ISSUE TITLE
Jupyter notebook does not launch

### ISSUE THREAD

**Issue by Alhaider** [ContinuumIO/anaconda-issues#2336]
/anaconda/bin/jupyter_mac.command ; exit;
[I 04:05:58.627 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 04:06:05.070 NotebookApp] [nb_anacondacloud] enabled
[I 04:06:05.118 NotebookApp] [nb_conda] enabled
[I 04:06:05.651 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 04:06:05.651 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 04:06:05.752 NotebookApp] Serving notebooks from local directory: /Users/walhaider
[I 04:06:05.752 NotebookApp] 0 active kernels 
[I 04:06:05.753 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=ce88e05c339ff50069a43090135ef6c0a7e44c632cb8e3cd
[I 04:06:05.753 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:06:05.774 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=ce88e05c339ff50069a43090135ef6c0a7e44c632cb8e3cd
0:97: execution error: "http://localhost:8888/tree?token=6fd36bac365bad447fa1796c585b8d54b63dd7db42f50477" doesn’t understand the “open location” message. (-1708)

**Comment by diskandarnerd** [comment]
i have the same problem, where can i find the solution to this?
