### ISSUE TITLE
Unable to access Anaconda 3 or anaconda 2

### ISSUE THREAD

**Issue by saigiridhar92** [ContinuumIO/anaconda-issues#2352]
I tried to install Anaconda-3 4.4.0 today. First, at the last leg of the install, i received errors like "Failed to create Anaconda menus", "Failed to add Anaconda to system path". If I retried, it would not do anything.hence, I ignored it. When I tried to open Anaconda 3 I received the error - "could not find or load the Qt platform plugin "windows in "". 

In the forum, someone suggested to paste "Users/ABC/Anaconda3/Library/plugins/platforms" to "Users/ABC/Anaconda3/". I did that. It successfully allowed to open anaconda 3 navigator. Now I was asked to install jupyter, spyder, etc. When I tried to that, I recieved a new error saying tconda does not have the write permisssion at "Users/ABC/Anaconda3". Now the forums also said that this issue is happening with the new versions. So I went back to Anaconda 3 4.1.1, but now, even that won't work.

What to do?

**Comment by y2kbugger** [comment]
See #732 and #1775
