### ISSUE TITLE
Issue trying to install offline packages involving invalid offline indexes

### ISSUE THREAD

**Issue by tswicegood** [ContinuumIO/anaconda-issues#236]
I have the following in a directory:

```
nose-1.3.4-py27_0.tar.bz2
openssl-1.0.1j-4.tar.bz2
python-2.7.9-1.tar.bz2
readline-6.2-2.tar.bz2
sqlite-3.8.4.1-0.tar.bz2
tk-8.5.15-0.tar.bz2
zlib-1.2.7-1.tar.bz2
```

When I try to install it with the command `conda install --quiet --offline ./packages/*` I receive the following error:

```
depends: [u'python 2.7*', u'openssl 1.0.1*', u'readline 6.2', u'sqlite', u'tk 8.5*', u'zlib 1.2.7']
Fetching package metadata:
Error: No packages found in current osx-64 channels matching: zlib 1.2.7

You can search for this package on Binstar with

    binstar search -t conda zlib 1.2.7

You may need to install the Binstar command line client with

    conda install binstar
```

Note that I've created the `zlib` tarball by zipping up the contents found in `~/anaconda/pkgs/zlib-1.2.7-1`.  On unpacking the tarball and looking at the meta data (and inspecting what's in the package cache) there's no `depends` value which causes it to not be added to the index (see [lines 238-239 on conda/fetch.py](https://github.com/conda/conda/blob/master/conda/fetch.py#L238-L239)).

The reliance on `depends` was added [here](https://github.com/conda/conda/commit/24a6d68f14ef8b3456c57f8bc419070195d089cf) when adding support for using local packages to determine the index, no I'm not sure what the deal is.  I tried the following:
- Remove the check for `depends` and attempt to add everything -- failed (error changed to not being able to find zlib dependency for zlib).
- Adjusted the meta data in the tarball to add an empty `depends` array to `info/index.json` -- success.

Based on this experiment, I believe the correct thing is to rebuild zlib and ensure it has an empty `depends` value in its meta data -- otherwise we have a package that cannot be installed directly from cache in an offline mode.

**Comment by ilanschnell** [comment]
It sounds like you found the answer, i.e. add the `depends` key in `info/index.json`.  The problem with the current implementation of tarball installation is that conda is looking at the dependencies of packages to be installed.  This behavior was deliberately changed, and is now causing the first problems.
Nevertheless, as the dependencies are always installed after the tarballs themselves, you may ignore the error for now.

**Comment by tswicegood** [comment]
@ilanschnell yes -- that solution does work for me on my machine, but it doesn't fix the rest of the `zlib` packages that are installed in every package cache.  I think we need to bump the build number and release another version with the corrected info.  That is, unless it's valid for `depends` to not be there.

I'm not sure why its presence is needed, but it does seem like having conda treat an unset `depends` as an empty array seems reasonable.  Going that route means that we need to release a bug fix version for conda to get this fix in place -- it seems like a better route would be making `zlib` have the proper meta data since it seems that its required.

Regarding ignoring the errors, I can't -- it's a blocker for use with `--offline` which is a requirement for offline conda environments.  I have to have a zlib libraries that works anywhere (or a conda version that's capable of dealing with an unset `depends` value).  There are only three options to make that happen:

* Release an updated zlib with the correct metadata (I'm happy to help with it, but I couldn't get that library to build on OS X) -- requires a release of zlib
* Update `conda` to treat an unset `depends` as an empty array -- requires a release of conda
* Modify conda-env so it attempts to validate the `info/index.json` file and fix the known error -- requires a hack to avoid dealing with the underlying issue the way the first two options do.

As a side note, the [`test/index.json`][2] file includes meta data for zlib that includes `depends`.  Removing that value from the test data causes [this test][3] (along with `test_run` and `test_search`) to fail with a JSON error (I double checked, the JSON is valid).

---

In reading through the code to try to understand what was happening, I'm not sure *why* it ignores packages without `depends`.  [The commit][1] where it was added doesn't shed any light on why its there.  Is there something specific that `depends` provides that an empty array wouldn't deal with?

[1]: https://github.com/conda/conda/commit/24a6d68f14ef8b3456c57f8bc419070195d089cf
[2]: https://github.com/conda/conda/blob/master/tests/index.json#L19990-L19997
[3]: https://github.com/conda/conda/blob/master/tests/test_cli.py#L126-L134

**Comment by ilanschnell** [comment]
I just uploaded new builds (zlib-1.2.7-2), which include the `depends` key.  Maybe changing conda to recognize an unset `depends` as an empty list is also an idea.

**Comment by tswicegood** [comment]
Thanks, @ilanschnell!  I think it makes sense to go at this from both ends so the data we're generating is correct and that conda can handle it gracefully in places it can.

**Comment by tswicegood** [comment]
[Here's a gist][1] of all of the packages in my package cache that do not contain `depends`.  It appears most of them have newer packages, but some do not.  For example, Flask 0.10.1-py27_1 has a `requires`, but no `depends` (side note: py27 is missing, but py34 is not).

[1]: https://gist.github.com/tswicegood/357b1af1f06f44afb708

**Comment by remkade** [comment]
Closing as fixed, please reopen if you find this happening again with the newest packages.
