### ISSUE TITLE
Not able to exit virtualenv anaconda3-4.4.0

### ISSUE THREAD

**Issue by vishesh9494** [ContinuumIO/anaconda-issues#2368]
There has been a recent problem with virtualenv on our machine. Someone globally added a virtual environment of anaconda3-4.4.0 and it not able to decativate now:

    (anaconda3-4.4.0) gpuuser@gpunode:~$ source deactivate
    pyenv-virtualenv: deactivate anaconda3-4.4.0
    (anaconda3-4.4.0) gpuuser@gpunode:~$ 

Please Help!

**Comment by kalefranz** [comment]
Please `conda update conda`.
