### ISSUE TITLE
No module named nlp_utils

### ISSUE THREAD

**Issue by mdivk** [ContinuumIO/anaconda-issues#2372]
from nlp_utils import clean_text, pos_tag_text
sys.path.append("../")
from param_config import config

Traceback (most recent call last):

  File "<ipython-input-6-a5bcef188afd>", line 1, in <module>
    from nlp_utils import clean_text, pos_tag_text

ImportError: No module named nlp_utils

Can anyone help? Thank you very much. This is from Spyder 3.1.4. did I miss anything here?

**Comment by mdivk** [comment]
![screenshot - 6_18_2017 12_19_06 pm](https://user-images.githubusercontent.com/10734547/27262205-cbcb84be-541f-11e7-9496-ff54994c1058.jpg)

**Comment by mdivk** [comment]
![screenshot - 6_18_2017 12_25_43 pm](https://user-images.githubusercontent.com/10734547/27262243-ad8f5fc4-5420-11e7-8f75-6b0a0b2e6d4d.jpg)

**Comment by nehaljwani** [comment]
The code which you are trying to run seems very similar to https://github.com/ChenglongChen/Kaggle_CrowdFlower/blob/master/Code/Feat/preprocess.py#L21-L23

The module you seek to import is also available at: https://github.com/ChenglongChen/Kaggle_CrowdFlower/blob/master/Code/Feat/nlp_utils.py
