### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ScottJones7work** [ContinuumIO/anaconda-issues#2394]
## Main error
The following errors occurred:
## Traceback
```

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
No information was given

---

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```
