### ISSUE TITLE
Conda package build fails on Linux systems

### ISSUE THREAD

**Issue by jheinen** [ContinuumIO/anaconda-issues#241]
I run into the following problem on several Linux systems, e.g. CentOS 5 / 6 / 7, Fedora 20, Ubuntu 14.04, when I try to build a conda package for our GR framework (http://gr-framework.org).

    conda build --no-binstar-upload recipe
    BUILD START: gr
    Fetching package metadata: ...
    Solving package specifications: .
    The following NEW packages will be INSTALLED:
 
        openssl:  1.0.1k-0
        python:   2.7.9-1
        readline: 6.2-2
        sqlite:   3.8.4.1-0
        system:   5.8-1
        tk:       8.5.15-0
        zlib:     1.2.8-0
 
    Linking packages ...
    Error: PREFIX too long: 144 characters, but only 128 allowed
    Error: post-link failed for: openssl-1.0.1k-0                             |  42%
    make: *** [conda] Error 1

On Mac OS X 10.10 (Yosemite) and Windows 8.1, everything works fine.
Anaconda is installed in /usr/local/anaconda on all of our OS X / Linux systems.

There is also an open ticket (Id: 9154528) and a Conda issue (#1087), but I didn't get any answer yet.

Does anyone have an idea how to solve this problem?

**Comment by ccordoba12** [comment]
In conda/conda#1087 you mentioned this was an issue with an outdated `conda-build` version, so I'm closing this one.
