### ISSUE TITLE
Mac Launcher icon doesn't launch launcher

### ISSUE THREAD

**Issue by Back2Basics** [ContinuumIO/anaconda-issues#246]
affecting launcher: 1.0.0-1
On mac: yosemite (but could be more)

Launching launcher from terminal works just fine, but the icon doesn't launch launcher.  (it bounces once)

To re-create run:
"conda uninstall launcher"
delete the icon  from your launcher
"conda install launcher"

"conda update launcher" doesn't have the same effect.

**Comment by Fedster** [comment]
Nope, I tried and it does not work (on OS X 10.10.2):

open /usr/local/anaconda/Launcher.app/
LSOpenURLsWithRole() failed with error -10810 for the file /usr/local/anaconda/Launcher.app.

I refer you to this thread that gives my info:

https://groups.google.com/a/continuum.io/forum/?fromgroups#!topic/anaconda/HmZC0dTBXVA

**Comment by asmeurer** [comment]
That error code apparently means unknown error. Google suggests all different kinds of reasons that it could be happening. Try `conda install -f launcher`.

**Comment by Back2Basics** [comment]
What happens when you type "Launcher<enter>" at a terminal?

**Comment by Fedster** [comment]
> On 2 Feb 2015, at 22:21, Aaron Meurer <notifications@github.com> wrote:
> 
> That error code apparently means unknown error. Google suggests all different kinds of reasons that it could be happening. Try conda install -f launcher.

If I do that it just reinstalls the Launcer, nothing more, no issues sorted.


> 
> —
> Reply to this email directly or view it on GitHub.
> 


--
Federico Calboli
f.calboli@gmail.com

**Comment by Fedster** [comment]
> On 2 Feb 2015, at 22:30, Jeremy Langley <notifications@github.com> wrote:
> 
> What happens when you type "Launcher" at a terminal?

/usr/local/anaconda/Launcher.app/Contents/MacOS/Launcher
/usr/local/anaconda/bin/activate: line 2: conda: command not found
/usr/local/anaconda/bin/activate: line 6: /bin/_conda-env-missing: No such file or directory

(FYI: for a number of reasons I am using Anaconda to get Python 3 and I am keeping the lot out of my PATH)



> 
> —
> Reply to this email directly or view it on GitHub.
> 


--
Federico Calboli
f.calboli@gmail.com

**Comment by Back2Basics** [comment]
Instructions to fix a defunct launcher:
* Delete the defunct launcher off your desktop and out of the dock.
* Update conda using "conda update conda" at the terminal
* You can run "launcher" from the terminal to place this program back in the dock
