### ISSUE TITLE
Latest boost doesn't have boost_iostreams

### ISSUE THREAD

**Issue by Juanlu001** [ContinuumIO/anaconda-issues#247]
Unfortunately if I want to `conda build` a package with this requirement I am forced to build boost myself. Is there a chance the devs can consider rebuilding boost with this extra library? That would ease the installation of FEniCS with these recipes:

http://github.com/juanlu001/fenics-recipes

**Comment by ccordoba12** [comment]
Hola @Juanlu001! I'm in charge of boost these days. I have a couple of questions for you:

1. In which platforms are you building Fenics?
2. Do you know if Boost.iostreams needs some special requirements to be be built?

**Comment by Juanlu001** [comment]
¡Hola @ccordoba12! :)

I am building FEniCS in several different Linux distros, namely Arch Linux, Ubuntu 14.04 Server, Linux Mint 17 and CentOS 6. I have been unable to find a list of requirements per library but installing libbz2 and libicu did the trick.

If I am not mistaken, Anaconda's boost right now provides at least python, filesystem, program_options, system and thread, lacking iostreams. These are the libraries I know I need:

https://bitbucket.org/fenics-project/dolfin/src/376dc2f223cb47291c311c1f3a69898d27c4538f/CMakeLists.txt?at=dolfin-1.5.0#cl-316

I tried the `--with-libraries` option when building boost expecting a failure if the requirements are not met, but it is not the case:

https://github.com/Juanlu001/fenics-recipes/blob/dd76acdebac8a1c18662e81a751468238fe30aea/boost/build.sh#L39

**Comment by ccordoba12** [comment]
Ok, so to make things clear: we need to install libbz2 and libicu before building boost so that iostreams are build, right?

The problem with boost build system is that it's smart enough to build what it can and don't fail if it can't build the rest.

**Comment by Juanlu001** [comment]
On Jan 29, 2015 7:01 PM, "Carlos Cordoba" <notifications@github.com> wrote:
>
> Ok, so to make things clear: we need to install libbz2 and libicu before
building boost so that iostreams are build, right?

Yes, I think so.

>
> The problem with boost build system is that it's smart enough to build
what it can and don't fail if it can't build the rest.

Indeed, for very exotic definitions of "smart"...

**Comment by ccordoba12** [comment]
Ok, thanks for the info. I'll see what I can do about it :-)

**Comment by asmeurer** [comment]
QT does a similar thing. Usually at the end of the configure stage it lists all the features it plans to compile in. It's worth stopping and looking through the list before compiling to make sure everything you want is going to be included.

**Comment by Juanlu001** [comment]
Hello! Is there an ETA for this?

**Comment by ccordoba12** [comment]
Sorry for not working on this one. We were very busy preparing Anaconda 2.2. I'll take a look at this one next week.

**Comment by Juanlu001** [comment]
Great, thanks for your reply! I will gladly beta-test the package once 
it is cooked :)

**Comment by ccordoba12** [comment]
@Juanlu001, I'm working on this right now, so I have a little question for you: is `icu` needed as run time dependency of `boost`? Or is just a build one?

**Comment by Juanlu001** [comment]
To be honest I don't know, I don't see an easy way to test wheter it is or not. I use boost as a dependency so I don't know which kind of functions should I call to see if icu is required in run time or not, sorry to be of little help here :/

I happen to be working on the FEniCS recipes right now so tell me if there is something I can do about this.

**Comment by ccordoba12** [comment]
Please test the package present in my channel

https://binstar.org/ccordoba12

to see if things are working for you. I think icu is just a build dependency ;-)

**Comment by ccordoba12** [comment]
Sorry, I verified that `icu` is needed at least by `boost_regex`, so it's a runtime dependency.

**Comment by ccordoba12** [comment]
Don't worry about testing. I think everything is ready to upload a new `boost` version to the official channels.

**Comment by Juanlu001** [comment]
Cool! For me, if it has iostreams it's perfect :)

**Comment by Juanlu001** [comment]
Hello @ccordoba12, did you finally update a new `boost` version to the official channels with this issue fixed? Just asking so we can close this issue!

**Comment by Juanlu001** [comment]
I just tried rebuilding fenics just in case and saw that `icu` was downloaded, but apparently the problem of `boost_iostreams` still holds:

```
Boost version: 1.57.0

  Boost include path: /home/juanlu/.miniconda3/envs/_build/include

  Could not find the following Boost libraries:

          boost_iostreams

```

**Comment by ccordoba12** [comment]
You're right, `iostreams` is not included in our current package. We're trying to fix the situation :-)

**Comment by Juanlu001** [comment]
Sorry for being a pain in the neck, but I am having another fenics-recipes sprint these days and I wonder what is the status of iostreams in Anaconda boost :) @gmarkall

**Comment by ccordoba12** [comment]
@Juanlu001, I think our latest boost packages (1.57.0-4) solve this issue on Linux 32/64 and Mac.

Please test them and let us know if that's the case

**Comment by Juanlu001** [comment]
On 2015-07-09 15:14, Carlos Cordoba wrote:
>
> @Juanlu001 <https://github.com/Juanlu001>, I think our latest boost 
> packages (1.57.0-4) solve this issue on Linux 32/64 and Mac.
>
> Please test them and let us know if that's the case
>

Success!! :D

```
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   system
--   thread
--   iostreams
```

one warning though: the build system detected version 1.58.0 instead of 
1.57.0. Still, all the required sublibraries are present. Thanks a lot!

**Comment by Juanlu001** [comment]
Closing!

**Comment by shongololo** [comment]
I'm getting this error on Linux Ubuntu with Conda 4.0.6 -> is there a trick to installing boost with iostreams?

**Comment by ccordoba12** [comment]
Please run

    conda install -c conda-forge boost

That should fix your problem :-)
