### ISSUE TITLE
`pinned` package breaks conda install --force option

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/anaconda-issues#249]
If one creates a `pinned` file for a conda environment in which one pins the version of a package `A`'s dependencies, e.g. `B 1.0.0`, one cannot force the install of conflicting version of `A`:

Example:
`numpy` pinned at 1.9.0
`pytables` version to force: 3.0.0

```
[sandbox] C:\Anaconda>conda install --force pytables=3.0.0
Fetching package metadata: ..
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ] |#################################################| 100%


Hint: the following combinations of packages create a conflict with the
remaining packages:
  - numpy 1.9.0
  - pytables 3.0|3.0.0*
```

This result would be expected without the `--force` option, but should not occur with the `--force` option.

If one removes, e.g. `numpy` from the `pinned` file temporarily, one can force the conflicting installation with:
`C:\Anaconda>conda install --no-deps pytables=3.0.0`

The same should be possible with the `--force` option in the presence of a conflicting pinned package.

**Comment by asmeurer** [comment]
There is a `--no-pinned` flag.

**Comment by asmeurer** [comment]
Even so, `--force` shouldn't do any resolution at all. I seem to remember there was a reason why it was done. I don't remember what it was, though.

**Comment by ARF1** [comment]
I saw the `--no-pin` option, but to be honest, I understood that it simply ignores the `pinned` file. The help is not very clear on what it does:

```
--no-pin              don't use pinned packages
```

"Don't use pinned package"? (for what?)

If I am understanding correctly, a better choice would be:
`--no-pin              ignore pinned file`

That being said, `--force --no-pin` solves my problem. Many thanks.

**Comment by asmeurer** [comment]
I fixed the help.
