### ISSUE TITLE
Provide `pytables=3.0.0` for current numpy versions

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/anaconda-issues#250]
`pytables 3.1.*` has a bug with string matching which severely degrades performance in some cases, requiring some projects to remain at version 3.0.0.

Please provide `pytables` at version 3.0.0 for current versions of `numpy` At present, anaconda provides `pytables` only at 3.0.0 for numpy 1.7*. As far as I can see, there is no reason to prevent use with later versions of numpy.

**Comment by nehaljwani** [comment]
`pytables 3.4.2` is available for all `numpy >=1.9.3,<2`
