### ISSUE TITLE
"fatal error" on launcher startup

### ISSUE THREAD

**Issue by wojdyr** [ContinuumIO/anaconda-issues#252]
New Windows 7 machine, fresh Anaconda installation (today), selecting Launcher from the Start menu shows:
![axwoirf](https://cloud.githubusercontent.com/assets/491873/5938057/55bc2d26-a6ef-11e4-953a-45647aae23b3.png)
I'd provide more details, but I don't know where to look for them.

**Comment by tswicegood** [comment]
Hey @wojdyr.  Thanks for the report.  I'm sorry you've having issues with this.  We're in the process of a big update to Launcher (slated for dev release in February) which I'm pretty sure will fix whatever's causing this issue.  I'll post back to this thread with a link once we have a release ready if you would be interested in helping test early releases?

**Comment by wojdyr** [comment]
Sure, why not.
Thanks for your work on Anaconda.

**Comment by hongxiangfei** [comment]
the same error here. looking forward to the update : )

**Comment by AnotherFrustratedLauncher** [comment]
Well, it's February 10th and I'm eagerly awaiting the release.  I'm tired of seeing this launch error and am willing to test.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by Drekko** [comment]
I am getting the same issue
Is there a new launcher update yet for windows ?

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
