### ISSUE TITLE
conda update and conda install not working. HTTP error while trying to retrieve this URL

### ISSUE THREAD

**Issue by Abhi-1729** [ContinuumIO/anaconda-issues#2546]
I am not able to install any package or even update conda. 

I have retied installing it multiple times and also I tried updating the anaconda-navigator as well. Still getting the same error.

Getting the following error:

(C:\Anaconda) C:\Users\av8>conda update conda
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-
64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port
=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Cause
d by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConn
ection object at 0x0000000005540E48>, 'Connection to repo.continuum.io timed out
. (connect timeout=9.15)'))",),)

SYSTEM INFO:

(C:\Anaconda) C:\Users\av8>conda info -a
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
                          C:\Users\av8\AppData\Local\conda\conda\envs
                          C:\Users\av8\.conda\envs
          package cache : C:\Anaconda\pkgs
                          C:\Users\av8\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\av8\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/7 W
indows/6.1.7601
          administrator : True
# conda environments:
#
root                  *  C:\Anaconda

sys.version: 3.6.1 |Anaconda 4.4.0 (64-bit)| (default...
sys.prefix: C:\Anaconda
sys.executable: C:\Anaconda\python.exe
conda location: C:\Anaconda\lib\site-packages\conda
conda-build: None
conda-env: C:\Anaconda\Scripts\conda-env.exe
conda-server: C:\Anaconda\Scripts\conda-server.exe
user site dirs:

**Comment by Abhi-1729** [comment]
Update: Solved the issue.

Defined the proxy in the .condarc file.

**Comment by anitakh1** [comment]
how??

**Comment by ashukrishna100** [comment]
I recently got this issue resolved. Use this command to see proxy_servers
`conda config --show`

If any proxy server is present in the configuration. Kindly use
`conda config --remove-key proxy_servers`. It will remove saved proxy servers from anaconda configuration.
Enter
`conda clean --source-cache`
Now your http error is gone.
Give it a try and let me know in case of any difficulty.
