### ISSUE TITLE
Jupiter Notebook does not launch

### ISSUE THREAD

**Issue by diskandarnerd** [ContinuumIO/anaconda-issues#2554]
Dannys-MBP:~ dannyiskandar$ /anaconda/envs/python2/bin/jupyter_mac.command ; exit;
[I 18:23:04.988 NotebookApp] Serving notebooks from local directory: /Users/dannyiskandar
[I 18:23:04.988 NotebookApp] 0 active kernels 
[I 18:23:04.988 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=204e5a881f1d3d9ca85a53f2ff723780de1b99728df3adee
[I 18:23:04.988 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:23:04.989 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=204e5a881f1d3d9ca85a53f2ff723780de1b99728df3adee
0:97: execution error: "http://localhost:8888/tree?token=8f62cdc70b33d2c109209596f814808beefef7d46575d29f" doesn’t understand the “open location” message. (-1708)

**Comment by striatum** [comment]
I am receiving the same error-message:

> 0:42: execution error: "http://localhost:8888/tree" doesn’t understand the “open location” message. (-1708)

Relevant info:


Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Library/Frameworks/Python.framework/Versions/anaconda  (writable)
    default environment : /Library/Frameworks/Python.framework/Versions/anaconda
       envs directories : /Library/Frameworks/Python.framework/Versions/anaconda/envs
                          /Users/petar/.conda/envs
          package cache : /Library/Frameworks/Python.framework/Versions/anaconda/pkgs
                          /Users/petar/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/petar/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

**Comment by striatum** [comment]
Do we deserve at least some explanation? What to do? Where to go from here?

**Comment by bryevdv** [comment]
This is evidently an issue on Apple's end, that affects the notebook independently of Anaconda. See 

https://github.com/jupyter/notebook/issues/2438

for more detailed investigation.
