### ISSUE TITLE
Installing pyNN package on conda

### ISSUE THREAD

**Issue by PANDORINO** [ContinuumIO/anaconda-issues#258]
Hi, I am a quite inexperienced user and I am trying to install the pyNN package among the conda packages but unfortunately I cannot. I typed 'conda install pyNN' but is not working. I tried looking up online different options but I haven't been able to solve it. Anyone who could help with this? Many thanks

**Comment by asmeurer** [comment]
pyNN is not available as a conda package but you can install it with `pip install pyNN`.

**Comment by ccordoba12** [comment]
That's what I suggested on the Anaconda mailing list. You can also do

    conda install -c trentonoliphant pynn

which is a conda package hosted in binstar.
