### ISSUE TITLE
f2py is hiding somewhere

### ISSUE THREAD

**Issue by kabanovdmitry** [ContinuumIO/anaconda-issues#259]
I installed Anaconda with Python 3.4, but I do not have `f2py` command available. Command

    conda search f2py

gives nothing.

As far as I know, f2py is a part of numpy. Therefore, if I have numpy installed (which is the case) then `f2py` command should be available.

**Comment by ilanschnell** [comment]
Correct, the `f2py` command is part of the `numpy` package.

**Comment by jakevdp** [comment]
Note that with Python 3 you'll want to use ``f2py3`` instead of ``f2py``. Like in Python 2, it is installed automatically as part of the ``numpy`` package.

**Comment by ianhbell** [comment]
(WINDOWS)
Actually, this issue should be reopened.  f2py.py is installed by numpy as a script, but is not accessible as ``f2py`` on the path. In order to run the script, you need to add give the entire path to the script to the python call.  Which is certainly very annoying.
