### ISSUE TITLE
Environments created on Navigator fail to get added to Jupyter Notebook menus

### ISSUE THREAD

**Issue by TheMitchWorksPro** [ContinuumIO/anaconda-issues#2595]
This problem was encountered on a new Macbook Pro today that is running macOS Sierra version 10.12.5.   Install Anaconda, and by default, all the configuration files end up in a hidden folder, but this may reflect changes in the Macintosh design.  They are accessible by a two-finger hot-menu on the icon.

Then if you add an environment using Navigator, the environment does not appear in Jupyter notebook menus for creation of a new notebook.  Finally, using Navigator to add a 2.7 environment to a 3.6 installation, you only get 9 packages installed.  Is this right?  Note that attempting to create the same environment manually from Terminal using the "create" command resulted in an environment with 44 packages.  Using the 'ipykernel' switch still failed to produce an environment that would appear in the Jupyter notebook menus as an option though (even though this trick worked on Windows when I last attempted it with an older release of Anaconda).

These problems were encountered with the latest distribution just downloaded on 6/24/2017 on a Mac that was also brand new.  I troubleshot them with a teacher in a class I am in and he figured out that adding some missing packages with "Jupyter" in the name seemed to fix the issue.  But I think this indicates you might want to fix things in Navigator so the environments just work after people create them.  I say "seemed to" because the different environments only show in menus if I launch the Python 2.7 secondary environment specifically.  If I start Jupyter from either default (3.6) or from a secondary PY36 environment, I get only one option (the current one) for notebooks I can use in Jupyter notebooks.  I would have expected to have access to building notebooks (running notebook kernels) from the Jupyter menus for all of my environments regardless of which environment was used to start it.

**Comment by goanpeca** [comment]
You need to install [the notebooks extensions](https://github.com/Anaconda-Platform/anaconda-nb-extensions)
