### ISSUE TITLE
scipy is broken on Mac OS X

### ISSUE THREAD

**Issue by abergeron** [ContinuumIO/anaconda-issues#26]
You can verify this by running the scipy self-tests:

python -c 'import scipy; scipy.test()'

This is most likely due to a misconfiguration or the fortran compiler which then produces broken fortan interface code.

**Comment by ilanschnell** [comment]
What exactly is broken?  Is it still an issue today (over a year later)?

**Comment by abergeron** [comment]
The brokenness is in the bindings for fortran functions that return floats.  I don't know if it's still an issue as I haven't tested it since reporting.  But if the scipy tests pass then it is fixed.

**Comment by groutr** [comment]
This no longer seems to be an issue.  Tested on OSX 10.10 with scipy 0.15.1
