### ISSUE TITLE
Launcher encountered error

### ISSUE THREAD

**Issue by maitrihegde** [ContinuumIO/anaconda-issues#262]
![error](https://cloud.githubusercontent.com/assets/8629532/6111113/8205fbc0-b0ac-11e4-8e60-cbd19b42e476.png)

The following error occured when i opened the launcher for the first time

**Comment by ccordoba12** [comment]
Sorry for the inconvenience. The launcher is being reworked and a new version will be available in a couple of weeks.

**Comment by dieffenbachia** [comment]
I had the same error upon opening the launcher for the first time

**Comment by AdrianPerju** [comment]
I have the same issue. Threre is a new version in this moment?

**Comment by ccordoba12** [comment]
Not yet.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
