### ISSUE TITLE
Anaconda documentation short coming

### ISSUE THREAD

**Issue by TheMitchWorksPro** [ContinuumIO/anaconda-issues#2623]
The GUI would lead me to believe something I am afraid to try because I can't find any documentation indicating feature support for this.  In Navigator, when you pick an environment, the large tile-icons for applications that are available either for use or to install changes (i.e.: spyder goes from "launch" in your primary environment to "install" in your additional environments).

Does this mean I can install Spyder on multiple environments using Navigator to have the ability to easily switch between Python 2.7 and Python 3.6 in Spyder?  If so, this needs to be documented so I know nothing will get corrupted by attempting it.  Past version of Navigator corrupted my machine if I made assumptions like this, so I am leary to try things without the documentation of to prove my assumptions are correct.

Please advise if I can try this or not.  I am using a Macbook Pro for this installation and just installed Anaconda / Navigator as of June 24th, 2017 (the most current one).

If this is a supported feature, documentation should indicate this.  If it is not a supported feature, you might want to tweak the GUI so users don't make the mistake.  (But I am hoping its a feature that just needs to be in the documentation).

Thanks.

**Comment by goanpeca** [comment]
@TheMitchWorksPro yes, conda environments isolate installations so you can install a different version of Spyder on separate environments.
