### ISSUE TITLE
Navigator startup: byte indices must be integers or slices, not str

### ISSUE THREAD

**Issue by spatrick** [ContinuumIO/anaconda-issues#2647]
Fresh new install of Anaconda3-4.2.0 for 64-bit Linux, on an ubuntu 14.04 machine (therefore, already had python 2.7.6 and 3.4.3 as the most up-to-date versions from default canonical repos). 

trying to run anaconda-navigator at command line briefly brings up logo splashscreen, but then get the following error block in bash console:
```
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/spatrick/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```
Also, invoking python interpreter (which used to work just fine) by using python or python3 at command line now gives this error instead:

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007fd039dda740 (most recent call first):
Aborted (core dumped)
```

However, if I just directly open up, say an IDLE window, or an ipython notebook in Jupyter, or whatever, everything appears to run just fine.

**Comment by goanpeca** [comment]
spatrick it seems conda is not correctly set on your path

**Comment by striatum** [comment]
I am receiving the same error-message:

> 0:42: execution error: "http://localhost:8888/tree" doesn’t understand the “open location” message. (-1708)

Relevant info:


Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Library/Frameworks/Python.framework/Versions/anaconda  (writable)
    default environment : /Library/Frameworks/Python.framework/Versions/anaconda
       envs directories : /Library/Frameworks/Python.framework/Versions/anaconda/envs
                          /Users/petar/.conda/envs
          package cache : /Library/Frameworks/Python.framework/Versions/anaconda/pkgs
                          /Users/petar/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/petar/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

**Comment by striatum** [comment]
I've opened this issue and it got closed. Any advice for us poor users? Thanks!

**Comment by spatrick** [comment]
@goanpeca That was my first thought, too. I just found issue [https://github.com/ContinuumIO/anaconda-issues/issues/1837](url), which I may or may not be a duplicate of. As in that case, I have the line export PATH="~/anaconda/bin:$PATH" in my .bashrc, so ... I think the path is OK? or no?

Anyway, I that issue, you suggested running `$ source activate root` before `$ anaconda-navigator`. That indeed works for me! Even the plain python interpreter works. At least, it's all working while I'm in that root environment.
