### ISSUE TITLE
spacy package is outdated in main conda channel

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#2649]
It seems like there is no recent spacy package in the main conda channel.
The installation instructions on their website suggesting to use conda-forge:
https://spacy.io/docs/usage/

It would be great if there was a recent package available in the main channel, as there have been major changes. In particular downloading language packages is not possible in the same way in the version that's in the main channel.

**Comment by BrenBarn** [comment]
The package has apparently not been updated in conda defaults since this issue was raised, and is now even more woefully out of date.  Can it be updated?

**Comment by angloyna** [comment]
Spacy recently released a patch version 2.3.2 last month, but defaults should now be closer to current now as v2.3.1 is available.
