### ISSUE TITLE
Jupyter Notebook doesnt open

### ISSUE THREAD

**Issue by nikhildamodaran** [ContinuumIO/anaconda-issues#2660]
I have been using Anaconda for sometime. Suddenly Jupyter doesnt launch. I get the following error message. I am operating on Mac OS 10.12.5
```
Nikhils-MacBook-Pro:~ Nick$ /Applications/anaconda/bin/jupyter_mac.command ; exit;
[I 21:56:20.394 NotebookApp] Serving notebooks from local directory: /Users/Nick
[I 21:56:20.395 NotebookApp] 0 active kernels 
[I 21:56:20.395 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=700531ebb89586c2cc0bddf10b53b764463f16c1730fbf7d
[I 21:56:20.395 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:56:20.398 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=700531ebb89586c2cc0bddf10b53b764463f16c1730fbf7d
0:97: execution error: "http://localhost:8888/tree?token=27813922751d245dca576b5e4398cc4421f056e0e18c63dd" doesn’t understand the “open location” message. (-1708)


```

**Comment by tekhneco** [comment]
Same here. Mac OS 10.12.5. Occurred immediately after Apple forced an auto-update upon restart. Now, Anaconda requires URL to open Jupyter. Launch button only activates new terminal window.

`0:97: execution error: "http://localhost:8889/tree?token=77e05c11e9e59320f1add0e8c8f398cada3c531d4e23a2ce" doesn’t understand the “open location” message. (-1708)`

**Comment by jgmorrison** [comment]
A solution is to add the browser to the jupyter_notebook_config.py file:

    jupyter notebook --generate-config

Edit the file output from that command and uncomment the following line and add a browser:

    c.NotebookApp.browser = u'Safari'

You can use 'Safari', 'Firefox', or for chrome the following:

    c.NotebookApp.browser = u'open -a "Google Chrome" %s'

**Comment by mariahakinbi** [comment]
You can also change 

`browser = webbrowser.get(self.browser or None)`

to:

`browser=webbrowser.get("Safari")`

in the notebookapp.py file. This worked for me!

source: https://github.com/jupyter/notebook/issues/2438

**Comment by csoja** [comment]
Thank you for posting the solutions!

**Comment by ChandlerBBT** [comment]
actually, it's just somehow foolish bug created by PC itself, as operating system change the default IE software without any permission granted by you. The fast and useful way to solve this is----just change back to the IE software you used. And then , try again to initiate jupyter notebook in conda/cmd. You will find it works now !
