### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by MrGranddy** [ContinuumIO/anaconda-issues#2677]
## Main error
Application <b>glueviz</b> launch may have produced errors.
## Traceback
```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [Errno 9] Bad file descriptor

Current thread 0x00007fff996a73c0 (most recent call first):
/Users/bugrayesilkaynak/anaconda3/bin/python.app: line 3: 39247 Abort trap: 6           /Users/bugrayesilkaynak/anaconda3/python.app/Contents/MacOS/python "$@"

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.5.0;Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment]
@MrGranddy what version of glueviz?

**Comment by MrGranddy** [comment]
0.10.4

**Comment by goanpeca** [comment]
@astrofrog, thoughts?

**Comment by astrofrog** [comment]
I wonder if it's an issue with python.app - @MrGranddy can you try:

```
python -c 'from glue import qglue; qglue()'
```

Does this start up glue?

**Comment by astrofrog** [comment]
@MrGranddy - thanks, can you now try:

```
python.app -c 'from glue import qglue; qglue()'
```

Any luck?

**Comment by MrGranddy** [comment]
Again same happened, it opens with the warning:
WARNING:glue:Failed to load plugin configuration
/Users/bugrayesilkaynak/anaconda3/lib/python3.6/site-packages/IPython/paths.py:62: UserWarning: IPython dir '/Users/bugrayesilkaynak/.ipython' is not a writable location, using a temp directory.
  " using a temp directory.".format(ipdir))
QTextCursor::setPosition: Position '-1' out of range
QTextCursor::setPosition: Position '10' out of range
