### ISSUE TITLE
pyqt=4 in python 3.6 not working

### ISSUE THREAD

**Issue by lneuhaus** [ContinuumIO/anaconda-issues#2682]
Hi, 
I am trying to do 
`conda install pyqt=4` 
in a python 3.6 conda environment (last version, 64 bits windows 7). Since my code requires pyqt4 (instead of 5), I am obliged to downgrade to python 3.5 to make its installation work with conda. Can I do something to make pyqt4 work with python 3.6, or is an integration planned in the near future, or is this a hopeless case?
Thanks a lot!

**Comment by mingwandroid** [comment]
You need to update your code I'm afraid.

**Comment by ccordoba12** [comment]
To expand what @mingwandroid said: PyQt4 is unsupported by Continuum, so no new packages will be created for new Python versions (i.e. Python 3.6 and above).

So we recommend you to port your code to PyQt5 instead. You can use a compatibility layer (like [qtpy](https://github.com/spyder-ide/qtpy)) to do it very easily.

**Comment by lneuhaus** [comment]
thanks, ill be doing that!
