### ISSUE TITLE
incompatibility between ETS (traitsui, etc) and Wx 3.0

### ISSUE THREAD

**Issue by ThomasLecocq** [ContinuumIO/anaconda-issues#269]
We are using a in-house developed UI based on TraitsUI (enable, traits, etc), aka The Enthought Tool Suite. It seems ETS is not supporting wx 3.0. They recommend using pyQt or PySide, but all elements of ETS are available for those backends, while they seem to be on Wx2.8.

Could 2.8 remain an available package to anaconda via conda ?

Cheers

Tom

**Comment by ccordoba12** [comment]
Do you need it for all platforms?

**Comment by ThomasLecocq** [comment]
I'd say win64 and linux64 are a must (at least for us) !

**Comment by remkade** [comment]
Closing this as is no longer applicable.
