### ISSUE TITLE
Nothing happens when clicking 'Open Terminal' on anaconda-navigator environment

### ISSUE THREAD

**Issue by Pourya-Shams** [ContinuumIO/anaconda-issues#2711]
In Anaconda Navigator, clicking 'Open Terminal' (in the green arrow popup menu) produces no result.

![conda](https://user-images.githubusercontent.com/22933345/27687715-7c5d5b52-5d0a-11e7-9921-32dc0a48e008.png)

# **Environment**

Windows 7
Anaconda3-4.1.1-Windows-x86_64

# **Expected result**

Clicking on the 'Open Terminal' menu item would open a system terminal with the proper environment activated.

**Comment by goanpeca** [comment]
@Pourya-Shams please open navigator from the `Anaconda Command Prompt` and try again and see if any traceback appears on the command prompt.

Also could you provide the output of `$ conda info` and `$ conda list`

**Comment by ritika26** [comment]
I am also facing the same issue.When i tried to open terminal from anaconda navigator nothing is opening.
I am using window 10. Please let me know the possible solution.
