### ISSUE TITLE
Python build does not recognize modern kernel / libc features

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#2714]
On Ubuntu's Python 3.5:
```
$ python3.5 -c "import os; print(os.sched_getaffinity(0))"
{0, 1, 2, 3}
```
On a hand-compiled Python 3.x:
```
$ ./python -c "import os; print(os.sched_getaffinity(0))"
{0, 1, 2, 3}
```
On Anaconda-compiled Python 3.6:
```
$ python -c "import os; print(os.sched_getaffinity(0))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```

The reason is probably that such features need recent enough libc headers, and Anaconda compiles Python against a very old glibc for ABI reasons.

**Comment by mingwandroid** [comment]
Hi @pitrou, this is fixed in the new from-scratch Miniconda3 I built using cross-compilers and Core Dependency Trees.

**Comment by remkade** [comment]
Closing as fixed.
