### ISSUE TITLE
bcolz: add carray_ext.pxd to package

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/anaconda-issues#273]
The philosophy of the bcolz package is to keep it restricted to the core storage functionality: See [this comment by FrancescAlted](https://github.com/Blosc/bcolz/pull/63#issuecomment-59657227). Following this comment the decision was made to expose the cython api to allow packages to be built on top of it.

One example is [bquery](https://github.com/visualfabriq/bquery) which implements efficient out-of-core groupby aggregation, factorization, etc for bcolz databases.

To compile successfully however, it requires the cython header file for the installed bcolz package: carray_ext.pxd. This is currently missing from the anaconda bcolz packages.

**Comment by ilanschnell** [comment]
The conda recipe which creates the package merely does a call to `python setup.py install`.  So if the `.pxd` file is missing, it should probably be fixed in `setup.py`, which makes this an upstream problem.

**Comment by ARF1** [comment]
Resolved with Blosc/bcolz#159.
