### ISSUE TITLE
(OSX) `anaconda-navigator` produces "ImportError: No module named 'PySide'"

### ISSUE THREAD

**Issue by colby-j-wise** [ContinuumIO/anaconda-issues#2740]
Getting error after recent re-install of anaconda-navigator. It won't open now. Conda info and Conda List below:
`| ~ @ Colbys-MacBook-Air (colbywise) 
| => conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.16
         python version : 3.5.3.final.0
       requests version : 2.14.2
       root environment : /Users/colbywise/anaconda  (writable)
    default environment : /Users/colbywise/anaconda
       envs directories : /Users/colbywise/anaconda/envs
                          /Users/colbywise/.conda/envs
          package cache : /Users/colbywise/anaconda/pkgs
                          /Users/colbywise/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/colbywise/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.5.3 Darwin/15.6.0 OSX/10.11.6    
                UID:GID : 501:20`

**Comment by colby-j-wise** [comment]
`| => conda list
# packages in environment at /Users/colbywise/anaconda:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.4.0                    py35_1  
alabaster                 0.7.10                   py35_0  
anaconda                  custom                   py35_0  
anaconda-clean            1.1.0                    py35_0  
anaconda-client           1.6.3                    py35_0  
anaconda-navigator        1.6.3                    py35_0  
anaconda-project          0.6.0                    py35_0  
appnope                   0.1.0                    py35_0  
appscript                 1.0.1                    py35_0  
argcomplete               1.0.0                    py35_1  
asn1crypto                0.22.0                   py35_0  
astroid                   1.4.9                    py35_0  
astropy                   1.3.3               np112py35_0  
babel                     2.4.0                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.6.0                    py35_0  
bitarray                  0.8.1                    py35_0  
bkcharts                  0.2                      py35_0  
blaze                     0.10.1                   py35_0  
bleach                    1.5.0                    py35_0  
bokeh                     0.12.6                   py35_0  
boto                      2.47.0                   py35_0  
bottleneck                1.2.1               np112py35_0  
cffi                      1.10.0                   py35_0  
chardet                   3.0.4                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.7                      py35_0  
cloudpickle               0.2.2                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.9                    py35_0  
conda                     4.3.22                   py35_0  
conda-build               2.1.16                   py35_0  
conda-env                 2.6.0                         0  
conda-verify              2.0.0                    py35_0  
configobj                 5.0.6                    py35_0  
contextlib2               0.5.5                    py35_0  
cryptography              1.8.1                    py35_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py35_0  
cython                    0.25.2                   py35_0  
cytoolz                   0.8.2                    py35_0  
dask                      0.15.0                   py35_0  
datashape                 0.5.4                    py35_0  
decorator                 4.0.11                   py35_0  
dill                      0.2.6                    py35_0  
distributed               1.17.1                   py35_0  
docutils                  0.13.1                   py35_0  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_1  
et_xmlfile                1.0.1                    py35_0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.7                    py35_0  
flask                     0.12.2                   py35_0  
flask-cors                3.0.2                    py35_0  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py35_0  
gevent                    1.2.2                    py35_0  
greenlet                  0.4.12                   py35_0  
h5py                      2.7.0               np112py35_0  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py35_1  
html5lib                  0.999                    py35_0  
icu                       54.1                          0  
idna                      2.5                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.6.1                    py35_0  
ipython                   6.1.0                    py35_0  
ipython_genutils          0.2.0                    py35_0  
ipywidgets                6.0.0                    py35_0  
isort                     4.2.15                   py35_0  
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.3                      py35_0  
jedi                      0.10.2                   py35_2  
jinja2                    2.9.6                    py35_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            5.1.0                    py35_0  
jupyter_console           5.1.0                    py35_0  
jupyter_core              4.3.0                    py35_0  
Keras                     2.0.4                     <pip>
lazy-object-proxy         1.3.1                    py35_0  
libdynd                   0.7.2                         0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libpq                     9.5.4                         0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.8.0                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                2.0.2               np112py35_0  
mistune                   0.7.4                    py35_0  
mkl                       2017.0.3                      0  
mkl-service               1.1.2                    py35_3  
mpmath                    0.19                     py35_1  
msgpack-python            0.4.8                    py35_0  
multipledispatch          0.4.9                    py35_0  
navigator-updater         0.1.0                    py35_0  
nb_anacondacloud          1.4.0                    py35_0  
nb_conda                  2.2.0                    py35_0  
nb_conda_kernels          2.1.0                    py35_0  
nbconvert                 5.2.1                    py35_0  
nbformat                  4.3.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.4                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  5.0.0                    py35_0  
numba                     0.33.0              np112py35_0  
numexpr                   2.6.2               np112py35_0  
numpy                     1.12.1                   py35_0  
numpydoc                  0.6.0                    py35_0  
odo                       0.5.0                    py35_1  
olefile                   0.44                     py35_0  
openpyxl                  2.4.7                    py35_0  
openssl                   1.0.2l                        0  
packaging                 16.8                     py35_0  
pandas                    0.20.2              np112py35_0  
pandas-datareader         0.3.0.post0               <pip>
pandocfilters             1.4.1                    py35_0  
partd                     0.3.8                    py35_0  
path.py                   10.3.1                   py35_0  
pathlib2                  2.2.1                    py35_0  
patsy                     0.4.1                    py35_0  
pbr                       3.0.1                     <pip>
pep8                      1.7.0                    py35_0  
pexpect                   4.2.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    4.1.1                    py35_0  
pip                       9.0.1                     <pip>
pip                       9.0.1                    py35_1  
pkginfo                   1.4.1                    py35_0  
ply                       3.10                     py35_0  
prompt_toolkit            1.0.14                   py35_0  
protobuf                  3.3.0                     <pip>
psutil                    5.2.2                    py35_0  
psycopg2                  2.7.1                    py35_0  
psycopg2                  2.7.1                     <pip>
ptyprocess                0.5.1                    py35_0  
py                        1.4.34                   py35_0  
pyasn1                    0.2.3                    py35_0  
pycosat                   0.6.2                    py35_0  
pycparser                 2.17                     py35_0  
pycrypto                  2.6.1                    py35_6  
pycurl                    7.43.0                   py35_2  
pyflakes                  1.5.0                    py35_0  
pygments                  2.2.0                    py35_0  
pylint                    1.6.4                    py35_1  
pyodbc                    4.0.16                   py35_0  
pyopenssl                 17.0.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_2  
pytables                  3.3.0               np112py35_0  
pytest                    3.1.2                    py35_0  
python                    3.5.3                         1  
python-dateutil           2.6.0                    py35_0  
python.app                1.2                      py35_4  
pytz                      2017.2                   py35_0  
pywavelets                0.5.2               np112py35_0  
pyyaml                    3.12                     py35_0  
pyzmq                     16.0.2                   py35_0  
qt                        5.6.2                         2  
qtawesome                 0.4.4                    py35_0  
qtconsole                 4.3.0                    py35_0  
qtpy                      1.2.1                    py35_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0  
requests                  2.14.2                   py35_0  
requests-file             1.4.1                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.9.4                    py35_1  
rpy2                      2.8.5                     <pip>
ruamel_yaml               0.11.14                  py35_1  
scikit-image              0.13.0              np112py35_0  
scikit-learn              0.18.2              np112py35_0  
scipy                     0.19.1              np112py35_0  
seaborn                   0.7.1                    py35_0  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sortedcollections         0.5.3                    py35_0  
sortedcontainers          1.5.7                    py35_0  
sphinx                    1.6.2                    py35_0  
sphinxcontrib             1.0                      py35_0  
sphinxcontrib-websupport  1.0.1                    py35_0  
spyder                    3.1.4                    py35_0  
sqlalchemy                1.1.11                   py35_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np112py35_0  
stevedore                 1.23.0                    <pip>
sympy                     1.0                      py35_0  
tblib                     1.3.2                    py35_0  
tensorflow                1.1.0                     <pip>
terminado                 0.6                      py35_0  
testpath                  0.3.1                    py35_0  
Theano                    0.9.0                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                    py35_0  
tornado                   4.5.1                    py35_0  
traitlets                 4.3.2                    py35_0  
unicodecsv                0.14.1                   py35_0  
unixodbc                  2.3.4                         0  
virtualenv                15.1.0                   py35_0  
virtualenv                15.1.0                    <pip>
virtualenv-clone          0.2.6                     <pip>
virtualenvwrapper         4.7.2                     <pip>
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.12.2                   py35_0  
wheel                     0.29.0                   py35_0  
widgetsnbextension        2.0.0                    py35_0  
wordcloud                 1.3.1                     <pip>
wrapt                     1.10.10                  py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.6                    py35_0  
xlwings                   0.10.4                   py35_0  
xlwt                      1.2.0                    py35_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zict                      0.1.2                    py35_0  
zlib                      1.2.8                         3  `

**Comment by goanpeca** [comment]
@colby-j-wise not sure what the problem is, try to reintall qt pyqt and qtpy. Please open a terminal and type:

`$ conda install qtpy pyqt qt -f`

**Comment by colby-j-wise** [comment]
I was able to get it working. I had to do a clean install of anaconda python. It appears there were a number of conflicts given how I originally install python/anaconda a year ago vs a number of virtualenvs I have been working off of sine then. Net for net it made sense to reinstall things correctly and cleanly

Appreciate the reply!
