### ISSUE TITLE
libffi package does not contain libffi.pc (pkgconfig file)

### ISSUE THREAD

**Issue by fallen** [ContinuumIO/anaconda-issues#275]
Hi, 
I tried to compile glib package from https://github.com/conda/conda-recipes/tree/master/glib but it failed because it didn't find libffi.
After some investigation, it turns out that your libffi package ( https://binstar.org/anaconda/libffi/files ) doest not contain the libffi.pc file.
However, compiling libffi package from https://github.com/conda/conda-recipes/tree/master/libffi does provide the libffi.pc.
I uploaded my own libffi on my binstar account then, but I think you might want to fix your libffi package by recompilig it from the conda-recipes one.

Cheers!

**Comment by nehaljwani** [comment]
This should be fixed with the conda package `libffi=3.2.1=1`

```bash
(275) [nwani@oldhell ~]$ find /home/nwani/m3/pkgs/libffi-3.2.1-1 | grep libffi.pc
/home/nwani/m3/pkgs/libffi-3.2.1-1/lib/pkgconfig/libffi.pc

(275) [nwani@oldhell ~]$ cat $CONDA_PREFIX/lib/pkgconfig/libffi.pc
prefix=/home/nwani/m3/envs/275
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
toolexeclibdir=${exec_prefix}/lib
includedir=${libdir}/libffi-3.2.1/include

Name: libffi
Description: Library supporting Foreign Function Interfaces
Version: 3.2.1
Libs: -L${toolexeclibdir} -lffi
Cflags: -I${includedir}
```
