### ISSUE TITLE
Update runipy package in default channels?

### ISSUE THREAD

**Issue by rmcgibbo** [ContinuumIO/anaconda-issues#277]
The latest release of `runipy` is 0.1.3. The latest release packaged in the conda defaults is 0.1.1. The 0.1.3 release is necessary for supporting new IPython3.

https://pypi.python.org/pypi/runipy/0.1.3

**Comment by ilanschnell** [comment]
Good, to know.  I'll update it right away.

**Comment by ilanschnell** [comment]
runipy 0.1.3 is now available
