### ISSUE TITLE
Conda package for IPython Notebook v3 needs jsonschema

### ISSUE THREAD

**Issue by chrish42** [ContinuumIO/anaconda-issues#278]
Hello. This is the result of trying to run `ipython notebook` after upgrading to version 3 with `conda install ipython`:

    ImportError: No module named jsonschema

    IPython notebook format depends on the jsonschema package:

        https://pypi.python.org/pypi/jsonschema

    Please install it first.

Looks like a missing dependency (and a missing package in Anaconda?) to me...

**Comment by ilanschnell** [comment]
```
$ conda install ipython-notebook
```
should fix it.  This installs a meta-package which contains all the dependencies, including `jsonschema`
