### ISSUE TITLE
Application launcher fatal error

### ISSUE THREAD

**Issue by pgvoorhees** [ContinuumIO/anaconda-issues#279]
Receiving the following error in Ananconda Launcher:
![2015-03-04 13_11_04-launcher - anaconda - continuum analytics](https://cloud.githubusercontent.com/assets/422644/6489926/5780b194-c270-11e4-8ca0-d4236ea6084f.png)

Clicking through does not seem to find a bottom where the launcher will finally display.

How can I help flesh this error out?

**Comment by ccordoba12** [comment]
Thanks for reporting. We are aware of this problem.

The launcher is being reworked right now and a new version will be released soon.

**Comment by pgvoorhees** [comment]
Very good. Thanks!
