### ISSUE TITLE
UnsatisfiableError when installing lasagne

### ISSUE THREAD

**Issue by JGH1000** [ContinuumIO/anaconda-issues#2794]
UnsatisfiableError: The following specifications were found to be in conflict:
  - lasagne -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by JGH1000** [comment]
Same with wxPython:

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - wxpython -> python 2.7* -> openssl 1.0.1*
Use "conda info <package>" to see the dependencies for each package.

Any advice?

**Comment by JGH1000** [comment]
Guess it is just missing for python 3.6

**Comment by cohen5** [comment]
Hi
Did you find a way to make it work?
Thanks
