### ISSUE TITLE
Navigator Error- DO NOT Blindly close without reading everything please!

### ISSUE THREAD

**Issue by AurenH** [ContinuumIO/anaconda-issues#2845]
I read the original thread,
The navigator won't run, so I can't update anything.
I tried uninstalling and re-installing.
I also tried a new, clean installation with the file on the site.
It persists.
I would appreciate your help rather than an automated "this is a duplicate" response.

## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=568)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\orenh\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\orenh\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\orenh\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\orenh\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\orenh\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=568)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: he_IL
python: 2.7.13
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Comment by AurenH** [comment]
It won't launch.
Can't click anything on any UI, it completely crashes.
But hey, you obviously enjoy dubbing everything duplicate without really
providing solutions.

**Comment by goanpeca** [comment]
@AurenH please go to the terminal and type

The referenced issue contains the solution

https://github.com/ContinuumIO/anaconda-issues/issues/1984#issuecomment-307225225
