### ISSUE TITLE
Setting Qt using anaconda in OSx

### ISSUE THREAD

**Issue by skvsree** [ContinuumIO/anaconda-issues#285]
Hi One of the fastest ways of setting up [eric] (http://eric-ide.python-projects.org/) in Windows is installing Anaconda python and then eric using it.  
Anaconda comes with all prerequisites of eric including qt, sip and scintilla and I had no issues doing that in Windows.
But when I tried the same in OSX it failed with below error.  
Looks like this error can happen in regular installation as mentioned in below link.
https://gist.github.com/jimk/2563701
```
Sorry, please install QScintilla2 and
 it's PyQt4 wrapper.
 Error: cannot import name Qsci
```
I have reported this [issue to eric] (http://die-offenbachs.homelinux.org:48888/issues/issue175) team and they pointed out that it is installation issue.
If this is as designed, I would like to make this as a feature request enabling lot people to use Anaconda as Qt installation is Mac is painful.

**Comment by ccordoba12** [comment]
One question: is Qscintilla part of Qt and/or PyQt? If it is, then we will look into this issue. If not, you'd need to create a conda recipe for it, and then compile it to build a MacOS X conda package based on it.

**Comment by skvsree** [comment]
As per [Qt Wiki page](http://qt-project.org/wiki/QScintilla) At the moment the commercial version of QScintilla is bundled with the commercial version of PyQt.
QScintilla2 supports Qt v3, Qt v4 and Qt v5.

**Comment by ccordoba12** [comment]
Well, that's the problem then. I'm almost sure Continuum (the company behind Anaconda) only has commercial support for PyQt on Windows, not on Linux nor Mac.

@asmeurer, could you confirm this?

**Comment by ccordoba12** [comment]
Well, I'm in charge of building Qt/PyQt on Linux and Mac, and we use the open source versions in those platforms.

So I'm afraid there's nothing we can do about this one.
