### ISSUE TITLE
starting anaconda-navigator

### ISSUE THREAD

**Issue by pbhart** [ContinuumIO/anaconda-issues#2854]
I have anaconda2 and anaconda3 and no anaconda-navigator in my menu.  Using linuxmint.

Phil Hart
pbhart@gmail.com

**Comment by goanpeca** [comment]
@pbhart sorry, we still do not provide launchers for navigator on Linux. We are working on it for a future release

**Comment by pbhart** [comment]
Any workarouns for a launcher in linux?

Phil Hart

**Comment by goanpeca** [comment]
@pbhart you mean besides opening a terminal and typing

`$ anaconda-navigator` ?
