### ISSUE TITLE
Include pip installed packages in environment

### ISSUE THREAD

**Issue by soerendip** [ContinuumIO/anaconda-issues#287]
Hi,

I want to use rdkit and other packages with anaconda. 
I installed a package X with pip.

When I create the environment with

> conda create --use-local -n env rdkit ...  

It is not possible to add package X because it has been installed with pip.

So, my current solution is to activate the environment and then install package X again.

Which is pretty odd. Is there a better way to include such packages?

regards

**Comment by ilanschnell** [comment]
You can use `conda create --clone` see `conda create --help`.
