### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sdikby** [ContinuumIO/anaconda-issues#2925]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - _nb_ext_conf ==0.4.0
  - bokeh ==0.12.6
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.4', 'qt': '4.8.7', 'language': 'de_DE', 'python': '2.7.11', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@sdikby you have a very old version of navigator.

Please update to the latest.

Open a command prompt and type:

```
$ conda update anaconda-navigator
$ conda install navigator-updater
```
