### ISSUE TITLE
Already shared packages with root environment packages

### ISSUE THREAD

**Issue by ykg2910** [ContinuumIO/anaconda-issues#2929]
Hello, I have created a virtualenv say 'venv' with conda and installed few packages, but the packages which were not installed separately in 'venv', they are already linked to anaconda root environment.

so if I use pip freeze, it shows all the packages installed in root conda environment, not just installed in 'venv'. Is this behaviour expected? This is different from normal virtualenv.

**Comment by kalefranz** [comment]
Make sure your environment is activated, and you're using the correct `pip`.  `which -a pip` will show you all instances on PATH.
