### ISSUE TITLE
Spyder 2 won't start on user with non ASCII characters 

### ISSUE THREAD

**Issue by noenandre** [ContinuumIO/anaconda-issues#294]
Update recently from anaconda 1.6 to 2.1, then Spyder stop working.
Now every attempt to start Spyder in Anaconda Command Prompt result in the following error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 11: ordinal not in range(128)

Spyder work just fine on a separate user, on the same computer that do not contain Nordic characters (Ø)

Windows 64-Bit and 32-Bit installer.

**Comment by ccordoba12** [comment]
Please open a terminal (i.e. cmd.exe) and run this command

    spyder --reset

then try again. It should work now :-)

**Comment by noenandre** [comment]
Any attempt to reset spyder result in the same UnicodeDecodeError.
Also tried to delete the .spyder folder at C:\Users\Bjørn as suggested [elsewhere](http://docs.continuum.io/anaconda/known-issues.html).

In addition I tried a clean install on another computer, with the same username, where I got the same errors. So it clear it is not leftovers from the 1.6 install causing problems.

**Comment by ccordoba12** [comment]
Please update Spyder to its latest version by running this command on a terminal (i.e. cmd.exe)

    conda update spyder

and try again. I think we fixed this error in Spyder 2.3.4

**Comment by noenandre** [comment]
Update both Spyder and Anaconda solved this issue.
Thanks!

**Comment by ccordoba12** [comment]
Really, really glad to hear it! :-)
