### ISSUE TITLE
Windows gdal 1.11.2 packages missing libraries & binaries

### ISSUE THREAD

**Issue by jedfrechette** [ContinuumIO/anaconda-issues#295]
The installation of gdal 1.11.2 on a clean Anaconda-2.1.0-Windows-x86_64.exe install completes without error. However attempting to import the module fails with:

```
ImportError: DLL load failed: The specified module could not be found.
```
Looking in Anaconda/pkgs/gdal-1.11.2-np19py27_0/Lib/site-packages/osgeo/ there are, in fact, none of the .pyd or .exe files that should be there. 

From looking at the sizes of the gdal packages in the repos it looks like this probably also affects the win32 builds. The 1.11.2 packages are only a few hundred K versus several M for the older versions.

Reverting to 1.11.1 or earlier provides a workaround for the issue.

**Comment by jorisvandenbossche** [comment]
I also experienced this issue. Downgrading to 1.10.1 also did the job.

**Comment by waterguy77** [comment]
We are also having this issue.  I have an older install that is working fine, but we are trying to install on a new machine and are having this issue.  What is the procedure for downgrading to an earlier version?

**Comment by jorisvandenbossche** [comment]
@waterguy77 you can specify the version when installing (or this will also replace a current install with other version): `conda install gdal=1.11.1`

**Comment by waterguy77** [comment]
@jorisvandenbossche Thanks!  I'll give it a try.

**Comment by groutr** [comment]
This should be fixed with the new split of gdal into libgdal and gdal python bindings.
