### ISSUE TITLE
Jupyter launch error - Mac

### ISSUE THREAD

**Issue by arunadas** [ContinuumIO/anaconda-issues#2969]
Hi There!

I installed Jupyter today on different Mac book pro, this time on clicking the launch button of Jupyter the error is different

Last login: Sat Jul  8 13:12:10 on ttys000
Arunas-MacBook-Pro:~ arunadas$ /anaconda/bin/jupyter_mac.command ; exit;
[I  NotebookApp] Serving notebooks from local directory: /Users/arunadas
[I  NotebookApp] 0 active kernels 
[I  NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=5ae6c96aeaf38db7843ce372350782f0876bada9a71f9587
[I  NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C  NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=5ae6c96aeaf38db7843ce372350782f0876bada9a71f9587
0:97: execution error: "http://localhost:8888/tree?token=77446ff794b2c01efe3f7f730dff3f0e5cfadc8ff50f55ed" doesn’t understand the “open location” message. (-1708)

Copy paste url option lets me open the application but definitely have to check the launch button implementation, seems like its not working as desired/designed.

Please let me know what you find...

**Comment by goanpeca** [comment]
See


https://github.com/jupyter/notebook/issues/2438

for more detailed investigation.
