### ISSUE TITLE
Tab expansion on Jupiter Notebook

### ISSUE THREAD

**Issue by SilasK** [ContinuumIO/anaconda-issues#298]
Dear all,

why is the tab expansion or better said the tooltip for the function parameter no more working?
Do you add this feature or can you say me how to revert back to Ipython notebook?

**Comment by ccordoba12** [comment]
I think you need to use `Shift+Tab` now, instead of `Tab`.

Pinging @damianavila because he knows more about it.

**Comment by damianavila** [comment]
Yep, SHIFT+TAB is the way now... you can see the keyboard shortcut reference at the Help menu for more information about them.

**Comment by ccordoba12** [comment]
Ok, since I think there's nothing more to talk about, I'm closing this issue.
