### ISSUE TITLE
Anaconda Navigator - Update prompt at launch

### ISSUE THREAD

**Issue by Ericvulpi** [ContinuumIO/anaconda-issues#2988]
I get the following prompt when I launch Anaconda Navigator. If I click yes, the Navigator just closes, no update.

![screen shot 2017-07-09 at 14 08 36](https://user-images.githubusercontent.com/2828372/27993751-2464635c-64b0-11e7-98e4-81a173a04d07.png)

I'm on mac, using Anaconda Navigator 1.5.3.

**Comment by goanpeca** [comment]
@Ericvulpi please open a terminal and type

```
$ conda install navigator-updater
$ navigator-updater
```

**Comment by Ericvulpi** [comment]
Well, I solved it with
`conda install anaconda-navigator`
Just seemed worth mentionning
