### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tmina37** [ContinuumIO/anaconda-issues#2989]
Main error The following errors occurred: ## Traceback     CondaHTTPError: HTTP 401 UNAUTHORIZED for url  https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json> Elapsed: 00:00.774578 CF-RAY: 37bc0ac77aef205a-KIX The remote server has indicated you are using invalid credentials for this channel. If the remote site is anaconda.org or follows the Anaconda Server API, you will need to   a  remove the invalid token from your system with  anaconda logout , optionally  followed by collecting a new token with  anaconda login , or   b  provide conda with a valid token directly. Further configuration help can be found at  https://conda.io/docs/config.html>.     ## System information     python: 3.6.1 language: ja_JP os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel version: 1.6.2 platform: win-64 qt: 5.6.2 pyqt: 5.6.0 conda: 4.3.21

**Comment by goanpeca** [comment]
@tmina37 please logout and login.
And remove the `anaconda-fusion` channel
