### ISSUE TITLE
No module PyQt4

### ISSUE THREAD

**Issue by elmerehbi** [ContinuumIO/anaconda-issues#2990]
I have searched about this problem and found out many issues and questions but I can't seem to find a suitable solution.

I just removed my anaconda and reinstalled it. When I import pyplot or seaborn I am faced with the same error of PyQt4 not being found.

I tried to install it with conda but it says I already have the latest version.

I also tried downgrading to pyqt4 with: `conda instlal pyqt=4.11.4` which downgrades matplotlib from v2 to v1 and the error persists.

What can I do?

PS: I am on Ubuntu and using Anaconda 3

**Comment by ccordoba12** [comment]
Please post here the full error you're getting.
