### ISSUE TITLE
Anaconda Navigator cannot open in mac

### ISSUE THREAD

**Issue by yuanzeluo** [ContinuumIO/anaconda-issues#2998]
Hi, I know this question has been asked before but I the methods I found cannot solve my problem.

When I try to click on the anaconda icon to open it, the icon showed up in my Dock and then disappears. `vim ~/.bash_profile` gives `# added by Anaconda3 2.5.0 installer
export PATH="//anaconda/bin:$PATH"

# added by Anaconda3 4.2.0 installer
export PATH="//anaconda/bin:$PATH"`

`sudo rm -rf ~/.continuum/` Does not help...

`anaconda-navigator` in terminal gives `Segmentation fault: 11`

`conda info` in terminal gives `Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.0.2
         python version : 3.5.3.final.0
       requests version : 2.18.1
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/CEiffel/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/CEiffel/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.18.1 CPython/3.5.3 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20`

How to solve the problem?

Thank you very much!

**Comment by yuanzeluo** [comment]
`open -a anaconda-navigator` in terminal gives:
`LSOpenURLsWithRole() failed for the application /anaconda/Anaconda-Navigator.app with error -10810.
`

**Comment by goanpeca** [comment]
@yuanzeluo OSX seem to have broken some things in a recent update

**Comment by yuanzeluo** [comment]
So is there anything I can do that may fix it?
Or I can only wait for the update?

**Comment by goanpeca** [comment]
Well @yuanzeluo you should be able to open it from the terminal by doing just

```
$ anaconda-navigator
```

**Comment by BernardF1** [comment]
I had the same problem. The only solution I found was to completely remove Anaconda and then reinstall. It worked fine after that.

**Comment by yuanzeluo** [comment]
The problem is still  not solved...
`$ anaconda-navigator` in terminal gives `Segmentation fault: 11`

Do I have to reinstall all the packages again if I remove an reinstall anaconda?

**Comment by BernardF1** [comment]
That I don't know - when I did it, I was only  using the out-of-the-box packages. But even if you have to reinstall 20 packages, it's probably less effort than you are spending trying to troubleshoot, so I'd give it a try. What's the worst that could happen? ;o) (famous last words)

**Comment by niral-patel** [comment]
I have the same issue, when I open it through the spotlight, it shows an error,
I installed it three times by using HomeBrew and finally, I installed it using the installer from ANACONDA.
Even, I got 
“jupyter_mac.command” can’t be opened because (null) is not allowed to open documents in Terminal.
while launch the Jupyter notebook
Can you please help me?
