### ISSUE TITLE
DLL not found when importing pyzmq (Windows, 32bit, py33)

### ISSUE THREAD

**Issue by almarklein** [ContinuumIO/anaconda-issues#3]
On importing zmq, I get ImportError: module not found. In effect, IPython notebook does not work.
 
Tracing dependencies with cx_Freeze tools gives only python33.dll. I haven't tried with dependency walker yet. Can it be that it is build against an older Python version?

If I install the binary package from Gohlke, all works well. By the way, Anaconda's version is 2.2, while Gohlke's version is 13.

**Comment by almarklein** [comment]
Works fine now.

**Comment by ccordoba12** [comment]
@almarklein this is usually caused by corruptions doing by `conda update` when the IPython notebook is running in the background.

@asmeurer is working on solving them for the next Anaconda release

**Comment by almarklein** [comment]
@ccordoba12 Ah that would explain it; damn, it would mean that I'd been bitten by that issue much more times than I thought ...
