### ISSUE TITLE
Mac OS Yosemite Fatal error - SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by tbshirey** [ContinuumIO/anaconda-issues#301]
New install 2 days ago of Anaconda on Mac Yosemite. Have opened the Launcher and used all apps successfully after initial install. Today when launching Anaconda the Launcher fails to open giving ...fatal error....SyntaxError: Unexpected token. I know this issue was reported before but wondering if others are still experiencing this with the current version? Clicking restart Launcher only loops back to original  error. Suggestions?  

Thanks.

**Comment by tbshirey** [comment]
I should add that I installed Anaconda version 2.2.0.

**Comment by tbshirey** [comment]
Update:  I am having similar issues to dferguso in #216 . 

Also, I can open spyder by calling it from the Mac terminal, but the Launcher app will not open. Could this be an issue of requiring network access to open the Launcher? This is the first time I tried to open it while offline.

**Comment by ccordoba12** [comment]
The launcher is being reworked now. A new version will be available soon.

Sorry for the inconveniences.

**Comment by tbshirey** [comment]
No problem. Thanks for the quick reply!

**Comment by mcfone** [comment]
Hi - I've just run into the same issue with the Launcher ("SyntaxError: Unexpected token <") Anaconda3-2.3.0-MacOSX-x86_64.pkg on Yosemite. Is there any workaround, or is the newer version close? I see this was first reported with 2.2.0, and is still there in 2.3.0.
Thanks.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
