### ISSUE TITLE
/usr/lib64/liboxygenstyle.so.4: undefined symbol _ZN8QPainter10drawPixmapERK6QRectFRK7QPixmapS2_

### ISSUE THREAD

**Issue by icymist** [ContinuumIO/anaconda-issues#304]
matplotlib is not usable on SuSE 13.2 with latest Anaconda 2.2.0. matplotlib installed with system python works without a problem.

This is what I get.

12:04 $ ipython
Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Mar  9 2015, 16:20:48) 
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.pyplot as plt

In [2]: plt.plot([0, 1], [1,1])
/home/chaitanya/opt/anaconda/bin/python: symbol lookup error: /usr/lib64/liboxygenstyle.so.4: undefined symbol: _ZN8QPainter10drawPixmapERK6QRectFRK7QPixmapS2_

**Comment by ccordoba12** [comment]
Please run

    conda update pyqt

and try again. We fixed this error yesterday but we'd be glad if you could confirm us that the fix is working for you :-)

**Comment by icymist** [comment]
Yep. Works for me now.

**Comment by dkxls** [comment]
I ran into the same issue and had to update pyqt and matplotlib to get back to a working state.

    conda update pyqt
    conda update matplotlib
