### ISSUE TITLE
Navigator GUI problem

### ISSUE THREAD

**Issue by fhernand78** [ContinuumIO/anaconda-issues#3052]
Hello there,

I have installed the latest version of Anaconda Navigator, with Python 3.6, all seems to work very good, but I realized that I needed Python 3.5. I have all unistalled and re-installed Anaconda Navigator with Python 3.5. Now, when I launch Anaconda Navigator, the green cercle appears....initializing.....updating metadata.....updating repodata,....and then dissapear, noting happens...there's no GUI of Anaconda Navigator. But, if I launch spyder, anaconda prompt, Jupyter, works fine.  It is installed on Windows 10.

What can I do for having the GUI?

Fernando

**Comment by goanpeca** [comment]
@fhernand78 if you need python 3.5 you should create a conda environment for that. No need to install navigator for 3.5

**Comment by fhernand78** [comment]
But I have already did that. The problem is that I cannot open the Navigator. Is there any way solve that problem?

**Comment by fhernand78** [comment]
I have solved the problem.

On a python terminal.....

conda update conda anaconda-navigator


thanks and I hope this will help someone.
