### ISSUE TITLE
Spyder can't boot, ValueError in pandas

### ISSUE THREAD

**Issue by isomerase** [ContinuumIO/anaconda-issues#306]
This is the second time this issue has happened to me (Windows v8.1 64-bit, Anaconda v2.2.0). 

Possibly unrelated, but Spyder froze when I ran a script. The dialog asked me if I want to quit Spyder, I choose yes. 

Now, I can't boot Spyder anymore-- I've tried the shortcut, running through Launcher, and running from terminal. Last time this happened to me I ended up having to DL+reinstall Anaconda...

I followed the instructions on the support page: I tried launching again, ran Reset Spyder Settings, tried to launch from `cmd`, deleted `.spyder2` directory, and tried all permutations of the above.

Here is the error I get in `cmd` when I try to run Spyder:
![spyder error](https://cloud.githubusercontent.com/assets/5415776/7150435/be6fd8ba-e2cf-11e4-8d78-c62433e749ff.png)

Let me know if there's anything else you need. This is a 3 day old Dell laptop with no other Python distributions.

**Comment by ccordoba12** [comment]
This happens when you run

    conda update pandas

(or another update commands) without closing Spyder first. To fix it, please close Spyder, the IPython notebook and any other Python application that can import Pandas, and run

    conda install -f pandas

**Comment by isomerase** [comment]
Wonderful! Thanks!
