### ISSUE TITLE
matplotlib pdf backend crashes python

### ISSUE THREAD

**Issue by joergdietrich** [ContinuumIO/anaconda-issues#309]
```
[joerg@shiraz ~] $ ipython --pylab
Python 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Mar  6 2015, 12:03:53) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
pUsing matplotlib backend: TkAgg

In [1]: plt.figure()
Out[1]: <matplotlib.figure.Figure at 0x7f9760762c50>

In [2]: x = np.random.normal(size=100)

In [3]: y = np.random.normal(size=100)

In [4]: plt.scatter(x, y)
Out[4]: <matplotlib.collections.PathCollection at 0x7f975e00ad30>

In [5]: plt.savefig("foo.png")

In [6]: plt.savefig("foo.pdf")
*** Error in `/home/joerg/applications/anaconda3/bin/python3': double free or corruption (out): 0x0000000002e2ce20 ***
Aborted (core dumped)
```

```
$ conda update ipython python matplotlib
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/joerg/applications/anaconda3:
#
ipython                   3.1.0                    py34_0  
matplotlib                1.4.3                np19py34_1  
python                    3.4.3                         0  
```

**Comment by ccordoba12** [comment]
@tcaswell, are you seeing this error too?

And, do you know what can be happening in this case?

**Comment by joergdietrich** [comment]
Same thing happens with `plt.savefig('foo.svg')`.

**Comment by jkseppan** [comment]
It seems that Anaconda has freetype 2.5.2. That version had a bug leading to a double free, which caused some crashes in Ubuntu 14.04:

https://github.com/matplotlib/matplotlib/issues/2916/
http://savannah.nongnu.org/bugs/?40997
https://bugs.launchpad.net/freetype/+bug/1310728

I think the bug is fixed in freetype 2.5.3, or you could look up Ubuntu's backported patch.

**Comment by ccordoba12** [comment]
Thanks a lot @jkseppan!! I just have one question for you:

So the only thing we need to do is update is freetype? Or do we need to recompile cairo against the new freetype too?

I mean, I don't know if cairo is used by matplotlib to render PDF's in the background. Or is that not the case?

**Comment by jkseppan** [comment]
If you're saving via the pdf backend, it's not using cairo, but there is also a cairo backend that's separate from the pdf backend, and some of the GUI backends could be using cairo. It would probably not be good to link two different versions of freetype in the same binary, one via ft2font and another via cairo.

**Comment by tacaswell** [comment]
Sorry I missed this last week, I can confirm that this is happening with both python 2 and 3.  Things work fine linked against the system freetype

**Comment by swnphys** [comment]
Happened to me as well.

**Comment by tacaswell** [comment]
@ccordoba12 Any word on getting this fixed?

**Comment by tacaswell** [comment]
@swnphys The solution (for now) seems to be to force conda to downgrade to the first build of mpl

```
conda install matplotlib=1.4.3=np19py27_0
```

**Comment by ccordoba12** [comment]
@tacaswell, working on it right now :-) I think I'll patch 2.5.2 with the backported fix because that's the current version in Ubuntu.

Please be patient because this involves recompiling several big packages: fontconfig, Qt, cairo and mpl. Let me know if there are other packages we need to recompile.

**Comment by tacaswell** [comment]
Thanks.  I got bit by this last night too (why is building the mpl docs segfaulting?!?).

I don't know any other packages which link to freetype off the top of my head.

**Comment by ccordoba12** [comment]
I submitted a pull request against our internal repo, let's hope it's merged soon :-)

**Comment by ccordoba12** [comment]
We just updated `freetype`, and I already verified that it fixes this problem. So please run

    conda update freetype

to get the fix.

We didn't consider necessary to update all packages I mentioned before because the patches suggested by @jkseppan don't touch header files, so they don't change Freetype API.

**Comment by tacaswell** [comment]
Great!

**Comment by swn9gag** [comment]
Thank you so much for this!
