### ISSUE TITLE
Problems downgrading fromPyQt 5 to PyQt4 (Anaconda2)

### ISSUE THREAD

**Issue by mbhdtech** [ContinuumIO/anaconda-issues#3104]
Hey guys!

I am currently fixing a bug in a piece of software, and it was initially written in Python 2.7 with PyQt4. I installed Anaconda2, and the packages where installed. When I tried running the code from source, it turns out that PyQt5 was installed. I tried installing older versions of PyQt.
Using: `conda install pyqt=4.11.4`

From there, I also tried changing the version in the Anaconda Navigator, but I keep getting an "unsatisfiable error". This error happened when I tried downgrading to pyqt 4.11.4.
I was at the same time, trying to downgrade from 5.6.2 to 4.8.7. I thought this would have taken care of the unsatisfiable error, but it seems Anaconda refuses to downgrade from 5.6.0.

I tried creating a new environment, called oldpyqt. I then tried installing pyqt4 but I still get the errors. Any suggestions? 

Thanks!

**Comment by ccordoba12** [comment]
Please create an conda environment and install there pyqt 4, instead of trying to downgrade pyqt in your root environment.

That would make your life way more easier.
