### ISSUE TITLE
Add new package "rasterio"

### ISSUE THREAD

**Issue by kpurdon** [ContinuumIO/anaconda-issues#312]
Would it be possible to add https://github.com/mapbox/rasterio to anaconda? It looks like some people already have recipes: https://binstar.org/search?q=rasterio. This is in the same realm as shapely/fiona which are already in anaconda.

**Comment by groutr** [comment]
Sure.  We can add that.  With current workloads, give us a week or so to add it to the official repos.

**Comment by kpurdon** [comment]
@groutr thanks for the quick response.

**Comment by groutr** [comment]
Status update:  Ran into some issues building one of the dependencies on windows.  Still working on it, but it will take a little more time.

**Comment by groutr** [comment]
Sorry for the long silence.  I've successfully built rasterio for the official repos.  I was just about to release it tonight, but I saw that they just released a new version!  I'll repackage the new version and upload it tomorrow.

**Comment by kpurdon** [comment]
Awesome, Thanks @groutr!

**Comment by groutr** [comment]
New package is available
```conda install rasterio```

If you have any further problems, please open a new issue.  Again, sorry for the wait.
