### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vickorian** [ContinuumIO/anaconda-issues#3133]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 02:25:21.039 NotebookApp] Serving notebooks from local directory: F:/
[I 02:25:21.039 NotebookApp] 0 active kernels 
[I 02:25:21.039 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=49bd2ce234cdf524c007c58ca0f224a40742faff9bb111c3
[I 02:25:21.039 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:25:21.040 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=49bd2ce234cdf524c007c58ca0f224a40742faff9bb111c3
[I 02:25:22.403 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 02:25:22.404 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 02:25:22.429 NotebookApp] 404 GET /tree?token=f51cf2c93f63fb55676f764c61ad929ec29262e2836288d8 (::1) 26.03ms referer=None

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment]
See https://github.com/jupyter/notebook/issues/2382

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Comment by vickorian** [comment]
I know this is closed, but this doesn't resolve the issue. The problem occurs when jupyter_notebook_config.py is modified. When line 202 is given a value other then the default and uncommented, notebook fails to resolve. You are left with 404 errors. When the line is recommented, the notebook will happily run, but only in the default directory.

**Comment by vickorian** [comment]
I solved the issue. The default directory is apparently not allowed to be set to a base drive, it must be a folder within the drive. As such, "F:/" does not resolve, but "F:/Folder/" does work correctly.
