### ISSUE TITLE
python3 boost-1.57.0-0 (linux-64) issue

### ISSUE THREAD

**Issue by rmcgibbo** [ContinuumIO/anaconda-issues#316]
When building and testing a py3 package that links against boost, I noticed that there's a bug with the boost-1.57.0-0 package in the defaults channel on linux-64. I suspect the same issue applies on os-x too.

The package doesn't list any dependencies, but in fact it _does_ depend on python 2.7. The boost package includes `libboost_python.so.1.57.0` which contains symbols that are expected to be found in `libpython2.7.so`.

When testing a package on python33 that depends on boost (and using the boost-1.57.0-0 package), I noticed the following error:

```
ImportError: /home/vagrant/miniconda/envs/_test/lib/python3.3/site-\
packages/pyublas/../../../libboost_python.so.1.57.0: undefined symbol: PyClass_Type
```

As mentioned on [S.O.](http://stackoverflow.com/questions/19865757/importerror-usr-lib-libboost-python-so-1-54-0-undefined-symbol-pyclass-type/19870624#19870624):
> PyClass_Type is is part of the Python 2 C API and not part of the Python 3 C API. Hence, the  Boost.Python library was likely built against Python 2. However, it is being loaded by a Python 3 interpreter, where the PyClass_Type is not available.

I think the only way to fix this is to explicitly declare that boost depends on python, and build separate conda packages of boost for each python ABI.

**Comment by rmcgibbo** [comment]
Another way to see this is by running `nm` and looking at the python API symbols

```
$ nm ~/miniconda/pkgs/boost-1.57.0-0/lib/libboost_python.so | grep 'U Py'
[... snip ...]
                 U PyInt_AsLong
                 U PyInt_FromLong
                 U PyInt_Type
[... snip ...]
                 U PyString_AsString
                 U PyString_FromFormat
                 U PyString_FromString
[... snip ...]
```

Many of the symbols like `PyInt_*` and `PyString_*` are not part of the python3 C API or were renamed.

**Comment by ccordoba12** [comment]
We build boost only against Python 2 for now.

I'm not sure how to build it to support Python 2 **and** 3 at the same time.

**Comment by rmcgibbo** [comment]
It might be a good idea to make the `boost-1.57.0-0` package declare that it has a python dependency then. As it is, the dependency resolver doesn't realize this, so `conda install python=3 package-that-depends-on-boost` will go out and grab this package (and then fail), as opposed to showing the dependency conflict.

**Comment by ccordoba12** [comment]
You're right, a runtime dependency should solve this problem.

**Comment by ccordoba12** [comment]
This was solved in the Boost recipe present in conda-recipes. New packages will be available soon :-)

**Comment by rmcgibbo** [comment]
Great.
