### ISSUE TITLE
python interpreter loses readline settings when imported certain modules in Linux

### ISSUE THREAD

**Issue by jjhelmus** [ContinuumIO/anaconda-issues#317]
Custom readline settings are lost upon importing certain modules (matplotlib.pyplot) using the python interpreter installed using Miniconda.  Namely if the .inputrc files specifies a vi editing mode and maps the up/down arrows to perform history searching this searching if functional in the Python 2.7.9 interpreter shipped by miniconda but breaks after the line `matplotlib.pyplot` is executed.  Other imports also will produce this loss of search functionality, they seem to be limited to compiled modules.  This loss of search functionality is not seem in the system Python interpreter. I believe this issue may be related to the readline issues in #42  

The example of this behavior is a bit complicated to reproduce but the following example is a minimal example that I was able to make which reproduces the issues reliably:

* In a fresh ubuntu-trusty-64 VM Miniconda was installed and added to the path. 
* Matplotlib and related modules were installed using `conda install matplotlib`.  `conda info` and `conda list` are as follows:

```
vagrant@vagrant-ubuntu-trusty-64:~$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.11.0
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/vagrant/miniconda  (writable)
  default environment : /home/vagrant/miniconda
     envs directories : /home/vagrant/miniconda/envs
        package cache : /home/vagrant/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

vagrant@vagrant-ubuntu-trusty-64:~$ conda list
# packages in environment at /home/vagrant/miniconda:
#
cairo                     1.12.18                       3  
conda                     3.11.0                   py27_0  
conda-env                 2.1.4                    py27_0  
fontconfig                2.11.1                        3  
freetype                  2.5.2                         0  
libpng                    1.5.13                        1  
libxml2                   2.9.0                         0  
matplotlib                1.4.3                np19py27_1  
numpy                     1.9.2                    py27_0  
openssl                   1.0.1k                        1  
pip                       6.1.1                    py27_0  
pixman                    0.26.2                        0  
py2cairo                  1.10.0                   py27_2  
pycosat                   0.6.1                    py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_1  
python                    2.7.9                         2  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.2                   py27_0  
pyyaml                    3.11                     py27_0  
qt                        4.8.6                         1  
readline                  6.2                           2  
requests                  2.6.0                    py27_0  
setuptools                15.1                     py27_1  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
sqlite                    3.8.4.1                       1  
system                    5.8                           2  
tk                        8.5.18                        0  
yaml                      0.1.4                         0  
zlib                      1.2.8                         0
```

* A custom .inputrc files was specified as:

```
set editing-mode vi
"\e[A":history-search-backward
"\e[B":history-search-forward
```

*  The loss of the history search after `import matplotlib.pyplot` will now occur in the Miniconda Python interpreter.  For example after starting the interpreter using `python`, `import numpy as np` works.  Then `import n` follow by up arrow will complete the line as `import numpy as np`.  Issuing the command `import matplotlib.pyplot` breaks the history search, after this import `import n` followed by the up error gives no completion.

* No loss of history search is seen in the system python interpreter (/usr/bin/python) after numpy and matplotlib are installing using apt-get (`sudo apt-get install python-numpy python-matplotlib`)

Other readline functionality also breaks when importing matplotlib.pyplot as well as other modules. 

Currently I am using the following work around in my .inputrc file to set emacs binding in the Python interpreter which maintains the history search functionality.

```
set editing-mode vi
$if Python
   set editing-mode emacs
$endif
"\e[A":history-search-backward
"\e[B":history-search-forward
```

**Comment by jjhelmus** [comment]
After more investigation this has nothing to do with the matplotlib, the issue is actually when importing PyQt4.  Specifically readline changes behavior when `import PyQt4.QtCore` is run in Python interpreter installed by miniconda.  This is seen when importing the conda PyQt4 or the PyQt4 installed by the OS.

**Comment by jjhelmus** [comment]
The root cause of this is the when the Python readline module is compiled there are two possible `readline_until_enter_or_signal` functions which are defined in the Python [readline.c source code](https://hg.python.org/cpython/file/648dcafa7e5f/Modules/readline.c) and are selected by the pre-processor based on **HAVE_RL_CALLBACK** and **HAVE_SELECT**.  

[The first](https://hg.python.org/cpython/file/648dcafa7e5f/Modules/readline.c#l981), which is used by the Ubuntu system Python, calls the readline library `rl_callback_read_char` after input is detected and run this through **PyOS_InputHook** if this is not NULL.  Therefore when QtCore is imported and **PyOS_InputHook** gets defined as some Qt character handler, the input still gets handled by the readline library in the end.   

[The second](https://hg.python.org/cpython/file/648dcafa7e5f/Modules/readline.c#l1055) `readline_until_enter_or_signal` function set the **rl_event_hook** to **PyOS_InputHook** which results in the readline library's [`rl_read_key`](http://git.savannah.gnu.org/cgit/readline.git/tree/input.c#n414) function executing this function if it is not NULL.  Therefore when QtCore is imported the Qt character handled takes complete control over input handling bypassing readline completely.  

My recommendation would be to compile the interpreter with **HAVE_RL_CALLBACK** and **HAVE_SELECT** in order to always include the readline library in the character input.  This is how Ubuntu seems to compile Python.  These settings can be checked with the following script on Python 2.7:

``` Python
import sysconfig
print "HAVE_RL_CALLBACK:", sysconfig.get_config_vars("HAVE_RL_CALLBACK")
print "HAVE_SELECT:", sysconfig.get_config_vars("HAVE_SELECT")
```

The results for the Python installed by Miniconda:

```
$ python check.py 
HAVE_RL_CALLBACK: [0]
HAVE_SELECT: [1]
```

and the Ubuntu 12.04 system Python

```
$ /usr/bin/python check.py 
HAVE_RL_CALLBACK: [1]
HAVE_SELECT: [1]
```

**Comment by ccordoba12** [comment]
Hi, could you run

    conda update python

and try again to see if things are fixed for you with our new Python version?

Thanks :-)

**Comment by jjhelmus** [comment]
@ccordoba12 Yes, the new version of Python 2,  2.7.9-3, installed with `conda update python` completely fixes this issue.  Thanks for the fix! 

```
$ conda list | grep python
python                    2.7.9                         3  
python-dateutil           2.4.2                    py27_0
$ python check
HAVE_RL_CALLBACK: [1]
HAVE_SELECT: [1]
```

**Comment by ccordoba12** [comment]
Fantastic!! Thanks for letting us know about it ;-)
