### ISSUE TITLE
graphical way to install packages from PyPI

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#3186]
Request originated from @AllenDowney, but I agree that this would be a significant benefit to Anaconda users: a graphical interface to search and install packages from PyPI.  Perhaps the most obvious way to do this would be to augment Navigator to have this functionality, but there are other ways this could be achieved.

cc @goanpeca @chdoig

**Comment by goanpeca** [comment]
@ijstokes the possibility of doing this is there (the code exists) we just decided not to expose it as mixing pip packages and conda can create problems, and providing such functionality would probably lead to more problems.

I guess we need to have a list of blacklisted packages that CANNOT be installed via pip or more general, we need to disallow pip installation of packages that are already provided as conda packages and for that we need to have a curated list of pypi names -> conda equivalent names. (graphviz pyqtt etc...

But I am open to suggestions.

**Comment by ijstokes** [comment]
conda and pip from the command line don't play nicely if they are used on the same package, so in an ideal world we'd make conda smart enough to notice pip-versions of packages before taking any action.  I think the same logic could be applied to Navigator's package management view.  Perhaps one way is to have one of the drop-down options be "PyPI packages".

There is a deeper issue we need to consider: do we believe we're in a world where the average/target Anaconda user will be able to happily exist exclusively in a conda world?  Or will they be driven to pip on the command line anyway?  My view is that pip + conda is a reality we are going to have to live with.  For our target audience I think the command line puts them off (or worse: scares them or they refuse to use it).  If we are in an environment were Anaconda, designed to be "the data science easy button", makes new-to-programming users go to the command line to get reasonably common things done then we are providing a negative user experience.  On that basis I would say we should seriously consider how we provide those users with a graphical interface for PyPI package installation, whether it is in Navigator or elsewhere.

**Comment by goanpeca** [comment]
>If we are in an environment were Anaconda, designed to be "the data science easy button", makes new-to-programming users go to the command line to get reasonably common things done then we are providing a negative user experience. On that basis I would say we should seriously consider how we provide those users with a graphical interface for PyPI package installation, whether it is in Navigator or elsewhere.

I would rather have conda packages for all available pip packages (based on some metric of usage or download) once an automated build system is in place than providing a functionality that will provide more problems than solutions.
