### ISSUE TITLE
Cannot mix incompatible Qt libraries (on KDE and Ubuntu)

### ISSUE THREAD

**Issue by almarklein** [ContinuumIO/anaconda-issues#32]
This is a common problem when applications come with their own Qt library, as is the case with (ana)conda. I have encountered this with Pyzo and the binaries for IEP. I find this error particularly easy to reproduce on a Kubuntu box.
### Cause

From what I understood, this is caused because styles and/or plugins are attempted to be loaded, but these depend on another version of Qt, causing a clash.
### Solution

Disable looking for plugins. This needs to be done in two ways: 
- there needs to be a qt.conf next to the executable that has this content: "[Paths]\nPlugins = '.'\n"
- before creating the application object, one needs to do `QtGui.QApplication.setLibraryPaths([])`. The effect of the latter seems also be achievable by instead setting the environment variable "QT_PLUGIN_PATH" to an empty string.
### Side effects

Unfortunately, when disabling the plugins, the app will look less native. No oxygen theme on KDE, no integration of the menu bar on Unity.

**Comment by astyonax** [comment]
I ``solved'' by moving all anaconda's Qt libraries in a different place:
```bash
cd anaconda/lib
mkdir oldqt
mv libQt* oldqt -v
cd 
```
I think that only the OS libraries are used now,
and anaconda's spyder and matplotlib are working fine.

I'm using netrunner 14, with kde 4.13.0 and Qt 4.8.6 

This is not a clean solution, 
a better solution would be that the qt package be installed only if needed, 
best would be that it does not look around for OS libraries at all.

**Comment by almarklein** [comment]
@astyonax beware that this situation has a high risk of errors when there are incompatibility problems; e.g. when PyQy4 is build on another version of Qt than is present on your system.

> best would be that it does not look around for OS libraries at all.

That's basically what we try to achieve with the qt.conf and QT_PLUGIN_PATH.

**Comment by astyonax** [comment]
I was indeed quite surprised that my workaround is working, 
but I'm new to anaconda, and I was looking for a simple solution to get used to get used to it.

btw: I did not want to set  qt.conf and QT_PLUGIN_PATH because I have to remember if an app is in anaconda or not.

**Comment by ripopov** [comment]
Solution with qt.conf in ~/anaconda/bin/ worked for me. Why it is not implemented in installer? - Lost some time trying to fix this in Kubuntu 14.10.

**Comment by almarklein** [comment]
Today ran to this issue again (what a nightmare) on OSX. I double-checked that I had all the fixes in place, to no avail. Then I saw that there was a directory called `imageformats` that I'd not seen before. Apparently the loading of these libs pulled in the system Qt libs, and the simple solution was simply to remove this directory. 

Granted, this was for an app frozen with cx_Freeze (and on OSX with PySide). Anaconda may be unaffected. Still sharing in the hope it may be useful to someone.

**Comment by mrmartin** [comment]
For anyone still running into this problem, the solution is now simply:
```
conda update conda
conda update anaconda
```
