### ISSUE TITLE
Launcher crashes upon starting- Windows 7

### ISSUE THREAD

**Issue by ivan7707** [ContinuumIO/anaconda-issues#322]
Hi,  I am trying to use the launcher.  I downloaded the 32 bit anaconda on my machine (windows 7, 64 bit).  I get the error:  

Sorry, the application encountered a fatal error.  Please report the following to us at ...

I downloaded anaconda on my laptop a couple of days ago (windows 7, 64 bit) and it is working just fine.

**Comment by ccordoba12** [comment]
The launcher is being reworked at the moment and a new version will be available soon.

Sorry for the inconvenience :-)

**Comment by ivan7707** [comment]
thanks for the info.

**Comment by HTrammel** [comment]
Any update on this.  I am having the same problem with a fresh download and install from today.  Thanks in advance.

**Comment by ccordoba12** [comment]
I think a new launcher will be available in Anaconda 2.3, to be released on the first week of July.

**Comment by HTrammel** [comment]
Thank you for the update.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
