### ISSUE TITLE
miniconda .bash_profile shadow .profile

### ISSUE THREAD

**Issue by Carreau** [ContinuumIO/anaconda-issues#323]
I dont' have a `.bash_profile` (usually) I have a `.profile` that get sourced (regardless of the shell I use). 

when installing miniconda, it creates an (empty) `.bash_profile` in which after it add the PATH modifs it needs. 

But then my `.profile` is not sourced anymore, which is surprising. 

When creating the `.bash_profile`, if not exist, you shoudl probably add a `source ~/.profile` in it.

**Comment by ccordoba12** [comment]
I think it's hard for us to predict every possible way in which people loads their `profile`s.

So you should skip the installation step where Miniconda/Anaconda asks about adding itself to your `PATH`. Then you can add it manually as it suits you :-)

@asmeurer, what do you think?

**Comment by Carreau** [comment]
Agree that I'm an edge case, I was just surprised, and filled an issue more as a "it would be great if", or make it google-able so that other people can find it.

It's not my only problem as I use [fish](http://fishshell.com/), and `source activate <env>` does not work, but I have to dig into it first, and this is less surprising. If there is any place where I can dig into miniconda installer and potentially submit a patch...

**Comment by ccordoba12** [comment]
Unfortunately our Miniconda installers are not part of a public repo.

Take a look at conda/conda#540 for fish.

**Comment by Carreau** [comment]
Yeah, I figured for miniconda, thanks for the fish link, I'll have a look.

**Comment by csaroff** [comment]
If ~/.bash_profile is missing, could you just check to see if ~/.profile exists and add it there if so? Is it really so non-standard to use ~/.profile in place of ~/.bash_profile?

**Comment by remkade** [comment]
For now this is not on our roadmap. Our recommendation is to use `conda init` which will work properly in all shells.
