### ISSUE TITLE
Anaconda Launcher Not working

### ISSUE THREAD

**Issue by KirthiRaman** [ContinuumIO/anaconda-issues#327]
Sorry, the application encountered a fatal error. Please report the following to us at
https://github.com/ContinuumIO/anaconda-issues

SyntaxError: Unexpected token <

**Comment by ccordoba12** [comment]
The launcher is being reworked at this moment and a new version will be available soon.

Sorry for the inconvenience :-)

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
