### ISSUE TITLE
Cannot activate environments (Windows)

### ISSUE THREAD

**Issue by edadoko** [ContinuumIO/anaconda-issues#3277]
I have installed conda and made sure the path has no non-ascii characters/numbers. 
```
               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 3.0.6
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
                          C:\Users\eda.doko\AppData\Local\conda\conda\envs
                          C:\Users\eda.doko\.conda\envs
          package cache : C:\Anaconda\pkgs
                          C:\Users\eda.doko\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/2.7.13 Windows/10 Windows/10.0.10240
          administrator : False
```

I can successfully create environments, but when I try to activate them I get the error message:

'@"C:\Anaconda\Scripts\..\python.exe" -c "import ctypes; print(ctypes.cdll.kernel32.GetACP())"' is not recognized as an internal or external command, operable program or batch file. The filename, directory name, or volume label syntax is incorrect.

When running `conda update anaconda` the error message is:
`ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::qt-5.6.2-vc9_4'.
WindowsError(2, 'The system cannot find the file specified')
Attempting to roll back.
WindowsError(2, 'The system cannot find the file specified')`

Running `conda install qt=5.6.2` results again in:
`ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::qt-5.6.2-vc9_5'.
WindowsError(2, 'The system cannot find the file specified')
Attempting to roll back.
WindowsError(2, 'The system cannot find the file specified')`

`conda install pyqt --force,` and `conda install qtpy --force` work, but `conda install qt --force` again fails with the same error message. 

The error message from `anaconda-navigator` is:
`Traceback (most recent call last):
  File "C:\Anaconda\Scripts\anaconda-navigator-script.py", line 5, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\app\main.py", line 59, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Anaconda\lib\site-packages\qtpy\__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found`

**Comment by goanpeca** [comment]
@edadoko did you install for all users or just for the current user?

**Comment by edadoko** [comment]
For all users

**Comment by goanpeca** [comment]
@edadoko could try reinstalling just for the current user and use the suggested defaults?

**Comment by edadoko** [comment]
Sure, by defaults do you mean filling in the path environment manually? @goanpeca

**Comment by goanpeca** [comment]
@edadoko I mean download the latest installer and follow all the default options that are selected in the installer and make sure to install in a place without spaces or non-ascii characters/numbers.

It could be the path you used or even `C:\Users\eda.doko\anaconda`

**Comment by edadoko** [comment]
that is why I'm not using the default path because it suggests  `C:\Users\eda.doko\AppData\Local\Continuum\Anaconda2` but AppData is a hidden folder. I was using `C:\Anaconda`. 
But I did reinstall and install everything as suggested, and I am still getting the same error.

**Comment by goanpeca** [comment]
@kalefranz

**Comment by Rodolphe21** [comment]
I have also the same issue, and have installed following the standard option (only for me the user) and behind AppData... See my post here: https://github.com/ContinuumIO/anaconda-issues/issues/3581

What is the solution please?  

Thank you

Cheers,

Rodolphe

**Comment by goanpeca** [comment]
If the installer suggests something like

`C:\Users\<username>\AppData\Local\Continuum\Anaconda2` please change to 

`C:\Users\<username>\Anaconda2`
