### ISSUE TITLE
HTTP error still occurs

### ISSUE THREAD

**Issue by WolfDSCoder** [ContinuumIO/anaconda-issues#3293]
Please don't close this without considering that I tried the suggestion to update navigator and get the same HTTP and SSL error.

- conda update anaconda-navigator --> same HTTP error
- there is no update button on anaconda navigator

#3292 #1932

**Comment by goanpeca** [comment]
@WolfDSCoder those errors are transient, either the server was down temporarily or you internet connection went down temporarily
