### ISSUE TITLE
Conda python using old python's sys.path

### ISSUE THREAD

**Issue by andreas-wilm** [ContinuumIO/anaconda-issues#332]
Hi,

our anaconda installation all of a sudden uses the old Python path again. This problem is identical to https://github.com/ContinuumIO/anaconda-issues/issues/156 which apparently was fixed with a reinstallation. This is a shared installation so I'd like to fix it without reinstalling if possible.

    which python
    /mnt/software/unstowable/anaconda/bin/python

    python
    >>> import sys
    >>> sys.path
    ['', '/mnt/software/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', ...]
    # mnt/software/lib/python2.7/ was the pre-anaconda installation

No Python related environment variables are set. 

    set | grep PYTHON
    # empty
    
Reinstalling Python with conda consequently also fails:

    conda install -f python
    Traceback (most recent call last):
    File "/mnt/software/unstowable/anaconda/bin/conda", line 4, in <module>
    from conda.cli import main
    File "/mnt/software/unstowable/anaconda/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from conda.cli.main import main
    File "/mnt/software/unstowable/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 43, in <module>
    import argparse
    File "/mnt/software/lib/python2.7/argparse.py", line 85, in <module>
    import collections as _collections
    File "/mnt/software/lib/python2.7/collections.py", line 8, in <module>
    from _collections import deque, defaultdict
    ImportError: No module named _collections
 
Any ideas?

Andreas

**Comment by andreas-wilm** [comment]
It turns out plenty of files were missing from anaconda/lib/python2.7 for no apparent reason. Restoring the files fixed the installation.

Andreas

**Comment by ccordoba12** [comment]
Thanks for letting us know.

**Comment by andreas-wilm** [comment]
Actually, we have no indication of how this happened and write access was restricted. Also this seems to have happened before (see linked issue). The only unusual thing that happened before the break down was that a conda lock was acquired.

**Comment by andreas-wilm** [comment]
And it just happend again for a second while installing packages in another terminal and during the extracting, unlinking and linking stages. After the commands were done things worked again.
