### ISSUE TITLE
Crash of Launcher 

### ISSUE THREAD

**Issue by abuadan** [ContinuumIO/anaconda-issues#333]
Attempted to install gluviz when the installation failed the launcher displayed this error;
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by ccordoba12** [comment]
The launcher is being reworked right now and a new version will be available soon.

Sorry for the inconvenience :-)

**Comment by alaindomissy** [comment]
I experience the same error:
Using Ubuntu 15.04
installed: Anaconda3-2.2.0-Linux-x86_64.sh
updated anaconda : conda update --prefix /home/user/anaconda3 anaconda
installed launcher: conda install launcher
when starting launcher, get this error:

Sorry, the application encountered a fatal error. Please report the following to us at https://github.com/ContinuumIO/anaconda-issues.

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

Would there be any work around while we wait for the next version of launcher? Thank you very much!

**Comment by alaindomissy** [comment]
The above error only appears when I use Ubuntu launcher, search for "launcher" and click on the found (anaconda) Launcher icon.
If I f use a consiole andd type launcher, the anaconda launcger starts up fine.
So I now have a workaround to use laucher

**Comment by meyersbs** [comment]
If I enter any of the following commands, anaconda runs just fine.
``` bash
    launcher
    /opt/anaconda3/bin/launcher
    bash /opt/anaconda3/bin/launcher
```

However, if I copy any of those commands into a new menu item, they all fail with the error mentioned above. It's been two months, why isn't this fixed?

**Comment by MikhSol** [comment]
The same for me on Mac OS X.

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

It appears after I interrupt spider update and try to create a new environment.
Maybe it will help.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by MikhSol** [comment]
I try to run it. Smoke test was passed. If i will have some problems during
the work, I will send you a letter.
Thank you.

2015-10-06 16:33 GMT+03:00 Gonzalo Peña-Castellanos <
notifications@github.com>:

> Hi, we are working on a new launcher which should address the issues
> presented by the previous version.
>
> If you would like to try it please go to a terminal, remove the previous
> launcher, install the new version and launch it by typing:
>
> conda remove launcher
> conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
> launcher
>
> Let us know if the issues persist, or any other comments and suggestions
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuumIO/anaconda-issues/issues/333#issuecomment-145857093>
> .
>



-- 
Best regards,
Mikhail.

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
