### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vijey18** [ContinuumIO/anaconda-issues#3331]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 19:05:00.175 NotebookApp] The port 8888 is already in use, trying another port.
[I 19:05:00.178 NotebookApp] The port 8889 is already in use, trying another port.
[I 19:05:00.248 NotebookApp] Serving notebooks from local directory: C:\Users\vijeykumar.selvaraj
[I 19:05:00.248 NotebookApp] 0 active kernels 
[I 19:05:00.248 NotebookApp] The Jupyter Notebook is running at: http://localhost:8890/?token=c7ca86d099d990ab81757236108e4a8b161a20d1d491621d
[I 19:05:00.249 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:05:00.252 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=c7ca86d099d990ab81757236108e4a8b161a20d1d491621d
[I 19:05:00.963 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 19:05:00.965 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 19:05:01.005 NotebookApp] 404 GET /tree?token=55424f419a42c4f6041ff0c025a243887ba6267c06030445 (::1) 42.00ms referer=None
[I 19:05:03.731 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 19:05:03.735 NotebookApp] 404 GET /tree (::1) 5.00ms referer=http://localhost:8890/tree

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
See https://github.com/jupyter/notebook/issues/2382

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Comment by vijey18** [comment]
I am trying to open the jupter notebook either through the jupyter notebook or the console and the above error is what i repeatedly get. I have installed the anaconda software using administrator access. Any help to launch the notebook would be appreciated.

**Comment by vijey18** [comment]
Hi, even after updating the Navigator I encounter the same issue again.

**Comment by vijey18** [comment]
[I 19:21:42.882 NotebookApp] The port 8888 is already in use, trying another port.
[I 19:21:42.960 NotebookApp] Serving notebooks from local directory: C:\Users\vijeykumar.selvaraj
[I 19:21:42.961 NotebookApp] 0 active kernels 
[I 19:21:42.961 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=955d64e0b82d4b0383c2bef4b7f7048d0248bfedcb841ca3
[I 19:21:42.961 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:21:42.964 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8889/?token=955d64e0b82d4b0383c2bef4b7f7048d0248bfedcb841ca3
[I 19:21:43.660 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 19:21:43.662 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 19:21:43.702 NotebookApp] 404 GET /tree?token=483f15d05c85d990c7b495edae74712ea4aa1f8e25d382b8 (::1) 41.98ms referer=None
