### ISSUE TITLE
RStudio not opening on Mac

### ISSUE THREAD

**Issue by sebastian-luna-valero** [ContinuumIO/anaconda-issues#3338]
Hello,

I was helping @hkoohy to install the latest `rstudio` with conda on a Mac.

The installation itself went fine, but when you type `rstudio` at the CLI the program does not start and we only get a small, blank window with an `OK` button on it.

Here you are the information about the environment:
```
rstudio 1.0.136
conda: 4.3.22
macbook pro: 10.12.5
```

Has anyone successfully used conda's `rstudio` on Mac? If so, could you please share the installation instructions, please?

Many thanks for your help.

Sebastian

**Comment by mingwandroid** [comment]
Can you try from `anaconda-navigator`? It's another Qt based application, does that run OK?

Do you have any other R installed? On PATH? With files in ~?

`conda list --show-channel-urls` would be helpful here. While RStudio is running can you should the output of:

`lsof -p $(ps aux | grep rstudio | sort | head -1 | tr -s " " | cut -f2 -d' ') | grep "\.so\|.dylib" | tr -s " " | cut -f9 -d' ' | sort | xargs md5 | sed -E 's|(MD5 \()([0-9a-zA-Z/.+\_-]*)\) = ([0-9a-f]*)|\3 \2|g' | sort`

**Comment by sebastian-luna-valero** [comment]
Many thanks @mingwandroid 

I think we were facing an ABI incompatibility again between `defatuls`, `r`, `conda-forge` and `bioconda`. 

The issue is that we work in Bioinformatics and a vast amount of dependencies are going to `bioconda` and `conda-forge`. I have faced several issues so far due to the ABI incompatibility. In my opinion, there should be a discussion/co-ordination between the communities involved in order to prevent these issues from happening, otherwise it will be harmful for the reputation of conda and its acceptance.

Below are my experiments with conda environment files. I hope you find them useful.

Best regards,
Sebastian

* option 1:

```
name: rstudio

channels:
- defaults
- r

dependencies:
- rstudio
```

worked well, with:

```
lsof -p $(ps aux | grep rstudio | sort | head -1 | tr -s " " | cut -f2 -d' ') | grep "\.so\|.dylib" | tr -s " " | cut -f9 -d' ' | sort | xargs md5 | sed -E 's|(MD5 \()([0-9a-zA-Z/.+\_-]*)\) = ([0-9a-f]*)|\3 \2|g' | sort
e933057789e60406502f57c28ba7dcb8 /Users/sebastian/conda/i1/envs/rstudio/lib/libz.1.2.8.dylib

lsof -p $(ps aux | grep rsession | sort | head -1 | tr -s " " | cut -f2 -d' ') | grep "\.so\|.dylib" | tr -s " " | cut -f9 -d' ' | sort | xargs md5 | sed -E 's|(MD5 \()([0-9a-zA-Z/.+\_-]*)\) = ([0-9a-f]*)|\3 \2|g' | sort
129fc5d2ba037edfb6fe00d9dc348cbc /Users/sebastian/conda/i1/envs/rstudio/lib/libssl.1.0.0.dylib
14fa67f1ad9ddca0c1da9c45a01ceee1 /Users/sebastian/conda/i1/envs/rstudio/lib/R/modules/internet.so
1a09dfba6f026fad207f0c13907c7584 /Users/sebastian/conda/i1/envs/rstudio/lib/libssh2.1.0.1.dylib
243c2dba1ed69359f84183fde5cd8b38 /Users/sebastian/conda/i1/envs/rstudio/bin/rsclang/libclang.dylib
24ef24669e10025ec0575d7d2b7f9b91 /Users/sebastian/conda/i1/envs/rstudio/lib/libgfortran.3.dylib
2849cf030117a2fa118407eb053fc6d3 /Users/sebastian/conda/i1/envs/rstudio/lib/libkrb5.3.3.dylib
36331432dd74e886e8aef01549318fdf /Users/sebastian/conda/i1/envs/rstudio/lib/R/library/graphics/libs/graphics.so
38a514e9bbb2c69fbe7ac0f050c62aa9 /Users/sebastian/conda/i1/envs/rstudio/lib/libicuuc.54.1.dylib
3b1fa0543edc86ff34aa4511780eb4c7 /Users/sebastian/conda/i1/envs/rstudio/lib/libcrypto.1.0.0.dylib
576fe275f7924783348ee40c1a815595 /Users/sebastian/conda/i1/envs/rstudio/lib/libcurl.4.dylib
58dedf3c5ee743de351c171a643c601b /Users/sebastian/conda/i1/envs/rstudio/lib/R/library/stats/libs/stats.so
5e8cdc0a48b3d8a7d4dc2ccd1b20ce3d /Users/sebastian/conda/i1/envs/rstudio/lib/libintl.9.dylib
61d6cbeebeebeb3756df04ccf4fb7cbb /Users/sebastian/conda/i1/envs/rstudio/lib/libcom_err.3.0.dylib
7ffb65a84922076bf9f9703927069d06 /Users/sebastian/conda/i1/envs/rstudio/lib/R/library/grDevices/libs/grDevices.so
8ce46eed21723109e0995261078caf2b /Users/sebastian/conda/i1/envs/rstudio/lib/R/lib/libR.dylib
a2d79a058d6dfed7d5ce4f1b08ca0794 /Users/sebastian/conda/i1/envs/rstudio/lib/libk5crypto.3.1.dylib
b046bd07a9730dc2cc56e289530f98bc /Users/sebastian/conda/i1/envs/rstudio/lib/libgcc_s.1.dylib
bcac4111a08ef28530c77660640ed2d9 /Users/sebastian/conda/i1/envs/rstudio/lib/liblzma.5.dylib
bce1dd21f4f13012d25aa1531ff60cbf /Users/sebastian/conda/i1/envs/rstudio/lib/R/library/methods/libs/methods.so
bda804b0b0f7643e7864a06b66217342 /Users/sebastian/conda/i1/envs/rstudio/lib/libkrb5support.1.1.dylib
c7ca60c64ec4f7e6031e08df717e9a75 /Users/sebastian/conda/i1/envs/rstudio/lib/libquadmath.0.dylib
d159af09c65333f9bbb424a0eee4078d /Users/sebastian/conda/i1/envs/rstudio/lib/libicudata.54.1.dylib
d7cb98b69b34b681e604cf90041afad0 /Users/sebastian/conda/i1/envs/rstudio/lib/R/library/utils/libs/utils.so
dcfc8bb9b615176679aa9097f5b8acb5 /Users/sebastian/conda/i1/envs/rstudio/lib/libreadline.6.2.dylib
e581f6eaa56d5cc5a73871954fa27858 /Users/sebastian/conda/i1/envs/rstudio/lib/libicui18n.54.1.dylib
e933057789e60406502f57c28ba7dcb8 /Users/sebastian/conda/i1/envs/rstudio/lib/libz.1.2.8.dylib
ecfe2aef1bd19212b429444d66974689 /Users/sebastian/conda/i1/envs/rstudio/lib/libpcre.1.dylib
eef395af67294b6b702e174d56ac5c9f /Users/sebastian/conda/i1/envs/rstudio/lib/libgssapi_krb5.2.2.dylib
f8a91209556db7d6c968711419dab939 /Users/sebastian/conda/i1/envs/rstudio/lib/libiconv.2.dylib
fc3cf7e368f4b233cc69ac3b540981d5 /Users/sebastian/conda/i1/envs/rstudio/lib/R/library/tools/libs/tools.so
```

* option 2:

```
name: rstudio-others

channels:
- bioconda
- conda-forge
- defaults

dependencies:
- rstudio
- bioconductor-deseq2
```

hangs forever, with:

```
conda env create -f env.rstudio.others 
Fetching package metadata ...............
Solving package specifications: .^C
Traceback (most recent call last):
  File "/Users/sebastian/conda/i1/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda_env/cli/main.py", line 76, in main
    return conda_exception_handler(args.func, args, parser)
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda_env/installers/conda.py", line 32, in install
    channel_priority_map=_channel_priority_map)
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/plan.py", line 489, in install_actions_list
    for specs_by_prefix in required_solves]
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/plan.py", line 489, in <listcomp>
    for specs_by_prefix in required_solves]
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/resolve.py", line 915, in solve
    solution, obj6 = C.minimize(eq_b, solution)
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/logic.py", line 536, in minimize
    newsol = self.sat()
  File "/Users/sebastian/conda/i1/lib/python3.6/site-packages/conda/logic.py", line 438, in sat
    solution = pycosat.solve(clauses, vars=self.m, prop_limit=limit)
KeyboardInterrupt
```

* option 3:

```
name: rstudio-others

channels:
- bioconda
- conda-forge
- defaults
- r

dependencies:
- rstudio
- bioconductor-deseq2
```

hangs forever again, same problem as above.

* option 4:

```
name: rstudio-others

channels:
- defaults
- r
- bioconda
- conda-forge

dependencies:
- rstudio
- bioconductor-deseq2
```

worked well, with:

```
lsof -p $(ps aux | grep rstudio | sort | head -1 | tr -s " " | cut -f2 -d' ') | grep "\.so\|.dylib" | tr -s " " | cut -f9 -d' ' | sort | xargs md5 | sed -E 's|(MD5 \()([0-9a-zA-Z/.+\_-]*)\) = ([0-9a-f]*)|\3 \2|g' | sort
e933057789e60406502f57c28ba7dcb8 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libz.1.2.8.dylib

lsof -p $(ps aux | grep rsession | sort | head -1 | tr -s " " | cut -f2 -d' ') | grep "\.so\|.dylib" | tr -s " " | cut -f9 -d' ' | sort | xargs md5 | sed -E 's|(MD5 \()([0-9a-zA-Z/.+\_-]*)\) = ([0-9a-f]*)|\3 \2|g' | sort
129fc5d2ba037edfb6fe00d9dc348cbc /Users/sebastian/conda/i1/envs/rstudio-others/lib/libssl.1.0.0.dylib
14fa67f1ad9ddca0c1da9c45a01ceee1 /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/modules/internet.so
243c2dba1ed69359f84183fde5cd8b38 /Users/sebastian/conda/i1/envs/rstudio-others/bin/rsclang/libclang.dylib
24ef24669e10025ec0575d7d2b7f9b91 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libgfortran.3.dylib
2849cf030117a2fa118407eb053fc6d3 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libkrb5.3.3.dylib
2cf723bc70c18dc3ea2a68947ff44e93 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libcrypto.1.0.0.dylib
36331432dd74e886e8aef01549318fdf /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/library/graphics/libs/graphics.so
38a514e9bbb2c69fbe7ac0f050c62aa9 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libicuuc.54.1.dylib
58dedf3c5ee743de351c171a643c601b /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/library/stats/libs/stats.so
61d6cbeebeebeb3756df04ccf4fb7cbb /Users/sebastian/conda/i1/envs/rstudio-others/lib/libcom_err.3.0.dylib
7ffb65a84922076bf9f9703927069d06 /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/library/grDevices/libs/grDevices.so
8c102dd1276d49133028c7d4f66a5ab4 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libiconv.2.dylib
8ce46eed21723109e0995261078caf2b /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/lib/libR.dylib
a2d79a058d6dfed7d5ce4f1b08ca0794 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libk5crypto.3.1.dylib
ab2b886e04408db75e7df0c8eddd0402 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libssh2.1.0.1.dylib
b046bd07a9730dc2cc56e289530f98bc /Users/sebastian/conda/i1/envs/rstudio-others/lib/libgcc_s.1.dylib
bc21234f4b2f54649061cc203fec9f5b /Users/sebastian/conda/i1/envs/rstudio-others/lib/libintl.9.dylib
bcac4111a08ef28530c77660640ed2d9 /Users/sebastian/conda/i1/envs/rstudio-others/lib/liblzma.5.dylib
bce1dd21f4f13012d25aa1531ff60cbf /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/library/methods/libs/methods.so
bda804b0b0f7643e7864a06b66217342 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libkrb5support.1.1.dylib
c7ca60c64ec4f7e6031e08df717e9a75 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libquadmath.0.dylib
d159af09c65333f9bbb424a0eee4078d /Users/sebastian/conda/i1/envs/rstudio-others/lib/libicudata.54.1.dylib
d7cb98b69b34b681e604cf90041afad0 /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/library/utils/libs/utils.so
dcfc8bb9b615176679aa9097f5b8acb5 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libreadline.6.2.dylib
e581f6eaa56d5cc5a73871954fa27858 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libicui18n.54.1.dylib
e933057789e60406502f57c28ba7dcb8 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libz.1.2.8.dylib
ecfe2aef1bd19212b429444d66974689 /Users/sebastian/conda/i1/envs/rstudio-others/lib/libpcre.1.dylib
eef395af67294b6b702e174d56ac5c9f /Users/sebastian/conda/i1/envs/rstudio-others/lib/libgssapi_krb5.2.2.dylib
fc288b07ae26a39af815d46a1380db8f /Users/sebastian/conda/i1/envs/rstudio-others/lib/libcurl.4.dylib
fc3cf7e368f4b233cc69ac3b540981d5 /Users/sebastian/conda/i1/envs/rstudio-others/lib/R/library/tools/libs/tools.so
```

but when I do `library(DESeq2)` I get:
```
Error: package ‘DESeq2’ was built for x86_64-apple-darwin14.5.0
```

**Comment by mingwandroid** [comment]
> The issue is that we work in Bioinformatics and a vast amount of dependencies are going to bioconda and conda-forge. I have faced several issues so far due to the ABI incompatibility. In my opinion, there should be a discussion/co-ordination between the communities involved in order to prevent these issues from happening, otherwise it will be harmful for the reputation of conda and its acceptance

We are trying to solve these issues but it will be *very* difficult. At least we hope to base our recipes on `conda-forge` recipes, but that says nothing for toolchains and system libraries. We will never, for example, provide `X11` or anything that talks so directly to the hardware (mesa vs nvidia vs AMD) or has a blessed system package (XQuartz) while `conda-forge` went ahead and did that. I tried to convince the others that providing `X11` and forcing it on people was not a good thing to do but I failed.

**Comment by sebastian-luna-valero** [comment]
Many thanks for your answer. This is an interesting discussion.

I assume you are very busy, but when you have a spare time at some point (no rush at all), I would be very interested in knowing more about your proposal for an ideal scenario to solve these issues. Could you please elaborate a little bit more your answer? (so people with a limited view of the big picture like myself can understand better the issue and the stumbling blocks)

For example, I can see dependencies with `X11` a hard requirement for certain plotting packages. How would you go about solving that? Do you think containers have a role to play in overcoming this problem? (please see the other discussion [here](https://github.com/bioconda/bioconda-utils/issues/81#issuecomment-318480205))

**Comment by mingwandroid** [comment]
The *solution* to these issues is complex and likely not achievable. I don't think I could summarise it without doing a disservice to both the issues and the people involved but I'll try anyway.

Some of them are technical and here we can *hope* that the 'best' (such that an objective measure even exists) solution will win out, but generally, even the 'best' solution comes with baggage - most likely in the form of package rebuilding or incompatibility with old packages.

Some of them are to do with people and their preferences, sometimes well founded in the technical realm,  sometimes to do with practicality and sometimes to do with a subtle (but very important) difference in opinion about what the goals are.  Other times, the differences are rooted in ideology (GPL vs proprietary, GCC vs clang, etc).

I can't really talk about the `X11` thing further than I already have except to say that I had a strong opinion that we shouldn't package it as it is a system library that interfaces with hardware (and therefore very easy for pretty much everyone to install when they need it) but the decision went the other way and that caused another rift in compatibility between `conda-forge` and `defaults`.

These days, I'm pushing for compatibility at the recipe level as much as possible and sharing efforts in curating those recipes and if we get *some* degree of binary compatibility as a result of that then great, but I'm not going to compromise the quality of `defaults` chasing that (probably unobtainable) goal.

It is my opinion that one of conda-forge's inviolable rules (or at least one of its strong guiding principles) should have been compatibility with defaults. I understand why that didn't happen at the time though - it is very difficult to be compatible with something you cannot see the source code of or contribute fixes to.

**Comment by sebastian-luna-valero** [comment]
Hi @mingwandroid 

Sorry for my late response. Indeed, very interesting. Many thanks for your time and effort to write these answers.

I agree there is no single path going forward, and I am with you when you say that quality should go before convenience. 

I will close the issue, and we'll keep trying to work around ABI incompatibilities hopefully with everyone's help.

Many thanks again!

Best regards,
Sebastian
