### ISSUE TITLE
404 Error encountered while opening Jupyter Notebook

### ISSUE THREAD

**Issue by vijey18** [ContinuumIO/anaconda-issues#3339]
While attempting to launch a jupyter notebook on windows 7, 

Error logs:-
=====================================================================
[I 21:25:56.119 NotebookApp] Serving notebooks from local directory: C:\Users\vijeykumar.selvaraj
[I 21:25:56.120 NotebookApp] 0 active kernels 
[I 21:25:56.120 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=106507e4d771ddcb1be2c4d4b8476186c36f05c85884abcf
[I 21:25:56.121 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:25:56.124 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=106507e4d771ddcb1be2c4d4b8476186c36f05c85884abcf
[I 21:25:56.837 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 21:25:56.839 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 21:25:56.882 NotebookApp] 404 GET /tree?token=1eb74089462c1c3e2027a2aacb97ba73db5426e3aa403f76 (::1) 46.00ms referer=None
===================================================================
Navigator.log
==========
```json
[
    {
        "level": "ERROR",
        "line": 287,
        "message": "error",
        "method": "communicate",
        "module": "conda_api",
        "path": "C:/Users/vijeykumar.selvaraj/AppData/Local/Continuum/Anaconda3/lib/site-packages/anaconda_navigator/api/conda_api.py",
        "time": "2017-07-19 18:27:06,578"
    }
]
```
===================================================================
Package details:-
Anaconda version is 4.3.22

Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
                          C:\Users\vijeykumar.selvaraj\AppData\Local\conda\conda\envs
                          C:\Users\vijeykumar.selvaraj\.conda\envs
          package cache : C:\Anaconda3\pkgs
                          C:\Users\vijeykumar.selvaraj\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\vijeykumar.selvaraj\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Windows/7 Windows/6.1.7601    
          administrator : True

**Comment by goanpeca** [comment]
See https://github.com/jupyter/notebook/issues/2382

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```
