### ISSUE TITLE
Launcher not working (past 2 weeks)

### ISSUE THREAD

**Issue by KirthiRaman** [ContinuumIO/anaconda-issues#334]
I keep getting
"Uncaught SyntaxError: Unexpected token <", source: https://gateway.zscaler.net/auD?origurl=http%3A%2F%2Fwww%2egoogle%2danalytics%2ecom%2fanalytics%2ejs&wexps=1 (1)

popups and eventually have to exit.

I had installed launcher 6 months ago on my old macbook and it works perfectly fine.  I have a new laptop and I was trying to install on this one, I never had luck for a long time.  This is very very very discouraging for people to embrace Anaconda as IDE.  If this is not resolved soon, I'll probably switch to other IDE.

Thanks

**Comment by KirthiRaman** [comment]
OK. I finally figured that /bin/spyder is working.  However, the launcher still should be fixed. !

**Comment by ccordoba12** [comment]
Yes, the laucher is still not working. Sorry for that :-)
