### ISSUE TITLE
404 error seen  while attempting to open jupyter notebook even after upgrading conda package

### ISSUE THREAD

**Issue by vijey18** [ContinuumIO/anaconda-issues#3341]
404 Error is seen even after upgrading to the latest conda package

(C:\Anaconda3) C:\Users\vijeykumar.selvaraj>conda update anaconda-navigator
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Anaconda3:
#
anaconda-navigator        1.6.3                    py36_0

**Comment by vijey18** [comment]
The previous case have been closed citing updation of conda package will solve the 404 issue. That was not the case. Cases 3331 and 3339 were closed citing that these cases were a duplicate of case 2382. However that is not the case

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
