### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by himimireyes** [ContinuumIO/anaconda-issues#3350]
wd:~$ anaconda-navigator
After anaconda-navigator lanches, this line shows up: 

libpng warning: iCCP: known incorrect sRGB profile

Is there anything I need to resolve it? 
After searching I can't find a similar issue. 
Thanks,
Noemi

**Comment by goanpeca** [comment]
@himimireyes the is just a warning, you can safely ignore it
