### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by xldistance** [ContinuumIO/anaconda-issues#3359]
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda2
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda2'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_tensorflow --clone="C:\ProgramData\Anaconda2\envs\tensorflow"

```
## System information
```
platform: win-32
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: zh_CN
python: 2.7.13
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@xldistance it seems you installed anaconda for all users and created that command using admin privileges, now every time you need to change that environment you have to use admin privileges as well (an Anaconda Prompt opened as Administrator).

I would recommend in general to not install for all users, but only for the current user as the installer suggests by default.
