### ISSUE TITLE
spyder do not show the main interface

### ISSUE THREAD

**Issue by ShijianXu** [ContinuumIO/anaconda-issues#3376]
I double click the icon of spyder, and it starts the program. But after that, it can not enter the interface. I do not know how to deal with it.
it showed this,
![Uploading a.PNG…]()
and then, nothing.
My laptop is win10, 64.

**Comment by ShijianXu** [comment]
![a](https://user-images.githubusercontent.com/15571333/28423600-0dd8ca14-6d9e-11e7-829f-b12e6d703c36.PNG)

**Comment by ccordoba12** [comment]
Please open a terminal, run this command there

    spyder --show-console

and post here any errors you see.

**Comment by ShijianXu** [comment]
well, it seems no error was shown in the console.
![a](https://user-images.githubusercontent.com/15571333/28445998-9495b3e4-6dfa-11e7-9254-9d2dab89dc1e.PNG)
![b](https://user-images.githubusercontent.com/15571333/28446005-99f17c1a-6dfa-11e7-8e49-63fb1bcd97ac.PNG)

**Comment by ShijianXu** [comment]
Before the problem occurs, I was running a neural network. and then my computer crashed, so I closed spyder by task manager forcedly. And after that, spyder can not show the interface.

**Comment by ccordoba12** [comment]
Ok, then please run

    spyder --reset

and try to open Spyder again. That should fix your problem.

**Comment by ShijianXu** [comment]
Yes, the problem fixed. Thanks a lot.
