### ISSUE TITLE
opencv out of date on osx

### ISSUE THREAD

**Issue by dougalsutherland** [ContinuumIO/anaconda-issues#339]
It seems like the OSX package for opencv hasn't been built in a while; it's 2.4.8 rather than the latest 2.4.10, but more importantly it seems to only be available for numpy 1.7.

I'm building it now myself with [the recipe from conda/conda-recipes](https://github.com/conda/conda-recipes/tree/master/opencv), but it'd be nice to not have to do that. :)

**Comment by dougalsutherland** [comment]
For some reason the build failed for me:

```
[ 48%] Building CXX object modules/legacy/CMakeFiles/opencv_legacy.dir/src/calibfilter.cpp.o
/usr/local/anaconda/conda-bld/work/opencv-2.4.10/modules/legacy/src/calibfilter.cpp:98:9: error:
      comparison of array 'this->latestPoints' not equal to a null pointer is
      always true [-Werror,-Wtautological-pointer-compare]
    if (latestPoints != NULL)
        ^~~~~~~~~~~~    ~~~~
/usr/local/anaconda/conda-bld/work/opencv-2.4.10/modules/legacy/src/calibfilter.cpp:526:9: error:
      address of array 'this->latestCounts' will always evaluate to 'true'
      [-Werror,-Wpointer-bool-conversion]
    if( latestCounts )
    ~~  ^~~~~~~~~~~~
2 errors generated.
make[2]: *** [modules/legacy/CMakeFiles/opencv_legacy.dir/src/calibfilter.cpp.o] Error 1
make[1]: *** [modules/legacy/CMakeFiles/opencv_legacy.dir/all] Error 2
make: *** [all] Error 2
```

though the homebrew version installed successfully (against system python, not conda).

I'll look into why tomorrow, maybe. (Does homebrew not compile `modules/legacy`?)

**Comment by groutr** [comment]
We also get the those errors on our build machines.  However, I was able to compile 3.0rc1 successfully.  I don't know very much about opencv.  Will a 3.0 package break a lot of things?

**Comment by dougalsutherland** [comment]
I don't know, I'm not very familiar with the library either. (I ended up not needing it for what I was going to use it for the other day.)

It seems like compiling with `-Wno-error=-Wpointer-bool-conversion -Wno-error=-Wtautological-pointer-compare` should make it work, but I haven't been able to get that to work by setting either `CXXFLAGS` or `ARCHFLAGS` in `build.sh`. I haven't looked into their build scripts at all to see if that's not being honored for some reason.

**Comment by groutr** [comment]
I'll close this issue then.  We'll probably update opencv when 3.0.0 is released.  It includes support for Python 3.
