### ISSUE TITLE
[miniconda] psutil can not be installed

### ISSUE THREAD

**Issue by delicb** [ContinuumIO/anaconda-issues#34]
With fresh installation of Miniconda3-2.0.3-Windows-x86_64.exe I can not install psutil.
This is output from cmd:

```
D:\ $ conda install psutil
# All requested packages already installed.
# packages in environment at C:\bin\Anaconda:
#

D:\ $ conda remove psutil
Error: no packages found to remove from environment: C:\bin\Anaconda

D:\ $
```

OS is Windows 7 64-bit. 
I have tried to do `conda clean -tli` and repeat installatin but that did not help.

When I create new environment (also python 3.3), I can install psutil in it, but I need psutil in main environment because `conda build` uses it for creating new packages. I think that psutil should come preinstalled since conda needs it, like yaml.

**Comment by RutgerK** [comment]
@delicb, i can replicate this behavior with conda 3.10.1 on Win7 64bit. But only in the root installation, using -f (--force) makes no difference. If i create a new environment, `conda install psutil` works as expected. That might be a workaround if you really need it.

**Comment by delicb** [comment]
Hi @RutgerK, thanks for the reply.

I do not have access to Windows machine anymore to confirm that this is still an issue and since I am not using Windows any more, I am not affected by this issue. However, I think that it would be great if this is fixed, since it can be a blocker for some people (`conda build` uses main envinronment, so installing psutil in new environment is not covering that use case).

**Comment by groutr** [comment]
I cannot reproduce this issue on my Win7 64bit machine.  I also noted that the miniconda installer seems to include psutil already.
