### ISSUE TITLE
Cannot install patch under Windows and Python 3

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#340]
```
Z:\llvmlite>conda install patch
Fetching package metadata: ........
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following combinations of packages create a conflict with the
remaining packages:
  - python 3.4*
  - patch
```

**Comment by ccordoba12** [comment]
On Windows the installed `patch` is a Python program, not GNU `patch`. So it seems that program is not compatible with Python 3.

There was a proposal to create a conda package for GNU `patch` but I think nobody has worked on that so far :-)

**Comment by remram44** [comment]
patch is no longer a Python script (see resolution for #119) so this should now be solved.

**Comment by msarahan** [comment]
Thanks @remram44 closing
