### ISSUE TITLE
"conda run" steals the options of the script it is running

### ISSUE THREAD

**Issue by davekirby** [ContinuumIO/anaconda-issues#342]
When running an application via "conda run" any --options that you pass to the script are read by conda run itself instead of the application you are trying to run.

For example:
```
$ conda run ipython --pylab
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: --pylab
```

This means that you cannot run any application that needs command line options, 

I am running conda 3.12 with Python 3.4.3

**Comment by asmeurer** [comment]
You can force the arguments to be interpreted as the command by using `--`, like `conda run -- ipython --pylab`. This should probably be documented better.

**Comment by bjfar** [comment]
This doesn't seem to work anymore? I now get "--: command not found"
