### ISSUE TITLE
Boost 1.57.0 broken on Mac

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#343]
When installing boost 1.57.0 on mac, none of the libraries are installed. This should be rebuilt.

**Comment by ccordoba12** [comment]
Just to clarify: are you talking about Boost from Anaconda or Boost from a Binstar channel? I say it because of what you wrote in the title of this issue :-)

**Comment by jakirkham** [comment]
Boost from the Anaconda channel on Binstar. So, I guess Boost from Anaconda would be accurate.

**Comment by jakirkham** [comment]
I have a feeling that it failed to identify the compiler to use. At least, that is a problem that I have seen, which had the same effect.

**Comment by jakirkham** [comment]
@ccordoba12, if you think this belongs under a different issue tracker, I would be happy to move it. Just let me know.

**Comment by ccordoba12** [comment]
What command are you using in this case to install boost?

**Comment by jakirkham** [comment]
Simply `conda install boost`. If you try extracting the OS X archive here ( https://binstar.org/anaconda/boost/files ), only the `include` and `info` directories are present. There is no `lib` directory as would be expected.

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification. I was a bit confused because when users mention Binstar it's usually to refer to third-party packages, not to packages officially distributed by Continuum.

This is a very bad situation, so I'll try to fix it as soon as possible.

**Comment by jakirkham** [comment]
Ah ok, sorry for the confusion.

If it helps any, I tried build boost at one point and it, for some reason, did not recognize any compiler and simply bypassed building the libraries. As most of Boost is include files, they decide simply to raise a warning. As a result, `conda-build` create a package identical in structure to the one we are seeing here.

**Comment by ccordoba12** [comment]
You're right. I checked our Mac package and it doesn't come with any library!

This is really odd because I used the recipe present in `conda-recipes` and I got a right package. In case you need it, I uploaded to my binstar channel (which is ccordoba12 too).

**Comment by jakirkham** [comment]
Yeah, it's kind of odd. Thanks for doing that.

I noticed that the build number of the package from Anaconda and the one given by the recipe from `conda-recipes` are not the same. The first being `1` and the second being `4`.

However, there doesn't seem to be any record in `conda-recipes` of version `1.57.0`. So, I don't know what recipe was used to generate this particular release. Maybe there is an internal copy?

**Comment by ccordoba12** [comment]
We use a different system to `conda build` to build things internally, that's why build numbers in `conda-recipes` and Anaconda are different. But this system works almost identically to `conda build` :-)

> there doesn't seem to be any record in conda-recipes of version 1.57.0

I don't understand what you mean. The current version in `conda-recipes` is exactly 1.57.0. However, the first version added to the repo was 1.55.0, which was updated by me and others to 1.57.0.

> So, I don't know what recipe was used to generate this particular release.

This is the recipe:

https://github.com/conda/conda-recipes/tree/master/boost

**Comment by jakirkham** [comment]
> We use a different system to conda build to build things internally, that's why build numbers in conda-recipes and Anaconda are different.

That makes sense. All I was trying to say was I expected this to be true.

> I don't understand what you mean. The current version in conda-recipes is exactly 1.57.0

Yes, but I was meaning version `1.57.0` with build number `1` in the public repo, but it appears I missed this commit ( 95b17f85b5a10fab5b5a700e909f294b3bf6f9b1 ) where it does exist so I was mistaken. Is this essentially how that version was built in Anaconda?

**Comment by ccordoba12** [comment]
We use the same recipe for Anaconda, but I don't why it's generating a wrong package. We are investigating that right now ;-)

**Comment by jakirkham** [comment]
Cool, thanks. Ok, I've see this happen if Boost can't find a valid compiler, if that helps.

**Comment by jakirkham** [comment]
@ccordoba12, was there ever a solution for this?

**Comment by ccordoba12** [comment]
I created a new package in my Binstar channel (ccordoba12), which is waiting to be added to the main channels. I hope this is solved this week :-)

**Comment by jakirkham** [comment]
Cool, thanks for clarifying.

**Comment by jakirkham** [comment]
Looks like this has been moved in and it works fine. Closing this...
