### ISSUE TITLE
How to install PyQt4 on windows 10?

### ISSUE THREAD

**Issue by hugebaozi** [ContinuumIO/anaconda-issues#3432]
i have the latest conda and python 2.7 .  When I tried `conda install pyqt=4` It reports 
UnsatisfiableError: The following specifications were found to be in conflict:
  - navigator-updater -> pyqt >=5.6 -> qt 5.6.*
  - pyqt 4*
Use "conda info <package>" to see the dependencies for each package.
How to do now? I kind of need pyQt4

**Comment by ccordoba12** [comment]
Qt4 (and so PyQt4) was not updated by the company which creates Qt to support Windows 10, so it has problems and crashes there.

But if you still want to install it, you should do it using a conda environment, like this

    conda create -n old-pyqt pyqt=4*
