### ISSUE TITLE
Rope and Jedi both have major new version

### ISSUE THREAD

**Issue by Tillsten** [ContinuumIO/anaconda-issues#345]

**Comment by ccordoba12** [comment]
* Rope was only updated on Python 2, and the update is very minimal (only fixes for some tests, if I remember correctly)
* Spyder is the most important consumer of Jedi right now, and it's not ready for Jedi 0.9. However, it'll be in its next bugfix release (2.3.5), to be ready in a couple of weeks. Then, we'll update Jedi :-)

**Comment by Tillsten** [comment]
I am on spyder DEV so i didnt notice the problems with jedi 0.9, sorry. Btw pyflakes also have a 0.9 released.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know :-)
