### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by salomonh78** [ContinuumIO/anaconda-issues#3450]
Anaconda Navigator Update error:

Extra data: line 2 column 1 - line 5903 column 1 (char 82 - 524195)

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.1.9', 'qt': '4.8.6', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.3'}

**Comment by goanpeca** [comment]
Please update to the latest version of Navigator.

Open a terminal and type:

```
$ conda update anaconda-navigator
```
