### ISSUE TITLE
Spyder cannot launch in ubuntu 16.04

### ISSUE THREAD

**Issue by tungngthanh** [ContinuumIO/anaconda-issues#3454]
I just installed new ubuntu machine for practicing machine learning.
I just follow everything in this [link](http://www.computervisionbytecnalia.com/en/2016/06/deep-learning-development-setup-for-ubuntu-16-04-xenial/) about setting up things.
I install anaconda 3 as usual, but lately cannot launch spyder
when i try to run spyder in the terminal
and the result is always segmentation fault( core dumped)
So everything else works but spyder (python .py works normally)
Any advice or suggestion are welcome. Thank you.

**Comment by ccordoba12** [comment]
What version of Spyder are you using?

**Comment by tungngthanh** [comment]
thank you for asking. I find a way to overcome that error:
create a new environment and copy from all the package from the old environment to that new one.
So it works

**Comment by ccordoba12** [comment]
Great!
