### ISSUE TITLE
Confusing install/update progress bar in Launcher

### ISSUE THREAD

**Issue by DavidMertz** [ContinuumIO/anaconda-issues#348]
Maybe more a "mis-feature" than a bug, but I find the progress bar within an install within the Launcher confusing.  It shows the percentage completion of one particular action needed for the install (e.g. a certain package that is part of it), but the overall effect is the bar bouncing back and forth between almost complete and just starting.

Perhaps a second bar indicating _overall_ progress could increase monotonically, while the "package progress" bar could get reset with each stage, as currently?

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
