### ISSUE TITLE
Navigator not creating or showing environments properly (Windows 10) 

### ISSUE THREAD

**Issue by csheaff** [ContinuumIO/anaconda-issues#3492]
I cannot create an environment from a yaml file (generated by a Windows machine). I can create an environment on the command line, but Navigator will not recognize it afterwards.

**Comment by goanpeca** [comment]
@csheaff could you attach the yaml file?

**Comment by csheaff** [comment]
[myyaml.txt](https://github.com/ContinuumIO/anaconda-issues/files/1168745/myyaml.txt)
