### ISSUE TITLE
Conda 3.13.0 YamlFileSpec exception error 

### ISSUE THREAD

**Issue by jimcarson** [ContinuumIO/anaconda-issues#351]
*Version*: Python 3.4, Conda 3.13.0

*Symptom*: When running "conda" with no arguments, there is a traceback from the conda_env -help command.  

*Cause*: This file:

        ?/anaconda/lib/python3.4/site-packages/conda_env/specs/yaml_file.py 

has a python 2-style exception, which causes the traceback.

![screen shot 2015-06-07 at 6 44 43 pm](https://cloud.githubusercontent.com/assets/976855/8027115/4edbc374-0d45-11e5-8fc4-f8cf74204a4d.png)

*Solution*: change the comma to an "as": Change this:

        except EnvironmentFileNotFound, e:

to this:

        except EnvironmentFileNotFound as e:

**Comment by groutr** [comment]
This would probably be better reported on the conda issue tracker
https://github.com/conda/conda/issues

**Comment by jimcarson** [comment]
You're correct.  It looks like it was already done: https://github.com/conda/conda-env/pull/95
