### ISSUE TITLE
argparse in python3 conflicts with conda

### ISSUE THREAD

**Issue by Back2Basics** [ContinuumIO/anaconda-issues#354]
$ conda update conda
Fetching package metadata: ....
- All requested packages already installed.
- packages in environment at /Users/me/miniconda3:
#
conda                     3.13.0                   py34_0  

$ conda install argparse
Fetching package metadata: ....
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|################################################################################################################################################| 100%

Hint: the following packages conflict with each other:
  - argparse
  - conda

**Comment by ccordoba12** [comment]
`argparse` is part of the standard library since Python 3.2:

https://docs.python.org/3.4/library/argparse.html

**Comment by Back2Basics** [comment]
Thank you.
