### ISSUE TITLE
"node" is nearly 3 years old

### ISSUE THREAD

**Issue by brandon-rhodes** [ContinuumIO/anaconda-issues#355]
Building an Anaconda environment has become my go-to first step towards developing any project (thank you SO MUCH for creating it!), except for a single snag: if a project requires a Node service or a few npm packages, then it very often refuses to use my Anaconda environment because the `node` package there is still on version 0.8.7 from August 2012. Could the version of node.js compiled and shipped with Anaconda be upgraded to the most recent 0.12.4 (Stable) so that as many third-party packages and libraries are likely to be able to work with it?

With an up-to-date node.js, there are few projects that would not work out of the box with Anaconda. Thanks!

**Comment by groutr** [comment]
Node and node.js are two different packages.  Which one are you referring to?

**Comment by brandon-rhodes** [comment]
The `node` package available through `conda` provides the node.js interpreter. With an Anaconda environment active:

```
$ which node
node not found
$ node
zsh: command not found: node
$ conda install node
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /home/brandon/.v/aa:

The following NEW packages will be INSTALLED:

    node: 0.8.7-0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |##################################################| 100%
$ which node
/home/brandon/.v/aa/bin/node
$ node
> 30 + 40
70
> {} + []
'[object Object]'
```

My complaint is simply that its version is rather old:

```
$ node -v
v0.8.7
```

**Comment by groutr** [comment]
I see what's going on now.  I'll add it to my todo list. :)

**Comment by brandon-rhodes** [comment]
I am now running into errors installing common Node.js-powered tools (coffeescript, in this case) because of the August 2012 version of node.js that ships with Anaconda. If Anaconda could upgrade to the LTS v4.3.2 or else the stable v5.7.1 version of node.js, a number of compatibility problems would disappear.

**Comment by jakevdp** [comment]
I found this when debugging some of my own stuff – just a note that the conda-forge channel currently has a more up-to-date node version:
```
jakevdp$ conda search node
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
node-webkit                  0.10.1                        0  defaults        
nodejs                       4.2.6                         0  defaults        
                          *  4.4.7                         0  conda-forge     
```

**Comment by mingwandroid** [comment]
This is fixed on defaults now.

**Comment by brandon-rhodes** [comment]
Wonderful — thanks for getting this updated!

**Comment by merriam** [comment]
Um, its 3 years old again.   Current node version in 13.x, not the 10.x currently.
