### ISSUE TITLE
No regex module

### ISSUE THREAD

**Issue by extratoro** [ContinuumIO/anaconda-issues#356]
Hi,
I am using the 3.13 version with python 2.7.8 final.0
When doing a basic 
    import regex

I get the following:
    ImportError: No module named regex

I might be missing something as I am not a python module & package expert
I tried a conda update anaconda but it did not change anything.

**Comment by sclarke** [comment]
It sounds like you should be using `import re`. The documentation at python.org is also very helpful.

**Comment by ccordoba12** [comment]
Yes, the module is called `re`, not `regex`.
