### ISSUE TITLE
Installer creates shortcuts with incorrect execution directories (Anaconda 4.4.0, Windows)

### ISSUE THREAD

**Issue by ahauerwas** [ContinuumIO/anaconda-issues#3580]
Under Windows 7 x64 when installing Anaconda3 4.4.0, I'm specifying that the install should be for All Users, and the program is installed in the C:\ProgramData\Anaconda3.  So far, so good.

But the shortcuts that get loaded in the Start Menu have their "Start in" directory set to the user directory of the user who performed the installation (e.g. the text C:\Users\hauerwas); in a multi-user system, this could be a problem.  The shortcuts that have this issue are:

Anaconda Cloud
Anaconda Prompt
IPython
Jupyter Notebook
Jupyter QTConsole
Reset Spyder Settings

These should _likely_ be set to the "%userprofile%" environment variable instead of the static directory of the user that installed the software; it would then resolve at launch to the user profile of whichever user is launching the software.

It could be that the installer is _trying_ to set them to "%userprofile%" but is resolving the environment variable to the current user's directory at installation.

**Comment by mingwandroid** [comment]
Thanks for the report.

**Comment by mingwandroid** [comment]
@csoja, can we move this to the 5.1 milestone. I'm not sure if it is still an issue but I'd like to make sure it is not.

**Comment by msarahan** [comment]
PR at https://github.com/ContinuumIO/menuinst/pull/66
