### ISSUE TITLE
Anaconda3-4.4.0 Windows 10 Error

### ISSUE THREAD

**Issue by MoeJayyousi** [ContinuumIO/anaconda-issues#3601]
I have been trying to install Anaconda on Windows 10. I'm using Anaconda3-4.4.0 but it keep throwing the attached error. Any idea how to solve this or what is the issue?

<img width="250" alt="anaconda error" src="https://user-images.githubusercontent.com/30477221/28637343-11acd0b6-71f6-11e7-9750-7230b2daa3e3.png">

**Comment by mingwandroid** [comment]
You likely have some non-system DLLs in your C:\Windows\System32 folder.

**Comment by MoeJayyousi** [comment]
yeah i installed the following file and it works now:
Anaconda3-4.2.0-Windows-x86_64.zip
