### ISSUE TITLE
sqlite 3.13.0 needs an upgrade

### ISSUE THREAD

**Issue by Moisan** [ContinuumIO/anaconda-issues#3603]
The current version of sqlite offered by anaconda is [3.13.0](https://anaconda.org/anaconda/sqlite). I ran into [some issue recently](https://stackoverflow.com/questions/45335276/sqlite-select-query-including-a-values-in-the-where-clause-returns-correctly-w/45335411#45335411) due to this and the only way to resolve it is to use a more recent version of sqlite. Conda-forge has [a more up to date package](https://anaconda.org/conda-forge/sqlite) but I think it is an issue that the default channel ships 3.13.0 by default with a new python environment. @chrish42

**Comment by csoja** [comment]
sqlite 3.20.1 was added on Oct 3, 2017 and is available in https://repo.continuum.io/pkgs/main.  Thank you for letting us know, and apologies for the delayed response.
