### ISSUE TITLE
PyQt/Qt 5.6 has QWebKit on Linux, QWebEngine on MacOS X

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#3604]
The qt 5.6.0 and pyqt 5.6.2 builds from the defaults channel provide the ``PyQt5.QtWebEngineWidgets`` module on Mac and the ``PyQt5.QtWebKitWidgets`` module on Linux. Is there any way to switch PyQt5 on Linux over to using WebEngine too?

**Comment by mingwandroid** [comment]
Not while remaining compatible with CentOS5, but it's something we may be able to do in the future.

**Comment by ccordoba12** [comment]
Yeah, sorry, but there's no way for us to provide `QtWebEngineWidgets` at the moment.

However, there's a constant in `qtpy` called `WEBENGINE` that let's you write code that works for both libraries. They mostly have the same API.

**Comment by astrofrog** [comment]
Just to check, when are you planning to drop support for CentOS5?

**Comment by mingwandroid** [comment]
Hopefully for the next release. Some new packages are already being built on CentOS6 when building them on 5 is not possible.
