### ISSUE TITLE
R Studio Error

### ISSUE THREAD

**Issue by wruslandr** [ContinuumIO/anaconda-issues#3606]
## Main error
Application <b>rstudio</b> launch may have produced errors.
## Traceback
```
"TypeError: undefined is not an object (evaluating 'window.desktopHooks.notifyRCrashed')"

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.4.0-87-generic;#110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by mingwandroid** [comment]
You probably have old broken R packages in `~/R/library`. Closing due to the age of this report. Please re-open if you see issues with updated packages.
