### ISSUE TITLE
Qt fails in GNOME/Fedora 22

### ISSUE THREAD

**Issue by janpipek** [ContinuumIO/anaconda-issues#368]
I have Fedora 22, Anaconda 2.2.0, Python 2.7.10, pyqt 4.11.3  (all packages updated today). The same with python 3.4..

When KDE is running, everything works fine.
But once GNOME is started, any attempt to start application using PyQt (my own applications, spyder, ipython qtconsole) fails with the following message:

```
/home/honza/anaconda/bin/python: symbol lookup error: /lib64/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType
```

Thanks for any ideas, luckily I use Gnome only occasionally ;-)

**Comment by ccordoba12** [comment]
Please run

    conda install -c asmeurer pango

to fix this problem. It only occurs in Fedora because it's the only major distribution to be using a too recent version of `fontconfig`.

**Comment by janpipek** [comment]
Thanks a lot. It really works.

**Comment by prasadv2088** [comment]
Thanks It works with Fedora 22 for spyder too

**Comment by daudich** [comment]
Fedora 22  :+1:

**Comment by jerrymomo10** [comment]
Thanks

**Comment by Shoune** [comment]
Legend! Thank you very much.

**Comment by dballesteros7** [comment]
Worked like a charm!

**Comment by rgiovanini** [comment]
Worked Perfectly! 
I was the same trouble with matplotlib on Fedora 22. Thanks a lot!

**Comment by Tipplynne** [comment]
Works now in Python 3.5 in condas and Fedora 22. Such Joy. Many thanks.

**Comment by NiranjanMudhiraj** [comment]
i got this error 
```javascript
/lib64/libpangoft2-1.0.so.0: undefined symbol: FcWeightToOpenType
```
 i fixed this problem by your solution 
```javascript
$ conda install -c asmeurer pango
```

but i got another error:
```javascript
/home/niranjan/anaconda3/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/niranjan/mxnet/python/mxnet/../../lib/libmxnet.so)
```
can you tell me how to fix this problem.thanks in advance.


```javascript

```

**Comment by ccordoba12** [comment]
Do you have the `libgcc` package installed?

**Comment by NiranjanMudhiraj** [comment]
yes, it is installed

**Comment by ccordoba12** [comment]
What program are you trying to run? I see the error comes from `libmxnet.so` but I haven't heard of that library before.

**Comment by NiranjanMudhiraj** [comment]
deep learning package https://mxnet.readthedocs.org/en/latest/build.html#python-package-installation
can you tell me any working solution for this problem.thanks in advance

**Comment by ccordoba12** [comment]
No idea, sorry. Your problem is not related to the problem on this issue (which you confirmed was solved after following my advice).

**Comment by havocp** [comment]
I think the problem is that Fedora has a Pango that requires latest fontconfig, and my conda env has an older fontconfig than the system one:

```
(py3)[hp@localhost anaconda-ui]$ nm -D /lib64/libfontconfig.so.1 | grep FcWeightFromOpenType
00000033faa21dd0 T FcWeightFromOpenType
(py3)[hp@localhost anaconda-ui]$ nm -D ~/bin/Anaconda-2.2.0/envs/py3/lib/libfontconfig.so.1 | grep FcWeightFromOpenType
(py3)[hp@localhost anaconda-ui]$
```

Conda has fontconfig 2.11.1, this function was added in 2.11.91. Fedora 22 has 2.11.94.

conda's older fontconfig is breaking the system pango, essentially. So installing a conda version of pango would fix it as discussed here, as would putting a newer fontconfig in conda.

This will presumably break on other linux distributions if/when they upgrade Pango.

**Comment by chendaniely** [comment]
want to confirm that 

`conda install -c asmeurer pango` 

also fixes the 

`~/anaconda3/bin/python: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType`

 error in Arch Linux

**Comment by wuwuwuwuwu55555** [comment]
thanks!
