### ISSUE TITLE
DLL not found when running makepy.py in win32com.client (with solution hopefully)

### ISSUE THREAD

**Issue by tomnor** [ContinuumIO/anaconda-issues#37]
Anaconda version 2.0.4 win-64 (windows 7)

The error trace back to win32\lib\pywintypes.py", line 98. Its after the last try of finding the dll  files. I can find the files
pywintypes27.dll
pythoncom27.dll
in C:\Anaconda\Lib\site-packages\win32, but the function __import_pywin32_system_module__
does not look there. It does look in the same directory as he sits in. So I copied the dll files to 
C:\Anaconda\Lib\site-packages\win32\lib
and so it seem to work fine. However, something could possibly be done to avoid this from start, a patch, or something with the install procedure.

**Comment by mcg1969** [comment]
Ping. Can we please fix this? Anaconda shouldn't be forcing [ExcelPython, for instance](https://github.com/ericremoreynolds/excelpython/blob/d28fd94fd61df748b565071a3a653f5c607c6a11/addin/xlpython/xlpyserver.py#L7-L15) to have to search around for the libraries. See also [here](http://stackoverflow.com/questions/19280894/py2exe-no-system-module-pywintypes).

**Comment by groutr** [comment]
It shouldn't be too difficult to resolve.  I can look at it and see how it can be fixed.

**Comment by mcg1969** [comment]
Excellent, thanks. I can confirm that the solution offered above (moving the DLLs)  works.

**Comment by groutr** [comment]
Can I get some version information?  What version of pywin32 is having issues?  You can find the package version in the output of ```conda list```  I would like to know the versions of pywin32 and anaconda.

**Comment by mcg1969** [comment]
This is the 64-bit version of Python 3.4... 
pywin32: version 219 (py34_0)
anaconda: 2.2.0 (np19py34_0)

**Comment by groutr** [comment]
I'm not sure what is failing exactly.  I'm on 64-bit version of Python 3.4 (Windows XP), and I can't reproduce any of these issues.  As far as I can tell, the workaround in ExcelPython is not necessary.

**Comment by mcg1969** [comment]
I've reproduced this on two different Windows 8 installations. You can do `import pywintypes` from the command line without issues? 

When I get home I will completely remove Anaconda and do a fresh install.

**Comment by groutr** [comment]
These are the imports that we test when we create the package, and they all import successfully.
```python
import pywintypes
import win32api
import win32clipboard
import win32console
import win32cred
import win32com
import win32file
import win32gui
import win32help
import win32inet
import win32job
import win32lz
import win32net
import win32pdh
import win32pipe
import win32print
import win32process
import win32profile
import win32ras
import win32security
import win32service
import win32timezone
import win32transaction
import win32ts
import win32ui
import win32uiole
import win32wnet
import winxpgui
from win32com.shell import shell, shellcon
```

**Comment by mcg1969** [comment]
Here's what I did to reproduce the problem:

1. Remove Anaconda completely.
2. Download Anaconda 2.2.0 (64-bit Windows, Python 2.7)
3. Install with default settings.
4. Start an Anaconda Command Prompt
5. Start python
6. Enter the commands: `import pywintypes`, `import pythoncom`

Both fail.

```
Added C:\Users\mcgrant\Anaconda and C:\Users\mcgrant\Anaconda\Scripts to PATH.

C:\Users\mcgrant\Anaconda>python
Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import pywintypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mcgrant\Anaconda\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\mcgrant\Anaconda\lib\site-packages\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes27.dll)
>>> import pywincom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pywincom
>>> import wimcom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wimcom
>>> import wincom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wincom
>>> import pythoncom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mcgrant\Anaconda\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "C:\Users\mcgrant\Anaconda\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\mcgrant\Anaconda\lib\site-packages\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes27.dll)
>>>
```

**Comment by mcg1969** [comment]
Full `conda info --all` output below. Obviously the `binstar` settings are left over from my previous installation; but given that I haven't actually used them yet, surely this wouldn't be a cause of the problem?

```
Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : C:\Users\mcgrant\Anaconda  (writable)
  default environment : C:\Users\mcgrant\Anaconda
     envs directories : C:\Users\mcgrant\Anaconda\envs
        package cache : C:\Users\mcgrant\Anaconda\pkgs
         channel URLs : https://conda.binstar.org/asmeurer/win-64/
                        https://conda.binstar.org/asmeurer/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\mcgrant\.condarc
    is foreign system : False

# conda environments:
#
root                  *  C:\Users\mcgrant\Anaconda

sys.version: 2.7.9 |Anaconda 2.2.0 (64-bit)| (default...
sys.prefix: C:\Users\mcgrant\Anaconda
sys.executable: C:\Users\mcgrant\Anaconda\python.exe
conda location: C:\Users\mcgrant\Anaconda\lib\site-packages\conda
conda-build: C:\Users\mcgrant\Anaconda\Scripts\conda-build.exe
conda-convert: C:\Users\mcgrant\Anaconda\Scripts\conda-convert.exe
conda-develop: C:\Users\mcgrant\Anaconda\Scripts\conda-develop.exe
conda-env: C:\Users\mcgrant\Anaconda\Scripts\conda-env.exe
conda-index: C:\Users\mcgrant\Anaconda\Scripts\conda-index.exe
conda-inspect: C:\Users\mcgrant\Anaconda\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\mcgrant\Anaconda\Scripts\conda-metapackage.exe
conda-pipbuild: C:\Users\mcgrant\Anaconda\Scripts\conda-pipbuild.exe
conda-server: C:\Users\mcgrant\Anaconda\Scripts\conda-server.exe
conda-skeleton: C:\Users\mcgrant\Anaconda\Scripts\conda-skeleton.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\mcgrant\Anaconda;C:\Users\mcgrant\Anaconda\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS
\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\MATLAB\R2014a\bin;C:\Program Files\MATLAB\R2014a\bin;C:\Program Files\MATLA
B\R2009a\bin;C:\Program Files (x86)\MATLAB\R2009a\bin;C:\Program Files (x86)\MATLAB\R2009a\bin\win32;C:\Program Files\MATLAB\R2009a\
bin\win64;C:\Program Files (x86)\CMake 2.8\bin;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsof
t SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Too
ls\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\TDM-GCC-64\bin;C:\Program Files\Mosek\7\tools
\platform\win64x86\bin;C:\TDM-GCC-32\bin;C:\Program Files (x86)\Git\cmd;C:\Users\mcgrant\Anaconda;C:\Users\mcgrant\Anaconda\Scripts;

PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    C:\Users\mcgrant\.continuum
    C:\Users\mcgrant\Anaconda\licenses
    C:\Users\mcgrant\AppData\Roaming\Continuum
License files (license*.txt):
Package/feature end dates:

```

**Comment by groutr** [comment]
In your site-packages directory, is there a pywin32.pth file?  If so, what are the contents of it?

**Comment by mcg1969** [comment]
```
# .pth file for the PyWin32 extensions
win32
win32\lib
Pythonwin

**Comment by mcg1969** [comment]
I just repeated the above process with Python 3.4 (removing the other version of Anaconda completely, and rebooting, before proceeding.) I get the same error message, and `pywin32.pth` is the same.

**Comment by groutr** [comment]
I still can't reproduce this import issue.  I tried with a clean install of Anaconda 2.2.0 (python 3).  
```
Python 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1
600 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pywintypes

In [2]: pywintypes??
Type:        module
String form: <module 'pywintypes' from 'C:\\Users\\builder\\Anaconda3\\lib\\site-packages\\win32\\pywintypes34.dll'>
File:        c:\users\builder\anaconda3\lib\site-packages\win32\pywintypes34.dll

Docstring:   Module containing common objects and functions used by various Pywin32 modules

In [3]:
```
I'm starting to suspect it might be a configuration issue.  I notice that you have the anaconda directories at the beginning and end of your path.  Maybe try removing the anaconda directories at the beginning of your path?

**Comment by groutr** [comment]
One more thing that might yield some information.
Can you send me the contents of sys.path
```
import sys
print sys.path
```

**Comment by mcg1969** [comment]
OK, we're getting somewhere. Ryan, did you ever try importing on the `python` command line instead of the `ipython` command line? I had never done the latter, but I'm able to import `pywintypes` from iPython just like you did. It is bare Python that is the issue here.

Here's `sys.path` for Python (extra carriage returns are mine):
```
>>> sys.path
['', 
'C:\\Users\\mcgrant\\Anaconda3\\python34.zip', 
'C:\\Users\\mcgrant\\Anaconda3\\DLLs',
'C:\\Users\\mcgrant\\Anaconda3\\lib',
'C:\\Users\\mcgrant\\Anaconda3', 
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages', 
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\Sphinx-1.2.3-py3.4.egg', 
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\cryptography-0.8-py3.4-win-amd64.egg',
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\nose-1.3.4-py3.4.egg',
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\win32', 
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\win32\\lib',
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\Pythonwin',
'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\setuptools-14.3-py3.4.egg']
```

And here it is for iPython:
```
In [2]: sys.path
Out[2]:
['',
 'C:\\Users\\mcgrant\\Anaconda3\\Scripts',
 'C:\\Users\\mcgrant\\Anaconda3\\python34.zip',
 'C:\\Users\\mcgrant\\Anaconda3\\DLLs',
 'C:\\Users\\mcgrant\\Anaconda3\\lib',
 'C:\\Users\\mcgrant\\Anaconda3',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\Sphinx-1.2.3-py3.4.egg',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\cryptography-0.8-py3.4-win-amd64.egg',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\nose-1.3.4-py3.4.egg',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\setuptools-14.3-py3.4.egg',
 'C:\\Users\\mcgrant\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\mcgrant\\.ipython']
```

**Comment by mcg1969** [comment]
I'm going to guess that the problem is `lib\site-packages\win32\lib\pywintypes.py`, specifically the function  `__import_pywin32_system_module__`. It is clear that the authors have really struggled with this problem. Check out the comments:

    # This has been through a number of iterations.  The problem: how to 
    # locate pywintypesXX.dll when it may be in a number of places, and how
    # to avoid ever loading it twice.  This problem is compounded by the
    # fact that the "right" way to do this requires win32api, but this
    # itself requires pywintypesXX.
    # And the killer problem is that someone may have done 'import win32api'
    # before this code is called.  In that case Windows will have already
    # loaded pywintypesXX as part of loading win32api - but by the time
    # we get here, we may locate a different one.  This appears to work, but
    # then starts raising bizarre TypeErrors complaining that something
    # is not a pywintypes type when it clearly is!

    # So in what we hope is the last major iteration of this, we now
    # rely on a _win32sysloader module, implemented in C but not relying
    # on pywintypesXX.dll.  It then can check if the DLL we are looking for
    # lib is already loaded.

**Comment by groutr** [comment]
I saw the many comments in the pywintypes.py file.
I was able to reproduce this issue in a new environment.  It imports when I use IPython and fails when I use python.  This baffles me.

**Comment by educhana** [comment]
Hi,

Same issue here win python 3 & win7 64bits

In my case, the order of the imports matter:

```python 
import win32com.client as com
import pywintypes
```
works, but:

```python
import pywintypes
import win32com.client as com
```
fails.

**Comment by groutr** [comment]
@educhana I think what is happening there is win32com.client is loading the DLL that pywintypes uses.  If you look at how pywintypes is loading, it searches to see if the DLL it needs is already loaded.  If so, it will use that, otherwise it has to load the DLL itself.  That is where the failure seems to be happening.
I'm hoping that the correct solution is simply moving (not copying) the DLLs from win32 to win32\lib.  This way we can avoid having 3 copies of the same file in the package.

**Comment by Ogaday** [comment]
A temporary solution is to call your python scripts with the ipython interpreter rather than the python one.

eg.

    #file foo.py
    import pythoncom
then 
```ipython foo.py```
rather than
```python foo.py```

**Comment by 16071993** [comment]
Excellent it worked.Great,Thumbs Up
