### ISSUE TITLE
pillow ImageCms module import error in python3 env

### ISSUE THREAD

**Issue by bgreen-litl** [ContinuumIO/anaconda-issues#371]
Note that this import works in a python2 anaconda env (as well as in a python3 virtualenv).

    >>> from PIL import ImageCms
    Traceback (most recent call last):
      File "/Users/bob/anaconda/envs/test3/lib/python3.4/site-packages/PIL/ImageCms.py", line 89, in <module>
        from PIL import _imagingcms
    ImportError: cannot import name '_imagingcms'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/bob/anaconda/envs/test3/lib/python3.4/site-packages/PIL/ImageCms.py", line 93 <module>
    from _util import deferred_error
    ImportError: No module named '_util'

My installed packages are:

    $ conda list
    # packages in environment at /Users/bob/anaconda/envs/test3:
    #
    You are using pip version 7.0.3, however version 7.1.0 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    freetype                  2.5.2                         2
    jpeg                      8d                            1
    libpng                    1.6.17                        0
    libtiff                   4.0.2                         1
    openssl                   1.0.1k                        1
    pillow                    2.8.2                    py34_0
    pip                       7.0.3                    py34_0
    python                    3.4.3                         0
    readline                  6.2                           2
    setuptools                17.1.1                   py34_0
    sqlite                    3.8.4.1                       1
    tk                        8.5.18                        0
    xz                        5.0.5                         0
    zlib                      1.2.8                         0

**Comment by bgreen-litl** [comment]
bump

**Comment by bgreen-litl** [comment]
Created a PR which seems to fix this https://github.com/conda/conda-recipes/pull/342

**Comment by MichaelMauderer** [comment]
I see this issue with pillow 4.2.1 under Anaconda for Python 3.6.1,  Windows 10 64 Bit.
Does this indicate a missing external dependency? If so that would be a useful thing to put into that error message.

**Comment by bgreen-litl** [comment]
This take me a ways back, but from what I recall this issue was a missing dep at build time - not runtime.  Looks like there is a .bat file for doing the windows build and it doesn't mention littlecms2

https://github.com/conda/conda-recipes/blob/a796713805ac8eceed191c0cb475b51f4d00718c/python/pillow/bld.bat

I would file a new issue if I were you, pointing out that the littlecm2 dep is in build.sh but not bld.bat.

**Comment by mchapman87501** [comment]
I see this issue with pillow 5.0.0 under Anaconda3 5.0.1 on macOS 10.13.3.

**Comment by WarrenWeckesser** [comment]
I still see this error on Mac OSX (10.9.5, yeah, its getting a little old...).  The directory `~/mc37` is a Miniconda installation, where I installed pillow with `conda install pillow`:

~$ ~/mc37/bin/ipython --pylab
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: TkAgg

```
In [1]: from PIL import ImageCms                                                                                           
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/mc37/lib/python3.7/site-packages/PIL/ImageCms.py in <module>
     22 try:
---> 23     from PIL import _imagingcms
     24 except ImportError as ex:

ImportError: cannot import name '_imagingcms' from 'PIL' (/Users/warren/mc37/lib/python3.7/site-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5649c7a5961e> in <module>
----> 1 from PIL import ImageCms

~/mc37/lib/python3.7/site-packages/PIL/ImageCms.py in <module>
     25     # Allow error import for doc purposes, but error out when accessing
     26     # anything in core.
---> 27     from _util import deferred_error
     28     _imagingcms = deferred_error(ex)
     29 from PIL._util import isStringType

ModuleNotFoundError: No module named '_util'

In [2]: import PIL                                                                                                         

In [3]: PIL.__version__                                                                                                    
Out[3]: '5.4.1'
```

**Comment by WarrenWeckesser** [comment]
It appears that I can fix this by patching `~/mc37/lib/python3.7/site-packages/PIL/ImageCms.py` as follows:

```
~/mc37/lib/python3.7/site-packages/PIL$ diff ImageCms.py.save ImageCms.py
27c27
<     from _util import deferred_error
---
>     from ._util import deferred_error
```

Upstream patch submitted: https://github.com/python-pillow/Pillow/pull/3793

**Comment by WarrenWeckesser** [comment]
The patch fixes a small mistake in the pillow code that defers the import error until an attempt is made to use `ImageCms`.  It does not fix the underlying problem with the Anaconda `pillow` package: the module `_imagingcms` is not installed.    Any ideas why this is?

**Comment by msarahan** [comment]
Is that an optional thing that we just aren't enabling?  I have no idea.  Our recipe is at https://github.com/anacondarecipes/pillow-feedstock

**Comment by WarrenWeckesser** [comment]
I was looking into this a bit more.  The C library [LittleCMS](http://www.littlecms.com/) is required, but it is not in the build dependencies of the pillow package, and I don't think there is a conda package for LittleCMS itself.  I asked about it over at the `pillow` feed-stock repo: https://github.com/conda-forge/pillow-feedstock/issues/58
