### ISSUE TITLE
Navigator issue -Solution from Issue #3721 didn't help

### ISSUE THREAD

**Issue by EncryptTheEncrypted** [ContinuumIO/anaconda-issues#3724]
Hello,
I tried the solution that was send to me in the now closed Issue #3721 , but I still get the same error message. Any further ideas how I could fix this? I already uninstalled and reinstalled Anaconda three times today.

Best regards,
EncryptTheEncrypted

**Comment by goanpeca** [comment]
@EncryptTheEncrypted please run

`$ anaconda-navigator --reset`
