### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by zhenhe168** [ContinuumIO/anaconda-issues#3739]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - pil ==1.1.7
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Linux;4.4.0-83-generic;#106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017;x86_64;x86_64', 'version': '1.2.1', 'language': 'en_US', 'conda': '4.1.6', 'platform': 'linux-64', 'python': '3.5.2', 'qt': '5.7.0', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
