### ISSUE TITLE
install cx_Oracle

### ISSUE THREAD

**Issue by OAnastasios** [ContinuumIO/anaconda-issues#3752]
I am new to anaconda, (currently using mostly Spyder) and would like to know if we can have the cx_Oracle package included for python 3.6. Thank you

**Comment by mingwandroid** [comment]
Please run:

`conda install cx_oracle`

**Comment by OAnastasios** [comment]
This does not work. I had to install cx_Oracle-5.3-12c.win-amd64-py3.6-2.exe (md5) under Anaconda/../site-packages. I now see a cx_Oracle-5.3-py3.6.egg-info directory with 4 files in it one of them being named top_level.txt with the string cx_Oracle in it,. I also am seeing a cx_Oracle.cp36-win_amd64.pyd file on the same level as the aforementioned directory. Never had such issues with java, even as a newbie back then..

**Comment by mingwandroid** [comment]
> This does not work

What exactly happens? Can you copy the text from the Anaconda Prompt cmd.exe window and paste it here please?

**Comment by mingwandroid** [comment]
Here is what I get:

```
conda install cx_oracle
```

gives:

```
conda install cx_oracle
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Users\builder\mc-x64-3.6:

The following NEW packages will be INSTALLED:

    cx_oracle: 6.0b2-py36_0

Proceed ([y]/n)? y

cx_oracle-6.0b 100% |###############################| Time: 0:00:00   2.67 MB/s
```

then to use it:

```
python -c "import cx_Oracle"
```

.. gives:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1047: Oracle Client library cannot be loaded: The specified module could not be found. See https://oracle.github.io/odpi/doc/installation.html for help
```

And you need to follow those instructions as we cannot redistribute the `Oracle Client library`.

**Comment by OAnastasios** [comment]
So, I ran cx_Oracle-5.3-12c.win-amd64-py3.6-2.exe (md5) and things went to place as discussed earlier (all under site-packages. Then went to Anaconda prompt and ran:
>>> conda install cx_oracle
I got:
SyntaxError: invalid syntax
>>> conda install cx_oracle
File "<stdin>", line 1
conda install cx_oracle
                   >

**Comment by mingwandroid** [comment]
This is not the Anaconda Prompt. This is the Python interpreter.

You can find the former in your Start Menu.

**Comment by mingwandroid** [comment]
Conda update conda just ensures you have the latest bug fixes.

**Comment by OAnastasios** [comment]
Thank you!
