### ISSUE TITLE
Provide `backports.ssl_match_hostname` for all platforms in auto channel

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#379]
Currently, `backports.ssl_match_hostname` is only provided for Linux 64 and 32. However, it is a pure Python package and is often required by other packages. It would be nice if the auto channel on binstar/anaconda included this package for all platforms.

**Comment by asmeurer** [comment]
I think the package `ssl_match_hostname` in the official channels is what you want.

**Comment by jakirkham** [comment]
So, I am not understanding why there is a distinction between the two. Could you please help me understand?

**Comment by jakirkham** [comment]
Also, I am concern that when a Python package requires `backports.ssl_match_hostname` in its `setup.py` that running steps like `conda skeleton pypi <PACKAGE>`, `conda pipbuild <PACKAGE>`, or `python setup.py bdist_conda` may not provide the desired result.

In fact, I ran into this exact problem when upgrading the package for `websocket-client`.

Personally, I would think, instead of adding a bunch of code for various corner cases in `conda`, adding a package to <anaconda.org> would be easier.
