### ISSUE TITLE
Navigator May Not have Created Environments right on Mac

### ISSUE THREAD

**Issue by TheMitchWorksPro** [ContinuumIO/anaconda-issues#3805]
I have 3 kernels: default which I do not use, PY36 for PYthon 3.6 and PY27 for Python 2.7.  Since first installing and setting up Anaconda, if I loaded Jupyter Notebook from the default environment, I only get menus for Python 3 notebook (I think in that environment).  If I am in PY36, I only get Jupyter menus for PYthon 3 notebook (I think in PY36 environment).  If use navigator to launch Jupyter NOtebook from PY27 evironment, then I get two menu items, one for Python 36 and one for python 27.  

I did a conda-forge install of wordcloud into PY36 and it wasn't working even though install into PY36 environment went fine and conda list shows the new packages successfully installed.  

The console window for Jupyter Notebook when I check it now displays these messages and i honestly can't remember if I ever checked if it was doing this before or not.  Note the "0 active kernels" message.  Could this have something to do with the menus issue described above?  Could I be facing issues where I am not really able to load my different environments?

What is going on with this?
```
Last login: Tue Aug  1 17:25:35 on ttys000
Mitchells-MacBook-Pro:~ mitchmac$ /Users/mitchmac/anaconda/envs/PY36/bin/jupyter_mac.command ; exit;
[I 17:28:01.521 NotebookApp] Serving notebooks from local directory: /Users/mitchmac/Documents/jupyter_root
[I 17:28:01.521 NotebookApp] 0 active kernels 
[I 17:28:01.521 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=2c4e3adc5bda75e45cbda6ea76fc25583a754f48b2c50a2b
[I 17:28:01.521 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:28:01.522 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=2c4e3adc5bda75e45cbda6ea76fc25583a754f48b2c50a2b
[I 17:28:01.970 NotebookApp] Accepting one-time-token-authenticated connection from ::1

'''

**Comment by goanpeca** [comment]
@TheMitchWorksPro kernels from different environments are not visible on other environments, AFAIK, unless something is manually updated. So you (probably) need to install the notebook plus dependencies on each environment (kernel) you need.

**Comment by TheMitchWorksPro** [comment]
I'm confused.  Under Anaconda 4.1, if I created environments, the environments name and Notebook version would appear in a drop down menu on iPython.  That too was a little buggy, but overall, I ended up with menu items that could create notebooks for all versions of python /environment combinations on my machine.  ON my old windows machine, I had drop down items to do notebooks in Python 2.7, 3.5, and R, and there were separate menu items for my PY27 and PY27_test environment which had different packages installed on them.  Recently I got a mac and installed the current release of Anaconda (I think 4.3).  But menu only accesses the different notebooks as described.  If I want what I had before, what should i do diferently?  Additionally, why is it indicating kernels 0 in the startup messages?

**Comment by csoja** [comment]
It sounds like you were using the Jupyter notebook extensions.  These are no longer included in the Anaconda installer - but you can install them using conda yourself.  Here is the documentation: https://docs.continuum.io/anaconda/user-guide/tasks/use-jupyter-notebook-extensions  I believe nb_conda_kernels is the one you're looking for, so _conda install nb_conda_kernels_ should add that functionality back to your Jupyter Notebook.

**Comment by TheMitchWorksPro** [comment]
Just got back to this page and read your comments.  Sorry about that.  It has been a busy week.  Why was that left out of the newest release of anaconda?  Are there risks or issues I should be aware of before installing it?  Thanks for any input before I add it back to my environment.  I am assuming you had it int 4.1 and left it out of 4.3 for a reason.
