### ISSUE TITLE
conflict between netCDF4 and pytables

### ISSUE THREAD

**Issue by marbsrednas** [ContinuumIO/anaconda-issues#381]
After updating anaconda the following happens:

netCDF4 requires libhdf5_hl.so.9
pytables requires libhdf5.so.10

An update or reinstall of one of the modules removes the other module's hdf library. 

Thus, I can only get one of the two modules to work.

Can someone help or solve this issue?

Thanks very much,

Bram

**Comment by groutr** [comment]
Thanks for the notice.  We are looking into it.

**Comment by groutr** [comment]
New builds uploaded to the repos.

**Comment by marbsrednas** [comment]
Thanks for your help, Ryan!

Bram
