### ISSUE TITLE
Link numpy to libmkl_intel_ilp64 to allow blas calls with large matrices

### ISSUE THREAD

**Issue by andrewpaulreeves** [ContinuumIO/anaconda-issues#3823]
We're working with some very large matrices (~50000x50000 elements) upon which we need to perform BLAS operations.  Currently, anaconda numpy is linked to the library `libmkl_intel_lp64.so`, which uses int32 to index arrays, meaning that very larges arrays cannot be operated upon. The library `libmkl_intel_ilp64.so` is also distributed with anaconda MKL, which uses int64 for array indexing, and can hence work with large array sizes. This is described in more detail here - https://software.intel.com/en-us/mkl-macos-developer-guide-using-the-ilp64-interface-vs-lp64-interface. 

Example:
```
In [1]: import numpy
In [2]: A = numpy.random.random((50000, 50000))
In [3]: u, s, vt = numpy.linalg.svd(A)
init_dgesdd failed init
```

Is it possible to link numpy with the `ilp64` library so that it works with very large matrices out of the box?

**Comment by jjhelmus** [comment]
Unfortunately just linking against `libmkl_intel_ilp64.so` will not allow BLAS calls for large matrices.  NumPy's BLAS interface uses 32-bit integers and does not support lapack64, see numpy/numpy#5906.  As a test I tried building NumPy with the ilp64.so library, the resulting package segmentation faults when running the NumPy unit tests.
