### ISSUE TITLE
 r package update failure

### ISSUE THREAD

**Issue by xweipbcsf** [ContinuumIO/anaconda-issues#3842]
UnsatisfiableError: The following specifications were found to be in conflict:
  - r-backports
  - r-car ==2.0_26 -> r 3.2.1* -> r-base 3.2.1
Use "conda info <package>" to see the dependencies for each package.

**Comment by mingwandroid** [comment]
Please give the exact reproduction steps here.

**Comment by mingwandroid** [comment]
Closing due to lack of feedback.
