### ISSUE TITLE
bzip2 package is missing shared libraries

### ISSUE THREAD

**Issue by ink1** [ContinuumIO/anaconda-issues#3865]
I installed a package (samtools) which has bzip2 as a dependency but it failed to run because bzip2 only provided a static lib. Could shared libraries be included too?
bzip2-1.0.6-3

**Comment by crashfrog** [comment]
Also have this issue. I'm using Galaxy, and it doesn't seem possible to convince Galaxy to resolve Conda dependencies with a channel order that puts conda-forge ahead of defaults (despite what is configured in Galaxy.ini), so this has to be fixed in the package.

**Comment by msarahan** [comment]
The current bzip2 package is at https://repo.continuum.io/pkgs/main/linux-64/bzip2-1.0.6-h6d464ef_2.tar.bz2 - it does include shared libraries.

Note that this is the "main" channel, not the older "free" channel.  This new channel is automatically added for conda 4.3.27 and up.  You may need to update conda.  If you are otherwise customizing your default channels, you need to add https://repo.continuum.io/pkgs/main/ to your default channels.

**Comment by crashfrog** [comment]
Sorry, what channel is "main"? I'm not extremely familiar with the conda ecosystem, I'm trying to track down faulty package dependency management in our Galaxy install. Do you mean ```defaults```?

```
conda search -c main bzip2
Loading channels: done
Name                       Version                   Build  Channel        
bzip2                      1.0.6                         0  defaults       
bzip2                      1.0.6                         3  defaults       
bzip2                      1.0.6                h0376d23_1  defaults       
bzip2                      1.0.6                h6d464ef_2  defaults  
```

**Comment by msarahan** [comment]
defaults is made up of several URLs.  Among these:

https://repo.continuum.io/pkgs/main/
https://repo.continuum.io/pkgs/free/

conda is combining these into the "meta-channel" you know as defaults.  There is an order within this meta-channel.

**Comment by crashfrog** [comment]
Oh, wait, I think I have this backwards. The bzip2 package in defaults (in main, I guess) has the libbz2.so.1.0 object, but if I read the build script for the bzip2 package in conda-forge correctly:

https://github.com/conda-forge/bzip2-feedstock/blob/master/recipe/build.sh

It *doesn't* create libbz2.so.1.0 (just libbz2.so.1 and libbz2.so.1.0.6). So I guess I need to open an issue over there.
