### ISSUE TITLE
Unable to install Anaconda3-2.3.0 on RHEL 6.x

### ISSUE THREAD

**Issue by havenerk** [ContinuumIO/anaconda-issues#387]
Is there any reason the installer won't work on this somewhat older linux distro?  Anaconda-2.3.0 installs just fine.

When I try "bash Anaconda3-2.3.0-x86_64.sh" the install starts, but when it gets to installing python3.4.3, I get :

installing: python-3.4.3-1 ...
tar (child): /home/havenerk/anaconda3/pkgs/python-3.4.3-1.tar.bz2: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

So I tried installing a python3.4 environment under the python 2.7 Anaconda install.  Again, I got to the point of installing python3.4 and got this:

IOError: [Errno 13] Permission denied: u'/home/havenerk/anaconda/pkgs/python-3.4.3-1.tar.bz2'

Obviously, this is not a permissions problem because it is being installed in my home directory where my 2.7 Anaconda is.  Is it some sort of unicode error?  I did install anaconda3 successfully on a newer Fedora 22 system and a Ubuntu 15.04 system.  So I think it has something to do with the age of the RH system.  Maybe an incompatible tar utility?  Any suggestions?

**Comment by csoja** [comment]
Looks like there were no suggestions for this problem - and at this point Anaconda v2.3.0 is very outdated.  Closing this issue.
