### ISSUE TITLE
anaconda update attempts to roll back individually updated packages

### ISSUE THREAD

**Issue by lyonj** [ContinuumIO/anaconda-issues#39]
> conda update numba

Updating conda environment at C:\Anaconda

The following packages will be downloaded:

| package | build |
| --- | --- |
| conda-2.2.1 | py27_0         129 KB |
| llvmmath-0.1.2 | np17py27_0          83 KB |
| llvmpy-0.12.1 | py27_0         6.1 MB |
| numba-0.11.1 | np17py27_0         1.0 MB |

The following packages will be UN-linked:

| package | build |
| --- | --- |
| conda-2.1.0 | py27_0 |
| llvmmath-0.1.1 | np17py27_2 |
| llvmpy-0.12.0 | py27_0 |
| numba-0.11.0 | np17py27_0 |

The following packages will be linked:

| package | build |
| --- | --- |
| conda-2.2.1 | py27_0   hard-link |
| llvmmath-0.1.2 | np17py27_0   hard-link |
| llvmpy-0.12.1 | py27_0   hard-link |
| numba-0.11.1 | np17py27_0   hard-link |

Proceed ([y]/n)? y

Fetching packages ...
conda-2.2.1-py27_0.tar.bz2 100% |###################| Time: 0:00:00   0.00  B/s
llvmmath-0.1.2-np17py27_0.tar.bz2 100% |############| Time: 0:00:00   8.49 MB/s
llvmpy-0.12.1-py27_0.tar.bz2 100% |#################| Time: 0:00:04   1.37 MB/s
numba-0.11.1-np17py27_0.tar.bz2 100% |##############| Time: 0:00:02 417.39 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%

> conda update anaconda

Updating conda environment at C:\Anaconda

The following packages will be UN-linked:

| package | build |
| --- | --- |
| llvmmath-0.1.2 | np17py27_0 |
| llvmpy-0.12.1 | py27_0 |
| numba-0.11.1 | np17py27_0 |

The following packages will be linked:

| package | build |
| --- | --- |
| llvmmath-0.1.1 | np17py27_2   hard-link |
| llvmpy-0.12.0 | py27_0   hard-link |
| numba-0.11.0 | np17py27_0   hard-link |

Proceed ([y]/n)? n

**Comment by FvD** [comment]
Perhaps you could change the line that says 

    "The following packages will be DOWNGRADED:" 

to the following:

    The following packages will be DOWNGRADED in anaconda's stable set of packages.
    This will NOT affect packages in your conda environments (these will stay at their current version)

This will make it clear that whatever set of package-versions you might have worked hard on to assemble in `my-env` will stay just as it is.

**Comment by drorata** [comment]
Is it confirmed that the formulation suggested by @FvD is correct? This is super confusing.

**Comment by goanpeca** [comment]
@kalefranz please close if this no longer applies? or move to conda repo?
