### ISSUE TITLE
navigation error

### ISSUE THREAD

**Issue by shuja1497** [ContinuumIO/anaconda-issues#3900]
Main Error:
string indices must be integers, not str

**Comment by goanpeca** [comment]
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```
