### ISSUE TITLE
launcher error first time run

### ISSUE THREAD

**Issue by nickeubank** [ContinuumIO/anaconda-issues#393]
This is super uninformative, sorry, but I installed anaconda on windows server 2012r2 (intel) (python 3.4 64 bit), did not add to path, did not register (I have another python installed and want to make sure the other installation remains default -- too many things I struggled to install I want to finish installing in anaconda before I switch over). 

When I launched the "launcher" I immediately got the error: Alert! Sorry, the application encountered a fatal error. Please report the following to us at [this site]. 

That was all. It then says "click ok to restart", and if i click ok it does the same thing again.

**Comment by nickeubank** [comment]
or is this just a consequence of no path var? I can't use Launcher from gui launcher?

**Comment by nickeubank** [comment]
Yup, looks like that was it. I guess this isn't a priority, but seems like a more informative error might be helpful, as would the launcher modifying the path variable similarly to the command prompt.

**Comment by ccordoba12** [comment]
The launcher is being reworked right now. Sorry for the inconvenience :-)

**Comment by meyersbs** [comment]
If I enter any of the following commands, anaconda runs just fine.
``` bash
    launcher
    /opt/anaconda3/bin/launcher
    bash /opt/anaconda3/bin/launcher
```

However, if I copy any of those commands into a new menu item, they all fail with the error mentioned above. It's been two months, why isn't this fixed?

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
