### ISSUE TITLE
Update SWIG to 3.0.3

### ISSUE THREAD

**Issue by Juanlu001** [ContinuumIO/anaconda-issues#395]
Right now the latest SWIG version is 3.0.2, but for building FEniCS 1.6.0 (FFC specifically) I would need SWIG 3.0.3, which according to the release notes adds some C++11 features:

http://sourceforge.net/p/swig/news/2014/12/swig-303-released/

@oliveirarodolfo already has a conda package for SWIG 3.0.5 on anaconda.org:

https://anaconda.org/roliveira/swig

**Comment by oliveirarodolfo** [comment]
I even got that package built from [conda-recipes repository](https://github.com/conda/conda-recipes/blob/master/swig/meta.yaml). Maybe you can add it as an additional package to be built on the [fenics-recipes repository](https://github.com/Juanlu001/fenics-recipes)...

**Comment by Juanlu001** [comment]
Done :) Still looking forward to the most recent version to appear in the official channels.

**Comment by oliveirarodolfo** [comment]
:+1:

**Comment by Juanlu001** [comment]
I see that the conda recipe got updated to swig 3.0.7 in https://github.com/conda/conda-recipes/pull/383, any chance the corresponding packages will get published in the official channel too? I have problems to build it on Anaconda Cloud due to a missing library (https://anaconda.org/Juanlu001/fenics_all/builds/2/0#L5413) even though I explicitly added it to `meta.yml` (https://github.com/Juanlu001/fenics-recipes/commit/b365213ff3ea98218093b9a19aea090c890595c0).

**Comment by msarahan** [comment]
Two things:

1. Yes, an official SWIG 3.0.8 package should be available very soon.
2. For the error about finding the header, you may need to add
$PREFIX/include to some CPPFLAGS setting:
http://stackoverflow.com/questions/7561509/how-to-add-include-and-lib-paths-to-configure-make-cycle

Also, for troubleshooting 2, make sure your recipe works locally before
troubleshooting anaconda.org - it's much easier.  Please let us know if you
think we have a bug on anaconda.org.

**Comment by Juanlu001** [comment]
Thanks for the suggestion @msarahan, it worked - which means the original recipe in `conda-recipes` is incomplete :) I will submit a pull request soon.

**Comment by Juanlu001** [comment]
I just saw that SWIG got updated to 3.0.8 one month ago https://anaconda.org/anaconda/swig/files. Closing this issue.
