### ISSUE TITLE
Pyramid: pcreate unable to find templates  - scaffolds unavailable

### ISSUE THREAD

**Issue by brendancol** [ContinuumIO/anaconda-issues#396]
I'm having trouble while using `pcreate` to start a Pyramid project:

    $> pcreate -s alchemy my_api_project
         ...
         Unavailable scaffolds: ['alchemy']

When i install pyramid via pyvenv + pip there is no problem using `pcreate`:

The issue maybe related to this function in `pyramid/scripts/pcreate.py : line 131`:

    def all_scaffolds(self):
        scaffolds = []
        eps = list(pkg_resources.iter_entry_points('pyramid.scaffold'))
        for entry in eps:
            try:
                scaffold_class = entry.load()
                scaffold = scaffold_class(entry.name)
                scaffolds.append(scaffold)
            except Exception as e: # pragma: no cover
                self.out('Warning: could not load entry point %s (%s: %s)' % (
                    entry.name, e.__class__.__name__, e))
        return scaffolds

**Comment by asmeurer** [comment]
I believe pyramid needs to maintain the egg directory. @ilanschnell @groutr

**Comment by ilanschnell** [comment]
Yes, that is the problem.  I'm building fixed packages right now.

**Comment by ilanschnell** [comment]
Fixed packages are available.

**Comment by brendancol** [comment]
great thanks...verified on my side and looks good

**Comment by ccordoba12** [comment]
Closing then :-)
