### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by SajidSalim** [ContinuumIO/anaconda-issues#4012]
![conda-error](https://user-images.githubusercontent.com/15053308/29065897-a8909524-7c3e-11e7-98e3-777b83757173.png)
As you can see, the app icon just goes out of the row when I refresh sometimes.
Hitting 'Refresh' again does not help. Have to close the application and start it again.

**Comment by goanpeca** [comment]
@SajidSalim this issue is already being tracked on our internal issue tracker.
