### ISSUE TITLE
build GDAL with HDF4 support

### ISSUE THREAD

**Issue by andreas-h** [ContinuumIO/anaconda-issues#403]
It would be greate if you could build gdal with support for HDF4 files: `--with-hdf4=ARG`.  For this, you would need to add HDF4 to the distribution.  I have a working HDF4 package here: https://binstar.org/andreas-h/hdf4.

**Comment by nehaljwani** [comment]
`libgdal >= 2.0.0` has been build with `--with-hdf4`

```bash
(403) [nwani@wildwest ~]$ conda list libgdal
# packages in environment at /home/nwani/m3/envs/403:
#
libgdal                   2.1.0                         0  
(403) [nwani@wildwest ~]$ gdal-config --formats | tr ' ' '\n' | grep hdf
hdf5
hdf4
```
