### ISSUE TITLE
Boost build against Anaconda error in Windows

### ISSUE THREAD

**Issue by dashesy** [ContinuumIO/anaconda-issues#4068]
I am trying to build boost with Anaconda python
    
    bootstrap.bat --with-python=c:\Anaconda3

The python headers are picked but not the library and I get this error:

```
LINK : fatal error LNK1104: cannot open file 'python36.lib'

    "cl"  "/Fdbin.ntx86/" "/Fobin.ntx86/" /Febin.ntx86\b2.exe "-DNDEBUG" "-DOPT_HEADER_CACHE_EXT" "-DOPT_GRAPH_DEBUG_EXT" "-DOPT_SEMAPHORE" "-DOPT_AT_FILES" "-DOPT_DEBUG_PROFILE" "-DOPT_FIX_TARGET_VARIABLES_EXT" "-DOPT_IMPROVED_PATIENCE_EXT" "-DNT" "-DYYSTACKSIZE=5000" "-DHAVE_PYTHON" "/nologo" "/GL" "/MT" "/O2" "/Ob2" "/Gy" "/GF" "/GA" "/wd4996" "-Ic:\Anaconda3\include" "command.c" "compile.c" "constants.c" "debug.c" "execcmd.c" "frames.c" "function.c" "glob.c" "hash.c" "hcache.c" "headers.c" "hdrmacro.c" "jam.c" "jambase.c" "jamgram.c" "lists.c" "make.c" "make1.c" "mem.c" "object.c" "option.c" "output.c" "parse.c" "pathsys.c" "regexp.c" "rules.c" "scan.c" "search.c" "subst.c" "w32_getreg.c" "timestamp.c" "variable.c" "modules.c" "strings.c" "filesys.c" "builtins.c" "class.c" "cwd.c" "native.c" "md5.c" "modules\set.c" "modules\path.c" "modules\regex.c" "modules\property-set.c" "modules\sequence.c" "modules\order.c" "execnt.c" "filent.c" "pathnt.c" "kernel32.lib" "advapi32.lib" "user32.lib"
```

If I avoid Python I could build the libraries with:

    b2 address-model=64 --build-type=complete --toolset=msvc-14.0 --threading=multi --runtime-link=shared --variant=release stage

This works with the official version of Python, so this maybe a packaging difference

**Comment by csoja** [comment]
We recommend using conda-build to build conda packages for use with Anaconda.  If you haven't had a chance, please check out the latest conda-build blog post: https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/ or the conda and conda-build documentation: https://conda.io/docs/ or conda-forge https://conda-forge.org/

Also, boost is available in the default repository for Windows, so it can be installed with conda.
