### ISSUE TITLE
Issue with PyMC 2.3.4 - rollback to 2.3.2?

### ISSUE THREAD

**Issue by Anjum48** [ContinuumIO/anaconda-issues#407]
There seems to be an issue with PyMC 2.3.4: https://github.com/pymc-devs/pymc/issues/46
Version 2.3.2 is still functional but unavailable on the repo: http://repo.continuum.io/pkgs/free/win-64/index.html

Would it be possible to add an older version to rollback to? Or an upgrade to 2.3.5?

**Comment by groutr** [comment]
We shall update to 2.3.5 :)

**Comment by Anjum48** [comment]
Thanks! :)
