### ISSUE TITLE
how to use lib which is installed by pip

### ISSUE THREAD

**Issue by Jayhello** [ContinuumIO/anaconda-issues#4088]
If I install a python lib like 'my_lib' by 'pip install my_lib'(which can't be installed by conda), that lib can only be used by default python interpreter not anaconda, when you use pychram(backend with anaconda interpreter), there is no prompt.
when you want to use 'my_lib' you had to change you python interpreter to default python interpreter.

My question is how to use python lib that can only installed by pip(default python pip)

**Comment by csoja** [comment]
It is possible to install a pip package into a conda environment.  Please see the conda documentation: https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages  
Can you do so and verify that the package appears in _conda list_ ?
If it is not working as the documentation specifies, please open a new issue here: https://github.com/conda/conda/issues
