### ISSUE TITLE
"Anaconda Command Prompt" doesn't do what it says on the box

### ISSUE THREAD

**Issue by CrescentFresh** [ContinuumIO/anaconda-issues#41]
* Anaconda-1.8.0-Windows-x86_64.exe
* unchecked the option to modify the system PATH (in an attempt at a standalone installation)

Although the "Anaconda Command Prompt" opens a cmd window (with message "Added C:\Anaconda and C:\Anaconda\Scripts to PATH."), issuing `echo %PATH%` shows this to be untrue.

Tell-tale indication it didn't work: nothing in \Scripts can be found:

    C:\Anaconda>conda
    'conda' is not recognized as an internal or external command,
    operable program or batch file.

After inspecting the command prompt bootstrapper (`anaconda.bat`), I notice this near the top:

    setlocal enableextensions enabledelayedexpansion

which completely defeats the purpose of a batch file modifying `PATH` for a cmd window to be able to see. ([setlocal](http://technet.microsoft.com/en-us/library/bb491001.aspx)).

**Comment by Ogaday** [comment]
Can confirm that @3kwa and @adrianheron's solutions worked for me.

**Comment by scw** [comment]
The two character change from @3kwa works great for me as well, would be great to have this merged.

**Comment by amsmaguire** [comment]
I'm having the same problem. Running Windows 7 64-bit, Anaconda's Spyder Python 2.7. I tried CrescentFresh's code with the modifications above but it says syntax error with the "%%i" part. I'm very new to Python so sorry if the solution is very obvious!

**Comment by scw** [comment]
@amsmaguire the fix @3kwa posted is simpler and also works, that's probably the easiest to get the Conda environment up correctly on Windows currently.

**Comment by amsmaguire** [comment]
Ok, so how do I access this anaconda.bat? I tried typing it into the Anaconda command prompt and also Spyder. If it helps, it looks like Anaconda installed into "C:\Users\myusername\AppData\Local\Continuum\Anaconda". Or at least that's what pops up when I start the Anaconda command prompt.

**Comment by Trentonoliphant** [comment]
The anaconda.bat file should be located in the scripts folder in your anaconda directory

**Comment by amsmaguire** [comment]
Awesome! It worked! Thanks for the extra hint for the newbie.

**Comment by ahuanguchi** [comment]
Yeah, the `set "PATH=%ANACONDA%;%ANACONDA_SCRIPTS%;%PATH%"` fix in anaconda.bat also worked for me.

**Comment by datnamer** [comment]
Had the same issue on windows, crescent fresh's fix worked.

**Comment by Sjurk** [comment]
I confirm that @3kwa and @adrianheron's solutions worked for me for Anaconda 2.1.0 on Win64.

During the despair, I removed the %ANACONDA%; and %ANACONDA_SCRIPTS% folders from my system path, since anaconda.bat made them appear twice. That caused the Launcher to fail. 
Undid -> It all works.

**Comment by ccordoba12** [comment]
@ilanschnell It seems this was already solved and will be released in the next Anaconda release. Is that right?

**Comment by technomalogical** [comment]
Just tried 64-bit Anaconda 2.1.0 on Windows 7. The `set "PATH=%ANACONDA%;%ANACONDA_SCRIPTS%;%PATH%"` fix in anaconda.bat also worked for me.

**Comment by emirhartato** [comment]
@CrescentFresh tested, and this works for me with Windows 8.1. Many thanks! I can do more stuff with Anaconda now :+1:

**Comment by harrymvr** [comment]
It worked for me too. Thanks :+1:

**Comment by ccordoba12** [comment]
@asmeurer, can we close this one? Was this fixed already?

**Comment by asmeurer** [comment]
As far as I know if should be fixed in Anaconda 2.2.

**Comment by harrymvr** [comment]
I solved this issue using the suggestions above in a friend's fresh installation of Anaconda. I am assuming they had the latest version.

**Comment by ccordoba12** [comment]
Closing because this was solved in Anaconda 2.2 (already released.)

**Comment by scw** [comment]
Just did a fresh install of 2.2, and can confirm it's fixed. Thanks!

**Comment by ccordoba12** [comment]
@scw, thanks for the confirmation

**Comment by delgadom** [comment]
This fails for me when using python 3 unless I add `set PYTHONHOME=%ANACONDA%` to anaconda.bat after the construction of `ANACONDA`. The path is fine, but calls to python fail because `PYTHONHOME` is still set to C:\Anaconda.

Also needs to be fixed for the `activate` command. Thanks!

**Comment by asmeurer** [comment]
`PYTHONHOME` should not be set by either anaconda.bat or activate. Setting the `PATH` should be all that's required.

**Comment by delgadom** [comment]
I dug into it further (after reinstalling 2.2) and found that I could not get a `python=3` env to work on my windows 7 machine without setting `PYTHONPATH` and `PYTHONHOME` in activate and reverting these changes in deactivate. I do not have this issue on a separate brand-new machine (winows 8). Is this because `PYTHONHOME` is set on my windows 7 machine? If `PYTHONHOME` is not set, the `PATH` is used - perhaps this is the reason.

If this is the case, it could explain the discrepancy between my systems. If that's the issue, though, it seems anaconda, activate, and deactivate should deal with these to accommodate users with `PYTHONHOME` set? Or at least should give a warning... it took me forever to figure out the issue.

Thanks for the reply

**Comment by asmeurer** [comment]
If PYTHONHOME is already set you'll need to unset it for activate to work correctly. The variable changes where Python looks for its libraries, regardless of where Python itself is, so having it set would cause any conda environment to look for things in the place.

**Comment by delgadom** [comment]
Ok thanks!

**Comment by erseema** [comment]
I have installed anaconda4.3 with python 2.7.
Though i have set path still when I run 'python' command on cmd prompt it prompts python is not internal or external command.

**Comment by PyAntony** [comment]
It is not fixed for me. I can't run "conda" commands at all and I don't even have anaconda.bat file. I have anaconda 4.4.0 in windows 10 (python 3.6). "python" command runs, "pip" command runs, but not "conda".  I have installed everything as indicated, multiple times. Does anybody knows why "conda" commands don't work? When I type "conda" It shows up:

"usage: CONDA-script.py [-h] [-V] command ...
CONDA-script.py: error: argument command: invalid choice: 'C:\\USERS\\AGD10\\ANACONDA3\\SCRIPTS\\CONDA-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')"

**Comment by navneetkrc** [comment]
Hey PyAntony try running command prompt from Scripts folder in Anaconda storage like this C:\Users\....\Continuum\Anaconda3\Scripts in address bar type cmd.exe and run.   You should be able to run conda commands from here. Worked for me and I hope this helps you too.
Cheers

**Comment by PyAntony** [comment]
Hello. Thanks for response. It doesn't work. I have tried that trick in both cmd and anaconda prompt and nothing. But there is something curios, I can run "conda-script.py" command in anaconda prompt and cmd and it is the same as running "conda". So weird, any idea why?

**Comment by mingwandroid** [comment]
I don't understand why we see uppercase characters here:

> C:\USERS\AGD10\ANACONDA3\SCRIPTS\CONDA-script.py

Do you know how that has happened? Do you know what sort of filesystem you are using?

**Comment by anikasamiha** [comment]
![capture](https://user-images.githubusercontent.com/26202154/31210374-7bd1385c-a9b3-11e7-88ad-6f88a176cdaa.PNG)
When i open anaconda prompt after installing anaconda ,the cmd shows me this.How to fix this problem?

**Comment by wlievens** [comment]
Same for me, how do we fix this?

**Comment by sabyagunnersya** [comment]
I'm also facing the same issue. But I don't have a folder named Continuum in the location you specified. Any solution for this?

**Comment by soldyx** [comment]
Go to C: \ drive, and search directly for "Continuum", you may get many search results but choose the one which has this combination:   Continuum\anaconda3\Scripts\
Then, search for Activate.bat in this folder.

Another way is that go to Command Prompt, and in the C drive as the root location type this:
`dir activate.bat /s /p`

You will get multiple results, one of which would have Continuum\anaconda3\Scripts\

**Comment by sabyagunnersya** [comment]
It worked. Thank you very much!

**Comment by blakeelias** [comment]
I can run `python` and `pip` from my Command Prompt, and it uses the Anaconda version (I have no other Python version installed). But I cannot run the `conda` command at all.

**Comment by gnanaprakash655** [comment]
HI all, whenevr i open my anaconda prompt,the following message shows up

The system cannot find the path specified.

C:\Users\prakash>

i clearly remember adding path to system variable while installing,
there is no conda.bat file in my scripts but there is one in the bin but I cant find the above mentioned line..someone please help me out here
this is giving a tough time

**Comment by samayo** [comment]
Wow, almost 7 years later and **still** the same issue.

**Comment by mingwandroid** [comment]
@samayo, this is plain old Windows DLL-hell. That's something on the end-user side really. We have implemented something that works around DLL-hell though that might work. Still, rather than comments like one you made, perhaps you can open a new issue detailing what you tried, what you expected and what went wrong.
