### ISSUE TITLE
Clearly mention in Anaconda documentation that the oldest Mac OS X version supported is 10.7

### ISSUE THREAD

**Issue by benmwebb** [ContinuumIO/anaconda-issues#413]
In short, it looks like the boost package was built on a new Mac, which only has the `clang++` compiler. This means that it won't work on OS X 10.6 (which I think is your floor, given that you set `MACOSX_DEPLOYMENT_TARGET` to 10.6) because it links it against `libc++.1.dylib` which is not present on a 10.6 machine (I think it would need at least 10.8):

```
zink:miniconda ben$ conda info 
Current conda install:

             platform : osx-64
        conda version : 3.16.0
  conda-build version : 1.16.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/ben/miniconda  (writable)
  default environment : /Users/ben/miniconda
     envs directories : /Users/ben/miniconda/envs
        package cache : /Users/ben/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

zink:miniconda ben$ otool -L lib/libboost_iostreams.dylib 
lib/libboost_iostreams.dylib:
    @rpath/./libboost_iostreams.dylib (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 19.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
zink:miniconda ben$ ls /usr/lib/libc++.1.dylib
ls: /usr/lib/libc++.1.dylib: No such file or directory
```

To make this work on the full range of OS X releases, you'd need to build it with `g++` rather than `clang++` on a machine old enough to have a 10.6 SDK. I built it on a 10.6 machine and it works fine for me: http://anaconda.org/salilab/boost-mac

**Comment by ccordoba12** [comment]
Yes, I built Boost on 10.7. That's the oldest Mac I have access to :-)

**Comment by benmwebb** [comment]
Er, OK - I'm a little surprised that Continuum can't afford a VM with 10.6 (or something even older) for building Mac packages, but the core issue here is if a bunch of your packages fail on 10.6, shouldn't the Anaconda/Miniconda installer refuse to install on such a machine (or print a big scary warning)? I know that if I package my own scientific software for conda, then people are going to try and install it on really old Macs, certainly as old as 10.6, and if that's not supported I'd rather they blamed you guys than me ;)

**Comment by ccordoba12** [comment]
@ilanschnell, what do you think about this?

I think we should move *officially* to 10.7 because it seems internally that's already the oldest platform we support.

**Comment by ilanschnell** [comment]
Anaconda officially only supports 10.7 and up.  We have dropped 10.6 and 10.5 support over a year ago.

**Comment by ccordoba12** [comment]
Thanks Ilan, closing then.

**Comment by benmwebb** [comment]
@ilanschnell Well, that's fine, but it's not enforced (or warned about) by the installer, which is the point I was getting at. It doesn't seem to be stated anywhere on the website either, e.g. the [quick start guide](https://store.continuum.io/static/img/Anaconda-Quickstart.pdf) just says any Mac with "64-bit Intel processor" is OK.

**Comment by ccordoba12** [comment]
@kerrywatson1, could you take a look at this one? Thanks! :-)

**Comment by csoja** [comment]
Closing as documentation shows 10.9 as the older MacOS platform we currently support. (https://docs.anaconda.com/anaconda/install/)
