### ISSUE TITLE
Package for scikit-learn 0.19

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#4136]
Hope this is a good way to ping the conda packaging crew.
scikit-learn will release 0.19 today or tomorrow using this tag: https://github.com/scikit-learn/scikit-learn/releases/tag/0.19.0

It would be great if we could do a relatively synchronous release between pypi and conda to ease people's installation issues. I realize it's Friday afternoon, not sure if we want to announce today.

**Comment by amueller** [comment]
I guess if you could give us an ETA on how long it would take you to create a package, that would help us decide when to release.

**Comment by ilanschnell** [comment]
Since you already tagged the release, we can kick-off the builds now and conda packages should be available in a few hours.  You can check our RSS feed https://repo.continuum.io/pkgs/rss.xml to see when it's up.

**Comment by ogrisel** [comment]
Alright, let's do this then. I am ready to upload the source and wheels to PyPI.

**Comment by amueller** [comment]
Sweet, thanks @ilanschnell :) I guess it's in the name lol ;)

**Comment by ogrisel** [comment]
I will start the upload now because it going to take some time from my home network and I don't want to wait too late (it's 8:36pm here).

**Comment by ogrisel** [comment]
Upload complete.

**Comment by ogrisel** [comment]
We will wait for the anaconda update to do the announcement.

**Comment by ilanschnell** [comment]
Scikit-learn 0.19.0 is available in the default channel now.

**Comment by amueller** [comment]
Great, thanks!
