### ISSUE TITLE
Anaconda's portaudio fails to detect default input device

### ISSUE THREAD

**Issue by jamesdj** [ContinuumIO/anaconda-issues#4139]
I'm trying to use [SpeechRecognition](https://github.com/Uberi/speech_recognition), which depends on [PyAudio](https://people.csail.mit.edu/hubert/pyaudio/), which in turn depends on [PortAudio](http://www.portaudio.com/). When I `pip install` these packages in vanilla Python 3.5, they work. If I `pip install` them in Anaconda Python 3.6, when I try to record audio, I get the error `OSError: No Default Input Device Available`. Here's a code snippet that produces the error:
```
import pyaudio
pa = pyaudio.PyAudio()
pa.get_default_input_device_info()
```
Looking through PyAudio's source code, this command seems to almost directly call PortAudio. So I suspect this is an issue with Anaconda's PortAudio configuration, rather than with PyAudio. However, I tried e.g. replacing Anaconda's PortAudio library with a symlink to the system PortAudio library, and it didn't fix the problem.

**Comment by thereisnotspoon** [comment]
did you resolve the issue?
though i have the same problem

**Comment by adrianosantospb** [comment]
Me too.

**Comment by BrenBarn** [comment]
@mingwandroid I encountered this problem with Python 3.6 on Linux Mint 18.  I'm just installing PyAudio with `conda install pyaudio`.  I think users have a reasonable expectation that `conda install pyaudio` will "just work" without anyone having to worry about the version.  It looks like it's PyAudio 0,2.11 and PortAudio 19.6.0

nehaljwani's build works, so whatever that is doing seems to be the right thing.

**Comment by mingwandroid** [comment]
> I think users have a reasonable expectation that conda install pyaudio will "just work" without anyone having to worry about exactly what version it installs (or it should noisily fail if there's no working version, not just install a broken one). 

Is this meant to be helpful? I would hope it were very obvious that we don't release broken software deliberately.

**Comment by sadleader** [comment]
@mingwandroid Thanks for checking this issue.
I had the same problem with Ubuntu 18.04, anaconda3, conda 4.6.9, default channel, and `conda install pyaudio`.

It was fixed by:
```
conda remove pyaudio
conda remove portaudio
pip install pyaudio
```
Have to remove both pyaudio and portaudio.

At last, Anaconda's pyaudio  works well on Windows 10.

**Comment by kislaykk** [comment]
@nehaljwani thanks a lot man , i was in trouble why the modules weren't able to return default audio devices.
i ran this command of yours once.
and the program ran smooth as hell.
thanks man

**Comment by Kkuntal990** [comment]
> I was able to reproduce the problem on my Linux machine. The main problem seems to be that the portaudio library shipped in the anaconda distribution doesn't link to libasound2 (which comes from alsa-libs).
> 
> I have test builds of portaudio and pyaudio on my channel. Please give them a try:
> 
> ```
> conda install nwani::portaudio nwani::pyaudio
> ```

I searched for so much time, finally found one solution that worked! Thanx

**Comment by BrenBarn** [comment]
A year later, nwani's version still works, and the anaconda version still doesn't work.  Can you please look at nwani's version to see why it works and make the anaconda version do that?  Thanks.

**Comment by andrewallison2012** [comment]
@nehaljwani thank you the command below you gave worked!

`conda install nwani::portaudio nwani::pyaudio`

**Comment by jjhelmus** [comment]
I've re-built the `portaudio` packages in `defaults` to include the fix from the package in the `nwani` channel.  New environments should include this package automatically.

**Comment by noah-de** [comment]
> I've re-built the `portaudio` packages in `defaults` to include the fix from the package in the `nwani` channel. New environments should include this package automatically.

Which are the package versions with the fix?
I just installed these conda packages today and... well, I am searching for the solution to the problem.

Brand new conda installation (Python 3.8), Ubuntu 19.10.

Neither of the following work.

`conda install nwani::portaudio nwani::pyaudio`
  -> No channel found

`conda install portaudio pyaudio`
 -> Installation succeeds, no audio device available

I need to get this working, so I will keep investigating. However, I wanted to post this as a data point.

**Comment by jjhelmus** [comment]
The new packages with the fix are portaudio 19.6.0 build 4.  The hashes will be different for each platform, for linux-64 the package is `portaudio-19.6.0-h7b6447c_4`.  

Testing locally I see that pyaudio also needs to be rebuilt.  I'll build these shortly.

**Comment by noah-de** [comment]
Many thanks!

**Comment by jjhelmus** [comment]
`pyaudio` 0.2.11 build 2 packages are now available.  Using these and portaudio build 4 I can run the following snippet without issue.  Previous builds did not allow this.

``` Python
import pyaudio
pa = pyaudio.PyAudio()
print(pa.get_default_input_device_info())
```

**Comment by noah-de** [comment]
Amazing!
Thank you!

Would these be the _correct_  packages for Linux 64?
```_
$ conda list
portaudio                 19.6.0               h7b6447c_4  
...
pyaudio                   0.2.11           py35h14c3975_1 
```

The releases on: https://anaconda.org/anaconda/pyaudio/files
don't show anything newer than 17 days ago.

It looks like I can't get **pyaudio 0.2.11 build 2 packages**

Thank you @jjhelmus !

**Comment by jjhelmus** [comment]
You will want to update pyaudio to build `_2`.  

It will take a day or two for the new packages to show up on anaconda.org.  The new packages can be found in the `pkgs/main` channel at https://repo.anaconda.com/pkgs/ which is where they are pulled from by default.  If you have adjusted you channel setting you can pull from this channel via the command line using `conda install -c defaults pyaudio`.  

For linux-64 the specific packages are:

```
$ conda search pyaudio | grep _2
pyaudio                       0.2.11  py36h7b6447c_2  pkgs/main           
pyaudio                       0.2.11  py37h7b6447c_2  pkgs/main           
pyaudio                       0.2.11  py38h7b6447c_2  pkgs/main
```

Note that Python 3.5 is no longer supported by Anaconda so no packages will be released for that version.

**Comment by Yagna24** [comment]
> @nehaljwani thank you the command below (that you gave) worked!
> 
> `conda install nwani::portaudio nwani::pyaudio`

Is there a way to make this work on colab ?

**Comment by Yagna24** [comment]
> A year later, nwani's version still works, and the anaconda version still doesn't work. Can you please look at nwani's version to see why it works and make the anaconda version do that? Thanks.

is there a way to make this work on google colab ?

**Comment by sunarowicz** [comment]
Is this already fixed for Linux arm64 too? If I install pyaudio and sounddevice using pip in anaconda environment on my Ubuntu arm64 machine, I get the default device just fine. But if I do the same using conda install, I'm not getting it. Seems to me not fixed for arm64 yet.
