### ISSUE TITLE
Windows boost package does not include zlib iostreams filter

### ISSUE THREAD

**Issue by benmwebb** [ContinuumIO/anaconda-issues#414]
The boost package for Mac and Linux includes the boost_iostreams module and the [zlib filters](http://www.boost.org/doc/libs/1_53_0/libs/iostreams/doc/classes/zlib.html), presumably thanks to issue #247. However, the package (`boost-1.57.0-0`) for Windows does not:

    >conda info
    Current conda install:
    
                 platform : win-32
            conda version : 3.16.0
      conda-build version : 1.16.0
           python version : 2.7.9.final.0
         requests version : 2.7.0
         root environment : C:\Documents and Settings\IMP Developer\Miniconda  (writable)
      default environment : C:\Documents and Settings\IMP Developer\Miniconda
         envs directories : C:\Documents and Settings\IMP Developer\Miniconda\envs
            package cache : C:\Documents and Settings\IMP Developer\Miniconda\pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/win-32/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

    > dir C:\Documents and Settings\IMP Developer\Miniconda\Library\lib\boost_zlib*.dll
     Volume in drive C has no label.
     Volume Serial Number is 7442-98DD

     Directory of C:\Documents and Settings\IMP Developer\Miniconda\Library\lib

    File Not Found

(If built with zlib support, there should be a `boost_zlib-vc100-mt-1_57.dll` in this directory.)

My guess is this is because on Mac and Linux `libz` is available in the system path, but this is not the case for Windows. For consistency (well, and also because my conda packages use boost::iostreams::zlib and so don't work on Windows) it would be great to have zlib support in the Windows package too. I built my own Boost package which does include zlib on Windows at http://anaconda.org/salilab/boost which you are (of course) welcome to look at or borrow from. (Unfortunately I was only able to make it work by including the zlib source code in the recipe, which seems ugly - maybe you have a better solution. The [installation instructions](http://www.boost.org/doc/libs/1_53_0/libs/iostreams/doc/installation.html) hint that it should be possible to make this work with the existing zlib `.dll`, but I've never been able to make that work.)

**Comment by ccordoba12** [comment]
I'll fix it when we update Boost to its latest version :-)

**Comment by ccordoba12** [comment]
I fixed this problem already, and new packages will be available soon. However, there wont' be a zlib boost library because we're using our (shared) zlib package.

**Comment by benmwebb** [comment]
Since the boost packages don't seem to be available yet (any idea when?), is it possible for me to test them out for you before release? If not, here's the little test program I use (basically straight out of the boost docs, but with their bugs fixed ;)

```
#include <fstream>
#include <iostream>
#include <boost/iostreams/filtering_streambuf.hpp>
#include <boost/iostreams/copy.hpp>
#include <boost/iostreams/filter/zlib.hpp>

int main()
{
    using namespace std;

    ifstream file("hello.z", ios_base::in | ios_base::binary);
    boost::iostreams::filtering_streambuf<boost::iostreams::input> in;
    in.push(boost::iostreams::zlib_decompressor());
    in.push(file);
    boost::iostreams::copy(in, cout);
}
```

This compiles fine with my modified boost-1.57.0 package with
```
cl /EHsc /MD test-boost-libz.cpp -DBOOST_ALL_DYN_LINK -I%LIBRARY_INC% /link /libpath:%LIBRARY_LIB%
```
but fails with the stock anaconda boost 1.5.7.0-0 package with
```
LINK : fatal error LNK1104: cannot open file 'boost_zlib-vc100-mt-1_57.lib`
```
Note that using the system zlib is a laudable goal but it looks to me like Boost's autolinking on Windows will look for a `boost_zlib` library anyway (and so fail).

**Comment by benmwebb** [comment]
Also, if you're going to all the trouble of rebuilding the boost package, you may as well add [bzip2 support](http://www.boost.org/doc/libs/1_38_0/libs/iostreams/doc/classes/bzip2.html) too, since someone's bound to complain about it lacking bzip2 support as soon as you announce it supports zlib ;) Should just be a case of setting the `BZIP2_INCLUDE` and `BZIP2_LIBPATH` variables, same as is done for zlib.

**Comment by ccordoba12** [comment]
@benmwebb, I can't make bzip2 support to work, sorry. It failed during linking, I think.

I'll upload the current packages to my Anaconda channel so you can test them. Please ping me again if I haven't done it for Sunday ;-)

**Comment by benmwebb** [comment]
Too bad about the bzip2 support! If your Anaconda channel is https://anaconda.org/ccordoba12/boost, then I don't see anything newer than 1.57.0 there...

**Comment by ccordoba12** [comment]
Sorry, I haven't uploaded my packages yet.
