### ISSUE TITLE
Direct link to python 3.4 not working anymore

### ISSUE THREAD

**Issue by MaxNoe** [ContinuumIO/anaconda-issues#417]
Since a few weeks or so the link
http://continuum.io/downloads#34
does not lead to the python 3.4 installer anymore. The displayed button is for python 2.7.

**Comment by ccordoba12** [comment]
@ilanschnell?

**Comment by ilanschnell** [comment]
I think the link is: http://continuum.io/downloads#py34

Note `#py34` (instead of just `#34`).

**Comment by MaxNoe** [comment]
That also leads me to 2.7

**Comment by ccordoba12** [comment]
The link is correct, and after I followed it, I can see links to the Anaconda3 installers, as expected:

![seleccion_001](https://cloud.githubusercontent.com/assets/365293/9424630/7b38fabe-48b8-11e5-8db9-6e6373e60745.png)

**Comment by ilanschnell** [comment]
One can always go here: https://repo.continuum.io/archive/index.html
No fancy shenanigans on this page.

**Comment by MaxNoe** [comment]
Not for me on windows:

![anaconda34](https://cloud.githubusercontent.com/assets/5488440/9424651/e1c6dacc-48f3-11e5-879a-10a4d5312108.png)

**Comment by ccordoba12** [comment]
Please press the *I want Python 3.4* button

**Comment by MaxNoe** [comment]
I know ;) But we want to deliver the link to students ;) Last year the direct llinked worked and showed directly the correct button without needing to press the 'I want python3.4'. We want to minimize the number of students downloading the wrong version.

**Comment by ccordoba12** [comment]
Then please use the page referenced by @ilanschnell a couple of comments above :-)

**Comment by ccordoba12** [comment]
Although you're right that the link doesn't work when pasted on the browser

**Comment by MaxNoe** [comment]
I just thought I let you know because it used to work ;)

**Comment by ccordoba12** [comment]
@ilanschnell, who's in charge of our web page?

**Comment by ilanschnell** [comment]
Amenity

**Comment by nehaljwani** [comment]
Closing as `Python 3.4` is no longer supported
