### ISSUE TITLE
Navigator error

### ISSUE THREAD

**Issue by Tbrahmbha** [ContinuumIO/anaconda-issues#4183]
The Navigator is not launching for some reason

**Comment by goanpeca** [comment]
@Tbrahmbha could you provide some extra information? If you launch it from the CLI what do you see? What OS?

Please time `conda info` and `conda list` and paste the results here

**Comment by Tbrahmbha** [comment]
I got it to finally launch and open the navigator, however, it is very slow
and as soon as I launch spyder from the anaconda navigator the
ipython console says the kernel died restarting multiple times. Should I
uninstall and reinstall anaconda?

I am using Mac OS EL Capitan version 10.11.6

Best Regards,

Teerth Brahmbhatt
