### ISSUE TITLE
Spyder 2 (python2.7) no longer launches. I changed name of python envs

### ISSUE THREAD

**Issue by hachidan05** [ContinuumIO/anaconda-issues#422]
So I have python 3 and spyder 3 as default working directory. Then I made a "python2" environment using conda commands and activated the enviroment. I can launch Spyder 2 (python 2.7) before. I changed named python.exe and pythonw.exe (within envs/python2) to python2.exe and pythonw2.exe so I can use iPython notebook with python2 kernel. I rather not change name everytime i want to switch between using spyder and iPython notebook. What is the best way to have both?

**Comment by ccordoba12** [comment]
Most probably changing names to python.exe and pythonw.exe is what broke your environment. You don't need to do that.

**Comment by hachidan05** [comment]
So how do you suggest I get iPython notebook to work (run python2 kernel along with python3 kernel) without changing name of python.exe?

**Comment by hachidan05** [comment]
I figured it out. Change directory to my anaconda python2.7 envs then do a ipython kernelspec install-self.
