### ISSUE TITLE
Spyder wont load after updating to PyQt5

### ISSUE THREAD

**Issue by jojk** [ContinuumIO/anaconda-issues#4243]
Steps:

1. Install anaconda3-4.4.0 on your windows 10 machine confirm that spyder works, use it for months.
2. open the anaconda command prompt
3. uninstall PyQt4 which comes with that version "conda uninstall pyqt"  (this will also uninstall anaconda-navigator, jupyter, matplotlib, qtconsole, scikit-image, seaborn, spyder)
5. run "conda update --all" it will NOT re-add the modules you just removed. 
6. Install PyQt5 (5.6.0) and the other modules (conda picks spyder 3.2.0 py36_0)
7. try to run spyder via "spyder.exe"
8. it will display a dialog window: "python has stopped responding"  and will automatically close (anaconda-navigator also will not run)

Resolutions that failed:

1. removing the spyder.lock folder
2. running "conda update --all" and "conda update spyder" again
3. trying to go back to pyqt version 4 fails because it is in conflict with python 3.6.
4. I'm hesitant to try to reinstall anaconda because I installed a lot of third party packages to the conda environment and don't want to spend a lot of time reinstalling and troubleshooting those. They have been installed for months. Maybe reinstalling wont remove those?

Thanks for your help!

**Comment by goanpeca** [comment]
@jojk please try with the latest version of Anaconda
