### ISSUE TITLE
error when Launching spyder with anaconda

### ISSUE THREAD

**Issue by shihu4937** [ContinuumIO/anaconda-issues#4246]
I am working on a project using FEnicsproject.  I used the anacondat to set up my environment. I try launch the spyder, however I run into the following errors.  I did not know what I need to do.  Any help would be appreciated. thanks!

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/hushi/anaconda2/envs/fenicsproject/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/hushi/anaconda2/envs/fenicsproject/lib/python2.7/site-packages/spyder/app/start.py", line 135, in main
    from spyder.app import mainwindow
  File "/Users/hushi/anaconda2/envs/fenicsproject/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 78, in <module>
    from qtpy.compat import from_qvariant
  File "/Users/hushi/anaconda2/envs/fenicsproject/lib/python2.7/site-packages/qtpy/compat.py", line 15, in <module>
    from .QtWidgets import QFileDialog
  File "/Users/hushi/anaconda2/envs/fenicsproject/lib/python2.7/site-packages/qtpy/QtWidgets.py", line 24, in <module>
    from PyQt4.QtGui import *
ImportError: dlopen(/Users/hushi/anaconda2/envs/fenicsproject/lib/python2.7/site-packages/PyQt4/QtGui.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/hushi/anaconda2/envs/fenicsproject/lib/libQtGui.4.8.7.dylib
  Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 34.0.0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.22
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by ccordoba12** [comment]
How did you install fenics?

**Comment by shihu4937** [comment]
I installed it with anaconda to my MAC
the command is: conda create -n fenicsproject -c conda-forge fenics

**Comment by ccordoba12** [comment]
I think this error appears because you're mixing packages from conda-forge and defaults.

Instead of installing everything in the default environment, you should install conda-forge packages in a different conda environment, and then change your Python interpreter in Spyder to use it.

You can do the last part by going to

    Tools > Preferences > Python interpreter

**Comment by shihu4937** [comment]
Thank you for your reply ~~ccordoba12
My Fenicsproject was installed as a separate environment. and the python interpreter was set up.  
I reinstalled all the packages inside the environment and somehow the problem seems disappeared. 

thanks again!

**Comment by shihu4937** [comment]
I believe that the problem is caused by my recent installation of one package scitools. This might have caused some interference to libpng and matplotlib.

**Comment by ccordoba12** [comment]
> the problem seems disappeared.

Great!
