### ISSUE TITLE
Mac OSX Navigator fails to start - 

### ISSUE THREAD

**Issue by bn-sandbox** [ContinuumIO/anaconda-issues#4255]
I've run conda clean --all 
followed by anaconda-navigator, which doesn't fix the problem - it rebuilds the anaconda libraries/app but then craps out in the same place.

I've looked at all of the permissions for the associated directories and files, don't see anything - they are all owned by the same user/group as everything else, and perms are 755.

Any ideas?   Thx!

BN

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro9,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
```
Traceback (most recent call last):
File "/Users/bn/anaconda3/lib/python3.5/site-packages/psutil/_psosx.py", line 293, in wrapper
return fun(self, *args, **kwargs)
File "/Users/bn/anaconda3/lib/python3.5/site-packages/psutil/_psosx.py", line 356, in cmdline
return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/bn/anaconda3/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/bn/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/bn/anaconda3/lib/python3.5/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/bn/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "/Users/bn/anaconda3/lib/python3.5/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=656)

```
conda config --show

add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  Users/bn/anaconda3/conda-bld: file:///
  pkgs/free: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
  local: ["file:///Users/bn/anaconda3/conda-bld"]
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /Users/bn/anaconda3/envs
  - /Users/bn/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /Users/bn/anaconda3/pkgs
  - /Users/bn/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0

**Comment by goanpeca** [comment]
@bn-sandbox it seems you ran navigator with sudo at some point, you will need to remove the navigator configuration files and try again

`sudo rm -rf ~/.anaconda/`
