### ISSUE TITLE
boost package is broken as conda-build dependency on Mac OS X

### ISSUE THREAD

**Issue by pavoljuhas** [ContinuumIO/anaconda-issues#428]
I tried to use the standard boost package from Anaconda (boost-1.57.0-4) as a build recipe dependency for my own package which needs the boost_python library.  The recipe compiled OK with conda-build, however importing that package failed with "Symbol not found:" errors.

I am not sure if the Anaconda boost package is built with [this recipe](https://github.com/conda/conda-recipes/blob/master/boost), however the build script [there](https://github.com/conda/conda-recipes/blob/master/boost/build.sh#L17-L21) forces the macosx-version-min to 10.8 ignoring the `MACOSX_DEPLOYMENT_TARGET=10.6` set in the environment by conda build.  My package relies on the conda-build target 10.6 and I guess the results are incompatible when boost_python is constructed for 10.8.

Could you please fix the boost recipe to adhere to the MACOSX_DEPLOYMENT_TARGET and release an updated package?

**Comment by ccordoba12** [comment]
Are you deploying on 10.6?

**Comment by pavoljuhas** [comment]
I am deploying on 10.10, OS X Yosemite.

**Comment by ccordoba12** [comment]
I fixed this problem in conda-recipes, by setting again `macosx-version-min` to `10.6`.

New packages will be available soon, thanks for your patience :-)

**Comment by pavoljuhas** [comment]
Please see conda/conda-recipes#487 for a cleaned up version of the boost recipe.  Let me know if you have any  questions about proposed changes.
