### ISSUE TITLE
typing and pasting in ipython is extremely slow in --pylab mode

### ISSUE THREAD

**Issue by isofer** [ContinuumIO/anaconda-issues#43]
Typing and pasting are slowed in ipython --pylab,
The problem happen on many platforms, and suggested to be related to the QT backend.

see details:
https://groups.google.com/a/continuum.io/d/topic/anaconda/kvWVtW40aDI/discussion

**Comment by csoja** [comment]
Sounds like this issue was handled on the anaconda mailing list in 2013, but this issue did not get closed. Closing now.
