### ISSUE TITLE
Anaconda.org search results don't sort

### ISSUE THREAD

**Issue by pelson** [ContinuumIO/anaconda-issues#430]
It seems clicking on the sort buttons doesn't actually do anything: 

e.g. https://anaconda.org/search?q=shapely&sort=_ndownloads
and https://anaconda.org/search?q=shapely&sort=upvotes (this may be sorted, but unexpectedly ascending)

**Comment by goanpeca** [comment]
@pelson, thanks for reporting

**Comment by scw** [comment]
Came to mention the same. Also affects sorting by package version, which is useful in exploring the packages.

**Comment by pelson** [comment]
Always the same old trouble makers, eh @scw :wink:

**Comment by scw** [comment]
@pelson to the trouble makers :sake:

**Comment by pelson** [comment]
Appears to have been fixed.
