### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hooliowobbits** [ContinuumIO/anaconda-issues#4300]
## Main error
Application <b>rstudio</b> launch may have produced errors.
## Traceback
```
failed to get the current screen resources
QXcbConnection: XCB error: 172 (Unknown), sequence: 163, resource id: 163, major code: 149 (Unknown), minor code: 20
load glyph failed err=6 face=0x15ab920, glyph=2798
load glyph failed err=6 face=0x15ab920, glyph=2798

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.24
qt: 5.6.2
language: en_AU
python: 2.7.13
os: Linux;4.4.0-87-generic;#110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by mingwandroid** [comment]
Hi @hooliowobbits, do you actually suffer any problem?

**Comment by hooliowobbits** [comment]
@mingwandroid I'm not sure what you mean exactly by the word "problem".  From what i can tell there is no apparent loss in functionality, however the error message is obvious and repeatable.  

Background: I'm developing an image for use in a classroom environment (100+ users) and it won't do me or Anaconda any good PR to allow such an obvious errors to go unresolved.

Which brings me to the question; @goanpeca Why is this issue closed?

**Comment by mingwandroid** [comment]
This 'error' (it is some software being overzealous in it's reporting of issues that it manages to work around) is because we build our software to work with very old Linux distributions and that causes some mismatches when run on more modern Linux distributions (here the Xcb protocol has grown some new commands, but Xcb gracefully ignores (though reports) mismatches).

The only 'fix' I could provide is to hide such a message but that feels like cheating.

This issue is closed because there is nothing we can do about it except to suggest you ignore it.

**Comment by mingwandroid** [comment]
Oh and the other one is that a font is missing a glyph. I am not going to lose any sleep over that one either.

**Comment by mingwandroid** [comment]
Finally, the reason you are reporting this is because an automatic bug reporting feature got added to Anaconda Navigator a few releases ago. This has since been toned down in new versions so` conda update anaconda-navigator` should get you one that will not prompt you to report these things.

**Comment by hooliowobbits** [comment]
Hi there, thanks for your reply.  Two things, three things actually:
1. Thanks for everything you guys do to produce conda and navigator and all the rest, it's revolutionizing the way we're doing software delivery to researchers.  It's amazing and i can see it fixing many many problems.  I don't want my issue here to overshadow all the good work that you guys do.
2. We're presenting this software stack as a better way of doing things, and software with errors that appear (whether benign or not) doesn't create a good impression (on us as curators, or on yourselves as application developers).  If you have the capacity to make that error dissapear i'd appreciate it if you could; i don't understand how it's cheating; if the software is smart enough to fix a problem (as i'm sure it fixes thousands of them) then let it celebrate that and leave the error dialogs for actual errors.  
3. I appreciate the ability to semi-automatically report issues.   I've installed miniconda and anaconda about 50 times in the last few weeks, and one of the installs i had the error and had no way to deal with it other than say "ahh that's ugly.  but it seems to work ok".  Remember as users we don't know if the error is benign or not.  For new users it represents a blow to their confidence in the software, and being able to report it is empowering.

**Comment by mingwandroid** [comment]
Thanks @hooliowobbits, when I first commented here I though it was just some text in a shell or console window that you were reporting rather than an actual, in the users' face dialog.

So I fully understand your concerns, however `conda update anaconda-navigator` should prevent this dialog from appearing for these trivial issues.

**Comment by hooliowobbits** [comment]
@mingwandroid no worries.  I'm glad we were able to get there in the end.

While we're talking, I have a feature request; what's the best way for me to go about submitting it?

**Comment by mingwandroid** [comment]
Probably a new issue here is best.

**Comment by hooliowobbits** [comment]
Hey, I'd like to reopen this issue please.  I am still getting this problem, and it persists after running ` conda update anaconda-navigator`.  i can provide whatever details you like, but essentially i'm running what i believe to be a current version of anaconda-navigator:
```
(root) ubuntu@fudging-core:~$ conda update anaconda-navigator
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/ubuntu/.local/miniconda3:
#
anaconda-navigator        1.6.4                    py36_0 
```
and i've attached a screenshot to show the persistent problem.

![screenshot-1](https://user-images.githubusercontent.com/3781911/30625484-de4dbdce-9e06-11e7-8fdd-dfd9e6d93453.png)

i'm able to replicate the issue on multiple computers using the same (openstack) image built by me.  the image is built up from a vanilla ubuntu 16.04 image and the build scripts are available at https://github.com/hooliowobbits/fudge/blob/master/toolchains/core.014/ansible.core.014.yml which calls https://github.com/hooliowobbits/fudge/blob/master/ansible/tasks/ansible.core.yml which calls https://github.com/hooliowobbits/fudge/blob/master/ansible/files/usr-local-scripts-install.miniconda.sh.  it's not necessary for you to step through these scripts, but I've included them in case you want to know exactly how i got where i am.
