### ISSUE TITLE
Spyder 3.2.0 won't launch on Navigator 1.6.2 for Windows.

### ISSUE THREAD

**Issue by f-tonini** [ContinuumIO/anaconda-issues#4315]
I created a custom Py2.7 environment on Navigator 1.6.2 for Windows (64bit). After installing Spyder 3.2.0, I click on launch and the progress bar moves for a few seconds but the software does not launch.

**Comment by goanpeca** [comment]
@f-tonini if you update to the latest navigator do you see the issue? On the terminal

`$ conda update anaconda-navigator`

**Comment by f-tonini** [comment]
Since conda is not in my PATH (to avoid conflicts with other python installs I have) and I have to be on root to update navigator, I opened the terminal from inside navigator. However, it throws a WindowsError(32,  'The process cannot access the file because it is being used by another process'). Any workaround to upgrade from terminal in my situation?

**Comment by goanpeca** [comment]
@f-tonini, sure just use the full paths ?

```
C:\user\someuser\anaconda\scripts\activate root
```

and then use as usual ?

**Comment by f-tonini** [comment]
Ok, so now it's updated to v1.6.4. I reopen the navigator app, go into my custom env and click launch for Spyder 3.2.0. Same as before, progress bar moving, nothing opens...

**Comment by goanpeca** [comment]
@f-tonini what if you launch spyder from that already activated terminal (or activate right env)

```
$ C:\user\someuser\anaconda\scripts\activate YOURENV
$ spyder
```

Any traceback there?

**Comment by f-tonini** [comment]
yes, if I do what you suggested above the software will launch properly.
