### ISSUE TITLE
Anaconda navigator error

### ISSUE THREAD

**Issue by duytrung** [ContinuumIO/anaconda-issues#4334]
Hi,

I ran anaconda navigator to create environment. It has generated error as following:
```
> anaconda-navigator
Qt: Session management error: None of the authentication protocols specified are supported
libpng warning: iCCP: known incorrect sRGB profile
2017-08-17 16:58:13,280 - ERROR conda_api.communicate:292
error

2017-08-17 16:59:23,535 - ERROR conda_api.communicate:292
error
```

**Comment by goanpeca** [comment]
@duytrung is it not running?

**Comment by jw447** [comment]
I had the same issue. The anaconda navigator is running but seems to be with a lot of bugs... error conda_api.communicate: 292; resolution problem,...... Can anyone help me?

**Comment by goanpeca** [comment]
@jw447 what version are you using?

**Comment by jw447** [comment]
I am using the latest one, I think it is Anaconda3-5.0.1-Linux-x86_64

**Comment by goanpeca** [comment]
What version of Anaconda Navigator
