### ISSUE TITLE
R kernal keeps dying

### ISSUE THREAD

**Issue by Shad0w-f0x** [ContinuumIO/anaconda-issues#4342]
Hi, this is my first time using Anaconda and I just downloaded it and installed R Essentials. When I try to open an R notebook in Jupyter Notebook , the kernal always dies and is unable to restart. I get this message: 'C:\Users\Sarah\Anaconda3\R/bin/x64/Rterm.exe' is not recognized as an internal or external command,operable program or batch file.

I've posted about this previously here:  https://github.com/IRkernel/IRkernel/issues/498
and it was suggested that it's due to a problem with the conda package of R.  

Any help would be greatly appreciated thanks.

**Comment by takluyver** [comment]
The thing that particularly made me think this is an Anaconda issue is that running `R` in the command prompt (which appears to point to `C:\Users\Sarah\Anaconda3\Scripts\R.exe`) fails with the same error.

**Comment by mingwandroid** [comment]
I cannot reproduce this.

Please try todo this in a brand new Miniconda installation as follows:

```
cd %TEMP%
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe', 'mc3.exe') }"
start /wait "" mc3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%TEMP%\mc3
%TEMP%\mc3\Scripts\activate.bat
conda install -y r-essentials jupyter
jupyter notebook
```

**Comment by Shad0w-f0x** [comment]
Sorry, I'm new to this, how do I open a command prompt from miniconda?

**Comment by mingwandroid** [comment]
You open it from the Windows `Start Menu` itself.

**Comment by mingwandroid** [comment]
Closing due to lack of feedback. Please re-open once you have tried my suggestion and iff that suggestion fails.
