### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mdelrio1** [ContinuumIO/anaconda-issues#4387]
Application action error

/Users/migueldelrio/anaconda/bin/python /Users/migueldelrio/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/migueldelrio/anaconda notebook=5.0.0: The following specifications were found to be in conflict:
  - notebook 5.0.0*
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.4.4', 'conda': '4.1.8', 'os': 'Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386', 'version': '1.2.2', 'qt': '4.8.7', 'language': 'en', 'pyqt': '4.11.4', 'platform': 'osx-64'}

**Comment by goanpeca** [comment]
@mdelrio1 you are using a very old version of Navigator.

Please open a terminal and update to the latest version.


```
$ conda update anaconda-navigator
```
