### ISSUE TITLE
Fatal error during start up of Anaconda Launcher

### ISSUE THREAD

**Issue by perdalum** [ContinuumIO/anaconda-issues#439]
Anaconda Launcher-1.0.0
Latest version of El Capitain public beta as of 7 September 2015

This was the message:

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by rbmayer** [comment]
Received same error message. Running launcher on Ubuntu 14.04.

**Comment by perdalum** [comment]
I deleted the ~/anaconda directory and re-installed. That removed the error and I now have a working Anaconda. Still, this says nothing regarding the source of the problem.

**Comment by idichekop** [comment]
I have the same problem and it is reported also in issue #333.
In my case, I can run the launcher from a terminal, but not to the docked icon in my desktop.

**Comment by goanpeca** [comment]
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by amanparnami** [comment]
I encountered the same issue when I updated the Notebook package from Launcher GUI on MacOSX.

**Comment by emirkmo** [comment]
+1 to I encountered the same error when I tried to update the notebook package via the Launcher GUI. But not only that, this broke my entire conda installation.

Terminal no longer recognize the "conda" command, or any other anaconda related commands. But I can still access the python installed by anaconda. I just can't, for example, access jupyter notebook anymore.

I can verify that all of the anaconda packages, files, etc. are still there. The only step I took was to press update on the Launcher GUI, next to notebooks. Now I cannot use anaconda, but must re-install. Without access to the "conda" commands.

**Comment by goanpeca** [comment]
@emirkmo Anaconda Launcher is deprecated.

Please use Anaconda Navigator which replaced Launcher.

The latest version of navigator is (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers

**Comment by emirkmo** [comment]
@goanpeca As I said, "conda" commands **do not work.** It will say "command not found", even though all of the files exist, the paths are the same, etc. 

However, to record for posterity, deleting the anaconda folder, and re-installing the newest version (4.2) via the website has fixed the issue. I was not able to find another fix.

Thanks for the response!
