### ISSUE TITLE
Cannot mix incompatible Qt library (version 0x50201) with this library (version 0x50602)

### ISSUE THREAD

**Issue by onlytailei** [ContinuumIO/anaconda-issues#4415]
Ubuntu 14.04
anaconda 2
When I use matplotlib to show image, such error appeared.

It seems that my system qt is 5.2.1 but conda qt is 5.6.2.

What should I do?

I also tried Spyder. It doesn't work as well.
spyder
Traceback (most recent call last):
  File "/home/tai/anaconda2/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/tai/anaconda2/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/tai/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/tai/anaconda2/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: /home/tai/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libgsttag-1.0.so.0: undefined symbol: _gst_tag_list_type

**Comment by ccordoba12** [comment]
Do you have LD_LIBRARY_PATH set?

**Comment by onlytailei** [comment]
Oh I found that. I link this qt 5.2.1 in LD_LIBRARY_PATH. 
After I delete it, conda works again.

**Comment by ccordoba12** [comment]
Great!

**Comment by jsvelasquez** [comment]
Hi, I am having this problem as well. Could you please be a bit more specific on what to do to solve it?

**Comment by ccordoba12** [comment]
@jsvelasquez, please google for something like

> How to unset enviroment variables

or

> How to unset LD_LIBRARY_PATH

**Comment by jsvelasquez** [comment]
@ccordoba12 thanks, it works!

**Comment by ccordoba12** [comment]
Great, thanks for letting us know about it!
