### ISSUE TITLE
Ipython broken in new env

### ISSUE THREAD

**Issue by MaxNoe** [ContinuumIO/anaconda-issues#442]
If I do 

```
conda create -n test python=3.4
source activate test
conda install ipython
ipython 
```

I get the following error:

```
/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda3/envs/test/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/core/application.py", line 24, in <module>
    from IPython.core import release, crashhandler
  File "/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/core/ultratb.py", line 116, in <module>
    from IPython.utils import path as util_path
  File "/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/utils/path.py", line 21, in <module>
    from IPython.utils.process import system
  File "/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/utils/process.py", line 28, in <module>
    from ._process_posix import _find_cmd, system, getoutput, arg_split, check_pid
  File "/home/maxnoe/.local/anaconda3/envs/test/lib/python3.4/site-packages/IPython/utils/_process_posix.py", line 24, in <module>
    from IPython.external import pexpect
ImportError: cannot import name 'pexpect
```

Any Idea how to fix it? In my base environment all is fine.

**Comment by MaxNoe** [comment]
I am stupid. 

A had a directory `test` in the folder in which i was executing the command.

**Comment by ccordoba12** [comment]
Could you remove your `test` environment and post the output of

     conda create -n test python=3.4 ipython

? Thanks :-)

**Comment by MaxNoe** [comment]
```
$ conda create -n test python=3.4 ipython
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/maxnoe/.local/anaconda3/envs/test:

The following NEW packages will be INSTALLED:

    decorator:        4.0.2-py34_0 
    ipython:          4.0.0-py34_0 
    ipython_genutils: 0.1.0-py34_0 
    openssl:          1.0.1k-1     
    path.py:          7.6-py34_0   
    pexpect:          3.3-py34_0   
    pickleshare:      0.5-py34_0   
    pip:              7.1.2-py34_0 
    python:           3.4.3-1      
    readline:         6.2-2        
    setuptools:       18.1-py34_0  
    simplegeneric:    0.8.1-py34_0 
    sqlite:           3.8.4.1-1    
    system:           5.8-2        
    tk:               8.5.18-0     
    traitlets:        4.0.0-py34_0 
    wheel:            0.24.0-py34_0
    xz:               5.0.5-0      
    zlib:             1.2.8-0      

Proceed ([y]/n)?: 
```

**Comment by ccordoba12** [comment]
This is very strange because (as you can see) `pexpect` is installed as part of `ipython` dependencies.

So I don't understand how your error is generated :-s

**Comment by MaxNoe** [comment]
Yes, I also can do `import pexpect` but not `from IPython.externals import pexpect`

**Comment by MaxNoe** [comment]
The ipython docs say:
> pexpect
The pexpect package is used in IPython’s irunner script, as well as for managing subprocesses. IPython now includes a version of pexpect in IPython.external, but if you have installed pexpect, IPython will use that instead. 

And that seems somehow to fail.

**Comment by MaxNoe** [comment]
I found this: https://github.com/chapmanb/bcbio-nextgen/issues/990
But reinstalling does not help.

**Comment by MaxNoe** [comment]
If I install ipython using pip, it works

**Comment by ccordoba12** [comment]
Please look at https://github.com/ipython/ipython/issues/8806. It seems the same error as yours.

**Comment by MaxNoe** [comment]
I do not really see the connection. The error is different: `no module named pexpect` instead of `    from IPython.external import pexpect
ImportError: cannot import name 'pexpect`, also the issue was an outdated setuptools version. I have an up to date conda.

**Comment by idgserpro** [comment]
@MaxNoe  In fact I think it's the same error. The message ```no module named pexpect``` is only how the Zope displays this error. The error is even on the same line ```IPython/utils/_process_posix.py", line 24```. Which version of setuptools you using?

**Comment by idgserpro** [comment]
@MaxNoe I saw in the [comment](#issuecomment-140083103) that you are using setuptools 18.1. In my case, this version worked. I am using python 2 and you are using python 3. I do not know if is that. However, the error is the same. The pexpect is not added to PYTHONPATH.

**Comment by idgserpro** [comment]
@MaxNoe although the [comment](#issuecomment-140083103) say you are using the 4.0.0 version of IPython, it looks like it has an older version on your PYTHONPATH. In version 4.0.0, the line 24 of  file ```IPython/utils/ _process_posix.py``` is  
```python
import pexpect
```
and not
```python
from IPython.external import pexpect
```
 see: https://github.com/ipython/ipython/commit/6b5847f205a4a15454d400b203a0098c7a171c6b#diff-5

**Comment by csoja** [comment]
Closing due to lack of recent activity.
