### ISSUE TITLE
Internet routines cannot be loaded when load R Studio from Navigator

### ISSUE THREAD

**Issue by Mikejs2178** [ContinuumIO/anaconda-issues#4421]
Using Anaconda Navigator 1.6.3, R Studio version 1.0.153 and R version 3.4.1.
MacBook Air Mac OS version 10.12.6

When launch R Studio with Navigator, I get the following error:
Error in tools::startDynamicHelp() : internet routines cannot be loaded
This R Studio was installed via conda with R Essentials
When I start an older version of R Studio outside of Anaconda Navigator (i.e. a Version of Rstudio I had before I installed the Anaconda version of R Studio) I do not get this problem

**Comment by mregensberg** [comment]
+1

**Comment by slinnarsson** [comment]
I get a similar error on a clean install of Anaconda 4.4.0 after doing "conda install rpy2". This is on Mac OS Sierra, and the R version I get is 3.4.1:

```
> source("http://bioconductor.org/biocLite.R")

Error in file(filename, "r", encoding = encoding) : 
  internet routines cannot be loaded
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  unable to load shared object '/Users/sten/anaconda3/lib/R/modules//internet.so':
  dlopen(/Users/sten/anaconda3/lib/R/modules//internet.so, 6): Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: /Users/sten/anaconda3/lib/R/modules//internet.so
  Reason: image not found
```

Note that @rpath has nothing to do with R, but is a [mechanism for finding shared libraries](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html) on Mac OS X.

Checking under `~/anaconda3/lib` indeed there is no libssh2.1.dylib. After doing

```
conda install libssh2
```

it still doesn't work, but now it wants to load another library (`libgssapi_krb5.2.2.dylib`) which we can get by installing krb5:

```
conda install krb5
```

...and this **solves the problem**! At least on my machine.

**Comment by mingwandroid** [comment]
Thanks @slinnarsson, I need to get this fixed ASAP.

**Comment by Mikejs2178** [comment]
Thanks, this solved the problem.

**Comment by mingwandroid** [comment]
This is open until I fix it properly.

**Comment by lihp11** [comment]
Thanks，it solved my problem!!!

**Comment by mattsears18** [comment]
thanks @slinnarsson, solved for me.

**Comment by andreassandhi** [comment]
thanks @slinnarsson, solved for me.

**Comment by JLprogramming** [comment]
Thank you @slinnarsson! It solved the problem I've stuck for 2 days!

**Comment by StealthNameless** [comment]
Hello,

I have tried to fix the internet routines problem as well by copying  conda install krb5 into R studio and trying to run it. I revieved the fallowing error messages

Error: unexpected symbol in "conda install"
Error: unexpected symbol in "conda install.packages"

I have macOS Sierra 10.12.4, Anaconda Navigator 1.6.2, and R Studio version 3.4.1

Ultimately I am trying to install caTools but I get the faloowing error message

caTools’ is not available (for R version 3.4.1)

All my packages are up to date.

**Comment by slinnarsson** [comment]
@StealthNameless you need to run the conda comman in your terminal, not inside R studio.

**Comment by jrumbut** [comment]
@slinnarsson You are a hero.

**Comment by nickyongzhang** [comment]
@slinnarsson Thank you so much. You make my day.

**Comment by WallyFAI** [comment]
Awesome @slinnarsson, really saved me. Thank you!

**Comment by lambdamoses** [comment]
Thank you, @slinnarsson, it solved the problem

**Comment by zackkatz** [comment]
Thank you @slinnarsson, worked for me as well on a Mac

**Comment by doronator** [comment]
black magic, but it works!

**Comment by codykingham** [comment]
When running `conda install libssh2`, Conda wants to downgrade my Python package to 3.5.4. Which I don't want.

**Comment by mingwandroid** [comment]
This is a bug in conda.

Please use `conda install libssh2 python=3.6`

**Comment by codykingham** [comment]
@mingwandroid It works. You're the wind in my sails today. ⛵️

**Comment by mingwandroid** [comment]
This is fixed properly now. Make sure you are using the latest `conda` then `conda update r-essentials rstudio`.

**Comment by LilySnow** [comment]
@slinnarsson Thanks! Solved for me!

**Comment by fengwei-li** [comment]
the above suggestions can not solve my problem.
however, I fix it through
`cd ~/anaconda3/lib`(your anaconda3 lib PATH) 
`rstudio`

**Comment by thesuperzapper** [comment]
If you are using RStudio Server, you might need to start it with the `--rsession-ld-library-path=/opt/conda/lib` command line argument.

This is because RStudio ignores the servers `LD_LIBRARY_PATH` when starting R sessions.

**Comment by avishai987** [comment]
Adding mypath/miniconda/envs/my_env/lib to LD_LIBRARY_PATH, in addition to the existing mypath/miniconda/envs/my_env/lib/R/lib solved the problem
