### ISSUE TITLE
Recipes for non-proprietary things are not in conda-recipes repository

### ISSUE THREAD

**Issue by dan-blanchard** [ContinuumIO/anaconda-issues#45]
I already posted this on the conda-recipes repository 
(ContinuumIO/conda-recipes#39), but I guess it's really more of an Anaconda issue. Anyway, it'd be really nice if you guys posted the recipes you've created for Anaconda for things that you don't consider proprietary—I completely understand you not wanting to post the recipes for anything you have accelerated versions of—because they would be great examples, and it would allow people to tweak them more easily.

For example, there are recipes for `requests` and `beautiful-soup` in `conda-recipes`, but they are likely different from what you've got.

**Comment by tswicegood** [comment]
@csoja just want to make sure this is on your radar.  Might be a good task for anyone looking to cut their teeth on building packages and getting things setup in binstar-build at the same time.

**Comment by moorepants** [comment]
+1

**Comment by csoja** [comment]
The conda recipes Continuum uses for the currently supported packages in the Anaconda Distribution are currently available at https://github.com/ContinuumIO/anaconda-recipes and will be moving to https://github.com/AnacondaRecipes   The long delay for this effort was because the majority of our packages used a legacy recipe and build system other than conda recipes & conda-build and it took time to convert everything over.

**Comment by pelson** [comment]
Awesome. Thanks @csoja. Out of interest, did you consider putting a suffix/prefix on the repo names in https://github.com/AnacondaRecipes? Without one it makes it hard to see what is the actual code repo vs the recipe repo (hence the `-feedstock` in conda-forge).

Anyway, thanks again for making this public. 👍

**Comment by csoja** [comment]
@pelson we did consider it, but decided against it as the new repo only has recipes.  (At least that is what I remember, @msarahan may remember better.)

**Comment by msarahan** [comment]
I'd have to ask @ovillellas.  @csoja, although this repo contains only recipes, there can still be confusion when someone clones any given one of these repositories.  @pelson's suggestion is to clarify the case when someone might have a folder that contains clones of both the original source repo, and a recipe repo for that source.

**Comment by msarahan** [comment]
@rrenfrow86, @csoja told me I should ping you on this.  We agree that we should add *something* to our repo names to make this clarification.  Crystal doesn't like feedstock, and recommended "recipe."  I'm fine with that.  I'm pretty sure the actual name doesn't matter, as we can have URLs and links to translate amongst conda-forge's nomenclature and ours.

**Comment by pelson** [comment]
Completely agree that feedstock would be a bad choice. Thanks for taking the suggestion on board. 👍
