### ISSUE TITLE
Pytables from pandas missing cython dependency

### ISSUE THREAD

**Issue by balarsen** [ContinuumIO/anaconda-issues#451]
With pandas and h5py and pytables installed the to_hdf() is broken with a missing cython dependency (see below).
pandas                       \*  0.16.2               np19py34_0  defaults
pytables                          \*  3.2.1.1              np19py34_0  defaults
h5py                           \*  2.5.0                np19py34_3  defaults
python                           \*  3.4.3                         0  defaults

The solution is to install cython and then it works fine
cython                           \*  0.23.2                   py34_0  defaults

So I believe that pytables needs to install cython as a dependency. (or pandas/pytables needs a much better error message)
## In [50]: data.to_hdf('all_data_pandas.h5', '')

ImportError                               Traceback (most recent call last)
/Users/blarsen/anaconda/envs/python3/lib/python3.4/site-packages/pandas/io/pytables.py in **init**(self, path, mode, complevel, complib, fletcher32, **kwargs)
    387         try:
--> 388             import tables
    389         except ImportError as ex:  # pragma: no cover

ImportError: No module named 'tables'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-50-3af8565fb0f2> in <module>()
----> 1 data.to_hdf('all_data_pandas.h5', '')

/Users/blarsen/anaconda/envs/python3/lib/python3.4/site-packages/pandas/core/generic.py in to_hdf(self, path_or_buf, key, *_kwargs)
    916
    917         from pandas.io import pytables
--> 918         return pytables.to_hdf(path_or_buf, key, self, *_kwargs)
    919
    920     def to_msgpack(self, path_or_buf=None, **kwargs):

/Users/blarsen/anaconda/envs/python3/lib/python3.4/site-packages/pandas/io/pytables.py in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, **kwargs)
    266     if isinstance(path_or_buf, string_types):
    267         with HDFStore(path_or_buf, mode=mode, complevel=complevel,
--> 268                        complib=complib) as store:
    269             f(store)
    270     else:

/Users/blarsen/anaconda/envs/python3/lib/python3.4/site-packages/pandas/io/pytables.py in **init**(self, path, mode, complevel, complib, fletcher32, **kwargs)
    388             import tables
    389         except ImportError as ex:  # pragma: no cover
--> 390             raise ImportError('HDFStore requires PyTables, "{ex}" problem importing'.format(ex=str(ex)))
    391
    392         if complib not in (None, 'blosc', 'bzip2', 'lzo', 'zlib'):

ImportError: HDFStore requires PyTables, "No module named 'tables'" problem importing

<<snip some debugging testing>>

In [52]: data.to_hdf('all_data_pandas.h5', 'data')
In [53]:

**Comment by gplssm** [comment]
I can reproduce this error using pandas 0.18.1/0.19 in a virtualenv. Is someone taking care about?

**Comment by nehaljwani** [comment]
Cython is a build time dependency for PyTables, not a runtime dependency. 

Also, `Python 3.4` is no longer supported.

**Comment by nehaljwani** [comment]
See https://github.com/ContinuumIO/anaconda-recipes/blob/master/pytables/meta.yaml#L24
