### ISSUE TITLE
Unable to update Anaconda in ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by heeramani** [ContinuumIO/anaconda-issues#4520]
`conda update --prefix /home/heeramani/anaconda2 anaconda`
This command this following error.
`Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/linux-64/`

Running `conda info`
give following information
            `Current conda install:

             platform : linux-64
             conda version : 2.2.5
             root environment : /home/heeramani/anaconda2  (writable)
             default environment : /home/heeramani/anaconda2
             envs directories : /home/heeramani/anaconda2/envs
             package cache : /home/heeramani/anaconda2/pkgs
             channel URLs : conda-canary/linux-64/
             http://repo.continuum.io/pkgs/free/linux-64/
             http://repo.continuum.io/pkgs/pro/linux-64/
             config file : /home/heeramani/.condarc
             is foreign system : False

**Comment by ccordoba12** [comment]
You simply need to run

    conda update anaconda

**Comment by heeramani** [comment]
@ccordoba12 
I have also run run this command
`conda update anaconda`
Giving following error
`Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/linux-64/`
Mainly I have to install PIL anaconda package. For that i wanted to just update it. But that neither this command work nor command for installing PIL given on [https://anaconda.org/anaconda/pil](url) work.
This command give following error:
`conda install -c anaconda pil`
`Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/linux-64/`

**Comment by ccordoba12** [comment]
It seems you don't have access to that address because it's blocked.

Are you running behind a proxy?

**Comment by heeramani** [comment]
Yes I am behind proxy. What are some alternative methods

**Comment by ccordoba12** [comment]
You need to set your proxy. Look in our documentation how to do that.

**Comment by heeramani** [comment]
Documentation of Anaconda ?

**Comment by ccordoba12** [comment]
https://docs.continuum.io/
