### ISSUE TITLE
wheel-0.26 is broken

### ISSUE THREAD

**Issue by mwcraig** [ContinuumIO/anaconda-issues#453]
As originally noticed by @embray in astropy/astropy#4180 there is a problem with `wheel==0.26`. 

Reproducing the failure is straightforward:

```bash
$ conda create -n bad_wheel python=2.7 wheel
$ source activate bad_wheel
$ pip install suds-jurko # Nothing special about this package, except that it has no wheel on pypi
Collecting suds-jurko
  Using cached suds-jurko-0.6.tar.bz2
Building wheels for collected packages: suds-jurko
  Running setup.py bdist_wheel for suds-jurko
  Complete output from command /Users/mcraig/anaconda/envs/bad_wheel/bin/python -c "import setuptools;__file__='/private/var/folders/j2/kwz9qs3d54j3p5mv5m9m5mz44_blx6/T/pip-build-gIiQ_0/suds-jurko/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/j2/kwz9qs3d54j3p5mv5m9m5mz44_blx6/T/tmp3mgoR9pip-wheel-:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for suds-jurko
Failed to build suds-jurko
Installing collected packages: suds-jurko
  Running setup.py install for suds-jurko
Successfully installed suds-jurko-0.6

$ conda list
# packages in environment at /Users/mcraig/anaconda/envs/bad_wheel:
#
openssl                   1.0.1k                        1
pip                       7.1.2                    py27_0
python                    2.7.10                        1
readline                  6.2                           2
setuptools                18.1                     py27_0
sqlite                    3.8.4.1                       1
suds-jurko                0.6                       <pip>
tk                        8.5.18                        0
wheel                     0.26.0                   py27_0
zlib                      1.2.8                         0
```

@embray found the underlying problem (from the issue linked to above):

> The wheel package for conda is broken as of wheel==0.26...It's missing important metadata--namely the appropriate entry_points.txt, which is required for setuptools to be able to discover the bdist_wheel command.

**Comment by ccordoba12** [comment]
@ilanschnell?

**Comment by ilanschnell** [comment]
Thanks for reporting this issue.  I think I understand why the new wheel package is broken.  The conda package for `wheel 0.24.0` had an `.egg-info` directory, whereas the conda package for `wheel 0.26.0` only has an `.egg-info` file.

**Comment by ilanschnell** [comment]
Yes, we switched from using our internal build system to conda-build, which didn't retain the egg-info directory.  Using this fix to conda-build: https://github.com/conda/conda-build/commit/5860ff539c95cd3e92676933e50fe98615d67d79
I was able to fix wheel packages that work again.  They will be available for all platforms tomorrow.

**Comment by ilanschnell** [comment]
I uploaded the new wheel 0.26.0 packages.

**Comment by mwcraig** [comment]
Thanks for the quick fix, @ilanschnell!

**Comment by embray** [comment]
Thanks!

**Comment by fmailhot** [comment]
Why did the version number not change?

**Comment by ilanschnell** [comment]
Because, I only rebuild the current version, by increasing the build number.

**Comment by ccordoba12** [comment]
The build number changed, which is all that was needed in this case.
