### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rieuwertblok** [ContinuumIO/anaconda-issues#4568]
## Main error
Application <b>qtconsole</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/envs/ML_WU/bin/jupyter-qtconsole", line 4, in <module>
    import qtconsole.qtconsoleapp
  File "/anaconda/envs/ML_WU/lib/python2.7/site-packages/qtconsole/qtconsoleapp.py", line 64, in <module>
    from qtconsole.jupyter_widget import JupyterWidget
  File "/anaconda/envs/ML_WU/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 19, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "/anaconda/envs/ML_WU/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/anaconda/envs/ML_WU/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/anaconda/envs/ML_WU/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/anaconda/envs/ML_WU/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/anaconda/envs/ML_WU/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment]
@rieuwertblok what is the output of

`conda list` and `conda info`

**Comment by rieuwertblok** [comment]
rblok$ conda list
# packages in environment at /anaconda:
#
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
_license                  1.1                      py27_1  
alabaster                 0.7.10                   py27_0  
anaconda-client           1.6.3                    py27_0  
anaconda                  custom                   py27_0  
anaconda-navigator        1.6.2                    py27_0  
anaconda-project          0.6.0                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
asn1crypto                0.22.0                   py27_0  
astroid                   1.4.9                    py27_0  
astropy                   1.3.2               np112py27_0  
babel                     2.4.0                    py27_0  
backports                 1.0                      py27_0  
backports-abc             0.5                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.5                      py27_0  
beautifulsoup4            4.6.0                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bleach                    1.5.0                    py27_0  
bokeh                     0.12.5                   py27_1  
boto                      2.46.1                   py27_0  
bottleneck                1.2.1               np112py27_0  
cdecimal                  2.3                      py27_2  
cffi                      1.10.0                   py27_0  
chardet                   3.0.3                    py27_0  
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.9                    py27_0  
conda                     4.0.8                    py27_0  
conda-env                 2.4.5                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.5                    py27_0  
cryptography              1.8.1                    py27_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask                      0.14.3                   py27_1  
datashape                 0.5.4                    py27_0  
decorator                 4.0.11                   py27_0  
distributed               1.16.3                   py27_0  
docutils                  0.13.1                   py27_0  
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
flask                     0.12.2                   py27_0  
flask-cors                3.0.2                    py27_0  
freetype                  2.5.5                         2  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.1.1                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.2.1                    py27_0  
greenlet                  0.4.12                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.7.0               np112py27_0  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
html5lib                  0.999                    py27_0  
icu                       54.1                          0  
idna                      2.5                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.6.1                    py27_0  
ipython                   5.3.0                    py27_0  
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py27_0  
ipywidgets                6.0.0                    py27_0  
isort                     4.2.5                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.10.2                   py27_2  
jinja2                    2.9.6                    py27_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter-client            5.0.1                     <pip>
jupyter-console           5.1.0                     <pip>
jupyter-core              4.3.0                     <pip>
jupyter_client            5.0.1                    py27_0  
jupyter_console           5.1.0                    py27_0  
jupyter_core              4.3.0                    py27_0  
lazy-object-proxy         1.2.2                    py27_0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.7.3                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                2.0.2               np112py27_0  
mistune                   0.7.4                    py27_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_3  
mpmath                    0.19                     py27_1  
msgpack-python            0.4.8                    py27_0  
multipledispatch          0.4.9                    py27_0  
navigator-updater         0.1.0                    py27_0  
nbconvert                 5.1.1                    py27_0  
nbformat                  4.3.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.3                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  5.0.0                    py27_0  
numba                     0.33.0              np112py27_0  
numexpr                   2.6.2               np112py27_0  
numpy                     1.12.1                   py27_0  
numpydoc                  0.6.0                    py27_0  
odo                       0.5.0                    py27_1  
olefile                   0.44                     py27_0  
openpyxl                  2.4.7                    py27_0  
openssl                   1.0.2l                        0  
packaging                 16.8                     py27_0  
pandas                    0.20.1              np112py27_0  
pandocfilters             1.4.1                    py27_0  
partd                     0.3.8                    py27_0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.2.1                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    4.1.1                    py27_0  
pip                       9.0.1                    py27_1  
ply                       3.10                     py27_0  
prompt-toolkit            1.0.14                    <pip>
prompt_toolkit            1.0.14                   py27_0  
psutil                    5.2.2                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.33                   py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.2                    py27_0  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_6  
pycurl                    7.43.0                   py27_2  
pyflakes                  1.5.0                    py27_0  
pygments                  2.2.0                    py27_0  
pylint                    1.6.4                    py27_1  
pyodbc                    4.0.16                   py27_0  
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_1  
pytables                  3.3.0               np112py27_0  
pytest                    3.0.7                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
python.app                1.2                      py27_4  
pytz                      2017.2                   py27_0  
pywavelets                0.5.2               np112py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         2  
qtawesome                 0.4.4                    py27_0  
qtconsole                 4.3.0                    py27_0  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
requests                  2.11.1                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
scandir                   1.5                      py27_0  
scikit-image              0.13.0              np112py27_0  
scikit-learn              0.18.1              np112py27_1  
scipy                     0.19.0              np112py27_0  
seaborn                   0.7.1                    py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sortedcollections         0.5.3                    py27_0  
sortedcontainers          1.5.7                    py27_0  
sphinx                    1.5.6                    py27_0  
spyder                    3.1.4                    py27_0  
sqlalchemy                1.1.9                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.8.0               np112py27_0  
subprocess32              3.2.7                    py27_0  
sympy                     1.0                      py27_0  
tables                    3.3.0                     <pip>
tblib                     1.3.2                    py27_0  
terminado                 0.6                      py27_0  
testpath                  0.3                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.5.1                    py27_0  
traitlets                 4.3.2                    py27_0  
unicodecsv                0.14.1                   py27_0  
unixodbc                  2.3.4                         0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.12.2                   py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        2.0.0                    py27_0  
wrapt                     1.10.10                  py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
xlwings                   0.10.4                   py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zict                      0.1.2                    py27_0  
zlib                      1.2.8                         3  
RaBl:~ rblok$ 


I also tried 

$conda info
but there is no response for a long long time so I killed it. Then, I looked at the processes.
RaBl:~ rblok$ ps -fu rblok | grep anaconda
  502   684     1   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   685   684   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   686   685   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   687   686   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   688   687   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   689   688   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   690   689   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   691   690   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   692   691   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   693   692   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   694   693   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   695   694   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   696   695   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   697   696   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   698   697   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   699   698   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   701   699   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   702   701   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   703   702   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   704   703   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   705   704   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   706   705   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   707   706   0  7:17am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   708   707   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   709   708   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   710   709   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   711   710   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   712   711   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   713   712   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   714   713   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   715   714   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   716   715   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   717   716   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   718   717   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   719   718   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   720   719   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   721   720   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   722   721   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   723   722   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   725   723   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   726   725   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   727   726   0  7:17am ??         0:00.33 /anaconda/bin/python /anaconda/bin/conda info --json
  502   728   727   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   729   728   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   730   729   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   731   730   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   732   731   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   733   732   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   734   733   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   735   734   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   736   735   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   737   736   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   738   737   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   739   738   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   740   739   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   742   740   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   743   742   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   744   743   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   745   744   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   746   745   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   747   746   0  7:17am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   748   747   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   749   748   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   750   749   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   751   750   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   752   751   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   753   752   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   754   753   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   755   754   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   756   755   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   757   756   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   758   757   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   759   758   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   760   759   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   761   760   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   762   761   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   763   762   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   764   763   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   765   764   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   766   765   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   767   766   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   768   767   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   769   768   0  7:17am ??         0:00.35 /anaconda/bin/python /anaconda/bin/conda info --json
  502   770   769   0  7:17am ??         0:00.34 /anaconda/bin/python /anaconda/bin/conda info --json
  502   771   770   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   773   771   0  7:17am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   774     1   0  7:17am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   775   773   0  7:17am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   776   774   0  7:17am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   777   775   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   778   776   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   779   777   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   780   778   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   781   779   0  7:17am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   782   780   0  7:17am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   783   781   0  7:17am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   784   782   0  7:17am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   785   783   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   786   784   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   787   785   0  7:18am ??         0:00.41 /anaconda/bin/python /anaconda/bin/conda info --json
  502   788   786   0  7:18am ??         0:00.41 /anaconda/bin/python /anaconda/bin/conda info --json
  502   789   787   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   790   788   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   791   789   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   792   790   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   793   791   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   794   792   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   795   793   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   796   794   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   797   795   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   798   796   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   799   797   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   800   798   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   801   799   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   802   800   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   803   801   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   804   802   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   805   803   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   806   804   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   807   805   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   808   806   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   809   807   0  7:18am ??         0:00.39 /anaconda/bin/python /anaconda/bin/conda info --json
  502   810   808   0  7:18am ??         0:00.39 /anaconda/bin/python /anaconda/bin/conda info --json
  502   813   809   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   814   810   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   815   813   0  7:18am ??         0:00.36 /anaconda/bin/python /anaconda/bin/conda info --json
  502   816   814   0  7:18am ??         0:00.42 /anaconda/bin/python /anaconda/bin/conda info --json
  502   817   815   0  7:18am ??         0:00.43 /anaconda/bin/python /anaconda/bin/conda info --json
  502   818   816   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   819   817   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   820   818   0  7:18am ??         0:00.39 /anaconda/bin/python /anaconda/bin/conda info --json
  502   821   819   0  7:18am ??         0:00.40 /anaconda/bin/python /anaconda/bin/conda info --json
  502   822   820   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   823   821   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   824   822   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   825   823   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   826   824   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   827   825   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   828   826   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   829   827   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   830   828   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   831   829   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   832   830   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   833   831   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   834   832   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   835   833   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   836   834   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   837   835   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   838   836   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   839   837   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   840   838   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   841   839   0  7:18am ??         0:00.39 /anaconda/bin/python /anaconda/bin/conda info --json
  502   842   840   0  7:18am ??         0:00.43 /anaconda/bin/python /anaconda/bin/conda info --json
  502   843   841   0  7:18am ??         0:00.41 /anaconda/bin/python /anaconda/bin/conda info --json
  502   844   842   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   845   843   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   846   844   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   847   845   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   848   846   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   849   847   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   850   848   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   851   849   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   852   850   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   853   851   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   854   852   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   855   853   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   856   854   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   857   855   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   858   856   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   859   857   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   860   858   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   861   859   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   862   860   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502   863   861   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   864   862   0  7:18am ??         0:00.39 /anaconda/bin/python /anaconda/bin/conda info --json
  502   865   863   0  7:18am ??         0:00.38 /anaconda/bin/python /anaconda/bin/conda info --json
  502   866   864   0  7:18am ??         0:00.37 /anaconda/bin/python /anaconda/bin/conda info --json
  502


And it keeps going for another couple dozen such lines.

I tried

**Comment by goanpeca** [comment]
@rieuwertblok you may have an invalid installation. Probably the best option is to reinstall.

**Comment by rieuwertblok** [comment]
I did a clean install and now the anaconda seems to work and it also doesn't leave me with 400 unfinished " ? "processes.

In any case thank you for looking into this. I still don't know what happened, though.

Brst,

Rieuwert

R.J. Blok
Dept. Mathematics and Statistics
Bowling Green State University
Bowling Green, OH 43402, U.S.A.
