### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Larquebus** [ContinuumIO/anaconda-issues#4579]
## Main error
<b>Unable to move <i>test</i></b><br><br>Error message:<br>[Errno 13] Permission denied: 'C:\\Users\\Chris Larabee\\AnacondaProjects\\test'
## Traceback
```

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@Larquebus seems you installed for all users? We recommend you install for the current user only. Also installing in a path that contains spaces is not fully supported. When reinstalling anaconda make sure to install it in a path that contains no spaces.

>'C:\Users\Chris Larabee\AnacondaProjects\test'

You can try to remove that folder manually and try again after reinstalling if the problem persists.

Cheers
