### ISSUE TITLE
Pytables 3.2, python 3.4 under windows x64

### ISSUE THREAD

**Issue by tritemio** [ContinuumIO/anaconda-issues#458]
This issue is to bring attention to what seems an Anaconda specific bug in the latest pytables 3.2 package under windows 7 x64 and python 3.4.

https://github.com/PyTables/PyTables/issues/492

@cgohlke cannot reproduce the crash with self-built binaries. Strangely, the crash log linked in the previous issue, contains the gcc string, but the package should be built with MS compiler.

Is there a public recipe for the pytables package in anaconda? If yes I may be able to test-build the package.

**Comment by ccordoba12** [comment]
Pinging @groutr about this one.

**Comment by filmor** [comment]
This seems to be a regression in the very latest package, I've the case where code started failing for a user when going from pytables 3.2.1 to 3.2.2.

**Comment by groutr** [comment]
I can make the pytables recipe available.  It will take a day or two though.
