### ISSUE TITLE
Linking to Anaconda's libnetcdf causes an ld error under MacOS X

### ISSUE THREAD

**Issue by khinsen** [ContinuumIO/anaconda-issues#46]
I am trying to build ScientificPython using the recipe at

    https://github.com/khinsen/conda-recipes/tree/scientificpython/scientificpython

Under MacOS X (tested with 10.7 and 10.9, with the latest Xcode and a freshly updated Anaconds), this ends with an ld error:

    gcc -bundle -undefined dynamic_lookup -L/Users/hinsen/anaconda/envs/_build/lib -arch x86_64 -arch x86_64 -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/Src/Scientific_netcdf.o -L/Users/hinsen/anaconda/envs/_build/lib -L/Users/hinsen/anaconda/envs/_build/lib -lnetcdf -o build/lib.macosx-10.5-x86_64-2.7/Scientific/darwin/Scientific_netcdf.so
    ld: malformed dylb, load command #4 is outside size of load commands in /Users/hinsen/anaconda/envs/_build/lib/libnetcdf.dylib file '/Users/hinsen/anaconda/envs/_build/lib/libnetcdf.dylib' for architecture x86_64

**Comment by groutr** [comment]
This recipe builds fine for me. Closing.
