### ISSUE TITLE
Issue with Anaconda Launcher

### ISSUE THREAD

**Issue by kengilbert** [ContinuumIO/anaconda-issues#460]
We've encountered a problem in Anaconda Launcher that we can't recover from

**Comment by goanpeca** [comment]
@kengilbert can you provide me with some information?

**Comment by kengilbert** [comment]
After launcher is opened, nothing works. Thanks for you help. - Ken Gilbert
---

## Uncaught Exception

```
Error: spawn conda ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)
```

## Platform Information

* Operating System: darwin
* Conda Version: 3.18.1
* Conda Platform: osx-64

```json
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64/",
    "https://repo.continuum.io/pkgs/free/noarch/",
    "https://repo.continuum.io/pkgs/pro/osx-64/",
    "https://repo.continuum.io/pkgs/pro/noarch/"
  ],
  "conda_build_version": "not installed",
  "conda_version": "3.18.1",
  "default_prefix": "/Users/kgilbert/anaconda",
  "envs": [],
  "envs_dirs": [
    "/Users/kgilbert/anaconda/envs"
  ],
  "is_foreign": false,
  "pkgs_dirs": [
    "/Users/kgilbert/anaconda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "2.7.10.final.0",
  "rc_path": null,
  "requests_version": "2.7.0",
  "root_prefix": "/Users/kgilbert/anaconda",
  "root_writable": true,
  "sys_rc_path": "/Users/kgilbert/anaconda/.condarc",
  "user_rc_path": "/Users/kgilbert/.condarc",
  "condaBuildVersion": "not installed",
  "condaVersion": "3.18.1",
  "defaultPrefix": "/Users/kgilbert/anaconda",
  "envsDirs": [
    "/Users/kgilbert/anaconda/envs"
  ],
  "isForeign": false,
  "pkgsDirs": [
    "/Users/kgilbert/anaconda/pkgs"
  ],
  "pythonVersion": "2.7.10.final.0",
  "rcPath": null,
  "requestsVersion": "2.7.0",
  "rootPrefix": "/Users/kgilbert/anaconda",
  "rootWritable": true,
  "sysRcPath": "/Users/kgilbert/anaconda/.condarc",
  "userRcPath": "/Users/kgilbert/.condarc"
}
```

Please remove this line, scroll back to the top, and follow the directions at the top of this report.
On Oct 6, 2015, at 1:44 PM, Gonzalo Peña-Castellanos <notifications@github.com<mailto:notifications@github.com>> wrote:


@kengilbert<https://github.com/kengilbert> can you provide me with some information?

**Comment by goanpeca** [comment]
@kengilbert we wil look into it, thanks for the information

**Comment by goanpeca** [comment]
In the meantime can you use the previous launcher version?

**Comment by kengilbert** [comment]
Dear Gonzalo, no the previous version stopped working after the upgrade. - Ken
On Oct 6, 2015, at 5:30 PM, Gonzalo Peña-Castellanos <notifications@github.com<mailto:notifications@github.com>> wrote:


In the meantime can you use the previous launcher version?

**Comment by goanpeca** [comment]
Can you try in a terminal?

```bash
conda remove launcher
conda install launcher=1.0
```

What do you get?

**Comment by kengilbert** [comment]
Gonzalo, it works, but takes a long time to start up. I think that is why I thought it was not working after the upgrade. - Ken


On Oct 6, 2015, at 9:35 PM, Gonzalo Peña-Castellanos
 <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Can you try in a terminal?

conda remove launcher
conda install launcher=1.0

What do you get?

**Comment by goanpeca** [comment]
Hi Kenneth

Good to hear. Is this long time to start the same every time or reduced after the first time?

**Comment by kengilbert** [comment]
Gonzalo, the start up time is about the same each time. Mainly the time is spent on the "Loading apps list…" part. I think I had gotten used to Spyder starting up more quickly when the Launcher had less to load. What have you learned from knowing the previous version of the Launcher works?

Ken


On Oct 6, 2015, at 10:33 PM, Gonzalo Peña-Castellanos
 <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Hi Kenneth

Good to hear. Is this long time to start the same every time or reduced after the first time?

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
