### ISSUE TITLE
create a new env with full anaconda?

### ISSUE THREAD

**Issue by MaxNoe** [ContinuumIO/anaconda-issues#463]
Is it possible to create a new environment with all the standard packages, that would be there if 
conda was newly installed with **that  specific python version**?

I would like something like this:

```
$ conda create --full -n py35 python=3.5
```

**Comment by groutr** [comment]
Just install the anaconda package.
conda create -n new_anaconda anaconda

Note that the package versions anaconda are fixed.  Installing the 
anaconda package will not download the latest versions of the packages.

Ryan

**Comment by MaxNoe** [comment]
Yes, i know. That's why I opened this issue.

I would like a fast way to get the standard packages for a certain python version!

**Comment by csoja** [comment]
There has not yet been a release of the Anaconda meta-package with Python 3.5 (it is coming soon).  You can get the standard Anaconda packages for a certain python version as long as there is a corresponding Anaconda meta-package.  
So-
conda create -n ana3 anaconda python=3.4 
will get you an environment with all the standard Anaconda Python 3.4 packages.  

but if you attempt the same right now with python=3.5 you will get "Error: Unsatisfiable package specifications." Once Anaconda v2.4 has been released, you will be able to easily create an Anaconda Python 3.5 environment.

**Comment by markasstrick** [comment]
Check out the anaconda documentation for "building identical conda environment" [here](http://conda.pydata.org/docs/using/envs.html). Basically you use 
`conda list --explicit > spec-file.txt`
to create a file with a list of all the packages in your ananconda install. Then create a new environment with the python version you like. It's easy to create a new environment with pycharm if you that IDE. Then you can use
`conda install --name MyEnvironment --file spec-file.txt` 
to install all the packages to the new environment.

**Comment by notsmartenough** [comment]
I installed CUDA 8 from nvidia website and added the environment variables, how do I make anaconda recognise this? I don't want to download this again and I can't see cuda in `conda list`
