### ISSUE TITLE
Include patchelf with Anaconda installer

### ISSUE THREAD

**Issue by bombaci-vsc** [ContinuumIO/anaconda-issues#464]
There's a disconnect between the included conda-build package and installing conda-build manually.

On Linux, the conda-build package has a dependency on patchelf, and running `conda install conda-build` installs patchelf as a dependency.  What's strange is the Anaconda Installer includes conda-build, but somehow doesn't include the patchelf dependency.

This is confusing because to use the already installed conda-build you must first install conda-build.

**Comment by nehaljwani** [comment]
Newer versions of Anaconda installers do not ship with `conda-build`
```bash
(root) [nwani@centos6x64 ~]$ bash Anaconda2-4.3.1-Linux-x86_64.sh -bp anaconda2
...
(root) [nwani@centos6x64 ~]$ source anaconda2/bin/activate
(root) [nwani@centos6x64 ~]$ conda list | grep conda
# packages in environment at /home/nwani/anaconda2:
anaconda                  4.3.1               np111py27_0
anaconda-client           1.6.0                    py27_0
anaconda-navigator        1.5.0                    py27_0
anaconda-project          0.4.1                    py27_0
conda                     4.3.14                   py27_0
conda-env                 2.6.0                         0
```
