### ISSUE TITLE
h5py rebuild for numpy 1.10.0

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#465]
It appears that `h5py` is pinned to the `numpy` version it was built with. As a result, it is not possible to use `numpy` 1.10.0 without a rebuild of `h5py`.

**Comment by ilanschnell** [comment]
Not all packages are rebuild against numpy 1.10 yet.  The Anaconda 2.4 (end of October) will feature numpy 1.10, and then we'll have everything consistent.

**Comment by jakirkham** [comment]
Ok, sure. Sounds reasonable. Thanks @ilanschnell.
