### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tchakravarty** [ContinuumIO/anaconda-issues#4684]
## Main error
The following errors occurred:
## Traceback
```
CondaValueError: pip returned an error.
```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@tchakravarty what were you trying to do ?

**Comment by tchakravarty** [comment]
Import a requirements.txt in Anaconda Navigator to set up a new
environment. Attached.
  keras_pckg.txt
<https://drive.google.com/file/d/0B7R7Ftd5dF0gdFdNWlBySDg4dkVpLUJJbGFVTmc0NWthRHRj/view?usp=drivesdk>

T

**Comment by goanpeca** [comment]
@tchakravarty the environment was created for OSX not for windows and these environments are not cross-platform, we are working on that.

<img width="560" alt="screen shot 2017-08-28 at 09 34 11" src="https://user-images.githubusercontent.com/3627835/29775705-2b23c00c-8bd4-11e7-8ae0-cfc9f2df660c.png">

**Comment by tchakravarty** [comment]
Sure, and I took that line out. Sent from phone, hence attached original
received text file.

T

**Comment by goanpeca** [comment]
@tchakravarty is not about taking the line out or not. The environment was created on a different OSystem and wont work on a different one.

**Comment by tchakravarty** [comment]
If I am not mistaken pip freeze is platform agnostic?

T
