### ISSUE TITLE
Revert to default python on Mac after installing Anaconda

### ISSUE THREAD

**Issue by incorelabs** [ContinuumIO/anaconda-issues#4686]
I installed Anaconda today and did not know that it would change the default version of python i.e. python2 and point it to a version of python inside it's bin directory which is Python 3.

I still do want to use Anaconda but I still want to use python2 when I type python.

How do I fix this? Plus, why does it change it?

**Comment by goanpeca** [comment]
@incorelabs you can create conda environments with conda and anaconda, so the default python version on your default environment (called root) has the python version of the Anaconda you installed (2 or 3) if you need a python2/3 version different from root you can create an environment for that.

```
$ conda create --name py2 python=2
$ source activate py2
$ python
```
or 

```
$ conda create --name py35 python=3.5
$ source activate py35
$ python
```

or

```
$ conda create --name py36 python=3.6
$ source activate py36
$ python
```

**Comment by mingwandroid** [comment]
I would like to add, if you stick to doing it this way and then need to get back to using your system python for whatever reason, you can do `source deactivate`.
