### ISSUE TITLE
Segmentation fault during import

### ISSUE THREAD

**Issue by kyleabeauchamp** [ContinuumIO/anaconda-issues#47]
So this code causes a segmentation fault on my machine:

```
import simtk.openmm as mm
import scipy.optimize.minpack2
```

Interestingly, if I import in the _opposite_ order there is no segfault.

I'm not sure what the issue is, although I presume there's some funny incompatibility going on with my SO files.  

Here are some system details:

Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz

```
-bash-4.1$ uname -a
Linux mskcc-ln1.local 2.6.32-279.14.1.el6.x86_64 #1 SMP Tue Nov 6 23:43:09 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.1$ cat /etc/redhat-release 
CentOS release 6.4 (Final)

-bash-4.1$ python --version
Python 2.7.5 :: Anaconda 1.8.0 (64-bit)

-bash-4.1$ g++ --version
g++ (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

Anyone have any ideas here?

Here is a link to my GDB backtrace:

https://gist.github.com/kyleabeauchamp/b5bcecbd62a49f9a92a2

So I've only seen this segfault happen on our centos cluster.

PS: this issue is also posted here: https://github.com/SimTk/openmm/issues/250

FYI, OpenMM is a swig-wrapped C++ library.

**Comment by goanpeca** [comment]
Stale issue. Closing
