### ISSUE TITLE
Add `setuptools_scm` to anaconda package repository?

### ISSUE THREAD

**Issue by rmcgibbo** [ContinuumIO/anaconda-issues#471]
`setuptools_scm` is a PyPA project that extends setuptools. It would be useful to have available to `conda install`. https://pypi.python.org/pypi/setuptools_scm/1.8.0

**Comment by msarahan** [comment]
Looks good. Have you used versioneer? Much the same as this. I can package
this and put it in conda-recipes. I don't really see this becoming a core
part of conda install, though. This is really more of a per-project config
thing.  Did you mean just to request that this be available as a conda
package?

**Comment by rmcgibbo** [comment]
Yeah, I just meant that it would be nice to be able to install through conda without building a recipe.

**Comment by rmcgibbo** [comment]
> Did you mean just to request that this be available as a conda
package?

Exactly.

**Comment by rmcgibbo** [comment]
This is done now.
