### ISSUE TITLE
Should Anaconda's Python be looking at user site packages?

### ISSUE THREAD

**Issue by gmarkall** [ContinuumIO/anaconda-issues#473]
It seems that the Anaconda Python package's site.py has `ENABLE_USER_SITE` set to `None`, which allows user site packages (e.g. those in `~/.local/...`) to end up in `sys.path`. It looks to me like this is fairly prone to breaking the isolation of conda environments, especially since user site packages can end up with paths of system Python modules in `.pth` files in there.

There are a few issues that look like they might be caused by this:

https://github.com/ContinuumIO/anaconda-issues/issues/404
https://github.com/ContinuumIO/anaconda-issues/issues/394
https://github.com/conda/conda/issues/1693

Is there any reason for Anaconda's Python to be looking at user site packages? Can we stop it doing that?

**Comment by ilanschnell** [comment]
I'm glad you figured out what is going on.  It will require more discussion to change Python's default behavior.
