### ISSUE TITLE
Anaconda Navigator quit unexpectedly - KeyError: 'uri', Abort trap: 6

### ISSUE THREAD

**Issue by saidamir** [ContinuumIO/anaconda-issues#4747]
Can you please help? Need to use Navigator, thank you!
XYZ-MacBook-Pro:~ xyz$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/xyz/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6

**Comment by goanpeca** [comment]
@saidamir what version of navigator are you using?

Please paste the output of `$ conda info` and `$ conda list`

**Comment by saidamir** [comment]
I am not sure what version I am using - how can I find it out? It opens for one second and closes right then.
xyz-MacBook-Pro:~ azizmamatov$ conda
usage: conda [-h] [-V] command ...
conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    info         Display information about current conda install.
    help         Displays a list of available conda commands and their help
                 strings.
    list         List linked packages in a conda environment.
    search       Search for packages and display their information. The input
                 is a Python regular expression. To perform a search with a
                 search string that starts with a -, separate the search from
                 the options with --, like 'conda search -- -h'. A * in the
                 results means that package is installed in the current
                 environment. A . means that package is not installed but is
                 cached in the pkgs directory.
    create       Create a new conda environment from a list of specified
                 packages.
    install      Installs a list of packages into a specified conda
                 environment.
    update       Updates conda packages to the latest compatible version. This
                 command accepts a list of package names and updates them to
                 the latest versions that are compatible with all other
                 packages in the environment. Conda attempts to install the
                 newest versions of the requested packages. To accomplish
                 this, it may update some packages that are already installed,
                 or install additional packages. To prevent existing packages
                 from updating, use the --no-update-deps option. This may
                 force conda to install older versions of the requested
                 packages, and it does not prevent additional dependency
                 packages from being installed. If you wish to skip dependency
                 checking altogether, use the '--force' option. This may
                 result in an environment with incompatible packages, so this
                 option must be used with great caution.
    upgrade      Alias for conda update. See conda update --help.
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove. See conda remove --help.
    config       Modify configuration values in .condarc. This is modeled
                 after the git config command. Writes to the user .condarc
                 file (/Users/azizmamatov/.condarc) by default.
    clean        Remove unused packages and caches.
    package      Low-level conda package utility. (EXPERIMENTAL)

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.

other commands, such as "conda build", are avaialble when additional conda
packages (e.g. conda-build) are installed

xyz-MacBook-Pro:~ azizmamatov$ conda list
# packages in environment at /Users/azizmamatov/anaconda:
#
_license                  1.1                      py27_1  
_nb_ext_conf              0.3.0                    py27_0  
alabaster                 0.7.9                    py27_0  
anaconda                  4.2.0               np111py27_0  
anaconda-clean            1.0.0                    py27_0  
anaconda-client           1.5.1                    py27_0  
anaconda-navigator        1.3.1                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astroid                   1.4.7                    py27_0  
astropy                   1.2.1               np111py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
beautifulsoup4            4.5.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.2                   py27_0  
boto                      2.42.0                   py27_0  
bottleneck                1.1.0               np111py27_0  
cdecimal                  2.3                      py27_2  
Cerberus                  1.1                       <pip>
cffi                      1.7.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.6                      py27_0  
cloudpickle               0.2.1                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.3.18                   py27_0  
conda-build               2.0.2                    py27_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.3                    py27_0  
cryptography              1.5                      py27_0  
curl                      7.49.0                        1  
cycler                    0.10.0                   py27_0  
cython                    0.24.1                   py27_0  
cytoolz                   0.8.0                    py27_0  
dask                      0.11.0                   py27_0  
datashape                 0.5.2                    py27_0  
decorator                 4.0.10                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.12                     py27_2  
dynd-python               0.7.2                    py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
filelock                  2.0.6                    py27_0  
flask                     0.11.1                   py27_0  
flask-cors                2.1.2                    py27_0  
freetype                  2.5.5                         1  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.2                    py27_0  
greenlet                  0.4.10                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.6.0               np111py27_2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
icu                       54.1                          0  
idna                      2.1                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.16                   py27_0  
ipykernel                 4.5.0                    py27_0  
ipython                   5.1.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.2                      py27_1  
jedi                      0.9.0                    py27_1  
jinja2                    2.8                      py27_1  
jpeg                      8d                            2  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.0                    py27_0  
lazy-object-proxy         1.2.1                    py27_0  
libdynd                   0.7.2                         0  
libpng                    1.6.22                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvmlite                  0.13.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.6.4                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.3               np111py27_0  
mistune                   0.7.3                    py27_1  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_2  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.8                    py27_0  
nb_anacondacloud          1.2.0                    py27_0  
nb_conda                  2.0.0                    py27_0  
nb_conda_kernels          2.0.0                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.1.0                    py27_0  
nbpresent                 3.0.2                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.1                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.2.3                    py27_0  
numba                     0.28.1              np111py27_0  
numexpr                   2.6.2               np111py27_0  
numpy                     1.11.3                   py27_0  
odo                       0.5.0                    py27_1  
openpyxl                  2.3.2                    py27_0  
openssl                   1.0.2j                        0  
pandas                    0.18.1              np111py27_0  
partd                     0.3.6                    py27_0  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    3.3.1                    py27_0  
pip                       8.1.2                    py27_0  
pkginfo                   1.3.2                    py27_0  
ply                       3.9                      py27_0  
prompt_toolkit            1.0.3                    py27_0  
psutil                    4.3.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.14                     py27_1  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_0  
pyflakes                  1.3.0                    py27_0  
pygments                  2.1.3                    py27_0  
pylint                    1.5.4                    py27_1  
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_0  
pytables                  3.2.3.1             np111py27_0  
pytest                    2.9.2                    py27_0  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
python.app                1.2                      py27_4  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     15.4.0                   py27_0  
qt                        5.6.0                         0  
qtawesome                 0.3.3                    py27_0  
qtconsole                 4.2.1                    py27_1  
qtpy                      1.1.2                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.12.4                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_0  
schema                    0.6.5                     <pip>
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.18.1                    <pip>
scikit-learn              0.18.1              np111py27_1  
scipy                     0.19.0              np111py27_0  
seaborn                   0.7.1                    py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.4.6                    py27_0  
spyder                    3.0.0                    py27_0  
sqlalchemy                1.0.13                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
sympy                     1.0                      py27_0  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py27_0  
tornado                   4.4.1                    py27_0  
traitlets                 4.3.0                    py27_0  
unicodecsv                0.14.1                   py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.11                  py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
wrapt                     1.10.6                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.3                    py27_0  
xlwings                   0.10.0                   py27_0  
xlwt                      1.1.2                    py27_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3

**Comment by goanpeca** [comment]
@saidamir you are using an extremely old version. Please open the command prompt and update with the following command

`$ conda update anaconda-navigator` latest version is 1.6.5, you are using 1.3.1

**Comment by saidamir** [comment]
Thank you very much! In the future, how do I check for updates?

**Comment by goanpeca** [comment]
@saidamir Navigator should prompt you when there is a new version available :-)

You also need to install the updater package so it can be done via the gui.

`$ conda install navigator-updater`

Cheers~

**Comment by saidamir** [comment]
Thank you very much!

**Comment by goanpeca** [comment]
Glad to be of help!

**Comment by Myriam31** [comment]
$ conda update anaconda-navigator worked for me

**Comment by ghivikas** [comment]
Hi I am also facing Navigator Launch and getting bellow error on console.
(my_env) vikas@vikas-VPCEH36EN:/tmp$ anaconda-navigator
Traceback (most recent call last):
  File "/home/vikas/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Aborted (core dumped)

**Comment by ghivikas** [comment]
Output of conda info 
(my_env) vikas@vikas-VPCEH36EN:/tmp$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/vikas/anaconda3  (writable)
    default environment : /home/vikas/anaconda3/envs/my_env
       envs directories : /home/vikas/anaconda3/envs
          package cache : /home/vikas/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

**Comment by ghivikas** [comment]
output of conda list
(my_env) vikas@vikas-VPCEH36EN:/tmp$ conda list
# packages in environment at /home/vikas/anaconda3/envs/my_env:
#
_license                  1.1                      py36_1  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.6.4                    py36_0  
anaconda-project          0.6.0                    py36_0  
beautifulsoup4            4.6.0                    py36_0  
certifi                   2016.2.28                py36_0  
chardet                   3.0.4                    py36_0  
clyent                    1.2.2                    py36_0  
dbus                      1.10.20                       0  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
icu                       54.1                          0  
jbig                      2.1                           0  
jpeg                      9b                            0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libiconv                  1.14                          0  
libpng                    1.6.30                        1  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
olefile                   0.44                     py36_0  
openssl                   1.0.2l                        0  
pcre                      8.39                          1  
pillow                    4.2.1                    py36_0  
pip                       9.0.1                    py36_1  
psutil                    5.2.2                    py36_0  
pyqt                      5.6.0                    py36_2  
python                    3.6.2                         0  
python-dateutil           2.6.1                    py36_0  
pytz                      2017.2                   py36_0  
pyyaml                    3.12                     py36_0  
qt                        5.6.2                         5  
qtpy                      1.3.1                    py36_0  
readline                  6.2                           2  
requests                  2.14.2                   py36_0  
ruamel_yaml               0.11.14                  py36_1  
setuptools                36.4.0                   py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
tornado                   4.5.2                    py36_0  
wheel                     0.29.0                   py36_0  
xz                        5.2.3                         0  
yaml                      0.1.6                         0  
zlib                      1.2.11                        0

**Comment by ghivikas** [comment]
i am using Ubuntu16.04

**Comment by bryanleekw** [comment]
same as me..I am having the same issue

**Comment by bryanleekw** [comment]
bryanleekw@nb1:/opt/anaconda/bin$ anaconda-navigator 
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Aborted (core dumped)
bryanleekw@nb1:/opt/anaconda/bin$

**Comment by sambatlim** [comment]
I found this tip is work:

$ run your anaconda prompt as administrator
$ conda update anaconda-navigator
$ conda update navigator-updater

Then open your anaconda-navigator again. Hopefully it works.
