### ISSUE TITLE
Anaconda Crash at launch Mac Sierra 10.12.06

### ISSUE THREAD

**Issue by monergy** [ContinuumIO/anaconda-issues#4753]
Trying to launch anaconda 3-4.4.0 on Mac Sierra OS 10.12.06 using the icon it crashes after the icon appears for a few seconds I tried 

I have also tried `sudo anaconda-navigator` to launch and get this error

Traceback (most recent call last):
  File "/Users/matthewshields/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6
How do I correct this?

**Comment by goanpeca** [comment]
@monergy you are probably using a very old version? so I would advice to open a terminal

```
$ conda update anaconda-navigator
$ conda install navigator-updater
```

**Comment by Xiangmengkong** [comment]
I had the same error and updated my anaconda to solve it. But I get the following error message at launch:

2017-08-29 13:58:07,848 - ERROR download_api._download:197
Invalid url http://content.continuum.io/api/events

2017-08-29 13:58:07,875 - ERROR download_api._download:197
Invalid url http://content.continuum.io/api/videos

2017-08-29 13:58:08,217 - ERROR download_api._download:197
Invalid url http://content.continuum.io/api/webinars

It doesn't bother too much. But I'd be happy to know what they mean.

**Comment by goanpeca** [comment]
@Xiangmengkong we recently updated our brand and some urls where redirected. Those errors are harmless and relate to content in the Community and Learning tabs. It should be fixed in the new version to be released in a couple of days
