### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by opjklu** [ContinuumIO/anaconda-issues#4774]
## Main error
<b>Unable to move <i>test</i></b><br><br>Error message:<br>[Errno 13] Permission denied: u'D:\\C++Pro\\tens\\test'
## Traceback
```

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: zh_CN
python: 2.7.13
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@opjklu what where you trying to accomplish?
