### ISSUE TITLE
futurize and pasteurize scripts are not installed from package future

### ISSUE THREAD

**Issue by ianmartin** [ContinuumIO/anaconda-issues#478]
Scripts futurize and pasteurize from the python package future are not installed in the bin directory using conda install. Removing and installing using pip does install them.

```
$ conda list future
# packages in environment at /home/server/software/anaconda:
#
future                    0.14.3                   py27_0  
futures                   3.0.2                    py27_0
```

```
$ futurize
bash: futurize: command not found
```

```
Current conda install:

             platform : linux-64
        conda version : 3.18.2
  conda-build version : 1.13.0
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /home/server/software/anaconda  (read only)
  default environment : /home/server/software/anaconda

<-- snip -->

         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by bilderbuchi** [comment]
I just ran into the same issue

**Comment by underchemist** [comment]
me as well.

```
Current conda install:

             platform : osx-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.0
     root environment : /Users/underchemist/anaconda  (writable)
  default environment : /Users/underchemist/anaconda/envs/py27
     envs directories : /Users/underchemist/anaconda/envs
        package cache : /Users/underchemist/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/underchemist/.condarc
    is foreign system : False
```

**Comment by bilderbuchi** [comment]
Is this an Anaconda problem or a `future` problem (e.g. with setup.py or whatever)? pinging @edschofield

**Comment by edschofield** [comment]
I think this is an anaconda packaging problem, since "pip install future" installs the futurize and pasteurize scripts...

**Comment by msarahan** [comment]
Thanks.  We will investigate.

**Comment by bilderbuchi** [comment]
thank you.

**Comment by kyleabeauchamp** [comment]
I just compared the currently uploaded package (https://anaconda.org/anaconda/future/0.15.2/download/osx-64/future-0.15.2-py27_0.tar.bz2) to the results of running `conda-build future` using (https://github.com/ContinuumIO/anaconda-recipes/tree/master/future) and installing the output tarball.  

I find that re-building the recipe does indeed install the binary:

```
$ which futurize
~/opt/bin/futurize
```

Perhaps a botched recipe was uploaded?

**Comment by kyleabeauchamp** [comment]
Perhaps it would make sense to add a test section to the `meta.yaml` that checks the helpstring of both `futurize` and `pasteurize`:

```
pasteurize -h
futurize -h
```

**Comment by mmysinger** [comment]
If anyone else lands here looking for the futurize script, you can use the patch below to fix the meta.yaml from https://github.com/ContinuumIO/anaconda-recipes/tree/master/future

After patching 'cd' into the directory above your local future recipe then:
`
conda-build future
conda install --use-local future
`

`
@@ -7,13 +7,23 @@
   url: https://pypi.python.org/packages/source/f/future/future-0.15.2.tar.gz
   md5: a68eb3c90b3b76714c5ceb8c09ea3a06
 
+build:
+  number: 1
+  entry_points:
+    - futurize = libfuturize.main:main
+    - pasteurize = libpasteurize.main:main
+
 requirements:
   build:
     - python
+    - setuptools
   run:
     - python
 
 test:
+  commands:
+    - futurize -h
+    - pasteurize -h
   imports:
     - future
`

**Comment by stuarteberg** [comment]
This issue is fixed on conda-forge, but not in `defaults`.  I guess anaconda hasn't yet started using conda-forge's recipe for this package?

**Comment by ilanschnell** [comment]
I just uploaded `future-0.16.0` build 1 packages with the entry points.

**Comment by stuarteberg** [comment]
Thanks, @ilanschnell!
