### ISSUE TITLE
Scipy sph_harm miscompilation

### ISSUE THREAD

**Issue by Eric89GXL** [ContinuumIO/anaconda-issues#479]
I found an inconsistency in sph_harm, but it appears on Linux 64-bit Python 3.4 (e.g., on Anaconda scipy=0.16 or scipy=0.15) but not on Python 2.7 with equivalent numpy/scipy versions. Running this command in a Python 3.4 Anaconda virtual environment I get:

```
$ python -c "from scipy.special import sph_harm; print(sph_harm(1, 1, 1., 1.))"
(-0.290723302201-2.02129965364e-310j)
```
But the correct result is what I get on Python 2.7:
```
(-0.157078470549-0.24463522341j)
```
It does work on my system Python3 when using the Ubuntu-packaged scipy 0.14.1, or when I build scipy myself, latest master with MKL or maintenance/0.16.x using system BLAS.

The scipy devs told me that:

"Whatever compiler they are using has miscompiled the Cython-generated routine __pyx_f_5scipy_7special_8sph_harm_sph_harmonic so that it returns the wrong value."

See:

https://github.com/scipy/scipy/issues/5376

**Comment by Eric89GXL** [comment]
Notably, this happens both on Ubuntu 15.04 that I am running, and on Travis-CI Ubuntu 12.04 builds (where I originally saw the problem).

**Comment by msarahan** [comment]
Potentially related to https://github.com/ContinuumIO/anaconda-issues/issues/425#issuecomment-147113803

**Comment by mzaffalon** [comment]
Is there any workaround until this gets fixed?

**Comment by Eric89GXL** [comment]
@mzaffalon for now you might be able to make use of the Python version of the `_sph_harm` function we've been using locally in our mne-python package in place of the `scipy` one:

https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/maxwell.py#L380

**Comment by mzaffalon** [comment]
@Eric89GXL thank you. It looks like the problem does not affect Windows 64.

**Comment by Eric89GXL** [comment]
Fixed in https://github.com/scipy/scipy/pull/6074
