### ISSUE TITLE
Defaulting to numpy 1.10.* causes performance regression

### ISSUE THREAD

**Issue by esheldon** [ContinuumIO/anaconda-issues#482]
numpy 1.10.0 and 1.10.1 have a serious performance regression

https://github.com/numpy/numpy/issues/6467

The new numpy can be ten to thousands of times slower for real world use cases with structured arrays.  The numpy devs have not yet committed to any timescale for rolling out the fix.

1.10.* is now the default in anaconda.  I think it would be prudent to somehow roll back so that 1.9 is again the default.  I understand this may be logistically difficult, so I want to open a discussion.

At the very least, I think it would be useful to send notification that common numpy operations could be much slower after a conda update, and give explicit instructions on now to pin numpy.

**Comment by ccordoba12** [comment]
@ilanschnell?

**Comment by ilanschnell** [comment]
People are going to except NumPy 1.10 in the next Anaconda release.  The fact that some operations are somewhat slower is an upstream problem.  I don't think we can do anything about this.

**Comment by esheldon** [comment]
This is a huge performance regression, not "somewhat slower".  One of my codes is 1500 times slower with 1.10*.  I think people would like to be warned at the very least, and given instructions on how to pin numpy.

**Comment by ilanschnell** [comment]
Ok, we can add a note about that in the release notes.
