### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by nunes90** [ContinuumIO/anaconda-issues#4828]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

```
## System information
```
python: 3.6.1
language: pt_BR
os: Linux;4.12.8-2-ARCH;#1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017;x86_64;
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
This is a drivers issue. I don't think there is something we could do about it.

**Comment by L4student** [comment]
@ccordoba12 @goanpeca 
I suspect it's also somehow related to spyder/conda because I have two conda environments (both with spyder, one with Py-3.6 and the other with Py-2.7) within my main anaconda installation (with Py-2.7), and I only get these errors when I try to run spyder from my main conda installation. I don't get these errors when I run spyder from either of the two environments as shown below. 
```
$ spyder
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```
```
$ spyder
[3]-  Done                    spyder
```
```
$ spyder
^Z
[1]+  Stopped                 spyder
```

**Comment by L4student** [comment]
I am not sure, but it seems to me if this could be an issue related to `pyqt` version? The ones that run fine are both `4.11.4` version and the one that's giving an error is `5.6.0` version.
