### ISSUE TITLE
Navigator crashes in windows 10 - both laptop and desktop

### ISSUE THREAD

**Issue by EhudEilon** [ContinuumIO/anaconda-issues#4887]
The crash occurs immediately upon activation. It may be linked to Keras/tensorflow installation as they were the last packages I've updated.
Error message is:

2017-09-01 15:47:42,761 - DEBUG
    community.load_content : 224
    Event parse failed: {'location_city': '', 'categories': [], 'registration_url_label': '', 'location_state_province': '', 'registration_url': 'https://www.pycon.it/en/registration/', 'date_end': '', 'location_country': '', 'location_company': '', 'date_start': '', 'subtitle': '', 'title': 'PyData Florence', 'summary': '', 'sticky': '', 'location_region': '', 'banner': 'https://www.anaconda.com/wp-content/uploads/2017/03/pydatalogo-generic_2.png', 'url': 'https://www.pycon.it/en/registration/', 'id': '469'}

My system is: 
Python: 3.5.0
Anaconda-navigator: 1.3.1
Conda: 4.3.24
qt: 5.6.0
pyqt: 5.6.0
Keras: 2.0.6
tensorflow: 1.3.0

**Comment by EhudEilon** [comment]
Maybe a full log of a crash event would be benefical
[crashlog.txt](https://github.com/ContinuumIO/anaconda-issues/files/1270298/crashlog.txt)

**Comment by goanpeca** [comment]
@EhudEilon you are using an old version of navigator. Please update to the latest version.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda install navigator-updater
```
