### ISSUE TITLE
Launcher fatal error

### ISSUE THREAD

**Issue by DavidUnderdown** [ContinuumIO/anaconda-issues#489]
I've tried several times to install Anaconda on a Windows 7 PC.  Installation always appears to complete OK, but then the Launcher gives fatal error as soon as it starts (if I open the Anaconda command line interface it seems to get a little further, with the Python version appearing at the top of the window, but it still crashes out).

I've uninstalled the previous versions of Python I had, installed as Admin for all users, and various other combinations.

I can't see anything relevant in the Windows logs.

**Comment by goanpeca** [comment]
Hi @DavidUnderdown, which version of the launcher are you trying to install?

**Comment by DavidUnderdown** [comment]
Sorry it's Anaconda3-2.3.0 64-bit (required for this course http://www.open.edu/openlearn/learn-to-code-installation )

**Comment by goanpeca** [comment]
Thanks,

Could you open a command prompt, type the following:
```bash
conda list launcher
```

and paste the result back?

Cheers

**Comment by DavidUnderdown** [comment]
# packages in environment at C:\Anaconda3:
#
launcher                  1.0.0                         1

**Comment by goanpeca** [comment]
There is a new launcher in beta testing, could you give it a try, to see if it solves your problem?

Please try in the command prompt and let us know how it went.
```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

**Comment by DavidUnderdown** [comment]
The install step isn't working, I think it's probably firewall or proxy issues at my end as it can't connect to the url.  I can download the launcher package manually, can I just change the URL to a local file URL, or is there a different syntax

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
