### ISSUE TITLE
Anaconda Navigator crashes OS Sierra

### ISSUE THREAD

**Issue by shainova** [ContinuumIO/anaconda-issues#4902]
Hi
The Navigator constantly crashes! I have seen this issue several times but no solution helped. Anybody can help? Below is the conda info and also the error I get hen running anaconda-navigator from the terminal.
Thanks!!
Shai

Current conda install:

               platform : osx-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 2.0.2
         python version : 3.5.4.final.0
       requests version : 2.14.2
       root environment : /Users/Shai/anaconda  (writable)
    default environment : /Users/Shai/anaconda
       envs directories : /Users/Shai/anaconda/envs
                          /Users/Shai/.conda/envs
          package cache : /Users/Shai/anaconda/pkgs
                          /Users/Shai/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.5.4 Darwin/16.5.0 OSX/10.12.4    
                UID:GID : 501:20

Traceback (most recent call last):
  File "/Users/Shai/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6

**Comment by goanpeca** [comment]
Please  update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Comment by shainova** [comment]
it worked! Thanks :)

**Comment by Garorod** [comment]
I can't believe! Thanks
