### ISSUE TITLE
Navigator Error when importing an environment

### ISSUE THREAD

**Issue by Ericvulpi** [ContinuumIO/anaconda-issues#4969]
I downloaded the environment from a mac computer to my account on anaconda cloud then downloaded it on an Ubuntu 16.04 system.
Error appears when I try importing through the navigator app

## Main error
The following errors occurred:
## Traceback
```

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.10.0-33-generic;#37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@Ericvulpi the environment is most likely OSX only hence why you see the error. You will need to manually tweak the env requirements so that it can work on linux. We are working on a cross platform environment export solution.

**Comment by Ericvulpi** [comment]
A neat trick would be for anaconda to point the packages causing the problem, and maybe bypass them in the environment building process
