### ISSUE TITLE
Recursion Depth Execeeded

### ISSUE THREAD

**Issue by Andrew62** [ContinuumIO/anaconda-issues#497]
I tried to make a R environment and I received:

RuntimeError: maximum recursion depth exceeded

System and command info: 

conda create -n my-r-env -c r r-essentials

             platform : osx-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Python 3.4.3 :: Anaconda 2.3.0 (x86_64)

**Comment by mcg1969** [comment]
A fix has been posted here: https://github.com/conda/conda/issues/1748

For now, you can bypass this by downgrading to conda 3.18.2 first by issuing the command `conda install conda==3.18.2` prior to attempting your installation.

**Comment by groutr** [comment]
Fixed with conda 3.18.4
