### ISSUE TITLE
Can I install anaconda on a 2008 MAcBook (Intel Core 2 Duo) with OS X 10.7.5?

### ISSUE THREAD

**Issue by billtubbs** [ContinuumIO/anaconda-issues#4995]
I think it's a 32-bit machine.  I don't see any 32 bit versions of anaconda installer.  Please confirm if this is impossible.

**Comment by mingwandroid** [comment]
We no longer support macOS < 10.9 nor 32 bit macOS.

**Comment by billtubbs** [comment]
According to the following from [Documentation - Installation](https://docs.continuum.io/anaconda/install/) this should be possible.

System requirements

License: Free use and redistribution under the terms of the Anaconda End User License Agreement.
Operating system: Windows Vista or newer, macOS 10.7+, or Linux, including Ubuntu, RedHat, CentOS 6+, and others.
Windows XP supported on Anaconda versions 2.2 and earlier. See Old package lists. Download it from our archive.
System architecture: 64-bit x86, 32-bit x86, or Power8.
Minimum 3 GB disk space to download and install.

**Comment by billtubbs** [comment]
Okay thanks.

**Comment by mingwandroid** [comment]
@electronwill, @kerrywatson, bringing this to your attention.

**Comment by billtubbs** [comment]
I managed to [install the Scipy stack with pip](https://www.scipy.org/install.html).  Seems to work although had some problems with PATH variables.  Wonder how long before something breaks...
