### ISSUE TITLE
Navigator fails to launch

### ISSUE THREAD

**Issue by emb356** [ContinuumIO/anaconda-issues#5023]
Anaconda Navigator fails to launch on Windows 10, anaconda-navigator command reads:

QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'

How do I fix this issue?

**Comment by goanpeca** [comment]
**See issue #4747 for more information on how to fix this issue.**

---

Closing as duplicate of #4747

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
