### ISSUE TITLE
Missing spyder shortcut after update

### ISSUE THREAD

**Issue by Tomcatus** [ContinuumIO/anaconda-issues#503]
Hello, I'm using Anaconda x64 with Python 2.7 on a Windows 10 x64 computer and after doing an update of Spyder from the Launcher app I can't see shortcut nor run the app from Start Menu. Before doing an update by the Launcher the shortcuts were visible and accessible.

**Comment by ccordoba12** [comment]
This will be fixed after Anaconda 2.4 is released, most surely on Monday.

**Comment by Tomcatus** [comment]
Indeed the updated version doesn't have this issue. Thanks a lot :)

**Comment by mujtaba617** [comment]
Same problem exists even today. Spyder and Anaconda Prompt shortcuts disappeared after an update.
