### ISSUE TITLE
r-irkernel linked against an old version of libzmq

### ISSUE THREAD

**Issue by cel4** [ContinuumIO/anaconda-issues#506]
`otool -L /Users/ch/miniconda/envs/sci34/lib/R/library/rzmq/libs/rzmq.so`

```
/Users/ch/miniconda/envs/sci34/lib/R/library/rzmq/libs/rzmq.so:
	@rpath/R/library/rzmq/libs/rzmq.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/./libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/./libzmq.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/R/lib/libR.dylib (compatibility version 3.2.0, current version 3.2.2)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 635.21.0)
	@rpath/./libstdc++.6.dylib (compatibility version 7.0.0, current version 7.19.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```

---

`ls ~/miniconda/envs/sci34/lib/libzmq*`
```
/Users/ch/miniconda/envs/sci34/lib/libzmq.5.dylib
/Users/ch/miniconda/envs/sci34/lib/libzmq.a
/Users/ch/miniconda/envs/sci34/lib/libzmq.dylib
/Users/ch/miniconda/envs/sci34/lib/libzmq.la
```

**Comment by cel4** [comment]
see also: https://github.com/IRkernel/IRkernel/issues/205

**Comment by parente** [comment]
Thanks, @cel4. Now I know where to file conda package problems!

**Comment by cel4** [comment]
I am a little bit surprised that this rebuild did not happen automatically when the new anaconda version was released a couple of days ago. I understand that updating c-extensions is annoying because it tends to constantly break linkage. However not having to compile is one of the defining features of conda and I would expect more focus on tackling this problem.

I don't really seem to understand your strategy here. So far every new anaconda release was carefully prepared to make sure that everything works together. Breakages between major anaconda versions happened frequently, but were often handled on request by @asmeurer via gitter support and bug requests.

With the latest release of anaconda this issue was not fixed and installing `jupyter` implicitly blocks the `ir-kernel` package. It seems that there are either very limited resources or little interest to actually fix this issue here.

@ilanschnell, are you planning to give first class support for the `r` packages in future, or will you focus more on the pythonic world? Also are you planning to tackle the constant breakages that make manually updating very problematic? In principle an automated pipeline that rebuilds all packages that depend on an updated c package should do, right?

**Comment by mrterry** [comment]
I just ran into this.  I was bragging about how conda had good support for R and how Jupyter notebooks are great way to share analysis in R.  R-notebook is currently dead on arrival.  Maybe next time.

**Comment by jmberros** [comment]
I see this is still open. Here's a quickfix from @cfljam in https://github.com/IRkernel/IRkernel/issues/205, just in case anyone is trying to get their R-notebook to work and ends up in this thread, like me:

`conda create -y -n rkernel-fix -c r r-essentials  python=3.4 zeromq=4.0*`

**Comment by ilanschnell** [comment]
@groutr has taken over building R packages, and should take a look at this.

**Comment by groutr** [comment]
I have rebuilt irkernel against the latest libraries in the anaconda repo.  Are things still broken?

**Comment by parente** [comment]
@groutr Thanks for taking this. I'll give it a shot over in jupyter/docker-stacks and report back.

**Comment by parente** [comment]
r-irkernel=0.5 fixes the problem

**Comment by cel4** [comment]
works for me, too. Thanks a lot! 

I am closing this.

**Comment by ScottLawtonSSM** [comment]
(I'm not very active on Github so please let me know if there's a better way or place to report this.)
Doesn't work for me -- possbily miniconda vs conda?

first attempt:
`conda install -c r r-essentials`

When that led to R failing in Jupyter (full error below) I tried the above suggestion:
`conda create -y -n rkernel-fix -c r r-essentials python=3.4 zeromq=4.0*`
(I also tried python=3.5)

I wasn't sure how to apply @parente's solution but tried appending it:
`conda create -y -n rkernel-fix -c r r-essentials python=3.4 zeromq=4.0* r-irkernel=0.5`

I also tried several things from a related thread: https://github.com/IRkernel/IRkernel/issues/205

`jupyter notebook` starts up as expect and a Python3 notebook works. But an R notebook gives me an error:

`Kernel started: 972c1e8f-2e54-42b0-9790-0ac531f5acff
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/slawton/miniconda3/envs/rkernel-fix/lib/R/library/rzmq/libs/rzmq.so':
  dlopen(/Users/slawton/miniconda3/envs/rkernel-fix/lib/R/library/rzmq/libs/rzmq.so, 6): Library not loaded: @rpath/libzmq.5.dylib
  Referenced from: /Users/slawton/miniconda3/envs/rkernel-fix/lib/R/library/rzmq/libs/rzmq.so
  Reason: image not found
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
`

I could delete miniconda and start with full conda; not sure that will help.

FYI: new MacBook running OS X El Capitan 10.11.5.

**Comment by RZachLamberty** [comment]
I don't think this issue is resolved. I'm also on OS X 10.11.5 and experiencing identical behavior, but with the full `conda` install, so I think that "conda vs. miniconda" is not the issue.

Environment created the same way:

```
conda create -y -n rkernel-fix -c r r-essentials python=3.4 zeromq=4.0* r-irkernel=0.5 jupyter
```

any attempt to load an `R` kernel fails with the exact same error message as in ScottLawtonSSM's post above.

My specific conda info:

```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.2
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/zach.lamberty/anaconda2  (writable)
  default environment : /Users/zach.lamberty/anaconda2/envs/rkernel-fix
     envs directories : /Users/zach.lamberty/anaconda2/envs
        package cache : /Users/zach.lamberty/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Finally, I will note that creating a symlink from my conda library dir to my `brew`-installed ZeroMQ library will allow me to open and use `R` kernels in jupyter notebooks:

```
ln -s /usr/local/lib/libzmq.5.dylib /path/to/my/conda/envs/my_env_name/lib/libzmq.5.dylib
```

As this install process works seemlessly for my colleagues using windows and *nix OSes, I'm pretty sure this is just an issue with the osx channel's conda package.

**Comment by ScottLawtonSSM** [comment]
Thanks for the additional detail; useful to know that miniconda isn't the issue. Also: it's apparently not a Python 2.x vs. 3.x issue; I started with the latter.

QUESTION: other than brew (which has cause problems for me in the past), does anyone know an easy way to get libzmq.5.dylib ... a quick Google search didn't yield an obvious answer (though I haven't made a detailed search).

Also, fyi:
```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.2
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/slawton/miniconda3  (writable)
  default environment : /Users/slawton/miniconda3
     envs directories : /Users/slawton/miniconda3/envs
        package cache : /Users/slawton/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by mingwandroid** [comment]
Hi @RZachLamberty, I have test packages for `R 3.3.1` on https://anaconda.org/rdonnellyr for all platforms.

Would it be possible for you and you colleagues to give this version a test? The following should see you right:

`conda create -y -n rkernel-fix -c rdonnellyr r-essentials jupyter`

Many thanks.

**Comment by mingwandroid** [comment]
FYI, I checked the r-rzmq package in rdonnellyr and it links against the correct libzmq:

`name @rpath/libzmq.5.dylib`

**Comment by RZachLamberty** [comment]
@mingwandroid That worked for me, thank you. I did notice another oddity, maybe a bug, but it's not pertinent to this thread -- do you have a preferred way that I should report that?
