### ISSUE TITLE
%PREFIX%\Library\bin not include in PATH on 32-bit Windows

### ISSUE THREAD

**Issue by jjhelmus** [ContinuumIO/anaconda-issues#509]
Using the latest Miniconda (3.16.0) and Anaconda installer (2.3.0) on 32-bit Windows, the PATH variable is updated to include the **%PREFIX%** and **%PREFIX%\Scripts** directories but it does not include the **%PREFIX%\Library\bin** directory.  This directory is include in the PATH of any environments created using `conda create` with the merging of  conda/conda-env#152.  

This leads to all types of hijinks where packages work in a conda environment but not in the root environment.  Some examples I have run into are PyQt4 (`python -c "import PyQt4.QtCore"`) and matplotlib (`python -c "import matplotlib.pyplot`) although the latter may be a result of the former.  Adding the **%PREFIX%\Library\bin** directory to PATH solves these issues and should likely be the default action.

I have not attempted to determine if this effects the 64-bit Windows installer or the Python 3 Windows installers.

**Comment by msarahan** [comment]
Thanks for pointing this out.  For now, please add %PREFIX%\Library\bin to your PATH manually.  We will work on a fix for conda that makes this happen more automatically for "legacy" installations updating to newer versions that more towards putting stuff in Library\bin.

All current Miniconda installers will be affected by this issue.  The pending Anaconda 2.4 installers will not have this issue.  This will be fixed in the next Miniconda release, and I will also look into a way to make conda update this when updating, if it finds that a PREFIX is in PATH.

**Comment by msarahan** [comment]
I have a fix (in private repo) that does the following as a post-link script for conda-env:

```
@setlocal enableextensions enabledelayedexpansion
@echo off

echo import os, sys > get_prefix.py
echo if sys.prefix in os.environ["PATH"] and os.path.join(sys.prefix, "Library", "bin") not in os.environ["PATH"]: >> get_prefix.py
echo     print(os.path.join(sys.prefix, "Library", "bin")) >> get_prefix.py
echo else: >> get_prefix.py
echo     print()  >> get_prefix.py

:: stick that on the end of PATH
FOR /F "delims=" %%i IN ('call python get_prefix.py') DO set EXTRA_PATH=%%i
echo "Ensuring that <PREFIX>\Library\bin is on PATH."
setx PATH "%PATH%;%EXTRA_PATH%"

del get_prefix.py

endlocal
```

Feedback welcome.  We'll get this, or a comparable fix out soon.

**Comment by jjhelmus** [comment]
The updates to Miniconda with the 3.18.3 release has fixed this issue for me, thank you for this!  The Library/bin directory is included by default in the PATH after install with this new version.  

This still leave the issue of what should be done if Miniconda/Anaconda was installed with a previous version.  The get_prefix.py fix seems reasonable but it is unclear to me if this would persist between sessions or if this work without a call to conda env.  There may be a more preferable solution besides telling users to manually add the directory to their PATH in System Properties but I am not knowledgeable enough on this topic to supply one.

**Comment by msarahan** [comment]
setx sets the environment variable permanently, so it should persist.  I'm working on a more complete script that sets PATH at either User level or system-wide, depending on installation type.  That should hopefully go in today, and packages should be available soon.

**Comment by msarahan** [comment]
This fix has been released as conda-env-2.4.4-1.  It has been tested to work with both user-level, and system-level installations of Miniconda version 3.16 and Anaconda 2.3.  Updating from earlier versions should behave similarly.

I'm closing this issue, but feel free to reopen this if the issue remains.

**Comment by tico-tico** [comment]
FYI Updating to **conda-env-2.4.4-1** shows a warning and tries to downgrade the python package. Is that intended?

```
c:\Miniconda2>conda update --all
Fetching package metadata: ....
Solving package specifications: ................................................
............................................................
Warning: 2 possible package resolutions (only showing differing packages):
        [u'msvc_runtime-1.0.1-vc9_0.tar.bz2', u'python-2.7.10-1.tar.bz2'],
        [u'msvc_runtime-1.0.0-vc9_0.tar.bz2', u'python-2.7.10-3.tar.bz2'],

Package plan for installation in environment C:\Miniconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.10              |                1        17.9 MB
    conda-env-2.4.4            |           py27_1          65 KB
    ------------------------------------------------------------
                                           Total:        18.0 MB

The following packages will be UPDATED:

    conda-env: 2.4.4-py27_0 --> 2.4.4-py27_1

The following packages will be DOWNGRADED:

    python:    2.7.10-3     --> 2.7.10-1

Proceed ([y]/n)?
```

**Comment by jjhelmus** [comment]
FYI, I'm getting an error while linking the new conda-env package on Windows 32:

```
> conda update --all
...
Linking packages ...
"Ensuring that C:\Users\IEUser\Miniconda2\Library\bin is on user PATH environment variable."
"" was unexpected at this time.
Error: Error: post-link fails for: conda-env-2.4.4-py27_1
```

**Comment by jjhelmus** [comment]
> echo import os, sys > get_prefix.py
> echo if sys.prefix in os.environ["PATH"] and os.path.join(sys.prefix, "Library", "bin") not in os.environ["PATH"]: >> get_prefix.py
> echo     print(os.path.join(sys.prefix, "Library", "bin")) >> get_prefix.py
> echo else: >> get_prefix.py
> echo     print()  >> get_prefix.py

This will end up printing `()` to the console if a Python 2 interpreter is used which is what is causing the post-link to fail using Miniconda 2.  Adding the following line and changing the first line as follows solves the issue:

``` 
echo from __future__ import print_function > get_prefix.py
echo import os, sys >> get_prefix.py
```

**Comment by msarahan** [comment]
Thanks.  @marscher has pointed out site.py to me in https://github.com/conda/conda/issues/1753#issuecomment-154421628

I am going to head in that direction instead, and remove this post-link script.  Note that some programs in Library/bin will not be on PATH.  I will add shortcuts to these on Windows where appropriate.  One potential issue is that conda-build needs patch.exe, which lives in Library/bin, but I think conda-build can (and does) set PATH internally anyway.

**Comment by msarahan** [comment]
Also: people can still activate the root environment to add Library/bin to PATH temporarily.

**Comment by msarahan** [comment]
This issue should be fixed.  The relevant fixed packages were:

python-2.7.10-4.
python-3.4.3-4
python-3.5.0-3

conda-env-2.4.4 (build 2)
menuinst-1.2.2

The fix is that the conda-env post-link script has been removed.  It has been replaced by a modified Lib/site.py file in each Python installation, plus a library_bin.pth file in each Python installation.  The combination of these lead to Library/bin being added to os.environ["PATH"] for any Python process.  Any programs you install that end up in Library/bin (for example, patch) will still not be on PATH for older installations.  You can either modify PATH to add Library/bin yourself, or uninstall and reinstall using a new installer (Anaconda >= 2.4.0; Miniconda >= 3.18)

I'm closing this issue, but please reopen it if you are still having issues.

**Comment by nguy** [comment]
I don't necessarily want to reopen this issue in case it doesn't pertain. But after installing a couple of packages on Conda 2.4.4 (on a Windows 10 computer belonging to someone else), the executable files showed up in ```...\Anaconda2\Scripts``` not ```...\Anaconda2\Lib\bin```. Had to add this to the PATH environment to get packages working properly.
