### ISSUE TITLE
Difficulty configuring Python 3.4 and Python 2.7 Anacondas side by side

### ISSUE THREAD

**Issue by jeremybickerstaffe** [ContinuumIO/anaconda-issues#514]
![image](https://cloud.githubusercontent.com/assets/13586102/10940906/deec25a4-8300-11e5-99ea-f5b97e3a0d40.png)

Environment: Windows 7 64-bit
Anaconda with Python 3.4 installed.
Added a Python 2.7 Anaconda using "conda create -n py27 python=2.7 anaconda"
Then using Anaconda Launcher, changed environment to py27, and ran Spyder. Result: first, error messages about QT, and then the Launcher crashed with the error message above.

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
