### ISSUE TITLE
Error updating the Spyder app

### ISSUE THREAD

**Issue by princec7** [ContinuumIO/anaconda-issues#519]
I tried updating the Spyder app, but the update was unsuccessful and I was told to report the error here. However, after opening the launcher, the "update" button no longer is visible next to the "launch" button for the Spyder app. The version is now 2.3.7, but I'm not sure what the version was before the attempted update.

**Comment by ccordoba12** [comment]
Could you open a terminal and run

    coda update spyder

and see if that fixes the problem?

**Comment by princec7** [comment]
I get the following error message. I'm very, very new to all of this, so if
it's beyond my ability to troubleshoot, don't hesitate to tell me so.
[image: Inline image 2]

**Comment by ccordoba12** [comment]
You can't attach images via email. You need to drag and drop it here :-)

**Comment by princec7** [comment]
Ok I updated my previous comment

**Comment by ccordoba12** [comment]
Sorry, I incorrectly wrote the command above. This is right one:

    conda update spyder

**Comment by princec7** [comment]
Great! Thanks. I imagine similar commands can be entered to update the other apps?

**Comment by yavigol** [comment]
Hello.  I updated Spyder application from launcher.  As a result I can launch neither launcher nor Spyder anymore.  Furthermore, I uninstalled Anaconda, downloaded the latest installation file from continuum's web site and installed the file. After that I launched the launcher and find that Spyder update is available.  I ran the update and at the end of it (during the linking stage) received the fatal error message.  I performed the process on two computers I have (both running windows 7 32bit) and got the same result in both cases.  It is not the first time when Spyder updates from launcher cause such errors.  It is pity that an update, which is supposed to be simple, makes me lose a lot of time to figure out what is going on and to reinstall anaconda from scratch.  I would appreciate if Continuum could correct the code appropriately and check anaconda updates well before issuing them to the public...

**Comment by yavigol** [comment]
I tried updating with 'conda update spyder'.  The update process at the end generated the following message:
TypeError: install() got an unexpected keyword argument 'root_prefix'

when i try running spyder, i receive the following message: 'Windows is searching for pythonw.exe.  To locate the file yourself, click Browse.

Is there any way to resolve the issue?

**Comment by ccordoba12** [comment]
@yavigol, it seems your installation was corrupted somehow. You should uninstall and install again.

**Comment by msarahan** [comment]
@yavigol please update menuinst before updating spyder.  Those errors are indicative of old menuinst versions.  Menuinst installs your Start menu shortcuts.

**Comment by yavigol** [comment]
where and when should i update the menu instructions?

**Comment by msarahan** [comment]
menuinst is a package.  At a terminal, enter in:

```
conda update conda
conda update menuinst
```

**Comment by yavigol** [comment]
Carlos, I got same errors on two computers installing just downloaded installation file...  I doubt uninstalling and installing again will help..

**Comment by yavigol** [comment]
I can send the after 'conda update spyder' screen-shot with the error message, if you wish

**Comment by yavigol** [comment]
what would be the best way to update spyder in the future?  conda update spyder?  updating from the launcher often creates fatal errors on my computers...

**Comment by msarahan** [comment]
Conda update from the terminal will be much more reliable than the launcher.  The launcher is a javascript program that calls conda in the background.  It is a lot more complicated, and more can go wrong.

updating menuinst did not work for being able to update spyder?  If not, then please paste your output here.   Here are instructions on how to copy/paste from the terminal on Windows: http://www.howtogeek.com/howto/windows-vista/copy-to-the-clipboard-from-the-windows-command-prompt/

**Comment by yavigol** [comment]
Sarah, after I ran your code Spyder does start when i run it from the search bar but does not start when i run it from the start menu due to some reason.  is there any way to correct that?

**Comment by yavigol** [comment]
i actually copied the screenshot to e-mail message already.  could you please provide an e-mail address to send the image to?

**Comment by msarahan** [comment]
There is likely a new start menu shortcut that was created for you.  Unfortunately, Windows is a little bit crusty in this regard.  The new menu shortcut exists on your hard drive (and shows up in the search), but may not show up in the start menu itself yet.  Restarting explorer fixes this.  Logging out and back in is probably the easiest, but restarting the computer or restarting explorer itself would work too.

Unfortunately, if the older shortcut was created in a different folder than the new shortcut, then the old shortcut does not get cleaned up.  I recommend manually deleting the old one.  For Windows < 10, you can right-click on it to remove it.

**Comment by yavigol** [comment]
Mike, what instructions should i enter in the future to update spyder, i-notebook, etc. avoiding using launcher?  do you have a kind of manual for that?

**Comment by yavigol** [comment]
Mike, by the way, I restarted computer but the shortcuts still do not work.  What would be the folder with valid shortcuts?

**Comment by msarahan** [comment]
It should be a folder like:
Anaconda2 (64-bit)
or
Anaconda3 (64-bit)

Whether the folder says 2 or 3 depends on the python version of your root installation. It may say 32-bit instead of 64-bit, also.  Note that if you installed system-wide to begin with, you should be prompted for elevation.  If you do not grant elevation, then the shortcuts are not installed.  Elevation is required because for system-wide installs, writing to the shortcut install location requires elevation.

Regarding updates:
http://conda.pydata.org/docs/using/pkgs.html#package-update

or just
```
conda update --all
```

**Comment by yavigol** [comment]
Mike, thank you for you help!

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
