### ISSUE TITLE
Please provide the configuration required for setting a proxy server on windows 7 for Anaconda v4.3.21

### ISSUE THREAD

**Issue by m-marek** [ContinuumIO/anaconda-issues#5218]
Hi everyone,

I've been troubleshooting a timeout error when running either 
``pip install <package>``  or 
``conda install <package>`` from my Anaconda prompt, running as administrator.
It seems the problem is in my proxy configuration, which I'm not able to crack for Windows 7. 

Error:

![capture](https://user-images.githubusercontent.com/25646735/30216404-d3337ee8-94aa-11e7-9949-ae52e5e3f62a.PNG)

![capture1](https://user-images.githubusercontent.com/25646735/30216521-2f310cb0-94ab-11e7-98a0-ee56c0274646.PNG)

I sit in a corporate environment and have contacted my IT department to resolve the issue, but they have asked I obtain the correct Windows 7 configuration, as they've only been able to obtain instructions for Windows XP and are struggling to get this to work behind the proxy server.

My current .condarc file reads
channels:
  -- conda-forge
  -- defaults
ssl_verify: true
proxy_servers:
  http: http://username:****@company_name.com:8080
  https: https://username:****@company_name.com:8080
  https://10.64.16.6: https://10.64.16.6

My HTTP_PROXY and HTTPS_PROXY environment variables are set to:
http://proxy.company_name.com/filename.pac
- though I believe the .condarc file will override this. 

Current conda install:
![conda install](https://user-images.githubusercontent.com/25646735/30216736-e63e6b3c-94ab-11e7-8e14-c9d8b974a940.PNG)

Please could you provide the precise proxy syntax / configuration for Windows 7 that I should apply to enable pip and conda installs?

**Comment by m-marek** [comment]
Amended .condarc file

**Comment by mejihero** [comment]
Hi m-marek,

I got the same issue as you had. Can I ask how to find the company_name for the company_name.com:8080? I am also working behind proxy server and can I ask how to find the port number, please? I tried to open the .pac file and it seems like my port number would be 8090.

Thanks,
Leo

**Comment by csoja** [comment]
https://docs.anaconda.com/anaconda/user-guide/tasks/proxy/
