### ISSUE TITLE
Anaconda 64-bit installs 32-bit PyQt4 and therefore PyQt doesn't work

### ISSUE THREAD

**Issue by pcp16** [ContinuumIO/anaconda-issues#522]
I did:

   conda install pyqt

from my Anaconda-64, and pyqt got installed with no issues. However, when importing from pyqt:

   from PyQt4 import QtCore

I get that the DLL could not be loaded:

   ImportError: DLL load failed: %1 is not a valid Win32 application.

I installed Anaconda-32 and PyQt on that and there were no issues (since both Python and the library are 32-bit)

**Comment by jeffrey-guy-lyon** [comment]
I also am getting this error. Is there a fix yet?

**Comment by msarahan** [comment]
I have verified that our packages contain the correct DLLs.  You may be encountering PATH issues.  If you have other software that contains Qt, and that software is 32-bit, and that software comes before Anaconda in PATH, then Anaconda's programs will use the wrong Qt.

One quick way to check this is to create an environment that uses Qt:

conda create -n pyqt_test python pyqt

Activate that environment, and try your import statement again.  Does it work?  If it does, then PATH is the issue.  Activating the environment prepends to PATH, so the environment files get found first.

**Comment by jeffrey-guy-lyon** [comment]
The first line in PATH is C:\Anaconda. I don't have any other Qt versions installed.

I was able to fix the problem by doing the following:

1. conda uninstall pyqt
2. downloaded the correct package version (qt-4.8.7-vc9_5.tar.bz2) from https://repo.continuum.io/pkgs/free/win-64/
3. conda install --use-local pyqt

Could the conda package manager be installing the wrong package?
