### ISSUE TITLE
ContinuumlO | anaconda-navigator error #197 invalid url

### ISSUE THREAD

**Issue by zsash** [ContinuumIO/anaconda-issues#5221]
I got a problem when I tried to start the anaconda-navigator.

:~$ anaconda-navigator
2017-09-08 22:52:45,294 - ERROR download_api._download:197
Invalid url http://content.continuum.io/api/videos

2017-09-08 22:52:45,295 - ERROR download_api._download:197
Invalid url http://content.continuum.io/api/events

2017-09-08 22:52:45,585 - ERROR download_api._download:197
Invalid url http://content.continuum.io/api/webinars

ps: The window of the anaconda-navigator is so large,i wanted to adjust the size of it. But I failed, because i CAN'T adjust it.
![2017-09-08 21-36-26](https://user-images.githubusercontent.com/30721421/30217656-6878bb88-94e9-11e7-9b63-a46210798ee7.png)

**Comment by goanpeca** [comment]
@zsash 1.7 will include a fix to adjust size. 1.6.6 release next week includes a fix for the issue you see on the cli. You can ignore as it does not affect Home or Environments tab

**Comment by dick7** [comment]
I got the same problem.

**Comment by goanpeca** [comment]
@dick7 you need to update to the latest anaconda-navigator.

There is also a new release of the anaconda distribution. Version 5.0.0

https://www.continuum.io/downloads
