### ISSUE TITLE
seaborn not installable with python3.5

### ISSUE THREAD

**Issue by tritemio** [ContinuumIO/anaconda-issues#523]
On a python 3.5 environment (Windows x64) seaborn is not installable even though is listed in the package list at: http://docs.continuum.io/anaconda/pkg-docs

```
> conda install seaborn
Fetching package metadata: ......
Solving package specifications: ........
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - seaborn
  - python 3.5*

Use 'conda info seaborn' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14
````

**Comment by tritemio** [comment]
Same problem with the  `future` package, under Windows x64. Both packages are available under OS X.

**Comment by bilderbuchi** [comment]
probably one of their dependencies does not have a py35 version available, see [here](https://github.com/ContinuumIO/anaconda-issues/issues/543#issuecomment-158100534)

**Comment by tritemio** [comment]
I checked again and both `future` and `seaborn` are now available for python 3.5 under Windows x64. Thanks!

**Comment by ccordoba12** [comment]
Matplotlib (seaborn dependency) is not available for Python 3.5 yet.

**Comment by tritemio** [comment]
@ccordoba12, yes it installs matplotlib 1.4.3, but at least the seaborn package is now present.

**Comment by ccordoba12** [comment]
Yes, they are available now in Anaconda. What I meant is that matplotlib **1.5** is not available yet on Windows, but that's unrelated to this error.

Sorry for the noise :-)
