### ISSUE TITLE
qscintilla no longer packaged with PyQt4 from version 4.11.4?

### ISSUE THREAD

**Issue by dschreij** [ContinuumIO/anaconda-issues#524]
In version 4.11.4 of the pyqt package, qscintilla no longer seems to be present. In version 4.10.4 you could import PyQt4.Qsci, but python can no longer find this module in 4.11.4. Is this intended behavior or did a mistake slip in with the creation of this new package?

**Comment by dschreij** [comment]
In version 4.10.4 and below Qscintilla2 came with the pyqt package on Windows. Now in version 4.11.4 python cannot find it anymore and I get an import error when trying to import from PyQt4.Qsci. Is this intended behavior or did some mistake slip in with version 4.11.4 of this package?

**Comment by msarahan** [comment]
We have historically packaged the PyQt binaries provided by Riverbank Computing.  They do not provide binaries for Python 3.5 (see http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/)

As a result, we have to build from source.  Qsci is (I think) an addon that is not built by default (http://stackoverflow.com/questions/28746247/building-qscintilla2-python-bindings-on-windows7-with-mingw-pyqt4-11-qt4-8-6).  I will look at what it will take to add this back in, but it may be some time before I get to this.  You can try to use the package provided by Christoph Gohlke, http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4 but I don't know if he packages QScintilla with his PyQt, either.

If you figure out how to build it, a PR would be welcome.

**Comment by dschreij** [comment]
Thanks for your reply. I am still on Python 2.7.10 and the issue also occurs there. For now I have reverted to PyQt 4.10.4 which works, but if I find the time I'll try to fix the 4.11.4 version regarding QScintilla.

**Comment by msarahan** [comment]
Yes, the issue occurs there because I didn't want to bifurcate our build system.  PyQt is built from source for all platforms, and that means that QScintilla will be missing from all platforms.  Sorry.  I'll try to be quick about merging anything you might come up with so that it is available again quickly.

**Comment by ccordoba12** [comment]
> if I find the time I'll try to fix the 4.11.4 version regarding QScintilla.

There is no way to fix it, other than repackaging Riverbank installers as conda packages because QScintilla is proprietary.

**Comment by chrisjbillington** [comment]
@ccordoba12 

> QScintilla is proprietary.

Is it? [Riverbank computing says](https://www.riverbankcomputing.com/software/qscintilla/license) it uses the same licensing model as PyQt itself.

**Comment by msarahan** [comment]
I'm pretty sure we're not going to include QScintilla with our PyQt packages.  It's really a separate thing, and I don't think Riverbank should distribute both if the source for one doesn't include the other.  QScintilla2 has a recipe on conda-forge: https://github.com/conda-forge/qscintilla2-feedstock

I recommend using conda-forge's package: ``conda install -c conda-forge qscintilla2``
