### ISSUE TITLE
Deliver bash activate also on windows for use with mingw, msys2, git bash etc.

### ISSUE THREAD

**Issue by MaxNoe** [ContinuumIO/anaconda-issues#525]
Could you deliver the bash version of activate also on windows?
This would be very helpful for using anaconda in the Windows bash versions.

**Comment by msarahan** [comment]
Good idea.  We're a little bit swamped right now, and we might not get to this for a while.  I think all that is necessary is to edit the conda-env deployment scripts (setup.py) to make sure that BOTH the .bat files and the shell files (no extension) get copied.  I think the scripts for Linux/mac should work just as well on Unix-style prompts on Windows.  To try it, you can just copy them from the conda-env source code.  You will need to do ```source activate ...``` for the same reasons that you need to on Mac / Linux.

PR's welcome, if you get things to work.

**Comment by MaxNoe** [comment]
Apparently it's not that simple because of the different directory structure on windows. 
If I add the activate and deactivate files and try to activate an environment I get an error
that the `anaconda/envs/<envname>/bin`directory is not found. Which is of course due to it's non-existance on windows.

**Comment by msarahan** [comment]
Rats, that would have been too easy, I suppose.  Yes, some translation is necessary to go from Windows native representation to CYGWIN-style representation.  How does Virtualenv do it?  https://github.com/pypa/virtualenv/tree/develop/virtualenv_embedded

I don't see any magic translation stuff going on there, but maybe it is embedded in their ```__VIRTUAL_ENV__```

Sorry, no time to work on this now, but again, PRs welcome.

**Comment by MaxNoe** [comment]
I figured out, that the paths are in `conda.cli.activate`. This would need to have same `if sys.platform == 'win32'`-code added.

I think I can manage to add these.

**Comment by msarahan** [comment]
Cool!  Make sure you look at https://github.com/conda/conda/pull/1727 - I hope there's something helpful in there for you.

**Comment by MaxNoe** [comment]
Mmh. Maybe not. Could you maybe shortly explain how the windows structure works? Instead of just `bin`, `.` `Scripts` and `Library/bin` has to go into the path?

**Comment by msarahan** [comment]
It depends on what you want to achieve.  Windows treats shared libraries differently, and keeping them on PATH is necessary.  We have begun moving to keeping dlls and non-Python executables in Library/bin.  This is actually something that was very disruptive with the latest release, and we're working hard to iron that out.  Python processes themselves will soon add Library/bin to PATH for you, so you don't need to worry too much about it - but it is nice to set it, in case people are using environments to provide programs such as git without necessitating a separate git installation.  I just tried this at a Software Carpentry workshop, and it worked fairly well.

Scripts is for, well, scripts.  Conda, activate, deactivate all live here.  Exe's used to all be installed here, but that was a mess, and recipes had to specifically copy stuff to this folder, whereas with the Library/bin approach, we can just set the output prefix to Library, and it adheres to the (much more sane) Unix-style folder layout.

. is for Python.exe, and not much else.

**Comment by MaxNoe** [comment]
Ok. The only problem I still have, is that the new path is joined with `;` where the bash expects `:`

**Comment by MaxNoe** [comment]
Ah, the reason is, that `os.environ['PATH']` returns the windows `PATH`, not the same as `echo $PATH` in a `msys2`-Shell

**Comment by msarahan** [comment]
See also some history: https://github.com/conda/conda/issues/747

**Comment by MaxNoe** [comment]
This behaviour has its root in the way `msys2` handles the windows paths. It only shows unix like paths to the user but works internally with windows paths. And if fails if one exports PATH as windows path. really strange.

**Comment by MaxNoe** [comment]
Ok. running `cygpath -p -u ` on the returned PATH works. But this is ugly i think. One would have to test if `uname -o == Msys`

**Comment by msarahan** [comment]
You've gotta do what you've gotta do.  I don't think this is excessively ugly.  I think it's just simply necessary.  If it works, people will be very appreciative.

**Comment by MaxNoe** [comment]
Only  one problem remains: the symlinking in conda.install.install_conda does not work.

the function `win_hard_link` throws a not specified OSError and `win_soft_link` does not throw an exception but is not doing any linking either.

**Comment by msarahan** [comment]
I think that's done with simple .bat files in the PR I linked above: conda/conda#1727

I have done symlinks on Windows before, but they are really not mainstream.  If you can find a way to do it with bat files instead (or just get things working with that PR), then I think that would be best.  I will get that PR merged hopefully pretty soon, once the dust from the Anaconda 2.4 release settles a bit more.

**Comment by MaxNoe** [comment]
Ok. If scrolled through this pull request and I think it solves every issue besides the PATH handling.

Could you add the lines
```{bash}
if (( $(uname -o) == Msys )); then
  _NEW_PATH=$(cygpath -p -u "$_NEW_PATH")
fi
```
Everywhere, where a new PATH is set?

**Comment by msarahan** [comment]
Sure.  You could also do this yourself: fork my repo, make your changes in a branch, then issue a PR against my branch from that PR (msarahan:wulmer-fix/activate-behaviour-on-windows).  That way, you'll get credit for your work on this.

If you don't want to do that, let me know and I'll just add your stuff in.

**Comment by MaxNoe** [comment]
I will hand in the PR.

**Comment by MaxNoe** [comment]
A question concerning the symlinking: Why should the batch files work? The activate.bat files do not. Why should these?

**Comment by msarahan** [comment]
Yes, I guess I was getting things mixed up.  The bat files are like symlinks for the activate.bat scripts in the root installation.  They aren't connected to the activate (non-bat) scripts in any way.  Sorry for misleading you.  From your PR, it looks like you worked things out.  I will try to get this tested and merged quickly.

**Comment by msarahan** [comment]
For the record: this PR is at https://github.com/msarahan/conda/pull/1

It will be part of https://github.com/conda/conda/pull/1727

Closing this issue.
