### ISSUE TITLE
Launcher 1.0.0 "+ New Env" caused dialog exception

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#532]
I tried to create a new environment from the 1.0.0 Launcher using Python 3.5 as the base and I immediately got this error dialog:

```
Sorry, the application encountered a fatal error. Please report the following to us at https://github.com/ContinuumIO/anaconda-issues.

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)
```

**Comment by ijstokes** [comment]
Even better, after that when I click on the Launcher icon on my desktop I get:
<img width="415" alt="screen shot 2015-11-12 at 6 08 38 pm" src="https://cloud.githubusercontent.com/assets/293525/11134134/80f6f604-8968-11e5-9e06-a0de161760f8.png">
Seems like I managed to fix things with:

```bash
conda install -f -y launcher
```

and then I tried with Python 3.4 and it worked OK.

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
