### ISSUE TITLE
Sorry, the application encountered a fatal error.

### ISSUE THREAD

**Issue by manujdhariwal** [ContinuumIO/anaconda-issues#534]
Not able to start Anaconda Launcher
Downloaded Anaconda 2 Windows 7 64bit version ..... Please help me I require this for my class ....

**Comment by ccordoba12** [comment]
Don't use the Launcher for the time being. Just open a terminal (i.e. `cmd.exe`) and run

    jupyter notebook

if you want to use the notebook.

**Comment by manujdhariwal** [comment]
thanks, although I tried the new launcher (instructions were given in one
of the comments in the forum for a similar problem) and that worked!
thanks though for this ......

**Comment by ccordoba12** [comment]
Ok, glad to know the new Launcher worked for you!

**Comment by Drekko** [comment]
Can you please direct me to the forum that explains how to install the new launcher? I am having the same issue

**Comment by csoja** [comment]
These are the instructions for installing and running another version of the Launcher that may work for you: 

conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher

**Comment by Drekko** [comment]
Sorry tried this fix and still no luck. Successfully installed your other version of your launcher as you can see in cmd prompt in the screenshot, and nothing loads in the launcher...
![untitled](https://cloud.githubusercontent.com/assets/16935659/12692401/8e9b382c-c74a-11e5-9aba-25edf426efcd.png)
