### ISSUE TITLE
Update runipy for compatibility with IPython/Jupyter 4

### ISSUE THREAD

**Issue by cel4** [ContinuumIO/anaconda-issues#535]
currently `runipy` does not seem to work in conda environments on osx. At first glance it seems to be a packaging issue of `ipython`.

`runipy Untitled.ipynb`
```
/Users/ch/miniconda/envs/sci34/lib/python3.4/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/Users/ch/miniconda/envs/sci34/lib/python3.4/site-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)
/Users/ch/miniconda/envs/sci34/lib/python3.4/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "/Users/ch/miniconda/envs/sci34/bin/runipy", line 4, in <module>
    from runipy.main import main
  File "/Users/ch/miniconda/envs/sci34/lib/python3.4/site-packages/runipy/main.py", line 14, in <module>
    from IPython.config import Config
ImportError: bad magic number in 'IPython.config': b'\x03\xf3\r\n'
```

installing `runipy` into a clean virtualenv seems to work.

**Comment by ccordoba12** [comment]
This seems to be caused because the `runipy` version we're distributing is not compatible with IPython/Jupyter 4.

We'll update `runipy` as soon as possible to fix that.

**Comment by cel4** [comment]
@ccordoba12, I have also tried replacing conda's `runipy` version by the latest checkout from github in my environment with the latest version of anaconda. For me that does not work, so I assume the problem lies deeper down.

**Comment by ccordoba12** [comment]
Then please report this problem with the runipy developers :-)

**Comment by cel4** [comment]
The issue is probably in your code base not in runipy's. At least I do not see it in a non-conda virtualenv with pip installed `runipy` and `jupyter`.

**Comment by cel4** [comment]
This has been caused by leftover files in `lib/site-packages/IPython` and is not reproducible. Removing the directory with `rm -r` and reinstalling via `conda install ipython` fixed it. Closing as non-issue.
