### ISSUE TITLE
ipython-qtconsole update fail

### ISSUE THREAD

**Issue by inivri** [ContinuumIO/anaconda-issues#538]
Application encountered fatal error during qtconsole update from Launcher.
Alert requested this issue reported here.

**Comment by ccordoba12** [comment]
Please don't use the Launcher to update packages. It doesn't work reliably, so it's better to use a terminal (`cmd.exe`) and run

    conda update qtconsole

**Comment by inivri** [comment]
Terminal it is. Thank you.

**Comment by ccordoba12** [comment]
Great!
