### ISSUE TITLE
Qt DLL version conflicts

### ISSUE THREAD

**Issue by nicktimko** [ContinuumIO/anaconda-issues#540]
Many other applications use Qt, MikTeX, TortoiseHG, GraphViz, etc, and when working on the command line, it's convenient to have their bin folders on the PATH. It also seems to result in DLL Hell (oh the glory days), as their versions are subtlety different, and the wrong one might be selected among, e.g.:
```
D:\Code> where.exe QtGui4.dll
C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\QtGui4.dll
C:\Program Files\TortoiseHg\QtGui4.dll
C:\Program Files (x86)\Graphviz2.38\bin\QtGui4.dll
C:\Users\Nick\Anaconda3\Library\bin\QtGui4.dll
```
This seems to result in Anaconda's Matplotlib (the most frequent Qt-dependent app I use) grabbing the wrong one, and I get:
```
Python 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Nov  7 2015, 13:15:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  [...]
  File "C:\Users\Nick\Anaconda3\lib\site-packages\matplotlib\backends\qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: DLL load failed: The specified procedure could not be found.
```

If I run `python` from the `Anaconda3\Library\bin` folder, it works fine, presumably because that's the [#2 search location for DLLs](https://msdn.microsoft.com/en-us/library/7d83bc18.aspx). I did attempt #&#65279;1 as per MSDN and copied `Qt*.dll` from `Library\bin` into the Anaconda root with `python.exe`, but for some reason that didn't work.

As per Michael's suggestion on [the Google Group's thread](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/vcY-P7MBwo0), flipping the joining of paths to `PATH` worked (in `site.py`, line 173 in the release above). The ordering isn't the cleanest, perhaps, but it's a workable workaround.

```diff
 if sys.prefix == sitedir:
-   os.environ["PATH"]=os.pathsep.join([os.environ["PATH"], dir])
+   os.environ["PATH"]=os.pathsep.join([dir, os.environ["PATH"]])
 sys.path.append(dir)
```

**Comment by divenex** [comment]
In my case, with Windows 10 64bit, and the same version of Anaconda as above, Matplotlib is imported correctly. However, when I move the mouse on top of a figure generated by Matplotlib, Python crashes.

For now I solved the issue by changing the order of the system paths by hand, so that Anaconda is before the rest. This stopped the Python crashes.

The conflicting QtGui4.dll was provided by MikTeX.

**Comment by aeferreira** [comment]
In my case, also with Windows 10 64bit, and a Miniconda python 3.5 install, the conflicting QtGui4.dll was located at **windows\system32**. That is the the [#3 search location for DLLs](https://msdn.microsoft.com/en-us/library/7d83bc18.aspx) and was being used before any others on the search PATH. It didn't matter where in the PATH were the Miniconda's dlls.

**Renamed the Qt related dlls in windows\system32**, (left from some very old install of some application, that I can no longer recall), and it worked. Finally I can do *from matplotlib import pyplot as pl* (and also run something as awesome as the anaconda navigator which was giving similar errors).

**Comment by ccordoba12** [comment]
@aeferreira, thanks for mentioning the problems with `windows\system32`. As you said, anything in there is used before any other library in PATH, so there's nothing we can do about that :-)

**Comment by stephenakearns** [comment]
@ccordoba12 - can this issue be closed? Or is there a next step here?

**Comment by ccordoba12** [comment]
We can't really do anything about this ones. If there are conflicts with our Qt copy, that's because other programs install their copies of Qt in `C:\Windows\System32`.

**Comment by nicktimko** [comment]
@ccordoba12 I'm not much of a Windows dev, but as per [that MSDN article](https://msdn.microsoft.com/en-us/library/7d83bc18.aspx), (supposedly) the process' executable directory and current directory are searched before the system path. I mentioned trying to put the packaged DLL into the path with `python.exe`, but that didn't work and I don't know why (if the "process" is really something else, different Windows version, etc, etc.). If that problem was figured out then maybe it would be fixable.

This is probably deviating from my original gripe though, so maybe @aeferreira could open another issue for that if it's still a nuisance 😉

**Comment by ccordoba12** [comment]
> I mentioned trying to put the packaged DLL into the path with python.exe, but that didn't work and I don't know why

I think Qt dll's would need to be put next to PyQt dll's (i.e. in `site-packages`) for this approach to work. But that deviates from our current practice, which is putting dll's in `Library\bin`.

When you activate an environment (or add Anaconda to your `PATH`), we always put `Library\bin` in front of `PATH`, so the *only* situation we can't deal with is dll's in `C:\Windows\System32`. But that's a really bad practice from other programs :-)
