### ISSUE TITLE
logilab-common is not available for Python 3.5 on Windows, which prevents installing pylint

### ISSUE THREAD

**Issue by bilderbuchi** [ContinuumIO/anaconda-issues#543]
I just downloaded and installed latest Anaconda3, 64bit, 2.4.0, for Windows, Python 3.5, conda 3.18.5. After updating everything, and installing a couple of other packages, I try to install pylint, but I get 
```
Z:\>conda install pylint
Fetching package metadata: ....
Solving package specifications: ............
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - pylint
  - python 3.5*

Use 'conda info pylint' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14
```
Running `conda info pylint` as suggested yields (among a load of others) one section involving py35:
```
pylint 1.4.2 py35_0
-------------------
file name   : pylint-1.4.2-py35_0.tar.bz2
name        : pylint
version     : 1.4.2
build number: 0
build string: py35_0
channel     : defaults
size        : 246 KB
date        : 2015-10-31
license     : GPL
license_family: GPL2
md5         : 39b28ee413f6960a1dc1d89c12e48638
installed environments:
dependencies:
    astroid 1.3.4
    python 3.5*
```
but I can't recognize anything actionable for me. It conflicts with its own dependency?!
Why is this failing, as there seems to be a version available? How can I fix this?

**Comment by ccordoba12** [comment]
Nop, this means that there's no Pylint package available right now for Python 3.5.

**Comment by bilderbuchi** [comment]
possibly connected: #523

**Comment by bilderbuchi** [comment]
> Nop, this means that there's no Pylint package available right now for Python 3.5.

but it's right there in the list from `conda info`?

**Comment by ccordoba12** [comment]
Then there are not packages available for its dependencies.

Pinging @msarahan about this one.

**Comment by bilderbuchi** [comment]
I climbed down the dependency tree, and the culprit seems to be logilab-common 1.0.2, for which no py35 build is available.

**Comment by ccordoba12** [comment]
Pinging @msarahan about this one. It should be an easy fix.

**Comment by bilderbuchi** [comment]
I just retried the install, and it seems logillab-common was updated in the meantime - Installation worked! Thank you.
