### ISSUE TITLE
Pip install of Theano on top of current anaconda + mkl not linking correctly

### ISSUE THREAD

**Issue by JamesOwers** [ContinuumIO/anaconda-issues#547]
Hello,

I'm having problems with location of dylibs for mkl. Please see this linked issue where I describe how to reproduce the issue and and the diagnosis by people working on Theano. https://github.com/Theano/Theano/issues/3630#issuecomment-158194897

**Comment by jfsantos** [comment]
I have the same issue with current Anaconda (Python 3.4) and dev version of Theano.

**Comment by dougalsutherland** [comment]
Just a note that this is still an issue. It would presumably be helped by using `@rpath` in the install_name of the MKL libraries, but I haven't played around with it yet.

**Comment by cranmer** [comment]
+1

**Comment by cranmer** [comment]
I've tried also `THEANO_FLAGS='blas.ldflags=' jupyter notebook <notebook>` but that's not working for me either.

**Comment by arogozhnikov** [comment]
facing same issue on travis (with nomkl, haha). Appeared ~3 days ago.  (but only for python 3, python 2 run smoothly).
I am quite sure this is somewhat inside conda changed. 
Failed job: https://travis-ci.org/arogozhnikov/hep_ml/builds/113947777

**Comment by arogozhnikov** [comment]
I have no idea what was changed - conda packages or conda itself, but I rerun the same built today - and it passed.
