### ISSUE TITLE
Can't start navigator on Mac(10.11.6)

### ISSUE THREAD

**Issue by michael-lin-zdaly** [ContinuumIO/anaconda-issues#5479]
When I use `anaconda-navigator`, after initializing... message, it quits in a second and i got

```
Traceback (most recent call last):
  File "/Users/linjinghao/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6
```

**Comment by goanpeca** [comment]
@michael-lin-zdaly you are using a deprecated version of navigator. Please update to the latest one (1.6.4)

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
