### ISSUE TITLE
Can't import matplotlib.pyplot with anaconda, windows 10

### ISSUE THREAD

**Issue by samuelmurray** [ContinuumIO/anaconda-issues#548]
After installing anaconda on my windows 10 PC, IntelliJ gives me an error message: "Qt: Untested Windows version 10.0 detected!" when trying to import matplotlib.pyplot. The program compiles and runs, though if I try to plot something and show the plots, the program crashes. Is there a known solution to this? I tried updating to Qt5 (through 'conda install'), but I'm not sure if (and how) I have configure something after doing this?

**Comment by msarahan** [comment]
Please try updating Qt to version 4.8.7.  We have patched this issue in that version.  Qt5 is not compatible with Qt4 applications.

**Comment by samuelmurray** [comment]
I uninstalled Qt5 with "conda remove Qt5", and when running this code:
from PyQt4.QtCore import QT_VERSION_STR
print("Qt version:", QT_VERSION_STR)
I still get the error + output:
Qt: Untested Windows version 10.0 detected!
Qt version: 4.8.7

**Comment by msarahan** [comment]
What is the output of ```conda list```?

**Comment by samuelmurray** [comment]
alabaster                 0.7.6                    py35_0
anaconda                  2.4.0               np110py35_0
anaconda-client           1.1.0                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.0.5               np110py35_1
babel                     2.1.1                    py35_0
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.8.3                     <pip>
blaze-core                0.8.3                    py35_0
bokeh                     0.10.0                   py35_0
boto                      2.38.0                   py35_0
bzip2                     1.0.6                    vc14_2  [vc14]
cffi                      1.2.1                    py35_0
clyent                    0.4.0                    py35_0
colorama                  0.3.3                    py35_0
comtypes                  1.1.2                    py35_0
conda                     3.18.5                   py35_0
conda-build               1.18.1                   py35_0
conda-env                 2.4.4                    py35_2
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
cryptography              1.0.2                    py35_0
curl                      7.45.0                   vc14_0  [vc14]
cython                    0.23.4                   py35_0
cytoolz                   0.7.4                    py35_0
datashape                 0.4.7               np110py35_1
decorator                 4.0.4                    py35_0
docutils                  0.12                     py35_1
fastcache                 1.0.2                    py35_0
flask                     0.10.1                   py35_1
freetype                  2.5.5                    vc14_0  [vc14]
greenlet                  0.4.9                    py35_0
h5py                      2.5.0               np110py35_4
hdf5                      1.8.15.1                 vc14_3  [vc14]
icu                       54.1                          0
idna                      2.0                      py35_0
ipykernel                 4.1.1                    py35_0
ipython                   4.0.0                    py35_1
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_3
ipython-qtconsole         4.0.1                    py35_4
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.0                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.0                      py35_0
jedi                      0.9.0                    py35_0
jinja2                    2.8                      py35_0
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.4.0                    py35_0
jupyter                   1.0.0                    py35_0
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0
jupyter_console           4.0.3                    py35_0
jupyter_core              4.0.6                    py35_0
launcher                  1.0.0                         4
libpng                    1.6.17                   vc14_1  [vc14]
libsodium                 1.0.3                         0
libtiff                   4.0.6                    vc14_0  [vc14]
lxml                      3.4.4                    py35_0
markupsafe                0.23                     py35_0
matplotlib                1.4.3               np110py35_3
menuinst                  1.2.1                    py35_0
mistune                   0.7.1                    py35_0
msvc_runtime              1.0.1                    vc14_0  [vc14]
multipledispatch          0.4.8                    py35_0
nbconvert                 4.0.0                    py35_0
nbformat                  4.0.1                    py35_0
networkx                  1.10                     py35_0
nltk                      3.1                      py35_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py35_0
notebook                  4.0.6                    py35_0
numexpr                   2.4.4               np110py35_0
numpy                     1.10.1                   py35_0
odo                       0.3.4                    py35_0
openpyxl                  2.2.6                    py35_0
openssl                   1.0.2d                   vc14_0  [vc14]
pandas                    0.17.0              np110py35_0
path.py                   8.1.2                    py35_0
patsy                     0.4.0               np110py35_0
pep8                      1.6.2                    py35_0
pickleshare               0.5                      py35_0
pillow                    3.0.0                    py35_1
pip                       7.1.2                    py35_0
ply                       3.8                      py35_0
psutil                    3.2.2                    py35_0
py                        1.4.30                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_0
pycparser                 2.14                     py35_0
pycrypto                  2.6.1                    py35_3
pycurl                    7.19.5.1                 py35_1
pyflakes                  1.0.0                    py35_0
pygments                  2.0.2                    py35_0
pyopenssl                 0.15.1                   py35_1
pyparsing                 2.0.3                    py35_0
pyqt                      4.11.4                   py35_3
pyreadline                2.1                      py35_0
pytables                  3.2.2               np110py35_1
pytest                    2.8.1                    py35_0
python                    3.5.0                         3
python-dateutil           2.4.2                    py35_0
pytz                      2015.6                   py35_0
pywin32                   219                      py35_1
pyyaml                    3.11                     py35_2
pyzmq                     14.7.0                   py35_1
qt                        4.8.7                    vc14_4  [vc14]
qtconsole                 4.1.0                    py35_0
requests                  2.8.1                    py35_0
rope                      0.9.4                    py35_1
rope-py3k-0.9.4           1                         <pip>
scikit-image              0.11.3              np110py35_0
scikit-learn              0.16.1              np110py35_0
scipy                     0.16.0              np110py35_0
setuptools                18.4                     py35_0
simplegeneric             0.8.1                    py35_0
sip                       4.16.9                   py35_2
six                       1.10.0                   py35_0
snowballstemmer           1.2.0                    py35_0
sockjs-tornado            1.0.1                    py35_0
sphinx                    1.3.1                    py35_0
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py35_0
spyder                    2.3.7                    py35_3
spyder-app                2.3.7                    py35_0
sqlalchemy                1.0.9                    py35_0
statsmodels               0.6.1               np110py35_0
sympy                     0.7.6.1                  py35_0
tables                    3.2.2                     <pip>
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.7.4                    py35_0
tornado                   4.2.1                    py35_1
traitlets                 4.0.0                    py35_0
ujson                     1.33                     py35_0
unicodecsv                0.14.1                   py35_0
werkzeug                  0.10.4                   py35_0
wheel                     0.26.0                   py35_1
xlrd                      0.9.4                    py35_0
xlsxwriter                0.7.7                    py35_0
xlwings                   0.4.1                    py35_0
xlwt                      1.0.0                    py35_0
zeromq                    4.1.3                    vc14_1  [vc14]
zlib                      1.2.8                    vc14_2  [vc14]

**Comment by msarahan** [comment]
Thanks.  You do have the correct version of Qt.  Do you have any other software installed that has Qt?  If it comes earlier in PATH, you may be getting other Qt dlls.  See issue https://github.com/ContinuumIO/anaconda-issues/issues/540

We have a fix (prepend Library/bin) that should be available soon.  If you're up for it, you can apply the fix mentioned in that issue.  Please let us know if it does not work.

**Comment by samuelmurray** [comment]
This did indeed fix it! Now both the test code above, and my full program with pyplot work without error messages or crashes. Thanks alot :)

Ps. Is this a 'bad' fix, so that I should revert it when you release the official fix? Ds.

**Comment by msarahan** [comment]
This is not a "bad" fix.  It will be overwritten by the next Python update, but your functionality should be exactly the same.  Just leave things as they are and don't worry about it.  Let us know if you run into further issues.

Closing this issue.
