### ISSUE TITLE
Navigator Home is empty

### ISSUE THREAD

**Issue by ahnugent** [ContinuumIO/anaconda-issues#5480]
I upgraded to Navigator 1.6.4 and now there are no apps (Spyder, Jupyter, etc.) on the Home screen.

**Comment by goanpeca** [comment]
@ahnugent please open the terminal/Prompt and type

```
$ anaconda-navigator --reset
$ anaconda-navigator
```

And try again. Also please share any traceback appearing on the console.

**Comment by ahnugent** [comment]
Right, now we're back to the old problem: Navigator opens, with all apps displayed in the Home page, then closes after about 1 second. Here is the traceback:

(prospecting) C:\Users\allen>anaconda-navigator --reset
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
QWindowsFontDatabase::createEngine: CreateFontFromLOGFONT failed ()
Traceback (most recent call last):
  File "C:\Users\allen\Anaconda3\envs\prospecting\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'

**Comment by goanpeca** [comment]
@ahnugent you are back to using an old version of navigator... ????

**Comment by ahnugent** [comment]
Seems to be fixed after a reboot.
Thanks!
