### ISSUE TITLE
openmpi and krb5 both built incorrectly on OSX

### ISSUE THREAD

**Issue by pelson** [ContinuumIO/anaconda-issues#549]
Please see my comment at https://github.com/ioos/conda-recipes/pull/605#issuecomment-158295040.
Essentially, the /opt/anaconda1anaconda2anaconda3 prefix isn't being set when these packages are installed, thus making at least openmpi unusable on OSX.

**Comment by groutr** [comment]
Thank you for the detailed report (in your other comment).  Hopefully we can remedy this soon.
Tagging @ilanschnell

**Comment by pelson** [comment]
I wonder if we should make it easy to test this kind of thing in conda-build.
That is, beyond the:

```
test:
   commands:
      - grep anaconda1anaconda2 $PREFIX -r | [ $(wc -l) -eq 0 ]
```

**Comment by groutr** [comment]
I wonder if the `build:detect_binary_files_with_prefix` option in conda-build already does this.
