### ISSUE TITLE
Update glueviz to 0.6

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#550]
[glueviz v0.6](https://pypi.python.org/pypi/glueviz/0.6.0) has now been released - could you update the conda package accordingly? There are a couple of other changes that should be made:

* The ``xlrd`` pacakge should be added as a dependency
* The ``ipython-console`` dependency should be removed and replaced by ``ipykernel`` and ``qtconsole`` (this is due to the changes in IPython 4)

There is no compiled code in glueviz, so you may also be able to avoid tying it to a specific Numpy version (since I know you've been doing that wherever possible recently)

Thanks!

**Comment by astrofrog** [comment]
I noticed today that glueviz 0.6 is available via conda - however quite a few of the dependencies have been removed (ipython, h5py, scipy) and the ones mentioned above (xlrd, ipykernel, and qtconsole) at not included. Would it be possible to add these? Thanks!

**Comment by ilanschnell** [comment]
Ok,  added them back in.  This is the list now.  I'll make new packages today.
```
    - pandas
    - astropy
    - matplotlib
    - ipython
    - h5py
    - scipy
    - xlrd
    - ipykernel
    - qtconsole
```

**Comment by astrofrog** [comment]
@ilanschnell - thanks! There are a few dependencies missing from your list, in particular PyQt and Numpy

The full list should be:

```
    - pyqt
    - numpy
    - pandas
    - astropy
    - matplotlib
    - ipython
    - ipykernel
    - qtconsole
    - h5py
    - scipy
    - xlrd
```

Note that while Numpy is in that list, it's only a run-time dependency so the conda package doesn't need to be tidied to a specific Numpy version.

In addition, the package provides a script (``glue``) that should be treated as a GUI executable on MacOS X, in other words if you were using recipes, you'd need:

```
build:
  osx_is_app: True
```

which will then also include ``python.app`` into the dependency list.

Let me know if you need any more details!

**Comment by astrofrog** [comment]
This was fixed a while back - thanks @ilanschnell!
