### ISSUE TITLE
Can't launch Qtconsole nor spyder

### ISSUE THREAD

**Issue by jelmelk** [ContinuumIO/anaconda-issues#552]
Just before the problem started, I ran `conda install graphviz`. The installation completed without errors, but I can't use Qtconsole nor spyder.

**Spyder** does not load at all. **Qtconsole** shows this error after attempting to launch from the Launcher:
![Imgur](http://i.imgur.com/ygMOzsu.png)

**Comment by ccordoba12** [comment]
I think you need to run

    conda update python

to fix this problem.

**Comment by jelmelk** [comment]
I'm gonna close this issue then reopen it with conda. I didn't test if your method words, but I had to do `conda install -f qt` to force a re-installation of qt.

I did that because when I did `conda install spyder` it gave me an error that PyQt4 didn't exist. I can now run Qtconsole and Spyder, but the module I installed isn't working.
