### ISSUE TITLE
Navigator does not allow environment creation for root-installed Anaconda

### ISSUE THREAD

**Issue by phonque** [ContinuumIO/anaconda-issues#5532]
Hi,

I posted the issue below to the Continuum Anaconda Google group and was requested to post it here as well.
--------------------
I installed Anaconda, but I'm unable to create a new environment using the Anaconda Navigator: the 'Create' button is grayed out.
Below the printscreen and some anaconda system details.

I did manage to create an environment using the command line conda, though. After that, I'm still not able to create a new environment using Navigator.

Cheers,
Jasper

Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /anaconda  (writable)
    default environment : /anaconda
       envs directories : /anaconda/envs
                          /Users/username/.conda/envs
          package cache : /anaconda/pkgs
                          /Users/username/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/username/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20
<img width="458" alt="anaconda environment error incl name" src="https://user-images.githubusercontent.com/9309352/30475593-a50b9444-9a07-11e7-9055-161b56b60fb9.png">

**Comment by goanpeca** [comment]
@phonque did you use the graphical installer or the bash installer?

**Comment by phonque** [comment]
@goanpeca I did use the graphical installer

**Comment by goanpeca** [comment]
@phonque then this is a non issue cause we do not support OSX all users install. If you were able to do it it was because of a bug in OSX 10.XX something :-p

**Comment by phonque** [comment]
@goanpeca I chose to install a personal version, using the graphical installer. I de-installed the Anaconda which showed the 'error' and just performed a new installation, following the exact same steps. Surprise surprise: I'm now able to create a new environment using the Navigator!?-->
a location appears and this did not happen the first time....

<img width="685" alt="anaconda working environment" src="https://user-images.githubusercontent.com/9309352/30493177-72b7f03c-9a43-11e7-9d95-28e34fa49df4.png">

**Comment by goanpeca** [comment]
@phonque exactly what I expected to happen XD

**Comment by olisteadman** [comment]
Would it be possible to clarify this in the documentation (or point to any existing instruction that warns users not to "install to all", if they want to be able to use GUI to create envs)?

This Would be a big help to first-time users, who might not otherwise realise, and end up having to install it twice (as has happened above for @phonque).

**Comment by lconde-ucl** [comment]
@IselinaH I am having the exact same issue, did you figure out how to fix it?

**Comment by lconde-ucl** [comment]
@IselinaH I'm having the same issue. Did you figure out how to fix it?

**Comment by lconde-ucl** [comment]
@IselinaH instead of creating a separate conda env for R, I integrated R into Jupyter notebooks within my existing R installation by installing the R kernel package:

% R
> install.packages('IRkernel')
> IRkernel::installspec(user = TRUE)
