### ISSUE TITLE
Launcher unable to install qt-console

### ISSUE THREAD

**Issue by jjstarn-usgs** [ContinuumIO/anaconda-issues#554]
I installed miniconda3 (downloaded 11/23/2015). Then 'activate' and 'conda install launcher'. WHen installing qt-concole from the launcher, I get the message:

'Sorry, the application encountered a fatal error. Please report the following to us at (here).'

There were no messages that followed.

**Comment by rsignell-usgs** [comment]
I worked with @jjstarn-usgs on this a bit, and we found out that that **bad things happen when you type `activate` or `launcher` from the anaconda root environment directory**.   

Changing to another directory solved the problem.

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
