### ISSUE TITLE
Creating an environment fails with "post-link failed for..."

### ISSUE THREAD

**Issue by stmax82** [ContinuumIO/anaconda-issues#555]
I'm trying to create a new environment. I get several "The system cannot find the file specified." errors followed by the error "post-link failed for: pyqt-4.11.4-py34_3".

OS is Win8 x64, conda version is 3.18.5.

Below is the complete console output.

C:...>conda create -p pyenv python=3.4 scikit-learn pandas matplotlib scipy ipython-notebook
Fetching package metadata: ....
Solving package specifications: ........................
Package plan for installation in environment C:...\pyenv:

The following packages will be downloaded:

| package | build |
| --- | --- |
| libtiff-4.0.6 | vc10_1         465 KB |
| setuptools-18.5 | py34_0         652 KB |
| cycler-0.9.0 | py34_0           6 KB |
| matplotlib-1.5.0 | np110py34_0         6.2 MB |
| pandas-0.17.1 | np110py34_0         5.9 MB |

```
------------------------------------------------------------
                                       Total:        13.2 MB
```

The following NEW packages will be INSTALLED:

```
cycler:           0.9.0-py34_0
decorator:        4.0.4-py34_0
ipykernel:        4.1.1-py34_0
ipython:          4.0.0-py34_1
ipython-notebook: 4.0.4-py34_3
ipython_genutils: 0.1.0-py34_0
jinja2:           2.8-py34_0
jpeg:             8d-vc10_0          [vc10]
jsonschema:       2.4.0-py34_0
jupyter_client:   4.1.1-py34_0
jupyter_core:     4.0.6-py34_0
libpng:           1.6.17-vc10_1      [vc10]
libsodium:        1.0.3-0
libtiff:          4.0.6-vc10_1       [vc10]
markupsafe:       0.23-py34_0
matplotlib:       1.5.0-np110py34_0
mistune:          0.7.1-py34_0
msvc_runtime:     1.0.1-vc10_0       [vc10]
nbconvert:        4.0.0-py34_0
nbformat:         4.0.1-py34_0
notebook:         4.0.6-py34_0
numpy:            1.10.1-py34_0
openssl:          1.0.2d-vc10_0      [vc10]
pandas:           0.17.1-np110py34_0
path.py:          8.1.2-py34_0
pickleshare:      0.5-py34_0
pip:              7.1.2-py34_0
pygments:         2.0.2-py34_0
pyparsing:        2.0.3-py34_0
pyqt:             4.11.4-py34_3
pyreadline:       2.1-py34_0
python:           3.4.3-4
python-dateutil:  2.4.2-py34_0
pytz:             2015.7-py34_0
pyzmq:            14.7.0-py34_1
qt:               4.8.7-vc10_4       [vc10]
scikit-learn:     0.17-np110py34_1
scipy:            0.16.0-np110py34_0
setuptools:       18.5-py34_0
simplegeneric:    0.8.1-py34_0
sip:              4.16.9-py34_2
six:              1.10.0-py34_0
tk:               8.5.18-vc10_0      [vc10]
tornado:          4.2.1-py34_1
traitlets:        4.0.0-py34_0
wheel:            0.26.0-py34_1
zeromq:           4.1.3-vc10_1       [vc10]
zlib:             1.2.8-vc10_2       [vc10]
```

Proceed ([y]/n)? y

Fetching packages ...
libtiff-4.0.6- 100% |###############################| Time: 0:00:00 476.46 kB/s
setuptools-18. 100% |###############################| Time: 0:00:01 548.27 kB/s
cycler-0.9.0-p 100% |###############################| Time: 0:00:00   3.05 MB/s
matplotlib-1.5 100% |###############################| Time: 0:00:07 869.22 kB/s
pandas-0.17.1- 100% |###############################| Time: 0:00:07 849.03 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
The system cannot find the path specified.###                            |  45%
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the file specified.###############                |  68%
Error: Error: post-link failed for: pyqt-4.11.4-py34_3

C:...>

**Comment by stmax82** [comment]
I noticed that the problem only happens when one of the parent directories contains a "!" character. :)

**Comment by FailSafe86** [comment]
Having the same issue right now, did you manage to solve it?

**Comment by msarahan** [comment]
Sorry, this might also be a package installation order problem.  The Qt package creates a file that the PyQt packages uses.  Unfortunately, packages are getting installed alphabetically.  We are working on this issue.  For now, a workaround is to just reinstall pyqt after activating your new env:

conda install -f pyqt

**Comment by stmax82** [comment]
For me the problem only happens when I'm in some directory that contains a "!" bang character. The error hasn't happend again since I moved all my projects into another directory.

I just tried this and it's still reproducible:

```
cd c:\temp
conda create -p pyenv python=3.4 scikit-learn pandas matplotlib scipy ipython-notebook
```
=> works flawlessly

```
mkdir c:\temp\bang!
cd c:\temp\bang!
conda create -p pyenv python=3.4 scikit-learn pandas matplotlib scipy ipython-notebook
```
=> fails with error:

```
The system cannot find the path specified.
The system cannot find the file specified.
Error: Error: post-link failed for: pyqt-4.11.4-py34_4
```

**Comment by tombardo** [comment]
I am having a similar issue trying to setup a new environment with

conda create -n py34 python=3.4 anaconda

This fails during linking with:

`ipython-qtcons 100% |###############################| Time: 0:00:00   1.31 MB/s
ipywidgets-4.1 100% |###############################| Time: 0:00:00   2.68 MB/s
spyder-2.3.8-p 100% |###############################| Time: 0:00:00   8.39 MB/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00 562.04 kB/s
spyder-app-2.3 100% |###############################| Time: 0:00:00   2.53 MB/s
anaconda-2.5.0 100% |###############################| Time: 0:00:00   1.41 MB/s

Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
The system cannot find the path specified.####                           |  46%
Error: Error: post-link failed for: qt-4.8.7-vc10_5`

I have then tried to force install of qt and pyqt with no success:

`conda install -f qt
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
   qt
Use "conda info <package>" to see the dependencies for each package.`

Also if I do a conda list on the new environment any package that comes alphabetically after pyqt is not installed.  Any thoughts or suggestions?

**Comment by stmax82** [comment]
Problem seems to be fixed - I cannot reproduce it anymore. Close?

**Comment by tombardo** [comment]
I haven’t tried in a while. I say close it.

 

Tom

**Comment by msarahan** [comment]
Thanks for checking on this.
