### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by luismiguells** [ContinuumIO/anaconda-issues#5557]
When I try to open Anaconda Navigator from here:

![captura de pantalla de 2017-09-15 13-16-36](https://user-images.githubusercontent.com/25065697/30497400-56c88ede-9a18-11e7-8a5c-6331465fee8d.png)
Give this:

![captura de pantalla de 2017-09-15 13-19-04](https://user-images.githubusercontent.com/25065697/30497433-7b604a16-9a18-11e7-80a1-a5ac550356e4.png)

I can open from the terminal using `anaconda-navigator I'm using Ubuntu 16.04 LTS and the latest version of Acanconda.

**Comment by goanpeca** [comment]
@luismiguells we do not officially support a launcher icon on linux so please use the terminal and make sure the root environment is properly activated

```
$ source activate root
$ anaconda-navigator
```
