### ISSUE TITLE
Better error message if dependencies are incompatible

### ISSUE THREAD

**Issue by bilderbuchi** [ContinuumIO/anaconda-issues#556]
Recently, I tried to install pylint (#543), and I got this error message:

```
Z:\>conda install pylint
Fetching package metadata: ....
Solving package specifications: ............
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - pylint
  - python 3.5*

Use 'conda info pylint' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14
```

Pylint conflicts with python 3.5? Interesting, because running `conda info pylint` as the error message suggested yields (among a load of others) one section involving py35:

```
pylint 1.4.2 py35_0
-------------------
file name   : pylint-1.4.2-py35_0.tar.bz2
name        : pylint
version     : 1.4.2
build number: 0
build string: py35_0
channel     : defaults
size        : 246 KB
date        : 2015-10-31
license     : GPL
license_family: GPL2
md5         : 39b28ee413f6960a1dc1d89c12e48638
installed environments:
dependencies:
    astroid 1.3.4
    python 3.5*
```

so, it seems pylint conflicts with its own dependency (while at the same time offering a version for py35)?!?

Some helpful hints reveal that it's a _dependency_  of pylint that fails here (in this case: logilab-common did not have a py35 version out yet), but the error message does not in any way imply that that could be the cause - the user has to manually climb down the dependency tree to find out (easy with pylint, as it was only 2 steps, but this could be pretty involved, especially with a branching dependency tree). 

It would be great if the error message would be more expressive about the fact that a dependency is incompatible, not the package-to-install itself.

**Comment by nehaljwani** [comment]
This issue was moved to conda/conda#5387
