### ISSUE TITLE
RasterIO example thows a TypeError

### ISSUE THREAD

**Issue by samsammurphy** [ContinuumIO/anaconda-issues#5566]
## Expected behavior and actual behavior.

Following the windows decimation example:
https://mapbox.s3.amazonaws.com/playground/perrygeo/rasterio-docs/windowed-rw.html?#decimation

It defines a numpy array 'r'. The subsequent rasterio.open() method uses the dtype attribute of this array. This raises a TypeError

```
raise TypeError("invalid dtype: {0!r}".format(dtype))
TypeError: invalid dtype: dtype('uint8')
```
using `np.uint8` instead seems to work.

## Steps to reproduce the problem.

1) conda environment with python=3.5.4
2) conda install rasterio
3) try the window decimation example:
https://mapbox.s3.amazonaws.com/playground/perrygeo/rasterio-docs/windowed-rw.html?#decimation

## Operating system

Linux Mint 18

**Comment by csoja** [comment]
Anaconda's rasterio was rebuilt and uploaded most recently on Nov 29th, 2017.  However, it sounds like perhaps a rasterio documentation issue - I would suggest opening the issue on https://github.com/mapbox/rasterio/issues

**Comment by clausTue** [comment]
probelm persists here  with 

    rasterio:   0.36.0-py36hb8ea33a_1

**Comment by msarahan** [comment]
@clausTue Please file this issue on the rasterio github issue tracker (https://github.com/mapbox/rasterio)

Data type conversions like you demonstrate are not a problem introduced with how we build packages - it is certainly a problem with how rasterio is assuming things about input data, and how it is handling (or not handling) implicit type conversion or type equivalency.

**Comment by msarahan** [comment]
PS: I believe this may be an issue with newer numpy versions.  You may want to try to install an older numpy version to see if this helps.  Ultimately, the fix will still be in rasterio, but pinning to an older numpy version may help bridge the gap.  If you do discover a specific numpy version that works, we can potentially change our current rasterio packages to limit them appropriately.
