### ISSUE TITLE
Missing package: libpython 3.5

### ISSUE THREAD

**Issue by tugrulxyz** [ContinuumIO/anaconda-issues#561]
Hi,

I am trying to install theano dependencies using 

conda install mingw libpython

and get 

Hint: the following packages are in conflict with each other:
 - libpython
 - python 3.5*

any chance that libpython 3.5 can be added soon?

thanks

**Comment by gpatera** [comment]
I had to downgrade to anaconda 2.3 with python 3.4 and then it worked. Definitely it's a problem with 3.5

**Comment by msarahan** [comment]
As far as I know, mingw has not added compatibility with the msvc 2015 compiler that is standard for python 3.5.  We can't provide libpython until that support exists.

**Comment by ccordoba12** [comment]
@tugrulxyz, if you need to compile Python extensions, we sincerely recommend you to use Visual Studio instead of MinGW. It's much more stable and reliable, specially on Windows 64.

**Comment by tugrulxyz** [comment]
creating a python 3.4 env did the trick. thanks for the replies.

**Comment by rilut** [comment]
Talking about Python 3.5, MSVC 2015 and Theano, can I use Theano with MSVC 2015? I set my .THEANORC to
```
[global]
device = cpu
cxx=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe
```
But I can't get it to run. Do I still need to provide libpython 3.5? Any idea that I can provide libpython 3.5 manually?

**Comment by soupault** [comment]
I second @rilut . If someone could describe how to build `libpython` for Py3.5, I'd help with creating a `.whl`. It would be perfect as a temporary solution.

**Comment by jzuhone** [comment]
@ccordoba12 not necessarily an option for all of us to use MSVC 2015, by the way.

**Comment by ccordoba12** [comment]
@jzuhone, as I said, it's our recommendation, and the best option (in terms of stability and robustness) according to my experience. Sorry to hear that it's not an option for you.

@soupault, if I understood @msarahan correctly, MinGW needs to provide support for libpython3.5. So there's nothing someone else can do about it.

**Comment by ccordoba12** [comment]
@soupault, to be more precise, MinGW needs to add support for MSVC 2015 in order to be able to compile libpython3.5.

**Comment by paralin** [comment]
Any updates on this?

**Comment by pouya-cognitiv** [comment]
Still nothing?

**Comment by ccordoba12** [comment]
Sorry guys but we use Visual Studio for all our compilation needs, so this very, very low priority for us.

**Comment by mingwandroid** [comment]
It seems this issue is asking about creating an import library for mingw-w64 GCC only:

http://deeplearning.net/software/theano/install_windows.html

.. rather than an entire recompilation of Python using GCC on Windows?

I will test some options next week.

**Comment by pouya-cognitiv** [comment]
Yes. That would be great.
Thank you.

**Comment by ccordoba12** [comment]
What I meant is that we don't use MinGW to compile anything internally, 
so we don't care too much about it.

**Comment by jzuhone** [comment]
@ccordoba12 is there some documentation for how to properly compile on Windows for Anaconda using MSVC?

**Comment by ccordoba12** [comment]
@msarahan is more knowledgeable about it, but essentially we use features for that, like in this recipe:

https://github.com/conda/conda-recipes/blob/master/cairo/meta.yaml

``` 
features:
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]
```

That let's you manage different Visual Studio compilers per Python version. So vc9 corresponds to Visual Studio 2008, vc10 to Visual Studio 2010 and vc14 to Visual Studio 2015.

When conda-build finds features with those names, it automatically selects the right compiler per Python version.

**Comment by msarahan** [comment]
Features are only indicators.  They do not select compilers.  They only reflect the "standard" decision, and if people undermine the standard, then those tags are not actually accurate.  We need to fix that.  We adhere to the standards that the Python.org builds set out - those are the versions mentioned by Carlos.

conda-build internally takes care of picking the "right" compiler based on those standards.  If you have installed Visual Studio to the standard location (and selected to install the C/C++ compiler, which is not default on VS 2015), then things should "just work."  See the conda-recipes repository for many examples.  Among these, hdf5 stands out as especially exercising the compiler:

https://github.com/conda/conda-recipes/blob/master/hdf5/bld.bat

while pandas uses cython, and has a very simple bld.bat, but is also compiling an awful lot:

https://github.com/pydata/pandas/tree/master/conda.recipe

**Comment by electron0zero** [comment]
for me problem was same, i was using TDM-GCC for 64bit but still facing some issues.
fixed it with with the help from [Python WIKI](https://wiki.python.org/moin/WindowsCompilers#Compilers_Installation_and_configuration)

**Comment by mingwandroid** [comment]
libpython for Python 3.5 is now released. The old `mingw` package is deprecated, please use `m2w64-toolchain` instead as that provides 64-bit support. FWIW, we do use `mingw-w64` internally for all of our R language software on Windows.

Theano was also mentioned in this thread. On Windows `conda install theano` will instead `m2w64-toolchain` and will use it automatically.

**Comment by rilut** [comment]
@mingwandroid thanks, this is all what we needed!  
Btw, is `mingw` package deprecated on Python 3 only, or on Python 2 Anaconda too?

**Comment by mingwandroid** [comment]
The `mingw` package is entirely deprecated. You can attempt to use it if you wish, but if anything goes wrong, my solution will involve, as the very first step, installing `m2w64-toolchain` instead.

`m2w64-toolchain` provides support for both 32-bit and 64-bit GCC in a unified way.

**Comment by danielcsaba** [comment]
Hi @mingwandroid, this is a bit off topic but maybe you have some information about it. 

I was using `libpython` and `mingw` with `cffi` to build binaries for Windows under Python 2.7 (the source code contains some GCC macros so I couldn't use Visual Studio).

I was hoping that with the Python 3.5 release of `libpython` I'll be able to do the same. My first attempts were unsuccessful. Do you know by any chance whether the `m2w64-toochain` could be called from `cffi`? Many thanks in advance.

**Comment by mingwandroid** [comment]
Yes, that should be fine (unless you use long doubles).
