### ISSUE TITLE
Cannot install spyder in new environment

### ISSUE THREAD

**Issue by duncanmcbryde** [ContinuumIO/anaconda-issues#562]
Installing Spyder in a new environment causes Anaconda Launcher to crash. Using a fresh Install of Anaconda Python 3.5 64 bit (Edit: Using Anaconda3-2.4.0-Windows-x86_64) and Windows 7 64 bit I create a new environment "tankexp" and attempt to install Spyder. The install fails on "linking pyqt". In addition, it appears that the the environment does not set the paths correctly. After the crash I can activate the environment and call conda, but I cannot deactivate or run conda commands.
![capture](https://cloud.githubusercontent.com/assets/8402755/11510065/93c645f0-9859-11e5-9595-403ba2ef6773.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8402755/11510073/95f6aaea-9859-11e5-933c-a79c1436e4dc.PNG)
![capture3](https://cloud.githubusercontent.com/assets/8402755/11510076/97cd765a-9859-11e5-9cb2-2ada3af5e13d.PNG)

%PATH% before activating
C:\Users\duncan.mcbryde\AppData\Local\Continuum\Anaconda3;C:\Users\duncan.mcbryde\AppData\Local\Continuum\Anaconda3\Scripts;

%Path% after activating
C:\Users\duncan.mcbryde\AppData\Local\Continuum\Anaconda3\envs\tankexp;C:\Users\duncan.mcbryde\AppData\Local\Continuum\Anaconda3\envs\tankexp\Scripts;C:\Users\duncan.mcbryde\AppData\Local\Continuum\Anaconda3\envs\tankexp\Library\bin; etc...

**Comment by duncanmcbryde** [comment]
When attempting to launch Spyder the reported text is 
> 20; The directory name is invalid; None; 267; None

**Comment by ccordoba12** [comment]
I think this is going to be fixed in Anaconda 2.4.1, sorry for the inconvenience :-)

**Comment by duncanmcbryde** [comment]
OK, thanks for that. Any workarounds in the meantime, or what the root cause is? I should point out this was a single-user install. I'm attempting to see if doing a system install with Admin rights provides a usable environment.

**Comment by duncanmcbryde** [comment]
I fixed my environment activation issues by adding the Anaconda root directories `C:\Anaconda3`, `C:\Anaconda3\Scripts` and `C:\Anaconda3\Lib\bin` to my user path. Despite them being set in the system path they were not read when activating and deactivating environments. Now I can use
> activate test
and
> deactivate test
to switch in and out of environments.

I used this [Path Editor](https://patheditor2.codeplex.com/) as doing so natively in Windows was quite confusing!
![capture](https://cloud.githubusercontent.com/assets/8402755/11527471/1c2750f4-98d9-11e5-8a8c-5904600f8001.PNG)

**Comment by duncanmcbryde** [comment]
Looks like solving the path weirdness still results in Spyder failing to install through the application launcher when linking PyQT as before.

**Comment by duncanmcbryde** [comment]
I've found a workaround. while spyder fails to launch from the application launcher it can be started from the Anaconda Prompt with `activate <environment name>` and `spyder`. The spyder reports the version of python as specified by the environment, so I assume it's using the environment properly.

**Comment by ccordoba12** [comment]
Unfortunately the Launcher doesn't work very well. Please the terminal to install/update packages.

As I said, I think the problems you report will be solved in Anaconda 2.4.1, but I'm glad you've found a workaround in the meantime.
