### ISSUE TITLE
Jupyter package needs to be updated

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#563]
We haven't updated the `jupyter` meta-package since August.  This is a problem since the Jupyter team recommends the best way to install Jupyter is via

    conda install jupyter

And we currently point to 4.0.0.  There was an XSS vulnerability identified several weeks ago, and Jupyter is now up to 4.0.6.  I think we need to prioritize getting an updated Jupyter meta-package out there.

http://repo.continuum.io/pkgs/free/osx-64/jupyter-1.0.0-py27_0.tar.bz2

http://jupyter.readthedocs.org/en/latest/install.html#how-to-install-jupyter-notebook

**Comment by ccordoba12** [comment]
@ijstokes, I think there's no need to update the `jupyter` metapackage because it pulls the latest version of the `notebook` package (along with `qtconsole`, `ipywidgets`, etc), and the `notebook` is already at version `4.0.6` :-)

**Comment by ijstokes** [comment]
@ccordoba12 I am confused then about the dependency version information in the `jupyter` package.  I've checked both http://repo.continuum.io (linux-64 and osx-64) and also what I have on my local system (osx-64), and they all seem to indicate that the Jupyter package explicitly states older versions from `4.0.1` to `4.0.4`:

```bash
$ grep -i -e jupyter -e notebook ~/anaconda/pkgs/jupyter-1.0.0-py*/info/index.json | cut -f 6- -d /

jupyter-1.0.0-py27_0/info/index.json:    "jupyter_console 4.0.0", 
jupyter-1.0.0-py27_0/info/index.json:    "notebook 4.0.1", 
jupyter-1.0.0-py27_0/info/index.json:  "name": "jupyter", 
jupyter-1.0.0-py27_0/info/index.json:    "jupyter_console 4.0.0", 
jupyter-1.0.0-py27_0/info/index.json:    "notebook 4.0.1", 

jupyter-1.0.0-py34_0/info/index.json:    "jupyter_console 4.0.0", 
jupyter-1.0.0-py34_0/info/index.json:    "notebook 4.0.1", 
jupyter-1.0.0-py34_0/info/index.json:  "name": "jupyter", 
jupyter-1.0.0-py34_0/info/index.json:    "jupyter_console 4.0.0", 
jupyter-1.0.0-py34_0/info/index.json:    "notebook 4.0.1", 

jupyter-1.0.0-py35_0/info/index.json:    "jupyter_console", 
jupyter-1.0.0-py35_0/info/index.json:    "notebook", 
jupyter-1.0.0-py35_0/info/index.json:  "name": "jupyter", 
jupyter-1.0.0-py35_0/info/index.json:    "jupyter_console 4.0.2", 
jupyter-1.0.0-py35_0/info/index.json:    "notebook 4.0.4", 
```

Having said that, I can confirm that `conda create -n jupyter jupyter` **does** pull down the latest notebook `4.0.6` -- however how this happens is a mystery to me.  Are you able to explain it?

**Comment by ccordoba12** [comment]
I think when you installed `jupyter` those were the latest versions of everything (e.g. `notebook` was at `4.0.1`, etc). That's the only explanation I can find because we don't pin any particular version in `jupyter`, as can be seen here:

https://github.com/ContinuumIO/anaconda/blob/master/packages/jupyter-1.0.0/meta.yaml

Then the only way to update `jupyter` after installing it probably is

    conda remove jupyter
    conda install jupyter

because obviously

    conda update jupyter

is not going to work because we haven't bumped `jupyter` version at all :-)

Could you see if it works for you?

**Comment by msarahan** [comment]
There is an important difference between repodata.json and index.json.  repodata.json is used most of the time from what I can tell, and even in that, there's two sections: dependencies and requirements, and only one gets used most of the time.  I don't know exactly when index.json gets used, but a recent issue related issue was https://groups.google.com/a/continuum.io/forum/#!searchin/anaconda/discrepancy/anaconda/5GsiFhl4zt8/9TPF5xVOBAAJ .  @ilanschnell would have to explain how things work.

**Comment by ilanschnell** [comment]
Yes, `repodata.json` is used when conda has access to it.  The file `info/index.json` is only used to create `repodata.json`, but in the Anaconda system there are special that get you from `info/index.json` to `repodata.json`, which are not documented well (I agree).  Within `info/index.json` the "depends" key is the only thing which conda uses (in offline mode, if at all), and "requires" is never used by conda.  I hope this explains things a bit better.

**Comment by ijstokes** [comment]
OK, I think this is still a confusing situation.  I was looking *inside* the package tarball and all indications were that `jupyter 1.0.0` **fixes** the `notebook` package version.  Here are some fragments:

`info/index.json`:
```json
  "depends": [
    "ipykernel 4.0.3", 
    "ipywidgets 4.0.2", 
    "jupyter_console 4.0.0", 
    "nbconvert 4.0.0", 
    "notebook 4.0.1", 
    "python 2.7*", 
    "qtconsole 4.0.0"
  ], 
  "requires": [
    "ipykernel 4.0.3", 
    "ipywidgets 4.0.2", 
    "jupyter_console 4.0.0", 
    "nbconvert 4.0.0", 
    "notebook 4.0.1", 
    "python 2.7", 
    "qtconsole 4.0.0"
  ], 
```

`info/requires.txt`:
```bash
ipykernel-4.0.3-py27_0
ipython-4.0.0-py27_0
ipython_genutils-0.1.0-py27_0
ipywidgets-4.0.2-py27_0
jupyter_client-4.0.0-py27_0
jupyter_console-4.0.0-py27_0
jupyter_core-4.0.2-py27_0
nbconvert-4.0.0-py27_0
nbformat-4.0.0-py27_0
notebook-4.0.1-py27_0
```

What is the motivation for including those detailed versions if they are ignored?  That seems misleading to me and I imagine will confuse others as well.

**Comment by ijstokes** [comment]
I was, in fact, doing some operations last night with `--offline` (or whatever the flag is) in order to just pull packages from my local package cache, and perhaps it was under that context that I saw this behavior.

**Comment by ijstokes** [comment]
OK, put differently, it seems to me that the unsuspecting conda user would *expect* that the most complete and accurate dependency information is encoded *inside* the package tarball.  That is what I expected, and that seems very reasonable.  I will open a separate issue to track/discuss this.

**Comment by ilanschnell** [comment]
Ok, I will rebuild the package to avoid confusion.

**Comment by ilanschnell** [comment]
New conda packages are available.
