### ISSUE TITLE
Fatal Error - Glueviz Install

### ISSUE THREAD

**Issue by c443** [ContinuumIO/anaconda-issues#564]
Hello All,

I have just installed the latest version of anaconda from the website 64bit windows graphical installer. I have tried a couple of times this morning uninstalling and re-installing the whole application. I get an error either installing Glueviz from the application launcher or updating spyder again through the launcher and after this there is no way to re-install Glueviz or to repair Spyder. 

I get a message box titled Alert that says "sorry, the application encountered a fatal error. Please report the following to us at ..[here]" the status in the Glueviz install window at this point is "linking pyqt".

Thanks,
Chris

**Comment by c443** [comment]
Update: Installs correctly from cmd

**Comment by hayesgb** [comment]
I had the same problem; update conda and glueviz fails to start, either from the launcher, or the an iPython notebook.
