### ISSUE TITLE
cannot open spyder app

### ISSUE THREAD

**Issue by tarokiritani** [ContinuumIO/anaconda-issues#568]
After updating matplotlib from 1.4.3 to 1.5.0, it is no longer possible to open spyder either from the launcher or from the command line. I switched back to 1.4.3, but this does not help.

spyder does not launch from another environment with the same python version (3.4.3-5). However, it can start from yet another environment with python 3.4.3-0.

**Comment by tarokiritani** [comment]
I tried to install spyder-app in the launcher in one of the envs, and got an fatal error. The alert message told me to report the error here.

**Comment by ccordoba12** [comment]
Please try to run in a terminal

    conda update spyder

That should fix the problem
