### ISSUE TITLE
overwriting global python env messing up python2.7 use by other programs

### ISSUE THREAD

**Issue by mmclau14** [ContinuumIO/anaconda-issues#5714]
after removing these lines from by bashprofile i found that it fixed the problem. however i would think this should not have caused a problem in the first place and never should have overwritten `python` (which is python 2 on my comp) with python 3 which is `python3` is there any way for me to force anaconda to use python 3 instead of overwriting the python env with a different version
```
# added by Anaconda3 4.2.0 installer
export PATH="/Users/michaelmclaughlin/anaconda/bin:$PATH"
export LD_LIBRARY_PATH=$TOOLS/curl-7.43.0/lib:$LD_LIBRARY_PATH
```

**Comment by mingwandroid** [comment]
To be clear, Anaconda never overwrites any system files or programs.

Here, you have *elected* to have the Anaconda installer to add the folder containing its binaries to your `PATH`.

This is a choice; one I do not recommend. Instead, you should `. <path_to_anaconda>/bin/activate`when you need it and `. <path_to_anaconda>/bin/deactivate` it (or just not `activate` it in the first place) when you want to use your system software.
