### ISSUE TITLE
open cv2

### ISSUE THREAD

**Issue by thelostscientist** [ContinuumIO/anaconda-issues#572]
can someone please update package manager for py3.5 to include opencv2?

**Comment by msarahan** [comment]
There are some packages for Python 3.5 OpenCV available on Anaconda.org: https://anaconda.org/search?q=opencv

In particular, I know that https://anaconda.org/memex/opencv/files has 3.5 versions available.

**Comment by thelostscientist** [comment]
cool, the memex build worked!

Thanks!
