### ISSUE TITLE
Cannot run anaconda installer from directory with space in path

### ISSUE THREAD

**Issue by KennethNielsen** [ContinuumIO/anaconda-issues#575]
Hallo Anaconda devs

The Linux anaconda installer fails to install, when being run from a path with a space in. This becomes a problem e.g. when on a Danish Linux system where the default download folder is called "Hentede filer". I can of course just move, but I though, why not try and have it fixed.

I think, the fix is as simply as quotes around the `$THIS_PATH` variable in all places where it is being used (there are a few missing at line 237 and 253).

Something like the following diff might fix it, but I am unable to try it out because the script checks size and checkssum and I couldn't figure out in a rush how to fix that.

```diff
--- Anaconda2-2.4.0-Linux-x86_64.sh_old	2015-12-07 09:20:34.305528834 +0100
+++ Anaconda2-2.4.0-Linux-x86_64.sh	2015-12-07 09:30:00.517800538 +0100
@@ -234,7 +234,7 @@
 echo "PREFIX=$PREFIX"
 
 # verify the MD5 sum of the tarball appended to this header
-MD5=$(tail -n +504 $THIS_PATH | md5sum -)
+MD5=$(tail -n +504 "$THIS_PATH" | md5sum -)
 echo $MD5 | grep 39f0827de433ae727759c9748d4a64b2 >/dev/null
 if (( $? )); then
     echo "WARNING: md5sum mismatch of tar archive
@@ -250,7 +250,7 @@
 #   ownership to root himself.
 cd $PREFIX
 
-tail -n +504 $THIS_PATH | tar xf - --no-same-owner
+tail -n +504 "$THIS_PATH" | tar xf - --no-same-owner
 if (( $? )); then
     echo "ERROR: could not extract tar starting at line 504" >&2
     exit 1
```

**Comment by ilanschnell** [comment]
Thanks for the feedback, and the possible fix.  It is very uncommon to have spaces in paths on Linux systems, and we never did any testing in this regard.  I've added the suggested changes to the script, but I am almost certain that other problems will still remain.  We have to decide weather or not, we want to support spaces in the install path, and start testing for this usecase.

**Comment by KennethNielsen** [comment]
Thanks for feedback @ilanschnell

I think "very uncommon" is an oldish and no longer valid assumption. The standard download path e.g  is one of these xdg-paths (I think), which is translateable, so it can be **anything** really.

In any case. If you do decide not to support it. Maybe just test for it at the beginning and give a easy to understand error.

**Comment by ilanschnell** [comment]
Your new Anaconda 2.4.1 installers, which have been created yesterday, already contain your fix.  So, with a little luck, all will work now.

**Comment by KennethNielsen** [comment]
@ilanschnell great, I will test them later today.

**Comment by KennethNielsen** [comment]
@ilanschnell it works. Thanks for the quick response.

**Comment by ilanschnell** [comment]
Great!  I'm a bit surprised that it works, because as I said earlier, we have never done any testing in that respect, and was expecting other issues.

**Comment by ilanschnell** [comment]
Strange, I just tried:
```
$ bash Anaconda2-2.4.1-Linux-x86_64.sh -b -p 'spaces in path'
ERROR: Cannot install into directories with spaces
```
There actually has been (and still is) code to disallow spaces in the install prefix all along.

**Comment by msarahan** [comment]
Yes, but Kenneth's request was different: running the installer from a path
that has spaces in it.  He wasn't necessarily trying to install into a
space-containing prefix.

**Comment by ilanschnell** [comment]
Ah, thanks for the clarification, @msarahan.  Yes, I was just able to verify that *running* the installer for a path with spaces works.
