### ISSUE TITLE
Rebuild for gcc>=5.2 ABI

### ISSUE THREAD

**Issue by yesimon** [ContinuumIO/anaconda-issues#577]
I was trying to build against the `boost` package on linux64 but realized that it hasn't been built with the dual ABI of gcc 5 while my system gcc is version 5.2. (https://gcc.gnu.org/gcc-5/changes.html#libstdcxx).

I understand that I could build using an old compiler but I would appreciate a rebuild of C++ libraries if possible. Other than boost, I don't know specifically which packages would be affected, but anything that provides a C++ shared library is a good candidate.

**Comment by ccordoba12** [comment]
Sorry, I don't think that's going to happen. You can build your own boost packages using the boost recipes present in our conda-recipes repository:

https://github.com/conda/conda-recipes

**Comment by yesimon** [comment]
Can you elaborate a bit further? Is this like a "we don't have the development bandwidth for this and are not willing to commit to future plans"? Or is it like "the GCC 5 ABI transition is bungled and we don't like that clang and gcc built software don't work together so we're waiting until GCC 6"?

I just want to understand the decision so that I can more fully commit to anaconda's version with workarounds versus a separately built package.

**Comment by ccordoba12** [comment]
It's not about bandwidth, it's something it was decided before I started with Continuum, so I can't say much about it.

Right now we compile almost all our packages with gcc 4.4 on CentOS 5, and we're discussing to move to gcc 4.8 on CentOS 6. So gcc 5 is not in our plans and probably won't be for another year or two.

Sorry, but if you want to compile packages with a more recent gcc, you can use our own `gcc` packages, which provides gcc 4.8.

**Comment by yesimon** [comment]
Thanks for the info.

Would it be possible to describe the build environment for default channel conda packages in the online documentation or README.md? This might make more sense in the conda-recipes repo so I'll open an issue there.

**Comment by frol** [comment]
@yesimon You can take a look at our work at Salford Systems repo:

* https://anaconda.org/salford_systems/boost-gcc5
* https://anaconda.org/salford_systems/gcc-5

Here is our fork with the recipes: https://github.com/salford-systems/conda-recipes

**Comment by yesimon** [comment]
@frol Looks good. I'll keep your channel in mind. What's your build platform for binary packages?

**Comment by frol** [comment]
@yesimon CentOS 6.7 (glibc 2.12) for both Linux-64 and Linux-32.
