### ISSUE TITLE
Consider updating nbconvert to 4.1.0

### ISSUE THREAD

**Issue by cel4** [ContinuumIO/anaconda-issues#579]
nbconvert-4.1.0 was released on 30 Oct

**Comment by ccordoba12** [comment]
Thanks for letting us know about it. I'll create a pull request in our internal repo to do that.

**Comment by petebachant** [comment]
This would definitely be helpful. Some slides I made with the notebook only convert properly with 4.1.0 due to some differences in the newer versions of Reveal.js.
