### ISSUE TITLE
Error when conda updating from 3.5.0 to 3.5.1

### ISSUE THREAD

**Issue by aewhatley** [ContinuumIO/anaconda-issues#582]
Got some error messages while installing Python 3.5.1 (Anaconda). Here is the traceback:

Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
menuinst Exception:Traceback (most recent call last):                    |   0%
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\conda\install.py", line 3
43, in mk_menus
    env_setup_cmd=env_setup_cmd)
TypeError: install() got an unexpected keyword argument 'root_prefix'
menuinst Exception:Traceback (most recent call last):                    |  25%
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\conda\install.py", line 3
43, in mk_menus
TypeError: install() got an unexpected keyword argument 'root_prefix'
menuinst Exception:Traceback (most recent call last):###########         |  82%
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\conda\install.py", line 3
43, in mk_menus
TypeError: install() got an unexpected keyword argument 'root_prefix'
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
        1 file(s) copied.##############################                  |  65%
menuinst Exception:Traceback (most recent call last):#######             |  74%
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\conda\install.py", line 3
43, in mk_menus
    try:
TypeError: install() got an unexpected keyword argument 'root_prefix'
menuinst Exception:Traceback (most recent call last):##############      |  88%
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\conda\install.py", line 3
43, in mk_menus
    try:
TypeError: install() got an unexpected keyword argument 'root_prefix'
menuinst Exception:Traceback (most recent call last):##################  |  97%
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\conda\install.py", line 3
43, in mk_menus
    try:
TypeError: install() got an unexpected keyword argument 'root_prefix'
[      COMPLETE      ]|##################################################| 100%

**Comment by ccordoba12** [comment]
What's your conda version?

**Comment by msarahan** [comment]
This is a menuinst being out of date issue.  Please run ```conda update menuinst``` then try to update Python again.

**Comment by aewhatley** [comment]
It looks like the newest menuist was installed already, as when I typed that in, it said up to date. I guess somewhere in the traceback it was updated anyways.

**Comment by msarahan** [comment]
I stand corrected. The issue is that menuinst and conda are more tightly coupled than they should be. Please update conda and try again.  The errors are going to lead to potentially missing start menu shortcuts. If that doesn't bother you, just ignore them.

In general, always update conda first, then do any other updates.
