### ISSUE TITLE
Bad OpenBlas causes very poor performance for running multiple processes

### ISSUE THREAD

**Issue by dnidever** [ContinuumIO/anaconda-issues#593]
The default setting for the OpenBlas package (which is a dependency of numpy) which gets built when you "conda install numpy" is such that there is very poor performance when running multiple python processes at once.  The default setting tells each instance of numpy/OpenBlas to use ALL available cores.  Since all processes do this most of the time is spent swapping between threads and performance is dramatically slowed - the overall processing time increases linearly with the number of processes running.  The NUM_THREADS parameter in Makefile.rules should be set to something reasonable like maybe 6.  Interestingly, according to the build recipes in "build.sh" NUM_THREADS=1, but for some reason this is not actually the case.

**Comment by msarahan** [comment]
OpenBLAS respects the OMP_NUM_THREADS environment variable.  By default, it tries to use all cores.  This is desirable for people running only one process.  Your proposal of something reasonable might be reasonable for your hardware and use case, but it is not likely best for everyone. 

The build recipes in conda-recipes are not necessarily the recipes used for packages in our main repos. We maintain a separate internal repo, with many recipes being an older format that predates conda.  It is always good to ask what is in the recipe in use: much of the time we can share it, but keeping the two repos in sync is more work than we have time for.

**Comment by mjuric** [comment]
@msarahan Thanks, makes sense!

I didn't realize that the recipes from `conda-recipes` were not used to build the distribution! That explains the difference in the observed vs. assumed (based on `build.sh`) behaviors.
