### ISSUE TITLE
openblas 0.2.14-3 links to /usr/local/lib/libgfortran.2.dylib on OS X

### ISSUE THREAD

**Issue by pkgw** [ContinuumIO/anaconda-issues#595]
The shared library distributed in the `openblas` binary package has a dependency on `/usr/local/lib/libgfortran.2.dylib`, at least in version `0.2.14-3` of the package. This effectively means that you have to have a Homebrew installation with the cloned Apple GCC for the library to work. I'm not sure what exactly Anaconda's binary compatibility policies are, but my impression is that these sorts of external dependencies are intended to be avoided.

```
Anaconda 19:21 info $ otool -L /conda/lib/libopenblasp-r0.2.14.dylib 
/conda/lib/libopenblasp-r0.2.14.dylib:
    libopenblasp-r0.2.14.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libgfortran.2.dylib (compatibility version 3.0.0, current version 3.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

I would investigate patching the build recipe, but [the version posted in conda/conda-recipes](https://github.com/conda/conda-recipes/tree/master/openblas) is for build version 2 of the package, and judging by the file contents, things were heavily revised for version 3.

Solving this problem is probably a matter of providing a `-static-libgfortran` flag to the appropriate link line.

I'll also note that the dylib weighs in at 56 megabytes, which seems quite hefty. But maybe that's not unreasonable.

**Comment by nunocalaim** [comment]
In the meanwhile what can I do as a workaround to this problem?

**Comment by asinine** [comment]
installing gfortran-4.2.3.pkg from https://cran.r-project.org/bin/macosx/tools/ solved this for me

**Comment by nunocalaim** [comment]
This indeed worked for me! Thank you!

**Comment by pkgw** [comment]
As an update, my interpretation is that this package should be avoided on OS X — the OS comes with BLAS libraries built in. So in the end, I ended up not needing to have openblas as a dependency for my package.

**Comment by nunocalaim** [comment]
In my case openblas was a dependency of another package, namely cvx-opt. I wouldn't know how to tell cvx-opt that I already had a BLAS library so it shouldn't use the openblas

**Comment by 183amir** [comment]
@groutr is there any chance to look back into this? There is also a duplicate here: https://github.com/ContinuumIO/anaconda-issues/issues/608 and this is still happening in `openblas-0.2.19-0`.
Thanks.
ping @anjos

**Comment by msarahan** [comment]
@183amir @groutr is no longer with Continuum.  I will re-raise this issue in our next meeting for reassignment to another team member.

**Comment by 183amir** [comment]
Thank you @msarahan that would be great.

**Comment by ilanschnell** [comment]
I've added a `libgfortran` conda package (on OSX), and also made a new `openblas-0.2.19-1` which now links against `libgfortran`.  This should fix this issue.

**Comment by eugene-yang** [comment]
I used `conda install -c anaconda openblas` to reinstall openblas. Looks like openblas is still referring `libgfortran.2.dylib`
```
ImportError: dlopen(/Users/eugene.yang/Documents/Repositories/libact/libact/query_strategies/_variance_reduction.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libgfortran.2.dylib
  Referenced from: /Users/eugene.yang/anaconda3/lib/libopenblas_nehalemp-r0.2.19.dylib
```
