### ISSUE TITLE
Anaconda Upload and Continuous Integration

### ISSUE THREAD

**Issue by jgmorrison** [ContinuumIO/anaconda-issues#5951]
Brought up by @openvest 

Anaconda upload –user ORG package

Minor quibble: --user is a misnomer since it's not the user.

Larger issue: this doesn't answer whether it can be auto-uploaded to the org channel . think Continuous Integration agent

Major issue: I've done this before and can't believe that we haven't fixed this. To do it in a continuous integration environment, this requires running conda build with –output, just to capture the name to upload. Forcing people to do bash scripting to upload is a pain. Please tell me this has been fixed.

**Comment by csoja** [comment]
This is an anaconda-client issue.  Please open this at https://github.com/Anaconda-Platform/anaconda-client/issues
