### ISSUE TITLE
install_name pathing issue in readline 6.2-2 on OS X

### ISSUE THREAD

**Issue by pkgw** [ContinuumIO/anaconda-issues#598]
OK, this one gets a bit subtle. I believe that the dylibs distributed for `readline`, as well as other basic C language packages, are broken for some development use cases on OS X. This may only apply on relatively recent versions of the OS; I'm using 10.10.

First, let's look at the `install_name` information for the readline dylib when installed. In my example Miniconda is installed in `/conda`:

```
$ otool -L /conda/lib/libreadline.dylib 
/conda/lib/libreadline.dylib:
    libreadline.6.2.dylib (compatibility version 6.0.0, current version 6.2.0)
    /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
```

As I understand it, the first line of output is the `install_name`. It is neither an absolute path, nor does it begin with a string like `@rpath`. I believe this is broken, as I will describe below.

(**edit**: `otool -D` gives you the `install_name` directly and is consistent with the `-L` output.)

The problem is that if you compile an executable against this library, it will embed this prefix-less `install_name`. If you then try to run the executable, the dynamic loader will only search for it in the standard system paths. On OS X 10.10, the system version of `libreadline` is not compatible with the Conda version (in particular it is named `libreadline.dylib`, not `libreadline6.2.dylib`), so you get a crash:

```
$ cat <<'EOF' >test.c
> #include <stdio.h>
> int main(int argc, char **argv) { printf("hello world\n"); return 0; }
> EOF
$ gcc -o test test.c -L/conda/lib -lreadline -Wl,-rpath,/conda/lib
$ otool -L test
test:
    libreadline.6.2.dylib (compatibility version 6.0.0, current version 6.2.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
$ ./test 
dyld: Library not loaded: libreadline.6.2.dylib
  Referenced from: /Users/vagrant/./test
  Reason: image not found
Trace/BPT trap: 5
```

The key problem is that `test` doesn't link to `libreadline` with any `@rpath` info, so as far as I can tell there's no way for the runtime loader to know where to find the appropriate dylib, even if you embed `/conda/lib` as an rpath in the executable. My takeaway from the Apple docs is that the `install_name` for a dylib should always be either an absolute path, or prefixed with `@rpath` or one of the other magic `@` values.

In contrast, things work OK if I link with the Conda version of `libQtGui`, since its `install_name` starts with `@rpath`:

```
$ otool -L /conda/lib/libQtGui.dylib |head -n3
/conda/lib/libQtGui.dylib:
    @rpath/./libQtGui.4.dylib (compatibility version 4.8.0, current version 4.8.7)
    @rpath/libQtCore.4.dylib (compatibility version 4.8.0, current version 4.8.7)
$ gcc -o test test.c -L/conda/lib -lQtGui -Wl,-rpath,/conda/lib
$ otool -L test
test:
    @rpath/./libQtGui.4.dylib (compatibility version 4.8.0, current version 4.8.7)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
$ ./test
hello world
```

Now, for binaries that are being packaged up for Conda, the post-install futzing tool seems to clean up most of this. However, I ran into this problem in the configuration stage for a CMake-based package that tests readline's presence by trying to compile and run an executable that links to it. As far as I can tell there's no way to generate a binary that works under these conditions.

The same issue is present in the dylibs provided in `libxml2`, `libxslt`, and `libpng16`, at least.

**Comment by pkgw** [comment]
Oh, here's the “clever” workaround I devised. Since the build environment is modifiable when running `conda build`, before I run `cmake` in my `build.sh` script, I manually patch up the dylibs:

```
for lib in xml2 xslt readline ; do
    lpath=$PREFIX/lib/lib${lib}.dylib
    iname=$(otool -L $lpath |sed -e '2!d' |awk '{print $1}')
    install_name_tool -id @rpath/$iname $lpath
done
```

Not exactly awesome but it seems to be working.

**Comment by pkgw** [comment]
See also [conda-build issue #279](https://github.com/conda/conda-build/issues/279), [conda-build pull request #312](https://github.com/conda/conda-build/pull/312).

**Comment by kalefranz** [comment]
@mingwandroid

**Comment by mingwandroid** [comment]
Will discuss how to proceed with this on Monday.

**Comment by jakirkham** [comment]
What's the plan here?

**Comment by mingwandroid** [comment]
You should be able to fix it up with a relative path. `@rpath/libname.dylib` should work. Did you try that?

But we should just build `readline` with conda-build. Perhaps @ilanschnell can help out with that?

**Comment by jakirkham** [comment]
> You should be able to fix it up with a relative path. `@rpath/libname.dylib` should work. Did you try that?

Of course. Sure it should work. Haven't tried it per se.

> But we should just build `readline` with conda-build. Perhaps @ilanschnell can help out with that?

Are there other ones like this that should be rebuilt? I haven't investigated, but maybe it is worth coming up with a list.

**Comment by mingwandroid** [comment]
I investigated this around the end of Feb or early March and there were a handful. Once all of the packages in `defaults` have `conda-build` recipes and are rebuilt from those, the new ones should be fine.

Looking at the fix-ups, you want everything to be specified relative to ${env}/lib, so for a `.dyli`b living in that folder you'd use:
    install_name_tool -id "@rpath/libname.dylib"

and for an executable in `bin` you'd use:
    install_name_tool -add_rpath "@loader_path/../lib/"

**Comment by mingwandroid** [comment]
Closing as the problematic packages are no longer in (much?) active use.
