### ISSUE TITLE
Anaconda crashes as soon as i open the navigator.

### ISSUE THREAD

**Issue by prateekponnuru** [ContinuumIO/anaconda-issues#5994]
Hi, I have Anaconda3 4.2.0 and it was working fine for some time. But now as i open the anaconda-navigator it opens up and crashes immediately. Here is the error message i receive when i run it from command prompt:
C:\Users\ponnurup>anaconda-navigator
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\widgets\
tabs\community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'

**Comment by goanpeca** [comment]
You are using an old version of Navigator no longer supported. 

Please remember to update to the latest version of Navigator to include the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda install navigator-updater
```

or 

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Comment by number161** [comment]
i have the updated everything. conda update anaconda-navigator
conda update navigator-updater. Still facing the problem. What can be done?
