### ISSUE TITLE
Package 'orange' uninstallable with Anaconda Python 3.5 release

### ISSUE THREAD

**Issue by kernc** [ContinuumIO/anaconda-issues#602]
`conda install orange` doesn't work with Anaconda Python 3.5 release (on Windows), so **Orange perhaps shouldn't be featured on the Anaconda Launcher's front page of said release**.

The version of Orange that works with Python3 is https://github.com/biolab/orange3

**Comment by marcomayer** [comment]
I agree as I just stumbled over the same issue. Thought I'd give the Launcher.app a try (on Mac OSX) that has been placed on my desktop, discovered Orange, wanted to install it and it says:

Hint: the following packages conflict with each other:
  - orange
  - python 3.5*

**Comment by ales-erjavec** [comment]
If it's of any use, the conda recipes for orange3 and required libraries are available at https://github.com/ales-erjavec/orange3-conda-recipe

**Comment by ilanschnell** [comment]
Thank you that is helpful.  I'll work on updating Orange today (which also means adding Py3k support).

**Comment by acbart** [comment]
Any updates on this? I was very interested in trying out Orange.

**Comment by nickteff** [comment]
I am interested too!  Any updates on py3k?

**Comment by msarahan** [comment]
I think orange3 should get you what you want:

    conda install orange3
