### ISSUE TITLE
pylint needs to be >=1.5 for Python3.5 

### ISSUE THREAD

**Issue by branning** [ContinuumIO/anaconda-issues#603]
[This was reported on StackOverflow, and the best resolution I could come up with was to install pylint from pip](http://stackoverflow.com/q/34445171/347567)

Pylint 1.4.2 is the current build in Conda, but that version doesn't work with Python3.5. The current version in pip is 1.5.2, which works fine. Please update the conda package.

**Comment by bilderbuchi** [comment]
Yes, please do this, I run into the same issues with the old pylint release available through anaconda, and python 3.5.

**Comment by branning** [comment]
This has been fixed, pylint is at version 1.5.4 in Conda. h/t @groutr
