### ISSUE TITLE
Rpy2 is broken with py35

### ISSUE THREAD

**Issue by rmcgibbo** [ContinuumIO/anaconda-issues#605]
rpy2 <= 2.7.3 is not supported on Python 3.5. It dies during import. The package in the `r` channel is currently at 2.7.0. See https://bitbucket.org/rpy2/rpy2/issues/312/python-35

**Comment by ccordoba12** [comment]
Letting @groutr know about this one :-)

**Comment by mingwandroid** [comment]
This is fixed now.
