### ISSUE TITLE
Issues with mklfft package

### ISSUE THREAD

**Issue by allyelsey** [ContinuumIO/anaconda-issues#6067]
From a customer:

"There is a pretty serious bug in the mkl fft package, w.r.t numpy
broadcasting. This is for an older version of mklfft

mklfft: 1.0-np18py27_p0

```
from scipy.signal import convolve, fftconvolve
import numpy as np
import numpy as np
arr = np.random.random((10, 30))
fir_filter = np.random.random(9).reshape(-1, 1)
fft = fftconvolve(arr, fir_filter, mode='full')
normal = convolve(arr, fir_filter, mode='full')
print arr.shape
print fir_filter.shape
print np.abs((fft - normal)).max()
```

yields:

```
(10, 30)

(9, 1)

6.02757077368
```

after removing mklfft

```
(10, 30)

(9, 1)

3.10862446895e-15
```
"

**Comment by msarahan** [comment]
CC @seibert - what is the status of mklfft?  It used to be part of accelerate, but we (the distribution team) have no idea what the current state is.

**Comment by allyelsey** [comment]
Is there a better place/repo to post this issue if this falls outside the Distribution team?

**Comment by allyelsey** [comment]
Opened an issue in the mklfft repo instead, https://github.com/ContinuumIO/mklfft/issues/1, closing.
