### ISSUE TITLE
Anaconda is not responding. 

### ISSUE THREAD

**Issue by iamnoob246** [ContinuumIO/anaconda-issues#6117]
I have updated the software to 1.6.4 and inputed source activate. I managed to get it to work before but now im having the same issue, how can I resolve this? I really need to work on some school work.

**Comment by goanpeca** [comment]
@iamnoob246 we can only help based on the information you provide, so please share, what is the output of

```
$ conda info
$ conda list
$ anaconda-navigator
```

Remember that `$` just indicates that these commands need to go into the Anaconda Prompt (on Windows) or the terminal (On linux and osx), so no need to include them when actually typing the command.
