### ISSUE TITLE
Anaconda 5 testing issue - Anaconda2-5.0.0-Linux-ppc64le.sh

### ISSUE THREAD

**Issue by Jacob-Barhak** [ContinuumIO/anaconda-issues#6134]
When trying to install this version on a Centos 6.9 Linux box, it does not report incompatibility before installation. Instead it raises an error that is not indicative. See transcript below:

[Anaconda5ppc64Error.txt](https://github.com/ContinuumIO/anaconda-issues/files/1334611/Anaconda5ppc64Error.txt)

The installer should detect compatibility to system before starting and give proper instructions to the user

**Comment by csoja** [comment]
Duplicate issue - tracking elsewhere.  Closing here.
