### ISSUE TITLE
Anaconda 5 testing issue - Anaconda2-5.0.0.dev9-Linux-x86_64.sh - building a package breaks

### ISSUE THREAD

**Issue by Jacob-Barhak** [ContinuumIO/anaconda-issues#6135]
The installation of Anaconda 2 is successful and it tests well on many use cases. However, when trying to build a noarch package that previously build successfully on Anaconda3 4.4.0  breaks on the new Anaconda5 .

The recipe can be found in:
 https://github.com/Jacob-Barhak/AnacondaRecipes/tree/master/phosphor

The transcript of the failed output can be found in:
[Anaconda5phosphorjs.txt](https://github.com/ContinuumIO/anaconda-issues/files/1334644/Anaconda5phosphorjs.txt)

This may be a build issue not related to version 5.0.0, yet it is worth a look.

**Comment by msarahan** [comment]
It appears to me that phosphor has a bizarre, overcomplicated tagging scheme.  the tag that you specified doesn't exist.  Instead, the tags look something like:

@phosphor/widgets@1.5.0

**Comment by Jacob-Barhak** [comment]
So Mike,

This package does build on windows and Linux with Anaconda3 version 4.4.0. See: https://anaconda.org/jacob-barhak/phosphor

This means that this is either an Anaconda 5 issue or a python 2 issue. 

The good news are that Anaconda 5 performs pretty well with many other use tasks.

**Comment by msarahan** [comment]
I think the relevant variable here is conda-build versions.  What version of conda-build (and/or git) are you using in both cases?

**Comment by Jacob-Barhak** [comment]
Well Mike,

It seems you are correct. 

It should be the latest version I used since I just installed it to test the new Anaconda release. I wiped out the VM so I cannot go back and double check without redoing the entire installation. Yet looking at another installation Anaconda 5 comes with conda-build 3.0.22 while I used conda build 3.0.19  with the successful builds.
It seems this is indeed a conda build issue. Please redirect it appropriately. Hopefully this will be fixed in the newer versions to allow backwards compatibility.

**Comment by csoja** [comment]
Closing here as it is best placed in the conda-build issue tracker.
