### ISSUE TITLE
Anaconda 5 testing issue - Installing 32 bit version on 64 bit machine unsuccesful

### ISSUE THREAD

**Issue by Jacob-Barhak** [ContinuumIO/anaconda-issues#6143]
When installing Anaconda3-5.0.0.dev9-Linux-x86.sh on a 64bit CentOs 6.9 the installation does not complete. There is a warning message at the start, yet if this is intended to fail, just stop the installation - otherwise the installation should be complete at users risk.

Attached is the error transcript:
[Anaconda5x32tOnx64.txt](https://github.com/ContinuumIO/anaconda-issues/files/1335129/Anaconda5x32tOnx64.txt)

**Comment by nehaljwani** [comment]
`yum install glibc.i686` should fix that error for you.

**Comment by Jacob-Barhak** [comment]
Ok Nehal,

Yet why wont the installer add this library if needed?

If it is known to be needed for some platforms, then three is not reason not to include it in the distribution.

I hope this makes sense.

           Jacob

**Comment by mingwandroid** [comment]
We do not install such system libraries as they vary from distro to distro

**Comment by Jacob-Barhak** [comment]
Ok Ray,

The explanation makes sense. This is an uncommon use case where folk install 32bit anaconda on a 64 bit machine. And the installation does give a warning to the user. So It is expected that the user know what they are doing. The extra work of supporting every platform may not by worth the benefit.

As long as the user can ask for help and get it, like in this channel for example, it is fair to avoid the extra work of supporting all platforms before the problem appears. As long as this is documented and there is support, I think it is reasonable to close this issue.  If this becomes a repetitive issue after multiple user requests, then it may be worth reopening. I myself was just testing and did not need this use case.

It is also reasonable to close this since 32bit systems are becoming less popular anyway. 

So if there is consensus with all those involved, please close the issue.
