### ISSUE TITLE
Anaconda 5 testing issue - Spyder does not start properly after installing Anaconda 2 64x on Windows 10

### ISSUE THREAD

**Issue by Jacob-Barhak** [ContinuumIO/anaconda-issues#6146]
After Installing Anaconda2x64 on a win10 machine, most things seem ok. However, when starting Spyder, there are two issues.

First Windows Firewall detect pythonw as a potential threat and prompts the user with a message box for approving this. This is unusual and perhaps intermittent and can be easily resolved by the user. 

However, the second issue is more troubling since Spyder loads and reports missing dependency - this installation is new. I am attaching a screenshot:
![virtualbox_vm_26_09_2017_18_32_15](https://user-images.githubusercontent.com/1986155/30889205-5d534034-a2ea-11e7-9065-ba822c6f314c.png)

Hopefully there is a quick solution here before release.

**Comment by csoja** [comment]
which version of nbconvert is installed?

**Comment by msarahan** [comment]
I think Jacob is testing old installers.

**Comment by Jacob-Barhak** [comment]
So Mike,

The installers being tested are in: 
https://repo.continuum.io/pkgs/misc/preview/

These were the instructions Crystal circulated and I got from Steve. 

Specifically to the message above I installed this one: 
Anaconda2-5.0.0.dev9-Windows-x86_64.exe 499.8M 2017-09-22 20:03:43 7cb91a31f96e185f225d6e017915fd9a 

I wiped out the VM since I need to test other versions so I cannot check the version of nbconvert withour repeating the process. However, I just did the Anaconda3 version and the second problem does not happen there. The nbconvert version there is: 5.2.1. I can try to recreate the installation and see if this is the same in the anaconda 2 version - it will take me a few hours - since the VMs are slow. 

Regardless, the first problem of being blocked by the firewall happens in the Anaconda3 installation as well. I am attaching a screenshot:

![virtualbox_vm_26_09_2017_20_31_26](https://user-images.githubusercontent.com/1986155/30891816-f4d18b7c-a2fa-11e7-8855-6e60dd4dc30c.png)

Let me know if you want me to proceed with testing - I hope I gave you sufficient information to evaluate.

**Comment by goanpeca** [comment]
Hi @Jacob-Barhak, latest installers are the rc2 ones

```
499.1M | 2017-09-26 06:05:35 | 2f69e947da7ac6780e9b14476fb887a1
-- | -- | --
Anaconda2-5.0.0.rc.2-Linux-x86.sh | 411.4M | 2017-09-26 14:48:02 | a574e495c157d59bf4ec337fa4f72ddd
Anaconda2-5.0.0.rc.2-Linux-x86_64.sh | 505.7M | 2017-09-26 14:37:21 | 2272857fcf773fc75a1bc49f6d507a48
Anaconda2-5.0.0.rc.2-Windows-x86_64.exe | 498.2M | 2017-09-26 14:30:49 | 8323b1d5f0b1c3fdb5b85efbb099beb0
```

**Comment by Jacob-Barhak** [comment]
Ok Gonzalo,

So are those known issues? Or do you want a repeat test round?

I am ok either way, as long as Stephen is ok.

**Comment by msarahan** [comment]
The 5.0 final release is out. Will try to coordinate with you better next
time.
