### ISSUE TITLE
MD5 sums mismatch for ncurses

### ISSUE THREAD

**Issue by storrgie** [ContinuumIO/anaconda-issues#616]
Trying to get R and Jupyter set up via:
```
conda install -c r r-essentials
```
But getting the following error:
```
Fetching packages ...
libgcc-4.8.5-1 100% |##########################################################| Time: 0:00:00   3.40 MB/s
ncurses-5.9-4. 100% |##########################################################| Time: 0:00:00   2.39 MB/s
ncurses-5.9-4. 100% |##########################################################| Time: 0:00:00   3.78 MB/s
ncurses-5.9-4. 100% |##########################################################| Time: 0:00:00   2.33 MB/s
ncurses-5.9-4. 100% |##########################################################| Time: 0:00:00   2.23 MB/s
Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/ncurses-5.9-4.tar.bz2 (e0ad9554f7d062cadab00b66de726f6a != 9271fc4904a6395e3221ea8ed02240a4)

```

**Comment by storrgie** [comment]
@asmeurer I'm new to conda, but I think that this package comes from the r channel? Is there a way to snag this package out of band and throw it in pkgs?

**Comment by storrgie** [comment]
Was able to move beyond ncurses by wget'ing from this location: https://anaconda.org/r/ncurses/files

However now I'm hitting this issue on seemingly every package...

requests is at version 2.9.0

**Comment by storrgie** [comment]
Revising, seems like I only his this one the following packages:

 - ncurses-5.9-4.tar.bz2
 - nlopt-2.4.2-1.tar.bz2
 - glib-2.43.0-2.tar.bz2

I simply rm'ed the .part files from pkgs/ and wget each of these individually.

**Comment by chapmanb** [comment]
I believe this is a manifestation of the problem I also filed in #621. These appear to be copied packages (like: https://anaconda.org/r/ncurses) which are currently showing this problem. Apologies for the duplicate, I didn't recognize they had the same underlying issue until digging more.

**Comment by kalefranz** [comment]
I believe this is now fixed.  Verified manually myself.
