### ISSUE TITLE
Conda install error in Windows

### ISSUE THREAD

**Issue by nansravn** [ContinuumIO/anaconda-issues#617]
<b>I´m having some trouble trying to install r-essentials packages in Windows.</b>

For example, if I try to install separatedly the packages r-digest or r-colorspace I get a 404 client error message.

Installing <b>r-digest</b>:

```
conda install -c r r-digest

Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/r/win-64/r-digest-0.6.8-0.tar.bz2: https://conda.anaconda.org/r/win-64/r-digest-0.6.8-0.tar.bz2
```

Installing <b>r-colorspace</b>:

```
conda install -c r r-colorspace

Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/r/win-64/r-colorspace-1.2_4-0.tar.bz2: https://conda.anaconda.org/r/win-64/r-colorspace-1.2_4-0.tar.bz2
```

If we take a look at the links above, we can check that that there aren't any Windows versions for both packages in the anaconda repository:
- https://anaconda.org/rgrout/r-digest/files
- https://anaconda.org/rgrout/r-colorspace/files

<b>What should I do to install these packages in Windows? I´m installing these packages in order to use the R Kernel and also %R magics (rpy2) with Jupyter. </b>

**Comment by mingwandroid** [comment]
Can you try with an updated r please?

`conda update -c r r-essentials` should get version 3.2.4.

**Comment by mingwandroid** [comment]
Closing due to lack of feedback, quite certain this is fixed.
