### ISSUE TITLE
Some r packages on win64 have md5sum mismatches and generally things are broken

### ISSUE THREAD

**Issue by kaiminglee** [ContinuumIO/anaconda-issues#618]
I followed http://conda.pydata.org/docs/r-and-r-essentials.html on win64 to install R in Anaconda (updated to latest version conda 3.19.0). The command 
`conda install -c r r-essentials` 
gives an error at the package `r-asserthat-0.1-1`:
`Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/win-64/r-assertthat-0.1-0.tar.bz2 (b3422c1a51f0867291ac20449144452a != a028678cf49255192c14c95cd3186af0)`

Manually downloading and md5summing the package from https://anaconda.org/r/r-assertthat/files shows indeed a mismatch between the actual md5 and the md5 in the package info.

**Comment by nansravn** [comment]
To deal with this bug I´ve dowloaded the file: 
    https://conda.anaconda.org/r/win-64/r-assertthat-0.1-0.tar.bz2

And then I´ve installed it locally with:

    conda install C:\Downloads\r-assertthat-0.1-0.tar.bz2

After installing <b>assertthat</b>, there were other MD5 Summing errors with other packages.

There were also this other error that i´ve reported in https://github.com/ContinuumIO/anaconda-issues/issues/617

**Comment by kaiminglee** [comment]
Thanks for the comment. I saw your issue, but it didn't look like a real duplicate. I'm looking for a fix in the repo, rather than a temp workaround, so I'll wait for the official fix from the repo maintainers.

**Comment by hrocha** [comment]
having the same issue.  Any chance this will be fixed soon?

**Comment by mingwandroid** [comment]
Hi, I'm looking at this now. It should be fixed in the next few hours.

**Comment by mingwandroid** [comment]
The md5sum for r-assertthat matches but our R on Windows story is not good (I can't install r-assertthat). I've not checked the other packages md5sums and with the state things are in given that I'm tasked with fixing R on Windows in the general sense there's little point, so I will change the title to reflect this and keep you posted on my progress.

Many thanks for your patience in this matter.

**Comment by mingwandroid** [comment]
On further investigation, it seems things aren't nearly as bleak as I painted them to be. I was able to install both r and r-essentials, and I then went through all of https://www.continuum.io/blog/developer/jupyter-and-conda-r successfully.

The build issue I mentioned previously is a different matter, so I'm closing this issue.

Thanks.
