### ISSUE TITLE
MD5 sums mismatch problem with copied packages

### ISSUE THREAD

**Issue by chapmanb** [ContinuumIO/anaconda-issues#621]
Hi all;
There appears to be a recent issue with MD5 sums for installs from anaconda.org that originate from copied packages. I can reproduce from the r channel singledispatch install. The files haven't changed in many months and installs previously worked cleanly:

https://anaconda.org/r/singledispatch/files

but as of yesterday we now see:
```
$ conda install -y -c r singledispatch
Fetching package metadata: ..........
Solving package specifications: .......................
Package plan for installation in environment /usr/local/share/bcbio_nextgen/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    singledispatch-3.4.0.3     |           py27_1          17 KB

The following NEW packages will be INSTALLED:

    singledispatch: 3.4.0.3-py27_1

Fetching packages ...
singledispatch 100% |######################################################################| Time: 0:00:00 672.61 kB/s
singledispatch 100% |######################################################################| Time: 0:00:00 558.80 kB/s
singledispatch 100% |######################################################################| Time: 0:00:00 789.17 kB/s
singledispatch 100% |######################################################################| Time: 0:00:00   5.64 MB/s
Error: MD5 sums mismatch for download: https://conda.anaconda.org/t/ch-bc25f844-3a21-4c4a-88c4-dc2db121c6ca/r/linux-64/singledispatch-3.4.0.3-py27_1.tar.bz2 (d444d0a9302013abd789d18f56cd878e != 442c7a8232b2ebd4ee3dd127111827f1)
```
The reports we've gotten (chapmanb/bcbio-nextgen#1179 chapmanb/bcbio-nextgen#1180) are also from copied packages (done before copying was deprecated).

Are there any recent changes which might have triggered this? Any possible workarounds? I've swapped over packages we used that were previously copied to native builds but now stuck on standard channels like r with this issue. Thanks much.

**Comment by yosuah** [comment]
I am hitting exactly the same issue. This issue fully breaks installing an R environment from conda, so as a not-particularly-elegant temporary hack, you can use this command to install the problematic base packages for R on linux-64:

```
wget https://anaconda.org/r/ncurses/5.9/download/linux-64/ncurses-5.9-4.tar.bz2 \
        https://anaconda.org/r/nlopt/2.4.2/download/linux-64/nlopt-2.4.2-1.tar.bz2 \
        https://anaconda.org/r/glib/2.43.0/download/linux-64/glib-2.43.0-2.tar.bz2 \
    && conda install --yes ncurses-5.9-4.tar.bz2 nlopt-2.4.2-1.tar.bz2 glib-2.43.0-2.tar.bz2
```

If you want it for another distribution, you need to find the correct file names from the 3 repositories for your environment. Please make sure to select exactly the same versions, otherwise you'll be facing issues later (for example if you install ncurses-5.9-5 then it will later get downgraded).

I tried installing from the original repositories by pinning the version number, but for some reason that didn't work.
```
conda install --yes -c https://conda.anaconda.org/asmeurer ncurses=5.9-4
```

Cheers,
Adam

**Comment by chapmanb** [comment]
Ádám;
Thanks for the workaround. I've also been hitting an issue with singledispatch, and found some additional issues with grabbing from the r references so pulled directly from Aaron's original packages and copied into the anaconda packages:
```
wget https://anaconda.org/asmeurer/ncurses/5.9/download/linux-64/ncurses-5.9-4.tar.bz2 \
     https://anaconda.org/asmeurer/nlopt/2.4.2/download/linux-64/nlopt-2.4.2-1.tar.bz2 \
     https://anaconda.org/asmeurer/glib/2.43.0/download/linux-64/glib-2.43.0-2.tar.bz2 \
     https://anaconda.org/asmeurer/singledispatch/3.4.0.3/download/linux-64/singledispatch-3.4.0.3-py27_1.tar.bz2 \
    && mv *.tar.bz2 /PATH/TO/anaconda/pkgs
```

**Comment by jbwhit** [comment]
For OSX the following worked for me: 

    wget https://anaconda.org/r/ncurses/5.9/download/osx-64/ncurses-5.9-1.tar.bz2 \
            https://anaconda.org/r/nlopt/2.4.2/download/osx-64/nlopt-2.4.2-1.tar.bz2 \
        && conda install --yes ncurses-5.9-1.tar.bz2 nlopt-2.4.2-1.tar.bz2

    conda install -y -c r r-irkernel r-recommended r-essentials

**Comment by kalefranz** [comment]
I think this has now been fixed on anaconda.org.  Please update if you encounter issues again.

**Comment by chapmanb** [comment]
Thanks so much for the fix. I can confirm it's working for me. Much appreciated.

**Comment by kikocorreoso** [comment]
Hi,
It is not working for me on a Windows 64-bits. I'm getting the error:
```
Error: MD5 sums mismatch for download:...
```
I'm using:
```
conda install -c https://conda.anaconda.org/r r-essentials 
```
or 
```
conda install -c https://conda.anaconda.org/r r-irkernel
```

**Comment by physiologoi** [comment]
Also not working on MAC OSX 10.10.5

conda install -c r r r-irkernel r-recommended r-essentials

Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/osx-64/r-codetools-0.2_14-r3.2.2_0.tar.bz2 (eebd67eaa0bbfde46e1973db03446887 != c1d78162d1cb53e6e25be0bca41ebbd0)
