### ISSUE TITLE
latest release openssl package is broken on libcrypto.a

### ISSUE THREAD

**Issue by j3mdamas** [ContinuumIO/anaconda-issues#6215]
With an update to conda version `4.3.27-py36h2866c0b_0`, we have access to openssl package version `1.0.2l-h9d1a558_3`. This particular build, which was uploaded yesterday to the defaults (https://anaconda.org/anaconda/openssl/files) started breaking a compilation command we have that uses `libcrypto.a`:

```
/usr/bin/ld: /home/joao/current/lib/libcrypto.a(rsa_lib.o): unrecognized relocation (0x29) in section `.text'
/usr/bin/ld: final link failed: Bad value
```

Any clue? @kalefranz, I see you did that build, maybe you have a clue?

If I downgrade the build to `1.0.2l-0`, the compilation works again.

(cc @stefdoerr)

**Comment by msarahan** [comment]
What gcc are you using? What binutils?

I think this is likely an issue of incompatibility with our very new compiler (gcc 7.2) and whatever you are using.

Although kalefranz did the mirroring to anaconda.org, he didn't build those packages. It was almost certainly @mingwandroid, but possibly me or @nehaljwani

If you would like to use our new compiler, I can give you some pointers. It is a conda package.

**Comment by j3mdamas** [comment]
thanks for the prompt reply @msarahan 

```
gcc version 5.2.0 (GCC)
GNU ld version 2.25.1-22.base.el7
```

I have the gcc-5 package installed (from the psi4 channel), since we depend on psi4.
Is the new gcc the one on `gcc_linux-64` package? I could try that.

João

**Comment by mingwandroid** [comment]
Your compilers are too old. You may want to use the gcc_linux-64 package
instead.

**Comment by msarahan** [comment]
using gcc_linux-64 might be a little different from using gcc-5.  It has a lot of activation scripts setting environment variables to make sure that everything works.  We have used it extensively with conda-build 3, but if you're still on conda-build 2, you might have issues.  There are example recipes using it with conda-build 3 all over https://github.com/anacondarecipes - see https://github.com/AnacondaRecipes/pytables-feedstock/blob/master/recipe/meta.yaml as one recent one

**Comment by j3mdamas** [comment]
Does it come with g++ too? I'm using the `x86_64-conda_cos6-linux-gnu-gcc` cross-compiler and it's working fine if I include `/usr/include`. But I can't find an equivalent for g++.

**Comment by msarahan** [comment]
they are split up.  you need gxx_linux-64.  There's also gfortran_linux-64.  But really, using the ``{{ compiler('c') }}`` jinja2 function that is in the example recipe I showed you is a much better way.  It resolves to these packages on linux, but also does the right thing on mac (clang and clangxx) and windows

**Comment by j3mdamas** [comment]
@msarahan thanks for tip. We are still building manually. Can we give me link to documentation on how to use these jinja2 calls in conda ymls?

**Comment by j3mdamas** [comment]
I mean, I know how to use jinja2 on conda yamls, but where is this `compiler('c)` coming from?

**Comment by msarahan** [comment]
https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/

**Comment by j3mdamas** [comment]
Thanks for all the help!
