### ISSUE TITLE
New swig-3.0.8 package does not work on CentOS 5

### ISSUE THREAD

**Issue by rmcgibbo** [ContinuumIO/anaconda-issues#622]
I just noticed today that the new swig-3.0.8 package for linux-64 uploaded today (built I think by @ilanschnell based on the last modified username in the tarball) fails to run correctly on a stock CentOS 5 (which we use as a build environment for downstream conda packages).

The [error messages](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/102265241#L316-L319) that I saw come from the fact that the `.swig-post-link.sh` depends on the existance of a binary called `xxd`, which is not that common (maybe in `yum install vim-common` http://programmer-experience.blogspot.com/2012/08/xxd-command-fedora-linux.html). (cc: https://github.com/omnia-md/conda-dev-recipes/pull/5)

**Comment by msarahan** [comment]
Thanks for this report.  I created that recipe by updating a recipe for swig 2.  I think the 3.0.2 package was created some other way, certainly with a different recipe.  We will investigate and either remove that xxd call, or package it and add a dependency.

**Comment by ilanschnell** [comment]
Correct, rebuilding swig with conda-build, and the `detect_binary_files_with_prefix` flag (as opposed to having the post install script) will fix the issue.

**Comment by msarahan** [comment]
swig-3.0.8 build 1 should fix this issue, and should now be available.  Closing.  Please reopen if you have further issues.
