### ISSUE TITLE
Placeholder too short in swig 3.0.8

### ISSUE THREAD

**Issue by mjuric** [ContinuumIO/anaconda-issues#623]
The prefix placeholder seems to have gotten shortened in 3.0.8. Code that used to build well with 3.0.2 now fails as it can't find swig include files. Inspection of the output shows this as the reason:
```
....
[sqlite-3.9.2        ]|#######################New string '/home/mjuric/projects/conda-lsst/miniconda/envs/_build/share/swig/3.0.8' is longer than old string '/opt/anaconda1anaconda2anaconda3/share/swig/3.0.8'. Skipping.
....
```
Looks like the placeholder has been made shorter than it previously was.

**Comment by msarahan** [comment]
Ping @ilanschnell - was swig 3.0.2 built as a conda recipe, then manually uploaded? I don't know why this would have changed otherwise.

**Comment by ilanschnell** [comment]
Looking at the swig 3.0.2 conda package, it was certainly created using conda-build.  To fix this issue, I think it would be easiest to use a conda recipe for swig (ie. convert the recipe).  In particular because conda-build has `detect_binary_files_with_prefix`.

**Comment by msarahan** [comment]
swig-3.0.8 build 1 should fix this issue, and should now be available.  Closing.  Please reopen if you have further issues.
