### ISSUE TITLE
should not make python symlinked to python3

### ISSUE THREAD

**Issue by meritozh** [ContinuumIO/anaconda-issues#6239]
> Install Anaconda python3 version

**Anaconda** install all its stuff in a standalone folder, default is `~/anaconda3`.

But **Anaconda** will also modify `$PATH` to make itself can be invoke through terminal.

The unsafe thing is anaconda will also install `python` which is symlinked to `pyhon3`, but python2 is not compatible with python3

Please make python3 only python3

**Comment by csoja** [comment]
This has been the case in Anaconda for a long time.  For those who use Anaconda, if this change was made it could cause a lot of problems and frustrations.  It sounds like for your use case, you should elect not to have Anaconda on path.  Anaconda makes it easy to use both Python2 and Python3 with environments. See https://conda.io/docs/user-guide/tasks/manage-python.html & https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment 
I'm going to put this as won't fix at this time.
