### ISSUE TITLE
Log all requests/responses in access log

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/anaconda-issues#624]
Please don't exclude logging any URLs. It is way harder to debug if the server got the request when debugging firewalls and such.  The log should be accurate.

https://github.com/Anaconda-Server/anaconda-server/blob/develop/binstar/server.py#L55
```
        if request.path != '/1/ping':
            common_fmt = '{remote_addr} - - [{asctime}] "{method} {path} -" {status} {content_length}'
            access_log.info(common_fmt.format(**data), data)
```

**Comment by ilanschnell** [comment]
I believe this is an Anaconda Server issue.
