### ISSUE TITLE
Anaconda no longer creates envs directory upon installation

### ISSUE THREAD

**Issue by mandeep** [ContinuumIO/anaconda-issues#6249]
After installing ``Anaconda3-5.0.0-Linux-x86_64.sh`` I noticed that the ``envs`` directory is no longer created during installation. 

System details:
``Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux``

Let me know if any other information is needed.

**Comment by nehaljwani** [comment]
@mandeep What's the benefit of having that directory?

**Comment by mandeep** [comment]
@nehaljwani For applications or plugins that call out to Conda that directory is used to look for environments. This change broke my Conda plugin for Sublime Text and I imagine there are other applications that may see breakage as well.

**Comment by nehaljwani** [comment]
So, should I blank directory with nothing in it suffice?

**Comment by nehaljwani** [comment]
But... shouldn't the plugin not assume that the directory will always be present?

**Comment by mandeep** [comment]
Historically, an empty envs directory has been created during installation. The fix was easy on my side, I'm only thinking about others who may not be as quick to react.

**Comment by csoja** [comment]
This directory was added back in Anaconda 5.0.1.  Thank you!

**Comment by mandeep** [comment]
Thanks @csoja!
