### ISSUE TITLE
libpng error: Read Error (savefig, usetex=True)

### ISSUE THREAD

**Issue by pharshalp** [ContinuumIO/anaconda-issues#6271]
Using Anaconda3-5.0.0 on 'Windows 10 - 64bit' --

- libpng 1.6.32 throws **"libpng error: Read Error"** when trying to save figures with matplotlib 2.0.2
- downgrading to libpng 1.6.30 **solves the problem** (works with matplotlib 2.0.2)
- **I didn't face this issue on mac OS (for the same version of Anaconda, libpng and matplotlib).**
UPDATE: This happens only when used with `usetex=True`

**Comment by nehaljwani** [comment]
The following works for me:
```
(6271) C:\Users\nwani>conda list libpng
# packages in environment at C:\Users\nwani\mc3\envs\6271:
#
libpng                    1.6.32           vc14hce43e6c_2  [vc14]

(6271) C:\Users\nwani>conda list matplotlib
# packages in environment at C:\Users\nwani\mc3\envs\6271:
#
matplotlib                2.0.2            py36h58ba717_1

(6271) C:\Users\nwani>python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> fig, ax = plt.subplots( nrows=1, ncols=1 )  # create figure & 1 axis
>>> ax.plot([0,1,2], [10,20,3])
[<matplotlib.lines.Line2D object at 0x0000024F7C117198>]
>>> fig.savefig('6271.png')
>>> plt.close(fig)
>>> exit()

(6271) C:\Users\nwani>dir 6271.png
 Volume in drive C has no label.
 Volume Serial Number is EAD9-8168

 Directory of C:\Users\nwani

09/30/2017  11:15 AM            22,202 6271.png
               1 File(s)         22,202 bytes
               0 Dir(s)  128,912,642,048 bytes free
```

**Comment by pharshalp** [comment]
I tried your MWE on my machine and it works (doesn't throw an error). But it still throws an error when I run my code (which uses matplotlib and libpng). So, looks like something other than matplotlib 2.0.2 is causing this. I will close this issue and dig a bit deeper to pinpoint the problem.

**Comment by mchels** [comment]
I can reproduce the issue for `usetex=True`. I also get the error message when saving as pdf. I don't get the error if no axes are created (i.e., substitute `fig = plt.figure()` for `fig, axes = plt.subplots()`) since in that case there is no text.

````C:\Users\MCHels>python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> plt.rc('text', usetex=True)
>>> fig, axes = plt.subplots()
>>> fig.savefig('foo.png')
libpng error: Read Error

C:\Users\MCHels>conda list libpng
# packages in environment at C:\Users\MCHels\Anaconda3:
#
libpng                    1.6.32           vc14hce43e6c_2  [vc14]

C:\Users\MCHels>conda list matplotlib
# packages in environment at C:\Users\MCHels\Anaconda3:
#
matplotlib                2.0.2            py36h58ba717_1
````

**Comment by pharshalp** [comment]
@mchels ahha! yep so 'usetex=True' was the reason I was getting that error... just checked this on a windows 10 machine as well as a mac. Only the windows version of libpng is giving this error when used with usetex=True

**Comment by nehaljwani** [comment]
This seems related to https://github.com/ContinuumIO/anaconda-issues/issues/6535 , which was solved by  https://github.com/AnacondaRecipes/libpng-feedstock/commit/dc7f110b6f61d39d7fd35e3f0acb6437a9fe7257

Try updating libpng. The 3rd build should have the fix.

**Comment by pharshalp** [comment]
Thanks for pointing that out @nehaljwani. Yes, the issue seems to be fixed.
