### ISSUE TITLE
Make pyopenssl and service_identity requirements for twisted

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#628]
Issue on mailing list points out that twisted needs both `pyopenssl` and `service_identity` to be able to run

    from twisted.internet import ssl

`pyopenssl` is already available in defaults, but we need to add `service_identity`.
https://pypi.python.org/pypi/service_identity

We should also add both as run requirements for `twisted`.

**Comment by ilanschnell** [comment]
I just made service_identity available.  You can now (on all platforms):
```
$ conda install service_identity
```
