### ISSUE TITLE
Anaconda-navigator crashes after Launch 

### ISSUE THREAD

**Issue by ghivikas** [ContinuumIO/anaconda-issues#6282]
Hi ,
My anaconda-navigator crashed after opening it and i am using ubuntu 16.04 and got following error on console.
(my_env) vikas@vikas-VPCEH36EN:/tmp$ anaconda-navigator
Traceback (most recent call last):
  File "/home/vikas/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Aborted (core dumped)
==========================================
output of conda info 
(my_env) vikas@vikas-VPCEH36EN:/tmp$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/vikas/anaconda3  (writable)
    default environment : /home/vikas/anaconda3/envs/my_env
       envs directories : /home/vikas/anaconda3/envs
          package cache : /home/vikas/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False
=========================================
output of conda list 
(my_env) vikas@vikas-VPCEH36EN:/tmp$ conda list
# packages in environment at /home/vikas/anaconda3/envs/my_env:
#
_license                  1.1                      py36_1  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.6.4                    py36_0  
anaconda-project          0.6.0                    py36_0  
beautifulsoup4            4.6.0                    py36_0  
certifi                   2016.2.28                py36_0  
chardet                   3.0.4                    py36_0  
clyent                    1.2.2                    py36_0  
dbus                      1.10.20                       0  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
icu                       54.1                          0  
jbig                      2.1                           0  
jpeg                      9b                            0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libiconv                  1.14                          0  
libpng                    1.6.30                        1  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
olefile                   0.44                     py36_0  
openssl                   1.0.2l                        0  
pcre                      8.39                          1  
pillow                    4.2.1                    py36_0  
pip                       9.0.1                    py36_1  
psutil                    5.2.2                    py36_0  
pyqt                      5.6.0                    py36_2  
python                    3.6.2                         0  
python-dateutil           2.6.1                    py36_0  
pytz                      2017.2                   py36_0  
pyyaml                    3.12                     py36_0  
qt                        5.6.2                         5  
qtpy                      1.3.1                    py36_0  
readline                  6.2                           2  
requests                  2.14.2                   py36_0  
ruamel_yaml               0.11.14                  py36_1  
setuptools                36.4.0                   py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
tornado                   4.5.2                    py36_0  
wheel                     0.29.0                   py36_0  
xz                        5.2.3                         0  
yaml                      0.1.6                         0  
zlib                      1.2.11                        0

**Comment by goanpeca** [comment]
@ghivikas Navigator is meant to be used in the root environment, please update to the latest version using while having the root environment activated.

Also you are using a very old `conda` you should also update it. The new release of Anaconda Distribution (5.0) is available for a week now, so I encourage you to make a fresh install :-)

https://www.anaconda.com/download/#linux
