### ISSUE TITLE
Not Able to run conda from anaconda command prompt

### ISSUE THREAD

**Issue by keshavbihani** [ContinuumIO/anaconda-issues#6321]
following issue occurs on running command prompt:
'C:\ProgramData\Anaconda3\Scripts\activate.bat' is not recognized as an internal or external command,

**Comment by csoja** [comment]
We have a fix in the most recent Miniconda installer for the "missing activate.bat" issue. Here are the current work around instructions, until a new version of the Anaconda installer is available:

Install Miniconda v4.3.31 or later from https://conda.io/miniconda.html or https://repo.continuum.io/miniconda/
Then, from the Anaconda Prompt:
conda install -y anaconda=5.0.1

For the full Anaconda 5.0.1 installer package list, use:
conda install -y anaconda=5.0.1 conda-build _ipyw_jlab_nb_ext_conf

**Comment by nnekaede** [comment]
I installed miniconda and ran from the Anaconda Prompt conda install -y anaconda=5.0.1. I then got this error: 
`Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while installing package 'defaults::ipykernel-4.6.1-py27h30cef79_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.6.1-py27h30cef79_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\nne1s\Miniconda2\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-4.6.1-py27h30cef79_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\nne1s\Miniconda2\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
`

I guess i am missing the file ipykernel-post-link.bat

**Comment by Raunak-Agrawal** [comment]
fuck

**Comment by csoja** [comment]
@Raunak-Agrawal  Can you open a new issue and fill out the template for the problem you are encountering?  The "activate.bat" issue should be fixed in Anaconda v5.1.

**Comment by Raunak-Agrawal** [comment]
which file path to add from anaconda to use django in atom? I am  being
able to use python but not django . Help me out.

**Comment by pritesh1110** [comment]
Can somebody help in solving this error.Thanks in advance!!
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::conda-4.5.4-py36_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')

**Comment by juhongm999** [comment]
@pritesh1110 Try running anaconda prompt as administrator

**Comment by rtuchman** [comment]
@csoja
If I already have anaconda installed, do I need to uninstall it before installing this miniconda?

**Comment by csoja** [comment]
This particular issue was fixed for Anaconda versions 5.1+.  If you are having a problem similar to this one in the latest installers, you may find something to help in the Troubleshooting section of the Anaconda documentation: https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#windows-error-failed-to-create-anaconda-menus-or-failed-to-add-anaconda-to-the-system-path    
To answer your specific question, Miniconda can be installed alongside Anaconda.
