### ISSUE TITLE
Navigator Error - Application Update Error

### ISSUE THREAD

**Issue by geneblandjr** [ContinuumIO/anaconda-issues#6328]
Anaconda Navigator Update error:

Extra data: line 2 column 1 - line 95 column 1 (char 48 - 4042)

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.2.12', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@geneblandjr you are using a deprecated (old) version of Navigator.

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
