### ISSUE TITLE
Add xarray (fomerly xray) to conda

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/anaconda-issues#635]
xref https://github.com/pydata/xarray/issues/721

In version 0.7.0, we renamed xray to xarray. It would be great to get v0.7.0 of both packages to conda. That way, users can either install xarray, or upgrade xray, in which case they will notice a deprecation warning telling them to switch to xarray. Both packages are now updated on pypi.

Thanks!

**Comment by ilanschnell** [comment]
Thanks for the information.  I just created and uploaded (to the default channel) packages for both `xarray` and `xray` 0.7.0.  Moving forward, we are just doing to keep uploading `xarray` then.

**Comment by shoyer** [comment]
Thanks @ilanschnell!
