### ISSUE TITLE
Deprecated files bundled into Anaconda version of numpy

### ISSUE THREAD

**Issue by zym1010** [ContinuumIO/anaconda-issues#637]
This is a clearer version of issue conda/conda#1901.

The problem is that the Anaconda version of numpy (say, <https://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.2-py27_0.tar.bz2>), has some files that are no longer in the official repository.

One such file is `numpy-1.10.2-py27_0/lib/python2.7/site-packages/numpy/fft/tests/test_fft.py`, which is no longer in the official repo <https://github.com/numpy/numpy/tree/5667fbafb5d84e3a412a07aac72c769baa590579/numpy/fft/tests>, where `5667fbafb5d84e3a412a07aac72c769baa590579` is SHA for 1.10.2.

This redundant file causes `python -c "import numpy; numpy.test()"` to fail.

I wonder if there are any more such files incorrectly bundled into the Anaconda version.

**Comment by ilanschnell** [comment]
Thanks for reporting this issue.  I forgot the exact reason, but we used an ond version of `test_fft.py` in order to test the `mklfft` package.  I removed the old version of `test_fft.py` from our build system, and once we release numpy 1.10.4, it will no longer include the old file.

**Comment by zym1010** [comment]
@ilanschnell  Thanks!
