### ISSUE TITLE
TgaImagePlugin.py function "_open()" doesn't handle case where file is corrupt

### ISSUE THREAD

**Issue by dsoodak** [ContinuumIO/anaconda-issues#638]
File "C:\Users\dsoodak\Anaconda2\lib\site-packages\PIL\TgaImagePlugin.py", line 57, in _open
    idlen = i8(s[0])
IndexError: string index out of range

Happens when trying to read corrupt file
Fixed it in my local copy of TgaImagePlugin.py with 2 lines of code
       
    def _open(self):
        s = self.fp.read(18)
       #Fix:
        if len(s)==0: #Make sure file was read
            raise SyntaxError("no lines read")

I made it a "Syntax Error" to match all the other errors thrown from this function so the library I am using knows how to handle it.

**Comment by msarahan** [comment]
Thanks for reporting this.  Please propose your fix upstream: https://github.com/python-pillow/Pillow

We do not generally fix bugs, only package tagged releases of upstream software.  If your fix is accepted upstream, we will package it when they make a new release.
