### ISSUE TITLE
Win XP on corporate network failing to load

### ISSUE THREAD

**Issue by adriantorrie** [ContinuumIO/anaconda-issues#639]
* WinXP Service Pack 3
* Corporate network sitting behind proxy (don't know if the proxy matters)
* `Anaconda3-2.4.1-Windows-x86.exe`
* Administrator install
* Installer cannot create menu
* Installer cannot register Python
* I amended system PATH to include `C:\Anaconda3` and `C:\Anaconda3\Scripts`

From the command line I try:
> `python`
I get an error in a pop up dialogue window:
`C:\Anaconda3\python.exe is not a valid Win32 application.`
Then when I close the dialogue window I get the following at the command line:
> `Access is denied.`

From the command line I try:
> `conda info`
I get the error back:
> `failed to create a process`

I have proxy user variables set and correctly url encoded:
* `http_proxy`
* `https_proxy`

Confirmed the following files exist (among others):
* `C:\Anaconda3\python.exe`
* `C:\Anaconda3\Scripts\conda.exe`

Installing as admin (luckily I have permissions) because installing in the user profile space is not an option as we are only given 30MB of profile space.

**Comment by msarahan** [comment]
Two things:

- Anaconda 2.3.0 was the last Python 3-based distribution to support Windows XP.  2.4.0+ has Python 3.5 built with Visual Studio 2015, which does not by default support WinXP.  You can install 2.3.0 and update it:

    conda update conda
    conda update --all

- User installs don't necessarily mean that you have to install to a location in your user folder.  You can tell it to install to any folder you have write access to.  It primarily affects whether shortcuts and registry modifications are done to locations that require elevation.  You can probably get away with a user-level install instead.

**Comment by adriantorrie** [comment]
The install works

I can't update using:
> `conda update conda`

Error back is:
> Fetching package metadata: Could not connect to https://repo.continuum.io/pkgs/pro/noarch
> ... other "could not connect" messages also .

I have `HTTP_PROXY` and `HTTPS_PROXY` set.

**Comment by adriantorrie** [comment]
All sorted. Thought I'd write this up as there is fragmented information over the web, I already had some of these things sorted, but I deleted everything and am able to recreate following these steps, so thought I'd post up a list to help any other unfortunates who are stuck in Win XP dinosaur land.

**For Win XP:**
* download and install [Anaconda3-2.3.0-Windows-x86.exe](https://repo.continuum.io/archive/Anaconda3-2.3.0-Windows-x86.exe)
* I installed at `C:\Anaconda`

**For corporate proxy that uses .pac file and SSL certificates for secure connections:**
* find a proxy server address from the pac file, `open Internet Explorer > Tools > Internet Options > Connections tab > LAN Settings`, and copy the address beneath `Use automatic configuration script`. Paste this address into Internet Explorer and choose `Open`. Search the file for `return` until you find what looks like a proxy IP or DNS address with the port number (if the pac file is long this may take awhile). Take note of these as you will use them later.
* create a file named `.condarc`, the [.condarc instructions](http://conda.pydata.org/docs/config.html#the-conda-configuration-file-condarc) say to create this file in your home directory, or the installation directory. I created mine in the installation directory: `C:\Anaconda\.condarc`
* add the following as per the  [.condarc instructions](http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers) (beware of special characters if you do decide to include your password in the file)

>     proxy_servers:
>         http: http://user:pass@corp.com:8080
>         https: https://user:pass@corp.com:8080
>
>     ssl_verify: False

* alterntively, if you do not wish to store user:pass credentials and will use the command line to answer authentication prompts, then:

>     proxy_servers:
>         http: http://corp.com:8080
>         https: https://corp.com:8080
>
>     ssl_verify: False

**Update conda**
* `conda update conda`

From here I can now use the Anaconda Launcher GUI to create and manage environments.

**Comment by msarahan** [comment]
Thanks for posting this. Pinging @electronwill for consideration for inclusion in our docs

**Comment by kerrywatson1** [comment]
Added to documentation action items.

**Comment by adriantorrie** [comment]
@kerrywatson1 
@electronwill 
@msarahan 

Further to the above regarding proxy issues, I found I could not install some `flask` packages (such as `flask-login`) as they were not found from the `conda install package-name` command, requiring me to use `pip install`. However pip also failed. Given I had these issues with the proxy I figured it was the same thing again, and considering I already had the `http_proxy` and `https_proxy` issue sorted I looked at SSL (which was part of the issue above). Our corporate network provides the cert for these types of connections, so I found the following helped ([attributed to an answer from SO](http://stackoverflow.com/a/29751768/893766)):

### https
`pip install --trusted-host pypi.python.org  package-name`

The SO answer also suggests if the https proxy wasn't working, to use the insecure http pypi.

### http
`pip install --index-url=http://pypi.python.org/simple/ --trusted-host pypi.python.org   package-name`

Perhaps this can be added to any documentation also, given that not all python packages are available via anaconda.

**Comment by electronwill** [comment]
I've added this to the docs at http://conda.pydata.org/docs/winxp-proxy.html . Thank you for the info, @adriantorrie .
