### ISSUE TITLE
Error Fetching Packages From Issue #631 

### ISSUE THREAD

**Issue by bpdatamining** [ContinuumIO/anaconda-issues#640]
Hi Mike,

I am sorry to open the issue again after once it was solved. 

After I recovered anaconda from #631 - I tried to create a scipy virualenv outside anaconda (for installing scikit learn and some packages to make a distributable project) which I could not as scipy was not allowed to be installed due to other dependencies BLAS, ATLAS, LAPACK etc.

The fetching packages error showed up again.

Upon starting the laucher (either at C:\python27 or C:\user...\anaconda2)
Error fetching package index
HTTPSConnectionPool(host='repo.continuum.io', port=443): Pool is closed
&
while trying to fetch any conda packages from c:\python27
requests.packages.urllib3.exceptions.ClosedPoolError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Pool is closed.

Since EC2 ELB instance was in the c:\python27, I restored the old folder again - deleted the old certificate. (as a solution that worked with #631) and edited .condarc  (I removed the repo.continuum.io URIs). The present .condarc is:

binstar_uploads: false
channels:
-https://conda.binstar.org/numba
-defaults

I uninstalled and reinstalled Anaconda in default directory C:\Users<user name>\anaconda2 (2.4.1 which is python 2.7.11)but still this is also showing above errors.

As regards cacert.pem (it resides in many folders - however, in certifi folder its not there and showing old_root.pem with weak.pem.) I tried to download new certificate - it doesn't work. 

As a test - from console the requests to repo.continuum.io shows Response [200]
but the requests.get('https://repo.continuum.io/', verify='path to cacert.pem file')
Traceback (most recent call last):
File "", line 1, in
File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
return request('get', url, *kwargs)
File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
return session.request(method=method, url=url, *kwargs)
File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
resp = self.send(prep, *send_kwargs)
File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
r = adapter.send(request, *kwargs)
File "C:\Python27\lib\site-packages\requests\adapters.py", line 331, in send
raise SSLError(e)
requests.exceptions.SSLError: [Errno bad ca_certs: 'path to cacert.pem file'] [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 ce
rtificate routines', 'X509_load_cert_crl_file', 'system lib')]

"conda update" generates following error:
AttributeError: 'HTTPResponse' object has no attribute 'tell'

Please, help. 

Many Thanks
Best Regards,
Bhoomin Pandya

**Comment by bpdatamining** [comment]
Hi Mike, 

I want to thank you and the team  especially Andrey Petrov for the urllib3 documentation Release Dev January 27, 2016.

The solution is (With Deleted  _license-1.1-py27_1.tar.bz2 certificate as in earlier solution) I had to update the Certifi and Requests with pip install -U certfi (as cacert.pem was missing):

At the console
>>> import requests
>>> import urllib3
>>> from urllib3 import HTTPSConnectionPool
>>> pool = HTTPSConnectionPool('repo.continuum.io', maxsize=1)
>>> r = pool.request('GET','/pkgs/free/win-32/', fields={'q': 'urllib3', 'v': '1.0'})
C:\Python27\lib\site-packages\urllib3\util\ssl_.py:316: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform.
 This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissin
gwarning.
  SNIMissingWarning
C:\Python27\lib\site-packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause c
ertain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Python27\lib\site-packages\urllib3\connectionpool.py:790: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

After this start the launcher. the iPython-notebook instance works. 
I have found the solution (not free from some errors I suppose).  I hope it lasts. 
I would be grateful if you can let me know how safe this is and any other better solution. 

Best Regards, 
Bhoomin Pandya

**Comment by nehaljwani** [comment]
The presence of `C:\Python27\lib\site-packages\` in the output suggests that you have a separate, standalone installation of Python2.7 and it is likely being picked up. Please make sure that you do not have either of `C:\Python27` in `PATH` environment variable and `C:\Python27\Lib\site-packages` in `PYTHONPATH` environment variable.
