### ISSUE TITLE
sysconfig.get_config_var("CC") problem

### ISSUE THREAD

**Issue by sunqm** [ContinuumIO/anaconda-issues#6410]
In anaconda 5.0.1, sysconfig.get_config_var("CC") returns
gcc -pthread -B /xx/xx/xx/compiler_compat

This causes problem in distutils.unixccompiler.UnixCCompiler. runtime_library_dir_option function that gcc compiler was not recognized.

```
from distutils import unixccompiler
print unixccompiler.UnixCCompiler().runtime_library_dir_option("")
```
It should be "-Wl,-R", not "-R".

**Comment by mingwandroid** [comment]
Confirmed, basename is called on this value, giving `compiler_compat`. Seems Python insists on having nothing but an executable name in `CC`.
