### ISSUE TITLE
No scipy 0.16.1 for win-32/win-64?

### ISSUE THREAD

**Issue by mstimberg** [ContinuumIO/anaconda-issues#642]
We are affected by the `solve_banded` regression from scipy 0.15.1 to 0.16.0 (scipy/scipy#5127) which was fixed with scipy release 0.16.1 -- it appears that there are no Windows builds for this release, though: https://anaconda.org/anaconda/scipy/files?version=0.16.1

This is problematic for us, since we cannot simply use scipy 0.15.1 either, since this does not have any Python 3.5 builds.

**Comment by ilanschnell** [comment]
Scipy 0.16.1 as well as 0.17.0 will be available very soon, but for technical reasons we cannot release them yet.
