### ISSUE TITLE
Fatal Error when Installing running Launcher

### ISSUE THREAD

**Issue by Drekko** [ContinuumIO/anaconda-issues#643]
Hello guys
I have deployed this through a batch file as I need to set up an unattended install through SCCM
I choose to install the software for All Users and it works however I cannot get one shortcut to work, the Launcher shortcut launches but gives me a fatal error when doing so;

I am installing the software to the windows 7 machines and installing it to C:\Anaconda3

And the Launcher shortcut properties are pointing to the correct paths:
Target: C:\Anaconda3\node-webkit\nw.exe "C:\Anaconda3/node-webkit/launcher"
Start in: C:\Anaconda3

![launcher](https://cloud.githubusercontent.com/assets/16935659/12641441/a9534de6-c603-11e5-9ef2-58be90142ce6.png)

**Comment by Drekko** [comment]
Let me know if you need additional info such as the batch file script etc

**Comment by barryloper** [comment]
As a workaround until this bug is fixed, I've found that allowing the installer to add Anaconda's python to the path and make it the default python makes the launcher work.

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
