### ISSUE TITLE
path.py is missing a dependency on pytest

### ISSUE THREAD

**Issue by gmarkall** [ContinuumIO/anaconda-issues#645]
Installing path.py 8.1.2 into an environment results in a file `lib/python3.5/site-packages/test_path.py` getting installed into the environment. This contains an `import pytest` statement.

The unittest module can occasionally stumble across this module during test discovery, leading to tracebacks like:

```
======================================================================
ERROR: test_path (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_path
Traceback (most recent call last):
  File "/home/gmarkall/miniconda35/envs/_test/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/gmarkall/miniconda35/envs/_test/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/gmarkall/miniconda35/envs/_test/lib/python3.5/site-packages/test_path.py", line 31, in <module>
    import pytest
ImportError: No module named 'pytest'
```

I imagine that path.py should depend on pytest in order to avoid this import failure when trying to use the unittest module in unrelated packages.

**Comment by msarahan** [comment]
Sorry, I disagree with this.  IMHO, people should limit the scope of their tests when running them.  Does unittest have a way of doing this?  I know I have done such things with nose and py.test.

In general, if test discovery is finding things outside of your desired package/module, I think you have a problem with your test method, not with whatever packages are in your environment.

This said, it's easy enough to add py.test, but this then propagates to an unknown number of packages in our ecosystem which should also be changed, ultimately leading to a situation where we probably ultimately always install all test runners by default.

**Comment by gmarkall** [comment]
I understand your point of view. The package I was working with did not limit the scope very tightly (beginning in `site-packages`, hence the issue). I haven't yet determined whether it's normal to use unittest in this way (discover nearly everything then "prune" unwanted things, which I guess is happening) or whether it's more usual to start within the module under test.

**Comment by msarahan** [comment]
If you have a module that lives in site-packages, I would explicitly point the test runner at that module, rather than leaving it to discover the whole of site-packages.

Some docs here on unittest: https://docs.python.org/devguide/runtests.html

**Comment by ilanschnell** [comment]
I agree with @msarahan, packages have to limit the testing scope.  Discovering all tests in `site-packages` is a disaster waiting to happen.
