### ISSUE TITLE
List and install packages in Launcher

### ISSUE THREAD

**Issue by binnisb** [ContinuumIO/anaconda-issues#647]
First, is the code for anaconda / launcher not open source? I was a bit sad to see that I can't submit a patch...

The Launcher is awesome! I love how simple it is to switch envs, install the pre-selected packages etc. It would be more awesome to be able to manage all packages from there as well. 

I assume that the Launcher is mainly for "non-programmers", or rather users that would rather not mess around with terminal stuff (Matlab / Mathematica users etc), it would be very beneficial for them to be able to list installed packages, search and install packages from the launcher as well. Why have the launcher if you then force users to go to terminal, activate env, install packages anyway? You would then just start ipython notebook from terminal as well.

**Comment by binnisb** [comment]
Well, ignore my first remark about not being able to submit a patch, I stumbled upon github.com/conda just now :)

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
