### ISSUE TITLE
Launching jupyter from windows menu does not activate the environement

### ISSUE THREAD

**Issue by petrushy** [ContinuumIO/anaconda-issues#6471]
Hi,

Launching jupyter for a particular environment through the windows menu does not perform a full activation of the environment. I am using the activate scripts to set up some environment variables for a package (JCC/orekit). A workaround is to enter the environments command prompt and then jupyter notebook, but I would think the expected behaviour from the menu is that it should be the same.

I guess this can be performed either through script or through the conda-wrapper addons.

Many thanks

**Comment by davidshen84** [comment]
I think this issue has been resolved.

I can create a custom environment and launch Jupyter with the activated environment. I tried from both the command line and the Windows Start menu.

**Comment by csoja** [comment]
Thank you for reporting that it is resolved.  Closing...
