### ISSUE TITLE
Miniconda install for all users fails on Windows 10

### ISSUE THREAD

**Issue by jennirinker** [ContinuumIO/anaconda-issues#6473]
When I ran the installer for the latest version of miniconda (as an administrator) with the option checked for it to be installed for all users, I received an error message that the installer couldn't write certain files. I then had to abort the installation. I have since deleted the partial installation files, then re-ran the installer with the option now checked for a "just me" installation, and the installer completed successfully.

OS: Windows 10 (sorry to be a pain...)
Miniconda installer: 64-bit "latest" windows installer
conda version: 4.3.27

**Comment by csoja** [comment]
Did you have full Administrator privileges when you ran Miniconda as an Administrator?  It sounds based on the error message that you lacked the permissions for an installation for all users.  I'm glad to hear the Just Me installation completed successfully.  I'm going to go ahead and close this issue, as it sounds like you have a working Anaconda installation.
