### ISSUE TITLE
scipy-0.17.0-np110py27_0.tar.bz2 doesn't require libgfortran

### ISSUE THREAD

**Issue by dpryan79** [ContinuumIO/anaconda-issues#648]
It seems that scipy-0.17.0-np110py27_0.tar.bz2 doesn't require libgfortran in its recipe. This causes many things that need scipy and are running on TravisCI to fail.

**Comment by dpryan79** [comment]
xref: https://github.com/conda/conda/issues/2028

**Comment by patricksnape** [comment]
I'm also seeing this across all versions of my [builds](https://travis-ci.org/menpo/menpo/jobs/107266079)

**Comment by msarahan** [comment]
Should be fixed: https://github.com/conda/conda/issues/2028#issuecomment-180488079

**Comment by patricksnape** [comment]
Thanks @msarahan!

**Comment by dpryan79** [comment]
It works now, thanks!

**Comment by patricksnape** [comment]
@msarahan It is still broken for 0.16.1! Same issue!

**Comment by msarahan** [comment]
Pinging @ilanschnell

**Comment by ilanschnell** [comment]
`scipy 0.16.1` should also be fixed now.
