### ISSUE TITLE
Problem withj Anaconda3 installation on Mac OS Sierra

### ISSUE THREAD

**Issue by joegallivan** [ContinuumIO/anaconda-issues#6511]
/Users/Joe2/anaconda/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
when trying to run a notebook supplied by Open Learn.  Also get "The operation can’t be completed because the original item for “Anaconda-Navigator” can’t be found." when trying to launch Anaconda from Applications.

**Comment by joegallivan** [comment]
Moved on a bit now from the above - when I did conda install navigator, the message no longer appeared. The problem is now, when I click on the Navigator icon on my iMac running OSX Sierra, the application briefly appears then crashes with an error message: "Anaconda Navigator quit unexpectedly. Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple." and a choice of Ignore, Report or Reopen.

**Comment by joegallivan** [comment]
Finally resolved - did conda update anaconda-navigator and it installed 3 new packages (anaconda-project, beautifulsoup4 (where DO they get these names from!!) and chardet) as well as going from 1.3.2-py34_0 of navigator to 1.5.0-py34_0. Navigator burst into life when I clicked on it in Applications - and immediately suggested I update navigator to version 1.6.2. I decided to forego that pleasure and quit whilst I was ahead.

**Comment by nicholasadam9** [comment]
hi, sounds like you were able to fix the issue with installing. I think I'm having the same error as you. I've updated anaconda-navigator, and those 3 packages were already installed. Any ideas on how I should proceed?

**Comment by goanpeca** [comment]
@joegallivan we do not support python 3.4 so I suggest you upgrade to 3.5 or 3.6. The latest version of Navigator is 1.6.8.

@nicholasadam9 you will need to update to the latest version of conda and the do the necessary updates. If you are using python 3.4 you will need to update to 3.5 or 3.6

**Comment by nicholasadam9** [comment]
@goanpeca I downloaded yesterday, what I believe was the latest version. I also ran update in terminal and it said version is up to date., which I believe is 3.6.
