### ISSUE TITLE
a few problems with inspector and help

### ISSUE THREAD

**Issue by betaglobin** [ContinuumIO/anaconda-issues#6513]
Hi,
I have updated Anaconda to the latest version and something is wrong with the following things:
1. Inspector (Cmd + I) doesn't work, I can't get any help of any object.
2. Despite the checkbox in Preferences -> Help -> Automatic Connections -> Editor is checked, I don't get any help with the arguments while I'm implementing.
3. Tab button, as a name auto-filler doesn't work.

The problem appears after 5-10 min of running the Sypder. To fix that, I need to kill the Anaconda and turn on everything again. But after a few minutes it's the same.
Anaconda Navigator 1.6.8
Spyder 3.2.3
macOS 10.13

**Comment by ccordoba12** [comment]
Please reopen this issue in

https://github.com/spyder-ide/spyder/issues
