### ISSUE TITLE
libpng error: Write Error

### ISSUE THREAD

**Issue by sn2234** [ContinuumIO/anaconda-issues#6535]
Uninstalled Anaconda 4 and installed Anaconda 5 on windows server 2016 (VS2017 preview on the same machine), Anaconda 4 worked fine
(C:\Users\Administrator\Anaconda3) C:\Users\Administrator\Documents>conda list libpng
# packages in environment at C:\Users\Administrator\Anaconda3:
#
libpng                    1.6.32           vc14hce43e6c_2  [vc14]

(C:\Users\Administrator\Anaconda3) C:\Users\Administrator\Documents>conda list matplotlib
# packages in environment at C:\Users\Administrator\Anaconda3:
#
matplotlib                2.0.2            py36h58ba717_1

(C:\Users\Administrator\Anaconda3) C:\Users\Administrator\Documents>python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> xx = (np.random.rand(100, 100) > 0.5).astype('uint8')
>>> xx.shape
(100, 100)
>>> plt.imshow(xx)
<matplotlib.image.AxesImage object at 0x00000190EB0040B8>
>>> plt.imsave("xx.png", xx)
libpng error: Write Error

(C:\Users\Administrator\Anaconda3) C:\Users\Administrator\Documents>dir xx.png
 Volume in drive C has no label.
 Volume Serial Number is D89A-3D90

 Directory of C:\Users\Administrator\Documents

10/09/2017  05:26 PM                 0 xx.png
               1 File(s)              0 bytes
               0 Dir(s)  40,410,468,352 bytes free

(C:\Users\Administrator\Anaconda3) C:\Users\Administrator\Documents>

**Comment by mingwandroid** [comment]
Single-line reproducer:

`python -c "import numpy as np; import matplotlib.pyplot as plt; xx = (np.random.rand(100, 100) > 0.5).astype('uint8'); plt.imsave('C:\\xx.png', xx)"`

**Comment by mingwandroid** [comment]
Any chance of testing with this new package?:

`conda update -c c3i_test2 libpng`

**Comment by sn2234** [comment]
Works for me now, thanks!

**Comment by mingwandroid** [comment]
Thank you for the feedback.

**Comment by bsipocz** [comment]
@mingwandroid - is there an ETA for the fixed packages getting distributed in the default channel? I'm just asking to see whether it makes any sense to add a workaround for our failing appveyor builds or can simply just wait this out.

**Comment by mingwandroid** [comment]
@bsipocz, Did the new package work for you or are you not in a position to test them?

**Comment by bsipocz** [comment]
It worked for one of our maintainers on his windows laptop, haven't checked it on appveyor yet.

**Comment by mingwandroid** [comment]
This has been released now, please close if this works for you @bsipocz.

**Comment by bsipocz** [comment]
@mingwandroid - Thank you, indeed it works now.

(I can't close the issue though as it wasn't me who opened it).

**Comment by mingwandroid** [comment]
OK, thank you for the feedback, closing.
