### ISSUE TITLE
New gcc version not compatible with cuda

### ISSUE THREAD

**Issue by tbung** [ContinuumIO/anaconda-issues#6555]
I am trying to build pytorch, this requires me to install cmake and gcc with conda. 

The new cmake version requires a recent version of `gcc`, installed via `gcc_linux-64`, while the cuda dependencies of pytorch require `gcc` version 5 or under. 

 Installing an older version of cmake is not possible with current conda, as this raises an `unsatisfiable dependency` error with `libedit`.

**Comment by mingwandroid** [comment]
It's pretty trivial to build whatever GCC versions we need, but I'd rather not unless strictly necessary.

**Comment by jjhelmus** [comment]
I had no issues using gcc 4.8.5 provided by the system to compiled pytorch 0.2.0.  The key is to not include the `gcc` package in the build environment as it pulls in libgcc which can clobber libstdc++ files coming from other packages.  I can provide more details @tbung if you are interested.

Trying to use gcc 7.2.0 provided by the `gcc_linux-64` package seems like a more difficult path.  To begin with modifications are needed to the header files provided by NVIDIA to suppress the gcc version check.  With those modification the build proceeds further but fails with `nullptr is undefined` errors similar to torch/torch7#682.  This may be coming from the fact that g++ 7.2.0 defaults to c++14 where as nvcc assumes c++98.  It may be possible to address this issue by passing the appropriate flags to nvcc.

**Comment by tbung** [comment]
Thank you very much for your help!

I, too, managed to build pytorch with gcc 5.4.0 provided by the system. Additionally, the pytorch guys [removed gcc from the conda install suggestions](https://github.com/pytorch/pytorch/commit/f74665f0c4b0caa8d667cd8d3e2bb764ac92bae0), so this issue can be closed now, since it is only about projects stopping to depend on/suggest the old `gcc` package and not about an actual issue with `conda`.

Thanks again for your time and patience! :blush:
