### ISSUE TITLE
nomkl is not available on Windows

### ISSUE THREAD

**Issue by gmarkall** [ContinuumIO/anaconda-issues#656]
On my 64-bit Windows installation of Miniconda:

```
[accelerate-dev-py35] C:\Users\gmarkall\work\accelerate>conda install nomkl
Fetching package metadata: ....
Error: No packages found in current win-64 channels matching: nomkl

Did you mean one of these?

    mkl

You can search for this package on anaconda.org with

    anaconda search -t conda nomkl
```

**Comment by ilanschnell** [comment]
The `nomkl` package is not available on Windows.  This is pointed out in my blog post: https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations
There are currently no plans to make this package available on Windows,

**Comment by gmarkall** [comment]
Thanks for the reply - I wasn't sure whether there were plans for it to be available on Windows in the future.

**Comment by ivoflipse** [comment]
This issue contains a better explanation for the why:
https://github.com/conda/conda-recipes/pull/586

**Comment by pwuertz** [comment]
Is building a nomkl distribution for Windows still an issue today?

Following the official [How to use OpenBLAS in Microsoft Visual Studio](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#1-native-msvc-abi) guide for building a native (MSVC) ABI OpenBLAS library works just fine. Building and linking `numpy` and `scipy` against native OpenBLAS builds works too.

As good as MKL may be for Intel users, it is well known that MKL (purposefully?) does a bad job on AMD CPUs, unless you happen to know the secret workaround of the day. Also, installing / distributing ~ 1 GB of MKL kernels for multiplying a few numpy arrays feels a bit out of proportion at times.

Being able to opt-out MKL in Anaconda would be really helpful.
