### ISSUE TITLE
Navigator error occoured when tried to open anaconda-navigator in ubuntu

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#6560]
_From @Devanya on August 23, 2017 23:16_

![screenshot from 2017-08-24 04-43-19](https://user-images.githubusercontent.com/29503559/29642537-1d37bb92-8887-11e7-8739-bc74ac2fcff6.png)

_Copied from original issue: conda/conda#5874_

**Comment by kalefranz** [comment]
_From @Devanya on August 23, 2017 23:25_

![screenshot from 2017-08-24 04-54-49](https://user-images.githubusercontent.com/29503559/29642780-78ee9d7e-8888-11e7-9487-fa0a632ed7e0.png)
![screenshot from 2017-08-24 04-55-17](https://user-images.githubusercontent.com/29503559/29642795-8221801e-8888-11e7-8400-b2b610178aa8.png)

**Comment by kalefranz** [comment]
_From @Devanya on August 25, 2017 12:38_

Some please look into this

**Comment by kalefranz** [comment]
_From @goanpeca on August 25, 2017 12:42_

@devanya, if you do 

```
$ source activate root
$ anaconda-navigator
```

?

**Comment by kalefranz** [comment]
_From @goanpeca on August 25, 2017 12:43_

Also the right repository to report this is https://github.com/ContinuumIO/anaconda-issues

**Comment by goanpeca** [comment]
@kalefranz on linux under some circumstances we always need to run source activate to run navi. The latest version has a much better messaging to indicate that the env needs to be activated.

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
