### ISSUE TITLE
Failed to initialize anaconda directory etc.

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#6589]
_From @oathofoblivion on June 24, 2017 10:27_

So, I've been trying to install anaconda for python3  for the past few months and I've been having no success at all. I always encounter exactly three error messages saying it can't initialize Anaconda directory etc. But, somehow yesterday when I used the same installer executable that I've been using for the past few months, it seems to run perfectly and didn't give the error messages that I've been seeing these past few months. As for what changed, the only thing that I did was I completely cleared any traces of Python3 that was installed on my PC (The directories of vanilla python3 and all its content, the python launcher, previous failed installation of anaconda, and cleaned my registry of any possible problems). Hope this helps with solving the problem that seems to be a common issue for Anaconda users.

_Copied from original issue: conda/conda#5593_

**Comment by kalefranz** [comment]
I'm sure this is just a dll hell issue.  But I'll move it to ContinuumIO/anaconda-issues so it can be closed from there.

**Comment by csoja** [comment]
Yes, sounds like one of the previous Python installations was conflicting with the new Anaconda installation.  Glad to hear this user managed to work through the issues and get Anaconda installed successfully.

**Comment by gitanuurage** [comment]
I am trying to install Anaconda3-2022.05-Windows-x86_64 on my Windows 10 OS.
After 20-25 minutes I am getting error of "FAILED TO INITIALIZED ANACONDA DIRECTORIES" and "Failed to run post install script"
I can see complete installation but Anaconda Navigator doesn't initiates.
Please help.

**Comment by DhruvRakhra2204** [comment]
@gitanuurage I am also facing the same issue

**Comment by GabeHells** [comment]
Go to C:\Users\"YOUR USER" and delete anything related to Python3. It will work.

**Comment by Sewens** [comment]
I found one dummy cause of failed init conda.
REMOVE the `.condarc` file from any directory where conda will loads.
