### ISSUE TITLE
qt.conf

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#66]
Whenever building qt or pyqt, it can be good to know about http://qt-project.org/doc/qt-4.8/qt-conf.html.

**Comment by cmeeren** [comment]
I don't know if this is relevant, but I fixed the missing Windows taskbar icon (for Spyder) by editing `C:\Anaconda\qt.conf` (which already existed) and changing the `Prefix` and `Binaries` paths to `C:\Anaconda\Lib\site-packages\PyQt4` (they were previously set to something that didn't exist on my system).

**Comment by ccordoba12** [comment]
This was fixed in Anaconda 2.2 by adding a `qt.conf` file for all platforms.

**Comment by webmedic** [comment]
what about anaconda 3. I'm running the latest version with all updates and it does not load svg icons.
