### ISSUE TITLE
RSS feed for package updates

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#660]
As discussed in this twitter exchange:

https://mobile.twitter.com/astrofrog/status/697072162948149248

it would be nice to have an RSS feed that reports updates to packages available via conda. Just to be clear, I'm not talking about releases of Anaconda, but rather information each day about which packages now have newer versions in conda (as an example, ``numpy 1.10.4 py27_0`` was made available on 2016-01-25).

Many packages now rely on conda for continuous integration, and sometimes an issue appears, and it can take a while to track down which package caused the issue, so having an RSS feed would help us narrow down the possibilities.

**Comment by ilanschnell** [comment]
We have something similar to an RSS feed: http://repo.continuum.io/pkgs/git-log.txt
I'll think about turning that information into an RSS feed.

**Comment by ilanschnell** [comment]
Hey, check out http://repo.continuum.io/pkgs/rss.xml

**Comment by astrofrog** [comment]
@ilanschnell - this is perfect, thanks!!

**Comment by kalefranz** [comment]
Wow that's awesome @ilanschnell
