### ISSUE TITLE
Installation of python 3.3 and 3.4 fail due to pysocks dependency

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#6615]
_From @bwohlberg on October 7, 2017 15:28_

Recent changes (this was working a few days ago) appear to have broken python 3.3 and 3.4:

```
$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
$ bash miniconda.sh -b -p $HOME/miniconda
$ export PATH="$HOME/miniconda/bin:$PATH"
$ conda update --yes -q conda
$ conda install --yes python=3.4
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pysocks -> python 3.6*
  - python 3.4*
```

Doing `conda info pysocks` indicates that there are no versions of the package available for python 3.3 and 3.4. It's not clear whether this issue is due to removal of these packages, or the introduction of a spurious dependency.

_Copied from original issue: conda/conda#6098_

**Comment by kalefranz** [comment]
Might be good for @nehaljwani to take a look at.  We haven't made pysocks a conda dependency, but it looks like it's now a dependency of something else being included in the latest miniconda installers.

If that's true, we should build pysocks at least for python 3.4.

**Comment by kalefranz** [comment]
@bwohlberg Does `conda create --dry-run python=3.3` and `conda create --dry-run python=3.4` still work for you?

**Comment by bwohlberg** [comment]
@kalefranz Yes, those both seem to work without any problems.

**Comment by rlmv** [comment]
This has been breaking our builds as well. Is there a workaround for this?

**Comment by kalefranz** [comment]
I see what happened.  We unbundled pip recently because of a path-length issue on windows (vendoring packages that had vendored packages).  Looks like we unbundled pip on all platforms, not just Windows.  And apparently pysocks is a package that is bundled with pip, so it's now included in miniconda.

Also, we don't have a python 3.4 build of pysocks.

1. We should just build a python 3.4 version of pysocks, even though we don't generally support adding packages to python 3.4 any longer.
2. We should probably only unbundle pip on Windows.

CC @mingwandroid @nehaljwani

**Comment by kalefranz** [comment]
@bwohlberg @rlmv  In the meantime,

    conda remove --yes pysocks

should fix the immediate error and let you proceed.  (You might end up removing pip in the process, which might be fine for you.)  Note though that if we release a new miniconda without pysocks as a conda-installed package, and you stick with https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh rather than pinning to a specific version and then using `conda update conda`, then `conda remove pysocks` might end up giving an error.

**Comment by mingwandroid** [comment]
We do not support Python 3.4 anymore. I don't understand why we would want to encourage the use of it? If you want to continue to use Python 3.4 you should not install the latest miniconda.

**Comment by msarahan** [comment]
Unbundling was only ever done for windows.  https://github.com/AnacondaRecipes/pip-feedstock/commit/56498da3a241bb4973b366fcc8da3fb5bea6f7a7#diff-e178b687b10a71a3348107ae3154e44cR17

Please look elsewhere for the issue, but I'm also with Ray on this.

**Comment by kalefranz** [comment]
I was wrong that the issue is related to pip unbundling.  My apologies for that.  It's actually related to requests unbundling its dependencies, which happened in the upstream, and not us unbundling pip.

Either way, ultimately, the best solution is to use environments.  Especially if you're doing something with older versions of python.  So

    conda create -n py33 python=3.3
    source activate py33

for example, or

    conda create -p ./env python=3.3
    source activate ./env

**Comment by rlmv** [comment]
Environments did the trick. Thanks for the help @kalefranz - I appreciate it!
