### ISSUE TITLE
Fatal Error cloning root environment using Launcher from Anaconda3-2.5.0-Windows-x86_64

### ISSUE THREAD

**Issue by mobcdi** [ContinuumIO/anaconda-issues#662]
After installing Anaconda3-2.5.0-Windows-x86_64 on Windows 10 I cloned the root environment and it got as far as pygt before showing an alert saying it encountered a fatal error

**Comment by ygautomo** [comment]
I have same issues,.on Anaconda2-2.5.0
After installing Anaconda2-2.5.0-Windows-x86_64 on Windows 8 I cloned the root environment and it got as far as pygt before showing an alert saying it encountered a fatal error

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
