### ISSUE TITLE
Anaconda Navigator does not launch application

### ISSUE THREAD

**Issue by JihedC** [ContinuumIO/anaconda-issues#6631]
Hello,

I have some issues with anaconda. 
R studio is installed and I can find in in the anaconda3/bin but it does not start. This is what I get:
<img width="438" alt="capture d ecran 2017-10-13 a 15 33 58" src="https://user-images.githubusercontent.com/22910541/31551572-e39bce1e-b02c-11e7-8ed3-9e89100aa339.png">

Here is the conda info:

Current conda install:

               platform : osx-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 2.1.17
         python version : 3.6.2.final.0
       requests version : 2.13.0
       root environment : /Users/jihedchouaref/anaconda3  (writable)
    default environment : /Users/jihedchouaref/anaconda3/envs/rstudio
       envs directories : /Users/jihedchouaref/anaconda3/envs
                          /Users/jihedchouaref/.conda/envs
          package cache : /Users/jihedchouaref/anaconda3/pkgs
                          /Users/jihedchouaref/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/jihedchouaref/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.13.0 CPython/3.6.2 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

#packages in environment at /Users/jihedchouaref/anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
alabaster                 0.7.10                   py36_1    conda-forge
anaconda                  custom                   py36_0    defaults
anaconda-client           1.6.5                      py_0    conda-forge
anaconda-navigator        1.6.8            py36hee14809_1    defaults
anaconda-project          0.8.0                    py36_0    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
appscript                 1.0.1                    py36_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
astroid                   1.5.3                    py36_0    conda-forge
astropy                   2.0.2               np113py36_1    conda-forge
babel                     2.4.0                    py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
bcftools                  1.6                           0    bioconda
beautifulsoup4            4.6.0                    py36_0    conda-forge
bioconductor-annotate     1.50.0                 r3.3.2_1    bioconda
bioconductor-annotationdbi 1.38.0                 r3.3.2_0    bioconda
bioconductor-biobase      2.36.2                        0    bioconda
bioconductor-biocgenerics 0.22.0                 r3.3.2_0    bioconda
bioconductor-biocparallel 1.6.6                  r3.3.2_1    bioconda
bioconductor-biomart      2.30.0                 r3.3.2_0    bioconda
bioconductor-biostrings   2.42.1                 r3.3.2_0    bioconda
bioconductor-deseq2       1.16.1                 r3.3.2_0    bioconda
bioconductor-edger        3.16.5                 r3.3.2_0    bioconda
bioconductor-genefilter   1.58.1                 r3.3.2_0    bioconda
bioconductor-geneplotter  1.50.0                 r3.3.2_0    bioconda
bioconductor-genomeinfodb 1.10.3                 r3.3.2_0    bioconda
bioconductor-genomicalignments 1.10.0                 r3.3.2_0    bioconda
bioconductor-genomicfeatures 1.26.4                 r3.3.2_0    bioconda
bioconductor-genomicranges 1.26.4                 r3.3.2_0    bioconda
bioconductor-iranges      2.8.2                  r3.3.2_0    bioconda
bioconductor-limma        3.30.13                r3.3.2_0    bioconda
bioconductor-nucler       2.8.0                  r3.3.2_0    bioconda
bioconductor-rsamtools    1.26.1                 r3.3.2_0    bioconda
bioconductor-rtracklayer  1.34.2                 r3.3.2_1    bioconda
bioconductor-s4vectors    0.12.2                 r3.3.2_0    bioconda
bioconductor-shortread    1.32.0                 r3.3.2_0    bioconda
bioconductor-summarizedexperiment 1.4.0                  r3.3.2_2    bioconda
bioconductor-tximport     1.4.0                  r3.3.2_0    bioconda
bioconductor-xvector      0.14.1                 r3.3.2_0    bioconda
bioconductor-zlibbioc     1.20.0                 r3.3.2_1    bioconda
biopython                 1.70                     py36_1    conda-forge
bitarray                  0.8.1                    py36_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3                   py36_0    conda-forge
bleach                    1.4.2                    py36_0    bioconda
blinker                   1.4                      py36_0    conda-forge
bokeh                     0.12.9                   py36_0    conda-forge
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1                    py36_1    conda-forge
bowtie2                   2.3.3.1          py36pl5.22.0_0    bioconda
bwa                       0.7.15                        1    bioconda
bz2file                   0.98                     py36_0    defaults
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.8                        0    defaults
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
cloudpickle               0.4.0                    py36_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
conda                     4.3.29                   py36_0    conda-forge
conda-build               2.1.17                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
contextlib2               0.5.5                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
curl                      7.55.1               h7601780_3    defaults
cutadapt                  1.14                     py36_0    bioconda
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.27.1                   py36_0    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
dask                      0.15.4                     py_0    conda-forge
dask-core                 0.15.4                     py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
distributed               1.19.2                   py36_0    conda-forge
docrep                    0.1.2                    py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
expat                     2.2.1                         0    conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
fasteners                 0.14.1                   py36_2    conda-forge
fastqc                    0.11.5               pl5.22.0_2    bioconda
filelock                  2.0.6                    py36_0    conda-forge
flask                     0.12.2                   py36_0    conda-forge
flask-cors                3.0.3                    py36_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                          0    defaults
font-ttf-inconsolata      2.000                         0    defaults
font-ttf-source-code-pro  2.030                         0    defaults
font-ttf-ubuntu           0.83                          0    defaults
fontconfig                2.12.1                        3    defaults
fonts-continuum           1                             0    defaults
freetype                  2.5.5                         2    defaults
funcargparse              0.1.2                    py36_1    conda-forge
gensim                    2.3.0               np113py36_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.1rc4                   py36_0    bioconda
glib                      2.50.2                        1    defaults
glob2                     0.4.1                    py36_0    bioconda
gmp                       6.1.2                         0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
greenlet                  0.4.12                   py36_0    conda-forge
gsl                       2.2.1           blas_openblas_2  [blas_openblas]  conda-forge
h5netcdf                  0.4.3                      py_0    conda-forge
h5py                      2.7.1                    py36_1    conda-forge
harfbuzz                  0.9.39                        2    defaults
hdf4                      4.2.12                        0    defaults
hdf5                      1.8.18                        0    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
htslib                    1.5                           0    bioconda
icu                       54.1                          0    defaults
idna                      2.6                      py36_1    conda-forge
imageio                   2.2.0                    py36_0    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
intel-openmp              2018.0.0             hdd0ccc9_7    defaults
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.0.1                      py_2    conda-forge
iso-639                   0.4.5                     <pip>
iso3166                   0.8                       <pip>
isort                     4.2.15                   py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
java-jdk                  8.0.92                        1    bioconda
jbig                      2.1                           0    conda-forge
jdcal                     1.3                      py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      8d                            2    defaults
jsonschema                2.6.0                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
jupyterlab                0.27.0                   py36_2    conda-forge
jupyterlab_launcher       0.5.3                    py36_0    conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                         1    bioconda
libgcc                    4.8.5               hdbeacc1_10    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.14                          4    conda-forge
libnetcdf                 4.4.1.1                       5    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.4                         0    defaults
libxslt                   1.1.29                        4    conda-forge
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.0.0                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2               np113py36_0    defaults
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
mkl                       2018.0.0             hc285769_4    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mmtf-python               1.0.9                      py_0    conda-forge
monotonic                 1.3                      py36_0    conda-forge
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
multipledispatch          0.4.9                    py36_0    conda-forge
navigator-updater         0.1.0            py36h7aee5fb_0    defaults
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   6.0                  ha932d30_1    defaults
netcdf4                   1.3.0                    py36_0    conda-forge
networkx                  2.0                      py36_0    conda-forge
nlopt                     2.4.2                    py36_2    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.1.0                    py36_0    conda-forge
numba                     0.35.0              np113py36_6    defaults
numexpr                   2.6.4                    py36_0    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
numpydoc                  0.7.0                    py36_0    conda-forge
oauthlib                  2.0.4                      py_0    conda-forge
odo                       0.5.1                    py36_0    conda-forge
olefile                   0.44                     py36_0    conda-forge
openblas                  0.2.19                        2    conda-forge
openjdk                   8.0.121                       1    defaults
openpyxl                  2.4.0                    py36_0    bioconda
openssl                   1.0.2l                        0    conda-forge
packaging                 16.8                     py36_0    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pango                     1.40.3                        1    defaults
partd                     0.3.8                    py36_0    conda-forge
path.py                   10.3.1                   py36_0    conda-forge
pathlib2                  2.3.0                    py36_0    conda-forge
patsy                     0.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pep8                      1.7.0                    py36_0    conda-forge
perl                      5.22.0.1                      0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    3.4.2                    py36_0    defaults
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
pkginfo                   1.4.1                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.3.1                    py36_0    conda-forge
psyplot                   1.0.0.post1              py36_0    conda-forge
psyplot-gui               1.0.1                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycosat                   0.6.2                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycryptodome              3.4.7                     <pip>
pycurl                    7.43.0           py36hdb90038_3    defaults
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyjwt                     1.5.3                      py_0    conda-forge
pylint                    1.7.1                    py36_0    conda-forge
pyodbc                    4.0.17                   py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytables                  3.4.2               np113py36_4    conda-forge
pytest                    3.2.3                    py36_0    conda-forge
python                    3.6.2                         0    conda-forge
python-crfsuite           0.9.2                    py36_0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
python.app                2                py36h02ac5de_5    defaults
pytz                      2017.2                   py36_0    conda-forge
pywavelets                0.5.2               np113py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_0    conda-forge
qt                        5.6.2                         2    defaults
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.3.1                    py36_0    conda-forge
r                         3.3.2                  r3.3.2_0    conda-forge
r-acepack                 1.4.1                  r3.3.2_0    conda-forge
r-assertthat              0.1                    r3.3.2_0    conda-forge
r-backports               1.0.5                  r3.3.2_0    conda-forge
r-base                    3.3.2                         0    defaults
r-base64enc               0.1_3                  r3.3.2_0    conda-forge
r-bh                      1.60.0_2               r3.3.2_0    bioconda
r-bitops                  1.0_6                  r3.3.2_0    conda-forge
r-boot                    1.3_18                 r3.3.2_0    conda-forge
r-brew                    1.0_6                  r3.3.2_0    conda-forge
r-broom                   0.4.2                  r3.3.2_0    conda-forge
r-car                     2.1_4                  r3.3.2_0    conda-forge
r-caret                   6.0_76                 r3.3.2_0    conda-forge
r-catools                 1.17.1                 r3.3.2_1    bioconda
r-cellranger              1.1.0                  r3.3.2_0    conda-forge
r-checkmate               1.8.2                  r3.3.2_0    conda-forge
r-chron                   2.3_50                 r3.3.2_0    conda-forge
r-class                   7.3_14                 r3.3.2_0    conda-forge
r-cluster                 2.0.6                  r3.3.2_0    conda-forge
r-codetools               0.2_15                 r3.3.2_0    conda-forge
r-colorspace              1.3_2                  r3.3.2_0    conda-forge
r-commonmark              1.2                    r3.3.2_0    conda-forge
r-crayon                  1.3.2                  r3.3.2_0    conda-forge
r-curl                    2.4                    r3.3.2_0    conda-forge
r-data.table              1.10.4                 r3.3.2_0    bioconda
r-dbi                     0.6_1                  r3.3.2_0    conda-forge
r-desc                    1.1.0                  r3.3.2_0    conda-forge
r-devtools                1.13.2                 r3.3.2_0    conda-forge
r-dichromat               2.0_0                  r3.3.2_0    conda-forge
r-digest                  0.6.12                 r3.3.2_0    conda-forge
r-dplyr                   0.5.0                  r3.3.2_1    bioconda
r-essentials              1.0                          0a    defaults
r-evaluate                0.10                   r3.3.2_0    conda-forge
r-forcats                 0.2.0                  r3.3.2_0    conda-forge
r-foreach                 1.4.3                  r3.3.2_0    conda-forge
r-foreign                 0.8_67                 r3.3.2_0    conda-forge
r-formatr                 1.4                    r3.3.2_0    conda-forge
r-formula                 1.2_1                  r3.3.2_0    conda-forge
r-futile.logger           1.4.1                  r3.3.2_0    bioconda
r-futile.options          1.0.0                  r3.3.2_0    bioconda
r-gdata                   2.17.0                 r3.3.2_0    conda-forge
r-getopt                  1.20.0                 r3.3.2_0    bioconda
r-ggplot2                 2.2.1                  r3.3.2_0    bioconda
r-gistr                   0.4.0                  r3.3.2_0    conda-forge
r-git2r                   0.19.0                 r3.3.2_0    conda-forge
r-glmnet                  2.0_5                  r3.3.2_0    conda-forge
r-gplots                  3.0.1                  r3.3.2_0    conda-forge
r-gridextra               2.2.1                  r3.3.2_0    conda-forge
r-gtable                  0.2.0                  r3.3.2_0    conda-forge
r-gtools                  3.5.0                  r3.3.2_0    conda-forge
r-haven                   1.0.0                  r3.3.2_0    conda-forge
r-hexbin                  1.27.1                 r3.3.2_0    conda-forge
r-highr                   0.6                    r3.3.2_0    conda-forge
r-hmisc                   4.0_3                  r3.3.2_0    conda-forge
r-hms                     0.3                    r3.3.2_0    conda-forge
r-htmltable               1.9                    r3.3.2_0    conda-forge
r-htmltools               0.3.6                  r3.3.2_0    conda-forge
r-htmlwidgets             0.9                    r3.3.2_0    conda-forge
r-httpuv                  1.3.3                  r3.3.2_0    conda-forge
r-httr                    1.2.1                  r3.3.2_0    conda-forge
r-hwriter                 1.3.2                  r3.3.2_0    bioconda
r-irdisplay               0.4.4                  r3.3.2_0    conda-forge
r-irkernel                0.8.7                  r3.3.2_0    conda-forge
r-iterators               1.0.8                  r3.3.2_0    conda-forge
r-itertools               0.1_3                  r3.3.2_0    bioconda
r-jpeg                    0.1_8                  r3.3.2_0    conda-forge
r-jsonlite                1.4                    r3.3.2_0    conda-forge
r-kernsmooth              2.23_15                r3.3.2_0    conda-forge
r-knitr                   1.12.3                 r3.3.2_0    bioconda
r-labeling                0.3                    r3.3.2_0    conda-forge
r-lambda.r                1.1.7                  r3.3.2_0    bioconda
r-lattice                 0.20_34                r3.3.2_0    conda-forge
r-latticeextra            0.6_28                 r3.3.2_0    conda-forge
r-lazyeval                0.2.0                  r3.3.2_0    conda-forge
r-lme4                    1.1_13                 r3.3.2_0    conda-forge
r-locfit                  1.5_9.1                r3.3.2_2    bioconda
r-lubridate               1.6.0                  r3.3.2_0    conda-forge
r-magrittr                1.5                    r3.3.2_0    conda-forge
r-maps                    3.2.0                  r3.3.2_0    conda-forge
r-markdown                0.8                    r3.3.2_0    conda-forge
r-mass                    7.3_45                 r3.3.2_0    conda-forge
r-matrix                  1.2_7.1                r3.3.2_0    conda-forge
r-matrixmodels            0.4_1                  r3.3.2_0    conda-forge
r-memoise                 1.1.0                  r3.3.2_0    conda-forge
r-mgcv                    1.8_17                 r3.3.2_0    conda-forge
r-mime                    0.5                    r3.3.2_0    conda-forge
r-minqa                   1.2.4                  r3.3.2_0    conda-forge
r-mnormt                  1.5_5                  r3.3.2_0    conda-forge
r-modelmetrics            1.1.0                  r3.3.2_0    conda-forge
r-modelr                  0.1.0                  r3.3.2_0    conda-forge
r-munsell                 0.4.3                  r3.3.2_0    conda-forge
r-nlme                    3.1_131                r3.3.2_0    conda-forge
r-nloptr                  1.0.4                  r3.3.2_0    conda-forge
r-nnet                    7.3_12                 r3.3.2_0    conda-forge
r-openssl                 0.9.7                  r3.3.2_0    conda-forge
r-packrat                 0.4.8_1                r3.3.2_0    conda-forge
r-pbdzmq                  0.2_4                  r3.3.2_0    conda-forge
r-pbkrtest                0.4_7                  r3.3.2_0    conda-forge
r-pki                     0.1_3                  r3.3.2_0    conda-forge
r-plogr                   0.1_1                  r3.3.2_0    conda-forge
r-plyr                    1.8.4                  r3.3.2_0    conda-forge
r-png                     0.1_7                  r3.3.2_0    conda-forge
r-pryr                    0.1.2                  r3.3.2_0    conda-forge
r-psych                   1.5.8                  r3.3.2_0    bioconda
r-purrr                   0.2.2                         1    bioconda
r-quantmod                0.4_8                  r3.3.2_0    conda-forge
r-quantreg                5.33                   r3.3.2_0    conda-forge
r-r6                      2.2.0                  r3.3.2_0    conda-forge
r-randomforest            4.6_12                 r3.3.2_0    conda-forge
r-rbokeh                  0.5.0                  r3.3.2_0    conda-forge
r-rcolorbrewer            1.1_2                  r3.3.2_0    conda-forge
r-rcpp                    0.12.13                r3.3.2_0    conda-forge
r-rcpparmadillo           0.7.800.2.0            r3.3.2_0    conda-forge
r-rcppeigen               0.3.2.9.1              r3.3.2_0    conda-forge
r-rcurl                   1.95_4.8               r3.3.2_0    conda-forge
r-readr                   0.2.2                  r3.3.2_0    bioconda
r-readxl                  1.0.0                  r3.3.2_0    conda-forge
r-recommended             3.3.2                  r3.3.2_0    conda-forge
r-rematch                 1.0.1                  r3.3.2_0    conda-forge
r-repr                    0.10                   r3.3.2_0    conda-forge
r-reshape2                1.4.2                  r3.3.2_0    conda-forge
r-rjson                   0.2.15                 r3.3.2_0    conda-forge
r-rjsonio                 1.3_0                  r3.3.2_0    conda-forge
r-rmarkdown               0.9.5                  r3.3.2_0    bioconda
r-roxygen2                6.0.1                  r3.3.2_0    conda-forge
r-rpart                   4.1_10                 r3.3.2_0    conda-forge
r-rprojroot               1.2                    r3.3.2_0    conda-forge
r-rsconnect               0.7                    r3.3.2_0    conda-forge
r-rserve                  1.7_3                  r3.3.2_0    conda-forge
r-rsqlite                 1.1_2                  r3.3.2_0    conda-forge
r-rstudioapi              0.7                    r3.3.2_0    conda-forge
r-rvest                   0.3.2                  r3.3.2_0    conda-forge
r-scales                  0.4.1                  r3.3.2_1    bioconda
r-selectr                 0.3_1                  r3.3.2_0    conda-forge
r-shiny                   1.0.3                  r3.3.2_0    conda-forge
r-snow                    0.4_1                  r3.3.2_0    bioconda
r-sourcetools             0.1.6                  r3.3.2_0    conda-forge
r-sparsem                 1.76                   r3.3.2_0    conda-forge
r-spatial                 7.3_11                 r3.3.2_0    conda-forge
r-stringi                 1.1.2                  r3.3.2_0    conda-forge
r-stringr                 1.2.0                  r3.3.2_0    conda-forge
r-survival                2.40_1                 r3.3.2_0    conda-forge
r-tibble                  1.2                    r3.3.2_1    bioconda
r-tidyr                   0.6.1                  r3.3.2_0    conda-forge
r-tidyverse               1.1.1                  r3.3.2_0    conda-forge
r-ttr                     0.23_1                 r3.3.2_0    conda-forge
r-uuid                    0.1_2                  r3.3.2_0    conda-forge
r-viridis                 0.3.1                  r3.3.2_0    bioconda
r-whisker                 0.3_2                  r3.3.2_0    conda-forge
r-withr                   1.0.2                  r3.3.2_0    conda-forge
r-xml                     3.98_1.6               r3.3.2_0    conda-forge
r-xml2                    1.1.1                  r3.3.2_0    conda-forge
r-xtable                  1.8_2                  r3.3.2_0    conda-forge
r-xts                     0.9_7                  r3.3.2_0    conda-forge
r-yaml                    2.1.14                 r3.3.2_0    conda-forge
r-zoo                     1.7_14                 r3.3.2_0    conda-forge
readline                  6.2                           2    defaults
reportlab                 3.4.0                    py36_0    defaults
requests                  2.13.0                   py36_0    conda-forge
requests-oauthlib         0.8.0                    py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
rstudio                   1.0.44                        0    defaults
ruamel_yaml               0.11.14                  py36_0    conda-forge
samtools                  1.5                           1    bioconda
scikit-image              0.13.0                   py36_2    conda-forge
scikit-learn              0.19.0          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     0.19.1          py36_blas_openblas_202  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py36_0    conda-forge
setuptools                36.3.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
smart_open                1.5.3                    py36_0    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sortedcollections         0.5.3                    py36_0    conda-forge
sortedcontainers          1.5.7                    py36_0    conda-forge
sphinx                    1.6.4                    py36_0    conda-forge
sphinx_rtd_theme          0.2.4                    py36_0    conda-forge
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.3                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
streamlink                0.8.1                     <pip>
sympy                     1.1.1                    py36_0    conda-forge
tbb                       4.4_20150728                  0    bioconda
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
toolz                     0.8.2                      py_2    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
trim-galore               0.4.4                pl5.22.0_0    bioconda
twython                   3.6.0                    py36_0    conda-forge
typing                    3.5.2.2                  py36_0    bioconda
unicodecsv                0.14.1                   py36_0    conda-forge
unixodbc                  2.3.4                         1    conda-forge
urllib3                   1.12                     py36_0    bioconda
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
websocket-client          0.44.0                    <pip>
werkzeug                  0.12.2                     py_1    conda-forge
wget                      1.19.1               hcb5d8a9_0    defaults
wheel                     0.30.0                     py_1    conda-forge
widgetsnbextension        3.0.3                    py36_2    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xarray                    0.9.6                    py36_0    conda-forge
xlrd                      1.1.0                    py36_1    conda-forge
xlsxwriter                0.9.8                    py36_0    conda-forge
xlwings                   0.11.4                   py36_0    conda-forge
xlwt                      1.3.0                    py36_0    conda-forge
xopen                     0.1.1                    py36_0    bioconda
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.1.5                         0    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                        0    conda-forge

Actually I realize now that anaconda does not launch any of the applications. Can someone help me ?

**Comment by mingwandroid** [comment]
You have attempted to mix packages from `defaults` and `conda-forge` in the same environment. At present this is not possible as we are not binary-compatible.

**Comment by JihedC** [comment]
Can I do something about it?
