### ISSUE TITLE
Please add useful packages to Anaconda - 'python-gnupg', 'pysftp', 'keras', 'cufflinks'

### ISSUE THREAD

**Issue by sholvick** [ContinuumIO/anaconda-issues#6637]
Hello - These are general packages that would be very useful to have included in the Anaconda distribution.  Thanks!
- python-gnupg  (pip install python-gnupg)

cufflinks | pip | pip install   cufflinks | Library for easy   interactive Pandas charting with Plotly.

python-gnupg | pip | pip install   python-gnupg | Python wrapper for the Gnu Privacy Guard (GPG or GnuPG)     https://pythonhosted.org/python-gnupg/#before-you-start

pysftp | pip | pip install pysftp | Simple sFTP library   used to connect to sFTP directories to upload or download data files.  Info: https://pypi.python.org/pypi/pysftp

keras | pip | pip install keras | Deep learning   library for advanced neural network algorithms (similar to TensorFlow)

**Comment by danielee0707** [comment]
Also consider ggplot maybe?

**Comment by tnilanon** [comment]
`keras` is already available. You can't find it?

```
$ conda search keras
Fetching package metadata ...........
keras                        1.1.1                    py27_0  defaults        
                             1.1.1                    py34_0  defaults        
                             1.1.1                    py35_0  defaults        
                             2.0.2                    py27_0  defaults        
                             2.0.2                    py35_0  defaults        
                             2.0.2                    py36_0  defaults        
                             2.0.5                    py27_0  defaults        
                             2.0.5                    py35_0  defaults        
                             2.0.5                    py36_0  defaults        
keras-gpu                    2.0.2                    py27_0  defaults        
                             2.0.2                    py35_0  defaults        
                             2.0.2                    py36_0  defaults        
                             2.0.5                    py27_0  defaults        
                             2.0.5                    py35_0  defaults        
                             2.0.5                    py36_0  defaults        

```

**Comment by tnilanon** [comment]
`pysftp` is also available in `conda-forge`.

```
$ conda search -c conda-forge pysftp
Fetching package metadata .............
pysftp                       0.2.9                    py27_0  conda-forge     
                             0.2.9                    py35_0  conda-forge     
                             0.2.9                    py36_0  conda-forge     
```

**Comment by tnilanon** [comment]
`python-gnupg` is also available in `conda-forge`.

```
$ conda search -c conda-forge python-gnupg
Fetching package metadata .............
python-gnupg                 0.3.8                    py27_0  conda-forge     
                             0.3.8                    py34_0  conda-forge     
                             0.3.8                    py35_0  conda-forge     
                             0.3.8                    py36_0  conda-forge
```

**Comment by sholvick** [comment]
Hi @tnilanon - Thank you for the response.  I honestly was not aware that conda-forge had additional packages available.  I was able to find all the packages you mentioned and should be good to go for now.  I do feel, however, that the pysftp and python-gnupg libraries are worth considering for inclusion in the base Anaconda distribution, but this is a great workaround for the time being.

Thank you for helping out, this question can be closed :)

**Comment by sholvick** [comment]
Per comments from @tnilanon above, the question can be closed.  I still think a few of these packages should be considered for inclusion in the base Anaconda distribution (pysftp, python-gnupg), but the above recommendations resolve my immediate need.  Thank you!

**Comment by tnilanon** [comment]
@sholvick Glad I could help. I agree that it will be easier for users if Continuum can expand their default repo, but that would mean extra work maintaining those packages.
