### ISSUE TITLE
Failed to create menus

### ISSUE THREAD

**Issue by vasu001** [ContinuumIO/anaconda-issues#6659]
I know this issue already listed, but no solution seems to work with Anaconda3 5.0 x64 windows for me.
Tried every solution listed here.

Don't have Java path.

Had anaconda 3 4.4 which worked fine. This one is not installing.

**Comment by msarahan** [comment]
please see #3488 for more discussion and some workarounds that other users have found. The conflicting DLLs in PATH or cyrillic/non-ascii characters in install paths definitely seem to be the culprits, and we're working on addressing that for the next release.

Closing as duplicate.
