### ISSUE TITLE
Psycopg2 cannot be installed in anaconda due to dependency issues

### ISSUE THREAD

**Issue by gorlins** [ContinuumIO/anaconda-issues#666]
This is on a Mac El Capitan but I believe it to be true for linux as well

    $ conda create -n mytest psycopg2=2.6.1 anaconda=2.5.0
    Fetching package metadata: ....
    Solving package specifications: ..........
    Error: Unsatisfiable package specifications.
    Generating hint:

    Hint: the following packages conflict with each other:
      - psycopg2 2.6.1*
      - anaconda 2.5|2.5.0*

This appears to be due to specifying an older version of openssl than is required for anaconda or python 2.7.11:

    $ conda info psycopg2=2.6.1
    psycopg2 2.6.1 py27_0
    ---------------------
    file name   : psycopg2-2.6.1-py27_0.tar.bz2
    name        : psycopg2
    version     : 2.6.1
    build number: 0
    build string: py27_0
    channel     : defaults
    size        : 281 KB
    date        : 2015-09-29
    license     : LGPL, BSD-like, ZPL
    license_family: LGPL
    md5         : 21e269ee15a8ebda571e60e41720e028
    installed environments:
    dependencies:
        openssl 1.0.1*
        python 2.7*

    $ conda info anaconda=2.5.0 | grep openssl
        openssl 1.0.2f 0
        pyopenssl 0.15.1 py35_1
        openssl 1.0.2f 0
        pyopenssl 0.15.1 py34_1
        openssl 1.0.2f 0
        pyopenssl 0.15.1 py27_1

    $ conda info python=2.7.11 | grep openssl
        openssl 1.0.2*

Package installs successfully if python is downgraded to python=2.7.10

**Comment by ilanschnell** [comment]
`psycopg2` has been rebuild against the new `openssl` 1.0.2, which fixes this issue.

**Comment by gorlins** [comment]
thanks!
