### ISSUE TITLE
Cython 0.23.4 OSX py2 conda package mislabeled

### ISSUE THREAD

**Issue by richafrank** [ContinuumIO/anaconda-issues#667]
I've got miniconda2 installed on osx-64.  `conda install` gives me a seemingly incorrect version of cython:

``` bash
$ conda create --name temp27 python=2.7 cython=0.23.4
$ source activate temp27
$ conda list|grep -i cython
cython                    0.23.4                   py27_1  
$ python -c "import Cython;print Cython.__version__"
0.22.1
```

When cythonizing during `conda build` later, I get:

```
error: [Errno 2] No such file or directory: '/Users/rich/miniconda2/envs/_build/lib/python2.7/site-packages/Cython/Utility/Generator.c'
```

**Comment by kalefranz** [comment]
kfranz@0283:~ ❯ conda create --name temp27 python=2.7 cython=0.23.4
    ...
    kfranz@0283:~ ❯ source activate temp27
    discarding /Users/kfranz/.conda/bin from PATH
    prepending /Users/kfranz/.conda/envs/temp27/bin to PATH
    (temp27)kfranz@0283:~ ❯ conda list|grep -i cython
    cython                    0.23.4                   py27_1
    (temp27)kfranz@0283:~ ❯ python -c "import Cython;print Cython.__version__"
    0.23.4
    (temp27)kfranz@0283:~ ❯ conda info
    Current conda install:

                 platform : osx-64
            conda version : 3.19.1
      conda-build version : 1.18.2
           python version : 2.7.10.final.0
         requests version : 2.9.1
         root environment : /Users/kfranz/.conda  (writable)
      default environment : /Users/kfranz/.conda/envs/temp27
         envs directories : /Users/kfranz/.conda/envs
            package cache : /Users/kfranz/.conda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/osx-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : /Users/kfranz/.condarc
        is foreign system : False

Can you give your `conda info` here?

**Comment by richafrank** [comment]
```bash
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/rich/miniconda2  (writable)
  default environment : /Users/rich/miniconda2
     envs directories : /Users/rich/miniconda2/envs
        package cache : /Users/rich/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by nehaljwani** [comment]
Not able to reproduce this:
```bash
(root) ➜  ~ conda create --name temp27 python=2.7 cython=0.23.4
(root) ➜  ~ source activate temp27
(temp27) ➜  ~ conda list cython
# packages in environment at /Users/nwani/m3/envs/temp27:
#
cython                    0.23.4                   py27_1
(temp27) ➜  ~ python -c "import Cython;print Cython.__version__; print Cython.__path__"
0.23.4
['/Users/nwani/m3/envs/temp27/lib/python2.7/site-packages/Cython']
```

@richafrank Could you please share output for:
```bash
(temp27) ➜  ~ python -c "import Cython; print Cython.__path__"
```

**Comment by richafrank** [comment]
Sure thing:
```bash
$ python -c "import Cython; print Cython.__path__"
['/Users/rich/miniconda2/envs/temp27/lib/python2.7/site-packages/Cython']
```

**Comment by nehaljwani** [comment]
@richafrank Do the output for the following commands match?
```zsh
(root) ➜  ~ source activate temp27
(temp27) ➜  ~ grep __version__ $CONDA_PREFIX/lib/python2.7/site-packages/Cython/Shadow.py
__version__ = "0.23.4"
(temp27) ➜  ~ grep __version__ $CONDA_PREFIX/../../pkgs/cython-0.23.4-py27_1/lib/python2.7/site-packages/Cython/Shadow.py
__version__ = "0.23.4
```

**Comment by richafrank** [comment]
Hmm, still 0.22...

```bash
$ grep __version__ $CONDA_PREFIX/lib/python2.7/site-packages/Cython/Shadow.py
__version__ = "0.22.1"
$ grep __version__ $CONDA_PREFIX/../../pkgs/cython-0.23.4-py27_1/lib/python2.7/site-packages/Cython/Shadow.py
__version__ = "0.22.1"
```

**Comment by nehaljwani** [comment]
That's super weird. Try this:
```bash
mv $CONDA_PREFIX/../../pkgs/cython-0.23.4-py27_1 $CONDA_PREFIX/../../pkgs/cython-0.23.4-py27_1.bak
conda create -yn temp27new python=2.7 cython=0.23.4
source activate temp27new
python -c "import Cython;print Cython.__version__"
```

**Comment by richafrank** [comment]
Ok, end result:
```bash
$ python -c "import Cython;print Cython.__version__"
0.23.4
```
I must have had a bad package from somewhere... At least it's good now. Thanks!
