### ISSUE TITLE
libgfortran-ng missing _gfortran_stop_numeric_f08

### ISSUE THREAD

**Issue by mkgrei** [ContinuumIO/anaconda-issues#6676]
Linux
miniconda3-4.3.11

numpy etc. installed from conda command requires libgfortran-ng=7.2.0
However, _gfortran_stop_numeric_f08 is missing in the installed libgfortran.so.4.0.0.
numpy etc. works fine, but self-implemented fortran codes crash.

$ nm -D ~/.pyenv/versions/miniconda3-4.3.11/lib/libgfortran.so.4.0.0 | grep numeric
000000000001be8d T _gfortran_error_stop_numeric
000000000001bcba T _gfortran_pause_numeric
000000000001bde8 T _gfortran_stop_numeric

numpy etc. in miniconda3-4.1.11 requires libgfortran=3.0.0, which has both _gfortran_stop_numeric_f08 and _gfortran_stop_numeric.
Is this some kind of major change to remove the backward compatibility?

$ nm -D ~/.pyenv/versions/miniconda3-4.1.11/lib/libgfortran.so.3.0.0 | grep numeric
000000000001acc0 T _gfortran_error_stop_numeric
000000000001aa80 T _gfortran_pause_numeric
000000000001abb0 T _gfortran_stop_numeric
000000000001abf0 T _gfortran_stop_numeric_f08

**Comment by mingwandroid** [comment]
It is a very recent version of `libgfortran`. You need to link to it and should use our compilers to do that:

`conda install gfortran_linux-64`
