### ISSUE TITLE
Matplotlib loading DLL error, Anaconda 4.4.0 after update or Anaconda 5.0.0

### ISSUE THREAD

**Issue by Iwan-Zotow** [ContinuumIO/anaconda-issues#6683]
Windows 7 Pro SP1 64bit, up-to-date. If I install Anaconda 4.4.0 my scripts and running `python -c "import matplotlib.pyplot"` works quite well. If I update conda and anaconda to version 5.0.0 from 4.4.0, or install fresh Anaconda 5.0.0 installer, running `python -c "import matplotlib.pyplot"`  will produce

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\qt_compat.py", line 128, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified procedure could not be found.

PyQt5 backend is used in both cases

**Comment by mingwandroid** [comment]
Did you let the installer add Anaconda to your PATH? Do you have any old anaconda in your PATH?

**Comment by Iwan-Zotow** [comment]
Yes, I let the installer add Anaconda to my path. This is private installation. No, I removed any mentions of Anaconda from my path when I uninstalled 4.4 and installed 5.0 and vice versa, and rebooted.

Not sure it is path related. If I install fresh 4.4.0, all is working. If I just issue commands `conda update conda` and then `conda update anaconda`, I'll get a lot of packages updated, but matplotlib won't work anymore.

**Comment by mingwandroid** [comment]
Can you try launching Python from the `Anaconda Prompt` please?

**Comment by Iwan-Zotow** [comment]
From `Anaconda Prompt` scripts with matplotlib appears to be working

**Comment by mingwandroid** [comment]
OK, this shows that you have `DLLs` in your `PATH` that conflict with the `DLLs` of the `Anaconda Distribution`. This is commonly called DLL-hell.

The only way around it is to not add things to `PATH` when you can avoid it (including the `Anaconda Distribution`; there is a warning about this in the installer) , esp. things installed for `All Users` since those appear before any user `PATH` entries.

That AD 4.4 did not conflict is just luck.

**Comment by Jarvis73** [comment]
Oh, I have met the same problem and I have fixed it. You just need to add _the five anaconda paths_ to your _system variables_ and make sure them in the front of other paths. 

Of course you can keep the five paths in the original position(maybe in your _user variables_), but you need to screen which path containing `Qt5Core.dll`, `Qt5Gui.dll` and `Qt5Widgets.dll`. My mistake is the path of `cmake-gui` whose location is in the front of `anaconda`, containing the three dlls.

**Comment by mingwandroid** [comment]
The best way to handle PATH and DLL-hell is to avoid them as much as possible. Let no installer add anything to PATH when given the choice.

For Anaconda on Windows we provide the Anaconda Prompt for CLI users and Anaconda Navigator for people who would rather not.

Both of these will add the necessary entries to the front of PATH *for that session only* meaning you are safe from other software in PATH causing problems for Anaconda but equally importantly safe from Anaconda causing problems for other software.
