### ISSUE TITLE
Anaconda homepage is blank

### ISSUE THREAD

**Issue by rajesh1980** [ContinuumIO/anaconda-issues#6684]
After upgrading to 1.6 Anaconda home page is showing blank. Earlier i used to get Spyder, RStudio Orange etc. 
I have tried anaconda-navigator --reset but no effect.

Attaching op of conda info and conda list
`C:\Rajesh>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Rajesh\Anaconda3  (writable)
    default environment : C:\Rajesh\Anaconda3
       envs directories : C:\Rajesh\Anaconda3\envs
                          C:\Users\rramach1\AppData\Local\conda\conda\envs
                          C:\Users\rramach1\.conda\envs
          package cache : C:\Rajesh\Anaconda3\pkgs
                          C:\Users\rramach1\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\rramach1\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.14393
          administrator : False`
conda list
`
# packages in environment at C:\Rajesh\Anaconda3:
#
_license                  1.1                      py36_1
alabaster                 0.7.10           py36hcd07829_0
anaconda                  5.0.0            py36hea9b2fc_0
anaconda-client           1.6.5            py36hd36550c_0
anaconda-navigator        1.6.8            py36h4b7dd57_0
anaconda-project          0.8.0            py36h8b3bf89_0
anyqt                     0.0.8                    py36_0
asn1crypto                0.22.0           py36h8e79faa_1
astroid                   1.5.3            py36h9d85297_0
astropy                   2.0.2            py36h06391c4_4
babel                     2.5.0            py36h35444c1_0
backports                 1.0              py36h81696a8_1
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2
beautifulsoup4            4.6.0            py36hd4cc5e8_1
bitarray                  0.8.1            py36h6af124b_0
bkcharts                  0.2              py36h7e685f7_0
blaze                     0.11.3           py36h8a29ca5_0
bleach                    2.0.0            py36h0a7e3d6_0
bokeh                     0.12.7           py36h012f572_1
boto                      2.48.0           py36h1a776d2_1
boto                      2.47.0                    <pip>
bottleneck                1.2.1            py36hd119dfa_0
bz2file                   0.98                      <pip>
bzip2                     1.0.6            vc14hdec8e7a_1  [vc14]
ca-certificates           2017.08.26           h94faf87_0
cachecontrol              0.12.3           py36hfe50d7b_0
cchardet                  1.1.3                     <pip>
certifi                   2017.4.17                 <pip>
certifi                   2017.7.27.1      py36h043bc9e_0
cffi                      1.10.0           py36hae3d1b5_1
chardet                   3.0.4                     <pip>
chardet                   3.0.4            py36h420ce6e_1
chest                     0.2.3                    py36_0
click                     6.7              py36hec8c647_0
cloudpickle               0.4.0            py36h639d8dc_0
clyent                    1.2.2            py36hb10d595_1
colorama                  0.3.9            py36h029ae33_0
comtypes                  1.1.2            py36heb9b3d1_0
conda                     4.3.29           py36h7c1b203_0
conda-env                 2.6.0                h36134e3_1
configobj                 5.0.6                    py36_0
configparser              3.5.0                     <pip>
console_shortcut          0.1.1                haa4cab3_2
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.0.3            py36h123decb_1
curl                      7.55.1           vc14hdaba4a4_3  [vc14]
cycler                    0.10.0           py36h009560c_0
cython                    0.26.1           py36h18049ac_0
cytoolz                   0.8.2            py36h547e66e_0
dask                      0.15.2           py36h25e1b01_0
dask-core                 0.15.2           py36hf9e56b0_0
datadotworld              1.2.0                     <pip>
datapackage               0.8.9                     <pip>
datashape                 0.5.4            py36h5770b85_0
decorator                 4.1.2            py36he63a57b_0
dill                      0.2.7.1          py36hf552773_0
distlib                   0.2.5            py36h51371be_0
distributed               1.18.3           py36h5be4c3e_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3            py36hfd66bb0_2
et_xmlfile                1.0.1            py36h3d2d736_0
ezodf                     0.3.2                     <pip>
fastcache                 1.0.2            py36hffdae1b_0
filelock                  2.0.12           py36hd7ddd41_0
flask                     0.12.2           py36h98b5e8f_0
flask-cors                3.0.3            py36h8a3855d_0
font-ttf-dejavu-sans-mono 2.37                 h6964260_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                h7457263_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fonts-continuum           1                             0
freetype                  2.8              vc14h17c9bdf_0  [vc14]
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py36h342a76c_0
glob2                     0.5              py36h11cc1bd_1
greenlet                  0.4.12           py36ha00ad21_0
h5py                      2.7.0            py36hfbe0a52_1
hdf5                      1.10.1           vc14hb361328_0  [vc14]
heapdict                  1.0.0            py36h21fa5f4_0
html5lib                  0.999999999      py36ha09b1f3_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2             vc14hc45fdbb_0  [vc14]
idna                      2.5                       <pip>
idna                      2.6              py36h148d497_1
ijson                     2.3                       <pip>
imageio                   2.2.0            py36had6c2d2_0
imagesize                 0.7.1            py36he29f638_0
intel-openmp              2018.0.0             hcd89f80_7
ipykernel                 4.6.1            py36hbb77b34_0
ipython                   6.1.0            py36h236ecc8_1
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.0.0            py36h2e74ada_0
isodate                   0.5.4                     <pip>
isort                     4.2.15           py36h6198cc5_0
itsdangerous              0.24             py36hb6c5a24_1
jdcal                     1.3              py36h64a5255_0
jedi                      0.10.2           py36hed927a0_0
jinja2                    2.9.6            py36h10aa3a0_1
joblib                    0.11                     py36_0
jpeg                      9b               vc14h4d7706e_1  [vc14]
jsonlines                 1.1.0                     <pip>
jsonschema                2.6.0            py36h7636477_0
jsontableschema           0.10.1                    <pip>
jupyter                   1.0.0            py36h422fd7e_2
jupyter_client            5.1.0            py36h9902a9a_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.3.0            py36h511e818_0
jupyterlab                0.27.0           py36h34cc53b_2
jupyterlab_launcher       0.4.0            py36h22c3ccf_0
keyring                   9.3.1                    py36_0
lazy-object-proxy         1.3.1            py36hd1c21d2_0
libiconv                  1.15             vc14h29686d3_5  [vc14]
libpng                    1.6.32           vc14hce43e6c_2  [vc14]
libssh2                   1.8.0            vc14hcf584a9_2  [vc14]
libtiff                   4.0.8           vc14h04e2a1e_10  [vc14]
libxml2                   2.9.4            vc14h8fd0f11_5  [vc14]
libxslt                   1.1.29           vc14hf85b8d4_5  [vc14]
linear-tsv                1.0.0                     <pip>
llvmlite                  0.20.0                   py36_0
locket                    0.2.0            py36hfed976d_1
lockfile                  0.12.2           py36h0468280_0
lxml                      3.8.0            py36h45350b2_0
m2-bash                   4.3.042                       5
m2-gcc-libs               5.3.0                         4
m2-heimdal                1.5.3                        10
m2-heimdal-libs           1.5.3                        10
m2-icu                    56.1                          2
m2-libcrypt               1.3                           2
m2-libdb                  5.3.28                        3
m2-libedit                3.1                    20150326
m2-libopenssl             1.0.2.g                       2
m2-libreadline            6.3.008                       8
m2-libsqlite              3.10.0.0                      2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-ncurses                6.0.20160220                  2
m2-openssh                7.1p2                         2
m2-openssl                1.0.2.g                       2
m2-zlib                   1.2.8                         4
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-c-ares              1.11.0                        2
m2w64-ca-certificates     20150426                    103
m2w64-curl                7.48.0                        2
m2w64-diffutils           3.3.2                         2
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gnutls              3.4.11                        2
m2w64-grep                2.24                          2
m2w64-gsl                 2.1                           2
m2w64-jansson             2.7                           3
m2w64-libffi              3.2.1                         4
m2w64-libiconv            1.14                          6
m2w64-libidn              1.32                          4
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libmetalink         0.1.3                         2
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libssh2             1.7.0                         2
m2w64-libsystre           1.0.1                         3
m2w64-libtasn1            4.7                           2
m2w64-libtiff             4.0.6                         2
m2w64-libtre-git          122.c2f5d13                   5
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-nettle              3.1.1                         4
m2w64-nghttp2             1.9.2                         2
m2w64-nlopt               2.4.2                         3
m2w64-openssl             1.0.2.g                       2
m2w64-p11-kit             0.23.2                        2
m2w64-pcre                8.38                          2
m2w64-rtmpdump-git        499.a107cef                   4
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
markupsafe                1.0              py36h0e26971_1
matplotlib                2.0.2            py36h58ba717_1
mccabe                    0.6.1            py36hb41005a_1
menuinst                  1.4.8            py36h870ab7d_0
mistune                   0.7.4            py36h4874169_0
mkl                       2018.0.0             h36b65af_4
mkl-service               1.1.2            py36h57e144c_4
mpmath                    0.19             py36he326802_2
msgpack-python            0.4.8            py36h58b1e9d_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9            py36he44c36e_0
navigator-updater         0.1.0            py36h8a7b86b_0
nbconvert                 5.3.1            py36h8dc0fde_0
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  1.11             py36hdf4b0f5_0
nltk                      3.2.4            py36hd0e0a39_0
nose                      1.3.7            py36h1c3779e_2
notebook                  5.0.0            py36h27f7975_1
numba                     0.35.0             np113py36_10
numexpr                   2.6.2            py36h7ca04dc_1
numpy                     1.13.1           py36haf1bc54_2
numpydoc                  0.7.0            py36ha25429e_0
odo                       0.5.1            py36h7560279_0
olefile                   0.44             py36h0a7bdd2_0
openpyxl                  2.4.8            py36hf3b77f6_1
openssl                   1.0.2l           vc14hcac20b0_2  [vc14]
orange3                   3.4.1                    py36_0
packaging                 16.8             py36ha0986f6_1
pandas                    0.20.3           py36hce827b7_2
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36h3ef6317_1
partd                     0.3.8            py36hc8e763b_0
path.py                   10.3.1           py36h3dd8b46_0
pathlib2                  2.3.0            py36h7bfb78b_0
patsy                     0.4.1            py36h42cefec_0
pep8                      1.7.0            py36h0f3d67a_0
pickleshare               0.7.4            py36h9de030f_0
pillow                    4.2.1            py36hdb25ab2_0
pip                       9.0.1            py36hadba87b_3
pkginfo                   1.4.1            py36hb0f9cfa_1
ply                       3.10             py36h1211beb_0
progress                  1.3              py36hbeca8d3_0
prompt_toolkit            1.0.15           py36h60b8f86_0
psutil                    5.2.2            py36he84b5ac_0
py                        1.4.34           py36ha4aca3a_1
pyasn1                    0.3.7            py36h6f5899e_0
pycodestyle               2.3.1            py36h7cc55cd_0
pycosat                   0.6.2            py36hf17546d_1
pycparser                 2.18             py36hd053e01_1
pycrypto                  2.6.1            py36he68e6e2_1
pycurl                    7.43.0           py36h086bf4c_3
pyflakes                  1.5.0            py36h56100d8_1
pygments                  2.2.0            py36hb010967_0
pylint                    1.7.2            py36h091ff97_0
pyodbc                    4.0.17           py36h0006bc2_0
pyopenssl                 17.2.0           py36h15ca2fc_0
pyparsing                 2.2.0            py36h785a196_1
pyqt                      5.6.0            py36hb5ed885_5
pyqtgraph                 0.10.0                   py36_0
pyreadline                2.1                      py36_0
pysocks                   1.6.7            py36h698d350_1
pytables                  3.4.2            py36h85b5e71_1
pytest                    3.2.1            py36h753b05e_1
python                    3.6.2               h6679aeb_11
python-dateutil           2.6.1            py36h509ddcb_1
pytz                      2017.2           py36h05d413f_1
pywavelets                0.5.2            py36hc649158_0
pywin32                   221              py36h9c10281_0
pyyaml                    3.12             py36h1d1928f_1
pyzmq                     16.0.2           py36h38c27d9_2
qt                        5.6.2           vc14h6f8c307_12  [vc14]
qtawesome                 0.4.4            py36h5aa48f6_0
qtconsole                 4.3.1            py36h99a29a9_0
qtpy                      1.3.1            py36hb8717c5_0
r-assertthat              0.2.0                  r3.4.1_0
r-backports               1.1.0                  r3.4.1_0
r-base                    3.4.1                         0
r-base64enc               0.1_3                  r3.4.1_0
r-bh                      1.62.0_1               r3.4.1_0
r-bindr                   0.1                    r3.4.1_0
r-bindrcpp                0.2                    r3.4.1_0
r-bitops                  1.0_6                  r3.4.1_2
r-boot                    1.3_19                 r3.4.1_0
r-broom                   0.4.2                  r3.4.1_0
r-car                     2.1_4                  r3.4.1_0
r-caret                   6.0_76                 r3.4.1_0
r-catools                 1.17.1                 r3.4.1_2
r-cellranger              1.1.0                  r3.4.1_0
r-class                   7.3_14                 r3.4.1_0
r-cluster                 2.0.6                  r3.4.1_0
r-codetools               0.2_15                 r3.4.1_0
r-colorspace              1.3_2                  r3.4.1_0
r-crayon                  1.3.2                  r3.4.1_0
r-curl                    2.6                    r3.4.1_0
r-data.table              1.10.4                 r3.4.1_0
r-dbi                     0.6_1                  r3.4.1_0
r-dichromat               2.0_0                  r3.4.1_2
r-digest                  0.6.12                 r3.4.1_0
r-dplyr                   0.7.0                  r3.4.1_0
r-essentials              1.6.0                  r3.4.1_0
r-evaluate                0.10                   r3.4.1_0
r-forcats                 0.2.0                  r3.4.1_0
r-foreach                 1.4.3                  r3.4.1_0
r-foreign                 0.8_68                 r3.4.1_0
r-formatr                 1.5                    r3.4.1_0
r-ggplot2                 2.2.1                  r3.4.1_0
r-gistr                   0.4.0                  r3.4.1_0
r-glmnet                  2.0_10                 r3.4.1_0
r-glue                    1.1.1                  r3.4.1_0
r-gtable                  0.2.0                  r3.4.1_0
r-haven                   1.0.0                  r3.4.1_0
r-hexbin                  1.27.1                 r3.4.1_0
r-highr                   0.6                    r3.4.1_0
r-hms                     0.3                    r3.4.1_0
r-htmltools               0.3.6                  r3.4.1_0
r-htmlwidgets             0.8                    r3.4.1_1
r-httpuv                  1.3.3                  r3.4.1_0
r-httr                    1.2.1                  r3.4.1_0
r-irdisplay               0.4.4                  r3.4.1_0
r-irkernel                0.7.1                  r3.4.1_0
r-iterators               1.0.8                  r3.4.1_0
r-jsonlite                1.5                    r3.4.1_0
r-kernsmooth              2.23_15                r3.4.1_0
r-knitr                   1.16                   r3.4.1_0
r-labeling                0.3                    r3.4.1_2
r-lattice                 0.20_35                r3.4.1_0
r-lazyeval                0.2.0                  r3.4.1_0
r-lme4                    1.1_13                 r3.4.1_0
r-lubridate               1.6.0                  r3.4.1_0
r-magrittr                1.5                    r3.4.1_2
r-maps                    3.2.0                  r3.4.1_0
r-markdown                0.8                    r3.4.1_0
r-mass                    7.3_47                 r3.4.1_0
r-matrix                  1.2_10                 r3.4.1_0
r-matrixmodels            0.4_1                  r3.4.1_0
r-mgcv                    1.8_17                 r3.4.1_0
r-mime                    0.5                    r3.4.1_0
r-minqa                   1.2.4                  r3.4.1_2
r-mnormt                  1.5_5                  r3.4.1_0
r-modelmetrics            1.1.0                  r3.4.1_0
r-modelr                  0.1.0                  r3.4.1_0
r-munsell                 0.4.3                  r3.4.1_0
r-nlme                    3.1_131                r3.4.1_0
r-nloptr                  1.0.4                  r3.4.1_2
r-nnet                    7.3_12                 r3.4.1_0
r-openssl                 0.9.6                  r3.4.1_0
r-packrat                 0.4.8_1                r3.4.1_0
r-pbdzmq                  0.2_6                  r3.4.1_0
r-pbkrtest                0.4_7                  r3.4.1_0
r-pkgconfig               2.0.1                  r3.4.1_0
r-pki                     0.1_3                  r3.4.1_0
r-plogr                   0.1_1                  r3.4.1_0
r-plyr                    1.8.4                  r3.4.1_0
r-pryr                    0.1.2                  r3.4.1_0
r-psych                   1.7.5                  r3.4.1_0
r-purrr                   0.2.2.2                r3.4.1_0
r-quantmod                0.4_9                  r3.4.1_0
r-quantreg                5.33                   r3.4.1_0
r-r6                      2.2.1                  r3.4.1_0
r-randomforest            4.6_12                 r3.4.1_0
r-rbokeh                  0.5.0                  r3.4.1_0
r-rcolorbrewer            1.1_2                  r3.4.1_3
r-rcpp                    0.12.11                r3.4.1_0
r-rcppeigen               0.3.3.3.0              r3.4.1_0
r-rcurl                   1.95_4.8               r3.4.1_0
r-readr                   1.1.1                  r3.4.1_0
r-readxl                  1.0.0                  r3.4.1_0
r-recommended             3.4.1                  r3.4.1_0
r-rematch                 1.0.1                  r3.4.1_0
r-repr                    0.10                   r3.4.1_0
r-reshape2                1.4.2                  r3.4.1_0
r-rjsonio                 1.3_0                  r3.4.1_2
r-rlang                   0.1.1                  r3.4.1_0
r-rmarkdown               1.5                    r3.4.1_0
r-rpart                   4.1_11                 r3.4.1_0
r-rprojroot               1.2                    r3.4.1_0
r-rsconnect               0.8                    r3.4.1_0
r-rstudioapi              0.6                    r3.4.1_0
r-rvest                   0.3.2                  r3.4.1_0
r-scales                  0.4.1                  r3.4.1_0
r-selectr                 0.3_1                  r3.4.1_0
r-shiny                   1.0.3                  r3.4.1_0
r-sourcetools             0.1.6                  r3.4.1_0
r-sparsem                 1.77                   r3.4.1_0
r-spatial                 7.3_11                 r3.4.1_0
r-stringi                 1.1.5                  r3.4.1_0
r-stringr                 1.2.0                  r3.4.1_0
r-survival                2.41_3                 r3.4.1_0
r-tibble                  1.3.3                  r3.4.1_0
r-tidyr                   0.6.3                  r3.4.1_0
r-tidyverse               1.1.1                  r3.4.1_0
r-ttr                     0.23_1                 r3.4.1_0
r-uuid                    0.1_2                  r3.4.1_0
r-xml2                    1.1.1                  r3.4.1_0
r-xtable                  1.8_2                  r3.4.1_0
r-xts                     0.9_7                  r3.4.1_2
r-yaml                    2.1.14                 r3.4.1_0
r-zoo                     1.8_0                  r3.4.1_0
requests                  2.18.4           py36h4371aae_1
requests                  2.18.1                    <pip>
rfc3986                   0.4.1                     <pip>
rope                      0.10.5           py36hcaf5641_0
rstudio                   1.0.153                       1
ruamel_yaml               0.11.14          py36h9b16331_2
scikit-image              0.13.0           py36h6dffa3f_1
scikit-learn              0.19.0           py36h294a771_2
scipy                     0.19.1           py36h7565378_3
seaborn                   0.8.0            py36h62cb67c_0
setuptools                36.5.0           py36h65f9e6e_0
simplegeneric             0.8.1            py36heab741f_0
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.18.1           py36h9c25514_2
six                       1.10.0           py36h2c0fdd8_1
smart-open                1.5.3                     <pip>
snowballstemmer           1.2.1            py36h763602f_0
sockjs-tornado            1.0.3                    py36_0
sortedcollections         0.5.3            py36hbefa0ab_0
sortedcontainers          1.5.7            py36ha90ac20_0
sphinx                    1.6.3            py36h9bb690b_0
sphinxcontrib             1.0              py36hbbac3d2_1
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1
spyder                    3.2.3            py36h132a2c8_0
sqlalchemy                1.1.13           py36h5948d12_0
sqlite                    3.20.1           vc14h7ce8c62_1  [vc14]
statsmodels               0.8.0            py36h6189b4c_0
sympy                     1.1.1            py36h96708e0_0
tabulator                 1.0.0a5                   <pip>
tblib                     1.3.2            py36h30f5020_0
testpath                  0.3.1            py36h2698cfe_0
tk                        8.6.7            vc14hb68737d_1  [vc14]
toolz                     0.8.2            py36he152a52_0
tornado                   4.5.2            py36h57f6048_0
traitlets                 4.3.2            py36h096827d_0
typing                    3.6.2            py36hb035bda_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.22             py36h276f60a_0
urllib3                   1.21.1                    <pip>
vc                        14                   h2379b0c_1
vs2015_runtime            14.0.25123           hd4c4e62_1
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1            py36h67c50ae_1
werkzeug                  0.12.2           py36h866a736_0
wheel                     0.29.0           py36h6ce6cde_1
widgetsnbextension        3.0.2            py36h364476f_1
win_inet_pton             1.0.1            py36he67d7fd_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11          py36he5f5981_0
xlrd                      1.1.0            py36h1cb58dc_1
xlsxwriter                0.9.8            py36hdf8fb07_0
xlwings                   0.11.4           py36hd3cf94d_0
xlwt                      1.3.0            py36h1a4751e_0
yaml                      0.1.7            vc14hb31d195_1  [vc14]
zict                      0.1.2            py36hbda90c0_0
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]
`

**Comment by goanpeca** [comment]
@rajesh1980 could you delete `C:\Users\rramach1\.condarc` and try again?
