### ISSUE TITLE
conda install git hangs dependency resolution

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#6687]
I'm trying to install git on a windows machine via conda after installing the latest anaconda.
First, I had it suggest downgrading Python3.6.2 to 2.7.13. I said no, called the same command again, and now the dependency resolution is hanging (doesn't accept ctrl+C).

**Comment by kalefranz** [comment]
Let's close this issue and track at https://github.com/conda/conda/issues/6179
