### ISSUE TITLE
After installing gcc, all cython packages that uses C++ are broken.

### ISSUE THREAD

**Issue by rainwoodman** [ContinuumIO/anaconda-issues#6692]
After installing gcc, all cython packages that uses C++ are broken. The error looked familiar. But I think the solution shall be more than 'do not install gcc on Linux'. 

Apparently the new anaconda packages from the default channel are building against 3.4.20+ -- possible related to the new shift to the cross compilation chain, but the gcc packages haven't been updated for this yet.

(root) [yfeng1@waterfall ~]$ conda install gcc
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/yfeng1/anaconda3/install:

The following NEW packages will be INSTALLED:

    gcc: 4.8.5-7

Proceed ([y]/n)? y

(root) [yfeng1@waterfall ~]$ !jup
jupyter-notebook 
gcc: error: unrecognized command line option ‘-R’
Traceback (most recent call last):
  File "/home/yfeng1/anaconda3/install/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/notebook/notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/yfeng1/anaconda3/install/lib/python3.6/site-packages/zmq/backend/cython/../../../../../libzmq.so.5.1.2)

**Comment by mingwandroid** [comment]
Please see this document for information on the compiler packages:

https://docs.google.com/document/d/103QY204eD82fJzpT7eXy_rV2bKwe6Hx5uAnkMg_xwkI/edit?ts=59d3dfc1#heading=h.p4o4zy619i0w

**Comment by rainwoodman** [comment]
Thanks. I left my concerns inside the doc. I can confirm installing gcc_linux-64 doesn't break everything.

**Comment by mingwandroid** [comment]
> I left my concerns inside the doc.

Thanks.

> doesn't break everything.

That doesn't sound like a complete success?! Please clarify.

**Comment by rainwoodman** [comment]
I had to do 
```
ln -s _sysconfigdata_m_linux_x86_64-linux-gnu.py  _sysconfigdata_x86_64_conda_cos6_linux_gnu.py
```
in python3.6/ directory before python works.

After that the mpicc wrappers still wants to use the system provided gcc.

**Comment by mingwandroid** [comment]
Can you give me exact reproduction steps please?

**Comment by rainwoodman** [comment]
@msarahan pointed out I need to update my Python. After the update the file is created. (I was on Python 3.6.2_15). The mpich2 issue is in a different PR. 

The final conclusion of this is that after anaconda 5.x we shall remove libgcc, gcc, libgfortran, which are not automatically removed.

Rather, we shall rely on the ```compiler('c')``` construct in meta.yaml and conda-build for building recipes;

For local manual compilation, manually install packages like  `libgcc-ng, gcc_linux-64`. Also remember to update python to a newer version that came with anaconda 5.x. Then there is no more error.

I'll close this ticket. Thanks for the help.

**Comment by mingwandroid** [comment]
Great! Thank you for helping out too.
