### ISSUE TITLE
Windows uninstall switches

### ISSUE THREAD

**Issue by liamkirwan** [ContinuumIO/anaconda-issues#6730]
I am working on wrapping Anaconda in a chocolatey package, and am having some difficulty with the uninstaller. I can see there is a silent switch which will automatically uninstall, but it creates a background process to do so, before exiting the parent process.

This is causing problems for me, as chocolatey takes the exit code 0 as a signal the work is done, while there are close to 100,000 files to clean up in a default install. There is documentation on the Anaconda site explaining the install switches, but nothing I could find regarding the uninstaller exe.

Is there any documentation of all available switches for the uninstaller? More specifically, is there a way I can ask the parent to wait for it's child processes to exit before ending itself?

```
Time     Process                 PID  Operation      Path                                                                  Detail                                                                                     
----     -------                 ---  ---------      ----                                                                  ------                                                                                     
13:50:07 powershell.exe          8388 Process Create C:\ProgramData\chocolatey\bin\choco.exe                               PID: 3588, Command line: "C:\ProgramData\chocolatey\bin\choco.exe" uninstall anaconda3     
13:50:08 choco.exe               7276 Process Start                                                                        Parent PID: 3588, Command line: "C:\ProgramData\chocolatey\choco.exe" uninstall anaconda3, 
13:50:32 choco.exe               7276 Process Create C:\ProgramData\chocolatey\tools\7z.exe                                PID: 8576, Command line: "C:\ProgramData\chocolatey\tools\7z.exe" x -aoa -o"C:\ProgramData\
13:50:34 choco.exe               7276 Process Create C:\ProgramData\chocolatey\tools\detector\diec.exe                     PID: 8688, Command line: "C:\ProgramData\chocolatey\tools\detector\diec.exe" "C:\tools\Anac
13:50:35 choco.exe               7276 Process Create C:\tools\Anaconda3\Uninstall-Anaconda3.exe                            PID: 5908, Command line: "C:\tools\Anaconda3\Uninstall-Anaconda3.exe" /S                   
13:50:35 Uninstall-Anaconda3.exe 5908 Process Start                                                                        Parent PID: 7276, Command line: "C:\tools\Anaconda3\Uninstall-Anaconda3.exe" /S, Current di
13:50:36 Uninstall-Anaconda3.exe 5908 Process Create C:\Users\lkirwan-adm\AppData\Local\Temp\chocolatey\~nsuA.tmp\Un_A.exe PID: 8800, Command line: "C:\Users\lkirwan-adm\AppData\Local\Temp\chocolatey\~nsuA.tmp\Un_A
13:50:36 Un_A.exe                8800 Process Start                                                                        Parent PID: 5908, Command line: "C:\Users\lkirwan-adm\AppData\Local\Temp\chocolatey\~nsuA.t
13:50:36 Uninstall-Anaconda3.exe 5908 Process Exit                                                                         Exit Status: 0, User Time: 0.0000000 seconds, Kernel Time: 0.2031250 seconds, Private Bytes
13:50:36 choco.exe               7276 Process Create C:\windows\System32\shutdown.exe                                      PID: 5988, Command line: "C:\windows\System32\shutdown.exe" /a                             
13:50:36 Un_A.exe                8800 Process Create C:\tools\Anaconda3\pythonw.exe                                        PID: 552, Command line: "C:\tools\Anaconda3\pythonw.exe" -E -s "C:\tools\Anaconda3\Lib\_nsi
13:50:36 pythonw.exe             552  Process Start                                                                        Parent PID: 8800, Command line: "C:\tools\Anaconda3\pythonw.exe" -E -s "C:\tools\Anaconda3\
13:50:38 pythonw.exe             552  Process Exit                                                                         Exit Status: 0, User Time: 0.0625000 seconds, Kernel Time: 1.0468750 seconds, Private Bytes
13:50:38 Un_A.exe                8800 Process Create C:\tools\Anaconda3\pythonw.exe                                        PID: 3816, Command line: "C:\tools\Anaconda3\pythonw.exe" -E -s "C:\tools\Anaconda3\Lib\_ns
13:50:38 pythonw.exe             3816 Process Start                                                                        Parent PID: 8800, Command line: "C:\tools\Anaconda3\pythonw.exe" -E -s "C:\tools\Anaconda3\
13:50:39 pythonw.exe             3816 Process Exit                                                                         Exit Status: 0, User Time: 0.0937500 seconds, Kernel Time: 0.5000000 seconds, Private Bytes
13:50:47 choco.exe               7276 Process Exit                                                                         Exit Status: 0, User Time: 2.7187500 seconds, Kernel Time: 23.9687500 seconds, Private Byte
14:12:01 Un_A.exe                8800 Process Exit                                                                         Exit Status: 0, User Time: 4.6875000 seconds, Kernel Time: 1246.3750000 seconds, Private By
```

Failing that, can we raise this as a feature request? Doesn't need to be default, just give me the option to keep the parent process alive until the uninstall is complete (or, give me way to invoke un_a.exe)

**Comment by csoja** [comment]
I'd recommend looking at constructor and possibly creating an issue there or submitting a PR: https://github.com/conda/constructor

**Comment by heaths** [comment]
The problem is for any chainer that uninstalls older packages to install new. In general, chainers (and I have a lot of experience writing these), should not invoke sub-installers/chainers asynchronously. The problem now is that uninstalling the old version appears to succeed because of what @liamkirwan said. But now the installer gets invoked and the uninstaller and installer are now in a race condition. The installer effectively fails to install a complete image because the uninstaller deleted a bunch of files simultaneously.

If a chainer is actually un/installing Anaconda, creating a custom installer using _constructor_ would not be sufficient. This is a problem with the uninstaller. At the very least, chainers need a `wait` switch to wait for the child process to terminate and should marshal the child process exit code as the parent exit code. This is typical of all chainers, which is effectively what your uninstaller is.

**Comment by msarahan** [comment]
Also, if you consider Anaconda a standalone program for data-science stuff, your approach is fine.  If you consider it a large set of individually updatable packages (which it is), then chocolatey is just not a good fit.  Having package managers that manage other package managers is a recipe for pain.  See: pip and conda.

**Comment by heaths** [comment]
Perhaps that's true for the original issue of trying to redistribute packages via chocolatey, but when an installer like Visual Studio is trying to chain an upgrade where your uninstaller runs in parallel with your installer, a race condition ultimately leads to missing package files for end users.

**Comment by mingwandroid** [comment]
> At the very least, chainers need a wait switch to wait for the child process to terminate and should marshal the child process exit code as the parent exit code. This is typical of all chainers, which is effectively what your uninstaller is.

Is this not an acceptable solution here though?
