### ISSUE TITLE
An unexpected error occured on Navigator start-up

### ISSUE THREAD

**Issue by vdsprakash** [ContinuumIO/anaconda-issues#6740]
![screenshot 42](https://user-images.githubusercontent.com/23026717/31734475-7409282e-b45c-11e7-8474-615f184885aa.png)

**Comment by goanpeca** [comment]
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
