### ISSUE TITLE
Can't find installed package in Navigator

### ISSUE THREAD

**Issue by renatekloet** [ContinuumIO/anaconda-issues#6744]
Hi,

The 'twitter' package I installed earlier, it does show when I call conda list in the prompt but I can't find it in the package list in the navigator

![image](https://user-images.githubusercontent.com/32833923/31737170-f153b06c-b446-11e7-87d6-409eff7417e3.png)

Can you help me find twitter back?

**Comment by goanpeca** [comment]
@renatekloet because navigator handles conda pakcages, not pip packages. Although pip packages should be displayed in the list
