### ISSUE TITLE
Python 3.6 backspace key behaves strangely

### ISSUE THREAD

**Issue by danielee0707** [ContinuumIO/anaconda-issues#6747]
On Arch Linux with KDE, running anaconda python 3.6.2 in terminal. Pressing backspace was recognized as space, and arrow keys behaved strangely. Also history reading using arrow keys didn't behave correctly.

**Comment by danielee0707** [comment]
When using anaconda terminal in pycharm, this error also showed up. Any idea what it is?

xkbcommon: ERROR: failed to add default include path /home/<username>/.cache/pacaur/anaconda/pkg/anaconda/opt/anaconda/lib
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .

**Comment by mingwandroid** [comment]
Have you set `LD_LIBRARY_PATH`?

**Comment by danielee0707** [comment]
I could fix the second issue with export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb, but I'd like to know why this is happening and fix it completely. What about the first one?

**Comment by mingwandroid** [comment]
Have you set LD_LIBRARY_PATH?

**Comment by danielee0707** [comment]
I set to /opt/anaconda/lib, is it right?

**Comment by danielee0707** [comment]
Reinstalled using anaconda default script fixed my issues. Seems that its the aur installer that caused all the problems. Sorry for bothering.

**Comment by mingwandroid** [comment]
Interesting information. Did you file a bug with the AUR maintainer? If not, could you do that please?

**Comment by danielee0707** [comment]
Yes I did.

**Comment by Hannabrahman** [comment]
Hello, I am having the same problem, could you please guide how you fix it?
Actually, my anaconda was working fine but because of memory limitation, I moved the whole folder to another directory. The problem start from that time.

Any help?

**Comment by soupwaylee** [comment]
@Hannabrahman I had the same issue, so I clean re-installed my miniconda and re-did the envs from scratch...
