### ISSUE TITLE
Default readline version installed when creating environment doesn't work with URxvt

### ISSUE THREAD

**Issue by tomeaton17** [ContinuumIO/anaconda-issues#6758]
I am using Ubuntu 17.04 with URxvt as my terminal emulator. When I create a new environment with `conda create -n myenv python=3.6`  there is no errors with this command. I then try to use the python prompt I cannot use backspace or arrow keys. When I do use these keys, it just adds blank characters to the prompt. This means that the keyboard control characters are not being interpreted correctly.

To fix this I must go into `envs/myenv/lib` and delete all `libreadline` files. I then install readline with `pip install readline`. The version of readline is 6.2.4.1.

Please can you fix the readline that is installed by default so that it works with URxvt.

**Comment by kbobrowski** [comment]
I have the same issue, it could be solved by downgrading to readline 6.2:

```conda install readline=6.2```

**Comment by NMertsch** [comment]
The issues don't seem to be readline-related but instead terminfo-related. See my comment at #8271 for how I fixed it without downgrading. I suggest closing this issue or #8271 as they deal with the same issue.
