### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by cbasurto** [ContinuumIO/anaconda-issues#677]
![screenshot 2016-02-26 08 39 15](https://cloud.githubusercontent.com/assets/7121040/13353842/1eca5c28-dc65-11e5-804c-8575618b7f8b.png)

**Comment by ccordoba12** [comment]
Which application? The Launcher?

**Comment by cbasurto** [comment]
Yes

**Comment by cbasurto** [comment]
The green Launcher icon fails to open, and when I try to re-download Anaconda it reads "the computer already has the software."

**Comment by cbasurto** [comment]
Hello Carlos,

No worries, I fixed the issue. I uninstalled and reinstalled the software.
Thanks!

Camille

**Comment by ccordoba12** [comment]
Thanks for letting us know about it :-)
