### ISSUE TITLE
qt libraries have RUNPATH instead of RPATH, are not robust against LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by speleo3** [ContinuumIO/anaconda-issues#6783]
Using freshly installed Anaconda (4.4 or 5.0) on Arch Linux:

```
export LD_LIBRARY_PATH=/usr/lib
anaconda-navigator
Segmentation fault (core dumped)
```

The reason is that some Qt libraries have **RUNPATH** instaed of **RPATH**, which gives **LD_LIBRARY_PATH** priority. Conda build uses `patchelf --force-rpath`, but that has not the expected effect in some cases, see NixOS/patchelf/issues/94.

A possible fix would be to call `patchelf --remove-rpath` before  `patchelf --force-rpath`.

**Comment by mingwandroid** [comment]
I think I will just patch Qt here.` DT_RUNPATH` is an absolute train-wreck of a misfeature.

But do you need `LD_LIBRARY_PATH` that's just as bad a misfeature (except for engineers use in debugging).

**Comment by speleo3** [comment]
> I think I will just patch Qt here.

works for me, thanks!

> But do you need LD_LIBRARY_PATH

I don't, but others who want to use my software have it.

**Comment by mingwandroid** [comment]
Can you not setup DT_RPATH ${ORIGIN} entries for them assuming a fixed relative layout? That's what we do.

**Comment by speleo3** [comment]
> Can you not setup DT_RPATH ${ORIGIN} entries for them assuming a fixed relative layout?

Yes I can, for stuff I deploy myself. But the bug affects all PyQt related packages in Anaconda right now, that's why I reported it.

**Comment by mingwandroid** [comment]
OK thanks.

**Comment by mingwandroid** [comment]
This is fixed in the next build (not yet released) of qt for linux. To test you can install via:

`conda update qt -c rdonnellyr`
