### ISSUE TITLE
Anaconda Navigator quit unexpectedly on Macbook Pro, Yosemite

### ISSUE THREAD

**Issue by hilaryzhu** [ContinuumIO/anaconda-issues#6794]
Hi, 
Please help!  I've been using anaconda navigator for 2 years, and today, after I restarted my laptop, suddenly Anaconda navigator wouldn't start, giving me the attached error.  

Truly appreciate your help!
[error.txt](https://github.com/ContinuumIO/anaconda-issues/files/1403389/error.txt)

**Comment by hilaryzhu** [comment]
And here's my conda info:
Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.3.5
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /Users/apple/anaconda  (writable)
    default environment : /Users/apple/anaconda
       envs directories : /Users/apple/anaconda/envs
          package cache : /Users/apple/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

**Comment by hilaryzhu** [comment]
Command line works fine though using jupyter notebook.  The last two times I launched navigator, I also got these error popup: http://speedtracer.apple.com/tracer/analyze returned unexpected response code: 200, not sure if it's relavant.

**Comment by goanpeca** [comment]
@hilaryzhu you are using very old versions, I would encourage you to update to the latest Anaconda Installers https://www.anaconda.com/download/
