### ISSUE TITLE
Update pyzmq and/or remove gevent_pyzmq

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#68]
_Issue by **[danielfrg](https://github.com/danielfrg)** from Monday Aug 12, 2013 at 17:54 GMT_
_Originally opened as https://github.com/conda/conda/issues/244_

---

Based on https://github.com/traviscline/gevent-zeromq/issues/35#issuecomment-14991514 since pyzmq ≥ 2.2.0.1 gevent_pyzmq is no longer required.

In general shouldn't be a problem but the gevent_pyzmq requires pyzmq==2.2; the last version is 13.1.

I think just removing gevent_zmq is a good idea since is no longer necessary or in development, and with that is possible to update pyzmq to the latest version.

**Comment by nehaljwani** [comment]
`pyzmq==16.0.2` has been made [available](https://anaconda.org/anaconda/pyzmq/files).
