### ISSUE TITLE
conda lists cryptography package version 1.0.2 but I get 0.9.1 on import

### ISSUE THREAD

**Issue by davidslac** [ContinuumIO/anaconda-issues#682]
I am educating myself about python packaging, .pth files, egg files, etc. While poking around in my anaconda install, I noticed that I have a flat file install for cryptography 0.9.1, and a egg file install with associated .pth file for version 1.0.2. When I do conda list, I see

```
conda list | grep crypto
cryptography              1.0.2                    py27_0  
```

in the site-packages directory, I see

```
anaconda2/lib/python2.7/site-packages $ ls -1 | grep crypto
cryptography  # directory, flat file install of 0.9.1
cryptography-0.9.1-py2.7-linux-x86_64.egg-info
cryptography-1.0.2-py2.7-linux-x86_64.egg
cryptography.pth
pycrypto-2.6.1-py2.7.egg-info
```

and the contents of the .pth file is

```
anaconda2/lib/python2.7/site-packages $ cat cryptography.pth 
./cryptography-1.0.2-py2.7-linux-x86_64.egg
```

but when I import cryptography, I get

```
 ~ $ python
Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cryptography
>>> cryptography.__version__
'0.9.1'
```

so in my anaconda (root environment), there is a mismatch between what conda list reports and what I get from the interpreter. I can see why this is if I inspect the sys.path, the 1.0.2 egg comes after the site-packages directory where the flat file install is:

```
>>> [(ii,xx) for ii,xx in enumerate(sys.path) if xx.find('crypto')>=0]
[(9, '/reg/neh/home/davidsch/sw/external/install/anaconda2/lib/python2.7/site-packages/cryptography-1.0.2-py2.7-linux-x86_64.egg')]
>>> print '\n'.join(sys.path[0:8])

/home/user/sw/external/install/anaconda2/lib/python27.zip
/home/user/sw/external/install/anaconda2/lib/python2.7
/home/user/sw/external/install/anaconda2/lib/python2.7/plat-linux2
/home/user/sw/external/install/anaconda2/lib/python2.7/lib-tk
/home/user/sw/external/install/anaconda2/lib/python2.7/lib-old
/home/user/sw/external/install/anaconda2/lib/python2.7/lib-dynload
/home/user/sw/external/install/anaconda2/lib/python2.7/site-packages
```

I'm basically exploring anaconda now, so maybe I installed some package in the root environment that had a weird dependency that caused this, like maybe I pip installed something, but I don't think so, I think I've only tried pip in other conda environments.

When I look at the .pth files that easy-install produces, they add some code on their import sys lines that manipulate the sys.path so that the new easy install based packages listed in the .pth file occur before anything else in sys.path. That is they initialize sys.__egginsert to 0 (if not set), insert the new easy-install packages at position 0 in sys.path, and then, adjust sys.__egginsert so that the next .pth file can pick up the value and continue to insert packages before other, 'non egg things' in sys.path. I don't see that code in the cryptography.pth, so maybe it it is a bug in cryptography? Or maybe it is a bug in the conda packaging of cryptography?

I did notice that pip list lists the correct version - 0.9.1, that gets imported.

**Comment by nehaljwani** [comment]
The conda package `cryptography=1.0.2` doesn't have this problem.

```bash
(root) [nwani@xyz ~]$ conda create -yn 682 python=2.7 cryptography=1.0.2
(root) [nwani@xyz ~]$ source activate 682
(682) [nwani@xyz ~]$ python -c 'import cryptography; print cryptography.__version__'
1.0.2
(682) [nwani@xyz ~]$ find $CONDA_PREFIX/lib/python2.7/site-packages/ -maxdepth 1 | grep cryptography
/home/nwani/m3/envs/682/lib/python2.7/site-packages/cryptography-1.0.2-py2.7-linux-x86_64.egg
/home/nwani/m3/envs/682/lib/python2.7/site-packages/cryptography.pth
```

You might have probably installed `cryptography==0.9.1` via pip accidentally. Please don't install packages of same name into the same conda environment via both pip and conda.
