### ISSUE TITLE
Missing libgfortran in Python 2.7 env on Travis

### ISSUE THREAD

**Issue by cle1109** [ContinuumIO/anaconda-issues#683]
I can't seem to figure out what the problem is. On my Travis build, I get the following error message after importing `numpy` (see also https://travis-ci.org/scot-dev/scot/jobs/113637558):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/miniconda3/envs/testenv/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/travis/miniconda3/envs/testenv/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/travis/miniconda3/envs/testenv/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/travis/miniconda3/envs/testenv/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/travis/miniconda3/envs/testenv/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/home/travis/miniconda3/envs/testenv/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

I explicitly installed the `libgfortran` package as suggested in #445, but this didn't resolve the problem. Also, I can't reproduce this issue on my local machine because `conda` gives me different dependencies (e.g. I can't install `matplotlib=1.4.0` because this depends on `numpy=1.9.3` - I wonder why it is possible to use `numpy=1.8.0` in the Travis env).

**Comment by insertinterestingnamehere** [comment]
@ilanschnell it looks like libgfortran is needed by openblas and shared object versioning is preventing it from finding the new one. The simplest thing to do is to rebuild openblas to use the newer version.

**Comment by ilanschnell** [comment]
I already rebuild `oenblas` against the newer version of `libgfortran` yesterday.

**Comment by insertinterestingnamehere** [comment]
Hmm. Okay, I can reproduce this locally without any package conflicts. It looks like this is an issue with the builds for 1.8.0 and 1.8.1 in particular. 1.8.2 doesn't have this issue. Building an env with `conda create -n testenv numpy=1.8.0` is sufficient to reproduce the issue.

**Comment by ilanschnell** [comment]
The older numpy versions are not supported anymore.  We might still support numpy 1.9.

**Comment by cle1109** [comment]
@insertinterestingnamehere I can't reproduce this on my local machine; both numpy 1.8.0 and 1.8.2 work (in Python 2.7). On Travis, neither version works (https://travis-ci.org/scot-dev/scot/jobs/113758472).

@ilanschnell does this mean we can't have testing envs for older setups? Our toolbox was working fine with specific older package versions, but now all of a sudden we can't test it anymore. I still have the feeling that there's something wrong with my setup (because everything's fine on my local machine)...

**Comment by ilanschnell** [comment]
Older versions of numpy should still work, but they have not been updated to the new libgfortran.

**Comment by cle1109** [comment]
So what does this mean for my failing build? Which version should I try in order to get it to work?

**Comment by insertinterestingnamehere** [comment]
Pinning the libgfortran version to 1.0 fixes it for me. That way it'll pull in the one with the older ABI. That won't work with packages that require the latest version of libgfortran, but it should work in the case that they all can use the old ABI. You could also just test with numpy 1.8.2. and support only the latest bugfix release from each major release, but that's totally up to you.

**Comment by cle1109** [comment]
`numpy` 1.8.2 doesn't work either (see the link above). It gives the same error related to `libgfortran.`

How can I pin `libgfortran` to 1.0? Do you mean via `conda` or do I have to get it via apt?

**Comment by cle1109** [comment]
Today, this error disappeared. I guess using `numpy` 1.8.2 fixed the problem.
