### ISSUE TITLE
Application spyder launch may have produced errors

### ISSUE THREAD

**Issue by cmendozalugo** [ContinuumIO/anaconda-issues#6844]
**Traceback**

Traceback (most recent call last):
File "/Users/carlosmendoza/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/carlosmendoza/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 13, in 
import zmq
File "/Users/carlosmendoza/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 29, in 
_load_libzmq()
File "/Users/carlosmendoza/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 9, in _load_libzmq
import sys, ctypes, platform
File "/Users/carlosmendoza/anaconda3/lib/python3.6/ctypes/__init__.py", line 7, in 
from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/carlosmendoza/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Symbol not found: __PyUnicode_AsWideCharString
Referenced from: /Users/carlosmendoza/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
Expected in: flat namespace
in /Users/carlosmendoza/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so

**System Info**
anaconda navi version: 1.6.9
python version: 3.6.3
platform : osx-64
conda version : 4.3.30
conda-env version : 4.3.30
conda-build version : 3.0.27
requests version : 2.18.4

**Comment by goanpeca** [comment]
@ccordoba12 thoughts?

**Comment by cmendozalugo** [comment]
Additional information... After the first time I received the error, I deleted the whole anaconda and reinstall it. At first it worked but after some updates in some components, it crashed again. It happens the same with jupyterlab, but not with jupiter notebook.

**Comment by goanpeca** [comment]
@mingwandroid ideas?

**Comment by zackankner** [comment]
I had the same problem. To fix my error I had to revert to version 3.6.2 of python. To do this, all you have to do is go to terminal and first type: conda search python. Next input conda install python=3.6.2. Hope this helps any body with the same problem

**Comment by ccordoba12** [comment]
This is fixed by updating the `python.app` package, actually.

**Comment by Makoto1021** [comment]
would you please guide me how to update the python.app?

**Comment by csoja** [comment]
have you tried _conda update python_ ?
