### ISSUE TITLE
Naigator size/zoom

### ISSUE THREAD

**Issue by peter73421** [ContinuumIO/anaconda-issues#6846]
Dears,

unfortunately I end up with "too big" navigator screen - so it gets big letter size and screen. How can reset it to default size? I am running on Ubuntu 16.04 machine.
Is it issue of displaying Navigator?

**Comment by goanpeca** [comment]
@peter73421, there is a setting in preferences to enable/disable high dpi screens scaling. Did you try with that? we are working on a configuration to set the exact value in computers with hgh dpi and size issues.

**Comment by peter73421** [comment]
Well. Preference window is not poping up... So I can't change it.

Dne 24. 10. 2017 10:00 odpoledne napsal uživatel "Gonzalo Peña-Castellanos"
<notifications@github.com>:

@peter73421 <https://github.com/peter73421>, there is a setting in
preferences to enable/disable high dpi screens scaling. Did you try with
that? we are working on a configuration to set the exact value in computers
with hgh dpi and size issues.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ContinuumIO/anaconda-issues/issues/6846#issuecomment-339113288>,
or mute the thread

**Comment by alec-djinn** [comment]
As of Jan 2019, I am having the same problem on Ubuntu 18.04 and Linux Mint Tessa. The navigator GUI is too large, I cannot access the settings since any drop-menu goes out of the screen. Is there a way to change the settings via terminal?
