### ISSUE TITLE
Conda distribution missing Win32 and Win64 delivery for r-ggthemes

### ISSUE THREAD

**Issue by kktam** [ContinuumIO/anaconda-issues#6866]
For Conda package [r-ggthemes](https://anaconda.org/bioconda/r-ggthemes). It currently does not support Win32 or Win64 delivery.

```
Installers
conda install 
 linux-64  v3.4.0
 osx-64  v3.4.0
To install this package with conda run:
conda install -c bioconda r-ggthemes 
```

However in the official ggthemes website, There are clearly Windows binaries available.

[https://cran.rstudio.com/web/packages/ggthemes/index.html](https://cran.rstudio.com/web/packages/ggthemes/index.html)

```
Reference manual: | ggthemes.pdf
-- | --
Vignettes: | Introduction to ggthemes
Package source: | ggthemes_3.4.0.tar.gz
Windows binaries: | r-devel: ggthemes_3.4.0.zip, r-release: ggthemes_3.4.0.zip, r-oldrel: ggthemes_3.4.0.zip
OS X El Capitan binaries: | r-release: ggthemes_3.4.0.tgz
OS X Mavericks binaries: | r-oldrel: ggthemes_3.4.0.tgz
Old sources: | ggthemes archive


```

Requesting Anaconda delivery to create delivery packages for ggthemes supporting Win32 and Win64, or create a minimum of work around steps on how to take zipped binaries and place into Windows conda environment.

**Comment by mingwandroid** [comment]
`bioconda` is not an official `Anaconda Distribution` channel. I provided steps in your `r-mice` issue detailing how to build packages for yourself so I will not repeat them here.
