### ISSUE TITLE
scipy import error

### ISSUE THREAD

**Issue by sho-87** [ContinuumIO/anaconda-issues#6872]
I just installed anaconda 5 (64bit), python 3.6, on Windows 10 and having some problems importing scipy modules

After a clean installation of anaconda, I ran `conda update conda` and `conda update anaconda`. This also seems to happen without these updates, but figured I'd update to make sure I was running the latest package versions

When updating anaconda, I see the following debug message:

`DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\Simon\Anaconda3', env_name: 'None', mode: 'None', used_mode: 'user'`

Then I start up python and try the following import: `import scipy.stats` (this also happens with others, like `scipy.signal`, `scipy.special`, but **not** `scipy.cluster`)

And I see the following error:

```
Traceback (most recent call last):

  File "<ipython-input-11-e2b9ec03ffc0>", line 1, in <module>
    import scipy.signal

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\signal\__init__.py", line 304, in <module>
    from .bsplines import *

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\signal\bsplines.py", line 12, in <module>
    from scipy.special import comb, gamma

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\special\_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm

ImportError: cannot import name '_ellipsoid'
```

This is preventing me from using a number of packages that require scipy (e.g. scikits-bootstrap). Any thoughts on what is happening?

**Comment by ccordoba12** [comment]
Please update to the latest Python 3.6 version, along with the latest SciPy version, and try again.

**Comment by sho-87** [comment]
I believe I'm currently on the latest of both. Checked using `conda update python` and `conda update scipy`

python 3.6.3 and scipy 0.19.1

**Comment by ccordoba12** [comment]
What about

    conda install -f scipy

?

**Comment by sho-87** [comment]
I still get the same import errors

**Comment by sho-87** [comment]
after some testing it seems that maybe its not an anaconda specific problem. throughout my reinstalls of anaconda I had another package installed via pip which didnt get removed. the presence of that package seems to have caused these scipy module import errors: https://github.com/cgevans/scikits-bootstrap/issues/16

it seems strange that the presence of a pip module would cause these types of issues, so maybe the problem is actually caused by some weird interaction between how anaconda handles packages and other packages installed via pip?

**Comment by ccordoba12** [comment]
Pip and conda shouldn't be mixed regarding compiled modules because their packages are usually binary incompatible.

So, it's fine to use Pip to install pure Python packages but not binary ones when using Anaconda.

**Comment by msarahan** [comment]
What @ccordoba12 says is mostly true.  In general, avoid mixing pip and conda.  Pip and conda are not fully aware of one another, and will clobber each other, with the result often being broken software.  Try to keep to conda-installing everything (conda-forge helps a lot with making this more feasible), and as an absolute last resort, fall back to pip installing things.

We will be working over time to improve this, but have no definite timeline for exactly when.

**Comment by ccordoba12** [comment]
I'm closing this one because there's nothing we can do about it for now.

**Comment by sho-87** [comment]
so if I want to use a package that isn't available via anaconda/conda-forge, and the package doesn't work when installing via pip as in my original post, then Im out of luck and theres absolutely nothing I can do?

would using a virtualenv and installing via pip there help the issue at all?

**Comment by msarahan** [comment]
Using conda environment will work better than using virtualenv.  If things don't work with pip, it might be because some binary dependencies in a wheel are incompatible with your system.  In that case, your ultimate fallback is to build things from source.  "things" meaning whatever it takes to get your stack to be compatible with your system.

**Comment by sho-87** [comment]
so looking through the source of the other package it doesnt look like it has any binary dependencies, and its not a binary package itself. It just relies on imports of packages that are a part of the anaconda distribution (e.g. numpy). So it seems to me it is just a pure python script and nothing else

In that case, why exactly would there be an issue with pip installing it and using anaconda at the same time? I can confirm that the location of the package is in a path that python has access to (same as where all other packages are located). Im not sure I understand the distinction here, or the reason why it shouldnt work
