### ISSUE TITLE
Unable to launch Anaconda Navigator

### ISSUE THREAD

**Issue by SereneLaw** [ContinuumIO/anaconda-issues#6873]
(C:\Users\Law\Anaconda3) C:\Users\Law\Documents>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Law\Anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Law\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 126, in main
    clean_logs()
  File "C:\Users\Law\Anaconda3\lib\site-packages\anaconda_navigator\utils\logs.py", line 157, in clean_logs
    with open(path, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Law\\.anaconda\\navigator\\logs\\navigator.log' 

Why the launch permission is denied?

**Comment by goanpeca** [comment]
@SereneLaw it seems you may have started Navigator at some point with Administrator privileges. Could you remove the `C:\Users\Law\.anaconda\navigator\logs\navigator.log` file manually from the windows file explorer?

**Comment by punvenu** [comment]
Worked like magic. Thank you goanpeca.

**Comment by mayouf** [comment]
Hi there,

I have the same issue but the folder ".anaconda" is empty !!

So I don't have a clue what is the problem here !! 

I did all the update, but still not working again

**Comment by mayouf** [comment]
Hi,

I am not sure why, but typing `anaconda-navigator --reset` did the trick for me !!

**Comment by simon1tan** [comment]
> Hi there,
> 
> I have the same issue but the folder ".anaconda" is empty !!
> 
> So I don't have a clue what is the problem here !!
> 
> I did all the update, but still not working again

It's not empty. On my computer, those files are all hidden. I don't even know why they are hidden. Go to your command line and type:
 dir /a /s .anaconda
