### ISSUE TITLE
Python 2.7.14

### ISSUE THREAD

**Issue by ardeal** [ContinuumIO/anaconda-issues#6876]
Hi,
as we know, the latest anaconda includes python 2.7.13
When will python 2.7.14 be released/included in anaconda?

Thanks!

**Comment by msarahan** [comment]
It has been available for quite a while, but it's with the new package collection. You may need to update conda (4.3.27 or higher) or manually add https://repo.continuum.io/pkgs/main to your channel list.

**Comment by ardeal** [comment]
Thank you Msarahan!

Is the exe anaconda version that contains Python 2.7.14 available?
According to your estimation, when will it be available?

**Comment by goanpeca** [comment]
@ardeal Anaconda v5.0.1 is to be released this week. Python 2.7.14 is included in this version.
