### ISSUE TITLE
New solver should prefer newer versions

### ISSUE THREAD

**Issue by ilanschnell** [ContinuumIO/anaconda-issues#688]
@mcg1969 I just tried this (Using conda 4.0.1 on OSX):
```
$ conda create -n foo accelerate python=2.7
Fetching package metadata: ....
Solving package specifications: ...........
...
The following NEW packages will be INSTALLED:

    accelerate: 1.0.1-np16py27_p0 
    bitarray:   0.8.1-py27_0      
    libnvvm:    1.0-p0            
    llvm:       3.2-0             
    llvmpy:     0.11.1-py27_0     
    meta:       0.4.2.dev-py27_0  
    nose:       1.3.7-py27_0      
    numba:      0.7.1-np16py27_0  
    numbapro:   0.10.1-np16py27_p0
    numpy:      1.6.2-py27_4      
    openssl:    1.0.2g-0          
    python:     2.7.11-0          
    readline:   6.2-2             
    sqlite:     3.9.2-0           
    tk:         8.5.18-0          
    zlib:       1.2.8-0           
```
However, when I say:
```
$ conda create -n foo accelerate=2.0.2 python=2.7
```
all is fine.  This means that `accelerate 2.0.2` is feasible, but for whatever reason the solver prefers this really old `accelerate 1.0.1` version.  I would expect what when you don't specify a version of a package, that you *always* want the latest.

**Comment by teoliphant** [comment]
I can confirm the same behavior.   This is a regression.   The solver should prefer the latest version if not specified.

**Comment by ilanschnell** [comment]
Ops, this is a conda issue.  I opened the conda issue here: https://github.com/conda/conda/issues/2197

**Comment by mcg1969** [comment]
A fix has been generated here: https://github.com/conda/conda/pull/2199
