### ISSUE TITLE
python crashes with 'help()'  'modules'

### ISSUE THREAD

**Issue by fhag** [ContinuumIO/anaconda-issues#6880]
Python crashes when I want to check installed modules in help(); modules
I did run 'conda update anaconda', got some debugging msgs and the problem remains.
Else python seems to be working therefore the problem is not urgent.

System ist windows 10.

[crash_module.txt](https://github.com/ContinuumIO/anaconda-issues/files/1413831/crash_module.txt)

Thank you a lot for your work.

**Comment by mingwandroid** [comment]
I would recommend you do not install to a folder containing any non-ascii characters. In this case G[é](https://unicodelookup.com/#é/1)rard is problematic.
