### ISSUE TITLE
Anaconda doesnt process updates from 1.5 to 1.6.4

### ISSUE THREAD

**Issue by KelvinBeerJones** [ContinuumIO/anaconda-issues#6881]
I get an alert to update from 1.5 to 1.6.4, and after downloading I am told to restart Anaconda. Tried refreshing and closing down and starting up again but I am stuck at version 1.5 - I keep getting asked to update again!

**Comment by goanpeca** [comment]
@KelvinBeerJones, version 1.5 had a problem updating under some circumstances. 

To update via the command line please do the following:
Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
