### ISSUE TITLE
CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/win-64/repodata.json>

### ISSUE THREAD

**Issue by giplessis** [ContinuumIO/anaconda-issues#6884]
Dear all,
I'm trying to install calliope by the following command 
`conda create -c conda-forge -n calliope python=3.6 calliope`
but I get the following error message:
> Fetching package metadata ...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed:
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003B97710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))",),)

I tried to update conda :
`conda update conda`
but it failed too with the same error message.

`conda -V` gives
> conda 4.3.25

Any hints?

Best regards

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by giplessis** [comment]
It's working now! The problem seems to be intermittent as mentionned in the error message.
Thanks.
