### ISSUE TITLE
Anaconda3 v2.5.0 on Windows 8.1 does not install any desktop launcher

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#690]
I have just installed the latest x86_64 Windows version of Anaconda (2.5.0) onto a Windows 8.1 system where I have administrator privileges.  After completing the install there was no obvious way to _start_ Anaconda or to see where it had been installed (although perhaps I would remember that I had selected "Install for Everyone" and then had picked "/Anaconda3").  Importantly the "Launcher" Icon did not appear on my desktop.

When I use File Explorer to navigate to `/Anaconda3` I am left with a very short list of runnable programs that I need to dig around to identify:
- `python.exe`
- `pythonw.exe`
- `Uninstall-Anaconda.exe`

Not very inspiring!  Now, **personally** I know that the Anaconda Launcher is in a program called `launcher` that can be found inside `/Anacond3/Scripts`, so I went there, located it amongst the 224 other files in the `Scripts` directory, and ran it.  It runs fine.

But it should have been added to my desktop when I did the initial installation of Anaconda.

**Comment by ijstokes** [comment]
Some updates:

1. Even more confusingly, despite the fact that I've installed Anaconda3 the Launcher announces in the top menu bar that my Python version is 2.7.6-2

2. Since the Anaconda installer failed to add Launcher to my desktop I tried dragging the `Scripts/launcher` executable onto my desktop and selecting "create shortcut".  The shortcut is just of two gears.

**Comment by ijstokes** [comment]
Additional information that may be relevant to this: I already had an old Anaconda 2.0 installed in `\Anaconda` and even when I put the shortcut `C:\Anaconda3\Scripts\launcher.bat` (notice that this is in `\Anaconda3` which is from Anaconda 2.5.0) on my desktop to run it still appears to pick up my out of date Anaconda 2.0 with Python 2.7.6-2 (as noted above).  I dug into the launcher code a little but got lost in the Node App and couldn't figure out exactly where or why this was happening, however my best guess is that `C:\Anaconda\something\something` is already earlier on `%PATH%` and the install of Anaconda 2.5.0 based on Python 3.5 did nothing to change this.

**Comment by ijstokes** [comment]
After some conversation with @csoja I have done even more investigating and have some additional comments/clarifications:

* Anaconda 2.5.0 with Python 3.5 as the base/root env Python appears to be installed correctly in `C:\Anaconda3`, although some (or all) of the post-file-install steps for setting up the icons/program links have failed.

* There is no indication of Anaconda 2.5.0 programs in any of the 3 "normal" places I think someone would expect to find them:

**Comment by msarahan** [comment]
Was this a user-local or system wide install?  Do you have admin rights?  Did you decline the request for elevation that the installer presented?

If installing shortcuts fails, there should be popup messages, and we have certainly had many instances of those that we're trying to fix.  However, I haven't seen silent failure before (outside of the known case where the user denies elevation).

**Comment by ijstokes** [comment]
System wide install.  I have admin rights.  I would not have declined any request I saw, but also I cannot recall if I was presented with a request to elevate installer permissions.

**Comment by ijstokes** [comment]
My first bullet point above seems to be inaccurate: the file links were installed/setup but just not in an easy to find or obvious place.  Strangely search didn't find them, nor (initially) could I find them in the "tile" or "apps" view.

A suggestion: I think the majority of people voted that the "tile" view was confusing.  With the (effective) disappearance of the Start menu in Windows 8 (and 8.1) I would suggest that we need to drop the Launcher icon (or whatever the new thing is called) right onto the desktop so people can find it in Windows 8 (which a lot of people are still running).

**Comment by ijstokes** [comment]
@msarahan mustn't I have given it admin permissions if the files were successfully written to `C:\Anaconda3`?  Or is it conceivable that I "automatically" had permissions to do that while **not** having permission to correctly create the Anaconda tiles?  Or maybe my last bullet point above points to the fact that things **were** installed, just not in a way that is easy or obvious to find on a Windows 8 system.

Also, I've just realized why "search" wasn't helpful: I was only "searching" for "Anaconda" (because that is what I installed and that is what I wanted to find), however if I search instead for "Python" I discover a lot more of the pieces, and even learn something new about Windows search: it searches more than just the text string with the icon, so I get "Anaconda Cloud" (???? how would it associate that with Python? It is just a URL that gets opened in my browser), "Jupyter Notebook", "Spyder", "Launcher" (old one, not new one), and many others (but note, not the new Launcher which **does** show up in the App view now).

**Comment by msarahan** [comment]
No, C:\Anaconda3 is generally a writeable location by unelevated admin users.  This differs from the location where shortcuts get installed for all users.  Windows won't let you write there.  C:\Windows\Anaconda3 would probably also fail without elevation.

I will discuss with Crystal how many of these things should be shortcuts on the desktop, not just start menu entries.  Should we have options in the installer to only select one or the other?  Currently we have no provision for that.

Just a tip: for any program you want to be on the tile view, you can find it (either by search, or by navigating the program list), then right-click and say "pin to start" or something like that.  I don't know if there's a way for us to install directly to the tile view.  If there is, maybe we should do that instead of (or in addition to) shortcuts on the desktop.

**Comment by ijstokes** [comment]
@msarahan Yes, I'm aware of the "pin to start" option and use it a lot.  My main point here is not to get myself sorted out (I can find the bits and pieces I need) but to indicate i) an experience other Windows 8.x users may have; and ii) possibly identify an interplay with previous Anaconda installations that hadn't been considered.

The short story: I installed Anaconda 2.5.0 and then had no obvious way to find it or use it.

**Comment by dashesy** [comment]
I had a similar issue (on Windows7 when installed for all users); the shortcuts did not appear in the start menu. I installed [vc_redist.x64.exe](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and then reinstalled Anaconda, which solved the issue for me.

**Comment by kgautam01** [comment]
Help me out please.
I tried installing anaconda package several times on my windows 8.1 x86 but while checking for various 'conda list'on the command prompt, it shows an error that no such package found. This is what jappening even after installing the package. No launcher is showing on the desktop and no spyder application as well. I tried launching the launcher and spyder from inside the 'Scripts' but rather than getting launched, it opens up a terminal which is blank and doing nothing.
PLEASE HELP ME OUT.
My lappy works on normal AMD processor with 2GB ram and windows 8.1 build 9600 32 bit.

**Comment by kgautam01** [comment]
Has it got anything to related to do with the qt version installed on my device?
I do not have much knowledge about it.

**Comment by ijstokes** [comment]
@kgautam01 it sounds like you have more of a user support question than a bug report.  The Anaconda mailing list is probably a better place to ask your question/ask for help:

https://groups.google.com/a/continuum.io/forum/#!forum/anaconda

A screenshot or a copy of the error messages you are getting will make it easier for people to help you.
