### ISSUE TITLE
Anaconda Prompt cannot activate environment

### ISSUE THREAD

**Issue by harryawk** [ContinuumIO/anaconda-issues#6906]
Hi, I got some issues when using the Anaconda prompt on Windows 10.

I install the Anaconda3, for single user, not checking the "add the PATH of Anaconda3" box while installing, and after installation, I cannot use any commands that can be ran from the Anaconda Prompt (like `conda` or `jupyter notebook`).

After that, I look at the `%USER_HOME%\Anaconda3\Scripts` and I didn't found the activate.bat file.

I've tried activating the environment using activate.bat in the `%USER_HOME%\Lib\venv\scripts\nt\activate.bat` but it's still not activating the environment. Any ideas of what should I do or where can I find the activate.bat ?

Thank you

**Comment by mingwandroid** [comment]
What version of Anaconda did you install? Please provide a link to the exact installer. Can you try with the latest (5.0.1). Can you should the output in cmd.exe of:

```
echo %PATH%
where python.exe
```

When you installed Anaconda, did you have a virus scanner active? If so, which one.

It seems to me that `USER_HOME%\Lib\venv\scripts\nt\activate.bat` has nothing to do with `Anaconda`.

**Comment by csoja** [comment]
We have a fix in the most recent Miniconda installer for the "missing activate.bat" issue. Here are the current work around instructions, until a new version of the Anaconda installer is available:

Install Miniconda v4.3.31 or later from https://conda.io/miniconda.html or https://repo.continuum.io/miniconda/ 
Then, from the Anaconda Prompt:
conda install -y anaconda=5.0.1

For the full Anaconda 5.0.1 installer package list, use:
conda install -y anaconda=5.0.1 conda-build _ipyw_jlab_nb_ext_conf
