### ISSUE TITLE
Force re-install doesn't work on macOS.

### ISSUE THREAD

**Issue by mingwandroid** [ContinuumIO/anaconda-issues#6915]
@csoja we need to rush out a fix for this, @bryevdv you use force re-installs AFAIK?

```
pushd /tmp
rm -rf /tmp/m3
curl -SLO https://repo.continuum.io/miniconda/Miniconda3-4.3.30-MacOSX-x86_64.sh
bash ./Miniconda3-4.3.30-MacOSX-x86_64.sh -bfp /tmp/m3
bash ./Miniconda3-4.3.30-MacOSX-x86_64.sh -bfp /tmp/m3
```

.. gives:

```
ln: ./lib: File exists
Error: post-link failed for: python.app-2-py36h7fe2238_6
```

**Comment by bryevdv** [comment]
On TravisCI (linux), when an external contributor submits a PR, the job doesn't have permissions to upload and reuse build stage artifacts, so I just have it re-run the build stage instead. To keep things simple I was running `Minconda.sh -f` (and would prefer to be able to continue to do that)

**Comment by mingwandroid** [comment]
Ah ok, this is a `macOS`-specific problem. It happened because we added `python.app` to `Miniconda` for `macOS` in the new releases and the post-link script for it did not force overwrite a symlink. All post-links in our installers need to force things or ignore errors it seems.
