### ISSUE TITLE
pip cannot after upgrade anaconda 4.4.0 to 5.0.0

### ISSUE THREAD

**Issue by strategist922** [ContinuumIO/anaconda-issues#6931]
Hi Team,
     I encounteded a problem that pip cannot after upgrade anaconda 4.4.0 to 5.0.0,
When I run following pip command, it show me errors:
pip list --outdated --format=legacy --trusted-host pypi.python.org
Error messages:

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\list.py", line 157, in run
    packages = self.get_outdated(packages, options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\list.py", line 168, in get_outdated
    dist for dist in self.iter_packages_latest_infos(packages, options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\list.py", line 169, in <listcomp>
    if dist.latest_version > dist.parsed_version
TypeError: '>' not supported between instances of 'Version' and 'SetuptoolsVersion'

   May I know what has been changed in Anaconda 5.0.0? and how to fix it?

Thanks and best regards,
James Chang

**Comment by msarahan** [comment]
please try "conda update pip" from an "anaconda prompt" terminal.

We needed to un-vendor pip due to path length issues, but that cause other problems, like the one you see.  We ended up re-vendoring pip, but with newer versions that don't have the path length issues.

**Comment by csoja** [comment]
@strategist922 Did this resolve your issue?

**Comment by strategist922** [comment]
@csoja, it seems work now, thanks
