### ISSUE TITLE
Updating Spyder from inside of Navigator caused Navigator to crash on launch [Mac OS]

### ISSUE THREAD

**Issue by g4nym3de** [ContinuumIO/anaconda-issues#6935]
# conda version:4.3.30, python 2.7.12
# Running MAC OS 10.12.6
**What I did:**
When trying to update spyder, it hangs. I force quit navigator and it went into crash on launch mode forever.
**What I tried:**
rm -rf  ~/.continuum
which didnt work
then I tried
conda remove anaconda-navigator, 
which gives the following error:

ERROR conda.core.link:_execute_actions(337): An error occurred while uninstalling package 'defaults::anaconda-navigator-1.3.2-py27_0'.
UnicodeDecodeError('ascii', '/Users/***my usrname***/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:\xe2\x80\x9d/Users/***my usrname***/Downloads/platform-tools\xe2\x80\x9d', 107, 108, 'ordinal not in range(128)')
Attempting to roll back.

UnicodeDecodeError('ascii', '/Users/***my name***/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:\xe2\x80\x9d/Users/***my name***/Downloads/platform-tools\xe2\x80\x9d', 107, 108, 'ordinal not in range(128)')

and I got stuck.
I have to download a newer version of anaconda and I'm keeping both versions. Wondering if that's ok?

**Comment by goanpeca** [comment]
@g4nym3de you are using a very olde version of NAvigator

Please update to the latest.


Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
