### ISSUE TITLE
cannot import module 'dbus'

### ISSUE THREAD

**Issue by jsbyysheng** [ContinuumIO/anaconda-issues#6964]
In Ubuntu16.04.3, I can import module `dbus` normally if I don't use anaconda. But I got `ImportError: No module named 'dbus'` when I used `python -c "import dbus"` with anaconda installed.  I used `conda list` and I could see `dbus` had been installed.

**Comment by mingwandroid** [comment]
Our `dbus` package is not `pydbus`, it is the C dbus library.

**Comment by jsbyysheng** [comment]
okay,,, it's strange that if I uninstall anaconda, all goes ok.

**Comment by RuiKylin** [comment]
[https://stackoverflow.com/questions/47879660/how-to-use-python-dbus-bindings-in-anaconda](How to use Python Dbus bindings in Anaconda)
`conda install -c scottwales dbus-python`

**Comment by AbstProcDo** [comment]
any better solution now? not working on python 3.7

**Comment by jsbyysheng** [comment]
> any better solution now? not working on python 3.7

Why not try using Anaconda in docker? The combination of VSCode and Anaconda Docker is very convenient.
