### ISSUE TITLE
Update error - Anaconda Navigator

### ISSUE THREAD

**Issue by ganesh3** [ContinuumIO/anaconda-issues#6985]
Hi,

I am getting the below error in Windows 10 for Anaconda3 update. My user has been provided write access as well to the folder.

(D:\Anaconda3) C:\Users\ganes>conda update anaconda-navigator
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment D:\Anaconda3:

The following packages will be UPDATED:

    anaconda:           4.4.0-np112py36_0 --> custom-py36h363777c_0
    anaconda-navigator: 1.6.2-py36_0      --> 1.6.9-py36hc720852_0
    conda-env:          2.6.0-0           --> 2.6.0-h36134e3_1

Proceed ([y]/n)? y

INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'None', used_mode: 'user'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'None', used_mode: 'user'
ERROR conda.core.link:_execute_actions(337): An error occurred while uninstalling package 'defaults::anaconda-navigator-1.6.2-py36_0'.
PermissionError(13, 'The process cannot access the file because it is being used by another process')
Attempting to roll back.

INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'None', used_mode: 'user'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'None', used_mode: 'user'

PermissionError(13, 'The process cannot access the file because it is being used by another process')

Regards
Ganesh Bhat

**Comment by mingwandroid** [comment]
Please try immediately after a reboot and also try temporarily disabling any virus scanners.
