### ISSUE TITLE
Nothing happens when i click 'Launch' buttons in Anaconda Navigator

### ISSUE THREAD

**Issue by samiryadav** [ContinuumIO/anaconda-issues#6987]
hi,
i am new to anaconda and programming.
i installed Anaconda3-5.0.1-Windows-x86_64
Installation finished successfully.But after installation, wheni click 'Launch' button for spyder,Jupyter etc,
nothing happens.Nothing loads.
(i also tried re installing but still the same issue).
i am running windows 64-bit 10 fall creator update.

Also, when i open python , spyder, jupyter directly from start menu , it works.
Install button works.when i pressed 'install' for r-studio, it installed the r-studio.

Thanks in advance.

**Comment by goanpeca** [comment]
@samiryadav , what type of installation did you perform. All users, current user? 

Could you open the Anaconda Prompt and type

```
$ conda info
$ conda list
```

**Comment by samiryadav** [comment]
hi,
Thanks for taking time to write and help.
In the mean time i reinstalled OS on my system as my system starts crashing
(BSOD) after few minutes.
after OS recovery, anaconda navigator is working. :)
i think it was some problem with OS after latest Fall Creators update of
windows 10.

Thanks again and have a good day.

**Comment by goanpeca** [comment]
@samiryadav no problem :-), glad to be of help

**Comment by koulabhinav** [comment]
Hello There,
I am facing this issue for some time. Have done multiple rounds of installation but still the same.
I have performed an "All User" installation. 

Another thing I noticed while launching Jupyter post instantiating Anaconda Navigator via command line is that I get below error:
'C:\Users\Abhinav' is not recognized as an internal or external command, operable program or batch file.


Here is the o/p of "conda info":

$ (base) PS C:\Users\Abhinav Koul> conda info
     active environment : base
    active env location : C:\Anaconda3
            shell level : 1
       user config file : C:\Users\Abhinav Koul\.condarc
 populated config files : C:\Users\Abhinav Koul\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=11.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Anaconda3  (writable)
      conda av data dir : C:\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\Abhinav Koul\.conda\pkgs
                          C:\Users\Abhinav Koul\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\Abhinav Koul\.conda\envs
                          C:\Users\Abhinav Koul\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
