### ISSUE TITLE
Update PyMC windows to work with anaconda 1.6 and 1.7

### ISSUE THREAD

**Issue by twiecki** [ContinuumIO/anaconda-issues#7]
The current PyMC 32 bit windows version seems to only work for an older Anaconda using npy 1.6.

It would be great if this package was upgraded.

Going forward I am wondering whether with a new anaconda version all official packages will also be upgraded to work with it.

**Comment by csoja** [comment]
Closing this as it looks like there were PRs merged at the time to address it, and pymc continues to be updated - and the latest is built against NumPy 1.11.
