### ISSUE TITLE
Pandas 0.21.0 not available through conda install

### ISSUE THREAD

**Issue by Austrianguy** [ContinuumIO/anaconda-issues#7026]
`conda install pandas=0.21.0` in Anaconda Prompt

raises

    PackageNotFoundError: Packages missing in current channels:
    - pandas 0.21.0*

This package version is available in `pip`. Please bring it to Anaconda to!

**Comment by vmuriart** [comment]
it is available on *conda-forge* [channel](https://anaconda.org/conda-forge/pandas). I'm not sure if this version is compiled the same way `Anaconda` expects it to be though.

`conda install -c conda-forge pandas`

An addendum to the question would be, is the *conda-forge* version compiled using the same tool-chain as *Anaconda*'s?

**Comment by mingwandroid** [comment]
No, `conda-forge` are not using the same toolchain as `defaults`. The toolchains on `defaults` are more modern. We are hoping to unify on toolchains soon.

This shouldn't matter for pure-Python things though.

**Comment by vmuriart** [comment]
@mingwandroid thanks for clarifying!

**Comment by dr-leo** [comment]
I ran into the same Problem. Pandas is available up to v0.20 through the Defaults channel. The lack of updates there has apparently not been communicated. The Pandas docs still advice a Standard conda install.

What is the reason for dropping binary Support of Pandas in the Defaults channel? Are other packages affected by this move?

**Comment by msarahan** [comment]
You probably need to update conda.  When we changed to our new toolchains, we started putting the new packages in a new place, the ``main`` channel, which lives at https://repo.continuum.io/pkgs/main.  Conda automatically adds that for you as of conda 4.3.26.  If you're using an earlier conda version and haven't otherwise added that channel, you will not see new packages.

**Comment by csoja** [comment]
pandas v 0.22.0 was uploaded to https://repo.continuum.io/pkgs/main/ on Sun Dec 31 2017.
pandas v0.21.1 was uploaded Dec 12, 2017.
pandas 0.21.0 was uploaded Nov 4th, 2017.

Closing this issue.
