### ISSUE TITLE
MD5 sums mismatch for download: https://conda.anaconda.org/r/osx-64/r-assertthat-0.1-r3.2.2_2.tar.bz2

### ISSUE THREAD

**Issue by clausherther** [ContinuumIO/anaconda-issues#703]
This was an open issue for Windows and was closed.

I'm getting this error trying to install r-essentials on the Mac:

Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/osx-64/r-assertthat-0.1-r3.2.2_2.tar.bz2

Mac OS X El Capitan 
conda 4.04 (Python 3.5.1 :: Anaconda 2.5.0 (x86_64))

**Comment by mingwandroid** [comment]
We are investigating this now.

**Comment by groutr** [comment]
I'm in the process of fixing the packages.

**Comment by clausherther** [comment]
Looks like this has been fixed, yes?

**Comment by csoja** [comment]
Yes, you are correct.  Closing the issue.
