### ISSUE TITLE
MD5 sums mismatch for r-base64enc-0.1_3-r3.2.2_0.tar.bz2

### ISSUE THREAD

**Issue by vroetman** [ContinuumIO/anaconda-issues#704]
When running `conda install r-base64enc` (or install --force for reinstall) I get the following error:

Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/r-base64enc-0.1_3-r3.2.2_0.tar.bz2 (77d12ee37cc0fdc0466171ad0097fabd != f083b028f4bf5d4a6255bd0149eb6774)

This is on Linux, running 
conda 4.0.4
and
Python 3.5.1 :: Continuum Analytics, Inc.

There is something funny with
https://anaconda.org/r/r-base64enc/files
where the files all seem to have been "updated" within the last 24 hours, have zero downloads, with new md5 sums, but the downloaded file matches the "old" md5sum that is further down.

**Comment by vroetman** [comment]
I'm pretty sure this is the same issue as #703 
Somehow all the offending packages were recently uploaded by "rgrout". Is @groutr aware of this?

**Comment by groutr** [comment]
@vroetman I am aware of the issue and I am working on a fix right now.

**Comment by vroetman** [comment]
It seems to be working for me this morning. Thanks for fixing it @groutr !
