### ISSUE TITLE
Error trying to install jupyter notebook in new environment

### ISSUE THREAD

**Issue by andregmiranda** [ContinuumIO/anaconda-issues#7044]
I've created a new environment to work with Python 2, but I keep getting this error when trying to install Jupyter Notebook package. I'd appreciate if anyone could lend me a hand. I'm new to Anaconda, so I have no ideia where to start.

![conda_error1](https://user-images.githubusercontent.com/33287398/32278402-c5647f20-befc-11e7-9e0e-3285b7e174dc.jpg)
![conda_error2](https://user-images.githubusercontent.com/33287398/32278403-c592d3ac-befc-11e7-9d1d-b285790b126f.jpg)
![conda_error3](https://user-images.githubusercontent.com/33287398/32278404-c5d0ce64-befc-11e7-95e0-4beb4fb1eca0.jpg)
![conda_error4](https://user-images.githubusercontent.com/33287398/32278405-c60b66be-befc-11e7-8714-2bf760d242d6.jpg)

**Comment by goanpeca** [comment]
@andregmiranda could you reinstall for the current user and not all users? Also, you need to install in a path that does not contain non-ascii characters or spaces.
