### ISSUE TITLE
Need an Anaconda distribution with all packages included...

### ISSUE THREAD

**Issue by Felix-neko** [ContinuumIO/anaconda-issues#7045]
Hi, folks! And thank you for your project = )

We need to deploy Anaconda in some computer classes that don't have internet connection. Sometimes our students need the packages that are listed in the Anaconda package list but aren't included in Anaconda installer by default (for example, PyQtGraph package).

Can you make some distribution like **Anaconda Full** in which all the packages will be included?

P.S. Its size is not a problem: some guys still use MATLAB that weights 10 Gb and more = )

**Comment by goanpeca** [comment]
@Felix-neko you could do this very thing you ask for by using constructor, which is the Open Source tool to create Anaconda Like distribution installers with specific packages of your choice

Take a look at https://github.com/conda/constructor/

**Comment by Felix-neko** [comment]
Gracias, compadre!
