### ISSUE TITLE
Broke Anaconda when updated Notebook on Mac OSX

### ISSUE THREAD

**Issue by amanparnami** [ContinuumIO/anaconda-issues#706]
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by dvu4** [comment]
yes I had the same the problem. Please help me to fix it.

**Comment by ilanschnell** [comment]
I need more information to reproduce this problem.  What is the OS?  Did you just:
```
$ conda update notebook
$ jupyter_notebook
```
and then get the error?

**Comment by dvu4** [comment]
my OS is El Captain 10.11.3 and I used to launcher to open notebook. When I tried the command like above in the terminal but it does not work.

`DUCs-MacBook-Air:~ ducvu$ conda update notebook
-bash: conda: command not found 
`
I also attached the error 

![1](https://cloud.githubusercontent.com/assets/11560476/13882894/450241bc-ecf5-11e5-8f2b-fd6b712c62d2.png)
![2](https://cloud.githubusercontent.com/assets/11560476/13882895/46255eda-ecf5-11e5-97fd-b387fb7fd330.png)

**Comment by csoja** [comment]
Launcher has been deprecated.  Please check out Anaconda-Navigator: https://docs.anaconda.com/anaconda/navigator/
