### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jrestupinian** [ContinuumIO/anaconda-issues#7079]
## Main error
Application <b>rstudio</b> launch may have produced errors.
## Traceback
```
/home/jose/anaconda3/bin/rstudio: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.9.51-1-MANJARO;#1 SMP PREEMPT Wed Sep 20 10:37:40 UTC 2017;x86_64;
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.27
```

**Comment by mingwandroid** [comment]
You need to install `libselinux` via your system package manager.

**Comment by goanpeca** [comment]
## See issue #3374 for more information on how to fix this issue.**

---

Closing as duplicate of #3374

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
