### ISSUE TITLE
Read 2GB or more from binary file using builtin read on 64bit python

### ISSUE THREAD

**Issue by dashesy** [ContinuumIO/anaconda-issues#709]
Windows7 x64 with Python 2.7.11 (Anaconda2 2.4.1 64-bit):

```ipynb
    >>> platform.architecture()
    Out[44]: ('64bit', 'WindowsPE')
```

I can read the entire file with `f.read()` but when I try to read a portion of the file with `f.read(count)` I get an error.

To reproduce, create file of size equal 8GB then try to read 4GB:

```python
    with open(fname, mode='rb') as f:
        content=f.read(0x100000000)
```

Will result in:
```text
    OverflowError: Python int too large to convert to C long
```

The maximum count I can read is `0x100000000 / 2 - 1` or (2GB - 1)

**Comment by groutr** [comment]
That's strange.  What is the value of `python -c "import sys; print(sys.maxint)"`?

**Comment by insertinterestingnamehere** [comment]
This sounds like it could be a Python bug. On 64 bit Windows, `long` is 32 bits, and that number corresponds to the maximum 32 bit integer positive value. They ought to be using 64 bit integers internally for stuff like this this.

**Comment by dashesy** [comment]
@groutr sorry it took some time, I since had moved to Anaconda3, I installed that version again for this test. `sys.maxint` is `2147483647`

>> Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 14:10:42) [MSC v.1500 64 bit (AMD64)]

**Comment by groutr** [comment]
@insertinterestingnamehere is right and this is a limitation with windows.  This is completely untested, but does `f.read(long(0x100000000))` work?

**Comment by dashesy** [comment]
No, same error as before. If it is a limitation on Windows I wonder why Anaconda3 and Python3 works. Perhaps it is a bug only fixed in Python3. Because this version works fine:

> Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 15:01:46) [MSC v.1900 64 bit (AMD64)]

**Comment by groutr** [comment]
That would make sense.  I guess the answer to this would be use Python 3.

**Comment by pitrou** [comment]
Python 3 has its own IO stack and has solved this kind of issues carefully. Python 2 is based on the C buffered IO stack (`fopen()` and friends) and suffers from all kind of platform-specific limitations.

**Comment by groutr** [comment]
Thanks for clarifying @pitrou.
If there's nothing further to discuss, I'm going to close this issue tomorrow.

**Comment by dashesy** [comment]
Thanks! It is solved for me anyways, Python3 is a much better language.
