### ISSUE TITLE
Jypuy

### ISSUE THREAD

**Issue by timofmax** [ContinuumIO/anaconda-issues#7090]
fresh install of Anaconda on Mac Os Sierra - the problems is can't open Jupyter, Spyder.
here is output when trying to open Jupyter:
```
PinacleOfAwesome:~ Tim$ /Users/Tim/anaconda3/bin/jupyter_mac.command ; exit;
Error in sitecustomize; set PYTHONVERBOSE for traceback:
KeyError: 'PYTHONPATH'
Traceback (most recent call last):
  File "/Users/Tim/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/Tim/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
  File "/usr/local/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/usr/local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/usr/local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/local/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/local/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/zmq/backend/cython/constants.so, 2): Symbol not found: _PyInt_FromLong
  Referenced from: /usr/local/lib/python2.7/site-packages/zmq/backend/cython/constants.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/zmq/backend/cython/constants.so
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```
What to do to fix it?

**Comment by mingwandroid** [comment]
You probably have (both/either) the `PYTHONPATH` (and/or) the `PYTHONHOME` environment variable(s) set to something. You need to not set those.

**Comment by timofmax** [comment]
Just checked:
`printenv`
Output:
`PinacleOfAwesome:~ Tim$ printenv
TERM_PROGRAM=iTerm.app
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/zl/dz8xcbb56dj2r581wf1c53y80000gp/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.rRqnTnHFzo/Render
TERM_PROGRAM_VERSION=3.1.4
TERM_SESSION_ID=w0t0p0:463757BB-626A-4654-BC86-7ED27FD60212
USER=Tim
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.LSNwEmNkDJ/Listeners
__CF_USER_TEXT_ENCODING=0x1F6:0x7:0x31
PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/Tim/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin/python2/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/bin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS
PWD=/Users/Tim
LANG=ru_RU.UTF-8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/Tim
COLORFGBG=7;0
ITERM_SESSION_ID=w0t0p0:463757BB-626A-4654-BC86-7ED27FD60212
LOGNAME=Tim
SECURITYSESSIONID=186a7
COLORTERM=truecolor
_=/usr/bin/printenv`
`PYTHONPATH` and `PYTHONHOME` not in environment variables.
Do I need to add variables and link them to python?
such as: `PinacleOfAwesome:~ Tim$ which python
/Users/Tim/anaconda3/bin/python
PinacleOfAwesome:~ Tim$ which python3
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`

**Comment by mingwandroid** [comment]
Having your system `Python` in front of `Anaconda`'s `Python` on `PATH` is likely the problem here.

I would recommend that you remove `Anaconda` from your `PATH` and use the `activate` script when you want to use `Anaconda`
