### ISSUE TITLE
Tensorflow 1.4.0 packages

### ISSUE THREAD

**Issue by 183amir** [ContinuumIO/anaconda-issues#7094]
Hi,

Tensorflow 1.4.0 packages have been released: https://github.com/tensorflow/tensorflow/releases/tag/v1.4.0
Is it possible to have the new version in the defaults channel?

Thanks!

**Comment by 183amir** [comment]
It has been two months now. Is there anything that I can do to help? A macos version of tensorflow 1.4.0 (besides the linux version) would also be great.

**Comment by jjhelmus** [comment]
Tensorflow 1.4.1 packages for linux-64 can be found in [my testing channel](https://anaconda.org/jjh_cio_testing/tensorflow-base).  These are still undergoing testing before moving to `defaults` at which time the files in the `jjh_cio_testing` channel will be re-named.  You are welcome to try them out.  

Packages supporting GPU are also being worked on, I'll update this thread with any progress.

**Comment by 183amir** [comment]
Thank you seems the packages are in now.
