### ISSUE TITLE
Matplotlib ImportError due to wrong libz being used, does not exist with system packages

### ISSUE THREAD

**Issue by wortiz** [ContinuumIO/anaconda-issues#7097]
On ubuntu 16.04 using miniconda2 for 64bit

I have miniconda2 installed with matplotlib on the front of my path and paraview (https://www.paraview.org/) downloaded and at the end of my path:

    $ echo $PATH
    /home/wortiz/miniconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wortiz/.local/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit/bin

When trying to run a script with matplotlib  with miniconda I get an ImportError:

    Traceback (most recent call last):
      File "../interpolate.py", line 6, in <module>
        import matplotlib.pyplot as plt
      File "/home/wortiz/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
        import matplotlib.colorbar
      File "/home/wortiz/miniconda2/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
        import matplotlib.contour as contour
      File "/home/wortiz/miniconda2/lib/python2.7/site-packages/matplotlib/contour.py", line 21, in <module>
        import matplotlib.font_manager as font_manager
      File "/home/wortiz/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py", line 58, in <module>
        from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
    ImportError: /home/wortiz/.local/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/wortiz/miniconda2/lib/python2.7/site-packages/matplotlib/../../.././libpng16.so.16)

ldd gives:

    $ ldd /home/wortiz/miniconda2/lib/python2.7/site-packages/matplotlib/../../.././libpng16.so.16
    	linux-vdso.so.1 =>  (0x00007ffe1c29c000)
    	libz.so.1 => /home/wortiz/miniconda2/lib/python2.7/site-packages/matplotlib/../../../././libz.so.1 (0x00007f29d5767000)
    	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f29d5428000)
    	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f29d505e000)
    	/lib64/ld-linux-x86-64.so.2 (0x0000559405de1000)

Removing paraview from the end of the path resolves the ImportError, I'm not sure how python is finding this libz as it is not on any library path and it does not seem to matter if I put paraview before or after miniconda on my PATH.

Running the same script using matplotlib and python from the ubuntu repositories with paraview on the path does not cause the same issue.

**Comment by mingwandroid** [comment]
This means that `paraview` and the `Anaconda Distribution`'s Python are incompatible because we use a more up to date `zlib` than they do.

This has nothing to do with `PATH` at all, since the only thing `PATH` is used for here is to locate `python`. Linux has more comprehensive mechanisms of locating shared libraries than Windows (where `PATH` matters a lot).

If you re-arrange you import statements such that `matplotlib` gets loaded before `paraview` things stand a better chance of working.

**Comment by wortiz** [comment]
I'm not importing paraview, I have no python interaction with paraview it is simply downloaded and on my path.

**Comment by wortiz** [comment]
I found another shared library built with cmake had found and used that libz using the PATH, rebuilding fixed.
