### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by avantikab** [ContinuumIO/anaconda-issues#7112]
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Packages missing in current channels:
            
  - rstudio ==1.0.153

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
            
```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.27
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by mingwandroid** [comment]
Can you restart navigator and try again?

Otherwise try from the Anaconda Prompt:

`conda create -n rstudio python=3.6 r-essentials=1.7 rstudio`

Rstudio and Python 2 cannot be installed in the same environment.

**Comment by avantikab** [comment]
@mingwandroid Thanks! This worked. But what if I need to work on Python 2.7. What do I need to do then?

**Comment by avantikab** [comment]
@mingwandroid is it better if I install R Studio separately?

**Comment by mingwandroid** [comment]
> But what if I need to work on Python 2.7. What do I need to do then?

You can create an environment for Python 2.7 (your root env will be ok here) and another for RStudio. If you need to use them in tandem via Rpy2 then you may need to do some manual manipulation of your `PATH` environment variable but it *should* work.

If you do not need to use them in tandem then it is best practice to isolate different software in different environments.

This limitation is imposed by us on the fact that Python 2 on Windows needs to run against the Visual Studio 2008 runtime and RStudio needs to run against the Visual Studio 2015 runtime and they are not compatible.

macOS and Linux do not suffer from this.

> is it better if I install R Studio separately?

Putting RStudio in it's own environment is more or less the same thing as installing RStudio separately.
