### ISSUE TITLE
How to install xgboost in tensorflow environment in Anaconda??

### ISSUE THREAD

**Issue by ashimagarg** [ContinuumIO/anaconda-issues#7145]
In anaconda prompt, I activated tensorflow using : 

activate tensorflow

I want to install xgboost in this tensorflow environment. I tried using this command : 

conda install -c conda-forge xgboost 

PackageNotFoundError: Packages missing in the current channels
  -xgboost

**Comment by csoja** [comment]
What platform are you on?  It looks like the conda-forge xgboost is only available for 64-bit Linux and Mac.  The Anaconda channel has py-xgboost, r-xgboost, and libxgboost for linux 32+64, Mac 64, Win 32+64.  You can see the full list of what "xgboost" conda packages are available on Anaconda Cloud here: https://anaconda.org/search?q=xgboost

**Comment by ashimagarg** [comment]
I am working on windows 64-bit platform. From the above link provided by you, I tried the following command : 

conda install -c anaconda py-xgboost 

But when I try to run a code from Spyder:
from xgboost import XGBClassifier 

IPython console returns 

Traceback (most recent call last):

  File "<ipython-input-2-9b31cfdb821c>", line 1, in <module>
    from xgboost import XGBClassifier

 File "F:\Machine Learning A-Z\Part 10 - Model Selection & Boosting\Section 49 - XGBoost\XGBoost\xgboost.py", line 30, in <module>
    from xgboost import XGBClassifier

ImportError: cannot import name 'XGBClassifier'


What should I do to resolve this issue?

**Comment by ashimagarg** [comment]
I am working on windows 64-bit platform. From the above link provided by you, I tried the following command :

conda install -c anaconda py-xgboost

And this solved my issue. 
Thanks for the help!

**Comment by csoja** [comment]
Great!
