### ISSUE TITLE
Installation fails on Mac  10.11.4 Beta (15E64a)

### ISSUE THREAD

**Issue by maysonicboom** [ContinuumIO/anaconda-issues#715]
Error message: Anaconda cannot be installed in /Volumes/Macintosh HD/Users/maysonlancaster because the path contains spaces.
Anaconda3-2.5.0-MacOSX-x86_64

**Comment by ccordoba12** [comment]
@ilanschnell?

**Comment by ilanschnell** [comment]
The Unix installers currently do not support spaces in the install path.  Sorry.

**Comment by mingwandroid** [comment]
Usually on OS X `/Volumes/Macintosh HD/` is the `sysroot`, so you can refer to it as simply `/`, therefore you might be able to workaround this issue for now by installing to `/Users/maysonlancaster/` instead.

**Comment by dg1sek** [comment]
On MacOS the problem seems to be that the graphical installer ALWAYS put "/Volumes/Macintosh HD" into the path and then fails. Only solution I found is use the command line installer, and then use "/Users/" instead of "/Volumes/Macintosh HD/Users/" as path...
