### ISSUE TITLE
using anaconda behind a proxy server in ubuntu 16.04

### ISSUE THREAD

**Issue by varshaneya** [ContinuumIO/anaconda-issues#7158]
What is the procedure for configuring proxy for anaconda in ubuntu 16.04? I am getting the error "Cannot connect to proxy" while using conda install. This is after adding proxy server related info in .condarc file in home directory.

The official site https://conda.io/docs/user-guide/configuration has proxy configuration information only for windows.

**Comment by goanpeca** [comment]
@varshaneya could you make sure you set the right values on .condarc as specified in the documentation AND add the following environment variables with the correct values (10.10.1.10:3128 is just for example):

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

**Comment by varshaneya** [comment]
I have set the environment variables HTTP_PROXY and HTTPS_PROXY as per my proxy server along with configuring .condarc file. Still getting the same error. What to do? Please reopen this issue. Thanks in advance.
