### ISSUE TITLE
Unable to create new anaconda python3 environment

### ISSUE THREAD

**Issue by tombardo** [ContinuumIO/anaconda-issues#718]
I installed Anaconda2-2.5.0 for windows 64 bit.  The install went fine and I have a functioning python 2.7 environment.  When I try to create a python3 anaconda environment using conda I get the following errors:

conda create -n py34 python=3.4 anaconda

This fails during linking with:

`ipython-qtcons 100% |###############################| Time: 0:00:00 1.31 MB/s
ipywidgets-4.1 100% |###############################| Time: 0:00:00 2.68 MB/s
spyder-2.3.8-p 100% |###############################| Time: 0:00:00 8.39 MB/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00 562.04 kB/s
spyder-app-2.3 100% |###############################| Time: 0:00:00 2.53 MB/s
anaconda-2.5.0 100% |###############################| Time: 0:00:00 1.41 MB/s

Extracting packages ...
[ COMPLETE ]|##################################################| 100%
Linking packages ...
The system cannot find the path specified.#### | 46%
Error: Error: post-link failed for: qt-4.8.7-vc10_5`

I have then tried to force install of qt and pyqt with no success:

`conda install -f qt
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
qt
Use "conda info " to see the dependencies for each package.`

Also if I do a conda list on the new environment any package that comes alphabetically after pyqt is not installed.

**Comment by nehaljwani** [comment]
Closing as `Python 3.4` is no longer supported.
