### ISSUE TITLE
latest `mistune` conda package broken on OS X

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#719]
_From @desilinguist on March 18, 2016 16:56_

Trying to export an iPython notebook to HTML on OS X leads to an error:

```
 File "/Users/nmadnani/anaconda/envs/rsmextra/lib/python3.4/site-packages/nbconvert/filters/markdown.py", line 22, in markdown2html_mistune
    raise ImportError("markdown2html requires mistune: %s" % _mistune_import_error)
ImportError: markdown2html requires mistune: dlopen(/Users/nmadnani/anaconda/envs/rsmextra/lib/python3.4/site-packages/mistune.so, 2): no suitable image found.  Did find:
	/Users/nmadnani/anaconda/envs/rsmextra/lib/python3.4/site-packages/mistune.so: malformed mach-o image: load command #12 length (0) too small in /Users/nmadnani/anaconda/envs/rsmextra/lib/python3.4/site-packages/mistune.so
```

I see that a new version (0.7.2) of the `mistune` package was built a few days ago. Downgrading to 0.7.1 makes the export work fine.

_Copied from original issue: conda/conda#2287_

**Comment by kalefranz** [comment]
_From @desilinguist on March 21, 2016 20:33_

Any thoughts on this?

**Comment by kalefranz** [comment]
I've reproduced this on OS X with mistune 0.7.2 and python 3.4 and 3.5.  Just `import mistune` to see the error.  The 0.7.1 is fine.

**Comment by clauswilke** [comment]
Until this is fixed, is there an easy way to downgrade `mistune`? Can this be done straight from `conda`? I've got a class of 60 students relying on a working `mistune` package to submit their homeworks.

**Comment by kalefranz** [comment]
I just verified this is fixed.  `conda update mistune` should give you something like `0.7.2-py35_1`.  However, `conda install mistune=0.7.1` would have also worked to dowgrade.

**Comment by clauswilke** [comment]
Yup, works. Great, thanks!
