### ISSUE TITLE
Anaconda crashes

### ISSUE THREAD

**Issue by Sameerkanse** [ContinuumIO/anaconda-issues#7191]
I am facing similar issue where Anaconda launches and then closes within 1 sec after showing home screen. Traceback report below
anacTraceback (most recent call last):
  File "/Users/sameerkanse/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6

i have already tried anaconda-navigator reset and that hasn't helped

**Comment by mingwandroid** [comment]
Anaconda uses Python 3.6 now, so you must have installed a pretty old version here. Please give exact details.

**Comment by goanpeca** [comment]
@mingwandroid is correct you are using an old (deprecated) version of Anaconda Navigator.

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Comment by Sameerkanse** [comment]
it updated in terminal however now Anconda won't open at all
It gives an error "Application Anaconda-Navigator cannot be opened"

when i entered the last command $ conda update navigator-updater it said 
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/sameerkanse/anaconda
  package name: navigator-updater
