### ISSUE TITLE
Cannot open Jupyter notebook

### ISSUE THREAD

**Issue by bebarge** [ContinuumIO/anaconda-issues#7193]
I downloaded Anaconda and typed in the Command Prompt as suggested "jupyter notebook"
But i got this:
![image](https://user-images.githubusercontent.com/33486904/32550205-5cb0f90a-c473-11e7-9c5d-f0d530cb620b.png)
My Anaconda version is 5.0.1

**Comment by mingwandroid** [comment]
On Wed, Nov 8, 2017 at 1:10 PM, patex1987 <notifications@github.com> wrote:

> I can see that You are using windows. Are You sure, that your python
> library (or anaconda) path is in your system PATH. If I recall it
> correctly, you were prompt during the installation to put Anaconda into
> your PATH. If you didn't choose that option, then these commands wont work
>

This is bad advice. The installer warns against doing this and people
should not ignore that warning. DLL hell is a bad problem on Windows, both
for the correct operation of Anaconda and also for the correct operation of
previously installed software. Adding to PATH on Windows should be avoided
whenever possible.

We provide the `Anaconda Prompt` and `Anaconda Navigator` both of which you
can find in the Start Menu. You should prefer to use these instead.
