### ISSUE TITLE
Anaconda-Navigator opening issue

### ISSUE THREAD

**Issue by Sameerkanse** [ContinuumIO/anaconda-issues#7196]
I tried updating Anaconda as mentioned in previous thread #7191 using
$ Conda update conda
$ conda update Anaconda-navigator
@ conda update navigator-updater

While first 2 commands updated the third command gave below error
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/sameerkanse/anaconda
  package name: navigator-updater

And now Anaconda-navigator just won't open. It says "File cannot be opened"

**Comment by goanpeca** [comment]
@Sameerkanse in that case please install the updater

`$ conda install navigator-updater`
