### ISSUE TITLE
numexpr with mkl-2018

### ISSUE THREAD

**Issue by prisae** [ContinuumIO/anaconda-issues#7207]
This is more a question than an issue. It looks like `numexpr` is not built against VML for `mkl-2018`, where it has been for `mkl-2017.0.4` and earlier (see https://github.com/pydata/numexpr/issues/293#issuecomment-343027562). Was this done on purpose? Will it remain like that, or might later versions of `numexpr` be built against VML again?

**Comment by msarahan** [comment]
That's a regression.  I don't know why - it was built against mkl, but apparently the VML part did not stick.  We'll fix it.

**Comment by prisae** [comment]
OK. Thanks for the quick reply.

**Comment by msarahan** [comment]
Reopening this until I have fixed the issue.

**Comment by msarahan** [comment]
new packages are available on the c3i_test2 channel.  @prisae if you can test them, I'd be appreciative.  The mkl site.cfg was not getting used, so I don't think the earlier builds were actually built against mkl (though that was our intention).  The new builds have this output in their test results:

```
===== testing package: numexpr-2.6.2-py36h514de0f_2 =====
10:53:36
running run_test.py
10:53:36
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
10:53:36
Numexpr version:   2.6.2
10:53:36
NumPy version:     1.13.3
10:53:36
Python version:    3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
10:53:36
AMD/Intel CPU?     True
10:53:36
VML available?     True
10:53:36
VML/MKL version:   Intel(R) Math Kernel Library Version 2018.0.0 Product Build 20170720 for Intel(R) 64 architecture applications
10:53:36
Number of threads used by default: 6 (out of 6 detected cores)
10:53:36
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by prisae** [comment]
Works fine for me with the new version.

**Comment by msarahan** [comment]
Thanks.  Closing.
