### ISSUE TITLE
Boost 1.60.0 fails due to its use of deprecated ice_not traits

### ISSUE THREAD

**Issue by benmwebb** [ContinuumIO/anaconda-issues#721]
The boost folks removed ice_not in 1.60 but forgot to update
boost::graph accordingly. Now any use of adjacency_matrix.hpp
(pretty much any package that uses Boost::Graph) fails:

    $ cat test.cpp
    #include <boost/graph/adjacency_list.hpp>
    #include <boost/graph/adjacency_matrix.hpp>

    $ g++ -c test.cpp -I /root/miniconda/include/
    /root/miniconda/include/boost/graph/adjacency_matrix.hpp:446: error: ‘ice_not’ is not a member of ‘boost::type_traits’
    /root/miniconda/include/boost/graph/adjacency_matrix.hpp:446: error: ‘::value’ has not been declared

This is upstream Boost bug https://svn.boost.org/trac/boost/ticket/11880.

This is easy to fix by applying the upstream patch, boostorg/graph@1d5f43d.

**Comment by ilanschnell** [comment]
Looks like an upstream problem, which is beyond the scope of Anaconda.

**Comment by ccordoba12** [comment]
I'll take a look at this one :-)
