### ISSUE TITLE
Anaconda-navigator doesn't open because of "QXcbConnection: XCB error: 3"

### ISSUE THREAD

**Issue by Thatguy1114** [ContinuumIO/anaconda-issues#7212]
I'm running Fedora 26, and starting Anaconda-navigator in the terminal. When I run `anaconda-navigator` the linked file ([hyperlink](https://gist.github.com/Thatguy1114/e43e5f4cd585defd880354f55410f86b)) is the output.

**Comment by goanpeca** [comment]
@Thatguy1114 that is the output and it does not run, or it still runs?

**Comment by goanpeca** [comment]
@ccordoba12 have you seen this before?

**Comment by Thatguy1114** [comment]
@goanpeca I haven't. Hence why I threw it here.

**Comment by goanpeca** [comment]
@Thatguy1114 are you tying to run navigator locally or are you running it on a remote terminal via ssh ?

**Comment by Thatguy1114** [comment]
Locally. Anaconda navigator is run directly on my pc.

**Comment by ccordoba12** [comment]
@Thatguy1114, what happens after the error messages you posted appear? Does Navigator crash?

**Comment by Thatguy1114** [comment]
Nothing. Literally nothing.

**Comment by ccordoba12** [comment]
What about Spyder? Does Spyder open or does it show the same outcome?

**Comment by Thatguy1114** [comment]
Spyder works.

**Comment by ccordoba12** [comment]
That's really odd... I would expect both programs to fail.

**Comment by Thatguy1114** [comment]
Any other programs I need to test?

**Comment by ccordoba12** [comment]
You can also run in a terminal (cmd.exe)

    jupyter qtconsole

**Comment by Thatguy1114** [comment]
Works. Anything else?

**Comment by Thatguy1114** [comment]
Im switching to Kubuntu, so for right now, I would not worry about me for right now.

**Comment by colag** [comment]
Hello all, 

I don't know if  I have to tell that in this section. But I have exactly the same problem as Thatguy1114

In a fresh installation of Anaconda 5.1 For Linux Installer version x64, anaconda-console give me the same output of a list of errors. 

jupyter qtconsole works fine as jupyter notebook too.

Do I miss something during the installation ?? Because I think I followed strictly the indications given on the webpage https://docs.anaconda.com/anaconda/install/linux

Oups, I forgot..... i am using Ubuntu 17.10 

Any solution or do I have to live without anaconda-navigator environment ?

Best regards, 

Jean-Marc Colagrossi

**Comment by vhuang26** [comment]
Same problem as colag and Thatguy1114 

Anaconda works fine with Ubuntu 16.4

With a fresh install of Ubuntu 17.10 + Anaconda 

ubuntu:~$ anaconda-navigator
QXcbConnection: XCB error: 3 (BadWindow), sequence: 577, resource id: 33554436, major code: 10 (UnmapWindow), minor code: 0

**Comment by Thadaeus** [comment]
Have the same issue. 

Anaconda + Ubuntu 17.10 in a virtual machine 

same error message like @vhuang26

**Comment by Darthpbal** [comment]
I can't run glue or the anaconda navigator in 17.10

**Comment by pettersoderlund** [comment]
@vhuang26 @Thadaeus I had the same problem, running ubuntu 17.1 on virtual machine. fixed it with help from here: https://github.com/ContinuumIO/anaconda-issues/issues/1323

changed 'enable_high_dpi_scaling = True' to False in
~/.anaconda/navigator/anaconda-navigator.ini  fixed it for me.
