### ISSUE TITLE
psutils failure: "DLL load failed: The specified procedure could not be found"

### ISSUE THREAD

**Issue by benmwebb** [ContinuumIO/anaconda-issues#722]
On a 32-bit Windows XP system all package builds fail at the end with the following error:

        from . import _psutil_windows as cext
    ImportError: DLL load failed: The specified procedure could not be found

This is easy to reproduce by simply trying to "import psutil" from a Python session. I get the same error with psutil 4.0.0 and 4.1.0.

My assumption is that psutil is trying to use some post-XP syscall, and XP is no longer supported, although I don't see any minimum Windows version listed at https://www.continuum.io/downloads - what is the current minimum?

`conda info` reports:

    Current conda install:

                 platform : win-32
            conda version : 4.0.5
      conda-build version : 1.20.0
           python version : 2.7.11.final.0
         requests version : 2.9.1
         root environment : C:\Documents and Settings\IMP Developer\Miniconda2  (writable)
      default environment : C:\Documents and Settings\IMP Developer\Miniconda2
         envs directories : C:\Documents and Settings\IMP Developer\Miniconda2\envs
            package cache : C:\Documents and Settings\IMP Developer\Miniconda2\pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/win-32/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

**Comment by msarahan** [comment]
I don't know of anything that would prevent this from working.  With Python
2.7, you should not bump into issues with being too old.

Generally, you can learn more about why things could not be loaded using
dependency walker: http://www.dependencywalker.com/

Load the _psutil_windows.pyd or _psutil_windows.dll file and see what it
says it can't load.

HTH,
Michael

**Comment by benmwebb** [comment]
Dependency Walker complains with:

    Error: At least one module has an unresolved import due to a missing export function in an implicitly-dependent module.

I think it's complaining about `GetTickCount64` in `kernel32.dll`, which needs Vista or later. So my guess is you guys built the psutil package on a Vista or later system. I can certainly build my packages on a newer system too if that's the case.

**Comment by msarahan** [comment]
Yeah, we're building on Windows 10, with either the Windows 7 SDK or Windows 10 SDK (VS 2015 builds).  Python 2.7 should all be using Win7 SDK.

It's strange that this has not been an issue before, though.  Does psutil from Christoph Gohlke work?  http://www.lfd.uci.edu/~gohlke/pythonlibs/#psutil

**Comment by benmwebb** [comment]
I tried `psutil-4.1.0-cp27-cp27m-win32.whl` from that URL in combination with Anaconda's python (as above). That doesn't work either, same error. Not entirely surprising since that URL states
"**Many binaries are not compatible with Windows XP or Wine**". This is fine and I can easily build on a Win7 machine instead - I'm just surprised that there's no minimum version listed on the Anaconda website. (I'm sure somebody will try to use my own conda packages on an XP box and then complain to me that they don't work ;)

**Comment by msarahan** [comment]
Yeah, sorry.  We build with the Windows 7 SDK and Visual Studio 2008 SP1.
For most things, it isn't a problem, and Python 2.7 works fine on Windows
XP.  I guess psutil may use some more specific Windows APIs that are not
backwards compatible.

The difficulty with listing a minimum version is that each package in
Anaconda may have different compatibility.  We do have minimal
specifications here:
https://docs.continuum.io/anaconda/index#product-specifications but I agree
that they are not very visible, and also not even completely accurate,
since they say that everything in 2.7 will work with WinXP.  Can I close
this issue, or are you hoping for some other action?

**Comment by benmwebb** [comment]
Thanks - this is good enough for me.
