### ISSUE TITLE
Navigator Not Open Programs - spaces issue

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#7224]
Windows 8.1 64bit
Anaconda 5.0.1.0
conda 4.3.30
Python 3.6.3

I uninstalled my previous Anaconda version using Iobit Uninstaller.

I installed the above.

Navigator opens but the large icons such as Spyder on the opening page do not load the programs.
They start to try to open, with the blue progress bar showing at the page bottom, but the progress bar just ends with nothing loaded.

These programs do load correctly from the Windows Menu, or from the terminal within Navigator.

I was getting the exact same issue in my previous version which I uninstalled and was hoping the upgrade to latest would cure it.

**Comment by goanpeca** [comment]
@joesoap99 please open navigator from the anaconda prompt, and then try to launch spyder and see if there is any traceback in the Prompt.

**Comment by joesoap99** [comment]
Thank you

I ran Navigator from the prompt.

I tried Spyder, Notebook and Orange 3.
None of them loaded to completion from the Navigator main page .

There was no traceback at all after the prompt.

I also tried anaconda-navigator --reset. 
It confirmed resetting but made no difference to the problem.

**Comment by goanpeca** [comment]
could you type on the anaconda prompt the following and paste the results (as text)

```
$ conda info
$ conda list
```

**Comment by joesoap99** [comment]
conda list scrolls down to only show the packages after the letter M.
I can't see a way of scrolling page by page to supply the whole data


LIST


2w64—iibogg 1.3.2 3
2w64—1ibpng 1.6.21 2
2w64—iibsndfiie 1.0.26 2
ri2w64—libssh2 1.7.0 2
2w64—iibsystre 1.0.1 3
ri2w64—libtasnl 4.7 2
2w64—1ibtiff 4.0.6 2
2w64—1ibtre—git 122.c215d13 5
2w64—iibuorbis 1.3.5 2
ri2w64—libwinpthread—git 5.0.0.4634.6971757 2
2w64—1ibxni2 2.9.3 4
ri2w64—npfr 3.1.4 4
2w64—nett1e 3.1.1 4
2w64—nghttp2 1.9.2 2
2w64—openssi 1.0.2.9 2
2w64—p11—kit 0.23.2 2
2w64—pcre 8.38 2
ri2w64—rtnpdunp—git 499.alO7ceF 4
2w64—speex 1.2rc2 3
ri2w64—speexdsp 1.2rc3 3
2w64—tci 8.6.5 3
2w64—tk 8.6.5 3
ri2w64—tktabie 2.10 5
2w64—winedit1ine 2.101 5
2w64—xz 5.2.2 2
2w64—z1ib 1.2.8 10
riarkupsaf e 1.0 py36h0e269?1.J.
riatplotlib 2.1.0 py36hllb4b9c_0
riccabe 0.6.1 py36hb4lOOSaJ.
enuinst 1.4.10 py36h42196fb_0
dstune 0.7.4 py36h4874169_0
riki 2018.0.0 h36b65af_4
dci—service 1.1.2 py36hS?e144c_4
ripnath 0.19 py36he3268022
risgpack—python 0.4.8 py36hSOble9d_0
sys2—conda—epoch 20160418 1
riultipledispatch 0.4.9 py36he44c36e_0
auigator—updater 0.1.0 py36h8a7b86b_0
thconuert 5.3.1 py36h8dcøfde_0
bfornat 4.4.0 py36h3a5bclb_0
etworkx 2.0 py36hff99le3_0
ìltk 3.2.4 py36hdOeOa39_0
ose 1.3.7 py36h1c3779e2
ìotebook 5.2.1 py36h4fb2ca6_0
unba 0.35.0 npll3py36JO
ìunexpr 2.6.2 py36h7ca04dcj.
unpy 1.13.3 py36ha320f96_0
ìunpydoc 0.7.0 py36ha25429e_0
)dO 0.5.1 py36h75602?9_0
defile 0.44 py36h0a7bdd2_0
)penpyxl 2.4.8 p936hf3b7?f6.J.
)penssl 1.0.2n ucl4h7f3Sf9e_0 [oct41
)range3 3.4.1 py360
ackaging 16.8 py36ha0986f6J.
,andas 0.21.0 py36heø9d4ddzt
andoc 1.19.2.1 hh2460c7J
andocf liters 1.4.2 py36h3ef6317z1.
artd 0.3.8 py36hc8e763b_0
ath.py 10.3.1 py36h3dd8b46_0
athlib2 2.3.0 py36h7bfb78b_0
atsy 0.4.1 py36h42cefec_0
ep8 1.7.0 py36hOf3d67a_0
dckieshare 0.7.4 py36h9deO3Of_0
ñllow 4.2.1 py36hdb25ab2_0
ip 9.0.1 py36hadba8?b_3
Æginf o 1.4.1 py36hbøf9cfai.
dy 3.10 py36hl2llbeb_0
n’ogress 1.3 py36hbeca8d3_0
ronpt_toolkit 1.0.15 py36h60b8f86_0
sutil 5.4.0 py36h4e662fb_0
1.4.34 py36ha4aca3aj.
ycodestyle 2.3.1 py36h7cc55cd_0
ycosat 0.6.2 py36hfl7S46dzt
ycparser 2.18 py36hd053e01J.
ycrypto 2.6.1 py36he68e6e2J.
ycurl 7.43.0 py36hOB6bf4c_3
,yf lakes 1.6.0 py36h0b975d6_0
ygnents 2.2.0 py36hh010967_0
ylint 1.7.4 py36ha4e6ded_0
yodbc 4.0.17 py36h0006bc2_0
yopengl 3.1.lal nptl3py36_0
yopenssl 17.2.0 py36hl5ca2fc_0
)ouarsincf 2.2.0 nu36h785a196z1.2w64—iibogg 1.3.2 3
2w64—1ibpng 1.6.21 2
2w64—iibsndfiie 1.0.26 2
ri2w64—libssh2 1.7.0 2
2w64—iibsystre 1.0.1 3
ri2w64—libtasnl 4.7 2
2w64—1ibtiff 4.0.6 2
2w64—1ibtre—git 122.c215d13 5
2w64—iibuorbis 1.3.5 2
ri2w64—libwinpthread—git 5.0.0.4634.6971757 2
2w64—1ibxni2 2.9.3 4
ri2w64—npfr 3.1.4 4
2w64—nett1e 3.1.1 4
2w64—nghttp2 1.9.2 2
2w64—openssi 1.0.2.9 2
2w64—p11—kit 0.23.2 2
2w64—pcre 8.38 2
ri2w64—rtnpdunp—git 499.alO7ceF 4
2w64—speex 1.2rc2 3
ri2w64—speexdsp 1.2rc3 3
2w64—tci 8.6.5 3
2w64—tk 8.6.5 3
ri2w64—tktabie 2.10 5
2w64—winedit1ine 2.101 5
2w64—xz 5.2.2 2
2w64—z1ib 1.2.8 10
riarkupsaf e 1.0 py36h0e269?1.J.
riatplotlib 2.1.0 py36hllb4b9c_0
riccabe 0.6.1 py36hb4lOOSaJ.
enuinst 1.4.10 py36h42196fb_0
dstune 0.7.4 py36h4874169_0
riki 2018.0.0 h36b65af_4
dci—service 1.1.2 py36hS?e144c_4
ripnath 0.19 py36he3268022
risgpack—python 0.4.8 py36hSOble9d_0
sys2—conda—epoch 20160418 1
riultipledispatch 0.4.9 py36he44c36e_0
auigator—updater 0.1.0 py36h8a7b86b_0
thconuert 5.3.1 py36h8dcøfde_0
bfornat 4.4.0 py36h3a5bclb_0
etworkx 2.0 py36hff99le3_0
ìltk 3.2.4 py36hdOeOa39_0
ose 1.3.7 py36h1c3779e2
ìotebook 5.2.1 py36h4fb2ca6_0
unba 0.35.0 npll3py36JO
ìunexpr 2.6.2 py36h7ca04dcj.
unpy 1.13.3 py36ha320f96_0
ìunpydoc 0.7.0 py36ha25429e_0
)dO 0.5.1 py36h75602?9_0
defile 0.44 py36h0a7bdd2_0
)penpyxl 2.4.8 p936hf3b7?f6.J.
)penssl 1.0.2n ucl4h7f3Sf9e_0 [oct41
)range3 3.4.1 py360
ackaging 16.8 py36ha0986f6J.
,andas 0.21.0 py36heø9d4ddzt
andoc 1.19.2.1 hh2460c7J
andocf liters 1.4.2 py36h3ef6317z1.
artd 0.3.8 py36hc8e763b_0
ath.py 10.3.1 py36h3dd8b46_0
athlib2 2.3.0 py36h7bfb78b_0
atsy 0.4.1 py36h42cefec_0
ep8 1.7.0 py36hOf3d67a_0
dckieshare 0.7.4 py36h9deO3Of_0
ñllow 4.2.1 py36hdb25ab2_0
ip 9.0.1 py36hadba8?b_3
Æginf o 1.4.1 py36hbøf9cfai.
dy 3.10 py36hl2llbeb_0
n’ogress 1.3 py36hbeca8d3_0
ronpt_toolkit 1.0.15 py36h60b8f86_0
sutil 5.4.0 py36h4e662fb_0
1.4.34 py36ha4aca3aj.
ycodestyle 2.3.1 py36h7cc55cd_0
ycosat 0.6.2 py36hfl7S46dzt
ycparser 2.18 py36hd053e01J.
ycrypto 2.6.1 py36he68e6e2J.
ycurl 7.43.0 py36hOB6bf4c_3
,yf lakes 1.6.0 py36h0b975d6_0
ygnents 2.2.0 py36hh010967_0
ylint 1.7.4 py36ha4e6ded_0
yodbc 4.0.17 py36h0006bc2_0
yopengl 3.1.lal nptl3py36_0
yopenssl 17.2.0 py36hl5ca2fc_0
)ouarsincf 2.2.0 nu36h785a196z1.


(C:\AP36) C:\Users\**** ***>conda info
Durrent conda install:
platf orn : vin—64
conda version : 4.3.3Ø
conda is private : False
conda—enu version : 4.3.3Ø
conda—huild version : 3.0.27
python version : 3.6.3.final.0
requests version : 2.18.4
root environnent : C:\AP36 <writable)
default environnent : C:\AP36
envs directories : C:\AP36\envs
C:\Users\Robert Ford\AppData\Local\conda\conda\envs
C:\Users\Robert Ford\.conda\envs
package cache : C:\AP36\pkgs
C:\Users\Robert Ford\AppData\Local\conda\conda\pkgs
channel URLs : https://conda.anaconda.org/anaconda—fusion/win—64
https : //conda . anaconda. org/anaconda—f us ion/noarch
https ://repo .continuun. io/pkgs/nain/win—64
https ://repo .continuun. io/pkgs/nain/noarch
https ://repo .continuun. io/pkgs/free/win—64
https ://repo .continuun. io/pkgs/free/noarch
https ://repo .continuun. io/pkgs/r/win—64
https ://repo .continuun. io/pkgs/r/noarch
https ://repo .continuun. io/pkgs/pro/win—64
https ://repo .continuun. io/pkgs/pro/noarch
https ://repo .continuun. io/pkgs/nsys2/win—64
https ://repo .continuun. io/pkgs/nsys2/noarch
config file : C:\Users\Robert Ford\.condarc
netrc file : None
offline node : False
user—agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/S.l
?Iindows/6 .3.9600
adninistrator : True
(C:\AP36) C:\Users\**** ***>

**Comment by goanpeca** [comment]
@joesoap99 we do not support spaces in paths as some libraries might experience odd behaviour or errors.

`C:\Users\Robert Ford\` I recommend you reinstall for current user only but select a location without spaces.

**Comment by joesoap99** [comment]
I did install to a destination folder of C:\AP36 which has no spaces.
I changed from the default which had spaces.

Anaconda puts stuff in my Users folder without my control. Listed in conda info above

I uninstalled and reinstalled but the problem remains.

**Comment by mingwandroid** [comment]
@goanpeca, correct me if I'm wrong, but Navigator runs via `pythonw.exe` so nothing would be output on the prompt?

@joesoap99, can you try this instead (again from the `Anaconda Prompt`):

```
python C:\AP36\Scripts\anaconda-navigator-script.py
```

.. and see if there is any console output when you try to launch those programs from Navigator?

**Comment by goanpeca** [comment]
>correct me if I'm wrong, but Navigator runs via pythonw.exe so nothing would be output on the prompt?

I am not sure @mingwandroid

**Comment by goanpeca** [comment]
@mingwandroid how do we reconcile the fact that even if anaconda is installed in a non-spaces path, conda and other programs will still use the User folder to store config.

**Comment by mingwandroid** [comment]
Most things are perfectly fine in paths with spaces. Windows programs have a long heritage of working in paths with spaces (Program Files). Even now, we only recommend against it on Windows, we do not prohibit it (AD 5.0.0 did prohibit it at the last minute due to a problem in menuinst, but we fixed this bug and allowed it again for 5.0.1).

**Comment by goanpeca** [comment]
>fixed this bug and allowed it again for 5.0.1

I was not aware of this :-|

**Comment by joesoap99** [comment]
Hi,

I ran command below but no console output at all.

( Please note all the programs run fine from Anaconda on the Windows Menu or if I run from the terminal within Navigator. The only problem is that the programs do not run from the icons on the Navigator main page - it is this part which seems unable to find the programs.)

"@joesoap99, can you try this instead (again from the Anaconda Prompt):

python C:\AP36\Scripts\anaconda-navigator-script.py

.. and see if there is any console output when you try to launch those programs from Navigator?

**Comment by goanpeca** [comment]
@joesoap99 could you look for a file in this location and paste the content?


`C:\Users\Robert Ford\.anaconda\scripts\spyder.bat` ?

**Comment by joesoap99** [comment]
spyder,bat:

chcp 1252
call C:\AP36\Scripts\activate C:\AP36
C:\AP36\Scripts\spyder >C:\Users\Robert Ford\.anaconda\navigator\scripts\spyder-out-1.txt 2>C:\Users\Robert Ford\.anaconda\navigator\scripts\spyder-err-1.txt

**Comment by goanpeca** [comment]
Wait I just realized the problem, the output of the logs is not in quotes and it should be.

Working on a fix now!

**Comment by joesoap99** [comment]
Ran spyder.bat with error messages:

There seems a strange mixture of 'Robert', 'Ford' and 'Robert Ford'

![image](https://user-images.githubusercontent.com/8518350/32667290-33e3f340-c632-11e7-9621-f88753cb9c11.png)

C:\Users\Robert Ford\.anaconda\navigator\scripts>spyder.bat
C:\Users\Robert Ford\.anaconda\navigator\scripts>chcp 1252
Active code page: 1252
:\Users\Robert Ford\.anaconda\navigator\scripts>call C:\AP36\Scripts\activate C
:\AP36
(C:\AP36) C:\Users\Robert Ford\.anaconda\navigator\scripts>C:\AP36\Scripts\spyder
  Ford\.anaconda\navigator\scripts\spyder—out—1 .txt  Ford\.anaconda\navigator\
sripts\spyder—err—1.txt 1>C:\Users\Robert 2>C:\Users\Robert
The process cannot access the file because it is being used by another process.
(C:\AP36) C:\Users\Robert Ford\.anaconda\navigator\scripts>

**Comment by goanpeca** [comment]
@joesoap99 its the lack of quotes on the path to the log files. Have a fix on the works for this

**Comment by maheshmurthi** [comment]
I've been getting this issue and have been searching for solutions before I logged a new issue ( 99% of the times other people have found such issues ) and was happy to follow this thread.   Have been tracking this issue and am looking for a tentative release date where this will come.

Any ideas when this will be released ?

**Comment by goanpeca** [comment]
@maheshmurthi this coming week!

**Comment by maheshmurthi** [comment]
Fantastic !!

**Comment by technic** [comment]
Hi. The jupyter notebook launcher (the one that gets installed in windows StartMenu) also has similar issue. There is unquoted %USERPROFILE% variable in the command line. I edited it manually and fixed the problem.

**Comment by maheshmurthi** [comment]
@goanpeca - Looks like release is pending for quite a while

**Comment by goanpeca** [comment]
There is a release available, please update to the latest
