### ISSUE TITLE
deactivating or reactivating gcc_linux-64 causes an error to be printed if the current shell uses noclobber

### ISSUE THREAD

**Issue by anntzer** [ContinuumIO/anaconda-issues#7227]
The activation and deactivation scripts for gcc_linux-64 (and gxx_linux-64) on the anaconda channel contain lines of the form `env > /tmp/new-env-$$.txt` (to save the state of environment variables).
This fails if the file already exists (e.g., at deactivation, or later reactivating (after the deactivation) from within the same shell) if the current shell has the noclobber option set (https://en.wikipedia.org/wiki/Clobbering).
I believe a safer approach would be to store the set of environment variables in, well, another environment variable (e .g. $_CONDA_OLD_ENV_PID).

**Comment by msarahan** [comment]
The code for these is at https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-activation-feedstock/recipe

Please submit a PR if you have time.

**Comment by anntzer** [comment]
I don't mind reopening the issue there if that helps...
Also, right now the shebang #!/bin/bash at the top of the file is quite misleading, the script gets eval'd using whatever shell the user is currently using, not necessarily #!/bin/bash.

**Comment by mingwandroid** [comment]
`conda` supports only `bash` or `zsh` on Unix. `conda`'s activate script errors out if you are not using one of these two shells. If you are not using `conda`'s activate script then you are not activating `conda` properly, therefore, when used properly, the shell the user is currently using can only be `bash` or `zsh`.

We will remove `/tmp/new-env-$$.txt` if it exists before we write to it though.

**Comment by anntzer** [comment]
This is actually using zsh *and* using conda's activate script.
The point is that you cannot expect the user's shell to have noclobber *not* active.

**Comment by mingwandroid** [comment]
> The point is that you cannot expect the user's shell to have noclobber not active.

As I already said:

> We will remove /tmp/new-env-$$.txt if it exists before we write to it though.

**Comment by anntzer** [comment]
thanks.
