### ISSUE TITLE
Updating Package Removed Conda Files

### ISSUE THREAD

**Issue by jaredleekatzman** [ContinuumIO/anaconda-issues#727]
I tried to update a python package using the cuda program.

I ran `cuda update matplotlib` and an error occurred where I did not have sufficient permissions to edit a conda confgiruation file. 

Afterward, I tried to run conda again using `sudo conda update matplotlib`, but then the error showed:
`sudo: conda: command not found`

I tried using the Anaconda Launcher and received the error message
"Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)"

To add more craziness to this issue, I also no longer was able to execute the `pip` command.

**Comment by csoja** [comment]
This type of behavior should be fixed in the latest releases of conda.  Closing this issue.
