### ISSUE TITLE
About navigator not launching any tool inside of it

### ISSUE THREAD

**Issue by Anylee2142** [ContinuumIO/anaconda-issues#7276]
I have installed Anaconda3-5.0.1-Windows version.

But navigator doesn't launch any tool inside of it.

Cause is as specifed here, there should be NO SPACE within installation path

But also, the enviornment variables that conda uses is located at Users/ACCOUNT_NAME.
( you can find out this with 'conda info' from Anaconda prompt)

Not only installation path but also ACCOUNT USER NAME should have NO SPACE.

I tried to rename my window account but it's highly risky so i quitted.

Good thing is that everything except navigator works fine.

I hope space problem with installation path and window account name to be fixed in future release.

Thanks for reading.

**Comment by goanpeca** [comment]
@Anylee2142 yes, we are fixing this problem and will be available in the next minor release

**Comment by goanpeca** [comment]
Tracking on https://github.com/ContinuumIO/anaconda-issues/issues/7276
