### ISSUE TITLE
No any response from Conda...and Anaconda Navigator can't be opened...

### ISSUE THREAD

**Issue by cclin0828** [ContinuumIO/anaconda-issues#7287]
I dont know why...
No matter what I type in CMD, the conda sleeps deeply :
> C:\Users\Jim Lin>conda list
> C:\Users\Jim_Lin>conda search numpy
> C:\Users\JimLin>conda update conda

above is a demo of my CMD using, so that we can sure that 'conda' is could be recognized but no any response.
And as I try to open anaconda..., same, no any response...
Anyone can help me?

**Comment by goanpeca** [comment]
@cclin0828 did you open the normal prompt  or the Anaconda Promt?

**Comment by cclin0828** [comment]
@goanpeca thx for ur reply, at that time, I have tried normal prompt and Anaconda Prompt.
Same, no any responses from 'conda'.
I have uninstalled and reinstalled, now, it works well.
Thx for ur reply again. :)

**Comment by goanpeca** [comment]
@cclin0828 glad to hear is working again :-)
