### ISSUE TITLE
Anaconda 5.0.1 not opening in Mac OS 10.8.5

### ISSUE THREAD

**Issue by sridhar3525** [ContinuumIO/anaconda-issues#7308]
Just installed "Anaconda2-5.0.1-MacOSX-x86_64" package in Mac and tried to start anaconda-navigator from Launchpad, but the icon flashes in main taskbar but vanishes within seconds. 

Since I installed in Graphical way and not in command line terminal, I got the following error $Command not found for the commands: anaconda-navigator, conda etc

When I tried the command "open -a anaconda-navigator", I am getting the below error
LSOpenURLsWithRole() failed for the application /Users/admin/anaconda2/Anaconda-Navigator.app with error -10810.

**Comment by mingwandroid** [comment]
We do not support macOS 10.8 anymore. 10.9 is the minimum now.

**Comment by csoja** [comment]
In case you cannot update your macOS to 10.9 or newer - an older Anaconda installer may meet your needs: https://docs.anaconda.com/anaconda/faq#how-can-i-use-anaconda-on-older-macintosh-systems
