### ISSUE TITLE
Virtualenv PATH not fully set with ZSH on Windows

### ISSUE THREAD

**Issue by javidcf** [ContinuumIO/anaconda-issues#7313]
I am using virutalenvs in Anaconda 3 on Windows 10 with MSYS2. Things work fine with `cmd` and `bash`, I get all these new entries in `PATH`:
```
C:\Users\me\AppData\Local\Continuum\anaconda3\envs\myenv
C:\Users\me\AppData\Local\Continuum\anaconda3\envs\myenv\Library\mingw-w64\bin
C:\Users\me\AppData\Local\Continuum\anaconda3\envs\myenv\Library\usr\bin
C:\Users\me\AppData\Local\Continuum\anaconda3\envs\myenv\Library\bin
C:\Users\me\AppData\Local\Continuum\anaconda3\envs\myenv\Scripts
```

But for some reason when I activate the environment in `zsh` it only gets partially set up, and I get something like:

```
/home/me/AppData/Local/Continuum/anaconda3/envs/myenv
/home/me/AppData/Local/Continuum/anaconda3/envs/myenv/Library/mingw-w64
/home/me/AppData/Local/Continuum/anacond
```

That's not a typo, I do get a broken path. Each time it gets to a different character, but it seems as if the activation process somehow crashed in the middle (though I cannot see why or how). I generally use oh-my-zsh, but I have tried disabling it and I get the same.

**Comment by kalefranz** [comment]
Please `conda update conda`.  If you continue to have problems, file a new issue at https://github.com/conda/conda.
