### ISSUE TITLE
Remove old Python debug builds from https://repo.continuum.io/pkgs/free

### ISSUE THREAD

**Issue by mbargull** [ContinuumIO/anaconda-issues#7314]
There are some old Python debug builds in https://repo.continuum.io/pkgs/free which require a feature `debug`. Those trigger a bug in Conda, see: https://github.com/conda/conda/issues/6269#issuecomment-344077631.
I'm not sure how long it may take to land a fix for this in `conda`, so I'd like to ask you to remove those builds from the repository. Since they do not define their dependency on `debug`, they are somewhat broken  anyway:
```
(ins)(root) [miniconda3]$  conda create --dry-run -n x python=2.7.9=d1
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7.9 d1
Use "conda info <package>" to see the dependencies for each package.
```

Here is the list of those problematic builds:
```
https://repo.continuum.io/pkgs/free/linux-32:
    python: 2.7.9-d1    [debug]
    python: 2.7.9-d2    [debug]
    python: 2.7.10-d0   [debug]
    python: 2.7.11-d0   [debug]
```
```
https://repo.continuum.io/pkgs/free/linux-64:
    python: 2.7.9-d1    [debug]
    python: 2.7.9-d2    [debug]
    python: 2.7.10-d0   [debug]
    python: 2.7.11-d0   [debug]
```
```
https://repo.continuum.io/pkgs/free/osx-64:
    python: 2.7.9-d1    [debug]
    python: 2.7.10-d0   [debug]
    python: 2.7.11-d0   [debug]
```

**Comment by csoja** [comment]
These debug packages can be moved to the archive channel: https://repo.continuum.io/pkgs/archive/

**Comment by mbargull** [comment]
Shouldn't be a problem anymore with `conda >=4.3.33,<4.4.0a0|>=4.4.8`.
