### ISSUE TITLE
anaconda-navigator Segmentation fault

### ISSUE THREAD

**Issue by RunningDongxu** [ContinuumIO/anaconda-issues#7322]
dongxu@dongxu-Alienware-15-R3:~$ anaconda-navigator
Segmentation fault
dongxu@dongxu-Alienware-15-R3:~$ conda update conda
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/dongxu/anaconda3:
#
conda                     4.3.30           py36h5d9f9f4_0  
dongxu@dongxu-Alienware-15-R3:~$ conda update anaconda-navigator
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/dongxu/anaconda3:
#
anaconda-navigator        1.6.9            py36h11ddaaa_0

**Comment by PushyamiKaveti** [comment]
I had the same issue. I solved it by adding /lib to my LD_LIBRARY_PATH variable.
Note: on my system anaconda installation is at /home/pushyamik/anaconda3

@RunningDongxu ... let me know if this works?

**Comment by RunningDongxu** [comment]
@PushyamiKaveti  Still not works

**Comment by CommonClimate** [comment]
any updates on this? I am having the same issue. Also getting a seg fault while trying to launch Spyder. 
/Users/me/anaconda3/bin/pythonw: line 3: 90006 Segmentation fault: 11  /Users/me/anaconda3/python.app/Contents/MacOS/python "$@"

This has never happened before, and I cannot recall doing any update to conda or the OS between the last time it worked (Dec 29) and today.

**Comment by goanpeca** [comment]
Not sure what is causing this issue. @mingwandroid thoughts?

**Comment by mingwandroid** [comment]
There's no much to go on here. You need to use some debugging techniques to get more info. Some ideas:

1. Install to /tmp, run dtruss -f
2. Try setting DYLD_PRINT_LIBRARIES=1
3. Run through lldb and get a backtrace

**Comment by CommonClimate** [comment]
I solved the problem via brute force by uninstalling and re-installing anaconda. Not very subtle, but it worked.

**Comment by goanpeca** [comment]
Glad to hear it solve your problem @CommonClimate

**Comment by scordee** [comment]
Still get a seg fault on Ubuntu 14.04. I tried uninstalling and reinstalling. Also added /lib to the LD_LIBRARY_PATH. Will see what I can do to solve the issue.
