### ISSUE TITLE
Miniconda3 4.3.30 "python" and "conda" versions inconsistency

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#7323]
_From @FeodorFitsner on November 14, 2017 19:42_

Installing Miniconda3 4.3.30 on Windows (both [x64](https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Windows-x86_64.exe) and [x86](https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Windows-x86.exe)) and running `conda --version` yields wrong version information:

    conda 4.3.27

Shouldn't it be `conda 4.3.30`?

Also, target python version is also different in x64 and x86 packages.

x64: `Python 3.6.3 :: Anaconda, Inc.`
x86: `Python 3.6.2 :: Anaconda, Inc.`

Presumably both should target 3.6.3, right?

Could you please clarify?

_Copied from original issue: conda/conda#6306_

**Comment by kalefranz** [comment]
I've verified the report is accurate, at least for https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Windows-x86.exe

Thanks for the report @FeodorFitsner

**Comment by mingwandroid** [comment]
Fixed.

**Comment by FeodorFitsner** [comment]
Thank you!

**Comment by mingwandroid** [comment]
It's fixed in version 4.30.0.2 btw (or use the -latest ones instead).
