### ISSUE TITLE
Launching Error

### ISSUE THREAD

**Issue by keggin** [ContinuumIO/anaconda-issues#7353]
Whenever I try and launch the application I get this error:

> Traceback (most recent call last):
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 313, in catch_zombie
> yield
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
> return cext.proc_cmdline(self.pid)
> ProcessLookupError: [Errno 3] No such process
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
> return_value = func(*args, **kwargs)
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
> if misc.load_pid() is None: # A stale lock might be around
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
> cmds = process.cmdline()
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 721, in cmdline
> return self._proc.cmdline()
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 295, in wrapper
> return fun(self, *args, **kwargs)
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
> return cext.proc_cmdline(self.pid)
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
> self.gen.throw(type, value, traceback)
> File "/Users/keeganbyrnes/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 326, in catch_zombie
> raise AccessDenied(proc.pid, proc._name)
> psutil.AccessDenied: psutil.AccessDenied (pid=864)
> 

I've tried updating and re-installing several times with no luck.

**Comment by goanpeca** [comment]
Please run 

```
$ anaconda-navigator --reset
```
