### ISSUE TITLE
Standard library missing db.ndbm and db.gnu

### ISSUE THREAD

**Issue by kpalin** [ContinuumIO/anaconda-issues#7356]
python3.6 is missing **standard library** components db.ndbm and db.gnu. Similar to very old, ongoing, issue [#126] 

```
(py3) $ python -c 'import dbm.ndbm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kpalin/miniconda2/envs/py3/lib/python3.6/dbm/ndbm.py", line 3, in <module>
    from _dbm import *
ModuleNotFoundError: No module named '_dbm'
(py3) $ python -c 'import dbm.gnu'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kpalin/miniconda2/envs/py3/lib/python3.6/dbm/gnu.py", line 3, in <module>
    from _gdbm import *
ModuleNotFoundError: No module named '_gdbm'
```

**Comment by mingwandroid** [comment]
Why have you made **standard library** bold like that? The module you are talking about is the `dbm` module, `_gdbm` and `_dbm` are two *optional* accelerated backends for the `dbm` module which we *do* provide.

`_gdbm` is `GPL` and our aim is for our Python build to not use any `GPL` components eventually. This precludes using `_gdbm` and AFAIK `_dbm` is an Oracle thing that you need to pay for.

[From](https://docs.python.org/3/library/dbm.html):

> dbm is a generic interface to variants of the DBM database — dbm.gnu or dbm.ndbm. If none of these modules is installed, the slow-but-simple implementation in module dbm.dumb will be used. There is a third party interface to the Oracle Berkeley DB.

**Comment by r-barnes** [comment]
The lack of `_gdbm` means the standard library's `shelve` doesn't work between anaconda and non-anaconda Pythons.
