### ISSUE TITLE
Kernel keeps dying, restarting after I try .fit() in LinearRegression()

### ISSUE THREAD

**Issue by AnastasisB** [ContinuumIO/anaconda-issues#7358]
I've been struggling with this problem the past week. I've tried everything that I've found online but the problem persists.

```

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Some_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values

from sklearn.model_selection import train_test_split
X_tr, X_test, y_tr, y_test = train_test_split(X,y, test_size = 1/3, random_state = 0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_tr, y_tr)

```

Whenever I run the last line of the code above Kernel dies and then restarts. The first time I run it I also get an error (you can see it in the image below), but after that, whenever I run the code it's just the kernel problem.

![untitled](https://user-images.githubusercontent.com/33597467/32948933-a2c2d534-cba9-11e7-861b-5a74a4abc95d.jpg)
I've tried the following:

`conda update --all`
`conda update conda`
`conda update anaconda`

(checking each time if the problem persists)

Things I've tried:

- I've uninstalled my antivirus and turned off windows firewall.
- I've tried installing Windows6.1-KB2999226-x64.msu update as suggested in a thread.
- I've uninstalled and reinstalled Anaconda3 in various folders (C:\Users\Me\Anaconda3, C:\Anaconda3, D:\Anaconda3)
- In the installation process I checked "Just Me" and checked all the boxes as it was recommended.

I've installed Anaconda3 4.2.0 x64 because I'm currently following an online course. The problem persists even if I install the latest version (as found online).

I'm using

64bit Windows 7
Intel Core i5 CPU
8GB RAM
AMD Graphics
Python 3.5.4
Conda 4.3.30
Anaconda Navigator 1.6.8
Spyder 3.2.3

```
Dependencies:

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by sanjmeetabrol** [comment]
Hi!
I was facing the same issue and it got resolved by installing nomkl.
try:
conda install nomkl

For further details: https://stackoverflow.com/questions/39720911/sgdclassifier-kernel-dies-when-using-scikit

Hope this helps!

**Comment by AnastasisB** [comment]
I think this works only on mac and linux. On windows this package doesn't exist.

**Comment by msarahan** [comment]
It seems like you might have an older mkl lying around that is causing you headaches.  This is affectionately called DLL hell.  The most common way this happens is that other programs install DLLs into C:\Windows\System32, which has higher priority in the search scheme (https://msdn.microsoft.com/en-us/library/7d83bc18.aspx) than the PATH environment variable, which conda depends on.

If this is the problem, you need to identify which other MKL DLLs might be getting loaded, and move them somewhere less global that won't interfere with Anaconda.  If you manage to figure out who put those MKL DLLs there, you should complain to them, because it's nasty.

**Comment by AnastasisB** [comment]
@msarahan 

Can you help me with this ? I can't understand how I decide if a DLL is affecting conda.

**User PATH:**
D:\Anaconda3;D:\Anaconda3\Scripts;D:\Anaconda3\Library\bin;%CDSROOT%\OpenAccess\bin\win32\opt;%CDSROOT%\tools\Capture;%CDSROOT%\tools\PSpice\Library;%CDSROOT%\tools\PSpice;%CDSROOT%\tools\specctra\bin;%CDSROOT%\tools\fet\bin;%CDSROOT%\tools\libutil\bin;%CDSROOT%\tools\bin;%CDSROOT%\tools\pcb\bin;C:\Program Files (x86)\OpenVPN\bin;C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin


**System PATH:**
%INTEL_DEV_REDIST%redist\ia32\compiler;%INTEL_DEV_REDIST%redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\MATLAB\R2014a\runtime\win64;C:\Program Files\MATLAB\R2014a\bin;C:\Program Files\MATLAB\R2014a\polyspace\bin;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;

**Comment by AnastasisB** [comment]
I uninstalled Amplitube 4 and everything works like a charm now. Don't know what was going on though ...

**Comment by braintucker** [comment]
I had the same exact error and Amplitube4 installed on my computer as well, I uninstalled and the error went away. Very strange but seems as Amplitube4 has the DLLs
