### ISSUE TITLE
AD5 scripts in /etc/conda confuse non-interactive SSH

### ISSUE THREAD

**Issue by crusaderky** [ContinuumIO/anaconda-issues#7372]
I've installed on my Linux server gcc_linux-64, gxx_linux-64, and binutils_linux-64 and I have put in my ~/.bashrc ``/path/to/my/conda/bin/activate root``.
Now when I try connecting to the server with git using the ssh:// protocol, I am getting the error message

```
fatal: protocol error: bad line length character: INFO
```

I did not test scp and similar applications but I do expect similar problems.

The workaround was to hack into ``etc/conda/*activate.d/*.sh`` and remove the lines that dump the variables to the terminal at the end of every script.
IMHO a cleaner approach would be not to print anything, and to accept a ``-v/--verbose`` switch in the bin/activate script to re-enable printing out the variables.

**Comment by nehaljwani** [comment]
Not sure, but maybe we could restrict the echo only to a valid tty? https://stackoverflow.com/a/12442753/1005215

**Comment by mingwandroid** [comment]
The compilers only echo this info when `CONDA_BUILD` is set to `1`.
