### ISSUE TITLE
CondaHTTPError: HTTP 502 BAD GATEWAY  when doing conda install

### ISSUE THREAD

**Issue by u932b** [ContinuumIO/anaconda-issues#7406]
I am running into the following problem
Fetching package metadata .....
CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://repo.continuum.io/pkgs/main/linux-64/repodata.json.bz2>
Elapsed: 00:01.751717
CF-RAY: 3c0efea2eeaa4632-TPE
Is the server down?

**Comment by u932b** [comment]
curl -l  https://repo.continuum.io/pkgs/main/linux-64/repodata.json.bz2
works on remote machine, seems to be a local problem

**Comment by plammens** [comment]
Were you able to fix it?

**Comment by mike-seekwell** [comment]
`curl -l https://repo.continuum.io/pkgs/main/linux-64/repodata.json.bz2` is not working right now, server must be down
