### ISSUE TITLE
Update PyTorch Package - PyTorch 0.3.1 + CUDA Toolkit 8.0 + CUDNN 6.x

### ISSUE THREAD

**Issue by RoyiAvital** [ContinuumIO/anaconda-issues#7410]
Hello,

Could you update the PyTorch Package on the official Anaconda Channel?
It should be updated to PyTorch 0.2 + CUDA Toolkit 8.0 + CUDNN 6.x.

Thank You.

**Comment by RoyiAvital** [comment]
@jjhelmus , I go to Anaconda Navigator.
Under Environments I do a search for PyTorch.
I can see PyTorch is upgraded to `0.2.0`.
Yet PyTorch-GPU is still `0.2.0`.

Will it be updated?

Thank You.

**Comment by jjhelmus** [comment]
The `pytorch-gpu` package is not needed, `pytorch` support both GPU and CPU modes.  You should remove `pytorch-gpu` if you have it installed.

**Comment by RoyiAvital** [comment]
OK,
I switched from PyTorch-GPU package to PyTorch.
It seems the defaults are `cudatoolkit=8 cudnn=6`.

I will update them manually.

Great service!

Thank You.

**Comment by RoyiAvital** [comment]
@jjhelmus ,

@PyTorch released version 0.3.0 today.
Could the package be updated?

Thank You.

**Comment by jjhelmus** [comment]
I'll look into getting PyTorch 0.3.0 packages out soon.  The team is quite busy at the moment so I cannot make any promises on a timeline.

**Comment by jjhelmus** [comment]
PyTorch 0.3.0 packages are now available on `defaults` for CUDA 7.5 and 8.0 with CuDNN 6.  Packages using CUDA 8 + CuDNN 7 should be available later this week or early next week.

**Comment by RoyiAvital** [comment]
@jjhelmus ,

This is great!
Let us know when CUDA 8 + CuDNN 7 are available.

**Comment by jjhelmus** [comment]
PyTorch 0.3.0 packages build for CUDA 8 + CuDNN 7 are now available in `defaults`

**Comment by RoyiAvital** [comment]
@jjhelmus ,
Lovely.
How could one, using Anaconda Navigator could chose to install PyTorch 0.3 + CUDA 8 + CuDNN 7?

Thank You.

**Comment by jjhelmus** [comment]
@RoyiAvital I'm not a big Anaconda Navigator user, but I believe the workflow would be:  

* Go to the environments tab
* Change the drop down to "Not installed", click "Update Index..." and then type in pytorch
* Check the box next to pytorch
* Click Apply

This will only work on 64-bit Linux, we do not build PyTorch on other platforms.  If you prefer to install pytorch via the command line the command would be `conda install pytorch=0.3 cudatoolkit=8 cudnn=7`.

**Comment by RoyiAvital** [comment]
I know that.
The issue is I installed 0.3 last week which was with CuDNN 6.  
As far as I can tell in Navigator one can not chose which CuDNN to use with PyTorch.

Thank You.

**Comment by mingwandroid** [comment]
Must use them commandline. Navigator doesn't have such complex installation capabilities AFAIK.

**Comment by RoyiAvital** [comment]
What would be the command line to re download the PyTorch 0.3 now with CuDNN 7?

**Comment by mingwandroid** [comment]
@jjhelmus already answered that 3 hours ago. https://github.com/ContinuumIO/anaconda-issues/issues/7410#issuecomment-352263532

**Comment by RoyiAvital** [comment]
Hello,

PyTorch 0.3.1 is out.
Could you please update?

Also please note which are the defaults for CUDA ToolKit and CuDNN.

Thank You.

**Comment by jjhelmus** [comment]
@RoyiAvital Thanks for the heads up on the new version.  I'll look at getting an update out next week.

**Comment by RoyiAvital** [comment]
@jjhelmus , You're welcome.
Mostly because my share of this task is the easy one - it's you who are doing most of it :-).

So Thank You.

**Comment by RoyiAvital** [comment]
@jjhelmus , I still can't find it.
Am I missing something?

Thank You.

**Comment by jjhelmus** [comment]
Sorry, the new version is still not available.

**Comment by RoyiAvital** [comment]
@jjhelmus , Any update on that?

Thank You.

**Comment by jjhelmus** [comment]
PyTorch 0.3.1 packages for linux-64 are now available in `defaults` for CUDA 8.0, CuDNN 7.  

We are looking into CUDA 9 packages in the coming weeks.

**Comment by RoyiAvital** [comment]
@jjhelmus ,
PyTorch 0.4 is out.
Could we have an update?

Thank You.

**Comment by jjhelmus** [comment]
PyTorch 0.4.0 is now available in `defaults`.  Currently only CUDA 8 is supported, we are still working on CUDA 9 support.

**Comment by RoyiAvital** [comment]
@jjhelmus ,
Great!

By the way, is it also available for Windows?
As PyTorch 0.4 added Windows support.

**Comment by jjhelmus** [comment]
We have not released PyTorch packages for Windows at this time.  I'll discuss the topic with the team to see if we can add this platform to our build list.

**Comment by Iamyang** [comment]
Hi, I met the following error when I installed pytorch 0.4.0 in Linux environment. My cuda version is 8.0 and I don't know how to deal with this error. 
`yangliu@user01-PowerEdge-T630:~$ conda install pytorch=0.4.0 cuda80 -c soumith
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - libtorch-gpu
  - pytorch=0.4.0 -> cudatoolkit=8.0
  - pytorch=0.4.0 -> mkl[version='>=2018.0.2']
Use "conda info <package>" to see the dependencies for each package.`

**Comment by RoyiAvital** [comment]
@jjhelmus ,

PyTorch 0.4.1 is out.
Could we have updated releases (Including CUDA 9.2)?
Could we have Windows support?

Thank You.

**Comment by jjhelmus** [comment]
@RoyiAvital Thanks for the heads up.  The team is working on building PyTorch 0.4.1 packages including Windows versions.  I am not sure if CUDA 9.2 will be included in the initial build matrix but we are looking into adding 9.2.

**Comment by lesteve** [comment]
Is there a chance PyTorch >= 1.0 will be available in the `defaults` channel? This would be really appreciated!

For completeness, PyTorch 1.0 was released in December 2018 and PyTorch 1.0.1 was released yesterday (February 2019).
