### ISSUE TITLE
Tiny font scaling in windows Anaconda Navigator

### ISSUE THREAD

**Issue by ruffsl** [ContinuumIO/anaconda-issues#742]
For 4K screens and such, the Anaconda Navigator suffers from tiny font scaling in Windows 10:
![image](https://cloud.githubusercontent.com/assets/2293573/14401225/90103c3e-fdd7-11e5-8955-f72f0dbe9cea.png)

**Comment by goanpeca** [comment]
@ruffsl thanks for reporting.

We are in the process of getting this fixed.

**Comment by timestocome** [comment]
? It's now Sept any idea if this is going to get fixed?

**Comment by ccordoba12** [comment]
Qt5 is going to be released along with Anaconda 4.2 on September 27.

**Comment by timestocome** [comment]
Thank you!

**Comment by MichelleKaz** [comment]
I also have the same issue. As today is Sep 27th, what do I need to do to make this update effective on my laptop. Thanks.

**Comment by ccordoba12** [comment]
`conda update qt pyqt`

**Comment by MichelleKaz** [comment]
Thank you for the update. Where do I run this command? I am using Windows laptop. Sorry I am a new user.

**Comment by ccordoba12** [comment]
In a Windows command prompt or terminal (i.e. `cmd.exe`)

**Comment by MichelleKaz** [comment]
I have run this in windows command prompt - 100% completed. However font size is still tiny when I open Anaconda navigator. I have restarted the laptop too. Please help.

**Comment by ccordoba12** [comment]
Maybe you also need to update Navigator:

    conda update anaconda-navigator

@goanpeca can help you further :-)

**Comment by timestocome** [comment]
No luck 

I ran all the current Windows OS updates. Then I updated qt/pyqt and anaconda-navigator, and I tried restarting the Surface but the fonts are still microscopic 

It's nbd, I pretty much just work from a cli, but your gui looked interesting and I thought I'd give it a try.

The menu bar font is readable, but nothing inside of the gui is, perhaps there's a different font inside that's hardcoded somewhere?

**Comment by goanpeca** [comment]
Hi @timestocome can we try something?

if you go to the command prompt and type

```
set QT_SCALE_FACTOR=2
anaconda-navigator
```

What do you get?

**Comment by timestocome** [comment]
Same thing, top title bar looks good ( Windows OS may set this font )
Everything inside the Anaconda window is too tiny to read.

**Comment by timestocome** [comment]
Getting a warning
libpng warning: iCCP: known inoccors sRGB profile

**Comment by goanpeca** [comment]
>libpng warning: iCCP: known inoccors sRGB profile

The warning is harmless

>Same thing, top title bar looks good ( Windows OS may set this font )
Everything inside the Anaconda window is too tiny to read.

Thats too bad, we had tested this with win10 on a high res screen this was solving the problem on that machine :-|, will need to investigate further.

**Comment by timestocome** [comment]
no problem, ping me if you need me to test anything

**Comment by goanpeca** [comment]
Thanks :+1:, will get back to you

**Comment by roxbarrett** [comment]
```
set QT_AUTO_SCREEN_SCALE_FACTOR=1
anaconda-navigator
```
fixed the issue for me! Thank you! Let me know if you want any info to help you guys further troubleshoot.

**Comment by MichelleKaz** [comment]
set QT_AUTO_SCREEN_SCALE_FACTOR=1
anaconda-navigator

has worked for me too. Thank you.

**Comment by MichelleKaz** [comment]
I also get the same warning message
libpng warning: iCCP: known incorrect sRGB profile

**Comment by goanpeca** [comment]
the warning is harmless it is not a problem

**Comment by carloslagorio** [comment]
I ran all the updates to no avail. My problem is the opposite, the GUI is displayed so big on my screen that it comes out pixelated and does not fit on my screen (so I can't access the top right icons for instance or reach about 75% of the GUI area).

thanks!

**Comment by goanpeca** [comment]
issuing a fix for the too big problem soon

**Comment by goanpeca** [comment]
This has been fixed in the latest version of navigator

`conda update anaconda-navigator`

Or by installing the latest version of Anaconda

`conda update anaconda`

**Comment by timestocome** [comment]
Thank you! 
It works on my SurfaceBook, I'm looking forward to checking it out.

**Comment by christinahaig** [comment]
I know this seems like a dead thread, but I have the latest version of Navigator and I am having the same problem.  My screen resolution is 3840x2160, with a Windows 10 scaling of of 250%.  If I change the scaling to be bigger, my other menus look far too big (particularly Spyder), but at this scaling, Navigator looks miniature.  

My Windows version is Windows 10 Enterprise version 1803, Navigator version 1.9.6

I have tried set QT_AUTO_SCREEN_SCALE_FACTOR=1 anaconda-navigator without good results.  However, when I choose a higher factor, like QT_AUTO_SCREEN_SCALE_FACTOR=2 anaconda-navigator  I get better results.  It gets a little bit too big, but at least it's human-readable.

I hope this helps someone.
