### ISSUE TITLE
anaconda-project does not encrypt variables

### ISSUE THREAD

**Issue by DavidMertz** [ContinuumIO/anaconda-issues#7459]
Quite possibly this is the wrong repo to file this. I welcome suggestions of where to move it (I posted on the AE-Platform Flow:
---
More with certification/course for `anaconda-project`.  Notwithstanding the documentation stating:

> Any variable ending in _PASSWORD, _SECRET, or _SECRET_KEY is automatically encrypted.

I find the following:

```bash
684-tmp % anaconda-project init --directory secrets --yes
Project configuration is in /Users/dmertz/tmp/secrets/anaconda-project.yml
685-tmp % cd secrets/
686-secrets % anaconda-project add-variable --default=user USERNAME
687-secrets % anaconda-project add-variable --default=pw USER_PASSWORD
688-secrets % grep variables: anaconda-project.yml
variables: {USERNAME: user, USER_PASSWORD: pw}
```

Doesn’t look very encrypted to me.  I've also tried it with `_SECRET` suffix, same story.

**Comment by csoja** [comment]
Closing here, as the posting in the other repo is the correct place.
