### ISSUE TITLE
blosc linked against incorrect libraries on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [ContinuumIO/anaconda-issues#7469]
On win64/python36 in a clean environment I get a DLL load error when I try to import blosc.
```
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import blosc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\envs\blosc\lib\site-packages\blosc\__init__.py", line 13, in <module>
    from blosc.blosc_extension import (
ImportError: DLL load failed: The specified module could not be found.
>>>
```

**env:**
```
λ(blosc)  conda list
# packages in environment at C:\Miniconda3\envs\blosc:
#
c-blosc                   1.10.2                   vc14_0  [vc14]
certifi                   2017.11.5        py36hb8ac631_0
icc_rt                    2017.0.4             h97af966_0
intel-openmp              2018.0.0             hd92c6cd_8
mkl                       2018.0.1             h2108138_4
numpy                     1.13.3           py36ha320f96_0
pip                       9.0.1                    py36_1    http://dc1pmat02:8089/PackageRepository/External
python                    3.6.3                h3b118a2_4
python-blosc              1.5.1                    py36_0
setuptools                36.7.2                   py36_0    conda-forge
vc                        14                            0    http://dc1pmat02:8089/PackageRepository/External
vs2015_runtime            14.0.25420                    0    http://dc1pmat02:8089/PackageRepository/External
wheel                     0.30.0           py36h6c3ec14_1
wincertstore              0.2                      py36_0    http://dc1pmat02:8089/PackageRepository/External
zlib                      1.2.11                   vc14_0  [vc14]  http://dc1pmat02:8089/PackageRepository/External
```

**Comment by dhirschfeld** [comment]
![image](https://user-images.githubusercontent.com/881019/33199760-7dc641dc-d13d-11e7-86c6-d920942df118.png)

**Comment by dhirschfeld** [comment]
...so it seems that the blosc build in the defaults channel is incorrectly linked against the *debug* version of the VC++ libraries.

**Comment by dhirschfeld** [comment]
...indeed, manually copying the debug dlls to the blosc directory fixed the issue.

**Comment by msarahan** [comment]
sorry, I think we fixed this in the past, but lost that fix in the transition to conda-forge recipes.  Thanks for reporting.

**Comment by dhirschfeld** [comment]
You mean an updated build of `python-blosc` 1.5.1? Version 1.5.1 is the current latest version in defaults and is the one built against the debug libraries.

In any case the new builds don't seem to have hit the defaults channel yet so I'll try again later...

**Comment by dhirschfeld** [comment]
Unfortunately The packaging of blosc seems a bit of a mess. The below versions of blosc are available in defaults:
```
blosc                        1.6.1                    vc14_1  defaults
                             1.7.0                    vc14_1  defaults
                             1.7.0                    vc14_2  defaults
                             1.12.0               h03602f7_0  defaults
                             1.12.0               h6afc36b_0  defaults
c-blosc                      1.10.2                   vc14_0  defaults
                             1.10.2                    vc9_0  defaults
python-blosc                 1.4.4                    py35_0  conda-forge
                             1.4.4                    py36_0  conda-forge
                             1.4.4            py35hdad557a_0  defaults
                             1.4.4            py27h55489d0_0  defaults
                             1.4.4            py36h632aa9d_0  defaults
                             1.5.1                    py27_0  defaults
                             1.5.1                    py35_0  defaults
                             1.5.1                    py36_0  defaults
```
Where both `c-blosc` and `blosc` refer to the C library and `python-blosc` refers to the Python interface which depends on the C library.

Before today the last version of `blosc`, 1.7.0 was built way back in 31-Oct-2015. After version 1.7.0, it seems the package was renamed `c-blosc` with version 1.10.2 being built on 24-Jun-2017. Today version 1.12.0 of `blosc` was built, seemingly reverting back to the original name.

All of this would be fine, *except* that the just built version  of `python-blosc` which links to the just built `blosc` is version 1.4.4 which is a very old version (03-Sep-2016). Before today the latest version 1.5.1 of `python-blosc` which linked to the older `c-blosc` library was already in the defaults library.

What this means is that anyone doing `conda install python-blosc` will get the "latest" version 1.5.1 which is built against the old, broken `c-blosc` library.

Sure, you can force and pin the version (if you know what you're doing and why), but the best fix would be to build a new `python-blosc` version 1.5.1 linking to the just built `blosc` 1.12.0

**Comment by dhirschfeld** [comment]
NB: I preferred it when the timestamps were actual datestrings - was more human friendly/debuggable than having to spin up a Python interpreter to enter `datetime.fromtimestamp(1511807562142/1000)`

**Comment by dhirschfeld** [comment]
On a positive note, if you to force install the 1.4.4 version it does work! 👍

**Comment by msarahan** [comment]
Indeed, the package naming here is especially terrible.  Sorry there's such a mess.  We'll be sticking with the conda-forge names for now (blosc for the c library, python-blosc for the python package).

I'm building a new blosc 1.5.1 now.  Sorry, I didn't check that before I built, and I had a bit of a stale recipe.

The difference you see in timestamps is because the older timestamps were being inserted by our legacy build system that is no longer in use.  Conda-build put in timestamps as a means of tie-breaking otherwise equivalent hashed packages.  There has been some debate about these timestamps at https://github.com/conda/conda/pull/6001

**Comment by mingwandroid** [comment]
Can we not call it libblosc and use a metapackage for c-blosc with a deprecation notice?

**Comment by msarahan** [comment]
I'm open to that, but we really need to settle https://github.com/conda/conda/wiki/CEP-2:-Renaming-packages before working on that any more.

**Comment by msarahan** [comment]
build number 1 of python-blosc version 1.5.1 is now available.  Closing this issue.

**Comment by dhirschfeld** [comment]
@msarahan - thanks for the fixes - `blosc` is working well now!

Since you sorted this out so quickly, can I be a bit cheeky and put in a plug for my issue #1469 which is also due to the library being linked against the incorrect dlls.

I think #1469 is pretty important because conda itself depends on `ruaml_yaml` so if that's broken you're dead in the water - you can't use conda to install a fixed version but have to manually monkey-patch your Miniconda install.

Of course, it's only on Windows containers where it's broken so it will only affect a very small number of users, nevertheless it would be good for a Miniconda install to Just Work on Windows containers.

**Comment by msarahan** [comment]
That looks pretty bad.  Unfortunately, it's more than I have time for right now.  Since @mingwandroid assigned himself to that issue way back when, maybe he can take a look.  Otherwise, we'll add it to the pile and hopefully get to it soon.
