### ISSUE TITLE
osx-64 libxml2 includes busted `.la` file

### ISSUE THREAD

**Issue by pkgw** [ContinuumIO/anaconda-issues#747]
For some reason, the current osx-64 package of libxml2 (`libxml2-2.9.2-0`) includes a `lib/libxml2.la` Libtool file that includes a reference to `/usr/lib/libiconv.la`. This dependent file is not present on my dev system, and the downstream effect is that packages that (1) depend on libxml2 and (2) use libtool themselves will fail to compile.

(Cf. similar issue #596)

**Comment by nehaljwani** [comment]
This has been fixed in `libxml2=2.9.4`:

```bash
(747) ➜  ~ conda list libxml2
# packages in environment at /Users/nwani/m3/envs/path:
#
libxml2                   2.9.4                         0
(747) ➜  ~ grep dependency_libs $CONDA_PREFIX/lib/libxml2.la
# Linker flags that cannot go in dependency_libs.
dependency_libs=' -lz -L/Users/nwani/m3/envs/path/lib /Users/nwani/m3/envs/path/lib/libiconv.la -lm'
```

Please upgrade the dependency on libxml2 so that libtool file comes in handy.
