### ISSUE TITLE
kq_init warnings with latest spyder 3.2.4

### ISSUE THREAD

**Issue by shivendra90** [ContinuumIO/anaconda-issues#7470]
Getting these warnings at spyder's startup. Just updated it to 3.2.4 but never seen these messages before.
Executed `export EVENT_NOKQUEUE=1` but did not fix. I believe updating lib event should fix it but how do I do it? Complete reinstall of the IDE is still displaying these warnings.
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.6.0
language: en
os: Darwin;17.2.0;Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by ccordoba12** [comment]
> I believe updating lib event

I think you need to install libevent with Homebrew to fix this:

https://brew.sh/

**Comment by shivendra90** [comment]
Thanks. That worked.
