### ISSUE TITLE
Navigator misses a desktop file on Linux

### ISSUE THREAD

**Issue by jmandreoli** [ContinuumIO/anaconda-issues#748]
I have installed anaconda-navigator on a Linux/Fedora-20, on a MacOS/ElCapitan and on a Windows machine, all three using an anaconda install based on Python 3.5. In all cases, I ran:
`conda install anaconda-navigator`
The install succeeded in all cases. Then, running anaconda-navigator worked fine on Windows, but failed on both Linux and MacOS, with essentially the same error:
1- when I run just the executable, without having activated an environment, it crashes with the following error

> Traceback (most recent call last):
  File "/opt/Tools/anaconda/andreoli/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 58, in main
    window = run_app(splash)
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 33, in run_app
    window = MainWindow(splash=splash)
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 99, in __init__
    self.api = AnacondaAPI()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 424, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 42, in __init__
    super(_AnacondaAPI, self).__init__()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/conda_manager/api/manager_api.py", line 30, in __init__
    self._client_api = ClientAPI()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/conda_manager/api/client_api.py", line 485, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/conda_manager/api/client_api.py", line 82, in __init__
    self._conda_api = CondaAPI()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/conda_manager/api/conda_api.py", line 1108, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/conda_manager/api/conda_api.py", line 243, in __init__
    self.set_root_prefix()
  File "/opt/Tools/anaconda/andreoli/lib/python3.5/site-packages/conda_manager/api/conda_api.py", line 352, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

2- When I run the same executable after having activated the environment, it freezes in the phase "Updating repodata" (that's the message I can see in the logo).

**Comment by ccordoba12** [comment]
Questions:

1. Are you running Navigator in an environment?
2. Did you do a system installation instead of a user one? By system installation, I mean if you installed Anaconda for all users in your computer :-)

**Comment by jmandreoli** [comment]
1. I have not created a specific environment. But in one case (crash) I just run the executable anaconda-navigator. In the other case (freeze) I do beforehand "source activate" followed by the root dir of the anaconda install (the default environment) which apparently sets things in my PATH. I would prefer not to have to do that to run the navigator.

2. I believe I did install Anaconda for all users. It is indeed used by many users (both on the Linux and the MacOS machines) and this has never raised a problem.

**Comment by ChadFulton** [comment]
I had a similar issue trying to get anaconda-navigator into the Unity Launcher in Ubuntu 16.04. I had added a `.desktop` item running the `~/anaconda3/bin/anaconda-nagivator` command, and ran into the  exception trace that was given above.

In my case, the error appeared to be related to a problem with the `~/anaconda3/bin/` directory not being added to the path in a way that was accessible to the launcher. I removed the line that anaconda added to `.bashrc` and put it in `.profile`, logged out and back in, and then the launcher icon worked to open anaconda nagivator and no longer threw the exception.

**Comment by ccordoba12** [comment]
@ChadFulton, if you prefer not to add the Anaconda bin dir to `PATH` in `.profile`, you need to have the following in your desktop file for Navigator to work:

    Exec=/usr/bin/env PATH=/home/foo/anaconda3/bin/:$PATH /home/foo/anaconda3/bin/anaconda-navigator

**Comment by goanpeca** [comment]
@csoja, @ccordoba12, should we add this launchers for linux on install automatically?

**Comment by ccordoba12** [comment]
I'd prefer this functionality to be added to the `menuinst` package. I don't know if @msarahan has time to do it though :-)

**Comment by msarahan** [comment]
Linux and Mac are not really supported by menuinst right now. Probably best
to not count on it, unless one of you wants to take that project on.

**Comment by ccordoba12** [comment]
I don't have time to maintain the project, but I definitely like to add Linux and Mac functionality to it. I'll see what I can do about it after releasing Spyder 3.0.

**Comment by covelloz** [comment]
@ccordoba12 
Putting "Exec=/usr/bin/env PATH=/home/foo/anaconda3/bin/:$PATH /home/foo/anaconda3/bin/anaconda-navigator" in the .desktop file works to launch the program. However, if you try to launch "Jupyter Notebook" from Anaconda Navigator, it will fail.

I found that @ChadFulton 's solution to work flawlessly. Jupyter Notebook will execute properly if you append the line added by Anaconda from your .bashrc file to your .profile file.

-----------------------------------------------------------------------
# added by Anaconda2 4.1.1 installer
export PATH="/home/covello/anaconda2/bin:$PATH"
-----------------------------------------------------------------------

-> Lubuntu 15.10

**Comment by jmandreoli** [comment]
Yes, setting the PATH variable solves the initial problem reported here. It works fine on Windows and Mac OS. However, I still have a problem with the Linux install: it takes ages, apparently in the "uploading repodata" phase, and then I only have access to the "installed" listing, the "upgradable" and "uninstalled" listing being empty.  This is a separate bug, so I'll check the bug list and possibly open a new bug. Thanks.

**Comment by selahlynch** [comment]
@ChadFulton's solution worked for me too on Ubuntu 16.04 with Anaconda3-4.3.1-Linux-x86_64.sh

**Comment by RoyiAvital** [comment]
Is there "Official" Anaconda Navigator Desktop Shortcut for Ubuntu based Linux Systems?

It's not user friendly to launch it from terminal.

Thank You.

**Comment by iam-mhaseeb** [comment]
I solved it with this solution:
```
nano ~/.local/share/applications/anaconda.desktop
[Desktop Entry]
Name=Anaconda
Comment=anaconda-navigator
Exec=/usr/bin/env PATH=/home/haseeb/anaconda3/bin/:$PATH /home/haseeb/anaconda3/bin/anaconda-navigator
Icon=/home/haseeb/anaconda3/lib/python3.6/site-packages/anaconda_navigator/static/images/logos/continuum_twitter.jpg
Terminal=false
Type=Application
StartupNotify=true
```
