### ISSUE TITLE
Conda Navigator slow startup, no applications

### ISSUE THREAD

**Issue by vmuriart** [ContinuumIO/anaconda-issues#749]
Morning, just did a fresh install to anaconda 4.0, and the start up for navigator is dreadfully slow. Takes about two minutes to finally load up. Tried it on 2 other machines with the same results on 2.7 and 3.5

I suspect the issue is with the proxy somehow; though havent been able to narrow it down.

**Comment by goanpeca** [comment]
@vmuriart it might indeed be a proxy setting, can you give us some info on your OS, your setup, Qt version... etc?

**Comment by goanpeca** [comment]
You can also access the Error Log Viewer from the help menu or by pressing F6

**Comment by vmuriart** [comment]
Tried it on:
Os: Windows 8.1/Windows 7
hardware: Laptop/ Desktop (both behind proxy)
Qt Version: whatever is bundled with Anaconda.
Anaconda versions tried: `Anaconda4 Py2.7 x64`, `Anaconda4 Py3.5 x64`

The only errors im seeing are very vague. 

```
2016-04-12 08:18:25,526 - ERROR
main_window.create_application_projects : 267
None

2016-04-12 10:04:27,128 - ERROR
main_window.create_application_projects : 267
None

2016-04-12 10:04:27,128 - DEBUG
anaconda_api.create_application_projects : 212
([], False)
```

It looks like the download is done through [conda-manager](https://github.com/spyder-ide/conda-manager/blob/master/conda_manager/api/download_api.py) and i don't see anywhere its taking any of the proxy variables. 


`Requests` though should be extracting them from my env. variables unless that was somehow disabled. I saw this similar [issue](https://github.com/spyder-ide/conda-manager/issues/37) but didn't understand how it was solved there.

**Comment by goanpeca** [comment]
Can you try defining the proxy variables in .condarc following [these instructions](http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers) ?

**Comment by vmuriart** [comment]
Just tried it from home, outside the proxy. Each section took a bit longer to load, except repodata which  was much faster than before. I setup the the `.condarc` earlier today to see if that helped but didn't. I'll try it again though.

**Comment by vmuriart** [comment]
strange, i can no longer reproduce the issue on my notebook after the first time it connected without the proxy. Now that I am back behind it, it loads up faster than w.o the proxy; my guess is that its failing somewhere along the line and just using the local files?

On my desktop that hasnt been outside the proxy, issue is still present. I set the `.condarc` and issue still persists. One thing to note though, unlike the previous version of Anaconda, i don't see anywhere in this new version that it open the `.condarc` file to extract the proxy settings

**Comment by vmuriart** [comment]
closing for now. the `.condarc` didn't help, but after I removed my `https_proxy` env variable some of the applications showed up; but now all my `https` traffic was dead. `Requests` is finding the right proxy variable, but for some reason isn't succeeding in getting any `https` data when called by the `navigator`.

**Comment by vmuriart** [comment]
one thing though, the `logger` could use a bit of improvement. I bet there's a few exceptions and errors being thrown by requests that the `logger` isn't properly recording.

**Comment by goanpeca** [comment]
Did you notice that the logger has a dropdown to select a file?

The condamanager.log files log condamanager related stuff

**Comment by vmuriart** [comment]
Yup. Check it as well. I don't remember seeing any exceptions that would
have led me to requests. I'll check again tomorrow. Most of the errors I
saw just said "None"

**Comment by vmuriart** [comment]
Took a look just now at the other log file, no error's were recorded there. I'm still troubleshooting this as its perplexing what's going on...

**Comment by lgpage** [comment]
I am having the exact same problem with this.
Slow startup, no applications, no internet traffic.

OS: Ubuntu 14.04
Anaconda: Tried both `Anaconda2-4.0.0-Linux-x86_64` and `Anaconda3-4.0.0-Linux-x86_64`
Proxy servers (`http_proxy` and `https_proxy`) are exported in my `.bashrc` and I also tried adding them to a `.condarc` file as suggested in the documentation. Still have the same problem.

**Comment by goanpeca** [comment]
The new release of Navigator coming up in a few weeks will solve proxy related issues.

**Comment by lgpage** [comment]
Awesome :D  Thanks for the info.

**Comment by goanpeca** [comment]
:+1:

**Comment by obarak** [comment]
Hi, having this issue also with the new release.
Installed a fresh Anaconda 4.0 a few months back, and just now updated to latest versions of all components (using `conda update conda,` `conda update anaconda`). Navigator startup is around 2 minutes. When I'm off the corporate network it starts in seconds, so it's probably proxy-related. Interestingly, Like @vmuriart I'm also behind Intel's proxy... 

thanks!

**Comment by goanpeca** [comment]
We are releasing bugfix release today to corretcly handle the proxy configuration. Stay tunned :-)

**Comment by obarak** [comment]
Hi guys, any update on this? Didn't see a new version yet...

**Comment by goanpeca** [comment]
1.2.2 i out for a week now :-),

**Comment by obarak** [comment]
Oh, got it, thanks.

**Comment by obarak** [comment]
It's working fine now, although startup is still a few seconds slower than when not using proxy.
Generally, I think the navigator should set the ENV variables itself when starting up if it detects a proxy defined in .condarc.
I don't want to have these ENV set all the times (conflicts with other apps), so currently I had to set up a batch file that sets the ENVs and then starts Navigator.

**Comment by vmuriart** [comment]
Just got mine to work after adding the condarc file. 

@goanpeca Why are both the environment variables and `.condarc` needed for the proxy. I would think that the presence of the environment variables would mitigate needing the `.condarc` file.

**Comment by goanpeca** [comment]
@vmuriart conda uses both env variables and condarc settings, whereas anaconda-client only uses environment variables. Due to this mismatch between those two libraries (whcih Navigator depends on) is why we see this behavior.

**Comment by vmuriart** [comment]
Based on that though, if I have my environment variables set correctly, then it should work and I shouldn't need to have a `.condarc` file at all. 

This wasn't the case though. The environment variables alone weren't enough for the proxy to fully work, I had to duplicate the environment variable data in the `.condarc` file as well. 

It's not a big deal, just something that caught me off-guard. I've had to write/research so many work-arounds for other program's, this one is very minimal in comparison 😄 

Thanks!

**Comment by arvindpdmn** [comment]
Can someone explain "You have to set condarc configuration plus the ENV variables (that requests library uses)"? Exactly what do I need to do?

For me it takes many minutes, not just 2! My net connection is slow. Why does navigator use internet when starting up? Can I disable this?

**Comment by dhowland** [comment]
This is apparently not yet fixed.  Many minutes to open Navigator, even with my proxy settings correct in .condarc

**Comment by dajamerson** [comment]
I had to configure both the .condarc file and the environment variables to get it to work.
