### ISSUE TITLE
Will moviepy be added to conda sources?

### ISSUE THREAD

**Issue by lidh15** [ContinuumIO/anaconda-issues#7500]
Anaconda is in my opinion the best environment for python Deep Learning. I encounter a project which requires moviepy for data visualization. When I try "conda install moviepy", it is not found. I know that "pip3 install moviepy" works, but I have both python 3.5 and python 3.6, and pip3 install will always add package to 3.5, the only way I can add package for 3.6 is conda install (maybe I shall edit path). 
I wonder if conda source can include moviepy.

**Comment by nehaljwani** [comment]
Till that package is added to defaults, you can get it from conda-forge
```
conda install -c conda-forge moviepy
```

**Comment by lidh15** [comment]
Thanks a lot.
