### ISSUE TITLE
SciPy build for Python 2.7 on Windows uses wrong MSVC runtime

### ISSUE THREAD

**Issue by insertinterestingnamehere** [ContinuumIO/anaconda-issues#753]
The latest build of SciPy for Python 2.7 on Windows (I've verified this on 64 bit Windows, but it likely applies to the 32 bit binaries as well) links against msvcr100 rather than msvcr90. This causes an error on import for most of the compiled extensions in scipy on systems that don't already have msvcr100 available somewhere. Even on systems where msvcr100 is available, mixing C runtimes is a terrible idea since it can cause other subtle bugs. The package needs to be rebuilt with the right compiler and C runtime.

**Comment by ilanschnell** [comment]
Yes, it also applied to the 32-bit Windows binary.  I've added `vs2010_runtime` as a dependency, and uploaded new packages.

**Comment by msarahan** [comment]
This is not the correct solution.  You are mixing runtimes with this solution, which is a bad idea (http://siomsystems.com/mixing-visual-studio-versions/), even if we did get away with it for a long time.  Please rebuild scipy as @insertinterestingnamehere requested - if it doesn't work for some reason, and you need help figuring it out how to make it work, either of us would be happy to help you, I'm sure.

I'm reopening this issue.

**Comment by ilanschnell** [comment]
Sorry, I shouldn't have closed this.  Adding the `vs2010_runtime` dependency is indded just a temporary hack.

**Comment by insertinterestingnamehere** [comment]
Thanks for taking some time to look at this @ilanschnell, but, yes, we definitely aren't finished yet. Thanks for reopening it @msarahan.

**Comment by mingwandroid** [comment]
No, it's not there yet.

**Comment by csoja** [comment]
@mingwandroid It should be there now - can you confirm and close this issue if it is?

**Comment by mingwandroid** [comment]
Verified fixed.
