### ISSUE TITLE
CondaError: MD5MismatchError r-rcpp-0.12.13

### ISSUE THREAD

**Issue by nicolaasuni** [ContinuumIO/anaconda-issues#7533]
I am getting the following error in Conda (I am using Miniconda3-4.2.12-Linux-x86_64.sh):

```
CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'http://repo.continuum.io/pkgs/r/linux-64/r-rcpp-0.12.13-r342h9f83869_0.tar.bz2'.
  download saved to: /pkgs/r-rcpp-0.12.13-r342h9f83869_0.tar.bz2
  expected md5 sum: 6dee27451b02d23eacc96373a99740df
  actual md5 sum: be50a7006de307a3ae1c162cb3d96425
```

JFrog Artifactory report the following Checksums:
```
SHA-256: a181c379ffa15f51e6d168afbba14ec3656ea19a9f556d336999456d8d6eb0e6
SHA-1: 1dbfcabf958a85915cf11c58d52ad7ae8624c01e
MD5: be50a7006de307a3ae1c162cb3d96425
```

Seems like that this package has the wrong MD5?

**Comment by mingwandroid** [comment]
@kalefranz, any idea here? I had to rebuild all these to pin r-base.

**Comment by nicolaasuni** [comment]
I think that this is because packages may have the same name and version, but different MD5 checksums:
https://github.com/conda/conda/issues/4956
I'll try to "zap" the Artifactory cache and see if it works.

**Comment by nicolaasuni** [comment]
I have manually downloaded the file and checked:
```
wget http://repo.continuum.io/pkgs/r/linux-64/r-rcpp-0.12.13-r342h9f83869_0.tar.bz2
md5sum r-rcpp-0.12.13-r342h9f83869_0.tar.bz2 
be50a7006de307a3ae1c162cb3d96425  r-rcpp-0.12.13-r342h9f83869_0.tar.bz2
```
So the MD5 in the repodata.json is definitely different.

**Comment by nicolaasuni** [comment]
I suspect that something went wrong when the packages were updated and now the r repository is unusable. How often these packages are checked/rebuilt?

**Comment by nehaljwani** [comment]
@nicolaasuni Un-releated to your query, are you using the remote repository feature in Artifactory?

**Comment by nicolaasuni** [comment]
The issue seems solved now.
Would it be possible that the http://repo.continuum.io was serving the old file because of caching?
