### ISSUE TITLE
Spyder Issue

### ISSUE THREAD

**Issue by graphicstone** [ContinuumIO/anaconda-issues#7536]
In the Navigator app when I try to launch the Spyder a progress bar comes at the bottom of the app but after few seconds it disappears and nothing is displayed. I tried restarting the system after the install but still it is not working.

**Comment by ccordoba12** [comment]
Could you start Spyder from a system terminal (i.e. cmd.exe) with this command

    spyder --show-console

and then post the error messages that appear there here? Thanks!

**Comment by graphicstone** [comment]
I was able to run the Spyder app from it's stand alone launcher but not from the navigator, but still when I tried the given command in cmd it gave this: " 'spyder' is not recognized as an internal or external command, operable program or batch file. "

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
