### ISSUE TITLE
Launcher problems

### ISSUE THREAD

**Issue by DaveBackus** [ContinuumIO/anaconda-issues#755]
We're using Anaconda to teach Python to 100 programming newbies at NYU, and it's been great.  But we recently ran across a bug with some of our students that has led to us ignore Launcher and start programs from the command line, which perhaps is what we should have done from the start.  

**One thing** we ran across is this error when we tried to launch Jupyter from Launcher:  
Error launching application:
App notebook not installed.

**Another thing** we ran across was that the update button hung:  no response, even after waiting a long time.  So we went to the command line to see what was happening.  Conda refused to do anything because it thought another instance of conda update was already running.

Looking into this further, it seems that the lifecycle of a conda update ANYTHING call includes the following: 

1. check for a conda lock file. If one is found, throw an error and stop
2. Otherwise, create a lock file on the computer
3. Do the updates
4. remove the lock file so step 1 doesn’t fail next time.

When doing our updates from launcher it made it to step 3, hit some kind of error, which it didn't report back to us, and stopped.  We have several instances of this on different operating systems.  

We got around this by going to the command like, deleting the lock fil, and then using conda the usual way.  

We plan to use the command line only in the future, so we're fine.  But you might want to look into Launcher if this is to be a widely used tool in the future.  

Cheers, 
Dave and Spencer 
http://databootcamp.nyuecon.com/

**Comment by goanpeca** [comment]
Hi @DaveBackus, thanks for reporting. Just to clarify, are you talking about Anaconda Navigator (Replaced Launcher) or about Launcher (now deprecated?)

**Comment by DaveBackus** [comment]
Launcher.

Two related thoughts:

* If Launcher is deprecated, could you put something at the top suggesting
users switch to Navigator?

* Also:  I updated the whole distribution recently with Conda, no sign of
anything that looks like Navigator.  What am I missing?

**Comment by goanpeca** [comment]
>If Launcher is deprecated, could you put something at the top suggesting
users switch to Navigator?

Since it is deprecated and no code development is longer taking place, I doubt this will happen, however  [Launcher docs](https://docs.continuum.io/anaconda-launcher/index) are clear about the situation.

>Also:  I updated the whole distribution recently with Conda, no sign of
anything that looks like Navigator.  What am I missing?

[Anaconda 4.0](https://www.continuum.io/blog/developer-blog/anaconda-4-release) was released recently so I am not sure you got the right one.

For more information on Navigator, please visit the [docs](https://docs.continuum.io/anaconda/navigator)

**Comment by DaveBackus** [comment]
Your call, but it strikes me as inefficient to bury it in the docs when
changes could be flagged in the apps themselves.  Python packages often do
something similar when you use features to be deprecated:  they issue a
warning in pink explaining the situation.
