### ISSUE TITLE
Spyder and Anaconda Navigator not working

### ISSUE THREAD

**Issue by DTRRNGTN** [ContinuumIO/anaconda-issues#7614]
I have had a working anaconda distribution running with 2 environments (root and tensorflow).

Since this weekend neither spyder nor anaconda navigator have been working. When I ran them from an icon they just hang and then end. When I run them from the command line they show an error linked to the QT bindings. (No Qt bindings could be found). 

I have tried uninstalling and reinstalling the distribution as well as updating the individual packages. If I install QT5 then the error moves to the zmq backend. 

Nothing has resolved the issue. 

I am running Windows 10 and python 3. I have tried several versions of the distribution (Python 3.5 and 3.6) but nothing has worked. 

I have now uninstalled the whole thing, hoping that a wider fix is on the way?

**Comment by goanpeca** [comment]
@DTRRNGTN please post the output of

```
conda info
conda list
```

**Comment by laleba** [comment]
C:\Users\lale>conda info
'conda' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lale>

**Comment by goanpeca** [comment]
No feedback provided.

**Comment by DTRRNGTN** [comment]
@goanpeca I was travalling this week and I only had a chance to try this today. I have run a full re-install of the latest Anaconda 64 bit distribution for Windows 10 and it is now working. I have also created a tensorflow environment with GPU acceleration and this also seems to be fine.

Thanks for your help but I confirm that this is now closed. This is the output from conda info for information.

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\Daniel\Anaconda3  (writable)
    default environment : C:\Users\Daniel\Anaconda3
       envs directories : C:\Users\Daniel\Anaconda3\envs
                          C:\Users\Daniel\AppData\Local\conda\conda\envs
                          C:\Users\Daniel\.conda\envs
          package cache : C:\Users\Daniel\Anaconda3\pkgs
                          C:\Users\Daniel\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Daniel\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.15063
          administrator : False
