### ISSUE TITLE
Package Request for wxpython-phoenix

### ISSUE THREAD

**Issue by allyelsey** [ContinuumIO/anaconda-issues#7625]
I would like to see the wxpython-phoenix releases for Python 3.6 be included in anaconda (for 2.7 as well if you wish). It can be found in older versions here:

https://anaconda.org/conda-forge/wxpython 
https://anaconda.org/newville/wxpython-phoenix

this might help with recipes.

**Comment by nehaljwani** [comment]
@csoja The py3 support starts with the phoenix release which is version 4. Upstream has released two beta versions. For this request, should building a beta release be considered?

**Comment by newville** [comment]
fwiw, https://anaconda.org/GSECARS/wxpython is a more complete, with packages based on wxpython 4.0.0a3 for linux-64, darwin-64, win-64, and win-32.

**Comment by JeremyEnns** [comment]
wxpython has finalized version 4.0.0. Can we get a conda package built for this?

https://wxpython.org/pages/downloads/

**Comment by nehaljwani** [comment]
wxpython 4.0.1 is available in the defaults channel for all platforms.

**Comment by newville** [comment]
@nehaljwani Thanks!  I'm very very happy that Anaconda now has packages for wxPython 4!
