### ISSUE TITLE
Connection error when creating new environment or installing packages

### ISSUE THREAD

**Issue by vahndi** [ContinuumIO/anaconda-issues#764]
```
>conda create -n mta_31 python=3.5
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: Could not connect to https://repo.continuum.io/pkgs/p
ro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
....
Solving package specifications: .........

Package plan for installation in environment C:\Users\vahndi.minah\AppData\Local
\Continuum\Anaconda3\envs\mta_31:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-8.1.1                  |           py35_0         1.6 MB

The following NEW packages will be INSTALLED:

    pip:            8.1.1-py35_0
    python:         3.5.1-4
    setuptools:     20.3-py35_0
    vs2015_runtime: 14.00.23026.0-0
    wheel:          0.29.0-py35_0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/pip-8.1.1-py35_0
.tar.bz2
Error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443)
: Max retries exceeded with url: /pkgs/free/win-64/pip-8.1.1-py35_0.tar.bz2 (Cau
sed by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSCo
nnection object at 0x00000000047C27B8>: Failed to establish a new connection: [E
rrno 11004] getaddrinfo failed',)): https://repo.continuum.io/pkgs/free/win-64/p
ip-8.1.1-py35_0.tar.bz2
```

**Comment by vahndi** [comment]
I can connect with the browser so not a firewall issue

**Comment by totogo** [comment]
I got the same error

**Comment by lilmatt** [comment]
What OS is this with?

**Comment by totogo** [comment]
Windows10

**Comment by vahndi** [comment]
Windows too. I was able to install packages on the same computer over my home Wi-Fi so I think it was something to do with my company's firewall. Would be good to have a workaround though.

**Comment by lilmatt** [comment]
getaddrinfo is the DNS name -> IP resolution step, so could folks experiencing this run "nslookup repo.continuum.io" in a Windows Command Prompt and post what you get back? I want to see if we've got some sort of DNS problem on our hands or what.

**Comment by totogo** [comment]
Here is the DNS result
```
[Anaconda3] C:\Users\Toto>nslookup repo.continuum.io
Server:  Hiwifi.lan
Address:  10.1.199.1

Non-authoritative answer:
DNS request timed out.
    timeout was 2 seconds.
Name:    elb-repo-cio-73042851.us-east-1.elb.amazonaws.com
Addresses:  54.225.186.77
          23.23.167.24
          54.235.112.150
          54.243.28.47
          184.73.249.242
          184.72.230.63
Aliases:  repo.continuum.io
```

**Comment by vahndi** [comment]
My issue turned out to be my work's proxy server. Now I have created the .condarc file in my home directory with the following lines (user, pass, corp and port changed) it works fine - I only realised this because I was having the exact same problem with node and bower and a friend pointed out the solution for those.

[http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers](http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers)

```
proxy_servers:
    http: http://user:pass@corp.com:8080
    https: https://user:pass@corp.com:8080
```

**Comment by haiderhusnain** [comment]
I am struggling too with the same error.
I got following when run "nslookup repo.continuum.io"

DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  172.16.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out

**Comment by haiderhusnain** [comment]
I am unable to figure how to create .condarc file.

**Comment by nehaljwani** [comment]
@haiderhusnain Are you also behind a proxy server?

**Comment by haiderhusnain** [comment]
Yes

**Comment by vahndi** [comment]
@haiderhusnain if you are using Windows then Explorer doesn't allow you to create a file starting with a dot. You can use notepad++ to do this.

**Comment by haiderhusnain** [comment]
Yes i created a .txt file named ".condarc.txt" which contained text 
'proxy_servers'
            http://172.***.***.***:8080
but problem was not solved.

**Comment by haiderhusnain** [comment]
BTW by default proxy is picked from environment variable 'proxy_servers'. which is already set to right proxy.

**Comment by vahndi** [comment]
Mine is called `.condarc` - no `.txt` on the end

**Comment by haiderhusnain** [comment]
Your extension might be hidden.

**Comment by vahndi** [comment]
No, the extension is `condarc`

**Comment by haiderhusnain** [comment]
you mean 'proxy_servers.condarc'?

**Comment by vahndi** [comment]
No. The path to the file is like `C:\Users\user_name\.condarc`

**Comment by nehaljwani** [comment]
@haiderhusnain Please share output for command:

`conda config --show`

**Comment by haiderhusnain** [comment]
@nehaljwani Its here

add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/msys2: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/p
kgs/r", "https://repo.continuum.io/pkgs/pro", "https://repo.continuum.io/pkgs/ms
ys2"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
envs_dirs:
  - D:\Facial\envs
  - C:\Users\kashif\AppData\Local\conda\conda\envs
  - C:\Users\kashif\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - D:\Facial\pkgs
  - C:\Users\kashif\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0

**Comment by nehaljwani** [comment]
@haiderhusnain There doesn't seem to be any proxy server added in your conda configuration.

Please type `type C:\Users\user_name\.condarc` to verify whether or not you have added the requried configuration according to https://conda.io/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers

**Comment by fedanna** [comment]
I also had this problem, it was something wrong with my company firewall.
When I tried do the same, on the same computer, connected to my home wi-fi, everything was ok.

**Comment by ProfessorHuang** [comment]
I have solved this problem this morning when I uninstalled the python3.7 32bit that I installed before.

**Comment by msarahan** [comment]
https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#ssl-connection-errors

**Comment by gaurav-vision** [comment]
When am I running any command started with conda like "conda install mkl", then I am getting this error so please some one suggest me how can i resolve it.

Error:-
Collecting package metadata (current_repodata.json): failed

ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.

**Comment by shamim-io** [comment]
Thank you so much everyone. It solved my problem.

It occured due to the proxy setting in my machine. 
secondly i created .condarc file using vs code and saved the file by selecting no extension option. it worked..

**Comment by volcas** [comment]
> I recently got this issue resolved. Use this command to see proxy_servers
> `conda config --show`
> 
> If any proxy server is present in the configuration. Kindly use
> `conda config --remove-key proxy_servers`. It will remove saved proxy servers from anaconda configuration.
> Enter
> `conda clean --source-cache`
> Now your http error is gone.
> Give it a try and let me know in case of any difficulty.

This solution absolutely worked for me. Thanks.
Only change for the new version is instead of  `conda clean --source-cache`, I used  `conda clean --index-cache`
