### ISSUE TITLE
Upgrade jsonschema

### ISSUE THREAD

**Issue by minrk** [ContinuumIO/anaconda-issues#765]
The jsonschema package in conda is still 2.4.0, which has a memory leak that causes the Jupyter notebook server to grow unbounded in memory every time a notebook is saved. jsonschema 2.5.1, released last June, fixes this issue, so it would be helpful if the conda package could be updated to the current verson.

**Comment by groutr** [comment]
Thanks for the notice.  I'll get this in the queue.

**Comment by minrk** [comment]
Great, thanks!

**Comment by groutr** [comment]
Updated.
