### ISSUE TITLE
IPython "Warning GUI event loop or pylab initialization failed"

### ISSUE THREAD

**Issue by lseongjoo** [ContinuumIO/anaconda-issues#766]
After some point, ipython console startup shows below warning

Python 3.5.1 |Anaconda custom (x86_64)| (default, Dec  7 2015, 11:24:55) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
[TerminalIPythonApp] WARNING | GUI event loop or pylab initialization failed
UsageError: Invalid GUI request 'inline', valid ones are: tk, glut, qt, gtk3, qt5, wx, osx, pyglet, gtk

**Comment by msarahan** [comment]
You have some old ipython configuration that is setting your default backend to inline.  This is OK for the notebook, but not for the console.

This is an ipython issue, not an anaconda one.  If you can't find the config file, please raise this issue on their mailing list. Closing.

**Comment by lseongjoo** [comment]
Thanks for looking into the issue. I will check the config as you kindly instructed. 

Seongjoo




On Wed, Apr 27, 2016 at 5:54 AM -0700, "Mike Sarahan" <notifications@github.com> wrote:












You have some old ipython configuration that is setting your default backend to inline.  This is OK for the notebook, but not for the console.



This is an ipython issue, not an anaconda one.  If you can't find the config file, please raise this issue on their mailing list. Closing.
