### ISSUE TITLE
Notebook Will Not Launch on Root

### ISSUE THREAD

**Issue by greg-amato** [ContinuumIO/anaconda-issues#7660]
**Tried rolling back to previous anaconda version to no effect.  Notebook will not launch on root env.  At a loss where to go from here...**

`Traceback (most recent call last):
File "C:\Users\grega\Anaconda3\Scripts\jupyter-notebook-script.py", line 10, in 
sys.exit(main())
File "C:\Users\grega\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "C:\Users\grega\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
app.initialize(argv)
File "", line 2, in initialize
File "C:\Users\grega\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\grega\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1368, in initialize
self.init_webapp()
File "C:\Users\grega\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1161, in init_webapp
self.jinja_environment_options
File "C:\Users\grega\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 154, in __init__
base_url, default_url, settings_overrides, jinja_env_options)
File "C:\Users\grega\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 263, in init_settings
nbextensions_path=jupyter_app.nbextensions_path,
File "C:\Users\grega\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 874, in nbextensions_path
from IPython.paths import get_ipython_dir
File "C:\Users\grega\Anaconda3\lib\site-packages\IPython\__init__.py", line 55, in 
from .terminal.embed import embed
File "C:\Users\grega\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 16, in 
from IPython.terminal.interactiveshell import TerminalInteractiveShell
File "C:\Users\grega\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 32, in 
from .debugger import TerminalPdb, Pdb
File "C:\Users\grega\Anaconda3\lib\site-packages\IPython\terminal\debugger.py", line 6, in 
from IPython.core.completer import IPCompleter
File "C:\Users\grega\Anaconda3\lib\site-packages\IPython\core\completer.py", line 146, in 
import jedi
File "C:\Users\grega\Anaconda3\lib\site-packages\jedi\__init__.py", line 41, in 
from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
File "C:\Users\grega\Anaconda3\lib\site-packages\jedi\api\__init__.py", line 23, in 
from jedi.api import classes
File "C:\Users\grega\Anaconda3\lib\site-packages\jedi\api\classes.py", line 14, in 
from jedi.evaluate import representation as er
File "C:\Users\grega\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 69, in 
from jedi.evaluate import representation as er
File "C:\Users\grega\Anaconda3\lib\site-packages\jedi\evaluate\representation.py", line 52, in 
from jedi.evaluate import docstrings
File "C:\Users\grega\Anaconda3\lib\site-packages\jedi\evaluate\docstrings.py", line 46, in 
from numpydoc.docscrape import NumpyDocString
File "C:\Users\grega\Anaconda3\lib\site-packages\numpydoc\__init__.py", line 5, in 
from .numpydoc import setup
File "C:\Users\grega\Anaconda3\lib\site-packages\numpydoc\numpydoc.py", line 28, in 
if sphinx.__version__ AttributeError: module 'sphinx' has no attribute '__version__'
`

**Also looks like jedi and parso are show 4 resolutions.**

C:\Users\grega>conda update --all
Fetching package metadata .............
Solving package specifications: .
Warning: 4 possible package resolutions (only showing differing packages):
  - defaults::jedi-0.11.0-py35hc856aec_0, defaults::networkx-1.11-py35h097edc8_0, defaults::parso-0.1.0-py35hb960d57_0, defaults::scikit-image-0.13.1-py35ha2243b5_0
  - defaults::jedi-0.11.0-py35hc856aec_0, defaults::networkx-2.0-py35h29b0c50_0, defaults::parso-0.1.0-py35hb960d57_0, defaults::scikit-image-0.13.0-py35h49207bb_1
  - defaults::jedi-0.10.2-py35h3350e2d_0, defaults::networkx-2.0-py35h29b0c50_0, defaults::parso-0.1.1-py35he39c48a_0, defaults::scikit-image-0.13.0-py35h49207bb_1
  - defaults::jedi-0.10.2-py35h3350e2d_0, defaults::networkx-1.11-py35h097edc8_0, defaults::parso-0.1.1-py35he39c48a_0, defaults::scikit-image-0.13.1-py35ha2243b5_0

Package plan for installation in environment C:\Users\grega\Anaconda3:

The following packages will be UPDATED:

    jedi:  0.10.2-py35h3350e2d_0 --> 0.11.0-py35hc856aec_0

The following packages will be DOWNGRADED:

    parso: 0.1.1-py35he39c48a_0  --> 0.1.0-py35hb960d57_0

Proceed ([y]/n)? n

**If I run update again it gives the reverse resolution!**

**Comment by jjhelmus** [comment]
Can you provide the output from `conda list` in the environment which is causing issues?  

One option is to install the packages which are defined by the last anaconda release using `conda install anaconda=5.0.1`.   This set of packages has been tested and is known to work well together.

**Comment by greg-amato** [comment]
(root) C:\Users\grega>conda list
# packages in environment at C:\Users\grega\Anaconda3:
#
_license                  1.1                      py35_1
_nb_ext_conf              0.4.0                    py35_1
alabaster                 0.7.10           py35h3a808de_0
anaconda                  custom           py35h64770cb_0
anaconda-client           1.6.6            py35h690133a_0
anaconda-navigator        1.6.9            py35hfe15c67_0
anaconda-project          0.8.2            py35h06aeb26_0
anyqt                     0.0.8                    py35_0
argcomplete               1.0.0                    py35_1
asn1crypto                0.23.0           py35h65de013_0
astroid                   1.5.3            py35h82ecf54_0
astropy                   2.0.2            py35h6e1a5eb_4
attrs                     17.3.0           py35hdfbe3a1_0
babel                     2.5.0            py35hcd66c26_0
backports                 1.0              py35he88aa47_1
backports.shutil_get_terminal_size 1.0.0            py35h9d89c8b_2
beautifulsoup4            4.6.0            py35h61fcdcc_1
bitarray                  0.8.1            py35ha601307_0
bkcharts                  0.2              py35h4704c85_0
blaze                     0.11.3           py35hae12140_0
bleach                    2.1.1            py35h73b2768_0
bokeh                     0.12.11          py35h969371a_0
boto                      2.48.0           py35ha0bef00_1
bottleneck                1.2.1            py35h8a3671c_0
bzip2                     1.0.6                haa5b126_2
ca-certificates           2017.08.26           h94faf87_0
cachecontrol              0.12.3           py35h3f82863_0
certifi                   2017.11.5        py35h456c6ae_0
certifi                   2017.11.5                 <pip>
cffi                      1.11.2           py35h74ad5ef_0
chardet                   3.0.4            py35h177e1b7_1
chest                     0.2.3                    py35_0
click                     6.7              py35h10df73f_0
cloudpickle               0.5.2            py35hd830302_0
clyent                    1.2.2            py35h3cd9751_1
colorama                  0.3.9            py35h32a752f_0
comtypes                  1.1.2            py35hfae9076_0
conda                     4.3.30           py35hec795fb_0
conda-build               3.1.0            py35h5a4bd72_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py35h84a86bd_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py35h0a97e54_0
coverage                  4.4.2            py35h1d76e2e_0
cryptography              2.1.4            py35h8ead9e0_0
curl                      7.55.1               h3b839b5_4
cycler                    0.10.0           py35hcc71164_0
cymem                     1.31.2           py35h3642f57_0
cython                    0.27.3           py35h82876f0_0
cytoolz                   0.8.2            py35h6a98e29_0
dask                      0.16.0           py35hc436b91_0
dask-core                 0.16.0           py35h0988329_0
datashape                 0.5.4            py35ha38994c_0
decorator                 4.1.2            py35hc7d1f2e_0
dill                      0.2.7.1          py35hfe367cb_0
distlib                   0.2.5            py35h12c42d7_0
distributed               1.20.1           py35h3ced2a0_0
django                    1.11.3                   py35_0
docutils                  0.14             py35h8ccb97f_0
dynd-python               0.7.2                    py35_0
entrypoints               0.2.3            py35hb91ced9_2
et_xmlfile                1.0.1            py35h2c13def_0
fastcache                 1.0.2            py35h8710e77_0
filelock                  2.0.13           py35hed8fc95_0
flask                     0.12.2           py35he898f9a_0
flask-cors                3.0.3            py35h5700fb0_0
freetype                  2.8                  h51f8f2c_1
ftfy                      4.4.3            py35h615266c_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py35hb3d9581_0
glob2                     0.6              py35h9eb15d0_0
greenlet                  0.4.12           py35h0b77e5a_0
h5py                      2.7.1            py35hb2c3add_0
hdf5                      1.10.1               h98b8871_1
heapdict                  1.0.0            py35h3d1311d_0
html5lib                  0.999999999      py35h79d4e7f_0
hypothesis                3.38.5           py35h37a2ca4_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.6              py35h8dcb9ae_1
imageio                   2.2.0            py35hcd4b9a4_0
imagesize                 0.7.1            py35h7f87e83_0
intel-openmp              2018.0.0             hd92c6cd_8
ipykernel                 4.6.1            py35hab2028a_0
ipython                   6.2.1            py35h4a2ac14_1
ipython_genutils          0.2.0            py35ha709e79_0
ipywidgets                7.0.5            py35h49ade1d_0
isort                     4.2.15           py35h0bf7b49_0
itsdangerous              0.24             py35h99d45d4_1
jdcal                     1.3              py35h49a1460_0
jedi                      0.10.2           py35h3350e2d_0
jinja2                    2.10             py35hdf652bb_0
joblib                    0.11                     py35_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py35h27d56d3_0
jupyter                   1.0.0            py35hce9caf1_2
jupyter_client            5.1.0            py35hcddec19_0
jupyter_console           5.2.0            py35hf76c22e_1
jupyter_core              4.4.0            py35h629ba7f_0
jupyterlab                0.27.0           py35hf0f7bbb_2
jupyterlab_launcher       0.4.0            py35h7c94a28_0
keyring                   10.5.0           py35h82e68d4_0
lazy-object-proxy         1.3.1            py35he996729_0
libdynd                   0.7.2                         0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.32               h140d38e_4
libssh2                   1.8.0                h75d9407_3
libtiff                   4.0.9                h0f13578_0
libxml2                   2.9.4                h41ea7b2_6
libxslt                   1.1.29               h0037b19_6
llvmlite                  0.20.0                   py35_0
locket                    0.2.0            py35h0dfcdd0_1
lockfile                  0.12.2           py35h667c6d9_0
lxml                      4.1.1            py35ha957a02_0
lzo                       2.10                 h6df0209_2
markupsafe                1.0              py35hc253e08_1
matplotlib                2.1.0            py35hea29350_0
mccabe                    0.6.1            py35hcf31250_1
menuinst                  1.4.10           py35hb57c5a5_0
mistune                   0.8.1            py35h7e79247_0
mkl                       2018.0.1             h2108138_4
mkl-service               1.1.2            py35h051acba_4
mpmath                    1.0.0            py35h253b693_2
msgpack-python            0.4.8            py35hdef45cb_0
multipledispatch          0.4.9            py35hfb38682_0
murmurhash                0.26.4           py35h1512bc8_0
navigator-updater         0.1.0            py35h1d043e2_0
nb_anacondacloud          1.4.0                    py35_0
nb_conda                  2.2.0                    py35_0
nb_conda_kernels          2.1.0                    py35_0
nbconvert                 5.3.1            py35h98d6c46_0
nbformat                  4.4.0            py35h908c9d9_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11             py35h097edc8_0
nltk                      3.2.5            py35hbbcff45_0
nose                      1.3.7            py35h0e9586c_2
notebook                  5.2.2            py35h2b96da0_0
numba                     0.35.0             np113py35_10
numexpr                   2.6.4            py35hb78e28a_0
numpy                     1.13.3           py35hb7e80fb_0
numpydoc                  0.7.0            py35h72ac4f2_0
odo                       0.5.1            py35hc850252_0
olefile                   0.44             py35h7ba86d0_0
openpyxl                  2.4.9            py35h572dd3b_0
openssl                   1.0.2m               h093b818_1
orange3                   3.4.1                    py35_0
packaging                 16.8             py35h5fb721f_1
pandas                    0.21.0           py35h0510043_1
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py35h978f723_1
parso                     0.1.1            py35he39c48a_0
partd                     0.3.8            py35h894d1e4_0
patch                     2.5.9                         1
path.py                   10.5             py35h3b5be1d_0
pathlib                   1.0.1                    py35_0
pathlib2                  2.3.0            py35h4f1e8f6_0
patsy                     0.4.1            py35h01e4a18_0
pep8                      1.7.0            py35h15aeeed_0
pickleshare               0.7.4            py35h2f9f535_0
pillow                    4.3.0            py35h967e314_1
pip                       9.0.1            py35h691316f_4
pkginfo                   1.4.1            py35hb922f74_1
plac                      0.9.6                    py35_0
pluggy                    0.6.0            py35h717ee57_0
ply                       3.10             py35hb60f152_0
preshed                   1.0.0            py35h47f38c0_0
progress                  1.3              py35ha84af61_0
prompt_toolkit            1.0.15           py35h89c7cb4_0
psutil                    5.4.1            py35h5f28cdc_0
py                        1.5.2            py35h4fcc378_0
pyasn1                    0.4.2            py35hd2f34a6_0
pycodestyle               2.3.1            py35h35694a3_0
pycosat                   0.6.3            py35h456c199_0
pycparser                 2.18             py35h15a15da_1
pycrypto                  2.6.1            py35h8890bb5_1
pycurl                    7.43.0           py35hd6f0fee_3
pyflakes                  1.6.0            py35hb7fdafe_0
pygments                  2.2.0            py35h24c0941_0
pylint                    1.7.4            py35h717b2e0_0
pymongo                   3.4.0                    py35_0
pympler                   0.5              py35h0fea292_0
pyodbc                    4.0.21           py35h20c60d8_0
pyopenssl                 17.5.0           py35h75c5b16_0
pyparsing                 2.2.0            py35hcabcaab_1
pyqt                      5.6.0            py35hd46907b_5
pyqtgraph                 0.10.0                   py35_0
pyreadline                2.1              py35h9d47d9c_1
pysocks                   1.6.7            py35hb30ac0d_1
pytables                  3.4.2            py35h9e98cc6_2
pytest                    3.3.0            py35h465e706_0
python                    3.5.4               h1357f44_23
python-dateutil           2.6.1            py35h6b299a3_1
pytz                      2017.3           py35hb294b1a_0
pywavelets                0.5.2            py35h7c47ace_0
pywin32                   221              py35h14ddfd5_0
pyyaml                    3.12             py35h4bf9689_1
pyzmq                     16.0.3           py35h1861011_0
qt                        5.6.2           vc14h6f8c307_12  [vc14]
qtawesome                 0.4.4            py35h639d0ff_0
qtconsole                 4.3.1            py35hc47b0dd_0
qtpy                      1.3.1            py35h4918c39_0
regex                     2017.11.09       py35h3dee244_0
requests                  2.18.4           py35h54a615f_1
rope                      0.10.7           py35h5756fe0_0
ruamel_yaml               0.11.14          py35h7ef29f8_2
scikit-image              0.13.1           py35ha2243b5_0
scikit-learn              0.19.1           py35h2037775_0
scipy                     1.0.0            py35h75710e8_0
seaborn                   0.8.1            py35hc73483e_0
semver                    2.4.1                    py35_0    spacy
setuptools                36.5.0           py35h21a22e4_0
simplegeneric             0.8.1            py35h6406082_0
singledispatch            3.4.0.3          py35h33f66b4_0
sip                       4.18.1           py35h01cbaa7_2
six                       1.11.0           py35hc1da2df_1
snowballstemmer           1.2.1            py35h4c55bfa_0
sockjs-tornado            1.0.3                    py35_0
sortedcollections         0.5.3            py35h4a7ff62_0
sortedcontainers          1.5.7            py35h9857911_0
spacy                     1.9.0           py35_vc14hcdb467c_1  [vc14]
sphinx                    1.6.3            py35heeac824_0
sphinx_rtd_theme          0.2.4                    py35_0
sphinxcontrib             1.0              py35h45f5ca3_1
sphinxcontrib-websupport  1.0.1            py35ha3690eb_1
sputnik                   0.9.3                    py35_0    spacy
spyder                    3.2.4            py35h467e5b4_0
sqlalchemy                1.1.13           py35h5463dee_0
sqlite                    3.20.1               h9eeafa9_2
statsmodels               0.8.0            py35hfa6034c_0
sympy                     1.1.1            py35ha5375ed_0
tblib                     1.3.2            py35hd2cf7e1_0
termcolor                 1.1.0                    py35_0
testpath                  0.3.1            py35h06cf69e_0
thinc                     6.5.2           py35_vc14h2607e83_0  [vc14]
tk                        8.6.7                hcb92d03_3
toolz                     0.8.2            py35h7afdc4e_0
tornado                   4.5.2            py35h03246f3_0
tqdm                      4.19.4           py35h1d89acb_0
traitlets                 4.3.2            py35h09b975b_0
typing                    3.6.2            py35h37628ea_0
ujson                     1.35                     py35_0
unicodecsv                0.14.1           py35h0d88516_0
urllib3                   1.22             py35h8cc84eb_0
vc                        14                   h2379b0c_2
vs2015_runtime            14.0.25123           hd4c4e62_2
wcwidth                   0.1.7            py35h6e80d8a_0
webencodings              0.5.1            py35h5d527fb_1
werkzeug                  0.12.2           py35hc854123_0
wheel                     0.30.0           py35h38a90bc_1
widgetsnbextension        3.0.8            py35hdf37555_0
win_inet_pton             1.0.1            py35hbef1270_1
win_unicode_console       0.5              py35h56988b5_0
wincertstore              0.2              py35hfebbdb8_0
wrapt                     1.10.11          py35h54666f7_0
xlrd                      1.1.0            py35h22b952b_1
xlsxwriter                1.0.2            py35h6052a16_0
xlwings                   0.11.4           py35he637782_0
xlwt                      1.3.0            py35hd04410a_0
yaml                      0.1.7                hc54c509_2
zict                      0.1.3            py35hf5542e0_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py35_0
zope.interface            4.4.3            py35h57d3274_0

**Comment by greg-amato** [comment]
More dependency errors trying in install 5.0.1 

(root) C:\Users\grega>conda install anaconda=5.0.1
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda 5.0.1* -> alabaster 0.7.10 py36hcd07829_0 -> python >=3.6,<3.7.0a0
  - anaconda 5.0.1* -> asn1crypto 0.22.0 py36h8e79faa_1
  - anaconda 5.0.1* -> cachecontrol 0.12.3 py36hfe50d7b_0
  - anaconda 5.0.1* -> certifi 2017.7.27.1 py36h043bc9e_0
  - anaconda 5.0.1* -> cffi 1.10.0 py36hae3d1b5_1
  - anaconda 5.0.1* -> colorama 0.3.9 py36h029ae33_0
  - anaconda 5.0.1* -> cryptography 2.0.3 py36h123decb_1
  - anaconda 5.0.1* -> distlib 0.2.5 py36h51371be_0
  - anaconda 5.0.1* -> enum34 1.1.6 py27h2aa175b_1
  - anaconda 5.0.1* -> ipaddress 1.0.18 py27h08e1fa7_0
  - anaconda 5.0.1* -> lockfile 0.12.2 py36h0468280_0
  - anaconda 5.0.1* -> packaging 16.8 py36ha0986f6_1
  - anaconda 5.0.1* -> progress 1.3 py36hbeca8d3_0
  - anaconda 5.0.1* -> pyopenssl 17.2.0 py36h15ca2fc_0
  - anaconda 5.0.1* -> pysocks 1.6.7 py36h698d350_1
  - anaconda 5.0.1* -> urllib3 1.22 py36h276f60a_0
  - anaconda 5.0.1* -> webencodings 0.5.1 py36h67c50ae_1
  - anaconda 5.0.1* -> wheel 0.29.0 py36h6ce6cde_1
  - anaconda 5.0.1* -> wincertstore 0.2 py36h7fe50ca_0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by ozancaglayan** [comment]
Constantly having conflicts and downgrades since 3 weeks for networkx and scikit-image. Now jedi and parso came into play as well.

My anaconda version shows as `custom` and I can't force an install of 5.0.1:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.1.0
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /caglayan/anaconda3  (writable)
    default environment : /caglayan/anaconda3
       envs directories : /caglayan/anaconda3/envs
                          /caglayan/.conda/envs
          package cache : /caglayan/anaconda3/pkgs
                          /caglayan/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
```

```
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda 5.0.1*
  - flake8
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by greg-amato** [comment]
@ozancaglayan thanks for adding. scope of issues look related... those 4 modules are in disagreement for me (scikit, parso, jedi, networkx).  

Interesting that i'm getting "AttributeError: module 'sphinx' has no attribute '__version__'" when it's clearly defined reviewing the library.

**Comment by ozancaglayan** [comment]
I dont have any problem with notebooks or whatsoever but this downgrade and conflict thing is happening since some weeks for me.

**Comment by jjhelmus** [comment]
The `parso` and `jedi` multiple resolution should be fixed now and we are working on a fix for the `scikit-image`/`networkx` multiple resolution issue.  

Briefly, the latest release of `scikit-image` requires `networkx` be to strictly less than version 2.0.  Previous releases of `scikit-image` did not limit the `networkx` requirement (but should have).  Given this, the solver in conda is not sure if it should install the latest version of `networkx`, which is above 2.0, and an older version of `scikit-image`, or the latest version of `scikit-image` and an older release of `networkx`

@greg-amato  I believe the multiple resolution issue was not directly related to the inability to run `jupyter notebook`.  Are you still having issues.  If so you might try reinstalling sphinx using `conda install --force sphinx`.  Alternatively you could create a separate conda environment using `conda create -n notebook python=3.6 notebook` form which you could launch a Notebook.

Updating the root environment to anaconda 5.0.1 may be tricky as you have Python 3.5 installed and 5.0.1 requires Python 3.6.  Removing Anaconda entirely and reinstalled the latest version should work if this acceptable

**Comment by greg-amato** [comment]
Thanks @jjhelmus. Pointing out not being on python 3.6 helped.  Not sure why that hadn't updated since becoming the default versions.  I was able to follow this article to get python 3.6 and on anaconda 5.0.1
https://support.anaconda.com/customer/en/portal/articles/2797011-updating-anaconda-to-python-3-6
