### ISSUE TITLE
Jedi 0.9.0 in Anaconda 4.0.5 (Python 3.5) is NOT supported by Spyder 2.3.8 from the same bundle

### ISSUE THREAD

**Issue by pbentkowski** [ContinuumIO/anaconda-issues#768]
Spyder 2.3.8 DOES NOT support jedi 0.9.0 which comes with Anaconda 4.0.5 Python 3.5. See this post:
https://mail-index.netbsd.org/pkgsrc-wip-changes/2015/11/28/msg000754.html

I also could not downgrade to jedi 0.8.1 with 
`conda install jedi=0.8.1`
due to "specifications in conflict"

My specs: Python 3.5.1 | Anaconda 4.0.5 (linux-64 bit) | (default, Dec  7 2015, 11:16:01) | GNU/Linux [*]ubuntu 14.04

Spyder is the prime reason for having jedi in the bundle.

**Comment by ccordoba12** [comment]
I'll see what we can do to solve this issue. Thanks for reporting :-)

**Comment by ccordoba12** [comment]
I think we don't have time to fix this one, but you can use `pip` to install this version of Jedi in the meantime:

    pip install jedi==0.8.1

**Comment by pbentkowski** [comment]
OK. I did it. 
Is lack of auto-completion of file paths a jedi issue ?

**Comment by ccordoba12** [comment]
I don't think Jedi is able to do path completions, sorry.

**Comment by ccordoba12** [comment]
I think there's nothing else we can do about this one.

**Comment by pbentkowski** [comment]
Yup... I moved to a newer version of both, Spyder and Jedi. Thanks for having a look at this one.
