### ISSUE TITLE
accessing HDF5 attributes with h5py on 64-bit Windows segfaults Python

### ISSUE THREAD

**Issue by newville** [ContinuumIO/anaconda-issues#7686]
With a fresh install of Anaconda 2 5.0.1 on 64-bit Windows, accessing HDF5 attributes with h5py will segfault Python:

    Python 2.7.14 |Anaconda custom (64-bit)| (default, Nov  8 2017, 13:40:45) [MSC v.1500 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import h5py
    >>> h5py.__version__
    '2.7.1'
    >> t = h5py.File('T.h5')
    >> t['/top'].attrs
    <Attributes of HDF5 object at 73476144>
    >> t['/top'].attrs.keys()
    [u'attr1', u'attr2']
    >>> print( t['/top'].attrs['attr1'])

Accessing the attribute values crashes Python.  

I don't see that with Anaconda 2 4.4.0, h5py 2.7.0, or on other systems.  

For reference, an h5dump of the file looks like this:

```
Enter code herHDF5 "T.h5" {
GROUP "/" {
   GROUP "top" {
      ATTRIBUTE "attr1" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "a string"
         }
      }
      ATTRIBUTE "attr2" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "something else"
         }
      }
      DATASET "image" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 10, 10 ) / ( 10, 10 ) }
         DATA {
         (0,0): 0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45,
         (1,0): 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95,
         (2,0): 1, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45,
         (3,0): 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95,
         (4,0): 2, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.35, 2.4, 2.45,
         (5,0): 2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95,
         (6,0): 3, 3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.45,
         (7,0): 3.5, 3.55, 3.6, 3.65, 3.7, 3.75, 3.8, 3.85, 3.9, 3.95,
         (8,0): 4, 4.05, 4.1, 4.15, 4.2, 4.25, 4.3, 4.35, 4.4, 4.45,
         (9,0): 4.5, 4.55, 4.6, 4.65, 4.7, 4.75, 4.8, 4.85, 4.9, 4.95
         }
      }
   }
}
}

```

**Comment by newville** [comment]
Are there any suggestions or workarounds for this problem?  
At the moment, this is restricting me to using Anaconda 4.4 on Windows 64.

**Comment by nehaljwani** [comment]
@newville Could you also share the version of Windows that you are able to reproduce this error on?

**Comment by newville** [comment]
Windows 7 Professional.

**Comment by nehaljwani** [comment]
If you have access to a Windows 10 machine, could you please check if you are able to reproduce the same error there?

**Comment by newville** [comment]
It does work on Windows 10.  I've tried combinations of Python 3.6.3 and Python 2.7 and verified it works  with h5py 2.7.0 (as installed with 5.0.1 installer) and h5py 2.7.1 (as after `conda update --all`).

**Comment by newville** [comment]
@nehaljwani also: h5py 2.7.1 from conda-forge works on Windows 7 (64bit).

**Comment by nehaljwani** [comment]
@newville I don't know how to convert this DDL file back to .5 . Would it be possible for you to share the .5 file?

**Comment by newville** [comment]
@nehaljwani A file created with

``` python
import numpy as np
import h5py

fh = h5py.File('test.h5', 'w')
fh.create_group('/top') 
fh['/top'].attrs['attr1'] = 'Test Attribute 1'
fh['/top'].attrs['attr2'] = 'Test Attribute 2'
fh['/top'].create_dataset('image', data=np.arange(1000)/3.0)
fh.flush()
fh.close()
```

will show the problem:

```python
import h5py
fh = h5py.File('test.h5', 'r')
fh['/top'].attrs['attr1']
```

crashes Python.  It appears to be only on Windows 7 with h5py 2.7.1 from Anaconda, not from conda-forge.

**Comment by nehaljwani** [comment]
Thanks, I was able to reproduce this in an isolated environment. The crash report generated by Windows had:
```
Faulting application name: python.exe, version: 0.0.0.0, time stamp: 0x5a0379fd
Faulting module name: ntdll.dll, version: 6.1.7601.23796, time stamp: 0x590296ce
Exception code: 0xc0000005
Fault offset: 0x000000000004f2a2
Faulting process id: 0x5980
Faulting application start time: 0x01d3799c7ef566f0
Faulting application path: F:\nwani\installers\mc3\envs\h5pytest\python.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: bcb9bf93-e58f-11e7-842a-0cc47a798155
```

**Comment by nehaljwani** [comment]
So far, I have found this:
- If I build the recipe for hdf5 on Windows 10 and then use that dll on Windows 7, the above example crashes py27.
- If I build the recipe for hdf5 on Windows 7 and then use that dll on Windows 7, then above example doesn't crash py27.

**Comment by nehaljwani** [comment]
@newville I have uploaded new builds at https://anaconda.org/nehaljwani/hdf5 . Could you try `conda install -c nehaljwani hdf5` and let us know whether they solve your issue?

**Comment by nehaljwani** [comment]
The win7 builds of hdf5 are now on defaults. 

Feel free to reopen the issue if the new packages are still problematic.

**Comment by newville** [comment]
@nehaljwani  Thanks!
