### ISSUE TITLE
Missing Windows binaries for R

### ISSUE THREAD

**Issue by ColinTalbert** [ContinuumIO/anaconda-issues#770]
I'm trying to update R in my Windows 64 in conda with:

[condaR] >conda install -c r r=3.2.2
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..................
Solving package specifications: .
Error:  Package missing in current win-64 channels:
- r 3.2.2*

You can search for this package on anaconda.org with

```
anaconda search -t conda r 3.2.2*
```

and indeed on https://anaconda.org/r/r/files I don't see any windows builds since version 3.1.3

**Comment by mingwandroid** [comment]
Hi @ColinTalbert. We haven't released R > 3.1.3 for Windows yet, except for the MRO (Mircosoft R Open) version, which you can install using `conda install -c mro r=3.2.3`. It's at version 3.2.3.

Soon (either tonight or early on Monday) I will upload new builds of R 3.2.4 for Windows.

**Comment by mingwandroid** [comment]
Fixed.
