### ISSUE TITLE
Two C paths in Anaconda prompt

### ISSUE THREAD

**Issue by sdgp** [ContinuumIO/anaconda-issues#7709]
New to anaconda. I am seeing two C: paths in the Anaconda prompt. What's the difference ? 

C:\Anaconda\envs\python3.6) C:\Users\Administrator

I can't go back to the first C:\ path when I do cd ..

Is this normal ?

**Comment by msarahan** [comment]
Yes, totally normal.  The first path is the conda environment that is active.  The second is your current working directory.
