### ISSUE TITLE
Anaconda package for opencv3 has error

### ISSUE THREAD

**Issue by Halo-5** [ContinuumIO/anaconda-issues#771]
Installed the latest anaconda 4.0 (python 2.7.11 64 bit)

Installed this:

`conda install --channel https://conda.anaconda.org/menpo opencv3
`
This works:

`import cv2`
This simple script fails

```
import cv2
#import numpy as np
#import matplotlib.pyplot as plt

cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

while True:
    ret, frame = cap.read()
    #modify the frame
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    yarg = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
    out.write(frame)
    #show them both but the first one gets most stuttery
    cv2.imshow('gray',gray)
    cv2.imshow('frame',frame)
    cv2.imshow('yarg',yarg)


    if cv2.waitKey(1) & 0xFF ==ord('q'):
        break

cap.release()
out.release()
cv2.destroyAllWindows() 
```
With the error

```
OpenCV Error: Assertion failed (dst.data == dst0.data) in cvCvtColor, file /Users/jenkins/miniconda/0/2.7/conda-bld/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 8479
Traceback (most recent call last):
  File "cv2.py", line 17, in <module>
    out.write(frame)
cv2.error: /Users/jenkins/miniconda/0/2.7/conda-bld/work/opencv-3.1.0/modules/imgproc/src/color.cpp:8479: error: (-215) dst.data == dst0.data in function cvCvtColor

Cleaned up camera.

```

And my user name is not jenkins.

**Comment by msarahan** [comment]
Sorry, this is a community provided package.  We (continuum) do not build
or maintain this package, only host it on our site to make it easier to
obtain.  Please try to contact the maintainer(s) of the menpo channel.

**Comment by Halo-5** [comment]
how do i do that? there is no contact info at
https://conda.anaconda.org/menpo?
And wasn't there an opencv package by you as well?

**Comment by msarahan** [comment]
The second hit on Google for "menpo" took me here: http://www.menpo.org/

I have packaged OpenCV, yes.  I also packaged the memex channel OpenCV
packages.  Those were funded by DARPA.  I am currently not funded for that
work, and thus cannot guarantee any level of support.

Your error message includes "jenkins" because the menpo maintainers
probably built it with a jenkins build control server.  It has nothing to
do with the actual content of the message.  The error itself is likely some
data error - not an error in OpenCV itself, but an error in the data you're
feeding to OpenCV.  I am not experienced with video applications of OpenCV,
and can't offer any support here.  You might need to ask about this on the
OpenCV mailing list.

**Comment by zhanghan328** [comment]
I have the same problem. How can i do?

**Comment by BryanBo-Cao** [comment]
Same here

**Comment by ah3243** [comment]
Hey just got this problem. Seems to throw the error when trying to write to file. Has anyone found the source of the problem/a solution?

**Comment by ah3243** [comment]
The SOLUTION is to make sure the output object has the same size/attributes as the frame you're attempting to add to it. So it needs three channels and to be the same height and width. 

Either use 'frame.shape' to find out the size of your image(https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.html) and adjust the cv2.videoWriter parameters accordingly 

OR 

resize the frame (to the height and width you entered in cv2.videoWriter) before trying to save it.

**Comment by Maneeshmohan1** [comment]
cv2.imshow ,cvtcolor etc.. are not working in my conda enviornment
/home/travis/miniconda/conda-bld/conda_1486587069159/work/opencv-3.1.0/modules/highgui/src/window.cpp:281: error: (-215) size.width>0 && size.height>0 in function imshow
