### ISSUE TITLE
i install anaconda but get problem to add system PATH

### ISSUE THREAD

**Issue by kamran97** [ContinuumIO/anaconda-issues#7718]
![25198898_2074938586126492_77809662_o](https://user-images.githubusercontent.com/34417287/33805184-d5d2d3ee-ddcd-11e7-9463-8c2f0474c01c.jpg)
like that

**Comment by csoja** [comment]
This is not a problem - simply a warning, that we recommend using Anaconda Navigator or Anaconda Prompt, and not adding Anaconda to your path on Windows.
