### ISSUE TITLE
Anaconda3-5.0.1-Windows-x86_64.exe is broken

### ISSUE THREAD

**Issue by johngrabner** [ContinuumIO/anaconda-issues#7721]
on a fresh pc, windows 10
installed https://www.anaconda.com/download/
64-Bit Graphical Installer (515 MB)

![image](https://user-images.githubusercontent.com/8209285/33808487-ef5a7dc4-ddac-11e7-97d5-b6edf2402426.png)

launched jupyter
and get the following error on the console
[W 13:11:34.579 NotebookApp] 404 GET /static/tree/js/main.min.js (::1) 2.03ms referer=http://localhost:8888/tree

copied 
http://localhost:8888/?token=6e4c30186b1989a3e0768b28b5a7ffdbb43f1a9fe3a75c77
to the browser and get the same 404 error 

tried installing tensorflow
... conda create -n tensorflow python=3.6
... activate tensorflow
... pip install --ignore-installed --upgrade tensorflow-gpu 
... do the hello test ... tensorflow works

but launching jupyter from the start gets me same 404 error
[W 13:26:11.741 NotebookApp] 404 GET /static/tree/js/main.min.js (::1) 1.00ms referer=http://localhost:8888/tree?token=c710949014416c80d9179daf87d50e4eb6e5e9a242be78d0

the above occurs with chrome and edge browsers.

**Comment by johngrabner** [comment]
the full log when I launch jupyter

[I 13:30:17.213 NotebookApp] Serving notebooks from local directory: C:\Users\john_
[I 13:30:17.213 NotebookApp] 0 active kernels
[I 13:30:17.213 NotebookApp] The Jupyter Notebook is running at:
[I 13:30:17.213 NotebookApp] http://localhost:8888/?token=fe7006c91fd3c6187921525404783cd8f1ef5d666981e3d2
[I 13:30:17.213 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:30:17.217 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=fe7006c91fd3c6187921525404783cd8f1ef5d666981e3d2
[I 13:30:17.339 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[E 13:30:17.377 NotebookApp] Could not open static file ''
[W 13:30:17.407 NotebookApp] 404 GET /static/components/preact/index.js (::1) 6.01ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.409 NotebookApp] 404 GET /static/components/es6-promise/promise.min.js (::1) 2.04ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.410 NotebookApp] 404 GET /static/components/requirejs/require.js (::1) 0.97ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.412 NotebookApp] 404 GET /static/components/preact-compat/index.js (::1) 2.00ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.414 NotebookApp] 404 GET /static/components/proptypes/index.js (::1) 1.00ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.417 NotebookApp] 404 GET /static/tree/js/main.min.js (::1) 2.00ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.561 NotebookApp] 404 GET /static/components/preact/index.js (::1) 2.03ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.564 NotebookApp] 404 GET /static/components/proptypes/index.js (::1) 1.00ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.566 NotebookApp] 404 GET /static/components/preact-compat/index.js (::1) 1.00ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.569 NotebookApp] 404 GET /static/components/requirejs/require.js (::1) 1.00ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7
[W 13:30:17.574 NotebookApp] 404 GET /static/tree/js/main.min.js (::1) 0.99ms referer=http://localhost:8888/tree?token=887f69ec077eb3560879f40185389beb7d0e08757f01c6c7

**Comment by johngrabner** [comment]
restored windows to fresh install of windows.
reinstalled https://www.anaconda.com/download/
but this time specified for all users.
Same 404 error.

So clear that install + instructions do not work on a clean windows 10 install

**Comment by johngrabner** [comment]
disabled everything in windows defender, jupyter still does not work

**Comment by johngrabner** [comment]
installed nodejs ... does not help

**Comment by johngrabner** [comment]
run as administrator does not help

**Comment by kerrywatson1** [comment]
John, I am not a Windows user but believe you need to run Jupyter from Anaconda Navigator or Anaconda Prompt. You cannot run it from Windows Start menu. Somebody can correct me if I am wrong.

**Comment by johngrabner** [comment]
The installer has a checkbox for "Add Anaconda to my PATH environment variable" with the message "Not recommended. Instead, open Anaconda with the Windows Start menu and select Anaconda (64-bit).
Thanks for the suggestion.
Tested also from the anaconda console. Same outcome.
Tested from the Navigator.  Same outcome.
Because this is a fresh PC and fresh install of Windows 10, I suspect some dependency is missing.

**Comment by johngrabner** [comment]
turned off windows defender and turned off window firewall did not help.

**Comment by johngrabner** [comment]
changed default installation location to "C:\Users\john_\Documents\Anaconda" did not help.

**Comment by johngrabner** [comment]
reinstalled windows, and anaconda / jupyter now works.
I suspect that my installation of python then its removal before trying anaconda was not 100% clean.

**Comment by johngrabner** [comment]
reinstalled windows, and anaconda / jupyter now works.
I suspect that my installation of python then its removal before trying anaconda was not 100% clean.
