### ISSUE TITLE
Navigator Won#t launch

### ISSUE THREAD

**Issue by omoifodarling** [ContinuumIO/anaconda-issues#7742]
I run anaconda (5.0.1 with python 3.6.3) for my deep learning project on windows with GPU. When I started off it worked fine. But just after one week it stopped launching when I click from the start the anaconda/navigator. This is a bug as the application seems to have a life/cycle of about a week and then goes off - done this about thrice now. I would always have to uninstall and reinstall. This is a painful approach as K have loads of libraries installed and I often would have to do this again.

**Comment by goanpeca** [comment]
@omoifodarling, next time it fails, could you please open the Anaconda Prompt and type


```
anaconda-navigator
```

And paste any traceback, you should not need to reinstall everything.

**Comment by goanpeca** [comment]
No feedback provided. Closing.
