### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Elpiro** [ContinuumIO/anaconda-issues#7779]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 26, in <module>
    import pandas as pd
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\__init__.py", line 13, in <module>
    __import__(dependency)
  File "C:\Program Files\Anaconda3\lib\site-packages\numpy\__init__.py", line 152, in <module>
    test = testing.nosetester._numpy_tester().test
NameError: name 'testing' is not defined

```
## System information
```
python: 3.6.1
language: fr_FR
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
The traceback seems to be incomplete. What were you trying to accomplish?

Please update to the latest version of anaconda navigator 

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Comment by Elpiro** [comment]
For no reason, spyder crashed and wouldn't start again. That's after trying
to start spyder from Anaconda navigator that I get this issue.

A simple restart of the computer solved the problem. I don't know more
about the issue that could help you reproduce it.


Best regards and thanks for this wonderful product,

Bertrand Gallice

Le 15 déc. 2017 13:14, "Gonzalo Peña-Castellanos" <notifications@github.com>
a écrit :

The traceback seems to be incomplete. What were you trying to accomplish?

Please update to the latest version of anaconda navigator

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on
windows)
and type:

$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ContinuumIO/anaconda-issues/issues/7779#issuecomment-351991587>,
or mute the thread

**Comment by goanpeca** [comment]
>For no reason, spyder crashed and wouldn't start again. That's after trying
to start spyder from Anaconda navigator that I get this issue.

>A simple restart of the computer solved the problem. I don't know more
about the issue that could help you reproduce it.


Ok if you experience the problem again, please lt us know. Feel free to open a new issue with as much details as possible of the action being executed at the moment.
