### ISSUE TITLE
Anaconda navigator goes blank without showing anything on fedora 22

### ISSUE THREAD

**Issue by bhuvan-nrsc** [ContinuumIO/anaconda-issues#778]
I have installed anaconda package on fedora 22 and when i type anaconda-navigator as root it starts showing the error

Qt: Session management error: None of the authentication protocols specified are supported
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x1000002
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x1000009
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x1000009
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x1000009

can somebody help me out in solving the problem

**Comment by goanpeca** [comment]
If you run it as a normal user (not root) do you experience the same issues?

**Comment by bhuvan-nrsc** [comment]
yes iam facing the same issue even when i run it as a normal user

**Comment by stephenakearns** [comment]
@martindurant spent time looking at this issue - his solution: 

`conda install pango`

@bhuvan-nrsc can you test out and confirm. Please reopen if this doesn't resolve your issues.
