### ISSUE TITLE
Can't install schedule

### ISSUE THREAD

**Issue by ductam1987** [ContinuumIO/anaconda-issues#7810]
Please help me check the issue. Thanks.

$ conda search schedule
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:
            
  - schedule

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by csoja** [comment]
This means there is not a conda package available for schedule in the default repositories.  You can search on Anaconda Cloud https://anaconda.org/search?q=schedule for a conda package that might meet your needs - or you can pip install schedule  (https://pypi.python.org/pypi/schedule).
