### ISSUE TITLE
"Make starting directory for Jupyter Notebook configurable from Navigator"

### ISSUE THREAD

**Issue by PrinterMark** [ContinuumIO/anaconda-issues#7812]
Need to have a way to set the directory that Jupyter  starts from at Launch in Windows 10.

**Comment by goanpeca** [comment]
@PrinterMark thanks for the request. We are working on this feature and should be available in a newer release

**Comment by goanpeca** [comment]
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/983
