### ISSUE TITLE
Please provide PyTables for Numpy 1.11 for Windows

### ISSUE THREAD

**Issue by bryanwweber** [ContinuumIO/anaconda-issues#782]
Hello,
There are currently no builds of PyTables for Windows with Numpy 1.11, even though those packages exist for OS X and Linux: https://anaconda.org/anaconda/pytables/files Is it possible to build those packages for Windows?
Thank you!
Bryan

**Comment by marscher** [comment]
@msarahan could you please state if there is any reason not to provide these builds (compatibility reasons etc)?

**Comment by rmcgibbo** [comment]
+1 this would be really great to have. pytables is a key package that a lot of tools depend on, and this is a major blocker for upgrading to numpy 1.11

**Comment by csoja** [comment]
Closing this issue as PyTables has been updated for Numpy 1.11 in repo.continuum.io.

**Comment by marscher** [comment]
Greet! Thank you!
