### ISSUE TITLE
conda-build 1.20.1 broken on 32-bit Linux

### ISSUE THREAD

**Issue by benmwebb** [ContinuumIO/anaconda-issues#783]
`lib/python?.?/site-packages/conda_build/environ.py` contains the following:

    def linux_vars(compiler_vars, prefix):
        compiler_vars['LD_RUN_PATH'] = prefix + '/lib'
        if cc.bits == 32:
            compiler_vars['CFLAGS'] += ' -m 32'
            compiler_vars['CXXFLAGS'] += ' -m 32'
        return {}

Note the space between `-m` and `32`. This gets propagated to the `CFLAGS` and `CXXFLAGS` environment variables, and `-m 32` is not a valid `gcc` flag, so this causes any build that uses these variables (e.g. anything that uses `cmake`) to fail with something like

      cc1: error: unrecognized command line option "-m"

1.20.0 sets it to `-m32` instead and works correctly.

**Comment by msarahan** [comment]
Thanks for the report.  This is fixed in https://github.com/conda/conda-build/pull/916 - new release of conda build coming very soon - hopefully tomorrow.
