### ISSUE TITLE
why the default gcc is still 4.8.5

### ISSUE THREAD

**Issue by lidh15** [ContinuumIO/anaconda-issues#7831]
it drives me mad that anaconda controls the gcc and asks everyone to use 4.8.5 even after I have installed 5.4.0 and make many compilation fail.

**Comment by mingwandroid** [comment]
I'm not sure what you mean.

1. You shouldn't have Anaconda on your PATH when you are not using it. Use the activate scripts instead. That way your Anaconda software will only be found when it's activated.
2. We don't recommend that GCC package anymore. It's deprecated. We provide GCC 7.2.0 now-a-days, and the programs are not called `gcc` and `g++` so they don't get in the way of your system compilers (though they will be better than GCC 5.4.0 so I'd recommend using them when trying to work with Anaconda libraries and tools).
