### ISSUE TITLE
Windows7 - Anaconda Navigator not launching anymore when using icon

### ISSUE THREAD

**Issue by kochuyt** [ContinuumIO/anaconda-issues#7841]
Anaconda navigator icon no longer launches navigator on windows 7 (64-bit)

Current icon target:

    D:\Tooling\Conda3\pythonw.exe D:\Tooling\Conda3\cwp.py D:\Tooling\Conda3 "D:/Tooling/Conda3/pythonw.exe" "D:/Tooling/Conda3/Scripts/anaconda-navigator-script.py"

Current conda install:

               platform : win-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : D:\Tooling\Conda3  (writable)
    default environment : D:\Tooling\Conda3
       envs directories : D:\Tooling\Conda3\envs
                          C:\Users\tkochuyt\AppData\Local\conda\conda\envs
                          C:\Users\tkochuyt\.conda\envs
          package cache : D:\Tooling\Conda3\pkgs
                          C:\Users\tkochuyt\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\tkochuyt\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/3.6.3 Windows/7 Windows/6.1.7601    
          administrator : True

Current Anaconda Navigator install
    
    # packages in environment at D:\Tooling\Conda3:
    #
    anaconda-client           1.6.6            py36ha174c20_0    defaults
    anaconda-navigator        1.6.10           py36h51c3d4f_0    defaults
    anaconda-project          0.8.2            py36hfad2e28_0    defaults
    nb_anacondacloud          1.4.0                    py36_0    defaults

Additional info:
When launching navigator through shell, it launches but following error messages appear

    2017-12-19 09:46:27,015 - ERROR download_api._download:192
    Invalid URL '': No schema supplied. Perhaps you meant http://?

    2017-12-19 09:46:27,016 - ERROR download_api._download:197
    Invalid url

**Comment by goanpeca** [comment]
>Additional info:When launching navigator through shell, it launches but following error messages appear

Those messages are harmless and will be removed soon

Regarding that icon target, looks odd. @mingwandroid does it look like a normal target?

**Comment by jb16006** [comment]
Hi,

I have a similar problem with mine. When I launch anaconda navigator from either the icon or cmd, I get an error message saying:  'psutil.AccessDenied (pid=2016)'. I have done the following:

conda update anaconda-navigator
conda update anaconda
conda update navigator-updater

conda info

Current conda install:

               platform : win-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : C:\Users\jb16006\AppData\Local\Continuum\Anaconda2  (
ritable)
    default environment : C:\Users\jb16006\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\jb16006\AppData\Local\Continuum\Anaconda2\en
s
                          C:\Users\jb16006\AppData\Local\conda\conda\envs
                          C:\Users\jb16006\.conda\envs
          package cache : C:\Users\jb16006\AppData\Local\Continuum\Anaconda2\pk
s
                          C:\Users\jb16006\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\jb16006\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.14.2 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : False


conda list

_license                  1.1                      py27_1
alabaster                 0.7.10                   py27_0
anaconda                  custom           py27h689e5c3_0
anaconda-client           1.6.3                    py27_0
anaconda-navigator        1.6.10           py27hafe8de4_0
anaconda-project          0.6.0                    py27_0
asn1crypto                0.22.0                   py27_0
astroid                   1.4.9                    py27_0
astropy                   1.3.2               np112py27_0
babel                     2.4.0                    py27_0
backports                 1.0                      py27_0
backports_abc             0.5                      py27_0
basemap                   1.0.7               np112py27_0
beautifulsoup4            4.6.0                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.10.1                   py27_0
bleach                    1.5.0                    py27_0
bokeh                     0.12.5                   py27_1
boto                      2.46.1                   py27_0
bottleneck                1.2.1               np112py27_0
bzip2                     1.0.6                     vc9_3  [vc9]
ca-certificates           2017.08.26           h94faf87_0
cdecimal                  2.3                      py27_2
cffi                      1.10.0                   py27_0
chardet                   3.0.3                    py27_0
click                     6.7                      py27_0
click-plugins             1.0.3                    py27_0
cligj                     0.2.0                    py27_0
cloudpickle               0.2.2                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.9                    py27_0
comtypes                  1.1.2                    py27_0
conda                     4.3.31                   py27_0
conda-env                 2.6.0                h36134e3_1
configparser              3.5.0                    py27_0
console_shortcut          0.1.1                    py27_1
contextlib2               0.5.5                    py27_0
cryptography              1.8.1                    py27_0
curl                      7.52.1                    vc9_0  [vc9]
cycler                    0.10.0                   py27_0
cython                    0.25.2                   py27_0
cytoolz                   0.8.2                    py27_0
dask                      0.14.3                   py27_1
datashape                 0.5.4                    py27_0
decorator                 4.0.11                   py27_0
distributed               1.16.3                   py27_0
docutils                  0.13.1                   py27_0
entrypoints               0.2.2                    py27_1
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
expat                     2.2.5                h9878561_0
fastcache                 1.0.2                    py27_1
fiona                     1.7.10           py27ha5c57b9_0
flask                     0.12.2                   py27_0
flask-cors                3.0.2                    py27_0
freetype                  2.5.5                     vc9_2  [vc9]
freexl                    1.0.4                h1430290_5
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.1.1                    py27_0
gdal                      2.2.2            py27h58389d3_1
geos                      3.6.2                heec837b_2
get_terminal_size         1.0.0                    py27_0
gevent                    1.2.1                    py27_0
greenlet                  0.4.12                   py27_0
grin                      1.2.1                    py27_3
h5py                      2.7.1            py27h2dd4c20_0
hdf4                      4.2.13               hd0a9391_2
hdf5                      1.10.1               h08c2580_1
heapdict                  1.0.0                    py27_1
html5lib                  0.999                    py27_0
icc_rt                    2017.0.4             h97af966_0
icu                       57.1                      vc9_0  [vc9]
idna                      2.5                      py27_0
imagesize                 0.7.1                    py27_0
ipaddress                 1.0.18                   py27_0
ipykernel                 4.6.1                    py27_0
ipython                   5.3.0                    py27_0
ipython_genutils          0.2.0                    py27_0
ipywidgets                6.0.0                    py27_0
isort                     4.2.5                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.3                      py27_0
jedi                      0.10.2                   py27_2
jinja2                    2.9.6                    py27_0
jpeg                      9b                        vc9_0  [vc9]
jsonschema                2.6.0                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            5.0.1                    py27_0
jupyter_console           5.1.0                    py27_0
jupyter_core              4.3.0                    py27_0
kealib                    1.4.7                h40df8b5_5
lazy-object-proxy         1.2.2                    py27_0
libboost                  1.65.1            vc9h83875ae_3  [vc9]
libgdal                   2.2.2                h75964b3_1
libiconv                  1.15                 hda2e4ec_7
libkml                    1.3.0                h1826281_3
libnetcdf                 4.4.1.1              hbbeef04_8
libpng                    1.6.32               hc90de78_4
libpq                     9.6.6                h73434db_0
libspatialite             4.3.0a              hbf2645c_18
libtiff                   4.0.9                hafacce9_0
libxml2                   2.9.4                he44f8b2_6
llvmlite                  0.18.0                   py27_0
locket                    0.2.0                    py27_1
lxml                      3.7.3                    py27_0
lzo                       2.10                 h0bb7fe3_2
markupsafe                0.23                     py27_2
matplotlib                2.0.2               np112py27_0
matplotlib-scalebar       0.4.1                     <pip>
menuinst                  1.4.7                    py27_0
mistune                   0.7.4                    py27_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py27_3
mpmath                    0.19                     py27_1
msgpack-python            0.4.8                    py27_0
multipledispatch          0.4.9                    py27_0
munch                     2.2.0                    py27_0
navigator-updater         0.1.0            py27h5e42984_0
nbconvert                 5.1.1                    py27_0
nbformat                  4.3.0                    py27_0
netcdf4                   1.3.1            py27h45dfd53_2
networkx                  1.11                     py27_0
nltk                      3.2.3                    py27_0
nose                      1.3.7                    py27_1
notebook                  5.0.0                    py27_0
numba                     0.33.0              np112py27_0
numexpr                   2.6.2               np112py27_0
numpy                     1.12.1                   py27_0
numpydoc                  0.6.0                    py27_0
odo                       0.5.0                    py27_1
olefile                   0.44                     py27_0
openjpeg                  2.2.0                h70061b3_2
openpyxl                  2.4.7                    py27_0
openssl                   1.0.2n               hc64555f_0
packaging                 16.8                     py27_0
pandas                    0.20.1              np112py27_0
pandocfilters             1.4.1                    py27_0
partd                     0.3.8                    py27_0
path.py                   10.3.1                   py27_0
pathlib2                  2.2.1                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
pickleshare               0.7.4                    py27_0
pillow                    4.1.1                    py27_0
pip                       9.0.1                    py27_1
ply                       3.10                     py27_0
proj4                     4.9.3                h3980ba1_7
prompt_toolkit            1.0.14                   py27_0
psutil                    5.2.2                    py27_0
py                        1.4.33                   py27_0
pycosat                   0.6.2                    py27_0
pycparser                 2.17                     py27_0
pycrypto                  2.6.1                    py27_6
pycurl                    7.43.0                   py27_2
pyflakes                  1.5.0                    py27_0
pygments                  2.2.0                    py27_0
pylint                    1.6.4                    py27_1
pyodbc                    4.0.16                   py27_0
pyopenssl                 17.0.0                   py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_2
pyshp                     1.2.12                    <pip>
pytables                  3.4.2            py27h583b7c0_2
pytest                    3.0.7                    py27_0
python                    2.7.13                        1
python-dateutil           2.6.0                    py27_0
pytz                      2017.2                   py27_0
pywavelets                0.5.2               np112py27_0
pywin32                   220                      py27_2
pyyaml                    3.12                     py27_0
pyzmq                     16.0.2                   py27_0
qt                        5.6.2                     vc9_4  [vc9]
qtawesome                 0.4.4                    py27_0
qtconsole                 4.3.0                    py27_0
qtpy                      1.2.1                    py27_0
requests                  2.14.2                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_1
scandir                   1.5                      py27_0
scikit-image              0.13.0              np112py27_0
scikit-learn              0.18.1              np112py27_1
scipy                     0.19.0              np112py27_0
seaborn                   0.7.1                    py27_0
setuptools                27.2.0                   py27_1
shapely                   1.6.2            py27h014e281_0
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sortedcollections         0.5.3                    py27_0
sortedcontainers          1.5.7                    py27_0
sphinx                    1.5.6                    py27_0
spyder                    3.1.4                    py27_0
sqlalchemy                1.1.9                    py27_0
sqlite                    3.20.1               hcee4010_2
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.8.0               np112py27_0
subprocess32              3.2.7                    py27_0
sympy                     1.0                      py27_0
tblib                     1.3.2                    py27_0
testpath                  0.3                      py27_0
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.2                    py27_0
tornado                   4.5.1                    py27_0
traitlets                 4.3.2                    py27_0
unicodecsv                0.14.1                   py27_0
vc                        9                             0
vs2008_runtime            9.00.30729.5054               0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py27_0
werkzeug                  0.12.2                   py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        2.0.0                    py27_0
win_unicode_console       0.5                      py27_0
wrapt                     1.10.10                  py27_0
xerces-c                  3.2.0                hf00aa6f_2
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.6                    py27_0
xlwings                   0.10.4                   py27_0
xlwt                      1.2.0                    py27_0
zict                      0.1.2                    py27_0
zlib                      1.2.11               hbc2faf4_2


But still nothing. It still returns the same error message
Any help would be highly appreciated!!

**Comment by goanpeca** [comment]
This has been fixed. Closing
