### ISSUE TITLE
Unable to open notebook: Unknown Host Error

### ISSUE THREAD

**Issue by LakshayNagpal** [ContinuumIO/anaconda-issues#7843]
Hi,

I don't know but after few days, I opened anaconda navigator and when I launched jupyter notebook from navigator, a new tab opens as usual but the directory structure is not displayed instead everytime I see this.
<img width="1437" alt="screen shot 2017-12-19 at 4 25 32 pm" src="https://user-images.githubusercontent.com/9516787/34153792-4e48b124-e4d9-11e7-9039-a62a80b9d21e.png">
Description: Unable to locate the server named "localhost" --- the server does not have a DNS entry. Perhaps there is a misspelling in the server name, or the server no longer exists. Double-check the name and try again.

Here's the output displayed on terminal
<img width="847" alt="screen shot 2017-12-19 at 4 23 45 pm" src="https://user-images.githubusercontent.com/9516787/34153806-6263ff10-e4d9-11e7-9979-290321abe005.png">

I have deleted and installed anaconda multiple times, in different directory and various other methods but still jupyter notebook shows the same error.
Here's my .bash_profile contents:

<img width="368" alt="screen shot 2017-12-19 at 4 27 21 pm" src="https://user-images.githubusercontent.com/9516787/34154167-9393beee-e4da-11e7-8baa-b4a96ef11cee.png">

Please help me resolve this issue as I am facing this issue for quite a few days. Also, I have observed that my anaconda version is throwing this error since the addition of new tool named  'jupyterlab'.

Thanks :)

**Comment by csoja** [comment]
Unfortunately, this is not the right place to find help for Jupyter Notebook issues.  I'd recommend https://github.com/jupyter/notebook/issues or https://github.com/jupyterlab/jupyterlab/issues
