### ISSUE TITLE
Not able to download pypandoc-0.8.2.tar

### ISSUE THREAD

**Issue by vishalmestri** [ContinuumIO/anaconda-issues#7850]
I am running below command.
pip install -i https://pypi.anaconda.org/pypi/simple pypandoc

But it is giving me 404 for URL 
https://anaconda.org/pypi/pypandoc/0.8.2/download/pypandoc-0.8.2.tar.gz

![error](https://user-images.githubusercontent.com/34690425/34173059-320ea5fe-e51a-11e7-8fb9-950334662f8f.png)
![error1](https://user-images.githubusercontent.com/34690425/34173060-3248d5d0-e51a-11e7-867d-b6b9caca6ce6.png)

**Comment by csoja** [comment]
The pip packages in the https://anaconda.org/pypi channel are quite old. I'd recommend using conda install pypandoc if you have Anaconda installed - or installing the package with pip from pypi directly (https://pypi.python.org/pypi).
