### ISSUE TITLE
conda activate having issues on Windows 10

### ISSUE THREAD

**Issue by dvincentwest** [ContinuumIO/anaconda-issues#7853]
I am on Windows 10 (Enterprise Laptop), which is a newish computer for me.

I can install and use Anaconda just fine, but creating new envs has run into a problem.  After first having this problem, I re-installed a fresh copy of Miniconda (latest) with no packages at all.  I then try to create a new env and then activate it, but I get a notice that 'B'  is not a recognized internal command. 

![image](https://user-images.githubusercontent.com/9872343/34181521-168ffa40-e4d8-11e7-9028-18c34b628525.png)

**Comment by kalefranz** [comment]
This issue was moved to conda/conda#6597
