### ISSUE TITLE
Navigator Reset Error

### ISSUE THREAD

**Issue by ZizhenWang** [ContinuumIO/anaconda-issues#7860]
the log of "anaconda-navigator --reset" is:
Anaconda Navigator configuration reset...
Anaconda Navigator configuration reset failed!!!
[Error 32] : u'C:\\Users\\wangzizhen\\.anaconda\\navigator\\logs\\navigator.log'

**Comment by goanpeca** [comment]
Please manually delete `C:\Users\wangzizhen\.anaconda\` (its safe, and is what reset does)
