### ISSUE TITLE
Jasper Jpeg Dependency Issue

### ISSUE THREAD

**Issue by jgmorrison** [ContinuumIO/anaconda-issues#7872]
Customer brought up an issue with the jpeg dependency of the jasper package.

depends: jpeg >=9b,<10a

However jasper wants libjpeg.so.8

$ /opt/teza-conda/bin/conda create -n jasper jasper
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /teza/home/michael/.conda/
envs/jasper:

The following packages will be downloaded:

package | build
---------------------------|-----------------
jpeg-9b | 0 941 KB

The following NEW packages will be INSTALLED:

jasper: 1.900.1-2
jpeg: 9b-0

...
$ ldd ~/.conda/envs/jasper/lib/libjasper.so.1.0.0
linux-vdso.so.1 => (0x00007ffd5fb40000)
libm.so.6 => /lib64/libm.so.6 (0x00007f9635f0b000)
libjpeg.so.8 => not found
libc.so.6 => /lib64/libc.so.6 (0x00007f9635bb1000)
/lib64/ld-linux-x86-64.so.2 (0x0000003a7e800000)

If I create an environment where I specify the proper version of jpeg
alongside jasper, then things look better:

/opt/teza-conda/bin/conda create -n jasper2 jasper jpeg=8d
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /teza/home/michael/.conda/
envs/jasper2:

The following packages will be downloaded:

package | build
---------------------------|-----------------
jpeg-8d | 2 806 KB

The following NEW packages will be INSTALLED:

jasper: 1.900.1-2
jpeg: 8d-2
...
$ ldd ~/.conda/envs/jasper2/lib/libjasper.so.1.0.0
linux-vdso.so.1 => (0x00007ffc847f1000)
libm.so.6 => /lib64/libm.so.6 (0x00007f3c7f9cd000)
libjpeg.so.8 => /teza/home/michael/.conda/envs/jasper2/lib/./libjpeg.so.8
(0x00007f3c7f792000)
libc.so.6 => /lib64/libc.so.6 (0x00007f3c7f439000)
/lib64/ld-linux-x86-64.so.2 (0x0000003a7e800000)

Can you please help us resolve this by fixing the recipe for jasper?

**Comment by jjhelmus** [comment]
Where is this jasper package sourced from?  We do not provide a jasper-1.900.1-2 package in `defaults` for any platform.

**Comment by jgmorrison** [comment]
They were using a custom build. I am closing as it is not an issue with our builds.
