### ISSUE TITLE
Anaconda Navigator Crashed

### ISSUE THREAD

**Issue by parthibanmu** [ContinuumIO/anaconda-issues#7879]
Anaconda Navigator closed within the second once it open. It's more like just a blink and closed immediately

**Comment by goanpeca** [comment]
@parthibanmu please open the anaconda prompt (if on windowS) or a terminal on unix systems and run Navigator from there by typing

```
anaconda-navigator
```

Paste the traceback

**Comment by goanpeca** [comment]
Close due to lack of response
