### ISSUE TITLE
brian installation error in anaconda

### ISSUE THREAD

**Issue by assadRasheed** [ContinuumIO/anaconda-issues#7894]
(C:\ProgramData\Anaconda3) C:\Users\zai-pc>pip install brian
Collecting brian
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connec
tion broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', po
rt=443): Read timed out. (read timeout=15)",)': /simple/brian/
  Using cached brian-1.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zai-pc\AppData\Local\Temp\pip-build-lq1q1ryu\brian\setup.p
y", line 31
        except CCompilerError, ex:
                             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\zaid-pc\
AppData\Local\Temp\pip-build-lq1q1ryu\brian\

(C:\ProgramData\Anaconda3) C:\Users\za-pc>
when i tried to install brian it always gives that error

**Comment by csoja** [comment]
Since you are using Anaconda - it is preferable to use conda to install, instead of pip.  
Looks like brian2 is available on the Brian channel on Anaconda Cloud. https://anaconda.org/brian-team/brian2
