### ISSUE TITLE
my anaconda doesn't work.. help wanted

### ISSUE THREAD

**Issue by JangHoPeter** [ContinuumIO/anaconda-issues#7896]
Could you help me?

I installed anaconda ver. 4.3.1

and installed tensorflow, keras, pandas by cmd (pip install --upgrade tensorflow-gpu, pip install keras, pip install pandas)

after doing this, I couldn't use my anaconda and jupyter notebook. It didn't work.

Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Hwi>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.14.2
       root environment : C:\Users\Hwi\Anaconda3  (writable)
    default environment : C:\Users\Hwi\Anaconda3
       envs directories : C:\Users\Hwi\Anaconda3\envs
                          C:\Users\Hwi\AppData\Local\conda\conda\envs
                          C:\Users\Hwi\.conda\envs
          package cache : C:\Users\Hwi\Anaconda3\pkgs
                          C:\Users\Hwi\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Hwi\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.5.3 Windows/10 Windows/10.0.16299
          administrator : False

C:\Users\Hwi>conda list
packages in environment at C:\Users\Hwi\Anaconda3:

_license                  1.1                      py36_1
alabaster                 0.7.9                    py36_0
anaconda                  4.3.1               np111py36_0
anaconda-client           1.6.0                    py36_0
anaconda-navigator        1.5.0                    py36_0
anaconda-project          0.4.1                    py36_0
asn1crypto                0.22.0                   py35_0
astroid                   1.4.9                    py36_0
astropy                   1.3                 np111py36_0
babel                     2.3.4                    py36_0
backports                 1.0                      py36_0
beautifulsoup4            4.5.3                    py36_0
bitarray                  0.8.1                    py36_1
blaze                     0.10.1                   py36_0
bleach                    1.5.0                     <pip>
bokeh                     0.12.4                   py36_0
boto                      2.45.0                   py36_0
bottleneck                1.2.0               np111py36_0
bzip2                     1.0.6                    vc14_3  [vc14]
certifi                   2016.2.28                py35_0
cffi                      1.10.0                   py35_0
chardet                   2.3.0                    py36_0
chest                     0.2.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.7                    py36_0
comtypes                  1.1.2                    py36_0
conda                     4.3.30           py35hec795fb_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py36_0
console_shortcut          0.1.1                    py36_1
contextlib2               0.5.4                    py36_0
cryptography              1.8.1                    py35_0
curl                      7.52.1                   vc14_0  [vc14]
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.13.0                   py36_0
datashape                 0.5.4                    py36_0
decorator                 4.0.11                   py36_0
dill                      0.2.5                    py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_0
enum34                    1.1.6                     <pip>
et_xmlfile                1.0.1                    py36_0
fastcache                 1.0.2                    py36_1
flask                     0.12                     py36_0
flask-cors                3.0.2                    py36_0
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
greenlet                  0.4.11                   py36_0
h5py                      2.6.0               np111py36_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py36_1
html5lib                  0.9999999                 <pip>
icu                       57.1                     vc14_0  [vc14]
idna                      2.6                      py35_0
imagesize                 0.7.1                    py36_0
ipykernel                 4.5.2                    py36_0
ipython                   5.1.0                    py36_0
ipython_genutils          0.1.0                    py36_0
ipywidgets                5.2.2                    py36_1
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jdcal                     1.3                      py36_0
jedi                      0.9.0                    py36_1
jinja2                    2.9.4                    py36_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            4.4.0                    py36_0
jupyter_console           5.0.0                    py36_0
jupyter_core              4.2.1                    py36_0
Keras                     2.1.2                     <pip>
lazy-object-proxy         1.2.2                    py36_0
libpng                    1.6.27                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.15.0                   py36_0
locket                    0.2.0                    py36_1
lxml                      3.7.2                    py36_0
Markdown                  2.6.10                    <pip>
markupsafe                0.23                     py36_2
matplotlib                2.0.0               np111py36_0
menuinst                  1.4.7                    py35_0
mistune                   0.7.3                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
multipledispatch          0.4.9                    py36_0
nbconvert                 4.2.0                    py36_0
nbformat                  4.2.0                    py36_0
networkx                  1.11                     py36_0
nltk                      3.2.2                    py36_0
nose                      1.3.7                    py36_1
notebook                  4.3.1                    py36_2
numba                     0.30.1              np111py36_0
numexpr                   2.6.1               np111py36_2
numpy                     1.11.3                   py36_0
numpy                     1.13.3                    <pip>
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
openpyxl                  2.4.1                    py36_0
openssl                   1.0.2k                   vc14_0  [vc14]
packaging                 16.8                     py35_0
pandas                    0.19.2              np111py36_1
partd                     0.3.7                    py36_0
path.py                   10.0                     py36_0
pathlib2                  2.2.0                    py36_0
patsy                     0.4.1                    py36_0
pep8                      1.7.0                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.0.0                    py36_0
pip                       9.0.1                    py35_1
ply                       3.9                      py36_0
prompt_toolkit            1.0.9                    py36_0
protobuf                  3.5.1                     <pip>
psutil                    5.0.1                    py36_0
py                        1.4.32                   py36_0
pyasn1                    0.2.3                    py35_0
pycosat                   0.6.2                    py35_0
pycparser                 2.18                     py35_0
pycrypto                  2.6.1                    py36_5
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.1.3                    py36_0
pylint                    1.6.4                    py36_1
pyopenssl                 17.0.0                   py35_0
pyparsing                 2.2.0                    py35_0
pyqt                      5.6.0                    py36_2
pytables                  3.2.2               np111py36_4
pytest                    3.0.5                    py36_0
python                    3.5.3                         3
python-dateutil           2.6.0                    py36_0
pytz                      2016.10                  py36_0
pywin32                   220                      py35_2
pyyaml                    3.12                     py35_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.4.3                    py36_0
qtconsole                 4.2.1                    py36_2
qtpy                      1.2.1                    py36_0
requests                  2.14.2                   py35_0
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py35_1
scikit-image              0.12.3              np111py36_1
scikit-learn              0.18.1              np111py36_1
scipy                     0.18.1              np111py36_1
seaborn                   0.7.1                    py36_0
setuptools                38.2.4                    <pip>
setuptools                36.4.0                   py35_1
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py35_1
six                       1.11.0                    <pip>
snowballstemmer           1.2.1                    py36_0
sockjs-tornado            1.0.3                    py36_0
sphinx                    1.5.1                    py36_0
spyder                    3.1.2                    py36_0
sqlalchemy                1.1.5                    py36_0
statsmodels               0.6.1               np111py36_1
sympy                     1.0                      py36_0
tensorflow-gpu            1.4.0                     <pip>
tensorflow-tensorboard    0.4.0rc3                  <pip>
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.2                    py36_0
tornado                   4.4.2                    py36_0
traitlets                 4.3.1                    py36_0
unicodecsv                0.14.1                   py36_0
vc                        14                            0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.11.15                  py36_0
Werkzeug                  0.13                      <pip>
wheel                     0.30.0                    <pip>
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py36_0
win_unicode_console       0.5                      py36_0
wincertstore              0.2                      py35_0
wrapt                     1.10.8                   py36_0
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.2                   py36_0
xlwt                      1.2.0                    py36_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by nehaljwani** [comment]
>after doing this, I couldn't use my anaconda and jupyter notebook. It didn't work.

Is there a traceback that you can share?

**Comment by JangHoPeter** [comment]
Thank you for your concern. I reinstalled it. Thanks
