### ISSUE TITLE
installing Iminuit from Github on windows: it doesn't work!

### ISSUE THREAD

**Issue by specklee** [ContinuumIO/anaconda-issues#79]
Hi,
after have tried to follow this instructions to install pyminuit (https://code.google.com/p/pyminuit/wiki/HowToInstall) with wich I have installed a mingw compiler for windows I failed and the developer suggested me to try to install iminuit from github.

I have tried to do it but when I do

pip install iminuit

 it returns to me a lot of Warnings (deprecated conversion) and in the end a lot of undefined references like this one: 

build\temp.win-amd64-2.7\Release\iminuit_libiminuit.o:libiminuit.cpp:(.text+0x11749): undefined reference to `imp__PyErr_Occurred' 

what could I do? 

thanks

Gabriele

**Comment by csoja** [comment]
Old issue and out of scope of this for this repository.  Closing...
