### ISSUE TITLE
Anaconda Prompt Error

### ISSUE THREAD

**Issue by armstrang** [ContinuumIO/anaconda-issues#7904]
![untitlgged](https://user-images.githubusercontent.com/32195239/34324700-b5360572-e8b6-11e7-9fe6-32007c8cda40.png)

i can't use The anaconda Prompt

**Comment by nehaljwani** [comment]
Could you share the output for:
```
"C:\Users\Sultan Jorgi\Aanconda3\Scripts\conda.exe" info -a
```

In the meantime, see if this helps you to activate the Anaconda3 install:
```
"C:\Users\Sultan Jorgi\Aanconda3\Scripts\activate"
```

**Comment by armstrang** [comment]
![2](https://user-images.githubusercontent.com/32195239/34339024-5f1586dc-e9aa-11e7-92b9-336e25b754ef.png)
@nehaljwani 
![1](https://user-images.githubusercontent.com/32195239/34339022-5b7bf61e-e9aa-11e7-9eeb-d331edf52c57.png)

**Comment by mingwandroid** [comment]
@kalefranz, it seems conda 4.4 has regressed wrt spaces in the install location.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda#6599
