### ISSUE TITLE
spyder missing in windows 10 after installing anaconda 3.5

### ISSUE THREAD

**Issue by 17481325** [ContinuumIO/anaconda-issues#7908]
After installing anaconda on windows 10, I can't see spyder when I search in the windows search menu.

**Comment by csoja** [comment]
Spyder is included in the latest Anaconda - v5.0.1.  Did you install https://repo.continuum.io/archive/Anaconda3-5.0.1-Windows-x86_64.exe ? Can you find the Anaconda Prompt or Anaconda Navigator and launch it from one of those?

**Comment by 17481325** [comment]
I have reinstalled using the version you provided and I able to start Spyder from navigator . However I cannot see any short cuts from windows start menu. In addition I can see anaconda prompt even in the installation folder. I see some error in navigator which i have attached I am not sure if it has something to do with it. Thanks

<img width="558" alt="error_navigator" src="https://user-images.githubusercontent.com/34236615/34855077-af32ebec-f778-11e7-8403-7c500a8273c2.PNG">

**Comment by csoja** [comment]
So, it sounds like you are now able to start Spyder from Anaconda Navigator and you can see the Anaconda Prompt.  It is not clear to me what issue you are having.  Are you looking for a Spyder menu shortcut?

**Comment by 17481325** [comment]
Yes I am now able to start Spyder but all shortcut menus are missing(anaconda prompt, navigator and Spyder).

**Comment by csoja** [comment]
Do you have a virus scanner actively running?  Did you see any errors during your most recent installation to indicate what the error was that resulted in no menu items?

**Comment by goanpeca** [comment]
Stale issue, closing
