### ISSUE TITLE
Anaconda Navigator download error

### ISSUE THREAD

**Issue by IdanMorad** [ContinuumIO/anaconda-issues#7910]
Hey,
I have the latest navigator 1.6.9 with python 3.6.3.
When I'm trying to update my packages (no matter which) it just keep calculating package requirement for a long time, basically it get stuck.
When I look at the log I this error:
```json
[
    {
        "level": "ERROR",
        "line": 189,
        "message": "Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png",
        "method": "_download",
        "module": "download_api",
        "path": "C:/Users/imorad/AppData/Local/Continuum/Anaconda2/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2017-04-05 15:57:26,365"
    }
]
```
![image](https://user-images.githubusercontent.com/14161367/34336175-adc857b6-e95d-11e7-8d92-73472ceaf535.png)

Please advise

**Comment by goanpeca** [comment]
@IdanMorad those errors are unrelated to conda resolving package requirements.

Also the latest version is 1.6.10 please update to that one and try again.

**Comment by IdanMorad** [comment]
My mistake I using 1.6.10 and not 1.6.9.
![image](https://user-images.githubusercontent.com/14161367/34356483-cba6b2ca-ea46-11e7-924c-41c9414e8fc0.png)

so what is this problem it's relate?

**Comment by goanpeca** [comment]
@IdanMorad it seems conda 4.4.x introduced a small issue. We are making a release today for 1.6.11 to solve this problem.

Thanks for reporting, I will ping you back as soon as the packages are available.

**Comment by IdanMorad** [comment]
thanks =)

**Comment by goanpeca** [comment]
@IdanMorad  could please update to the latest version of navigator (1.6.11 just released) and check if it is working as expected?

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
