### ISSUE TITLE
Navigator Error, i am unable to launch spyder IDE, it is getting crashed throwing error with html5lib module. I am trying to uninstall module and getting following error:

### ISSUE THREAD

**Issue by Ashutosh-Srivastav** [ContinuumIO/anaconda-issues#7934]
Screenshot FYR.
The following errors occured:

None:
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error o
![launch-error-spyder](https://user-images.githubusercontent.com/21309941/34402339-dd01fbb6-ebc6-11e7-8aa1-51a7994a757f.jpg)
ccurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),),)

{'platform': 'win-64', 'qt': '4.8.7', 'conda': '4.4.4', 'pyqt': '4.11.4', 'python': '3.5.2', 'os': 'Windows;10;10.0.14393;AMD64;AMD64 Family 21 Model 19 Stepping 1, AuthenticAMD', 'language': 'en_US', 'version': '1.2.1'}

**Comment by ccordoba12** [comment]
This should be fixed in the Spyder latest release. Please update.
