### ISSUE TITLE
Can't open the launcher

### ISSUE THREAD

**Issue by zzstefan** [ContinuumIO/anaconda-issues#796]
Sorry, the application encountered a fatal error. Please report the following to us at https://github.com/ContinuumIO/anaconda-issues.

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

And when I type conda in the term, it shows command not found. And I'm sure I have change the path.

**Comment by ilanschnell** [comment]
The launcher was remove in Anaconda 4.0 is favor or the so-called Anaconda Navigator.

**Comment by zzstefan** [comment]
but I when I type in conda, it shows command not found. And I'm sure that I have change the path.

**Comment by stephenakearns** [comment]
Hi @zzstefan - Launcher has been deprecated. It is superceded by the conda package anaconda-navigator. You can read more about it here: https://docs.continuum.io/anaconda/navigator

Closing this, but happy to reopen if you are encountering any issues with Navigator.
