### ISSUE TITLE
vs*_runtime packages are missing OpenMP (VCOMP*.dll) libraries

### ISSUE THREAD

**Issue by patricksnape** [ContinuumIO/anaconda-issues#798]
`vs2015_runtime`, `vs2010_runtime` and `vs2008_runtime` packages are missing `vcomp140.dll`, `vcomp100.dll` and `vcomp90.dll` respectively. This prevents packages that require OpenMP from running correctly.

**Comment by msarahan** [comment]
Thanks, I'll see about including these.
