### ISSUE TITLE
on mac, anaconda3 shell installer disregards command line options starting from version 5.0

### ISSUE THREAD

**Issue by dudalev** [ContinuumIO/anaconda-issues#7985]
> $ /bin/bash Anaconda3-5.0.1-MacOSX-x86_64.sh -f -b -p /Users/qwe/ana3
> 
> Welcome to Anaconda3 5.0.1
> 
> In order to continue the installation process, please review the license
> agreement.
> Please, press ENTER to continue
> >>>

If any,

>  $ uname -a
> Darwin ziqqurah.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64 i386 MacBookAir6,2 Darwin`

**Comment by nehaljwani** [comment]
Unable to reproduce this. Works fine for me:
```
some-build-machine:installers builder$ wget https://repo.continuum.io/archive/Anaconda3-5.0.1-MacOSX-x86_64.sh

some-build-machine:installers builder$ /bin/bash Anaconda3-5.0.1-MacOSX-x86_64.sh -f -b -p /Users/nwani/installers/a3
PREFIX=/Users/nwani/installers/a3

installing: python-3.6.3-h6804ab2_0 ...
Python 3.6.3 :: Anaconda, Inc.
installing: bzip2-1.0.6-h92991f9_1 ...
installing: ca-certificates-2017.08.26-ha1e5d58_0 ...
installing: conda-env-2.6.0-h36134e3_0 ...
installing: gettext-0.19.8.1-hb0f4f8b_2 ...
installing: intel-openmp-2018.0.0-h68bdfb3_7 ...
installing: jbig-2.1-h4d881f8_0 ...
installing: jpeg-9b-haccd157_1 ...
...
installation finished.
```

In case you copied that command from somewhere, try typing it out by hand?

**Comment by dudalev** [comment]
This was already copied out from pyenv installer and tried by had.

The actual culprit was having '/usr/local/opt/gnu-getopt/bin' in my PATH, somehow with gnu-getopt-1.1.6 from homebrew it only parses the first argument and silently drops the others.

So, strictly speaking, this is a non-bug, but it is still maybe worth looking into.

**Comment by mingwandroid** [comment]
Oh joy, more `homebrew` breaking `macOS`. That they use `/usr/local` is a horribly selfish choice to make their own lives easier. It is selfish for two reasons:

1. `/usr/local/bin` is on `PATH` before `/usr/bin` so as soon as any of their buggy software gets used by other distros we run into issues like this.
2. `/usr/local/include` and `/usr/local/lib` are *hardcoded* into `clang` and `ld64` (the macOS linker) so any libs and headers put in those places get found and used, again causing trouble. One of the advantages of using the `Anaconda Distribution` compilers is that I removed those directories.

It is also incorrect from a Unix perspective, `/usr/local` is for the *system administrator* to install locally built software, and homebrew, being a distro does not meet that definition.

Please report this to `homebrew`, we should not have to work around their bugs.

**Comment by mingwandroid** [comment]
I'm tempted to reopen this to help people who search only in open issues, but I do not consider it a bug in `AD` that we should/can do anything about.
