### ISSUE TITLE
No instructions about building anaconda/mini-conda.

### ISSUE THREAD

**Issue by cssasha** [ContinuumIO/anaconda-issues#7989]
Hello Continuum team,

We'd like to port miniconda to aarch64 to be able to compile ML libraries we're using (especially pytorch). 

It seems that the only available compiled miniconda binaries are for amd64 and I could not find instructions about how to build miniconda ourselves...

What should we do?

Thank you in advance!
--Alex

**Comment by csoja** [comment]
I'd recommend looking at constructor & conda-build: https://github.com/conda/constructor & https://github.com/conda/conda-build

**Comment by cssasha** [comment]
thanks!
