### ISSUE TITLE
"python" 3.5.1-4 package for Anaconda3 on win64

### ISSUE THREAD

**Issue by ulfworsoe** [ContinuumIO/anaconda-issues#800]
The "python" 3.5.1-4 package for Anaconda3 on win64 seems to be broken.

What happens: I am building a conda package using Miniconda3 for win64. The ``bld.bat`` script executes:
```
%PYTHON% setup.py install
```
Python crashes immediately with a pop-up saying "The application was unable to start correctly (0xc0000142)". Using Miniconda2 works.

Note: Following appears to work correctly:
```
miniconda3/python -m conda create -n myenv python
miniconda3/python -m conda run -n myenv python.exe
```

**Comment by msarahan** [comment]
We had an inconsistency in our build system, resulting in the MSVC runtime being older than the version of Visual Studio 2015 used to build python.  We have removed the problem package (build 1 of vs2015_runtime).  Please try again.

**Comment by ulfworsoe** [comment]
Thank you! It works now.
