### ISSUE TITLE
lxml broken for Anaconda 5.0.1 on Windows 10

### ISSUE THREAD

**Issue by patrick984** [ContinuumIO/anaconda-issues#8006]
Using a clean install of Anaconda 5.0.1 x64 (no other packages or updates), the lxml package appears to be broken.

Windows 10 1703 (15063.789)

```
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```
  
After attempting to downgrade the lxml package:
`3.7.3-py36_0` is the latest version that works, `3.8.0-py36h45350b2_0` and newer all have the same error as above.

**Comment by cfobel** [comment]
I can also confirm this is an issue in the following **`win-32` Python 2.7.14** environment:

```
     active environment : lxml-4.4.1-win-32
    active env location : C:\Users\chris\Miniconda2-x86\envs\lxml-4.4.1-win-32
       user config file : C:\Users\chris\.condarc
 populated config files :
          conda version : 4.4.6
    conda-build version : 3.2.1
         python version : 2.7.14.final.0
       base environment : C:\Users\chris\Miniconda2-x86  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\chris\Miniconda2-x86\pkgs
                          C:\Users\chris\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\chris\Miniconda2-x86\envs
                          C:\Users\chris\AppData\Local\conda\conda\envs
                          C:\Users\chris\.conda\envs
               platform : win-32
             user-agent : conda/4.4.6 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

# Steps to reproduce

 1. Download and extract [`env-lxml-4.4.1-win-32-py27.yaml.zip`][env-lxml-4.4.1-win-32-py27.yaml.zip].
 2. Run:
         conda env create -n lxml-test -f env-lxml-4.4.1-win-32-py27.yaml
 3. Activate `lxml-test` environment.
 4. Run: `python -c "import lxml.etree"

[env-lxml-4.4.1-win-32-py27.yaml.zip]: https://github.com/ContinuumIO/anaconda-issues/files/1613064/env-lxml-4.4.1-win-32-py27.yaml.zip

**Comment by msarahan** [comment]
This should be fixed now.  We updated libxml2 and libxslt, and ensured that lxml is constrained more appropriately:

```
    libxml2:        2.9.7-h325896a_0
    libxslt:        1.1.32-h89dfad8_0
    lxml:           4.1.1-py27h31b8cb8_1
```

If you continue to see issues, you may have related libraries elsewhere on your system that conflict with ours.  We can help you figure out where they are.  For example, here's a related issue with explanations: https://github.com/ContinuumIO/anaconda-issues/issues/1672#issuecomment-360310029
