### ISSUE TITLE
anaconda-navigator writes a required config file that conda clean --all deletes

### ISSUE THREAD

**Issue by o12johns** [ContinuumIO/anaconda-issues#8019]
Note: This bug is with conda 4.4.6 and anaconda-navigator 1.6.11

To see that anaconda-navigator uses ~/anaconda3/pkgs/cache to store the
contents of its home page:

Zeus:~ ojohns$ navigator-updater #Dismiss the panel that appears
Zeus:~ ojohns$ cd anaconda3/pkgs/
Zeus:pkgs ojohns$ ls cache
0cdb2265.json	0cdb2265.q	9cd9d6b5.json	9cd9d6b5.q	abae4451.json	abae4451.q	d85a531e.json	d85a531e.q
Zeus:pkgs ojohns$ anaconda-navigator #See correct home page.  Then close window.
Zeus:pkgs ojohns$ mv cache acache
cache -> acache
Zeus:pkgs ojohns$ anaconda-navigator  #See empty home page.  Then close window.
Zeus:pkgs ojohns$ mv acache/ cache
acache/ -> cache
Zeus:pkgs ojohns$ anaconda-navigator #See correct home page once again

To see that conda clean —all deletes the folder ~/anaconda3/pkgs/cache:

Zeus:pkgs ojohns$ navigator-updater #Dismiss the panel that appears.
Zeus:pkgs ojohns$ cd ~/anaconda3/pkgs
Zeus:pkgs ojohns$ ls cache
0cdb2265.json	0cdb2265.q	9cd9d6b5.json	9cd9d6b5.q	abae4451.json	abae4451.q	d85a531e.json	d85a531e.q
Zeus:pkgs ojohns$ conda clean --all -y
Cache location: 
There are no tarballs to remove
Cache location: 
There are no unused packages to remove
source cache (/Users/ojohns/anaconda3/conda-bld/src_cache)
Size:                                           0 B

git cache (/Users/ojohns/anaconda3/conda-bld/git_cache)
Size:                                           0 B

hg cache (/Users/ojohns/anaconda3/conda-bld/hg_cache)
Size:                                           0 B

svn cache (/Users/ojohns/anaconda3/conda-bld/svn_cache)
Size:                                           0 B

Total:                                          0 B
Removing /Users/ojohns/anaconda3/conda-bld/src_cache
Removing /Users/ojohns/anaconda3/conda-bld/git_cache
Removing /Users/ojohns/anaconda3/conda-bld/hg_cache
Removing /Users/ojohns/anaconda3/conda-bld/svn_cache
Zeus:pkgs ojohns$ ls cache
ls: cache: No such file or directory
Zeus:pkgs ojohns$

**Comment by o12johns** [comment]
Note:  This bug is on an iMac running OSX Sierra.

**Comment by kalefranz** [comment]
cross-ref: https://github.com/conda/conda/issues/6658

**Comment by o12johns** [comment]
From comments on related thread conda/conda#6658, I gather that it is correct behaviour for conda clean -i to zap the directory ~/anaconda3/pkgs/cache that is used by anaconda-navigator.  So conda is not going to be modified.  Perhaps the best resolution then is just to use conda clean -pty to clean up after a conda download.  That does not zap ~/anaconda3/pkgs/cache and thus seems to leave Anaconda-Navigator in good shape.

**Comment by o12johns** [comment]
This issue appears to be corrected in Anaconda-Navigator 1.6.12.  Navigator now seems to check for existence of ~/anaconda3/pkgs/cache. And if it is not found, Navigator appears to do an update of its index before starting.  This resolves the issue which should now be closed.
