### ISSUE TITLE
Windows Miniconda Installer: install a "Anaconda Command Prompt" ...

### ISSUE THREAD

**Issue by rvzzz** [ContinuumIO/anaconda-issues#802]
![anaconda_env](https://cloud.githubusercontent.com/assets/3394457/15527180/112abcd2-2230-11e6-9651-5599508761a3.gif)

**Comment by goanpeca** [comment]
@rvzzz, thanks for reporting.

What version of Navigator are you using?

**Comment by rvzzz** [comment]
@goanpeca Hi..you're welcome. I think it's the newest, I just install it today. Then it had an update (on the top left, after the logo) and I run it..
![screen shot 2016-05-25 at 07 21 01](https://cloud.githubusercontent.com/assets/3394457/15530030/b76301c2-2249-11e6-9924-793e08128525.png)

**Comment by rsignell-usgs** [comment]
Doesn't work on Windows either.

**Comment by goanpeca** [comment]
Hi @rsignell-usgs. This is fixed on our next release, which will come out in two weeks.

**Comment by rsignell-usgs** [comment]
Could the new miniconda release for windows install a "Anaconda command prompt" on windows no matter what even if the  Advanced Options on the installer are unchecked)?
![miniconda_installer](https://cloud.githubusercontent.com/assets/1872600/15968410/d3d6c070-2ef9-11e6-8575-10bf4bf521aa.png)

**Comment by msarahan** [comment]
CC @ilanschnell @csoja - to do this, we only need to include "console_shortcut" as one of the miniconda packages on Windows.

**Comment by rsignell-usgs** [comment]
Sweet!  I just installed it locally, and it works great.   Thanks!!!

**Comment by goanpeca** [comment]
This has been fixed in the latest version of Navigator
