### ISSUE TITLE
What is the console_shortcut package?

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#8030]
Just as the title says, trying to figure out what the Windows package `console_shortcut` does. Not being a big Windows user am unfortunately kind of clueless here. So sorry for the basic question.

**Comment by JoelStansbury** [comment]
Old question, but incase others find it...

Here is the feedstock for console_shortcut
https://github.com/conda-forge/miniforge_console_shortcut-feedstock
In Windows, it adds an icon to enter Anaconda Prompt shortcut to the start menu.
If not windows, it is skipped and I believe this means it is not actually installed, but I'm still learning conda-build (see [meta.yaml#L10](https://github.com/conda-forge/miniforge_console_shortcut-feedstock/blob/main/recipe/meta.yaml#L10))

**Comment by jakirkham** [comment]
Thanks Joel! 🙏
