### ISSUE TITLE
KeyError: '_url'

### ISSUE THREAD

**Issue by Bhumin** [ContinuumIO/anaconda-issues#8054]
Anaconda Navigator is getting stuck at the start-up. When I tried to open with the Anaconda Prompt, it gives me following error:

(base) C:\Users\bhpathak>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 290, in _conda_info_processed
    channels=channels, pkgs_dirs=pkgs_dirs
  File "C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1618, in get_repodata
    url = data['_url']
KeyError: '_url'

=====================================================
Below is the output of $conda infor and $conda list
====================================================

(base) C:\Users\bhpathak>conda info

     active environment : base
    active env location : C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3
            shell level : 1
       user config file : C:\Users\bhpathak\.condarc
 populated config files : C:\Users\bhpathak\.condarc
          conda version : 4.4.6
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       base environment : C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3  (writable)
           channel URLs : https://github.com/nltk/nltk/win-64
                          https://github.com/nltk/nltk/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\bhpathak\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\bhpathak\AppData\Local\conda\conda\envs
                          C:\Users\bhpathak\.conda\envs
               platform : win-64
             user-agent : conda/4.4.6 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False

(base) C:\Users\bhpathak>conda list
# packages in environment at C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3:
#
_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
alabaster                 0.7.9                    py35_0
anaconda                  custom                   py35_0
anaconda-clean            1.0.0                    py35_0
anaconda-client           1.6.3                    py35_0
anaconda-navigator        1.6.11           py35h6f1961e_0
anaconda-project          0.6.0                    py35_0
argcomplete               1.0.0                    py35_1
astroid                   1.4.7                    py35_0
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
boto3                     1.4.0                    py35_0
botocore                  1.4.90                   py35_0
bottleneck                1.1.0               np111py35_0
bz2file                   0.98                     py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
ca-certificates           2017.08.26           h94faf87_0
cffi                      1.7.0                    py35_0
chardet                   3.0.4                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.4.6                    py35_0
conda-build               2.0.2                    py35_0
conda-env                 2.6.0                h36134e3_1
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.5                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cymem                     1.31.2           py35h3642f57_0
cython                    0.24.1                   py35_0
cytoolz                   0.8.2            py35h6a98e29_0
dask                      0.11.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
gensim                    1.0.1               np111py35_0
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.2                    py35_0
graphviz                  2.38.0                        4
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
icc_rt                    2017.0.4             h97af966_0
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
intel-openmp              2018.0.0             hcd89f80_7
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jmespath                  0.9.0                    py35_0
jpeg                      8d                       vc14_2  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
lazy-object-proxy         1.2.1                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.13.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.4                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.3               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.3                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
murmurhash                0.26.4           py35h1512bc8_0
navigator-updater         0.1.0            py35h1d043e2_0
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.28.1              np111py35_0
numexpr                   2.6.1               np111py35_1
numpy                     1.11.1                   py35_1
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2n               h74b6da3_0
pandas                    0.18.1              np111py35_0
partd                     0.3.6                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    3.3.1                    py35_0
pip                       8.1.2                    py35_0
pkginfo                   1.3.2                    py35_0
plac                      0.9.6                    py35_0
ply                       3.9                      py35_0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.3            py35h456c199_0
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.3.0                    py35_0
pygments                  2.1.3                    py35_0
pylint                    1.5.4                    py35_1
pyopenssl                 16.2.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
python-graphviz           0.5.2                    py35_0
pytz                      2015.4                   py35_0
pywin32                   220                      py35_1
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.0                    vc14_0  [vc14]
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.3.1                    py35_0
requests                  2.13.0                   py35_0
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_0
s3transfer                0.1.11           py35h2c3604a_1
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.18.0              np111py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
smart_open                1.3.5                    py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.6                    py35_0
spyder                    3.0.0                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.4.1                    py35_0
traitlets                 4.3.0                    py35_0
unicodecsv                0.14.1                   py35_0
vc                        14                   h2379b0c_2
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.24.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.6                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

============================

**Comment by goanpeca** [comment]
@Bhumin could you manually remove his folder

`C:\Users\bhpathak\AppData\Local\Continuum\Anaconda3\pkgs` and try again?

**Comment by Bhumin** [comment]
Ok, that solved the issue.

Thank you,
Bhumin

**Comment by goanpeca** [comment]
Thank you! I will add an extra check thanks to you reporting this issue

**Comment by goanpeca** [comment]
Issue moved to [ContinuumIO/navigator #1401](https://github.com/ContinuumIO/navigator/issues/1401) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Iphykay** [comment]
I have the same error but this time the KeyError is base
