### ISSUE TITLE
Spyder not starting

### ISSUE THREAD

**Issue by Fheanor** [ContinuumIO/anaconda-issues#806]
Hey everyone, I am working on a Windows 8.1 os and I installed Anaconda.
But if I start Spyder, nothing happen. 
So I tried to start it in a shell and here is what I got :

> 
> C:\Users\darke>spyder
> Traceback (most recent call last):
>   File "C:\Users\darke\Anaconda2\Scripts\spyder-script.py", line 2, in <module>
>     start_app.main()
>   File "C:\Users\darke\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 114, in main
>     from spyderlib import spyder
>   File "C:\Users\darke\Anaconda2\lib\site-packages\spyderlib\spyder.py", line 137, in <module>
>     from spyderlib.ipythonconfig import IPYTHON_QT_INSTALLED
>   File "C:\Users\darke\Anaconda2\lib\site-packages\spyderlib\ipythonconfig.py", line 26, in <module>
>     required_version=ZMQ_REQVER)
>   File "C:\Users\darke\Anaconda2\lib\site-packages\spyderlib\dependencies.py", line 70, in add
>     installed_version)]
>   File "C:\Users\darke\Anaconda2\lib\site-packages\spyderlib\dependencies.py", line 32, in __init__
>     self.installed_version = programs.get_module_version(modname)
>   File "C:\Users\darke\Anaconda2\lib\site-packages\spyderlib\utils\programs.py", line 238, in get_module_version
>     mod = __import__(module_name)
>   File "C:\Users\darke\Anaconda2\lib\site-packages\zmq\__init__.py", line 66, in <module>
>     from zmq import backend
>   File "C:\Users\darke\Anaconda2\lib\site-packages\zmq\backend\__init__.py", line 21, in <module>
>     if platform.python_implementation() == 'PyPy':
>   File "C:\Python27\lib\platform.py", line 1451, in python_implementation
>     return _sys_version()[0]
>   File "C:\Python27\lib\platform.py", line 1416, in _sys_version
>     repr(sys_version))
> ValueError: failed to parse CPython sys.version: '2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]'

Does anyone have any idea of how to fix this problem ?

Thanks !

**Comment by ccordoba12** [comment]
It seems you have another Python installation in

    C:\Python27

I think if you just remove it things will work properly :-)

**Comment by Fheanor** [comment]
Well done, it works now :+1: 
Thank you very much and have a good day :)
