### ISSUE TITLE
Empty home tab in Navigator with system wide install

### ISSUE THREAD

**Issue by pebbe** [ContinuumIO/anaconda-issues#8066]
Anaconda Navigator 1.6.11 on Ubuntu 16.04.3 LTS

I have Anaconda installed on a location available for other users. When another user starts anaconda-navigator, the home tab is empty.

There are two work-arounds:

 1. Copy _ANACONDA_ROOT_`/pkgs/cache/*` to `~/.conda/pkgs/cache/` before starting the navigator; or
 2. The user starts Anaconda Navigator, goes to tab "Environments" and clicks "Update index...", then back to tab "Home"

I think Anaconda Navigator should on start-up automaticly update the index when it is empty.

**Comment by goanpeca** [comment]
Hi @pebbe this issue has been raised by other users. The original idea would be for Navigator not require an internet connection to start up. Now, we could detect the empty cache and ask the user for an "update of the index" when navigator has started. I am hesitant of doing this automatically as this process can be time consuming depending on other factors.

Thoughts @pebbe 

cc @csoja, @kalefranz

**Comment by goanpeca** [comment]
This has been already fix.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
