### ISSUE TITLE
Installing Miniconda with prefix into a long directory path can cause bad interpreter in shebang

### ISSUE THREAD

**Issue by mkobit** [ContinuumIO/anaconda-issues#8067]
Example:

* `mkdir -p /tmp/install-issue && cd /tmp/install-issue`
* `curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O`
* long path - `bash Miniconda3-latest-Linux-x86_64.sh -u -b -p "$PWD/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"`
* execute conda

        $PWD/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/bin/conda --version
        zsh: /tmp/install-issue/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/bin/conda: bad interpreter: /tmp/install-

* short path - `bash Miniconda3-latest-Linux-x86_64.sh -u -b -p "$PWD/test-install-dir"`
* execute conda

        $PWD/test-install-dir/bin/conda --version                              
        conda 4.3.31

The `conda` has an absolute path to the python executable of the prefix directory:

```
#!/tmp/install-issue/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/bin/python 
```

**Comment by kalefranz** [comment]
This issue was moved to conda/constructor#156
