### ISSUE TITLE
Navigator Error #1884 Revisited

### ISSUE THREAD

**Issue by xelcho** [ContinuumIO/anaconda-issues#8069]
I am have the issue described by another last year. Please see the output from anaconda navigator when launching orange 3.8.
os - ubuntu gnome 16.04.3
installed orange via anaconda.
Please advise.
Output:
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
/home/xelcho/anaconda3/lib/python3.6/site-packages/orangecontrib/prototypes/widgets/owclock.py:3: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
/home/xelcho/anaconda3/lib/python3.6/site-packages/orangecontrib/prototypes/widgets/owclock.py:3: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
from PyQt4.QtCore import Qt, QPoint, QDateTime, QSize, QRegExp
/home/xelcho/anaconda3/lib/python3.6/site-packages/orangecontrib/prototypes/widgets/owclock.py:4: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
from PyQt4.QtGui import QApplication, QCalendarWidget, QBrush, \
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://example.com/my-widget/docs/')'

**Comment by goanpeca** [comment]
@xelcho you should post on the orange3 repo
