### ISSUE TITLE
PyQt5 is not available from wheel on ARM platforms

### ISSUE THREAD

**Issue by mvillion** [ContinuumIO/anaconda-issues#8071]
Hello,

The PyQt5 dependency added since 3.2.5 breaks installation on ARM platforms.
Same issue on Odroid XU4 and Rapsberry Pi:

>> sudo pip3 install spyder -U
[...]
Collecting pyqt5; python_version >= "3" (from spyder)
  Could not find a version that satisfies the requirement pyqt5; python_version >= "3" (from spyder) (from versions: )
No matching distribution found for pyqt5; python_version >= "3" (from spyder)

A workaround may be:
>> sudo pip3 install rope nbconvert pylint psutil pyopengl chardet qtpy sphinx pyzmq jedi cloudpickle -U
>> sudo pip3 install spyder -U --no-deps

**Comment by csoja** [comment]
This is the wrong issue tracker for this question.  This issue tracker is for questions related to the Anaconda Distribution and conda packages or environments.  For PyPI pip installation issues, please refer to https://pypi.python.org/pypi
