### ISSUE TITLE
Color changing after an error

### ISSUE THREAD

**Issue by SHAPESNATCH** [ContinuumIO/anaconda-issues#808]
Hello,

I don't know if it's bug but I want to report it to you.

C:\Users\Laptop>  anaconda show color_changing
Using Anaconda Cloud api site https://api.anaconda.org
[NotFound] ('"color_changing" could not be found', 404)

Example: http://i.imgur.com/cCgVeVD.png

![alt tag](http://i.imgur.com/cCgVeVD.png)

The problem is that after displaying the error the text color is changing to white.

**Information:**
OS: Windows 10
System type: 64-bit

conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.6
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\Laptop\Anaconda3  (writable)
  default environment : C:\Users\Laptop\Anaconda3
     envs directories : C:\Users\Laptop\Anaconda3\envs
        package cache : C:\Users\Laptop\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\Users\Laptop>anaconda -V
anaconda-script.py Command line client (version 1.4.0)

**Comment by ilanschnell** [comment]
Thanks for the bug report.  This is really a problem in https://github.com/Anaconda-Platform/anaconda-client.
I opened an issue there https://github.com/Anaconda-Platform/anaconda-client/issues/326
