### ISSUE TITLE
Miniconda3-latest-Windows-x86_64 install failed on Windows 10

### ISSUE THREAD

**Issue by bssrdf** [ContinuumIO/anaconda-issues#8085]
Hi, Just tried to install latest version and got errors in post_install. Tried both full version (5.0.1 x64) and mini version, and the error is the same. Please see linked pic with error message. https://app.box.com/s/n75z6d6gy4oc7tnj75f8wwkgyqb1p7b4
I then clicked ignore button to proceed but I don't think installation is a success.

**Comment by mingwandroid** [comment]
Please paste the contents of your screenshot as text into this issue. You should not expect people to click on a random URL for security reasons.

**Comment by bssrdf** [comment]
![img_20180110_144333](https://user-images.githubusercontent.com/689043/34795709-2aa1444e-f621-11e7-92a7-d69effc54cb0.jpg)

Sorry, directly uploaded pic this time.

**Comment by bssrdf** [comment]
A bit more information.

After installation was finished (by ignoring the errror), I manually executed 
python -E -s "O:\Anaconda3\Lib\_nsis.py" post_install

and got the output
`allusers is True`
`Traceback (most recent call last):
  File "O:\Anaconda3\Lib\_nsis.py", line 176, in <module>
    main()
  File "O:\Anaconda3\Lib\_nsis.py", line 150, in main
    run_post_install()
  File "O:\Anaconda3\Lib\_nsis.py", line 93, in run_post_install
    subprocess.check_call(args, env=env)
  File "O:\Anaconda3\Lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "O:\Anaconda3\Lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "O:\Anaconda3\Lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "O:\Anaconda3\Lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by mingwandroid** [comment]
What kind of file system are you using on the `O:` drive? Also why did you change from using `C:`?

**Comment by bssrdf** [comment]
I tried C: and got the same error. Does driver letter matter in this case?

In fact I even tried installing anaconda via Visual Studio Community Edition. They all failed with the same error. So I suspect something in my Win 10 is messing up.

**Comment by bssrdf** [comment]
Apparently I set %COMSPEC% to the wrong value which caused all this mess. Sorry, please close this issue.
