### ISSUE TITLE
annaconda installation error

### ISSUE THREAD

**Issue by abhishj2** [ContinuumIO/anaconda-issues#8095]
Was using Anaconda Python 2.7.11 under Windows10 without problems for several months, until I tried to install Orange from the Launcher, as documented here. Strange things started happening, so I did windows uninstall and then installed Anaconda/Python35 2.4.1 64-bit. At the end of the install script, got three error messages:

- Failed to create Anaconda menus
- Failed to create Anaconda directories
- Failed to add Anaconda to the system PATH

**Comment by mingwandroid** [comment]
Why not install the latest version of Anaconda2 or Miniconda2 instead?

**Comment by abhishj2** [comment]
@mingwandroid bro installed anaconda 5 too ... But at last moment error arises like unable to create menus...does machine learning can be done in momiconda}?

**Comment by mingwandroid** [comment]
Anything you can do with `Anaconda` you can do with `Miniconda` since they can both install the exact same `Anaconda Distribution` packages.

**Comment by mingwandroid** [comment]
I don't know how you and your brother are trying to install here, `Just Me` is safest, and not adding to `PATH` is best. Can you run debugview from Microsoft when installing Anaconda 5.0.1 and show the output that gets printed there?

**Comment by abhishj2** [comment]
Again the same errror arising while installing momiconda

**Comment by mingwandroid** [comment]
I asked you for more details, I cannot help unless you do.

**Comment by mingwandroid** [comment]
Please try without using `All Users` too. It is more reliable.

**Comment by msarahan** [comment]
please see #3488 for more discussion and some workarounds that other users have found. The conflicting DLLs in PATH or cyrillic/non-ascii characters in install paths definitely seem to be the culprits, and we're working on addressing that for the next release.

Closing as duplicate.
