### ISSUE TITLE
Anaconda - Navigator totally crashed now, after trying to rollback.  ref # 7855 problem

### ISSUE THREAD

**Issue by flwheeler2** [ContinuumIO/anaconda-issues#8104]
Previously spyder would not launch, now the entire Anaconda - Navigator is dead. :-(. 

this has just gone bad to  very bad 

[anaconda3 roll back.txt](https://github.com/ContinuumIO/anaconda-issues/files/1623892/anaconda3.roll.back.txt)

reference problem #7855 .. which was never resolved  and the rollback suggestion did not work, even made things worse.    Where do I go from here.

**Comment by goanpeca** [comment]
@flwheeler2 please paste the output of running

```
anaconda-navigator
```

Plus the information of 

`conda info` and 

`conda list`
