### ISSUE TITLE
Anaconda Navigator crashes upon launch (Mac OS X high sierra)

### ISSUE THREAD

**Issue by anirbunt** [ContinuumIO/anaconda-issues#8127]
crash report:
Traceback (most recent call last):
File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/tabs/community.py", line 372, in set_content_list
uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
Abort trap: 6

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

**Comment by viraj1327** [comment]
I tried to go with goanpeca solution but didn't work. So the alternate way is open terminal->cd into Desktop directory->type jupyter notebook. It works as fine as you launch from anaconda-navigator.
