### ISSUE TITLE
how to run cython on Windows with VC9 installed by conda

### ISSUE THREAD

**Issue by Evfro** [ContinuumIO/anaconda-issues#8129]
I have a fresh Windows 10 system and installed Anaconda.
I'm trying to run simple `cython` test in Jupyter notebook (Python 2 environment with cython installed):

```python
import setuptools
%load_ext Cython
```
```python
%%cython --a
cdef int a = 0
```

However, I get a `DistutilsPlatformError` error saying:

> Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

My current understanding is that I do not need to install this extra package, because I already have `vc9` and `vs2008_runtime` in my conda environment:
```
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
```

The question is: is my understanding correct? If yes, how do I point cython/setuptools to the required binaries provided by `vc` package?

Thanks!

**Comment by mingwandroid** [comment]
vc does not contain any such binaries. You need to get these compilers from Microsoft or you can use m2w64-toolchain and libpython.

**Comment by Evfro** [comment]
Thanks! So I got a wrong impression on what VC actually does.
