### ISSUE TITLE
conda env export with wheel 0.30.0 sees error while importing

### ISSUE THREAD

**Issue by absk82** [ContinuumIO/anaconda-issues#8131]
Hi,
I am trying to export a conda environment with 'conda env export -p <>' . If the version of wheel is 0.29.0. I see correct output as the following : 
wheel=0.29.0=py35_0  or  
wheel=0.29.0=py34_0 or 
wheel=0.29.0=py27_0

depending on the version.

But if the version of wheel is 0.30.0, I see the following output : 
- wheel=0.30.0=py_1
Because of this, when using this exported file to create a new environment, I see the following error : 

  conda.exceptions.NoPackagesFoundError: Package missing in current linux-64 channels: 
      - wheel 0.30.0 py_1

Has someone encountered this issue ? I would appreciate any help.

**Comment by treerink** [comment]
I had the same issue, replace 
wheel=0.30.0=py_1
by
wheel=0.30.0=py27h2bc6bb2_1
solved it

**Comment by absk82** [comment]
Thanks ! Does this mean that conda export should be fixed this ? So far I have been changing the version of wheel to 0.29.0=py34_0 and so on and has been working.

**Comment by treerink** [comment]
Where you used wheel=0.30.0=py_1 before, you can now use:
wheel=0.30.0=py27h2bc6bb2_1       for python 2.7
wheel=0.30.0=py35hd3883cf_1        for python 3.5
wheel=0.30.0=py36hfd4bba0_1        for python 3.6
I found it by looking with:
conda info wheel

(obviously they changed/dropped the naming wheel=0.30.0=py_1 which broke our dependency references)

Our tool is entirely fixed by this replacement.

**Comment by kalefranz** [comment]
For someone having this issue, can you provide the output of

    conda list --show-channel-urls

**Comment by absk82** [comment]
Here is the output : 

(.conda/testProject2) dcuser63012373@e0e0151ec07f:/mnt/ebs/hadibeencool@gmail.com/testProject2$ conda list --show-channel-urls
# packages in environment at /mnt/ebs/hadibeencool@gmail.com/testProject2/.conda/testProject2:
#
backports_abc             0.5                      py34_0    conda-forge
bzip2                     1.0.6                         3    defaults
ca-certificates           2017.11.5                     0    conda-forge
cairo                     1.14.8                        0    defaults
certifi                   2017.1.23                py34_0    conda-forge
configparser              3.5.0                    py34_0    conda-forge
curl                      7.54.1                        0    defaults
dbus                      1.10.22                       0    conda-forge
decorator                 4.0.10                   py34_0    conda-forge
entrypoints               0.2.2                    py34_1    conda-forge
expat                     2.2.5                         0    conda-forge
fontconfig                2.12.1                        3    defaults
freetype                  2.5.5                         2    defaults
gettext                   0.19.7                        1    conda-forge
glib                      2.50.2                        1    defaults
gmp                       6.1.0                         0    defaults
gsl                       2.2.1                         0    defaults
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
harfbuzz                  0.9.39                        2    defaults
icu                       54.1                          0    defaults
ipykernel                 4.5.2                    py34_0    conda-forge
ipython                   5.1.0                    py34_2    conda-forge
ipython_genutils          0.2.0                    py34_0    conda-forge
ipywidgets                5.2.2                    py34_2    conda-forge
jbig                      2.1                           0    defaults
jinja2                    2.9.5                    py34_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.5.1                    py34_0    conda-forge
jupyter                   1.0.0                    py34_3    defaults
jupyter_client            4.4.0                    py34_0    conda-forge
jupyter_console           5.1.0                    py34_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.13.2                        0    defaults
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0    defaults
libiconv                  1.14                          0    defaults
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.15                        1    conda-forge
libssh2                   1.8.0                         0    defaults
libtiff                   4.0.6                         3    defaults
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         0    defaults
markupsafe                1.0                      py34_0    conda-forge
mistune                   0.8.3                      py_0    conda-forge
mkl                       2017.0.3                      0    defaults
nb_conda_kernels          2.0.0                    py34_0    conda-forge
nbconvert                 4.2.0                    py34_0    conda-forge
nbformat                  4.2.0                    py34_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  4.3.1                    py34_0    conda-forge
numpy                     1.13.3                    <pip>
openssl                   1.0.2n                        0    conda-forge
pandoc                    1.15.0.6                      0    defaults
pango                     1.40.3                        1    defaults
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py34_0    conda-forge
pickleshare               0.7.3                    py34_0    conda-forge
pip                       9.0.1                    py34_0    conda-forge
pixman                    0.34.0                        0    defaults
prompt_toolkit            1.0.9                    py34_0    conda-forge
ptyprocess                0.5.1                    py34_0    conda-forge
pygments                  2.1.3                    py34_1    conda-forge
pyqt                      5.6.0                    py34_2    defaults
python                    3.4.5                         2    conda-forge
pyzmq                     16.0.2                   py34_0    conda-forge
qt                        5.6.2                         5    defaults
qtconsole                 4.2.1                    py34_0    conda-forge
r-assertthat              0.2.0                  r3.4.1_0    r
r-backports               1.1.0                  r3.4.1_0    r
r-base                    3.4.1                         1    r
r-base64enc               0.1_3                  r3.4.1_0    r
r-bh                      1.62.0_1               r3.4.1_0    r
r-bindr                   0.1                    r3.4.1_0    r
r-bindrcpp                0.2                    r3.4.1_0    r
r-bitops                  1.0_6                  r3.4.1_2    r
r-boot                    1.3_19                 r3.4.1_0    r
r-broom                   0.4.2                  r3.4.1_0    r
r-car                     2.1_4                  r3.4.1_0    r
r-caret                   6.0_76                 r3.4.1_0    r
r-catools                 1.17.1                 r3.4.1_2    r
r-cellranger              1.1.0                  r3.4.1_0    r
r-class                   7.3_14                 r3.4.1_0    r
r-cluster                 2.0.6                  r3.4.1_0    r
r-codetools               0.2_15                 r3.4.1_0    r
r-colorspace              1.3_2                  r3.4.1_0    r
r-crayon                  1.3.2                  r3.4.1_0    r
r-curl                    2.6                    r3.4.1_0    r
r-data.table              1.10.4                 r3.4.1_0    r
r-dbi                     0.6_1                  r3.4.1_0    r
r-dichromat               2.0_0                  r3.4.1_2    r
r-digest                  0.6.12                 r3.4.1_0    r
r-dplyr                   0.7.0                  r3.4.1_0    r
r-essentials              1.5.2                  r3.4.1_0    r
r-evaluate                0.10                   r3.4.1_0    r
r-forcats                 0.2.0                  r3.4.1_0    r
r-foreach                 1.4.3                  r3.4.1_0    r
r-foreign                 0.8_68                 r3.4.1_0    r
r-formatr                 1.5                    r3.4.1_0    r
r-ggplot2                 2.2.1                  r3.4.1_0    r
r-gistr                   0.4.0                  r3.4.1_0    r
r-glmnet                  2.0_10                 r3.4.1_0    r
r-glue                    1.1.1                  r3.4.1_0    r
r-gtable                  0.2.0                  r3.4.1_0    r
r-haven                   1.0.0                  r3.4.1_0    r
r-hexbin                  1.27.1                 r3.4.1_0    r
r-highr                   0.6                    r3.4.1_0    r
r-hms                     0.3                    r3.4.1_0    r
r-htmltools               0.3.6                  r3.4.1_0    r
r-htmlwidgets             0.8                    r3.4.1_1    r
r-httpuv                  1.3.3                  r3.4.1_0    r
r-httr                    1.2.1                  r3.4.1_0    r
r-irdisplay               0.4.4                  r3.4.1_0    r
r-irkernel                0.7.1                  r3.4.1_0    r
r-iterators               1.0.8                  r3.4.1_0    r
r-jsonlite                1.5                    r3.4.1_0    r
r-kernsmooth              2.23_15                r3.4.1_0    r
r-knitr                   1.16                   r3.4.1_0    r
r-labeling                0.3                    r3.4.1_2    r
r-lattice                 0.20_35                r3.4.1_0    r
r-lazyeval                0.2.0                  r3.4.1_0    r
r-lme4                    1.1_13                 r3.4.1_0    r
r-lubridate               1.6.0                  r3.4.1_0    r
r-magrittr                1.5                    r3.4.1_2    r
r-maps                    3.2.0                  r3.4.1_0    r
r-markdown                0.8                    r3.4.1_0    r
r-mass                    7.3_47                 r3.4.1_0    r
r-matrix                  1.2_10                 r3.4.1_0    r
r-matrixmodels            0.4_1                  r3.4.1_0    r
r-mgcv                    1.8_17                 r3.4.1_0    r
r-mime                    0.5                    r3.4.1_0    r
r-minqa                   1.2.4                  r3.4.1_2    r
r-mnormt                  1.5_5                  r3.4.1_0    r
r-modelmetrics            1.1.0                  r3.4.1_0    r
r-modelr                  0.1.0                  r3.4.1_0    r
r-munsell                 0.4.3                  r3.4.1_0    r
r-nlme                    3.1_131                r3.4.1_0    r
r-nloptr                  1.0.4                  r3.4.1_2    r
r-nnet                    7.3_12                 r3.4.1_0    r
r-openssl                 0.9.6                  r3.4.1_0    r
r-pbdzmq                  0.2_6                  r3.4.1_0    r
r-pbkrtest                0.4_7                  r3.4.1_0    r
r-pkgconfig               2.0.1                  r3.4.1_0    r
r-plogr                   0.1_1                  r3.4.1_0    r
r-plyr                    1.8.4                  r3.4.1_0    r
r-pryr                    0.1.2                  r3.4.1_0    r
r-psych                   1.7.5                  r3.4.1_0    r
r-purrr                   0.2.2.2                r3.4.1_0    r
r-quantmod                0.4_9                  r3.4.1_0    r
r-quantreg                5.33                   r3.4.1_0    r
r-r6                      2.2.1                  r3.4.1_0    r
r-randomforest            4.6_12                 r3.4.1_0    r
r-rbokeh                  0.5.0                  r3.4.1_0    r
r-rcolorbrewer            1.1_2                  r3.4.1_3    r
r-rcpp                    0.12.11                r3.4.1_0    r
r-rcppeigen               0.3.3.3.0              r3.4.1_0    r
r-readr                   1.1.1                  r3.4.1_0    r
r-readxl                  1.0.0                  r3.4.1_0    r
r-recommended             3.4.1                  r3.4.1_0    r
r-rematch                 1.0.1                  r3.4.1_0    r
r-repr                    0.10                   r3.4.1_0    r
r-reshape2                1.4.2                  r3.4.1_0    r
r-rlang                   0.1.1                  r3.4.1_0    r
r-rmarkdown               1.5                    r3.4.1_0    r
r-rpart                   4.1_11                 r3.4.1_0    r
r-rprojroot               1.2                    r3.4.1_0    r
r-rvest                   0.3.2                  r3.4.1_0    r
r-scales                  0.4.1                  r3.4.1_0    r
r-selectr                 0.3_1                  r3.4.1_0    r
r-shiny                   1.0.3                  r3.4.1_0    r
r-sourcetools             0.1.6                  r3.4.1_0    r
r-sparsem                 1.77                   r3.4.1_0    r
r-spatial                 7.3_11                 r3.4.1_0    r
r-stringi                 1.1.5                  r3.4.1_0    r
r-stringr                 1.2.0                  r3.4.1_0    r
r-survival                2.41_3                 r3.4.1_0    r
r-tibble                  1.3.3                  r3.4.1_0    r
r-tidyr                   0.6.3                  r3.4.1_0    r
r-tidyverse               1.1.1                  r3.4.1_0    r
r-ttr                     0.23_1                 r3.4.1_0    r
r-uuid                    0.1_2                  r3.4.1_0    r
r-xml2                    1.1.1                  r3.4.1_0    r
r-xtable                  1.8_2                  r3.4.1_0    r
r-xts                     0.9_7                  r3.4.1_2    r
r-yaml                    2.1.14                 r3.4.1_0    r
r-zoo                     1.8_0                  r3.4.1_0    r
readline                  6.2                           0    conda-forge
setuptools                32.3.1                   py34_0    conda-forge
simplegeneric             0.8.1                    py34_0    conda-forge
sip                       4.18                     py34_1    conda-forge
six                       1.10.0                   py34_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py34_0    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   4.4.2                    py34_0    conda-forge
traitlets                 4.3.1                    py34_0    conda-forge
wcwidth                   0.1.7                    py34_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
widgetsnbextension        1.2.6                    py34_3    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.1.5                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

**Comment by kalefranz** [comment]
Thanks @absk82.  Can you also give me the output of `conda info`?

**Comment by absk82** [comment]
Here it is : 

Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /mnt/ebs/hadibeencool@gmail.com/conda_env  (writable)
    default environment : /mnt/ebs/hadibeencool@gmail.com/testProject2/.conda/testProject2
       envs directories : /mnt/ebs/hadibeencool@gmail.com/conda_env/envs
                          /home/dcuser63012373/.conda/envs
          package cache : /mnt/ebs/hadibeencool@gmail.com/conda_env/pkgs
                          /home/dcuser63012373/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.10.0-42-generic debian/8.9 glibc/2.19    
                UID:GID : 30632126:30632126

**Comment by absk82** [comment]
I am seeing a similar issue with bzip2 also:

    conda.exceptions.NoPackagesFoundError: Package missing in current linux-64 channels: 
      - bzip2 1.0.6 h6d464ef_2

Here is the conda env export log :

**Comment by absk82** [comment]
Another one for widgetsnbextension. I don't see version 3.0.3 listed when I run 'conda info widgetsnbextension' .

    Traceback (most recent call last):
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda_env/installers/conda.py", line 32, in install
        channel_priority_map=_channel_priority_map)
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda/plan.py", line 475, in install_actions_list
        dists_for_envs = determine_all_envs(r, specs, channel_priority_map=channel_priority_map)
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda/plan.py", line 540, in determine_all_envs
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda/plan.py", line 540, in <genexpr>
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda/plan.py", line 539, in <genexpr>
        best_pkgs = (r.index[r.get_dists_for_spec(s, emptyok=False)[-1]] for s in specs)
      File "/mnt/ebs/blibxmpp@gmail.com/conda_env/lib/python3.6/site-packages/conda/resolve.py", line 563, in get_dists_for_spec
        raise ResolvePackageNotFound([(ms,)])
    conda.exceptions.ResolvePackageNotFound: 
      - widgetsnbextension 3.0.3 py_1

**Comment by kalefranz** [comment]
Please `conda update conda` to at least conda >= 4.3.27.
