### ISSUE TITLE
Anaconda installer fails when run as system context.

### ISSUE THREAD

**Issue by brismithPDX** [ContinuumIO/anaconda-issues#816]
Bug:
Anaconda installer fails when run as system context.

Environment: 
Windows 7 x64 Enterprise, 4gb ram, visualized, domain bound machine.

Steps to reproduce: 
kick off standard installer with the following flags in the system context. "/InstallationType=AllUsers /AddToPath=1 /RegisterPython=1 /S /D=C:\Anaconda3"

Context for bug: 
Microsoft System Center Configuration Manager (SCCM) runs application installers as system context (the same context as the SCCM agent).

SCCM is used for automating the deployment of software to large environments or allowing users access and install from a managed pool of approved software with out administrative privileges.

Information on SCCM Application deployment -
https://technet.microsoft.com/en-us/library/gg682082.aspx

Cause of Bug:
Installer attempts to use the "CSIDL_DESKTOPDIRECTORY" environmental variable that unavailable in the system context and inappropriate to use in a "all users" instillation mode.

Solution for Bug:
The "CSIDL_COMMON_DESKTOPDIRECTORY" environmental variable should be used instead, this variable is available in the system context and better suited for a "all users" installation mode.

Additional information:
Recognized Environmental Variables for system and user contexts reference -
https://technet.microsoft.com/en-us/library/dd560744(v=ws.10).aspx

Installation Contexts folder redirection and environmental variable reference -
https://msdn.microsoft.com/en-us/library/windows/desktop/dd765197(v=vs.85).aspx

Evidence of Bug:
Image of error message produced by installation attempt attached below.

![andaconda weirdness](https://cloud.githubusercontent.com/assets/19806848/15874447/0d376a84-2cb8-11e6-85be-0e015cca3d86.png)

Problem still exists in current ver. Anaconda 4:
![pasted image at 2016_06_07 01_44 pm](https://cloud.githubusercontent.com/assets/19806848/15874485/325354ea-2cb8-11e6-8afb-7982677fdb12.png)

**Comment by mingwandroid** [comment]
Indeed, very good.

**Comment by brismithPDX** [comment]
Just finished testing. The 4.1 release installer appears to work perfectly from system center and from the system user context.

Thank you very much for fixing this bug for us, it help out our deployments so freaking much!
If there is anything we can do for you or to help with "enterprise" or educational deployment testing just let me know.

**Comment by mingwandroid** [comment]
Brilliant! Many thanks for getting back to us with this confirmation. For testing it, well, just continue using it and keep the quality bug reports coming when you find issues.

**Comment by msarahan** [comment]
Marking this as closed, so I don't forget about it.  It will not actually be closed until the Anaconda 4.1 release, though...
