### ISSUE TITLE
Error when installing Anaconda 4.0.0 for ubuntu bundled with Windows 10 build 14342 Insider Preview

### ISSUE THREAD

**Issue by mpage38** [ContinuumIO/anaconda-issues#818]
I am experiencing error messages when I am installing Anaconda 4.0.0 (64-bit) for ubuntu bundled with Windows 10 Insider Preview.

ERROR:__main__: failed to link (src='/home/mp/anaconda3/pkgs/xxx', dst='/home/mp/anaconda3/lib/xxx', type=3, error=OSError(38, 'Function not implemented')

The installation terminates and python seems to work correctly, including libraries, but jupyter notebook won't work: notebook can't connect to the kernel.

**Comment by mingwandroid** [comment]
Are you trying to run Jupyter from Anaconda for Linux on Ubuntu Bash for Windows? Or is Jupyter a native Windows build? I'm guessing the latter since Linux GUI applications can't run on Ubuntu Bash for Windows at all.

**Comment by mpage38** [comment]
I am running Jupyter from Anaconda for Linux on Ubuntu Bash for Windows 10. I intended to run Jupyter notebooks in a browser.

**Comment by rogersachan** [comment]
Was this fixed as of build 14366?

**Comment by mpage38** [comment]
Yes, in Win10 build 14366, Anaconda gets installed without error message.
