### ISSUE TITLE
bunzip2: command not found

### ISSUE THREAD

**Issue by lambdaq** [ContinuumIO/anaconda-issues#8182]
### Actual Behavior

Miniconda2-latest-Linux-x86_64.sh fails to install

    bunzip2: command not found

### Expected Behavior

We could install regardless of bunzip2 utillity

### Steps to Reproduce

1. download https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
2. chmod 755 Miniconda2-latest-Linux-x86_64.sh && ./Miniconda2-latest-Linux-x86_64.sh

##### Anaconda or Miniconda version:

miniconda2-latest

##### Operating System:

Centos7

### suggestion:

CentOS7 does not have `bunzip2` utility pre-installed. And many of our linux accounts does not have limited or no `sudo` capability. 

But since Python has a built-in https://docs.python.org/2/library/bz2.html library, can we use this library to substitute the `bunzip2` command just in case?

### example script:

    #!/usr/bin/env python
    import bz2, sys
    print bz2.BZ2File(sys.argv[2]).read()

Save the script as `bunzip2`, place it under some dir in your `$PATH`, and the setup can be done smoothly.

**Comment by msarahan** [comment]
At the point that we run the installer, python itself exists within a bzip2 archive.  We can't assume that system python is available for us to use.

I think the next best thing is to bundle a self-contained bunzip2 executable in the installer, and always use that.

**Comment by lambdaq** [comment]
@msarahan  Most Linux systems have Python pre-installed. We can cover **more** distros with low cost, just few lines of code.

**Comment by msarahan** [comment]
Really?  I would expect bunzip2 to be more omnipresent than python.  Regardless, we need to gather evidence to guide any decision on this matter.  Assuming anything about the host system is what got us into hot water in the first place.  If a standalone fix is viable, it is preferable to anything that depends on the system in any way.

**Comment by jonnyhtw** [comment]
I'm getting this error when trying to install miniconda on google cloud platform FYI.

Cheers

**Comment by msarahan** [comment]
We are too deep into our release cycle for the Anaconda 5.1 release to fix this now.  We have added it to our 5.2 release milestone.  Miniconda installers may have this fix sooner.

**Comment by lambdaq** [comment]
@msarahan just a side note, bz2 is inefficient in both compression speed and ratio. Maybe in later versions we can use `xz` instead of `bz2`.

**Comment by harryscholes** [comment]
@jonnyhtw I got it working by first running `sudo apt-get install bzip2` btw

**Comment by jonnyhtw** [comment]
Thanks @harryscholes 

I'll have a look at that...

Jonny

**Comment by mnnit-geek** [comment]
For centos, `yum install bzip2` works just as fine!

**Comment by ryancat** [comment]
`sudo apt-get install bzip2` works for me too! Thanks!

**Comment by kbrose** [comment]
Seems to still be a problem on 5.3.0

**Comment by msf1t** [comment]
Still requires bunzip2...

**Comment by missingdaysqxy** [comment]
> ### Actual Behavior
> Miniconda2-latest-Linux-x86_64.sh fails to install
> 
> ```
> bunzip2: command not found
> ```
> ### Expected Behavior
> We could install regardless of bunzip2 utillity
> 
> ### Steps to Reproduce
> 1. download https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
> 2. chmod 755 Miniconda2-latest-Linux-x86_64.sh && ./Miniconda2-latest-Linux-x86_64.sh
> 
> ##### Anaconda or Miniconda version:
> miniconda2-latest
> 
> ##### Operating System:
> Centos7
> 
> ### suggestion:
> CentOS7 does not have `bunzip2` utility pre-installed. And many of our linux accounts does not have limited or no `sudo` capability.
> 
> But since Python has a built-in https://docs.python.org/2/library/bz2.html library, can we use this library to substitute the `bunzip2` command just in case?
> 
> ### example script:
> ```
> #!/usr/bin/env python
> import bz2, sys
> print bz2.BZ2File(sys.argv[2]).read()
> ```
> Save the script as `bunzip2`, place it under some dir in your `$PATH`, and the setup can be done smoothly.

wonderful idea. I solved my problem when I install anaconda in server. Mark this~~

**Comment by norru** [comment]
Ubuntu 18.04.2, `bzip2` package is INSTALLED and I have `bunzip2` in the path.

```
$ pyenv install anaconda2-2018.12
Installing Anaconda2-2018.12-Linux-x86_64.sh...

BUILD FAILED (Ubuntu 18.04 using python-build 1.2.9-19-g7d02b246)

Inspect or clean up the working tree at /tmp/python-build.20190311105339.428
Results logged to /tmp/python-build.20190311105339.428.log

Last 10 log lines:
/tmp/python-build.20190311105339.428 ~/Projects/ivt/parallax_testbed/scripts
/tmp/python-build.20190311105339.428/Anaconda2-2018.12-Linux-x86_64.sh /tmp/python-build.20190311105339.428 ~/Projects/ivt/parallax_testbed/scripts
WARNING: bzip2 does not appear to be installed this may cause problems below
PREFIX=/home/norru/.pyenv/versions/anaconda2-2018.12
pyenv: bunzip2: command not found
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

I've found the following workaround:

```
export PATH=/bin:$PATH
pyenv install anaconda2-2018.12
```

**Comment by FabianHenneke** [comment]
Since jitpack.io does not have `bunzip2` installed on their build servers, projects using miniconda can't build there. It would be great if this dependency could be removed.

**Comment by mingwandroid** [comment]
This has been fixed for a long time now.
