### ISSUE TITLE
Tkinter is not available on Anaconda 1.8 with Python 2.7

### ISSUE THREAD

**Issue by dtrillo** [ContinuumIO/anaconda-issues#82]
I work with Anaconda version if Python, 1.8 and I'm using Python 2.7

I am trying to use Tkinter , but I got an error. This package is not available by default?

**Comment by trevorwitter** [comment]
If using python V3.0 or later, import tkinter with lowercase "t". For python versions prior to V3.0, import Tkinter with a  capital "T"

https://wiki.python.org/moin/TkInter

**Comment by daohu527** [comment]
thanks, it worked for use "tkinter" instead "Tkinter"
