### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aspaccela** [ContinuumIO/anaconda-issues#8217]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[W 18:49:29.207 LabApp] Terminals not available (error was No module named 'terminado')
[I 18:49:29.217 LabApp] JupyterLab beta preview extension loaded from C:\Users\asanchep\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyterlab
[I 18:49:29.217 LabApp] JupyterLab application directory is C:\Users\asanchep\AppData\Local\Continuum\Anaconda3\share\jupyter\lab
[W 18:49:29.220 LabApp] JupyterLab server extension not enabled, manually loading...
[I 18:49:29.221 LabApp] JupyterLab beta preview extension loaded from C:\Users\asanchep\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyterlab
[I 18:49:29.228 LabApp] JupyterLab application directory is C:\Users\asanchep\AppData\Local\Continuum\Anaconda3\share\jupyter\lab
[I 18:49:29.516 LabApp] Serving notebooks from local directory: C:\Users\asanchep
[I 18:49:29.516 LabApp] 0 active kernels
[I 18:49:29.516 LabApp] The Jupyter Notebook is running at:
[I 18:49:29.516 LabApp] http://localhost:8888/?token=7f38f19137aa4f90afcf00d2dac20053aa548d84c4c426b9
[I 18:49:29.516 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:49:29.528 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=7f38f19137aa4f90afcf00d2dac20053aa548d84c4c426b9
[I 18:49:30.006 LabApp] Accepting one-time-token-authenticated connection from ::1
[I 18:49:30.579 LabApp] Build is up to date
[I 18:49:31.139 LabApp] Kernel started: ee9e0270-0a27-42f6-bbc2

**Comment by goanpeca** [comment]
@blink1023

**Comment by blink1073** [comment]
I don't understand that context.  JupyterLab is failing to start, and this is the console log?

**Comment by goanpeca** [comment]
That is the output of starting jupyter lab... would have been equivalente to launch it from the console. We capture the output in log files, if something seems "wrong" we prompt for a possible error.

In this case the trigger was `JupyterLab is failing to start, and this is the console log?`

**Comment by blink1073** [comment]
I would expect that warning when using notebook < 5.3 on Windows.

**Comment by goanpeca** [comment]
@aspaccela please provide the output of

```
conda info
```

and

```
conda list
```

**Comment by aspaccela** [comment]
conda info:
     active environment : base
    active env location : C:\Users\asanchep\AppData\Local\Continuum\Anaconda3
            shell level : 1
       user config file : C:\Users\asanchep\.condarc
 populated config files : C:\Users\asanchep\.condarc
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : C:\Users\asanchep\AppData\Local\Continuum\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\asanchep\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\asanchep\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\asanchep\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\asanchep\AppData\Local\conda\conda\envs
                          C:\Users\asanchep\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False

conda list:
# packages in environment at C:\Users\asanchep\AppData\Local\Continuum\Anaconda3:
#
_license                  1.1                      py36_1
alabaster                 0.7.10                   py36_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.3                    py36_0
anaconda-navigator        1.6.2                    py36_0
anaconda-project          0.6.0                    py36_0
anyqt                     0.0.8                    py36_0
asn1crypto                0.24.0                   py36_0
astroid                   1.4.9                    py36_0
astropy                   2.0.3            py36hfa6e2cd_0
attrs                     17.3.0           py36hc87868e_0
babel                     2.4.0                    py36_0
backports                 1.0              py36h81696a8_1
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2
beautifulsoup4            4.6.0                    py36_0
bitarray                  0.8.1                    py36_1
blaze                     0.10.1                   py36_0
bleach                    2.1.2                    py36_0
bokeh                     0.12.13          py36h047fa9f_0
boto                      2.46.1                   py36_0
bottleneck                1.2.1            py36hd119dfa_0
bzip2                     1.0.6                haa5b126_2
ca-certificates           2017.08.26           h94faf87_0
certifi                   2017.11.5        py36hb8ac631_0
cffi                      1.11.4           py36hfa6e2cd_0
chardet                   3.0.4            py36h420ce6e_1
click                     6.7              py36hec8c647_0
cloudpickle               0.5.2            py36h6b1d831_0
clyent                    1.2.2                    py36_0
colorama                  0.3.9            py36h029ae33_0
comtypes                  1.1.2                    py36_0
conda                     4.4.7                    py36_0
conda-env                 2.6.0                h36134e3_1
console_shortcut          0.1.1                    py36_1
contextlib2               0.5.5                    py36_0
coverage                  4.4.2            py36hd32d05b_0
cryptography              2.1.4            py36he1d7878_0
curl                      7.52.1                   vc14_0  [vc14]
cycler                    0.10.0           py36h009560c_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.16.1                   py36_0
dask-core                 0.16.1                   py36_0
datashape                 0.5.4                    py36_0
decorator                 4.2.1                    py36_0
dill                      0.2.7.1          py36hf552773_0
distributed               1.20.2                   py36_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3            py36hfd66bb0_2
et_xmlfile                1.0.1                    py36_0
fastcache                 1.0.2                    py36_1
flask                     0.12.2           py36h98b5e8f_0
flask-cors                3.0.2                    py36_0
freetype                  2.8                  h51f8f2c_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py36h342a76c_0
glue-core                 0.12.3           py36hf2828cb_0
glue-vispy-viewers        0.9              py36h7596f00_0
glueviz                   0.12.0               ha37a3ef_0
greenlet                  0.4.12           py36ha00ad21_0
h5py                      2.7.0               np112py36_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0            py36h21fa5f4_0
html5lib                  1.0.1            py36h047fa9f_0
hypothesis                3.38.5           py36h987501d_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.6              py36h148d497_1
imageio                   2.2.0            py36had6c2d2_0
imagesize                 0.7.1                    py36_0
intel-openmp              2018.0.0             hd92c6cd_8
ipykernel                 4.7.0            py36h2f9c1c0_0
ipython                   6.2.1            py36h9cf0123_1
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                6.0.0                    py36_0
isort                     4.2.5                    py36_0
itsdangerous              0.24             py36hb6c5a24_1
jdcal                     1.3                      py36_0
jedi                      0.11.1                   py36_0
jinja2                    2.10             py36h292fed1_0
joblib                    0.11                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_3
jupyter_client            5.2.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.31.1                   py36_0
jupyterlab_launcher       0.10.2                   py36_0
keyring                   10.5.0           py36h410770b_0
lazy-object-proxy         1.2.2                    py36_0
libpng                    1.6.32               h140d38e_4
libtiff                   4.0.9                h0f13578_0
llvmlite                  0.18.0                   py36_0
locket                    0.2.0            py36hfed976d_1
lxml                      3.7.3                    py36_0
markupsafe                1.0              py36h0e26971_1
matplotlib                2.1.1            py36h2062329_0
menuinst                  1.4.7                    py36_0
mistune                   0.8.3                    py36_0
mkl                       2018.0.1             h2108138_4
mkl-service               1.1.2            py36h57e144c_4
mpmath                    0.19                     py36_1
msgpack-python            0.5.1            py36he980bc4_0
multipledispatch          0.4.9                    py36_0
navigator-updater         0.1.0                    py36_0
nbconvert                 5.3.1            py36h8dc0fde_0
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.0              py36hff991e3_0
nltk                      3.2.3                    py36_0
nose                      1.3.7            py36h1c3779e_2
notebook                  5.3.1                    py36_0
numba                     0.33.0              np112py36_0
numexpr                   2.6.4            py36h30784b8_0
numpy                     1.12.1           py36hf30b8aa_1
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
olefile                   0.44             py36h0a7bdd2_0
openpyxl                  2.4.7                    py36_0
openssl                   1.0.2n               h74b6da3_0
orange3                   3.4.1                    py36_0
packaging                 16.8             py36ha0986f6_1
pandas                    0.22.0           py36h6538335_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36h3ef6317_1
parso                     0.1.1            py36hae3edee_0
partd                     0.3.8            py36hc8e763b_0
path.py                   10.5             py36h2b94a8f_0
pathlib2                  2.3.0            py36h7bfb78b_0
patsy                     0.4.1                    py36_0
pep8                      1.7.0                    py36_0
pickleshare               0.7.4            py36h9de030f_0
pillow                    5.0.0            py36h0738816_0
pip                       9.0.1            py36h226ae91_4
plotly                    2.2.2            py36h554761e_0
pluggy                    0.6.0            py36hc7daf1e_0
ply                       3.10                     py36_0
prompt_toolkit            1.0.15           py36h60b8f86_0
psutil                    5.4.3            py36hfa6e2cd_0
py                        1.5.2            py36hbcfbabc_0
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.18             py36hd053e01_1
pycrypto                  2.6.1                    py36_6
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.2.0            py36hb010967_0
pylint                    1.6.4                    py36_1
pympler                   0.5              py36h863af32_0
pyodbc                    4.0.16                   py36_0
pyopengl                  3.1.1a1             np112py36_0
pyopenssl                 17.5.0           py36h5b7d817_0
pyparsing                 2.2.0            py36h785a196_1
pyqt                      5.6.0            py36hb5ed885_5
pyqtgraph                 0.10.0                   py36_0
pyreadline                2.1              py36h094d952_1
pysocks                   1.6.7            py36h698d350_1
pytables                  3.2.2               np112py36_4
pytest                    3.3.2                    py36_0
python                    3.6.4                h6538335_1
python-dateutil           2.6.1            py36h509ddcb_1
pytz                      2017.3           py36h1d3fa6b_0
pywavelets                0.5.2            py36hc649158_0
pywin32                   221              py36h9c10281_0
pyyaml                    3.12             py36h1d1928f_1
pyzmq                     16.0.3           py36he714bf5_0
qt                        5.6.2           vc14h6f8c307_12
qtawesome                 0.4.4                    py36_0
qtconsole                 4.3.1            py36h99a29a9_0
qtpy                      1.3.1            py36hb8717c5_0
requests                  2.18.4           py36h4371aae_1
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.13.1           py36hfa6e2cd_1
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0            py36h1260518_0
seaborn                   0.7.1                    py36_0
send2trash                1.4.2                    py36_0
setuptools                38.4.0                   py36_0
simplegeneric             0.8.1            py36heab741f_0
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.18.1           py36h9c25514_2
six                       1.11.0           py36h4db2310_1
snowballstemmer           1.2.1                    py36_0
sortedcollections         0.5.3            py36hbefa0ab_0
sortedcontainers          1.5.9                    py36_0
sphinx                    1.5.6                    py36_0
spyder                    3.1.4                    py36_0
sqlalchemy                1.1.9                    py36_0
sqlite                    3.20.1               h9eeafa9_2
statsmodels               0.8.0               np112py36_0
sympy                     1.0                      py36_0
tblib                     1.3.2            py36h30f5020_0
testpath                  0.3.1            py36h2698cfe_0
tk                        8.6.7                hcb92d03_3
toolz                     0.9.0                    py36_0
tornado                   4.5.3                    py36_0
traitlets                 4.3.2            py36h096827d_0
unicodecsv                0.14.1                   py36_0
urllib3                   1.22             py36h276f60a_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1            py36h67c50ae_1
werkzeug                  0.14.1                   py36_0
wheel                     0.30.0           py36h6c3ec14_1
widgetsnbextension        2.0.0                    py36_0
win_inet_pton             1.0.1            py36he67d7fd_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.10                  py36_0
xlrd                      1.1.0            py36h1cb58dc_1
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.4                   py36_0
xlwt                      1.2.0                    py36_0
yaml                      0.1.7                hc54c509_2
zict                      0.1.3            py36h2d8e73e_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py36_0
zope.interface            4.4.3            py36h56cab3c_0

Note that this has happened after a conda update --all.
The environment is fully operative as far as I have tested

**Comment by blink1073** [comment]
@goanpeca, this could be a matter of the default channel notebook needing to be updated to include the `terminado` dependency: https://github.com/conda-forge/notebook-feedstock/pull/27

**Comment by goanpeca** [comment]
@blink1073 yes, most likely, raising an issue for this

**Comment by goanpeca** [comment]
@blink1073 it iseems to be just fine https://github.com/AnacondaRecipes/notebook-feedstock/blob/master/recipe/meta.yaml

**Comment by blink1073** [comment]
@aspaccela, can you please try running `conda uninstall notebook && conda install notebook`?  It looks like a new release of the notebook package should pick up the `terminado` requirement.

**Comment by aspaccela** [comment]
Uninstalled and installed notebook as requested...
But the problem remains... Should I try a fully uninstallation and installation of Anaconda?

**Comment by blink1073** [comment]
@aspaccela, does it work if you specifically run `conda install terminado`?

**Comment by jjhelmus** [comment]
`terminado` is not yet available in `defaults` for windows.  We are investigating the best option for including this as well as `winpty` and `pywinpty`.  Mixing VS runtimes is not a appealing option for us.

**Comment by jjhelmus** [comment]
`terminado` 0.8.1 is available for windows along with `winpty` and `pywinpty`.  `notebook` 5.4.0 and a new build of 5.3.1 have a dependency on `terminado` regardless of the platform. 

With these packages available, running `conda install notebook terminado` should fix this issue.

**Comment by aspaccela** [comment]
As suggested, I executed `conda install notebook terminado` and the fix was solved.

Thanks.

**Comment by goanpeca** [comment]
Thanks for working on this fix @jjhelmus
