### ISSUE TITLE
How to use Navigator on Windows with custom environments?

### ISSUE THREAD

**Issue by rsignell-usgs** [ContinuumIO/anaconda-issues#822]
Using Navigator on Windows, I can't figure out how to launch the Jupyter Notebook using a custom environment. 

With Launcher, you selected one of your custom environment from the drop down menu, and then you could see what apps were installed for that environment.  If the Notebook wasn't installed you could install it for that environment, and then launch it.

With Navigator, the home screen shows apps installed, but doesn't indicate the environment, so I guess it's root environment.  And it doesn't seem possible to switch environments on this page, like you could with Launcher. 

So I tried going to the Environments tab, selecting my custom environment, and then going back to the Home tab and launching the Notebook, but that was just my root environment again.  

So then I went back to the Environments tab, and tried to use the "Open in Jupyter Notebook" from there, but that didn't seem to do anything, as reported here: https://github.com/ContinuumIO/anaconda-issues/issues/802#issuecomment-225157660
 
So the only way I was able to start a Notebook using my custom environment was to use the command line:
```
activate IOOS
jupyter notebook
```
This is very frustrating.

**Comment by goanpeca** [comment]
@rsignell-usgs thanks for the feedback, we are fixing this for an upcoming release.

**Comment by goanpeca** [comment]
Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
