### ISSUE TITLE
Import error numpy

### ISSUE THREAD

**Issue by naymikm** [ContinuumIO/anaconda-issues#824]
When I try to imort numpy I get this error:

> > > import numpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/mnaymik/.local/lib/python2.7/site-packages/numpy/**init**.py", line 180, in <module>
> > >     from . import add_newdocs
> > >   File "/home/mnaymik/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
> > >     from numpy.lib import add_newdoc
> > >   File "/home/mnaymik/.local/lib/python2.7/site-packages/numpy/lib/**init**.py", line 8, in <module>
> > >     from .type_check import *
> > >   File "/home/mnaymik/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
> > >     import numpy.core.numeric as _nx
> > >   File "/home/mnaymik/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
> > >     from . import multiarray
> > > ImportError: /home/mnaymik/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsUTF8String

**Comment by nehaljwani** [comment]
Based on the location of the site-packages (`/home/mnaymik/.local/lib/python2.7/site-packages/`), it seems as if `numpy` was installed using `pip` and the `--user` flag. This is not necessarily compatibly with conda. Please delete `~/.local` and install `numpy` package using `conda install numpy`
