### ISSUE TITLE
Qt4 svg support broken on Linux and OSX

### ISSUE THREAD

**Issue by goanpeca** [ContinuumIO/anaconda-issues#825]
On Linux and OSX qt version 4.8.6 displays svg icons when used with Qt Stylesheets (QSS). On the other hand the latest Qt4 version  (4.8.7) results in no svg icon being rendered at all in the application.

No trace or error is found in console, but the issue is there.

This is affecting Spyder and Navigator

**Comment by MulticastMatt** [comment]
This is a stop ship issue for Navigator that is trying to wrap up the release in the next few days.  If we can get some help on this one ASAP, that would be appreciated.  Thank you!

**Comment by MulticastMatt** [comment]
Corresponding Navigator issue https://github.com/ContinuumIO/navigator/issues/505

**Comment by mingwandroid** [comment]
I'm taking a look at OSX now.

**Comment by mingwandroid** [comment]
It's building, will let it run overnight and then update this thread. Tomorrow I will tackle Linux unless someone beats me to it.

**Comment by MulticastMatt** [comment]
Thanks so much Ray!

**Comment by ccordoba12** [comment]
I'm almost sure this is a `qt.conf` issue. I'm also looking at it :-)

**Comment by MulticastMatt** [comment]
Awesome, thanks to you too Carlos!

**Comment by ccordoba12** [comment]
I found and solved the issue. New packages will be available tomorrow morning.

Thanks for reporting and letting us know about it :-)

**Comment by mingwandroid** [comment]
Thanks a lot Carlos.

**Comment by ccordoba12** [comment]
Things gave more troubles than I expected, but new packages will be available for sure tomorrow morning ;-)

**Comment by MulticastMatt** [comment]
Thanks so much for the update Carlos. Any idea of a time this may be available?  Navigator release testing is completely blocked at this point (no pressure 😅)

Matt

**Comment by ccordoba12** [comment]
This should be fixed now. Please test the new Qt and PyQt packages uploaded to our official channels, and close if everything is working correctly.

**Comment by stephenakearns** [comment]
closing this as seems like it is resolved.
