### ISSUE TITLE
Can't run virtualenv anymore

### ISSUE THREAD

**Issue by Andreilys** [ContinuumIO/anaconda-issues#8269]
Hello, I made an environment with anaconda earlier but now I'm unable to activate my virtualenvironment.

When I try to do "source activate venv" I get an error saying it can't find the conda environment venv, what I actually want to do is just activate the virtualenvironment in the current directory

When I do activate venv I get an error saying "run source activate envname" however I get the issue listed above.

How do I get rid the mapping that "source activate venv" has to anaconda and instead have it mapped to my virtualenv so I can activate it?

**Comment by diegoquintanav** [comment]
This just happened to me after doing conda update anaconda. My local venvs are now broken.

My current version of anaconda is 
`anaconda Command line client (version 1.6.5)`
and `conda` version
`conda 4.4.8`

Normally I was able to work with both systems, but now it does not work.

1.  If I do `source activate venv` conda says that there is no env named `venv`, before updating this activated the local env in `/venv`.
2. If I do `source venv/bin/activate` then `base` env of anaconda is activated, which is not the desired result.

**Comment by kalefranz** [comment]
Use `source activate ./venv`.  See https://github.com/conda/conda/pull/6447 and associated issues for more details.

**Comment by diegoquintanav** [comment]
Yeah, that does not work either

In my case
```
diego@envy:~$ mkdir -p Documents/venv-test
diego@envy:~$ cd Documents/venv-test/
diego@envy:~/Documents/venv-test$ virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/diego/Documents/venv-test/venv/bin/python2
Also creating executable in /home/diego/Documents/venv-test/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
diego@envy:~/Documents/venv-test$ source activate venv
Could not find conda environment: venv
You can list all discoverable environments with `conda info --envs`.
```

Now if I try your solution

```
diego@envy:~/Documents/venv-test$ source activate .venv
Could not find conda environment: .venv
You can list all discoverable environments with `conda info --envs`.
diego@envy:~/Documents/venv-test$ source activate ./venv
Not a conda environment: /home/diego/Documents/venv-test/venv
```
This, however, does it
```
diego@envy:~/Documents/venv-test$ source venv/bin/activate
(venv) diego@envy:~/Documents/venv-test$ deactivate
diego@envy:~/Documents/venv-test$ source venv/bin/activate
```

But deactivating does not work as usual

```
diego@envy:~/Documents/venv-test$ source venv/bin/activate
(venv) diego@envy:~/Documents/venv-test$ source deactivate
(venv) diego@envy:~/Documents/venv-test$ 
```

Now It's been a while since the last time I updated anaconda. Is this the intended behaviour?

**Comment by kalefranz** [comment]
```
diego@envy:~/Documents/venv-test$ virtualenv venv
diego@envy:~/Documents/venv-test$ source activate venv
```

Conda environments != virtualenv.  You're using virtualenv wrong.  You need

    source ./venv/bin/activate

**Comment by diegoquintanav** [comment]
Yes. My issue is that before this update I could do both, *maybe* due to a local misconfiguration, or *maybe* because conda searched for a local (env) match before searching in the envs list by default (That is my question now), and the update *changes* that. 

Either way, it worked that way and now it does not, but the method you show works.

**Comment by kalefranz** [comment]
Right.  With conda 4.4 and later, activate will give you an error message if you try to activate a directory that's not actually a conda environment.  So yes that's a change.
