### ISSUE TITLE
Anaconda3 5.0.0 Installation fail

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#8276]
_From @KirkLab on October 6, 2017 19:32_

When trying to install Anaconda3 5.0.0, the files all download, but the installation fails. An error pops up at the very end saying “Failed to create menus: abort retry ignore”. clicking retry does nothing. Since there are no menus, python cannot be opened. Even trying to open python or spyder from CMD, it appears as though anaconda doesnt officially install; computer does not recognize it. 

_Copied from original issue: conda/conda#6093_

**Comment by kalefranz** [comment]
_From @KirkLab on October 9, 2017 11:58_

![capture](https://user-images.githubusercontent.com/20971364/31337038-8f323114-acc7-11e7-91bb-8021b485d552.PNG)

**Comment by kalefranz** [comment]
_From @stahlous on October 9, 2017 19:42_

I have the same issue. I ran the Anaconda uninstaller to remove the old version, restarted my computer, and attempted twice to install 5.0.0 with the same result as @KirkLab. This is a Windows 10 machine with the 64-bit version.

**Comment by colinleach** [comment]
Same issue for me (on Win10). I tried several times to install with Anaconda3-5.0.1-Windows-x86_64.exe but got the "Failed to create menus" error each time.  I'd removed all other versions of Python from the machine. On checking the "C:\Users\colin\Anaconda3" directory there was very little there, certainly no pythonw.exe that the installer was trying to run.

I got a bit further with an old Anaconda3-4.4.0-Windows-x86_64.exe installer I downloaded several months ago (and installed successfully at that time). I again got a "Failed to create menus" error but at least the Anaconda3 directory had pretty much the expected files in it. I copied the start menu entries from another machine and launched an Anaconda prompt, but "conda list" returned an empty list.

I'm out of ideas for what to try next.

**Comment by colinleach** [comment]
**Update:**
Out of curiosity, I tried to run "`conda install conda`" on my broken 4.4.0 installation and got the unexpected error: `CondaIOError: Missing write permissions in: C:\Users\colin\Anaconda3`
I can't explain that, as Windows reports that I'm the owner of that directory and have "Full control" access. I can certainly create, modify and delete files there manually. I'm the administrator, owner and sole user of this PC.

It gave me the idea to try installing to a different location, and I'm happy to find that 5.0.1 installed without problems to d:\Anaconda3 after repeatedly failing with the $HOMEPATH$ default .  Weird...

**Comment by kalefranz** [comment]
What does windows report for permissions on the file `C:\Users\colin\Anaconda3\conda-meta\history`?

**Comment by colinleach** [comment]
Sorry, I can't answer this now. I deleted `C:\Users\colin\Anaconda3\` and all its contents after successfully installing to `D:\Anaconda3\`.

**Comment by ThirstyGeo** [comment]
Same behaviour for 5.1.0 on Windows 10

I have tried many solutions peppered around the web, including:

- removing all instances of previously installed conda and Anaconda (Windows remove programs, plus manual search of computer for hidden directories)
- cleaning PATH variable
- Installing With and Without admin privileges
- Installing to user directory, andinstalling to 'C:\Anaconda3'
- Installing for all, installing for individual
- Creating an entry in PATH, or not

**Comment by ThirstyGeo** [comment]
The solution in my case was:
1. open command window
2. set path=
3. Run install

So it appears that something in my PATH has been conflicting with the Anaconda3 install

**Comment by msarahan** [comment]
please see #3488 for more discussion and some workarounds that other users have found.  The PATH definitely seems to be the culprit, and we're working on addressing that for the next release.

Closing as duplicate.
