### ISSUE TITLE
Activation.bat failed for PATH containing double quote

### ISSUE THREAD

**Issue by adrianshum** [ContinuumIO/anaconda-issues#8297]
I have just installed Anaconda, but Anaconda Prompt does not have env setup properly.

Turned out it was caused by my exiting Path: I have double quote surrounding one of the entry (the last one, dunno if it makes a difference).

i.e. path looks like this: PATH=C:\Foo\Bar;"C:\Program Files\Apache Maven 3.1.0\bin"

This is a valid path for Windows, but when Anancoda activate.bat execute, it complains as it is trying to do

`@set "PATH=C:\Foo\Bar;"C:\Program Files\Apache Maven 3.1.0\bin""`

and compalins with message like 

`\Apache was unexpected at this time`

**Comment by mingwandroid** [comment]
This is a known issue but there is an easy workaround: ensure your PATH doesn't contain any double quotes (they are invalid actually).

This should work fine:

```
set "PATH=C:\Foo\Bar;C:\Program Files\Apache Maven 3.1.0\bin"
```

.. and in fact so does this:

```
set PATH=C:\Foo\Bar;C:\Program Files\Apache Maven 3.1.0\bin
```

People think they need quotes around spaces when using set or in the Windows registry when they do not and worse, they can actually cause harm.

**Comment by adrianshum** [comment]
Yes I am aware of the double quote is unnecessary.  However it does bring quite some confusion when it happens.  I will suggest adding a proper error message when activation.bat encounters double quote in path, or simply remove all double quotes in path.

What do you think?  I am pleased to submit a pull request on this minor fix :) but just want to know what's the preferred way of fixing it.

**Comment by mingwandroid** [comment]
A PR would be welcome yes!

**Comment by msarahan** [comment]
Thanks @adrianshum for offering to help us on this.  I think the right place to fix it is in conda: https://github.com/conda/conda/blob/master/conda/shell/Library/bin/conda.bat

If you have questions on how that works, please ping @kalefranz

**Comment by adrianshum** [comment]
@msarahan  I have just gone to have a look in the path you provided, it seems totally different from the activate.bat used by Anconda Prompt.  Was it revamped or it is actually something different?

**Comment by msarahan** [comment]
It was totally revamped in conda 4.4.  We consider the 4.3 series "LTS" right now - I'm sure a PR to the 4.3.x branch would also be welcome, and @kalefranz could apply it to his newer work from there.

**Comment by kalefranz** [comment]
While 4.3 is LTS, this seems like a pretty obscure issue where a patch could risk destabilizing 4.3. Any PR to 4.3 to fix this would require the addition of rigorous tests.

**Comment by adrianshum** [comment]
Have just updated conda.  Have had a quick test and seems the refactored logic no longer failed on path with double quote.  I guess I could simply close this issue.
