### ISSUE TITLE
Anaconda breaks Emacs build on Debian

### ISSUE THREAD

**Issue by andreas-roehler** [ContinuumIO/anaconda-issues#8322]
Couldn't build Emacs from source any more until Anaconda was removed from path. 

Further info from Emacs bug-report,
http://lists.gnu.org/archive/html/bug-gnu-emacs/2018-01/msg00828.html,
below.

Best,
Andreas Röhler

#####

Andreas Röhler <andreas.roehler@online.de> writes:

> /usr/lib/gcc/i586-linux-gnu/4.9/../../../i386-linux-gnu/libgdk-3.so:
> undefined reference to `cairo_surface_set_device_scale'
> /usr/lib/gcc/i586-linux-gnu/4.9/../../../i386-linux-gnu/libgtk-3.so:
> undefined reference to `cairo_surface_get_device_scale'

Some suggestions in [1] that having .../anaconda/lib in LIBRARY_PATH
might cause this.  [2] is inconclusive, but also mentions anaconda.  So
does [3].

[1]: https://askubuntu.com/questions/796662/gedit-error-for-non-sudo-undefined-symbol-cairo-surface-set-device-scale-und
[2]: https://github.com/Wilfred/remacs/issues/118
[3]: http://lists.gnu.org/archive/html/emacs-devel/2017-03/msg00543.html

**Comment by mingwandroid** [comment]
> Some suggestions in 1 that having .../anaconda/lib in LIBRARY_PATH

You mean `LD_LIBRARY_PATH`? We do not set that and you shouldn't either.

If you have `The Anaconda Distribution` in your `PATH` then various `config` programs from it can be found by `configure` and those `config` programs will return values only relevant to building and using software for the `Anaconda Distribution`.

The only solution when attempting to build software that doesn't use software from `The Anaconda Distribution` is to deactivate your `conda` environment.

This is not a bug.

**Comment by mingwandroid** [comment]
.. if you want to build an `emacs` that takes advantage of our software then you should use https://github.com/conda-forge/emacs-feedstock
