### ISSUE TITLE
gcc has unpinned isl

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#833]
It seems that the `gcc` package provides no version constraints for `isl`. Not having this constraint is causing us some problems as we have a newer version of `isl`.

@frol, provided a PR ( https://github.com/conda/conda-recipes/pull/501 ) that placed some constraints on `isl`. That seems reasonable from the build standpoint. However, it looks like many minor versions (particularly in that range) may need tighter run-time pinning based on what they are built with. This is evidenced by this ABI [report]( http://abi-laboratory.pro/tracker/timeline/isl/ ). I believe `0.12.*` should be sufficient as 0.12.1 or 0.12.2 should be fine with the current `gcc`. We had been using 0.12.2.

Instead of trying to rebuild `gcc` right now, I think we can probably get away with a hot-fix. So, some sort of hot-fix that allows 0.12.1 or 0.12.2 to be installed should work fine.

xref: https://github.com/conda-forge/isl-feedstock/issues/3

cc @mcg1969 @ocefpaf @jakevdp

**Comment by jakirkham** [comment]
Sorry to bring this up again. Any news on this? The problem here is causing us a fair bit of grief.

**Comment by mcg1969** [comment]
@ilanschnell @msarahan

**Comment by mcg1969** [comment]
I've pinged Ilan again, but we were pretty swamped this week.

**Comment by ilanschnell** [comment]
I just added the `isl` version dependency.  That is, `gcc` now depends on `isl 0.12.*`.

**Comment by jakirkham** [comment]
Thanks @ilanschnell. Just tried it out and it works great.

**Comment by ilanschnell** [comment]
Cool!

**Comment by jakirkham** [comment]
This issue appears to have resurfaced. Please see this [build]( https://travis-ci.org/conda-forge/pyagrum-feedstock/jobs/167379108#L323 ) as an example.

xref: https://github.com/conda-forge/pyagrum-feedstock/pull/2

cc @jschueller

**Comment by mcg1969** [comment]
@jakirkham are you sure? it looks like the referenced feedstock is having a problem on Mac, but the Mac does indeed have `isl 0.12.*` for both gcc packages.

**Comment by mcg1969** [comment]
Hmm, it does seem like something is amiss

**Comment by mcg1969** [comment]
I can't reproduce it locally, actually. @jakirkham can you by any chance come up with a bare `conda create -n` command that tries to install `gcc` and `isl 0.17.1`? I'm unable to.

**Comment by mingwandroid** [comment]
Recently, some packages were added to repo.continuum.io, and in that process, an old version of anaconda was used. This meant that the metadata hotfixes were not the latest ones.

I pushed 4 new packages now and at the same time, fixed the metadata.

I hope this explains everything!

**Comment by mcg1969** [comment]
That would explain why I can't reproduce it :-) Thanks @mingwandroid

**Comment by jakirkham** [comment]
Indeed. That does seem to have fixed it. Thanks @mingwandroid .

**Comment by mingwandroid** [comment]
I actually spent quite a lot of time (too much) thinking my repodata.json diffs were a problem rather than a fix, so the confirmation is appreciated :-)

**Comment by mcg1969** [comment]
We really do need to find a way to properly manage metadata hotfixes. I do like the idea of rebuilding the package with the new metadata, but the problem is we break MD5 when we do that, making it harder for people who want signature-verified environments.

**Comment by mingwandroid** [comment]
Yup. No argument from me. Content addressable seems to be a good way to handle this sort of thing, basically modelled on how git works.
