### ISSUE TITLE
import numpy failed with Anaconda 4.0.0 in Windows 7 (maybe related to multiarray)

### ISSUE THREAD

**Issue by alessandro-gentilini** [ContinuumIO/anaconda-issues#835]
I installed Anaconda on Windows using https://repo.continuum.io/archive/.winzip/Anaconda2-4.0.0-Windows-x86_64.zip

I get an error with the simple `import numpy`.

I get the following error using the standard command prompt of Windows and **I get the error also with "Anaconda Prompt"**.

```
C:\Users\ag>python
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ag\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Users\ag\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\ag\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\ag\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\ag\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\__init__.py", line 14, in <module>
    from . import multiarray
ImportError: DLL load failed: The operating system cannot run %1.
>>>
```

Maybe my issue is related to this one: 
https://github.com/ContinuumIO/anaconda-issues/issues/824

**Comment by alessandro-gentilini** [comment]
OK, maybe it is an issue related to my environment.

I had a look at https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/28hO1sXQtX8/pTV2Jhb9EgAJ and I tested `C:\Users\ag\AppData\Local\Continuum\Anaconda2\Lib\site-packages\numpy\core\multiarray.pyd` with "Dependency Walker" and I found that `libiomp5md.dll` was not found.

So I copied `C:\Users\ag\AppData\Local\Continuum\Anaconda2\Library\bin\libiomp5md.dll` to `C:\Users\gentiale\AppData\Local\Continuum\Anaconda2\Lib\site-packages\numpy\core` and now `import numpy` succeeded.

**Comment by mingwandroid** [comment]
HI sorry about the delay getting a reply. You should *not* have `libiomp5md.dll` in `C:\Windows\system32`. Whatever program decided to install a non-system DLL in your system DLL folder needs to be fixed.

**Comment by alessandro-gentilini** [comment]
@mingwandroid I agree!

**Comment by mingwandroid** [comment]
OK, in this instance, that is the cause of this issue and there is nothing for us to fix here. Moving DLLs so they are beside each other is not something that we can do for redistribution and packaging reasons.

**Comment by alexsavio** [comment]
I've found the same issue for Anaconda 4.3.1 and Python 3.6 in Windows 10. I had a **libiomp5md.dll** in C:\Windows\System32. Solved by renaming the dll file in the System32 folder, perfect to check what is the software that will fail next.

**Comment by mingwandroid** [comment]
@alexsavio, if you have installed badly behaved software which puts non-system DLLs into the System32 folder there isn't much we can do about that.

**Comment by alexsavio** [comment]
I am aware of that @mingwandroid, thanks. I just wanted to put this here, since it took me half a day to find this solution. I have been looking for the culprit but I can't find it, looks like MS Visual Studio, 3D Unity, or some Hololens related stuff. I actually don't care if they stopped working for now.

**Comment by ViktorM** [comment]
I met the same error with Python 3.6.0 Anaconda 4.3.1 (64-bit) and I don't have libiomp5md.dll in my System32

**Comment by marfeljoergsen** [comment]
ViktorM: I also have this problem - Python 3.6.3 :: Anaconda, Inc. And like you I don't have libiomp5md.dll in my System32... Yet I also get "ImportError: DLL load failed: The specified module could not be found.".... - Very strange - something is fishy...

**Comment by tomasvanoyen** [comment]
Any solution yet? 
I am having the same error message. python 3.6.2, numpy 1.13.1

**Comment by LewisPGEvans** [comment]
Any solution yet?
I also cannot import numpy, anaconda 5.0.0, python 3.6.2, numpy 1.13.1
had same problem with anaconda 5.0.1

**Comment by mingwandroid** [comment]
@LewisPGEvans, @tomasvanoyen, @ViktorM, please open a normal (i.e. non Anaconda) cmd.exe prompt and enter:

`where libiomp5md.dll`

**Comment by LewisPGEvans** [comment]
not found, in my case:

C:\Users\Lewis Evans>where libiomp5md.dll
INFO: Could not find files for the given pattern(s).

**Comment by LewisPGEvans** [comment]
I resolved my import-numpy problem by
pip uninstall numpy
pip install numpy=1.14.0

also had to fix html5lib (needed by pip), which couldnt import inputstream; resolved that by
conda update html5lib
