### ISSUE TITLE
Fastparquet broken in defaults

### ISSUE THREAD

**Issue by shughes-uk** [ContinuumIO/anaconda-issues#8368]
Fastparquet 0.1.3 right now is incompatible with Thrift 11.0 and this is what gets install when you conda install fastparquet right now.

Fastparquet 0.1.4 is available on conda-forge and fixes the issues and should probably be ported over immediately.

Cheers!

**Comment by msarahan** [comment]
0.1.4 is being uploaded to defaults now, and will be available in a few minutes.
