### ISSUE TITLE
pyproj cannot be installed anymore

### ISSUE THREAD

**Issue by krischer** [ContinuumIO/anaconda-issues#838]
`pyproj` cannot be installed anymore as `proj.4` has somehow been removed from the default conda channel. I'm not sure why and if this was a conscious choice but it does break installation of some packages that rely on `pyproj`.

At least I think that is the issue - all I know for sure is that `pyproj` could still be installed two days ago.

I tried on OSX-64 as well as linux-64, both with the latest Python 3.5.

```bash
$ conda install pyproj
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
Error: Dependency missing in current linux-64 channels:
  - pyproj -> proj.4 4.9.1

Close matches found; did you mean one of these?

    proj.4: proj4
```

I realize this can be alleviated by just adding for example the `conda-forge` channel but please fix this as it does break the default installation process for quite some packages.

**Comment by ilanschnell** [comment]
We just updated pyproj to 1.9.5.1, you should be able to install this package without problems.

**Comment by krischer** [comment]
Thanks for the fast response! Works like a charm.
