### ISSUE TITLE
The Python 3.5 win64 pyreadline conda package contains sphinx

### ISSUE THREAD

**Issue by aburgm** [ContinuumIO/anaconda-issues#841]
The package should only contain pyreadline, but it also contains a version of sphinx 1.3.1.

**Comment by aburgm** [comment]
See the contents of the tarball: https://anaconda.org/anaconda/pyreadline/2.1/download/win-64/pyreadline-2.1-py35_0.tar.bz2

**Comment by nehaljwani** [comment]
A new build of the pyreadline package is out, which doesn't have this problem.

https://repo.continuum.io/pkgs/main/win-64/pyreadline-2.1-py35h9d47d9c_1.tar.bz2

You'll require `conda >=4.3.27` to get access to the main channel.

**Comment by nehaljwani** [comment]
Related to https://github.com/conda/conda/issues/6216
