### ISSUE TITLE
Error while updating anaconda

### ISSUE THREAD

**Issue by aritro01** [ContinuumIO/anaconda-issues#8428]
So I've been trying to update anaconda but the dependency issue is persistent.
![screenshot from 2018-02-04 14-48-15](https://user-images.githubusercontent.com/8187667/35776059-4cd1c9fa-09bb-11e8-9880-0713ec3aa80f.png)

**Comment by goanpeca** [comment]
@aritro01 please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
