### ISSUE TITLE
GDAL: missing krb5 dependancy

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#845]
_From @brendancol on June 23, 2016 20:57_

_Copied from original issue: conda/conda#2843_

**Comment by jbednar** [comment]
The symptom is that if krb5 is not installed, GDAL complains about a missing libgssapi (e.g. when doing `import rasterio`, which requires GDAL). `conda install krb5` fixes it.

**Comment by nehaljwani** [comment]
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/976
