### ISSUE TITLE
Windows: Anaconda Navigator hangs at launch while "Loading repodata..."

### ISSUE THREAD

**Issue by dje7** [ContinuumIO/anaconda-issues#847]
Navigator hangs at launch while "Loading repodata..."

(C:\Users\Daniel\Anaconda3) C:\Users\Daniel>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\conda_manager\api\download_api.py", line 174, in _request_finished
    self._save(url, path, data)
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\conda_manager\api\download_api.py", line 190, in _save
    self._get_requests.pop(url)
KeyError: 'https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2'
Traceback (most recent call last):
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 268, in create_application_projects
    packages, apps = output
TypeError: 'NoneType' object is not iterable

Windows 10 machine
$conda -V shows  conda 4.1.3
$anaconda _V shows anaconda-scripts.py Command line client  (version 1.4.0)

If I do $conda update conda I get "all requested packages installed"
conda    4.1.3    py35_0
If I do $conda update anaconda I get "all requested packages installed"
anaconda    4.0.0     np110py35_0    

I installed it as a user only install and only chose the default settings.
Thanks in advance

**Comment by goanpeca** [comment]
Hi @dje7, thanks for reporting:
- Is this the first time you use Navigator?
- Do you have the latest version (1.1.1)?
- Are you behind a proxy?

A new version of Navigator is coming next week, and this problem has been (most likely) solved in the new version :-)

**Comment by dje7** [comment]
Yes. This is the first time I've used navigator. I have version 1.1.1 and am not behind a proxy.
Thanks.

**Comment by stephenakearns** [comment]
@goanpeca - any chance that conda 4.1.3 is causing issues?

**Comment by goanpeca** [comment]
I think we need to check with the new version coming out tomorrow?

**Comment by dje7** [comment]
I updated with conda 4.1.5 and anaconda navigator 1.2.1 and it works. Thanks. :)

**Comment by goanpeca** [comment]
:+1:
