### ISSUE TITLE
Troubles with installing R packages

### ISSUE THREAD

**Issue by psinger** [ContinuumIO/anaconda-issues#848]
I am currently trying to install the following R package:
https://github.com/glmmTMB/glmmTMB

However, regardless of which method I use, I end up with an error. After a lot of troubles, I managed to install the main dependency TMB though.

First try:
devtools::install_github("glmmTMB/glmmTMB",subdir="glmmTMB")

Here, I receive the error: 
Warning in file(con, "r") :
  cannot open file '/home/user/anaconda2/lib64/R/etc/r-devtools/Makeconf': No such file or directory
Error in file(con, "r") : cannot open the connection

Second try:
Make from git source

After manually installing all dependencies, it also fails for the same reason at devtools.

The package is not in cran, so cannot install it from there.

Anyone got an idea?

edit: I fixed the above error by make symlinks from r-devtools to the /etc folder that contains e.g. Makeconf. Now I receive the following error:

ERROR: sub-architecture 'R' is not installed
**\* arch - r-devtools
Error in system2(file.path(R.home("bin"), "R"), c(if (nzchar(arch)) paste0("--arch=",  :

**Comment by mingwandroid** [comment]
R 3.3.1 will be release soon, I'll ping you when it's ready and I'll also look into this at that point.

**Comment by mingwandroid** [comment]
We have our own `r-devtools` package now, can you try again with R 3.3.2?

**Comment by csoja** [comment]
Closing do to inactivity
