### ISSUE TITLE
how to get around my company's fire wall - tried to update conda but failed

### ISSUE THREAD

**Issue by seanliu333** [ContinuumIO/anaconda-issues#8494]
(C:\Users\liuxia\AppData\Local\Continuum\Anaconda3) C:\Users\liuxia>conda update
 conda
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusi
on/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=44
3): Max retries exceeded with url: /anaconda-fusion/win-64/repodata.json (Caused
 by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 40
7 Proxy Authentication Required',)))",),)

**Comment by Garyck91** [comment]
Which bash are you using to update?
Which system are you running?
