### ISSUE TITLE
QT compatibility issue for ipython

### ISSUE THREAD

**Issue by mikhailo** [ContinuumIO/anaconda-issues#85]
ipython work fine in general. However, then I try to use graphics it crashed giving me this

>>>Cannot mix incompatible Qt library (version 0x40801) with this library (version 0x40805)
Aborted

I tried to google the solution, for example here:
http://stackoverflow.com/questions/21212851/anaconda-spyder-qt-library-error-on-launch

but did not get any conclusive result.

It seems that it is a problem to qt version I installed. I also get the same error, while trying to launch qtconfig. For qtconfig it can be solved by removing anaconda path from $PATH variable

My native qt version is: 4.8.1 
OS: Linux Mint 13 Maya

Are there any reasonable ways to solve the problem apart from downloading, compiling and installing qt 4.8.5 on the system?

**Comment by ccordoba12** [comment]
This was fixed yesterday with the new Qt and PyQt packages.
