### ISSUE TITLE
Anaconda issues with IHaskell and OpenAI's gym

### ISSUE THREAD

**Issue by act65** [ContinuumIO/anaconda-issues#852]
Hey,

I have been having a little trouble getting anaconda to work with a couple of things, just though I would let you guys know.

* This [issue](https://github.com/openai/gym/issues/164) on pip installing gym was resolved by just removing anaconda. 
* and the IHaskell [docs](https://github.com/gibiansky/IHaskell) explicitly tells you to avoid anaconda.

**Comment by act65** [comment]
oh... i got ihaskell working.
and on second thoughts it probably isnt even your guys fault...

**Comment by emeinhardt** [comment]
Did you get IHaskell working *with* anaconda? If so, would you mind explaining how?
