### ISSUE TITLE
regression in activate script

### ISSUE THREAD

**Issue by neok-m4700** [ContinuumIO/anaconda-issues#853]
In the new version of the activate script (Last date of change: 2016-06-21, as in the script comments), on linux x86_64, sourcing the env scripts in `$PREFIX/etc/conda/activate.d` fails.

In `$PREFIX/bin/activate` I believe this line:
`_CONDA_D="${CONDA_DEFAULT_ENV}/etc/conda/activate.d"`

should be replaced with: 
`_CONDA_D="${CONDA_ENV_PATH}/etc/conda/activate.d"`

**Comment by msarahan** [comment]
Fixed in https://github.com/conda/conda/pull/2856 - closing.
