### ISSUE TITLE
Installing ANACONDA using SCCM

### ISSUE THREAD

**Issue by jeanabacaxi** [ContinuumIO/anaconda-issues#854]
Hello

Please, can you tell me if the new release is still planned for the end of june?

I got the issue #816 (SCCM using System account to install), and i wonder if i continue to search a solution or to wait for the new release  

Thanks a lot for the great work

**Comment by csoja** [comment]
Yes - v4.1 will definitely be available before the end of June.  We are targeting June 28th.
