### ISSUE TITLE
Freshly installed anaconda3 python crashes on use of MKL due to python fetching wrong dll's on import

### ISSUE THREAD

**Issue by sigurof** [ContinuumIO/anaconda-issues#8561]
### Actual Behavior
Anaconda3's installation of Python with MKL on Windows crashes bad and outputs the following error message:

> mkl_aa_fw_init_workdivision the procedure entry point could not be located in the dynamic link library C:\Users\[my name]\Anaconda3\Library\bin\mkl_intel_thread.dll

### Expected Behavior
I would normally expect python not to crash bad and output such an error message.

### Steps to Reproduce
- Open Anaconda Prompt
- Type "python --version" to verify this is indeed Python 3.6.3 :: Anaconda custom (64-bit)
- Type python to start python:
- Type in the following: 
```
import numpy as np
A = np.arange(2*3).reshape(2,3).astype(np.float32)
B = np.arange(2*3*2731).reshape(2,3,2731).astype(np.int16)
np.dot(A, B)
```
- If like mine, your python isn't loading dll's correctly, behold the beautiful crash that ensues.

### What is causing the error
dll hell. Some previous application on my computer has installed several mkl files (dll's) in C:\Windows\System32, which for some reason causes python to load those instead of the proper ones.
This issue is very similar to https://github.com/numpy/numpy/issues/6923, which seems to be caused by the same set of files. The folks over there traced the dll's back to Amplitube, which is certainly installed on my computer (not anymore it ain't).
I have confirmed that "disabling" the files
C:\Windows\System32\mkl_intel_thread.dll
C:\Windows\System32\mkl_def.dll
C:\Windows\System32\mkl_core.dll
by renaming them to disabled_mkl_blablabla, fixes the issue. It then seems like python discovers the correct dll files in Anaconda3. I am going to see if uninstalling Amplitube fixes the issue.
Even though the issue is similar to the one linked above, I think it deserves a new post, since it literally took me days to figure this problem out.
Hope this post helps someone out there!

##### Anaconda or Miniconda version:
Anaconda version 1.6.5
##### Operating System:
Windows 10 
##### `conda info`

```
     active environment : base
    active env location : C:\Users\[my name]\Anaconda3
            shell level : 1
       user config file : C:\SPB_Data\.condarc
 populated config files : C:\SPB_Data\.condarc
          conda version : 4.4.10
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : C:\Users\[my name]\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\[my name]\Anaconda3\pkgs
                          C:\Users\[my name]\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\[my name]\Anaconda3\envs
                          C:\Users\[my name]\AppData\Local\conda\conda\envs
                          C:\SPB_Data\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
As I am in the base env, this list is very long. Also, probably not very relevant.
```

EDIT: 23-Feb 2019: Uninstalling Amplitube did resolve the problem.

**Comment by chenchen2015** [comment]
It appears that software like Amplitube will install another copy of MKL library DLLs to the `system32` folder and therefore picked up by `numpy` and other libraries, in my case `matplotlib`, due to higher priority.

A simple solution for me now is to temporarily remove (or simply rename) the MKL dlls under `system32` folder. *I found that this way Amplitube can co-exist with Anaconda (or other Python environments that includes MKL) as I still want to use Amplitube.*

**Comment by mingwandroid** [comment]
Then you need to ask Amplitube people to stop installing non-system DLLs into the `System32` folder.

This is the most horribly, most selfish thing a software developer can do with regards to DLL-hell. It is basically saying "we don't care about any other software on your computer so long as our software works OK"

**Comment by utkuaslan85** [comment]
I was also facing MKL error when running `LogisticRegression ` from `sklearn.linear_model` in Spyder (Anaconda 3.6). And also I have Amplitube4 installed. I renamed file name of MKL library DLLs under `system32 `folder. Problem solved. Additionally Amplitube4 is working fine.

**Comment by NavinSinghsays** [comment]
I don't have amplitube installed still I am facing the similar issue
`import numpy as np
A = np.arange(2*3).reshape(2,3).astype(np.float32)
B = np.arange(2*3*2731).reshape(2,3,2731).astype(np.int16)
np.dot(A, B)`
when i run the above code i do get output though.
following are conda specs
`
(base) C:\Users\Navin>conda info

     active environment : base
    active env location : C:\Users\Navin\Anaconda3
            shell level : 1
       user config file : C:\Users\Navin\.condarc
 populated config files : C:\Users\Navin\.condarc
          conda version : 4.5.8
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\Navin\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Navin\Anaconda3\pkgs
                          C:\Users\Navin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Navin\Anaconda3\envs
                          C:\Users\Navin\AppData\Local\conda\conda\envs
                          C:\Users\Navin\.conda\envs
               platform : win-64
             user-agent : conda/4.5.8 requests/2.18.4 CPython/3.6.5 Windows/7 Wi
ndows/6.1.7600
          administrator : False
             netrc file : None
           offline mode : False`
after running conda list --show-channel-urls

`
(base) C:\Users\Navin>conda info

     active environment : base
    active env location : C:\Users\Navin\Anaconda3
            shell level : 1
       user config file : C:\Users\Navin\.condarc
 populated config files : C:\Users\Navin\.condarc
          conda version : 4.5.8
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\Navin\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Navin\Anaconda3\pkgs
                          C:\Users\Navin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Navin\Anaconda3\envs
                          C:\Users\Navin\AppData\Local\conda\conda\envs
                          C:\Users\Navin\.conda\envs
               platform : win-64
             user-agent : conda/4.5.8 requests/2.18.4 CPython/3.6.5 Windows/7 Wi
ndows/6.1.7600
          administrator : False
             netrc file : None
           offline mode : False`
![error](https://user-images.githubusercontent.com/40607848/43322783-518c83fa-91cd-11e8-9513-40ab73fa32a6.jpg)

**Comment by mingwandroid** [comment]
@NavinSinghsays, please type `where mkl_core.dll` from `cmd.exe`. While you may not have amplitube installed, something else may have put these DLLs somewhere they shouldn't be.

**Comment by NavinSinghsays** [comment]
when I executed the `where mkl_core.dll` on cmd.exe following is the o/p
`C:\Users\Navin>where mkl_core.dll
INFO: Could not find files for the given pattern(s).`

when same code was executed on Anaconda prompt following is the o/p
`(base) C:\Users\Navin>where mkl_core.dll
C:\Users\Navin\Anaconda3\Library\bin\mkl_core.dll`

**Comment by mingwandroid** [comment]
Can you try it in the Python interpreter please?

**Comment by NavinSinghsays** [comment]
@mingwandroid Hey, I updated my OS and issue is resolved. Thank you for the help.

**Comment by mfisher-idmod** [comment]
I found uninstalling and reinstalling numpy for Anaconda3 worked for me. I didn't have the dlls also in C:\Windows\System32\ in my case.

**Comment by heihaa** [comment]
Thank you for this thread!! It saved me! I uninstalled Amplitube and everything worked fine. I am relifed! No never more amplitube for me

**Comment by HasArslan** [comment]
> ### Actual Behavior
> Anaconda3's installation of Python with MKL on Windows crashes bad and outputs the following error message:
> 
> > mkl_aa_fw_init_workdivision the procedure entry point could not be located in the dynamic link library C:\Users[my name]\Anaconda3\Library\bin\mkl_intel_thread.dll

i have the same problem. did you find a solution?

**Comment by sigurof** [comment]
@HasArslan 

Because pure python is extremely slow, numpy uses certain files with pre-compiled code (written in a faster language, like c++ or c), which it calls upon when you do heavy numerical operations. When you run a python script, it needs to search for these files in folders on your computer. Python has a list of places it will search (pythonpath, search it up), and when it finds the file it's looking for, it will use that. 

The error message I posted, says that python couldn't find a certain function in the MKL library. This was due to python finding an older version of the mkl-files it was looking for, where this function didn't exist,  in a folder with a higher search priority than the folder where numpy actually had put these files. The files python found, belonged to another application (Amplitube), which had sloppily put its dependencies (the files) in the System32 folder. 

The solution for me was simply renaming the files that Amplitube uses (this could break amplitube though). Do NOT delete them, though, unless you are certain.

If you have the same problem as me, you should check if a file with the same name as that which the error is referring to by chance is located in your System32 folder or any other folder in the pythonpath. 
(The python path is basically a python variable with a list of paths).

**Comment by HasArslan** [comment]
Thank you for your kind reply. After reading your reply I have uninstalled the video editing programs and i do not experience the error anymore.

**Comment by tirthshah147** [comment]
['System32\libiomp5md.dll', 'System32\mkl_core.dll', 'System32\mkl_def.dll','System32\mkl_intel_thread.dll', 'SysWOW64\libiomp5md.dll','SysWOW64\mkl_core.dll','SysWOW64\mkl_intel_thread.dll', 'SysWOW64\mkl_p4.dll', 'SysWOW64\mkl_p4m.dll','SysWOW64\mkl_p4m3.dll', 'SysWOW64\mkl_p4p.dll']

Remove all these ddl files from C:\Windows\SysWOW64 and C:\Windows\System32

Just do this and restart the application once again and hurrrahhhh!!! ur problem will be solved and it will open without showing any ordinal 242 error............just do it it is the only solution..

**Comment by mingwandroid** [comment]
We have another solution we're evaluating. If anyone can help we'd be grateful:

`conda update -c rdonnelly python`

**Comment by githubtd01** [comment]
After running conda udate --all I get the ordinal 242 error message too. It happens when I try to open Spyder as well as when I try to run code. I tryed to reinstall without success. Amplitude was never installed on my system. I also get the error "chcp" could not be found in Anaconda promt.

Running  `conda update -c rdonnelly python` did solve the problem, but now Avast Antivirus thinks that pythonw is a  virus (Avast sucks).

After the change, I get this problem: https://github.com/pyinstaller/pyinstaller/issues/3740.

**Comment by lwbaqueros** [comment]
Another way which Works for me (I deleted all DLL files but the problem continued)  was to downgrade ANACONDA to Anaconda3-5.2.0-Windows-x86_64.
I got the installer in this [link][1] 


  [1]: https://repo.continuum.io/archive/.winzip/

**Comment by msarahan** [comment]
5.2.0 works because it's using an older MKL that's compatible with whatever else is on your system that's interfering.

The new python builds that Ray mentions are now on defaults.  Before trying any other workarounds, please update python and try again.

**Comment by jazken** [comment]
> We have another solution we're evaluating. If anyone can help we'd be grateful:
> 
> `conda update -c rdonnelly python`

I just updated this, seems to work. What changed?

**Comment by msarahan** [comment]
https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

implemented at https://github.com/AnacondaRecipes/python-feedstock/blob/master/recipe/0020-Add-CondaEcosystemModifyDllSearchPath.patch

**Comment by mingwandroid** [comment]
We implemented a fix for dll hell but decided against enabling it by default as it's somewhat controversial.

Still dll hell is a fact on the ground and recommending people uninstall software isn't good enough. Please set the env var CONDA_DLL_SEARCH_MODIFICATION_ENABLE and be happy. 

The python on my channel has this flag enabled by default. You are best off testify the defaults channels packages though.
