### ISSUE TITLE
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'

### ISSUE THREAD

**Issue by hakeemrehman** [ContinuumIO/anaconda-issues#8568]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by hakeemrehman** [comment]
Help me

**Comment by slothkins** [comment]
Me too!!!

**Comment by goanpeca** [comment]
@hakeemrehman @slothkins need som emore context but it seems you need to remove a corrupt configuration file.

`binstar/config.yaml`

**Comment by saylidighde** [comment]
Same issue!

**Comment by slothkins** [comment]
deleting works...thank you!!!

**Comment by saylidighde** [comment]
Deleting didn't work for me

**Comment by nkaid2011** [comment]
It works for me

**Comment by snare2015** [comment]
same issue with Anaconda5.1 for windows. deleting works.

**Comment by vertangelx** [comment]
Just installed Anaconda3 on Windows 10, encountered this error.

What is this `binstar/config.yaml` file?

**Comment by goanpeca** [comment]
Please update to the latest verions of anaconda-client to fix the issue

```
conda install anaconda-client=1.6.11
```

---

@vertangelx 
>What is this binstar/config.yaml file?

anaconda-client is the CLI tool to communicate with anaconda.org (the repository of conda packages). Navigator depends on conda and anaconda client, and similar to how the configuration of conda is stored in `condarc` files, the configuration of anaconda-client is stored on `binstar/config.yaml`

The name Binstar comes from how the service used to had a different name before the switch to anaconda.

**Comment by Aarth78** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Parth Ajmera\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

**Comment by goanpeca** [comment]
```
conda install anaconda-client=1.6.11
```

**Comment by Aarth78** [comment]
It worked!

**Comment by Patisu01** [comment]
Thanks a lot for the solution !!

**Comment by sandaluz** [comment]
Deleting the binstar/config.yaml worked. Thanks!!!!!

**Comment by Rhubarbdevil** [comment]
I tried: 
conda install anaconda-client=1.6.11
And it updated several files, but I still can't get the Anaconda Navigator to start. It gives me the same error. I have searched for binstar/config.yaml and it doesn't exist. Any help? I am on a Mac, not Windows. And I used Anaconda for a couple of months about a year ago, and now it won't start, with the error listed above. Thanks!

**Comment by HL--K** [comment]
I deleted the binstar/config.yaml file and it worked.  I had to search for it (using a program called 'Everything').  It was added to a completely separate directory by a previous install of Anaconda, and the previous uninstall did not delete it.

**Comment by Danifan1217** [comment]
Gracias, pude solucionar mi problema. ¡Los amo!

**Comment by borcabar** [comment]
After trying other options, the one that works for me was to delete that "binstar/config.yaml", here is the full path:

/Users/(your account name)/Library/Application Support/binstar/config.yaml

**Comment by gleckler1** [comment]
That did it... thanks!

**Comment by bhan88** [comment]
Deleteting config.yaml works !

/Users/your_user_name/Library/Application Support/binstar/config.yaml

**Comment by zhaadayx** [comment]
Yes deleting it worked! THANKS

**Comment by kajodowe** [comment]
It worked for me also. Thanks very much. I, like another user above, used the Freeware Program "Everything" to find this file.
