### ISSUE TITLE
Anaconda2 install problem on RHEL7.2

### ISSUE THREAD

**Issue by durack1** [ContinuumIO/anaconda-issues#857]
Attempting to install on Redhat Enterprise Linux 7.2

```
duro@grim:[~]:[210]> sh Anaconda2-4.0.0-Linux-x86_64.sh
```

Leads to:

```
installing: conda-env-2.4.5-py27_0 ...
Anaconda2-4.0.0-Linux-x86_64.sh: line 461: /export/duro/anaconda2/pkgs/python-2.7.11-0/bin/python: Permission denied
ERROR:
cannot execute native linux-64 binary, output from 'uname -a' is:
Linux grim 3.10.0-327.18.2.el7.x86_64 #1 SMP Fri Apr 8 05:09:53 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

It appears this issue has been around for quite sometime (at least since May 2015): https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/3oicnx_s0kI

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 pinging you both here

**Comment by dnadeau4** [comment]
This is not even uvcdat, it seems to be anaconda not being install properly.

**Comment by doutriaux1** [comment]
you probably have a bad binary, i would redownload it. As @dnadeau4 mentioned this is anaconda issue, not uvcdat.

**Comment by dnadeau4** [comment]
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.1_Release_Notes/Known-Issues-Installation.html

**Comment by doutriaux1** [comment]
@durack1 older version works for me:
```
bash Anaconda2-2.5.0-Linux-x86_64.sh
```

**Comment by dnadeau4** [comment]
Try the miniconda installer: http://conda.pydata.org/miniconda.html#miniconda  I read that it works!

**Comment by doutriaux1** [comment]
@dnadeau4 i don't think it's the same `anaconda`

**Comment by dnadeau4** [comment]
I read that there is a binary mismatch between linux-32 and linux-64 for Red Hat 7.2.  We can't do anything until anaconda fix the installer.

**Comment by durack1** [comment]
@dnadeau4 wanna drop the URL to the reading above here?

**Comment by dnadeau4** [comment]
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/3oicnx_s0kI
http://stackoverflow.com/questions/22096720/installing-anaconda-on-ubuntu-13-10-giving-an-error-message
....

**Comment by durack1** [comment]
@dnadeau4 you might also like to cleanup the redundant comments above.. As I will do to this comment once I click "comment"..

**Comment by doutriaux1** [comment]
@durack1 I get the same error with or without sudo but interestingly, using 
```
sudo bash Anaconda2-2.5.0-Linux-x86_64.sh
```
and using the prefix `/usr/local/anaconda2` works.

**Comment by doutriaux1** [comment]
could it be nfs related?
```
doutriaux1@aims-gpu:[~]:[1944]> df /usr/local
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/sdb       492128608 290329216 176794012  63% /usr/local
doutriaux1@aims-gpu:[~]:[1945]> df ~
Filesystem             1K-blocks        Used   Available Use% Mounted on
169.254.36.0:/volume1/data/export
                     85560200960 34192100352 51367981824  40% /export
```

**Comment by durack1** [comment]
@doutriaux1 you could be onto something, if the mount is not set as `x` executable, that may cause problems down the line

**Comment by durack1** [comment]
@doutriaux1 I just hit another `noexec` error with another bit of software, it seems our mounts are in fact `noexec`:
```
duro@grim:[~]:[621]> mount | grep export
169.x.x.x:/volume1/data/export on /export type nfs4 (rw,nosuid,nodev,noexec,relatime,vers=4.0,rsize=131072,wsize=131072,namlen=255,soft,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=169.x.x.x,local_lock=none,addr=169.x.x.x)
```

**Comment by nehaljwani** [comment]
Closing as `noexec` is opposite of what we want.

**Comment by durack1** [comment]
@nehaljwani sure closing this is ok, but it would be useful to augment the error message with a note to confirm install directory (and/or mounts) have `exec` permissions.. it took some trial and error to determine this was the problem. It would've been helpful if the error message highlighted that specific issue

**Comment by nehaljwani** [comment]
Re-opening as a request for enhancement of installers.

**Comment by ayushidalmia** [comment]
Is this resolved?

**Comment by durack1** [comment]
@ayushidalmia the resolution is to augment the error message, so that in the case of a `noexec` mount the user is notified of the problem, rather than the vague error that lead to the discussion above.

I do not believe the error augmentation is done, and therefore the issue is not resolved

**Comment by remkade** [comment]
This is not currently on our roadmap, but if it causes problems for anyone we'd be happy to reconsider. Thanks!
