### ISSUE TITLE
dateutil package 404

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#858]
@ilanschnell 

From: http://stackoverflow.com/questions/37776256/conda-says-conflict-over-installing-dateutil-in-python-3-5-1

It appears the URL http://repo.continuum.io/pkgs/free/linux-64/dateutil-2.4.2-py35_0.tar.bz2 used to point to a valid package, but now it returns 404.  What's the story here?

**Comment by ilanschnell** [comment]
In version 2.4.1, we renamed `dateutil` to `python-dateutil`.  Older versions (`1.5`-`2.4.1`) of `dateutil` still exist, and for `python-dateutil` we have version `2.4.1`-`2.5.3`.

Just use `python-dateutil`.

**Comment by skjaeve** [comment]
Could you remove the `dateutil` package entirely from Conda, so we get an understandable error message instead?
