### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by bobaikato** [ContinuumIO/anaconda-issues#859]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - alabaster ==0.7.8
  - anaconda ==4.0.0 -> alabaster 0.7.7 py27_0|0.7.7 py34_0|0.7.7 py35_0
Use "conda info <package>" to see the dependencies for each package.

{'language': 'en', 'qt': '4.8.7', 'pyqt': '4.11.4', 'version': '1.2.1', 'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386', 'platform': 'osx-64', 'conda': '4.1.4', 'python': '3.5.1'}

**Comment by goanpeca** [comment]
Hi, as it says the dependencies selected cannot be solved by conda as they result in a conflict.
>UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
    alabaster ==0.7.8
    anaconda ==4.0.0 -> alabaster 0.7.7 py27_0|0.7.7 py34_0|0.7.7 py35_0 Use "conda info " to see the dependencies for each package.

**Comment by bobaikato** [comment]
how do I resolve it?


Best Regards,
Bobai E. Kato

B.Eng (Hons) Software Engineering
Tel: +353 (0) 83-860-0339 | Email: bobaikato@gmail.com <mailto:bobaikato@gmail.com> | Web: http://bobaikato.branded.me/ <http://bobaikato.branded.me/>
LinkedIn: https://www.linkedin.com/in/katobobai <https://www.linkedin.com/in/katobobai> | Twitter: Bobaikato | Github: Bobaikato | Skype: bobaikato

**Comment by goanpeca** [comment]
What did you try to do?

Looks like you tried to both update anaconda and alabaster in a way that the versions cannot reconcile.

**Comment by bobaikato** [comment]
Yes actually. 
I tried updating anaconda but it was as well saying some packages will be downgraded. How can I skip the downgrade?


Best Regards,
Bobai E. Kato
B.Eng (Hons) Software Engineering
 
Tel: +353 (0) 83-860-0339
Email: bobaikato@gmail.com
Profile: http://bobaikato.branded.me/ , 
https://www.linkedin.com/in/katobobai 
Skype: Bobaikato | Twitter: Bobaikato

**Comment by goanpeca** [comment]
Short answer is you can't.
The package Anaconda already defines a set of specific versions, so updating to anaconda means to make the packages match those versions, which in most cases are the latest ones but in some others (like you see) it will downgrade.

1. You can either update anaconda, and then manually update the packages that were downgraded or,
1. You an wait one day while the new release of anaconda comes out (it comes out later today) so you can install the latest anaconda package with the most up to date versions.

**Comment by bobaikato** [comment]
Great I look forward to it. Will have to uninstall the one I have and install the latest version or I can simply update from the terminal?

Thanks


Best Regards,
Bobai E. Kato

B.Eng (Hons) Software Engineering
Tel: +353 (0) 83-860-0339 | Email: bobaikato@gmail.com <mailto:bobaikato@gmail.com> | Web: http://bobaikato.branded.me/ <http://bobaikato.branded.me/>
LinkedIn: https://www.linkedin.com/in/katobobai <https://www.linkedin.com/in/katobobai> | Twitter: Bobaikato | Github: Bobaikato | Skype: bobaikato
