### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jeevasakthits** [ContinuumIO/anaconda-issues#8597]
## Main error
The following errors occurred:
## Traceback
```
CondaEnvironmentNotFoundError: Could not find environment: C:\Users\jeeva sakthi\Anaconda3\envs\root .
You can list all discoverable environments with `conda info --envs`.
```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment]
@jeevasakthits you seem to have a space in your username

`C:\Users\jeeva sakthi`, this may lead to some libraries not working properly so I would advice re-installing in a place without spaces (or accented characters).

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
