### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by JuantLB** [ContinuumIO/anaconda-issues#863]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - _nb_ext_conf -> notebook >=4.2.0
  - _nb_ext_conf -> python 2.7*|3.4*
  - anaconda ==4.0.0
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'language': 'pt_PT', 'conda': '4.1.4', 'version': '1.2.1', 'qt': '4.8.7', 'python': '3.5.1', 'platform': 'win-64'}

**Comment by goanpeca** [comment]
@ccordoba12 any thoughts on this?

**Comment by ccordoba12** [comment]
I don't even understand what this error is about. @JuantLB, could you at least tell us what you were trying to do when you got that error?

I really don't understand how you expect help from us with such little information.... :-/

**Comment by JuantLB** [comment]
Sorry for that

I was trying to create a new  pyton 2.7 environment , with Anaconda Navigator.

Right now, I can´t create environments with the navigator. It just stops.

**Comment by goanpeca** [comment]
What version of navigator are you using?

**Comment by JuantLB** [comment]
Sorry for the delayed reponse

I'm using the most recent version, I guess, 1.2.1

J

2016-07-04 19:44 GMT+01:00 Gonzalo Peña-Castellanos <
notifications@github.com>:

**Comment by goanpeca** [comment]
Can you explain us whta yo tried to do in the first place?

**Comment by JuantLB** [comment]
I've tryed to create a new python 2.7 environment.



J

2016-07-05 16:15 GMT+01:00 Gonzalo Peña-Castellanos <
notifications@github.com>:

**Comment by goanpeca** [comment]
This only happens with 2.7, or 3.4, 3.5?

**Comment by JuantLB** [comment]
And with R an python 3.5

I did't try another ones.

I can't create new wnvironments or upgrade packages

J

2016-07-05 16:51 GMT+01:00 Gonzalo Peña-Castellanos <
notifications@github.com>:

**Comment by goanpeca** [comment]
Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
