### ISSUE TITLE
R source() internet routines cannot be loaded

### ISSUE THREAD

**Issue by PertuyF** [ContinuumIO/anaconda-issues#8640]
When using `source(https://bioconductor.org/biocLite.R)` inside `R`, the following error happens:

> Error in file(filename, "r", encoding = encoding) :
  internet routines cannot be loaded
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  unable to load shared object '/local/User/miniconda3/envs/r-env/lib/R/modules//internet.so':
  /local/User/miniconda3/envs/r-env/lib/R/modules//../../libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos

This command is supposed to install `biocInstaller` or load `biocLite`, and allow to use `biocLite` to install packages from bioconductor.

### Environment

install `miniconda3-latest` (at this time it is likely `4.4.10`)
install `bioconductor-biocinstaller` from channel `bioconda` (restrict further packages to R 4.3.1)
install `r-essentials`

## Solution

The current issue is submitted for documentation, and as been solved already.
[Issue #4421](https://github.com/ContinuumIO/anaconda-issues/issues/4421) was somehow related, but the indicated solution did not work in my case.

The error indicated a problem with `libcurl.so.4`, and it appeared that the `curl` version `7.55.1-0` package from channel `defaults` was responsible for this.
Downgrading `curl` to a previous version solved the problem (works with version `7.48.0-2`, or even `7.55.1-hcb0b314_2`).

**Comment by mingwandroid** [comment]
If you are using packages from `bioconda` and `Anaconda Defaults` together in the same environment then you should expect trouble and I cannot offer support for people doing this at present (we are not binary compatible).

**Comment by PertuyF** [comment]
Completely new environment with channels correctly set, as indicated from Bioconda, to priority:
```yaml
  - bioconda
  - conda-forge
  - defaults
```
This error happened again (this time using `curl` version `7.59.0-0`), and the same solution worked (downgrade to `curl` version `7.48.0-2`).

Strange thing is that the error raised only through SSH connection. If I connect directly to the same machine not using SSH, same session, same environment, same command, then no error.
I'm a bit puzzled here, any idea on how `curl` version could make it fail?

**Comment by mingwandroid** [comment]
Sorry, `anaconda-issues` is for reporting issues with the `Anaconda Distribution` only at present. `bioconda` and `conda-forge` are not supported here.

**Comment by mingwandroid** [comment]
You need to make an environment which does not include *anything* from `defaults` if you wish to use anything from `bioconda` or `conda-forge` and then if you run into any issues with that (outside of conda itself doing something wrong) then you need to report that to `bioconda`.

**Comment by abalter** [comment]
@mingwandroid -- But [the docs](https://bioconda.github.io/#set-up-channels) say to use the `defaults` channel:

```
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

**Comment by mingwandroid** [comment]
I didn't write those docs. I suggest you bring it up with bioconda

**Comment by abalter** [comment]
I'd be happy to. But what evidence do I give them that one should "not include _anything_ from `defaults`?"

**Comment by mingwandroid** [comment]
They should be aware of this. Just Google for binary compatibility.

**Comment by abalter** [comment]
@mingwandroid -- the only really useful hit from this:

https://www.google.com/search?q=bioconda+binary+compatibility&oq=bioconda+binary+compatibility&aqs=chrome..69i57.4489j0j9&sourceid=chrome&ie=UTF-8

Is an issue from 2016:

https://github.com/conda/conda/issues/3721

Perhaps the docs need to be edited?

**Comment by mingwandroid** [comment]
Yes, the bioconda docs may need to be edited. I am not sure, please bring it up with them.
