### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by marinacano** [ContinuumIO/anaconda-issues#8650]
When downloading the Anaconda package for Mac and opening it, it goes to Safari and shows a Navigator Error

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@marinacano what is the error?

**Comment by marinacano** [comment]
Here is a screenshot of the error:

**Comment by goanpeca** [comment]
@marinacano still no screenshot

**Comment by marinacano** [comment]
what do you mean? i sent it on the last email??? Here it is again:

**Comment by goanpeca** [comment]
@marinacano it does not work like that. Please open this on your browser

https://github.com/ContinuumIO/anaconda-issues/issues/8650

And attach on the github webpage

**Comment by marinacano** [comment]
<img width="819" alt="screen shot 2018-02-23 at 12 53 29 pdf" src="https://user-images.githubusercontent.com/36764996/36634228-585ec3b6-1999-11e8-8800-a3ed565e5ccc.png">

**Comment by goanpeca** [comment]
@marinacano please open the terminal and update anaconda-client to version 1.6.11 by doing

```
conda install anaconda-client=1.6.11
```

And try again

**Comment by marinacano** [comment]
thank you so much!! it works now!!

**Comment by goanpeca** [comment]
Glad to be of help :-)
