### ISSUE TITLE
root_prefix error

### ISSUE THREAD

**Issue by bernardshen** [ContinuumIO/anaconda-issues#8662]
Main Error

'root_prefix'

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

**Comment by goanpeca** [comment]
@bernardshen did you install Anaconda for all users?

**Comment by ajsgithub** [comment]
I had the same problem.  I installed from Anaconda3-5.0.1 and updated regularly.  I didn't have any problems until I updated to Anaconda Navigator 1.7.0.

I don't have time to wait for a solution so I uninstalled and reinstalled Anaconda3-5.1.0.  Anaconda Navigator now works again.

**Comment by bernardshen** [comment]
@goanpeca I tried both 'for me' and 'for all users' option. They all gave me the same error report.

**Comment by kem1** [comment]
Very same issue here (Windows 7). I tested

0) update with 
```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
1) run using launcher (normally)
2) run as administrator
3) run after anaconda-navigator --reset
4) run after "activate root"

Still experiencing the issue.

**Comment by goanpeca** [comment]
@kem1, @bernardshen @ajsgithub could you provide the output of running

```
conda info --json
```

**Comment by kalefranz** [comment]
Must be an ancient version of conda-build.

    conda update conda conda-build

**Comment by kalefranz** [comment]
If that doesn't work

    conda install conda-build --force

**Comment by kem1** [comment]
conda-build helped. Navigator starts normally now. I just tested conda update conda - it seems to be insufficient method.

Are you still interested in conda info --json ?

**Comment by goanpeca** [comment]
@kem1 yes, please provide it :-)

**Comment by kem1** [comment]
OK - here it is. I would like to say it again - after conda-build update it seems to be working properly

`>conda info --json
{
  "active_prefix": null,
  "active_prefix_name": null,
  "channels": [
    "https://conda.anaconda.org/anaconda-fusion/win-64",
    "https://conda.anaconda.org/anaconda-fusion/noarch",
    "https://conda.anaconda.org/Primer/win-64",
    "https://conda.anaconda.org/Primer/noarch",
    "https://conda.anaconda.org/omnia/win-64",
    "https://conda.anaconda.org/omnia/noarch",
    "https://repo.continuum.io/pkgs/main/win-64",
    "https://repo.continuum.io/pkgs/main/noarch",
    "https://repo.continuum.io/pkgs/free/win-64",
    "https://repo.continuum.io/pkgs/free/noarch",
    "https://repo.continuum.io/pkgs/r/win-64",
    "https://repo.continuum.io/pkgs/r/noarch",
    "https://repo.continuum.io/pkgs/pro/win-64",
    "https://repo.continuum.io/pkgs/pro/noarch",
    "https://repo.continuum.io/pkgs/msys2/win-64",
    "https://repo.continuum.io/pkgs/msys2/noarch"
  ],
  "conda_build_version": "3.6.0",
  "conda_env_version": "4.4.11",
  "conda_location": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\conda",
  "conda_prefix": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3",
  "conda_private": false,
  "conda_shlvl": -1,
  "conda_version": "4.4.11",
  "config_files": [
    "C:\\Users\\XXXXXX\\.condarc"
  ],
  "default_prefix": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "COMMANDER_PATH": "C:\\apps\\wincmd",
    "CONDA_ROOT": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3",
    "HOMEPATH": "\\Users\\XXXXXX",
    "PATH": "C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Program Files\\Common Files\\Microsoft Shared\\Windows Live;C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\Windows Live;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\windows\\system32;C:\\w
indows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\MATLAB\\R2017a\\bin;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\ManagementStudio\\;C:\\Program Fil
es (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files (x86)\\Window
s Live\\Shared;C:\\Program Files\\MATLAB\\MATLAB Compiler Runtime\\v80\\runtime\\win64;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\PuTTY\\;C:\\Program Files (x86)\\Skype\\
Phone\\;C:\\Program Files\\1E\\NomadBranch\\;C:\\PostgreSQL\\pg96\\bin;C:\\Program Files (x86)\\Intel\\UCRT\\;C:\\Program Files\\Intel\\UCRT\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program F
iles (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\apps\\Ruby24-x64\\bin;C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3;C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\Scripts;C:\\Users\\XXXXXX\\
AppData\\Local\\Continuum\\Anaconda3\\Library\\bin;C:\\Users\\XXXXXX\\AppData\\Local\\Programs\\Git\\cmd;c:\\ffmpeg\\bin",
    "PSMODULEPATH": "C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\PowerShell\\Modules\\",
    "REQUESTS_CA_BUNDLE": "<not set>",
    "SSL_CERT_FILE": "<not set>",
    "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox\\"
  },
  "envs": [
    "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3",
    "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\envs\\py36_airlytics",
    "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\envs\\py36_emsopmonitor",
    "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\envs\\py36_rl"
  ],
  "envs_dirs": [
    "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\envs",
    "C:\\Users\\XXXXXX\\AppData\\Local\\conda\\conda\\envs",
    "C:\\Users\\XXXXXX\\.conda\\envs"
  ],
  "is_windows_admin": false,
  "netrc_file": null,
  "offline": false,
  "pkgs_dirs": [
    "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\pkgs",
    "C:\\Users\\XXXXXX\\AppData\\Local\\conda\\conda\\pkgs"
  ],
  "platform": "win-64",
  "python_version": "3.6.4.final.0",
  "rc_path": "C:\\Users\\XXXXXX\\.condarc",
  "requests_version": "2.18.4",
  "root_prefix": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3",
  "root_writable": true,
  "site_dirs": [
    "C:\\Users\\XXXXXX\\AppData\\Roaming\\Python\\Python35"
  ],
  "sys.executable": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\python.exe",
  "sys.prefix": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3",
  "sys.version": "3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]",
  "sys_rc_path": "C:\\Users\\XXXXXX\\AppData\\Local\\Continuum\\Anaconda3\\.condarc",
  "user_agent": "conda/4.4.11 requests/2.18.4 CPython/3.6.4 Windows/7 Windows/6.1.7601",
  "user_rc_path": "C:\\Users\\XXXXXX\\.condarc"
}





























`

**Comment by goanpeca** [comment]
Thanks
