### ISSUE TITLE
Navigator pointing to the wrong notebook?

### ISSUE THREAD

**Issue by KenHollandWHY** [ContinuumIO/anaconda-issues#867]
I have a strange issue on Windows. I've been using anaconda for a while and have a dozen or so jupyter notebooks. Today I  downloaded the navigator and when I use its interface to launch jupyter, everything looks like it always does...but when I launch one of the notebooks and try to import pandas for example the notebook tries to load the module from a now deleted python 2.7 installation, and then quits in error. 
Only when I launch the notebook via the 64 bit command prompt does the notebook load all the python 3.4 modules I actually installed.

**Comment by goanpeca** [comment]
Hi @KenHollandWHY 

Are you launching the notebook from home screen? or from the environments tab?
What version of navigator are you using?

**Comment by KenHollandWHY** [comment]
I am launching it from cmd line -- I just downloaded the newest notebook. Previously I would l launch via the anaconda launcher but since its been depreciated I switched to the navigator.

**Comment by goanpeca** [comment]
Hi @KenHollandWHY 

You are reporting a bug on navigator so the questions are realted to navigator.

1. **Inside Navigator**: Are you launching the notebook from home screen? or from the environments tab?
2. What version of navigator are you using?

**Comment by KenHollandWHY** [comment]
Oh I see, yes its from the home screen and its 121.

**Comment by goanpeca** [comment]
Ok, lets try to dig deeper into this:

1. Could you open Navigator and from the home screen launch notebook, then create a new notebook (dont select and already existing one) and in that notebook run 

```python
import os
import sys
print(sys.path)
print(sys.executable)
```
And paste the results?

2. Could you launch the notebook from the command line, then create a new notebook (dont select and already existing one) and in that notebook run 

```python
import os
import sys
print(sys.path)
print(sys.executable)
```

And paste the results?

Thanks

**Comment by KenHollandWHY** [comment]
From the navigator:

> ['', 'C:\\Users\\NataliaGBC\\AppData\\Local\\Enthought\\Canopy32\\User\\Lib\\site-packages', '', 'C:\\Users\\NataliaGBC\\Anaconda3\\python34.zip', 'C:\\Users\\NataliaGBC\\Anaconda3\\DLLs', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib', 'C:\\Users\\NataliaGBC\\Anaconda3', 'c:\\users\\nataliagbc\\anaconda3\\lib\\site-packages\\sphinx-1.3.1-py3.4.egg', 'c:\\users\\nataliagbc\\anaconda3\\lib\\site-packages\\husl-4.0.0-py3.4.egg', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\cryptography-0.9.1-py3.4-win-amd64.egg', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\setuptools-0.6c11-py3.4.egg-info', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\NataliaGBC\\.ipython']
C:\Users\NataliaGBC\Anaconda3\python.exe

And from the cmnd line 

> ['', 'C:\\Users\\NataliaGBC\\Anaconda3\\python34.zip', 'C:\\Users\\NataliaGBC\\Anaconda3\\DLLs', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib', 'C:\\Users\\NataliaGBC\\Anaconda3', 'c:\\users\\nataliagbc\\anaconda3\\lib\\site-packages\\sphinx-1.3.1-py3.4.egg', 'c:\\users\\nataliagbc\\anaconda3\\lib\\site-packages\\husl-4.0.0-py3.4.egg', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\cryptography-0.9.1-py3.4-win-amd64.egg', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\setuptools-0.6c11-py3.4.egg-info', 'C:\\Users\\NataliaGBC\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\NataliaGBC\\.ipython']
C:\Users\NataliaGBC\Anaconda3\python.exe

so this line :"'C:\\Users\\NataliaGBC\\AppData\\Local\\Enthought\\Canopy32\\User\\Lib\\site-packages" is the issue?

**Comment by goanpeca** [comment]
**"'C:\Users\NataliaGBC\AppData\Local\Enthought\Canopy32\User\Lib\site-packages"**

Indeed, that sounds like path somehow got messed up

**Comment by KenHollandWHY** [comment]
Strange since that line is in neither the system nor the user PATH.
