### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by benbendemo** [ContinuumIO/anaconda-issues#8671]
Anaconda Navigator Update error:

//anaconda/bin/python //anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.6.4: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.6.4* -> pyqt >=5.6 -> qt 5.6.*
  - orange -> pyqt 4.* -> qt >=4.8.6,<5.0
  - orange -> pyqt 4.* -> sip >=4.16.4,<4.18
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.3.30', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Oct  2 22:20:08 PDT 2017; root:xnu-3248.71.4~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda install conda=4.4.10
conda install anaconda-navigator=1.7.0
conda install navigator-updater=0.1.0
```

**Comment by benbendemo** [comment]
The latest verison is Anaconda 2.5.1,why you suggest me to install anaconda-navigator=1.7.0,and by the way,I can't use conda command in my terminal with this "-bash: conda: command not found",can you help me?

**Comment by goanpeca** [comment]
>why you suggest me to install anaconda-navigator=1.7.0

@benbendemo because that is the latest anaconda navigator version (you seem to have 1.6.4)

>-bash: conda: command not found

Cause it seems to not be set on path, so you would need to navigate to the `...anaconda2/bin` folder and run

```
source activate root
```

And then run the commands I indicated

**Comment by benbendemo** [comment]
Thank you very much,I've solved the installation problem by removing "binstar/config.yaml" file,then anaconda2 could run well.Same situation like #8568 .
