### ISSUE TITLE
h2o import

### ISSUE THREAD

**Issue by adarsha04** [ContinuumIO/anaconda-issues#8677]
Hey guys,

I installed h2o for pyhton 2 using below code.(azure notebook IDE)
 !pip install h2o 

Then imported using:

import h2o

its giving the below error: 

H2OConnectionError: Could not establish link to the H2O cloud http://127.0.0.1:54321 after 20 retries
[07:03.57] H2OServerError: HTTP 503 Service Unavailable:
[07:04.78] H2OServerError: HTTP 503 Service Unavailable:
[07:05.99] H2OServerError: HTTP 503 Service Unavailable:

can I get some help from anyone please?

**Comment by csoja** [comment]
@adarsha04  I do not believe this is the right place for your issue as Anaconda, Inc. does not build or maintain the h2o python packages installed with pip.  https://www.h2o.ai/community-forum/ may help direct you to the best place for your question.
