### ISSUE TITLE
Saving window size

### ISSUE THREAD

**Issue by MarcosCarreira** [ContinuumIO/anaconda-issues#868]
Anaconda Navigator always open with a full screen window; reducing the size of the window does not save this preference automatically. Small issue, but simple to fix?
Version 1.2.1
Mac OSX 10.11.5
Thanks
Marcos

**Comment by goanpeca** [comment]
@MarcosCarreira will take note :-)

**Comment by MarcosCarreira** [comment]
Thanks!

**Comment by chrisjcameron** [comment]
This rough edge is particularly onerous on large displays -- I don't need 30 inches of empty frame for 6 items!

**Comment by goanpeca** [comment]
This has been fixed on the latest version of Navigator

`conda update anaconda-navigator`

or

`conda update anaconda`
