### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by etziperman** [ContinuumIO/anaconda-issues#869]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - anaconda ==4.1.0
  - bokeh ==0.12.0
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'python': '3.5.1', 'version': '1.2.1', 'conda': '4.1.5', 'platform': 'osx-64', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
