### ISSUE TITLE
The reason I couldn't update my anaconda version

### ISSUE THREAD

**Issue by benbendemo** [ContinuumIO/anaconda-issues#8718]
Anaconda Navigator Update error:

//anaconda/bin/python //anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.6.4: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.6.4* -> pyqt >=5.6 -> qt 5.6.*
  - orange -> pyqt 4.* -> qt >=4.8.6,<5.0
  - orange -> pyqt 4.* -> sip >=4.16.4,<4.18
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.3.30', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Mon Oct  2 22:20:08 PDT 2017; root:xnu-3248.71.4~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@benbendemo you have installed Orange which depends on qt=4.* and want to install Navigator which requires qt=5.*, so there is a conflict of dependencies.

To perform the update please do the following, open aterminal and type

```
conda remove orange
conda install anaconda-navigator=1.7.0
```

**Comment by benbendemo** [comment]
I've just uninstalled anaconda 1.7.0 and download anaconda 2.5.1,then run across this problem.I try to fix the problem as you instruct,but failed with "-bash: conda: command not found" in terminal.Pls help.

**Comment by goanpeca** [comment]
Answered on https://github.com/ContinuumIO/anaconda-issues/issues/8671
