### ISSUE TITLE
Changing the package filtering view hides the 'apply' button

### ISSUE THREAD

**Issue by mrduane** [ContinuumIO/anaconda-issues#872]
To reproduce:

- mark 1 or more packages for install
- change the filtered view (say from 'not installed' to 'all') using the drop-down at the top of the panel
- the 'apply' button in the lower right of the navigator window disappears, and it's not possible to add your selected packages to the env.

Workaround: un-mark & re-mark one of the packages you'd like to install.
Version: Navigator 1.2.1

**Comment by goanpeca** [comment]
Hi @mrduane, can reproduce this bug. An bugfix is on the way :-)
