### ISSUE TITLE
zlib1.dll conflict causing r load package error

### ISSUE THREAD

**Issue by haywardlam** [ContinuumIO/anaconda-issues#8721]
Using Anaconda Prompt/terminal, "activate test_env_6_p3_6_r" my environment with Python 3.6 and R. 
On the terminal, start up R by typing "r", it shows errors in loading packages:

- stats
- graphics
- grDevices

The problem is caused by zlib1.dll conflict. "zlib1.dll" file can be found in:

- C:\Users\hxl0852\anaconda3\test_env_6_p3_6_r\Library\mingw-64\bin
- C:\Windows\System32

On the terminal, type "echo %path%", shows 

(test_env_6_p3_6_r) C:\Users\hxl0852>echo %path%

C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r;
C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r\Library\mingw-w64\bin;
C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r\Library\usr\bin;
C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r\Library\bin;
C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r\Scripts;
C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r\bin;
C:\Users\hxl0852\anaconda3;
C:\Users\hxl0852\anaconda3\Library\mingw-w64\bin;
C:\Users\hxl0852\anaconda3\Library\usr\bin;
C:\Users\hxl0852\anaconda3\Library\bin;
C:\Users\hxl0852\anaconda3\Scripts;
C:\Users\hxl0852\anaconda3\bin;
C:\ProgramData\Oracle\Java\javapath;
C:\Program Files (x86)\Attachmate\Reflection\;
C:\windows\system32;
C:\windows;
C:\windows\System32\Wbem;
C:\windows\System32\WindowsPowerShell\v1.0\;
C:\Users\hxl0852\AppData\Local\Microsoft\WindowsApps;

The zlib1.dll in "C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r\Library\mingw-w64\bin" should take precedence over "C:\windows\system32", according to the path, but it does not. 

To test if the wrong zlib1.dll is being picked up when executing "r", I copied Anaconda zlib1.dll to "C:\Windows\system32", "r" starts with no error.

The problem is the path order does not seem to be respected. 

I don't really want to replace the C:Windows\system32\zlib1.dll because it may cause problems for other programs. 

Anaconda 5.1.0. 
Windows 10 Enterprise 64 bit

**Comment by mingwandroid** [comment]
> The zlib1.dll in "C:\Users\hxl0852\anaconda3\envs\test_env_6_p3_6_r\Library\mingw-w64\bin" should take precedence over "C:\windows\system32", according to the path, but it does not.

This is not how Windows DLL search proceeds though. C:\Windows\System32 is looked in before *anything* on `PATH`.

**Comment by mingwandroid** [comment]
> I don't really want to replace the C:Windows\system32\zlib1.dll

It might, but *no* software except system drivers and software provided by MS should ever place anything in that folder so the software it stands to break is probably pretty badly written anyway.

**Comment by mingwandroid** [comment]
As a suggestion you could check the creation/modification date on this rogue zlib1.dll file and try to figure out (possibly by looking at the creation/modification dates of your Start Menu entries) which software this is.

**Comment by mingwandroid** [comment]
Further, I already explained this to you in https://github.com/ContinuumIO/anaconda-issues/issues/8641#issuecomment-367834278
