### ISSUE TITLE
It should only take one click to mark (or un-mark) a package for installation

### ISSUE THREAD

**Issue by mrduane** [ContinuumIO/anaconda-issues#873]
Right now, both actions require 2 clicks.
version: Navigator 1.2.1

**Comment by goanpeca** [comment]
Thanks for reporting, we are actively working to improve the UI/UX.

**Comment by goanpeca** [comment]
In the meantime, you could click on the header on top of the "checkboxes" and sort by action when the combobox has **All** and you get this

![image](https://cloud.githubusercontent.com/assets/3627835/16538926/dfce5492-3ff7-11e6-8828-dfa69a948cf8.png)

**Comment by goanpeca** [comment]
This has been fixed in version 1.3
