### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by harahu** [ContinuumIO/anaconda-issues#8737]
### Actual Behavior

I am writing a TensorFlow Dataset, build from a generator that returns slices from a pandas DataFrame. My script runs fine, but in debug mode I get the following error messages:

```Exception ignored in: <generator object find_common_type.<locals>.<genexpr> at 0x126d5b8e0>
Traceback (most recent call last):
  File "/Users/harald/anaconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 1074, in <genexpr>
    if all(is_dtype_equal(first, t) for t in types[1:]):
SystemError: error return without exception set
Exception ignored in: <generator object find_common_type.<locals>.<genexpr> at 0x126d5b8e0>
Traceback (most recent call last):
  File "/Users/harald/anaconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 1081, in <genexpr>
    if all(is_datetime64_dtype(t) for t in types):
SystemError: error return without exception set
Exception ignored in: <generator object find_common_type.<locals>.<genexpr> at 0x126d5b8e0>
Traceback (most recent call last):
  File "/Users/harald/anaconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 1083, in <genexpr>
    if all(is_timedelta64_dtype(t) for t in types):
SystemError: error return without exception set
Exception ignored in: <generator object _yield_value at 0x126d5be08>
Traceback (most recent call last):
  File "/Users/harald/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 95, in _yield_value
    yield iterable[key]
SystemError: error return without exception set
Exception ignored in: <generator object _yield_value at 0x126d5bba0>
Traceback (most recent call last):
  File "/Users/harald/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 100, in _yield_value
    yield value
SystemError: error return without exception set
```

According to the [Python doc](https://docs.python.org/3/library/exceptions.html#SystemError) I should report this to "the author or maintainer of your Python interpreter". I presume this is you guys, as I run Python 3.6.4 |Anaconda, Inc.|. Feel free to put me in the right direction if I have missed something. It seems this could be a problem in either Pandas or TensorFlow as well.

### Expected Behavior

I expected there not to be SystemErrors.

##### Anaconda or Miniconda version:

anaconda Command line client (version 1.6.5)

##### Operating System:

MacOS High Sierra v10.13.3

##### `conda info`

```
     active environment : thesis
    active env location : /Users/harald/anaconda3/envs/thesis
            shell level : 1
       user config file : /Users/harald/.condarc
 populated config files : /Users/harald/.condarc
          conda version : 4.4.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /Users/harald/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/harald/anaconda3/pkgs
                          /Users/harald/.conda/pkgs
       envs directories : /Users/harald/anaconda3/envs
                          /Users/harald/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.3 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at /Users/harald/anaconda3/envs/thesis:
#
# Name                    Version                   Build  Channel
absl-py                   0.1.10                    <pip>
appnope                   0.1.0                     <pip>
astor                     0.6.2                     <pip>
bleach                    2.1.2                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2018.1.18                py36_0    defaults
cycler                    0.10.0                    <pip>
decorator                 4.2.1                     <pip>
entrypoints               0.2.3                     <pip>
gast                      0.2.0                     <pip>
grpcio                    1.9.1                     <pip>
html5lib                  1.0.1                     <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.2.1                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.1.2                     <pip>
jedi                      0.11.1                    <pip>
Jinja2                    2.10                      <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.2                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
Markdown                  2.6.11                    <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.2                     <pip>
mistune                   0.8.3                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
ncurses                   6.0                  hd04f020_2    defaults
notebook                  5.4.0                     <pip>
numpy                     1.14.1                    <pip>
openssl                   1.0.2n               hdbc3d79_0    defaults
pandas                    0.22.0                    <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.1.1                     <pip>
pexpect                   4.4.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1            py36h1555ced_4    defaults
prompt-toolkit            1.0.15                    <pip>
protobuf                  3.5.1                     <pip>
ptyprocess                0.5.2                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.6.4                hc167b69_1    defaults
python-dateutil           2.6.1                     <pip>
pytz                      2018.3                    <pip>
pyzmq                     17.0.0                    <pip>
qtconsole                 4.3.1                     <pip>
readline                  7.0                  hc1231fa_4    defaults
scikit-learn              0.19.1                    <pip>
scipy                     1.0.0                     <pip>
Send2Trash                1.5.0                     <pip>
setuptools                38.4.0                   py36_0    defaults
setuptools                38.5.1                    <pip>
simplegeneric             0.8.1                     <pip>
six                       1.11.0                    <pip>
sqlite                    3.22.0               h3efe00b_0    defaults
tensorboard               1.6.0                     <pip>
tensorflow                1.6.0                     <pip>
tensorflow-tensorboard    1.5.1                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.6.7                h35a86e2_3    defaults
tornado                   4.5.3                     <pip>
traitlets                 4.3.2                     <pip>
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0           py36h5eb2c71_1    defaults
widgetsnbextension        3.1.4                     <pip>
xz                        5.2.3                h0278029_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```

**Comment by Fierozen** [comment]
+1 Since I migrated one of my projects to Python 3.6.4, I have seen cases where thousands of these "SystemError: error return without exception set" are thrown. They come from different places, they don't seem to affect the behavior, only seen if debugging. I too am using Anaconda, running in PyCharm on High Sierra 10.13.4, in a virtual environment.

**Comment by mingwandroid** [comment]
Are you using pip to install stuff?

Can you update Python to 3.6.5

**Comment by hhusum** [comment]
Problem persists with Python 3.6.5

And yes, I am.

**Comment by mingwandroid** [comment]
Can you give complete reproduction steps please?

**Comment by hhusum** [comment]
I haven't had time to find minimal steps to reproduction, and this happens in a piece of code I can't share with you. I'll look for reproduction steps come the end June, if it is still there by then. Just thought you should be aware that this problem exists in case you had some obviously suspect code.

**Comment by Fierozen** [comment]
I will try to construct a minimal case where it happens. However, from my observations it appears that it might be intermittent.

**Comment by mingwandroid** [comment]
> in case you had some obviously suspect code

Err, well, not really, I mean we'd fix that. Here you're trying to use binaries built by Google with binaries built by us and that's likely going to be problematic.

**Comment by aardvark82** [comment]
I am encountering the same issue after upgrading Python. This started happening approx. 4 weeks ago.

Although I was using Anaconda, I uninstalled Anaconda, miniconda, Homebrew and installed the official 3.6 version from https://www.python.org/downloads/mac-osx/ and a clean venv and still encounbtering the issue. I'm stumped but this leads me to believe it's not Anaconda related.

Mostly raising exceptions in werkzeug, googleapiclient and oauth2client.
Setup:  Mac OS X latest version, Pycharm latest version. Libraries are latest version as of this moment (clean venv, no version specified in requirements.txt. file)

I've posted a SO question if anyone wants to contribute. https://stackoverflow.com/questions/50055316/flask-upgrade-lots-of-exception-ignored-in-messages-in-console

`127.0.0.1 - - [24/May/2018 15:24:12] "GET /intro HTTP/1.1" 200 -
Exception ignored in: <generator object url_parse.<locals>.<genexpr> at 0x11521aa98>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/werkzeug/urls.py", line 428, in <genexpr>
    if not rest or any(c not in s('0123456789') for c in rest):
SystemError: error return without exception set
Environment detected = MACBOOK PRO
url=http://localhost:5000/setTimeOffset?time_offset=-7 None None None None None None
Environment detected = MACBOOK PRO
session id=16c3172a-c645-4198-baf2-3bae1d1946ad None None None None None None
Access token expires in 0:59:59.988708
Exception ignored in: <generator object _findPageTokenName.<locals>.<genexpr> at 0x11521a410>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1165, in <genexpr>
    if tokenName in fields), None)
SystemError: error return without exception set
Exception ignored in: <generator object _findPageTokenName.<locals>.<genexpr> at 0x11521a410>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1165, in <genexpr>
    if tokenName in fields), None)
SystemError: error return without exception set
Exception ignored in: <generator object _findPageTokenName.<locals>.<genexpr> at 0x11521a410>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1165, in <genexpr>
    if tokenName in fields), None)
SystemError: error return without exception set
Exception ignored in: <generator object _findPageTokenName.<locals>.<genexpr> at 0x11521a410>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1165, in <genexpr>
    if tokenName in fields), None)
SystemError: error return without exception set
Exception ignored in: <generator object _findPageTokenName.<locals>.<genexpr> at 0x11521a410>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1165, in <genexpr>
    if tokenName in fields), None)
SystemError: error return without exception set
Exception ignored in: <generator object _findPageTokenName.<locals>.<genexpr> at 0x11521a410>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/googleapiclient/discovery.py", line 1165, in <genexpr>
    if tokenName in fields), None)
SystemError: error return without exception set
Exception ignored in: <generator object wrap_http_for_auth.<locals>.new_request.<locals>.<genexpr> at 0x115378f10>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/oauth2client/transport.py", line 169, in <genexpr>
    if all(getattr(body, stream_prop, None) for stream_prop in
SystemError: error return without exception set
Access token expires in 0:59:59.994491
Exception ignored in: <generator object wrap_http_for_auth.<locals>.new_request.<locals>.<genexpr> at 0x1156e3c50>
Traceback (most recent call last):
  File "/Project/venv/lib/python3.6/site-packages/oauth2client/transport.py", line 169, in <genexpr>
    if all(getattr(body, stream_prop, None) for stream_prop in
SystemError: error return without exception set`

**Comment by RunOrVeith** [comment]
Are you running PyCharm Debugger? I had the same problem, but I found it to be an issue of the debugger itself, not tensorflow, or django or anything else. 
You can disable these errors by setting the environment variable inside pycharm `PYDEVD_USE_FRAME_EVAL=NO` before starting the debug script.
Also see this error https://youtrack.jetbrains.com/issue/PY-30036

**Comment by danFromTelAviv** [comment]
PYDEVD_USE_FRAME_EVAL=NO didn't help me :/  thanks though
Is there any update on this ?

**Comment by DAlexis** [comment]
The same problem only with PyCharm Debugger under Ubuntu

**Comment by ReinierNL** [comment]
PYDEVD_USE_FRAME_EVAL=NO worked for me. Thank you!

**Comment by methane** [comment]
It seems this issue can be closed.
