### ISSUE TITLE
Channels protected with tokens should be supported

### ISSUE THREAD

**Issue by mrduane** [ContinuumIO/anaconda-issues#874]
Navigator doesn't support channels with tokens 

When adding the protected channel from within Navigator, the channel URL is converted to lowercase.  The URL contains the token however, which is case-sensitive, so there's an auth failure when trying to access the channel. 

If the channel is instead added from the command line, case sensitivity is preserved, but Navigator doesn't include the protected channel's package in its list. 

v1.2.1 on OSX

**Comment by mrduane** [comment]
Clarification - Navigator breaks channels that are protected with tokens. The channel URL is eventually converted to lowercase and over-written in .condarc, even if added properly from the command line.

**Comment by goanpeca** [comment]
@mrduane thanks for reporting. I can confirm this and moving to internal defects tracking.

**Comment by goanpeca** [comment]
Latest version of Navigator fixes this
