### ISSUE TITLE
It should be possible to paste channel URLs when adding a channel

### ISSUE THREAD

**Issue by mrduane** [ContinuumIO/anaconda-issues#875]
It's not possible to paste copied text when adding a channel. This would be useful for longer channel URLs, as well as those that require tokens.

v1.2.1 on OSX

**Comment by goanpeca** [comment]
Thanks for reporting @mrduane. Bugfix underway.

**Comment by goanpeca** [comment]
This is fixed on 1.3 version of Navigator :-)
