### ISSUE TITLE
Navigator启动时发生意外错误

### ISSUE THREAD

**Issue by 734307558** [ContinuumIO/anaconda-issues#8757]
主要错误
无法确定标记'tag：'的构造函数：yaml.org，2002：python / unicode'
  在“C：\ Users \ Firefly \ AppData \ Local \ ContinuumIO \ binstar \ config.yaml”第1行第1列

追溯
回溯（最近一次通话最后）：
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ exceptions.py”，第75行，在exception_handler
    return_value = func（* args，** kwargs）
  在start_app文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ app \ start.py”，第120行
    window = run_app（splash）
  在run_app中的第63行文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ app \ start.py”
    window = MainWindow（splash = splash）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ widgets \ main_window.py”，行163，在__init__中
    self.api = AnacondaAPI（）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ api \ anaconda_api.py”，行2004，在AnacondaAPI
    ANACONDA_API = _AnacondaAPI（）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ api \ anaconda_api.py”，第89行，在__init__中
    self._client_api = ClientAPI（）
  在ClientAPI中的第612行文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ api \ client_api.py”
    CLIENT_API = _ClientAPI（）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ anaconda_navigator \ api \ client_api.py”，第82行，在__init__中
    LOG_LEVEL = logging.NOTSET
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ binstar_client \ utils \ config.py”，行96，在get_server_api
    config = get_config（remote_site = site）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ binstar_client \ utils \ config.py”，第229行，在get_config
    file_configs = load_file_configs（SEARCH_PATH）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ binstar_client \ utils \ config.py”，第223行，在load_file_configs中
    raw_data = collections.OrderedDict（kv在itertools.chain.from_iterable（load_paths）中为kv）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ binstar_client \ utils \ config.py”，第223行，在 
    raw_data = collections.OrderedDict（kv在itertools.chain.from_iterable（load_paths）中为kv）
  在_dir_yaml_loader文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ binstar_client \ utils \ config.py”中，第203行
    产量文件路径，load_config（文件路径）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ binstar_client \ utils \ config.py”，第187行，在load_config
    data = yaml_load（fd）
  在yaml_load文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ binstar_client \ utils \ yaml.py”第9行
    返回safe_load（流）
  第94行，在safe_load中的文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ __ init__.py”
    返回负载（流，SafeLoader）
  第72行中的文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ __ init__.py”
    返回loader.get_single_data（）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ constructor.py”，第37行，在get_single_data
    返回self.construct_document（节点）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ constructor.py”，第46行，位于construct_document
    对于发电机中的虚设：
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ constructor.py”，第398行，位于construct_yaml_map
    value = self.construct_mapping（节点）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ constructor.py”，行204，位于construct_mapping
    return super（）。construct_mapping（node，deep = deep）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ constructor.py”，行125，位于construct_mapping
    key = self.construct_object（key_node，deep = deep）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ constructor.py”，第86行，位于construct_object
    data =构造函数（self，node）
  文件“E：\ InstallSofarew \ Anaconda3 \ lib \ site-packages \ yaml \ constructor.py”，第414行，位于construct_undefined
    node.start_mark）
yaml.constructor.ConstructorError：无法确定标记“tag：yaml.org，2002：python / unicode'的构造函数
  在“C：\ Users \ Firefly \ AppData \ Local \ ContinuumIO \ binstar \ config.yaml”第1行第1列

**Comment by goanpeca** [comment]
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.11
```
