### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jrpardee** [ContinuumIO/anaconda-issues#876]
The following errors occured:

RuntimeError:
Could not find anaconda.org user anaconda-server

{'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'qt': '4.8.7', 'python': '3.5.1', 'platform': 'osx-64', 'conda': '4.1.4', 'pyqt': '4.11.4', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
