### ISSUE TITLE
Invocation of python3.6 via ld-2.17.so segfaults

### ISSUE THREAD

**Issue by ericmjonas** [ContinuumIO/anaconda-issues#8773]
**Why this matters:** I am the project lead on PyWren, where we try and run arbitrary python code on lambda -- I [spoke on the project at Anacondacon last year](https://www.youtube.com/watch?v=OskQytBBdJU) . To get around some limitations in the lambda runtime environment, we have been exploring hacking the dynamic linker, `ld.so`. Thus we would like to run the anaconda python binary under our custom, modified `ld.so`. But sadly, we can't seem to run the latest py36 via ld.so. This also appears to be specific to py36, the py34 shipped by anaconda doesn't have this problem (again, see below). 

I want to stress that the problem below occurs with a **vanilla, shipped `ld.so`** -- we have made no modifications to the code. 

### Actual Behavior
I download the latest miniconda3 inside of a clean docker container using image `lambci/lambda:build` which is a replica of the AWS Lambda runtime environment. I install to `/root/miniconda3` accepting all the defaults. 

When I invoke python normally, everything works just fine:
```
bash-4.2# /root/miniconda3/bin/python -V     
Python 3.6.4 :: Anaconda, Inc.
```

But when I invoke explicitly via the dynamic linker, it segfaults:
```
bash-4.2# /lib64/ld-2.17.so /root/miniconda3/bin/python -V  
Segmentation fault (core dumped)
```

Note if I create a python3.4 environment:
```
bash-4.2# /root/miniconda3/bin/conda create -n test34 python=3.4
```
I get the correct expected behavior:

```
bash-4.2# /lib64/ld-2.17.so /root/miniconda3/envs/test34/bin/python -V
Python 3.4.5 :: Continuum Analytics, Inc.
```

One hint might be obtained by looking at the output of ldd:
```
bash-4.2# ldd /root/miniconda3/envs/test34/bin/python
        linux-vdso.so.1 =>  (0x00007ffeea5e3000)
        libpython3.4m.so.1.0 => /root/miniconda3/envs/test34/bin/../lib/libpython3.4m.so.1.0 (0x00007f0e50057000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0e4fe3b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0e4fc37000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f0e4fa34000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f0e4f732000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0e4f36e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0e50503000)
```
vs 
```
bash-4.2# ldd /root/miniconda3/bin/python
        linux-vdso.so.1 =>  (0x00007ffde6563000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb22093f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb22057b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb220377000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fb220174000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb21ff6c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb21fc6a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb2210b0000)
```

for python3.6. 

### Expected Behavior

The dynamic linker is supposed to be able to directly run binaries like this; indeed the anaconda python3.6 is the only binary I have found which exhibits this behavior. When I have tried building my own python package using the anaconda python36 recipe, it does not exhibit this behavior. 

### Steps to Reproduce

1. instal latest miniconda into docker container running image `lambci/lambda:build`
2. execute commands as above

**Comment by mingwandroid** [comment]
> I want to stress that the problem below occurs with a vanilla, shipped ld.so -- we have made no modifications to the code.

Did you compile this ld.so yourself? Can you make it available somewhere?

**Comment by ericmjonas** [comment]
No this is with the default (compiled)  `ld-2.17.so` that ships with 
the public docker image`lambci/lambci:build`. You should simply be able to run that image as above and see this behavior.

**Comment by mingwandroid** [comment]
I'm not sure about this one. I spent a bit of time on it and found the following difference between normal execution (`LD_LIBRARY_PATH=/lib64:/usr/lib64 LD_DEBUG=symbols /opt/conda/bin/python`):
```
        97:	symbol=seteuid;  lookup in file=/opt/conda/bin/python [0]
        97:	symbol=seteuid;  lookup in file=/lib64/libpthread.so.0 [0]
        97:	symbol=seteuid;  lookup in file=/lib64/libc.so.6 [0]
        97:	symbol=stdout;  lookup in file=/lib64/libpthread.so.0 [0]
        97:	symbol=stdout;  lookup in file=/lib64/libc.so.6 [0]
        97:	symbol=stdin;  lookup in file=/lib64/libpthread.so.0 [0]
        97:	symbol=stdin;  lookup in file=/lib64/libc.so.6 [0]
        97:	symbol=__environ;  lookup in file=/lib64/libpthread.so.0 [0]
        97:	symbol=__environ;  lookup in file=/lib64/libc.so.6 [0]
        97:	symbol=stderr;  lookup in file=/lib64/libpthread.so.0 [0]
        97:	symbol=stderr;  lookup in file=/lib64/libc.so.6 [0]
        97:	symbol=__libc_enable_secure;  lookup in file=/opt/conda/bin/python [0]
```

.. and executing it this way (`LD_LIBRARY_PATH=/lib64:/usr/lib64 LD_DEBUG=symbols /lib64/ld-linux-x86-64.so.2 /opt/conda/bin/python`):

```
..
        98:	symbol=seteuid;  lookup in file=/opt/conda/bin/python [0]
        98:	symbol=seteuid;  lookup in file=/lib64/libpthread.so.0 [0]
        98:	symbol=seteuid;  lookup in file=/lib64/libc.so.6 [0]
        98:	symbol=stdout;  lookup in file=/opt/conda/bin/python [0]
        98:	symbol=stdin;  lookup in file=/opt/conda/bin/python [0]
        98:	symbol=__environ;  lookup in file=/opt/conda/bin/python [0]
        98:	symbol=stderr;  lookup in file=/opt/conda/bin/python [0]
        98:	symbol=__libc_enable_secure;  lookup in file=/opt/conda/bin/python [0]
        98:	symbol=__libc_enable_secure;  lookup in file=/lib64/libpthread.so.0 [0]
```

`nm -g /opt/conda/bin/python` shows that these symbols (`stdout`, `stdin`, `__environ`, `stderr`) are present in `/opt/conda/bin/python`.

The fact we don't link dynamically to `libpython*.so* ` is down to the fact that we link the interpreter statically for speed reasons. I guess having/not having an extra level of shared libraries to hop through may cause the symbol resolution to differ between 3.4 and 3.6.

This thread seems useful but I don't have time to fully digest it: https://ghc.haskell.org/trac/ghc/ticket/8935

**Comment by mingwandroid** [comment]
I tested this on a range of different docker images. The results are:
ubuntu 17.10: no segfault (glibc 2.26)
ubuntu 16.04: no segfault (glibc 2.23)
ubuntu 14.04: segfault (glibc 2.19)
centos 7: segfault (glibc 2.17)

.. so it *seems* like it could be a bug in glibc that was fixed between versions 2.19 and glibc 2.23 (yeah this is a big range, help tracking it down further would be appreciated).

**Comment by mingwandroid** [comment]
I looked through all the bugs fixed at https://abi-laboratory.pro/tracker/changelog/glibc/2.20/log.html and couldn't find anything that sounds exactly like this. The only ones any way related (though some were for different architectures) were:

https://sourceware.org/bugzilla/show_bug.cgi?id=16613
https://sourceware.org/bugzilla/show_bug.cgi?id=16634
https://sourceware.org/bugzilla/show_bug.cgi?id=16796
https://sourceware.org/bugzilla/show_bug.cgi?id=16912
https://sourceware.org/bugzilla/show_bug.cgi?id=17153
https://sourceware.org/bugzilla/show_bug.cgi?id=17319

Of course RedHat patch glibc in very significant ways so just looking at upstream bugs fixed is far from the full story.

**Comment by ericmjonas** [comment]
First, thank you so much for all of this work, it is incredible! This is fascinating; do you know if there's any easy way to tell what host libraries other than libc an anaconda python distribution depends on ? what assumptions does the team make about the surrounding linux environment? I could compile a custom glibc and run everything inside of that environment, but things might become problematic quickly if there are a lot of other host library dependencies.

**Comment by mingwandroid** [comment]
For host libraries (or system libraries as we call them) we have made everything explicit so that nothing gets left to chance.

We use pseudo cross-compilers - they don't target a different machine, but they do use a sysroot -
 along with what we call Core Dependency Tree packages. These packages are RedHat CentOS6 RPMs unpacked and repacked in that compiler sysroot. Then [our recipes list the ones that they depend upon](https://github.com/AnacondaRecipes/tk-feedstock/blob/master/recipe/meta.yaml#L26-L29) (this makes it explicit). Finally conda-build detects when any other non-CDT system libraries have crept in to the build DSOs and raises an error (this last part is very new though and hasn't been used in many of the packages on repo.continuum.io yet).

You can see the full set of RPMs we use by looking for directories containing `cos6` in this git repo: https://github.com/AnacondaRecipes/aggregate

**Comment by nehaljwani** [comment]
I ran a git bisect on glibc between 2.19 and 2.20 and found the commit which fixed the issue. From the commit message, I got the bugzilla ID: https://sourceware.org/bugzilla/show_bug.cgi?id=16381

**Comment by nehaljwani** [comment]
To test this against custom built glibc, I did:
```
git clone git://sourceware.org/git/glibc.git; cd $_
git checkout <sha>
mkdir build; cd $_
./configure --disable-sanity-checks
make -jX
sed -i 's/math:/math:"${builddir}"\/login:/' testrun.sh # Because our python needs libutil.so.1
./testrun.sh /path/to/miniconda/installation/bin/python -V
```

**Comment by mingwandroid** [comment]
Thank you very much @nehaljwani!

**Comment by mingwandroid** [comment]
The [patch](https://cygwin.com/ml/libc-alpha/2014-01/txtfArH0tB7kp.txt
) is addressing a different problem and fixes this bug as a side effect only!

**Comment by ericmjonas** [comment]
Wow, this is a fantastic find, thank you so much @nehaljwani and @mingwandroid . I've patched my ld.so and it all works! I'm closing this bug, thank you again so much for all your help.

**Comment by mingwandroid** [comment]
@csoja it may be worth adding this info to our FAQ? Though it's unlikely to be frequently asked to be honest.
