### ISSUE TITLE
Cmake can't find OpenGL when anaconda's new compiler is used on Ubuntu

### ISSUE THREAD

**Issue by shadowwalkersb** [ContinuumIO/anaconda-issues#8779]
### Actual Behavior

When anaconda's new compilers are used, cmake can't find OpenGL on Ubuntu.

### Expected Behavior

I expect regardless of the compiler used, cmake should find OpenGL. 

### Steps to Reproduce
1. In a minimal cmake project use findOpenGL() in CMakeLists and conda-build, https://github.com/shadowwalkersb/foo/tree/a8058f28580087f3aee93a3470b14cc4c561bf5c.

Output:
```
cmake /home/ubuntu/miniconda/conda-bld/foo_1520290978333/work
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/miniconda/conda-bld/foo_1520290978333/build
```
Full log: https://circleci.com/gh/shadowwalkersb/foo/16

2. Add compiler via jinja function.
```
requirements:
    build:
        - cmake
        - {{ compiler('cxx') }}
```
Output:
```
cmake /home/ubuntu/miniconda/conda-bld/foo_1520290994901/work
-- The CXX compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /home/ubuntu/miniconda/conda-bld/foo_1520290994901/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: /home/ubuntu/miniconda/conda-bld/foo_1520290994901/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /home/ubuntu/miniconda/conda-bld/foo_1520290994901/_build_env/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY)
Call Stack (most recent call first):
  /home/ubuntu/miniconda/conda-bld/foo_1520290994901/_build_env/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /home/ubuntu/miniconda/conda-bld/foo_1520290994901/_build_env/share/cmake-3.9/Modules/FindOpenGL.cmake:170 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:6 (find_package)
```
Full log: https://circleci.com/gh/shadowwalkersb/foo/17

##### Anaconda or Miniconda version:
Miniconda2-4.4.10-Linux-x86_64.sh

##### Operating System:
The default image on CircleCI, Ubuntu 14.04 (Trusty).

##### `conda info`

```

     active environment : None
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 4.4.11
    conda-build version : 3.7.0
         python version : 2.7.14.final.0
       base environment : /home/ubuntu/miniconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/ubuntu/miniconda/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/miniconda/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/2.7.14 Linux/3.13.0-142-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

##### `conda list --show-channel-urls`

```

```

**Comment by mingwandroid** [comment]
> I expect regardless of the compiler used, cmake should find OpenGL.

We explicitly do not want this. cmake finding some random system libraries is something we try hard to avoid because it *will* lead to packages that only work on your own system (or other systems with a binary compatible version of that same library). We use CDT packages instead. These are repackaged RPMs from CentOS6 where the files (libraries and headers and anything else, .pc files in particular) live in the new compiler's sysroot directory.

To see how to use CDT packages (and a large list of ones needed to link to a library that uses both OpenGL *and* X11) you can refer to https://github.com/AnacondaRecipes/r-rgl-feedstock/blob/master/recipe/meta.yaml#L48-L67

If you want to let your build system leak into your conda package build then you need to take deliberate efforts to add /usr/include and /usr/lib to your compilation flags and probably also mess about with pkg-config.

**Comment by mingwandroid** [comment]
I recommend that you use your system compilers when you want to use your system libraries.

**Comment by shadowwalkersb** [comment]
That recipe is very helpful! Looked around for documentation for quite some time. Would definitely appreciate docs about `cdt()`, `{{native}}`, `{{posix}}`. Any other hidden gems like these? Also, any examples using cmake with cdt packages? Can't seem to make cmake find OpenGL after adding the `cdt()` entries copied from your example recipe.

**Comment by shadowwalkersb** [comment]
Bottom line, if I use the new compilers cmake can't find OpenGL (system or CDT package) and my build system breaks. Currently, only practical workaround I can come up with is to unset environment variables set by compilers, more precisely, unsetting `CXX` and `CXXFLAGS` seems to do the trick. Setting `CMAKE_PREFIX_PATH` or similar might help, too, but the path should look something like `$ENV{CONDA_PREFIX}/$ENV{HOST}/sysroot/usr/lib64` which is not pretty. I can't find any example usages or helpful documentation. So, any suggestions are appreciated.

**Comment by mingwandroid** [comment]
We are 'documentation-lite' around CDT packages. I'll have a go at getting your recipe to work, hopefully before the weekend.

**Comment by mingwandroid** [comment]
`{{native}}` and `{{posix}}` are MSYS2-isms, they simply expand to `m2w64-` and `m2-` respectively. The former are pure-Windows software and the latter are Cygwin-derived posix-y software so are not related to this stuff at all (CDTs are a linux-only thing).

**Comment by shadowwalkersb** [comment]
Something that I found and might be helpful, if not already known. OP specifically mentions Ubuntu, because OpenGL library is under `/usr/lib/x86_64-linux-gnu/` on Ubuntu, but under `/usr/lib` or a similar more standard directory on CentOS. So, cmake always finds OpenGL on CentOS. But, it is the system OpenGL it finds, so cmake can't find OpenGL in the new compiler's sysroot on Ubuntu or CentOS. When system compiler is used, cmake seems to set up a variable, `CMAKE_LIBRARY_ARCHITECTURE` (https://cmake.org/cmake/help/v3.4/variable/CMAKE_LIBRARY_ARCHITECTURE.html) which is used for finding packages (https://cmake.org/cmake/help/v3.0/command/find_package.html?highlight=find_package).

> Paths with lib/<arch> are enabled if the CMAKE_LIBRARY_ARCHITECTURE variable is set.

On Ubuntu that variable seems to be set to `x86_64-linux-gnu` which explains how OpenGL is found in a non-standard location. I guess, cmake gets that from the compiler and when the new compilers are used that variable is empty. I couldn't dig any further, but I think the new compilers will need to provide that when cmake probes, whatever the mechanism is.

**Comment by nehaljwani** [comment]
To make cmake look at the CDT package for openGL, I had to specify some settings in a toolchain file and specify it to cmake. An example for this is:
https://github.com/AnacondaRecipes/freeglut-feedstock

The contents of the cross-linux.cmake file have been copied from the [libnetcdf-feedstock](https://github.com/AnacondaRecipes/libnetcdf-feedstock) .

Credits @mingwandroid

**Comment by mingwandroid** [comment]
I'm thinking about making docs or other resources detailing  how to use our compilers with system libraries using CDT packages(CentOS6 level specifically).

It's a bit of a hassle I admit but these compilers are for building conda packages and controlling our compatibility carefully is a crucial consideration.

Having said that, I think they *are* useful for any C or C++ software developer who wants to use modern language, security and optimisation features and still be able to run the built software on old OSes.

**Comment by shadowwalkersb** [comment]
Contrary to, the maybe misleading OP, I do want to use the new compilers and upgrade our C++ code to use C++17, at least C++11. That's why I am interested in getting the new compilers to work for us. Besides OpenGL I am facing issues with undefined symbols with other packages which I will try to narrow down, report here and ask for help. But, regarding OpenGL, I will try out the toolchain file @nehaljwani suggested. It looks like all the missing pieces are in there, but having invested some time in digging up some cmake stuff, I think there shouldn't be a need for such a file. There must be something in how the new compilers are built that can help cmake find sysroot as mentioned in https://github.com/ContinuumIO/anaconda-issues/issues/8779#issuecomment-372044842. I just hoped someone here would, already, have a better idea than me. I will try to dig a little more if I can.

**Comment by mingwandroid** [comment]
If you knew the intimate details of the `CMake` codebase and how it works you wouldn't be surprised that we need to use a toolchain file here.

In this case, `CMake` pays lip service to being able to manage `sysroots` but it gets it badly wrong. If you really care I can dig out a few issues about how it handles sysroots. I have an idea about how to fix the one that causes us to need a toolchain file but I don't have time to fix it just yet.

If you want more details email me to ask about them as I don't want to be too harsh to a useful open source project in public.

**Comment by mingwandroid** [comment]
Also, I do not believe that a toolchain file is that bad a workaround which is why I've de-prioritized fixing CMake's sysroot management.

**Comment by shadowwalkersb** [comment]
Fair enough. Your last responses is what I was trying to get a feel of, I guess. If what is needed is fixing CMake's sysroot management, I have no intention of investing any time on it, nor I expect anyone else to do it, especially, if there is a workaround. So, I'll go with the toolchain file. @mingwandroid and @nehaljwani  , thanks for the explanations and the toolchain file.

> I'm thinking about making docs or other resources detailing how to use our compilers with system libraries using CDT packages(CentOS6 level specifically).

👍 I think , even the slightest, documentation would be great help for the community.

**Comment by BlackHC** [comment]
On Ubuntu, passing: `-D CMAKE_LIBRARY_ARCHITECTURE=x86_64-linux-gnu` to CMake has indeed fixed the issue for me.

My use-case is rather particular as I use conda to create a manual build environment for non-python projects.
