### ISSUE TITLE
h5py bug in Anaconda 1.9.0

### ISSUE THREAD

**Issue by MechEng78** [ContinuumIO/anaconda-issues#88]
h5py errors observed during IPython Notebook session.

![image](https://f.cloud.github.com/assets/6686699/2176470/9995d11e-95d4-11e3-9e0f-ef48b8563bd6.png)

![image](https://f.cloud.github.com/assets/6686699/2176474/b48e1f4e-95d4-11e3-9c69-eedf5604a087.png)

**Comment by caryan** [comment]
This appears to be fixed as of Anaconda 2.1

**Comment by ilanschnell** [comment]
Great.  Closing issue.
