### ISSUE TITLE
An unexpected error occurred on Navigator start-up. Main Error  'root_prefix'. Screenshot is uploaded.

### ISSUE THREAD

**Issue by prakshh** [ContinuumIO/anaconda-issues#8816]
![screenshot from 2018-03-09 23-34-01](https://user-images.githubusercontent.com/20643687/37207708-3590afae-23c4-11e8-833a-73a721ce0556.png)

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@prakshh could you open the terminal and provide the output of

```
conda info
```

and

```
conda list
```

**Comment by duncankmckinnon** [comment]
I had the same problem.

**Comment by goanpeca** [comment]
Stale issue, closing
