### ISSUE TITLE
Navigator auto-update gets stuck, possibly due to Anaconda "installed for everyone"

### ISSUE THREAD

**Issue by hilarysr** [ContinuumIO/anaconda-issues#8826]
cc: @ijstokes 

### Actual Behavior

This is on Windows 10 Pro.

I start Navigator and I'm told there is a 1.7.0 update available and asked if I would like to update from 1.6.9.  I say "yes".  Stuff happens.  Update appears to be complete.  I restart Navigator.  I get exactly the same message again, so apparently update didn't happen, or at least didn't happen correctly.  I say "yes" again. This time nothing appears to happen, at least not for 30 minutes.  Just a message "updating packages on "root". (see screenshot below)  I try to start Navigator again, thinking this may complete in the background.  I'm told Navigator is already running (I guess doing the update), so I resort to the Anaconda command line prompt to do what I want to do (install Sphinx).  I do `conda install sphinx`, I'm given a package plan, I say "yes" (do it!), packages download, then I get an error message that indicates the packages can't be installed.  I recall that I probably installed Anaconda "for all users".  I'm surprised that conda didn't notice that it wasn't going to be able to write anything to the current environment before it went to figure out a package plan for the current environment.  But that is an aside.  However I then realize that this is probably why the Navigator auto-update process is borked: My user can't update Navigator.  I'm not sure why it even tried, and I'm not sure what is going to happen when I abort the currently stuck second attempt to update.  But since it is all read-only to my user I'm probably OK, other than some surplus packages in my local user package cache (speculation!).

![capture](https://user-images.githubusercontent.com/32888144/37246931-853d40a0-2480-11e8-872b-9409e84df4d8.PNG)

### Expected Behavior

Navigator should not attempt to auto-update if the current user doesn't have write permissions to the conda environment where Navigator is running from.

Navigator's auto-update should have a time out.  Something must be missing for it to be spinning with the above screen for 30+ minutes.

### Steps to Reproduce

Install Anaconda 5.0.1 "for all users"

Start Navigator from the Start menu as a regular user

Agree to the Navigator update.

##### Operating System:

Windows 10

##### `conda info`

I have since run `conda install sphinx` with an Administrator CLI session, and that triggered a conda update

```
conda info

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\ijsto\.condarc
 populated config files :
          conda version : 4.4.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\ijsto\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\ijsto\AppData\Local\conda\conda\envs
                          C:\Users\ijsto\.conda\envs
               platform : win-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False
```
##### `conda list --show-channel-urls`

```
>conda list --show-channel-urls
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0    defaults
alabaster                 0.7.10           py36hcd07829_0    defaults
anaconda                  custom           py36h363777c_0    defaults
anaconda-client           1.6.5            py36hd36550c_0    defaults
anaconda-navigator        1.6.9            py36hc720852_0    defaults
anaconda-project          0.8.0            py36h8b3bf89_0    defaults
asn1crypto                0.22.0           py36h8e79faa_1    defaults
astroid                   1.5.3            py36h9d85297_0    defaults
astropy                   2.0.2            py36h06391c4_4    defaults
babel                     2.5.0            py36h35444c1_0    defaults
backports                 1.0              py36h81696a8_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2    defaults
beautifulsoup4            4.6.0            py36hd4cc5e8_1    defaults
bitarray                  0.8.1            py36h6af124b_0    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blaze                     0.11.3           py36h8a29ca5_0    defaults
bleach                    2.0.0            py36h0a7e3d6_0    defaults
bokeh                     0.12.10          py36h0be3b39_0    defaults
boto                      2.48.0           py36h1a776d2_1    defaults
bottleneck                1.2.1            py36hd119dfa_0    defaults
bzip2                     1.0.6            vc14hdec8e7a_1  [vc14]  defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cachecontrol              0.12.3           py36hfe50d7b_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.10.0           py36hae3d1b5_1    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
click                     6.7              py36hec8c647_0    defaults
cloudpickle               0.4.0            py36h639d8dc_0    defaults
clyent                    1.2.2            py36hb10d595_1    defaults
colorama                  0.3.9            py36h029ae33_0    defaults
comtypes                  1.1.2            py36heb9b3d1_0    defaults
conda                     4.4.11                   py36_0    defaults
conda-build               3.0.27           py36h309a530_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h065de53_0    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
cryptography              2.0.3            py36h123decb_1    defaults
curl                      7.55.1           vc14hdaba4a4_3  [vc14]  defaults
cycler                    0.10.0           py36h009560c_0    defaults
cython                    0.26.1           py36h18049ac_0    defaults
cytoolz                   0.8.2            py36h547e66e_0    defaults
dask                      0.15.3           py36h396fcb9_0    defaults
dask-core                 0.15.3           py36hd651449_0    defaults
datashape                 0.5.4            py36h5770b85_0    defaults
decorator                 4.1.2            py36he63a57b_0    defaults
distlib                   0.2.5            py36h51371be_0    defaults
distributed               1.19.1           py36h8504682_0    defaults
docutils                  0.14             py36h6012d8f_0    defaults
entrypoints               0.2.3            py36hfd66bb0_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
fastcache                 1.0.2            py36hffdae1b_0    defaults
filelock                  2.0.12           py36hd7ddd41_0    defaults
flask                     0.12.2           py36h98b5e8f_0    defaults
flask-cors                3.0.3            py36h8a3855d_0    defaults
freetype                  2.8              vc14h17c9bdf_0  [vc14]  defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2            py36h342a76c_0    defaults
glob2                     0.5              py36h11cc1bd_1    defaults
greenlet                  0.4.12           py36ha00ad21_0    defaults
h5py                      2.7.0            py36hfbe0a52_1    defaults
hdf5                      1.10.1           vc14hb361328_0  [vc14]  defaults
heapdict                  1.0.0            py36h21fa5f4_0    defaults
html5lib                  0.999999999      py36ha09b1f3_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2             vc14hc45fdbb_0  [vc14]  defaults
idna                      2.6              py36h148d497_1    defaults
imageio                   2.2.0            py36had6c2d2_0    defaults
imagesize                 0.7.1            py36he29f638_0    defaults
intel-openmp              2018.0.0             hcd89f80_7    defaults
ipykernel                 4.6.1            py36hbb77b34_0    defaults
ipython                   6.1.0            py36h236ecc8_1    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
ipywidgets                7.0.0            py36h2e74ada_0    defaults
isort                     4.2.15           py36h6198cc5_0    defaults
itsdangerous              0.24             py36hb6c5a24_1    defaults
jdcal                     1.3              py36h64a5255_0    defaults
jedi                      0.10.2           py36hed927a0_0    defaults
jinja2                    2.9.6            py36h10aa3a0_1    defaults
jpeg                      9b               vc14h4d7706e_1  [vc14]  defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter                   1.0.0            py36h422fd7e_2    defaults
jupyter_client            5.1.0            py36h9902a9a_0    defaults
jupyter_console           5.2.0            py36h6d89b47_1    defaults
jupyter_core              4.3.0            py36h511e818_0    defaults
jupyterlab                0.27.0           py36h34cc53b_2    defaults
jupyterlab_launcher       0.4.0            py36h22c3ccf_0    defaults
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults
libiconv                  1.15             vc14h29686d3_5  [vc14]  defaults
libpng                    1.6.32           vc14h5163883_3  [vc14]  defaults
libssh2                   1.8.0            vc14hcf584a9_2  [vc14]  defaults
libtiff                   4.0.8           vc14h04e2a1e_10  [vc14]  defaults
libxml2                   2.9.4            vc14h8fd0f11_5  [vc14]  defaults
libxslt                   1.1.29           vc14hf85b8d4_5  [vc14]  defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lockfile                  0.12.2           py36h0468280_0    defaults
lxml                      4.1.0            py36h0dcd83c_0    defaults
lzo                       2.10             vc14h0a64fa6_1  [vc14]  defaults
markupsafe                1.0              py36h0e26971_1    defaults
matplotlib                2.1.0            py36h11b4b9c_0    defaults
mccabe                    0.6.1            py36hb41005a_1    defaults
menuinst                  1.4.10           py36h42196fb_0    defaults
mistune                   0.7.4            py36h4874169_0    defaults
mkl                       2018.0.0             h36b65af_4    defaults
mkl-service               1.1.2            py36h57e144c_4    defaults
mpmath                    0.19             py36he326802_2    defaults
msgpack-python            0.4.8            py36h58b1e9d_0    defaults
multipledispatch          0.4.9            py36he44c36e_0    defaults
navigator-updater         0.1.0            py36h8a7b86b_0    defaults
nbconvert                 5.3.1            py36h8dc0fde_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
networkx                  2.0              py36hff991e3_0    defaults
nltk                      3.2.4            py36hd0e0a39_0    defaults
nose                      1.3.7            py36h1c3779e_2    defaults
notebook                  5.0.0            py36hd9fbf6f_2    defaults
numba                     0.35.0             np113py36_10    defaults
numexpr                   2.6.2            py36h7ca04dc_1    defaults
numpy                     1.13.3           py36ha320f96_0    defaults
numpydoc                  0.7.0            py36ha25429e_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.44             py36h0a7bdd2_0    defaults
openpyxl                  2.4.8            py36hf3b77f6_1    defaults
openssl                   1.0.2n               h74b6da3_0    defaults
packaging                 16.8             py36ha0986f6_1    defaults
pandas                    0.20.3           py36hce827b7_2    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py36h3ef6317_1    defaults
partd                     0.3.8            py36hc8e763b_0    defaults
path.py                   10.3.1           py36h3dd8b46_0    defaults
pathlib2                  2.3.0            py36h7bfb78b_0    defaults
patsy                     0.4.1            py36h42cefec_0    defaults
pep8                      1.7.0            py36h0f3d67a_0    defaults
pickleshare               0.7.4            py36h9de030f_0    defaults
pillow                    4.2.1            py36hdb25ab2_0    defaults
pip                       9.0.1            py36hadba87b_3    defaults
pkginfo                   1.4.1            py36hb0f9cfa_1    defaults
ply                       3.10             py36h1211beb_0    defaults
progress                  1.3              py36hbeca8d3_0    defaults
prompt_toolkit            1.0.15           py36h60b8f86_0    defaults
psutil                    5.4.0            py36h4e662fb_0    defaults
py                        1.4.34           py36ha4aca3a_1    defaults
pycodestyle               2.3.1            py36h7cc55cd_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pycrypto                  2.6.1            py36he68e6e2_1    defaults
pycurl                    7.43.0           py36h086bf4c_3    defaults
pyflakes                  1.6.0            py36h0b975d6_0    defaults
pygments                  2.2.0            py36hb010967_0    defaults
pylint                    1.7.4            py36ha4e6ded_0    defaults
pyodbc                    4.0.17           py36h0006bc2_0    defaults
pyopenssl                 17.2.0           py36h15ca2fc_0    defaults
pyparsing                 2.2.0            py36h785a196_1    defaults
pyqt                      5.6.0            py36hb5ed885_5    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
pytables                  3.4.2            py36h71138e3_2    defaults
pytest                    3.2.1            py36h753b05e_1    defaults
python                    3.6.3                h9e2ca53_1    defaults
python-dateutil           2.6.1            py36h509ddcb_1    defaults
pytz                      2017.2           py36h05d413f_1    defaults
pywavelets                0.5.2            py36hc649158_0    defaults
pywin32                   221              py36h9c10281_0    defaults
pyyaml                    3.12             py36h1d1928f_1    defaults
pyzmq                     16.0.2           py36h38c27d9_2    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtawesome                 0.4.4            py36h5aa48f6_0    defaults
qtconsole                 4.3.1            py36h99a29a9_0    defaults
qtpy                      1.3.1            py36hb8717c5_0    defaults
requests                  2.18.4           py36h4371aae_1    defaults
rope                      0.10.5           py36hcaf5641_0    defaults
ruamel_yaml               0.11.14          py36h9b16331_2    defaults
scikit-image              0.13.0           py36h6dffa3f_1    defaults
scikit-learn              0.19.1           py36h53aea1b_0    defaults
scipy                     0.19.1           py36h7565378_3    defaults
seaborn                   0.8.0            py36h62cb67c_0    defaults
setuptools                36.5.0           py36h65f9e6e_0    defaults
simplegeneric             0.8.1            py36heab741f_0    defaults
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.18.1           py36h9c25514_2    defaults
six                       1.11.0           py36h4db2310_1    defaults
snowballstemmer           1.2.1            py36h763602f_0    defaults
sortedcollections         0.5.3            py36hbefa0ab_0    defaults
sortedcontainers          1.5.7            py36ha90ac20_0    defaults
sphinx                    1.7.1                    py36_0    defaults
sphinxcontrib             1.0              py36hbbac3d2_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1    defaults
spyder                    3.2.4            py36h8845eaa_0    defaults
sqlalchemy                1.1.13           py36h5948d12_0    defaults
sqlite                    3.20.1           vc14h7ce8c62_1  [vc14]  defaults
statsmodels               0.8.0            py36h6189b4c_0    defaults
sympy                     1.1.1            py36h96708e0_0    defaults
tblib                     1.3.2            py36h30f5020_0    defaults
testpath                  0.3.1            py36h2698cfe_0    defaults
tk                        8.6.7            vc14hb68737d_1  [vc14]  defaults
toolz                     0.8.2            py36he152a52_0    defaults
tornado                   4.5.2            py36h57f6048_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
typing                    3.6.2            py36hb035bda_0    defaults
unicodecsv                0.14.1           py36h6450c06_0    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_2    defaults
vs2015_runtime            14.0.25123           hd4c4e62_2    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
werkzeug                  0.12.2           py36h866a736_0    defaults
wheel                     0.29.0           py36h6ce6cde_1    defaults
widgetsnbextension        3.0.2            py36h364476f_1    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
wrapt                     1.10.11          py36he5f5981_0    defaults
xlrd                      1.1.0            py36h1cb58dc_1    defaults
xlsxwriter                1.0.2            py36hf723b7d_0    defaults
xlwings                   0.11.4           py36hd3cf94d_0    defaults
xlwt                      1.3.0            py36h1a4751e_0    defaults
yaml                      0.1.7            vc14hb31d195_1  [vc14]  defaults
zict                      0.1.3            py36h2d8e73e_0    defaults
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  defaults
```

**Comment by goanpeca** [comment]
@hilarysr 

Regarding this

>possibly due to Anaconda "installed for everyone"

Yes, unless you open Navigator with Admin privileges, auto update will not work :-|

**Comment by ijstokes** [comment]
It seems like it either be good to stop Auto update from even attempting to run under these circumstances if we know that it is going to fail

**Comment by Peter-Griffin-ah** [comment]
Encountered the same issue updating from 1.7.0 to 1.8.1 and 1.8.2.  Running as administrator resolved the issue.

Auto detection and requesting to raise privileges is the standard for the vast majority of programs in the Windows environment.  I certainly understand that there may be higher priority bugs, but I would hope that this is eventually supported.

**Comment by mcarballodbpm** [comment]
Updated as admin and It was succesfully

**Comment by juleztb** [comment]
Encountered the same problem in the update from 1.7.0 to 1.8.2.
This is kind of annoying because I would have to call our IT everytime I need administrator rights. Would be better if there was a admin prompt at the beginning of the update instead of it starting and running forever.

**Comment by goanpeca** [comment]
>Would be better if there was a admin prompt at the beginning of the update instead of it starting and running forever.

@juleztb we are working to have this on 1.8.4 to be released in a couple of weeks.

**Comment by krish6874** [comment]
[I 14:14:29.815 LabApp] The port 8888 is already in use, trying another port.
[I 14:14:29.842 LabApp] JupyterLab beta preview extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 14:14:29.842 LabApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
[W 14:14:29.848 LabApp] Error loading server extension jupyterlab
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
proc = Process(cmd, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
self.proc = self._create_process(cwd=cwd, env=env)
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
cmd[0] = which(cmd[0], kwargs.get('env'))
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1454, in init_server_extensions
func(self)
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
info = get_app_info(app_dir)
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
handler = _AppHandler(app_dir, logger)
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[I 14:14:30.035 LabApp] Serving notebooks from local directory: C:\Users\user
[I 14:14:30.035 LabApp] 0 active kernels
[I 14:14:30.035 LabApp] The Jupyter Notebook is running at:
[I 14:14:30.035 LabApp] http://localhost:8889/?token=a6c733f49fdaa01406fc495c85df81ecab61ded2bcfe7612
[I 14:14:30.035 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:14:30.072 LabApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8889/?token=a6c733f49fdaa01406fc495c85df81ecab61ded2bcfe7612
[I 14:14:30.610 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 14:14:30.688 LabApp] 404 GET /lab?token=3fbbf4861dbe338493cc6e59e14eec1d3b8b74182af4342b (::1) 78.00ms referer=None

**Comment by krish6874** [comment]
problem in install mglearn
pip version cannot upgrafe from 9.0.1  to 10.0.1
anaocnda navigator updator 1.7.0 to 1.8.3 takes long

**Comment by begrs** [comment]
As a fellow developer I do not exactly understand why you recommend installing just for the actual user and do not raise privileges for updates.
Here are the pro and con in my perspective:
Pro of using current user instead of admin:
 - avoid some privilege issues like the updating
 - user does not have to be admin
Con:
 - for rare multi-user systems it will get installed more than once
 - potential security issue because a dev environment that is used to to execute raw code can be modified by any application running for the current user - although, I must admit it is hard to proof the criticality of this risk.

**Comment by goanpeca** [comment]
We are working on a fix for this issue to be released on version 1.8.6

**Comment by AbstractMonkey** [comment]
Just chiming in to add that I also encountered this issue.

**Comment by barVybes** [comment]
Same issue.
And its maddening to download a fresh install of Anaconda, get through the install, and then find it came with Nav 1.7.0 instead of whatever the latest version is.  And then run into this update issue.

**Comment by pgrenon** [comment]
I experienced this on a laptop with full admin rights. I struggled for weeks until i found this thread. 

Behaviour: 
Normally, starting the Navigator would trigger update and freeze. However, running as administrator would not offer the option to update at start. 

Resolution: 
I followed option 2 there https://docs.anaconda.com/anaconda/navigator/update-navigator I have no real clue what I did but there was a need to update base conda first. I ended up with 1.8.4 (when 1.8.3 was the version advertised by the auto-update)  -- I suppose this is somehow resolved or about to be resolved, don't know if the below is of any interest. 


```
(base) C:\windows\system32>conda update anaconda-navigator
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.5.2

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - anaconda-navigator


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-navigator-1.8.4   |           py36_0         4.7 MB

The following packages will be UPDATED:

    anaconda-navigator: 1.7.0-py36_0 --> 1.8.4-py36_0

Proceed ([y]/n)?


Downloading and Extracting Packages
anaconda-navigator 1.8.4: ##################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\pythonw.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\pythonw.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\anaconda-navigator-script.py']
- DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\pythonw.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\pythonw.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\anaconda-navigator-script.py']
done

(base) C:\windows\system32>conda update anaconda-navigator
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.5.2

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed.


(base) C:\windows\system32>
(base) C:\windows\system32>
(base) C:\windows\system32>conda update -n base conda
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.2                |           py36_0         1.0 MB

The following packages will be UPDATED:

    conda: 4.4.10-py36_0 --> 4.5.2-py36_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda 4.5.2: ################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\windows\system32>block should really be the equivalent of
'block' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\windows\system32>



```

**Comment by sgrossberndt** [comment]
Same here after just downloading Anaconda. As user I get an update announced from 1.7.0 to 1.8.5 which does not work. As I did not add anaconda to the path I had to open a shell with admin rights and execute conda.bat from its install location

`C:\ProgramData\Anaconda3\Library\bin\conda update -n base conda`
followed by
`C:\ProgramData\Anaconda3\Library\bin\conda update anaconda-navigator`

only then Anaconda 1.8.5 could be installed, just updating anaconda-navigator only updated to 1.8.4

**Comment by goanpeca** [comment]
Version 1.8.7 of Navigator and 0.2.1 of Navigator Updater to be released this week fix this problem.

**Comment by goanpeca** [comment]
Please update to the latest navigator and navigator updater. Open a Terminal or Anaconda Prompt and type

```
conda install anaconda-navigator=1.8.7
conda install navigator-updater=0.2.1
```

**Comment by hebernielsen** [comment]
Here it is August 13 and the problem seems to be there. On Windows 10 Professional, updating from version 1.7 to 1.8.7, it has been running for over 2 hours. Looking in Task Manager there is internet traffic activity in bursts of receiving traffic up to >64Kbps but of course I can't tell what the activity actually is. I am in administrator mode on Windows, so there should be no problem with "privileges". I hadn't opened Anaconda for a few months, when I started it I got the window messages regarding doing the update. I already shut it down after 2 hours this morning and restarted it, so it's not a one-time thing.

**Comment by kenhan168** [comment]
Tried on @goanpeca solution, it works on Windows 10.

Details as follow.

1. Run "Anaconda Prompt" in "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)" with "Run as Administrator" mode

2. within the Anaconda Prompt, run 

conda install anaconda-navigator=1.8.7
conda install navigator-updater=0.2.1

**Comment by MrCabrac** [comment]
You have to open "Anaconda Navigator" as administrator.

**Comment by tdg219** [comment]
Having this same problem going from 1.8.7 to 1.9.2

Tried running navigator as admin to update, and then prompt as an admin and running conda install anaconda-navigator=1.9.2 and neither worked.

Has this been happening to anyone else for the current update?

**Comment by Analytics206** [comment]
> Having this same problem going from 1.8.7 to 1.9.2
> 
> Tried running navigator as admin to update, and then prompt as an admin and running conda install anaconda-navigator=1.9.2 and neither worked.
> 
> Has this been happening to anyone else for the current update?

Yes I have been trying to update from 1.8.7 to 1.9.2 for weeks now. I have tried all the above solutions 10x with no progress.

**Comment by cvmathur** [comment]
I too am struggling to update from 1.8.7 to 1.9.2, none of the above techniques work 👎

**Comment by quickbooksolutions** [comment]
When I run 'as admin' I no longer have the upgrade link for 1.9.2 in the Anaconda navigator, even though I am on 1.7. Only way to see this link is run as user, but then it fails (as stated in this thread).

**Comment by amin145** [comment]
Run Anacoda Navigator as Admin and it works

**Comment by pratikpatodi01** [comment]
Run Anacoda Navigator as Admin and it works

**Comment by sandro-byte32** [comment]
For me running Navigator as Admin doesn`t solve the issue.

**Comment by threepwoody** [comment]
For me neither. Even when running it as admin, it gets stuck at "updating package on root".

**Comment by unitycoder** [comment]
same here, but this seemed to work from cmd.exe prompt (also started anaconda as admin, not sure if required)
`conda update --all`

**Comment by DevGlitch** [comment]
> same here, but this seemed to work from cmd.exe prompt (also started anaconda as admin, not sure if required) `conda update --all`

This wouldn't work as it will only update the packages, not anaconda.


I personally was able to fix this issue using the answer from #11966.

Running `conda install anaconda=custom` in the command line and then after it ran, launching anaconda and updating it. Hope this helps.

**Comment by narenlulla** [comment]
Upgrade navigator from 2.1.1 to 2.1.4 not working tried all suggestions on this and other threads with admin rights and without, startup still prompts upgrade to 2.1.4. 
May have to uninstall and reinstall as the only way around

**Comment by jaybo** [comment]
I had an ancient Anaconda which seemed to be messing things up.  Deleted it, installed latest Anaconda, but still needed:
```
cd %USERPROFILE%
del /s .conda .anaconda .continuum
```

**Comment by Kolonin-Gleb** [comment]
I still struggle with updating Anaconda Navigator in 2024.
Tried different solutions above. 
Infinite installation is still a thing.

**Comment by hyperjeff** [comment]
Can confirm, still a problem.

**Comment by UnderJollyRoger** [comment]
Still a problem. I'm attempting to update from 2.5.0 to 2.6.2.
I'm running as admin, clicked update now and then seemingly it never gets passed this window.
![image](https://github.com/user-attachments/assets/3e3e057c-9b22-40f5-9985-7d689380dc27)

**Comment by juliascopel** [comment]
Still an issue for me trying to update from 2.3.1 to 2.7.0. Tried _conda deactivate_ followed by _conda update anaconda-navigator_ and also _conda update conda_ followed by _conda update --all_ and _conda update anaconda-navigator_. Everytime I got stuck on "updating package on root". I ended up uninstalling Anaconda.
