### ISSUE TITLE
Unicode error when importing Seaborn

### ISSUE THREAD

**Issue by extratoro** [ContinuumIO/anaconda-issues#883]
When importing seaborn (edit: same thing with networkx) in a notebook, I get the following error:

    \Continuum\Anaconda3\lib\site-packages\scipy\__config__.py", line 5
    lapack_opt_info={'include_dirs': ['C:\Users\a181990\AppData\Local\Continuum\Anaconda3\\Library', 'C:\Users\a181990\AppData\Local\Continuum\Anaconda3\\Library\\include', 'C:\Users\a181990\AppData\Local\Continuum\Anaconda3\\Library\\lib'], 'library_dirs': ['C:\Users\a181990\AppData\Local\Continuum\Anaconda3\\Library\\lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'libraries': ['mkl_lapack95_lp64', 'mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']}
                                         ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

It might be related to my config because I cannot reproduce it on another pc.

Current conda install:

    platform : win-64
    conda version : 4.1.6
    conda-env version : 2.5.1
    conda-build version : 1.21.3
    python version : 3.5.2.final.0
    requests version : 2.10.0
    root environment : C:\Users\a181990\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\a181990\AppData\Local\Continuum\Anaconda3
    envs directories : C:\Users\a181990\AppData\Local\Continuum\Anaconda3\envs
    package cache : C:\Users\a181990\AppData\Local\Continuum\Anaconda3\pkgs
    channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

Conda list:
    packages in environment at C:\Users\a181990\AppData\Local\Continuum\Anaconda3:
    
    _license                  1.1                      py35_1  
    alabaster                 0.7.8                    py35_0  
    anaconda-client           1.4.0                    py35_0  
    anaconda                  custom                   py35_0  
    argcomplete               1.0.0                    py35_1  
    astropy                   1.2.1               np111py35_0  
    babel                     2.3.3                    py35_0  
    backports                 1.0                      py35_0  
    beautifulsoup4            4.4.1                    py35_0  
    bitarray                  0.8.1                    py35_1  
    blaze-core                0.9.0                    py35_0  
    bokeh                     0.12.0                   py35_0  
    boto                      2.40.0                   py35_0  
    bottleneck                1.1.0               np111py35_0  
    bzip2                     1.0.6                    vc14_3  [vc14]
    cffi                      1.6.0                    py35_0  
    click                     6.6                      py35_0  
    clyent                    1.2.2                    py35_0  
    colorama                  0.3.7                    py35_0  
    comtypes                  1.1.2                    py35_0  
    conda                     4.1.6                    py35_0  
    conda-build               1.21.3                   py35_0  
    conda-env                 2.5.1                    py35_0  
    configobj                 5.0.6                    py35_0  
    console_shortcut          0.1.1                    py35_1  
    cryptography              1.4                      py35_0  
    curl                      7.49.0                   vc14_0  [vc14]
    cycler                    0.10.0                   py35_0  
    cython                    0.24                     py35_0  
    cytoolz                   0.8.0                    py35_0  
    datashape                 0.5.2                    py35_0  
    decorator                 4.0.10                   py35_0  
    docutils                  0.12                     py35_2  
    dynd-python               0.7.2                    py35_0  
    entrypoints               0.2.2                    py35_0  
    et_xmlfile                1.0.1                    py35_0  
    fastcache                 1.0.2                    py35_1  
    flask                     0.11.1                   py35_0  
    freetype                  2.5.5                    vc14_1  [vc14]
    futures                   3.0.3                    py35_0  
    get_terminal_size         1.0.0                    py35_0  
    greenlet                  0.4.10                   py35_0  
    h5py                      2.6.0               np111py35_0  
    hdf5                      1.8.15.1                 vc14_4  [vc14]
    idna                      2.1                      py35_0  
    imagesize                 0.7.1                    py35_0  
    ipykernel                 4.3.1                    py35_0  
    ipython                   4.2.0                    py35_0  
    ipython-notebook          4.0.4                    py35_3  
    ipython-qtconsole         4.0.1                    py35_4  
    ipython_genutils          0.1.0                    py35_0  
    ipywidgets                4.1.1                    py35_0  
    itsdangerous              0.24                     py35_0  
    jdcal                     1.2                      py35_1  
    jedi                      0.9.0                    py35_1  
    jinja2                    2.8                      py35_1  
    jpeg                      8d                       vc14_0  [vc14]
    jsonschema                2.5.1                    py35_0  
    jupyter                   1.0.0                    py35_3  
    jupyter_client            4.3.0                    py35_0  
    jupyter_console           4.1.1                    py35_0  
    jupyter_core              4.1.0                    py35_0  
    launcher                  1.0.0                         4  
    libdynd                   0.7.2                         0  
    libpng                    1.6.22                   vc14_0  [vc14]
    libsodium                 1.0.3                         0  
    libtiff                   4.0.6                    vc14_2  [vc14]
    llvmlite                  0.11.0                   py35_0  
    lxml                      3.6.0                    py35_0  
    markupsafe                0.23                     py35_2  
    matplotlib                1.5.1               np111py35_0  
    menuinst                  1.4.1                    py35_0  
    mistune                   0.7.2                    py35_0  
    mkl                       11.3.3                        1  
    mkl-rt                    11.1                         p0  
    mkl-service               1.1.2                    py35_2  
    mpmath                    0.19                     py35_1  
    msvc_runtime              1.0.1                    vc14_0  [vc14]
    multipledispatch          0.4.8                    py35_0  
    nbconvert                 4.2.0                    py35_0  
    nbformat                  4.0.1                    py35_0  
    networkx                  1.11                     py35_0  
    nltk                      3.2.1                    py35_0  
    node-webkit               0.10.1                        0  
    nose                      1.3.7                    py35_1  
    notebook                  4.2.1                    py35_0  
    numba                     0.26.0              np111py35_0  
    numexpr                   2.6.0               np111py35_0  
    numpy                     1.11.1                   py35_0  
    odo                       0.5.0                    py35_0  
    openpyxl                  2.3.2                    py35_0  
    openssl                   1.0.2h                   vc14_0  [vc14]
    pandas                    0.18.1              np111py35_0  
    patch                     2.5.9                         1  
    path.py                   8.2.1                    py35_0  
    patsy                     0.4.1                    py35_0  
    pep8                      1.7.0                    py35_0  
    pickleshare               0.7.2                    py35_0  
    pillow                    3.2.0                    py35_1  
    pip                       8.1.2                    py35_0  
    ply                       3.8                      py35_0  
    psutil                    4.3.0                    py35_0  
    py                        1.4.31                   py35_0  
    pyasn1                    0.1.9                    py35_0  
    pycosat                   0.6.1                    py35_1  
    pycparser                 2.14                     py35_1  
    pycrypto                  2.6.1                    py35_4  
    pycurl                    7.43.0                   py35_0  
    pyflakes                  1.2.3                    py35_0  
    pygments                  2.1.3                    py35_0  
    pyodbc                    3.0.10                   py35_0  
    pyopenssl                 0.16.0                   py35_0  
    pyparsing                 2.1.4                    py35_0  
    pyqt                      4.11.4                   py35_6  
    pyreadline                2.1                      py35_0  
    pytables                  3.2.2               np111py35_4  
    pytest                    2.9.2                    py35_0  
    python                    3.5.2                         0  
    python-dateutil           2.5.3                    py35_0  
    pytz                      2016.4                   py35_0  
    pywin32                   220                      py35_1  
    pyyaml                    3.11                     py35_4  
    pyzmq                     15.2.0                   py35_0  
    qt                        4.8.7                    vc14_8  [vc14]
    qtconsole                 4.2.1                    py35_0  
    r                         3.1.3                         0    r
    r-assertthat              0.1                           0    r
    r-base64enc               0.1_2                  r3.1.3_0    r
    r-bh                      1.55.0_3                      0    r
    r-bitops                  1.0_6                         0    r
    r-bradleyterry2           1.0_6                         0    r
    r-brglm                   0.5_9                         0    r
    r-car                     2.0_24                        0    r
    r-caret                   6.0_41                        0    r
    r-catools                 1.17.1                        0    r
    r-chron                   2.3_45                 r3.1.3_0    r
    r-colorspace              1.2_4                         0    r
    r-data.table              1.9.4                  r3.1.3_0    r
    r-dbi                     0.3.1                         0    r
    r-dichromat               2.0_0                         0    r
    r-digest                  0.6.8                         0    r
    r-dplyr                   0.4.1                         0    r
    r-essentials              1.1                    r3.1.3_0    r
    r-evaluate                0.7                    r3.1.3_0    r
    r-foreach                 1.4.2                         0    r
    r-formatr                 1.2                    r3.1.3_0    r
    r-ggplot2                 1.0.0                         0    r
    r-glmnet                  2.0_2                  r3.1.3_0    r
    r-gtable                  0.1.2                         0    r
    r-gtools                  3.4.1                         0    r
    r-hexbin                  1.27.0                        0    r
    r-highr                   0.5                    r3.1.3_0    r
    r-htmltools               0.2.6                         0    r
    r-htmlwidgets             0.5                    r3.1.3_0    r
    r-httpuv                  1.3.2                  r3.1.3_0    r
    r-irdisplay               0.3                    r3.1.3_0    r
    r-irkernel                0.4                    r3.1.3_1    r
    r-iterators               1.0.7                         0    r
    r-jsonlite                0.9.16                 r3.1.3_0    r
    r-knitr                   1.10                   r3.1.3_0    r
    r-labeling                0.3                           0    r
    r-lazyeval                0.1.10                        0    r
    r-lme4                    1.1_7                         0    r
    r-magrittr                1.5                           0    r
    r-maps                    2.3_9                         0    r
    r-markdown                0.7.7                  r3.1.3_0    r
    r-mime                    0.3                    r3.1.3_0    r
    r-minqa                   1.2.4                         0    r
    r-munsell                 0.4.2                         0    r
    r-nloptr                  1.0.4                         0    r
    r-pbkrtest                0.4_2                         0    r
    r-plyr                    1.8.1                         0    r
    r-profilemodel            0.5_9                         0    r
    r-proto                   0.3_10                        0    r
    r-quantmod                0.4_5                  r3.1.3_0    r
    r-quantreg                5.11                          0    r
    r-r6                      2.0.1                         0    r
    r-randomforest            4.6_10                 r3.1.3_0    r
    r-rbokeh                  0.2.2                  r3.1.3_0    r
    r-rcolorbrewer            1.1_2                         0    r
    r-rcpp                    0.11.3                        0    r
    r-rcppeigen               0.3.2.3.0                     0    r
    r-repr                    0.3                    r3.1.3_0    r
    r-reshape2                1.4.1                         0    r
    r-rjsonio                 1.3_0                         0    r
    r-rmarkdown               0.5.1                  r3.1.3_0    r
    r-rzmq                    0.7.7                  r3.1.3_0    r
    r-scales                  0.2.4                         0    r
    r-shiny                   0.11.1                 r3.1.3_0    r
    r-sparsem                 1.6                           0    r
    r-stringi                 0.4_1                  r3.1.3_0    r
    r-stringr                 0.6.2                         0    r
    r-tidyr                   0.2.0                  r3.1.3_0    r
    r-ttr                     0.23_0                 r3.1.3_0    r
    r-uuid                    0.1_1                  r3.1.3_0    r
    r-xtable                  1.7_4                  r3.1.3_0    r
    r-xts                     0.9_7                  r3.1.3_0    r
    r-yaml                    2.1.13                        0    r
    r-zoo                     1.7_11                        0    r
    requests                  2.10.0                   py35_0  
    rope                      0.9.4                    py35_1  
    ruamel_yaml               0.11.7                   py35_0  
    scikit-image              0.12.3              np111py35_1  
    scikit-learn              0.17.1              np111py35_1  
    scipy                     0.17.1              np111py35_1  
    seaborn                   0.7.0                    py35_0  
    setuptools                23.0.0                   py35_0  
    simplegeneric             0.8.1                    py35_1  
    sip                       4.16.9                   py35_2  
    six                       1.10.0                   py35_0  
    snowballstemmer           1.2.1                    py35_0  
    sockjs-tornado            1.0.3                    py35_0  
    sphinx                    1.4.1                    py35_0  
    sphinx_rtd_theme          0.1.9                    py35_0  
    spyder                    2.3.8                    py35_1  
    spyder-app                2.3.8                    py35_0  
    sqlalchemy                1.0.13                   py35_0  
    statsmodels               0.6.1               np111py35_1  
    sympy                     1.0                      py35_0  
    tk                        8.5.18                   vc14_0  [vc14]
    toolz                     0.8.0                    py35_0  
    tornado                   4.3                      py35_1  
    traitlets                 4.2.1                    py35_0  
    ujson                     1.35                     py35_0  
    unicodecsv                0.14.1                   py35_0  
    vs2015_runtime            14.0.25123                    0  
    werkzeug                  0.11.10                  py35_0  
    wheel                     0.29.0                   py35_0  
    xlrd                      1.0.0                    py35_0  
    xlsxwriter                0.9.2                    py35_0  
    xlwings                   0.7.2                    py35_0  
    xlwt                      1.1.2                    py35_0  
    zeromq                    4.1.3                    vc14_1  [vc14]
    zlib                      1.2.8                    vc14_3  [vc14]

**Comment by msarahan** [comment]
Those single slashes need to be double slashes.  You need to manually edit
Continuum\Anaconda3\lib\site-packages\scipy\__config__.py, or perhaps just
force reinstall scipy (this happened because of an old bug, which your
current version of conda fixed, but the file is only written at package
install time).

conda install -f scipy

should work.

HTH,
Michael

**Comment by extratoro** [comment]
Hi, worked perfectly.

Thanks.
