### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jus1tin** [ContinuumIO/anaconda-issues#884]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - anaconda-build ==1.15.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.4', 'qt': '4.8.7', 'pyqt': '4.11.4', 'platform': 'win-64', 'language': 'en_GB', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel', 'version': '1.2.1', 'python': '3.5.1'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
