### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by derekhe** [ContinuumIO/anaconda-issues#885]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - plotly ==1.3.2
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'language': 'en', 'qt': '4.8.7', 'pyqt': '4.11.4', 'conda': '4.1.4', 'version': '1.2.1', 'os': 'Darwin;15.0.0;Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64;x86_64;i386', 'platform': 'osx-64', 'python': '3.5.1'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
