### ISSUE TITLE
Anaconda Python 3 version breaks Fedora 24 dnf command tab completion

### ISSUE THREAD

**Issue by glarue** [ContinuumIO/anaconda-issues#886]
After installing Python 3 using Anaconda (and leaving the system installation of Python untouched) on Fedora 24, tab completion using the `dnf` command throws an error. Here, the command `sudo dnf install py` was entered, and then `tab` was pressed to pull up matching packages:

`sudo dnf install pyTraceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'dnf'
` 

Prioritizing the system Python directory over the Anaconda version in the system `PATH` fixes the issue, so it appears to be a problem with Anaconda not including the correct module.

**Comment by shrmrf** [comment]
BTW, I had the same thing when I set the `global` Python to anything else besides `system` using `pyenv global <version>` 

Moving back to `system` fixed it for me.

**Comment by mingwandroid** [comment]
The problem here is likely that `dnf` isn't being explicit enough in locating the Python binary it needs for bash completion. @nehaljwani is my go-to guy for fedora though, maybe he knows more?

**Comment by malramsay64** [comment]
I can confirm that this is an issue with zsh not being explicit enough. I have submitted a pull request https://github.com/zsh-users/zsh/pull/18 which is a 2 line modification of the dnf completion script.

To fix in the system installed zsh change the instances of `python2` and `python3` in `/usr/share/zsh/5.3.1/functions/_dnf` to `/usr/bin/python2` and `/usr/bin/python3` respectively.

**Comment by mingwandroid** [comment]
Great. I am going to close this as it is a bug in` zsh`.

**Comment by mingwandroid** [comment]
> You might want to manage anaconda from `pyenv`

For anyone reading, no, you definitely do not want to do that.

**Comment by rish4bhn** [comment]
Facing this issue on Fedora 27 too.

**Comment by odinsbane** [comment]
I performed a `conda install conda` which allowed me to switch environments ,but now dnf is completely broken.

Traceback (most recent call last):
  File "/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.6/site-packages/dnf/__init__.py", line 31, in <module>
    import dnf.base
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 26, in <module>
    from dnf.comps import CompsQuery
  File "/usr/lib/python3.6/site-packages/dnf/comps.py", line 29, in <module>
    import dnf.util
  File "/usr/lib/python3.6/site-packages/dnf/util.py", line 32, in <module>
    import librepo
ModuleNotFoundError: No module named 'librepo'

There is the error.

**Comment by shrmrf** [comment]
Hey @mingwandroid ... Sorry I might've spoken without testing... Thanks for clarifying.

**Comment by mingwandroid** [comment]
Yes deactivate conda before running dnf.

**Comment by makarov-roman** [comment]
@mingwandroid I did `conda install conda` and it's not working for me. I guess I need to reinstall dnf rpm package manually

**Comment by mingwandroid** [comment]
I didn't suggest you update conda. I suggested `conda deactivate`.
