### ISSUE TITLE
MongoDB OpenSSL incompatibility

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-issues#890]
Appears that `mongod` may have an incorrect version constraint w.r.t. `openssl` and/or may need to be rebuilt with a newer version of `openssl`. For instance, I see this issue trying to startup the MongoDB daemon.

```
mongod: error while loading shared libraries: libssl.so.6: cannot open shared object file: No such file or directory
```

**Comment by cehbrecht** [comment]
i have the same problem with mongodb=3.3.8 on linux, version 2.6.12 works. So i pinned version 2.6.12.

But i also would like to install the same conda environment on osx, but here i have only the version 3.3.9 which conflicts with my pin.

The quickest solution for my deployment problem would be to remove mongodb=3.3.8 (linux) from the main channel. Conda would pick then the highest available version on each system and it should work.

**Comment by dhimmel** [comment]
I'd like to echo the previous comments that `mongodb` on anaconda cloud needs some attention. First the [coverage is really poor](https://anaconda.org/anaconda/mongodb/files), with very spotty version and OS coverage. There's no window builds at all.

> The quickest solution for my deployment problem would be to remove mongodb=3.3.8 (linux) from the main channel.

@cehbrecht, removing binaries is a bad option. What about linux users who have environments that depend on `mongodb=3.3.8`? Why not just do `conda install mongodb=2`, so you get version 2 on both linux and OSX?

**Comment by cehbrecht** [comment]
@dhimmel 
the only mongodb version in common on linux and osx is 2.4. Linux has in addition 2.6 and 3.3.8 while osx has 3.3.9. I've already upgraded to a mongodb >= 2.6, so i'm not using 2.4 anymore. The current workaround i have is to use a conda pinned file with ``mongodb 2.6.*|3.3.9``. Not nice, but it works. 

It would be nice if there could be an updated mongodb version >= 3.3.9  for both osx and linux.

**Comment by csoja** [comment]
mongodb 3.4.10 for 64-bit Windows, MacOS, Linux is available as of Oct 31, 2017.

**Comment by jakirkham** [comment]
Thanks.
