### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jrking123** [ContinuumIO/anaconda-issues#891]
Got this error while trying to upgrade packages in a Python 2.7 environment

The following errors occurred:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - apptools ==4.3.0
  - python ==3.5.2
Use "conda info <package>" to see the dependencies for each package.

{'language': 'en', 'conda': '4.1.6', 'pyqt': '4.11.4', 'qt': '4.8.7', 'python': '3.5.2', 'platform': 'osx-64', 'version': '1.2.1', 'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386'}

**Comment by goanpeca** [comment]
@jrking123 looks like some of the packages you were trying to upgrade had dependency conflicts.

This is not a bug on conda, but simply the packages selected versions cannot be installed together. What packages were you trying to upgrade?

If you have an environment with python 2.7 and want to upgrade to 3.5, it is better to create a new environment with 3.5, or if you want to make a definitive switch to 3.5, then perhaps you should consider download Anaconda3 (which comes with python3 by default on the root environment)

Cheers

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
