### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by bluels** [ContinuumIO/anaconda-issues#892]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - basemap ==1.0.7
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'platform': 'win-64', 'python': '3.5.2', 'language': 'en_US', 'conda': '4.1.6', 'pyqt': '4.11.4', 'qt': '4.8.7', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
