### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by bijoordzen** [ContinuumIO/anaconda-issues#8938]
## Main error
The following errors occurred:
## Traceback
```
ResolvePackageNotFound: 
  - pytorch==0.1.12=py35_0.1.12cu80
```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.16299;AMD64;AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.11
```

**Comment by goanpeca** [comment]
Not sure what is going. But please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda install conda=4.5
conda install anaconda-navigator=1.8
```

**Comment by bijoordzen** [comment]
Thanks Issue resolved

**Comment by MRAwesome41297** [comment]
my issue not solved .
it shows this error

ResolvePackageNotFound:
  - pytorch==0.1.12=py35_0.1.12cu80
