### ISSUE TITLE
Package request: pymssql

### ISSUE THREAD

**Issue by blitzd** [ContinuumIO/anaconda-issues#8948]
pymssql seems to be left behind, there's only a version of it for Python 3.5 in the default distribution. You'd think with Microsoft being a partner now this wouldn't be so...

**Comment by nehaljwani** [comment]
Right now, pymssql (>2.1.3) has only dev releases available. It is on the verge of making a new release (v2.1.4): https://github.com/pymssql/pymssql/issues/528 . When that happens, a new package can be made available in the defaults channel.

**Comment by blitzd** [comment]
The comment prior to yours on the pymssql issue makes it sound like 2.1.4 likely still has a lot of testing to go through before it'll be released, so having 2.1.3 available would be optimal. For a lot of people the dependencies for pymssql can be painful to get around (see https://github.com/pymssql/pymssql/issues/473 for examples), which I find Anaconda nicely solves in many situations with the addition of binary deps to the envs. 

I understand if it can't be added, but for us this is a big glaring hole in your db support right now (especially with Microsoft now being a partner). I know they support more PyODBC - but PyODBC has always been flaky in my experience.

**Comment by mccarthyryanc** [comment]
I would really like to see a Python 3.6 version my pymssql.

**Comment by nehaljwani** [comment]
pymssql 2.1.4 is now available in the defaults channel.
