### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by yxtj** [ContinuumIO/anaconda-issues#895]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - futures ==3.0.5
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'python': '3.5.2', 'pyqt': '4.11.4', 'version': '1.2.1', 'platform': 'win-64', 'language': 'en_US', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'conda': '4.1.6'}

**Comment by yxtj** [comment]
I tried to update the futures library  from 3.0.4 to 3.0.5 using the Navigator.
I select it by right-clicking -> mark for update. Then click the "apply" button on the right bottom.

**Comment by goanpeca** [comment]
futures 3.0.5 is not compatible with python 3.5.* which is what the error message is saying.

This is not a bug per se, but conda cannot satisfy the dependencies because there is a conflict, or no packages are available for the python version you current;y have.
