### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kskwong** [ContinuumIO/anaconda-issues#897]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - python 3.5*
  - wxpython ==3.0
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'language': 'en_US', 'python': '3.5.2', 'conda': '4.1.6', 'qt': '4.8.7', 'pyqt': '4.11.4', 'version': '1.2.1', 'platform': 'win-64'}

**Comment by goanpeca** [comment]
@kskwong , could you explain what you were trying to do? (what packages were you trying to install?

**Comment by kskwong** [comment]
Thank you for your reply.  I installed Anaconda for Python 3.5 today, and immediately tried to install wxPython using Anaconda Navigator. 'wxPython' was the only package I was trying to install, nothing else.

**Comment by goanpeca** [comment]
Ok, so as the message suggests, not all packages can be installed depending on other packages you have installed. Wxpython does not seem to be compatible (or no package is available to work with) python 3.5.
