### ISSUE TITLE
Incompatible library versions of curl

### ISSUE THREAD

**Issue by tunaloveheart** [ContinuumIO/anaconda-issues#8970]
Hi All, 

I am running Rstudio through the Anaconda launcher. I am getting this error when trying to install packages from GitHub and other installs which need devtools: 

Installation failed: unable to load shared object '/anaconda3/lib/R/library/curl/libs/curl.so':
  dlopen(/anaconda3/lib/R/library/curl/libs/curl.so, 6): Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /anaconda3/lib/R/library/curl/libs/curl.so
  Reason: Incompatible library version: curl.so requires version 10.0.0 or later, but libcurl.4.dylib provides version 9.0.0

I thought maybe I could solve this by updating curl 
conda update curl 
Solving environment: done

## Package Plan ##

  environment location: /anaconda3

  added / updated specs: 
    - curl

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    curl-7.58.0                |       ha441bb4_0         131 KB
    pycurl-7.43.0.1            |   py36hdbc3d79_0          59 KB
    ------------------------------------------------------------
                                           Total:         190 KB

The following packages will be UPDATED:

    curl:   7.55.1-h7601780_3     --> 7.58.0-ha441bb4_0      
    pycurl: 7.43.0-py36hdb90038_3 --> 7.43.0.1-py36hdbc3d79_0

but the version is the not the same as I already have, but its also not version 10.0.0 or later as highlighted in the error. 

I have been trawling the forums but I haven't found anything obvious that will help me. Im not too savy so any help is much appreciated. 

Kind Regards
D

**Comment by mingwandroid** [comment]
Please reopen a new issue with the details asked for in the template.
