### ISSUE TITLE
problem installing anaconda on windows 10 - only getting the anaconda prompt

### ISSUE THREAD

**Issue by Anja2018** [ContinuumIO/anaconda-issues#8976]
Hi everyone,

so I recently got a new computer, and after already having installed python 3 and 2, I decided to install Anaconda as to get an easy way to install and incorporate packages. 
However, it doesn't seem to be installed.
Here are some details: The whole happens on a Windows 10 machine. When I install it, i used the 'Install for Me only' version, I did not add the variable to path. The installation then progresses without a problem or error-message. In the next window, however, when it asks to install Microsoft Visual Studio, it doesn't seem to be able to connect to Internet, even though I can be on the same time searching stuff on the browser with the firewall disabled.

I then press skip, and the installation finishes without displaying any errors. When I then however try to open the app, the only thing that seems to be installed in the start menu under the folder Anaconda3 (64bit) is the Anaconda prompt. Starting it, it doesn't recognize neither python nor conda as commands.

Things I tried: Installing it with adding path to the variable, no change. Installing it for all users: no change. Uninstalling all other versions of python first and deleting their entries in the system variables, then reinstalling it, no change. Installing miniconda first, then anaconda, no change either.

Do you have any ideas what I am doing wrong/what else I could try?

Cheers and thanks,
Anja

**Comment by nehaljwani** [comment]
@Anja2018 Do you have any antivirus software installed on your Windows system?

**Comment by Anja2018** [comment]
yes, it is called sophos protection. I tried, however, doing the installation with both the windows firewall and the antivirus software disabled, and I got the same results as before...

**Comment by murilo-bigoto** [comment]
I've been having the same problem. I tried to pause my antivirus and unistall the last anaconda versions. I saw some forums and none solve my problem.

**Comment by Anja2018** [comment]
same here. If you find a solution, let me know!

**Comment by wde66crush** [comment]
Same problem here.

**Comment by Punya-Swaroop-Sirgiri** [comment]
https://www.youtube.com/watch?v=Q0jGAZAdZqM

**Comment by sunkara296** [comment]
Retry installation by selecting both the options in Advanced installation options. It should work.

![image](https://user-images.githubusercontent.com/17019958/39853357-d59e23b8-53ef-11e8-83d5-931c12b8aed6.png)

**Comment by mingwandroid** [comment]
Please do not do this.

**Comment by sharonv153** [comment]
Hi, I kept having the same issue every time I tried to install Anaconda 64 bit. I installed and uninstalled it multiple times and choose the different settings hoping to solve the problem. Finally, I decided to try and install the 32 bit instead and it worked, I got no connectivity issues and all installed perfectly.

**Comment by sudevpdas** [comment]
> Uninstall, and then manually remove any leftover 'conda' (or similar) folders before reinstalling.
> 
> In my instance, the leftover folders where in my user path, and AppData\Local (make sure hidden folders are visible in your File Explorer). This worked for me.

Thanks, I was able to install it by doing so.

**Comment by tanmayks1999** [comment]
I am having the same issue but after deleting these file also noting changed only anaconda prompt is see after installing and conda is not recognized but python is recognized .

**Comment by docian** [comment]
i don't understand why have they closed this issue!? i'm getting the same issue after several attempts. odd behavior in many ways and lot of issues!

**Comment by ra67052** [comment]
Same here I have spent the best part of day trying to get anaconda to work and any solutions do not work

**Comment by docian** [comment]
after several installing-uninstalling nothing is working: neither prompt, nor navigator. env path variables aren't updated (PYTHONPATH), conda is missing from /Scripts folder and so on and so forth.

**Comment by PickledBeef** [comment]
Here is the same issue. None of google solutions works.

**Comment by ra67052** [comment]
I manged to find a solution, I uninstalled all IDE's like Pycharm (saved my files though) and then removed the all the python interpreters. Uninstalled all conda instances and deleted hided data and then Installed miniconda and then anaconda after that and it worked, spent 15 hours of my life trying to get this to work

**Comment by tanmayks1999** [comment]
I was getting same issue even after uninstalling and reinstalling many
times . So out of frustration I deleted all the user defined environment
variable. Then after installing everything was fine.

**Comment by ashishgumaste** [comment]
I was having the same issue, and I tried a lot of workaround..finally when I checked in my McAfee logs, I found this....

US\<username> ran ANACONDA3-2019.03-WINDOWS-X86_64.EXE, which tried to access C:\ANACONDA\PKGS\LIBTIFF-4.0.10-HB898794_2\LIBRARY\BIN, violating the rule "PDF.EXE Malware", and was blocked. For information about how to respond to this event, see KB85494.

Since I am using a company laptop and cannot change/update McAfee settings I think I will give up installing Anaconda. Other alternative I think is to install Python separately from python.org and then do a pip install for Jupyter and other libraries

**Comment by philipesantos136** [comment]
Install 32bits versions works fine for me.

**Comment by ro-oliveira95** [comment]
> Hi, I kept having the same issue every time I tried to install Anaconda 64 bit. I installed and uninstalled it multiple times and choose the different settings hoping to solve the problem. Finally, I decided to try and install the 32 bit instead and it worked, I got no connectivity issues and all installed perfectly.

This worked for me! After several tries and almost giving up from Anaconda.
Thank you sir :) @sharonv153

**Comment by matthewgson** [comment]
I had a same problem exactly described like above. I solved this issue by completely deleting previous miniconda installation (located in AppData) and deleting ALL registry that includes keyword miniconda. 
Some of it may not be deleted but it works. Hope it might help someone.

**Comment by eduardohl** [comment]
After a lot of trying I found something that worked well:
This post on stackoverflow explains you can install from an older version of anaconda: 
https://stackoverflow.com/questions/57255100/why-isnt-anaconda-distribution-functioning-on-windows-10-64-bit
Use this link + Dec 2018 version: https://stackoverflow.com/questions/57255100/why-isnt-anaconda-distribution-functioning-on-windows-10-64-bit

After that update conda installation using https://docs.anaconda.com/anaconda/install/update-version/ + https://www.anaconda.com/keeping-anaconda-date/

Voila!

**Comment by elbaraediscord** [comment]
Thank you it saved my life!

**Comment by Rohitkumar3796** [comment]
> Hi, I kept having the same issue every time I tried to install Anaconda 64 bit. I installed and uninstalled it multiple times and choose the different settings hoping to solve the problem. Finally, I decided to try and install the 32 bit instead and it worked, I got no connectivity issues and all installed perfectly.

Thank You bro I tried and its done

**Comment by HridoyHazard** [comment]
i'm having the same issue now. tried 64bit and 32bit both but there were no problem while installing but after the installation i don't have anaconda-navigator in start menu or anywhere. i have this folder in installation directory.and if i open the conda.exe file it just automatically close after open. plz help 
![image](https://user-images.githubusercontent.com/71395891/175231526-d33519c2-a215-49ff-90c0-87de7b0ef12d.png)

**Comment by ForrestCY** [comment]
I started to self learning Python before but failed and stopped a while , pick up again recently . 
I installed Pycharm community free version . Last year I replaced my computer . 
Install python and pycharm , then Anaconda again . Since I am a novice learner , usually lines of code so using jupyter notebook within firefox is more convenient than in pycharm . 

Days ago , I cannot open anaconda again . I then uninstalled it and installed again , but same , cannot even start. 

Should I unintall ALL python versions , pycharm & Anaconda , mini conda . 
I feel frustrated for a beginner to just install a software to start .
