### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sebi06** [ContinuumIO/anaconda-issues#902]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - anaconda ==4.1.1
  - theano ==0.7.0 -> numpy 1.10*|1.9*
  - theano ==0.7.0 -> python 2.6*|2.7*|3.3*|3.4*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'linux-64', 'version': '1.2.1', 'conda': u'4.1.8', 'qt': '4.8.7', 'language': 'de_DE', 'python': '2.7.12', 'os': 'Linux;4.4.0-28-generic;#47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016;x86_64;x86_64', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
