### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Enchantertim** [ContinuumIO/anaconda-issues#903]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - google-apputils ==0.4.2
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': '4.1.4', 'python': '3.5.1', 'qt': '4.8.7', 'language': 'en', 'pyqt': '4.11.4', 'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386'}

**Comment by goanpeca** [comment]
There is version conflict between google-apputils  and your python 3.5
