### ISSUE TITLE
Installation problem of Anaconda3 on Lubuntu

### ISSUE THREAD

**Issue by misams** [ContinuumIO/anaconda-issues#9031]
Hi, 

yesterday I made a clean re-installation of Linux on my old Laptop (32bit, Lubuntu 16.04.4 LTS, LXDE) and I also tried to install "Anaconda3-5.1.0-Linux-x86.sh". During installation I got the following error message:

`
PREFIX=/home/sams/anaconda3
installing: python-3.6.4-hc3d631a_1 ...
Anaconda3-5.1.0-Linux-x86.sh: line 362:  3037 Illegal instruction     (core dumped) "$PREFIX/pkgs/python-3.6.4-hc3d631a_1/bin/python" -E -s "$PREFIX"/pkgs/.install.py $INST_OPT --root-prefix="$PREFIX" --link-dist="$1"`

I hope someone can help me?!

Thanks, best regards
Michael

**Comment by mingwandroid** [comment]
You CPU is probably too old.

**Comment by misams** [comment]
Thanks for your answer - that's maybe the cause.
I tried Miniconda3-4.1.11-Linux-x86 and it worked with Pyhton3.5.2!

Best Regards
Michael

**Comment by chucku** [comment]
Thanks for this.  I had a similar problem trying to install on an older machine.  CPU details:

CPU:       Topology: Single Core model: Intel Pentium 4 bits: 32 type: MT 
           arch: Netburst Northwood rev: 9 L2 cache: 512 KiB 
           flags: pae sse sse2 bogomips: 11968 
           Speed: 2993 MHz min/max: N/A Core speeds (MHz): 1: 2993 2: 2993 

I did a binary search :) on releases and found that 4.4.0 works and 5.0.0 fails.
