### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rohitsangale** [ContinuumIO/anaconda-issues#9033]
## Main error
The following errors occurred:
## Traceback
```

```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.2
```

**Comment by goanpeca** [comment]
@rohitsangale what was the error?

**Comment by rohitsangale** [comment]
Package installation issue .

**Comment by goanpeca** [comment]
Hmm, please update navigator

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

**Comment by rohitsangale** [comment]
C:\Users\Rohit Sangale\Anaconda3\python.exe C:\Users\Rohit
Sangale\Anaconda3\Scripts\conda-script.py install --yes --json
--force-pscheck --name root anaconda-navigator=1.6.4: The following
specifications were found to be in conflict:
- anaconda-navigator 1.6.4* -> python 2.7*
- python 3.4*
Use "conda info " to see the dependencies for each package.

**Comment by goanpeca** [comment]
please provide the output of 

```
conda info
conda list
```

**Comment by rohitsangale** [comment]
the earlier issues of package installation is solved  but anaconda navigator is not working properly & unable to launch applications like syder ,qtconsole & also giving error  when i try to update the navigator by clicking the option of update on navigator.
the following is the output when i try updating it by clicking on update option.
C:\Users\Rohit Sangale\Anaconda3\python.exe C:\Users\Rohit Sangale\Anaconda3\Scripts\conda-script.py install --yes --json --force-pscheck --name root anaconda-navigator=1.6.4: The following specifications were found to be in conflict:
- anaconda-navigator 1.6.4* -> python 2.7*
- python 3.4*
Use "conda info " to see the dependencies for each package.

& when i type conda info , the following output-
C:\Users\Rohit Sangale>conda info

     active environment : None
       user config file : C:\Users\Rohit Sangale\.condarc
 populated config files : C:\Users\Rohit Sangale\.condarc
          conda version : 4.4.2
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Users\Rohit Sangale\Anaconda3\New folder  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Rohit Sangale\Anaconda3\New folder\pkgs
                          C:\Users\Rohit Sangale\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Rohit Sangale\Anaconda3\New folder\envs
                          C:\Users\Rohit Sangale\AppData\Local\conda\conda\envs
                          C:\Users\Rohit Sangale\.conda\envs
               platform : win-64
             user-agent : conda/4.4.2 requests/2.14.2 CPython/3.6.5 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
 & when I type  conda list , the following output-
C:\Users\Rohit Sangale>conda list
# packages in environment at C:\Users\Rohit Sangale\Anaconda3\New folder:
#
_license                  1.1                      py36_1
alabaster                 0.7.10                   py36_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.3                    py36_0
anaconda-navigator        1.6.2                    py36_0
anaconda-project          0.6.0                    py36_0
anyqt                     0.0.8                    py36_0
asn1crypto                0.22.0                   py36_0
astroid                   1.4.9                    py36_0
astropy                   1.3.2               np112py36_0
babel                     2.4.0                    py36_0
backports                 1.0                      py36_0
backports.weakref         1.0rc1                   py36_0
beautifulsoup4            4.6.0                    py36_0
bitarray                  0.8.1                    py36_1
blaze                     0.10.1                   py36_0
bleach                    1.5.0                    py36_0
bokeh                     0.12.5                   py36_1
boto                      2.46.1                   py36_0
bottleneck                1.2.1               np112py36_0
bzip2                     1.0.6                    vc14_3  [vc14]
ca-certificates           2017.08.26           h94faf87_0
cffi                      1.10.0                   py36_0
chardet                   3.0.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.9                    py36_0
comtypes                  1.1.2                    py36_0
conda                     4.4.2                    py36_0
conda-env                 2.6.0                h36134e3_1
console_shortcut          0.1.1                    py36_1
contextlib2               0.5.5                    py36_0
cryptography              1.8.1                    py36_0
cudatoolkit               8.0                           3
cudnn                     6.0                           0
curl                      7.52.1                   vc14_0  [vc14]
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.14.3                   py36_1
datashape                 0.5.4                    py36_0
decorator                 4.0.11                   py36_0
dill                      0.2.7.1          py36hf552773_0
distributed               1.16.3                   py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_1
et_xmlfile                1.0.1                    py36_0
fastcache                 1.0.2                    py36_1
flask                     0.12.2                   py36_0
flask-cors                3.0.2                    py36_0
font-ttf-dejavu-sans-mono 2.37                          0
font-ttf-inconsolata      2.000                         0
font-ttf-source-code-pro  2.030                         0
font-ttf-ubuntu           0.83                          0
fonts-continuum           1                             0
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
glue-core                 0.12.3           py36hf2828cb_0
glue-vispy-viewers        0.9              py36h7596f00_0
glueviz                   0.12.0               ha37a3ef_0
greenlet                  0.4.12                   py36_0
h5py                      2.7.0               np112py36_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py36_1
html5lib                  0.9999999                py36_0
icu                       57.1                     vc14_0  [vc14]
idna                      2.5                      py36_0
imagesize                 0.7.1                    py36_0
ipykernel                 4.6.1                    py36_0
ipython                   5.3.0                    py36_0
ipython_genutils          0.2.0                    py36_0
ipywidgets                6.0.0                    py36_0
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jdcal                     1.3                      py36_0
jedi                      0.10.2                   py36_2
jinja2                    2.9.6                    py36_0
joblib                    0.11                     py36_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.6.0                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            5.0.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
jupyterlab                0.30.6           py36h047fa9f_0
jupyterlab_launcher       0.6.0                    py36_0
keyring                   10.5.0           py36h410770b_0
lazy-object-proxy         1.2.2                    py36_0
libpng                    1.6.27                   vc14_0  [vc14]
libprotobuf               3.2.0                    vc14_0  [vc14]
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.18.0                   py36_0
locket                    0.2.0                    py36_1
lxml                      3.7.3                    py36_0
m2-bash                   4.3.042                       5
m2-gcc-libs               5.3.0                         4
m2-heimdal                1.5.3                        10
m2-heimdal-libs           1.5.3                        10
m2-icu                    56.1                          2
m2-libcrypt               1.3                           2
m2-libdb                  5.3.28                        3
m2-libedit                3.1                    20150326
m2-libopenssl             1.0.2.g                       2
m2-libreadline            6.3.008                       8
m2-libsqlite              3.10.0.0                      2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-ncurses                6.0.20160220                  2
m2-openssh                7.1p2                         2
m2-openssl                1.0.2.g                       2
m2-zlib                   1.2.8                         4
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-c-ares              1.11.0                        2
m2w64-ca-certificates     20150426                    103
m2w64-curl                7.48.0                        2
m2w64-diffutils           3.3.2                         2
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gnutls              3.4.11                        2
m2w64-grep                2.24                          2
m2w64-gsl                 2.1                           2
m2w64-jansson             2.7                           3
m2w64-libffi              3.2.1                         4
m2w64-libiconv            1.14                          6
m2w64-libidn              1.32                          4
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libmetalink         0.1.3                         2
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libssh2             1.7.0                         2
m2w64-libsystre           1.0.1                         3
m2w64-libtasn1            4.7                           2
m2w64-libtiff             4.0.6                         2
m2w64-libtre-git          122.c2f5d13                   5
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         4
m2w64-mpfr                3.1.4                         4
m2w64-nettle              3.1.1                         4
m2w64-nghttp2             1.9.2                         2
m2w64-openssl             1.0.2.g                       2
m2w64-p11-kit             0.23.2                        2
m2w64-pcre                8.38                          2
m2w64-rtmpdump-git        499.a107cef                   4
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
markdown                  2.6.9                    py36_0
markupsafe                0.23                     py36_2
matplotlib                2.0.2               np112py36_0
menuinst                  1.4.7                    py36_0
mistune                   0.7.4                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
msgpack-python            0.4.8                    py36_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9                    py36_0
navigator-updater         0.1.0            py36h8a7b86b_0
nbconvert                 5.1.1                    py36_0
nbformat                  4.3.0                    py36_0
networkx                  1.11                     py36_0
nltk                      3.2.3                    py36_0
nose                      1.3.7                    py36_1
notebook                  5.0.0                    py36_0
numba                     0.33.0              np112py36_0
numexpr                   2.6.2               np112py36_0
numpy                     1.12.1                   py36_0
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
olefile                   0.44                     py36_0
openpyxl                  2.4.7                    py36_0
openssl                   1.0.2o               h8ea7d77_0
orange3                   3.4.1                    py36_0
packaging                 16.8                     py36_0
pandas                    0.20.1              np112py36_0
pandoc                    1.19.2.1                      1
pandocfilters             1.4.1                    py36_0
partd                     0.3.8                    py36_0
path.py                   10.3.1                   py36_0
pathlib2                  2.2.1                    py36_0
patsy                     0.4.1                    py36_0
pep8                      1.7.0                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.1.1                    py36_0
pip                       9.0.3                     <pip>
pip                       9.0.1                    py36_1
plotly                    2.2.2            py36h554761e_0
ply                       3.10                     py36_0
prompt_toolkit            1.0.14                   py36_0
protobuf                  3.2.0                    py36_0
psutil                    5.2.2                    py36_0
py                        1.4.33                   py36_0
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_6
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.2.0                    py36_0
pylint                    1.6.4                    py36_1
pyodbc                    4.0.16                   py36_0
pyopengl                  3.1.1a1             np112py36_0
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyqt                      5.6.0                    py36_2
pyqtgraph                 0.10.0                   py36_0
pyreadline                2.1              py36h094d952_1
pytables                  3.2.2               np112py36_4
pytest                    3.0.7                    py36_0
python                    3.6.1                         2
python-dateutil           2.6.0                    py36_0
pytz                      2017.2                   py36_0
pywavelets                0.5.2               np112py36_0
pywin32                   220                      py36_2
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                    vc14_4  [vc14]
qtawesome                 0.4.4                    py36_0
qtconsole                 4.3.0                    py36_0
qtpy                      1.2.1                    py36_0
r-assertthat              0.2.0            r342h01a9704_0
r-backports               1.1.1            r342h3217c2d_0
r-base                    3.4.2                hd3afeec_0
r-base64enc               0.1_3            r342hca0b27c_4
r-bh                      1.65.0_1         r342h2243e07_0
r-bindr                   0.1              r342ha70b456_0
r-bindrcpp                0.2              r342he0cf37b_0
r-bitops                  1.0_6            r342hc4cc12e_4
r-boot                    1.3_20           r342h834dc84_0
r-broom                   0.4.2            r342h779228a_0
r-caret                   6.0_77           r342h4d06727_0
r-catools                 1.17.1           r342h7ba4ff6_4
r-cellranger              1.1.0            r342hfe96f31_0
r-class                   7.3_14           r342hd963038_4
r-cluster                 2.0.6            r342hb962b98_0
r-codetools               0.2_15           r342hd33aafb_0
r-colorspace              1.3_2            r342h7878913_0
r-config                  0.2              r342h1bc11c9_0
r-crayon                  1.3.4            r342h1ecf080_0
r-curl                    3.0              r342h0c1ac88_0
r-cvst                    0.2_1            r342h586ffb9_0
r-data.table              1.10.4_1         r342h70f4df9_0
r-dbi                     0.7              r342h740eb65_0
r-ddalpha                 1.3.1            r342h8577c99_0
r-debugme                 1.0.2            r342hac6a8a0_0
r-deoptimr                1.0_8            r342h8011e7d_0
r-dichromat               2.0_0            r342h5d3b908_4
r-digest                  0.6.12           r342h45c1662_0
r-dimred                  0.1.0            r342h0a0e87f_0
r-dplyr                   0.7.4            r342hebb6f2c_0
r-drr                     0.0.2            r342ha33e3d9_0
r-essentials              1.7.0            r342hac5c45a_0
r-evaluate                0.10.1           r342h6002382_0
r-forcats                 0.2.0            r342he8e709c_0
r-foreach                 1.4.3            r342h420b518_4
r-foreign                 0.8_69           r342h0be368e_0
r-formatr                 1.5              r342hde702e4_0
r-ggplot2                 2.2.1            r342h574d846_0
r-gistr                   0.4.0            r342hce11cbc_0
r-glmnet                  2.0_13           r342he225388_0
r-glue                    1.1.1            r342hf365760_0
r-gower                   0.1.2            r342h601ddb7_0
r-gtable                  0.2.0            r342h0306998_0
r-haven                   1.1.0            r342h87b6d74_0
r-hexbin                  1.27.1           r342ha59edbe_4
r-highr                   0.6              r342h46316e3_0
r-hms                     0.3              r342hbed9107_0
r-htmltools               0.3.6            r342h6f9dbde_0
r-htmlwidgets             0.9              r342h1de9d11_0
r-httpuv                  1.3.5            r342hef81ad5_0
r-httr                    1.3.1            r342h3d373e7_0
r-ipred                   0.9_6            r342h8b93065_0
r-irdisplay               0.4.4            r342h493ca25_0
r-irkernel                0.8.9            r342h34d04e9_0
r-iterators               1.0.8            r342hfe8643f_4
r-jsonlite                1.5              r342h56bb22a_0
r-kernlab                 0.9_25           r342hd9ee2fe_0
r-kernsmooth              2.23_15          r342h0a5b6a8_4
r-knitr                   1.17             r342h2aeaf5c_0
r-labeling                0.3              r342h1b22440_4
r-lattice                 0.20_35          r342h36ddd8c_0
r-lava                    1.5.1            r342h7bde0ec_0
r-lazyeval                0.2.0            r342ha7c403b_0
r-lubridate               1.6.0            r342h66b6780_0
r-magrittr                1.5              r342h30e08dc_4
r-maps                    3.2.0            r342h7d5dd07_0
r-markdown                0.8              r342h43f5b0a_0
r-mass                    7.3_47           r342h1a97f4d_0
r-matrix                  1.2_11           r342hdfe9c5d_0
r-mgcv                    1.8_22           r342h5004514_0
r-mime                    0.5              r342h2177764_0
r-mnormt                  1.5_5            r342h5769c91_0
r-modelmetrics            1.1.0            r342hc782412_0
r-modelr                  0.1.1            r342h2d61cf6_0
r-munsell                 0.4.3            r342h66c67b1_0
r-nlme                    3.1_131          r342h50b31b5_0
r-nnet                    7.3_12           r342h4e6eed8_0
r-numderiv                2016.8_1         r342hcd88280_0
r-openssl                 0.9.7            r342hd1bc1d3_0
r-packrat                 0.4.8_1          r342hc457dde_0
r-pbdzmq                  0.2_6            r342h9ec97ee_0
r-pkgconfig               2.0.1            r342hee5d7c7_0
r-pki                     0.1_5.1          r342h16ef83a_0
r-plogr                   0.1_1            r342h364fde6_0
r-plyr                    1.8.4            r342habc6609_0
r-processx                2.0.0.1          r342h49d1e3b_0
r-prodlim                 1.6.1            r342h7fd35c7_0
r-pryr                    0.1.2            r342h2b00293_0
r-psych                   1.7.8            r342h3d42236_0
r-purrr                   0.2.3            r342h7fe2810_0
r-quantmod                0.4_11           r342h574fc0c_0
r-r6                      2.2.2            r342h65183d9_0
r-randomforest            4.6_12           r342he4bac99_4
r-rbokeh                  0.5.0            r342h499442e_0
r-rcolorbrewer            1.1_2            r342h6cb45cc_0
r-rcpp                    0.12.13          r342h3e881fa_0
r-rcpproll                0.2.2            r342h4c765f1_0
r-rcurl                   1.95_4.8         r342hec0ec68_0
r-readr                   1.1.1            r342h37978c3_0
r-readxl                  1.0.0            r342hfc97dd6_0
r-recipes                 0.1.0            r342h383f9f7_0
r-recommended             3.4.2                h1751db4_0
r-rematch                 1.0.1            r342h69263cc_0
r-repr                    0.12.0           r342hf93323b_0
r-reshape2                1.4.2            r342h278f13d_0
r-reticulate              1.2              r342hc9f85fa_0
r-rjsonio                 1.3_0            r342h433ea5f_4
r-rlang                   0.1.2            r342ha421a6b_0
r-rmarkdown               1.6              r342h086bd35_2
r-robustbase              0.92_7           r342h25ff28c_0
r-rpart                   4.1_11           r342h4e779ed_0
r-rprojroot               1.2              r342hf57ac4f_0
r-rsconnect               0.8.5            r342h069ace8_0
r-rstudioapi              0.7              r342h6e777cf_0
r-rvest                   0.3.2            r342h4286d12_0
r-scales                  0.5.0            r342h44e79eb_0
r-selectr                 0.3_1            r342h5756207_0
r-sfsmisc                 1.1_1            r342hc96e9a0_0
r-shiny                   1.0.5            r342h9740604_0
r-sourcetools             0.1.6            r342h7a12c6a_0
r-spatial                 7.3_11           r342h351adbe_4
r-stringi                 1.1.5            r342h12ab220_0
r-stringr                 1.2.0            r342h38b0a1e_0
r-survival                2.41_3           r342h0998d5e_0
r-tensorflow              1.4              r342h0bf44f9_0
r-tfruns                  1.0              r342h9055efa_0
r-tibble                  1.3.4            r342h4fd6444_0
r-tidyr                   0.7.1            r342h92303bf_0
r-tidyselect              0.2.2            r342h3ab1f0f_0
r-tidyverse               1.1.1            r342h3a97584_0
r-timedate                3012.100         r342h6b5be10_4
r-ttr                     0.23_2           r342haa282ee_0
r-uuid                    0.1_2            r342hb7f30ee_4
r-viridislite             0.2.0            r342hb3e2508_0
r-whisker                 0.3_2            r342ha73a13a_4
r-withr                   2.0.0            r342h26ea15c_0
r-xml2                    1.1.1            r342hb18e4cc_0
r-xtable                  1.8_2            r342h5f07e11_0
r-xts                     0.10_0           r342hae93010_4
r-yaml                    2.1.14           r342h209047d_0
r-zoo                     1.8_0            r342h7ed1f00_0
requests                  2.14.2                   py36_0
rope                      0.9.4                    py36_1
rstudio                   1.0.136                  vc14_2  [vc14]
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.13.0              np112py36_0
scikit-learn              0.18.1              np112py36_1
scipy                     0.19.0              np112py36_0
seaborn                   0.7.1                    py36_0
setuptools                39.0.1                    <pip>
setuptools                27.2.0                   py36_1
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
snowballstemmer           1.2.1                    py36_0
sortedcollections         0.5.3                    py36_0
sortedcontainers          1.5.7                    py36_0
sphinx                    1.5.6                    py36_0
spyder                    3.1.4                    py36_0
sqlalchemy                1.1.9                    py36_0
statsmodels               0.8.0               np112py36_0
sympy                     1.0                      py36_0
tblib                     1.3.2                    py36_0
tensorflow                1.2.1                    py36_0
tensorflow-gpu            1.1.0               np112py36_0
testpath                  0.3                      py36_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.2                    py36_0
tornado                   4.5.1                    py36_0
traitlets                 4.3.2                    py36_0
unicodecsv                0.14.1                   py36_0
vc                        14                            0
vs2015_runtime            14.0.25420                    0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.12.2                   py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        2.0.0                    py36_0
win_unicode_console       0.5                      py36_0
wrapt                     1.10.10                  py36_0
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.4                   py36_0
xlwt                      1.2.0                    py36_0
zict                      0.1.2                    py36_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by mingwandroid** [comment]
Please do not install the `Anaconda Distribution` into a folder that contains spaces.
