### ISSUE TITLE
R kernel dies automatically 

### ISSUE THREAD

**Issue by PanditPranav** [ContinuumIO/anaconda-issues#9038]
This is the anaconda environment I have on my computer. 
As soon as I start R kernel it dies automatically. 
I have tried multiple solutions proposed elsewhere, but no success. 

Looking forward to a solution. 

Microsoft Windows [Version 10.0.16299.309]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Pranav Pandit>conda info

     active environment : None
       user config file : C:\Users\Pranav Pandit\.condarc
 populated config files : C:\Users\Pranav Pandit\.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 2.7.14.final.0
       base environment : C:\Users\Pranav Pandit\Anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Pranav Pandit\Anaconda2\pkgs
                          C:\Users\Pranav Pandit\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Pranav Pandit\Anaconda2\envs
                          C:\Users\Pranav Pandit\AppData\Local\conda\conda\envs
                          C:\Users\Pranav Pandit\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

C:\Users\Pranav Pandit>
C:\Users\Pranav Pandit>conda list --show-channel-urls
# packages in environment at C:\Users\Pranav Pandit\Anaconda2:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h9111531_0    defaults
_r-mutex                  1.0.0                     mro_2    r
alabaster                 0.7.10           py27h2cab13d_0    defaults
anaconda                  5.1.0                    py27_2    defaults
anaconda-client           1.6.14                   py27_0    defaults
anaconda-navigator        1.8.2                    py27_0    defaults
anaconda-project          0.8.2            py27he89e3ca_0    defaults
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.2                    py27_0    defaults
astropy                   2.0.5            py27hc997a72_1    defaults
attrs                     17.4.0                   py27_0    defaults
babel                     2.5.3                    py27_0    defaults
backports                 1.0              py27h6492d98_1    defaults
backports.functools_lru_cache 1.5                      py27_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27h1657125_2    defaults
backports.shutil_which    3.5.1                    py27_2    defaults
backports_abc             0.5              py27h0ec6b72_0    defaults
beautifulsoup4            4.6.0            py27hc287451_1    defaults
bitarray                  0.8.1            py27h0c8e037_1    defaults
bkcharts                  0.2              py27h92b6de3_0    defaults
blaze                     0.11.3           py27h97e5449_0    defaults
bleach                    2.1.3                    py27_0    defaults
bokeh                     0.12.15                  py27_0    defaults
boto                      2.48.0           py27h1ccb131_1    defaults
bottleneck                1.2.1            py27hde90680_0    defaults
bzip2                     1.0.6                h8a7aa22_4    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cdecimal                  2.3              py27h0c8e037_3    defaults
certifi                   2018.1.18                py27_0    defaults
cffi                      1.11.5           py27hdb016f4_0    defaults
chardet                   3.0.4            py27h56c3b73_1    defaults
click                     6.7              py27hb6defca_0    defaults
cloudpickle               0.5.2                    py27_1    defaults
clyent                    1.2.2            py27h4424948_1    defaults
colorama                  0.3.9            py27hdfe4ae1_0    defaults
comtypes                  1.1.4                    py27_0    defaults
conda                     4.5.0                    py27_0    defaults
conda-build               3.7.2                    py27_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py27h5217224_0    defaults
configparser              3.5.0            py27h2fa79a8_0    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py27h42efda5_0    defaults
cryptography              2.2.1            py27h0c8e037_0    defaults
curl                      7.59.0               h7a46e7a_0    defaults
cycler                    0.10.0           py27h59acbbf_0    defaults
cython                    0.28.1           py27h0c8e037_0    defaults
cytoolz                   0.9.0.1          py27h0c8e037_0    defaults
dask                      0.17.2                   py27_0    defaults
dask-core                 0.17.2                   py27_0    defaults
datashape                 0.5.4            py27h3d6e61b_0    defaults
decorator                 4.2.1                    py27_0    defaults
distributed               1.21.4                   py27_0    defaults
docutils                  0.14             py27h8652d09_0    defaults
entrypoints               0.2.3            py27h0271f2b_2    defaults
enum34                    1.1.6            py27h2aa175b_1    defaults
et_xmlfile                1.0.1            py27h1de5d23_0    defaults
fastcache                 1.0.2            py27h0c8e037_2    defaults
filelock                  3.0.4                    py27_0    defaults
flask                     0.12.2           py27h30d9212_0    defaults
flask-cors                3.0.3            py27h4926b05_0    defaults
freetype                  2.8                  hea645e0_1    defaults
funcsigs                  1.0.2            py27h8885ae1_0    defaults
functools32               3.2.3.2          py27h0cdbcdb_1    defaults
futures                   3.2.0            py27h8b2aecd_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2            py27h1842022_0    defaults
glob2                     0.6              py27hd4eee8c_0    defaults
greenlet                  0.4.13           py27h0c8e037_0    defaults
grin                      1.2.1                    py27_4    defaults
h5py                      2.7.1            py27h2dd4c20_0    defaults
hdf5                      1.10.1               h79de857_2    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1            py27h5a33001_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 h2aa20d9_1    defaults
idna                      2.6              py27h1ea29d3_1    defaults
imageio                   2.3.0                    py27_0    defaults
imagesize                 1.0.0                    py27_0    defaults
intel-openmp              2018.0.0                      8    defaults
ipaddress                 1.0.19                   py27_0    defaults
ipykernel                 4.8.2                    py27_0    defaults
ipython                   5.4.1                    py27_2    defaults
ipython_genutils          0.2.0            py27hbe997df_0    defaults
ipywidgets                7.1.2                    py27_0    defaults
isort                     4.3.4                    py27_0    defaults
itsdangerous              0.24             py27hcf63135_1    defaults
jdcal                     1.3              py27h8c72977_0    defaults
jedi                      0.11.1                   py27_1    defaults
jinja2                    2.10             py27hba1794b_0    defaults
jpeg                      9b                   ha175dff_2    defaults
jsonschema                2.6.0            py27haaf3834_0    defaults
jupyter                   1.0.0                    py27_4    defaults
jupyter_client            5.2.3                    py27_0    defaults
jupyter_console           5.2.0            py27h6ed736b_1    defaults
jupyter_core              4.4.0            py27h1619e65_0    defaults
jupyterlab                0.31.12                  py27_0    defaults
jupyterlab_launcher       0.10.5                   py27_0    defaults
kiwisolver                1.0.1            py27h9815e84_0    defaults
lazy-object-proxy         1.3.1            py27ha5c8080_0    defaults
libcurl                   7.59.0               h0990ea7_0    defaults
libiconv                  1.15                 hda2e4ec_7    defaults
libpng                    1.6.34               h325896a_0    defaults
libsodium                 1.0.16               h8b3e59e_0    defaults
libssh2                   1.8.0                h77a7533_4    defaults
libtiff                   4.0.9                hafacce9_0    defaults
libxml2                   2.9.7                h325896a_0    defaults
libxslt                   1.1.32               h89dfad8_0    defaults
llvmlite                  0.22.0           py27ha7086b9_0    defaults
locket                    0.2.0            py27h1ca288a_1    defaults
lxml                      4.2.1            py27h803002f_0    defaults
lzo                       2.10                 h0bb7fe3_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0              py27h9d4480d_1    defaults
matplotlib                2.2.2            py27h8803d4e_0    defaults
mccabe                    0.6.1            py27hde0bf6e_1    defaults
menuinst                  1.4.11           py27h0c8e037_0    defaults
mistune                   0.8.3                    py27_0    defaults
mkl                       2018.0.2                      1    defaults
mkl-service               1.1.2            py27h3c6b6b0_4    defaults
mkl_fft                   1.0.1            py27hc997a72_0    defaults
more-itertools            4.1.0                    py27_0    defaults
mpmath                    1.0.0            py27h0d59bc2_2    defaults
mro-base                  3.4.3                         0    r
mro-basics                3.4.3                         0    r
msgpack-python            0.5.6            py27hdc96acc_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.5.0                    py27_0    defaults
navigator-updater         0.1.0            py27h5e42984_0    defaults
nbconvert                 5.3.1            py27h7a573cf_0    defaults
nbformat                  4.4.0            py27hf49b375_0    defaults
networkx                  2.1                      py27_0    defaults
nltk                      3.2.5            py27h88af825_0    defaults
nose                      1.3.7            py27h84c72c6_2    defaults
notebook                  5.4.1                    py27_0    defaults
numba                     0.37.0          np114py27h720bfd4_0    defaults
numexpr                   2.6.4            py27h20dc147_0    defaults
numpy                     1.14.2           py27h0bb1d87_1    defaults
numpydoc                  0.7.0            py27hf7b062b_0    defaults
odo                       0.5.1            py27h64810b2_0    defaults
olefile                   0.45.1                   py27_0    defaults
openpyxl                  2.5.1                    py27_0    defaults
openssl                   1.0.2o               h2c51139_0    defaults
packaging                 17.1                     py27_0    defaults
pandas                    0.22.0           py27hc56fc5f_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py27h76461d3_1    defaults
parso                     0.1.1            py27hd69ea77_0    defaults
partd                     0.3.8            py27h1e0692f_0    defaults
path.py                   11.0                     py27_0    defaults
pathlib2                  2.3.0            py27h0ae272f_0    defaults
patsy                     0.5.0                    py27_0    defaults
pep8                      1.7.1                    py27_0    defaults
pickleshare               0.7.4            py27hb5f6335_0    defaults
pillow                    5.0.0            py27h901f87c_0    defaults
pip                       9.0.1                    py27_5    defaults
pkginfo                   1.4.2                    py27_1    defaults
pluggy                    0.6.0            py27h89dc50b_0    defaults
ply                       3.11                     py27_0    defaults
prompt_toolkit            1.0.15           py27h3a8ec6a_0    defaults
psutil                    5.4.3            py27h0c8e037_0    defaults
py                        1.5.3                    py27_0    defaults
pycodestyle               2.3.1            py27h24cd5d9_0    defaults
pycosat                   0.6.3            py27hcd410c5_0    defaults
pycparser                 2.18             py27hb43d16c_1    defaults
pycrypto                  2.6.1            py27h0c8e037_7    defaults
pycurl                    7.43.0.1         py27hc64555f_0    defaults
pyflakes                  1.6.0            py27h34e7826_0    defaults
pygments                  2.2.0            py27ha50f84f_0    defaults
pylint                    1.8.3                    py27_0    defaults
pyodbc                    4.0.22           py27hc56fc5f_0    defaults
pyopenssl                 17.5.0           py27h59156d7_0    defaults
pyparsing                 2.2.0            py27hc7d9fa6_1    defaults
pyqt                      5.6.0            py27h224ed30_5    defaults
pysocks                   1.6.8                    py27_0    defaults
pytables                  3.4.2            py27h583b7c0_2    defaults
pytest                    3.5.0                    py27_0    defaults
python                    2.7.14              h4a10d90_31    defaults
python-dateutil           2.7.2                    py27_0    defaults
pytz                      2018.3                   py27_0    defaults
pywavelets                0.5.2            py27h0dc3f48_0    defaults
pywin32                   222              py27h0c8e037_0    defaults
pywinpty                  0.5.1                    py27_0    defaults
pyyaml                    3.12             py27ha287073_1    defaults
pyzmq                     17.0.0           py27h0c8e037_0    defaults
qt                        5.6.2            vc9hc26998b_12  [vc9]  defaults
qtawesome                 0.4.4            py27h766b13d_0    defaults
qtconsole                 4.3.1            py27h77d40ac_0    defaults
qtpy                      1.4.0                    py27_0    defaults
r-assertthat              0.2.0           mro343h889e2dd_0    r
r-backports               1.1.2           mro343h889e2dd_0    r
r-base64enc               0.1_3           mro343h889e2dd_0    r
r-bh                      1.65.0_1        mro343h889e2dd_0    r
r-bindr                   0.1             mro343h889e2dd_0    r
r-bindrcpp                0.2             mro343h889e2dd_0    r
r-boot                    1.3_20                 mro343_0    r
r-broom                   0.4.3           mro343h889e2dd_0    r
r-callr                   1.0.0           mro343h889e2dd_0    r
r-caret                   6.0_78          mro343h889e2dd_0    r
r-cellranger              1.1.0           mro343h889e2dd_0    r
r-checkpoint              0.4.3                  mro343_0    r
r-class                   7.3_14                 mro343_0    r
r-cli                     1.0.0           mro343h889e2dd_0    r
r-clipr                   0.4.0           mro343h889e2dd_0    r
r-cluster                 2.0.6                  mro343_0    r
r-codetools               0.2_15                 mro343_0    r
r-colorspace              1.3_2           mro343h889e2dd_0    r
r-crayon                  1.3.4           mro343h889e2dd_0    r
r-curl                    3.1                    mro343_0    r
r-cvst                    0.2_1           mro343h889e2dd_0    r
r-data.table              1.10.4_3        mro343h889e2dd_0    r
r-dbi                     0.7             mro343h889e2dd_0    r
r-dbplyr                  1.1.0           mro343h889e2dd_0    r
r-ddalpha                 1.3.1           mro343h889e2dd_0    r
r-deoptimr                1.0_8           mro343h889e2dd_0    r
r-deployrrserve           9.0.0                  mro343_0    r
r-dichromat               2.0_0           mro343h889e2dd_0    r
r-digest                  0.6.13          mro343h889e2dd_0    r
r-dimred                  0.1.0           mro343h889e2dd_0    r
r-doparallel              1.0.12                 mro343_0    r
r-dplyr                   0.7.4           mro343h889e2dd_0    r
r-drr                     0.0.2           mro343h889e2dd_0    r
r-essentials              3.4.3                  mro343_0    r
r-evaluate                0.10.1          mro343h889e2dd_0    r
r-forcats                 0.2.0           mro343h889e2dd_0    r
r-foreach                 1.4.5                  mro343_0    r
r-foreign                 0.8_69                 mro343_0    r
r-formatr                 1.5             mro343h889e2dd_0    r
r-ggplot2                 2.2.1           mro343h889e2dd_0    r
r-glmnet                  2.0_13          mro343h889e2dd_0    r
r-glue                    1.2.0           mro343h889e2dd_0    r
r-gower                   0.1.2           mro343h889e2dd_0    r
r-gtable                  0.2.0           mro343h889e2dd_0    r
r-haven                   1.1.0           mro343h889e2dd_0    r
r-hexbin                  1.27.1          mro343h889e2dd_0    r
r-highr                   0.6             mro343h889e2dd_0    r
r-hms                     0.4.0           mro343h889e2dd_0    r
r-htmltools               0.3.6           mro343h889e2dd_0    r
r-htmlwidgets             0.9             mro343h889e2dd_0    r
r-httpuv                  1.3.5           mro343h889e2dd_0    r
r-httr                    1.3.1           mro343h889e2dd_0    r
r-ipred                   0.9_6           mro343h889e2dd_0    r
r-irdisplay               0.4.4           mro343h889e2dd_0    r
r-irkernel                0.8.11                 mro343_0    r
r-iterators               1.0.9                  mro343_0    r
r-jsonlite                1.5                    mro343_0    r
r-kernlab                 0.9_25          mro343h889e2dd_0    r
r-kernsmooth              2.23_15                mro343_0    r
r-knitr                   1.18            mro343h889e2dd_0    r
r-labeling                0.3             mro343h889e2dd_0    r
r-lattice                 0.20_35                mro343_0    r
r-lava                    1.5.1           mro343h889e2dd_0    r
r-lazyeval                0.2.1           mro343h889e2dd_0    r
r-lubridate               1.7.1           mro343h889e2dd_0    r
r-magrittr                1.5             mro343h889e2dd_0    r
r-maps                    3.2.0           mro343h889e2dd_0    r
r-markdown                0.8             mro343h889e2dd_0    r
r-mass                    7.3_47                 mro343_0    r
r-matrix                  1.2_12                 mro343_0    r
r-mgcv                    1.8_22                 mro343_0    r
r-microsoftr              3.4.3.0097             mro343_0    r
r-mime                    0.5             mro343h889e2dd_0    r
r-mnormt                  1.5_5           mro343h889e2dd_0    r
r-modelmetrics            1.1.0           mro343h889e2dd_0    r
r-modelr                  0.1.1           mro343h889e2dd_0    r
r-munsell                 0.4.3           mro343h889e2dd_0    r
r-nlme                    3.1_131                mro343_0    r
r-nnet                    7.3_12                 mro343_0    r
r-numderiv                2016.8_1        mro343h889e2dd_0    r
r-openssl                 0.9.9           mro343h889e2dd_0    r
r-pbdzmq                  0.2_6           mro343h889e2dd_0    r
r-pillar                  1.0.1           mro343h889e2dd_0    r
r-pkgconfig               2.0.1           mro343h889e2dd_0    r
r-plogr                   0.1_1           mro343h889e2dd_0    r
r-plyr                    1.8.4           mro343h889e2dd_0    r
r-png                     0.1_7                  mro343_0    r
r-prodlim                 1.6.1           mro343h889e2dd_0    r
r-psych                   1.7.8           mro343h889e2dd_0    r
r-purrr                   0.2.4           mro343h889e2dd_0    r
r-quantmod                0.4_12          mro343h889e2dd_0    r
r-r6                      2.2.2                  mro343_0    r
r-randomforest            4.6_12          mro343h889e2dd_0    r
r-rbokeh                  0.6.3                  mro343_0    r
r-rcolorbrewer            1.1_2           mro343h889e2dd_0    r
r-rcpp                    0.12.14         mro343h889e2dd_0    r
r-rcpproll                0.2.2           mro343h889e2dd_0    r
r-readr                   1.1.1           mro343h889e2dd_0    r
r-readxl                  1.0.0           mro343h889e2dd_0    r
r-recipes                 0.1.1           mro343h889e2dd_0    r
r-recommended             3.4.3                  mro343_0    r
r-rematch                 1.0.1           mro343h889e2dd_0    r
r-repr                    0.12.0          mro343h889e2dd_0    r
r-reprex                  0.1.1           mro343h889e2dd_0    r
r-reshape2                1.4.3           mro343h889e2dd_0    r
r-revoioq                 8.0.9                  mro343_0    r
r-revomods                11.0.0                 mro343_0    r
r-revoutilsmath           10.0.1                 mro343_0    r
r-rlang                   0.1.6           mro343h889e2dd_0    r
r-rmarkdown               1.8             mro343h889e2dd_0    r
r-robustbase              0.92_8          mro343h889e2dd_0    r
r-rpart                   4.1_11                 mro343_0    r
r-rprojroot               1.3_1           mro343h889e2dd_0    r
r-rstudioapi              0.7             mro343h889e2dd_0    r
r-runit                   0.4.26                 mro343_0    r
r-rvest                   0.3.2           mro343h889e2dd_0    r
r-scales                  0.5.0           mro343h889e2dd_0    r
r-selectr                 0.3_1           mro343h889e2dd_0    r
r-sfsmisc                 1.1_1           mro343h889e2dd_0    r
r-shiny                   1.0.5           mro343h889e2dd_0    r
r-sourcetools             0.1.6           mro343h889e2dd_0    r
r-spatial                 7.3_11                 mro343_0    r
r-stringi                 1.1.6           mro343h889e2dd_0    r
r-stringr                 1.2.0           mro343h889e2dd_0    r
r-survival                2.41_3                 mro343_0    r
r-tibble                  1.4.1           mro343h889e2dd_0    r
r-tidyr                   0.7.2           mro343h889e2dd_0    r
r-tidyselect              0.2.3           mro343h889e2dd_0    r
r-tidyverse               1.2.1           mro343h889e2dd_0    r
r-timedate                3042.101        mro343h889e2dd_0    r
r-ttr                     0.23_2          mro343h889e2dd_0    r
r-utf8                    1.1.2           mro343h889e2dd_0    r
r-uuid                    0.1_2           mro343h889e2dd_0    r
r-viridislite             0.2.0           mro343h889e2dd_0    r
r-whisker                 0.3_2           mro343h889e2dd_0    r
r-withr                   2.1.1           mro343h889e2dd_0    r
r-xml2                    1.1.1           mro343h889e2dd_0    r
r-xtable                  1.8_2           mro343h889e2dd_0    r
r-xts                     0.10_1          mro343h889e2dd_0    r
r-yaml                    2.1.16          mro343h889e2dd_0    r
r-zoo                     1.8_0           mro343h889e2dd_0    r
requests                  2.18.4           py27h3159eba_1    defaults
rope                      0.10.7           py27hb65afb6_0    defaults
ruamel_yaml               0.15.35          py27h0c8e037_1    defaults
scandir                   1.7              py27h0c8e037_0    defaults
scikit-image              0.13.1           py27h0c8e037_1    defaults
scikit-learn              0.19.1           py27he00e316_0    defaults
scipy                     1.0.0            py27h7cd1477_0    defaults
seaborn                   0.8.1            py27hab56d54_0    defaults
send2trash                1.5.0                    py27_0    defaults
setuptools                39.0.1                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27h3f9d112_0    defaults
sip                       4.18.1           py27h5ec1c1a_2    defaults
six                       1.11.0           py27ha5e1701_1    defaults
snowballstemmer           1.2.1            py27h28d3bf7_0    defaults
sortedcollections         0.6.1                    py27_0    defaults
sortedcontainers          1.5.9                    py27_0    defaults
sphinx                    1.7.2                    py27_0    defaults
sphinxcontrib             1.0              py27h0e2fb95_1    defaults
sphinxcontrib-websupport  1.0.1            py27h0d0f901_1    defaults
spyder                    3.2.8                    py27_0    defaults
sqlalchemy                1.2.5            py27h0c8e037_0    defaults
sqlite                    3.22.0               h8b3e59e_0    defaults
ssl_match_hostname        3.5.0.1          py27hea8a0f4_2    defaults
statsmodels               0.8.0            py27hc77c1fc_0    defaults
subprocess32              3.2.7            py27hcc576e2_0    defaults
sympy                     1.1.1            py27hde44fae_0    defaults
tblib                     1.3.2            py27h8ae915c_0    defaults
terminado                 0.8.1                    py27_1    defaults
testpath                  0.3.1            py27h1cd488d_0    defaults
tk                        8.6.7                h144d9c4_3    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   5.0.1                    py27_1    defaults
traitlets                 4.3.2            py27h1b1b3a5_0    defaults
typing                    3.6.4                    py27_0    defaults
unicodecsv                0.14.1           py27h0bf7bb0_0    defaults
urllib3                   1.22             py27hb9f5a07_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
vs2015_runtime            14.0.25123                    3    defaults
wcwidth                   0.1.7            py27hb1a0d82_0    defaults
webencodings              0.5.1            py27h4e224a2_1    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.30.0           py27ha643586_1    defaults
widgetsnbextension        3.1.4                    py27_0    defaults
win_inet_pton             1.0.1            py27hf41312a_1    defaults
win_unicode_console       0.5              py27hc037021_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py27hcd2b27d_0    defaults
xlrd                      1.1.0            py27h2b87a7f_1    defaults
xlsxwriter                1.0.2            py27h5ed79b1_0    defaults
xlwings                   0.11.7                   py27_0    defaults
xlwt                      1.3.0            py27h2271735_0    defaults
yaml                      0.1.7                h3e6d941_2    defaults
zeromq                    4.2.3                h7a60450_3    defaults
zict                      0.1.3            py27h0171463_0    defaults
zlib                      1.2.11               hbc2faf4_2    defaults

C:\Users\Pranav Pandit>
`

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by mingwandroid** [comment]
You need to install into a path that does not contain any spaces.

**Comment by PanditPranav** [comment]
Thanks, it helped. 

After changing the install location to a new local address without 'spaces', now it works.
