### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kellyfitz** [ContinuumIO/anaconda-issues#909]
Application action error

/Users/fitzk/anaconda/bin/python /Users/fitzk/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/fitzk/anaconda spyder=2.3.9: The following specifications were found to be in conflict:
  - spyder 2.3.9*
  - spyder-app -> python 3.4*|3.5*
  - spyder-app -> spyder 2.2.0|2.2.4|2.2.5|2.3.0|2.3.0rc1|2.3.1|2.3.2|2.3.3|2.3.4|2.3.5.2|2.3.6|2.3.7|2.3.8
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.1.8', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.11', 'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@ccordoba12 there is no spyder-app for 2.3.9
