### ISSUE TITLE
UNABLE TO LAUNCH CONDA NAVIGATOR

### ISSUE THREAD

**Issue by EmilioSantias** [ContinuumIO/anaconda-issues#9099]
Hi, see below the error. Could you give me some clue for fixing it?

dlopen(/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/constants.cpython-36m-darwin.so, 2): Symbol not found: __ZNKSt11logic_error4whatEv
  Referenced from: /anaconda3/lib//libc++.1.dylib
  Expected in: /usr/lib/libc++abi.dylib
 in /anaconda3/lib//libc++.1.dylib

**Comment by mingwandroid** [comment]
Please fill in all the details asked for in the template instead of just deleting them.
