### ISSUE TITLE
Can't start Navigator nor Launcher

### ISSUE THREAD

**Issue by dgua** [ContinuumIO/anaconda-issues#910]
Launched Navigator. Was notified a new version was available. Clicked OK to download. Nothing seemed to happen. After a while quit Navigator. 

After that, Navigator quits immediately after starting. Launcher puts a this dialog box:
Sorry, the application encountered a fatal error. Please report the following to us at https://github.com/ContinuumIO/anaconda-issues.

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by goanpeca** [comment]
Do you have the latest version of navigator?, launcher is deprecated.

To update navivagtor to the latest versions please run from the command line

`conda install anaconda-navigator=1.2.2 -f`

Cheers

**Comment by dgua** [comment]
conda is now broken as well:

Adula:~ davide$ conda info -e
-bash: /Users/davide/anaconda/bin/conda: /opt/anaconda1anaconda2anaconda3/bin/python: bad interpreter: No such file or directory


HELP!!!

**Comment by goanpeca** [comment]
Well I honestly dont know what happened. I would just reinstall anaconda.

**Comment by dgua** [comment]
No. I just clicked OK on the offer to update Navigator. I did NOT select to update any other component. I will try re-install anaconda.

**Comment by goanpeca** [comment]
>I did NOT select to update any other component.

I understand but unfortunately conda forces an update anytime it wants, and there is no way to override this AFAIK, so went you accepted to update anaconda-navigator, in the background it executes

`conda install anaconda-navigator=1.2.2 -c <your channels> --yes`

If you run this in the command line, conda will also autoupdate (even if one did not specifically asked for that)

**Comment by dgua** [comment]
OK, after re-installing anaconda I used the command above to force install Navigator. Still same result: Navigator quits immediately after starting. Perhaps something in .conda is corrupted?

**Comment by goanpeca** [comment]
If they exists can you delete
```bash
<USER HOME FOLDER>/.condarc
<USER HOME FOLDER>/.anaconda
```
can you paste the content of `conda list` and can you provide some details on your system configuration (OS, python version?)

**Comment by dgua** [comment]
In my home folder I have .conda and .anaconda, but not .condarc
Renaming .anaconda had no effect. 
Running OS X 10.9.5. Python 2.7. (Used to have 3.5 environment as well).

**Comment by goanpeca** [comment]
Can you DELETE the `<HOME>/.anaconda` folder and then restart. There should be an error log inside
`<HOME>/.anaconda/navigator/logs/<somefile>`. 

Could your paste the contents of that file?

**Comment by goanpeca** [comment]
@ccordoba12 do you know if we have any issues on OS X 10.9.5?

**Comment by goanpeca** [comment]
@dgua, I cannot reproduce this :-/

**Comment by dgua** [comment]
Well, I can start spyder from the command line now, and also notebook. So I don't need the crappy Navigator (BTW, I much preferred Launcher). Two issues with Navigator, besides the horrible GUI:
1. How can you start spyder in a virtual environment from Navigator?
2. I pushed the Update button in the Windows version. Button changes color for a while, then comes back same as before. This is really bad: there is no notification to the user than an update is in process, that it either has completed successfully or failed--and why am I offered to update again when I just did???
I do not like to restart my computer, so I will try what you say when I have more time.

**Comment by dgua** [comment]
Sorry, that was a bit harsh. Thank you for your support.

**Comment by panas89** [comment]
conda update -all

This fixed this issue for me on Windows 64 bit.

**Comment by mimilalo99** [comment]
HI 
I had a same issue . 
i tried to update condo . 
it worked , you need to run with sudo 

conda update --prefix /Users/"put your username "/anaconda anaconda

then 
run anaconda-navigator

**Comment by RoyiAvital** [comment]
Is there official Desktop Launcher (`.desktop`) for Ubuntu based Linux for Anaconda Navigator?

**Comment by sundayle** [comment]
block Anacona Host
sudo vim /etc/hosts
127.0.0.1 api.alpha.binstar.org
127.0.0.1 api.anaconda.org

https://www.sundayle.com/2018/01/21/Anacona-Navigator-No-response/
