### ISSUE TITLE
UNABLE TO LAUNCH ANACONDA NAVIGATOR

### ISSUE THREAD

**Issue by EmilioSantias** [ContinuumIO/anaconda-issues#9109]
### Actual Behavior

dlopen(/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/constants.cpython-36m-darwin.so, 2): Symbol not found: __ZNKSt11logic_error4whatEv
  Referenced from: /anaconda3/lib//libc++.1.dylib
  Expected in: /usr/lib/libc++abi.dylib
 in /anaconda3/lib//libc++.1.dylib

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
Requested information was not provided, closing
