### ISSUE TITLE
cudatoolkit is updated to 9.0, but cudnn and nccl packages are for 8.0

### ISSUE THREAD

**Issue by soumith** [ContinuumIO/anaconda-issues#9121]
- `cudatoolkit` was updated to `9.0` 2 days and 2 hours ago
- however, equivalent cudnn and nccl packages were not uploaded
- if a package depends on cudatoolkit, cudnn and nccl, then it gets an incompatible version of cudnn / nccl (the binaries for cudnn are specific to each major cuda version and are not compatible across versions, however, they dont actually track this in their version number. cudnn 7.0.5 is a valid version for CUDA8 and CUDA9, but the bits to download and distribute are actually different for each of the CUDA versions).

**Comment by jjhelmus** [comment]
cudnn and nccl are now available for CUDA 9.

All the packages distributed by Anaconda, Inc should be pinning the version of the `cudatoolkit` package to prevent installation of an incompatible versions.  Your third bullet seem to indicate this is not the case.  Do you have any examples of conda installing incompatible packages along these lines?
