### ISSUE TITLE
Qt 5.10 support

### ISSUE THREAD

**Issue by Felix-neko** [ContinuumIO/anaconda-issues#9124]
Hi all! Are you planning to support Qt 5.10? It can be really needed for us, because it supports WebGL Streaming...

**Comment by mingwandroid** [comment]
We updated to the Qt 5.9.4 LTS *very* recently and tend to stick to LTS releases for stability reasons. I'm not sure if 5.10 works on the lower end of the operating systems we target (CentOS6, macOS 10.11) but it might.

If you really need use to look into building Qt 5.10 you could perhaps talk to our sales department: sales@anaconda.com

**Comment by mingwandroid** [comment]
> Well, so, if I download Anaconda now, there will be Qt 5.9.4?

No, the Anaconda 5.1.0 installer and package set that was last released a few months back doesn't have Qt 5.9.4, but the Anaconda Distribution, which is a roll software distribution has packages for Qt 5.9.4 so to get them you'd run `conda update qt`

**Comment by Felix-neko** [comment]
@mingwandroid , I,m running `conda update qt` in my Anaconda folder, but it says, that Qt 5.6 is already installed = ((

```
C:\Anaconda3\Scripts>conda update qt
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Anaconda3:
#
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
```

How can I cope with it?

**Comment by mingwandroid** [comment]
`conda-forge` is not the `Anaconda Distribution`, you need to remove conda-forge from your `.condarc` file.

**Comment by Felix-neko** [comment]
Well, one more problem: I've made `conda search qt` and it finds only 5.9.2 (not 5.9.4)
Maybe I should do something else to find 5.9.4?

P.S. It's important because (AFAIK) my PyQGIS is built with Qt 5.9.4 = (

**Comment by mingwandroid** [comment]
I believe you are confusing Qt and PyQt:

```
conda search qt
Loading channels: done
# Name                  Version           Build  Channel
qt                        5.6.2     h9975529_14  pkgs/main
qt                        5.6.2     hb1cebc6_12  pkgs/main
qt                        5.9.4      h14e15a9_0  pkgs/main
```

**Comment by mingwandroid** [comment]
Also, since your PyQGIS was not built by us so it is unknown whether or not it will work with `Qt` or `PyQt` from the `Anaconda Distribution`, chances are it will not.

**Comment by mingwandroid** [comment]
And there is no PyQt 5.9.4 release, but that's ok because PyQt 5.9.2 is compatible with Qt 5.9.4 because the Qt project takes binary compatibility seriously.

**Comment by kai66673** [comment]
>> And there is no PyQt 5.9.4 release, but that's ok because PyQt 5.9.2

its nice, but what about usage of pyqgis3 from pyqt5 standalone gui application?
just for now is impossible because of qgis._core cannot be imported ... bla-bla "5_9_3 is incompatible with 5_9_4"

**Comment by mingwandroid** [comment]
You didn't get pyqtgis3 from the Anaconda Distribution, did you?

**Comment by kai66673** [comment]
Yes, we trying this one with miniconda distribution. Its works, but with Qt-5.6. For our purposes >=Qt-5.9 is necessary

**Comment by mingwandroid** [comment]
`Miniconda` is still the `Anaconda Distribution`, it just doesn't contain hundreds of packages to begin with, instead it's like a buffet. Install what you need.

I am asking specifically how you installed `pyqtgis3` because AFAIK *we* (The `Anaconda Distribution` team) do not and have never provided any packages for that.

**Comment by ccordoba12** [comment]
> qgis._core cannot be imported ... bla-bla "5_9_3 is incompatible with 5_9_4"

This indicates that you have both the `pyqt5` pip package and the `pyqt 5` conda package installed in your environment, so you should remove `pyqt5` to make things work.

**Comment by kai66673** [comment]
>> This indicates that you have both the pyqt5 pip package and the pyqt 5 conda package installed in your environment, so you should remove pyqt5 to make things work.

(mini)conda environment not used at all

**Comment by ccordoba12** [comment]
So, what are posting this in Anaconda issues? Sorry, but I don't get it.

**Comment by kai66673** [comment]
> I am asking specifically how you installed pyqtgis3 because AFAIK we (The Anaconda Distribution team) do not and have never provided any packages for that.

AFAIK? may be.
The question about including qgis (compiled with Qt-5.9,4) package(s) in anaconda distribution. Will not when be a similar problem, because of PyQt5 == 5.9.4 does not exist at all?

**Comment by kai66673** [comment]
Sorry, dudes.
Whether my english is terrible, whether you read in my posts only even words )

**Comment by leofang** [comment]
@mingwandroid can this issue be reopened? v5.13 of Qt/PyQt is already out, but Conda still stays at v5.9...
