### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ThayMoRo** [ContinuumIO/anaconda-issues#913]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - dateutil ==2.4.1
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'pyqt': '4.11.4', 'conda': '4.1.8', 'version': '1.2.1', 'os': 'Darwin;15.3.0;Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'python': '3.5.2', 'platform': 'osx-64'}

**Comment by goanpeca** [comment]
Hi @ThayMoRo, what were you trying to do?

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)


Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
