### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by LairBob** [ContinuumIO/anaconda-issues#914]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - anaconda ==4.1.1
  - ipython ==5.0.0
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.1', 'qt': '4.8.7', 'conda': '4.1.8', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel', 'language': 'en_US', 'version': '1.2.2', 'platform': 'win-64', 'pyqt': '4.11.4'}

**Comment by csoja** [comment]
anaconda v4.1.1 includes an older version of ipython as the ipython 5.0 release came out after anaconda v4.1.1.  If you want both, please install anaconda=4.1.1 first and then update ipython to v5.0.0.
