### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by WRZY** [ContinuumIO/anaconda-issues#9148]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
LSOpenURLsWithRole() failed with error -1712 for the file /anaconda/bin/jupyter_mac.command.

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.1.0;Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
