### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jlsydor** [ContinuumIO/anaconda-issues#915]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - hdf5 ==1.8.16
  - pytables -> hdf5 1.8.15.1
  - pytables -> numexpr 2.0*|2.2*|2.3*
  - pytables -> numpy 1.6*|1.7*|1.8*|1.9*
  - pytables -> python 2.6*|2.7*|3.3*|3.4*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'version': '1.2.1', 'conda': '4.1.8', 'language': 'en_CA', 'pyqt': '4.11.4', 'python': '3.5.2', 'platform': 'win-64', 'qt': '4.8.7'}

**Comment by goanpeca** [comment]
It seems you were trying to install packages that are not compatible and have conflicts among them.
