### ISSUE TITLE
Anaconda Installation Issues

### ISSUE THREAD

**Issue by Yolup1** [ContinuumIO/anaconda-issues#9150]
Receive error stating that anaconda is not an internal or external command

open navigator and/or prompt 

 I did a lot of things terribly wrong because I am a noob, here it goes
 download and install anaconda windows 64 bit
 It works!
 play with tensorflow and run out of space on hard drive partition
 stupidly uninstall anaconda manually (delete the `Anaconda3` folder from my user folder)
 attempt to install it on my other empty one terabyte partition
 it didn't work, so i uninstalled it with the uninstaller (I only just learned of the uninstaller at the time)
 try to reinstall it onto original partition
 it failed

`conda` commands will not work as well

Anaconda version:
5.1.0 64-bit python 3.6
OS:
Windows 10
Result from conda info:
`'conda' is not recognized as an internal or external command`

`'conda' is not recognized as an internal or external command`

Another thing that does not work is the install microsoft vscode, it won't connect to the internet

Things i have tried:
reinstalling
uninstalling restarting computer then installing
ran installation without automatic paths
ran installation for all users
ran installation as admin
opened installation with the command line
tried running the hashes encoder thing
deleted all dependencies and reinstalled it
using command line to add it to path
importing a friends activate.bat and conda.bat files (those are gone too)
my computer refuses to download the installer again so i tried that kinda
miniconda won't download either
currently trying to add anaconda folder and installer to windows defender exceptions list

Please note that it worked perfectly before i tried to move it to my other partition

i hope i have given enough information, as it is all i have. I also hope i am on the right forum.
Please ask me if you need more information. P.S. once again no conda commands will work

**Comment by nehaljwani** [comment]
@Yolup1 Questions for you:
- On the one TB partition, were you installing it on a path with spaces or without spaces?
- What's the filesystem on that partition?
- Do you see the same behaviour with the miniconda installer?
- How does your computer connect to the internet? Is it behind a corporate firewall/proxy server?

>my computer refuses to download the installer again

What's the error message?

**Comment by Yolup1** [comment]
1) without spaces
2) if you mean the format on the partition, it is NTFS. if you mean any directories, there are no directories on the partition, it is empty
3) i cannot download the miniconda installer, just like the anaconda installer
4) when i download the installer from the internet via firefox, the connection fails. i am using a home computer and as far as i know there is no firewall or proxy active, but I am a minor and therefore my parents are in charge of that. my computer connects to the internet from a Wi-Fi dongle that connects to a network extender which is also connected to our main router/modem. We have a DSL modem and the internet is very slow. Max speed ive ever seen on it is 2Mbps.
the error message from firefox is simply that the download has failed, the one time i downloaded the installer is the only time the download succeeded.

**Comment by Yolup1** [comment]
ok i'm stupid, there was a space in the directory on my secondary partition. the partition is labeled "secondary partition" if this information changes anything i hope it helps, i will edit my previous comments. just a side note, the partition i am currently trying to install too does NOT have a space in it.

**Comment by Yolup1** [comment]
I'm going to close this issue as I was able to install Miniconda and upgrade it into full Anaconda.
