### ISSUE TITLE
nb_conda_kernels cannot be uninstalled cleanly

### ISSUE THREAD

**Issue by cel4** [ContinuumIO/anaconda-issues#916]
Uninstalling `nb_conda_kernels-1.0.3` apparently does not clean up the config file.

Having uninstalled nb_conda_kernels, the config file `/Users/ch/miniconda/envs/sb35/etc/jupyter/jupyter_notebook_config.json` still contains:

```
{
  "NotebookApp": {
    "nbserver_extensions": {
      "nb_conda": true,
      "nbpresent": true,
      "nb_anacondacloud": true
    },
    "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager"
  }
}
```

Which leads to this error, whenever one tries to start the notebook/lab:

```
[C 08:12:01.197 LabApp] Bad config encountered during initialization:
[C 08:12:01.197 LabApp] The 'kernel_spec_manager_class' trait of <jupyterlab.labapp.LabApp object at 0x101bd7470> instance must be a type, but 'nb_conda_kernels.CondaKernelSpecManager' could not be imported
[D 08:12:01.197 LabApp] Config at the time: {'LabApp': {'log_level': 10}}
[D 08:12:01.197 LabApp] Exiting application: jupyter-notebook
```

and refuses to start the notebook.

**Comment by ilanschnell** [comment]
This a problem with the current notebook extension mechanism, which will be fixed upstream.
For now, you should be able to disable the extension cleanly by typing:
```
python -m nb_conda_kernels.install --disable
``
