### ISSUE TITLE
Package request: ipython-notebook for Python 3.6

### ISSUE THREAD

**Issue by stmax82** [ContinuumIO/anaconda-issues#9163]
Having installed the latest miniconda on a new system (Python 3.6 on Win 10 x64) I was kinda surprised that `conda install ipython-notebook` didn't work because there's no ipython-notebook package for Python 3.6 yet.

Workaround is to create an environment with Python 3.5 or to install an older miniconda?

Could the package be updated?

**Comment by mingwandroid** [comment]
The package you need is called simply `jupyter`.

**Comment by stmax82** [comment]
oh it was renamed. I actually tried "jupyter-notebook", but that wasn't found either. thanks :p
