### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by roywwei** [ContinuumIO/anaconda-issues#917]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - dask ==0.10.1
Use "conda info <package>" to see the dependencies for each package.

{'qt': '4.8.7', 'language': 'zh_CN', 'python': '3.5.2', 'conda': '4.1.8', 'pyqt': '4.11.4', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel', 'platform': 'win-64', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
@roywwei what were you trying to do?

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
