### ISSUE TITLE
Anaconda custom (64-bit) - not showing version number

### ISSUE THREAD

**Issue by tysun** [ContinuumIO/anaconda-issues#9187]
I read this issue.
https://github.com/ContinuumIO/anaconda-issues/issues/1088

But When I run `python --version` I still get **Anaconda custom (64-bit)**. It doesn't show the version number.

And my current version `conda -V` is still conda 4.5.1 even though I ran `conda update conda` and `conda update anaconda`. Therefore I cannot update `pip 9.0.3` to version 10. 

Strange thing is is I run `conda update anaconda` it says:
```
Solving environment: done

Package Plan

  environment location: /Users/tysun/anaconda3

  added / updated specs: 
    - anaconda

The following packages will be UPDATED:

    anaconda: 5.1.0-py36_2 --> custom-py36ha4fed55_0`
```

**Comment by msarahan** [comment]
conda and anaconda are two different versions.  Conda is a package manager, while anaconda is a collection of packages.  The versions of anaconda reflect a very specific set of packages that are all tested together.  If you update anything in that collection, you then have a custom anaconda version, which is what you're seeing.  Nothing is wrong here.
