### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by chrisqu527** [ContinuumIO/anaconda-issues#919]
Anaconda Navigator Update error:

/Users/apple/anaconda/bin/python /Users/apple/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.2.2:     LOCKERROR: It looks like conda is already doing something.
    The lock ['/Users/apple/anaconda/pkgs/.conda_lock-42160'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock

{'platform': 'osx-64', 'language': 'en', 'python': '3.5.1', 'qt': '4.8.7', 'version': '1.2.1', 'pyqt': '4.11.4', 'conda': '4.1.8', 'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386'}

**Comment by goanpeca** [comment]
Did you try to update anaconda while installing something on another environment (in the environments tab), looks like that was the issue

**Comment by chrisqu527** [comment]
it is helpful. fixed. thanks a lot.
