### ISSUE TITLE
I'm not able to connect to anaconda server for downlads

### ISSUE THREAD

**Issue by Flock1** [ContinuumIO/anaconda-issues#9194]
### Actual Behavior

Nothing. No internet speed for downloads (internet is fine and works on others machines)

### Expected Behavior

Quick downloads

### Steps to Reproduce

Installing anaconda for Ubuntu 16.04

##### Operating System: Ubuntu 16.04

```

```

**Comment by csoja** [comment]
Anaconda can be almost 600MB (https://repo.anaconda.com/archive/) - even with a fast internet connection, it won't be that fast of a download.  If you want a quick download, you may want to download and install Miniconda instead (https://conda.io/miniconda.html or https://repo.anaconda.com/miniconda/ or ) - as it is much smaller - and then use conda to install the other packages you want.

**Comment by Flock1** [comment]
That's fine. But I'm not even able to update conda, which is just a few MBs. The site was very slow and nothing is getting installed.

**Comment by csoja** [comment]
Can you give more details on exactly what you are doing?  Are you attempting to download the installers directly and are not able to download them?  Or do you already have Anaconda installed, and conda is not able to connect and update anything?  If you are behind a proxy, there are additional configuration changes you need to make for conda to be able to install and update packages.

**Comment by Flock1** [comment]
I think there's some problem from my side. This is my bad. The servers at my workplace seem to be messing up. Hope they work it out.

**Comment by csoja** [comment]
I hope so too.  I'm going to close this issue as based on the available information, there is nothing we can do from our side.
