### ISSUE TITLE
byte indices must be integers or slices, not str

### ISSUE THREAD

**Issue by cmorris2945** [ContinuumIO/anaconda-issues#9203]
When I click on the Anaconda Navigator I get this error message.
When I try to install or update anything for Anaconda in the Anaconda Command Prompt it does nothing and keeps asking me if I want to send this as a error report.

Traceback

Traceback (most recent call last):
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\Christopher\Anaconda3.2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment]
@cmorris2945 if you open the anaconda prompt does it print something?

Also could you provide the output of running on the anaconda prompt

```
conda info
```

and
```
conda list --show-channel-urls
```

If there is an error please paste (as text) the text of the error

**Comment by cmorris2945** [comment]
When I open my "Anaconda Prompt" up and run as "administrator" I get this message,and after I run an update for anything in anaconda navigator,I get this:



And after I try to update myanaconda navigator I get this askingme to submit a report:



I tried to uninstall my Anaconda Navigatorand reinstalling it, but this does not work.I get the same results...
-CHRIS
"Sports, football, beer and above all gambling, filled up the horizons of their minds. To keep people in control and ignorant was not difficult...."  
- George Orwell,  author:'1984'
 

    On Thursday, April 19, 2018, 1:01:52 PM EDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
@cmorris2945 if you open the anaconda prompt does it print something?

Also could you provide the output of running on the anaconda prompt
conda info

and
conda list --show-channel-urls

If there is an error please paste (as text) the text of the error

**Comment by cmorris2945** [comment]
Here is my conda info:


And the conda list info...







"Sports, football, beer and above all gambling, filled up the horizons of their minds. To keep people in control and ignorant was not difficult...."  
- George Orwell,  author:'1984'
 

    On Thursday, April 19, 2018, 1:01:52 PM EDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
@cmorris2945 if you open the anaconda prompt does it print something?

Also could you provide the output of running on the anaconda prompt
conda info

and
conda list --show-channel-urls

If there is an error please paste (as text) the text of the error

**Comment by cmorris2945** [comment]
Here you are:

![image](https://user-images.githubusercontent.com/30676606/39020382-a9e922a4-43fa-11e8-9c20-556cee2820e3.png)

**Comment by cmorris2945** [comment]
this is the conda info:

![image](https://user-images.githubusercontent.com/30676606/39020417-c6d8998a-43fa-11e8-814e-a17372e10b71.png)

**Comment by goanpeca** [comment]
@cmorris2945 please delete the following file

`C:\Users\Christopher\.condarc` and try again. Also no need to run the terminal as admin unless you installed for all users.

**Comment by cmorris2945** [comment]
I do run the terminal in "admin", always....

**Comment by cmorris2945** [comment]
That worked!
But I can't launch "Spyder" now.
How do I reset the program?

**Comment by cmorris2945** [comment]
Never mind. Looks like I got it working now.

What is the deal with  ".condarc"??
Is it some sort of file that doens't work??

**Comment by goanpeca** [comment]
It somehow landed in a corrupt state

**Comment by cmorris2945** [comment]
I have another issue.A program I am trying to run.
I keep getting the error:"TypeError: unhashable type: 'slice'"
My dataset are a big list of genes from call analysis,with letters and numbers in the columns and rows:

import phateimport matplotlib.pyplot as pltimport pandas as pdfrom sklearn.manifold import TSNEfrom sklearn.cluster import KMeansfrom sklearn.decomposition import PCAfrom sklearn.manifold import LocallyLinearEmbedding

import matplotlib.pyplot as pltfrom mpl_toolkits.mplot3d.axes3d import Axes3D, get_test_datafrom matplotlib import cmimport numpy as np




#import the datasetmyData = pd.read_csv('EMLG.csv')
x = myData.iloc[:, :-1].valuesy = myData.iloc[:, 3].values

from sklearn.preprocessing import LabelEncoder, OneHotEncodermyLabelEncoderX = LabelEncoder()myData[:,1] = myLabelEncoderX.fit_transform(myData[:,1])
myLabelEncoderX.fit_transform(x[:, 0].astype(str))X = mydata.iloc[:,:].values
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

tree_data, tree_clusters = phate.tree.gen_dla()phate_operator = phate.PHATE(k=15, t=100)tree_phate = phate_operator.fit_transform(tree_data)plt.scatter(tree_phate[:,0], tree_phate[:,1], c=tree_clusters)plt.show()

OUTPUT:

from sklearn.preprocessing import LabelEncoder, OneHotEncodermyLabelEncoderX = LabelEncoder()myData[:,1] = myLabelEncoderX.fit_transform(myData[:,1])Traceback (most recent call last):
  File "<ipython-input-5-ebe7fbbbc55f>", line 3, in <module>    myData[:,1] = myLabelEncoderX.fit_transform(myData[:,1])
  File "C:\Users\chris\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2685, in __getitem__    return self._getitem_column(key)
  File "C:\Users\chris\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2692, in _getitem_column    return self._get_item_cache(key)
  File "C:\Users\chris\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2484, in _get_item_cache    res = cache.get(item)
TypeError: unhashable type: 'slice'


How do I fix this??

"Sports, football, beer and above all gambling, filled up the horizons of their minds. To keep people in control and ignorant was not difficult...."  
- George Orwell,  author:'1984'
 

    On Thursday, April 19, 2018, 6:45:40 PM EDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
@cmorris2945 please delete the following file

C:\Users\Christopher\.condarc and try again. Also no need to run the terminal as admin unless you installed for all users.
