### ISSUE TITLE
mistune should be built with cython

### ISSUE THREAD

**Issue by scw** [ContinuumIO/anaconda-issues#9215]
### Actual Behavior

Installing mistune >= 0.8.1 results in a pure Python version being installed.
### Expected Behavior
With earlier releases of the package in the defaults chhanel, a library compiled via Cython was emitted, which has much better performance characteristics. This can be rectified by adding the `cython` package to the `requirements > build` section of meta.yaml, `mistune` will automatically build the optimized version if Cython is available.

##### Anaconda or Miniconda version:
Miniconda3 4.4.10, but reproducible on other platforms

##### `conda info`

```
     active environment : base
    active env location : /Users/scw/miniconda3
            shell level : 1
       user config file : /Users/scw/.condarc
 populated config files : /Users/scw/miniconda3/.condarc
          conda version : 4.5.1
    conda-build version : 3.8.0
         python version : 3.6.5.final.0
       base environment : /Users/scw/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/scw/miniconda3/pkgs
                          /Users/scw/.conda/pkgs
       envs directories : /Users/scw/miniconda3/envs
                          /Users/scw/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/3.6.5
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
<all from defaults>
```

**Comment by mingwandroid** [comment]
Thanks @scw, could I ask that you make a PR to `conda-forge` to rectify this? The are effectively our 'upstream' now. https://github.com/conda-forge/mistune-feedstock

**Comment by scw** [comment]
@mingwandroid I'm happy to do so, the only thing that stopped me from doing that first is that from the looks of it, they currently treat mistune as a pure Python package in the [meta.yaml](https://github.com/conda-forge/mistune-feedstock/blob/master/recipe/meta.yaml). I think this change would require it to shift back to a per-platform package, since the compiled component will vary between platforms. I'll open an issue there and ask.

**Comment by scw** [comment]
PR submitted upstream, closing this.

**Comment by jjhelmus** [comment]
mistune 0.8.3 build 1 packages in `defaults` include the compiled extension.  Thanks for bringing this to our attention @scw
