### ISSUE TITLE
Anaconda NodeJS stuck on 8.9.3

### ISSUE THREAD

**Issue by tysun** [ContinuumIO/anaconda-issues#9217]
`conda list` says `nodejs 8.9.3 h378b8a2_0` but NodeJS is at version 8.11.1. I've tried various update methods with no luck. Should I update manually?

**Comment by nehaljwani** [comment]
nodejs 8.11.1 is available on defaults for linux and macOS

The windows one hasn't been updated to 8.11.1 due to https://github.com/npm/npm/issues/18978
