### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by taoshengyijiu1747** [ContinuumIO/anaconda-issues#922]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - python 3.5*
  - scrapy ==1.0.1
Use "conda info <package>" to see the dependencies for each package.

{'language': 'zh_CN', 'platform': 'win-64', 'conda': '4.1.6', 'version': '1.2.1', 'python': '3.5.2', 'qt': '4.8.7', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
