### ISSUE TITLE
Update Index Reverts Environment to Root

### ISSUE THREAD

**Issue by overlordxxx** [ContinuumIO/anaconda-issues#9226]
### Actual Behavior

Environment reverts to the root when the index is updated and causes Python to crash.

### Expected Behavior

Environment remains in the last active environment when the index is updated and Python does not crash.

### Steps to Reproduce

Update to the most recent version of Anaconda.  Create an environment. Open Spyder and try to run a script.  Install packages.  Update index.  Try to run a script in Spyder.  

##### Anaconda or Miniconda version:

After updating to the most recent version of Anaconda I experienced problems with the environments.  After a while I noticed that when viewing the environment in Navigator the environment switched to the Root when Update Index was activated.  I uninstalled Anaconda and used an archive of an older version.  After installing the archive version the problem disappeared and Anaconda worked normally.

##### Operating System:
Windows 10 (Bootcamp)
##### `conda info`

```

```
##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@overlordxxx are you using Anaconda Navigator or the command prompt?

Please provide the requested information
