### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sahilseth** [ContinuumIO/anaconda-issues#923]
Application action error

/Users/sahilseth/anaconda/bin/python /Users/sahilseth/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/sahilseth/anaconda orange-app=1.0.1: The following specifications were found to be in conflict:
  - orange-app 1.0.1*
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Darwin;14.5.0;Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64;x86_64;i386', 'conda': '4.1.8', 'platform': 'osx-64', 'language': 'en', 'qt': '4.8.7', 'pyqt': '4.11.4', 'python': '3.4.4', 'version': '1.2.2'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

---

Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
