### ISSUE TITLE
Anaconda update fails

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#924]
I've been trying to update my environment but get the following message.
I don't know what the conflict could be. Is there any way to find out?

```
╰─$ conda update anaconda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/andy/anaconda3:

The following packages will be DOWNGRADED due to dependency conflicts:

    jupyter:         1.0.0-py35_3       --> 1.0.0-py35_2      
    jupyter_client:  4.3.0-py35_0       --> 4.2.2-py35_0      
    jupyter_console: 5.0.0-py35_0       --> 4.1.1-py35_0      
    libgfortran:     3.0.0-1            --> 3.0-0             
    mkl:             11.3.3-0           --> 11.3.1-0          
    mkl-service:     1.1.2-py35_2       --> 1.1.2-py35_0      
    notebook:        4.2.1-py35_0       --> 4.1.0-py35_1      
    numexpr:         2.6.0-np111py35_0  --> 2.5-np110py35_0   
    numpy:           1.11.1-py35_0      --> 1.10.4-py35_1     
    pip:             8.1.2-py35_0       --> 8.1.1-py35_1      
    scikit-learn:    0.17.1-np111py35_2 --> 0.17.1-np110py35_0
    scipy:           0.17.1-np111py35_1 --> 0.17.0-np110py35_2
```

**Comment by ilanschnell** [comment]
Can you try:
```
$ conda install anaconda=4.1.1
```

**Comment by amueller** [comment]
``╰─$ conda install anaconda=4.1.1``

Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - anaconda 4.1.1*
  - theano -> numpy 1.10*|1.6*|1.7*|1.8*|1.9*
  - theano -> python 2.6*|2.7*|3.3*|3.4*
Use "conda info <package>" to see the dependencies for each package.

**Comment by amueller** [comment]
I did ``conda remove theano`` and now the upgrade seems to work, though I get
```
The following packages will be DOWNGRADED due to dependency conflicts:

 jupyter_console:    5.0.0-py35_0                 --> 4.1.1-py35_0      
```

**Comment by csoja** [comment]
Jupyter_console was updated to 5.0.0 after Anaconda v4.1.1 was released.  You should be able to update it after you've installed anaconda v4.1.1 and not have a problem.  (_conda update jupyter_console_)  
Glad to hear you were able to successfully update to the latest version of Anaconda!
