### ISSUE TITLE
Anaconda Navigator only asks to be updated when it has no admin privileges to actually process the update.

### ISSUE THREAD

**Issue by squibbler10293** [ContinuumIO/anaconda-issues#9250]
I just installed the most recent 64 bit version of Anaconda on Windows 10.

First I installed it for all users instead of just the current user. On every start of the Anaconda Navigator I would be prompted for its automatic update dialogue (1.7.0 to current version) but the update infinitely loops as I assume it hasn't been given the proper admin privileges.

When I start the Navigator with admin rights, it doesn't prompt me for the update at all and doesn't even seem to check for updates in general (the blue progress bar in the lower right corner doesn't show up after startup).

Then I cleanly uninstalled and deleted every trace of Anaconda and installed it for just the current user instead. Unfortunately, it again never seems to check for an update, now that it doesn't need special privileges.

**Comment by vijuspiderman** [comment]
Hi squibbler10293,
Me too had the same issue. Open it with admin privileges. Then go to 'Environments', then click 'Update Index'. After a while it will ask you whether you wanna update. Try this before unistalling. Have a great day.
Regards,
VKV

**Comment by goanpeca** [comment]
@squibbler10293  @MariaJo1972 @vijuspiderman 

Please update to the latest navigator and navigator updater. Open a Terminal or Anaconda Prompt and type

```
conda install anaconda-navigator=1.8.7
conda install navigator-updater=0.2.1
```
