### ISSUE TITLE
curl 7.49.0 prefix too short

### ISSUE THREAD

**Issue by michaelbrooks** [ContinuumIO/anaconda-issues#927]
Installed Anaconda3 4.1.1 on OSX and received the following error:

```
creating default environment...
ERROR: placeholder '/Users/ilan/minonda/envs/_build_placehold_placehold_placehold_placehold_placehol' too short in: curl-7.49.0-0
```

It appears the `has_prefix` file in the curl 7.49.0 package has changed to the following:
```
/Users/ilan/minonda/envs/_build_placehold_placehold_placehold_placehold_placehol binary lib/libcurl.4.dylib
/Users/ilan/minonda/envs/_build_placehold_placehold_placehold_placehold_placehol binary lib/libcurl.dylib
/opt/anaconda1anaconda2anaconda3 text bin/curl-config
/opt/anaconda1anaconda2anaconda3 text lib/libcurl.la
/opt/anaconda1anaconda2anaconda3 text lib/pkgconfig/libcurl.pc
```

My installation prefix was longer than `/Users/ilan/minonda/envs/_build_placehold_placehold_placehold_placehold_placehol`, which must have caused the error. See http://conda.pydata.org/docs/spec.html#package-metadata

I noted that curl 7.45.0 (included with Anaconda 4.0) has an entirely different `has_prefix` file, and did not have this issue.

**Comment by ilanschnell** [comment]
The `has_prefix` file shows that the placeholder length is 80 bytes, which used to be the default (but we are switching over to using 255 for now on).  When exactly are you getting the error?  Are you creating an environment into a prefix which is more than 80 characters long?

**Comment by michaelbrooks** [comment]
Yes, exactly. It was part of an automated test script that installed Anaconda in a specific location with a long path. 255 should be adequate. I'm not sure why this file needed to change in curl 7.49 though.

**Comment by ilanschnell** [comment]
I just recompiled curl 7.49 with the 255 byte placeholder, and added `curl-7.49.0-1` to the repository.  I'm not sure if that helps you, though, because you use the Anaconda 4.1.1 installer.

**Comment by michaelbrooks** [comment]
Thanks!

**Comment by StudioEtrange** [comment]
Hi
Still, while installing anaconda 4.1.1, with miniconda
The problem is still there. Even if we install curl-7.49.0-1 first. 
Because curl is downgraded :  

conda install curl=7.49.0=1
...
conda install anaconda
...
The following packages will be DOWNGRADED due to dependency conflicts:
    curl:               7.49.0-1           --> 7.49.0-0 
Linking packages ...
Error: ERROR: placeholder '/Users/ilan/minonda/envs/_build_placehold_placehold_placehold_placehold_placehol' too short in: curl-7.49.0-0


Links stick to 7.49.0-0 version

**Comment by ilanschnell** [comment]
I think 255 is more then plenty.  We tried doing 1024 first, but that was not feasible.  On some OSes creating that long path isn't even possible.

**Comment by msarahan** [comment]
@StudioEtrange, we debated this quite a lot at https://github.com/conda/conda-build/pull/877 - ultimately settling on 255 characters, for reasons summarized in https://github.com/conda/conda-build/pull/877#issuecomment-221749660.

These downgrade issues are serious, though, and we'll try to smooth things like this out somehow.

**Comment by ilanschnell** [comment]
I think for the next Anaconda 4.2 release, which is planned for the end of September, we should make sure that all packages have the new 255 byte placeholder.
