### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by yohanzuo** [ContinuumIO/anaconda-issues#930]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - jedi ==0.8.1
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.4', 'python': '3.5.1', 'qt': '4.8.7', 'os': 'Windows;10;10.0.14366;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'version': '1.2.1', 'platform': 'win-64', 'language': 'zh_CN', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Jedi is not compatible with Python3.5, would need to downgrade python or create a new environment with a python version that does not have dependencies conflict with jedi.

To learn more about conflict resolution you can go to the [documentation](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

**Comment by yohanzuo** [comment]
Thanks for your answer and the significant work you‘ve done。
