### ISSUE TITLE
Segmentation fault after installing glibc in conda

### ISSUE THREAD

**Issue by githubgsq** [ContinuumIO/anaconda-issues#9309]
I installed Anaconda2-5.1.0-Linux-x86_64, but I need latest glibc, then I executed "conda install -c dan_blanchard glibc"
![image](https://user-images.githubusercontent.com/23164715/39619068-0216401e-4fb9-11e8-8a9e-aa75f685621d.png)

It seems that glibc has been installed successfully
but after that, I can't use conda, also other shell commands. "segmentation fault" always
![image](https://user-images.githubusercontent.com/23164715/39619286-e13dae6c-4fb9-11e8-9568-d7ef82abfa62.png)

Do you have any advice please?
thanks!

**Comment by mingwandroid** [comment]
Yes, do not install a broken package from `dan_blanchard`? This is a 3rd party release, not something released by the `Anaconda Distribution` team and therefore we cannot do anything about it.

If you can find some way to contact the owner of this channel they might be able to help you.

**Comment by mingwandroid** [comment]
> but I need latest glibc

Why do you think you need the latest `glibc` in your conda environment? Also, `2.18` is far from the latest version, `2.27` is the latest.

Also

**Comment by githubgsq** [comment]
@mingwandroid thanks!  Is there any method to install glibc>=2.14 in conda please?

**Comment by githubgsq** [comment]
@mingwandroid I want to install pytorch through Anaconda, but glibc>=2.14 needed.

**Comment by mingwandroid** [comment]
> I want to install pytorch through Anaconda, but glibc>=2.14 needed.

What makes you say that? Can you point to some documentation? Pretty much all of the official software in the `Anaconda Distribution` is compatible with `glibc 2.12` and some amount of it is compatible with `glibc 2.11`.

I noticed that the pytorch team have their own conda channel too and that is their officially recommended way to install it, is that how you are trying to install it?

**Comment by mingwandroid** [comment]
Installing the official way via:
```
conda create -n pytorch-official torchvision cudatoolkit=8.0 -c pytorch -c https://repo.continuum.io/pkgs/main -c https://repo.continuum.io/pkgs/free
conda activate pytorch-official
```

.. does indeed require `glibc>=2.14`, as seen by:
```
import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch-official/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/conda/envs/pytorch-official/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
```

(BTW including all these details would have saved me some time).

So the official PyTorch packages need glibc 2.14 at least. I do not think you'll be able to do much about this, except use a newer linux distro if you need to use the official packages. Maybe you could ask them to document this requirement too?

**Comment by mingwandroid** [comment]
@jjhelmus a penny for your thoughts?

**Comment by githubgsq** [comment]
hi, @mingwandroid , pytorch has been installed successfully via pip according to https://pytorch.org/previous-versions/
Thanks a lot for your kind advice ;)
