### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by YehudaItkin** [ContinuumIO/anaconda-issues#931]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - azure ==1.0.2
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.9', 'qt': '4.8.7', 'pyqt': '4.11.4', 'language': 'en_US', 'platform': 'linux-64', 'version': '1.2.2', 'os': 'Linux;3.19.0-65-generic;#73~14.04.1-Ubuntu SMP Wed Jun 29 21:05:22 UTC 2016;x86_64;x86_64', 'python': '3.5.1'}

**Comment by goanpeca** [comment]
Azure is not compatible with Python3.5, would need to downgrade python or create a new environment with a python version that does not have dependencies conflict with azure.

To learn more about conflict resolution you can go to the [documentation](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
