### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by slwessels** [ContinuumIO/anaconda-issues#933]
The following errors occured:

RuntimeError:
Could not find anaconda.org user t

{'pyqt': '4.11.4', 'conda': '4.1.6', 'language': 'en_ZA', 'version': '1.2.1', 'os': 'Linux;4.4.0-31-generic;#50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016;x86_64;x86_64', 'qt': '4.8.7', 'platform': 'linux-64', 'python': '3.5.1'}

**Comment by goanpeca** [comment]
Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
