### ISSUE TITLE
navigator won't open

### ISSUE THREAD

**Issue by m00nd00r** [ContinuumIO/anaconda-issues#934]
when i click the anaconda navigator app from the start window in windows10, nothing happens.

when i type 'anacaonda-navigator' into the command line i get this:

C:\WINDOWS\system32>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Johnnysporto\Anaconda\Scripts\anaconda-navigator-script.py", line 3, in <module>
    import anaconda_navigator.app.main
  File "C:\Users\Johnnysporto\Anaconda\lib\site-packages\anaconda_navigator\app\main.py", line 15, in <module>
    from qtpy.QtCore import QEvent, QObject, Qt
  File "C:\Users\Johnnysporto\Anaconda\lib\site-packages\qtpy\__init__.py", line 129, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

just today i installed graphiz and updated anaconda and navigator. 

do i need to uninstall anaconda altogether and reinstall? if so, what's the proper way to uninstall it?

**Comment by goanpeca** [comment]
Looks like you do not have qt installed.
could you try to `conda install qt pyqt` ?

**Comment by m00nd00r** [comment]
that was the problem. which is strange because navigator worked before i updated everything. i'm surprised the update didn't include the very thing it needs to actually run after the update.
