### ISSUE TITLE
Failed to create Menus [Windows10 Installation]

### ISSUE THREAD

**Issue by aakash94** [ContinuumIO/anaconda-issues#9358]
### Actual Behavior

'Failed to create Menus’ towards the end of the installation process.

### Expected Behavior

No hiccups in the initial installation of anaconda

### Steps to Reproduce

Download and Run Anaconda installer with admin rights. Install for all users.

##### Operating System: Windows 10 Home. Version:1709.  OS Build 16299.431

Where in execution the failure pops up : 
`Execute: "C:\ProgramData\Anaconda3\pythonw.exe" -E -s "C:\ProgramData\Anaconda3\Lib\_nsis.py" mkmenus `
Unable to go to anaconda prompt.
Also Miniconda installation, when I tried, worked just fine.

P.S. this is my first time trying out anaconda, so do let me know if I am doing something wrong, or provide some other information.

**Comment by msarahan** [comment]
What is the value of your PATH environment variable?

**Comment by aakash94** [comment]
The system PATH variables remain unchanged (did a diff to confirm) before and after the installation(with the error of course).
I have attached a text file with list of all system PATH variables on my machine.
[Path.txt](https://github.com/ContinuumIO/anaconda-issues/files/1995403/Path.txt)

**Comment by msarahan** [comment]
You have an already existing Python installation at the front of your path.  That's probably not a good idea.  It's better to not modify PATH at all, but to add to it only in local prompts.  The Anaconda Prompt is a shortcut that we created to do this for you.

I recommend that you uninstall the other Python installation, or at least remove it from PATH, then try then installer again.

**Comment by aakash94** [comment]
so, uninstalling python and removing system variables did not help. getting the same issue.

**Comment by aakash94** [comment]
Do let me know if there is some alternate way of installing anaconda or some other procedure that can help me get over this issue. Thanks

**Comment by aakash94** [comment]
Also, I realize that there is no pythonw.exe in the installation folder.

`Execute: "C:\ProgramData\Anaconda3\pythonw.exe" -E -s "C:\ProgramData\Anaconda3\Lib\_nsis.py" mkmenus `

Could that have anything to do with the failed install ?

**Comment by aakash94** [comment]
So, a windows update did the trick for me. Dont know what changed. But works like a charm now.
