### ISSUE TITLE
PyCharm is not able to run jupyter with error no such kernel named python3

### ISSUE THREAD

**Issue by MordicusEtCubitus** [ContinuumIO/anaconda-issues#936]
I have this issue with pycharm 2016.2 and Anaconda 3.4
It is discussed here: http://stackoverflow.com/questions/38257138/jupyter-no-such-kernel-named-python3

I've investigated this a bit, and apparently there is 2 possible reasons
- An error in PyCharm which uses default NATIVE_KERNEL_NAME (python3) but Anaconda replace it by "Python [Root]"
- In Anaconda which removes default NATIVE_KERNEL_NAME with no good reason and in a bad way, as I think it should just update it

For a longer explanation: Anaconda provides its own manager class CondaKernelSpecManager
in file lib/python3.5/site-packages/nb_conda_kernels/manager.py

In its "get_kernel_spec(self, kernel_name)" it tries to find provided kernel name in conda environments
If not it calls super(CondaKernelSpecManager, self).get_kernel_spec(kernel_name)
But this one calls "find_kernel_specs" which is overrided in conda manager, so calls finally conda's method, which removes NATIVE_KERNEL_NAME from spec list

I don't see the need to remove natives names, especially if they are not duplicated with conda environements.
More, if conda env as same name than native, an update is just enough 
So I suggest this work around:

    def find_kernel_specs(self):
        """Returns a dict mapping kernel names to resource directories.

        The update process also add the resource dir for the conda
        environments.
        """
        kspecs = super(CondaKernelSpecManager, self).find_kernel_specs()

        # COMMENT THIS
        # remove native kernels because it is provided by the env name
        # if "python3" in kspecs:
        #     kspecs.pop("python3")
        # elif "python2" in kspecs:
        #     kspecs.pop("python2")
        # elif "R" in kspecs:
        #     kspecs.pop("R")

**Comment by bollwyvl** [comment]
@MordicusEtCubitus We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing!

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```
As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166

**Comment by MordicusEtCubitus** [comment]
Thanks a lot, I confirm that solves the issue I was facing.

**Comment by justwjr** [comment]
Fixed, thank you!
had to run:

conda update nb_conda nb_conda_kernels nb_anacondacloud
