### ISSUE TITLE
I can't update

### ISSUE THREAD

**Issue by Cocorico84** [ContinuumIO/anaconda-issues#9360]
Hello,

### Actual Behavior

I have tried to update with 
`conda update conda`
`conda update anaconda-navigator`
`conda update navigator-updater`
but I can't even open anaconda. In that moment I open anaconda prompt it says "Error report".

### Expected Behavior

I expected Anaconda works and opens its IDE

### Steps to Reproduce

Just click on Anaconda quick startup

##### Anaconda or Miniconda version:

Anaconda3 5.1.0

##### Operating System:

Windows 10

##### `conda info`
 ```
     active environment : None
       user config file : C:\Users\Coco\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Users\Coco\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Coco\Anaconda3\pkgs
                          C:\Users\Coco\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Coco\Anaconda3\envs
                          C:\Users\Coco\AppData\Local\conda\conda\envs
                          C:\Users\Coco\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

I can't have it. I have "Error report" message.

Thanks for your answer

**Comment by Cocorico84** [comment]
When I open Anaconda and try to launch it, the first line is :

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

I tried to write `conda info` but it printed out

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

**Comment by goanpeca** [comment]
it seems your installation is corrupted. You may have to uninstall and reinstall Anaconda.

**Comment by Cocorico84** [comment]
I have already done it unfortunately.

**Comment by goanpeca** [comment]
@Cocorico84 please try again with the latest installers and make sure you remove via the windows uninstaller
