### ISSUE TITLE
not able to open navigator on clicking the icon

### ISSUE THREAD

**Issue by spkuku** [ContinuumIO/anaconda-issues#9363]
![screenshot 1519](https://user-images.githubusercontent.com/39196644/39935042-5f284408-5565-11e8-9d08-01767ebb08fb.png) 
also jupyter notbook is showing error 404 not found
i have set the path  also done every thing told in the video but still not able to launch the navigator can anyone please tell me the problem
on windows 10

**Comment by goanpeca** [comment]
@spkuku please provide the output of typing in the `Anaconda Prompt`

```
conda info
```

and

```
conda list --show-channel-urls
```

**Comment by goanpeca** [comment]
No feedback provided. Closing.
