### ISSUE TITLE
For two complementing packages, you deliver two mutually incompatible packages

### ISSUE THREAD

**Issue by mario98** [ContinuumIO/anaconda-issues#9386]
Hi,

as of today, you deliver pytorch in version 0.4 (very recent) and torchvision in version 0.2 (several month old). However, pytorch 0.4 contained a lot of breaking changes, and those were only adapted in torchvision 0.2.1. But torchvision 0.2 is incompatible to pytorch 0.4! (For example you can't load DenseNet because it contains dots in the name)

I urge you to also update torchvision as soon as possible, otherwise people will not be able to use pytorch for most computer vision tasks with anaconda!

And for the future, I'd recommend that you take action to avoid situations like this one. For example, you could create "linked packages" or similar such that you only update both at the same time.

In the past, I have always advocated anaconda and recommended it to friends and colleagues because it is easy to use and works mostly out-of-the-box, however, this is a real disappointment. I hope this is an exception, not the rule.

Also I have seen that those are actually delivered on different channels. One is from "anaconda" and the other from "conda-forge". I mean, what? Didn't anyone realize that this is a bad idea when it is actually important to keep updates synced between those packages?

**Comment by jjhelmus** [comment]
Torchvision 0.2.1 was added to the repository on May 14.  We try to keep up-to-date with changes and incompatibilities to the collection of software that we provide but occasionally we miss an important update.  In this case, we missed the update to torchvision when we updated pytorch to version 0.4.  Reports from the community, like yours, are an extremely helpful in finding these issues.
