### ISSUE TITLE
Xonsh 0.4.4 not installing via Navigatori 1.2.1 on OS X 10.11.5

### ISSUE THREAD

**Issue by Danilushka** [ContinuumIO/anaconda-issues#939]
The install button appears and when I click on it, a progress bar indicates activity.
But unlike other Navigator installs, the button does not change titles from Install to Launch.
Even with a reboot of Navigator and a reboot of OS X.
I checked the console, there are no error log messages indicating anything failed.

**Comment by goanpeca** [comment]
Hi @Danilushka, from what channel are you trying to install Xonsh?

**Comment by Danilushka** [comment]
Hi Gonzalo,

trying to instal directly from in the Navigator app (see image included below).
Notice the last panel on the right labeled "Xonshell' and the green-highlighted "Install" button.

<img width="1880" alt="screen shot 2016-07-25 at 2 23 41 pm" src="https://cloud.githubusercontent.com/assets/5448471/17117958/6e552eba-5273-11e6-8bce-346bae7a195f.png">

**Comment by goanpeca** [comment]
@Danilushka this should have been fixed in the latest release (1.3)

`conda update anaconda-navigator`

or

`conda update anaconda` to update to the latest anaconda version :-)
