### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by VAUTPL** [ContinuumIO/anaconda-issues#940]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - opencv ==2.4.8
  - tensorflow -> numpy >=1.10.1
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.1.9', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
The pacakges selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
