### ISSUE TITLE
Failed to create menus

### ISSUE THREAD

**Issue by mehraks** [ContinuumIO/anaconda-issues#9400]
Unable to install Anaconda3 5.0.1 on a machine running windows 10 64-bit OS as per the Anaconda Documentation. It shows error message "Failed to create menus".
I have uninstalled many times and new installation, but no success.
What is wrong with my installation? Please help me to resolve the installation issue.

**Comment by msarahan** [comment]
please see https://github.com/ContinuumIO/anaconda-issues/issues/3488 for more discussion and some workarounds that other users have found.

Closing as duplicate.
