### ISSUE TITLE
Unexpected warning for numpy.log1p on nump.NaN input when using MKL

### ISSUE THREAD

**Issue by trendelkampschroer** [ContinuumIO/anaconda-issues#9401]
### Actual Behavior

RuntimeWarning: invalid value encountered in log1p 

for large array of numpy.nan 

### Expected Behavior

No warning  should be issued for numpy.nan input irrespective of array size.

Using 
`
conda create -n no_err
source activate no_err
conda install -c conda-forge numpy
`
No warning is raised. It is possible that this is caused by NaN handling in log1p in Intel-MKL.

### Steps to Reproduce
`
conda create -n test
source activate test
conda install -c anaconda numpy
python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.14.3'
>>> x = np.nan * np.ones((10, 10))
>>> np.log1p(x)
array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])
>>> x = np.nan * np.ones((1000, 1000))
>>> np.log1p(x)
__main__:1: RuntimeWarning: invalid value encountered in log1p
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
`

##### Anaconda or Miniconda version:

conda --version
conda 4.5.2

##### Operating System:

macOS

##### `conda info`

```
active environment : test
    active env location : /Users/btschroer/.miniconda3/envs/test
            shell level : 1
       user config file : /Users/btschroer/.condarc
 populated config files : /Users/btschroer/.condarc
          conda version : 4.5.2
    conda-build version : 3.10.1
         python version : 3.6.3.final.0
       base environment : /Users/btschroer/.miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/othoz/osx-64
                          https://conda.anaconda.org/othoz/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/btschroer/.miniconda3/pkgs
                          /Users/btschroer/.conda/pkgs
       envs directories : /Users/btschroer/.miniconda3/envs
                          /Users/btschroer/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.3 Darwin/17.5.0 OSX/10.13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at /Users/btschroer/.miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2018.03.07                    0    anaconda
certifi                   2018.4.16                py36_0    anaconda
intel-openmp              2018.0.0                      8    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
mkl                       2018.0.2                      1    defaults
mkl_fft                   1.0.1            py36h917ab60_0    anaconda
mkl_random                1.0.1            py36h78cc56f_0    anaconda
ncurses                   6.1                  h0a44026_0    defaults
numpy                     1.14.3           py36h9d02e6b_0    anaconda
numpy-base                1.14.3           py36ha9ae307_0    anaconda
openblas                  0.2.20                        7    conda-forge
openssl                   1.0.2o               h26aff7b_0    anaconda
pip                       10.0.1                   py36_0    defaults
python                    3.6.5                hc167b69_1    defaults
readline                  7.0                  hc1231fa_4    defaults
setuptools                39.1.0                   py36_0    defaults
sqlite                    3.23.1               hf1716c9_0    defaults
tk                        8.6.7                h35a86e2_3    defaults
wheel                     0.31.1                   py36_0    defaults
xz                        5.2.3                h727817e_4    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```

**Comment by trendelkampschroer** [comment]
This is also happening for `np.expm1`.

**Comment by msarahan** [comment]
@oleksandr-pavlyk, is this expected or in any way harmful?

**Comment by trendelkampschroer** [comment]
This is harmful in sofar as it signals that there is a problem while there isn`t. numpy.nan should not signal on normal numeric operations.

This warning occurs also if applied to pandas.DataFrame s which is bad since there will usually be missing values reprrsented by numpy.nan which are expected to be propagated silently.

As pointed out above this does not occur for conda-forge builds which link against openblas not MKL. 

Probably the build with MKL treats non signaling NaNs (e.g numpy.nan) as signaling, at least for np.log1p and np.expm1. But, I am guessing here.

**Comment by WarrenWeckesser** [comment]
Another report of the issue, in the NumPy repository: https://github.com/numpy/numpy/issues/15206

**Comment by hjstein** [comment]
As I noted inhttps://github.com/numpy/numpy/issues/15206:

1. The issue is easily reproducible by creating an array of 8193 NaNs & doesn't occur with an array of 8192 NaNs.
2. `conda update numpy` upgraded numpy from 1.15.4 to 1.17.4.  After upgrading, the warning no longer occurs for me.

**Comment by trendelkampschroer** [comment]
The issue seems to be gone for `numpy-1.18.1-py38` from the `defaults` channel. Older builds, e.g `1.17.4-py38` , `1.16.5-py37`,  `1.15.4-py37`, all have the problem.

So the problem still persists. It would be very much appreciated if the changes in the `numpy-1.18.1-py38` build would be backported to builds for versions `1.15`, `1.16`, and `1.17` so that a fixed version for those packages is also available from the `defaults` channel.

**Comment by trendelkampschroer** [comment]
Closing this issue as it seems to be inactive.
