### ISSUE TITLE
Anaconda Navigator not opening Windows 10

### ISSUE THREAD

**Issue by abhikrish06** [ContinuumIO/anaconda-issues#9411]
### Actual Behavior
When trying to open Anaconda Navigator, I initially get a small terminal kind of window then nothing opens. And when I am trying 'conda update conda' it is giving me error

```
CorruptedEnvironmentError: The target environment has been corrupted. Corrupted environments most commonly occur when the conda process is force-terminated while in an unlink-link transaction.
  environment location: C:\Users\KRISHNA\Anaconda3
  corrupted file: C:\Users\KRISHNA\Anaconda3\conda-meta\anaconda-client-1.6.14-py36_0.json
```

### Expected Behavior
Anaconda Navigator should open.

### Steps to Reproduce
NA

##### Anaconda or Miniconda version:
conda 4.5.2
##### Operating System:
Windows 10
##### `conda info`

```
(base) C:\WINDOWS\system32>conda info

     active environment : base
    active env location : C:\Users\KRISHNA\Anaconda3
            shell level : 1
       user config file : C:\Users\KRISHNA\.condarc
 populated config files : C:\Users\KRISHNA\.condarc
          conda version : 4.5.2
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Users\KRISHNA\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\KRISHNA\Anaconda3\pkgs
                          C:\Users\KRISHNA\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\KRISHNA\Anaconda3\envs
                          C:\Users\KRISHNA\AppData\Local\conda\conda\envs
                          C:\Users\KRISHNA\.conda\envs
               platform : win-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
CorruptedEnvironmentError: The target environment has been corrupted. Corrupted environments most commonly
occur when the conda process is force-terminated while in an unlink-link
transaction.
  environment location: C:\Users\KRISHNA\Anaconda3
  corrupted file: C:\Users\KRISHNA\Anaconda3\conda-meta\anaconda-client-1.6.14-py36_0.json
```

**Comment by goanpeca** [comment]
Well it seems conda installation is corrupted. I would adive opening the Anaconda Prompt and trying to run

```
conda install anaconda-client=1.6.14 --force
```

And see if that solves the problem

**Comment by JoshiKumar** [comment]
I am having the same issue. The below force installation didn't help much. 

conda install anaconda-client=1.6.14 --force

**Comment by abhikrish06** [comment]
Yes, it did not resolve the issue. I am still getting the same error

`(base) C:\Users\KRISHNA>conda install anaconda-client=1.6.14 --force
Solving environment: failed

CorruptedEnvironmentError: The target environment has been corrupted. Corrupted environments most commonly occur when the conda process is force-terminated while in an unlink-link transaction.
  environment location: C:\Users\KRISHNA\Anaconda3
  corrupted file: C:\Users\KRISHNA\Anaconda3\conda-meta\anaconda-client-1.6.14-py36_0.json
`

**Comment by goanpeca** [comment]
@kalefranz ideas?

**Comment by goanpeca** [comment]
How about manually removing this file

`C:\Users\KRISHNA\Anaconda3\conda-meta\anaconda-client-1.6.14-py36_0.json`

**Comment by olivernina** [comment]
Removing the corrupted file seemed to work for me. Thanks

**Comment by jeffegg2** [comment]
Not working.......

**Comment by sreek011** [comment]
> pls help
> Anacond3 not opening in windows 10 also tried it from anaconda command prompt
> which gives this error
> 
> i tried updating - conda update conda
> conda update --all
> uninstall it with clean and reinstall but nothing works
> 
> Traceback (most recent call last):
> File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy__init__.py", line 204, in
> from PySide import **version** as PYSIDE_VERSION # analysis:ignore
> ModuleNotFoundError: No module named 'PySide'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\ProgramData\Anaconda3\Scripts\anaconda-navigator-script.py", line 6, in
> from anaconda_navigator.app.main import main
> File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in
> from anaconda_navigator.utils.conda import is_conda_available
> File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils__init__.py", line 15, in
> from qtpy.QtGui import QIcon
> File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy__init__.py", line 210, in
> raise PythonQtError('No Qt bindings could be found')
> qtpy.PythonQtError: No Qt bindings could be found



The following steps resolved the problem for me:

a. > 'conda install anaconda-clean' (Anaconda prompt was working) 

b. > 'anaconda-clean --yes' 

c. Uninstalled anaconda (current installation: 2020.02) (windows control panel, add remove programs, uninstall)

d. Entries (anaconda, spyder, python etc...) in windows registry removed

e. Deleted files and folders persisting after uninstall. - Launch windows file explorer, go to root directory under which anaconda was installed ), In my case C: (windows) drive. Search with key words anaconda, python, spyder etc. Folders and files persisting after anaconda installation were listed in the search results. Delete all persisting files and folders

f. Installed Newer version, 2020.02 (installed with default/ recommended options) 

z. Outcome  - problem resolved.
