### ISSUE TITLE
Navigator install package Error

### ISSUE THREAD

**Issue by byersiiasa** [ContinuumIO/anaconda-issues#942]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - fiona ==1.6.0
  - gdal ==2.1.0 -> libgdal 2.1.0
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 62 Stepping 4, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by ilanschnell** [comment]
The (old) version of fiona we have on the repository is not compatible with gdal 2.1.0.  We have created a new compatible version of fiona for Unix, but not on Windows yet.

**Comment by byersiiasa** [comment]
Ok thanks

**Comment by goanpeca** [comment]
To learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
