### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ahmetanildindar** [ContinuumIO/anaconda-issues#943]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - basemap ==1.0.7
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.2', 'qt': '4.8.7', 'language': 'tr_TR', 'platform': 'win-64', 'conda': '4.1.6', 'pyqt': '4.11.4', 'version': '1.2.1', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
