### ISSUE TITLE
Html syntax error

### ISSUE THREAD

**Issue by Myjordans** [ContinuumIO/anaconda-issues#9431]
Hi im pasting a basic code in jupyterlab and it's giving me a syntax error
<!DOCTYPE html>
< html>
< head>
< title>Page Title</title>
< /head>
< body>

<..h1>header</h1>

< p>This is a paragraph.</p>

</ .body>
</ .html> dont mind the spaces and .. its just to show you guys the code
----------------------------------------------------------------------------------------------
 File "<ipython-input-2-b9136dccb7b2>", line 1
    <html>
    ^
SyntaxError: invalid syntax

feels like something needs to be installed, not really sure why it's not working

**Comment by mingwandroid** [comment]
This has nothing to do with Anaconda Distribution.
