### ISSUE TITLE
Navigator Error while attempting to install Mosaic

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#944]
Application action error

/Users/ijstokes/anaconda/bin/python /Users/ijstokes/anaconda/bin/conda install --yes --json --force-pscheck --prefix /Users/ijstokes/anaconda anaconda-mosaic=1.3.1: The following specifications were found to be in conflict:
  - anaconda-mosaic 1.3.1*
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.1.6', 'qt': '4.8.6', 'language': 'en_US', 'python': '2.7.10', 'os': 'Darwin;15.5.0;Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.3'}

<img width="704" alt="screenshot 2016-07-26 10 51 34" src="https://cloud.githubusercontent.com/assets/293525/17142668/f80ffe4a-531e-11e6-903d-4b252dbf1e9d.png">

**Comment by goanpeca** [comment]
This has been fixed in the latest navigator
