### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by carloslesmes** [ContinuumIO/anaconda-issues#946]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - anaconda-build ==1.15.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'python': '3.5.1', 'version': '1.2.1', 'language': 'en', 'pyqt': '4.11.4', 'conda': '4.1.6', 'platform': 'osx-64', 'qt': '4.8.7', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
