### ISSUE TITLE
Anaconda does not install pyqt5 dependencies on Ubuntu 18.04

### ISSUE THREAD

**Issue by sirredbeard** [ContinuumIO/anaconda-issues#9465]
### Actual Behavior

After installing anaconda from the [Anaconda website](https://www.anaconda.com/download/#linux) on Ubuntu 18.04 something is amiss with pyqt5 dependencies. 

Spyder will not run:  https://gist.github.com/sirredbeard/2870f8d2948365b9b6cf653d55327e7c

### Expected Behavior

The anaconda installer would properly install pyqt5 dependencies.

### Steps to Reproduce

$ aria2c -x 5 "https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh"
$ chmod u+x Anaconda3-5.1.0-Linux-x86_64.sh
$ ./Anaconda3-5.1.0-Linux-x86_64.sh
$ spyder

### Workaround

$ sudo apt-get install python3-pyqt5 -y
$ spyder

##### `conda info`

```
conda info

     active environment : None
       user config file : /home/hayden/.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /home/hayden/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/hayden/anaconda3/pkgs
                          /home/hayden/.conda/pkgs
       envs directories : /home/hayden/anaconda3/envs
                          /home/hayden/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Linux/4.4.0-17134-Microsoft ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

https://github.com/ContinuumIO/anaconda-issues/files/2043433/output.txt

I get the same even after running updates on conda and all packages.

**Comment by ccordoba12** [comment]
That is not a problem with Spyder but with a faulty graphics card driver.

This will be fixed in the next Spyder version, but to be able to use it for now please open a terminal (konsole, xterm, etc) an run there

    conda install pyopengl

**Comment by sirredbeard** [comment]
Thank you.
