### ISSUE TITLE
Anaconda installer should run updates as part of installation

### ISSUE THREAD

**Issue by sirredbeard** [ContinuumIO/anaconda-issues#9466]
### Actual Behavior

The [Anaconda installer for Linux](https://www.anaconda.com/download/#linux) does not check for updates after installing.

### Expected Behavior

At the end of installation, the Anaconda installer should update Anaconda and all default packages.

A user should always have the most up to date version of the environment when finished installing.

One of the advantages of Anaconda is how up to date it's packages always are.

The installer script should incorporate:

$ conda update -n base conda

$ conda update --all

**Comment by mingwandroid** [comment]
Other people use Anaconda differently. Having an *option* to update I would support though but forcing it on everyone is not something we could contemplate.

**Comment by sirredbeard** [comment]
Is the installer script open source? I can't locate it in the repo.

It just seems weird users will download Anaconda from the website, install it, launch Spyder, and then get told that their version of Spyder is 2-3 version out of date.

And let's be honest, updating Anaconda apps isn't the easiest either.
