### ISSUE TITLE
import multiarray ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by lakshmisivareddy** [ContinuumIO/anaconda-issues#9469]
Hi i am getting below error

 i tried changing python & numpy versions but nothing worked out

\Anaconda3\envs\MYML\lib\site-packages\numpy\core_init_.py", line 16, in  from . import multiarray ImportError: DLL load failed: The specified module could not be found

i am using numpy : 1.14.3
python : 3.6.5

**Comment by mingwandroid** [comment]
Closing due to requested by not provided information.
