### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by daiabg** [ContinuumIO/anaconda-issues#9491]
Hi 

I just installed Anaconda and Jupyter Notebooks. When installing fProphet I have got this error and I tried to fix it by uninstalling Anaconda and reinstalling it again.

![image](https://user-images.githubusercontent.com/39795708/40776084-aad0a254-64c1-11e8-9b7a-75dc990be2e5.png)

Can you please help?

**Comment by nehaljwani** [comment]
@daiabg Looks like you installed Anaconda for all users? Could you try running the Anaconda prompt as admin?

**Comment by daiabg** [comment]
Hi

@nehaljwani thank you for your response. It works on admin but everything is saved on the root. I just started using Anaconda and I do not know how can I use fprophet without being an admin.

Is there anything I can do?

Thank you
Daiana

**Comment by goanpeca** [comment]
@daiabg you have 2 options:

1.) Install Anaconda for the current user and **not** for All users
2.) Create a new environment (not root) with packages you need and run things from within that environment
