### ISSUE TITLE
libgdal missing xz dependency

### ISSUE THREAD

**Issue by dougalsutherland** [ContinuumIO/anaconda-issues#951]
I previously had xz 5.0.5-1 installed (on OSX 10.11.6). I just did `conda install fiona`, which pulled in a bunch of related stuff including gdal but nothing related to xz or lzma. `import fiona` then gave:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-cc872b235141> in <module>()
----> 1 import fiona

/usr/local/anaconda/lib/python2.7/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/usr/local/anaconda/lib/python2.7/site-packages/fiona/collection.py in <module>()
      5 import sys
      6 
----> 7 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      8 from fiona.ogrext import Session, WritingSession
      9 from fiona.ogrext import (

ImportError: dlopen(/usr/local/anaconda/lib/python2.7/site-packages/fiona/ogrext.so, 2): Library not loaded: @rpath/./liblzma.5.dylib
  Referenced from: /usr/local/anaconda/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
```

After `conda update xz`, which gave me 5.2.2, it works.

Seems like libgdal should have a version dependency on xz.

**Comment by eronlloyd** [comment]
Any updates on this?

**Comment by fspaolo** [comment]
Same here. I installed 'gdal' using 'conda install -c conda-forge gdal', which gave me:

    python -c "import gdal"
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/fpaolo/anaconda2/lib/python2.7/site-packages/gdal.py", line 2, in <module>
        from osgeo.gdal import deprecation_warn
      File "/Users/fpaolo/anaconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
        _gdal = swig_import_helper()
      File "/Users/fpaolo/anaconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
        _mod = imp.load_module('_gdal', fp, pathname, description)
    ImportError: dlopen(/Users/fpaolo/anaconda2/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/liblzma.5.dylib
      Referenced from: /Users/fpaolo/anaconda2/lib/libgdal.20.dylib
      Reason: Incompatible library version: libgdal.20.dylib requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

I then did 'conda update xz', which then gave me a different error:

    python -c "import osgeo"
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/fpaolo/anaconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
        _gdal = swig_import_helper()
      File "/Users/fpaolo/anaconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
        _mod = imp.load_module('_gdal', fp, pathname, description)
    ImportError: dlopen(/Users/fpaolo/anaconda2/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Symbol not found: __ZN2H56H5FileC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEjRKNS_17FileCreatPropListERKNS_15FileAccPropListE
      Referenced from: /Users/fpaolo/anaconda2/lib//libkea.1.4.6.dylib
      Expected in: /Users/fpaolo/anaconda2/lib//libhdf5_cpp.12.dylib
     in /Users/fpaolo/anaconda2/lib//libkea.1.4.6.dylib

However, replacing the 'conda' installation by the 'pip' installation ('conda uninstall gdal' and 'pip install gdal') makes everything run smoothly.

**Comment by nehaljwani** [comment]
This is fixed by https://github.com/ContinuumIO/anaconda/commit/bc1dbef54fb809af6794136d4a850125e489acb9

`libtiff=4.0.6=0` depends on `xz=5.0.5` and this was fixed after rebuilding the packaging and bumping the build number to 1. So now `libtiff=4.0.6=1` depends on `xz 5.2.*`. So this should automatically be fixed for all new installations of `fiona`. For existing installations, update `libtiff` to >= `4.0.6-2` which will automatically bump `xz`
