### ISSUE TITLE
Python compiled without the `--with-ensurepip=install` flag.

### ISSUE THREAD

**Issue by ostrokach** [ContinuumIO/anaconda-issues#952]
When I try to create a virtual environment using `venv` from Anaconda Python 3.5, I get the following error:

```
$ pyvenv myvenv
Error: Command '['/home/username/mypackage/myvenv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
```

It seems that this is due to Python being compiled [without the `--with-ensurepip=install` flag](http://stackoverflow.com/a/22594608/2063031).

Maybe this is something that could be fixed in the next Anaconda release? Or is this intentional?

**Comment by ilanschnell** [comment]
The reason Python isn't compiled with `--with-ensurepip=install` is because pip (and it's setuptools dependency) are installed independent of Python as conda packages.  By default, the `python` depends on `pip`.  This is handled by conda, and can be disabled by setting, in `~/.condarc`:
```
anaconda_upload: False
```

**Comment by ddearauj** [comment]
Hi, I have the same problem. I edited my `.condarc` file and I still get the same error

**Comment by leafonsword** [comment]
It seems after install python using conda, setting `anaconda_upload: False` doesn't help~

**Comment by ks7000** [comment]
I had this problem too, please, with all due respect, read my comment at:
[https://github.com/ContinuumIO/anaconda-issues/issues/6917#issuecomment-346909681](url)
