### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tofol** [ContinuumIO/anaconda-issues#955]
Application action error

C:\Anaconda3\python.exe C:\Anaconda3\Scripts\conda-script.py install --yes --json --force-pscheck --prefix C:\Anaconda3 spyder=2.3.9: The following specifications were found to be in conflict:
  - spyder 2.3.9*
  - spyder-app -> python 2.7*|3.4*
  - spyder-app -> spyder 2.2.0|2.2.4|2.2.5|2.3.0|2.3.0rc1|2.3.1|2.3.2|2.3.3|2.3.4|2.3.5.2|2.3.6|2.3.7|2.3.8
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel', 'python': '3.5.2', 'version': '1.2.2', 'conda': '4.1.11', 'pyqt': '4.11.4', 'qt': '5.6.0', 'language': 'es_ES'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
