### ISSUE TITLE
While installing anconda 5.2.0 , i am getting this error at the end and Installation get Aborted

### ISSUE THREAD

**Issue by extendann** [ContinuumIO/anaconda-issues#9558]
![anac](https://user-images.githubusercontent.com/36704059/41190050-5c67ad16-6bf5-11e8-9be7-38e150232a7b.png)

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by nehaljwani** [comment]
@extendann Do you get the same error when you try to install it for not 'all users'? Do you see the same error when you install it to a custom, specific location?
