### ISSUE TITLE
Make starting directory for Jupyter Notebook configurable from Navigator

### ISSUE THREAD

**Issue by HeatherHaveman** [ContinuumIO/anaconda-issues#9562]
This is a suggestion.  It would reduce the # of questions (lots & lots on stackoverflow) about this, which would be especially useful for those who aren't familiar with machine structures in any detail -- i.e., the vast majority of PC & Mac users.

**Comment by goanpeca** [comment]
This is a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/983
