### ISSUE TITLE
/usr/bin/ld: this linker was not configured to use sysroots

### ISSUE THREAD

**Issue by himanshu04s** [ContinuumIO/anaconda-issues#9564]
Hello,
I am trying to install a code named as GPAW using anaconda Python-2.17.15 on CentOS7. While building it, I stuck on an error "/usr/bin/ld: this linker was not configured to use sysroots"

I am not getting the solution. The output is shown below:

[root@localhost gpaw-1.4.0]# python setup.py install --home='/opt/gpaw-1.4.0'
.git directory not found. GPAW git hash not written.
running install
running build
running build_py
running build_ext
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/bc.o -c c/bc.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/localized_functions.o -c c/localized_functions.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/mpi.o -c c/mpi.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/_gpaw.o -c c/_gpaw.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/operators.o -c c/operators.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/woperators.o -c c/woperators.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/transformers.o -c c/transformers.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/blacs.o -c c/blacs.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/utilities.o -c c/utilities.c 
mpicc -DNPY_NO_DEPRECATED_API=7 -DPARALLEL=1 -DGPAW_INTERPRETER=1 -Wall -Wno-unknown-pragmas -std=c99 -fPIC -I/opt/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda2/include/python2.7 -I/opt/anaconda2/include/python2.7 -o build/temp.linux-x86_64-2.7/c/xc/libvdwxc.o -c c/xc/libvdwxc.c 
mpicc -o build/bin.linux-x86_64-2.7//gpaw-python build/temp.linux-x86_64-2.7/c/_gpaw.o build/temp.linux-x86_64-2.7/c/bc.o build/temp.linux-x86_64-2.7/c/blacs.o build/temp.linux-x86_64-2.7/c/blas.o build/temp.linux-x86_64-2.7/c/bmgs/bmgs.o build/temp.linux-x86_64-2.7/c/cerf.o build/temp.linux-x86_64-2.7/c/fftw.o build/temp.linux-x86_64-2.7/c/lapack.o build/temp.linux-x86_64-2.7/c/lcao.o build/temp.linux-x86_64-2.7/c/lfc.o build/temp.linux-x86_64-2.7/c/lfc2.o build/temp.linux-x86_64-2.7/c/localized_functions.o build/temp.linux-x86_64-2.7/c/mlsqr.o build/temp.linux-x86_64-2.7/c/mpi.o build/temp.linux-x86_64-2.7/c/operators.o build/temp.linux-x86_64-2.7/c/plane_wave.o build/temp.linux-x86_64-2.7/c/plt.o build/temp.linux-x86_64-2.7/c/point_charges.o build/temp.linux-x86_64-2.7/c/spline.o build/temp.linux-x86_64-2.7/c/symmetry.o build/temp.linux-x86_64-2.7/c/tetra.o build/temp.linux-x86_64-2.7/c/transformers.o build/temp.linux-x86_64-2.7/c/utilities.o build/temp.linux-x86_64-2.7/c/wigner_seitz.o build/temp.linux-x86_64-2.7/c/woperators.o build/temp.linux-x86_64-2.7/c/xc/ensemble_gga.o build/temp.linux-x86_64-2.7/c/xc/libvdwxc.o build/temp.linux-x86_64-2.7/c/xc/libxc.o build/temp.linux-x86_64-2.7/c/xc/m06l.o build/temp.linux-x86_64-2.7/c/xc/pbe.o build/temp.linux-x86_64-2.7/c/xc/pw91.o build/temp.linux-x86_64-2.7/c/xc/revtpss.o build/temp.linux-x86_64-2.7/c/xc/revtpss_c_pbe.o build/temp.linux-x86_64-2.7/c/xc/rpbe.o build/temp.linux-x86_64-2.7/c/xc/tpss.o build/temp.linux-x86_64-2.7/c/xc/vdw.o build/temp.linux-x86_64-2.7/c/xc/xc.o build/temp.linux-x86_64-2.7/c/xc/xc_mgga.o  -L/opt/anaconda2/lib/python2.7/config -lxc -lblas -llapack -L. -lpython2.7 -lpthread -ldl -lutil -lm  -Wl,--no-as-needed -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lmkl_blacs_intelmpi_lp64 -L/opt/anaconda2/lib -Wl,-rpath=/opt/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Xlinker -export-dynamic
/usr/bin/ld: this linker was not configured to use sysroots
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "setup.py", line 260, in <module>
    'Topic :: Scientific/Engineering :: Physics'])
  File "/opt/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/opt/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/opt/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 212, in run
    assert error == 0
AssertionError

**Comment by l4m1a4** [comment]
I'm facing the same issue with Anaconda 3. Have you solved the problem?
