### ISSUE TITLE
Missing anaconda builds for scipy 0.18 on win32/win64

### ISSUE THREAD

**Issue by ssanderson** [ContinuumIO/anaconda-issues#957]
c.f. https://anaconda.org/anaconda/scipy/files?version=0.18.0

There are conda packages for win32/win64 for older versions of scipy, and there are conda packages for the latest scipy for osx64 and linux32/64.  Is it intentional that there's no recent of scipy for windows?

**Comment by csoja** [comment]
These are available now.
