### ISSUE TITLE
anaconda navigator crashes on launch on mac os x 10.9.5

### ISSUE THREAD

**Issue by Ramshakamal22** [ContinuumIO/anaconda-issues#9582]
on trying to open the anaconda navigator from terminal , i got this traceback errorTraceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtpy/__init__.py", line 169, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/anaconda-navigator", line 7, in <module>
    from anaconda_navigator.app.main import main
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/anaconda3/lib/python3.6/site-packages/qtpy/__init__.py", line 175, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

i also tried updating anaconda by 
$ conda update --all
 tried installing and re-installing it several times, but the anaconda icon appears on the dock and just disappears.
this is the result for conda info-
active environment : None
       user config file : /Users/Mac/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : 3.10.7
         python version : 3.6.5.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda3/pkgs
                          /Users/Mac/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/Mac/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Darwin/13.4.0 OSX/10.9.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by Ramshakamal22** [comment]
the version of python i installed is 3.6 and anaconda version is 5.2

**Comment by mingwandroid** [comment]
macOS 10.9 is no longer supported (though many things will still work, however anything that uses Qt will not). 10.10 is the current minimum.
