### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vinaysannaiah** [ContinuumIO/anaconda-issues#9586]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
/home/vinay/anaconda3/envs/virtual_platform/lib/python3.5/site-packages/numexpr/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version

```
## System information
```
python: 3.5.4
version: 1.6.2
conda: 4.5.4
language: en_US
pyqt: None
os: Linux;4.15.0-23-generic;#25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018;x86_64;x86_64
qt: 5.10.1
platform: linux-64
```

**Comment by goanpeca** [comment]
@vinaysannaiah please open the terminal and update conda and the packages.

```
conda update conda
conda update --all
```

**Comment by usherbob** [comment]
@vinaysannaiah Did you fix your problem. I met a similar error after my python version was downgraded from 3.7 to 3.6. I update my anaconda navigator, it could work though it gave an error
`
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
`
However, the spyder under root enviironment still not work(where the version of python was downgraded from 3.7 to 3.6). Spyder in other environment could work normally. So are there some suggestions/

**Comment by ZhongmouLi** [comment]
Hi, I met the same problem. Have your solved this?
