### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by singh4jitendra** [ContinuumIO/anaconda-issues#9602]
## Main error
The following errors occurred:
## Traceback
```

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
