### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by boustrephon** [ContinuumIO/anaconda-issues#9603]
### Actual Behavior

[W 15:17:40.510 LabApp] server_extensions is deprecated, use nbserver_extensions
[I 15:17:42.064 LabApp] The port 8888 is already in use, trying another port.
[I 15:17:42.135 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 15:17:42.279 LabApp] JupyterLab beta preview extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 15:17:42.279 LabApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
[I 15:17:42.495 LabApp] Serving notebooks from local directory: C:\
[I 15:17:42.495 LabApp] 0 active kernels 
[I 15:17:42.495 LabApp] The Jupyter Notebook is running at: http://localhost:8889/?token=00388cc59c31484d0a910e149b29ffb0ce2db64e83b3a44c
[I 15:17:42.496 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:17:42.502 LabApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8889/?token=00388cc59c31484d0a910e149b29ffb0ce2db64e83b3a44c
[I 15:17:42.767 LabApp] Accepting one-time-token-authenticated connection from ::1
[I 15:17:44.454 LabApp] Refusing to serve hidden directory 'C:\\', via 404 Error
[W 15:17:44.454 LabApp] directory does not exist: ''
[W 15:17:44.455 LabApp] 404 GET /api/contents/?content=1&1528960664302 (::1) 2.00ms referer=http://localhost:8889/lab
[I 15:17:44.479 LabApp] Build is up to date

### Expected Behavior

Should have opened Jupyter Lab - could not because it was trying to get a listing from the C:\ root.

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@blink1072

**Comment by blink1073** [comment]
It looks like an unresolved issue with the notebook server, cf https://github.com/jupyter/notebook/pull/1168#issuecomment-230777153.

**Comment by boustrephon** [comment]
I don’t mind not being able to start Jupyter notebooks in C:. However, I would like to know how to get Anaconda Navigator to start up notebooks somewhere other than C:. Is there a setting somewhere that I can change?

**Comment by goanpeca** [comment]
> Is there a setting somewhere that I can change? 

Not at the moment, the user home folder is the (fixed) default atm
