### ISSUE TITLE
sysconfig.py skipping  {_CONDA}_PYTHON_SYSCONFIGDATA_NAME

### ISSUE THREAD

**Issue by rainwoodman** [ContinuumIO/anaconda-issues#9621]
Currently, the sysconfig.py shipped with python-3.6.5 skips `_CONDA_PYTHON_SYSCONFIGDATA_NAME` and `_PYTHON_SYSCONFIGDATA_NAME`.

No matter if the behavior is expected, it is currently triggered by a bug. When `check_exists=True`, the name importlib is undefined at line 350.

This occurs if the code flow runs through `_init_posix` at line 427, which calls _get_sysconfigdata_name(True).

This may affect other python versions as well.

I ran into this while trying to override LDSHARED in the wrapper conda package for compiling with Cray's prgenv-gnu. If it is not overridden as the Cray compilers (cc/CC), then the linker picked by Python, gcc,  produces a shared object that is missing the MPI libraries. This is likely causing pytorch (with MPI distributed backend) to fail at runtime.

**Comment by mingwandroid** [comment]
Please provide details asked for in the template. This was fixed a while ago.

**Comment by mingwandroid** [comment]
You probably need to update python in your base enviornment.

Can you detail what you mean by 'other python versions'? Do you mean ones not from AD, because if you do that's not something we support to any large extent.

**Comment by rainwoodman** [comment]
I am using
```
python                    3.6.5                hc3d631a_2 
```

The function body  in sysconfig.py is

```
def _get_sysconfigdata_name(check_exists=False):
    for envvar in ('_PYTHON_SYSCONFIGDATA_NAME', '_CONDA_PYTHON_SYSCONFIGDATA_NAME'):
        res = os.environ.get(envvar, None)
        if res and check_exists:
            try:
                loader = importlib.util.find_spec(res)
            except:
                res = None
        if res:
            return res
    return '_sysconfigdata_{abi}_{platform}_{multiarch}'.format(
            abi=sys.abiflags,
            platform=sys.platform,
            multiarch=getattr(sys.implementation, '_multiarch', ''))
```

The only place importlib is mentioned in the file is in this function. So the import line will always fail.

'other version' I mean other conda patched versions of Python packages on the anaconda channel, e.g. 2.7 or 3.5.

**Comment by rainwoodman** [comment]
The vanilla version of the function (from cpython master branch) is
```
def _get_sysconfigdata_name():
    return os.environ.get('_PYTHON_SYSCONFIGDATA_NAME',
        '_sysconfigdata_{abi}_{platform}_{multiarch}'.format(
        abi=sys.abiflags,
        platform=sys.platform,
        multiarch=getattr(sys.implementation, '_multiarch', ''),
))
```

**Comment by mingwandroid** [comment]
Thanks for the bug report.

If you add `import importlib.util` just above `loader = importlib.util.find_spec(res)` does it work ok for you here?

**Comment by rainwoodman** [comment]
Yes. This bug is fixed by adding the import -- I think I checked this. 

However, I suspect I am not solving my original problem in a correct way:

If I provide a new sysconf in my compiler package, (even after this fix), then in ``meta.yaml`` I am forced to declare the compilers in the host section too. Otherwise the sysconf file is not installed to the host environment. That's not right, because the compilers may not even exist for the host platform.

Does it mean I shall also install python to the build environment when an C extension is built?

**Comment by mingwandroid** [comment]
Compilers are meant to be specified in the build section. Closing as 3.7 and 3.6.6 will add `import importlib.util`

**Comment by mingwandroid** [comment]
3.6.6 is now available as is 3.7.0.

**Comment by rainwoodman** [comment]
Thanks. 

Is it good practice or not for customized compiler packages to override ``_CONDA_PYTHON_SYSCONFIGDATA_NAME``?

**Comment by mingwandroid** [comment]
> Is it good practice or not for customized compiler packages to override _CONDA_PYTHON_SYSCONFIGDATA_NAME?

Yes. I think it's a good idea to think carefully about your flags etc, there's no reason some compiler package (or sub/split package) cannot add files to the python installation paths for your exact compiler name/config.

It's what we do after all!

**Comment by rainwoodman** [comment]
There is an issue with adding a new sysconfig file from a compiler package with the current recommended practices:

 - the compiler package shall be installed to the build env, and the new sysconfig file is installed to the build env.

 - python shall be installed to the host env. But then python doesn't actually see the new sysconfig file.

 - if python is installed to the build env, and used for building, then the software will be installed to the build env and produce an empty package.

 - if we provide a different package that provides the sysconfig file, then there is no clean way to add it to `hosts` section -- there is no jinja macro (c_compiler, etc) for this.

**Comment by mingwandroid** [comment]
You are meant to use $PYTHON or %PYTHON%, not `python`.

`_CONDA_SYSCONFIGDATA_NAME` is not a full path, it is just a module name.

**Comment by rainwoodman** [comment]
Sorry I forgot to add this. Using $PYTHON picks up the python in the host env, but it still doesn't find the sysconfig file in the build env.

**Comment by mingwandroid** [comment]
I don't understand still, as I said, `_CONDA_PYTHON_SYSCONFIGDATA_NAME` is just a module name it is not associated with any python in particular and since our python is in both your host env and your build env and both have this module name this detail should not matter.

**Comment by rainwoodman** [comment]
The physical file of the module is installed with the compiler to the build env. The host env python can't find it.

**Comment by mingwandroid** [comment]
The physical file exists in both pythons and is never identified by a full filename, therefore either python can find this module, depending on which you run. At this point you need to provide me with a test case if possible.

**Comment by rainwoodman** [comment]
Here is a test case:

[anaconda-9621.tar.gz](https://github.com/ContinuumIO/anaconda-issues/files/2151270/anaconda-9621.tar.gz)
