### ISSUE TITLE
OSX import pymouse

### ISSUE THREAD

**Issue by CamAust** [ContinuumIO/anaconda-issues#9627]
Seeking to import, use pymouse. 

Circumstances:
I have a small programing task that I am not yet sure if I can achieve easiest in unix bash, or python.  For this task, I need to receive input when the mouse/trackpad is clicked. Hence I have sought to use pymouse as an import into python. 

Yesterday downloaded latest Mac OSX version of Anaconda 3.  Installed.  
Just prior to this, also yesterday, from Terminal, I ran pip to install pymouse.  

From what I can see, both from Terminal and Jupyter, the latest Anaconda 3 installation complete package is being access, hence I am not sure that my previous pip install of pymouse has created a conflict, and hence is the cause of the issue. 

Note - not yet a coder.  Learning. 

### Actual Behavior

In terminal - launching python, and seeking to  import pymouse leads to the following ..

    python
    Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
    [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pymouse
       Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "/anaconda3/lib/python3.6/site-packages/pymouse/__init__.py", line 89, in <module>
          from mac import PyMouse, PyMouseEvent
    ModuleNotFoundError: No module named 'mac'
    >>> 

Similarly if run in Jupyter.

<img width="1099" alt="screen shot 2018-06-18 at 1 55 42 pm" src="https://user-images.githubusercontent.com/22573697/41517614-a87e4794-72ff-11e8-952c-39a01613a6c3.png">

line 88 & 89 of pymouse is as follows - the OSX "darwin" if else .. 

    elif sys.platform == 'darwin':
    from mac import PyMouse, PyMouseEvent

mac is installed as part of the package, and the mac.py files in in the pymouse folder so I am not sure why it is not being recognised, unless in line above should read:

    from mac.py import PyMouse, PyMouseEvent

(Do not know enough python yet.)

<img width="741" alt="screen shot 2018-06-18 at 2 06 10 pm" src="https://user-images.githubusercontent.com/22573697/41517773-e7556f96-7300-11e8-84a9-42b5215e4cfa.png">

### Expected Behavior

import pymouse will run without error. 

### Steps to Reproduce
With latest Anaconda package installed on OSX, run python from Terminal or, in Jupyter, and enter
    import pymouse

##### Anaconda or Miniconda version:
Anaconda 3, downloaded yesterday. 

##### Operating System:
OSX 10.11.6

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by CamAust** [comment]
I think this will prove a simple quick issue to resolve for a more experienced person.

**Comment by jjhelmus** [comment]
This error is not a result of Anaconda or conda packages but rather the pymouse, please raise this question with that project.

**Comment by CamAust** [comment]
I tried that first. The project no longer exists and has been worked into a new project.  It appeared to me that his package is downloaded and part of the anaconda package.  Are you sure?

**Comment by jjhelmus** [comment]
> I ran pip to install pymouse

Using pip to install pymouse means that the package is not coming from Anaconda but rather from PyPI.  The files may appear in the anaconda directory on your system but they were not placed their by conda.

**Comment by CamAust** [comment]
Ah, that is very helpful.  So if I can remove the pip install, and replace with an anaconda fresh install, that may resolve the issue.
