### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [ContinuumIO/anaconda-issues#9637]
## Main error
The following errors occurred:
## Traceback
```

```
## System information
```
python: 3.6.1
language: es_PE
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
