### ISSUE TITLE
Keras where can i get it

### ISSUE THREAD

**Issue by muk07** [ContinuumIO/anaconda-issues#9639]
I do not see Keras among available packages

**Comment by jjhelmus** [comment]
@muk07 What platform and conda version are you using?  `keras` packages are available on 64-bit versions of Windows, Linux and macOS.

**Comment by muk07** [comment]
win7 - 6420.06.2018, 19:19, "Jonathan J. Helmus" <notifications@github.com>:@muk07 What platform and conda version are you using?  keras packages are available on 64-bit versions of Windows, Linux and macOS.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


М.Катаргин

**Comment by jjhelmus** [comment]
If you installed the 64-bit version of Anaconda/Miniconda on Windows you can install keras by typing `conda install keras` from the command line.

If this does not work, please provide the information requested in the issue template, namely, the output of`conda info` and `conda list --show-channel-urls`.
