### ISSUE TITLE
Navigator Error Failed to install traits and traitsui

### ISSUE THREAD

**Issue by wuhongyewhy** [ContinuumIO/anaconda-issues#964]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
- python 3.5*
- traits ==4.5.0
  Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'qt': '4.8.7', 'version': '1.2.2', 'conda': '4.1.11', 'python': '3.5.2', 'os': 'Windows;7;6.1.7600;AMD64;Intel64 Family 6 Model 26 Stepping 4, GenuineIntel', 'pyqt': '4.11.4', 'language': 'zh_CN'}

**Comment by goanpeca** [comment]
Hi @wuhongyewhy the packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)

Please download the latest version of navigator (1.3.2)

On the command prompt you can type:

`conda update anaconda-navigator`

or you can also update to the latest anaconda distribution (4.2) by typing:

`conda update anaconda`
`conda update anaconda-navigator`

Cheers
