### ISSUE TITLE
Can't open anaconda-navigator: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

### ISSUE THREAD

**Issue by chaiheng753** [ContinuumIO/anaconda-issues#9644]
### Actual Behavior

I have completed the Anaconda installation, closed the Ubuntu 18.04 terminal and reopened the terminal, then typed anaconda-navigator and I received error message as follows.

1. Navigator doesn't open, so I am not sure if the installation is successful or not.  
2. Can anyone help to solve this issue?

##### `conda info`

```
chaiheng753@heng:~$ anaconda-navigator
anaconda-navigator: command not found
chaiheng753@heng:~$ sudo su
[sudo] password for chaiheng753:
root@heng:/home/chaiheng753# anaconda-navigator
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

**Comment by mingwandroid** [comment]
Please do not run as super user. This is causing problems with connecting
to your display. In general never run as super user, only use that when
doing administrative tasks on your computer.

**Comment by chaiheng753** [comment]
If I do not run as a super user, the Ubuntu terminal returns the following error:

chaiheng753@heng:~$ anaconda-navigator
anaconda-navigator: command not found

Can you please tell me how should I run the anaconda-navigator, if I don't sudo su? Thank you.

**Comment by nehaljwani** [comment]
@chaiheng753 Which path did you install it to?

**Comment by chaiheng753** [comment]
@nehaljwani I am using Ubuntu 18.04 on Windows 10. This is where I installed Anaconda3:

C:\Users\Lim\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\root\anaconda3

If I don't run it as a super user, can you please let me know how should I run the anaconda-navigator? Thank you.

**Comment by nehaljwani** [comment]
@chaiheng753 Are you using WSL? Why not install Anaconda on Windows natively?

**Comment by chaiheng753** [comment]
@nehaljwani I installed Ubuntu on Windows 10. I guess that's WSL, isn't it. Yeah, I installed Anaconda on Windows as well. Thank you :)
