### ISSUE TITLE
Anaconda C compiler (Linux) activation script should set env LDSHARED

### ISSUE THREAD

**Issue by marscher** [ContinuumIO/anaconda-issues#9667]
Hi,

this variable is being used by distutils to determine the the linker used for building shared libraries on posix like platforms. If it is not present, the linker will be derived from the LD variable, which truncates the absolute paths to the linker. This leads to using the wrong linker, if gcc is present outside of the environment.

A workaround for me was to set LDSHARED to "$CC -shared"

The affected packages would presumably be gcc_linux-64 or gcc_impl_linux-64 (7.2.0)

Thanks for looking into this.

**Comment by mingwandroid** [comment]
Distutils uses the `sysconfig` module for this stuff. `LDSHARED` is set in that.

**Comment by marscher** [comment]
LDSHARED will be evaluated and set to a backup there, but the highest priority is from the environment variable. So if not set, LDSHARED will point to the wrong linker, because Anaconda compilers variables are using absolute paths to the tools instead of setting PATH accordingly. This breaks assumptions in sysconfig.

**Comment by mingwandroid** [comment]
> The first command to generate the object code is utilizing an absolute path to the compiler, while the linker invocation uses $PATH to resolve the linker

You appear to have things very badly messed up on your system. Running our compilers should not run gcc at all. I am assuming you have some mix of env vars pointing to conda tools and other env vars pointing to system tools. This is not supported.

Your recommendation about setting `LDSHARED` is not something I will do. It seems to be some hack to work around local problems.

Clearly we are able to build lots of Python software with things setup as they are.

**Comment by marscher** [comment]
I'm using the miniconda3 docker container of your company :) Problems
first appeared as this container does not contain a system-wide gcc
installation, which leads to a failure to link at all.

**Comment by marscher** [comment]
https://bugs.python.org/issue24935

**Comment by mingwandroid** [comment]
> Problems first appeared as this container does not contain a system-wide gcc installation

None of our build machines contain system compilers either, having them present risks them being used and we never want that. I don't personally maintain this docker container.

I think this bug is a [dupe](https://github.com/ContinuumIO/anaconda-issues/issues/9621).

**Comment by mingwandroid** [comment]
This should be fixed in Python 3.6.6 which we released not long ago.

**Comment by mingwandroid** [comment]
Also in Python 3.7.0 which we released just now (interpreter only ATM).
