### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by leoarty** [ContinuumIO/anaconda-issues#967]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - python 3.5*
  - wxpython ==3.0
Use "conda info <package>" to see the dependencies for each package.

{'language': 'zh_CN', 'pyqt': '4.11.4', 'os': 'Windows;7;6.1.7601;x86;x86 Family 6 Model 58 Stepping 9, GenuineIntel', 'python': '3.5.2', 'conda': '4.1.11', 'qt': '4.8.7', 'platform': 'win-32', 'version': '1.2.2'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
