### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rootuparna** [ContinuumIO/anaconda-issues#9681]
I have windows 8 version 6.3 and its a 64 bit system. I installed the anaconda package for 64 bit. Installation was fine but I cannot find the anaconda navigator anywhere. Could someone please help me if I went wrong somewhere ? I checked both check boxes : 1) Add anaconda to my path env variable 2)Register anaconda as my default python.

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@rootuparna please provide the requested information so we can debug the issue
