### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by atulagrwl** [ContinuumIO/anaconda-issues#969]
Anaconda Navigator Update error:

Extra data: line 2 column 1 - line 253 column 1 (char 81 - 19752)

{'platform': 'osx-64', 'version': '1.2.2', 'conda': u'4.1.11', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@atulagrwl thanks for reporting, this will be fixed in the new release of Navigator

**Comment by goanpeca** [comment]
This has been fixed by the latest version of navigator.

`conda update anaconda-navigator`

or

`conda update anaconda`
