### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by piscab** [ContinuumIO/anaconda-issues#970]
Anaconda Navigator Update error:

Extra data: line 2 column 1 (char 81)

{'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'language': 'en', 'python': '3.5.1', 'conda': '4.1.11', 'pyqt': '4.11.4', 'platform': 'osx-64', 'version': '1.2.2', 'qt': '4.8.7'}

**Comment by goanpeca** [comment]
Tracking with #969 
---

Closing as duplicate
