### ISSUE TITLE
Miniconda3 builds for Windows-x86 since version 3-3.18.3 contain the file "python.exe" with the error "python.exe is not a Win32 application"

### ISSUE THREAD

**Issue by alllexandrrr2018** [ContinuumIO/anaconda-issues#9700]
Miniconda3 builds for Windows-x86 since version 3-3.18.3 contain the file "python.exe" with the error "python.exe is not a Win32 application". 
The last correct version: Miniconda3-3.16.0-Windows-x86

**Comment by nehaljwani** [comment]
@alllexandrrr2018 Which version of Windows are you running the installer on? 3.16.0 is too old and we haven't heard anyone complain so far about the 4.x installers.

**Comment by alllexandrrr2018** [comment]
I'm trying to install the Miniconda3 package on Windows XP SP3 32 bit.
All build versions above 3.16.0 give the error "Filed to create menus". If I ignore this error, then in the C: \ Mininconda3 directory, a python.exe file is created, which, when run, causes an error "python.exe is not a Win32 application".
A similar problem occurs with the Anaconda3 builds with versions above 2.3.0.

**Comment by nehaljwani** [comment]
I don't think Windows XP is supported anymore. It went EOL in April 2014 anyway.

**Comment by msarahan** [comment]
Yes, windows XP has not been supported for quite a while.  Sorry.
