### ISSUE TITLE
EnvironmentLocationNotFound: Not a conda environment

### ISSUE THREAD

**Issue by voidplayer** [ContinuumIO/anaconda-issues#9704]
### Actual Behavior
```conda.exe``` is not found after installing conda in windows 10

```
(base) C:\Users\Mañana\Anaconda3>conda install
"conda" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(base) C:\Users\Mañana\Anaconda3>cd Scripts

(base) C:\Users\Mañana\Anaconda3\Scripts>conda.exe install pip

EnvironmentLocationNotFound: Not a conda environment: C:\Users\Ma├▒ana\Anaconda3

https://github.com/ContinuumIO/anaconda-issues
```

### Expected Behavior

Not giving ```EnvironmentLocationNotFound: Not a conda environment``` error when trying to install pip. Notice I have to cd into the path where conda.exe is. If you echo %PATH% you get that weird path string you can see after ```EnvironmentLocationNotFound: Not a conda environment```

### Steps to Reproduce
I didnt modified the PATH during the install. I launched it via the start menu

I guess it has to do with the PATH having this spanish ñ. I cant change the user on the machine so i cant try another user

##### Anaconda or Miniconda version:

Latest that you can download from their web

##### Operating System:
windows 10

**Comment by nehaljwani** [comment]
@voidplayer Does your account name on Windows have non-ascii characters in them? Could you try installing to a PATH which doesn't have that name? For instance: `C:\Anaconda3`?

**Comment by voidplayer** [comment]
installing it in "c:\anaconda3" did it...

thanks!!
