### ISSUE TITLE
Issue while opening Anaconda Navigator

### ISSUE THREAD

**Issue by pvsrgithub** [ContinuumIO/anaconda-issues#9706]
Hello,

I am facing issue while opening Anaconda navigator. I am using x64 bit Windows 7 machine and Anconda also 64bit one.
It is showing below error.

![image](https://user-images.githubusercontent.com/40787307/42204709-0f11f62e-7ec0-11e8-8a60-10bfcadb7dfc.png)

Sometimes it is showing pythonw.exe in APPCRASH.

I am giving conda info below.
![image](https://user-images.githubusercontent.com/40787307/42204857-7a3110f2-7ec0-11e8-9aae-0efc32470ad9.png)

I have same issue while opening anaconda navigator through command line too.

anaconda-navigator   ---- DOESNT WORK and throw same error
spyder ----- DOESN'T WORK and throw same error
python --- 
![image](https://user-images.githubusercontent.com/40787307/42205037-f55bb660-7ec0-11e8-97f6-ff4f7089b293.png)

Please let me know if you need any more info.

Appreciate any help regarding this.

Thanks In Advance..

**Comment by pvsrgithub** [comment]
I tried conda update anaconda-navigator in anaconda prompt, along with conda install navigator-updater. Gave me below info..

![image](https://user-images.githubusercontent.com/40787307/42205582-86200c0e-7ec2-11e8-9a7a-97c724cd141d.png)

**Comment by pvsrgithub** [comment]
conda list output from anaconda prompt.

[conda_list.txt](https://github.com/ContinuumIO/anaconda-issues/files/2158149/conda_list.txt)

**Comment by goanpeca** [comment]
@pvsrgithub you are mixing conda-forge and default packages and that will lead to problems.

**Comment by pvsrgithub** [comment]
@goanpeca Could you please let me know how to fix it.

**Comment by goanpeca** [comment]
@pvsrgithub you would need to remove the conda-forge channel from your configuration and install packages from defaults.

Make sure your `.condarc` does not include conda forge, open a terminal or anaconda prompt and run

```
conda update --all
```

**Comment by pvsrgithub** [comment]
Excellent.. Thanks so much for your help. This is solved now... Cheers.. :+1: :  :  :1st_place_medal:  :100:
