### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by abhiadroit1** [ContinuumIO/anaconda-issues#9714]
## Main error
The following errors occurred:
## Traceback
```
CondaError: dist_name is not a valid conda package: quantlib
```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
