### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by merbst** [ContinuumIO/anaconda-issues#972]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - accelerate ==2.3.0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 15 Stepping 11, GenuineIntel', 'language': 'en_US', 'python': '3.5.2', 'platform': 'win-64', 'version': '1.2.1', 'conda': '4.1.6', 'qt': '5.6.0'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
