### ISSUE TITLE
This now works after update --all.  Huge dependency failure is gone.Install Python 3.7 via Conda works. 

### ISSUE THREAD

**Issue by pythologist** [ContinuumIO/anaconda-issues#9722]
Both of these fail.

This command has a short list
-------
conda install -c anaconda python=3.7
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pytest -> colorama
  - pytest -> more-itertools[version='>=4.0'] -> six[version='>=1.0.0,<2.0.0']
  - pytest -> python=3.3
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.

This appears to be where the previous dependency issue was reported.

This one has a long list.
---------

Using this command: conda create -n py37 python=3.7 anaconda
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda -> asn1crypto==0.24.0=py36_0
  - anaconda -> cachecontrol==0.12.3=py27h15eca11_0
  - anaconda -> certifi==14.05.14=py27_0
  - anaconda -> cffi==0.8.6=py27_0
  - anaconda -> chardet==2.3.0=py35_0
  - anaconda -> configobj==4.7.2=py26_0 -> python=2.6
  - anaconda -> cryptography==0.5.4=py27_0
  - anaconda -> distlib==0.2.5=py27hbc39c7c_0
  - anaconda -> distribute==0.6.45=py26_0
  - anaconda -> distributed==1.21.8=py36_0 -> msgpack-python
  - anaconda -> idna==2.2=py35_0
  - anaconda -> ipaddress==1.0.16=py27_0
  - anaconda -> lockfile==0.12.2=py27hcad0c83_0
  - anaconda -> ordereddict==1.1=py26_0
  - anaconda -> packaging==17.1=py36_0
  - anaconda -> progress==1.3=py27hcb558ea_0
  - anaconda -> pyasn1==0.1.9=py35_0
  - anaconda -> pycparser==2.9.1=py26_0
  - anaconda -> pyopenssl==0.14=py27_0
  - anaconda -> pyparsing==1.5.6=py26_0
  - anaconda -> pysocks==1.6.8=py36_0
  - anaconda -> pytest==2.4.2=py26_0 -> colorama
  - anaconda -> qtconsole==4.2.1=py35_2 -> jupyter_client[version='>=4.1'] -> jupyter_core -> traitlets -> enum34
  - anaconda -> requests==1.2.3=py26_0
  - anaconda -> six==1.4.1=py26_0
  - anaconda -> urllib3==1.22=py36h276f60a_0
  - anaconda -> wheel==0.29.0=py35_0
  - anaconda -> widgetsnbextension==1.2.6=py35_0 -> notebook[version='>=4.2.0'] -> nbconvert -> bleach -> html5lib[version='>=0.99999999'] -> webencodings
  - anaconda -> win_inet_pton==1.0.1=py36he67d7fd_1
  - anaconda -> wincertstore==0.2=py36h7fe50ca_0
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.

**Comment by pythologist** [comment]
Fixed. I followed instructions from a previous issue.

**Comment by mingwandroid** [comment]
Packages do not exist yet.
