### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ryanmartinneutrino** [ContinuumIO/anaconda-issues#975]
The following errors occured:

RuntimeError:
HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/pro/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/noarch/

{'language': 'en_US', 'python': '3.5.2', 'qt': '4.8.7', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'version': '1.2.1', 'conda': '4.1.11', 'platform': 'win-64', 'pyqt': '4.11.4'}

**Comment by goanpeca** [comment]
Hi @ryanmartinneutrino, there were some issues with the repo.continuum.io server. They should have been fixed already.
