### ISSUE TITLE
Error with Anaconda prompt

### ISSUE THREAD

**Issue by tnkumar** [ContinuumIO/anaconda-issues#9757]
I uninstalled and installed again on my Windows 7.
When I open Anaconda prompt, it shows this error message. Please help

![anaconda prompt error](https://user-images.githubusercontent.com/9000263/42714715-b9c69542-86b9-11e8-8570-bdc5f651767a.png)

![image](https://user-images.githubusercontent.com/9000263/42714884-3582950a-86ba-11e8-9382-e9886a600698.png)

**Comment by tnkumar** [comment]
Thanks @nehaljwani. By copying chcp.com from C:\Windows\System32 to a directory in the PATH, the problem went away. The issue is resolved

**Comment by mingwandroid** [comment]
C:\Windows\System32 should already be in your PATH.
