### ISSUE TITLE
i cant find anaconda navigator

### ISSUE THREAD

**Issue by picotnanu** [ContinuumIO/anaconda-issues#9759]
i just installed anaconda for the first time and it gived me the : failed to create anaconda menus and i unistalled it and install it back and it didnt give the error but i dont know where to start the program i search in my pc anaconda navigator and it gives me "anaconda navigator.exe" but it dosent even have an icon and when i press it nothing happens . i am doing something wrong? how to open this app ?

**Comment by goanpeca** [comment]
@picotnanu please provide the requested information, otherwise we cannot debug the issue

**Comment by picotnanu** [comment]
what are the requested information?

**Comment by picotnanu** [comment]
@goanpeca what information should i provide? i have windows 10 and... umm.. what should i say ?

**Comment by goanpeca** [comment]
When you open a new issue there is a prefilled template with all the information you need to add. It seems you just ignored that content



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by picotnanu** [comment]
@goanpeca  yeah.. sorry about that, but what is "conda info " and "conda list show channel urls" ? and at steps to reproduce i dont know what to say. i seyd anything there i think

**Comment by picotnanu** [comment]
everything*

**Comment by picotnanu** [comment]
Anaconda or Miniconda version:
anaconda version 5.2 and python version 3.6 ,64-bit
 Operating System:
windows 10

**Comment by picotnanu** [comment]
@goanpeca  ok but i still dont know what are "conda info " and "conda list show channel urls"

**Comment by goanpeca** [comment]
Are commands you need to run on the terminal or on the Anaconda Prompt on windows

**Comment by picotnanu** [comment]
@goanpeca  and how do i do that if i dont know how to open anaconda prompt or i cant? not sure

**Comment by goanpeca** [comment]
https://conda.io/docs/user-guide/getting-started.html
