### ISSUE TITLE
Please add package to gdal dependencies

### ISSUE THREAD

**Issue by danielbwright** [ContinuumIO/anaconda-issues#976]
Hello,
I have been struggling to resolve the following error, when trying to import the gdal package:

> > > import gdal
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/{username}/anaconda/lib/python2.7/site-packages/gdal.py", line 2, in <module>
> > >     from osgeo.gdal import deprecation_warn
> > >   File "/Users/{username}/anaconda/lib/python2.7/site-packages/osgeo/**init**.py", line 21, in <module>
> > >     _gdal = swig_import_helper()
> > >   File "/Users/{username}/anaconda/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
> > >     _mod = imp.load_module('_gdal', fp, pathname, description)
> > > ImportError: dlopen(/Users/{username}/anaconda/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @loader_path/./libgssapi_krb5.2.2.dylib
> > >   Referenced from: /Users/{username}/anaconda/lib/libgdal.20.dylib
> > >   Reason: image not found

After scouring the web, I found that "conda install krb5" will clear this up. Could krb5 be added as an automatically recognized dependency for gdal? 

Mac El Capitan 10.11.5, Python 2.7.
Thanks,
Dan

**Comment by nehaljwani** [comment]
This problem has been resolved with `libgdal > 2.0.0`:

2.2.0 was compiled with `-lgssapi_krb5`
```bash
(gdal) ➜  ~ grep krb5 /Users/nwani/m3/envs/gdal/../../pkgs/libgdal-2.0.0-0/lib/libgdal.la
dependency_libs=' -lsqlite3 -lexpat -L/opt/anaconda1anaconda2anaconda3/lib /opt/anaconda1anaconda2anaconda3/lib/libnetcdf.la /opt/anaconda1anaconda2anaconda3/lib/libhdf5_hl.la /opt/anaconda1anaconda2anaconda3/lib/libhdf5.la -L/usr/lib -lpq -ldl /opt/anaconda1anaconda2anaconda3/lib/libcurl.la -lssl -lcrypto -lgssapi_krb5 -lresolv -liconv -lxml2 -lz -lpthread -licucore -lm'
(gdal) ➜  ~ grep krb5 /Users/nwani/m3/envs/gdal/../../pkgs/libgdal-2.0.0-0/lib/libgdal.dylib
Binary file /Users/nwani/m3/envs/gdal/../../pkgs/libgdal-2.0.0-0/lib/libgdal.dylib matches
```
2.1.0 wasn't compiled with `-lgssapi_krb5`
```bash
(gdal) ➜  ~ grep krb5 /Users/nwani/m3/envs/gdal/../../pkgs/libgdal-2.1.0-0/lib/libgdal.la
(gdal) ➜  ~ grep krb5 /Users/nwani/m3/envs/gdal/../../pkgs/libgdal-2.1.0-0/lib/libgdal.dylib
```
If you still wish to use 2.0.0, then workaround is: `conda install krb5`
