### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sorrysnowy** [ContinuumIO/anaconda-issues#977]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - hdf5 ==1.8.16
  - pytables -> hdf5 1.8.15.1
  - pytables -> numpy 1.6*|1.7*|1.8*|1.9*
  - pytables -> python 2.6*|2.7*|3.3*|3.4*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.1.9', 'version': '1.2.1', 'language': 'en_US', 'python': '3.5.2', 'qt': '4.8.7', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'pyqt': '4.11.4', 'platform': 'win-64'}

**Comment by goanpeca** [comment]
pytables does not have a package for python 3.5. If you need to use it you will need to create a python `2.6|2.7|3.3|3.4` first.

To learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
