### ISSUE TITLE
Link conda command for versions like python/pip does

### ISSUE THREAD

**Issue by evandam** [ContinuumIO/anaconda-issues#9770]
I tend to manage multiple Anaconda installs for users on a server, and it would be very helpful to link the `conda` command automatically to include the version, similar to how the `python` command often links to `python3` and `python3.6`.

Would it be possible to integrate this in Anaconda's install process? On Linux/Mac, it would just be something like this:
```bash
ln -s $CONDA_PREFIX/bin/conda $CONDA_PREFIX/bin/conda3
ln -s $CONDA_PREFIX/bin/conda $CONDA_PREFIX/bin/conda3.6
```

**Comment by mingwandroid** [comment]
Can anyone explain why this is good? Why do you want the python version encoded into the exe name? Since conda manages python 2 and 3 environments side-by-side I don't see the use-case.

**Comment by evandam** [comment]
Maybe it's a miss on my part, but what do you mean by conda managing them side-by-side? As in virtual environments?

We default to using a Python 3 environment but we still need to maintain our Python 2 version, so we have a separate Anaconda install there. It's really just easier to run `python2` with both versions in your `PATH` than teaching users how to manage virtual environments.

**Comment by mingwandroid** [comment]
> We default to using a Python 3 environment but we still need to maintain
our Python 2 version, so we have a separate Anaconda install there

You do not need to do that. Please read:
https://conda.io/docs/user-guide/tasks/manage-environments.html

**Comment by nehaljwani** [comment]
Conda is a generic package manager and environment manager. I wouldn't want to tie conda itself to python versions like that.

**Comment by evandam** [comment]
Agreed. Closing this and looking into revising how we manage things.

Thanks!
