### ISSUE TITLE
Corrupt qt package

### ISSUE THREAD

**Issue by Bezier89** [ContinuumIO/anaconda-issues#9771]
### Actual Behavior

SafetyError: The package for qt located at [ROOT]\pkgs\qt-5.6.2-vc10_5
appears to be corrupted. The path 'Scripts/.qt-post-link.bat'
has a sha256 mismatch.
  reported sha256: 28da36c312ce270171fe8631e790a54794efafae067f9c811705ff2c903dc30a
  actual sha256: ee900b25dd07aaaa13437801df8a53f8471859a5953e50199f8698f4b1d117d8

### Expected Behavior

Package should report the correct sha256 for "Scripts/.qt-post-link.bat" in its info\paths.json file.

### Steps to Reproduce

conda create -n TestEnv1 qt=5.6.2=vc10_5

##### Anaconda or Miniconda version:

conda version : 4.5.5

##### Operating System:

Windows 10

###

Note that this package was only uploaded 12 days ago (https://anaconda.org/anaconda/qt/files), and is the latest build number among the qt=5.6.2=vc10_* builds.

**Comment by mingwandroid** [comment]
package is old, please use qt 5.9.6

**Comment by mingwandroid** [comment]
It was not uploaded 12 days ago, just some date-stamp has changed. vs10 is no longer supported either.
