### ISSUE TITLE
pandas, using it on Jupyter's Notebook, the same error keeps popping up

### ISSUE THREAD

**Issue by admase** [ContinuumIO/anaconda-issues#9776]
Hopefully, I'm at the right location for my issue, which is pandas, using it on Jupyter's Notebook, the same error keeps popping up. When performing the following code df_can = pd.read.(type of file) and running it, error is, "MODULE" PANDAS DOES NOT ATTRIBUTE "READ" I've tried doing, condas uninstall PACKAGENAME, and re-installing it, tried conda update PACKAGENAME or pandas and none of it solves my issue. So if you have a good understanding of my issue and has dealt with before, please share your methods because of this I'm beginning to look for a replacement for anacondas. thank you very much if you shared.

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
Please provide the request information (in the issue template), otherwise we cannot help you debug the issues. Also you do not need to put all the information in the title, the description serves that purpose.
