### ISSUE TITLE
Security issue in Jupyter Notebook 5.5.0

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#9777]
Last week-end, Jupyter Notebook 5.6.0 was released. It fixes a security issue in 5.5.0, which is the latest version currently available from `conda` in the default channels. The conda-forge channel already provides [notebook](https://anaconda.org/conda-forge/notebook)  5.6.0.

Could you please update the `notebook` package in the default channels as well?

https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/jupyter/wm00hlNctJg

**Comment by jjhelmus** [comment]
notebook `5.6.0` is available in `defaults` for all platforms.
