### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Mengnan-HE** [ContinuumIO/anaconda-issues#978]
The following errors occured:

RuntimeError:
Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/seaborn-0.7.0-py27_0.tar.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000006A042B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)): https://repo.continuum.io/pkgs/free/win-64/seaborn-0.7.0-py27_0.tar.bz2

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'zh_CN', 'python': '2.7.12', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 55 Stepping 8, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
@lilmatt do you know if repo still having issues? is this related to that?
