### ISSUE TITLE
Anaconda Navigator fails to open and cant update Conda

### ISSUE THREAD

**Issue by whitesonkun** [ContinuumIO/anaconda-issues#9797]
### Actual Behavior

So as the title said, i cant open navigator as it was stuck on the green ring with initializing said in the center and command prompt cmd keep popping up, then it gives me this : 

>  # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
>     Traceback (most recent call last):
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
>         from ..activate import main as activator_main
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
>         context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
>         argparse_args=argparse_args)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
>         self._set_search_path(search_path)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
>         self._set_raw_data(load_file_configs(search_path))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
>         raw_data = odict(kv for kv in chain.from_iterable(load_paths))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
>         raw_data = odict(kv for kv in chain.from_iterable(load_paths))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
>         yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
>         ruamel_yaml = yaml_load(fh)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
>         return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
>         loader = Loader(stream, version, preserve_quotes=preserve_quotes)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
>         Reader.__init__(self, stream, loader=self)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
>         self.stream = stream  # type: Any  # as .read is called
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
>         self.determine_encoding()
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
>         self.update(1)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
>         self.check_printable(data)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
>         'unicode', "special characters are not allowed")
>     ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
>       in "C:\Users\Aldiya Yusuf\.condarc", position 0
> 
> `$ C:\Users\Aldiya Yusuf\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\Aldiya Yusuf\Anaconda3`
> 
>   environment variables:
>                  CIO_TEST=<not set>
>                CONDA_ROOT=C:\Users\Aldiya Yusuf\Anaconda3
>                  HOMEPATH=\Users\Aldiya Yusuf
>                      PATH=C:\Windows\System32;C:\Program Files (x86)\Intel\iCLS
>                           Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WIN
>                           DOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1
>                           .0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine
>                           Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine
>                           Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
>                           Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine
>                           Components\IPT;C:\Program Files (x86)\IVI
>                           Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI
>                           Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI
>                           Foundation\VISA\WinNT\Bin;C:\Program
>                           Files\MATLAB\R2017a\runtime\win64;C:\Program
>                           Files\MATLAB\R2017a\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program
>                           Files\Microsoft VS Code\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Library\mingw-w64\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Library\usr\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Library\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Scripts;C:\Windows\System32
>              PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
>                           PowerShell\v1.0\Modules
>        REQUESTS_CA_BUNDLE=<not set>
>             SSL_CERT_FILE=<not set>
>                VXIPNPPATH=C:\Program Files (x86)\IVI Foundation\VISA\
> 
>      active environment : None
>        user config file : C:\Users\Aldiya Yusuf\.condarc
>  populated config files :
>           conda version : 4.5.4
>     conda-build version : 3.10.5
>          python version : 3.6.5.final.0
>        base environment : C:\Users\Aldiya Yusuf\Anaconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/win-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/win-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/win-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/pro/win-64
>                           https://repo.anaconda.com/pkgs/pro/noarch
>                           https://repo.anaconda.com/pkgs/msys2/win-64
>                           https://repo.anaconda.com/pkgs/msys2/noarch
>           package cache : C:\Users\Aldiya Yusuf\Anaconda3\pkgs
>                           C:\Users\Aldiya Yusuf\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Users\Aldiya Yusuf\Anaconda3\envs
>                           C:\Users\Aldiya Yusuf\AppData\Local\conda\conda\envs
>                           C:\Users\Aldiya Yusuf\.conda\envs
>                platform : win-64
>              user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
>           administrator : False
>              netrc file : None
>            offline mode : False

Same thing happned on Anaconda Prompt, it gives me the same error report on boot, some said i should reinstall, i did, but it doesnt work
some said i should update, i tried the code `conda update` `conda update conda` and `conda update all` but nothing works

### Expected Behavior

Anaconda works properly, both Navigator and Prompt

I mean it was working at first but idk what happened

##### `conda info`
i cant do this, `conda info` gives me an error

> >     Traceback (most recent call last):
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
>         return func(*args, **kwargs)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
>         context.__init__(argparse_args=args)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
>         argparse_args=argparse_args)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
>         self._set_search_path(search_path)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
>         self._set_raw_data(load_file_configs(search_path))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
>         raw_data = odict(kv for kv in chain.from_iterable(load_paths))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
>         raw_data = odict(kv for kv in chain.from_iterable(load_paths))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
>         yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
>         ruamel_yaml = yaml_load(fh)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
>         return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
>         loader = Loader(stream, version, preserve_quotes=preserve_quotes)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
>         Reader.__init__(self, stream, loader=self)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
>         self.stream = stream  # type: Any  # as .read is called
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
>         self.determine_encoding()
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
>         self.update(1)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
>         self.check_printable(data)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
>         'unicode', "special characters are not allowed")
>     ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
>       in "C:\Users\Aldiya Yusuf\.condarc", position 0
> 
> `$ C:\Users\Aldiya Yusuf\Anaconda3\Scripts\conda info`

##### `conda list --show-channel-urls`
same

> Traceback (most recent call last):
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
>         return func(*args, **kwargs)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
>         context.__init__(argparse_args=args)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
>         argparse_args=argparse_args)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
>         self._set_search_path(search_path)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
>         self._set_raw_data(load_file_configs(search_path))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
>         raw_data = odict(kv for kv in chain.from_iterable(load_paths))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
>         raw_data = odict(kv for kv in chain.from_iterable(load_paths))
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
>         yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
>         ruamel_yaml = yaml_load(fh)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
>         return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
>         loader = Loader(stream, version, preserve_quotes=preserve_quotes)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
>         Reader.__init__(self, stream, loader=self)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
>         self.stream = stream  # type: Any  # as .read is called
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
>         self.determine_encoding()
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
>         self.update(1)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
>         self.check_printable(data)
>       File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
>         'unicode', "special characters are not allowed")
>     ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
>       in "C:\Users\Aldiya Yusuf\.condarc", position 0
> 
> `$ C:\Users\Aldiya Yusuf\Anaconda3\Scripts\conda list --show-channel-urls`
> 
>   environment variables:
>                  CIO_TEST=<not set>
>                CONDA_ROOT=C:\Users\Aldiya Yusuf\Anaconda3
>                  HOMEPATH=\Users\Aldiya Yusuf
>                      PATH=C:\Windows\System32;C:\Program Files (x86)\Intel\iCLS
>                           Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WIN
>                           DOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1
>                           .0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine
>                           Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine
>                           Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
>                           Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine
>                           Components\IPT;C:\Program Files (x86)\IVI
>                           Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI
>                           Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI
>                           Foundation\VISA\WinNT\Bin;C:\Program
>                           Files\MATLAB\R2017a\runtime\win64;C:\Program
>                           Files\MATLAB\R2017a\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program
>                           Files\Microsoft VS Code\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Library\mingw-w64\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Library\usr\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Library\bin;C:\Users\Aldiya
>                           Yusuf\Anaconda3\Scripts;C:\Windows\System32
>              PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
>                           PowerShell\v1.0\Modules
>        REQUESTS_CA_BUNDLE=<not set>
>             SSL_CERT_FILE=<not set>
>                VXIPNPPATH=C:\Program Files (x86)\IVI Foundation\VISA\
> 
>      active environment : None
>        user config file : C:\Users\Aldiya Yusuf\.condarc
>  populated config files :
>           conda version : 4.5.4
>     conda-build version : 3.10.5
>          python version : 3.6.5.final.0
>        base environment : C:\Users\Aldiya Yusuf\Anaconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/win-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/win-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/win-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/pro/win-64
>                           https://repo.anaconda.com/pkgs/pro/noarch
>                           https://repo.anaconda.com/pkgs/msys2/win-64
>                           https://repo.anaconda.com/pkgs/msys2/noarch
>           package cache : C:\Users\Aldiya Yusuf\Anaconda3\pkgs
>                           C:\Users\Aldiya Yusuf\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Users\Aldiya Yusuf\Anaconda3\envs
>                           C:\Users\Aldiya Yusuf\AppData\Local\conda\conda\envs
>                           C:\Users\Aldiya Yusuf\.conda\envs
>                platform : win-64
>              user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
>           administrator : False
>              netrc file : None
>            offline mode : False

**Comment by whitesonkun** [comment]
the error message in internet browser

 > Navigator Error
> An unexpected error occurred on Navigator start-up
> 
> Report
> Please report this issue in the anaconda issue tracker
> 
> Main Error
> expected str, bytes or os.PathLike object, not NoneType
> Traceback
> Traceback (most recent call last):
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
>     return_value = func(*args, **kwargs)
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
>     window = run_app(splash)
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
>     window = MainWindow(splash=splash, tab_project=False)
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
>     self.api = AnacondaAPI()
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
>     ANACONDA_API = _AnacondaAPI()
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
>     self._conda_api = CondaAPI()
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
>     CONDA_API = _CondaAPI()
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
>     self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
>   File "C:\Users\Aldiya Yusuf\Anaconda3\lib\ntpath.py", line 76, in join
>     path = os.fspath(path)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by goanpeca** [comment]
Please remove this file

`C:\Users\Aldiya Yusuf\.condarc`

**Comment by whitesonkun** [comment]
thank you, its working properly now
