### ISSUE TITLE
Update scons conda package to 2.3.1

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#98]
_Issue by **[kblomqvist](https://github.com/kblomqvist)** from Monday Mar 10, 2014 at 07:33 GMT_
_Originally opened as https://github.com/conda/conda/issues/593_

---

**Comment by frol** [comment]
It is already 2.3.5 released and still 2.3.0 in conda repos!

**Comment by kblomqvist** [comment]
Today it's 2.5.1. Could you update this, please?

**Comment by goanpeca** [comment]
@ilanschnell, @mingwandroid ?

**Comment by mingwandroid** [comment]
@csoja, making you aware of this one for scheduling purposes.

**Comment by csoja** [comment]
@nehaljwani updated this to 3.0.0 on Saturday Oct 21st.  It is available in the main channel (https://repo.continuum.io/pkgs/main)
