### ISSUE TITLE
sftp support for pycurl?

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#980]
_From @jmfee-usgs on August 3, 2016 19:56_

When I install pycurl using conda, it installs a version that does not include support for certain protocols including sftp.  Is it possible to update this package to bind to a ssl library?

_Copied from original issue: conda/conda#3223_

**Comment by dhirschfeld** [comment]
This would be a very useful feature (for me)!

The [pypi version](https://pypi.org/project/pycurl/) supports pip so for now I've just built a conda package for that (win64/py35):
```
conda install -c dhirschfeld pycurl
```

**Comment by nehaljwani** [comment]
This will require curl to be built with libssh2

**Comment by nehaljwani** [comment]
SFTP support is now available in the latest build of curl:

```
(root) root@16cf8a14f464:~# conda list curl
# packages in environment at /m3:
#
curl                      7.55.1               hcb0b314_2  

(root) root@16cf8a14f464:~# curl -V
curl 7.55.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11 libssh2/1.8.0
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp *sftp* smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```
