### ISSUE TITLE
Unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by kmnhz** [ContinuumIO/anaconda-issues#9806]
Anaconda navigator does not open and show this error message in the browser.

### Actual Behavior
Got an error message when I tried to open Anaconda Navigator

Got an error message when I tried to open Anaconda Navigator
### Expected Behavior
Anaconda opening page should open

May be something wrong with script or command line
### Steps to Reproduce
Deleted all anaconda and python related files in my PC

##### Anaconda or Miniconda version:
Anaconda 5.2
##### Operating System:
Windows 7
##### `conda info`

```
conda is not recognized as an internal or external command, operable program or batch file

```

##### `conda list --show-channel-urls`

```
conda is not recognized as an internal or external command, operable program or batch file
```

**Comment by goanpeca** [comment]
@kmnhz please open the `Anaconda Prompt` and provide the requested information
```
conda info
```

```
conda list --show-channel-urls
```
