### ISSUE TITLE
glueviz 0.8.2 package missing many dependencies

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#981]
It looks like glueviz has been bumped to 0.8.2 in the defaults channel but many dependencies have been removed. Would it be possible to make the build in the defaults channel consistent with the conda-forge recipe here?

https://github.com/conda-forge/glueviz-feedstock/blob/master/recipe/meta.yaml

This is a somewhat urgent issue since it is causing failed installations for users who have the channel priority setting set to false or who don't specify the conda-forge channel.

cc @ilanschnell @ccordoba12

**Comment by ccordoba12** [comment]
@astrofrog, Thanks for letting us know about this issue :-)

I submitted a PR to our internal repo to update our recipe with the new deps for Glueviz. I'll ping Ilan tomorrow to create new packages for it.

**Comment by astrofrog** [comment]
@ccordoba12 - thanks! :)

**Comment by ilanschnell** [comment]
New packages are uploaded.  I'm closing this issue, please reopen if there are still problems.
