### ISSUE TITLE
Unable to import installed libraries in Jupyternotebook

### ISSUE THREAD

**Issue by suraty** [ContinuumIO/anaconda-issues#9818]
Hello,
I installed Anaconda on windows 10, and then Tensorflow via conda environment, and then Keras via pip command.
In Anaconda Prompt, I activated the tensorflow environment,  I typed python and then I can code:
_`import tensorflow`
`import keras`_
All is ok.

But when I deactivate the environment, I type python, again and then there are errors when I code:
_`import tensorflow`_
**Error: ModuleNotFoundError**
_`import keras`_
**Error: ModuleNotFoundError**

 And the same error in the Jupyter notebook.
In the Jupyter notebook, also I tried below codes:

> `!conda info --env
> # conda environments:
> base                  *  D:\Programs\Anaconda3
> tensorflow               D:\Programs\Anaconda3\envs\tensorflow
> 
> sys.path
> ['',
>  'D:\\Programs\\Anaconda3\\python36.zip',
>  'D:\\Programs\\Anaconda3\\DLLs',
>  'D:\\Programs\\Anaconda3\\lib',
>  'D:\\Programs\\Anaconda3',
>  'D:\\Programs\\Anaconda3\\lib\\site-packages',
>  'D:\\Programs\\Anaconda3\\lib\\site-packages\\win32',
>  'D:\\Programs\\Anaconda3\\lib\\site-packages\\win32\\lib',
>  'D:\\Programs\\Anaconda3\\lib\\site-packages\\Pythonwin',
>  'D:\\Programs\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
>  'C:\\Users\\asus\\.ipython']
> 
> sys.executable
> 'D:\\Programs\\Anaconda3\\python.exe'`

I understood that the executable should be: 
`D:\Programs\Anaconda3\envs\tensorflow`
instead of the above. Because I installed Tensorflow and Keras in that environment.

Why is Jupyter notebook not found the installed libraries?
How can I solve it?

Attached images describe my problem!
![image](https://user-images.githubusercontent.com/38600508/43209132-2c258022-9041-11e8-80ec-992e2f0e2513.png)
![image](https://user-images.githubusercontent.com/38600508/43209211-587d20da-9041-11e8-9db0-856d3878520d.png)

**Comment by jjhelmus** [comment]
This is the expected behavior.  Packages are only available in the environment they are installed into.  If you want Keras and Tensorflow available in the `base` environment you need to install them there.
