### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by TDVvDlunn** [ContinuumIO/anaconda-issues#982]
Anaconda Navigator Update error:

Extra data: line 2 column 1 (char 82)

{'conda': '4.1.11', 'qt': '4.8.7', 'language': 'de_DE', 'version': '1.2.2', 'pyqt': '4.11.4', 'platform': 'win-64', 'python': '3.5.1', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel'}

**Comment by goanpeca** [comment]
Tracking with #969 
---

Closing as duplicate
