### ISSUE TITLE
Idk why my anaconda navigator won't work anymore, shows sth as attached!!pls!

### ISSUE THREAD

**Issue by ywanglocus** [ContinuumIO/anaconda-issues#9827]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

]===================
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
byte indices must be integers or slices, not str
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

========================

![image](https://user-images.githubusercontent.com/40369958/43300448-59d7dd70-912d-11e8-8cf9-faba8887a39a.png)

Idk why my anaconda navigator won't work anymore, showed as above

**Comment by goanpeca** [comment]
@ywanglocus please open the Anaconda Prompt and type and paste the putput of

```
conda info
```

And

```
conda list --show-channel-urls
```

**Comment by ywanglocus** [comment]
hey why you close it, btw i can't even open my anaconda prompt

**Comment by ywanglocus** [comment]
![image](https://user-images.githubusercontent.com/40369958/43323608-1e9a5be0-9180-11e8-9cf4-39abb9ce519c.png)
 this is what happened when i opened anaconda prompt

**Comment by goanpeca** [comment]
Please provide the full error trace as text not as images

**Comment by ywanglocus** [comment]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
        Reader.__init__(self, stream)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\wyd15\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\ProgramData\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                 HOMEPATH=\Users\wyd15
          MOZ_PLUGIN_PATH=C:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\plugins\
                     PATH=C:\ProgramData\Anaconda3\Library\bin;C:\Rtools\bin;C:\Rtools\mingw_32\
                          bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program
                          Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
                          tem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Samsung\SamsungLink\AllShare Framework DMS\bin\;C:\Program Files
                          (x86)\clisp-2.49;C:\Program Files\MiKTeX
                          2.9\miktex\bin\x64\;C:\Program
                          Files\MATLAB\R2014b\runtime\win64;C:\Program
                          Files\MATLAB\R2014b\bin;C:\Program Files\MATLAB\R2014b\polyspace\bin;C
                          :\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program
                          Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL
                          Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows
                          Performance Toolkit\;C:\Program Files (x86)\Git\cmd;C:\Program Files (
                          x86)\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:
                          \WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\wyd15\Download\soft
                          \ampl.mswin64;C:\Program Files\Microsoft Windows Performance
                          Toolkit\;C:\Program Files\CMake\bin;C:\Python27;C:\Program
                          Files\Git\cmd;C:\Program Files (x86)\Pandoc\;C:\Program Files
                          (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\wyd15\AppData\Loc
                          al\Julia-0.6.2\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\PostgreSQL\9.6\bin;C:\Program Files\PostgreSQL\9.2\lib;C:\Users\
                          wyd15\Desktop\work\bird;C:\Users\wyd15\Desktop\work\bird\tutorials;;C:
                          \Users\wyd15\.dnx\bin;C:\Users\wyd15\AppData\Local\Microsoft\WindowsAp
                          ps;C:\Program Files\PostgreSQL\9.6\bin;C:\Program
                          Files\PostgreSQL\9.6\lib;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\W
                          indowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mo
                          dules;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-
                          sdk\platform\PowerShell
               PYTHONPATH=C:\Users\wyd15\Desktop\work\bird;C:\Users\wyd15\Desktop\work\bird\tuto
                          rials;
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\wyd15\.condarc
 populated config files :
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\wyd15\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\wyd15\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\wyd15\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.14.2 CPython/3.6.4 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true


C:\Users\wyd15> conda info
'conda' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\wyd15> conda config --set report_errors true
'conda' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\wyd15>

**Comment by goanpeca** [comment]
Please erase this file `C:\Users\wyd15\.condarc`

And try again

**Comment by ywanglocus** [comment]
wow it worked!!! thank you so much!!!

**Comment by goanpeca** [comment]
Glad to be of help!
