### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by czzerone** [ContinuumIO/anaconda-issues#9832]
The following errors occured:

RuntimeError:
Could not find anaconda.org user E:\Python\python.exe

{'python': '3.5.2', 'version': '1.2.1', 'os': 'Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'conda': '4.1.6', 'pyqt': '4.11.4', 'qt': '4.8.7', 'platform': 'win-64', 'language': 'zh_CN'}

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

**Comment by czzerone** [comment]
@goanpeca I can't update it because the same reason......

(E:\Anaconda3) C:\Users>conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......Error: Could not find anaconda.org user E:\Python\python.exe

(E:\Anaconda3) C:\Users>conda update --all
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......Error: Could not find anaconda.org user E:\Python\python.exe

(E:\Anaconda3) C:\Users\xulinyi>

**Comment by goanpeca** [comment]
@czzerone please look for and remove this file

`C:\Users\xulinyi\.condarc`

**Comment by czzerone** [comment]
@goanpeca I solved it! Thanks : )
