### ISSUE TITLE
Request selenium 3.8.0 due to known issue

### ISSUE THREAD

**Issue by bryevdv** [ContinuumIO/anaconda-issues#9839]
### Actual Behavior

Selenium tests with chromedriver on TravisCI and others persistently, intermittently fail due to documented issue https://github.com/SeleniumHQ/selenium/issues/5296 However, the lowest version available on the main channel is the affected version, 3.8.1

```
(base) ❯ conda search selenium=3.8
Loading channels: done
# Name                  Version           Build  Channel
selenium                  3.8.1          py27_0  pkgs/main
selenium                  3.8.1          py35_0  pkgs/main
selenium                  3.8.1          py36_0  pkgs/main
```

This issue persists through at least selenium 3.13

### Expected Behavior

Anaconda provided a Selenium version that functions despite this issue

### Steps to Reproduce

Run selenium tests on TravisCI with selenium >= 3.8.1 repeatedly until failure occurs, e.g https://travis-ci.org/bokeh/bokeh/jobs/408670050

##### Operating System:

Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

##### `conda info`
 
N/A

##### `conda list --show-channel-urls`
```
+conda config --get channels
--add channels 'bokeh'   # lowest priority
--add channels 'defaults'   # highest priority

```

**Comment by jjhelmus** [comment]
@bryevdv I'm building this now, it should be available on `defaults` later today.

**Comment by jjhelmus** [comment]
selenium 3.8.0 is now available in for all platforms and supported Python version.

```
