### ISSUE TITLE
Cant open anaconda navigator ,I have tried the anaconda-navigator command in anaconda prompt too but it didnt worked.It says no such command exists  

### ISSUE THREAD

**Issue by keshavatgithub** [ContinuumIO/anaconda-issues#9843]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by csoja** [comment]
Please provide the information requested in the template if possible - there is not enough information to diagnose what might be wrong.  However, it sounds like Anaconda did not get installed completely on your machine.  This may help you track down why: https://docs.anaconda.com/anaconda/user-guide/troubleshooting.html#windows-error-failed-to-create-anaconda-menus-or-failed-to-add-anaconda-to-the-system-path
