### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by texpine** [ContinuumIO/anaconda-issues#985]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - scikit-image ==0.12.3
  - scikits-image ==0.7.1 -> numpy 1.6*|1.7*
  - scikits-image ==0.7.1 -> python 2.6*
Use "conda info <package>" to see the dependencies for each package.

{'language': 'fr_CA', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel', 'python': '3.5.2', 'qt': '4.8.7', 'conda': '4.1.9', 'platform': 'win-64', 'pyqt': '4.11.4', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
