### ISSUE TITLE
graphviz  - 'dot' is not recognized as an internal or external command, -- Window 7   

### ISSUE THREAD

**Issue by chisumo2016** [ContinuumIO/anaconda-issues#9850]
Can someone assist to resolve this problem on window machine, please

Found 4 models.
Inspecting model relations.

 1/4 [=======>--------------------]  25%
 2/4 [==============>-------------]  50%
 3/4 [=====================>------]  75%
 4/4 [============================] 100%
In Graph.php line 375:

  An error occurred while creating the graph; GraphViz returned: 'dot' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by mingwandroid** [comment]
You failed to fill in the issue template so we cannot help you here.

**Comment by chisumo2016** [comment]
How?i didn't get you
