### ISSUE TITLE
rpy2 requires icu=54.1 but possible to get 56.1 and then magic is broken

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#986]
I had to add an entry `icu=54.1` into my environment file here: https://anaconda.org/ijstokes/pydatasf in order to get a working `rpy2` that would allow me to do:

```
%load_ext rpy2.ipython
```

Without that entry I get a dynamic library load error.

Should be reproducible by using the above specified environment file and removing the explicit `icu` entry.

**Comment by mingwandroid** [comment]
Hi @ijstokes, do you know what version of ICU you had before that? Also, which platform was this on?

**Comment by ijstokes** [comment]
I had ended up with a more recent version: 56.1. So I had to downgrade to get the version rpy2 was looking for.  This was on OS X.

**Comment by essicolo** [comment]
Ubuntu 16.04 here. `import rpy2.objects` returns `ImportError: libicuuc.so.54: cannot open shared object file: No such file or directory`. After `conda install icu=54`, `import rpy2.objects` returns `ImportError: libicuuc.so.56: cannot open shared object file: No such file or directory`.

**Comment by mingwandroid** [comment]
You've probably installed something from `conda-forge` and that's broken your setup.

Remove the `conda-forge` channel and try to update everything in your environment to proceed.

**Comment by essicolo** [comment]
Indeed. I deleted the `- conda-forge` line in `.condarc`. Then I removed the environment. I created it again and the issue no longer appears. Thanks!
