### ISSUE TITLE
Anaconda navigator does not work every time my system starts from sleep mode. Here is a screenshot

### ISSUE THREAD

**Issue by Preeti321** [ContinuumIO/anaconda-issues#9867]
Anaconda navigator does not respond whenever my system starts after sleep. 
![image](https://user-images.githubusercontent.com/42052213/43620602-3252172c-9699-11e8-8bc3-d513ee088d20.png)

**Comment by mingwandroid** [comment]
You failed to fill in the template as requested so we are unable to help with this.
