### ISSUE TITLE
Navigator error occurred while start up 

### ISSUE THREAD

**Issue by rasithakumara** [ContinuumIO/anaconda-issues#9878]
### Actual Behavior
opening of a browser page indicating navigator error occurred while start up 
MAIN ERROR:  expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior

opening of anaconda navigator 

### Steps to Reproduce

start > All Programs > Anaconda(64bit) > Anaconda Prompt 

##### Anaconda or Miniconda version:

Anaconda3-5.2.0-Windows-x86_64

##### Operating System:

Windows 7 Enterprise  

##### `conda info`

```
conda is not recognized as a internal or external command  
operable program or batch file 
```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@rasithakumara it seems you have an invalid installation. Please make sure to reinstall and disable any antivirus during the process. Also installing for the `current user` is recommended

**Comment by rasithakumara** [comment]
I have been having this issue with anaconda not responding past two weeks i
have reinstalled anaconda 3.5.0 (64bit) quite a number of times due to the
navigator error

However Ill try again
