### ISSUE TITLE
create an environment for macOS system python?

### ISSUE THREAD

**Issue by bmosley** [ContinuumIO/anaconda-issues#9904]
### Actual Behavior

need to use system python on macOS. I've created an environment for 2.7 but need to be able to work with system python which will not work for me in a 2.7 environment

### Expected Behavior

ability to change to system python on macOS conveniently when needed and back to anaconda (default)

### Steps to Reproduce

install anaconda 3.6 on macOS
attempt to access system python

(sorry its vague)

##### Anaconda or Miniconda version:

conda 4.5.9

##### Operating System:
macOS 10.13.6

##### `conda info`

```
    conda-build version : 3.4.1
         python version : 3.6.6.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda3/pkgs
```

**Comment by mingwandroid** [comment]
Your use either `conda deactivate` or .`$CONDA_PREFIX/bin/deactivate`

**Comment by bmosley** [comment]
Thanks mingwandroid! The option you gave me doesn't seem to work. Could you provide some more details?

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with
```

using:
`sudo ln -s /anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh`

results in:
`ln: /etc/profile.d/conda.sh: No such file or directory`

**Comment by bmosley** [comment]
no I dont. not sure why I went with that option to start. thanks!
