### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by MikeLaptev** [ContinuumIO/anaconda-issues#991]
The following errors occured:

UnsatisfiableSpecifications:
The following specifications were found to be in conflict:
  - python ==3.5.2
  - ssl_match_hostname -> python 2.6*|2.7*|3.3*|3.4*
Use "conda info <package>" to see the dependencies for each package.

{'platform': 'win-64', 'version': '1.2.1', 'conda': u'4.1.6', 'qt': '4.8.7', 'language': 'en_US', 'python': '2.7.12', 'os': 'Windows;10;10.0.10586;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'pyqt': u'4.11.4'}

**Comment by goanpeca** [comment]
The packages selected for installation are in conflict, to learn more you can [read here](http://conda.pydata.org/docs/troubleshooting.html#unsatisfiable)
