### ISSUE TITLE
Anaconda - not able to connect Netezza using Pyodbc

### ISSUE THREAD

**Issue by Saranya411** [ContinuumIO/anaconda-issues#9914]
### Actual Behavior

We are trying to connect Netezza using pyodbc in Jupyter.

Please find below the connection string we are using  to connect.

<ipython-input-4-94ce10ca1409> in <module>()
----> 1 conx = pyodbc.connect('DRIVER={NetezzaSQL};SERVER=XXXXX;database="XXXX";UID=XXXX;PWD:XXXX;')

Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/local/nz/lib64/libnzodbc.so' : file not found (0) (SQLDriverConnect)")

but we have this file .

xxxxxxx@yyyyy$ ls -lrth /usr/local/nz/lib64/libnzodbc.so
-rwxr-xr-x. 1 root bin 2.2M Jul  9  2015 /usr/local/nz/lib64/libnzodbc.so

We are using RHEL 7.5. Can you please hep us in resolving the issuse asap ?

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by mingwandroid** [comment]
This sounds like an Enterprise support request. Please contact sales@anaconda.com to see if we can assist you further.
