### ISSUE TITLE
There is no win32 package for Python 3.7 and NumPy 1.15 (yet?)

### ISSUE THREAD

**Issue by bryanwweber** [ContinuumIO/anaconda-issues#9925]
### Actual Behavior

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.15 -> numpy-base==1.15.0=py27hfef472a_0 -> python[version='>=2.7,<2.8.0a0']
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.
```

### Expected Behavior

The package should install

### Steps to Reproduce

`conda install python=3.7 numpy=1.15`

##### Operating System: Windows 32-bit (Appveyor)

There is no win32 package for NumPy 1.15 on anaconda.org: https://anaconda.org/anaconda/numpy/files?version=1.15.0 Do you plan to build one, or are there dependency problems that will prohibit this? Thank you!

**Comment by mingwandroid** [comment]
There's been a huge stack of Python 3.7 packages to build and as our last popular platform 32 bit Windows comes last.

It should be there now.

**Comment by speth** [comment]
I certainly understand win32 as being a lower priority. However, the last uploads to https://anaconda.org/anaconda/numpy/files?sort=time&sort_order=desc&version=1.15.0 seem to have been on 2018-07-27, just after the release of Numpy 1.15, and include win32 packages for Python 2.7, 3.5, and 3.6. This seems to be the only package for Numpy 1.15 missing across all of the platform and Python version combinations.

**Comment by mingwandroid** [comment]
Ah, I've been idea how this happened, I guess someone didn't push a change? We'll get them built ASAP.

**Comment by msarahan** [comment]
heh... I wonder who that was?  Sorry.

**Comment by bryanwweber** [comment]
@mingwandroid @msarahan Thanks for the quick responses. Any idea when the package will be uploaded? This is the cause of the only failing build so we can do a new release of our package.

**Comment by msarahan** [comment]
Package is being uploaded now.  Closing.

**Comment by bryanwweber** [comment]
Thank you @msarahan!
