### ISSUE TITLE
ModuleNotFoundError : No module named 'conda' in Amaconda 3 when start up

### ISSUE THREAD

**Issue by STREETKILLER007** [ContinuumIO/anaconda-issues#9927]
hello developer, i used conda and created environment. It works fine.

using window 7, 64 bit, no Python Install, only Amaconda 3.

but today, i tried to open Amaconda Prompt, it showed up following issue :  

```
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\conda-script.py", line 6, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
i checked my Environment Variable.

**System Variable :**  

Path : d:\Anaconda3\envs\py36
Pythonhome : d:\Anaconda3\envs\py36
Pythonpath : d:\Anaconda3\envs\py36\Lib

Tried to delete d:\Anaconda3\envs\py36 from Path, d:\Anaconda3\envs\py36 from Pythonhome, d:\Anaconda3\envs\py36\Lib from Pythonpath, still did not solve.

Would like to know what happened and how to solve, thank you.

**Comment by STREETKILLER007** [comment]
i installed Amaconda3 and look at the Path after i installed it.

It included :  

M:\Anaconda3;M:\Anaconda3\Library\mingw-w64\bin;M:\Anaconda3\Library\usr\bin;M:\Anaconda3\Library\bin;M:\Anaconda3\Scripts;

so if i put Amaconda in my D, the path should be, hope it solve my error.

D:\Anaconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\usr\bin;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;

**Comment by STREETKILLER007** [comment]
I removed Pythonhome, Pythonpath,  d:\Anaconda3\envs\py36 from Path.
It solved my problem.

**Comment by gautham949** [comment]
Removed python home? Can you explain me what exactly you did. I'm facing the same problem

**Comment by vivek-venk** [comment]
Thanks!! Had the same issue with PYTHONHOME and PYTHONPATH in the environment variables. Removing them helped opening up the Anaconda navigator. Seems like a conflict with the Python version if installed in the system prior to Anaconda installation as Anaconda installs python.

**Comment by pratap3001** [comment]
STREETKILLER007 thank you for your solution. It works.
