### ISSUE TITLE
cryptography package has un-needed dependency

### ISSUE THREAD

**Issue by dstansby** [ContinuumIO/anaconda-issues#9929]
Installing `cryptography` in a clean conda environment downloads the following packages:
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    idna-2.7                   |           py37_0          99 KB
    cryptography-2.3           |   py37hdbc3d79_0         543 KB
    cryptography-vectors-2.3   |           py37_0        30.5 MB
    asn1crypto-0.24.0          |           py37_0         155 KB
    cffi-1.11.5                |   py37h342bebf_0         205 KB
    six-1.11.0                 |           py37_1          21 KB
    pycparser-2.18             |           py37_1         168 KB
    ------------------------------------------------------------
                                           Total:        31.6 MB
```

Most of that is for `cryptography-vectors`, which is just a package with test data, and not needed for `cryptography` (it is not installed when `cryptography` is installed using pip). Would it be possible to remove this dependency?

(originally filed at https://github.com/pyca/cryptography/issues/4398)

**Comment by jjhelmus** [comment]
As of version 2.3.1 the `cryptography` package no longer requires `cryptography-vectors`.  Thanks for reporting this @dstansby

**Comment by JoshRosen** [comment]
Here's a cross-reference to the commit where this was fixed: https://github.com/AnacondaRecipes/cryptography-feedstock/commit/69bc72c703255d37a7408f995c7a282266c45b26
