### ISSUE TITLE
"import gensim" throws a fatal error

### ISSUE THREAD

**Issue by ksmnaidu** [ContinuumIO/anaconda-issues#9939]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```
I am using Anaconda 4.3.1 version distributed across our hadoop cluster. As a requirement, I have installed a list of packages across all our nodes. gensim is one of them which was installed successfully without any error. While trying to import gensim, I am getting the below error.
"Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so."

The weirder part is, if I import seaborn or tensorflow package before importing gensim, I am not getting this error and I am successfully importing gensim package. Not sure if there is a dependency of any kind and why gensim is not being imported on its own.

Any help would be appreciated.
""

**Comment by mingwandroid** [comment]
Closed due to not providing the requested information.
