### ISSUE TITLE
Cython built .pyd depends on library version

### ISSUE THREAD

**Issue by JoyMonteiro** [ContinuumIO/anaconda-issues#9947]
Hello,

I'm using miniconda on appveyor to automate building windows wheels for
my project 
https://github.com/CliMT/climt

I use  conda to install the msys/m2w64 compilers and use them to compile my
cython extension. The build and test goes well on appveyor:
https://ci.appveyor.com/project/JoyMonteiro/climt/build/0.9.1.387/job/uafadrrmgw17vy3k

However, if I try to pip install it on another windows machine (which has Anaconda 
installed, upgraded python to the same 3.6.6 version that appveyor uses), it refuses to load my
compiled code.

Running it through dependency walker shows that the dll points to certain libraries
whose version is not present in the Anaconda directory, reminiscent of the following
issue: https://github.com/ContinuumIO/anaconda-issues/issues/7883

Is there any way to build a wheel so that it can be reliably deployed on different
versions of Anaconda in windows?

**Comment by mingwandroid** [comment]
Which libraries? A python 3.6.6 module will not work on a different python if that's what you mean?

**Comment by mingwandroid** [comment]
And please fill in the issue template. It's there for good reasons.

**Comment by JoyMonteiro** [comment]
Thanks for the quick reply. I was filling up the template just now, and I might have found
an issue with my setup. Will check if I can fix it by myself.

Closing this for now, will open it again if it turns out that that wasn't the issue.
