### ISSUE TITLE
Mac OS X openssl seems to be broken (libcrypto-1.0.0.dylib)

### ISSUE THREAD

**Issue by mingwandroid** [ContinuumIO/anaconda-issues#995]
Hey @ilanschnell, here's the issue you asked me to open.

Reproduce with:
```
$ echo "int main() { return 0; }" | gcc -x c -Wl,-rpath,${CONDA_PREFIX}/lib -L${CONDA_PREFIX}/lib -lcrypto -o a.out -
$ ./a.out
```
gives =>
```
    dyld: Library not loaded: libcrypto.1.0.0.dylib
      Referenced from: /Users/rdonnelly/conda/conda-build/./a.out
      Reason: image not found
    Trace/BPT trap: 5
```

**Comment by ilanschnell** [comment]
I tried the example, and I get the same error, but then I look at `a.out`, I see:
```
$ otool -L a.out 
a.out:
	libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```
And setting `DYLD_LIBRARY_PATH=${CONDA_PREFIX}/lib` I can run `./a.out` run just fine.

**Comment by ilanschnell** [comment]
Using the following command, I can fix `a.out`:
```
$ install_name_tool -change libcrypto.1.0.0.dylib ${CONDA_PREFIX}/libcrypto.dylib a.out
```
So I don't think there is a problem with `libcrypto.1.0.0.dylib` itself.

**Comment by mingwandroid** [comment]
You shouldn't need to set `DYLD_LIBRARY_PATH` and in-fact you cannot set that on El Capitan due to SIP.

If you try the OpenSSL 1.0.2h build #2 that I uploaded to https://www.anaconda.org/rdonnelly then my test works just fine. I'm fairly sure that the string replacement code has broken that dylib.

**Comment by ilanschnell** [comment]
When I fix the binary using `install_name_tool`, then I don't need `DYLD_LIBRARY_PATH` to be set in order for `a.out` to work.

**Comment by mingwandroid** [comment]
I think both your options are ways to work around the problem rather than fixes for the problem. You shouldn't need to set `DYLD_LIBRARY_PATH` and in-fact you cannot set that on El Capitan due to SIP.

If you try my OpenSSL 1.0.2h build #2 from: https://anaconda.org/rdonnelly/openssl/1.0.2h/download/osx-64/openssl-1.0.2h-2.tar.bz2 then the test works fine.

At present, with the openssl package on defaults as it is, I cannot build posgresql and that's holding up psycopg2, whereas with one built more traditionally, I can build postgresql (it is also on my channel).

> When I fix the binary using install_name_tool, then I don't need DYLD_LIBRARY_PATH to be set in order for a.out to work.

I guess we are in agreement that the binary is broken. Apart from this linking problem, I wonder what other issues may be present?

**Comment by ilanschnell** [comment]
I don't think the binary is broken at all.  You always have to either use `install_name_tool` or set `DYLD_LIBRARY_PATH`.  How would `a.out` otherwise know where `libcrypto` is?

**Comment by msarahan** [comment]
So it is a normal assumption that people run install_name_tool at the start of their build scripts?  Or set DYLD_LIBRARY_PATH?  I haven't seen that.  Isn't install_name_tool usually run by conda-build, setting @rpath or something like that?

**Comment by mingwandroid** [comment]
When we made a.out we told `dyld` where to look using `-Wl,-rpath,${CONDA_PREFIX}/lib`, and so `a.out` has the correct `LD_RPATH` entry. Adding full paths to dylibs isn't how we do it, we keep them relative and use the rpath mechanism to provide a series of prefixes to `dyld`.

`otool -L` isn't really much good for investigating OS X dyld matters, I recommend `otool -l` instead as it gives a lot more details.

If you want, I can keep digging into this, but I'm pretty sure that they dylib is broken.

**Comment by mingwandroid** [comment]
To use install_name_tool at the start of each build, we couldn't use hardlinks of course either.

**Comment by mingwandroid** [comment]
So we're on the same page, if you do `conda install -c rdonnelly openssl`

Then the following fails:

`echo "int main() { return 0; }" | gcc -x c -Wl,-rpath,${CONDA_PREFIX}/pkgs/openssl-1.0.2h-1/lib -L${CONDA_PREFIX}/pkgs/openssl-1.0.2h-1/lib -lcrypto -o a.out -`

.. while the following succeeds:

`echo "int main() { return 0; }" | gcc -x c -Wl,-rpath,${CONDA_PREFIX}/pkgs/openssl-1.0.2h-2/lib -L${CONDA_PREFIX}/pkgs/openssl-1.0.2h-2/lib -lcrypto -o a.out -`

**Comment by mingwandroid** [comment]
I think I've made some progress.

The difference between the two executables is:

mine.out:

```
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libcrypto.1.0.0.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
```

old.out:


```
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libcrypto.1.0.0.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
```

This will fix the executable `old.out`: 
install_name_tool -change libcrypto.1.0.0.dylib @rpath/libcrypto.1.0.0.dylib ilan.out

.. but we need to fix the dylib instead. I'm looking at that now, I don't think it'll be too difficult.

**Comment by mingwandroid** [comment]
From defaults:

```
otool -l ${CONDA_PREFIX}/pkgs/openssl-1.0.2h-1/lib/libcrypto.1.0.0.dylib  | grep LC_ID_DYLIB -A5
          cmd LC_ID_DYLIB
      cmdsize 48
         name libcrypto.1.0.0.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 1.0.0
compatibility version 1.0.0
```

From my channel:

```
otool -l ${CONDA_PREFIX}/pkgs/openssl-1.0.2h-1/lib/libcrypto.1.0.0.dylib  | grep LC_ID_DYLIB -A5
          cmd LC_ID_DYLIB
      cmdsize 56
         name @rpath/libcrypto.1.0.0.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 1.0.0
compatibility version 1.0.0
```

For some reason the `id` name is wrong. It can be corrected via:

`install_name_tool -id @rpath/libcrypto.1.0.0.dylib ${CONDA_PREFIX}/pkgs/openssl-1.0.2h-1/lib/libcrypto.1.0.0.dylib`

**Comment by ilanschnell** [comment]
Ok, `openssl 1.0.2h 2` is available now, which uses `@rpath`.

**Comment by mingwandroid** [comment]
Great. Thanks @ilanschnell.

Did you need to add something general to the build system for this or is it a one-off issue with openssl?

**Comment by ilanschnell** [comment]
This is what I did (generally):
https://github.com/ContinuumIO/anaconda/commit/548ed5cbd6d1f981ce59604203e21db58da8a707

**Comment by ilanschnell** [comment]
I just tried out the original command (`gcc -x c -Wl,-rpath,${CONDA_PREFIX}/lib ...`) and that works fine with the new `openssl-1.0.2h-2` package.

**Comment by mingwandroid** [comment]
Yup, all seems well in the world of OS X OpenSSL now. Thanks for helping out.
